### ISSUE TITLE
How do we know what Port is being used for in/out using PIA VPN

### ISSUE THREAD

**Issue by euronck** [haugene/docker-transmission-openvpn#100]
I know this is a stupid question. But do I go about finding what port is being used by transmission over PIA VPN. Do I need to open that port on my router. Currently I just have the port 9091 open?

**Comment by haugene** [comment]
If you're using pia it should automatically contact pia to get an open port and set this port in your transmission client. As all the traffic is tunneled through vpn, opening ports in your router is not necessary. 

But it should work out of the box. Check the network settings in transmission web ui, it should say which port is used and that it is open. 

If not, please attach container logs (docker logs <container name/id>).

**Comment by haugene** [comment]
Closing this soon if you don't have any follow up questions?

**Comment by euronck** [comment]
haugene thank you for answering the question. 
I actually do have anther question about your awesome container. 
If I punched a hole in the firewall so i can access the page from the internet. If I want to have a username and password on the page to protect it from unauthorized users how can i do that?

for example when i go to http://mydns:9090 it displays a page saying username and password before showing the transmission torrent page.
