### ISSUE TITLE
Route other containers' web traffic through transmission-openvpn (Synology)

### ISSUE THREAD

**Issue by Edulcorate** [haugene/docker-transmission-openvpn#1006]
I am running Docker on Synology DSM 6.2 and hoping someone can help out with a guide / explanation... I would like to direct the web traffic from other containers (namely Jackett, Sonarr and Radarr) through haugene-transmission-openvpn container ie. so that Jackett, Sonarr, Radarr etc. are running through the same VPN I have configured for Transmission.

I've read various posts online which lead me to believe that this is possible, but I can't quite fit all the pieces together to make it work. 

Failing that, a guide on how to setup Jackett to use the transmission-openvpn container's proxy server would also be great. 

I have zero coding knowledge, so as much of a step-by-step as possible would be greatly appreciated. 

I have added environment variables to my current docker containers using the Synology DSM gui... not sure how to go about editing docker containers any other way on Synology.

Many thanks!

**Comment by Edulcorate** [comment]
This looks like it'll do the trick: https://github.com/haugene/docker-transmission-openvpn/issues/991

I've searched and searched online but I just can't work out how to edit the dockerfile (or do I need to be editing something else - dockercompose?) on my Synology NAS... I know it needs to be done via SSH but that's about as far as I get.

**Comment by Edulcorate** [comment]
One other thing I've tried that doesn't seem to work for me is adding to the Environement Variables of the Jackett container in the Synology GUI: --net=container:haugene-transmission-openvpn1 ("haugene-transmission-openvpn1" is the name of the transmission container as it appears in the GUI).

Jackett seems to ignore this and does not run through a VPN (because trying to add indexers that are blockedby my ISP still show an error). From https://github.com/haugene/docker-transmission-openvpn/issues/991 it seems like I need to open port 9117 to the transmission container, but I don't know how to do that. 

I've confirmed that transmission-vpn container is running correctly (ie. the VPN is enabled and working).

**Comment by nayneyT** [comment]
Hi, I do exactly this so it does work.

I use a macvlan setup so mine does not require the additional port configuration but prior to running a macvlan config I was running it the default-bridge method that docker uses by default.

So you've configured haugene's docker image to a container. In this container you must be stipulating ports to map using the -p option in the docket run or alternatively in the ports: section of a docker-compose.yml file.

You wish to connect a second container e.g. Jackett, Lidarr, Sonarr etc to Haugene's transmission container.

You must however also make changes to Haugen's container to allow the lidarr, Hackett ports to pass through.

What you end up with is Haugene's container with all the port maps for Hackett, lidarr, sonarr etc and the the lidarr container has no port maps but is just connect to the Haugen's container.

If this doesn't make sense I can provide examples.

**Comment by Edulcorate** [comment]
Thank you very much for the info. 

I have managed to map the ports as you described in the Synology GUI (and removed the port maps from sonarr, radarr etc) and added --net=container:haugene to the environment variables of Sonarr, Radarr etc. and can spin up the containers without any errors. 

However, I now cannot access the Web UI for Sonarr, Radarr etc. 

I found [this post](https://www.reddit.com/r/synology/comments/7rq245/routing_specific_docker_container_through_vpn/) which says "any web UIs provided by the containers will not be accessible without a reverse proxy."

I know how to add a reverse proxy using Application Portal in the Synology GUI, but I can't figure out how to add a reverse proxy to now make Sonarr, Radarr etc accessible again via the Web UI. 

Any further help greatly appreciated.

**Comment by nayneyT** [comment]
HI Edulcorate,

I've been away for a while so please accept my apologise. I know how annoying it is when you are awaiting a response.

Let's assume you Synology is using a 'normal' IP range e.g. 192.168.0.10 etc and you're not gone crazy and started using large IP subnets.

You have configured Haugene's transmission container with the ports for you're other containers that will attach to it.

In the other container's you've attached to them using the --net=container:haugene (assuming you have named the container haugene) this should attach them to your container.

So far so good.

You should now be able to get to the sonarr WebGUI using the Haugene IP plus the port number of sonarr e.g. http://192.168.0.10:8989

If this doesn't open the GUI then I think it may be something silly that's still missing. Did you add the local network environment variable?

      - LOCAL_NETWORK=192.168.0.0/24 # Optional - Sets the local network that should have access. Accepts comma separated list.

In the docker run command you will need to use the environment option and will need to amend your docker run command to add:

 `--env LOCAL_NETWORK=192.168.0.0/24`

**Comment by mlavio829** [comment]
is there by any chance a step by step guide on how to do this? 
I'm new to using docker and this is a bit confusing in terms of how to do this.
I have the container running but I can't seem to figure out ho to get Sonarr or radarr through the open vpn container

**Comment by Dalarialus** [comment]
Is there much benefit to doing like this rather than using the haugene/docker-transmission-openvpn-proxy container and configuring that as a proxy in sonarr/radarr/etc?

**Comment by mlavio829** [comment]
How does one do that?

**Comment by Fr0ntier3** [comment]
I have the transmission-openvpn docker working properly, but now I want my sonarr and jackett dockers to run through it as well.  Whatever I have tried I can't access sonarr or jackett once they are all on.  here were a few different suggestions throughout this post and i've tried them each individually and all at once just in case.  Can someone help me with the variables... this is a capture from my Jackett docker.  (for reference Docker-Transmission_OpenVPN is the name of that docker.

![image](https://user-images.githubusercontent.com/63888055/79624739-9fc4fd80-80d8-11ea-9070-9704baed1d59.png)

**Comment by drummermattuk** [comment]
Hey, Did you manage to sort this in the end, Im trying to do the exact same thing but I can't access the web ui when its running

**Comment by Fr0ntier3** [comment]
I never managed to get it working, I had to go back to my old method of
running them in their own dockers and configuring my firewall to sort the
IPs through VPNs.

**Comment by drummermattuk** [comment]
Ah okay, I might try to do the same as I have no idea what I'm doing, tried every combination and it just doesn't load

**Comment by pkishino** [comment]
working solution is posted above,closing
