### ISSUE TITLE
Would it be possible to tag a new release?

### ISSUE THREAD

**Issue by Cellane** [haugene/docker-transmission-openvpn#1007]
**Is your feature request related to a problem? Please describe.**
First of all, thank you so much for the amazing Docker image! It works like a charm for me!

That being said, whenever possible, I like to use a specific version tag for running my containers rather than `latest`. When looking at the images available on Docker Hub, I noticed that while the `latest` image (which I’m using for now) was released 3 months ago, the last version tag (`2.7`) was released over 10 months ago.

Furthermore, the release notes here on GitHub mention that there are some known issues in the 2.7 release which are solved in the `latest` tag.

**Describe the solution you'd like**
If it wouldn’t be too much problem, please release another stable version of this image under a version tag, and publish it to Docker Hub.

Thank you!

**Comment by haugene** [comment]
Hey @Cellane. Had been thinking of this one for a while. Just postponed setting up a CI build for too long. Now I have and the tagged versions are more frequent and will stay that way going forward 😄

**Comment by Cellane** [comment]
Thank you so much! 🙇‍♂️
