### ISSUE TITLE
No Upload - Ports are open

### ISSUE THREAD

**Issue by ZMOT7S** [haugene/docker-transmission-openvpn#1008]
**Describe the problem**
No torrents are uploading, even with opened ports. They download fine. 

I manually changed the port in transmission settings, allowed the port in and out with UFW, made sure the port was open with Mullvad and on my router. 

**Add your docker run command**
docker run --cap-add=NET_ADMIN -d --sysctl net.ipv6.conf.all.disable_ipv6=0 \
              -v /media/Media:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=MULLVAD \
              -e OPENVPN_CONFIG=mullvad_us-ny_udp \
              -e OPENVPN_USERNAME=MyAccountName \
              -e OPENVPN_PASSWORD=MyPassword \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.0.0/16 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn

**Logs**
Unfortunately when I run the logs command, it's just this over and over...

"Thu Jan 16 21:24:56 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #2334282 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
"

I tried appending --mute-replay-warnings but it gave me "unknown flag"

**Host system:**
Ubuntu 18.04 LTS

Which version of Docker are you using? -->
Docker CE 19.03.5

**Comment by pkishino** [comment]
the  warnings can be muted setting docker env : OPENVPN_OPTS --mute-replay-warnings
shouldnt have to do anything on router as tunnels to your vpn..
which port are you trying to open?
The peer port?

**Comment by ZMOT7S** [comment]
Yes, the peer port, which I changed to 11249. I didn't think about it until now but do I need to add it to docker with -p 11249:11249? I've only been using linux for about a week no so I'm pretty new to all of this.

**Comment by pkishino** [comment]
No, no need to. Have you checked in transmission that the port is open?

**Comment by ZMOT7S** [comment]
It seems to be working after a reboot. Maybe it was an issue with port binding.

**Comment by zeoninja** [comment]
I have no uploads either, but the peer port states it open?
