### ISSUE TITLE
ExpressVPN Support

### ISSUE THREAD

**Issue by sethtmoore** [haugene/docker-transmission-openvpn#1011]
What all would be needed to add support for ExpressVPN?

**Comment by Sammus187** [comment]
See last heading under https://haugene.github.io/docker-transmission-openvpn/supported-providers/ - ExpressVPN uses customer certificates per user which contain credentials, so it's not really practical or maybe even possible to add it in a meaningful way. The instructions there work fine - I use ExpressVPN with no issue.
