### ISSUE TITLE
Docker/Transmission stops running

### ISSUE THREAD

**Issue by mpit52** [haugene/docker-transmission-openvpn#1014]
**Describe the problem**
Hello all,
I am new to dockers, transmission and just about all of this so please bear with me. I am running 'container station' on a QNAP 253Be with the latest firmware and updates. When I execute the commands below to create a docker for transmission, the docker creates but only runs for about 30 seconds before stopping. Below is the command I used to generate said docker. I tried swapping out the VPN config files with other known port forwarding servers but I do not believe that to be the issue. I would assume the docker to continue to run even though the VPN failed to connect or error out. Any and all help would be appreciated.

**Add your docker run command**
`docker run --cap-add=NET_ADMIN -d \
          --name=transmission \
          -v /share/CACHEDEV1_DATA/Container/Download:/data \
          -v /etc/localtime:/etc/localtime:ro \
          -e CREATE_TUN_DEVICE=true \
          -e OPENVPN_PROVIDER=PIA \
          -e OPENVPN_CONFIG="Czech Republic" \
          -e OPENVPN_USERNAME=username \
          -e OPENVPN_PASSWORD=password \
          -e WEBPROXY_ENABLED=false \
          -e LOCAL_NETWORK=192.168.7.0/24 \
          --log-driver json-file \
          --log-opt max-size=10m \
          -p 9091:9091 \
          haugene/transmission-openvpn`
**Logs**
[docker-logs-transmission_1.18.20.txt](https://github.com/haugene/docker-transmission-openvpn/files/4082280/docker-logs-transmission_1.18.20.txt)

**Host system:**
QNAP: TS-253Be, 4.4.1.1146
Container Station: 2.0.957

[~] # docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   0bbe3ac
 Built:        Wed Nov 27 03:52:27 2019
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   0bbe3ac
 Built:        Wed Nov 27 03:52:27 2019
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by mpit52** [comment]
Quick question about the "LOCAL_NETWORK" argument. Are you referring to the local network of my house/environment or the local network that the docker runs on? While my home network is a 192.168.7.0/24 network, when I view settings/preferences in "Container Station" it appear that the container network is 10.0.3.0/24. While I tried using both in the script, I get the same result of the container stopping within a few seconds.

**Comment by nayneyT** [comment]
do the following command:

docker logs transmission

what do the logs say?

I imagines it's either a permissions issue or unable to find ovpn file.

**Comment by mpit52** [comment]
That command was ran and attached with my original post "docker-logs-transmission_1.18.20.txt". I will run this again when I get home latter today but I don't expect it to show anything different. The docker shows a local IP,l and seems to connect or at least get a response back from the VPN but stops shortly after. Sometime the docker runs for 5-10 seconds others it runs closer to 60-90 seconds.

**Comment by dhitchcock** [comment]
Might just be a PIA outage, I came here because my container kept stopping too, saw this bug and exclaimed AH-HA!  But, I discovered when I tried to connect to the server I use with the official PIA client it was timing out.  Half hour later, the server was back online and transmission back in business.

**Comment by mpit52** [comment]
Hm, that's the thing, the windows client I have connects without an issue while going to the same server.  I can try changing the server again but I feel that it might be something else. 
I've been deleting and redeploying the container each time to which I can only assume there is an easier way.
