### ISSUE TITLE
Permission rights Raspberry Pi - NAS

### ISSUE THREAD

**Issue by mrwolf78** [haugene/docker-transmission-openvpn#1017]
I have succesfully set up Transmission on my Raspberry Pi, and it downloads to a mounted nfs share on my Synology NAS. I also have the following settings in my .yml-file:

```
  environment:

    - OPENVPN_PROVIDER=WINDSCRIBE
    - OPENVPN_USERNAME=XXX
    - OPENVPN_PASSWORD=XXX
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.0.0/24
    - TRANSMISSION_RATIO_LIMIT=0
    - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    - PUID=1000
    - GUID=1000
```
I also have sonarr running on my NAS, but I get constant errors when it tries to import a download:

> Couldn't import episode /volume1/downloads/torrents/completed/xxx.mkv: Access to the path is denied.

A manual chmod fixes it, but I'm sure I'm missing something here, can anyone help me out?

**Comment by Cellane** [comment]
Have you tried running the container with the `TRANSMISSION_UMASK=0` enviromental variable? It fixed a similar problem for me.

**Comment by mrwolf78** [comment]
Yes! That did the trick, thanks!
