### ISSUE TITLE
VPN affecting other running containers

### ISSUE THREAD

**Issue by 5tanly** [haugene/docker-transmission-openvpn#1028]
**Describe the problem**

The container is affecting other containers internet connection, seems to put all containers running alongside it also inside of the VPN. I can confirm this because I have a minecraft server container whos port is only opened when the transmission container is stopped.

We need a way to whitelist ports so they dont get behind the VPN. Similar to how NordVPN has their linux program. `> nordvpn whitelist add port 25565 tcp`

**Add your docker run command**

Not sure since I am running it in the Docker GUI plugin in OMV
Maybe its `dumb-init /etc/openvpn/start.sh`

**Host system:**

OpenMediaVault 4.1.32-1
Docker 19.03.5
Running on a custom built server with consumer parts

**Comment by 5tanly** [comment]
I put the container in bridge mode and my Minecraft server got opened again, but now the webgui isn't loading. The gui loads fine but the torrents don't load up

This is how I have my networking set up
<img width="346" alt="image" src="https://user-images.githubusercontent.com/31938727/73184562-a7cd5c80-40ea-11ea-980d-583989aa9718.png">

**Comment by pkishino** [comment]
This sounds more like a configuration error where your docker containers are sharing  the same network instead of separate ones. Because this is not default behavior. I would look into how omv sets up the container

**Comment by 5tanly** [comment]
> This sounds more like a configuration error where your docker containers are sharing the same network instead of separate ones. Because this is not default behavior. I would look into how omv sets up the container

Sorry, after doing some more research I found that that I was setting it up wrong. The containers were sharing the same network.
After fixing that everything works fine, the transmission container has its VPN and my other containers can connect to the internet and be port forwarded without issue.
