### ISSUE TITLE
ivacy - add czech server

### ISSUE THREAD

**Issue by kalikadze** [haugene/docker-transmission-openvpn#1030]
**Is your feature request related to a problem? Please describe.**
Its not a problem, just request for update: Hello, I would like to ask you if is possible to add Czech VPN server for Ivacy?

**Describe the solution you'd like**
https://support.ivacy.com/vpn-servers/
can you add this server? :
Czech Republic | cz2-ovpn-udp.dns2use.com | cz2-ovpn-tcp.dns2use.com

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by pkishino** [comment]
Please create a PR with the new server added
