### ISSUE TITLE
Question RE: systemd integration for reverse proxy

### ISSUE THREAD

**Issue by dom2114** [haugene/docker-transmission-openvpn#1032]
Everything is setup and working perfectly, and Ive gotten the container to automatically launch when my system boots via the 'systemd documentation'.
However, I am trying to apply the exact same logic (i.e. auto run the container at boot) for transmission-openvpn-proxy.  I use this so I can access transmission remotely:

$ docker run -d \
      --link <transmission-container>:transmission \
      -p 8080:8080 \
      haugene/transmission-openvpn-proxy

Can someone please help me understand how to have this code automatically at boot?
Thank you!

**Comment by lhanson** [comment]
Docker has its own method of ensuring containers run on startup. See (https://docs.docker.com/config/containers/start-containers-automatically/); particularly, you probably want to add `--restart always` to your run command. With this flag added, as long as the docker daemon starts on boot it will handle the rest.

**Comment by dom2114** [comment]
thanks.  yes i found this page, but when i run the following command, the container does not survive a reboot:
docker run -d \
	--restart always \
      --link transmission-openvpn:transmission \
      -p 8080:8080 \
	haugene/transmission-openvpn-proxy 


I need help translating the above query into the following structure (which came from the 'systemd integration documentation'):

[Unit]
Description=haugene/transmission-openvpn docker container
After=docker.service
Requires=docker.service

[Service]
User=bittorrent
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill transmission-openvpn
ExecStartPre=-/usr/bin/docker rm transmission-openvpn
ExecStartPre=/usr/bin/docker pull haugene/transmission-openvpn
ExecStart=/usr/bin/docker run \
        --name transmission-openvpn \
        --cap-add=NET_ADMIN \
        --device=/dev/net/tun \
        -v /home/bittorrent/data/:/data \
        -e "OPENVPN_PROVIDER=TORGUARD" \
        -e "OPENVPN_USERNAME=bittorrent@example.com" \
        -e "OPENVPN_PASSWORD=hunter2" \
        -e "OPENVPN_CONFIG=CA\ Toronto" \
        -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
        -e "TRANSMISSION_UMASK=0" \
        -p 9091:9091 \
        --dns 8.8.8.8 \
        --dns 8.8.4.4 \
        haugene/transmission-openvpn
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

**Comment by dom2114** [comment]
Came across this, but still can't get it working.
https://dev.to/suntong/autostart-docker-container-with-systemd-5aod

Here's where I'm at so far:
[Unit]
Description=Proxy
Requires=docker.service
After=docker.service

[Service]
User=dom
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill transmission-openvpn-proxy
ExecStartPre=-/usr/bin/docker rm transmission-openvpn-proxy
ExecStartPre=/usr/bin/docker pull haugene/transmission-openvpn-proxy
ExecStart=/usr/bin/docker run \
	--name 	ransmission-openvpn-proxy \
	-p 8080:8080 \
	haugene/transmission-openvpn-proxy
Restart=always	

[Install]
WantedBy=multi-user.target


I'll be the first to admit I'm basically guessing.  Appreciate any help anyone can offer.

**Comment by lhanson** [comment]
Sorry, I haven't set things up with systemd like this so I can't offer any additional suggestions. Hopefully somebody else can jump in.
