### ISSUE TITLE
Is there a way to filter downloads into separate folders?

### ISSUE THREAD

**Issue by Jtiem** [haugene/docker-transmission-openvpn#1033]
Love the work you have done, first off.

Currently, when I torrent different file types I am having to manually set a new download destination after the torrent file is uploaded to the watch folder.

It would be great if I could have multiple watch folders that have corresponding download destinations.

**Comment by pkishino** [comment]
How are you adding torrents? Sounds like it might be easier to modify input source as it’s easy to specify download location of downloads

**Comment by haugene** [comment]
Glad you like the project @Jtiem. I see that such a feature would come in handy, but it's not something that will be added on to this project any time soon. I'm struggelig to find the time to keep it up to date as it is, and we have so far not done any "Transmission patching" as this would be.
The "watch" directory is not a feature from this project, but of Transmission itself, and I think that this feature request is better posted on their project.

That being said. I seem to remember that download managers like sickchill, couchpotato, sonarr, radarr and maybe others have functionality to specify where the downloads should be stored. So you might use one of them. If not you could always try to script it yourself using [transmission-remote](https://linux.die.net/man/1/transmission-remote).

I wish you the best of luck on this and I can answer any follow-up questions if you'd like, but I'll close this issue for now. If you come up with a script that handles this, let me know. Maybe we can add it to the image 😄
