### ISSUE TITLE
Transmission-openvpn in Portainer

### ISSUE THREAD

**Issue by pierozek89** [haugene/docker-transmission-openvpn#1036]
Hi!

I'm having a problem with setting up transmission-openvpn in Portainer (running on linux armv7l HassOS 3.7, on rp4). I've pull image haugene/transmission-openvpn:latest-armhf , I've added the VPN provider (PUREVPN) and credentials . I'm able to start the container, but nothings happens, please see the logs below:

Using OpenVPN provider: PUREVPN,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
Sat Feb  1 15:09:44 2020 WARNING: file '/etc/openvpn/purevpn/Wdc.key' is group or others accessible,
Sat Feb  1 15:09:44 2020 OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Oct 14 2018,
Sat Feb  1 15:09:44 2020 library versions: OpenSSL 1.0.2s  28 May 2019, LZO 2.08,
Sat Feb  1 15:09:44 2020 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.,
Sat Feb  1 15:09:44 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Sat Feb  1 15:09:44 2020 RESOLVE: Cannot resolve host address: vleu-no2-ovpn-udp.pointtoserver.com:53 (Name or service not known),
Sat Feb  1 15:09:44 2020 RESOLVE: Cannot resolve host address: vleu-no2-ovpn-udp.pointtoserver.com:53 (Name or service not known),
Sat Feb  1 15:09:44 2020 Could not determine IPv4/IPv6 protocol,
Sat Feb  1 15:09:44 2020 SIGUSR1[soft,init_instance] received, process restarting,

**Comment by haugene** [comment]
Closing this and following up PureVPN config update in #1012 
New recommended configs have been downloaded from [here](https://support.purevpn.com/openvpn-files).
