### ISSUE TITLE
Timezone Issue

### ISSUE THREAD

**Issue by felixsum** [haugene/docker-transmission-openvpn#104]
I rely on the scheduling feature of transmission, but I noticed that it wasn't starting and stopping at the times I wanted. I discovered that the docker container is on UTC while I'm on EST. Is there a environment variable for changing the timezone and if not could you add one? For the mean time, I'll create a cron job.

**Comment by mattberther** [comment]
@felixsum the easiest solution is likely to add `-v /etc/localtime:/etc/localtime:ro` to your `docker run` command. This will have the docker container use the localtime of the host.

Alternatively you could create your own image, deriving from this one, adding the following:

```
FROM haugene/transmission-openvpn

RUN apt-get update \
    && apt-get install -y tzdata \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV TZ America/Mountain
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

**Comment by felixsum** [comment]
Thank you! That's very helpful. The solution I found is to have the normal speed limit be 0 up and down and then the turtle mode is 9999 up and down. So whenever turtle mode is enabled, torrents are running.

**Comment by haugene** [comment]
I run all my containers with the /etc/localtime mount, should probably add it to the example run command in the README. Thats's usually the behavior you expect from the container anyways.

**Comment by haugene** [comment]
@felixsum, did the solution @mattberther proposed solve your problem? If so, we can probably close this issue :)

**Comment by superkrups20056** [comment]
> @mattberther Thank you! That's very helpful. The solution I found is to have the normal speed limit be 0 up and down and then the turtle mode is 9999 up and down. So whenever turtle mode is enabled, torrents are running. I was able to offset the hours to my timezone using this method.

@wideltann why didn't you just set the turtle mode to be 0 up and down and specify the times that it should be in turtle mode with the environmental variables TRANSMISSION_ALT_SPEED_TIME_ENABLED=true, TRANSMISSION_ALT_SPEED_TIME_BEGIN=nnn, and TRANSMISSION_ALT_SPEED_TIME_END=nnn (where nnn is the minutes after midnight)? I thought that is how the ALT SPEED function was meant to be used?

**Comment by wideltann** [comment]
`ExecStart=/usr/bin/docker run -v /etc/localtime:/etc/localtime:ro \
        --privileged \
        -v /media/data:/data \
	--sysctl net.ipv6.conf.all.disable_ipv6=0 \
        -e "OPENVPN_PROVIDER=MULLVAD" \
        -e "OPENVPN_USERNAME=" \
        -e "OPENVPN_PASSWORD=m" \
	-e "TRANSMISSION_DOWNLOAD_DIR=/data/completed" \
	-e "TRANSMISSION_INCOMPLETE_DIR=/data/incomplete" \
	-e "TRANSMISSION_INCOMPLETE_DIR_ENABLED=true" \
        -e "TRANSMISSION_UMASK=007" \
        -e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true" \
        -e "TRANSMISSION_RPC_USERNAME=" \
        -e "TRANSMISSION_RPC_WHITELIST=*.*.*.*" \
        -e "TRANSMISSION_RPC_PASSWORD=" \
	-e "TRANSMISSION_SPEED_LIMIT_DOWN=0" \
	-e "TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true" \
	-e "TRANSMISSION_SPEED_LIMIT_UP=0" \
	-e "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true" \
        -e "TRANSMISSION_ALT_SPEED_TIME_ENABLED=true" \
        -e "TRANSMISSION_ALT_SPEED_DOWN=9999" \
        -e "TRANSMISSION_ALT_SPEED_UP=9999" \
        -e "TRANSMISSION_ALT_SPEED_TIME_BEGIN=180" \
        -e "TRANSMISSION_ALT_SPEED_TIME_END=540" \
        -e "TRANSMISSION_RATIO_LIMIT=2.0" \
        -e "TRANSMISSION_RATIO_LIMIT_ENABLED=true" \
        -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
	-e "PUID=1000" \
	-e "PGID=1002" \
        -p 9091:9091 \
        --dns 8.8.8.8 \
        --dns 8.8.4.4 \
        haugene/transmission-openvpn
`
@superkrups20056 well haha that's exactly what I did. I didn't do a great job explaining my implementation in the comment so here's what the ExecStart looked like in my systemd service file.
