### ISSUE TITLE
docker tranmission open vpn prevents me from accessing NAS

### ISSUE THREAD

**Issue by daragaram** [haugene/docker-transmission-openvpn#1044]
Hi, many thanks for reading.

I just finally solved many issues to run the transmission, however,
when i began to run it, it prevented me from accessing the actual NAS server (:5000) and other ports.
How can I solve this issue? could you help me? :(

**Comment by mehulboricha** [comment]
Docker does not interfere with the host system. Are you trying to access NAS from the container itself or from the host system?

**Comment by haugene** [comment]
If this happens then you're running it with `network=host`. See https://docs.docker.com/engine/reference/run/#network-settings

You should run it in bridge mode and use LOCAL_NETWORK environment variable to allow access from your local LAN. If you need access from outside your LAN then a proxy container is the way to go. This is described in the documentation: https://haugene.github.io/docker-transmission-openvpn/access/
