### ISSUE TITLE
Shutting down

### ISSUE THREAD

**Issue by willigiann** [haugene/docker-transmission-openvpn#1047]
**Describe the problem**
I am running a Synology DSM 6.2 and I am trying to run your docker image using NordVPN. I followed your instructions from your https://haugene.github.io/docker-transmission-openvpn/synology-nas/ site. The image starts and stops. I don't know much about docker to know where I can see why it shut down.

Thank you very much

**Add your docker run command**
docker run \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    -d \
    -v /volume2/docker/transmission-openvpn/config/resolv.conf:/etc/resolv.conf \
    -v /volume1/Media/:/data \
    -e "OPENVPN_PROVIDER=NORDVPN" \
    -e "OPENVPN_USERNAME=xxxxxxxxxxxxxxxxxx" \
    -e "OPENVPN_PASSWORD=xxxxxxxxxxxxxxxxxx" \
    -e "LOCAL_NETWORK=xxx.xxx.xxx.0/24" \
    -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
    -e "PGID=100" \
    -e "PUID=1024" \
    -p 9091:9091 \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --name "transmission-openvpn-syno" \
    haugene/transmission-openvpn:latest

**Logs**

**Host system:**
Synology DS1819+

**Comment by joeflan** [comment]
I'm running into a similar issue on my Synology DS620. My configuration is close to the one you posted and I keep seeing this in my logs 

*Log*
AUTH: Received control message: AUTH_FAILED
SIGTERM[soft,auth-failure] received, process exiting

I know for a fact my credentials are correct but I keep getting this restarting issue

**Comment by acosmichippo** [comment]
same problem here with PIA.

**Comment by acosmichippo** [comment]
also tried generating PPTP/L2TP/SOCKS password, but no luck.

https://www.privateinternetaccess.com/pages/client-support/generate-password

**Comment by acosmichippo** [comment]
FWIW I was able to get the docker working on my unraid server, so I know my credentials are good.  might be some kind of issue with the synology setup.

**Comment by ilike2burnthing** [comment]
Any special characters in your password or email, e.g. `+`? - https://github.com/haugene/docker-transmission-openvpn/issues/1092

**Comment by pkishino** [comment]
closing for now, waiting for updates
