### ISSUE TITLE
Listening Port

### ISSUE THREAD

**Issue by mouzzampk2014** [haugene/docker-transmission-openvpn#1048]
Hi, need little help. How can I change listening port from 51413 to 44234. Do I need to change in settings.json or somewhere else. I am running via docker-compose. I tried to change it in settings.json but after restart port changed back to 51413.
![1](https://user-images.githubusercontent.com/44548525/74613066-02167780-5103-11ea-9890-91b56f62178f.jpg)

Thanks

**Comment by pkishino** [comment]
yes, it is one of the transmission settings.
TRANSMISSION_PEER_PORT
set this to 44234

**Comment by mouzzampk2014** [comment]
Yes I changed that in settings.json but after restart port reverted back to 51413 or shall I do add that in .env TRANSMISSION_PEER_PORT?

**Comment by pkishino** [comment]
Yes, you need to set the docker env variable so that it sticks after restart

**Comment by pkishino** [comment]
Please close the topic when done

**Comment by mouzzampk2014** [comment]
Hi, thank you so much. It's working perfectly fine. Adding environment variable fixed the issue.
