### ISSUE TITLE
FastestVPN Update - Current Configs Not Connecting

### ISSUE THREAD

**Issue by QuiGonLeong** [haugene/docker-transmission-openvpn#1049]
**Which provider?**
FastestVPN 

**Where are the configs?**
https://support.fastestvpn.com/download/openvpn-tcp-udp-config-files/

**Comment by pankompot** [comment]
FYI - I think only some of the config files changed so you can try and figure out which one works until all files are updated. For me it works e.g. when I set config to Austria-UDP

**Comment by haugene** [comment]
FastestVPN provider has now been updated through #1016. It is on the latest tag as well as release 2.11
Please pull the new version and see if there is still a problem. Closing the issue for now, feel free to re-open if the problem persists.
