### ISSUE TITLE
Support basic auth for proxy UI

### ISSUE THREAD

**Issue by subdavis** [haugene/docker-transmission-openvpn#1050]
**Is your feature request related to a problem? Please describe.**

I'd like a better guarantee that nobody else is using my setup. 

**Describe the solution you'd like**

Optional basic auth support for the proxy interface

**Describe alternatives you've considered**

Security through obscurity: I just don't tell people IP address and port.

**Comment by lhilton** [comment]
```
  -e TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
  -e TRANSMISSION_RPC_PASSWORD=YourAwesomeSecurePassword
  -e TRANSMISSION_RPC_USERNAME=ACoolUsernmae
```

Add these env variables to get auth. Your clients using RPC will also need to be updated with whatever values you use for the username and password.

**Comment by subdavis** [comment]
Mm.  I thought I checked the dockerfile before I posted this, but I guess not.  Thanks!
