### ISSUE TITLE
Script not running on torrent finish

### ISSUE THREAD

**Issue by zellenberg** [haugene/docker-transmission-openvpn#1052]
**Describe the problem**
I have set TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED = true, and TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME = /mnt/user/appdata/Transmission_VPN/transmissionfinishpushover.sh, however when a torrent finishes, nothing happens. I have verified that the script itself works, as I have manually tested it.

**Add your docker run command**
I am not sure how to get this!

**Logs**
The logs do not even mention anything relating to the script, my variables, or anything else when a torrent finishes

**Host system:**
I am running this on Unraid 6.8.2

**Comment by pkishino** [comment]
The done script needs to be inside the container and the path needs to be the path to the script inside the container

**Comment by zellenberg** [comment]
@pkishino I am running this on unraid, is putting the script in the config (appdata) folder not actually in the container? If not - how do I put it in the container?

**Comment by zellenberg** [comment]
I changed the path to /config/transmissionfinishpushover.sh (/config is mapped to /mnt/user/appdata/Transmission_VPN/) but it still doesn't work

**Comment by pkishino** [comment]
Have you tried wheeling into the container and running the script from inside?

**Comment by zellenberg** [comment]
@pkishino yes - when I access the transmission docker console I can run the script manually and it works

**Comment by pkishino** [comment]
Is there anything in the transmission logs?

**Comment by zellenberg** [comment]
Nothing. No reference to failure or even attempt to run the script.

**Comment by zellenberg** [comment]
@pkishino scratch that - I was looking in the wrong place. It seems that it is trying to call the script, but somehow it isn't working.

`[2020-02-23 19:56:27.010] 1917.2019.DVDSCR.x264-TOPKEK Calling script "/config/transmissionfinishpushover.sh" (torrent.c:2118)`

**Comment by zellenberg** [comment]
@pkishino scratch that - I was looking in the wrong place. It seems that it is trying to call the script, but somehow it isn't working.

[2020-02-23 19:56:27.010] [FILE NAME REMOVED] Calling script "/config/transmissionfinishpushover.sh" (torrent.c:2118)

**Comment by zellenberg** [comment]
I realize it may be an issue with my script, so Ill post it here

`#!/bin/sh
curl -s \
	-F "token=[TOKEN REMOVED]" \
	-F "user=[USER REMOVED]" \
	-F "title=Download Finished" \
	-F "priority=-2" \
	-F "message=$TR_TORRENT_NAME finished" \
	http://api.pushover.net/1/messages > /dev/null
`

**Comment by zellenberg** [comment]
I figured it out! Had to go into the docker console and chmod 755 the script file. Thanks for your help @pkishino !!
