### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by mlcarson** [haugene/docker-transmission-openvpn#1057]
**Is your feature request related to a problem? Please describe.**

The most popular apps that would utilize this docker are Sonarr and Radarr.  I've had problems with both in the past because I'm running them in separate Docker containers which utilize the volume "/downloads" whereas this container utilizes "/data" for the same purpose.  I don't understand why this poses a conflict but both Sonarr and Radarr were complaining about not being able to import files from /data/completed which makes sense since the volume /data isn't defined in their containers.  

My solution to this was fairly simple but it would be more obvious with a documented example.  Instead of using /data for my volume in this container, I created "/downloads" to be consistent with the other containers.  I then used the following Transmission environmental variables.
-e "TRANSMISSION_DOWNLOAD_DIR=/downloads/completed" 
-e "TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete" 
-e "TRANSMISSION_WATCH_DIR=/downloads/watch" 

**Describe the solution you'd like**
In the Arguments section of the documentation, mention the above variables in the Transmission configuration options area and how they can be used to override the default volume of "/data" 

I know you link to a web page with all of the Transmission options but if you don't know that they're there then you don't look for them.
https://github.com/haugene/docker-transmission-openvpn/blob/master/DockerEnv

**Comment by pkishino** [comment]
Actually the way to fix this is to use the folder mapping setting in radar/sonarr to tell sonarr what the correct folder naming in one container is and what that correspond to in container b

**Comment by mlcarson** [comment]
I'll admit that I've not tried that setting.  It's only visible if you enable advanced settings and Remote Path Mappings didn't seem to be the appropriate option when everything is being done on the same server.  This would also create yet another level of indirection.  I can see that it could work assuming you pass the correct Host but it requires changing two container apps rather than just one.    Changing everything to match at the container configuration level for Sonarr/Radarr/Transmission/NZBGet seems to be the simpler solution unless I'm breaking something that I'm unaware of.    It's the first time on my system far that everything just seems to work.
