### ISSUE TITLE
Could Not connect to tracker - public trackers only

### ISSUE THREAD

**Issue by tsmithco** [haugene/docker-transmission-openvpn#1059]
Any downloads sent to Transmission with a public tracker have a warning, and show Could not connect to tracker.  However, they still download. (at seemingly slower speeds).  
Anything from a private tracker does not show the warning, and shows normal speeds.

DNS working fine.  Can open bash shell in container and ping via dns names.
VPN is PIA
Running on Synology

**Comment by mehulboricha** [comment]
I think that your VPN provider might be limiting this, but try and check it on your computer.

1. Start the VPN on your computer.
2. Download the torrent that you were getting this error on.

This will be the best way to debug the problem.
