### ISSUE TITLE
Unable to see or download 'latest' tag on Synology Docker

### ISSUE THREAD

**Issue by spacecakes** [haugene/docker-transmission-openvpn#106]
Hi,

for some reason I am not given the choice to select tags newer than `1.10`. From what I understand, Docker tags are software versions. Crucially I need to connect to IntegrityVPN and `1.10` gives me an error stating there is no such provider.

I've been unable to manually install the files either.

[Screenshot](https://www.dropbox.com/s/7rmfj070fqfm2s7/Sk%C3%A4rmklipp%202016-07-26%2009.45.16.png?dl=0) _Swedish: choose tag_

**Comment by spacecakes** [comment]
This might be a Synology issue. I was able to download the latest version using the terminal instead, typing out `sudo docker pull haugene/transmission-openvpn` and then it popped up in the Docker GUI. I've filed a report with Synology.

**Comment by haugene** [comment]
Hmm, yeah that's weird. But definately sounds like a Synology issue, double checked that I remembered to create the 1.11 tag on Docker Hub at least. Please keep me posted if they have a response to your report.

A lot of people use Synology and even if they fix it, it would require a software update for all who wants to use a newer image. Maybe the solution is that I delete some of the older tags.

**Comment by haugene** [comment]
Have now deleted tags older than 1.5, should be of little interest by now... Check and see if it fixed anything (might be cached for a while though).

**Comment by spacecakes** [comment]
They've confirmed it's an issue, but I'm not sure how to interpret the response:

> Dear Gabriel Lundmark,

>As we know if would be a issue on Docker server.
>We are also waiting for the fix and hope it will be soon. 

>Thanks,

>Tashi

I see fewer tags now, but still nothing newer than 1.10. I executed a pull command using SSH and the latest version popped up in Docker. Easy workaround.

**Comment by haugene** [comment]
Okay. Then, let's hope they fix it soon! Closing this for now, not an issue with this container anyways :)
