### ISSUE TITLE
Which dns is used by default

### ISSUE THREAD

**Issue by farika** [haugene/docker-transmission-openvpn#1062]
Hi,

Which DNS is used by default when vpn is connected? The dns of the vpn, or does docker refer to the host's dns and therefore it is a leak dns? 
I don't know how I can check because ipleak website only verify the ip leak with the magnet, not the DNS.
Does i need to clearly specify a --dns in my docker run command?

Thanks

**Comment by mehulboricha** [comment]
It will use your VPNs DNS unless specified explicitly to use any particular DNS servers.

For more read this: https://serverfault.com/questions/416708/how-to-ensure-openvpn-connection-uses-specific-dns
