### ISSUE TITLE
Privado VPN update ovpn files please

### ISSUE THREAD

**Issue by Ricardo-0101** [haugene/docker-transmission-openvpn#1065]
**Which provider?**
Privado

**Where are the configs?**
[https://privado.io/apps/ovpn_configs.zip](url)

**Comment by pilotman28** [comment]
Perhaps updating the ovpn files will also resolve
WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1571', remote='link-mtu 1572'
WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'

**Comment by haugene** [comment]
Updated now and pushed to dev branch. Can you try pulling the :dev tag and see if it works any better for you? It seems they only deleted some configs. So all the existing configs (that are not deleted) should still work.

The list of deleted configs are:
```
        deleted:    openvpn/privado/ams-001.ovpn
        deleted:    openvpn/privado/ams-002.ovpn
        deleted:    openvpn/privado/ams-003.ovpn
        deleted:    openvpn/privado/ams-004.ovpn
        deleted:    openvpn/privado/dca-017.ovpn
        deleted:    openvpn/privado/dca-018.ovpn
        deleted:    openvpn/privado/fll-001.ovpn
        deleted:    openvpn/privado/fll-002.ovpn
        deleted:    openvpn/privado/hkg-001.ovpn
        deleted:    openvpn/privado/jfk-005.ovpn
        deleted:    openvpn/privado/jfk-006.ovpn
        deleted:    openvpn/privado/mad-001.ovpn
        deleted:    openvpn/privado/nrt-001.ovpn
        deleted:    openvpn/privado/syd-001.ovpn
        deleted:    openvpn/privado/syd-002.ovpn
        deleted:    openvpn/privado/yyz-001.ovpn
        deleted:    openvpn/privado/yyz-002.ovpn
```

Among them were the default config ams-001. But if you set the config to any other it should still work.

Anyways. Test it and we can merge to master.

**Comment by pilotman28** [comment]
I'd say it works:
Mon Mar 30 08:53:24 2020 VERIFY OK: depth=1, CN=Privado
Mon Mar 30 08:53:24 2020 VERIFY X509NAME OK: CN=ams-005.vpn.privado.io
Mon Mar 30 08:53:24 2020 VERIFY OK: depth=0, CN=ams-005.vpn.privado.io
Mon Mar 30 08:53:25 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1569', remote='link-mtu 1570'
Mon Mar 30 08:53:25 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
Mon Mar 30 08:53:25 2020 Control Channel: TLSv1.2, cipher SSLv3 DHE-RSA-AES256-SHA, 4096 bit RSA
Mon Mar 30 08:53:25 2020 [ams-005.vpn.privado.io] Peer Connection Initiated with [AF_INET]91.148.224.50:1194
Mon Mar 30 08:53:26 2020 SENT CONTROL [ams-005.vpn.privado.io]: 'PUSH_REQUEST' (status=1)
