### ISSUE TITLE
TigerVPN : packet HMAC authentication failed

### ISSUE THREAD

**Issue by DraGula** [haugene/docker-transmission-openvpn#1067]
Hello
I've been having a problem with TigerVPN for a while now.
I often have errors like "**packet HMAC authentication failed**".
I can't connect to the VPN. I'm either forced to restarting the container, or rebuild it.

My command line is :

> docker run --name torvpn --cap-add=NET_ADMIN -d -v downloadsshare:/data -e "CREATE_TUN_DEVICE=true" -e "TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true" -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" -e "OPENVPN_PROVIDER=TIGER" -e "OPENVPN_CONFIG=Frankfurt" -e "OPENVPN_USERNAME=xxxxxx" -e "OPENVPN_PASSWORD=xxxxx" -e "WEBPROXY_ENABLED=false" -e "LOCAL_NETWORK=192.168.1.0/24" -e "TRANSMISSION_WATCH_DIR_ENABLED=true" --log-driver json-file --log-opt max-size=10m --mount source=downloadsshare,target=/mnt/torrvpn --restart=always -p 9091:9091 haugene/transmission-openvpn

I've checked the ovpn files (and ca) for tigervpn, it's like the same as the web site.
I'm a little lost, I don't really know what to look for...

The log file is like :
```
Thu Mar  5 20:35:51 2020 UDP link remote: [AF_INET]37.253.248.92:1194,
Thu Mar  5 20:35:51 2020 [tigervpn.com] Peer Connection Initiated with [AF_INET]37.253.248.92:1194,
Thu Mar  5 20:35:52 2020 Preserving previous TUN/TAP instance: tun0,
Thu Mar  5 20:35:52 2020 Initialization Sequence Completed,
Thu Mar  5 20:36:02 2020 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Thu Mar  5 20:36:12 2020 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Thu Mar  5 20:36:22 2020 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Thu Mar  5 20:36:22 2020 [tigervpn.com] Inactivity timeout (--ping-restart), restarting,
Thu Mar  5 20:36:22 2020 SIGUSR1[soft,ping-restart] received, process restarting,
Thu Mar  5 20:36:27 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Mar  5 20:36:27 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]37.253.248.92:1194,
Thu Mar  5 20:36:27 2020 UDP link local (bound): [AF_INET][undef]:1194,
Thu Mar  5 20:36:27 2020 UDP link remote: [AF_INET]37.253.248.92:1194,
Thu Mar  5 20:36:27 2020 [tigervpn.com] Peer Connection Initiated with [AF_INET]37.253.248.92:1194,
Thu Mar  5 20:36:28 2020 Preserving previous TUN/TAP instance: tun0,
Thu Mar  5 20:36:28 2020 Initialization Sequence Completed,
Thu Mar  5 20:36:38 2020 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Thu Mar  5 20:36:48 2020 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Thu Mar  5 20:36:58 2020 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Thu Mar  5 20:36:58 2020 [tigervpn.com] Inactivity timeout (--ping-restart), restarting,
Thu Mar  5 20:36:58 2020 SIGUSR1[soft,ping-restart] received, process restarting,
Thu Mar  5 20:37:03 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Mar  5 20:37:03 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]37.253.248.92:1194,
Thu Mar  5 20:37:03 2020 UDP link local (bound): [AF_INET][undef]:1194,
Thu Mar  5 20:37:03 2020 UDP link remote: [AF_INET]37.253.248.92:1194,
Thu Mar  5 20:37:03 2020 [tigervpn.com] Peer Connection Initiated with [AF_INET]37.253.248.92:1194,
Thu Mar  5 20:37:04 2020 Preserving previous TUN/TAP instance: tun0,
Thu Mar  5 20:37:04 2020 Initialization Sequence Completed,
```

An idea ? :)
Thanks !

**Comment by DraGula** [comment]
Yop,
No idea here ? Sniffff

**Comment by pkishino** [comment]
Could it be that they have changed their openvpn config? Can you compare the ones from here with the latest from their website?

**Comment by DraGula** [comment]
Hi,
I've checked the ovpn files (and ca) for tigervpn, it's like the same as the web site.
:(

**Comment by DraGula** [comment]
No other ideas?

**Comment by pkishino** [comment]
Seems like some problem with the config files:
https://askubuntu.com/questions/594868/openvpn-hmac-authentication-failure-no-matter-what-i-do
Can you show the ovpn file from tiger next to the one in the repo for easy comparison please?

**Comment by haugene** [comment]
Merged #1102 that adds new servers for TigerVPN and changes the default server. Try it and see if it works now? do a `docker pull haugene/transmission-openvpn` to make sure you have the latest version

**Comment by benmcmath** [comment]
I too saw these errors. I was able to get Tiger working by following [the instructions](https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_custom_provider) on creating a CUSTOM vpn provider.  Hope that helps

**Comment by DraGula** [comment]
> I too saw these errors. I was able to get Tiger working by following [the instructions](https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_custom_provider) on creating a CUSTOM vpn provider. Hope that helps

Thank you for your feedback. 

For me for the moment I've got my fingers crossed,
The only thing that seems to work on my side is to add several servers in the conf ("OPENVPN_CONFIG=CA Toronto,CZ Prague,US Chicago,US Denver,SE Stockholm,NO Oslo,IT Milan,IE Dublin,FR Paris,LU Luxembourg,UA Kiev")
If it stops working, I'll test via a custom config.
Thank you
