### ISSUE TITLE
RTNETLINK answers: Permission denied

### ISSUE THREAD

**Issue by sparky2002** [haugene/docker-transmission-openvpn#1069]
Firstly, apologies for what will probably be a noob error.

I am getting the following error when starting my container

/sbin/ip -6 addr add fde4:8dba:82e2::1017/64 dev tun0,
RTNETLINK answers: Permission denied,
Sun Mar  8 11:29:38 2020 Linux ip -6 addr add failed: external program exited with error status: 2,
Sun Mar  8 11:29:38 2020 Exiting due to fatal error,

I have tried the suggestions  https://github.com/dperson/openvpn-client/issues/75,
#960 , #789.

I have added the line 

net.ipv6.conf.all.disable_ipv6 = 1

and enabled packet forwarding 
into the sysctl.conf

and commented out the ipv6 references in the hosts file

I believe, i am experiencing something similar to #789 

Software is OMV5 (Portainer,io) on raspberry pi 4.
image haugene/transmission-openvpn:latest-armhf

A copy of my log is posted below.
Using OpenVPN provider: TUNNELBEAR,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
Sun Mar  8 11:29:36 2020 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6,
Sun Mar  8 11:29:36 2020 WARNING: file '/etc/openvpn/tunnelbear/PrivateKey.key' is group or others accessible,
Sun Mar  8 11:29:36 2020 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019,
Sun Mar  8 11:29:36 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10,
Sun Mar  8 11:29:36 2020 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
Sun Mar  8 11:29:36 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Sun Mar  8 11:29:36 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]195.154.237.97:443,
Sun Mar  8 11:29:36 2020 UDP link local: (not bound),
Sun Mar  8 11:29:36 2020 UDP link remote: [AF_INET]195.154.237.97:443,
Sun Mar  8 11:29:36 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Sun Mar  8 11:29:37 2020 [1758/server] Peer Connection Initiated with [AF_INET]195.154.237.97:443,
Sun Mar  8 11:29:38 2020 TUN/TAP device tun0 opened,
Sun Mar  8 11:29:38 2020 /sbin/ip link set dev tun0 up mtu 1500,
Sun Mar  8 11:29:38 2020 /sbin/ip addr add dev tun0 local 172.18.12.98 peer 172.18.12.97,
Sun Mar  8 11:29:38 2020 /sbin/ip -6 addr add fde4:8dba:82e2::1017/64 dev tun0,
RTNETLINK answers: Permission denied,
Sun Mar  8 11:29:38 2020 Linux ip -6 addr add failed: external program exited with error status: 2,
Sun Mar  8 11:29:38 2020 Exiting due to fatal error,

Any help will be appreciated, I am new to all this and it is driving me to insanity!!

Thanks

Paul

**Comment by euam23** [comment]
Same issue here. My log looks almost identical exiting with the same error. 

Any pointers would be greatly appreciated. 

Thanks

**Comment by euam23** [comment]
Try #847 ! I'm in the same boat as yourself. Fairly new to the whole docker idea. Had exactly the same issue as you and it kept dying on the IPV6. 
Copied and pasted the pull filter commands and it worked. 

Trust me, this has been driving me nuts, took me a fair few days on off to figure it out. 

Good luck

**Comment by sparky2002** [comment]
I'll look at that - thanks.

I need to have some time away from technology.

I've been wanting to smash the thing up with a hammer - not helped by some
of my mistakes!

Cheers

Need to have some time away from it all

**Comment by sparky2002** [comment]
Yeh, done that suggestion.
On a positive, I have learnt to copy files out of the container, edit, and then copy back.

Still doesn't work tho!

In my log it says 'No VPN configuration provided. Using default'.
Could it be that I've added the lines of code in container:/etc/openvpn/tunnel eat/United kingdom.ovpn but for some reason it is not reading that file??
I have added the openvpn location in environment variables..

**Comment by sparky2002** [comment]
Sorted, got it to read the config file. I was using the incorrect OPENVPN_LOCATION instead of OPENVPN_CONFIG.

**Comment by pkishino** [comment]
> Sorted, got it to read the config file. I was using the incorrect OPENVPN_LOCATION instead of OPENVPN_CONFIG.

Please close ticket if sorted :)

**Comment by AKDub** [comment]
Having the same problem after switching to Mullvad from NordVPN.

How do you edit the files? I cant exec into the container as it only stays up for a few seconds

**Comment by sparky2002** [comment]
Look #847 above 

And this below

> docker cp mullvad_au-per_udp.ovpn transmission-openvpn:/etc/openvpn/mullvad/
> 

This translates to 'docker cp yourconfigfile.ovpn yourcontainername:/etc/openvpn/yourvpnprovider'

**Comment by andyfore** [comment]
I had this error and I fixed it by doing using the advanced settings on the MVD config generator to mark it as IPv4 only and to ensure that I did not have the killswitch on.
