### ISSUE TITLE
Use extrenal ovpn files

### ISSUE THREAD

**Issue by fdecourt** [haugene/docker-transmission-openvpn#1073]
Hi,
It should be nice to add few parameters in the environment variables and the directory to allow the use of dedicated ovpn files instead of the one included in the container. Many advantages : 
1. Provider free
2. Providers cutomization easy
3. Easy maintenance for you : you don't have to update your docker image with new provider ovpn anytime there are some changes

**Comment by haugene** [comment]
You are completely free to mount an .ovpn file and run with that instead. Just to clarify, have you read this? https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_custom_provider

If you haven't then I hope this is what you're looking for. And if you have read it and still want some additional customization, can you clearify?
