### ISSUE TITLE
Transmission Container stops just after reboot of Alpine Linux

### ISSUE THREAD

**Issue by marc0janssen** [haugene/docker-transmission-openvpn#1077]
I have a Intel NUC with Alpine Linux and of course docker installed.

If I start the Haugene Transmission-openvpn container all works fine, no problem at all.

If I then reboot the Alpine Linux system, the Transmission container is eventually stopped after reboot.
If I then restart the container by hand from the prompt... ALL IS OKAY AGAIN.

**Docker command
docker run --restart=always --cap-add=NET_ADMIN --device=/dev/net/tun -d \
	-v /docker/transmissionVPN/resolv.conf:/etc/resolv.conf \
	-v /mnt/downloads/watchVPN/:/downloads/watchVPN \
	-v /mnt/downloads/:/downloads \
	-v /docker/transmissionVPN/:/transmissionVPN \
	-e "NORDVPN_COUNTRY=NL" -e "NORDVPN_PROTOCOL=UDP" -e "OPENVPN_PROVIDER=NORDVPN" -e "OPENVPN_USERNAME=yyyyyyy" -e "OPENVPN_PASSWORD=xxxxxxxx" -e "LOCAL_NETWORK=192.168.1.0/24" -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" -e "PGID=100" -e "PUID=0" -e "TRANSMISSION_DOWNLOAD_DIR=/downloads/complete" -e "TRANSMISSION_INCOMPLETE_DIR=/transmissionVPN/incomplete" -e "TRANSMISSION_WATCH_DIR=/downloads/watchVPN" -e "TRANSMISSION_WEB_UI=kettu" -e "TRANSMISSION_UMASK=0" -e "TRANSMISSION_RATIO_LIMIT=0" -e "TRANSMISSION_RATIO_LIMIT_ENABLED=true" -e "TRANSMISSION_IDLE_SEEDING_LIMIT=0" -e "TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true" -p 9091:9091 --sysctl net.ipv6.conf.all.disable_ipv6=0 --name "transmission-openvpn-syno" haugene/transmission-openvpn:latest

**Logs**
2020-03-15 13:34:37 Selecting the best server...,
2020-03-15 13:34:37 Searching for group: legacy_p2p,
2020-03-15 13:34:37 Searching for technology: openvpn_udp,
2020-03-15 13:34:37 Best server : nl613.nordvpn.com,
2020-03-15 13:34:37 Downloading config: default.ovpn,
2020-03-15 13:34:37 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/nl613.nordvpn.com.udp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2812  100  2812    0     0  17685      0 --:--:-- --:--:-- --:--:-- 17685,
2020-03-15 13:34:37 Selecting the best server...,
2020-03-15 13:34:37 Searching for country : NL (153),
2020-03-15 13:34:37 Searching for group: legacy_p2p,
2020-03-15 13:34:37 Searching for technology: openvpn_udp,
2020-03-15 13:34:37 Best server : nl613.nordvpn.com,
2020-03-15 13:34:37 Downloading config: nl613.nordvpn.com.ovpn,
2020-03-15 13:34:37 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/nl613.nordvpn.com.udp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2812  100  2812    0     0  19527      0 --:--:-- --:--:-- --:--:-- 19527,
2020-03-15 13:34:37 Checking line endings,
2020-03-15 13:34:37 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config nl613.nordvpn.com.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0,
Sun Mar 15 13:34:39 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019,
Sun Mar 15 13:34:39 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08,
Sun Mar 15 13:34:39 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Sun Mar 15 13:34:39 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Sun Mar 15 13:34:39 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Sun Mar 15 13:34:39 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]178.239.173.163:1194,
Sun Mar 15 13:34:39 2020 Socket Buffers: R=[212992->212992] S=[212992->212992],
Sun Mar 15 13:34:39 2020 UDP link local: (not bound),
Sun Mar 15 13:34:39 2020 UDP link remote: [AF_INET]178.239.173.163:1194,
Sun Mar 15 13:34:39 2020 TLS: Initial packet from [AF_INET]178.239.173.163:1194, sid=19319ce0 7be03910,
Sun Mar 15 13:34:39 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Sun Mar 15 13:34:39 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun Mar 15 13:34:39 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun Mar 15 13:34:39 2020 VERIFY KU OK,
Sun Mar 15 13:34:39 2020 Validating certificate extended key usage,
Sun Mar 15 13:34:39 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun Mar 15 13:34:39 2020 VERIFY EKU OK,
Sun Mar 15 13:34:39 2020 VERIFY OK: depth=0, CN=nl613.nordvpn.com,
Sun Mar 15 13:34:39 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun Mar 15 13:34:39 2020 [nl613.nordvpn.com] Peer Connection Initiated with [AF_INET]178.239.173.163:1194,
Sun Mar 15 13:34:40 2020 SENT CONTROL [nl613.nordvpn.com]: 'PUSH_REQUEST' (status=1),
Sun Mar 15 13:34:45 2020 SENT CONTROL [nl613.nordvpn.com]: 'PUSH_REQUEST' (status=1),
Sun Mar 15 13:34:45 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.8.0.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.0.16 255.255.255.0,peer-id 27,cipher AES-256-GCM',
Sun Mar 15 13:34:45 2020 Option 'explicit-exit-notify' in [PUSH-OPTIONS]:6 is ignored by previous <connection> blocks ,
Sun Mar 15 13:34:45 2020 OPTIONS IMPORT: timers and/or timeouts modified,
Sun Mar 15 13:34:45 2020 OPTIONS IMPORT: explicit notify parm(s) modified,
Sun Mar 15 13:34:45 2020 OPTIONS IMPORT: compression parms modified,
Sun Mar 15 13:34:45 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified,
Sun Mar 15 13:34:45 2020 Socket Buffers: R=[212992->425984] S=[212992->425984],
Sun Mar 15 13:34:45 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Sun Mar 15 13:34:45 2020 OPTIONS IMPORT: route options modified,
Sun Mar 15 13:34:45 2020 OPTIONS IMPORT: route-related options modified,
Sun Mar 15 13:34:45 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Sun Mar 15 13:34:45 2020 OPTIONS IMPORT: peer-id set,
Sun Mar 15 13:34:45 2020 OPTIONS IMPORT: adjusting link_mtu to 1657,
Sun Mar 15 13:34:45 2020 OPTIONS IMPORT: data channel crypto options modified,
Sun Mar 15 13:34:45 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Sun Mar 15 13:34:45 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun Mar 15 13:34:45 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun Mar 15 13:34:45 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:04,
Sun Mar 15 13:34:45 2020 TUN/TAP device tun0 opened,
Sun Mar 15 13:34:45 2020 TUN/TAP TX queue length set to 100,
Sun Mar 15 13:34:45 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=0,
Sun Mar 15 13:34:45 2020 /sbin/ip link set dev tun0 up mtu 1500,
Sun Mar 15 13:34:45 2020 /sbin/ip addr add dev tun0 10.8.0.16/24 broadcast 10.8.0.255,
Sun Mar 15 13:34:45 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1585 10.8.0.16 255.255.255.0 init,
Up script executed with tun0 1500 1585 10.8.0.16 255.255.255.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.0.16,
Using Kettu UI, overriding TRANSMISSION_WEB_HOME,
Generating transmission settings.json from env variables,
sed'ing True to true,
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   root,
User uid:    0,
User gid:    0,
-------------------------------------,
,
STARTING TRANSMISSION,
NO PORT UPDATER FOR THIS PROVIDER,
Transmission startup script complete.,
Sun Mar 15 13:34:45 2020 /sbin/ip route add 178.239.173.163/32 via 172.17.0.1,
Sun Mar 15 13:34:45 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1,
Sun Mar 15 13:34:45 2020 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1,
Sun Mar 15 13:34:45 2020 Initialization Sequence Completed,
Sun Mar 15 13:48:04 2020 event_wait : Interrupted system call (code=4),
Sun Mar 15 13:48:04 2020 SIGTERM received, sending exit notification to peer,
Sun Mar 15 13:48:05 2020 /sbin/ip route del 178.239.173.163/32,
Sun Mar 15 13:48:05 2020 /sbin/ip route del 0.0.0.0/1,
Sun Mar 15 13:48:05 2020 /sbin/ip route del 128.0.0.0/1,
Sun Mar 15 13:48:05 2020 Closing TUN/TAP interface,
Sun Mar 15 13:48:05 2020 /sbin/ip addr del dev tun0 10.8.0.16/24,
Sun Mar 15 13:48:05 2020 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.0.16 255.255.255.0 init,
Sun Mar 15 13:48:05 2020 SIGTERM[soft,exit-with-notification] received, process exiting,

**Host system:**
Intel NUC7i3BNH
Alpine Linux  cccc  5.4.12-1-lts #2-Alpine SMP Thu, 16 Jan 2020 12:53:54 UTC x86_64 Linux

Client:
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        633a0ea838f10e000b7c6d6eed1623e6e988b5bb
 Built:             Mon Nov 25 16:06:35 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       633a0ea838f10e000b7c6d6eed1623e6e988b5bb
  Built:            Fri Nov 15 10:30:46 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:

**Comment by mehulboricha** [comment]
Hey there,

You have to start the container on every reboot, that is how docker works. For more information read this: https://haugene.github.io/docker-transmission-openvpn/systemd-integration/

**Comment by marc0janssen** [comment]
Hi There,

All others container just come online after a reboot.

**Comment by marc0janssen** [comment]
Thanks mehulboricha!! I got it.. In the meantime I fixed it in another fashion. Thanks!

**Comment by mehulboricha** [comment]
That's awesome. Can you please comment here what you did because it will help many others who have similar issues. :D

**Comment by marc0janssen** [comment]
Ok ... I will add my solution here. But first I have to explain. I am using the Haugene images for quite awhile. The previous version had no "automatic" NORDVPN server selection. You had to set it manually by OPENVPN_CONFIG. 

What I wanted in those days was to cycle through the available NORDVPNservers every several hours. So I wrote a script that cycled through the available VPN-configs at random in the Docker image. 

Now this is not necessary anymore, the docker image of Haugene picks a random NORDVPN server every time a restart the container. This is great.

What I also wanted was, if the VPN-tunnel would crash I should start a new automatically. This is now also a lot easier because the images pick a server automatically at start-up..

I rewrote the original scripts for this new way of HAUGENE docker image. But if anyone is interested in the old scripts... I can shared them.

That said, here are the scripts. I use. Using it with cron, will start the docker container after 2 minutes and you don't need  SYSTEMD integration.

**First script:** To randomly get NORDVPN connected (remember it is easy now, on the old images needed to do a lot more).

--- start script : randomizeSabnzbdVPN.sh
#!/bin/sh
NOW=$(date +"%d-%m-%Y %H:%M")
container="transmission-openvpn-syno"

docker restart  $container
sleep 10
IP=`docker exec $container sudo bash -c 'curl -s https://ipecho.net/plain'`

echo $NOW " - Cycling transmissionVPN to" $IP >> /logging/vpn/vpn.log 

--- end script ---

This has any crontab-entry link:
0	5	1,3,5	*	*	if [ "`date +%H`" == "05" ]; then sleep ${RANDOM:1:2}m; fi; /docker/sabnzbdvpn/scripts/randomizeSabnzbdVPN.sh > /dev/null 2>&1


**Second script:** To recover for a bad VPN-connection.

This script is to check for a faulty VPN-connection and restart.
(again this is super simpel with the current HAUGENE images, but you needed a lot more work with the older images).

--- start script: recoverTransmissionVPN.sh

#!/bin/sh
NOW=$(date +"%d-%m-%Y %H:%M")
container="transmission-openvpn-syno"

if [ ! "`docker logs --tail 8 $container | grep 'Initialization Sequence Completed'`" ]; then


	docker restart $container
	echo $NOW " - transmissionVPN trying to be recovered" >> /logging/vpn/error.log; 

	sleep 10
	
	IP=`docker exec $container sudo bash -c 'curl -s https://ipecho.net/plain'`
	if [ ! "$IP" ]; then IP="000.000.000.000"; fi
	echo $NOW " - Cycling transmissionVPN to" $IP >> /logging/vpn/vpn.log 

fi

---- end script

This one has a crontab-entry like:
*/2	*	*	*	*	/docker/transmissionVPN/scripts/recoverTransmissionVPN.sh;

**Comment by marc0janssen** [comment]
SINCE I run my docker on a Alpine Linux system, I have to use OPENRC instead of SYSTEMD.

I don't like this SYSTEMD/OPENRC methode, because a crashed container will be destroyed and al your current downloads will be gone.

Any for you guys who are on Alpine and to like the OPENRC(SYSTEMD) solution, here is my 2 cents on such a script:




#!/sbin/openrc-run

name=$RC_SVCNAME
command="/usr/bin/docker"
command_args="run --restart=always --cap-add=NET_ADMIN --device=/dev/net/tun -d -v /docker/transmissionVPN/resolv.conf:/etc/resolv.conf -v /mnt/downloads/watchVPN/:/downloads/watchVPN -v /mnt/downloads/:/downloads -v /docker/transmissionVPN/:/transmissionVPN -v /docker/transmissionVPN/data/:/data -v /docker/transmissionVPN/config/:/config -e 'NORDVPN_COUNTRY=NL' -e 'NORDVPN_PROTOCOL=UDP' -e 'OPENVPN_PROVIDER=NORDVPN' -e 'OPENVPN_USERNAME=USER' -e 'OPENVPN_PASSWORD=PASSWORD' -e 'LOCAL_NETWORK=192.168.1.0/24' -e 'OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60' -e 'PGID=0' -e 'PUID=0' -e 'TRANSMISSION_DOWNLOAD_DIR=/downloads/complete' -e 'TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete' -e 'TRANSMISSION_WATCH_DIR=/downloads/watchVPN' -e 'TRANSMISSION_WEB_UI=kettu' -e 'TRANSMISSION_UMASK=0' -e 'TRANSMISSION_RATIO_LIMIT=0' -e 'TRANSMISSION_RATIO_LIMIT_ENABLED=true' -e 'TRANSMISSION_IDLE_SEEDING_LIMIT=0' -e 'TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true' -p 9091:9091 --sysctl net.ipv6.conf.all.disable_ipv6=0 --name 'transmission-openvpn-syno' haugene/transmission-openvpn:latest"

depend() {
        after docker
}

start_pre() {
	/usr/bin/docker kill transmission-openvpn-syno
	/usr/bin/docker rm transmission-openvpn-syno
	/usr/bin/docker pull haugene/transmission-openvpn 
}

**Comment by mehulboricha** [comment]
Hey there,

Let me suggest you the method that I am using to preserve the transmission data on every reboot or even after updating the container.

As mentioned here I am using systemd integration as mentioned here: https://haugene.github.io/docker-transmission-openvpn/systemd-integration/

Let me explain how this will work:
Transmission Stores all the data of how many torrents are added, being downloaded, etc. in the transmission home directory. So what you need to do is to preserve that directory. The best way to do that is to use volumes.

So first set Environment Variable: 

> TRANSMISSION_HOME=/dockerdata

Then mount the volume in docker run like:

-v /home/pi/dockerdata/transmissionopenvpn/:/dockerdata

I hope this is the solution you were looking for :D

**Comment by marc0janssen** [comment]
Hi Melhulboricha,

That is what I also have already. This is my docker creation script.


docker run --restart=always --cap-add=NET_ADMIN --device=/dev/net/tun -d \
	-v /docker/transmissionVPN/resolv.conf:/etc/resolv.conf \
	-v /mnt/downloads/watchVPN/:/downloads/watchVPN \
	-v /mnt/downloads/:/downloads \
	-v /docker/transmissionVPN/:/transmissionVPN \
	**-v /docker/transmissionVPN/data/:/data \**
	-v /docker/transmissionVPN/config/:/config \
	-e 'NORDVPN_COUNTRY=NL' \
	-e 'NORDVPN_PROTOCOL=UDP' \
	-e 'OPENVPN_PROVIDER=NORDVPN' \
	-e 'OPENVPN_USERNAME=USER' \
	-e 'OPENVPN_PASSWORD=PASSWORD' \
	-e 'LOCAL_NETWORK=192.168.1.0/24' \
	-e 'OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60' \
	-e 'PGID=0' -e 'PUID=0' \
	-e 'TRANSMISSION_DOWNLOAD_DIR=/downloads/complete' \
	-e 'TRANSMISSION_INCOMPLETE_DIR=/transmissionVPN/incomplete' \
	-e 'TRANSMISSION_WATCH_DIR=/downloads/watchVPN' \
	-e 'TRANSMISSION_WEB_UI=kettu' \
	-e 'TRANSMISSION_UMASK=0' \
	-e 'TRANSMISSION_RATIO_LIMIT=0' \
	-e 'TRANSMISSION_RATIO_LIMIT_ENABLED=true' \
	-e 'TRANSMISSION_IDLE_SEEDING_LIMIT=0' \
	-e 'TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true' \
	-p 9091:9091 \
	--sysctl net.ipv6.conf.all.disable_ipv6=0 \
	--name "transmission-openvpn-syno" \
	haugene/transmission-openvpn:latest

MY point with the OPENRC was that it is not that great, maybe systemd is better, but OPENRC is not that great,

1. it starts that container. that is a good thing.
2. It can't stop the container, that's bad. It does not recognize the service "transmission".

This means the integration is not that great, so I prefer my "crond" methode.

Thanks for all your help!

**Comment by mehulboricha** [comment]
No, I was talking about preserving the transmission state.

You have not mentioned the transmission home directory using the TRANSMISSION_HOME env variable. Please check my previous reply and you have also not defined a volume to store transmission home directory.

**Comment by mehulboricha** [comment]
Oh okay okay. Got it. You can close the issue if it is resolved now :D
