### ISSUE TITLE
Cannot access to WebUI

### ISSUE THREAD

**Issue by MathieuDepetris** [haugene/docker-transmission-openvpn#1078]
First of all, thank you very much for the brilliant work !

I'm quite new in using docker and I cannot access to the webUI of transmission and I really don't understand why.

I try to install it on a synology NAS with NordVPN provider. I make all the architecture request in the documentation section (TUN.sh and resolv.conf files with directories associated and task Scheduler for the TUN.sh) and I launch the package through this command:

docker run \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    -d \
    -v /volume1/docker/transmission_openvpn/resolv.conf:/etc/resolv.conf \
    -v /volume1/telechargements/:/data \
    -v /etc/localtime:/etc/localtime:ro \
    -e CREATE_TUN_DEVICE=true \
    -e "OPENVPN_PROVIDER=NORDVPN" \
    -e "OPENVPN_USERNAME=username" \
    -e "OPENVPN_PASSWORD=password" \
    -e "NORDVPN_COUNTRY=FR" \
    -e "NORDVPN_CATEGORY=P2P" \
    -e "NORDVPN_PROTOCOL=udp" \
    -e "LOCAL_NETWORK=10.0.0.0/24" \
    -e "DOCKER_LOG=true" \
    --log-driver json-file \
    --log-opt max-size=10m \
    -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
    -e "TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false"\
    -e "TRANSMISSION_WEB_UI=transmission-web-control"\
    -e "PGID=100" \
    -e "PUID=1234" \
    -p 9091:9091 \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --name "transmission-openvpn-syno" \
    haugene/transmission-openvpn:latest

I think I don't make any mistake on the LOCAL_NETWORK value because my NAS is located at 10.0.0.3

I open port 9091 (in tcp/udp protocols) on my router Nighthawk R7000 and in my NAS firewall but impossible to reach transmission webUI through the shortcut located on the NAS destock (and also at https://10.0.0.3:9091/).

Furthermore, impossible to take a look to the log. When I click on container detail and go to the log, I have the following message "no log available" (even if I specified below DOCKER_LOG=true).

Does any could help me ?

Best,

Mathieu

**Comment by pkishino** [comment]
A few comments:
- Router shouldn’t have port open as most likely don’t want direct access from outside your network
- https isn’t enabled in the container, use http
- check if the nas is listening on the port using netstat etc
- while in terminal, check: docker logs transmission-openvpn-syno
This should show something
Otherwise check docker ps -a to see that the container is up

**Comment by MathieuDepetris** [comment]
Dear @pkishino, thank you very much for your feedback.
Since your previous comment:
- I close ports on my router, I will see later for the access outisde network
- I modifided https for http but still no access. I tried http://10.0.0.3:9091 and http://my_nas_domaine:9091
- I don't know exactely who to listening the port but when I launch docker inspect -f '{{.State.Pid}}' transmission-openvpn-syno it display the port 14688 and the port change when I restart the container
- with you command docker logs transmission-openvpn-syno I have this log:

mknod: /dev/net/tun: File exists
Using OpenVPN provider: NORDVPN
2020-03-17 13:35:44 Checking curl installation
2020-03-17 13:35:44 Removing existing configs
2020-03-17 13:35:44 Selecting the best server...
2020-03-17 13:35:44 Searching for group: legacy_p2p
2020-03-17 13:35:44 Searching for technology: openvpn_udp
2020-03-17 13:35:44 Best server : fr388.nordvpn.com
2020-03-17 13:35:44 Downloading config: default.ovpn
2020-03-17 13:35:44 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/fr388.nordvpn.com.udp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2810  100  2810    0     0   1576      0  0:00:01  0:00:01 --:--:--  1575
2020-03-17 13:35:44 Selecting the best server...
2020-03-17 13:35:44 Searching for country : FR (74)
2020-03-17 13:35:44 Searching for group: legacy_p2p
2020-03-17 13:35:44 Searching for technology: openvpn_udp
2020-03-17 13:35:44 Best server : fr388.nordvpn.com
2020-03-17 13:35:44 Downloading config: fr388.nordvpn.com.ovpn
2020-03-17 13:35:44 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/fr388.nordvpn.com.udp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2810  100  2810    0     0   1371      0  0:00:02  0:00:02 --:--:--  1371
2020-03-17 13:35:44 Checking line endings
2020-03-17 13:35:44 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config fr388.nordvpn.com.ovpn
Setting OPENVPN credentials...
adding route to local network 10.0.0.0/24 via 172.17.0.1 dev eth0
Tue Mar 17 13:35:53 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
Tue Mar 17 13:35:53 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
Tue Mar 17 13:35:53 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Mar 17 13:35:53 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Mar 17 13:35:53 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Mar 17 13:35:53 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]139.28.219.245:1194
Tue Mar 17 13:35:53 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Tue Mar 17 13:35:53 2020 UDP link local: (not bound)
Tue Mar 17 13:35:53 2020 UDP link remote: [AF_INET]139.28.219.245:1194
Tue Mar 17 13:35:53 2020 TLS: Initial packet from [AF_INET]139.28.219.245:1194, sid=7342bb0c ce77b7d9
Tue Mar 17 13:35:53 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Mar 17 13:35:53 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Tue Mar 17 13:35:53 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
Tue Mar 17 13:35:53 2020 VERIFY KU OK
Tue Mar 17 13:35:53 2020 Validating certificate extended key usage
Tue Mar 17 13:35:53 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue Mar 17 13:35:53 2020 VERIFY EKU OK
Tue Mar 17 13:35:53 2020 VERIFY OK: depth=0, CN=fr388.nordvpn.com
Tue Mar 17 13:35:53 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Tue Mar 17 13:35:53 2020 [fr388.nordvpn.com] Peer Connection Initiated with [AF_INET]139.28.219.245:1194
Tue Mar 17 13:35:54 2020 SENT CONTROL [fr388.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Tue Mar 17 13:35:55 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.8.3.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.3.18 255.255.255.0,peer-id 16,cipher AES-256-GCM'
Tue Mar 17 13:35:55 2020 Option 'explicit-exit-notify' in [PUSH-OPTIONS]:6 is ignored by previous <connection> blocks
Tue Mar 17 13:35:55 2020 OPTIONS IMPORT: timers and/or timeouts modified
Tue Mar 17 13:35:55 2020 OPTIONS IMPORT: explicit notify parm(s) modified
Tue Mar 17 13:35:55 2020 OPTIONS IMPORT: compression parms modified
Tue Mar 17 13:35:55 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Tue Mar 17 13:35:55 2020 Socket Buffers: R=[212992->425984] S=[212992->425984]
Tue Mar 17 13:35:55 2020 OPTIONS IMPORT: --ifconfig/up options modified
Tue Mar 17 13:35:55 2020 OPTIONS IMPORT: route options modified
Tue Mar 17 13:35:55 2020 OPTIONS IMPORT: route-related options modified
Tue Mar 17 13:35:55 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Tue Mar 17 13:35:55 2020 OPTIONS IMPORT: peer-id set
Tue Mar 17 13:35:55 2020 OPTIONS IMPORT: adjusting link_mtu to 1657
Tue Mar 17 13:35:55 2020 OPTIONS IMPORT: data channel crypto options modified
Tue Mar 17 13:35:55 2020 Data Channel: using negotiated cipher 'AES-256-GCM'
Tue Mar 17 13:35:55 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Mar 17 13:35:55 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Mar 17 13:35:55 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
Tue Mar 17 13:35:55 2020 TUN/TAP device tun0 opened
Tue Mar 17 13:35:55 2020 TUN/TAP TX queue length set to 100
Tue Mar 17 13:35:55 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Tue Mar 17 13:35:55 2020 /sbin/ip link set dev tun0 up mtu 1500
Tue Mar 17 13:35:55 2020 /sbin/ip addr add dev tun0 10.8.3.18/24 broadcast 10.8.3.255
Tue Mar 17 13:35:55 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1585 10.8.3.18 255.255.255.0 init
Up script executed with tun0 1500 1585 10.8.3.18 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.3.18
Using Transmission Web Control  UI, overriding TRANSMISSION_WEB_HOME
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1234:100
Setting permission for files (644) and directories (755)
Setting permission for watch directory (775) and its files (664)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1234
User gid:    100
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Tue Mar 17 13:35:55 2020 /sbin/ip route add 139.28.219.245/32 via 172.17.0.1
Tue Mar 17 13:35:55 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.3.1
Tue Mar 17 13:35:55 2020 /sbin/ip route add 128.0.0.0/1 via 10.8.3.1
Tue Mar 17 13:35:55 2020 Initialization Sequence Completed
Couldn't (re)open log file "/proc/1/fd/1": Permission denied

Do you have any idea where the problem are ?
Best,
Mathieu

**Comment by pkishino** [comment]
Looking at the log, try accessing 10.8.3.18:9091
Second, the docker_log cant start due to permissions, you might need root
permission for the container if you want this enabled, try to remove it for
now

**Comment by mistrzunio** [comment]
try to run it in host networking mode as in https://docs.docker.com/network/network-tutorial-host/
and see if you can access the ui

**Comment by MathieuDepetris** [comment]
Dear @pkishino and @mistrzunio thank you for your help.
To be honest I don't know exactly what wrong but I try to modify my command and test some things found on forums and now it's working. If that can help some other, I post my command below:

docker run  --cap-add=NET_ADMIN -d \
            -v /volume1/telechargements/:/data \
            -v /etc/localtime:/etc/localtime:ro \
            -e CREATE_TUN_DEVICE=true \
            -e OPENVPN_PROVIDER=NORDVPN \
            -e OPENVPN_USERNAME=mymail \
            -e OPENVPN_PASSWORD=mypass \
            -e NORDVPN_COUNTRY=FR \
            -e NORDVPN_CATEGORY=P2P \
            -e NORDVPN_PROTOCOL=udp \
            -e WEBPROXY_ENABLED=false \
            -e TRANSMISSION_WEB_UI=transmission-web-control \
            -e TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false \
            -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
            -e LOCAL_NETWORK=10.0.0.0/24 \
            --dns 8.8.8.8 \
            --dns 8.8.4.4 \
            --restart=unless-stopped \
            -p 9091:9091 \
            --name transmission-openvpn-syno \
            haugene/transmission-openvpn:latest

Best,
Mathieu
