### ISSUE TITLE
Accessing Transmission WebUI from Outside Local Network

### ISSUE THREAD

**Issue by Radicitus** [haugene/docker-transmission-openvpn#1080]
Hey there!
First off, thank you so much for the amazing work! Aside from this annoying config stuff on my part, your container has worked flawlessly with everything and was easy enough to set up with your great documentation. You deserve a million cookies!

Now, for the problem. So, I actually am able to access the UI from outside, but only until the container restarts. Then, I need to login from my home network and go into settings in the UI and check "Use port forwarding on my router". Then, I am able to access the UI from outside again, and I need to do this every time. I was wondering if there is a way to pass this to the settings file from docker-compose. Or, if I'm doing something completely wrong (like exposing my network traffic to my ISPs by accident as a result of checking that setting). Any input is appreciated. Thanks!

**Comment by mehulboricha** [comment]
I am no expert here but I think setting this to true will fix your problem

TRANSMISSION_PORT_FORWARDING_ENABLED=true

**Comment by Radicitus** [comment]
I'm dumb, didn't realize there's an extensive health check before it's accessible through traefik outside my home network.

**Comment by haugene** [comment]
Yeah. That healthcheck has been mentioned in an issue before. It runs with a 5m interval, which I thought was nice as it will detect errors but not spam. The problem then is that it takes 5 minutes before it runs the first time and that is unfortunate when it prevents it from being added to load balancers like this.

You can have a look here. https://docs.docker.com/engine/reference/run/#healthcheck
You have the option to override the default setting and do `--health-interval=10s` or whatever. Or you can disable it with `--no-healthcheck` and just see for yourself if it's not working.
