### ISSUE TITLE
VPN startup hangs after UDP link remote

### ISSUE THREAD

**Issue by Sloop0** [haugene/docker-transmission-openvpn#1081]
Apologies for what is probably a very basic question, but I'm new to openVPN. I've tried everything I can think of with no results.

On launch, VPN startup reaches the UDP link remote step, and then does nothing after that until the ping times out and it repeats.

Docker-compose file:

`transmission:
    image: haugene/docker-transmission-openvpn
    container_name: transmission
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "9091:9091"
      - "8888:8888"
    volumes:
      - ${CONFIG}/vpn:/data
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - OPENVPN_PROVIDER=GHOSTPATH
      - OPENVPN_USERNAME=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_CONFIG=United-States-Roseburg, United-States-Seattle
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.86.0/24`

Logs:
```
Using OpenVPN provider: GHOSTPATH
2 servers found in OPENVPN_CONFIG, United-States-Seattle chosen randomly
Starting OpenVPN using config United-States-Seattle.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.86.0/24 via 172.22.0.1 dev eth0
Thu Mar 19 12:21:56 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
Thu Mar 19 12:21:56 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
Thu Mar 19 12:21:56 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Mar 19 12:21:56 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]167.88.112.78:443
Thu Mar 19 12:21:56 2020 UDP link local: (not bound)
Thu Mar 19 12:21:56 2020 UDP link remote: [AF_INET]167.88.112.78:443
```

I'm running on a Windows 10 PC using Docker for Windows. I know that can introduce some issues, but I have quite a few other containers up and running successfully.

**Comment by haugene** [comment]
Hey @Sloop0. There might be differences between vpn providers, but it seems most of the vpn remote servers respond to ping. I tested a couple of remote IPs from random providers and they responded.

This server (167.88.112.78) does not respond. Are you sure it's still a valid config? Can you download the configs from your provider and compare?

**Comment by am-ghub** [comment]
I'm running into the same problem, I also get a TLS error then the process restarts:

Logs: 

> Using OpenVPN provider: IPVANISH
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Sat Mar 28 12:16:17 2020 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Sat Mar 28 12:16:17 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
Sat Mar 28 12:16:17 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
Sat Mar 28 12:16:17 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Mar 28 12:16:17 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]2.58.12.12:443
Sat Mar 28 12:16:17 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sat Mar 28 12:16:17 2020 UDP link local: (not bound)
Sat Mar 28 12:16:17 2020 UDP link remote: [AF_INET]2.58.12.12:443
Sat Mar 28 12:17:17 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sat Mar 28 12:17:17 2020 TLS Error: TLS handshake failed
Sat Mar 28 12:17:17 2020 SIGUSR1[soft,tls-error] received, process restarting
Sat Mar 28 12:17:17 2020 Restart pause, 5 second(s)
Sat Mar 28 12:17:22 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Mar 28 12:17:22 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]2.58.12.12:443
Sat Mar 28 12:17:22 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]2.58.12.12:443
Sat Mar 28 12:17:22 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sat Mar 28 12:17:22 2020 UDP link local: (not bound)
Sat Mar 28 12:17:22 2020 UDP link remote: [AF_INET]2.58.12.12:443
Sat Mar 28 12:18:22 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sat Mar 28 12:18:22 2020 TLS Error: TLS handshake failed
Sat Mar 28 12:18:22 2020 SIGUSR1[soft,tls-error] received, process restarting
Sat Mar 28 12:18:22 2020 Restart pause, 5 second(s)
Sat Mar 28 12:18:27 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Mar 28 12:18:27 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]2.58.12.12:443
Sat Mar 28 12:18:27 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]2.58.12.12:443
Sat Mar 28 12:18:27 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sat Mar 28 12:18:27 2020 UDP link local: (not bound)
Sat Mar 28 12:18:27 2020 UDP link remote: [AF_INET]2.58.12.12:443

I've checked network connectivity from within the container and can ping google.com.  
I can't ping the link remote (2.58.12.12).  
I've also verified my username and password.

I'm running on openmediavault and here is the config I'm using:

> [
    {
        "Id": "d7f876c82457c8b8ef1efa97040944c4f9b68bf67e9cc6f1d6443d76d1d8add7",
        "Created": "2020-03-28T12:16:16.117030192Z",
        "Path": "dumb-init",
        "Args": [
            "/etc/openvpn/start.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 8767,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-03-28T12:16:17.825781477Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2020-03-28T12:21:17.830404216Z",
                        "End": "2020-03-28T12:21:18.186045116Z",
                        "ExitCode": 0,
                        "Output": "PING google.com (216.58.211.46) 56(84) bytes of data.\n64 bytes from muc03s14-in-f14.1e100.net (216.58.211.46): icmp_seq=1 ttl=51 time=29.2 ms\n\n--- google.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 29.200/29.200/29.200/0.000 ms\nNetwork is up\n"
                    },
                    {
                        "Start": "2020-03-28T12:26:18.270756204Z",
                        "End": "2020-03-28T12:26:18.612104397Z",
                        "ExitCode": 0,
                        "Output": "PING google.com (216.58.211.238) 56(84) bytes of data.\n64 bytes from mad01s24-in-f238.1e100.net (216.58.211.238): icmp_seq=1 ttl=51 time=29.3 ms\n\n--- google.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 29.382/29.382/29.382/0.000 ms\nNetwork is up\n"
                    },
                    {
                        "Start": "2020-03-28T12:31:18.6938583Z",
                        "End": "2020-03-28T12:31:18.941312084Z",
                        "ExitCode": 0,
                        "Output": "PING google.com (216.58.211.46) 56(84) bytes of data.\n64 bytes from mad08s05-in-f14.1e100.net (216.58.211.46): icmp_seq=1 ttl=51 time=28.8 ms\n\n--- google.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 28.832/28.832/28.832/0.000 ms\nNetwork is up\n"
                    }
                ]
            }
        },
        "Image": "sha256:e9e00e9eb44c158014ef4c2e1faa3a5b6d84e4d994e10c6e94466d0f569ad407",
        "ResolvConfPath": "/var/lib/docker/containers/d7f876c82457c8b8ef1efa97040944c4f9b68bf67e9cc6f1d6443d76d1d8add7/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/d7f876c82457c8b8ef1efa97040944c4f9b68bf67e9cc6f1d6443d76d1d8add7/hostname",
        "HostsPath": "/var/lib/docker/containers/d7f876c82457c8b8ef1efa97040944c4f9b68bf67e9cc6f1d6443d76d1d8add7/hosts",
        "LogPath": "/var/lib/docker/containers/d7f876c82457c8b8ef1efa97040944c4f9b68bf67e9cc6f1d6443d76d1d8add7/d7f876c82457c8b8ef1efa97040944c4f9b68bf67e9cc6f1d6443d76d1d8add7-json.log",
        "Name": "/eloquent_blackwell",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": [
            "03bfd3fbf3ca5f5ee27ad99e2f05d0e50b3306f9fb85ee7b959e3fb6b7e45dff"
        ],
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro",
                "/allshares/downloads:/data:rw",
                "/allshares/backups/docker/openvpn_transmission:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "8888/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8888"
                    }
                ],
                "9091/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "9091"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [
                "NET_ADMIN"
            ],
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Sysctls": {
                "net.ipv6.conf.all.disable_ipv6": "0"
            },
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/ea7bac8f727ba793d1d5bca35d26c68a87432aad8a33d4d4ce80fcdec92f08d4-init/diff:/var/lib/docker/overlay2/316dfe53982d516eeef4711e77ce9df82270408b4a9e81888eea55d98e095429/diff:/var/lib/docker/overlay2/778a5bb3c1571cedf9eaac3540cf120998c8c531f320c9fa27af478dbd0b4ef2/diff:/var/lib/docker/overlay2/ebf6e1792db0433bac628c250d4221ef782b2b593d692d6d0c4e5b2db1f8ab99/diff:/var/lib/docker/overlay2/1047c588c7417a75a18ab7fbab8154e070b4f319710d3885b63e22dc8ff20d2c/diff:/var/lib/docker/overlay2/d34a3315175c908426469e41eae2abb08ddecd48a57621998af1e652972a79a4/diff:/var/lib/docker/overlay2/19c04bb5eb1a377bf3c6c91bda2642b7fa621480867551359d94dab959ce0a8b/diff:/var/lib/docker/overlay2/3ed05c581397b235309e59835653a831ede761418924a785b5342886b76791a8/diff:/var/lib/docker/overlay2/316f73a93b56ee4d2b3917c5e13218366f9fd6bc51a5bc5d66ec69c4e7bcb778/diff:/var/lib/docker/overlay2/25c0aa76bffbe80083bde040d71d8d9093ffa19cf133442a48bed26f3c16449a/diff",
                "MergedDir": "/var/lib/docker/overlay2/ea7bac8f727ba793d1d5bca35d26c68a87432aad8a33d4d4ce80fcdec92f08d4/merged",
                "UpperDir": "/var/lib/docker/overlay2/ea7bac8f727ba793d1d5bca35d26c68a87432aad8a33d4d4ce80fcdec92f08d4/diff",
                "WorkDir": "/var/lib/docker/overlay2/ea7bac8f727ba793d1d5bca35d26c68a87432aad8a33d4d4ce80fcdec92f08d4/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/allshares/downloads",
                "Destination": "/data",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/allshares/backups/docker/openvpn_transmission",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "42d444c5a1b7",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8888/tcp": {},
                "9091/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "TRANSMISSION_ENCRYPTION=1",
                "TRANSMISSION_ALT_SPEED_UP=50",
                "TRANSMISSION_HOME=/data/transmission-home",
                "TRANSMISSION_RATIO_LIMIT=2",
                "TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false",
                "TRANSMISSION_ALT_SPEED_TIME_ENABLED=false",
                "TRANSMISSION_PEER_PORT_RANDOM_ON_START=false",
                "TRANSMISSION_MAX_PEERS_GLOBAL=200",
                "TRANSMISSION_WATCH_DIR_ENABLED=true",
                "TRANSMISSION_SPEED_LIMIT_DOWN=100",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TRANSMISSION_SEED_QUEUE_ENABLED=false",
                "TRANSMISSION_SPEED_LIMIT_UP=100",
                "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false",
                "TRANSMISSION_UPLOAD_LIMIT=100",
                "TRANSMISSION_RPC_PORT=9091",
                "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=",
                "TRANSMISSION_CACHE_SIZE_MB=4",
                "TRANSMISSION_ALT_SPEED_TIME_DAY=127",
                "PUID=1000",
                "TRANSMISSION_BIND_ADDRESS_IPV4=0.0.0.0",
                "WEBPROXY_PORT=8888",
                "TRANSMISSION_RPC_URL=/transmission/",
                "TRANSMISSION_INCOMPLETE_DIR_ENABLED=true",
                "TRANSMISSION_WATCH_DIR=/data/watch",
                "LOCAL_NETWORK=192.168.0.0/24",
                "DOCKER_LOG=false",
                "TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0",
                "TRANSMISSION_PEER_ID_TTL_HOURS=6",
                "TRANSMISSION_INCOMPLETE_DIR=/data/incomplete",
                "ENABLE_UFW=false",
                "TRANSMISSION_PEER_CONGESTION_ALGORITHM=",
                "TRANSMISSION_WEB_HOME=",
                "TRANSMISSION_START_ADDED_TORRENTS=true",
                "TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true",
                "TRANSMISSION_MESSAGE_LEVEL=2",
                "TRANSMISSION_RPC_HOST_WHITELIST=",
                "TRANSMISSION_DOWNLOAD_LIMIT=100",
                "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=false",
                "TRANSMISSION_SEED_QUEUE_SIZE=10",
                "TRANSMISSION_DOWNLOAD_DIR=/data/completed",
                "TRANSMISSION_PEER_LIMIT_GLOBAL=200",
                "CREATE_TUN_DEVICE=true",
                "TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false",
                "UFW_EXTRA_PORTS=",
                "TRANSMISSION_BLOCKLIST_URL=http://www.example.com/blocklist",
                "TRANSMISSION_PEER_PORT_RANDOM_HIGH=65535",
                "TRANSMISSION_PEER_SOCKET_TOS=default",
                "TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0",
                "TRANSMISSION_RPC_PASSWORD=password",
                "TRANSMISSION_ALT_SPEED_DOWN=50",
                "TRANSMISSION_UTP_ENABLED=true",
                "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false",
                "TRANSMISSION_RPC_WHITELIST_ENABLED=false",
                "TRANSMISSION_PREFETCH_ENABLED=1",
                "TRANSMISSION_UPLOAD_LIMIT_ENABLED=0",
                "TRANSMISSION_PEER_PORT_RANDOM_LOW=49152",
                "TRANSMISSION_PEX_ENABLED=true",
                "TRANSMISSION_UMASK=2",
                "HEALTH_CHECK_HOST=google.com",
                "TRANSMISSION_QUEUE_STALLED_MINUTES=30",
                "UFW_DISABLE_IPTABLES_REJECT=false",
                "TRANSMISSION_BIND_ADDRESS_IPV6=::",
                "TRANSMISSION_LPD_ENABLED=false",
                "OPENVPN_PASSWORD=<MYCONFIRMEDPASSWORD_REDACTED>",
                "TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false",
                "TRANSMISSION_BLOCKLIST_ENABLED=false",
                "TRANSMISSION_IDLE_SEEDING_LIMIT=30",
                "OPENVPN_USERNAME=<MYCONFIRMEDUSERNAME_REDACTED>",
                "TRANSMISSION_RENAME_PARTIAL_FILES=true",
                "UFW_ALLOW_GW_NET=false",
                "TRANSMISSION_RPC_ENABLED=true",
                "TRANSMISSION_ALT_SPEED_TIME_END=1020",
                "TRANSMISSION_WEB_UI=",
                "TRANSMISSION_RATIO_LIMIT_ENABLED=false",
                "TRANSMISSION_DHT_ENABLED=true",
                "TRANSMISSION_RPC_WHITELIST=127.0.0.1",
                "DROP_DEFAULT_ROUTE=",
                "TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5",
                "TRANSMISSION_PORT_FORWARDING_ENABLED=false",
                "TRANSMISSION_WATCH_DIR_FORCE_GENERIC=false",
                "TRANSMISSION_PREALLOCATION=1",
                "TRANSMISSION_QUEUE_STALLED_ENABLED=true",
                "OPENVPN_PROVIDER=IPVANISH",
                "TRANSMISSION_PEER_LIMIT_PER_TORRENT=50",
                "GLOBAL_APPLY_PERMISSIONS=true",
                "TRANSMISSION_ALT_SPEED_ENABLED=false",
                "TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=true",
                "TRANSMISSION_PEER_PORT=51413",
                "TRANSMISSION_RPC_USERNAME=username",
                "WEBPROXY_ENABLED=true",
                "PGID=100",
                "TRANSMISSION_ALT_SPEED_TIME_BEGIN=540",
                "DEBIAN_FRONTEND=noninteractive",
                "TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=false",
                "TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=14"
            ],
            "Cmd": [
                "dumb-init",
                "/etc/openvpn/start.sh"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "/etc/scripts/healthcheck.sh"
                ],
                "Interval": 300000000000
            },
            "Image": "haugene/transmission-openvpn:latest",
            "Volumes": {
                "/config": {},
                "/data": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "omv_docker_extra_args": "--cap-add=NET_ADMIN -d -p 9091:9091 -p 8888:8888 --sysctl net.ipv6.conf.all.disable_ipv6=0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "98d0da53b9cdc83141215011fe91271b1d29b1f4b93309013abe1f4fc3e82461",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8888/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8888"
                    }
                ],
                "9091/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "9091"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/98d0da53b9cd",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "aacd5eeeee797031e26eb8a1019e8f7c316658173cfd2c532c0149c07c5d2110",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "7a15f156663556c6d5397b1d70dc37c5f08e91fb82394773e0415f7bb739206c",
                    "EndpointID": "aacd5eeeee797031e26eb8a1019e8f7c316658173cfd2c532c0149c07c5d2110",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

Any help is really appreciated.

**Comment by haugene** [comment]
I think both your issues relates to outdated configs, or use of invalid config.
For your case @am-ghub I see you're using IPVANISH and the configs there was updated very recently in #1101.

Can you try pulling the image to make sure you have the newest version? `docker pull haugene/docker-transmission-openvpn` and then try again? If that doesn't work, the default .ovpn file might point to a non-working server. In that case you can try to set `OPENVPN_CONFIG` to any of the configs found in this list: https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/ipvanish (use the name of the file without .ovpn).

For example: `OPENVPN_CONFIG=ipvanish-NL-Amsterdam-ams-c05`. I also see from the list that some of the configs come from the last update, and some are from an update in September. Hopefully the old ones are still valid and that's why they're still there, otherwise we should clean up a bit.

Test it out and report back if it works or not.

**Comment by pkishino** [comment]
no further update,closing as outdated config most likely cause
