### ISSUE TITLE
Cannot find OPENVPN_CONFIG. 

### ISSUE THREAD

**Issue by HanSemmelink** [haugene/docker-transmission-openvpn#1084]
i am trying to change the vpn from PIA to NordVPN, but i am not able to change the OPENVPN_CONFIG.. i am pretty new to this and getting very confused with all the coding.. haha

I am using Unraid 6.8.3 and I installed it from the apps store. 
Some help would be highly appreciated

**Comment by edgd1er** [comment]
Hi @HanSemmelink,

3 vars need to be set for the nordvpn update script to run properly.
Well, I guess you are looking for the documentation. .  https://haugene.github.io/docker-transmission-openvpn/nordvpn-script/

**Comment by ericrousse** [comment]
We also need to remove the variable OPENVPN_CONFIG, right ?
