### ISSUE TITLE
Surfshark VPN

### ISSUE THREAD

**Issue by embedded-crypto** [haugene/docker-transmission-openvpn#1088]
**Which provider?**
surfshark

**Where are the configs?**
https://account.surfshark.com/api/v1/server/configurations

**Comment by mehulboricha** [comment]
I have added all the latest configurations of Surfshark a few days ago and submitted a pull request for the same. Waiting for @haugene  to approve it.

Meanwhile, if you want to give it a try then it is in dev branch here: https://github.com/mehulboricha/docker-transmission-openvpn/tree/dev

**Comment by haugene** [comment]
It's now merged to master and also in the newest tagged release 2.11
Check it out and close the issue if everything works as it should :)
