### ISSUE TITLE
HDD never spindown

### ISSUE THREAD

**Issue by Gio-dot** [haugene/docker-transmission-openvpn#1089]
**Describe the problem**
I'm using tranmission in docker on rpi3b+ running updated OMV 4. If transmission container is running, even when there are no torrents, HDD never goes in spindown. If i stop the Transmission container, hdd regularly goes in sleep mode.

**Add your docker run command**

**Logs**

**Host system:**

**Comment by Gio-dot** [comment]
Is it possible that i am the only one with this issue?

**Comment by ajkblue** [comment]
Have you tried [these steps](https://haugene.github.io/docker-transmission-openvpn/known-issues/#reach_sleep_or_hybernation_on_your_host_if_no_torrents_are_active) from the known-issues page? It seems to be an issue with Transmission.  According to that  page, try adding `-e "TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false"` argument when you run the container.
