### ISSUE TITLE
Add HTTP proxy support

### ISSUE THREAD

**Issue by atmosx** [haugene/docker-transmission-openvpn#109]
I have a similar setup on an RPi. It's a great idea to dockerize this. Since we're routing all the traffic through VPN it would be a good idea to add a lightweight HTTP proxy.

**Comment by haugene** [comment]
The readme describes how to use nginx as a proxy and a preconfigured image is provided as well: 
https://hub.docker.com/r/haugene/transmission-openvpn-proxy/

Dockerfiles are available both for x64 and RPi:
https://github.com/haugene/docker-transmission-openvpn/tree/master/proxy

What exactly are you looking for here?

**Comment by ouafnico** [comment]
Maybe he means a Squid proxy on the docker? It could be great!

**Comment by atmosx** [comment]
Exactly. I mean an HTTP proxy, not a reverse proxy. I had something like privoxy/polipo in mind, that will allow users to also browse with some privacy - except from downloading torrents.

**Comment by haugene** [comment]
Aha! Yes, that would be a neat feature :+1: 

Could configure/activate it using environment variables as all the other features, or provide it on a separate tag. Anyways, a good suggestion!

**Comment by haugene** [comment]
Gotta love Docker! I was playing around with this and figured it should be possible to make something from the container networking mode. And indeed it is :smile: 

You can make any container join the network stack of another container by specifying --network container:<name|id> (or --net=container:<name|id> for older docker versions). See the [run reference](https://docs.docker.com/engine/reference/run/#/network-container).

So if you start the transmission-openvpn container and also specify a port bind for privoxy (e.g. -p 8118:8118) then it will be set up in the stack and you can find some privoxy image on hub and just hook it in to your existing network.

I testet with a couple of images and it worked like a charm! Here's one with tor and privoxy:
docker run -d --name tor-privoxy --net=container:<name|id> rdsubhas/tor-privoxy-alpine

Run that one, and it should be good to go :+1: But remember to bind the ports you need when starting the openvpn container. And also set the LOCAL_NETWORK environment variable to allow the proxied traffic to "escape" the container.

Let me know how it goes. Should probably include a section in the README on this as well...

**Comment by haugene** [comment]
I'll conclude that my previous answer is the recommended way to use a proxy with this container and close this issue. It leverages the docker platform instead of creating more custom components, introduces flexibility in which proxy to follows separation of concerns principle. It makes it all more maintainable to not bundle more running services into this container.
