### ISSUE TITLE
Creating Torrent

### ISSUE THREAD

**Issue by Fizpop91** [haugene/docker-transmission-openvpn#1096]
This isnt really an issue, I just needed help and wasnt sure where else to ask for this specific query.

I need to create a torrent, which of course can be done in the Transmission app, but not in the Transmission web gui.
Is it possible to create a torrent in the app but seed it from the docker transmission web gui?

**Comment by haugene** [comment]
Well I guess that if you create a torrent somewhere you could just add it in this client and it would download the torrent and then seed it? Or do you want to never seed from the place you create it?

Could you just copy the torrent data to the right location in the container/mount and then add the torrent and point to it? It should verify the local data is there and start seeding?

As you see I'm not sure here, but I expect it should be possible. I'll leave this issue for a little while in case anybody else have some ideas. But it's not an issue with this image so I will close it at some point.

**Comment by Fizpop91** [comment]
That will work, but the torrent is about 300GB, would prefer not to download 300GB unnecessarily. I want to seed it from my Synology.
Ah, that makes sense, maybe ill give that a try.
I understand, thanks for the help anyway!

**Comment by noahkiss** [comment]
I've done this and like @haugene mentioned, the easiest way is to move (or copy, or hardlink) the files you'd like to seed to your /data/completed location. Once you've done that, upload the .torrent file to transmission's web ui and it'll verify your local files and then begin seeding. You won't have to re-download anything.

**Comment by pkishino** [comment]
Please close this, not an issue

**Comment by haugene** [comment]
Doing it. Good luck @Fizpop91 and thanks for confirming @noahkiss

**Comment by Fizpop91** [comment]
Thanks for the help :)

**Comment by emk2203** [comment]
I don't know if this is possible only with the current version, but the easiest way is to enter the container with

```bash
docker exec -it $USER-transmission-1 bash

/usr/local/bin/transmission-create -o /data/watch/torrentname.torrent -c "My Comment Here" -t "Tracker URI" /data/completed/<data of torrent, directory or file>

exit
```

For transmission to see it, you need to fix permissions and ownership of the torrent file.
