### ISSUE TITLE
Random IPVanish configs are not found

### ISSUE THREAD

**Issue by callahan22** [haugene/docker-transmission-openvpn#1097]
**Description of problem**
As of perhaps a week ago (can't be sure as just noticed issue and have known that things were not downloading for maybe a week but not gotten round to looking at issue until now).

The issue is that 2 of the 3 IPVanish configs I use are not found when the transmission-vpn container fires up. The 3 I have set to random select from are:

`- OPENVPN_CONFIG="ipvanish-NL-Amsterdam-ams-a03,ipvanish-NL-Amsterdam-ams-a05,ipvanish-NL-Amsterdam-ams-a12"`

When transmission-vpn fires up, the logs read, (only showing the errors here for sake of brevity):

```
Using OpenVPN provider: IPVANISH
3 servers found in OPENVPN_CONFIG, "ipvanish-NL-Amsterdam-ams-a03 chosen randomly
Supplied config "ipvanish-NL-Amsterdam-ams-a03.ovpn could not be found.
...
Using OpenVPN provider: IPVANISH
3 servers found in OPENVPN_CONFIG, "ipvanish-NL-Amsterdam-ams-a12 chosen randomly
Supplied config "ipvanish-NL-Amsterdam-ams-a03.ovpn could not be found.
...
3 servers found in OPENVPN_CONFIG, ipvanish-NL-Amsterdam-ams-a05 chosen randomly
Starting OpenVPN using config ipvanish-NL-Amsterdam-ams-a05.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.100.0/24 via 172.18.0.1 dev eth0
Sat Mar 28 14:18:03 2020 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
.........
```
Looking in your master branch, (docker-transmission-openvpn/openvpn/ipvanish/ipvanish-NL-Amsterdam-ams-a03.ovpn), this config seems to be correct with the latest version I have just downloaded from IPVanish so I'm really not sure of the issue. If the error had been that the connection failed, I would have put it down to load on the VPN server at IPVanish end but the error message suggests that this is more down to the config not being found in the base build of transmission-vpn.

**Host system**
Ubuntu Linix 18.04

**Comment by ipatch** [comment]
just started noticing this issue as well last night earlier today after i had to reboot my box late last night.

starting the container in the foreground with the below command

```shell
 docker run \--cap-add=NET_ADMIN \                                                                                                                                                      should-You | 0 < 13:12:10
    -v /opt/docker/pg/pg-torrential/data:/data \
    -v $ETC_LOCALTIME:/etc/localtime:ro \
    --env-file /opt/docker/pg/pg-torrential/DockerEnv \
    -e CREATE_TUN_DEVICE=true \
    --log-driver json-file \
    --log-opt max-size=10m \
    -p 9091:9091 \
    --dns 1.1.1.1 --dns 1.0.0.1 \
    haugene/transmission-openvpn:latest
```

yields the below output

```shell
Using OpenVPN provider: ipvanish
3 servers found in OPENVPN_CONFIG, ipvanish-NL-Amsterdam-ams-a12" chosen randomly
Supplied config ipvanish-NL-Amsterdam-ams-a12".ovpn could not be found.
Using default OpenVPN gateway for provider ipvanish
Setting OPENVPN credentials...
adding route to local network 10.0.1.0/24 via 172.17.0.1 dev eth0
Sat Mar 28 13:12:38 2020 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Sat Mar 28 13:12:38 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
Sat Mar 28 13:12:38 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
Sat Mar 28 13:12:38 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Mar 28 13:12:38 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]X.X.X.X:443
Sat Mar 28 13:12:38 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sat Mar 28 13:12:38 2020 UDP link local: (not bound)
Sat Mar 28 13:12:38 2020 UDP link remote: [AF_INET]X.X.X.X:443
Sat Mar 28 13:13:38 2020 [UNDEF] Inactivity timeout (--ping-exit), exiting
Sat Mar 28 13:13:38 2020 SIGTERM[soft,ping-exit] received, process exiting
```

**Comment by ilike2burnthing** [comment]
Configs were updated yesterday - https://www.ipvanish.com/software/configs/configs.zip

Last person to update them here was @cjjwisniewski from 12/9/19 - https://github.com/haugene/docker-transmission-openvpn/pull/971

**Comment by ipatch** [comment]
updated my start command to specify the path to a single configuration file, and the container started as it should, but using the default to openvpn configuration within a `DockerEnv` file presently does not work for me.

```shell
OPENVPN_CONFIG=default
```

nor did specifying a path to configuration files within the `DockerEnv` file such as,

```
OPENVPN_CONFIG="./ipvanish-configs/ipvanish-NL-Amsterdam-ams-a03,./ipvanish-configs/ipvanish-NL-Amsterdam-ams-a05,./ipvanish-configs/ipvanish-NL-Amsterdam-ams-a12"
```

did not work, _not entirely sure if i setup that configuration file properly or not_

and I did just download the new **configs.zip** from ipvanish earlier today.

**Comment by callahan22** [comment]
Think I may have just spotted the problem. Up until now, this env option has always worked:

`- OPENVPN_CONFIG="ipvanish-NL-Amsterdam-ams-a03,ipvanish-NL-Amsterdam-ams-a05,ipvanish-NL-Amsterdam-ams-a12"`

But I think an update of docker-ce has changed how that env option is being interpreted. @ipatch - Notice how the error reads either:

`Supplied config "ipvanish-NL-Amsterdam-ams-a03.ovpn could not be found.`
or
`Supplied config ipvanish-NL-Amsterdam-ams-a12".ovpn could not be found.`

Note the missing " at either ends of those? Notice how only when transmision picks the middle server, it works? I think something changed in the latest version of docker as if you now add them as so:

`- OPENVPN_CONFIG=ipvanish-NL-Amsterdam-ams-a03,ipvanish-NL-Amsterdam-ams-a05,ipvanish-NL-Amsterdam-ams-a12`

it seems to resolve the issue.

Can you confirm at your end?
