### ISSUE TITLE
How to configure on Raspberry Pi 3 ?

### ISSUE THREAD

**Issue by chicungunya** [haugene/docker-transmission-openvpn#1098]
Hello,
I'm on a Raspberry Pi 3 with image of OMV 4. I think I tried everything but doesn't work. 
You can check here my configuration : https://pastebin.com/TKixMYPT (I have hidden my credentials id of my vpn) (SURFSHARK VPN)
And there is my error : https://pastebin.com/9jCYmmZc

Can you please help ? 

thanks a lot

Edit : I tried with NORDVPN and there is my error : https://pastebin.com/Vf8v2Fmg

**Comment by pkishino** [comment]
Yes, your authentication failed because it cannot create the credentials.. this is an issue with omv, please check how to either give write permission to process or such

**Comment by haugene** [comment]
You've mounted both the volumes as read-only. That won't work. The container needs to be able to write both config and data.

```
 "Binds": [
                "/sharedfolders/WD:/config:ro",
                "/sharedfolders/WD/Films:/data:ro",
```
