### ISSUE TITLE
Feature: Bind transmission ipv4 address to OpenVPN client IP

### ISSUE THREAD

**Issue by ianneub** [haugene/docker-transmission-openvpn#11]
When starting up transmission we should bind it to the IP given to us from PIA. This should prevent leaking our IP.

The transmission setting is `bind-address-ipv4`.

## Script to get the IP of `tun0`:
```
# ifconfig tun0 | sed -n '2 p' | awk '{print $2}' | cut -d: -f2
10.181.1.6
```
## Things to consider
* [ ] What if the IP changes?
* [x] Will the interface always be `tun0`?

**Comment by haugene** [comment]
Ref: https://openvpn.net/index.php/open-source/documentation/howto.html
> First, define a static unit number for our tun interface, so that we will be able to refer to it later in our firewall rules:
>
>dev tun0

Looks like we can update the config files with "dev tun0" instead of "dev tun" to statically set it...

**Comment by haugene** [comment]
If the IP changes because the interface went down and came up again, we should be OK. Transmission will be killed on interface down, and restarted on interface up.

So, can the IP change without interface going up and down?
