### ISSUE TITLE
Login page before comming to tranmission page

### ISSUE THREAD

**Issue by euronck** [haugene/docker-transmission-openvpn#110]
haugene awesome job at the container and answering questions. 
If I punched a hole in the firewall so i can access the page from the internet. If I want to have a username and password on the page to protect it from unauthorized users how can i do that?

for example when i go to http://mydns:9090 it displays a page saying username and password before showing the transmission torrent page.

**Comment by haugene** [comment]
Thanks :)

Transmission has support for this. Set environment variable TRANSMISSION_RPC_AUTHENTICATION_REQUIRED to true and then set TRANSMISSION_RPC_USERNAME and TRANSMISSION_RPC_PASSWORD to whatever you want.

**Comment by bshuler** [comment]
docker run --name haugene_transmission-openvpn  -d --privileged  \
              -v /mount/torrents/:/data \
              -e "OPENVPN_PROVIDER=TorGuard" \
              -e "OPENVPN_CONFIG=USA-ATLANTA" \
              -e "OPENVPN_USERNAME=user" \
              -e "OPENVPN_PASSWORD=pass" \
              -e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true" \
              -e "TRANSMISSION_RPC_USERNAME=user" \
              -e "TRANSMISSION_RPC_PASSWORD=pass" \
              -p 9091:9091 \
              haugene/transmission-openvpn:latest

**Comment by haugene** [comment]
Sooo, I'm going to close this one soon if you're not having any more issues?

**Comment by DFsharp** [comment]
Hey, I'm having a similar issue and didn't want to open a new one. "rpc-authentication-required" is always set to false for me, even if I set it in the environment variable. Am I missing something? I'm using:

```
sudo docker run --name transmission_openvpn --privileged  -d\
 -v /mnt/pool:/data  \
-e "OPENVPN_PROVIDER=PIA"  \
-e "OPENVPN_USERNAME=user"  \
-e "OPENVPN_PASSWORD=pass" \
-e “OPENVPN_CONFIG=Netherlands” \
-e “TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true” \
-e "TRANSMISSION_RPC_ENABLED=true" \
-e "TRANSMISSION_RPC_USERNAME=user" \
-e "TRANSMISSION_RPC_PASSWORD=pass"  \
-e “TRANSMISSION_RPC_WHITELIST=127.0.0.1” \
-e "TRANSMISSION_DOWNLOAD_DIR=/data/downloads" \
-e "LOCAL_NETWORK=192.168.15.2/49" \
-e "TRANSMISSION_WATCH_DIR=/data/watch" \
-e "TRANSMISSION_WATCH_DIR_Enabled=true" \
-e "TRANSMISSION_ALT_SPEED_UP=100" \
-e "TRANSMISSION_ALT_SPEED_DOWN=2000" \
-p 9091:9091  haugene/transmission-openvpn
```
I appreciate your help!

**Comment by haugene** [comment]
First, FYI: You don't have to set some of the variables you're setting. They're the default value anyways. Looks to be: TRANSMISSION_RPC_ENABLED, TRANSMISSION_RPC_WHITELIST, TRANSMISSION_WATCH_DIR and TRANSMISSION_WATCH_DIR_Enabled

Second, what you're missing... Could it be that you're using other quotation marks for OPENVPN_CONFIG and TRANSMISSION_RPC_AUTHENTICATION_REQUIRED than all the others?

**Comment by DFsharp** [comment]
Well I'll be damned. Never edit config files in Google Docs! Thanks for the help!

**Comment by haugene** [comment]
Duly noted ;) np!
