### ISSUE TITLE
How to configure outer (host)firewall

### ISSUE THREAD

**Issue by DerBunteBall** [haugene/docker-transmission-openvpn#1112]
Hey all,

I have a short and silly question about how to configure the outer firewall.

With the term outer firewall I mean the host firewall.

I want to setup a Raspberry Pi 4 as box. If I'm right this would look like this:

1. RPI4 is the host and has isntalled Docker CE
2. Container runs in a NAT network on the host as default
3. When enabling UFW via ENVs (ENABLE_UFW) firwall is active in the container
4. The host has no firewall at this point. It would be necessary to enable the firewall at the host and open all ports the container needs.

Is this correct or totally wrong?

Best Regards

PS: Sorry for my bad english

**Comment by mgithens1** [comment]
A VPN client creates a new adapter that establishes an outbound connection. So unless you have rules on the firewall to explicitly block outbound traffic, then by default the VPN will be "unaware" of the firewall.  The VPN provider controls any open ports that would allow for inbound connections, your router/firewall have no effect here.

**Comment by pkishino** [comment]
as @mgithens1 says, you do not need to configure anything on your end FW
