### ISSUE TITLE
IVACY Cert verify error

### ISSUE THREAD

**Issue by david-77** [haugene/docker-transmission-openvpn#1119]
IVACY Provider

Tested with LuxembourgTCP and LuxembourgUDP

Hi everyone,
Juste tried this image, and I fail to connect to Ivacy.
Here is the result with Luxembourd (TCP/UDP same error):

```

Sat Apr  4 21:33:35 2020 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.,
Sat Apr  4 21:33:35 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Sat Apr  4 21:33:35 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]94.242.230.4:53,
Sat Apr  4 21:33:35 2020 UDP link local: (not bound),
Sat Apr  4 21:33:35 2020 UDP link remote: [AF_INET]94.242.230.4:53,
Sat Apr  4 21:33:35 2020 VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: C=HK, ST=HK, L=HongKong, O=PureVPN, OU=IT, CN=PureVPN, name=PureVPN, emailAddress=mail@host.domain,
Sat Apr  4 21:33:35 2020 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed,
Sat Apr  4 21:33:35 2020 TLS_ERROR: BIO read tls_read_plaintext error,
Sat Apr  4 21:33:35 2020 TLS Error: TLS object -> incoming plaintext read error,
Sat Apr  4 21:33:35 2020 TLS Error: TLS handshake failed,
Sat Apr  4 21:33:35 2020 SIGUSR1[soft,tls-error] received, process restarting
```

I'm suprised to see "PureVPN" mentionned here.

And thanks for the docker image, it's a great work !!

**Comment by phenomenomenom** [comment]
I've had many issues connecting to Ivacy recently. It seems like their servers and documentation has been poorly maintained.

Try one of these servers:
- de2-ovpn-udp.dns2use.com
- de2-ovpn-tcp.dns2use.com
- nl-ovpn-udp2.dns2use.com
- nl-ovpn-tcp2.dns2use.com
- vlus-pa2-ovpn-udp.dns2use.com
- vlus-pa2-ovpn-tcp.dns2use.com

**Comment by david-77** [comment]
Thanks for this answer.
Can you tell me where did you get those vpn servers ?

**Comment by phenomenomenom** [comment]
I contacted Ivacy support and they suggested them.

I do find the self-signed certificates concerning, as well as the PureVPN reference. I had a similar message with some Ivacy servers.

**Comment by ToneStrife** [comment]
I am having troubles with IVACY too

**Comment by david-77** [comment]
Yes,
I contacted the support too, and they gave me the openvpn files. And after check, I see that the current openvpn files in the souce code are obsolete.

**Comment by antifarben** [comment]
> the current openvpn files in the souce code are obsolete

Could you please create a PR to fix [the ivacy ovpn files](https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/ivacy)?

**PS:** It seems that [the Czech server is missing as well](https://github.com/haugene/docker-transmission-openvpn/issues/1030).
