### ISSUE TITLE
Setup CI with shellcheck and other linters

### ISSUE THREAD

**Issue by wilmardo** [haugene/docker-transmission-openvpn#1123]
**Is your feature request related to a problem? Please describe.**
The shellscripts in the repository aren't concise in markup and style. Also best practices aren't always followed. 

**Describe the solution you'd like**
A CI job run for each commit and PR to fail and warn when something isn't like it should be.

**Additional context**
I am fluent in most of the CI environments (worked with Travis, Drone and Gitlab) but I need one enabled on this repository to get started.
@haugene do you have a preference? Travis was the go to for a long time on Github but Azure pipelines seem gaining in popularity since the Microsoft acquisition. I would suggest Travis since I know it well and it integrates nicely into PR's.

I am thinking of setting up:

- [ ] [koalaman/shellcheck](https://github.com/koalaman/shellcheck)
- [ ] [markdownlint/markdownlint](https://github.com/markdownlint/markdownlint)

Suggestions are welcome!

**Comment by haugene** [comment]
Great idea. I'm all for it. Using CircleCI for this project now and would gladly accept a PR on a check like that.

See project build: https://circleci.com/gh/haugene/docker-transmission-openvpn
And config is in the .circleci folder of the repo.

**Comment by wilmardo** [comment]
Ah cool, missed the current CI implementation haha
Will look into this hopefully next Friday :+1:

**Comment by miigotu** [comment]
I would suggest using GitHub actions, it's built into GitHub now and external CI/CD is no longer necessary.

**Comment by pkishino** [comment]
@wilmardo hey, had any chance to update this? would be great :)
