### ISSUE TITLE
IP Leaks / Broken Killswitch / Tunnel Hardening

### ISSUE THREAD

**Issue by a-n-d-i** [haugene/docker-transmission-openvpn#1127]
If I firewall off port 1194 on my Docker Host (or somewhere else down the line), the "killswitch" is not working / the container is using my local internet connection if the vpn is disrupted.

To reproduce:

Block VPN Traffic. In my setup this one does the trick, yours may vary. Be aware of the docker host / ufw issue (major unreleated concern btw, docker by default ignores host ufw rules, see for example https://github.com/chaifeng/ufw-docker). 

`iptables -I DOCKER-USER 1 -p udp --dport 1194 -j DROP`

OR just remove the VPN route, easier than messing with iptables

`route del -net 0.0.0.0 gw 10.8.8.1 netmask 128.0.0.0 dev tun0`

start the container, open a shell in the container, install w3m or similar and connect some "showmyip" service. (if you do this on a running container, stuff freezes and I was to impatient to wait for timeouts).

I guess the main problem is that relying on openvpns "tunnel down" trigger as a killswitch does not cover the time period until the connection times out. Also (almost) any traffic should be sent through the vpn to protect against possible vulnerabilities in transmission. 

### ufw config
It's pretty open, the container is allowed to initiate connections to pretty much anything.

> Logging: on (low)
> Default: deny (incoming), **allow (outgoing),** deny (routed)
> New profiles: skip
> 
> To                         Action      From
> --                         ------      ----
> 51413                      ALLOW IN    Anywhere                  
> 8888                       ALLOW IN    Anywhere                  
> 9091                       ALLOW IN    172.24.0.1                
> 9091                       ALLOW IN    192.168.0.0/16  

This should be much more restrictive, like deny all outgoing except vpn and name/dns. 
see: https://gist.github.com/Necklaces/18b68e80bf929ef99312b2d90d0cded2

### routing table

> Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
> 0.0.0.0         10.8.8.1        128.0.0.0       UG    0      0        0 tun0
> **0.0.0.0         172.24.0.1**      0.0.0.0         UG    0      0        0 eth0
> [...]

There is a default route for routing stuff without using the vpn tunnel. This might be removed (also depending on name/dns service I guess)

**Comment by ovizii** [comment]
Some of the advice on the page you linked sounds solid, I hope someone can help add those rules into this docker image. I'm just not all that sure about needing the IPs of the VPN servers that might make thigsn more difficult to support all these different VPN providers.

**Comment by pkishino** [comment]
@a-n-d-i while I havent had any issues myself (other setup) I agree with your concerns, feel free to create a PR and we can review it :)

**Comment by pkishino** [comment]
please take a look at the PR and add suggestions there

**Comment by ksurl** [comment]
fwiw this is my `openvpn-pre-start.sh`. you would replace the openvpn section with the IP of your vpn server. find that out with `nslookup fqdn` of the server you connect to. and repeat for as many IP's as it returns. 

```
#!/bin/bash

# reset
ufw --force reset

# default
ufw default deny incoming
ufw default deny outgoing

# localhost
ufw allow in on eth0 from 127.0.0.1 port 9091 proto tcp

# dns
ufw allow out 53

# openvpn
ufw allow out to $IP port 1194 proto udp

# tunnel
ufw allow out on tun0
ufw allow in on tun0 to any port 51413 proto tcp
```
