### ISSUE TITLE
Prevent data leakage when tunnel is down

### ISSUE THREAD

**Issue by jtrott** [haugene/docker-transmission-openvpn#1134]
I've knocked together a quick startup script that removes the default gateway before openvpn is started and instead puts in static routes to the openvpn server endpoints.
This prevents any data leaking out from transmission if the tunnel happens to come down.
The script is hard coded to proxpn but could easily be changed and made much simpler if it can be added to the start.sh, which already knows which random config it has picked.
Not sure how to do a pull, so just added it here in case it is useful for anyone.

```
#!/bin/sh

# grab the current router IP
ROUTER=`/sbin/ip route list | /bin/grep default | /bin/grep eth0 | /usr/bin/awk '{print $3}'`

# delete the default route
/sbin/ip route del default via $ROUTER dev eth0

# Loop through provided ovpn config files
for i in $(echo $OPENVPN_CONFIG | sed "s/,/ /g")
do
    # get the server address from the config file
    SERVER_ADDR=`/bin/grep remote /etc/openvpn/proxpn/${i}.ovpn | /usr/bin/awk '{print $2}' | /usr/bin/sort -fu`
    # set a static route for each server entry
    /sbin/ip route add $SERVER_ADDR via $ROUTER dev eth0
done
```

**Comment by Cycl** [comment]
Is this different from setting this env variable: DROP_DEFAULT_ROUTE=true ([used in this script](https://github.com/haugene/docker-transmission-openvpn/blob/0b6ab30294f139f06eaf74cf4808ec8c9c7e9db1/transmission/start.sh#L60))?

Though that one seems to do it after the tunnel is up, but before transmission is started.

I do also see the static route that this script also adds too - though not sure if that is done by default or through the ufw commands I run.

**Comment by jtrott** [comment]
That variable seems to try and drop the default route if transmission fails, I think.
I'd much rather lock down the container networking before transmission is even launched.

**Comment by pkishino** [comment]
Lets continue discussion on PR linked, please take a look
