### ISSUE TITLE
Port isn't open niether could i save a new one

### ISSUE THREAD

**Issue by Hamm3rhart** [haugene/docker-transmission-openvpn#1135]
**Describe the problem**
I don't know why but the ports are closed for docker/Transmission.
I opened 52072 UDP/TCP in my firewall, using
```
iptables -I INPUT -p udp --dport 52072 -j ACCEPT
iptables -I INPUT -p tcp --dport 52072 --syn -j ACCEPT
```
and I added an entry in my shorewall:
```
ACCEPT		net		$FW		tcp	52072
ACCEPT		net		$FW		udp	52072
```
(I know i don't need to do both but i did to be sure)
When i try to connect to through UDP/TCP to the real adrees of the server it works just fine. I opened the ports in the vpn as well. And i recognized that i can't change the default port of Transmission to my 52072. After a restart of the container it is the default port again and sometime when i open the network settings in transmission it says "Port 1".

**Add your docker run command**
```
docker run --cap-add=NET_ADMIN -d --dns 8.8.8.8 \
-v /opt/docker/transmission/data:/data \
-v /etc/localtime:/etc/localtime:ro \
-v /etc/openvpn/client/default.ovpn:/etc/openvpn/custom/default.ovpn \
-v /media/extern/Torrent:/extern \
-e CREATE_TUN_DEVICE=true \
-e OPENVPN_PROVIDER=CUSTOM \
-e OPENVPN_CONFIG=default \
-e OPENVPN_USERNAME=**NAME** \
-e OPENVPN_PASSWORD=**PW** \
-e WEBPROXY_ENABLED=false \
-e TRANSMISSION_WEB_UI=transmission-web-control \
-e TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
-e LOCAL_NETWORK=192.168.0.0/16 \
--log-driver json-file \
--log-opt max-size=10m \
-p 9091:9091 \
--name Torrent \
haugene/transmission-openvpn:latest
```

**Logs**
```
{"log":"Using OpenVPN provider: CUSTOM\n","stream":"stdout","time":"2020-04-12T16:22:45.852257306Z"}
{"log":"Starting OpenVPN using config default.ovpn\n","stream":"stdout","time":"2020-04-12T16:22:45.85304207Z"}
{"log":"Setting OPENVPN credentials...\n","stream":"stdout","time":"2020-04-12T16:22:45.853088426Z"}
{"log":"adding route to local network 192.168.0.0/16 via 172.17.0.1 dev eth0\n","stream":"stdout","time":"2020-04-12T16:22:46.634441495Z"}
{"log":"Sun Apr 12 18:22:47 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019\n","stream":"stdout","time":"2020-04-12T16:22:47.003807854Z"}
{"log":"Sun Apr 12 18:22:47 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08\n","stream":"stdout","time":"2020-04-12T16:22:47.00383137Z"}
{"log":"Sun Apr 12 18:22:47 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts\n","stream":"stdout","time":"2020-04-12T16:22:47.00432494Z"}
{"log":"Sun Apr 12 18:22:47 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]My IP\n","stream":"stdout","time":"2020-04-12T16:22:47.021480549Z"}
{"log":"Sun Apr 12 18:22:47 2020 UDP link local: (not bound)\n","stream":"stdout","time":"2020-04-12T16:22:47.021508806Z"}
{"log":"Sun Apr 12 18:22:47 2020 UDP link remote: [AF_INET]MyIP\n","stream":"stdout","time":"2020-04-12T16:22:47.021522816Z"}
{"log":"Sun Apr 12 18:22:47 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this\n","stream":"stdout","time":"2020-04-12T16:22:47.02705315Z"}
{"log":"Sun Apr 12 18:22:47 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-12T16:22:47.367392064Z"}
{"log":"Sun Apr 12 18:22:47 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-12T16:22:47.367418359Z"}
{"log":"Sun Apr 12 18:22:47 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-12T16:22:47.367425063Z"}
{"log":"Sun Apr 12 18:22:47 2020 [server] Peer Connection Initiated with [AF_INETMyIP\n","stream":"stdout","time":"2020-04-12T16:22:47.367574939Z"}
{"log":"Sun Apr 12 18:22:48 2020 TUN/TAP device tun0 opened\n","stream":"stdout","time":"2020-04-12T16:22:48.379408119Z"}
{"log":"Sun Apr 12 18:22:48 2020 do_ifconfig, tt-\u003edid_ifconfig_ipv6_setup=0\n","stream":"stdout","time":"2020-04-12T16:22:48.379428203Z"}
{"log":"Sun Apr 12 18:22:48 2020 /sbin/ip link set dev tun0 up mtu 1500\n","stream":"stdout","time":"2020-04-12T16:22:48.379433921Z"}
{"log":"Sun Apr 12 18:22:48 2020 /sbin/ip addr add dev tun0 local 10.35.0.81 peer 10.35.0.82\n","stream":"stdout","time":"2020-04-12T16:22:48.38052646Z"}
{"log":"Sun Apr 12 18:22:48 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1605 10.35.0.81 10.35.0.82 init\n","stream":"stdout","time":"2020-04-12T16:22:48.381404911Z"}
{"log":"Up script executed with tun0 1500 1605 10.35.0.81 10.35.0.82 init\n","stream":"stdout","time":"2020-04-12T16:22:48.495311963Z"}
{"log":"Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.35.0.81\n","stream":"stdout","time":"2020-04-12T16:22:48.49536655Z"}
{"log":"Using Transmission Web Control  UI, overriding TRANSMISSION_WEB_HOME\n","stream":"stdout","time":"2020-04-12T16:22:48.495516908Z"}
{"log":"Generating transmission settings.json from env variables\n","stream":"stdout","time":"2020-04-12T16:22:48.495526747Z"}
{"log":"sed'ing True to true\n","stream":"stdout","time":"2020-04-12T16:22:48.505596509Z"}
{"log":"\n","stream":"stdout","time":"2020-04-12T16:22:48.645424973Z"}
{"log":"-------------------------------------\n","stream":"stdout","time":"2020-04-12T16:22:48.645458683Z"}
{"log":"Transmission will run as\n","stream":"stdout","time":"2020-04-12T16:22:48.645467101Z"}
{"log":"-------------------------------------\n","stream":"stdout","time":"2020-04-12T16:22:48.645473597Z"}
{"log":"User name:   root\n","stream":"stdout","time":"2020-04-12T16:22:48.645499347Z"}
{"log":"User uid:    0\n","stream":"stdout","time":"2020-04-12T16:22:48.645507443Z"}
{"log":"User gid:    0\n","stream":"stdout","time":"2020-04-12T16:22:48.645513574Z"}
{"log":"-------------------------------------\n","stream":"stdout","time":"2020-04-12T16:22:48.645519551Z"}
{"log":"\n","stream":"stdout","time":"2020-04-12T16:22:48.645526251Z"}
{"log":"STARTING TRANSMISSION\n","stream":"stdout","time":"2020-04-12T16:22:48.645563988Z"}
{"log":"NO PORT UPDATER FOR THIS PROVIDER\n","stream":"stdout","time":"2020-04-12T16:22:48.646003683Z"}
{"log":"Transmission startup script complete.\n","stream":"stdout","time":"2020-04-12T16:22:48.646090834Z"}
{"log":"Sun Apr 12 18:22:48 2020 Initialization Sequence Completed\n","stream":"stdout","time":"2020-04-12T16:22:48.86662641Z"}
```
I got this quite often:
`{"log":"Sun Apr 12 22:12:18 2020 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #7709252 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings\n","stream":"stdout","time":"2020-04-12T20:12:18.247976966Z"}`

**Host system:** Ubuntu 18.04

**Comment by pkishino** [comment]
Please read the documentation..
If you set the port in the GUI these settings are currently not saved in restart. You need to specify it in the docker run command. Also, what is it You are trying to do? Reach transmission GUI from outside your home network?? This way isn’t safe at all I think, you haven’t even set any authentication, anyone could port scan and then access it from outside..

**Comment by Hamm3rhart** [comment]
Not the Port for the Webinterface. I mean the incoming port for Torrents.

**Comment by pkishino** [comment]
Yes.. please read the documentation, it describes how to set things like that..

**Comment by Hamm3rhart** [comment]
So if i add this to my config it should let the traffic through?
```
-e ENABLE_UFW=true
-e UFW_ALLOW_GW_NET=true
-e UFW_EXTRA_PORTS=52072
```

**Comment by pkishino** [comment]
What are you trying to do?? You want to make your peer port work? Does your
VPN support  this?

**Comment by Hamm3rhart** [comment]
Yes it does. Right after the start of the container the Port Check says "Port is open" but if i try the port check later again it says closed.
![6e227a64](https://user-images.githubusercontent.com/50116721/79158063-f5965e80-7dd5-11ea-9d62-7eab0cf9e3c8.png)

**Comment by pkishino** [comment]
Which VPN? Usually vpns only allow a specific port..
You shouldn’t have to do anything in your router (no port forward etc) or
adjust any other transmission setting if you use the right port for the VPN
server.

Does it say port open before you click test or after test? Also check logs
for any error

**Comment by Hamm3rhart** [comment]
Right after the start i go to Settings -> Network ->Test the Port=Port is Open
After some time i do the same again= Port is closed
I am using Torguard and after the start it works just well but after some time it stoped working.
On my Raspberry it works great with out any problems OpenVPN+Deluge (Without docker)
![grafik](https://user-images.githubusercontent.com/50116721/79163605-b3721a80-7ddf-11ea-85a5-151e0114980d.png)

Docker and the pi using diffrent ips (first 4 docker last 2 pi)

**Comment by pkishino** [comment]
anything in the log? both transmission and docker

**Comment by Hamm3rhart** [comment]
Last time i saw, no. But i think i found the cultrip. I am not allowed to change the port. If i never change the port , doesn't matter if changes saved or not. I will stay connectable (means port is open), Because after i change something as mentioned above, transmission want to use port 1 but that is not possible. Even if change the port to default and save the config, it stays at port 1. To Fix this i need to restart transmisson (the container). I also added this now to my docker command
```
-e ENABLE_UFW=true
-e UFW_ALLOW_GW_NET=true
-e UFW_EXTRA_PORTS=51413
```
I don't know what it does but it has something to do with the firewall so. Please tell if this is not necessary

**Comment by pkishino** [comment]
@haugene any idea?

**Comment by Muckoma** [comment]
Sorry wanted to piggy back off this topic but I am getting terrible upload speeds in my transmission container. I am using NORDVPN. I'm assuming Peer to Peer exchange should be enabled but I cannot seem to be open the port. Tried multiple things and followed the documentation.

**Comment by pkishino** [comment]
Sorry to tell you but nordvpn doesn’t allow port forwarding any longer, one
reason I switched to PrivateVPN..

**Comment by Muckoma** [comment]
Well that sucks. Thanks for the info @pkishino . Saves me time troubleshooting.

**Comment by Hamm3rhart** [comment]
Update: I just need to open the Settings, I don't even need to do anything their. Right after i opened the settings, i am not connectable anymore . But transmission still say port is open :/

**Comment by Hamm3rhart** [comment]
I checked both logs (Transmisson and Docker) but nothing there. Both say thats everything is fine. I only found this in the Docker log but way bofore ( 6< hours) my current problem.
```
{"log":"Tue Apr 14 23:32:59 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-14T21:32:59.350148171Z"}
{"log":"Tue Apr 14 23:32:59 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-14T21:32:59.3501731Z"}
{"log":"Tue Apr 14 23:32:59 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-14T21:32:59.35017725Z"}
{"log":"Wed Apr 15 00:33:00 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-14T22:33:00.630215964Z"}
{"log":"Wed Apr 15 00:33:00 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-14T22:33:01.08315178Z"}
{"log":"Wed Apr 15 00:33:00 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-14T22:33:01.08317876Z"}
{"log":"Wed Apr 15 01:33:00 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-14T23:33:00.235571348Z"}
{"log":"Wed Apr 15 01:33:00 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-14T23:33:00.251240521Z"}
{"log":"Wed Apr 15 01:33:00 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-14T23:33:00.251431909Z"}
{"log":"Wed Apr 15 02:33:01 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-15T00:33:01.329897164Z"}
{"log":"Wed Apr 15 02:33:01 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-15T00:33:01.329947837Z"}
{"log":"Wed Apr 15 02:33:01 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-15T00:33:01.329958114Z"}
{"log":"Wed Apr 15 03:33:01 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-15T01:33:01.303706887Z"}
{"log":"Wed Apr 15 03:33:01 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-15T01:33:01.316466213Z"}
{"log":"Wed Apr 15 03:33:01 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-15T01:33:01.316479757Z"}
{"log":"Wed Apr 15 04:33:01 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-15T02:33:01.682758901Z"}
{"log":"Wed Apr 15 04:33:01 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-15T02:33:01.682810572Z"}
{"log":"Wed Apr 15 04:33:01 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-15T02:33:01.682824279Z"}
{"log":"Wed Apr 15 05:33:02 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-15T03:33:02.083314327Z"}
{"log":"Wed Apr 15 05:33:02 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-15T03:33:02.083344314Z"}
{"log":"Wed Apr 15 05:33:02 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-15T03:33:02.083347862Z"}
{"log":"Wed Apr 15 06:33:02 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-15T04:33:02.208809885Z"}
{"log":"Wed Apr 15 06:33:02 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-15T04:33:02.208839124Z"}
{"log":"Wed Apr 15 06:33:02 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-15T04:33:02.208847626Z"}
{"log":"Wed Apr 15 07:33:02 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-15T05:33:02.730671804Z"}
{"log":"Wed Apr 15 07:33:02 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-15T05:33:02.730710199Z"}
{"log":"Wed Apr 15 07:33:02 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-15T05:33:02.73071862Z"}
{"log":"Wed Apr 15 08:33:02 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-15T06:33:02.609136851Z"}
{"log":"Wed Apr 15 08:33:02 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-15T06:33:02.609234172Z"}
{"log":"Wed Apr 15 08:33:02 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-15T06:33:02.609251647Z"}
{"log":"Wed Apr 15 09:33:02 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'\n","stream":"stdout","time":"2020-04-15T07:33:03.154411437Z"}
{"log":"Wed Apr 15 09:33:02 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'\n","stream":"stdout","time":"2020-04-15T07:33:03.318653982Z"}
{"log":"Wed Apr 15 09:33:02 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'\n","stream":"stdout","time":"2020-04-15T07:33:03.318673869Z"}
```

**Comment by Hamm3rhart** [comment]
Update2: When i run `transmission-remote -p 51413` to rebind the port, it works again (I am connectable now). So i think that the config breaks in some way when i open the settings. Btw. i checked in the `settings.json` , there was no port change at all.

**Comment by pkishino** [comment]
Well, you seem like the first to have this problem.. I can open my settings and port remains open, change port back and forth, still fine.
And where are you checking settings.json? Inside or outside?
Because currently the container does not persist settings between restart, no settings are written to the json.

**Comment by Muckoma** [comment]
@pkishino Are you having any issues with PIA and port forwarding? I am seeing this in my logs. I tried using France and Romania. 
`[2020-04-17 01:23:49.343] Couldn't connect socket 24 to 2a00:23c5:b408:c700:6c31:ef21:1171:7e1c, port 55851 (errno 99 - Cannot assign requested address) (net.c:290)
[2020-04-17 01:23:49.343] Couldn't connect socket 24 to 2a00:23c5:b408:c700:6c31:ef21:1171:7e1c, port 55851 (errno 99 - Cannot assign requested address) (net.c:290)
[2020-04-17 01:23:50.381] Couldn't connect socket 24 to 2601:241:c203:9480:2d60:c13a:aa00:d554, port 38691 (errno 99 - Cannot assign requested address) (net.c:290)
[2020-04-17 01:23:50.381] Couldn't connect socket 24 to 2601:241:c203:9480:2d60:c13a:aa00:d554, port 38691 (errno 99 - Cannot assign requested address) (net.c:290)
[2020-04-17 01:23:50.381] Couldn't connect socket 24 to 2002:4d5c:5f07::4d5c:5f07, port 43933 (errno 99 - Cannot assign requested address) (net.c:290)
[2020-04-17 01:23:50.382] Couldn't connect socket 24 to 2002:4d5c:5f07::4d5c:5f07, port 43933 (errno 99 - Cannot assign requested address) (net.c:290)
`

**Comment by pkishino** [comment]
This is a separate issue..I don’t use PIA so cannot say, but those are ipv6 addresses..

**Comment by pkishino** [comment]
@Hamm3rhart 
can you please post the docker command you are using now please?

**Comment by Hamm3rhart** [comment]
This is my command
```
docker run --cap-add=NET_ADMIN -d --dns 8.8.8.8 \
-v /opt/docker/transmission/data:/data \
-v /etc/localtime:/etc/localtime:ro \
-v /etc/openvpn/client/default.ovpn:/etc/openvpn/custom/default.ovpn \
-v /media/extern/Torrent:/extern \
-e CREATE_TUN_DEVICE=true \
-e OPENVPN_PROVIDER=CUSTOM \
-e OPENVPN_CONFIG=default \
-e OPENVPN_USERNAME=NAME \
-e OPENVPN_PASSWORD=PASSWORD \
-e WEBPROXY_ENABLED=false \
-e TRANSMISSION_WEB_UI=transmission-web-control \
-e TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
-e LOCAL_NETWORK=192.168.0.0/16 \
-e ENABLE_UFW=true \
-e UFW_ALLOW_GW_NET=true \
-e UFW_EXTRA_PORTS=51413 \
--log-driver json-file \
--log-opt max-size=10m \
-p 9091:9091 \
--name Torrent \
haugene/transmission-openvpn:latest
```

**Comment by pkishino** [comment]
Ok, lets try and go through your stuff:
1) You shouldnt have to do any changes to your firewall to add these ports as they are inside the vpn (in first post, the iptables stuff)
2) As we mentioned, changing settings in the gui is not persistant currently, set any settings in the docker run
3) the mute-replay warnings are nothing strange..they can be suppressed as per the warning message
4)
```
-e ENABLE_UFW=true
-e UFW_ALLOW_GW_NET=true
-e UFW_EXTRA_PORTS=52072
```
should not be needed either
5)
```
docker run --cap-add=NET_ADMIN -d --dns 8.8.8.8 \  
-v /opt/docker/transmission/data:/data \
-v /etc/localtime:/etc/localtime:ro \
-v /etc/openvpn/client/default.ovpn:/etc/openvpn/custom/default.ovpn \
-v /media/extern/Torrent:/extern \
-e CREATE_TUN_DEVICE=true \
-e OPENVPN_PROVIDER=CUSTOM \
-e OPENVPN_CONFIG=default \
-e OPENVPN_USERNAME=NAME \
-e OPENVPN_PASSWORD=PASSWORD \
-e WEBPROXY_ENABLED=false \ ### can be removed, default is false 
-e TRANSMISSION_WEB_UI=transmission-web-control \ 
-e TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \ ### you can add --mute-replay-warnings here
-e LOCAL_NETWORK=192.168.0.0/16 \
-e ENABLE_UFW=true \
-e UFW_ALLOW_GW_NET=true \
-e UFW_EXTRA_PORTS=51413 \
--log-driver json-file \
--log-opt max-size=10m \
-p 9091:9091 \
--name Torrent \
### --TRANSMISSION_PEER_PORT=51413 is the setting for port, try this
haugene/transmission-openvpn:latest
```

here you can see most variables you can set and default values
https://github.com/haugene/docker-transmission-openvpn/blob/master/DockerEnv

**Comment by ovizii** [comment]
piggy-backing onto this thread as I need a similar pointer like the others:

- using ghostpath VPN
- on the ghostpath website I enabled port forwarding and got a TCP port XXXXX assigned to me
- based on https://github.com/haugene/docker-transmission-openvpn/blob/master/DockerEnv I have added this line to my .env file: `TRANSMISSION_PEER_PORT=XXXXX` 
- starting transmission and going to settings - network - listening port => closed

Do I need to do anything else? Ghostpath VPN sad it might take up to 4h to open this port for me but about 8h have already passed...

here are all the .env variables I have enabled
```
OPENVPN_PROVIDER=GHOSTPATH
OPENVPN_USERNAME=myusername
OPENVPN_PASSWORD=mypassword
PUID=1000
PGID=1000
CREATE_TUN_DEVICE=true
TRANSMISSION_WEB_UI=combustion
OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
LOCAL_NETWORK=192.168.0.0/16
GLOBAL_APPLY_PERMISSIONS=false
TRANSMISSION_PEER_PORT=XXXXX
```

**Comment by rbrussell82** [comment]
I'm not sure if my issue is related or not, but I'm also using Torguard with port forwarding and have noticed for a few weeks that my upload speeds and connections are almost non-existent.

In the transmission web interface, it shows my port is open, but even trying to seed an Ubuntu iso image, I hardly get any connections.

**Comment by Hamm3rhart** [comment]
@pkishino it is working now. I did as you said and removed the Iptables and the entries in my firewall. Now i run this docker command:
```
docker run --cap-add=NET_ADMIN -d --dns 8.8.8.8 \
-v /opt/docker/transmission/data:/data \
-v /etc/localtime:/etc/localtime:ro \
-v /etc/openvpn/client/default.ovpn:/etc/openvpn/custom/default.ovpn \
-v /media/extern/Torrent:/extern \
-e CREATE_TUN_DEVICE=true \
-e OPENVPN_PROVIDER=CUSTOM \
-e OPENVPN_CONFIG=default \
-e OPENVPN_USERNAME=NAME \
-e OPENVPN_PASSWORD=PW \
-e TRANSMISSION_WEB_UI=transmission-web-control \
-e TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
-e LOCAL_NETWORK=192.168.0.0/16 \
-e TRANSMISSION_DHT_ENABLED=false \
-e TRANSMISSION_PEX_ENABLED=false \
-e TRANSMISSION_DOWNLOAD_QUEUE_SIZE=50 \
--log-driver json-file \
--log-opt max-size=10m \
-p 9091:9091 \
--name Torrent \
haugene/transmission-openvpn:latest
```
The tracker says that i am connectable and transmission said it too. Everything seems to work now correctly. Thank you for your amazing support and your help.

**Comment by pkishino** [comment]
Great to hear that :) please close the issue when you can.
For other issues, please open separate tickets.
@rbrussell82 habe you tried other servers?
@ovizii  does it show the correct port in the GUI? Check logs please

**Comment by ovizii** [comment]
@pkishino here is my own issue: https://github.com/haugene/docker-transmission-openvpn/issues/1152

**Comment by Wimmerer** [comment]
Can we reopen this issue? I have the same problem as @Hamm3rhart. If I open the settings window in Transmission I get a rejected reply from trackers and `docker log transmission` shows Port is Open: No.

If I dont touch the settings window at all I stay connectable, and the logs show Port is Open: Yes

**Comment by pkishino** [comment]
> Can we reopen this issue? I have the same problem as @Hamm3rhart. If I open the settings window in Transmission I get a rejected reply from trackers and `docker log transmission` shows Port is Open: No.
> 
> If I dont touch the settings window at all I stay connectable, and the logs show Port is Open: Yes

@Hamm3rhart issue was solved, have you checked the same steps?
As this is happening inside transmission then it looks like a possible bug related to transmission, which is outside of the scope for this container. Have you tried checking the transmission repo for issues related to this?
The only other thing I could think is that your permissions are not correct and it cannot save the config or such, so when you open settings it is using a different port or such..
Please create a new issue with the necessary details
