### ISSUE TITLE
Allow the use of files for Passwords so Docker Secrets can be utilised

### ISSUE THREAD

**Issue by garybrown-geo** [haugene/docker-transmission-openvpn#1137]
**Is your feature request related to a problem? Please describe.**
Unable to use Docker secrets to hide my passwords.
**Describe the solution you'd like**
Allow the use of a password file for passwords to enable the use of Docker secrets

**Comment by ilike2burnthing** [comment]
Might be something to incorporate here - https://github.com/haugene/docker-transmission-openvpn/pull/1131

**Comment by haugene** [comment]
Duplicate of #534? Let's follow up in the other issue and close this in that case?
Sounds like a good feature and I'm open to PRs, but haven't got around to it myself yet.
