### ISSUE TITLE
Multiples LOCAL_NETWORK ?

### ISSUE THREAD

**Issue by ouafnico** [haugene/docker-transmission-openvpn#114]
Hi 

Nice work with this docker, works very well!

Any way to use multiple LOCAL_NETWORK variables?
On my host, I got multiples LAN, and when the docker start I don't have access to the GUI, except if I put the LOCAL_NETWORK variable, but then it works only with the network range I give for one LAN.

Any way to do this?

Thanks

**Comment by haugene** [comment]
In that case I think it will be easier for you to use the nginx proxy solution that is described in the README. It will then proxy all traffic so you can come from any address.

@lloesche wrote the routing for the LOCAL_NETWORK option. Maybe he knows, or just try the proxy ;)

**Comment by lloesche** [comment]
If you're up to it you could extend the existing code to accept more than one variable. Sth. like LOCAL_NETWORK0...100. If you send a PR just mention me so I see it and I'll review it.
If you can't, let me know and I'll see that I add that function sometime next week.

**Comment by haugene** [comment]
Any thoughts, @ouafnico ? If not, I think I'll close this issue soon.

**Comment by ouafnico** [comment]
Hi i have tried to modify your docker image to add a squid, with a basic configuration and it works well. I didnt try nginx solution.

**Comment by haugene** [comment]
Ok, great :+1:
Closing this then...

**Comment by ouafnico** [comment]
Thanks. I will give the modifications to made for using squid asap.

**Comment by haugene** [comment]
Sweet!
