### ISSUE TITLE
TigerVpn Errors keys out of sync

### ISSUE THREAD

**Issue by conorew** [haugene/docker-transmission-openvpn#1140]
**Describe the problem**
VPN errors for Tiger VPN provider - logs below.
Torrents still work with ok speed, but since I noticed this the log (noticed, may not be cause)
The web ui runs very slowly, most of the time loads with no torrents running.

**Add your docker run command**

> version: '3.5'
> 
> volumes:
>     portainer:
> 
> networks:
>     docker-network:
> 
> services:
> 
>   Transmission:
>     image: haugene/transmission-openvpn:latest-alpine
>     container_name: transmission
>     ports:
>       - "9091:9091"
>     volumes:
>       - /media/4TB/Downloads/:/data
>       - /etc/localtime:/etc/localtime:ro
>     environment:
>       OPENVPN_PROVIDER: Tiger
>       OPENVPN_CONFIG: "NL Amsterdam"
>       OPENVPN_USERNAME: 
>       OPENVPN_PASSWORD: 
>       LOCAL_NETWORK: 192.168.0.0/24å
>       TRANSMISSION_WEB_UI: combustion
>       TRANSMISSION_RATIO_LIMIT_ENABLED: 1
>       TRANSMISSION_RATIO_LIMIT: 0.02
>       TRANSMISSION_DOWNLOAD_QUEUE_SIZE: 15
>       TRANSMISSION_UTP_ENABLED: 'false'
>       GLOBAL_APPLY_PERMISSIONS: 'false'
>       OPENVPN_OPTS: '--inactive 3600 --ping 10 --ping-exit 60'
>       PUID: 1000
>       GUID: 1000
>     devices:
>       - /dev/net/tun
>     cap_add:
>       - NET_ADMIN
>     dns:
>       - 8.8.8.8
>       - 8.8.4.4
>     restart: unless-stopped

**Logs**

> Using OpenVPN provider: Tiger
> Starting OpenVPN using config NL Amsterdam.ovpn
> Setting OPENVPN credentials...
> adding route to local network xx.xx.xx.xx/24 via xx.xx.xx.xx dev eth0
> Wed Apr xx.xx.xx.xx 2020 OpenVPN 2.4.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Feb  7 2020
> Wed Apr xx.xx.xx.xx 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
> Wed Apr xx.xx.xx.xx 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Wed Apr xx.xx.xx.xx 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]xx.xx.xx.xx:1194
> Wed Apr xx.xx.xx.xx 2020 UDP link local (bound): [AF_INET][undef]:1194
> Wed Apr xx.xx.xx.xx 2020 UDP link remote: [AF_INET]xx.xx.xx.xx:1194
> Wed Apr xx.xx.xx.xx 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Wed Apr xx.xx.xx.xx 2020 [tigervpn.com] Peer Connection Initiated with [AF_INET]xx.xx.xx.xx:1194
> Wed Apr xx.xx.xx.xx 2020 TUN/TAP device tun0 opened
> Wed Apr xx.xx.xx.xx 2020 /sbin/ip link set dev tun0 up mtu 1500
> Wed Apr xx.xx.xx.xx 2020 /sbin/ip addr add dev tunxx.xx.xx.xx.123/16 broadcast xx.xx.xx.xx
> Wed Apr xx.xx.xx.xx 2020 /etc/openvpn/tunnelUp.sh tunxx.xx.xx.xx.xx.xx.xx.xx.xx.xx.xx.xx init
> Up script executed with tunxx.xx.xx.xx.xx.xx.xx.xx.xx.xx.xx.xx init
> Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : xx.xx.xx.xx
> Using Combustion UI, overriding TRANSMISSION_WEB_HOME
> Generating transmission settings.json from env variables
> sed'ing True to true
> Enforcing ownership on transmission config directories
> Applying permissions to transmission config directories
> 
> -------------------------------------
> Transmission will run as
> -------------------------------------
> User name:   abc
> User uid:    1000
> User gid:    1001
> -------------------------------------
> 
> STARTING TRANSMISSION
> NO PORT UPDATER FOR THIS PROVIDER
> Transmission startup script complete.
> Wed Apr xx.xx.xx.xx 2020 Initialization Sequence Completed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [5]
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 NOTE: --mute triggered...
> Wed Apr xx.xx.xx.xx 2020 55 variation(s) on previous 10 message(s) suppressed by --mute
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [7]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [6]
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [1]
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 NOTE: --mute triggered...
> Wed Apr xx.xx.xx.xx xx.xx.xx.xx variation(s) on previous 10 message(s) suppressed by --mute
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 NOTE: --mute triggered...
> Wed Apr xx.xx.xx.xx 2020 46 variation(s) on previous 10 message(s) suppressed by --mute
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [4]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [4]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [6]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [3]
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #xx.xx.xx.xx ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 NOTE: --mute triggered...
> Wed Apr xx.xx.xx.xx 2020 73 variation(s) on previous 10 message(s) suppressed by --mute
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #976728 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #976729 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #976730 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #976731 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #976732 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #976733 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #976734 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #976735 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #976736 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #976737 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
> Wed Apr xx.xx.xx.xx 2020 NOTE: --mute triggered...
> Wed Apr xx.xx.xx.xx 2020 22 variation(s) on previous 10 message(s) suppressed by --mute
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [1]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [7]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [7]
> Wed Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [1]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [7]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [4]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [4]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [4]
> Wed Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Thu Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [3]
> Thu Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [5]
> Thu Apr xx.xx.xx.xx 2020 NOTE: --mute triggered...
> Thu Apr xx.xx.xx.xx 2020 2 variation(s) on previous 10 message(s) suppressed by --mute
> Thu Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Thu Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Thu Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [1]
> Thu Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Thu Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Thu Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Thu Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Thu Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Thu Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Thu Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Thu Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [7]
> Thu Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [7]
> Thu Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [6]
> Thu Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [5]
> Thu Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [0]
> Thu Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Thu Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [5]
> Thu Apr xx.xx.xx.xx 2020 AEAD Decrypt error: cipher final failed
> Thu Apr xx.xx.xx.xx 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]xx.xx.xx.xx:1194 [1]

**Host system:**
ubuntu 18.04 server

**Comment by pkishino** [comment]
Please review latest tiger ovpn files from the provider with what is commited to the repo, if they need updating, please submit a PR
