### ISSUE TITLE
Creat Surfshank VPN

### ISSUE THREAD

**Issue by holiveira84** [haugene/docker-transmission-openvpn#1141]
**Which provider?**

surfshark
https://surfshark.com

**Where are the configs?**

https://support.surfshark.com/hc/en-us/articles/360013425373-How-to-set-up-Surfshark-VPN-on-Raspberry-Pi

**Comment by pkishino** [comment]
just checked repo, surfshark is already added
https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/surfshark

**Comment by pkishino** [comment]
https://haugene.github.io/docker-transmission-openvpn/supported-providers/

please close this...

**Comment by holiveira84** [comment]
thanks for it
