### ISSUE TITLE
freevpn.me update April 2020

### ISSUE THREAD

**Issue by bazzou789** [haugene/docker-transmission-openvpn#1143]
**Which provider?**
FREEVPN (freevpn.me)

**Where are the configs?**
All servers: https://freevpn.me/accounts/
Server1: https://freevpnme.b-cdn.net/FreeVPN.me-OpenVPN-Bundle-April-2020.zip
Server2: https://freevpnme.b-cdn.net/FreeVPN.me-OpenVPN-Bundle-April-2020.zip

**Comment by pkishino** [comment]
Please create a PR for this, see documentation how and what you need to do to update the config files
