### ISSUE TITLE
Transmission Container Constantly Restarting // NordVPN

### ISSUE THREAD

**Issue by scooploops** [haugene/docker-transmission-openvpn#1146]
Hello! New to this, but maybe someone could help me figure this out? Getting a constant restart loop. Using NordVPN.

[log.txt](https://github.com/haugene/docker-transmission-openvpn/files/4498434/log.txt)

**Comment by pkishino** [comment]
Your default.ovpn is wrong.. looks like a HTML file.. perhaps the nordvpn script is outdated again

**Comment by pkishino** [comment]
Please look here #1145 
And close this one most likely

**Comment by scooploops** [comment]
Added the following and still getting restart:

NORDVPN_PROTOCOL=tcp
NORDVPN_CATEGORY=openvpn_dedicated_tcp
NORDVPN_COUNTRY=US

Not sure what parameters I actually need to use

**Comment by pkishino** [comment]
Can you post full docker run command, and more of the log, looking at the log it is still trying to connect to a nordvpn server

**Comment by scooploops** [comment]
Running on Synology

Guide used: https://www.reddit.com/r/synology/comments/eahndo/synology_media_advanced_setup_guide/

Attached a fresh log 

[transmission-log.html.zip](https://github.com/haugene/docker-transmission-openvpn/files/4500046/transmission-log.html.zip)

**Comment by pkishino** [comment]
ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)

theres your problem

**Comment by scooploops** [comment]
@pkishino Thanks for the reply! Sorry, I'm really new to this, but I'm not sure what I need to do to correct the problem.

**Comment by pkishino** [comment]
not sure if this option works for synology:
CREATE_TUN_DEVICE=true

**Comment by scooploops** [comment]
@pkishino just tried and doesn't seem to

**Comment by pkishino** [comment]
did you check the link above?

**Comment by scooploops** [comment]
Looks like that did the trick! Was able to SSH in and do the necessary tasks. The container has been running no problem now
