### ISSUE TITLE
GLOBAL_APPLY_PERMISSIONS not being respected

### ISSUE THREAD

**Issue by arpitgupta** [haugene/docker-transmission-openvpn#1148]
Running on synology docker image sha: 8e114aca1530

From within the container

```
root@transmission-openvpn:/# env | grep GLOBAL_APPLY_PERMISSIONS
GLOBAL_APPLY_PERMISSIONS=false
```

how ever when transmission boots up i see the following logs
```
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
```

From the code it should work 
https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/userSetup.sh#L37

But for some reason when run it is not respecting this config.

When the container started it up the folder permissions were different from what i had setup the container with.

**Comment by arpitgupta** [comment]
Forgot to add. Started noticing this issue when i changed the PUID/PGID of the container to be a non admin user on my nas. Once that change was done torrents were no longer getting removed from the client once the seed ratio was met. I am using sonarr/radarr for this management.

**Comment by pkishino** [comment]
Are radarr/sonarr complaining or logging any errors? Transmission?

**Comment by arpitgupta** [comment]
Still trying to find the actual errors in the sonarr logs. Nothing was logged at a info level. What i had noticed on Synology is that after the container started permissions on the folder had been updated and the owner no longer had delete permission. However this did not prevent me from deleting the torrent from the transmission UI.

**Comment by pkishino** [comment]
sonarr also running in docker?

**Comment by arpitgupta** [comment]
Yup. Running as a non admin user in its own container.

**Comment by arpitgupta** [comment]
Actually looking the code the code is always run and is not part of the globally apply permissions.

So this would be an invalid issue. Question is do we be changing the permission of transmission home directory if it already existed? Same question with ownership.

https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/userSetup.sh#L27

**Comment by arpitgupta** [comment]
actually even when I was running as the admin user it would still fall
inside the if condition as the admin user was not root.

What is the API call to remove the torrent?

**Comment by pkishino** [comment]
you could try with transmission-remote or use the rpc api 
https://github.com/transmission/transmission/blob/2.9x/extras/rpc-spec.txt

**Comment by arpitgupta** [comment]
Ok confirmed using the rpc api i am able to remove the torrent just fine. I will be closing the ticket out and reach out to sonarr dev team to see what could be happening here.
