### ISSUE TITLE
NordVPN: parse error: Invalid numeric literal at EOF at line 1, column 4,

### ISSUE THREAD

**Issue by 321liftoff** [haugene/docker-transmission-openvpn#1153]
**Describe the problem**
I suspect something on the NordVPN changed, as it was running okay on April 14.  Container doesn't start with the following error:
> parse error: Invalid numeric literal at EOF at line 1, column 4,

**Add your docker run command**
Only options changed from default:
CREATE_TUN_DEVICE=true
OPENVPN_PROVIDER=NORDVPN
OPENVPN_USERNAME=""
OPENVPN_PASSWORD=""
and /data and /config volume mappings to local storage

**Logs**
> Using OpenVPN provider: NORDVPN,
2020-04-21 12:05:12 Checking curl installation,
2020-04-21 12:05:12 Removing existing configs,
2020-04-21 12:05:12 Selecting the best server...,
parse error: Invalid numeric literal at EOF at line 1, column 4,
2020-04-21 12:05:12 Searching for technology: openvpn_udp,
parse error: Invalid numeric literal at EOF at line 1, column 4,
2020-04-21 12:05:12 Unable to find a server with the specified parameters, using any recommended server,
parse error: Invalid numeric literal at EOF at line 1, column 4,
2020-04-21 12:05:12 Best server : ,
2020-04-21 12:05:12 Downloading config: default.ovpn,
2020-04-21 12:05:12 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0   1165      0 --:--:-- --:--:-- --:--:--  1157,
2020-04-21 12:05:12 Checking line endings,
2020-04-21 12:05:12 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config default.ovpn,
Setting OPENVPN credentials...,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.4),
Use --help for more information.,

**Host system:**
Docker being launched by Portainer running on Qnap NAS

**Comment by Muckoma** [comment]
Does your password have special characters in it? Try changing it to a simple password and see if that fixes the issue.

**Comment by 321liftoff** [comment]
Thanks for the feedback.  My password just has letters and numbers.

I was using the docker image "Created 2020-04-11 13:15:31"

There is a new Docker image "Created 2020-04-21 08:20:45" and this one works.

Thanks!

**Comment by shaad234** [comment]
unfortunattly I call the same error on Nordvpn config "parse error: Invalid numeric literal at EOF at line 1, column 4."

I changed version to 2.7 but still problem exist with the same notification.

**Comment by pkishino** [comment]
> unfortunattly I call the same error on Nordvpn config "parse error: Invalid numeric literal at EOF at line 1, column 4."
> 
> I changed version to 2.7 but still problem exist with the same notification.
@shaad234 
Please make sure you have the latest version

**Comment by shaad234** [comment]
> > unfortunattly I call the same error on Nordvpn config "parse error: Invalid numeric literal at EOF at line 1, column 4."
> > I changed version to 2.7 but still problem exist with the same notification.
> > @shaad234
> > Please make sure you have the latest version

The same issue on version 2.6 , latest 2.7 and beta. not sure what to do.....

**Comment by pkishino** [comment]
Latest 2.12
