### ISSUE TITLE
feat(ci): provide multi-arch docker image

### ISSUE THREAD

**Issue by Neonox31** [haugene/docker-transmission-openvpn#1154]
First, many thanks for your great work 😍 I use your docker image since many year and never had a problem with it !

**Is your feature request related to a problem? Please describe.**
I'm currently using your image inside a K3S cluster with hybrid node amd64/arm64 architectures and I'm forced to restrict my deployment to a specific arch according to specified docker tag.

**Describe the solution you'd like**
The solution to my problem would be using your image as a muti-arch docker image

**Describe alternatives you've considered**
Create my own multi-arch docker image depending of yours but I believe it is not a long term solution.

**Additional context**
I've got a template job for creating multi-arch docker images with Gitmab C.I here : https://gitlab.com/neonox31/ci-helpers/-/blob/master/templates/docker/.gitlab-ci-tpl.yml#L35
I never used circleCI but maybe I can help you ?

**Comment by Neonox31** [comment]
As a temporary fix, I created a project which builds a multi-arch (amd64/arm64) docker image from latest tags of each architecture : https://gitlab.com/neonox31/docker-transmission-openvpn

**Comment by haugene** [comment]
Glad to hear you've found the project useful 😄 And I'd appreciate som help to set up multi-arch image builds. I saw the Dockerfile you had set up and it gave me an idea of how this all works, but how would you recommend we set it up in this project?

I've been using CircleCI a bit in other projects as well as for work, so I can probably handle that part.

**Comment by pkishino** [comment]
@Neonox31 would be great to get more input and such :)

**Comment by Neonox31** [comment]
Unfortunately I still haven't had time to take care of it. I have to see if it is possible to use buildx with circle ci that I don't know well.
In the meantime @pkishino, you can use my docker `neonox31/transmission-openvpn` image which is built every night from latests tags for ARM64 and AMD64 architectures.
