### ISSUE TITLE
Couldn't connect to server error

### ISSUE THREAD

**Issue by bfenty** [haugene/docker-transmission-openvpn#1155]
I've been using this docker image for years with no issues and love it, today I just restarted the container and suddenly I'm getting this error. No idea what could be causing it, but it just keeps repeating that last line over and over.

`STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Fri Apr 24 12:41:58 2020 Initialization Sequence Completed
Generating new client id for PIA
Got new port 38885 from PIA
grep: /data/transmission-home/settings.json: Input/output error
transmission auth not required
waiting for transmission to become responsive
[2020-04-24 12:42:14.439] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server`

**Comment by ilike2burnthing** [comment]
Are you using a Canadian server? https://github.com/haugene/docker-transmission-openvpn/issues/1118

**Comment by bfenty** [comment]
Yes, I tried Montreal and Toronto, why?

**Comment by ilike2burnthing** [comment]
See linked issue

**Comment by bfenty** [comment]
I swapped servers and now I have a different error:

`STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Sat Apr 25 09:16:28 2020 Initialization Sequence Completed
Generating new client id for PIA
Got new port 42949 from PIA
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
_[DELETED A LINE HERE FOR PRIVACY]_
Sum:          150.5 GB              15.0     0.0
setting transmission port to 42949
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 0: No Response`

Still can't access the Web UI. Here's my docker run statement:

`docker run \
        --name=transmission \
        --cap-add=NET_ADMIN -d \
        -v /media/USB1/transmission3:/data \
        -v /etc/localtime:/etc/localtime:ro \
        -e CREATE_TUN_DEVICE=true \
        -e OPENVPN_PROVIDER=PIA \
        -e OPENVPN_CONFIG=Switzerland \
        -e OPENVPN_USERNAME=[username]\
        -e OPENVPN_PASSWORD=[password]\
        -e WEBPROXY_ENABLED=false \
        -e LOCAL_NETWORK=192.168.1.0/16 \
        --log-driver json-file \
        --log-opt max-size=15m \
        -p 9091:9091 \
        --restart unless-stopped \
        haugene/transmission-openvpn:latest`

**Comment by pkishino** [comment]
Please close if fixed
