### ISSUE TITLE
Surfshark Options error and some warnings

### ISSUE THREAD

**Issue by Futureisunknown** [haugene/docker-transmission-openvpn#1157]
Hi,

I am a new user of Surfshark. There is an error that i found in logs;

" Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:7: block-outside-dns (2.4.4) "

But i'm successfully connected to the vpn server. May be something changes in ovpn surfshark's config files? Can you check please?

------------
Plus; There are some warnings. Don't know it's important or not.

1. this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2. 'link-mtu' is used inconsistently, local='link-mtu 1633', remote='link-mtu 1581'
3. 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'
4. 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'

Thanks for this great container Haugene. Have a nice day.

**Comment by pkishino** [comment]
Yeah, those are all “issues” with the VPN, but comes down to config files/server config. You can check with surf shark if they have updated files (in that case you can create a PR with them so we can update in the repo here)  or changed something server side.. you could try and adjust the ovpn file to match the messages, but it might not really do any difference
