### ISSUE TITLE
DNS through VPN?

### ISSUE THREAD

**Issue by pratik5705** [haugene/docker-transmission-openvpn#1161]
Hello. I am running a Ubuntu 18.04 server with PiHole and Docker running this container. My VPN is NordVPN. I can see all dns for the trackers being routed through my PiHole. Is it possible to route it via the VPN?
Here is my docker-compose file. I have tried udp servers as well, but the same issue.

version: '3.3'
services:
    transmission-openvpn:
        volumes:
            - '/media/download/:/data'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=NordVPN
            - OPENVPN_USERNAME=####
            - OPENVPN_PASSWORD=######
            - NORDVPN_COUNTRY=US 
            - NORDXPN_CATEGORY=legacyz_p2p 
            - NORDVPN_PROTOCOL=tcp
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.1.0/24
            - TRANSMISSION_SPEED_LIMIT_UP=200
            - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
            - TRANSMISSION_RATIO_LIMIT=0.05
            - TRANSMISSION_RATIO_LIMIT_ENABLED=true
            - TRANSMISSION_SPEED_LIMIT_DOWN=1500
            - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
            - WEBPROXY_ENABLED=true
            - WEBPROXY_PORT=8888
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
            - '8888:8888'
        image: haugene/transmission-openvpn

Here is the log from the docker startup:

2020-04-28 10:05:21 Checking curl installation,
2020-04-28 10:05:21 Removing existing configs,
2020-04-28 10:05:21 Selecting the best server...,
2020-04-28 10:05:21 Searching for group: legacy_p2p,
2020-04-28 10:05:21 Searching for technology: openvpn_tcp,
2020-04-28 10:05:21 Best server : us3957.nordvpn.com,
2020-04-28 10:05:21 Downloading config: default.ovpn,
2020-04-28 10:05:21 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us3957.nordvpn.com.tcp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2821  100  2821    0     0   4136      0 --:--:-- --:--:-- --:--:--  4130,
2020-04-28 10:05:21 Selecting the best server...,
2020-04-28 10:05:21 Searching for country : US (228),
2020-04-28 10:05:21 Searching for group: legacy_p2p,
2020-04-28 10:05:21 Searching for technology: openvpn_tcp,
2020-04-28 10:05:21 Best server : us3957.nordvpn.com,
2020-04-28 10:05:21 Downloading config: us3957.nordvpn.com.ovpn,
2020-04-28 10:05:21 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us3957.nordvpn.com.tcp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2821  100  2821    0     0  16212      0 --:--:-- --:--:-- --:--:-- 16212,
2020-04-28 10:05:21 Checking line endings,
2020-04-28 10:05:21 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config us3957.nordvpn.com.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.25.0.1 dev eth0,
Tue Apr 28 10:05:24 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019,
Tue Apr 28 10:05:24 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08,
Tue Apr 28 10:05:24 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Tue Apr 28 10:05:24 2020 NOTE: --fast-io is disabled since we are not using UDP,
Tue Apr 28 10:05:24 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Tue Apr 28 10:05:24 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Tue Apr 28 10:05:24 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]196.247.50.133:443,
Tue Apr 28 10:05:24 2020 Socket Buffers: R=[131072->131072] S=[16384->16384],
Tue Apr 28 10:05:24 2020 Attempting to establish TCP connection with [AF_INET]196.247.50.133:443 [nonblock],
Tue Apr 28 10:05:25 2020 TCP connection established with [AF_INET]196.247.50.133:443,
Tue Apr 28 10:05:25 2020 TCP_CLIENT link local: (not bound),
Tue Apr 28 10:05:25 2020 TCP_CLIENT link remote: [AF_INET]196.247.50.133:443,
Tue Apr 28 10:05:25 2020 TLS: Initial packet from [AF_INET]196.247.50.133:443, sid=b820924b 49af5e88,
Tue Apr 28 10:05:25 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Tue Apr 28 10:05:25 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Tue Apr 28 10:05:25 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Tue Apr 28 10:05:25 2020 VERIFY KU OK,
Tue Apr 28 10:05:25 2020 Validating certificate extended key usage,
Tue Apr 28 10:05:25 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Tue Apr 28 10:05:25 2020 VERIFY EKU OK,
Tue Apr 28 10:05:25 2020 VERIFY OK: depth=0, CN=us3957.nordvpn.com,
Tue Apr 28 10:05:25 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Tue Apr 28 10:05:25 2020 [us3957.nordvpn.com] Peer Connection Initiated with [AF_INET]196.247.50.133:443,
Tue Apr 28 10:05:26 2020 SENT CONTROL [us3957.nordvpn.com]: 'PUSH_REQUEST' (status=1),
Tue Apr 28 10:05:26 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.7.0.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.7.0.5 255.255.255.0,peer-id 0,cipher AES-256-GCM',
Tue Apr 28 10:05:26 2020 Option 'explicit-exit-notify' in [PUSH-OPTIONS]:6 is ignored by previous <connection> blocks ,
Tue Apr 28 10:05:26 2020 OPTIONS IMPORT: timers and/or timeouts modified,
Tue Apr 28 10:05:26 2020 OPTIONS IMPORT: --explicit-exit-notify can only be used with --proto udp,
Tue Apr 28 10:05:26 2020 OPTIONS IMPORT: compression parms modified,
Tue Apr 28 10:05:26 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified,
Tue Apr 28 10:05:26 2020 Socket Buffers: R=[131072->425984] S=[87040->425984],
Tue Apr 28 10:05:26 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Tue Apr 28 10:05:26 2020 OPTIONS IMPORT: route options modified,
Tue Apr 28 10:05:26 2020 OPTIONS IMPORT: route-related options modified,
Tue Apr 28 10:05:26 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Tue Apr 28 10:05:26 2020 OPTIONS IMPORT: peer-id set,
Tue Apr 28 10:05:26 2020 OPTIONS IMPORT: adjusting link_mtu to 1659,
Tue Apr 28 10:05:26 2020 OPTIONS IMPORT: data channel crypto options modified,
Tue Apr 28 10:05:26 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Tue Apr 28 10:05:26 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Tue Apr 28 10:05:26 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Tue Apr 28 10:05:26 2020 ROUTE_GATEWAY 172.25.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:19:00:02,
Tue Apr 28 10:05:26 2020 TUN/TAP device tun0 opened,
Tue Apr 28 10:05:26 2020 TUN/TAP TX queue length set to 100,
Tue Apr 28 10:05:26 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=0,
Tue Apr 28 10:05:26 2020 /sbin/ip link set dev tun0 up mtu 1500,
Tue Apr 28 10:05:26 2020 /sbin/ip addr add dev tun0 10.7.0.5/24 broadcast 10.7.0.255,
Tue Apr 28 10:05:26 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1587 10.7.0.5 255.255.255.0 init,
Up script executed with tun0 1500 1587 10.7.0.5 255.255.255.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.7.0.5,
Generating transmission settings.json from env variables,
sed'ing True to true,
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   root,
User uid:    0,
User gid:    0,
-------------------------------------,
,
DROPPING DEFAULT ROUTE,
STARTING TRANSMISSION,
NO PORT UPDATER FOR THIS PROVIDER,
Transmission startup script complete.,
STARTING TINYPROXY,
Found config file /etc/tinyproxy/tinyproxy.conf, updating settings.,
Setting tinyproxy port to 8888,
Starting Tinyproxy lightweight HTTP proxy daemon: tinyproxy.,
Tinyproxy startup script complete.,
Tue Apr 28 10:05:27 2020 /sbin/ip route add 196.247.50.133/32 via 172.25.0.1,
Tue Apr 28 10:05:27 2020 /sbin/ip route add 0.0.0.0/1 via 10.7.0.1,
Tue Apr 28 10:05:27 2020 /sbin/ip route add 128.0.0.0/1 via 10.7.0.1,
Tue Apr 28 10:05:27 2020 Initialization Sequence Completed,

**Comment by haugene** [comment]
You've set `LOCAL_NETWORK=192.168.1.0/24`, so all traffic destined for IPs other than this should be routed through the VPN. Try [specifying dns](https://docs.docker.com/compose/compose-file/#dns) in your docker-compose:
```
dns:
  - 8.8.8.8
  - 8.8.4.4
```

To use Google DNS servers for example. See if you still get entries in your PiHole after that, it shouldn't.

**Comment by pratik5705** [comment]
Adding DNS stops entries in PiHole. However, does this mean that the DNS is being routed to Google un-encrypted (for my ISP and anyone else to view)?
I can see from the connection log that Nord provides DNS servers:
Tue Apr 28 10:05:26 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option _DNS 103.86.96.100_,dhcp-option _DNS 103.86.99.100_,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.7.0.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.7.0.5 255.255.255.0,peer-id 0,cipher AES-256-GCM',

Should I manually specify those instead of Google, or is there way for the script to use those?
Thanks for the prompt reply!

**Comment by haugene** [comment]
Well. After the VPN connection is set up, all DNS requests will go through it as it is not within the LOCAL_NETWORK cidr address. You can look at LOCAL_NETWORK cidr as a hole that's punched in the VPN. The rest goes out over the tunnel.

If your openvpn config has server names in dns form then the dns lookup for some.server.nordvpn.com will go directly to Google, from your home IP. But after that the requests will go through VPN.

I also saw those options they pushed. You'll have to check in the container if they're being set correctly? You could choose to use NordVPN DNS directly using the method I linked to, if you want.

**Comment by pratik5705** [comment]
How do I check in the container if they are being set correctly?

Without the dns being specified, I was seeing a lot of dns activity on pilhole when trackers were being resolved, aven after the VPN was setup, so that is what my initial query was directed towards - why is DNS traffic not being passed over the VPN?

**Comment by haugene** [comment]
Well... One reason could be that the DNS server (as in your case) was on the CIDR that you defined as LOCAL_NETWORK, as I mentioned above.

The VPN will originally direct all traffic towards the tunnel interface and thus through the VPN connection. But. Since this means you then can't communicate with the WebUI on a local address because the response would be grabbed and sent through the VPN, we open a range of IPs to be forwarded through the non-tunneled interface to your host networking.
So if the container is configured with a DNS on 192.168.1.1 then it's allowed to connect to it because you've allowed it.

What is the DNS server and how do you check it? Here's where it gets a bit more tricky.
The [docs state that](https://docs.docker.com/config/containers/container-networking/#dns-services):
> By default, a container inherits the DNS settings of the Docker daemon, including the /etc/hosts and /etc/resolv.conf.You can override these settings on a per-container basis.

So you should get it from your host, and you can set the dns flags to override them.
I tested now and I set the Google DNS as the example I sent to you. Then I exec'ed into the container and ran `apt install dnsutils`. This installs nslookup and dig.

Running the command `dig google.com` returned the following:
```
root@36cff049da6f:/# dig google.com

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49783
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             233     IN      A       172.217.0.238

;; Query time: 120 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Tue Apr 28 21:19:07 UTC 2020
;; MSG SIZE  rcvd: 55
```

Here we see that even if I set the dns servers to 8.8.8.8, I'm getting a response from server 127.0.0.11. Which is a loopback address. This is a sign that DNS caching is enabled. Also makes sense when I look at my resolv.conf:
```
root@36cff049da6f:/# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
```

Might be that we could override this even further. Force DNS to go directly to the DNS servers and omit a local DNS cache. But I'm unsure of the potential issues that might cause as well. I think Docker spawns a resolver for each user created network. This is done automatically for all docker-compose setups. If you do a `docker run ...` it attaches to the default bridge network, but for docker-compose it creates a new one. Docker also provides DNS among services in a network, so if we override it too hard will we then lose some of that functionality?

This is as far as I know it today. Might have the time and interest to dig deeper some other time - as it is interesting of course. But for now I've been assuming that Docker is using the DNS I provide and it will then be routed through VPN.

**Comment by pratik5705** [comment]
Thanks for your responses and help. I guess where I am struggling is that the intended functionality, as you stated is "that Docker is using the DNS I provide and it will then be routed through VPN."
In my case, docker is using the DNS that I provide initially, and continues to use that DNS even after the VPN connection is initiated.
I have tried a torrent from ipleak.net to see the IP address the torrent reports back. It is the IP address of the VPN (not my actual IP). However, I can see the DNS queries for ipleak.net from the torrent tracker on my pi-hole.
Another thing that I tried to do is run Pi-Hole on a different machine than the one running docker. However, this doesn't change the behavior at all, I continue to see DNS queries to pi-hole for the trackers that the torrent is using. These continue to go to Pi-Hole even after the VPN is established. Ipleak always (correctly) reports the VPN IP address though.

Appreciate your responsiveness.

**Comment by haugene** [comment]
I'm confused. I thought you said that if you provided the Google DNS it would no longer show up in your pi-hole? You can't both use your pi-hole as DNS **and** go through VPN. Would defeat the purpose in any case because pi-hole is not on VPN and would such query through your ISP.

Do you mean that you would expect OpenVPN to change your DNS servers after the connection was initiated?

If you want to run the container without it having routes open to your local network (after connection is set up) then you would have to drop the LOCAL_NETWORK variable and go for the [reverse proxy solution instead](https://haugene.github.io/docker-transmission-openvpn/access/). That will dis-allow all traffic from the container to any 192.168.1.x address and instead rely on a proxy that is on the same subnet as the container in the Docker network, this is allowed by default by OpenVPN.

**Comment by pratik5705** [comment]
Sorry, I meant that when I start without specifying the DNS option (-dns), all DNS queries are being routed via pi-hole, even after the VPN connection is established. If I put DNS option, then they do not show up in pi-hole.
 I guess my question would be, is there a way to find out if the DNS is being routed through the VPN when I set the DNS option (-dns). I am concerned that they are going to google not via the VPN and can be seen by others outside my network.
I will play with the reverse proxy solution. When trying that, should I remove the LOCAL_NETWORK option?

**Comment by haugene** [comment]
Yes. If you use the proxy you don't need the LOCAL_NETWORK parameter. If you want to know for sure you'll have to install some kind of packet sniffer or network analyser and do your own verification. But the VPN will set up routing rules that should be sufficient and all non-local traffic will go through VPN.

You can view your iptables routing by exec'ing `ip r` in the container.
