### ISSUE TITLE
Set timezone at run time

### ISSUE THREAD

**Issue by edgd1er** [haugene/docker-transmission-openvpn#1163]
**Is your feature request related to a problem? Please describe.**

The container is by default set to UTC time which is not my local time. As a result, scheduled alternate speed does not kick in at the expected hours.

**Describe the solution you'd like**

When The TZ variable is not null, define localtime with $TZ , and reconfigure tzdata, the package being already present in the image. The operation does not take long, it could be inserted in /etc/openvpn/start.sh before the last command.

```
[[ -n ${TZ} ]] && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime && dpkg-reconfigure -f non-interactive tzdata
``` 

**Describe alternatives you've considered**

mounting /etc/localtime is unfortunately not an option for me.

**Additional context**

**Comment by haugene** [comment]
I'm pretty sure that this already works out of the box with the tzdata package?

Ran this now locally:
```
 ~ docker run --rm -it -e TZ=Europe/London haugene/transmission-openvpn bash -c "date"                                                           
Wed Apr 29 22:50:04 BST 2020
 
~ docker run --rm -it -e TZ=Europe/Paris haugene/transmission-openvpn bash -c "date"                                                            
Wed Apr 29 23:50:09 CEST 2020
```

Setting a valid TZ environment variable from [the list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of supported zones should do the trick.

**Comment by edgd1er** [comment]
Well, I focus may be too much on the timezone ;) The time seems to be ok. With your example, the timezone stays UTC. 

if you run: `docker run --rm -it -e TZ=Europe/Paris haugene/transmission-openvpn bash -c "date;cat /etc/timezone;ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime;dpkg-reconfigure tzdata; cat /etc/timezone" ` you will see that the timezone is then properly set.

the result is:
```
Thu Apr 30 00:11:30 CEST 2020
Etc/UTC

Current default time zone: 'Europe/London'
Local time is now:      Wed Apr 29 23:11:31 BST 2020.
Universal Time is now:  Wed Apr 29 22:11:31 UTC 2020.

Europe/London
```

That being said, I don't know if the BST rather than UTC timezone is that much important on a daily basis and what could be the consequences of a discrepancy between the host and the guest. May be dates for Daylight saving times switch are note the same for all countries: [USA and Canada ](https://www.timeanddate.com/news/time/europe-starts-dst-2020.html). 

From what you said, and what I've found with google, setting TZ seems to be enough. I should have looked before opening the issue. Sorry for the trouble.

I guess this issue could be closed.

Thanks for your project .

**Comment by pkishino** [comment]
Yeah, I have it set to Asia/Tokyo and it works fine with TZ already

**Comment by edgd1er** [comment]
ok, fair enough for me ;) thanks.

**Comment by haugene** [comment]
@edgd1er No trouble. Interesting note on the `/etc/timezone`. I was actually expecting it to have been updated as well. Never checked it directly.

Could have linked the timezone as well, as you propose. But as long as the current solution works for you then that's great. Feel free to re-open if you find another use-case where the difference in timezone plays a role 😄

**Comment by triksmelb** [comment]
Running on Synology Docker here, can confirm adding TZ=Australia/Melbourne sets the correct time/date within container.
thank you also for this great project.
