### ISSUE TITLE
Add a request at startup to check the public IP

### ISSUE THREAD

**Issue by diyfr** [haugene/docker-transmission-openvpn#1166]
To verify that the openvpn configuration is successful
Sample command
```shell
curl icanhazip.com
```

**Comment by pkishino** [comment]
There already is a health check that is run and verified that you are connected. I don’t quite get what it is you want added.

**Comment by ilike2burnthing** [comment]
That site returns your IP in plain text, so I'm assuming the idea here is to fetch this to ensure you don't have an IP leak

**Comment by diyfr** [comment]
> That site returns your IP in plain text, so I'm assuming the idea here is to fetch this to ensure you don't have an IP leak
That's it ! :)

**Comment by pkishino** [comment]
this would be fine, could you add a simple PR for this? Were you thinking to compare the result with something or?

**Comment by albertcarrete** [comment]
What about a _Prohibit IP_ setting where an ip address can be statically added as a configuration option. Then a process checks the result of icanhazip.com (or similar) against that setting and prevents leakage if it reports a matches.

**Comment by pkishino** [comment]
would love some comments on the PR linked
