### ISSUE TITLE
Add RSS feed with regex?

### ISSUE THREAD

**Issue by ViggoGaming** [haugene/docker-transmission-openvpn#1167]
Hey All.

I am using the docker image in this repo :+1: 

I want to add an RSS feed with regex included to this docker setup, but I can't figure out how to set it up correctly 😕 

I looked at the documentation here for the RSS plugin.
https://haugene.github.io/docker-transmission-openvpn/rss-plugin

I can see there is the "-e" flag to add an URL, but I can't figure out how to do regex on this URL. I think this is possible because of the original repo for transmission-rss supports this with the "regexp: foo" tag.

Thanks in advance for the help

**Host system:**
Ubuntu 19.04 Server version, Docker version 18.09.7

**Comment by pkishino** [comment]
looking at the code it currently doesnt support it..
but you could create a PR to add the needed support, shouldnt be too hard, just add the missing setting:
https://github.com/haugene/docker-transmission-openvpn/tree/master/plugins/rss

**Comment by pkishino** [comment]
feel free to try the PR linked

**Comment by ksurl** [comment]
have you thought about using an external client to send magnet/torrent links to the container? flexget is very powerful. if you need something simpler, then sonarr
