### ISSUE TITLE
Docker container runs only when root

### ISSUE THREAD

**Issue by user4567ty** [haugene/docker-transmission-openvpn#1169]
Hi all,

I've been using transmission-openvpn in combination with Plex, which is also running in a Docker container. The Transmission and the VPN have been running fine. The only problem is that the container needs to run as root. Which also makes all downloaded files belong to the root user. Is there a way to run this container using the default user? 

Thanks!

I setup docker-transmission-openvpn using the following config:

docker run --cap-add=NET_ADMIN -d \
              -v /home/plex/transvpn/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER= \
              -e OPENVPN_CONFIG= \
              -e OPENVPN_USERNAME= \
              -e OPENVPN_PASSWORD= \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.0.0/16 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn

*VPN config settings are removed*

**Comment by pkishino** [comment]
read documenation:
https://haugene.github.io/docker-transmission-openvpn/arguments/#user_configuration_options
