### ISSUE TITLE
Can't seem to access WEB UI via Qnap container

### ISSUE THREAD

**Issue by deadfreak** [haugene/docker-transmission-openvpn#117]
Fri Aug 12 15:03:38 2016 event_wait : Interrupted system call (code=4)                                                         
Fri Aug 12 15:03:38 2016 /sbin/ip addr del dev tun0 local 10.190.1.6 peer 10.190.1.5                                             
Fri Aug 12 15:03:38 2016 /etc/transmission/stop.sh tun0 1500 1558 10.190.1.6 10.190.1.5 init                                     
Fri Aug 12 15:03:38 2016 SIGINT[hard,] received, process exiting                                                                 
Using OpenVPN provider: PIA                                                                                                      
No VPN configuration provided. Using default.                                                                                    
Setting OPENVPN credentials...                                                                                             
adding route to local network 192.168.0.0/24 via 10.0.3.1 dev eth0                                                               
Fri Aug 12 14:39:15 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on
 Dec  1 2014                                                                                                                     
Fri Aug 12 14:39:15 2016 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts   
Fri Aug 12 14:39:15 2016 UDPv4 link local: [undef]                                                                               
Fri Aug 12 14:39:15 2016 UDPv4 link remote: [AF_INET]46.166.138.148:1198                                                         
Fri Aug 12 14:39:15 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Aug 12 14:39:15 2016 [66ebdea877608bc8f1a0844d919daea7] Peer Connection Initiated with [AF_INET]46.166.138.148:1198         
Fri Aug 12 14:39:17 2016 TUN/TAP device tun0 opened                                                                              
Fri Aug 12 14:39:17 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0                                                  
Fri Aug 12 14:39:17 2016 /sbin/ip link set dev tun0 up mtu 1500                                                                  
Fri Aug 12 14:39:17 2016 /sbin/ip addr add dev tun0 local 10.132.1.6 peer 10.132.1.5                                             
Fri Aug 12 14:39:17 2016 /etc/transmission/start.sh tun0 1500 1558 10.132.1.6 10.132.1.5 init         
 Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.132.1.6                                                           
Generating transmission settings.json from env variables                                                                         
STARTING TRANSMISSION                                                                                                            
STARTING PORT UPDATER                                                                                                            
Transmission startup script complete.                                                                                            
Fri Aug 12 14:39:17 2016 Initialization Sequence Completed                                                                       
Generating new client id for PIA    

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                  
                                 Dload  Upload   Total   Spent    Left  Speed                                                    
100   106  100    14  100    92      2     14  0:00:07  0:00:06  0:00:01    23                                                   
Got new port 22634 from pia                                                                                                      
transmission auth not required                                                                                                   
localhost:9091/transmission/rpc/ responded: "success"                                                                            
Checking port...                                                                                                                 
Port is open: Yes        

I'm trying to run this container from my Qnap device. Apparently it runs and doesn't seem to have any issue. However even with the "LOCAL_NETWORK=192.168.0.0/24" that was suggested, i still can't seem to pull up the web ui at all. The nas is on 192.168.1.2. Even tried changing it to: "LOCAL_NETWORK=192.168.1.0/24" and still nothing.

**Comment by haugene** [comment]
What IP are you accessing the web ui from? That's what matters since you define 192.168.0.0/24 as local traffic. 

And have you tried the option with the nginx proxy? If that works at least we know the container is behaving as it should and that this is an addressing issue...

**Comment by deadfreak** [comment]
192.168.1.2. As mentioned i did change it to "LOCAL_NETWORK=192.168.1.0/24" and still nothing is showing for the web ui. Haven't done the proxy thing yet as i assumed i could get it to work via the parameter instead (which is more simple for me).

**Comment by haugene** [comment]
You said the nas was on 192.168.1.2, which is the server here. So what is the ip of the client pc?

Please post ipconfig/ifconfig for the server and client pc. Also your docker run command or port config for the container. And what address are you typing into the browser? 

LOCAL_NETWORK works, this is probably a config issue. So I kinda need to see your config.

**Comment by haugene** [comment]
Closing this now... Please re-open if you still have issues.

**Comment by dubstrike** [comment]
The QNAP Container Station is in the 10.0.3.0/24 range.
