### ISSUE TITLE
ProtonVPN only with configs elegible for p2p

### ISSUE THREAD

**Issue by casaper** [haugene/docker-transmission-openvpn#1171]
**Which provider?**
ProtonVPN

**Where are the configs?**
> Most providers supply a .zip file containing all configs and certificates. Please provide a link to the .ovpn config bundle

ProtonVPN offers the files individually in an authenticated member section of their page, as far as I know.

I discovered that this image contains all the proton VPN configs available. The problem is, that only a fraction of the servers will allow p2p. So I think it doesn't make sense to carry all these configs, that will most likely not work well or not at all in this image, since this image is specifically for p2p.

**Comment by cat24max** [comment]
I have noted this a couple months ago, but some people just added them. I have no idea why, but yea...
