### ISSUE TITLE
Container keeps rebooting

### ISSUE THREAD

**Issue by user4567ty** [haugene/docker-transmission-openvpn#1173]
Hi,

Today I installed the docker-transmission-openvpn container and everything worked fine. I made some changes to my settings and deployed the container again using docker-compose. Now the container keeps rebooting giving the following error: 

`Using default OpenVPN gateway for provider protonvpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/protonvpn/default.ovpn
Use --help for more information.`

My docker-compose file:
transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - ${USERDIR}/Downloads:/data/watch
      - ${USERDIR}/Downloads/completed:/data/completed
      - ${USERDIR}/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true

Since deploying this container I'm also having connectivity issues with this server, running Ubuntu 18.04.

If anybody has a clue what the cause could be, let me know.

Thanks in advance!

**Comment by pkishino** [comment]
which release are you using?

**Comment by ILAsoft** [comment]
Had the same issue w/lastest-armhf, so switched to 2.12-armhf temporarily and working fine now...

**Comment by user4567ty** [comment]
I was using the latest version. Switching to an older release seems to be working. Thanks!

**Comment by screwfaze** [comment]
Older release not working for me anyone know of any other fix?

**Comment by SaltyPaws** [comment]
I have the same issue running ubuntu server 20.20 with Docker version 19.03.9, build 9d988398e7
ILAsoft's recommendation worked but this is not a long term solution...

**Comment by Blehhh** [comment]
I am having the same issue with my OMV setup
"Error opening configuration file: /etc/openvpn/protonvpn/default.ovpn"
It was working fine yesterday. If someone could assist me in what they have done to get a fix would be much appreciated. I have seen mentions of rolling back but unsure on how to do that.

**Comment by Bidley** [comment]
Same issue here, also unsure of how to roll back with OMV5/Portainer.

Logs: https://pastebin.com/8gXNNtMJ

Portainer config: https://pastebin.com/ehZQfCcV

**Comment by Bidley** [comment]
I don't know if it's related, but my issue seemed to start after updating Docker via OMV. Could this cause the above problems?

**Comment by Bidley** [comment]
OK I have it working now - I previously had the container within a docker network - removing the network from the equation allows the container to work as normal. Trying to route it through the network causes the same error again.

I'll be honest, I set this up about a year ago on OMV4 by following a youtube video, so I don't actually know if the network is necessary any more. But either way it seems to be working perfectly now.

**Comment by Blehhh** [comment]
I have tried setting up two different OMV vm's in virtual box, one running the latest version of omv4 and one running 4.1.3 they both get the same error: "options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/protonvpn/default.ovpn".

**Comment by pkishino** [comment]
protonvpn doesnt have a default.ovpn from what it looks like so you will need to specify openvpn_config parameter

**Comment by Blehhh** [comment]
> 
> 
> protonvpn doesnt have a default.ovpn from what it looks like so you will need to specify openvpn_config parameter

I am pretty sure I have done that, I set OPENVPN_CONFIG = "config certificate I downloaded from protonvpn", when I built the container through omv webgui but the logs still had the same error though.

**Comment by pkishino** [comment]
if you just downloaded the config it most likely will not work as it needs to be modified slightly to work with the container. I believe it is described in the documentation how

**Comment by pkishino** [comment]
try specifying one of the configs from the protonvpn directory here.. like nl-01.protonvpn.com.udp

**Comment by Blehhh** [comment]
ok I will take a look, thanks for the help.

**Comment by Blehhh** [comment]
I have tried that as well, but could have missed something. When setting it to nl-01.protonvpn.com.udp, I was not able to find that file in the /var/lib/docker/ directory so I tried downloading the file and then setting OPENVPN_CONFIG to that file but was still the same error.

**Comment by pkishino** [comment]
If you check this repo you will see the openvpn folder.. all config are in
there.
So just set the config sich and it will load, no need to download anything

**Comment by Blehhh** [comment]
Sorry if I am being dense but I do not understand what you mean. To point OPENVPN_CONFIG to one of the .ovpn files I need them on my system, but I am unable to find them in my docker folders using locate, so I clone this repository, then point OPENVPN_CONFIG to a .ovpn file.... and it does not work. 
`Supplied config /home/brook/transmission-openvpn/openvpn/protonvpn/au-09.protonvpn.com.tcp.ovpn.ovpn could not be found.`
I know that that file path has .ovpn twice but my config looks like this:
![image](https://user-images.githubusercontent.com/28968976/82977433-2993af00-a025-11ea-8c9b-c458a2184333.png)
It also still gives the initial error:
`Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/protonvpn/default.ovpn`

**Comment by pkishino** [comment]
all the openvpn files here: https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn
are baked into the docker image..
so please just try setting OPENVPN_CONFIG to au-09.protonvpn.com.tcp
thats it, nothing more

**Comment by Blehhh** [comment]
Ah ok I was over-complicating things sorry, my knowledge was lacking, was not aware you could do that. Unfortunately still the same issue though.

**Comment by pkishino** [comment]
Can you please post run command/config and any log please?

**Comment by Blehhh** [comment]
@pkishino Actually just using au-09.proton.com fixed it, I went through my build doc and I had made a typo when recreating it. Thank you so much for your help and patience.
