### ISSUE TITLE
support NORDLYNX  as VPN protocol

### ISSUE THREAD

**Issue by Pekeja** [haugene/docker-transmission-openvpn#1174]
With the launch of the n"new" NORDLYNX prototocal by NORDVPN, would it be possible to integrate this/have this as an optionin the VPN set-up?
What would be the fields?

**Comment by ilike2burnthing** [comment]
See - https://github.com/haugene/docker-transmission-openvpn/issues/1107

**Comment by Pekeja** [comment]
See - #1107
