### ISSUE TITLE
This file does nothing on create: openvpn/privado/updateConfigs.sh

### ISSUE THREAD

**Issue by lateparty** [haugene/docker-transmission-openvpn#1177]
**Describe the problem**

As a newly launched VPN provider Privado are regularly updating and changing their server offerings. Recently having removed and then added a swathe of servers. Inspecing the file in the subject "updateConfigs.sh" when ran in the container works perfectly however my bug is to report that it does not run on creation, and we are limited to the config files available at the last release without enacting this manual work around.

My expected behaviour would be that this update runs on creation each time.

Note: I made sure to run "docker stop", "docker rm", and "docker image prune -af" then my run command prior to reporting this, logs after the run:

```
[bash]$ sh trans_vpn-create.sh
Unable to find image 'haugene/transmission-openvpn:latest' locally
latest: Pulling from haugene/transmission-openvpn
23884877105a: Pull complete 
bc38caa0f5b9: Pull complete 
2910811b6c42: Pull complete 
36505266dcc6: Pull complete 
ddb9b42e3664: Pull complete 
843f09c5de2d: Pull complete 
f930803040ff: Pull complete 
c563cee4ca30: Pull complete 
887502671bf7: Pull complete 
Digest: sha256:0c36b139d761617f37bf63f4597f750cc6631fdc10698f83ded3642a73669082
Status: Downloaded newer image for haugene/transmission-openvpn:latest
6342bb3762282bb78f66a31a0b805c120e0b50da02a231ad1704ee8d8fc3b46d

```
**Host system:**

Arch Linux 5.6.10

**Comment by pkishino** [comment]
the updateConfigs.sh will not automatically run as it is currently setup..but you could add a line to a pre-startup script as per here: https://haugene.github.io/docker-transmission-openvpn/custom-scripts/
and call it to update the scripts when container starts.

**Comment by lateparty** [comment]
That's a reasonable workaround, thanks!
