### ISSUE TITLE
Can only get old tag (1.10)

### ISSUE THREAD

**Issue by cr3ation** [haugene/docker-transmission-openvpn#118]
![registry](https://cloud.githubusercontent.com/assets/8100213/18112206/2998b826-6f26-11e6-9be1-80f77715d4f1.png)
![image](https://cloud.githubusercontent.com/assets/8100213/18112209/2ca047c8-6f26-11e6-9c5b-e043d6e05625.png)

Need Docker Tag 1.11 or 1.12 to get IntegrityVPN-support. 

When downloading the image on my Synology NAS I can only find Docker Tag 1.5 - 1.10 in my registry. I have also tried to add https://hub.docker.com/r/haugene/transmission-openvpn/ to try manual download - same result. Can't find any "latest" release.

Please help!

**Comment by haugene** [comment]
The tags are there: https://hub.docker.com/r/haugene/transmission-openvpn/tags/
This is a Synology bug. But see #106 and check if his solution works for you. (ie, pull it manually and it will pop up in the GUI)

**Comment by cr3ation** [comment]
This is not a transmission-openvpn problem. 

Synology DiskStation Manager 6.0 uses Docker API v1. This problem seems to be related to API calls made with v1 of the protocol. No problem reported when using Docker API v2.

If anyone else have this problem, please report to Synology support and tell them to update Docker to use v2 of the Docker API. The more requests they get, the faster they will fix it.

Read more + workaround: https://github.com/docker/hub-feedback/issues/687
