### ISSUE TITLE
Torrent done script not working

### ISSUE THREAD

**Issue by rewhex** [haugene/docker-transmission-openvpn#1180]
Hello! I've the script that can delete fully downloaded torrents (w/o data of course), and placed this script in /dir/delete_torrent.sh, he's working perfectly with _docker exec transmission-openvpn bash /data/delete_torrent.sh_, but the script doesn't do anything when called automatically.

Need to say: calling manually with sh not working, only with bash, maybe this is the problem?
Docker command runs from systemd with user root.

I have tried everything from older issues, and nothing helps, any suggestions please?

**Script:**
```
#!/bin/bash
creds=($(cat /config/transmission-credentials.txt))

user="${creds[0]}"
pass="${creds[1]}"

sudo transmission-remote --auth $user:$pass -l | awk '$2 == "100%" && system("transmission-remote --auth $user:$pass -t " $1 " --remove")'
```

**Permissions:**
`-rwxr-xr-x  1 root root  243 May  9 08:04 delete_torrent.sh`

**Docker run command:**
```
docker run \
  --name transmission-openvpn \
  --cap-add=NET_ADMIN \
  -v /dir/:/data \
  -v /etc/localtime:/etc/localtime:ro \
  -e "LOCAL_NETWORK=192.168.0.0/24" \
  -e "CREATE_TUN_DEVICE=true" \
  -e "OPENVPN_PROVIDER=provider" \
  -e "OPENVPN_CONFIG=config" \
  -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
  -e "OPENVPN_USERNAME=user" \
  -e "OPENVPN_PASSWORD=pass" \
  -e "WEBPROXY_ENABLED=true" \
  -e "WEBPROXY_PORT=3002" \
  -e "ENABLE_UFW=false" \
  -e "TRANSMISSION_MESSAGE_LEVEL=3" \
  -e "TRANSMISSION_CACHE_SIZE_MB=32" \
  -e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true" \
  -e "TRANSMISSION_RPC_ENABLED=true" \
  -e "TRANSMISSION_RPC_PASSWORD=pass" \
  -e "TRANSMISSION_RPC_USERNAME=user" \
  -e "TRANSMISSION_INCOMPLETE_DIR_ENABLED=false" \
  -e "TRANSMISSION_INCOMPLETE_DIR=/data/transmission-home/incomplete" \
  -e "TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false" \
  -e "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true" \
  -e "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/data/delete_torrent.sh" \
  -e "TRANSMISSION_START_ADDED_TORRENTS=true" \
  -e "TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true" \
  -e "TRANSMISSION_WATCH_DIR_ENABLED=true" \
  -e "TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true" \
  -e "TRANSMISSION_WEB_UI=kettu" \
  -e "TRANSMISSION_UMASK=0" \
  --log-driver json-file \
  --log-opt max-size=10m \
  -p 9091:9091 \
  -p 127.0.0.1:3002:3002 \
  --dns 1.1.1.1 \
  --dns 1.0.0.1 \
  haugene/transmission-openvpn:latest-armhf
```

**Logs:**
I've seen these lines, there is no errors at all:
```
State changed from "Incomplete" to "Complete" (torrent.c:2218)
Calling script "/data/delete_torrent.sh" (torrent.c:2118)
```

**Host system:**
Raspberry Pi 4
Raspbian 10 (buster)

**Comment by pkishino** [comment]
hmm, 
you could try and log output in your script to make sure each step runs..
I did find this: https://gist.github.com/pawelszydlo/e2e1fc424f2c9d306f3a#gistcomment-3118360
perhaps of use?

**Comment by rewhex** [comment]
> hmm, 
> you could try and log output in your script to make sure each step runs..
> I did find this: https://gist.github.com/pawelszydlo/e2e1fc424f2c9d306f3a#gistcomment-3118360
> perhaps of use?
Tried to echo all of the commands, and yes - it works when I run it manually.
Also using this for testing:
`#!/bin/bash
echo "test" > /data/test.txt`
Running manually creates test.txt with _test_ word in it, but not automatically

**Comment by rewhex** [comment]
Still not solved, I will use cron for this.

**Comment by pkishino** [comment]
Hmm, I tried the script and it works fine for me. Strange
