### ISSUE TITLE
Transmission WebUI does not change when setting variables TRANSMISSION_WEB_HOME or TRANSMISSION_WEB_UI

### ISSUE THREAD

**Issue by jworcutt** [haugene/docker-transmission-openvpn#1186]
When using the environmental variables TRANSMISSION_WEB_HOME or TRANSMISSION_WEB_UI in Docker, the web UI does not change.  In fact I cannot get it to change from the Combustion UI no matter what I do.

![Screenshot_2020-05-11 Portainer(1)](https://user-images.githubusercontent.com/65208413/81635885-04256500-93d8-11ea-8e6a-d8291af911c7.png)

**Host system:**

Raspberry pi 4, Raspbian latest

**Comment by Iki-turso** [comment]
You need to clear your browser cache or hit Ctrl + F5 for the UI changes to take effect in your browser.
