### ISSUE TITLE
protonvpn  "Error opening configuration file: /etc/openvpn/protonvpn/default.ovpn"

### ISSUE THREAD

**Issue by douglasriper** [haugene/docker-transmission-openvpn#1190]
**Describe the problem**

The dock no longer launches in the logs it indicates "Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/protonvpn/default.ovpn".

I think it's because of the removal of the country Proton configurations in the dock.
Example: ch.protonvpn.com.udp,nl.protonvpn.com.udp,se.protonvpn.com.udp,is.protonvpn.com.udp
**Add your docker run command**

ExecStart=/usr/bin/docker run \
        --name transmission-openvpn \
        --cap-add=NET_ADMIN \
        --device=/dev/net/tun \
        -v /home/vilnus/docker/transmission-openvpn/:/data \
        -v /etc/timezone:/etc/timezone:ro \
        -v /etc/localtime:/etc/localtime:ro \
        -e "CREATE_TUN_DEVICE=true" \
        -e "OPENVPN_PROVIDER=PROTONVPN" \
        -e "OPENVPN_CONFIG=ch.protonvpn.com.udp,nl.protonvpn.com.udp,se.protonvpn.com.udp,is.protonvpn.com.udp" \
        -e "OPENVPN_USERNAME=######" \
        -e "OPENVPN_PASSWORD=##########" \
        -e "ENABLE_UFW=true" \
        -e "WEBPROXY_ENABLED=false" \
        -e "LOCAL_NETWORK=192.168.1.0/24" \
        -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
        -e "TRANSMISSION_UMASK=0" \
        --log-driver json-file \
        --log-opt max-size=10m \
        -p 9091:9091 \
        haugene/transmission-openvpn

**Logs**

`mknod: /dev/net/tun: File exists
Using OpenVPN provider: PROTONVPN
4 servers found in OPENVPN_CONFIG, se.protonvpn.com.udp chosen randomly
Supplied config se.protonvpn.com.udp.ovpn could not be found.
Using default OpenVPN gateway for provider protonvpn
Setting OPENVPN credentials...
enabling firewall
Firewall is active and enabled on system startup
allowing 51413 through the firewall
Rule added
allowing 172.17.0.1 through the firewall to port 9091
Rule added
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
allowing 192.168.1.0/24 through the firewall to port 9091
Rule added
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/protonvpn/default.ovpn
Use --help for more information.
`
**Host system:**

Ubuntu 18.04

**Comment by douglasriper** [comment]
Well it works by specifying the server directly (ch-10.protonvpn.com.udp,ch-11.protonvpn.com.udp, etc.) and not the country.
It used to be the other way around for me.
So I'm closing this issue :)

**Comment by rocinante333** [comment]
I just had this issue after updating my docker image.  Specifying ch-10.protonvpn.com.udp also fixed it for me. Thank you.

**Comment by stukev** [comment]
I think this should probably be reopened. OPENVPN_CONFIG is no longer a default variable and adding it manually doesn't seem to work either. It keeps exiting on me:
![image](https://user-images.githubusercontent.com/15886207/119239204-e0970d80-bb47-11eb-83a2-1a27828b6306.png)
