### ISSUE TITLE
QNAP: LOCAL_NETWORK Environment variable seems to error

### ISSUE THREAD

**Issue by grpollard** [haugene/docker-transmission-openvpn#1193]
Hi,

I was able to get this container working on my QNAP (Local IP: 192.168.86.120). However, I'm having issues trying to access the WebUI.  I've set the LOCAL_NETWORK as such in the config.v2.json file (Unclear if this is Qnap specific, but this is where the ENV variables are):  **"LOCAL_NETWORK=http://192.168.0.0/24"**
per https://haugene.github.io/docker-transmission-openvpn/access/

When I run the container, it does run and the OpenVPN instance is running. However, in the logs I see the following:

**adding route to local network http://192.168.0.0/24 via 10.0.3.1 dev eth0                                                                                                                      
Error: any valid prefix is expected rather than "http://192.168.0.0/24".** 

I've tried changing the Network settings for the container from NAT to Bridge mode per this thread:
https://github.com/haugene/docker-transmission-openvpn/issues/1044

Is my syntax correct in the LOCAL_NETWORK environmental variable above? I copied the same syntax as other ENVs in the json file.  Changing other ENVs works, I had to set OpenVPN credentials this way to get the OpenVPN service to work.

From the logs below, I believe my Transmission IP should be 10.35.0.25 locally? I am trying to access it using  10.35.0.25:9091

Wed May 20 22:26:19 2020 /sbin/ip route add 88.202.177.234/32 via 10.0.3.1                                                                                                                  
Wed May 20 22:26:19 2020 /sbin/ip route add 0.0.0.0/1 via 10.35.0.25                                                                                                                        
Wed May 20 22:26:19 2020 /sbin/ip route add 128.0.0.0/1 via 10.35.0.25                                                                                                                      
Wed May 20 22:26:19 2020 /sbin/ip route add 10.35.0.1/32 via 10.35.0.25                                                                                                                     
Wed May 20 22:26:19 2020 Initialization Sequence Completed  

I can provide Docker full logs if needed unless there is an easy fix for the LOCAL_NETWORK error above.

Thanks!

**Comment by pkishino** [comment]
Remove http://

**Comment by grpollard** [comment]
Thanks, that removed that error!

However, now I can't figure out how get into the transmission webui.  Below is my setup of IPs/VIPs

I am connecting to the Qnap over IP:120, shown below.

![Screen1](https://user-images.githubusercontent.com/9450320/82610389-45fa9c00-9b8c-11ea-9b91-29c345eeb2eb.png)

![Screen2](https://user-images.githubusercontent.com/9450320/82610444-5f034d00-9b8c-11ea-9b31-4d7b41f1baf4.png)
