### ISSUE TITLE
Supplied config US\ Dallas.ovpn could not be found

### ISSUE THREAD

**Issue by mbourgon** [haugene/docker-transmission-openvpn#1196]
**Describe the problem**
Using Surfshark and "US\ Dallas", I get "Supplied config US\ Dallas.ovpn could not be found. Using default openVPN gateway for provider surfshark"

**Add your docker run command**
(apologies for formatting)
sudo /usr/bin/docker run         --name transmission-openvpn         --cap-add=NET_ADMIN         -v /mnt/mydrive/:/data         -e "TRANSMISSION_DOWNLOAD_DIR=/data"         -e "TRANSMISSION_INCOMPLETE_DIR=/data"         -e "TRANSMISSION_WATCH_DIR=/data/" -e "TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true"        -e "CREATE_TUN_DEVICE=true"         -e "DROP_DEFAULT_ROUTE=true"         -e "OPENVPN_PROVIDER=SURFSHARK"         -e "OPENVPN_USERNAME=usernameisnothere"         -e "OPENVPN_PASSWORD=passwordisnothere"         -e "OPENVPN_CONFIG=US\ Dallas"         -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"         -e "TRANSMISSION_UMASK=0"      -e "TRANSMISSION_RATIO_LIMIT=2"   -e "TRANSMISSION_PEER_PORT_RANDOM_ON_START=true"         -e "LOCAL_NETWORK=192.168.50.0/24"         -p 9091:9091         --dns 8.8.8.8         --dns 8.8.4.4         haugene/transmission-openvpn:latest-armhf

**Logs**
Using OpenVPN provider: SURFSHARK
Supplied config US\ Dallas.ovpn could not be found.
Using default OpenVPN gateway for provider surfshark

**Host system:**
Raspberry Pi, 
Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:22 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by mbourgon** [comment]
"OPENVPN_CONFIG=us-dal_tcp" seems to fix it.  But is that the right way to handle it?  I think it's still an issue, albeit a lower one now.  Thanks.

**Comment by pkishino** [comment]
The config is called us-dal_tcp, so yes, that’s the correct way

**Comment by mbourgon** [comment]
@pkishino AH!  Okay, I didn't know what I was looking at.  The examples I'd found online were obviously for other providers, I just figured it was a universal syntax. Thanks!
