### ISSUE TITLE
Stopped working on Synology DS918+

### ISSUE THREAD

**Issue by Bholtland** [haugene/docker-transmission-openvpn#1197]
I've had it working for quite some time after following the steps in the documentation for Synology servers. Recently, I think since last week or so, I couldn't get it to work anymore. Nothing on my side has been updated or changed or anything, but I keep getting this error:

`Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/net/tun": no such file or directory`

**Comment by pkishino** [comment]
Possibly permission issues or so.. sure nothing updated like DSM? Try reboot it perhaps?

**Comment by Bholtland** [comment]
Thanks, I tried rebooting several times, to no prevail. I've not updated DSM, it's set on manual update. The only thing that I could link it with, is the fact that it worked before I shutdown my NAS a week ago, and this error came up after I started it up again. I checked the permissions, and that seemed okay. I will chmod/chown it again just to be sure. Thanks for your quick response!

**Comment by Bholtland** [comment]
Guess you were right after all! I followed your documentation again and now it works. Not sure what fixed it, but probably permission somewhere. Sorry for my rookie mistake and thanks for the help :)
