### ISSUE TITLE
FastestVPN default.opvn issue

### ISSUE THREAD

**Issue by JDea** [haugene/docker-transmission-openvpn#1201]
**Describe the problem**
I setup transmission on OMV5 with Docker via Portainer stacks.  If OPENVPN_CONFIG isn't specified, it uses default.opvn, but default.opvn is currently symlinked to Netherlands-UDP.ovpn. The Netherlands-UDP.ovpn file does not exist, so it throws an error when trying to use default.opvn.

Missing Netherlands-UDP.ovpn within the fastestvpn folder.
https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/fastestvpn

**Logs**
```
Using OpenVPN provider: FASTESTVPN
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.20.0.1 dev eth0
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/fastestvpn/default.ovpn
Use --help for more information.
```

**Host system:**
Raspberry Pi4 - OMV5 - Docker - Portainer

**Comment by pkishino** [comment]
Yes, you are right, should fix this
