### ISSUE TITLE
Update to transmission 3.0

### ISSUE THREAD

**Issue by varac** [haugene/docker-transmission-openvpn#1202]
Please provide an updated docker image which includes the latest [transmission 3.0 release](
https://github.com/transmission/transmission/releases/tag/3.00) which just got released.
Thanks !

**Comment by jpoggi** [comment]
Hi,

I think this would be done automatically on the next build, as soon as the ppa use in the Dockerfile will provide the third version of transmission :-)

**Comment by varac** [comment]
3.0 is already uploaded to the ppa:

http://ppa.launchpad.net/transmissionbt/ppa/ubuntu/pool/main/t/transmission/

ok, I'll wait for the next build, wonder on what condition it gets triggered... ?

**Comment by jpoggi** [comment]
IDK,

I have try building a new images by specifying a version of transmission without success.

I'm not sure if i'm selecting the correct version

The docker build stop at:

```
E: Version '3.00-1ubuntu1~' for 'transmission-cli' was not found
E: Version '3.00-1ubuntu1~' for 'transmission-common' was not found
E: Version '3.00-1ubuntu1~' for 'transmission-daemon' was not found
```

**Comment by claptrap251** [comment]
Don't think you need to specify version, it'll automatically pick the latest one.

**Comment by auanasgheps** [comment]
I just received an updated container image that contains the 3.0 version.

**Comment by pkishino** [comment]
yes, as mentioned above, this should update when the new image is built

**Comment by bbender716** [comment]
Hey guys, I re-pulled  the image for armhf (pi) and it seems like its still running the prev version of Transmission. Any ideas? @pkishino

**Comment by pkishino** [comment]
You need to rebuild the image, not pull it.. pulling will just get the
latest release version which isn’t updated yet.
If you clone the repo and build master branch dockerfile it will grab it

**Comment by varac** [comment]
This is not about how to build the image itself but a request to update the [haugene/transmission-openvpn](https://hub.docker.com/r/haugene/transmission-openvpn) image on docker hub.

**Comment by pkishino** [comment]
yes, for the next release this will be updated, still a few things left before we create a new release..so in the mean time, if you want an updated image you are free to build it yourself

**Comment by bbender716** [comment]
I rebuilt the image using Dockerfile.armhf and still ended up with transmission 2.94. Any ideas?

**Comment by pkishino** [comment]
Just checked.. the armhf is currently based on buster which has 2.94 as latest version available..from bullseye it's up at 3.0, thats why. @haugene we should discuss the next release, decide on dropping ubuntu and perhaps upping arm to bullseye etc..

**Comment by Draxter** [comment]
Almost 2 years later, and the `latest` tag created in February 2022 for the image on the docker hub still has the `2.94` version of Transmission. Am I missing something? I'm using the amd64 arch.

**Comment by Draxter** [comment]
@pkishino Almost 2 years later, and the `latest` tag created in February 2022 for the image on the docker hub still has the `2.94` version of Transmission. Am I missing something? I'm using the amd64 arch.

**Comment by pkishino** [comment]
Please read the discussion topic on the 4.0 release for reasons

**Comment by Draxter** [comment]
@pkishino OK, understood. 2.94 is more stable. 

Here’s a discussion on the topic if anyone reads this issue in the future: https://github.com/haugene/docker-transmission-openvpn/discussions/1937

**Comment by Draxter** [comment]
@pkishino OK, understood. 2.94 is more stable and doesn’t have an annoying bug. 

Here’s a discussion on the topic if anyone reads this issue in the future: https://github.com/haugene/docker-transmission-openvpn/discussions/1937
