### ISSUE TITLE
Do I need a separate VPN network container?

### ISSUE THREAD

**Issue by drego05** [haugene/docker-transmission-openvpn#1204]
Do I need to have a separate PIA VPN network created to run this and be able to connect to it via the GUI? I've run this in Docker and I know it connects successfully because I've ran an IP check against it, but maybe I'm missing something because I'm unable to hit the GUI at :9091

I know once this clicks, it'll be great -- just hit a stumbling block I guess. 

I'm pretty sure the issue I'm having is similar to this:
https://github.com/haugene/docker-transmission-openvpn/issues/860

Do I need to ports added somewhere else to be able to access the GUI locally on my network at :9091?

**Comment by drego05** [comment]
![image](https://user-images.githubusercontent.com/9039884/82762742-9a359400-9db7-11ea-8627-9d0b1143a266.png)

**Comment by pkishino** [comment]
you need to configure the LOCAL_NETWORK setting correctly, otherwise you can use also enable the proxy and use that.
https://haugene.github.io/docker-transmission-openvpn/arguments/

**Comment by drego05** [comment]
Thanks @pkishino - this is my setup. I've got the local network setup - just not sure where I'm going wrong and why it's not accessible across my internal network on port 9091

`services:
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 209.222.18.222
    - 209.222.18.218
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /srv/configs/Config/transmission:/data
  environment:
    - OPENVPN_PROVIDER=PIA
    - OPENVPN_USERNAME=PIA USERNAME
    - OPENVPN_CONFIG= CA Vancouver
    - OPENVPN_PASSWORD=PIA PASSOWRD
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.86.0/28`

**Comment by pkishino** [comment]
is the LOCAL_NETWORK the same range as your local range? e.g. I use 10.1.125.0/24 
86.0/28 seems a bit unusual

**Comment by drego05** [comment]
![File May 24, 11 04 54 PM](https://user-images.githubusercontent.com/9039884/82837475-024ead80-9e7e-11ea-9b1e-8aa629bee0bd.jpeg)

This is my current network setup. 

The times I have been able to get it to work, it's only been accessible under localhost:9091 on the computer running the docker container - correct me if I'm wrong but it should be available across the network no? say, http://hostname:9091.

Also, I'm not entirely sure what the 8888 is for, it was in the docker run command sample, i figured it was useful.

By enabling the proxy, you mean run a nginx container on that host machine and use that for the web proxy?

**Comment by pkishino** [comment]
This is the basic run, modified for your range:
```
$ docker run --cap-add=NET_ADMIN -d \
              -v /your/storage/path/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=PIA \
              -e OPENVPN_CONFIG=CA\ Toronto \
              -e OPENVPN_USERNAME=user \
              -e OPENVPN_PASSWORD=pass \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.86.0/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn
```

**Comment by drego05** [comment]
....... for the love of god, that worked. 

I checked the subnet calc and it said my network was a /28.

What did I do to config when I made it /28? and why would that not make the GUI accessible?

Thanks @pkishino -- seriously.

**Comment by pkishino** [comment]
/28 would have limited the network to 0-15 .. so it should have worked for
any ip within 0-15 but not others.

**Comment by drego05** [comment]
Thanks @pkishino  - really appreciate it.
