### ISSUE TITLE
Transmission not running, VPN connecting fine.

### ISSUE THREAD

**Issue by xianoth** [haugene/docker-transmission-openvpn#1213]
**Describe the problem**
Lost access to WebUI on 05/26/20. Restarted container with no effect. Destroyed and recreated container with no effect.  Did some digging and found that the vpn portion of the container is running as expected.  The transmission portion is not running as expected.

**Add your docker run command**
version: "3.6"
services:
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - /media/down:/data/completed
      - /media/share/Processing:/data/incomplete
      - /media/share/Blackhole:/data/watch
    environment:
      - OPENVPN_PROVIDER=VYPRVPN
      - OPENVPN_USERNAME=emailredacted
      - OPENVPN_PASSWORD=passredacted
      - OPENVPN_CONFIG="YYYYYYYYYYY"
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=10.0.0.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=pw redacted
      - TRANSMISSION_RPC_USERNAME=admin
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=0.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=3

**Logs**

Using OpenVPN provider: VYPRVPN,
Supplied config "YYYYYYYYYYY".ovpn could not be found.,
Using default OpenVPN gateway for provider vyprvpn,
Setting OPENVPN credentials...,
adding route to local network 10.0.0.0/24 via 172.19.0.1 dev eth0,
Thu May 28 12:31:43 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019,
Thu May 28 12:31:43 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08,
Thu May 28 12:31:43 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu May 28 12:31:43 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]128.90.96.16:443,
Thu May 28 12:31:43 2020 Socket Buffers: R=[212992->212992] S=[212992->212992],
Thu May 28 12:31:43 2020 UDP link local: (not bound),
Thu May 28 12:31:43 2020 UDP link remote: [AF_INET]128.90.96.16:443,
Thu May 28 12:31:43 2020 TLS: Initial packet from [AF_INET]128.90.96.16:443, sid=694a8ecf b9d86cb4,
Thu May 28 12:31:43 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Thu May 28 12:31:43 2020 VERIFY OK: depth=2, C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=Golden Frog GmbH Root CA, emailAddress=admin@goldenfrog.com,
Thu May 28 12:31:43 2020 VERIFY OK: depth=1, C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=VyprVPN Intermediate CA, emailAddress=admin@goldenfrog.com,
Thu May 28 12:31:43 2020 VERIFY X509NAME OK: C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=eu1.vyprvpn.com, emailAddress=admin@goldenfrog.com,
Thu May 28 12:31:43 2020 VERIFY OK: depth=0, C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=eu1.vyprvpn.com, emailAddress=admin@goldenfrog.com,
Thu May 28 12:31:44 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Thu May 28 12:31:44 2020 [eu1.vyprvpn.com] Peer Connection Initiated with [AF_INET]128.90.96.16:443,
Thu May 28 12:31:45 2020 SENT CONTROL [eu1.vyprvpn.com]: 'PUSH_REQUEST' (status=1),
Thu May 28 12:31:45 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 10.2.2.1,explicit-exit-notify 5,rcvbuf 524288,route-gateway 10.2.2.1,topology subnet,ping 10,ping-restart 60,ifconfig 10.2.2.204 255.255.255.0,peer-id 6,cipher AES-256-GCM',
Thu May 28 12:31:45 2020 Option 'explicit-exit-notify' in [PUSH-OPTIONS]:3 is ignored by previous <connection> blocks ,
Thu May 28 12:31:45 2020 OPTIONS IMPORT: timers and/or timeouts modified,
Thu May 28 12:31:45 2020 OPTIONS IMPORT: explicit notify parm(s) modified,
Thu May 28 12:31:45 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified,
Thu May 28 12:31:45 2020 Socket Buffers: R=[212992->425984] S=[212992->212992],
Thu May 28 12:31:45 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Thu May 28 12:31:45 2020 OPTIONS IMPORT: route options modified,
Thu May 28 12:31:45 2020 OPTIONS IMPORT: route-related options modified,
Thu May 28 12:31:45 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Thu May 28 12:31:45 2020 OPTIONS IMPORT: peer-id set,
Thu May 28 12:31:45 2020 OPTIONS IMPORT: adjusting link_mtu to 1625,
Thu May 28 12:31:45 2020 OPTIONS IMPORT: data channel crypto options modified,
Thu May 28 12:31:45 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Thu May 28 12:31:45 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Thu May 28 12:31:45 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Thu May 28 12:31:45 2020 ROUTE_GATEWAY 172.19.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:13:00:09,
Thu May 28 12:31:45 2020 TUN/TAP device tun0 opened,
Thu May 28 12:31:45 2020 TUN/TAP TX queue length set to 100,
Thu May 28 12:31:45 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=0,
Thu May 28 12:31:45 2020 /sbin/ip link set dev tun0 up mtu 1500,
Thu May 28 12:31:45 2020 /sbin/ip addr add dev tun0 10.2.2.204/24 broadcast 10.2.2.255,
Thu May 28 12:31:45 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.2.2.204 255.255.255.0 init,
Up script executed with tun0 1500 1553 10.2.2.204 255.255.255.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.2.2.204,
Generating transmission settings.json from env variables,
sed'ing True to true,
Enforcing ownership on transmission config directories,
Applying permissions to transmission config directories,
Setting owner for transmission paths to 1000:999,
Setting permission for files (644) and directories (755),
Setting permission for watch directory (775) and its files (664),
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   abc,
User uid:    1000,
User gid:    999,
-------------------------------------,
,
STARTING TRANSMISSION,
NO PORT UPDATER FOR THIS PROVIDER,
Transmission startup script complete.,
Thu May 28 12:31:46 2020 /sbin/ip route add 128.90.96.16/32 via 172.19.0.1,
Thu May 28 12:31:46 2020 /sbin/ip route add 0.0.0.0/1 via 10.2.2.1,
Thu May 28 12:31:46 2020 /sbin/ip route add 128.0.0.0/1 via 10.2.2.1,
Thu May 28 12:31:46 2020 Initialization Sequence Completed,
[2020-05-28 16:31:46.698] JSON parse failed in /data/transmission-home/settings.json at pos 2199: INVALID_NUMBER -- remaining text "02,,
    "upload-",
Thu May 28 13:31:43 2020 VERIFY OK: depth=2, C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=Golden Frog GmbH Root CA, emailAddress=admin@goldenfrog.com,
Thu May 28 13:31:43 2020 VERIFY OK: depth=1, C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=VyprVPN Intermediate CA, emailAddress=admin@goldenfrog.com,
Thu May 28 13:31:43 2020 VERIFY X509NAME OK: C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=eu1.vyprvpn.com, emailAddress=admin@goldenfrog.com,
Thu May 28 13:31:43 2020 VERIFY OK: depth=0, C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=eu1.vyprvpn.com, emailAddress=admin@goldenfrog.com,
Thu May 28 13:31:44 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Thu May 28 13:31:44 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Thu May 28 13:31:44 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,

**Host system:**

Running on Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-101-generic x86_64) server
Docker version 19.03.9, build 9d988398e7

**Comment by pkishino** [comment]
duplicate #1212
