### ISSUE TITLE
JSON Parse failed. settings.json umask value incorrect

### ISSUE THREAD

**Issue by pazk** [haugene/docker-transmission-openvpn#1219]
On start I get this error message witch halt the start. It seems like the 'umask' wont pass a number but want a text string. 

[2020-05-31 23:30:33.334] JSON parse failed in /data/transmission-home/settings.json at pos 2199: INVALID_NUMBER -- remaining text "02,,
    "upload-"

**Comment by pazk** [comment]
I solved it by removing the UMASK-parameter from my docker-compose..

**Comment by edelgado09** [comment]
Having this same issue. 

Symptoms: Cannot access the web-ui for transmission. Testing the connection in Radarr yields: 

> Unknown exception: Error getting response stream (ReadDoneAsync2): ReceiveFailure: 'http://192.168.1.4:9091/transmission/rpc'

and 

> Unable to retrieve queue and history items from Transmission: Unable to read data from the transport connection: Connection reset by peer.: 'http://192.168.1.4:9091/transmission/rpc

From transmission logs:

> NTb[rarbg]/RARBG_DO_NOT_MIRROR.exe.part': Operation not permitted,
chown: changing ownership of '/data/incomplete/Chernobyl.S01E01.1.23.45.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]': Operation not permitted,
chown: changing ownership of '/data/incomplete': Operation not permitted,
chown: changing ownership of '/data/watch': Operation not permitted,
Setting permission for files (644) and directories (755),
Setting permission for watch directory (775) and its files (664),
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   abc,
User uid:    1000,
User gid:    999,
-------------------------------------,
,
STARTING TRANSMISSION,
NO PORT UPDATER FOR THIS PROVIDER,
Transmission startup script complete.,
Sun May 31 17:52:23 2020 /sbin/ip route add 23.226.133.181/32 via 172.18.0.1,
Sun May 31 17:52:23 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1,
Sun May 31 17:52:23 2020 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1,
Sun May 31 17:52:23 2020 Initialization Sequence Completed,
[2020-05-31 17:52:23.447] JSON parse failed in /data/transmission-home/settings.json at pos 2197: INVALID_NUMBER -- remaining text "22,,
    "upload-",
Sun May 31 18:52:21 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 18:52:21 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 18:52:21 2020 VERIFY KU OK,
Sun May 31 18:52:21 2020 Validating certificate extended key usage,
Sun May 31 18:52:21 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 18:52:21 2020 VERIFY EKU OK,
Sun May 31 18:52:21 2020 VERIFY OK: depth=0, CN=us3459.nordvpn.com,
Sun May 31 18:52:21 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 18:52:21 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 18:52:21 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun May 31 19:52:21 2020 TLS: tls_process: killed expiring key,
Sun May 31 19:52:22 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 19:52:22 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 19:52:22 2020 VERIFY KU OK,
Sun May 31 19:52:22 2020 Validating certificate extended key usage,
Sun May 31 19:52:22 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 19:52:22 2020 VERIFY EKU OK,
Sun May 31 19:52:22 2020 VERIFY OK: depth=0, CN=us3459.nordvpn.com,
Sun May 31 19:52:22 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 19:52:22 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 19:52:22 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun May 31 20:52:21 2020 TLS: tls_process: killed expiring key,
Sun May 31 20:52:22 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 20:52:22 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 20:52:22 2020 VERIFY KU OK,
Sun May 31 20:52:22 2020 Validating certificate extended key usage,
Sun May 31 20:52:22 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 20:52:22 2020 VERIFY EKU OK,
Sun May 31 20:52:22 2020 VERIFY OK: depth=0, CN=us3459.nordvpn.com,
Sun May 31 20:52:22 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 20:52:22 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 20:52:22 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,

**Comment by pkishino** [comment]
please use search! this has been answered several times...
#1210
