### ISSUE TITLE
Tracker announce not working as expected

### ISSUE THREAD

**Issue by extink** [haugene/docker-transmission-openvpn#122]
When I startup this docker image the first announce of all the torrents is working as expected. Returning the list of peers, leechers and downloads. But soon after that, the announce is not working anymore. I still have an internet connection as it still downloading some torrent, but very slow (500kB/s - 1MB/s, with a 100MB/s line). PEX and DHT are working fine, because new torrents will find peers and leechers, even when the tracker announce is not working. I even tried it with and without the port forwarding of AirVPN, but got the same results.

Hope someone can help me with this bug or config fault.
### Config (AirVPN)

```
docker run \
--privileged \
--name=transmission \
--restart=always \
-d \
-v /Users/xxx/.docker/vpn.ovpn:/etc/openvpn/custom/default.ovpn \
-v /Volumes/Data/Torrents:/data \
-e OPENVPN_PROVIDER=CUSTOM \
-e OPENVPN_USERNAME=user \
-e OPENVPN_PASSWORD=pass \
-e LOCAL_NETWORK=192.168.1.0/24 \
-e TRANSMISSION_DOWNLOAD_DIR=/data/complete \
-e TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false \
-e TRANSMISSION_PEER_PORT=xxx \
-e TRANSMISSION_WATCH_DIR_ENABLED=false \
-p 9091:9091 \
haugene/transmission-openvpn
```
### Logs

```
Using OpenVPN provider: CUSTOM
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Thu Sep  8 06:44:52 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Thu Sep  8 06:44:52 2016 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Sep  8 06:44:52 2016 Control Channel Authentication: tls-auth using INLINE static key file
Thu Sep  8 06:44:52 2016 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Sep  8 06:44:52 2016 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Sep  8 06:44:52 2016 Socket Buffers: R=[212992->131072] S=[212992->131072]
Thu Sep  8 06:44:52 2016 UDPv4 link local: [undef]
Thu Sep  8 06:44:52 2016 UDPv4 link remote: [AF_INET]62.102.148.140:443
Thu Sep  8 06:44:52 2016 TLS: Initial packet from [AF_INET]62.102.148.140:443, sid=3ab7d6f5 7f78f65a
Thu Sep  8 06:44:52 2016 VERIFY OK: depth=1, C=IT, ST=IT, L=Perugia, O=airvpn.org, CN=airvpn.org CA, emailAddress=info@airvpn.org
Thu Sep  8 06:44:52 2016 Validating certificate key usage
Thu Sep  8 06:44:52 2016 ++ Certificate has key usage  00a0, expects 00a0
Thu Sep  8 06:44:52 2016 VERIFY KU OK
Thu Sep  8 06:44:52 2016 Validating certificate extended key usage
Thu Sep  8 06:44:52 2016 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Sep  8 06:44:52 2016 VERIFY EKU OK
Thu Sep  8 06:44:52 2016 VERIFY OK: depth=0, C=IT, ST=IT, L=Perugia, O=airvpn.org, CN=server, emailAddress=info@airvpn.org
Thu Sep  8 06:44:52 2016 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Thu Sep  8 06:44:52 2016 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Sep  8 06:44:52 2016 Data Channel Decrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Thu Sep  8 06:44:52 2016 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Sep  8 06:44:52 2016 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 4096 bit RSA
Thu Sep  8 06:44:52 2016 [server] Peer Connection Initiated with [AF_INET]62.102.148.140:443
Thu Sep  8 06:44:54 2016 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Thu Sep  8 06:44:54 2016 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 10.4.0.1,comp-lzo no,route-gateway 10.4.0.1,topology subnet,ping 10,ping-restart 60,ifconfig 10.4.25.197 255.255.0.0'
Thu Sep  8 06:44:54 2016 OPTIONS IMPORT: timers and/or timeouts modified
Thu Sep  8 06:44:54 2016 OPTIONS IMPORT: LZO parms modified
Thu Sep  8 06:44:54 2016 OPTIONS IMPORT: --ifconfig/up options modified
Thu Sep  8 06:44:54 2016 OPTIONS IMPORT: route options modified
Thu Sep  8 06:44:54 2016 OPTIONS IMPORT: route-related options modified
Thu Sep  8 06:44:54 2016 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Thu Sep  8 06:44:54 2016 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:03
Thu Sep  8 06:44:54 2016 TUN/TAP device tun0 opened
Thu Sep  8 06:44:54 2016 TUN/TAP TX queue length set to 100
Thu Sep  8 06:44:54 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Thu Sep  8 06:44:54 2016 /sbin/ip link set dev tun0 up mtu 1500
Thu Sep  8 06:44:54 2016 /sbin/ip addr add dev tun0 10.4.25.197/16 broadcast 10.4.255.255
Thu Sep  8 06:44:54 2016 /etc/transmission/start.sh tun0 1500 1558 10.4.25.197 255.255.0.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.4.25.197
Generating transmission settings.json from env variables
STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Thu Sep  8 06:44:59 2016 /sbin/ip route add 62.102.148.140/32 via 172.17.0.1
Thu Sep  8 06:44:59 2016 /sbin/ip route add 0.0.0.0/1 via 10.4.0.1
Thu Sep  8 06:44:59 2016 /sbin/ip route add 128.0.0.0/1 via 10.4.0.1
Thu Sep  8 06:44:59 2016 Initialization Sequence Completed
```

**Comment by logaritmisk** [comment]
I have the same issue, but I use Anonine as VPN provider. Would love to get some help as well.

**Comment by CooperBarrett** [comment]
I also have the same problem, everything works but it is EXTREMELY slow.
From my side, I have not managed to open my port:
![](https://framapic.org/sPwR9znLMhei/FYGJEd9VmJH9)

My 51413 port is open yet well on my router:
![](https://framapic.org/SGkJxlKxXH9E/W6R6jC5FKcjt)

Your port is open?

**Comment by pkishino** [comment]
You have to check if your vpn provider supports port-forwarding

**Comment by CooperBarrett** [comment]
yes but how to check, I go through OpenVPN installed on a VPS

**Comment by pkishino** [comment]
in my case I login to my provider and go to settings,there I can setup port-forwarding.
Not all providers have this available. which provider are you using?

**Comment by CooperBarrett** [comment]
The provider of my VPS? This is OVH, but for my VPN is OpenVPN Access Server

**Comment by haugene** [comment]
The OpenVPN provider you're using for your VPN connection. The thing is that it doesn't matter if you open ports on your VPS. You're using a VPN connection and all your traffic is tunneled to your VPN provider and your public IP will be the one where your VPN is terminated and let out into the internet. 

That's the whole point, right? To change which IP is visible. So then that's the IP other peers will contact and that's where the port forwarding need to be configured. Somewhere on your VPN-provider server.

**Comment by CooperBarrett** [comment]
Ok, I understood that it was in my VPN options. I show you what I like option:
![](Https://lut.im/OED0AAnnw8/8Z7npI5BBI5v5VLI)
![](Https://lut.im/Gbi0RCLT1b/gFVZsYXTv8GVELPY)
I do not see or I can set up my port.
I met you still my port configuration:
![](Https://lut.im/gEb2t64pwG/DoU9uG8Hqlfgo2gh)
I'm really sorry but I have to understand how to configure it.

**Comment by haugene** [comment]
Aha, I understand. So you're hosting your own vpn server. Then you would have to set up the routing as well. Your server will need to forward some port to the client in the container. 

We're getting a little off topic with vpn server configuration, but this is a place to start: http://superuser.com/questions/927060/openvpn-server-to-forward-incoming-connection-to-client

**Comment by CooperBarrett** [comment]
yes, that's exactly it, I host my own VPN! Sorry, I have really bad express myself ...
So, is it that I have to create a new topic?

I'll look at your link, it's not me look simple at first sight but it's worth it to have a look.

Thank you for your help !

**Comment by pkishino** [comment]
well, your problem has nothing to do with this container, I would contact whoever created your vpn software and see if they can help you.
Would seem very strange if you cannot set up your own port-forwarding.

**Comment by CooperBarrett** [comment]
_Sorry, Google trad:_

Hello,
Just for info I found the solution to my problem! My port is marked as "Open".
To start, the host (OVH) of my OpenVPN blocks port 51413, so I changed it to 55000.
Then you have to set up the forwarding rules. On the server that hosts OpenVPN, do (for 55000):
```
/sbin/iptables -A FORWARD -i eth0 -p tcp --dport 55000 -j ACCEPT
/sbin/iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 55000 -j DNAT --to 10.8.0.2:55000
```
Refresh the page and normally, the port should be Open : 
![](https://lut.im/Mq3Lg42ErP/D5JsxrT6OSM3qWli)
