### ISSUE TITLE
Transmission 3.0 not in latest image for armhf arch

### ISSUE THREAD

**Issue by bbender716** [haugene/docker-transmission-openvpn#1221]
**Is your feature request related to a problem? Please describe.**
Armhf latest isn't pulling Transmission 3.0, could this image be updated?

**Describe the solution you'd like**
Update the "latest" image for armhf to have Transmission 3.0 please :)

Hey guys, I re-pulled the image for armhf (pi) and it seems like its still running the prev version of Transmission. Any ideas?

Thanks all!

**Comment by ilike2burnthing** [comment]
When you click Settings (cog wheel, bottom left), and then About, what version does it say it's running?

**Comment by pkishino** [comment]
Duplicate #1202
