### ISSUE TITLE
Moved to a different network, now unable to start transmission

### ISSUE THREAD

**Issue by andsoitgoes** [haugene/docker-transmission-openvpn#1230]
Hi everyone,

So I’ve been using transmission for an eon now and for the last LONG while it’s been running without a hitch. 

I recently moved and it took my brain a second to realize that by changing providers I went from a 192.168.1.x network to a 10.0.0.x network. 

Updated the local network line in my script and restarted. No dice. Removed the openvpn_config line (which I actually commented on back last year!) and I’m still stuck. 

The error I’m getting now is 

`Tue Jun  2 21:46:07 2020 Initialization Sequence Completed,
2020-06-02 21:46:03 Checking line endings,
2020-06-02 21:46:03 Updating configs for docker-transmission-openvpn,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0   5901      0 --:--:-- --:--:-- --:--:--  5888,
Starting OpenVPN using config default.ovpn,
Tue Jun  2 21:46:05 2020 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019,
adding route to local network 10.0.0.0/24 via 172.17.0.1 dev eth0,
Tue Jun  2 21:46:05 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Tue Jun  2 21:46:05 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Tue Jun  2 21:46:05 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10,
Setting OPENVPN credentials...,
Tue Jun  2 21:46:05 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Tue Jun  2 21:46:05 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]107.181.177.9:1194,
Tue Jun  2 21:46:05 2020 Socket Buffers: R=[163840->163840] S=[163840->163840],
Tue Jun  2 21:46:05 2020 UDP link local: (not bound),
Tue Jun  2 21:46:05 2020 UDP link remote: [AF_INET]107.181.177.9:1194,
Tue Jun  2 21:46:05 2020 TLS: Initial packet from [AF_INET]107.181.177.9:1194, sid=ed346bf6 09640f38,
Tue Jun  2 21:46:05 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Tue Jun  2 21:46:05 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Tue Jun  2 21:46:05 2020 VERIFY KU OK,
Tue Jun  2 21:46:05 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Tue Jun  2 21:46:05 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Tue Jun  2 21:46:05 2020 Validating certificate extended key usage,
Tue Jun  2 21:46:05 2020 VERIFY EKU OK,
Tue Jun  2 21:46:05 2020 [ca701.nordvpn.com] Peer Connection Initiated with [AF_INET]107.181.177.9:1194,
Tue Jun  2 21:46:05 2020 VERIFY OK: depth=0, CN=ca701.nordvpn.com,
Tue Jun  2 21:46:05 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Tue Jun  2 21:46:06 2020 SENT CONTROL [ca701.nordvpn.com]: 'PUSH_REQUEST' (status=1),
Tue Jun  2 21:46:06 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.8.2.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.2.10 255.255.255.0,peer-id 18,cipher AES-256-GCM',
Tue Jun  2 21:46:06 2020 OPTIONS IMPORT: explicit notify parm(s) modified,
Tue Jun  2 21:46:06 2020 OPTIONS IMPORT: timers and/or timeouts modified,
Tue Jun  2 21:46:06 2020 OPTIONS IMPORT: compression parms modified,
Tue Jun  2 21:46:06 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified,
Tue Jun  2 21:46:06 2020 Socket Buffers: R=[163840->327680] S=[163840->327680],
Tue Jun  2 21:46:06 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Tue Jun  2 21:46:06 2020 OPTIONS IMPORT: route-related options modified,
Tue Jun  2 21:46:06 2020 OPTIONS IMPORT: route options modified,
Tue Jun  2 21:46:06 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Tue Jun  2 21:46:06 2020 OPTIONS IMPORT: adjusting link_mtu to 1657,
Tue Jun  2 21:46:06 2020 OPTIONS IMPORT: peer-id set,
Tue Jun  2 21:46:06 2020 OPTIONS IMPORT: data channel crypto options modified,
Tue Jun  2 21:46:06 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Tue Jun  2 21:46:06 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Tue Jun  2 21:46:06 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Tue Jun  2 21:46:06 2020 TUN/TAP device tun0 opened,
Tue Jun  2 21:46:06 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:06,
Tue Jun  2 21:46:06 2020 TUN/TAP TX queue length set to 100,
Tue Jun  2 21:46:06 2020 /sbin/ip link set dev tun0 up mtu 1500,
Tue Jun  2 21:46:06 2020 /sbin/ip addr add dev tun0 10.8.2.10/24 broadcast 10.8.2.255,
Tue Jun  2 21:46:06 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1585 10.8.2.10 255.255.255.0 init,
Up script executed with tun0 1500 1585 10.8.2.10 255.255.255.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.2.10,
Generating transmission settings.json from env variables,
sed'ing True to true,
STARTING TRANSMISSION,
Transmission startup script complete.,
NO PORT UPDATER FOR THIS PROVIDER,
Tue Jun  2 21:46:07 2020 /sbin/ip route add 107.181.177.9/32 via 172.17.0.1,
Tue Jun  2 21:46:07 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.2.1,
Tue Jun  2 21:46:07 2020 /sbin/ip route add 128.0.0.0/1 via 10.8.2.1`

I’m sure it’s just a stupid issue. My config file is:

‘ sudo docker run --name=transmission \
--cap-add=NET_ADMIN -d \
--restart=always \
-v /mnt/Volume_2/downloads/:/downloads \
-v /mnt/3TB_External/:/3TB_External \
-v /mnt/video/:/video \
-v /mnt/Volume_2/TV:/tv \
-v /etc/localtime:/etc/localtime:ro \
-e CREATE_TUN_DEVICE=true \
-e OPENVPN_PROVIDER=NORDVPN \
-e OPENVPN_USERNAME=xxxx \
-e OPENVPN_PASSWORD=xxxx \
-e WEBPROXY_ENABLED=false \
-e TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete \
-e TRANSMISSION_INCOMPLETE_DIR_ENABLED=true \
-e TRANSMISSION_DOWNLOAD_DIR=/downloads \
-e LOCAL_NETWORK=10.0.0.0/24 \
--log-driver json-file \
--log-opt max-size=10m \
-p 9091:9091 \
haugene/transmission-openvpn:latest-armhf’

Thanks as always.

**Comment by pkishino** [comment]
uhm, why would changing providers change your local network range? Are you using a new router? changed the ip range? 
what is your host ip?

**Comment by andsoitgoes** [comment]
I went from a 192 to a 10. Subnet. 

I’ve been using the same ISP for over a decade now, so I wasn’t prepared for the change. 

My local host IP is 10.0.0.x

New everything.

**Comment by pkishino** [comment]
? I think you are confusing local and external IP.. the local IP has nothing with the ISP to do..

**Comment by andsoitgoes** [comment]
Ugh. I thought I’d set a static IP and changed it. Clearly not! 

Confirmed the IP, entered it. All is fine now. Oy vey
