### ISSUE TITLE
Transmission now running on new LAN, but only getting a space error whenever downloading. 

### ISSUE THREAD

**Issue by andsoitgoes** [haugene/docker-transmission-openvpn#1233]
Okay back again. 

Got access to transmission after fiddling with the settings however it’s basically dead in the water. 

I keep getting the “out of space” error. No torrents download. Transmission correctly connects and reports the appropriate space in the location of my download however no torrents start and none progress more than a few megabytes. 

I think I’d also had something similar before but I can’t tell. Because it’s right into a docker but writing into my NAS, Which has ample space, I cannot understand how it could partially write a few megs and die. 

Again my code.

sudo docker run --name=transmission 
--cap-add=NET_ADMIN -d 
--restart=always 
-v /mnt/Volume_2/downloads/:/downloads 
-v /mnt/3TB_External/:/3TB_External 
-v /mnt/video/:/video 
-v /mnt/Volume_2/TV:/tv 
-v /etc/localtime:/etc/localtime:ro 
-e CREATE_TUN_DEVICE=true 
-e OPENVPN_PROVIDER=NORDVPN 
-e OPENVPN_USERNAME=xxxx 
-e OPENVPN_PASSWORD=xxxx 
-e WEBPROXY_ENABLED=false 
-e TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete 
-e TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
-e TRANSMISSION_DOWNLOAD_DIR=/downloads 
-e LOCAL_NETWORK=10.0.0.0/24 
--log-driver json-file 
--log-opt max-size=10m 
-p 9091:9091 
haugene/transmission-openvpn:latest-armhf’

And to confirm it’s not a nas issue I’ve moved files back and forth there with no issues. 

I’m flummoxed.

**Comment by pkishino** [comment]
You are missing the /data volume For transmission

**Comment by andsoitgoes** [comment]
> You are missing the /data volume For transmission

Strangely that didn’t solve it, I just redid the container for the 4th of 5th time and... it just worked. I had also run out of space on my Pi, but it still took a few redos
