### ISSUE TITLE
Transmission UI won't connect - container stuck at "starting" state

### ISSUE THREAD

**Issue by d4real** [haugene/docker-transmission-openvpn#1235]
Using OpenVPN provider: PIA

Supplied config "US East".ovpn could not be found.

Using default OpenVPN gateway for provider pia

Setting OPENVPN credentials...

adding route to local network 192.168.0.0/24 via 172.18.0.1 dev eth0

Tue Jun  2 16:11:09 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Tue Jun  2 16:11:09 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Tue Jun  2 16:11:09 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Jun  2 16:11:09 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.19:1198
Tue Jun  2 16:11:09 2020 UDP link local: (not bound)
Tue Jun  2 16:11:09 2020 UDP link remote: [AF_INET]172.98.67.19:1198
Tue Jun  2 16:11:10 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Jun  2 16:11:10 2020 [5d5860941f0cccd172759f15b664853b] Peer Connection Initiated with [AF_INET]172.98.67.19:1198
Tue Jun  2 16:11:16 2020 TUN/TAP device tun0 opened
Tue Jun  2 16:11:16 2020 /sbin/ip link set dev tun0 up mtu 1500
Tue Jun  2 16:11:16 2020 /sbin/ip addr add dev tun0 local 10.6.10.10 peer 10.6.10.9
Tue Jun  2 16:11:16 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.6.10.10 10.6.10.9 init

Up script executed with tun0 1500 1558 10.6.10.10 10.6.10.9 init

Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.6.10.10

Generating transmission settings.json from env variables

sed'ing True to true

Enforcing ownership on transmission config directories

Applying permissions to transmission config directories

Setting owner for transmission paths to 1000:999

Setting permission for files (644) and directories (755)

Setting permission for watch directory (775) and its files (664)

-------------------------------------

Transmission will run as

-------------------------------------
User name:   abc
User uid:    1000
User gid:    999
-------------------------------------

STARTING TRANSMISSION

CONFIGURING PORT FORWARDING

Transmission startup script complete.

Wait for tunnel to be fully initialized and PIA is ready to give us a port

Tue Jun  2 16:11:16 2020 Initialization Sequence Completed

[2020-06-02 16:11:16.675] JSON parse failed in /data/transmission-home/settings.json at pos 2202: INVALID_NUMBER -- remaining text "22,

    "upload-"

Generating new client id for PIA

Got new port 55753 from PIA
transmission auth required

waiting for transmission to become responsive
[2020-06-02 16:11:32.824] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-06-02 16:11:42.842] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server

**Describe the problem**

The Transmission web UI will not load and gives the error "refuses to connect" each time.  Chrome browser shows the error: ERR_CONNECTION_REFUSED

The status of the container always shows the health as "starting" but the container never fully starts it seems.

CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                            PORTS                              NAMES
691b8912c099        haugene/transmission-openvpn   "dumb-init /etc/open…"   9 minutes ago       Up 9 minutes (health: starting)   8888/tcp, 0.0.0.0:9091->9091/tcp   transmission-vpn

**Add your docker run command**

transmission-vpn:
      container_name: transmission-vpn
      image: haugene/transmission-openvpn
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun
      restart: always
      ports:
      - "9091:9091"
      dns:
        - 1.1.1.1
        - 1.0.0.1
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ${USERDIR}/docker/transmission-vpn:/data
        - ${USERDIR}/docker/shared:/shared
        - ${USERDIR}/Downloads:/data/watch
        - ${USERDIR}/Downloads/completed:/data/completed
        - ${USERDIR}/Downloads/incomplete:/data/incomplete
      environment:
        - OPENVPN_PROVIDER=PIA
        - OPENVPN_USERNAME=username
        - OPENVPN_PASSWORD=password
        - OPENVPN_CONFIG="US East"
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - LOCAL_NETWORK=192.168.0.0/24
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
        - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.0.20"
        - TRANSMISSION_RPC_PASSWORD=password
        - TRANSMISSION_RPC_USERNAME=username
        - TRANSMISSION_UMASK=022
        - TRANSMISSION_RATIO_LIMIT=1.00
        - TRANSMISSION_RATIO_LIMIT_ENABLED=true

**Logs**

Using OpenVPN provider: PIA
Starting OpenVPN using config US East.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.18.0.1 dev eth0
Wed Jun  3 07:15:20 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Wed Jun  3 07:15:20 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Wed Jun  3 07:15:20 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Jun  3 07:15:20 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]193.37.253.36:1198
Wed Jun  3 07:15:20 2020 UDP link local: (not bound)
Wed Jun  3 07:15:20 2020 UDP link remote: [AF_INET]193.37.253.36:1198
Wed Jun  3 07:15:20 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Jun  3 07:15:20 2020 [d4f95c520985db8fcd4e59a8c9751b13] Peer Connection Initiated with [AF_INET]193.37.253.36:1198
Wed Jun  3 07:15:21 2020 TUN/TAP device tun0 opened
Wed Jun  3 07:15:21 2020 /sbin/ip link set dev tun0 up mtu 1500
Wed Jun  3 07:15:21 2020 /sbin/ip addr add dev tun0 local 10.38.10.6 peer 10.38.10.5
Wed Jun  3 07:15:21 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.38.10.6 10.38.10.5 init
Up script executed with tun0 1500 1558 10.38.10.6 10.38.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.38.10.6
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1000:999
Setting permission for files (644) and directories (755)
Setting permission for watch directory (775) and its files (664)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    999
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Wed Jun  3 07:15:21 2020 Initialization Sequence Completed
[2020-06-03 07:15:21.573] JSON parse failed in /data/transmission-home/settings.json at pos 2202: INVALID_NUMBER -- remaining text "22,
    "upload-"
Generating new client id for PIA
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 7

**Host system:**

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

Docker version 18.06.1-ce, build e68fc7a
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by pkishino** [comment]
Please use search.. this has been answered several times #1210
