### ISSUE TITLE
Unhealthy container after latest update

### ISSUE THREAD

**Issue by mhbates** [haugene/docker-transmission-openvpn#1236]
**Describe the problem**
I'm getting repeated notifications that the container is unhealthy. I've restarted the container, removed and set it up again from scratch (besides the mounted volume of course), but it keeps becoming unhealthy after what seems like a random amount of time.

I'll plan on rolling back to the previous image and confirm that one still functions okay.

**Add your docker run command**
```
docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \
	-v /data:/data \
	-v /etc/localtime:/etc/localtime:ro \
	-v /music:/music \
	-v /media:/media \
	-e OPENVPN_PROVIDER=PIA \
	-e OPENVPN_CONFIG=CA\ Vancouver \
	-e OPENVPN_USERNAME=xxx \
	-e OPENVPN_PASSWORD=xxx \
	-e ENABLE_UFW=true \
	-e WEBPROXY_ENABLED=false \
	-e LOCAL_NETWORK=xxxxxxx/24 \
	--log-driver json-file \
	--log-opt max-size=10m \
	-p 9091:9091 \
	-e "TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=true" \
	-e "TRANSMISSION_SPEED_LIMIT_UP=1500" \
	-e "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true" \
	-e "TRANSMISSION_SPEED_LIMIT_DOWN=45000" \
	-e "TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true" \
	-e "TRANSMISSION_RATIO_LIMIT_ENABLED=true" \
	-e "TRANSMISSION_ALT_SPEED_DOWN=45000" \
	-e "TRANSMISSION_ALT_SPEED_UP=100" \
	-e "TRANSMISSION_ALT_SPEED_TIME_BEGIN=1020" \
	-e "TRANSMISSION_ALT_SPEED_TIME_END=1320" \
	-e "TRANSMISSION_ALT_SPEED_TIME_ENABLED=false" \
	-e "TRANSMISSION_DOWNLOAD_QUEUE_SIZE=200" \
	-e "TRANSMISSION_WEB_HOME=/data/transmission-home/web-ui" \
	-e PUID=1000 -e PGID=1000 \
	-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings" \
	--dns 209.222.18.222 \
	--dns 209.222.18.218 \
	--restart=always \
	--name transmission-openvpn \
	haugene/transmission-openvpn
```

**Logs**
The Docker logs don't seem to show anything out of the ordinary, but I can provide if needed.

**Host system:**
Docker on Debian 9 Stretch

**Comment by mhbates** [comment]
I've been looking around and I'm wondering if this issue has to do with the recent changes to the health check? As I mentioned, I'm using the latest version, created 2020-06-02 16:31:51. 

I checked the container health info of Portainer and saw this:
`PING google.com (172.217.14.206) 56(84) bytes of data. 64 bytes from sea30s01-in-f14.1e100.net (172.217.14.206): icmp_seq=1 ttl=55 time=235 ms --- google.com ping statistics --- 1 packets transmitted, 1 received, 0% packet loss, time 0ms rtt min/avg/max/mdev = 234.630/234.630/234.630/0.000 ms Network is up Openvpn process not running `

Hope this helps.

**Comment by mhbates** [comment]
Did some testing and yep, looks like that's the issue. I'm having the same problem described in the commit conversation here, https://github.com/haugene/docker-transmission-openvpn/commit/2db2ce1f0dc3dfefb2cc6a6c8313c0edf7454f31

Specifically:

> ps | grep 'openvpn --script-security' |wc| awk '{print $1}' = 0
> but
> ps -ef | grep 'openvpn --script-security' |wc| awk '{print $1}' = 2 on my system
> 
> Same for "ps | grep 'transmission-daemon' |wc| awk '{print $1}"

**Comment by mhbates** [comment]
Did some testing. Looks like the container does indeed have the updated healthcheck.sh, which is now returning 2 as expected. So apparently OpenVPN keeps failing for me. This is strange because when I'm in the container, it's showing the start time (STIME) being prior to the time of the error, "...Openvpn process not running".

**Comment by pkishino** [comment]
please use updated version or use the alpine version ( we will be dropping support for ubuntu version soon anyway..) the healthcheck was updated and found issue with non-alpine version, this was already merged in though, yesterday I believe

**Comment by mhbates** [comment]
Just loaded up the Alpine version, same issue. I think I found the problem. The commands you're using to check the OpenVPN and Transmission processes (ps -ef | grep .....) can have two valid returns instead of 1. It will return 2 if ps outputs both the process in question and the grep process that's being run. But it will equal 1 if the ps command doesn't capture grep quickly enough.

For example, I ran the commands back to back:
```
bash-5.0# ps | grep 'openvpn --script-security'
    6 root      1:48 openvpn --script-security 2 --up-delay --up /etc/openvpn/tunnelUp.sh --down /etc/openvpn/tunnelDown.sh --inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings --config /etc/openvpn/pia/CA Vancouver.ovpn
 2315 root      0:00 grep openvpn --script-security
bash-5.0# ps | grep 'openvpn --script-security'
    6 root      1:48 openvpn --script-security 2 --up-delay --up /etc/openvpn/tunnelUp.sh --down /etc/openvpn/tunnelDown.sh --inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings --config /etc/openvpn/pia/CA Vancouver.ovpn
bash-5.0# ps | grep 'openvpn --script-security'
    6 root      1:48 openvpn --script-security 2 --up-delay --up /etc/openvpn/tunnelUp.sh --down /etc/openvpn/tunnelDown.sh --inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings --config /etc/openvpn/pia/CA Vancouver.ovpn
 2319 root      0:00 grep openvpn --script-security

```

I'll keep testing and see if I can figure out a fix.

**Comment by pkishino** [comment]
ah..ran it a bunch of times but I guess I should over that case too, will add a fix

**Comment by pkishino** [comment]
please try the PR..i exclude the grep for now so only the process is checked

**Comment by mhbates** [comment]
Yep, I think that does it. Thank you!

**Comment by mcrowson** [comment]
looking forward to this fix. Thanks for being on it!

**Comment by Xaelias** [comment]
FWIW that's why pgrep is a thing vs grep :-)

**Comment by frankyw** [comment]
Same problem here, can we get this PR merged pls.
