### ISSUE TITLE
Transmission web interface and RPC

### ISSUE THREAD

**Issue by jmrushing** [haugene/docker-transmission-openvpn#1237]
Transmission web interface no longer appears to be working after latest update. Going to the usual address in my browser gives me a Connection Refused error. Also Portainer reports the container is perpetually in "Starting" status, even though the logs have stopped rolling and the container doesn't appear to be auto-restarting. The container appears to have passed the Health Check (i.e. OpenVPN seems to be working, querying google fine, and running `curl ifconfig.me` inside container returns an appropriate VPN address) In addition, Radarr reports in logs that it is unable to get a response from the Transmission RPC. Nothing about my configuration in docker-compose has changed.

docker-compose.yml and container log are attached

[docker-compose.yml.txt](https://github.com/haugene/docker-transmission-openvpn/files/4727002/docker-compose.yml.txt)
[transmission-vpn.log.txt](https://github.com/haugene/docker-transmission-openvpn/files/4727005/transmission-vpn.log.txt)

**Host system:**
Ubuntu bionic

**Comment by pkishino** [comment]
check the logs..it's quite clear..has been answered many times..
TRANSMISSION_UMASK=002 is WRONG
#1210
