### ISSUE TITLE
Docker image failing to extract on latest build

### ISSUE THREAD

**Issue by joshobriencom** [haugene/docker-transmission-openvpn#1239]
Latest docker image is failing to extract, have replicated on 2 machines, which have been able to run this docker image previously. 

Every time extract always fails at 11.7M of 113.4M

<img width="451" alt="Screen Shot 2020-06-05 at 11 56 53 am" src="https://user-images.githubusercontent.com/49133307/83828417-f5ef0e00-a723-11ea-8cc2-a73e95b6ed6b.png">

**Comment by pkishino** [comment]
```
docker pull haugene/transmission-openvpn
Using default tag: latest
latest: Pulling from haugene/transmission-openvpn
cbdc015de259: Already exists
35f8707632bb: Already exists
6b786d087f83: Already exists
31fb3cd05fdd: Already exists
91fc035a20aa: Pull complete
d077a6a3453b: Pull complete
6b0dfdc3394e: Pull complete
35c0f61740ac: Pull complete
83b4c6f01f0d: Pull complete
Digest: sha256:c8c97b9e36aff037a293ffba6b616fe47903291c0813a502d01974929504f430
Status: Downloaded newer image for haugene/transmission-openvpn:latest
docker.io/haugene/transmission-openvpn:latest
```

**Comment by pkishino** [comment]
seems like connection issues on your end

**Comment by joshobriencom** [comment]
Downloaded 5 other docker images today without issue, only having issue docker image where it always fails at extraction point, all downloads succeed, but fails at 11.7M of extracting the tar, when all previous installs on same environment have been flawless.

**Comment by pkishino** [comment]
just tried to remove and re-pull the image, no issues here (mac os) nor ubuntu server

**Comment by joshobriencom** [comment]
I also have two NAS running in different states on the other side of the country and both are WD PR2100's, so failing at the same extraction point.

**Comment by pkishino** [comment]
can you check which image that is supposed to be?

**Comment by joshobriencom** [comment]
Only what's in the screenshots so far, whether this is a docker issue only impacting Australia, however doesn't really explain why 5 other docker images worked without issue, only this one is causing a problem. 

I've also installed this docker container many times on these servers without issue, shame I decided to rebuild these servers I guess haha

**Comment by pkishino** [comment]
Still having issues? I connected to a few VPN everyone in eu/us and had no problem pulling

**Comment by joshobriencom** [comment]
Yep, there's no issue pulling it, all downloads succeed, it fails on extract and always at the same point(11.7M). 

I've now tried on 3 different WD PR2100's all in different states on different internet connections, and every time they fail at the exact same extraction point so must be a recent change which has broken this for these devices. 

This is the only docker image which is having the issue, so I'll probably have to create seperate OpenVPN and Transmission containers instead of using this docker image.

**Comment by pkishino** [comment]
Can you try with older releases to try and narrow this down? This seems
very strange, only noticeable change would be the tinyproxy commit where we
stepped up from Ubuntu 18 to 19 on the Ubuntu version. But you are getting
this issue on any release? Try alpine version?

**Comment by joshobriencom** [comment]
Happy to try that, how do I pull older releases?

I did have a look at some other users forks on docker, one fork has the latest release of this and it also failed at same point, then found another fork which is two months old and it worked perfectly. 

So I'd be happy to try going back through the releases to identify which one is successful to identify which change breaks it on WD NAS's.

**Comment by pkishino** [comment]
Well, instead of latest you could try :alpine or any of the other tags on dockerhub 
https://hub.docker.com/r/haugene/transmission-openvpn/tags

**Comment by joshobriencom** [comment]
docker pull haugene/transmission-openvpn:latest-alpine worked perfectly, I'd always used :latest previously without issue, so has the only recent (in the past say month) change been moving from Ubuntu 18 to 19?

Regardless whatever the most recent changes are, they must not be compatible with WD NAS's for whatever reason, is there any limitations using the alpine release instead of the main release?

Thanks for your suggestions to at least have the alpine release working

**Comment by pkishino** [comment]
Hello, not really, no. We will be dropping the Ubuntu version anyway with
next release I believe.. only alpine and arm going forward

**Comment by joshobriencom** [comment]
Awesome thank you
