### ISSUE TITLE
Expose SOCKS5 proxy to host

### ISSUE THREAD

**Issue by davidmpa** [haugene/docker-transmission-openvpn#1241]
**Is your feature request related to a problem? Please describe.**

This project is very good, especially the feature I like is the included TinyProxy that exposes HTTP proxy to host. I understand that the main feature of this container is to provide torrent support, and the HTTP proxy is only included to make it easier to log in private trackers.

However, it would be greatly beneficial if the proxy can be more general purpose. HTTP proxy cannot handle UDP and thus it's not possible to use this container as a router or firewall for selectively route host traffic based on application.

**Describe the solution you'd like**

There is a [similar project](https://github.com/mook/docker-openvpn-client-socks) (no Transmission) that exposes SOCKS5 to host. From what I understand, only `dante-server` needs to be installed an configured.

**Describe alternatives you've considered**

Nothing.

**Additional context**

Nothing.

Thank you

**Comment by haugene** [comment]
Re-opening for another cycle. Can't promise it'll be implemented. But I will have a look when I'm done with some other refactoring. Could be interesting.
