### ISSUE TITLE
Transmission RPC Fails to connect to server.

### ISSUE THREAD

**Issue by Justo-Lobo** [haugene/docker-transmission-openvpn#1246]
**Describe the problem**
Transmission Remote fails to connect to server. 

I've not changed my setup at all, the docker-compose is listed below. Not sure when this started failing but I noticed a health check in Portainer tonight and noticed this container was "unhealthy" and looking at the logs I could see the message. 

_[2020-06-07 23:36:40.012] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server_

I am using a unique pw for RPC, that much is blanked out below. 

If there's something I'm omitting please let me know and I'll be happy to troubleshoot or provide more detail. 

**Add your docker run command**

  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9103:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/openvpn/:/etc/openvpn/custom/
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - /media/mediadisk2gb/transmission/watch/:/data/watch
      - /media/mediadisk2gb/transmission/downloads/completed/:/data/completed
      - /media/mediadisk2gb/transmission/downloads/incomplete/:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=xxxxxxx
      - OPENVPN_PASSWORD=xxxxxxx
      - OPENVPN_CONFIG="Czech Republic"
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=xxxxxx
      - TRANSMISSION_RPC_USERNAME=admin
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=2.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=50
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete

**Logs**

Sun Jun  7 23:36:02 2020 SIGTERM[hard,] received, process exiting

Using OpenVPN provider: PIA

Supplied config "Czech Republic".ovpn could not be found.

Using default OpenVPN gateway for provider pia

Setting OPENVPN credentials...

adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0

Sun Jun  7 23:36:03 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019

Sun Jun  7 23:36:03 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10

Sun Jun  7 23:36:03 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts

Sun Jun  7 23:36:03 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.10:1198

Sun Jun  7 23:36:03 2020 UDP link local: (not bound)

Sun Jun  7 23:36:03 2020 UDP link remote: [AF_INET]172.98.67.10:1198

Sun Jun  7 23:36:03 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Sun Jun  7 23:36:03 2020 [51673f500db799e28df3cffe22990434] Peer Connection Initiated with [AF_INET]172.98.67.10:1198

Sun Jun  7 23:36:04 2020 TUN/TAP device tun0 opened

Sun Jun  7 23:36:04 2020 /sbin/ip link set dev tun0 up mtu 1500

Sun Jun  7 23:36:04 2020 /sbin/ip addr add dev tun0 local 10.21.10.10 peer 10.21.10.9

Sun Jun  7 23:36:04 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.21.10.10 10.21.10.9 init

Up script executed with tun0 1500 1558 10.21.10.10 10.21.10.9 init

Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.21.10.10

Generating transmission settings.json from env variables

sed'ing True to true

Enforcing ownership on transmission config directories

Applying permissions to transmission config directories

Setting owner for transmission paths to 1000:999

Setting permission for files (644) and directories (755)

Setting permission for watch directory (775) and its files (664)

-------------------------------------

Transmission will run as

-------------------------------------

User name:   abc

User uid:    1000

User gid:    999

-------------------------------------

STARTING TRANSMISSION

CONFIGURING PORT FORWARDING

Transmission startup script complete.

Wait for tunnel to be fully initialized and PIA is ready to give us a port

[2020-06-07 23:36:04.556] JSON parse failed in /data/transmission-home/settings.json at pos 2198: INVALID_NUMBER -- remaining text "02,

Sun Jun  7 23:36:04 2020 Initialization Sequence Completed

Got new port 21380 from PIA

transmission auth required

waiting for transmission to become responsive

[2020-06-07 23:36:19.979] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server

[2020-06-07 23:36:29.996] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server

[2020-06-07 23:36:40.012] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server

**Host system:**
Ubuntu 18.04

**Comment by pkishino** [comment]
Use search before opening new issue.. this has been covered many times.. your config is invalid
#1210
