### ISSUE TITLE
Latest Version Unhealthy

### ISSUE THREAD

**Issue by kyle-rs** [haugene/docker-transmission-openvpn#1247]
Reverting to image 2.5 and it works fine. Running on Ubuntu 20.04 Server. 

Image stays in "starting" and then goes to unhealthy.  Here is the error from the tail log:

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
[2020-06-08 04:07:56.734] JSON parse failed in /data/transmission-home/settings.json at pos 2197: INVALID_NUMBER -- remaining text "02,
    "upload-"
Sun Jun  7 21:08:01 2020 /sbin/ip route add 37.120.132.90/32 via 172.18.0.1
Sun Jun  7 21:08:01 2020 /sbin/ip route add 0.0.0.0/1 via 10.18.36.1
Sun Jun  7 21:08:01 2020 /sbin/ip route add 128.0.0.0/1 via 10.18.36.1
Sun Jun  7 21:08:01 2020 Initialization Sequence Completed

Connecting through AirVPN (connection is fine).  Here is my compose file, with some info blanked out as XXXX

  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - 9091:9091
      - XXXX:XXXX
      - XXXX:XXXX/udp
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn/default.ovpn:/etc/openvpn/custom/default.ovpn
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - ${SHAREDIR}/Downloads:/data/watch
      - ${SHAREDIR}/Downloads/completed:/data/completed
      - ${SHAREDIR}/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=user
      - OPENVPN_PASSWORD=pass
      - OPENVPN_CONFIG=default 
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.0.0/16
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_PEER_PORT=XXXX
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=XXXX
      - TRANSMISSION_RPC_USERNAME=XXXX
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true

**Comment by pkishino** [comment]
This has been covered dozen of times, please use search before opening new issues..
#1210
