### ISSUE TITLE
Ouroboros update wipes out existing torrents and data

### ISSUE THREAD

**Issue by andsoitgoes** [haugene/docker-transmission-openvpn#1249]
**Describe the problem**
I use ouroboros to update my docker containers, this works perfectly for all the various clients I use (homebridge, sonarr, radarr, jackett, etc) but when it updates transmission, everything I had is wiped out. All my seeding or downloading torrents are deleted, everything is reset to square one. 

I know I can choose to not use this method, but as I’m very forgetful I would prefer to keep it. I’m just hoping there’s a possibility to have the best of both worlds. 

**Logs**
N/a, wiped due to erasure

**Host system:**
Pi 4

**Comment by haugene** [comment]
Sounds like you're not mounting the /config volume

**Comment by haugene** [comment]
Hmm. I actually thought it would be in some of the main examples. But I see that it's not.
Just like you mount some directory `/some/storage/path:/data`, mount another to `/some/config/path:/config`

Should be stated clearly in the docs.
