### ISSUE TITLE
Container is unhealthy the moment it is deployed

### ISSUE THREAD

**Issue by JoshuaMunoz** [haugene/docker-transmission-openvpn#1250]
**Describe the problem**
I'm deploying this from Portainer, using Surfshark as my VPN to work with openVPN. When I deploy the container, I can see the port as it says its starting, then when it is running, the ports (in Portainer) go away and the container goes to status 'unhealthy.'

**Add your docker run command**
I'm deploying using the app template from Selfhosted Pro and NASHosted.

**Logs**
Tue Jun  9 17:45:02 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Tue Jun  9 17:45:02 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:04,
Tue Jun  9 17:45:02 2020 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2),
Tue Jun  9 17:45:02 2020 Exiting due to fatal error,
Using OpenVPN provider: SURFSHARK,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.160/24 via 172.17.0.1 dev eth0,
RTNETLINK answers: Operation not permitted,
Tue Jun  9 17:45:53 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019,
Tue Jun  9 17:45:53 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10,
Tue Jun  9 17:45:53 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Tue Jun  9 17:45:53 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Tue Jun  9 17:45:53 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Tue Jun  9 17:45:53 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]95.174.66.37:1194,
Tue Jun  9 17:45:53 2020 Socket Buffers: R=[212992->212992] S=[212992->212992],
Tue Jun  9 17:45:53 2020 UDP link local: (not bound),
Tue Jun  9 17:45:53 2020 UDP link remote: [AF_INET]95.174.66.37:1194,
Tue Jun  9 17:45:54 2020 TLS: Initial packet from [AF_INET]95.174.66.37:1194, sid=d078626a 7d5ed54b,
Tue Jun  9 17:45:54 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Tue Jun  9 17:45:54 2020 VERIFY OK: depth=2, C=VG, O=Surfshark, CN=Surfshark Root CA,
Tue Jun  9 17:45:54 2020 VERIFY OK: depth=1, C=VG, O=Surfshark, CN=Surfshark Intermediate CA,
Tue Jun  9 17:45:54 2020 VERIFY KU OK,
Tue Jun  9 17:45:54 2020 Validating certificate extended key usage,
Tue Jun  9 17:45:54 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Tue Jun  9 17:45:54 2020 VERIFY EKU OK,
Tue Jun  9 17:45:54 2020 VERIFY OK: depth=0, CN=no-osl-v002.prod.surfshark.com,
Tue Jun  9 17:45:54 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1633', remote='link-mtu 1581',
Tue Jun  9 17:45:54 2020 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM',
Tue Jun  9 17:45:54 2020 WARNING: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]',
Tue Jun  9 17:45:54 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA,
Tue Jun  9 17:45:54 2020 [no-osl-v002.prod.surfshark.com] Peer Connection Initiated with [AF_INET]95.174.66.37:1194,
Tue Jun  9 17:45:56 2020 SENT CONTROL [no-osl-v002.prod.surfshark.com]: 'PUSH_REQUEST' (status=1),
Tue Jun  9 17:45:56 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 162.252.172.57,dhcp-option DNS 149.154.159.92,redirect-gateway def1,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,block-outside-dns,route-gateway 10.8.8.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.8.2 255.255.255.0,peer-id 1,cipher AES-256-GCM',
Tue Jun  9 17:45:56 2020 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:7: block-outside-dns (2.4.7),
Tue Jun  9 17:45:56 2020 OPTIONS IMPORT: timers and/or timeouts modified,
Tue Jun  9 17:45:56 2020 OPTIONS IMPORT: explicit notify parm(s) modified,
Tue Jun  9 17:45:56 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified,
Tue Jun  9 17:45:56 2020 Socket Buffers: R=[212992->425984] S=[212992->425984],
Tue Jun  9 17:45:56 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Tue Jun  9 17:45:56 2020 OPTIONS IMPORT: route options modified,
Tue Jun  9 17:45:56 2020 OPTIONS IMPORT: route-related options modified,
Tue Jun  9 17:45:56 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Tue Jun  9 17:45:56 2020 OPTIONS IMPORT: peer-id set,
Tue Jun  9 17:45:56 2020 OPTIONS IMPORT: adjusting link_mtu to 1656,
Tue Jun  9 17:45:56 2020 OPTIONS IMPORT: data channel crypto options modified,
Tue Jun  9 17:45:56 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Tue Jun  9 17:45:56 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Tue Jun  9 17:45:56 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Tue Jun  9 17:45:56 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:04,
Tue Jun  9 17:45:56 2020 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2),
Tue Jun  9 17:45:56 2020 Exiting due to fatal error,
Using OpenVPN provider: SURFSHARK,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.160/24 via 172.17.0.1 dev eth0,
RTNETLINK answers: Operation not permitted,
Tue Jun  9 17:46:56 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019,
Tue Jun  9 17:46:56 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10,
Tue Jun  9 17:46:56 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Tue Jun  9 17:46:56 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Tue Jun  9 17:46:56 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Tue Jun  9 17:46:56 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]95.174.66.39:1194,
Tue Jun  9 17:46:56 2020 Socket Buffers: R=[212992->212992] S=[212992->212992],
Tue Jun  9 17:46:56 2020 UDP link local: (not bound),
Tue Jun  9 17:46:56 2020 UDP link remote: [AF_INET]95.174.66.39:1194,
Tue Jun  9 17:46:56 2020 TLS: Initial packet from [AF_INET]95.174.66.39:1194, sid=ff299ee7 92d66018,
Tue Jun  9 17:46:56 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Tue Jun  9 17:46:57 2020 VERIFY OK: depth=2, C=VG, O=Surfshark, CN=Surfshark Root CA,
Tue Jun  9 17:46:57 2020 VERIFY OK: depth=1, C=VG, O=Surfshark, CN=Surfshark Intermediate CA,
Tue Jun  9 17:46:57 2020 VERIFY KU OK,
Tue Jun  9 17:46:57 2020 Validating certificate extended key usage,
Tue Jun  9 17:46:57 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Tue Jun  9 17:46:57 2020 VERIFY EKU OK,
Tue Jun  9 17:46:57 2020 VERIFY OK: depth=0, CN=no-osl-v003.prod.surfshark.com,
Tue Jun  9 17:46:57 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1633', remote='link-mtu 1581',
Tue Jun  9 17:46:57 2020 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM',
Tue Jun  9 17:46:57 2020 WARNING: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]',
Tue Jun  9 17:46:57 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA,
Tue Jun  9 17:46:57 2020 [no-osl-v003.prod.surfshark.com] Peer Connection Initiated with [AF_INET]95.174.66.39:1194,
Tue Jun  9 17:46:58 2020 SENT CONTROL [no-osl-v003.prod.surfshark.com]: 'PUSH_REQUEST' (status=1),
Tue Jun  9 17:46:58 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 162.252.172.57,dhcp-option DNS 149.154.159.92,redirect-gateway def1,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,block-outside-dns,route-gateway 10.8.8.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.8.5 255.255.255.0,peer-id 1,cipher AES-256-GCM',
Tue Jun  9 17:46:58 2020 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:7: block-outside-dns (2.4.7),
Tue Jun  9 17:46:58 2020 OPTIONS IMPORT: timers and/or timeouts modified,
Tue Jun  9 17:46:58 2020 OPTIONS IMPORT: explicit notify parm(s) modified,
Tue Jun  9 17:46:58 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified,
Tue Jun  9 17:46:58 2020 Socket Buffers: R=[212992->425984] S=[212992->425984],
Tue Jun  9 17:46:58 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Tue Jun  9 17:46:58 2020 OPTIONS IMPORT: route options modified,
Tue Jun  9 17:46:58 2020 OPTIONS IMPORT: route-related options modified,
Tue Jun  9 17:46:58 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Tue Jun  9 17:46:58 2020 OPTIONS IMPORT: peer-id set,
Tue Jun  9 17:46:58 2020 OPTIONS IMPORT: adjusting link_mtu to 1656,
Tue Jun  9 17:46:58 2020 OPTIONS IMPORT: data channel crypto options modified,
Tue Jun  9 17:46:58 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Tue Jun  9 17:46:58 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Tue Jun  9 17:46:58 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Tue Jun  9 17:46:58 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:04,
Tue Jun  9 17:46:58 2020 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2),
Tue Jun  9 17:46:58 2020 Exiting due to fatal error,

**Host system:**
Debian 10 NAS

**Docker version**

debian@debian:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:11:17 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by pkishino** [comment]
please post the config..or at least link to the configs you are using
It looks like it cannot create the TUN/TAP .. so need to see the config

**Comment by theAkito** [comment]
> Tue Jun 9 17:46:58 2020 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2),

All you need to do is the following:
```
mknod /dev/net/tun
```

That is usual behaviour with OpenVPN within Docker.

**Comment by c-schaer** [comment]
I fixed this by adding this to my docker-compose.
`devices:
    - /dev/net/tun`
Not sure why the error showed up in the first place though.
