### ISSUE TITLE
cannot disable ipv6 via portainer template

### ISSUE THREAD

**Issue by SelfhostedPro** [haugene/docker-transmission-openvpn#1252]
**Is your feature request related to a problem? Please describe.**
I'm currently unable to use --sysctl net.ipv6.conf.all.disable_ipv6=0 via portainer's web interface so I'm unable to create an app template that will launch this easily:
https://github.com/SelfhostedPro/selfhosted_templates

**Describe the solution you'd like**
I would like an env variable to disable ipv6

**Describe alternatives you've considered**
I could set this via a command line but I would like to make these templates as easy to use as possible.

**Comment by pkishino** [comment]
according to this:
https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime
it needs to be set at runtime when starting the container, not from within.. so either in your docker run command or docker-compose.
Portainer is limited by docker compose version..

**Comment by SelfhostedPro** [comment]
Yeah it is. I'm trying to see if there's a flag/env variable to have openvpn itself ignore the ipv6 settings in the configuration so I don't need to disable it at runtime.

**Comment by chadmiller** [comment]
It can be set from the docker-compose.yaml too. It's a good idea to document what to do there, since you provide a docker-compose.yaml .

**Comment by pkishino** [comment]
updated the title so anyone searching for portainer issues can find this
