### ISSUE TITLE
Problems creating container

### ISSUE THREAD

**Issue by rubyredrick** [haugene/docker-transmission-openvpn#1253]
**Describe the problem**
docker build is failing on install of dumb-init

**Add your docker run command**

sudo docker build -t rick/transmission-openvpn .

I'm using the Dockerfile from the git repo, I have changed mine to set the environment variables for VPN.

I'm using docker build because for some reason, running the image from the registry using the Synology docker ui fails to create a persistent container. When I do that it does show the container as running but the transmission web ui is inaccessible and the container does not show up in the container list in the UI.

The build command terminates with:

Processing triggers for mime-support (3.63ubuntu1) ...
--2020-06-12 21:27:09--  https://github.com/Yelp/dumb-init/releases/download/v/dumb-init__amd64.deb
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-12 21:27:09 ERROR 404: Not Found.

The command '/bin/sh -c apt update     && apt -y install apt-utils software-properties-common wget git curl jq     && add-apt-repository ppa:transmissionbt/ppa     && apt update     && apt install -y sudo transmission-cli transmission-common transmission-daemon curl rar unrar zip unzip ufw iputils-ping openvpn bc tzdata bash     python2.7 python2.7-pysqlite2 && ln -sf /usr/bin/python2.7 /usr/bin/python2     && apt -y upgrade     && wget https://github.com/Secretmapper/combustion/archive/release.zip     && unzip release.zip -d /opt/transmission-ui/     && rm release.zip     && mkdir /opt/transmission-ui/transmission-web-control     && curl -sL `curl -s https://api.github.com/repos/ronggang/transmission-web-control/releases/latest | jq --raw-output '.tarball_url'` | tar -C /opt/transmission-ui/transmission-web-control/ --strip-components=2 -xz     && ln -s /usr/share/transmission/web/style /opt/transmission-ui/transmission-web-control     && ln -s /usr/share/transmission/web/images /opt/transmission-ui/transmission-web-control     && ln -s /usr/share/transmission/web/javascript /opt/transmission-ui/transmission-web-control     && ln -s /usr/share/transmission/web/index.html /opt/transmission-ui/transmission-web-control/index.original.html     && git clone git://github.com/endor/kettu.git /opt/transmission-ui/kettu     && apt install -y tinyproxy telnet vim     && wget https://github.com/Yelp/dumb-init/releases/download/v${DUMBINIT_VERSION}/dumb-init_${DUMBINIT_VERSION}_amd64.deb     && dpkg -i dumb-init_${DUMBINIT_VERSION}_amd64.deb     && rm -rf dumb-init_${DUMBINIT_VERSION}_amd64.deb     && wget https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64.deb     && dpkg -i dumb-init_1.2.2_amd64.deb     && rm -rf dumb-init_1.2.2_amd64.deb     && curl -L https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-linux-${DOCKERIZE_ARCH}-${DOCKERIZE_VERSION}.tar.gz | tar -C /usr/local/bin -xzv     && apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*     && groupmod -g 1000 users     && useradd -u 911 -U -d /config -s /bin/false abc     && usermod -G users abc' returned a non-zero code: 8

**** NOTE ***
I tried to fix this but so far I've failed.  What I found is that the Debian package is no longer accessible via the url used in the Docker file. It appears instead to be at
https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64.deb

I changed the docker file to reflect this:

...
    && wget https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64.deb \
    && dpkg -i dumb-init_1.2.2_amd64.deb \
    && rm -rf dumb-init_1.2.2_amd64.deb \
...

This successfully gets the package,  but I'm now getting an error, apparently from the dpkg -I command that stdin is not in gzip format.

**Logs**

**Host system:**

sudo docker version
Password:
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.11
 Git commit:        bfed4f5
 Built:             Fri Mar 13 06:46:11 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11
  Git commit:       3a371f3
  Built:            Fri Mar 13 06:44:35 2020
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by pkishino** [comment]
Which branch? Also, try the alpine version.. will be dropping support for the Ubuntu version soon.
And the container definitely works on synology so might want to look some more into that and search the closed issues

**Comment by rubyredrick** [comment]
Well I tried the alpine Dockerfile from the master branch this morning, and I have another problem.

Sending build context to Docker daemon  32.15MB
Step 1/11 : FROM alpine:3.8
3.8: Pulling from library/alpine
486039affc0a: Pull complete
Digest: sha256:2bb501e6173d9d006e56de5bce2720eb06396803300fe1687b58a7ff32bf4c14
Status: Downloaded newer image for alpine:3.8
 ---> c8bccc0af957
Step 2/11 : VOLUME /data
 ---> Running in 6942e2595889
Removing intermediate container 6942e2595889
 ---> 0fb591c7ac8b
Step 3/11 : VOLUME /config
 ---> Running in 3bc9ec20a4fe
Removing intermediate container 3bc9ec20a4fe
 ---> ecaab230c0dc
Step 4/11 : ARG DOCKERIZE_ARCH=amd64
 ---> Running in b835aa842dd2
Removing intermediate container b835aa842dd2
 ---> cb21c00fd78d
Step 5/11 : ENV DOCKERIZE_VERSION=v0.6.0
 ---> Running in f0efd30fe429
Removing intermediate container f0efd30fe429
 ---> 51a99818b06f
Step 6/11 : RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories     && apk --no-cache add bash dumb-init ip6tables ufw@testing openvpn shadow transmission-daemon transmission-cli curl jq     && echo "Install dockerize $DOCKERIZE_VERSION ($DOCKERIZE_ARCH)"     && wget -qO- https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-$DOCKERIZE_ARCH-$DOCKERIZE_VERSION.tar.gz | tar xz -C /usr/bin     && mkdir -p /opt/transmission-ui     && echo "Install Combustion"     && wget -qO- https://github.com/Secretmapper/combustion/archive/release.tar.gz | tar xz -C /opt/transmission-ui     && echo "Install kettu"     && wget -qO- https://github.com/endor/kettu/archive/master.tar.gz | tar xz -C /opt/transmission-ui     && mv /opt/transmission-ui/kettu-master /opt/transmission-ui/kettu     && echo "Install Transmission-Web-Control"     && mkdir /opt/transmission-ui/transmission-web-control     && curl -sL `curl -s https://api.github.com/repos/ronggang/transmission-web-control/releases/latest | jq --raw-output '.tarball_url'` | tar -C /opt/transmission-ui/transmission-web-control/ --strip-components=2 -xz     && ln -s /usr/share/transmission/web/style /opt/transmission-ui/transmission-web-control     && ln -s /usr/share/transmission/web/images /opt/transmission-ui/transmission-web-control     && ln -s /usr/share/transmission/web/javascript /opt/transmission-ui/transmission-web-control     && ln -s /usr/share/transmission/web/index.html /opt/transmission-ui/transmission-web-control/index.original.html     && rm -rf /tmp/* /var/tmp/*     && groupmod -g 1000 users     && useradd -u 911 -U -d /config -s /bin/false abc     && usermod -G users abc
 ---> Running in 2492f9bbe927
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/36) Installing ncurses-terminfo-base (6.1_p20180818-r1)
(2/36) Installing ncurses-terminfo (6.1_p20180818-r1)
(3/36) Installing ncurses-libs (6.1_p20180818-r1)
(4/36) Installing readline (7.0.003-r0)
(5/36) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
(6/36) Installing ca-certificates (20191127-r2)
(7/36) Installing nghttp2-libs (1.39.2-r0)
(8/36) Installing libssh2 (1.9.0-r1)
(9/36) Installing libcurl (7.61.1-r3)
(10/36) Installing curl (7.61.1-r3)
(11/36) Installing dumb-init (1.2.1-r0)
(12/36) Installing libmnl (1.0.4-r0)
(13/36) Installing jansson (2.11-r0)
(14/36) Installing libnftnl-libs (1.1.1-r0)
(15/36) Installing iptables (1.6.2-r0)
(16/36) Installing ip6tables (1.6.2-r0)
(17/36) Installing oniguruma (6.9.4-r0)
(18/36) Installing jq (1.6_rc1-r1)
(19/36) Installing libelf (0.8.13-r3)
(20/36) Installing iproute2 (4.13.0-r0)
Executing iproute2-4.13.0-r0.post-install
(21/36) Installing lzo (2.10-r2)
(22/36) Installing openvpn (2.4.6-r3)
Executing openvpn-2.4.6-r3.pre-install
(23/36) Installing linux-pam (1.3.0-r0)
(24/36) Installing shadow (4.5-r0)
(25/36) Installing libevent (2.1.8-r5)
(26/36) Installing libintl (0.19.8.1-r2)
(27/36) Installing transmission-cli (2.94-r0)
(28/36) Installing transmission-daemon (2.94-r0)
Executing transmission-daemon-2.94-r0.pre-install
(29/36) Installing libbz2 (1.0.6-r7)
(30/36) Installing expat (2.2.8-r0)
(31/36) Installing libffi (3.2.1-r4)
(32/36) Installing gdbm (1.13-r1)
(33/36) Installing xz-libs (5.2.4-r0)
(34/36) Installing sqlite-libs (3.25.3-r4)
(35/36) Installing python3 (3.6.9-r1)
(36/36) Installing ufw@testing (0.36-r2)
Executing busybox-1.28.4-r3.trigger
Executing ca-certificates-20191127-r2.trigger
OK: 82 MiB in 49 packages
Install dockerize v0.6.0 ()
wget: server returned error: HTTP/1.1 404 Not Found
tar: invalid magic
tar: short read

Here's the beginning of the Dockerfile up to the point of error:

FROM alpine:3.8
# MAINTAINER Kristian Haugene

VOLUME /data
VOLUME /config

ARG DOCKERIZE_ARCH=amd64
ENV DOCKERIZE_VERSION=v0.6.0
RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && apk --no-cache add bash dumb-init ip6tables ufw@testing openvpn shadow transmission-daemon transmission-cli curl jq \
    && echo "Install dockerize $DOCKERIZE_VERSION ($DOCKERIZE_ARCH)" \
    && wget -qO- https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-$DOCKERIZE_ARCH-$DOCKERIZE_VERSION.tar.gz | tar xz -C /usr/bin \


It seems that the expansion of $DOCKERIZE_ARCH is not happening in the last two lines.

I'm going to try a workaround by.hard-coding that.

**Comment by theAkito** [comment]
> ARG DOCKERIZE_ARCH=amd64
> ENV DOCKERIZE_VERSION=v0.6.0

Should work when `ARG` is changed to `ENV`.

**Comment by pkishino** [comment]
the image works on synology, have you checked the wiki ? you might need the proxy setup to access ui..
and the dockerfiles all work fine, they are being build in CI and I have built them several times recently
