### ISSUE TITLE
Container Unhealthy, Transmission WebUI not responding

### ISSUE THREAD

**Issue by williamstock** [haugene/docker-transmission-openvpn#1258]
**Define the Problem:** 
I have been unable to use the container at all for the last two weeks.  It's suddenly started reporting as unhealthy, and multiple restarts, updates, remove and recreations are not working to resolve this. 

**Docker Compose**
 transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 192.168.10.1
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn/:/data
      - ${USERDIR}/docker/shared:/shared
      - /nas/Downloads:/data/watch
      - /nas/Downloads/completed:/data/completed
      - /nas/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=CA Toronto
      - OPENVPN_USERNAME=xxxx
      - OPENVPN_PASSWORD=xxxx
      - WEBPROXY_ENABLED=false
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.0.0/16
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=transmission
      - TRANSMISSION_RPC_USERNAME=transmission
      - TRANSMISSION_UMASK=000
      - TRANSMISSION_RATIO_LIMIT=0.01
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true

**Docker Logs showing the issue:**
Using OpenVPN provider: PIA
Starting OpenVPN using config CA Toronto.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/16 via 172.18.0.1 dev eth0
Thu Jun 18 22:40:19 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Thu Jun 18 22:40:19 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Thu Jun 18 22:40:19 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Jun 18 22:40:19 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.20:1198
Thu Jun 18 22:40:19 2020 UDP link local: (not bound)
Thu Jun 18 22:40:19 2020 UDP link remote: [AF_INET]172.98.67.20:1198
Thu Jun 18 22:40:19 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Jun 18 22:40:19 2020 [c367457f6f68e44f71030711bd2e5817] Peer Connection Initiated with [AF_INET]172.98.67.20:1198
Thu Jun 18 22:40:20 2020 TUN/TAP device tun0 opened
Thu Jun 18 22:40:20 2020 /sbin/ip link set dev tun0 up mtu 1500
Thu Jun 18 22:40:20 2020 /sbin/ip addr add dev tun0 local 10.41.10.6 peer 10.41.10.5
Thu Jun 18 22:40:20 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.41.10.6 10.41.10.5 init
Up script executed with tun0 1500 1558 10.41.10.6 10.41.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.41.10.6
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1000:999
Setting permission for files (644) and directories (755)
Setting permission for watch directory (775) and its files (664)

Transmission will run as
User name:   abc
User uid:    1000
User gid:    999

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Thu Jun 18 22:40:21 2020 Initialization Sequence Completed

[2020-06-19 03:40:21.370] JSON parse failed in /data/transmission-home/settings.json at pos 2210: INVALID_NUMBER -- remaining text "00,
    "upload-"

Generating new client id for PIA
Got new port 27633 from PIA
transmission auth required
waiting for transmission to become responsive
[2020-06-19 03:40:37.101] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-06-19 03:40:47.111] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-06-19 03:40:57.119] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server

**Host System**
Ubuntu 18.04

**Docker Version**
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by pkishino** [comment]
please check your log, it clearly states that your config is incorrect:
[2020-06-19 03:40:21.370] JSON parse failed in /data/transmission-home/settings.json at pos 2210: INVALID_NUMBER -- remaining text "00,
"upload-"
see #1210

**Comment by williamstock** [comment]
Yes, but I have clearly never modified that config file.  It is created on the fly from the container environment variables are far as I can tell.  I also completly deleted the container, and image, and redownloaded everything, loaded up my Docker-Compose and same error...even though the settings.json config file was the default one sent with the container. 

The setting it is referring to is set by the "TRANSMISSION_UMASK=000" line in my docker-compose file.  As best as I can tell, this is formatted correctly.   Should there be somewhere else I should be looking?
