### ISSUE TITLE
How to execute a command after initialization completed?

### ISSUE THREAD

**Issue by dawez** [haugene/docker-transmission-openvpn#1261]
**Describe the problem**

Is there a way to execute a command after the VPN connection is established in a script?

I am using this command to get the public ip address

`curl --silent ifconfig.me`

When I try on the HOST I am getting 
`31.16.XXX.XXX`

I would expect to have a different one when I am using the VPN
`116.206.X.X`

According to the openvpn documentation the command should be added in the `--up` however I tried to add curl in the `tunnelUp.sh` script but still get the same value as the HOST

If I to launch the container with the background daemon option, I can see that the address is the same [HOST] before the `Initialization Sequence Completed` and then is the VPN afterwards. I can check the public ip with the docker command.

`docker exec -it container_name curl ifconfig.me`

Putting a sleep delay in the up script also does not make any difference it seems that unless the up script is completed, the vpn connection is not established. 

Is there a way/place to execute a command after the initialization is finished?

**Comment by pkishino** [comment]
look at my PR where I started to look into creating kill switch etc related to ip check
#1231

**Comment by dawez** [comment]
@pkishino thank will look at that

At the moment the clunky solution I've found. I change the tunnelUp.sh script to

```
echo "tunnel up script"
curl --silent ifconfig.me
printf "\n"
(echo "background process" && curl --silent ifconfig.me && pkill -15 openvpn) &
```

The last line in parenthesis correctly executes the curl in the vpn and gets the expected external ip address. Still do no know why the background process is detached and use the vpn instead. Maybe that's supposed be by design of openVPN?
