### ISSUE TITLE
Use alternate Private Internet Access configs

### ISSUE THREAD

**Issue by GreatGrizzly** [haugene/docker-transmission-openvpn#1262]
I want to lower my cipher strength to lower CPU load on my RPI4. I found the appropriate Private Internet Access config exists at `openvpn/pia/ip/DE Berlin.ovpn`. My current setting is `-e "OPENVPN_CONFIG=E Frankfurt,DE Berlin"`. How can I select the appropriate config? Thanks.

**Comment by pkishino** [comment]
use a custom ovpn file and set to custom config, see wiki

**Comment by GreatGrizzly** [comment]
The wiki does not have an example for navigating into configs that have the
same name but are located in different directories.

e.g. There are multiple types of "DE Berlin.ovpn" configs.

How do I select one over the other?

**Comment by pkishino** [comment]
https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/pia

it uses the name of the file.. there is only one "DE Berlin.ovpn", there is one "tcp/DE Berlin.ovpn".. 
so specify which one you want, e.g OPENVPN_CONFIG=DE Berlin or OPENVPN_CONFIG=tcp/DE Berlin

**Comment by GreatGrizzly** [comment]
You assume people know that git doesn't recognize directories in classical
sense. The example you gave me is helpful information to put in the wiki.

**Comment by pkishino** [comment]
feel free to edit the wiki, but each provider has different folder structure/naming..while I don't agree with this and think it should all be same, this is up to whoever submits a PR for a provider/approves it.. 
not sure what you mean with this: "You assume people know that git doesn't recognize directories in classical
sense"
what does git have to do with this? The naming references them just like normal file structure <parent>/<file> ?
