### ISSUE TITLE
PrivateVPN unable to resolve

### ISSUE THREAD

**Issue by Teberon** [haugene/docker-transmission-openvpn#1263]
Since some time I receive the following error in the logs:
today at 11:57 AM Mon Jun 22 11:57:19 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
today at 11:57 AM Mon Jun 22 11:57:39 2020 RESOLVE: Cannot resolve host address: ch-zur2.pvdata.host:1194 (Temporary failure in name resolution)
today at 11:57 AM Mon Jun 22 11:57:59 2020 RESOLVE: Cannot resolve host address: ch-zur2.pvdata.host:1194 (Temporary failure in name resolution)

I have set the container to use CH Zurich 2.ovpn which can be found here:
https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/privatevpn
the first row there says "remote ch-zur2.pvdata.host 1194 udp"

I have contacted PrivateVPN and received this answer:
`Thank you for contacting PrivateVPN support.

Please replace ch-zur.pvdata.host with this server IP and then retry to connect: 217.212.245.93

Should you have further questions, you are welcome to contact us.`

Would it be possible to update the configs?

**Comment by pkishino** [comment]
either use a custom ovpn file, or better yet, send a PR with updated config :)

**Comment by Teberon** [comment]
How to use a custom ovpn file, where do I find some information, guide, documentation? What do you mean by PR?

**Comment by pkishino** [comment]
in the wiki, read the main readme file (code tab) of the this repo for
link..
PR=Pull requests, submit a change request
