### ISSUE TITLE
Windscribe & VPS & Unable access Web UI externally

### ISSUE THREAD

**Issue by thracdog** [haugene/docker-transmission-openvpn#1264]
### SUMMARY
I'm unable to connect to the Web UI externally but I am able to access localhost:9091 when tunneling through. Any guidance would be greatly appreciated! 

**Note:** 
1. I'm not sure if this is useful but in portainer, the internal network ip 172.18.0.2. I've tried using as the local network being 172.18.0.2/32, and was unsuccessful in connecting remotely and via 172.18.0.2:9091.
2. portainer shows the container is healthy.
3. performing curl ifconfig.me/ip in the container shows a different IP than that of my VPS.

### COMPOSE CONFIG
  transmission-vpn:
    image: haugene/transmission-openvpn
    container_name: transmission-vpn
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - /storage/media:/plex
      - /storage/Downloads:/data/watch
      - /storage/Downloads/completed:/data/completed
      - /storage/Downloads/incomplete:/data/incomplete
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=WINDSCRIBE
      - OPENVPN_USERNAME=<from https://windscribe.com/getconfig/openvpn>
      - OPENVPN_PASSWORD=<from https://windscribe.com/getconfig/openvpn>
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=**my.vps.ip**/32
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,172.18.*.*,**my.vps.ip**"
      - TRANSMISSION_RPC_WHITELIST_ENABLED=true
      - TRANSMISSION_RPC_WHITELIST="127.0.0.1,172.18.*.*,**my.vps.ip**,**my.remote.computer.ip**"
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_PASSWORD=rpcpassword
      - TRANSMISSION_RPC_USERNAME=rpcusername
      - TRANSMISSION_UMASK=2
      - WEBPROXY_ENABLED=false
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - DOCKER_LOG=true
    cap_add:
      - NET_ADMIN
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - "9091:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1

### LOG
Using OpenVPN provider: WINDSCRIBE,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
adding route to local network **my.vps.ip**/32 via 172.18.0.1 dev eth0,
Thu Jun 25 10:39:11 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019,
Thu Jun 25 10:39:11 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10,
Thu Jun 25 10:39:11 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Jun 25 10:39:11 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Thu Jun 25 10:39:11 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Thu Jun 25 10:39:11 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]103.77.234.211:1194,
Thu Jun 25 10:39:11 2020 UDP link local: (not bound),
Thu Jun 25 10:39:11 2020 UDP link remote: [AF_INET]103.77.234.211:1194,
Thu Jun 25 10:39:12 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Thu Jun 25 10:39:12 2020 VERIFY OK: depth=1, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Operations, CN=Windscribe Node CA,
Thu Jun 25 10:39:12 2020 VERIFY KU OK,
Thu Jun 25 10:39:12 2020 Validating certificate extended key usage,
Thu Jun 25 10:39:12 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Thu Jun 25 10:39:12 2020 VERIFY EKU OK,
Thu Jun 25 10:39:12 2020 VERIFY OK: depth=0, C=CA, ST=ON, O=Windscribe Limited, OU=Operations, CN=Windscribe Node Server 4096,
Thu Jun 25 10:39:12 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1550',
Thu Jun 25 10:39:12 2020 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM',
Thu Jun 25 10:39:12 2020 WARNING: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]',
Thu Jun 25 10:39:12 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Thu Jun 25 10:39:12 2020 [Windscribe Node Server 4096] Peer Connection Initiated with [AF_INET]103.77.234.211:1194,
Thu Jun 25 10:39:18 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Thu Jun 25 10:39:18 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Thu Jun 25 10:39:18 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Thu Jun 25 10:39:18 2020 TUN/TAP device tun0 opened,
Thu Jun 25 10:39:18 2020 /sbin/ip link set dev tun0 up mtu 1500,
Thu Jun 25 10:39:18 2020 /sbin/ip addr add dev tun0 10.121.134.26/23 broadcast 10.121.135.255,
Thu Jun 25 10:39:18 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.121.134.26 255.255.254.0 init,
Up script executed with tun0 1500 1553 10.121.134.26 255.255.254.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.121.134.26,
Generating transmission settings.json from env variables,
sed'ing True to true,
Enforcing ownership on transmission config directories,
Applying permissions to transmission config directories,
Setting owner for transmission paths to 1000:998,
Setting permission for files (644) and directories (755),
Setting permission for watch directory (775) and its files (664),
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   abc,
User uid:    1000,
User gid:    998,
-------------------------------------,
,
STARTING TRANSMISSION,
NO PORT UPDATER FOR THIS PROVIDER,
Transmission startup script complete.,
Thu Jun 25 10:39:19 2020 Initialization Sequence Completed,
[2020-06-25 10:39:20.306] Transmission 3.00 (bb6b5a062e) started (session.c:769),
[2020-06-25 10:39:20.306] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:956),
[2020-06-25 10:39:20.306] RPC Server Adding address to whitelist: 172.18.*.* (rpc-server.c:956),
[2020-06-25 10:39:20.306] RPC Server Adding address to whitelist: **my.vps.ip** (rpc-server.c:956),
[2020-06-25 10:39:20.306] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:956),
[2020-06-25 10:39:20.306] RPC Server Adding address to whitelist: 172.18.*.* (rpc-server.c:956),
[2020-06-25 10:39:20.306] RPC Server Adding address to whitelist: **my.vps.ip** (rpc-server.c:956),
[2020-06-25 10:39:20.306] RPC Server Adding address to whitelist: 69.12.91.60 (rpc-server.c:956),
[2020-06-25 10:39:20.306] RPC Server Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (rpc-server.c:1243),
[2020-06-25 10:39:20.306] RPC Server Whitelist enabled (rpc-server.c:1249),
[2020-06-25 10:39:20.306] RPC Server Password required (rpc-server.c:1254),
[2020-06-25 10:39:20.306] Port Forwarding Stopped (port-forwarding.c:196),
[2020-06-25 10:39:20.306] DHT Generating new id (tr-dht.c:389),
[2020-06-25 10:39:20.306] Using settings from "/data/transmission-home" (daemon.c:646),
[2020-06-25 10:39:20.306] Saved "/data/transmission-home/settings.json" (variant.c:1221),
[2020-06-25 10:39:20.306] transmission-daemon requiring authentication (daemon.c:674),
[2020-06-25 10:39:20.306] Watching "/data/watch" for new .torrent files (daemon.c:698),
[2020-06-25 10:40:17.307] DHT Attempting bootstrap from dht.transmissionbt.com (tr-dht.c:299),

**Comment by pkishino** [comment]
I think in your case you need to use the webproxy
