### ISSUE TITLE
ARM build to docker hub for Raspberrypi

### ISSUE THREAD

**Issue by bennyb0y** [haugene/docker-transmission-openvpn#1273]
Any chance you can publish an ARM build for raspberry pi?

**Comment by pkishino** [comment]
have you tried the arm build that is already released?

**Comment by bennyb0y** [comment]
Maybe you can point me to it? I don’t see it [published](https://hub.docker.com/r/haugene/transmission-openvpn/tags)

Only x86

**Comment by pkishino** [comment]
Dockerhub, where all the builds are ;)
https://hub.docker.com/r/haugene/transmission-openvpn/

**Comment by bennyb0y** [comment]
I see only AMD builds 


https://hub.docker.com/r/haugene/transmission-openvpn/tags

**Comment by pkishino** [comment]
cause it's a multiarch build..

**Comment by pkishino** [comment]
I've used it fine on a raspberry pi before

**Comment by bennyb0y** [comment]
latest diddnt work on RPI4

`docker pull haugene/transmission-openvpn:latest-armhf`

worked, thanks!

**Comment by edgd1er** [comment]
@pkishino 

At the moment, the way to build images define a tag for each arch. Docker is able to select the proper architecture.

There is a way to define manifest to define one tag that is multi arch. In a project, I use buildx to build for each arch using a x86_64 github runner. when running docker pull multiarch image:latest, docker download the proper image according to the architecture. I'm very new to multi arch building. I have a much simplier project (single Dockerfile, no arch specific commands) building all arch images. Implementing multi arch tags could more difficult for this project.

Example for debian images: https://hub.docker.com/_/debian?tab=tags
![image](https://user-images.githubusercontent.com/3601462/86320978-57799e00-bc38-11ea-875e-8d9bbfe22860.png)

In the building process, haugene dockerfile is modified/set with build-arg variables. I guess docke buildx imagetools could create/modify manifest to unify multi-arch under the same tag. I must say I've never gone down that path.

**Comment by bennyb0y** [comment]
I did not see this originally, but this is also well documented here:

https://haugene.github.io/docker-transmission-openvpn/run-on-arm/
