### ISSUE TITLE
Cryptostorm configs possibly out of date

### ISSUE THREAD

**Issue by snausagethedog** [haugene/docker-transmission-openvpn#1274]
None of the included Cryptostorm ovpn files connect properly. The container attempts to start up and loops when it is unable to resolve the host address. I have tried multiple DNS settings, Google, Cloudflare, Quad9, and all produce the same error. The config files on Cryptostorm's website do not match the names of those in the container and appear to be much newer.

**Comment by pkishino** [comment]
please create a PR with updated configs if you want this added to project..
