### ISSUE TITLE
Add option to disable OpenVPN

### ISSUE THREAD

**Issue by igoro00** [haugene/docker-transmission-openvpn#1277]
I can't set up vpn connection (same as #1191), but really like configuration this image has(different GUI's, max ratio etc) so I'd like an option to disable openvpn entirely(just like activ/arch-transmissionvpn which has variable VPN_ENABLED = yes/no)

**Comment by pkishino** [comment]
why not then just use the transmission docker? https://hub.docker.com/r/linuxserver/transmission/
I don't really see the point in using this container without openvpn

**Comment by Luuk2016** [comment]
> I can't set up vpn connection (same as #1191), but really like configuration this image has(different GUI's, max ratio etc) so I'd like an option to disable openvpn entirely(just like activ/arch-transmissionvpn which has variable VPN_ENABLED = yes/no)

Then just use Transmission as a standalone application... 😕

**Comment by maorcc** [comment]
Here is a **use case** for this feature request:
I want to set up Transmission on [Home Assistant](https://www.home-assistant.io/), for now without VPN. Home Assistant is a popular open smart-home automation platform. Adding applications (e.g., Transmission) to Home Assistant requires creating a docker (like this project) and then creating a [Home Assistant Add-On](https://developers.home-assistant.io/docs/add-ons) that wraps the docker. There is a well maintained Add-On for the [docker-transmission-openvpn](https://github.com/haugene/docker-transmission-openvpn) by @petersendev that can be found here: https://github.com/petersendev/hassio-addons/tree/master/transmission-openvpn .
Unfortunately, there is no other properly maintained Home Assistant Add-On for Transmission.  If there was, it would have probably been based on https://hub.docker.com/r/linuxserver/transmission/ .

Therefore, adding an option here to disable VPN would allow running Transmission on Home Assistant also without VPN, and will provide an easy option to later add an OpenVPN service.

**Comment by pkishino** [comment]
I’m well aware of HA and that add-on.
I still don’t see the point of removing/disabling a core capability of this
container. There already exists , as you linked, a basic transmission
container that can be used for this, please use that then.

Again, the whole point of THIS container is a simple end to end setup to
put transmission behind openvpn(or WireGuard on the beta..)
