### ISSUE TITLE
OpenVPN not able to connect

### ISSUE THREAD

**Issue by namekal** [haugene/docker-transmission-openvpn#128]
I currently run this docker within a Fedora 23 VM via XenServer, only 1 NIC assigned to the VM, just to have some context of structure. I also have pretty much zero experience with docker, aside from learning how to exec in to ping.

I've been having this issue for about a week where i noticed i couldn't connect to the WebUI, and found that the vpn wasn't even connecting (which the transmission-daemon relies on if I'm not mistaken)

When running the following:

```docker run --name transmission-openvpn --privileged -v /shares/:/shares -e "OPENVPN_PROVIDER=NORDVPN" -e "TRANSMISSION_DOWNLOAD_DIR=\"/shares/downloads/tv_dl\"" -e "TRANSMISSION_INCOMPLETE_DIR_ENABLED=false" -e "OPENVPN_CONFIG=us104.nordvpn.com.udp1194" -e "OPENVPN_USERNAME=username" -e "OPENVPN_PASSWORD=password" -e "LOCAL_NETWORK=10.0.0.0/24" -p 9091:9091 haugene/transmission-openvpn```

It shows the following real-time output:

```
Using OpenVPN provider: NORDVPN
Starting OpenVPN using config us104.nordvpn.com.udp1194.ovpn
Setting OPENVPN credentials...
adding route to local network 10.0.0.0/24 via 172.17.0.1 dev eth0
Sat Sep 17 03:19:03 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Sat Sep 17 03:19:03 2016 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Sat Sep 17 03:19:03 2016 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Sep 17 03:19:03 2016 Control Channel Authentication: tls-auth using INLINE static key file
Sat Sep 17 03:19:03 2016 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sat Sep 17 03:19:03 2016 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sat Sep 17 03:19:03 2016 Socket Buffers: R=[212992->131072] S=[212992->131072]
Sat Sep 17 03:19:03 2016 UDPv4 link local: [undef]
Sat Sep 17 03:19:03 2016 UDPv4 link remote: [AF_INET]206.226.72.87:1194
Sat Sep 17 03:20:03 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sat Sep 17 03:20:03 2016 TLS Error: TLS handshake failed
Sat Sep 17 03:20:03 2016 SIGUSR1[soft,tls-error] received, process restarting
Sat Sep 17 03:20:03 2016 Restart pause, 2 second(s)
Sat Sep 17 03:20:05 2016 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Sat Sep 17 03:20:05 2016 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Sep 17 03:20:05 2016 Socket Buffers: R=[212992->131072] S=[212992->131072]
Sat Sep 17 03:20:05 2016 UDPv4 link local: [undef]
Sat Sep 17 03:20:05 2016 UDPv4 link remote: [AF_INET]206.226.72.87:1194
```

In a separate window, I exec into the container to test the network:

```
root@116d90effcc4:/# ping google.com
PING google.com (172.217.4.206) 56(84) bytes of data.
64 bytes from lga15s48-in-f14.1e100.net (172.217.4.206): icmp_seq=1 ttl=54 time=12.2 ms
64 bytes from lga15s48-in-f14.1e100.net (172.217.4.206): icmp_seq=2 ttl=54 time=16.0 ms
64 bytes from lga15s48-in-f14.1e100.net (172.217.4.206): icmp_seq=3 ttl=54 time=14.9 ms
64 bytes from lga15s48-in-f14.1e100.net (172.217.4.206): icmp_seq=4 ttl=54 time=12.9 ms
64 bytes from lga15s48-in-f14.1e100.net (172.217.4.206): icmp_seq=5 ttl=54 time=13.5 ms
```

After this I'm not sure where else to go to gather/provide info. I have not changed any firewall/router settings, and this had been working for a couple months with no issues. If you require any more info, please let me know what you need.

**Comment by haugene** [comment]
Hmm, there's been some changes to the nordvpn configs apparently. #125 updated the configs and is currently on the dev tag, but I did a comparison with a fresh download of the nordvpn config zips and saw that for the config you're using the remote ip had changed. Hopefully that will fix the issue.

Try running the container again using the dev. And if that doesn't work, does some of the other configs maybe?

**Comment by namekal** [comment]
> Try running the container again using the dev. 
Ah Thank you! This worked beautifully, although idk if it was my setup or not it took me a bit to clear the images. it was giving me errors removing :latest. ended up 'rm -rf /var/lib/docker' to get a clean slate. 

Added :dev to the 'pull' and 'run' lines within systemd service and it connected the vpn and via webui with no issues, tested with "CheckMyTorrentIP"

**Comment by haugene** [comment]
Good stuff! I'll merge it to master within a couple of days, so it'll be available on the latest tag as well. I'll just bundle up some changes and make a new release.

**Comment by haugene** [comment]
For future reference, "docker rmi haugene/transmission-openvpn" and "docker rmi haugene/transmission-openvpn:latest" should do the trick. But your rm - rf cleans it all ;)

**Comment by namekal** [comment]
Thanks. I had tried docker rmi but it returned with errors and wouldnt actually remove, had to resort to rm -rf.

**Comment by haugene** [comment]
Ah, well. That's the beauty of vms and containers right. If something doesn't work, you just nuke the place and you're back ;)
