### ISSUE TITLE
OVPN Sweden config

### ISSUE THREAD

**Issue by empaa** [haugene/docker-transmission-openvpn#1282]
Sorry for being not very tech savvy and making a pull request. However, the “Sweden” config of the provider OVPN has wrong addresses for the pools:

remote pool-1.prd.se.ovpn.se 1194
remote pool-1.prd.se.ovpn.se 1195

The addresses should probably be:

remote pool-1.prd.se.ovpn.com 1194
remote pool-1.prd.se.ovpn.com 1195

**Comment by slusken** [comment]
Yes it destroyed my docker again, I fixed 2 days ago and didnt have time to post a request.

When you are fixing it can you maybe provide one for multihop also?

https://files.ovpn.com/ubuntu_cli/ovpn-se-multihop.zip
Sweden_Multi or something like that...

Servers:
remote pool-1.prd.se.ovpn.com 1201
remote pool-1.prd.se.ovpn.com 1202
remote pool-2.prd.se.ovpn.com 1201
remote pool-2.prd.se.ovpn.com 1202
remote pool-3.prd.se.ovpn.com 1201
remote pool-3.prd.se.ovpn.com 1202
remote pool-4.prd.se.ovpn.com 1201
remote pool-4.prd.se.ovpn.com 1202
