### ISSUE TITLE
rar unrar zip unzip works in amd64 but not armhf

### ISSUE THREAD

**Issue by gustafssone** [haugene/docker-transmission-openvpn#1283]
**Describe the problem**
Raspbian and similar distros doesn't include unrar /unrar-free (as it wasn't developed by the time arm based archs was emerging). Thus the section of the Dockerfile that says "rar unrar zip unzip" doesn't work, i.e. building on armhf architectures leaves these packages out. Dockerfile.armhf doesn't have them at all.

The goal is to be able to run at proper exctraction script for all filetypes for the environment variable TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME as discussed here https://github.com/haugene/docker-transmission-openvpn/issues/701 and here https://github.com/haugene/docker-transmission-openvpn/issues/75 .

Suggestion is simply to ensure they really get included in all releases (all architectures), or add the package p7zip/p7zip-full which can handle all of them (and  works on arm-based architecture). The image https://hub.docker.com/r/linuxserver/transmission/ seems to have added these too!

**Add your docker run command**
Using a custom one through ixdotai/swarm-launcher:latest, but here are all the environmental variables:
OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mssfix 1450
OPENVPN_PROVIDER=NORDVPN
OPENVPN_USERNAME=nxx@xx.com
OPENVPN_PASSWORD=xx
WEBPROXY_ENABLED=true
LOCAL_NETWORK=192.168.1.0/24
NORDVPN_COUNTRY=SE
NORDVPN_CATEGORY=legacy_p2p
NORDVPN_PROTOCOL=udp
HEALTH_CHECK_HOST=google.com
CREATE_TUN_DEVICE=true
TRANSMISSION_WEB_UI=combustion
TRANSMISSION_BLOCKLIST_ENABLED=true
TRANSMISSION_BLOCKLIST_URL=https://github.com/sahsu/transmission-blocklist/releases/latest/download/blocklist.gz
TRANSMISSION_LPD_ENABLED=true
TRANSMISSION_UTP_ENABLED=true
TRANSMISSION_DOWNLOAD_DIR=/media/Tordrive/torrent/finished
TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
TRANSMISSION_MAX_PEERS_GLOBAL=500
TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
TRANSMISSION_DOWNLOAD_QUEUE_SIZE=20
TRANSMISSION_ENCRYPTION=1
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
TRANSMISSION_RPC_PASSWORD=xx
TRANSMISSION_RPC_USERNAME=xx

**Logs**
Nothing really in the logs, but the commands gives the following output at bash:
root@mycontainer:/# unrar
bash: unrar: command not found
root@mycontainer:/# rar
bash: rar: command not found
root@mycontainer:/# tzdata
bash: tzdata: command not found
root@mycontainer:/# unzip
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.
...

**Host system:**
Linux rpi03 4.19.118-v7l+ #1311 SMP armv7l GNU/Linux - Raspbian GNU/Linux 10 (buster)
Docker Engine - Community
 Version:           19.03.12

**Comment by pkishino** [comment]
Fine with me, can you add a small PR with the updated armhf file and I can review it, thanks

**Comment by gustafssone** [comment]
> Fine with me, can you add a small PR with the updated armhf file and I can review it, thanks

Great - have a look at https://github.com/haugene/docker-transmission-openvpn/pull/1284 now.

**Comment by gustafssone** [comment]
Command 7z seems to work inside the container, thanks for the quick help. Now I just need to adapt the script!
