### ISSUE TITLE
Dockerize failing with "Exec format error" in arm64 image

### ISSUE THREAD

**Issue by Mhmccabe** [haugene/docker-transmission-openvpn#1288]

**Comment by pkishino** [comment]
Please post config, which example are you referring to?

**Comment by Mhmccabe** [comment]
a variation of the one from the dockerhub page https://hub.docker.com/r/haugene/transmission-openvpn/


version: '3.3'
services:
    transmission-openvpn:
        volumes:
            - '/share/download/:/data'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=VYPRVPN
            - OPENVPN_CONFIG=Argentina-256
            - OPENVPN_USERNAME=***********
            - OPENVPN_PASSWORD=***********
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.0.0/16
            - PUID=1000 # id of the docker user
            - PGID=100 #Change to your PGID
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 # Leave this as is
        cap_add:
            - NET_ADMIN
        ports:
            - '9091:9091'
            - '8888:8888' #Transmission Port
        image: haugene/transmission-openvpn:latest-arm64
        # container_name: vpn2
        # restart: unless-stopped

**Comment by pkishino** [comment]
hmm,seems like there is an issue with dockerize generating settings from template
@haugene looks like dockerize not working ?

**Comment by haugene** [comment]
`Exec format error` is an error message that I have seen relating to running on wrong cpu architecture before. Are you sure that you should run arm64 image and not armhf? Can you try `latest-armhf` instead?

**Comment by Mhmccabe** [comment]
Hi, 
Thanks for taking the time to respond to me, its very much appreciated 

I can confirm, I am using the image haugene/transmission-openvpn:latest-arm64, the VPN connetion was being estblished, but the boot failed when it tried to configure transmission

I've ran it again with the image that you published yesterday, I am now getting the below


the VPN connection is established correcfly, I get the following when using latest:arm64
the CPU is an Arm Cortex a57

> Tue Jul 14 20:52:17 2020 OPTIONS IMPORT: data channel crypto options modified                                                                                                                                                                                                                                              
> Tue Jul 14 20:52:17 2020 Data Channel Encrypt: Cipher 'AES-256-GCM' initialized with 256 bit key                                                                                                                                                                                                                           
> Tue Jul 14 20:52:17 2020 Data Channel Decrypt: Cipher 'AES-256-GCM' initialized with 256 bit key                                                                                                                                                                                                                           
> Tue Jul 14 20:52:17 2020 ROUTE_GATEWAY 172.29.4.1/255.255.252.0 IFACE=eth0 HWADDR=*********                                                                                                                                                                                                                        
> Tue Jul 14 20:52:17 2020 TUN/TAP device tun0 opened                                                                                                                                                                                                                                                                        
> Tue Jul 14 20:52:17 2020 TUN/TAP TX queue length set to 100                                                                                                                                                                                                                                                                
> Tue Jul 14 20:52:17 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=0                                                                                                                                                                                                                                                        
> Tue Jul 14 20:52:17 2020 /sbin/ip link set dev tun0 up mtu 1500                                                                                                                                                                                                                                                            
> Tue Jul 14 20:52:17 2020 /sbin/ip addr add dev tun0 10.2.2.171/24 broadcast 10.2.2.255                                                                                                                                                                                                                                     
> Tue Jul 14 20:52:17 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.2.2.171 255.255.255.0 init                                                                                                                                                                                                                             
> /etc/transmission/start.sh: line 4: /etc/transmission/environment-variables.sh: No such file or directory                                                                                                                                                                                                                  
> Up script executed with tun0 1500 1553 10.2.2.171 255.255.255.0 init                                                                                                                                                                                                                                                       
> Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.2.2.171                                                                                                                                                                                                                                                     
> Generating transmission settings.json from env variables                                                                                                                                                                                                                                                                   
> mkdir: missing operand                                                                                                                                                                                                                                                                                                     
> Try 'mkdir --help' for more information.                                                                                                                                                                                                                                                                                   
> /etc/transmission/start.sh: line 45: /usr/local/bin/dockerize: cannot execute binary file: Exec format error                                                                                                                                                                                                               
> sed'ing True to true                                                                                                                                                                                                                                                                                                       
> sed: can't read /settings.json: No such file or directory                                                                                                                                                                                                                                                                  
>                                                                                                                                                                                                                                                                                                                            
> -------------------------------------                                                                                                                                                                                                                                                                                      
> Transmission will run as                                                                                                                                                                                                                                                                                                   
> -------------------------------------                                                                                                                                                                                                                                                                                      
> User name:   root                                                                                                                                                                                                                                                                                                          
> User uid:    0                                                                                                                                                                                                                                                                                                             
> User gid:    0                                                                                                                                                                                                                                                                                                             
> -------------------------------------                                                                                                                                                                                                                                                                                      
>                                                                                                                                                                                                                                                                                                                            
> STARTING TRANSMISSION                                                                                                                                                                                                                                                                                                      
> NO PORT UPDATER FOR THIS PROVIDER                                                                                                                                                                                                                                                                                          
> Transmission startup script complete.                                                                                                                                                                                                                                                                                      
> /opt/tinyproxy/start.sh: line 4: /etc/transmission/environment-variables.sh: No such file or directory                                                                                                                                                                                                                     
> Tue Jul 14 20:52:17 2020 /sbin/ip route add 209.99.109.19/32 via 172.29.4.1                                                                                                                                                                                                                                                
> Tue Jul 14 20:52:17 2020 /sbin/ip route add 0.0.0.0/1 via 10.2.2.1                                                                                                                                                                                                                                                         
> Tue Jul 14 20:52:17 2020 /sbin/ip route add 128.0.0.0/1 via 10.2.2.1                                                                                                                                                                                                                                                       
> Tue Jul 14 20:52:17 2020 Initialization Sequence Completed                                                                                                                                                                                                                                                                 
> Transmission 2.92 (14714)  http://www.transmissionbt.com/                                                                                                                                                                                                                                                                  
> A fast and easy BitTorrent client                                                                                                                                                                                                                                                                                          
>                                                                                                                                                                                                                                                                                                                            
> transmission-daemon is a headless Transmission session                                                                                                                                                                                                                                                                     
> that can be controlled via transmission-remote                                                                                                                                                                                                                                                                             
> or the web interface.                                                                                                                                                                                                                                                                                                      
>                                                                                                                                                                                                                                                                                                                            
> Usage: transmission-daemon [options]                                                                                                                                                                                                                                                                                       
>                                            


when I use the haugene/transmission-openvpn:latest-armhf I get the following

> Tue Jul 14 20:52:17 2020 OPTIONS IMPORT: data channel crypto options modified                                                                                                                                                                                                                                              
> Tue Jul 14 20:52:17 2020 Data Channel Encrypt: Cipher 'AES-256-GCM' initialized with 256 bit key                                                                                                                                                                                                                           
> Tue Jul 14 20:52:17 2020 Data Channel Decrypt: Cipher 'AES-256-GCM' initialized with 256 bit key                                                                                                                                                                                                                           
> Tue Jul 14 20:52:17 2020 ROUTE_GATEWAY 172.29.4.1/255.255.252.0 IFACE=eth0 HWADDR=********                                                                                                                                                                                                                        
> Tue Jul 14 20:52:17 2020 TUN/TAP device tun0 opened                                                                                                                                                                                                                                                                        
> Tue Jul 14 20:52:17 2020 TUN/TAP TX queue length set to 100                                                                                                                                                                                                                                                                
> Tue Jul 14 20:52:17 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=0                                                                                                                                                                                                                                                        
> Tue Jul 14 20:52:17 2020 /sbin/ip link set dev tun0 up mtu 1500                                                                                                                                                                                                                                                            
> Tue Jul 14 20:52:17 2020 /sbin/ip addr add dev tun0 10.2.2.171/24 broadcast 10.2.2.255                                                                                                                                                                                                                                     
> Tue Jul 14 20:52:17 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.2.2.171 255.255.255.0 init                                                                                                                                                                                                                             
> /etc/transmission/start.sh: line 4: /etc/transmission/environment-variables.sh: No such file or directory                                                                                                                                                                                                                  
> Up script executed with tun0 1500 1553 10.2.2.171 255.255.255.0 init                                                                                                                                                                                                                                                       
> Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.2.2.171                                                                                                                                                                                                                                                     
> Generating transmission settings.json from env variables                                                                                                                                                                                                                                                                   
> mkdir: missing operand                                                                                                                                                                                                                                                                                                     
> Try 'mkdir --help' for more information.                                                                                                                                                                                                                                                                                   
> /etc/transmission/start.sh: line 45: /usr/local/bin/dockerize: cannot execute binary file: Exec format error                                                                                                                                                                                                               
> sed'ing True to true                                                                                                                                                                                                                                                                                                       
> sed: can't read /settings.json: No such file or directory                                                                                                                                                                                                                                                                  
>                                                                                                                                                                                                                                                                                                                            
> -------------------------------------                                                                                                                                                                                                                                                                                      
> Transmission will run as                                                                                                                                                                                                                                                                                                   
> -------------------------------------                                                                                                                                                                                                                                                                                      
> User name:   root                                                                                                                                                                                                                                                                                                          
> User uid:    0                                                                                                                                                                                                                                                                                                             
> User gid:    0                                                                                                                                                                                                                                                                                                             
> -------------------------------------                                                                                                                                                                                                                                                                                      
>                                                                                                                                                                                                                                                                                                                            
> STARTING TRANSMISSION                                                                                                                                                                                                                                                                                                      
> NO PORT UPDATER FOR THIS PROVIDER                                                                                                                                                                                                                                                                                          
> Transmission startup script complete.                                                                                                                                                                                                                                                                                      
> /opt/tinyproxy/start.sh: line 4: /etc/transmission/environment-variables.sh: No such file or directory                                                                                                                                                                                                                     
> Tue Jul 14 20:52:17 2020 /sbin/ip route add 209.99.109.19/32 via 172.29.4.1                                                                                                                                                                                                                                                
> Tue Jul 14 20:52:17 2020 /sbin/ip route add 0.0.0.0/1 via 10.2.2.1                                                                                                                                                                                                                                                         
> Tue Jul 14 20:52:17 2020 /sbin/ip route add 128.0.0.0/1 via 10.2.2.1                                                                                                                                                                                                                                                       
> Tue Jul 14 20:52:17 2020 Initialization Sequence Completed                                                                                                                                                                                                                                                                 
> Transmission 2.92 (14714)  http://www.transmissionbt.com/                                                                                                                                                                                                                                                                  
> A fast and easy BitTorrent client                                                                                                                                                                                                                                                                                          
>                                                                                                                                                                                                                                                                                                                            
> transmission-daemon is a headless Transmission session                                                                                                                                                                                                                                                                     
> that can be controlled via transmission-remote                                                                                                                                                                                                                                                                             
> or the web interface.                                                                                                                                                                                                                                                                                                      
>                                                                                                                                                                                                                                                                                                                            
> Usage: transmission-daemon [options]                                                                                                                                                                                                                                                                                       
>

**Comment by haugene** [comment]
I might have spoke too soon. We build the arm64 image with the same Dockerfile as armhf, but we substitute the base image with a build argument. Looking at the Dockerfile though: https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile.armhf

The Dockerize version seems to be hard coded to armhf. That might be the issue here...
https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile.armhf#L28

**Comment by haugene** [comment]
But there is no arm64 version of Dockerize 🤔 
@Mhmccabe did you try running the latest-armhf instead of latest-arm64?

**Comment by Mhmccabe** [comment]
Yes, I tried both Arm64 and armhf, both had similar issues, with the exec format error, see above

**Comment by haugene** [comment]
Ok. Maybe we should look for a possible replacement for dockerize if it doesn't support all the architectures we want to support. Looking a bit around it seems we have many good options, but I would prefer a tool that is as simple as possible and that has a small footprint on the image size as well. 

The `gettext` package has the `envsubst` program and seems to take only 8 MB. Could be a good option.
I'm leaving for a summer vacation trip tomorrow and won't be able to do anything for a week or so. If you want to submit a PR I'd gladly have a look when I'm back. If not we will follow up later.

**Comment by Mhmccabe** [comment]
Hi ,

is there any update on the resolution of this issue?

thanks

**Comment by joaovbmdias** [comment]
Dockerize has no arm64 release, but it does have armhf release. Looking into docker hub, there's no arm based version released for transmission-openvpn. All versions seem to be linux/amd64, even if the tag indicates arm.
![Screenshot from 2020-08-18 11-29-49](https://user-images.githubusercontent.com/20491883/90502841-67950080-e146-11ea-8262-cc79a83fb0cb.png)

Is this right? Because it seems that regardless the tag you use you're going to get amd64 arch.

**Comment by haugene** [comment]
That means it worked @Mhmccabe?

**Comment by Mhmccabe** [comment]
I Haven’t  done a full feature test yet, but it launches now


On 24 Aug 2020, at 7:05 pm, Kristian Haugene <notifications@github.com> wrote:

﻿

That means it worked @Mhmccabe<https://github.com/Mhmccabe>?

**Comment by haugene** [comment]
Just as an FYI. We're seeing some other issues with the arm images on the dev branch. Working to fix them though. #1341

**Comment by sametjan** [comment]
This may be moot now, but I was able to solve this problem by cloning dockerize, compiling, copying the aarch64 binary to a directory, and then mounting that directory to `/usr/local/bin`.

Here's part of my `docker-compose.yaml`:
```yaml
  transmission:
    image: haugene/transmission-openvpn:latest-arm64
    container_name: transmission
    restart: always
    ports:
      - "9091:9091"
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      -/path/to/aarch64/dockerize/bin/:/usr/local/bin # Arm64 version of dockerize
      # Rest of your volumes
    env_file:
      - docker.env
```

**Comment by haugene** [comment]
Huh, so they did have a working release. Oh well, we've stopped using Dockerize at this point and it is merged to master. Pulling the latest should remove that error. But the arm versions might still be a bit broken with the new 3.0 release @sametjan? They're next on the list for some maintenance love.

**Comment by sametjan** [comment]
The only issue I was having with the newer images on arm64 was being unable to connect to UDP trackers, but switching VPN providers from Ivacy to ExpressVPN fixed that.
