### ISSUE TITLE
Questions about how stuff works

### ISSUE THREAD

**Issue by theAkito** [haugene/docker-transmission-openvpn#1290]
I am trying to understand this, what seems like, sophisticated implementation of Transmission in conjunction with OpenVPN.
I am very familiar with OpenVPN, but have no experience with Transmission.

Looking [here](https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/environment-variables.tmpl) I see a Go template file, however I can't figure out where the processing and expansion of the values happens. I can't find Docker documentation on it and I can't find traces of that in this project.
**Where and how do the values get translated exactly?**

Secondly, when looking at the above file or at [this one](https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile.alpine), I see so many precise environment variables for setting up Transmission the correct way. However, I cannot find even remotely that many environment variables in the official Transmission documentation.
**Are those environment variables custom or are they officially supported by Transmission?**
**If they are officially supported by Transmission, where is the documentation for that?**
**If they are custom made for this project, where are they defined and used/translated to actual Transmission options?**

Thirdly, is it possible to run this implementation without the OpenVPN Part?
**Is there something like a switch to turn off the OpenVPN requirement?**

Thank you.

**Comment by pkishino** [comment]
While the questions are fine, this is not really an issue so I will close this and try to answer the questions:
1. The template are run through dockerize to use them in the project, look at #1131 for a more detailed discussion on how to use and how the plan is to keep them persistant
2. they are all transmission configuration settings. Think they are all covered here: https://github.com/transmission/transmission/wiki/Editing-Configuration-Files
3. No, if you don't want the Openvpn part, better of run transmission directly
