### ISSUE TITLE
Alpine image not building due to ufw package issues

### ISSUE THREAD

**Issue by haugene** [haugene/docker-transmission-openvpn#1291]
Trying to build the alpine image it fails with:
```
ERROR: unsatisfiable constraints:
  ufw (missing):
    required by: world[ufw]
```

Looking at this package search it seems that ufw has been removed from edge/testing repo?
https://pkgs.alpinelinux.org/packages?name=ufw&branch=edge

Looking for some confirmation, but it seems it has been moved to the community repo. Maybe we should add that as well.

EDIT: It says that it should be in `testing`. https://wiki.alpinelinux.org/wiki/Uncomplicated_Firewall

**Comment by arcticaurora** [comment]
yeah. You can update @testing url to "http://dl-cdn.alpinelinux.org/alpine/edge/community"
