### ISSUE TITLE
CyberGhost

### ISSUE THREAD

**Issue by ingo2000** [haugene/docker-transmission-openvpn#1298]
**Which provider?**
Cyberghost
https://my.cyberghostvpn.com/

**Where are the configs?**

[openvpn.zip](https://github.com/haugene/docker-transmission-openvpn/files/4942827/openvpn.zip)

**Comment by vincentlabatut** [comment]
Hi,
Did you manage to set it up ? I have problems with transmission, but I feel this VPN is working for me.
I used a custom VPN.

**Comment by pkishino** [comment]
please create a PR with updated configs

**Comment by ingo2000** [comment]
Hello,
I also managed to get it working with custom VPN. So from my side I'm all set. 
However, if interested, I can contribute the required config files to make it a selectable option.  I jut need to know which files are mandatory for the configuration.
