### ISSUE TITLE
Cannot resolve host address

### ISSUE THREAD

**Issue by cwilford** [haugene/docker-transmission-openvpn#1299]
Hi all, 
I am having issues getting OpenVPN to connect using Torguard, from other issues I've read it appears to be a DNS resolution issue. I have not modified resolv.conf, I am passing DNS values in the docker-compose.yml file. I have tried the servers with quotes and without, and changing its location to above 'environment'. I am new to Docker and I have tried everything I have found with no luck, any help will be greatly appreciated!

**I can ping the server:**
PING us-sf.secureconnect.me (206.189.64.126) 56(84) bytes of data.
64 bytes from 206.189.64.126 (206.189.64.126): icmp_seq=1 ttl=52 time=39.9 ms
64 bytes from 206.189.64.126 (206.189.64.126): icmp_seq=2 ttl=52 time=31.5 ms
64 bytes from 206.189.64.126 (206.189.64.126): icmp_seq=3 ttl=52 time=38.9 ms
64 bytes from 206.189.64.126 (206.189.64.126): icmp_seq=4 ttl=52 time=29.6 ms
^C
--- us-sf.secureconnect.me ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 8ms
rtt min/avg/max/mdev = 29.599/34.941/39.852/4.479 ms

**and the DNS servers:** 
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=116 time=42.10 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=116 time=40.6 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=116 time=41.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=116 time=41.0 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=116 time=40.9 ms
^C

PING 8.8.4.4 (8.8.4.4) 56(84) bytes of data.
64 bytes from 8.8.4.4: icmp_seq=1 ttl=116 time=40.1 ms
64 bytes from 8.8.4.4: icmp_seq=2 ttl=116 time=41.7 ms
64 bytes from 8.8.4.4: icmp_seq=3 ttl=116 time=40.1 ms
64 bytes from 8.8.4.4: icmp_seq=4 ttl=116 time=40.9 ms
64 bytes from 8.8.4.4: icmp_seq=5 ttl=116 time=40.6 ms
^C

**Here is my docker-compose.yml:**

version: '3.3'
services:
    transmission-openvpn:
        volumes:
            - '/media/config/vpn'
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=TORGUARD
            - OPENVPN_CONFIG=USA-SAN-FRANCISCO
            - OPENVPN_USERNAME=xxxxxx
            - OPENVPN_PASSWORD=xxxxxxx
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.86.0/24
            - TZ=America/Los_Angeles
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mssfix 1640
           #- ENABLE_UFW=true
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
            - '51413:51413'
            - '51413:51413/udp'
        dns:
            - 8.8.8.8
            - 8.8.4.4
        image: haugene/transmission-openvpn

**Finally here is the .ovpn config it is using (minus static key and cert)**

client
dev tun
proto tcp
remote sf.west.usa.torguardvpnaccess.com 1912
remote 206.189.218.238 1912
resolv-retry infinite
nobind
persist-key
persist-tun
tun-mtu 1500
tun-mtu-extra 32
mssfix 1450
ca ca.crt
remote-cert-tls server
auth-user-pass
block-outside-dns
compress
ncp-disable
verb 3
reneg-sec 0
keepalive 5 30
fast-io
sndbuf 393216
rcvbuf 393216
cipher AES-256-GCM
auth SHA256
key-direction 1

**Here is the log from the container trying to start:**

Using OpenVPN provider: TORGUARD,
Starting OpenVPN using config USA-SAN-FRANCISCO.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.86.0/24 via 172.18.0.1 dev eth0,
Sun Jul 19 11:32:42 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019,
Sun Jul 19 11:32:42 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10,
Sun Jul 19 11:32:42 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Sun Jul 19 11:32:42 2020 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication,
Sun Jul 19 11:32:42 2020 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication,
Sun Jul 19 11:33:02 2020 RESOLVE: Cannot resolve host address: sf.west.usa.torguardvpnaccess.com:1912 (Temporary failure in name resolution),
Sun Jul 19 11:33:22 2020 RESOLVE: Cannot resolve host address: sf.west.usa.torguardvpnaccess.com:1912 (Temporary failure in name resolution),
Sun Jul 19 11:33:22 2020 Could not determine IPv4/IPv6 protocol,
Sun Jul 19 11:33:22 2020 SIGUSR1[soft,init_instance] received, process restarting,
Sun Jul 19 11:33:22 2020 Restart pause, 5 second(s),
Sun Jul 19 11:33:27 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Sun Jul 19 11:33:27 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]206.189.218.238:1912,
Sun Jul 19 11:33:27 2020 Socket Buffers: R=[212992->425984] S=[212992->425984],
Sun Jul 19 11:33:27 2020 UDP link local: (not bound),
Sun Jul 19 11:33:27 2020 UDP link remote: [AF_INET]206.189.218.238:1912,
Sun Jul 19 11:34:27 2020 [UNDEF] Inactivity timeout (--ping-exit), exiting,
Sun Jul 19 11:34:27 2020 SIGTERM[soft,ping-exit] received, process exiting,

Thanks in advance.

**EDIT 1**
I have tried with multiple other config files to no avail.
I have also tried what is mentioned in this [comment](https://github.com/moby/moby/issues/866#issuecomment-19218300) with no luck.

**Comment by jtcmedia** [comment]
Torguard has changed their hostnames. See https://torguard.net/network/

**Comment by cwilford** [comment]
> Torguard has changed their hostnames. See https://torguard.net/network/

Thanks for the reply. That is good information, is there anything that I can do to fix that or do I need to wait for Torguard to update their config files?

**Comment by pkishino** [comment]
> > Torguard has changed their hostnames. See https://torguard.net/network/
> 
> Thanks for the reply. That is good information, is there anything that I can do to fix that or do I need to wait for Torguard to update their config files?

you could download a config and try to change the hostname in the config and use it as a custom provider for the container

**Comment by pkishino** [comment]
Please try with latest config or with custom and then close this issue

**Comment by cwilford** [comment]
> Please try with latest config or with custom and then close this issue
I have now tried with the new config for multiple servers (SF and NY), rewrote my docker compose, redid the internal port openings and the port forwarding on my router. I'm not sure what I'm doing wrong.

**Docker Compose**
version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    - "51413:51413"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /media/config:/data
  environment:
    - CREATE_TUN_DEVICE=true
    - OPENVPN_PROVIDER=TORGUARD
    - OPENVPN_CONFIG=USA-SAN-FRANCISCO
    - OPENVPN_USERNAME=user
    - OPENVPN_PASSWORD=pass
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.86.0/24

**New Log**
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: TORGUARD,
Starting OpenVPN using config USA-SAN-FRANCISCO.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.86.0/24 via 172.18.0.1 dev eth0,
Fri Jul 24 16:29:00 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019,
Fri Jul 24 16:29:00 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10,
Fri Jul 24 16:29:00 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Fri Jul 24 16:29:00 2020 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication,
Fri Jul 24 16:29:00 2020 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication,
Fri Jul 24 16:29:20 2020 RESOLVE: Cannot resolve host address: us-sf.torguard.com:1912 (Temporary failure in name resolution),
Fri Jul 24 16:29:40 2020 RESOLVE: Cannot resolve host address: us-sf.torguard.com:1912 (Temporary failure in name resolution),
Fri Jul 24 16:29:40 2020 Could not determine IPv4/IPv6 protocol,
Fri Jul 24 16:29:40 2020 SIGUSR1[soft,init_instance] received, process restarting,
Fri Jul 24 16:29:40 2020 Restart pause, 5 second(s),
Fri Jul 24 16:29:45 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Fri Jul 24 16:29:45 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]206.189.218.238:1912,
Fri Jul 24 16:29:45 2020 Socket Buffers: R=[212992->425984] S=[212992->425984],
Fri Jul 24 16:29:45 2020 UDP link local: (not bound),
Fri Jul 24 16:29:45 2020 UDP link remote: [AF_INET]206.189.218.238:1912,
Fri Jul 24 16:30:45 2020 [UNDEF] Inactivity timeout (--ping-exit), exiting,
Fri Jul 24 16:30:45 2020 SIGTERM[soft,ping-exit] received, process exiting,
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: TORGUARD,
Starting OpenVPN using config USA-SAN-FRANCISCO.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.86.0/24 via 172.18.0.1 dev eth0,
Fri Jul 24 16:30:46 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019,
Fri Jul 24 16:30:46 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10,
Fri Jul 24 16:30:46 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Fri Jul 24 16:30:46 2020 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication,
Fri Jul 24 16:30:46 2020 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication,

**Comment by pkishino** [comment]
First of  all, you shouldn’t  need to do any forwarding in your router.. you can remove the ports, only the 9091 is needed for your access.
Try different dns.. like clouddns 1.1.1.1/1.0.0.1
I doubt this has anything to do with the container itself, possibly somehow your network/docker setup or else VPN issues.

**Comment by cwilford** [comment]
> First of all, you shouldn’t need to do any forwarding in your router.. you can remove the ports, only the 9091 is needed for your access.
> Try different dns.. like clouddns 1.1.1.1/1.0.0.1
> I doubt this has anything to do with the container itself, possibly somehow your network/docker setup or else VPN issues.

My apologies, I am new to Docker. I am seeing 127.0.0.11 in the resolv.conf in the container and can't ping anything. I am passing DNS in the docker-compose so I don't know why that is happening. I have spent 6 days trying to resolve this... any help would be huge. I am lost at this point.

**Comment by cwilford** [comment]
So I was able to get the dperson openvpn docker working after using the firewall-cmd --permanent --zone=trusted --change-interface=docker0 command. Could not get this to connect after still. Closing the issue.
