### ISSUE TITLE
Add "seeding idle timer" docker environment variable

### ISSUE THREAD

**Issue by rshamsz** [haugene/docker-transmission-openvpn#1302]
There are lots of torrents, especially old ones, which there is not much upload traffic for them and the seeding stays on for a long time without doing anything. 
To fix this issue it is possible to set "Stop seeding if idle for " variable to something short like 3 min which works fine, but the after each container upgrade its value gets reset to a default value of 30 min;
That would be good to have a environment variable for seeding idle timer as "seeding ratio" does. TRANSMISSION_RATIO_LIMIT.
so after each reboot or upgrade the "seeding idle timer" does not get reset to its default value

**Comment by pkishino** [comment]
TRANSMISSION_IDLE_SEEDING_LIMIT
It’s already  exposed.. please check the list of environmental settings in the transmission folder if the repo got all of them
