### ISSUE TITLE
Webinterface Transmission

### ISSUE THREAD

**Issue by normanu** [haugene/docker-transmission-openvpn#131]
Is it possible to replace the web interface as a standard with 
https://github.com/ronggang/transmission-web-control/

**Comment by haugene** [comment]
I haven't had the time to look at this yet, but seeing as it's just an alternate web interface it should be possible to run it on top of this container using some sort of container linking or other docker magic.

I'll have a look at it when I get some code time again ;)

**Comment by pkishino** [comment]
Hey, I took a quick look at the project.. it looks like it is not maintained any more though.
But if you are not afraid to play around a bit I would download the code, install it and then change this file: https://github.com/ronggang/transmission-web-control/blob/master/src/tr-web-control/script/transmission.js
and direct it towards the docker container. I believe that should work

**Comment by p3v4x** [comment]
Hi,
I've created account here to be able to post it. Well I'm not so advanced, but I've managed to run it with ronggang interface on QNAP TS453A.
Short instruction: 
1. Download this to the place where You have docker 
2. Modify RUN command in Dockerfile to install wget then download and run following script [https://github.com/ronggang/transmission-web-control/blob/master/release/tr-control-easy-install.sh](url). 
`RUN apt-get update \
    && apt-get -y install software-properties-common \
    && add-apt-repository multiverse \
    && add-apt-repository ppa:transmissionbt/ppa \
    && apt-get update \
    && apt-get install -y transmission-cli transmission-common transmission-dae$
    && apt-get install -y openvpn curl rar unrar zip unzip wget \
    && curl -sLO https://github.com/Yelp/dumb-init/releases/download/v1.0.1/dum$
    && dpkg -i dumb-init_*.deb \
    && rm -rf dumb-init_*.deb \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && curl -L https://github.com/jwilder/dockerize/releases/download/v0.0.2/do$
    && groupmod -g 1000 users \
    && useradd -u 911 -U -d /config -s /bin/false abc \
    && usermod -G users abc \
    && curl -s https://raw.githubusercontent.com/ronggang/transmission-web-cont$
    && chmod 777 /tmp/tr-control-easy-install.sh \
    && sh /tmp/tr-control-easy-install.sh`
3. Build image 
`docker build -t yourname/transmission-openvpn-web .`
4. Create container with desired options 
`docker create --name transmission-openvpn-web --privileged --dns 8.8.8.8 --dns 8.8.4.4 --restart always -v /share/Download/:/data -v /share/Download/transmission-home/:/config -e "OPENVPN_PROVIDER=PIA" -e "OPENVPN_USERNAME=username" -e "OPENVPN_PASSWORD=password" -e "OPENVPN_CONFIG=Netherlands" -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" -e "TRANSMISSION_UMASK=0" youname/transmission-openvpn-web`

It's interim solution until haugene won't add permament solution for that.

**Comment by haugene** [comment]
I think we'll stick with the default WebUI for now. Other UIs like this or Transmission remote can be configured, but I don't feel like bundling it into this image. If it's done in a clean way, I'll consider merging a PR ;) But I'll close this issue now.
