### ISSUE TITLE
curl encountered an error looking up new port: 7

### ISSUE THREAD

**Issue by antidefran** [haugene/docker-transmission-openvpn#1311]
**Describe the problem**
Transmission isn't starting and I can't access the UI. Logs show the warning "curl encountered an error looking up new port: 7". I'm using PIA as my provider and I have tried several locations including Netherlands, Toronto, US East, and US New York. 

**Settings in GUI**
[https://ibb.co/3cKzJKy](url)
[https://ibb.co/FYX5c2W](url)
[https://ibb.co/zrr1srX](url)

**Logs**

 Using OpenVPN provider: PIA

Starting OpenVPN using config CA Toronto.ovpn
Setting OPENVPN credentials...
adding route to local network 10.0.0.0/24 via 172.17.0.1 dev eth0
Mon Aug 3 12:53:26 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 5 2019
Mon Aug 3 12:53:26 2020 library versions: OpenSSL 1.1.1c 28 May 2019, LZO 2.10
Mon Aug 3 12:53:26 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Aug 3 12:53:26 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.20:1198
Mon Aug 3 12:53:26 2020 UDP link local: (not bound)
Mon Aug 3 12:53:26 2020 UDP link remote: [AF_INET]172.98.67.20:1198
Mon Aug 3 12:53:26 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Mon Aug 3 12:53:26 2020 [c367457f6f68e44f71030711bd2e5817] Peer Connection Initiated with [AF_INET]172.98.67.20:1198
Mon Aug 3 12:53:27 2020 TUN/TAP device tun0 opened
Mon Aug 3 12:53:27 2020 /sbin/ip link set dev tun0 up mtu 1500
Mon Aug 3 12:53:27 2020 /sbin/ip addr add dev tun0 local 10.58.10.6 peer 10.58.10.5
Mon Aug 3 12:53:27 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.58.10.6 10.58.10.5 init
Up script executed with tun0 1500 1558 10.58.10.6 10.58.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.58.10.6
Using Transmission Web Control UI, overriding TRANSMISSION_WEB_HOME
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 99:100
Setting permission for files (644) and directories (755)
Setting permission for watch directory (775) and its files (664)

.-------------------------------------.
Transmission will run as
.-------------------------------------.
User name: abc
User uid: 99
User gid: 100
.-------------------------------------.

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Mon Aug 3 12:53:27 2020 Initialization Sequence Completed
Generating new client id for PIA
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 52 . 

**Host system:**
Unraid 6.8.3 and Docker 19.03.5

**Comment by pkishino** [comment]
you probably dont want to share your vpn username and password like that..
I'm guessing you need to check the PIA which servers support port forwarding and check which port to use

**Comment by terxw** [comment]
Same issue, same error port number, but the issue is appearing only intermitently, my pia server supports port forwarding

**Comment by antidefran** [comment]
Yeah that was dumb of me. It’s already been changed.

Anthony DeFrancesco
TAC Supervisor, Technology Services
Division Of IRT, Rowan University
(856)256-4455
defrancescoa@rowan.edu
________________________________

**Comment by antidefran** [comment]
I'm still receiving the port 7 error in the docker logs, but I started being able to access to gui and things are downloading again. I didn't make any changes.
