### ISSUE TITLE
Empty response from the UI

### ISSUE THREAD

**Issue by vlaquest** [haugene/docker-transmission-openvpn#1312]
Hi,
I'm using the latest image on my Synology NAS DS216+II
I got the docker image up and running, unfortunately, I get an empty response from the UI.  http://192.168.0.16:31888 => ERR_EMPTY_RESPONSE
When I ssh on the NAS  I did a curl http://localhost:8888 => (connection reset)
I'm using a custom provider... and it looks like it has successfully launched openvpn
I have the feeling that transmission has not started, I have no clue how to start it or check it is ok.
attached is the detailed logs... [docker logs.txt](https://github.com/haugene/docker-transmission-openvpn/files/5018605/docker.logs.txt)
finally, when I start the following command inside the container :
/etc/transmission/start.sh

I get :
Up script executed with
ERROR, unable to obtain tunnel address
killing 17

Thanks for your help

**Comment by pkishino** [comment]
need to post docker config and the complete log

**Comment by vlaquest** [comment]
thanks for having a look at this :
[docker config.txt](https://github.com/haugene/docker-transmission-openvpn/files/5020887/docker.config.txt)
[docker logs.txt](https://github.com/haugene/docker-transmission-openvpn/files/5020888/docker.logs.txt)

It looks like it is prompting for a username in the logs => that explains why transmission is not launched.
The VPN may not be properly set up.
I'm currently working on the PR for cyberghost integration.

**Comment by pkishino** [comment]
Yeah, you need to update the config, there is a script in the repo, I think
it’s described in the wiki

**Comment by vlaquest** [comment]
I really spent hours following what's in the wiki... don't know where my config is bad :(
I just created the PR with my config.

**Comment by pkishino** [comment]
see the PR, adding comments there
