### ISSUE TITLE
Add Windscribe to VPN Providers

### ISSUE THREAD

**Issue by carlyman** [haugene/docker-transmission-openvpn#132]
Switched VPN providers and forget to check whether you supported or not.  If it could be added, it'd be much appreciated.

Here's a scrubbed version of the opvn config:
[Windscribe.ovpn.txt](https://github.com/haugene/docker-transmission-openvpn/files/496831/Windscribe.ovpn.txt)

-JC

**Comment by carlyman** [comment]
Missed the ability to add custom VPN from the readme as well as notes in #60 ..as such, closing issue.

**Comment by carlyman** [comment]
I followed the process of a customer VPN per the readme and #60; however, the log looks like its getting stuck:
`Using OpenVPN provider: CUSTOM`
`No VPN configuration provided. Using default.`
`Setting OPENVPN credentials...`
`adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0`
`Wed Sep 28 00:49:28 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014`

**Comment by pkishino** [comment]
I can take a look at this, but please provide me with a windscribe.ovpn config WITH the certificates so I can add it to the repo

**Comment by carlyman** [comment]
Which certificates do I share (want to make sure I don't share anything private obviously)...just the text in the ovpn file that I removed?   Additionally, dere's a link to the CA Cert and TLS Auth Key: https://assets.windscribe.com/desktop/other/openvpn_cert.zip

**Comment by haugene** [comment]
If the .ovpn files are not public, ie they are generated for you personally then there's no way around the CUSTOM approach. As long as you make the appropriate changes in paths to ca/tls keys in your ovpn files it should work...

**Comment by carlyman** [comment]
Ok, I checked and from what I can tell the ovpn file is not uniquely created or contain anything unique to my account.  There are differences based on which country you choose it seems, so not sure how best to get you that info?  I've attached one example: 
[Windscribe-Switzerland.ovpn.txt](https://github.com/haugene/docker-transmission-openvpn/files/501782/Windscribe-Switzerland.ovpn.txt)

**Comment by pkishino** [comment]
You should be able to download or link me a zip containing all the ovpn
configurations

**Comment by carlyman** [comment]
Here you go
[Windscribe-OVPN.zip](https://github.com/haugene/docker-transmission-openvpn/files/502910/Windscribe-OVPN.zip)

**Comment by carlyman** [comment]
Here you go; both TCP and UDP configs.
[Windscribe-OVPN-UDP.zip](https://github.com/haugene/docker-transmission-openvpn/files/502948/Windscribe-OVPN-UDP.zip)
[Windscribe-OVPN-TCP.zip](https://github.com/haugene/docker-transmission-openvpn/files/502949/Windscribe-OVPN-TCP.zip)

**Comment by pkishino** [comment]
Ok,great. Will try and get a pr done this weekend

**Comment by haugene** [comment]
This is now merged to master and available on the latest tag, closing issue
