### ISSUE TITLE
Support docker secrets

### ISSUE THREAD

**Issue by fletch3555** [haugene/docker-transmission-openvpn#1321]
**Is your feature request related to a problem? Please describe.**
I'm trying to use docker secrets, but the environment variables simply store `/run/secrets/<varname>`

**Describe the solution you'd like**

Either duplicate environment variables with `_FILE` suffix or overload existing ones to read secret file instead of using path directly

**Describe alternatives you've considered**

I considered using a "pre" script (https://haugene.github.io/docker-transmission-openvpn/custom-scripts/). For example, something such as this: https://medium.com/@adrian.gheorghe.dev/using-docker-secrets-in-your-environment-variables-7a0609659aab.  It would be better to have native support for it though.

**Comment by ilike2burnthing** [comment]
https://github.com/haugene/docker-transmission-openvpn/issues/534

**Comment by pkishino** [comment]
Duplicate

**Comment by fletch3555** [comment]
Ah, missed that one.  Sorry about that!
