### ISSUE TITLE
NordVPN Update

### ISSUE THREAD

**Issue by Malice890** [haugene/docker-transmission-openvpn#1327]
**Which provider?**

NordVPN
**Where are the configs?**

[us5647.nordvpn.com.udp.zip](https://github.com/haugene/docker-transmission-openvpn/files/5057824/us5647.nordvpn.com.udp.zip)

this is for a US P2P UDP

**Comment by pkishino** [comment]
Nordvpn uses a script to fetch config afaik, not Kanal ovpn files
