### ISSUE TITLE
Can no longer connect to Privado

### ISSUE THREAD

**Issue by lenaxia** [haugene/docker-transmission-openvpn#1335]
**Describe the problem**
I previously was able to connect to Privado, but no longer can. Getting Auth_Failed error. I've tried recreating the container, and I've manually updated the ovpn files. I can confirm my password is correct.

**Add your docker run command**
> version: "3"
> services:
>   transmission-vpn:
>     container_name: transmission-vpn
>     image: haugene/transmission-openvpn
>     cap_add:
>       - NET_ADMIN
>     devices:
>       - /dev/net/tun
>     restart: always
>     ports:
>     - "9091:9091"
>     dns:
>       - 192.168.0.5
>     volumes:
>       - /etc/localtime:/etc/localtime:ro
>       - /mnt/docker/transmission-vpn:/data
>       - /mnt/docker/shared:/shared
>       - "/mnt/downloads/[Plex Temp Library]/Unsorted:/data/Unsorted"
>     environment:
>       - CREATE_TUN_DEVICE=true
>       - OPENVPN_PROVIDER=PRIVADO
>       - OPENVPN_USERNAME="myUsername"
>       - OPENVPN_PASSWORD="myPassword"
>       - OPENVPN_CONFIG=lax-010
>       - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
>       - LOCAL_NETWORK=192.168.0.0/16
>       - PUID=${PUID}
>       - PGID=${PGID}
>       - TZ=${TZ}
>       - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
>       - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
>       - TRANSMISSION_RPC_PASSWORD=myRPCPassword
>       - TRANSMISSION_RPC_USERNAME=myRPCUsername
>         #      - TRANSMISSION_UMASK="002"
>       - TRANSMISSION_RATIO_LIMIT=1.00
>       - TRANSMISSION_RATIO_LIMIT_ENABLED=true
>     networks:
>       - medianet
> networks:
>   medianet:
>     external: true

**Logs**
> mknod: /dev/net/tun: File exists
> Using OpenVPN provider: PRIVADO
> Starting OpenVPN using config lax-010.ovpn
> Setting OPENVPN credentials...
> adding route to local network 192.168.0.0/16 via 172.21.0.1 dev eth0
> Fri Aug 21 00:37:18 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
> Fri Aug 21 00:37:18 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
> Fri Aug 21 00:37:18 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Fri Aug 21 00:37:18 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]45.152.182.234:1194
> Fri Aug 21 00:37:18 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
> Fri Aug 21 00:37:18 2020 UDP link local: (not bound)
> Fri Aug 21 00:37:18 2020 UDP link remote: [AF_INET]45.152.182.234:1194
> Fri Aug 21 00:37:18 2020 TLS: Initial packet from [AF_INET]45.152.182.234:1194, sid=c62e77e7 b681b8aa
> Fri Aug 21 00:37:18 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Fri Aug 21 00:37:18 2020 VERIFY OK: depth=1, CN=Privado
> Fri Aug 21 00:37:18 2020 VERIFY X509NAME OK: CN=lax-010.vpn.privado.io
> Fri Aug 21 00:37:18 2020 VERIFY OK: depth=0, CN=lax-010.vpn.privado.io
> Fri Aug 21 00:37:20 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1569', remote='link-mtu 1570'
> Fri Aug 21 00:37:20 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
> Fri Aug 21 00:37:20 2020 Control Channel: TLSv1.2, cipher SSLv3 DHE-RSA-AES256-SHA, 4096 bit RSA
> Fri Aug 21 00:37:20 2020 [lax-010.vpn.privado.io] Peer Connection Initiated with [AF_INET]45.152.182.234:1194
> Fri Aug 21 00:37:21 2020 SENT CONTROL [lax-010.vpn.privado.io]: 'PUSH_REQUEST' (status=1)
> Fri Aug 21 00:37:21 2020 AUTH: Received control message: AUTH_FAILED
> Fri Aug 21 00:37:21 2020 SIGTERM[soft,auth-failure] received, process exiting

**Host system:**
> $ docker image ls | grep vpn
> haugene/transmission-openvpn     latest              d42211b5a2c3        9 days ago          434MB
> haugene/transmission-openvpn     <none>              9e98b1502bd6        2 months ago        416MB

> $ docker version
> Client: Docker Engine - Community
>  Version:           19.03.8
>  API version:       1.40
>  Go version:        go1.12.17
>  Git commit:        afacb8b7f0
>  Built:             Wed Mar 11 01:25:46 2020
>  OS/Arch:           linux/amd64
>  Experimental:      false
>
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.8
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.12.17
>   Git commit:       afacb8b7f0
>   Built:            Wed Mar 11 01:24:19 2020
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.2.13
>   GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
>  runc:
>   Version:          1.0.0-rc10
>   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683

**Comment by lenaxia** [comment]
I did have special characters in my password. I have updated my password to be only letters and numbers. I also pulled the latest and recreated the container and am still seeing the same failure.

I confirmed that my alphanumeric password does work (at least on the website). 

Any other suggestions, or information that I can provide that can help?

> $ docker image ls | grep transmission
> haugene/transmission-openvpn     latest              ee7968739e88        30 hours ago        434MB
> $ docker inspect transmission-vpn
>   "Image": "sha256:ee7968739e880566abe74852b4b9e1f6437af1b97f61b8c3d6496b6cdeb4a955",

New logs: 

> Tue Aug 25 11:46:26 2020 [lax-010.vpn.privado.io] Peer Connection Initiated with [AF_INET]45.152.182.234:1194
> Tue Aug 25 11:46:27 2020 SENT CONTROL [lax-010.vpn.privado.io]: 'PUSH_REQUEST' (status=1)
> Tue Aug 25 11:46:27 2020 AUTH: Received control message: AUTH_FAILED
> Tue Aug 25 11:46:27 2020 SIGTERM[soft,auth-failure] received, process exiting
> mknod: /dev/net/tun: File exists
> Using OpenVPN provider: PRIVADO
> Starting OpenVPN using config lax-010.ovpn
> Setting OPENVPN credentials...
> adding route to local network 192.168.0.0/16 via 172.21.0.1 dev eth0
> Tue Aug 25 11:46:31 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020
> Tue Aug 25 11:46:31 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
> Tue Aug 25 11:46:31 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Tue Aug 25 11:46:31 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]45.152.182.234:1194
> Tue Aug 25 11:46:31 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
> Tue Aug 25 11:46:31 2020 UDP link local: (not bound)
> Tue Aug 25 11:46:31 2020 UDP link remote: [AF_INET]45.152.182.234:1194
> Tue Aug 25 11:46:31 2020 TLS: Initial packet from [AF_INET]45.152.182.234:1194, sid=cfbb518a 750169e5
> Tue Aug 25 11:46:31 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Tue Aug 25 11:46:32 2020 VERIFY OK: depth=1, CN=Privado
> Tue Aug 25 11:46:32 2020 VERIFY X509NAME OK: CN=lax-010.vpn.privado.io
> Tue Aug 25 11:46:32 2020 VERIFY OK: depth=0, CN=lax-010.vpn.privado.io
> Tue Aug 25 11:46:33 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1569', remote='link-mtu 1570'
> Tue Aug 25 11:46:33 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
> Tue Aug 25 11:46:33 2020 Control Channel: TLSv1.2, cipher SSLv3 DHE-RSA-AES256-SHA, 4096 bit RSA
> Tue Aug 25 11:46:33 2020 [lax-010.vpn.privado.io] Peer Connection Initiated with [AF_INET]45.152.182.234:1194
> Tue Aug 25 11:46:33 2020 event_wait : Interrupted system call (code=4)
> Tue Aug 25 11:46:33 2020 SIGTERM[hard,] received, process exiting

**Comment by haugene** [comment]
I have still not seen a case of `AUTH_FAILED` error message that was not related to the username/password. You need to check with your provider documentation. Some providers have a separate username and password on OpenVPN connections than they do in the apps/web etc. You could search for other issues that mention Privado and see if you can find it mentioned somewhere.

**Comment by lenaxia** [comment]
Okay, I will confirm with them.

**Comment by bcunningham86** [comment]
Have the same issue, not using docker, installed on pfSense.  Can confirm nothing changed, it just stopped working.  Tried all of these suggestions. Did any figure out a solution to this?
