### ISSUE TITLE
HideMyAss: TLS handshake failed

### ISSUE THREAD

**Issue by romain38** [haugene/docker-transmission-openvpn#134]
Hi,
Since the 27th of September, my VPN connection fails (with HideMyAss provider) without any change from me.

`VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: C=UK, ST=London, L=London, O=Privax Ltd, OU=HMA Pro VPN, CN=hidemyass.com, emailAddress=info@privax.com`
`TLS_ERROR: BIO read tls_read_plaintext error: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed`
`TLS Error: TLS object -> incoming plaintext read error`
`TLS Error: TLS handshake failed`
`Fatal TLS error (check_tls_errors_co), restarting`
`SIGUSR1[soft,tls-error] received, process restarting`
`Restart pause, 5 second(s)`

On HideMyAss [blog,](http://blog.hidemyass.com/2016/09/26/sweet-32-birthday-attack-what-is-it-and-whowhat-does-it-affect/#more-5263) a cipher update was indicated:
> We will be updating the cipher on the 27th of September, between 7am and 1pm UTC. HMA! Pro VPN may be unavailable for short intervals during this time.

Best regards.

Romain

**Comment by rwaesely** [comment]
I confirm I get the same issue :)

**Comment by haugene** [comment]
That ought to do it!
Try pulling the image again now...

**Comment by romain38** [comment]
It works, thank you for this fast fix!

**Comment by haugene** [comment]
:+1: Np!
