### ISSUE TITLE
Cannot open TUN/TAP device

### ISSUE THREAD

**Issue by trizmark** [haugene/docker-transmission-openvpn#1346]
**Describe the problem**
I have managed to set up my container about a week ago and everything was working fine. Downloaded the latest Ubuntu image and seeded it fine until the ration has reached 3.
3 days ago the container exited due to a VPN authentication failure.

I tried to restart the container, but now it fails to start. This is the last entry in the logs:
Mon Aug 31 20:10:25 2020 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
Mon Aug 31 20:10:25 2020 Exiting due to fatal error

I tried to create a new container (docker run rather than docker start), but I face the same issue.

**Add your docker run command**
docker run --cap-add=NET_ADMIN -d -v /home/pi/bittorrent:/data -v /etc/localtime:/etc/localtime:ro -e CREATE_TUN_DEVICE=true -e OPENVPN_PROVIDER=IPREDATOR -e OPENVPN_USERNAME=******** -e OPENVPN_PASSWORD=******** -e WEBPROXY_ENABLED=true -e WEBPROXY_PORT=8888 -p 9091:9091 haugene/transmission-openvpn:latest-armhf

**Logs**
Using OpenVPN provider: IPREDATOR
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Mon Aug 31 20:27:05 2020 WARNING: file '/etc/openvpn/ipredator/ta.key' is group or others accessible
Mon Aug 31 20:27:05 2020 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Mon Aug 31 20:27:05 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Mon Aug 31 20:27:05 2020 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
Mon Aug 31 20:27:05 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Aug 31 20:27:05 2020 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Aug 31 20:27:05 2020 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Aug 31 20:27:05 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]46.246.37.130:1194
Mon Aug 31 20:27:05 2020 Socket Buffers: R=[180224->180224] S=[180224->180224]
Mon Aug 31 20:27:05 2020 UDP link local: (not bound)
Mon Aug 31 20:27:05 2020 UDP link remote: [AF_INET]46.246.37.130:1194
Mon Aug 31 20:27:05 2020 TLS: Initial packet from [AF_INET]46.246.37.130:1194, sid=a6f5bd07 32b81874
Mon Aug 31 20:27:05 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Aug 31 20:27:05 2020 VERIFY OK: depth=1, C=SE, ST=Bryggland, L=Oeldal, O=Royal Swedish Beer Squadron, OU=Internetz, CN=Royal Swedish Beer Squadron CA, emailAddress=hostmaster@ipredator.se
Mon Aug 31 20:27:05 2020 VERIFY OK: nsCertType=SERVER
Mon Aug 31 20:27:05 2020 Validating certificate key usage
Mon Aug 31 20:27:05 2020 VERIFY KU OK
Mon Aug 31 20:27:05 2020 Validating certificate extended key usage
Mon Aug 31 20:27:05 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Mon Aug 31 20:27:05 2020 VERIFY EKU OK
Mon Aug 31 20:27:05 2020 VERIFY OK: depth=0, C=SE, ST=Bryggland, L=Oeldal, O=Royal Swedish Beer Squadron, CN=phahsairiefu.openvpn.ipredator.se, emailAddress=hostmaster@ipredator.se
Mon Aug 31 20:27:05 2020 Control Channel: TLSv1.2, cipher TLSv1.2 DHE-RSA-AES256-GCM-SHA384, 3881 bit RSA
Mon Aug 31 20:27:05 2020 [phahsairiefu.openvpn.ipredator.se] Peer Connection Initiated with [AF_INET]46.246.37.130:1194
Mon Aug 31 20:27:07 2020 SENT CONTROL [phahsairiefu.openvpn.ipredator.se]: 'PUSH_REQUEST' (status=1)
Mon Aug 31 20:27:07 2020 PUSH: Received control message: 'PUSH_REPLY,route 46.246.37.130 255.255.255.255 net_gateway,route-gateway 46.246.37.1,redirect-gateway def1,topology subnet,dhcp-option DOMAIN ipredator.se,dhcp-option DNS 46.246.46.46,dhcp-option DNS 194.132.32.23,ip-win32 dynamic,ping 10,ping-restart 60,explicit-exit-notify 3,sndbuf 0,rcvbuf 0,peer-id 4,cipher AES-256-CBC,ifconfig 46.246.37.231 255.255.255.0'
Mon Aug 31 20:27:07 2020 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:8: ip-win32 (2.4.7)
Mon Aug 31 20:27:07 2020 OPTIONS IMPORT: timers and/or timeouts modified
Mon Aug 31 20:27:07 2020 OPTIONS IMPORT: explicit notify parm(s) modified
Mon Aug 31 20:27:07 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Mon Aug 31 20:27:07 2020 Socket Buffers: R=[180224->180224] S=[180224->180224]
Mon Aug 31 20:27:07 2020 OPTIONS IMPORT: --ifconfig/up options modified
Mon Aug 31 20:27:07 2020 OPTIONS IMPORT: route options modified
Mon Aug 31 20:27:07 2020 OPTIONS IMPORT: route-related options modified
Mon Aug 31 20:27:07 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Mon Aug 31 20:27:07 2020 OPTIONS IMPORT: peer-id set
Mon Aug 31 20:27:07 2020 OPTIONS IMPORT: adjusting link_mtu to 1625
Mon Aug 31 20:27:07 2020 OPTIONS IMPORT: data channel crypto options modified
Mon Aug 31 20:27:07 2020 Outgoing Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Mon Aug 31 20:27:07 2020 Outgoing Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Aug 31 20:27:07 2020 Incoming Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Mon Aug 31 20:27:07 2020 Incoming Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Aug 31 20:27:07 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:06
Mon Aug 31 20:27:07 2020 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
Mon Aug 31 20:27:07 2020 Exiting due to fatal error

**Host system:**
Running on a Raspberry Pi, which is booted from an external SSD.

**Comment by travisthomas** [comment]
Create a script that runs as root on boot:

```
#!/bin/sh

# Create the necessary file structure for /dev/net/tun
if ( [ ! -c /dev/net/tun ] ); then
  if ( [ ! -d /dev/net ] ); then
    mkdir -m 755 /dev/net
  fi
  mknod /dev/net/tun c 10 200
fi

# Load the tun module if not already loaded
if ( !(lsmod | grep -q "^tun\s") ); then
  insmod /lib/modules/tun.ko
  insmod /lib/modules/iptable_mangle.ko
fi
```

Run it or reboot

**Comment by trizmark** [comment]
The container definitely has CREATE_TUN_DEVICE set to true:

pi@raspberrypi:~ $ docker inspect -f '{{range $index, $value := .Config.Env}}{{$value}} {{end}}' transmission
OPENVPN_PASSWORD=****** WEBPROXY_ENABLED=true WEBPROXY_PORT=8888 LOCAL_NETWORK=192.168.0.0/24 **CREATE_TUN_DEVICE=true** OPENVPN_PROVIDER=IPREDATOR OPENVPN_USERNAME=******* PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LC_ALL=C.UTF-8 DEBIAN_FRONTEND=noninteractive UDEV=off QEMU_CPU=arm1176 GLOBAL_APPLY_PERMISSIONS=true TRANSMISSION_ALT_SPEED_DOWN=50 TRANSMISSION_ALT_SPEED_ENABLED=false TRANSMISSION_ALT_SPEED_TIME_BEGIN=540 TRANSMISSION_ALT_SPEED_TIME_DAY=127 TRANSMISSION_ALT_SPEED_TIME_ENABLED=false TRANSMISSION_ALT_SPEED_TIME_END=1020 TRANSMISSION_ALT_SPEED_UP=50 TRANSMISSION_BIND_ADDRESS_IPV4=0.0.0.0 TRANSMISSION_BIND_ADDRESS_IPV6=:: TRANSMISSION_BLOCKLIST_ENABLED=false TRANSMISSION_BLOCKLIST_URL=http://www.example.com/blocklist TRANSMISSION_CACHE_SIZE_MB=4 TRANSMISSION_DHT_ENABLED=true TRANSMISSION_DOWNLOAD_DIR=/data/completed TRANSMISSION_DOWNLOAD_LIMIT=100 TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0 TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5 TRANSMISSION_ENCRYPTION=1 TRANSMISSION_IDLE_SEEDING_LIMIT=30 TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false TRANSMISSION_INCOMPLETE_DIR=/data/incomplete TRANSMISSION_INCOMPLETE_DIR_ENABLED=true TRANSMISSION_LPD_ENABLED=false TRANSMISSION_MAX_PEERS_GLOBAL=200 TRANSMISSION_MESSAGE_LEVEL=2 TRANSMISSION_PEER_CONGESTION_ALGORITHM= TRANSMISSION_PEER_ID_TTL_HOURS=6 TRANSMISSION_PEER_LIMIT_GLOBAL=200 TRANSMISSION_PEER_LIMIT_PER_TORRENT=50 TRANSMISSION_PEER_PORT=51413 TRANSMISSION_PEER_PORT_RANDOM_HIGH=65535 TRANSMISSION_PEER_PORT_RANDOM_LOW=49152 TRANSMISSION_PEER_PORT_RANDOM_ON_START=false TRANSMISSION_PEER_SOCKET_TOS=default TRANSMISSION_PEX_ENABLED=true TRANSMISSION_PORT_FORWARDING_ENABLED=false TRANSMISSION_PREALLOCATION=1 TRANSMISSION_PREFETCH_ENABLED=1 TRANSMISSION_QUEUE_STALLED_ENABLED=true TRANSMISSION_QUEUE_STALLED_MINUTES=30 TRANSMISSION_RATIO_LIMIT=2 TRANSMISSION_RATIO_LIMIT_ENABLED=false TRANSMISSION_RENAME_PARTIAL_FILES=true TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0 TRANSMISSION_RPC_ENABLED=true TRANSMISSION_RPC_HOST_WHITELIST= TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=false TRANSMISSION_RPC_PASSWORD=password TRANSMISSION_RPC_PORT=9091 TRANSMISSION_RPC_URL=/transmission/ TRANSMISSION_RPC_USERNAME=username TRANSMISSION_RPC_WHITELIST=127.0.0.1 TRANSMISSION_RPC_WHITELIST_ENABLED=false TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=true TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=false TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME= TRANSMISSION_SEED_QUEUE_ENABLED=false TRANSMISSION_SEED_QUEUE_SIZE=10 TRANSMISSION_SPEED_LIMIT_DOWN=100 TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false TRANSMISSION_SPEED_LIMIT_UP=100 TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false TRANSMISSION_START_ADDED_TORRENTS=true TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false TRANSMISSION_UMASK=2 TRANSMISSION_UPLOAD_LIMIT=100 TRANSMISSION_UPLOAD_LIMIT_ENABLED=0 TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=14 TRANSMISSION_UTP_ENABLED=false TRANSMISSION_WATCH_DIR=/data/watch TRANSMISSION_WATCH_DIR_ENABLED=true TRANSMISSION_HOME=/data/transmission-home TRANSMISSION_WATCH_DIR_FORCE_GENERIC=false ENABLE_UFW=false UFW_ALLOW_GW_NET=false UFW_EXTRA_PORTS= UFW_DISABLE_IPTABLES_REJECT=false TRANSMISSION_WEB_UI= PUID= PGID= TRANSMISSION_WEB_HOME= DROP_DEFAULT_ROUTE= WEBPROXY_USERNAME= WEBPROXY_PASSWORD= DOCKER_LOG=false HEALTH_CHECK_HOST=google.com

**Comment by svloosbroek** [comment]
I have the same problem. Running on latest-armhf build on docker 19. Tried passing --device /dev/net/tun instead of creating the tun device but problem remains

**Comment by svloosbroek** [comment]
I did some more research, turned out that the module in my kernel was not loaded correctly and this would cause the command in the container to fail. When running modprobe tun on the host (Ubuntu running on an Odroid XU4) I got the following message:

modprobe: FATAL: Module tun not found in directory /lib/modules/4.14.180-177

I resolved this by reinstalling the kernel using the following command: sudo apt-get install --reinstall linux-odroid-5422

You should look up what the package name is for your RPi kernel, run the command and you should be good to go. 

The post that put me on this path: https://forum.odroid.com/viewtopic.php?f=177&t=39695

Good luck

**Comment by Kaisbn** [comment]
Had the same issue. Fixed it by passing the device `/dev/net/tun` to the container, updating my packages (kernel + headers mainly) and rebooting.

**Comment by trizmark** [comment]
So I've updated my kernel and headers, rebooted and I got no more issues with the tun interface.

Thanks for all the suggestions!
