### ISSUE TITLE
cant get destkop webui on pc

### ISSUE THREAD

**Issue by nsar1907** [haugene/docker-transmission-openvpn#1349]
**Describe the problem**
i have installed lastest version of it and now cant get destkop webui. can access only for mobile

thats what i entire http://192.168.178.25:9091/transmission/web/
**Add your docker run command**

**Logs**

**Host system:**
synology nas

**Comment by pinkstrings** [comment]
What are your `WEBPROXY_ENABLED` and `WEBPROXY_PORT` environmental variables set to?

**Comment by nsar1907** [comment]
> What are your `WEBPROXY_ENABLED` and `WEBPROXY_PORT` environmental variables set to?

WEBPROXY false and PORT 8888

**Comment by justsomeguyontheinternet** [comment]
what is your docker run command?

did you adjust this parameter?
-e LOCAL_NETWORK=192.168.0.0/16
