### ISSUE TITLE
Can we bump the transmission client version to 2.94 or 3.00 in the arm64 image?

### ISSUE THREAD

**Issue by ndanyluk** [haugene/docker-transmission-openvpn#1350]
**Is your feature request related to a problem? Please describe.**
It appears that the Transmission 2.92 client is still the default client version for the arm64 docker image on dockerhub.  The reason for the request is that I believe there is a memory leak issue with 2.92 and that it was resolved in 2.94.

**Describe the solution you'd like**
Bump the version to 2.94 or 3.00, but this might require a different build methodology since the repos that the dockerfile builds against might not have the latest versions.  In that case, you would likely need to pull the release from github and build the transmission daemon rather than simply install from apt or apk

**Describe alternatives you've considered**
I don't know an alternative way to update the transmission daemon in container

**Additional context**

**Comment by ndanyluk** [comment]
Huh, upon further inspection it seems that Dockerfile.armhf calls out the latest buster base image, but the CircleCI builds revert that to stretch, which is locked to 2.92 as its latest transmission daemon

**Comment by ndanyluk** [comment]
Opened https://github.com/haugene/docker-transmission-openvpn/pull/1351 to hopefully close this issue

**Comment by haugene** [comment]
As we merged #1351 and this went quiet I assume that it is now OK. Closing.
