### ISSUE TITLE
Keep Ubuntu base image

### ISSUE THREAD

**Issue by YujiShen** [haugene/docker-transmission-openvpn#1354]
**Is your feature request related to a problem? Please describe.**

I found Ubuntu image has better speed than Alpine image. I am using them under exact same settings on Mac. For Alpine image, I can not get speed higher than 10 MB/s in 5 mins (average 5MB/s). But with Ubuntu image, I can get speed up to 40 MB/s and average 20 MB/s as soon as I start it.

I hesitate the type of this issue, but I think this is not a bug. I can provide more context if need.

**Describe the solution you'd like**

Could we keep both versions? I understand it will cause extra effort to support both versions...

**Describe alternatives you've considered**

Can we drop Alpine? I understand Alpine has smaller image size, but I think Ubuntu has better community and more packages. And in this case, better performance. All these are more important than image size. I am not sure what cause this, maybe glibc vs musl.

**Additional context**

I have only tested this on my Mac, but I have tested multiple times. Not sure whether it is the same case on Linux or Windows.

**Comment by pkishino** [comment]
Previously I tested this on both my MacBook Pro and Mac mini with several of the images and versions and never noticed this.
There’s nothing stopping you from staying in the Ubuntu version but moving forward we will only keep alpine

**Comment by haugene** [comment]
@YujiShen I see you closed the issue. Have you tested it more and got other results? Or are you still experiencing slower downloads? We did go for only alpine for now, but if we get multiple reports of limited speed then we definitely need to have another look at it. Sorry that I haven't gotten back to you on this sooner - but I did find your observations very interesting and something we should look out for on alpine.

If this is still an issue for you and others report on this as well then we can try to narrow down what causes it. And switching back to Ubuntu might still be an option - but I want to try and fix it on Alpine first at least.

Thoughts?

**Comment by YujiShen** [comment]
@haugene Thanks for paying attention to this! I see 3.0 is released so I closed it.

Last night I update my config to use 3.0. I am able to use next gen CA Toronto instead of European server for PIA which is near my location. 
- Upload looks better: it can keep at peak 2.2MB/s for last 10 hours, it always fluctuated and can not keep at max speed before. 
- I only tried few downloads, the max download speed is not as fast as before (15 vs 30MB/s). For latest download which took 40mins, it took about 30mins to gradually increased to 13MB/s.

It is hard to compare because:
1. Torrents are different and peers may change anytime. When I open this issue, I downloaded different but multiple torrents with a lot of peers for each situation. I remembered I also tested with a ubuntu ISO, but it is too small to keep running.
2. The old version can not use PIA with port forwarding any more(?)

I will keep an eye on this and reopen the issue. I think it will be a problem if I can not achieve my previous peak speed with 3.0 for all my downloads. The next gen and near server should only increase the download speed.

P.S. I think the download speed fluctuation may also be a problem, but I may not able to verify that...

**Comment by haugene** [comment]
Great. I'm curious to see what you find. I guess that the old PIA servers cannot be used anymore. Or at least the port-forwarding is not working.

There has been reported a bunch of issues now after 3.0 and I want to close more of them to make sure that the key features are working and make the transition as smooth as possible. So let's follow up on this later. Post if you have some results :+1:

**Comment by YujiShen** [comment]
@haugene Thanks for the support these days! It takes a lot of effort to maintain this project.

Things bug me most after upgrading is not performance, but stability. As I post in https://github.com/haugene/docker-transmission-openvpn/issues/1435#issuecomment-720936113, I can't keep container running in healthy state under 3.0 (2.14 has the same problem). 2.13 is the most stable version for me. I found can still get port forwarding from `DE Berlin` on old PIA server, but I am not sure how long I can still use it. I think this should not be a problem of different images, because 2.14 is also default to Ubuntu but still has the problem. I post my speculation here https://github.com/haugene/docker-transmission-openvpn/issues/1435#issuecomment-721511905.

**Comment by haugene** [comment]
How is the stability now @YujiShen. About the speed I think I might know what it might be. I think I've overwritten a default that we used to have when I upgraded to 3.0. It was discovered here: #1523 but is relating to this variable: #978

**Comment by YujiShen** [comment]
@haugene Thanks for revisiting the issue. Stability is very good after last release! I have been keep running it without any issue since the release.

For speed, I did not see same max speed compared to 2.13 on Ubuntu for now. About variables, not sure which one you are referring to. But I set almost all those variables in docker-compose.yml when I tuning the Transmission, and keep like this for a while. So maybe it is not the reason. Here is my Transmission config:

```
- TRANSMISSION_UMASK=2
- TRANSMISSION_CACHE_SIZE_MB=256
- TRANSMISSION_RENAME_PARTIAL_FILES=true
- TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
- TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
- TRANSMISSION_RATIO_LIMIT_ENABLED=false
- TRANSMISSION_UTP_ENABLED=true
- TRANSMISSION_LPD_ENABLED=true
- TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
- TRANSMISSION_START_ADDED_TORRENTS=false
- TRANSMISSION_PREALLOCATION=1
- TRANSMISSION_MAX_PEERS_GLOBAL=200000000
- TRANSMISSION_PEER_LIMIT_GLOBAL=200000000
- TRANSMISSION_PEER_LIMIT_PER_TORRENT=100
```

**Comment by haugene** [comment]
Good to hear :+1: About the variables I was actually wrong yesterday, the default hasn't changed. But looking at you compose you overwrite that. Try TRANSMISSION_UTP_ENABLED=false

**Comment by YujiShen** [comment]
@haugene I can get average about 15-20MB/s once I change to use ca_toronto (I get better speed on CA Montreal for old gen PIA server), so I think the performance is good on new image.
