### ISSUE TITLE
OPENVPN_PROVIDER=CUSTOM

### ISSUE THREAD

**Issue by elsaadouni** [haugene/docker-transmission-openvpn#1356]
Hi Guys,

I had created the below .yml and .ovpn files as following, but always getting this error

i do not have credential added from the server side while issuing the opvn file, nevertheless the same .opvn file is working directly if used from mobile with no issues

hence,  auth-user-pass /config/openvpn-credentials.txt file has  no data

any idea what could be wrong.

Files structures  and Error log

.yml file

**version: "2.1"
services:
transmission-openvpn:
volumes:
- /Users/elsaadouni/Desktop/Plex/default.ovpn:/etc/openvpn/custom/default.ovpn
- /Users/elsaadouni/Desktop/Plex/:/data
environment:
- CREATE_TUN_DEVICE=true
- OPENVPN_PROVIDER=CUSTOM
- OPENVPN_CONFIG=default
- OPENVPN_USERNAME=dummy
- OPENVPN_PASSWORD=dummy
- WEBPROXY_ENABLED=false
- LOCAL_NETWORK=mynetwork/16
cap_add:
- NET_ADMIN
logging:
driver: json-file
options:
max-size: 10m
ports:
- 9091:9091
restart: always
image: haugene/transmission-openvpn**

— .ovpn file

client
dev tun
proto tcp
remote 173.212.232.148 56478
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA512
cipher AES-256-CBC
ignore-unknown-option block-outside-dns
block-outside-dns
verb 3

-----BEGIN CERTIFICATE-----
<Data>
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
<Data>
-----END CERTIFICATE-----

-----BEGIN PRIVATE KEY-----
<Data>
-----END PRIVATE KEY-----

-----BEGIN OpenVPN Static key V1-----
<Data>
-----END OpenVPN Static key V1-----

Error Logs

Inspect

Stats
Using OpenVPN provider: CUSTOM
Starting OpenVPN using config default.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/16 via 172.17.0.1 dev eth0
Wed Sep 9 19:34:39 2020 Unrecognized option or missing or extra parameter(s) in /etc/openvpn/custom/default.ovpn:13: block-outside-dns (2.4.7)
Wed Sep 9 19:34:39 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020
Wed Sep 9 19:34:39 2020 library versions: OpenSSL 1.1.1c 28 May 2019, LZO 2.10
Wed Sep 9 19:34:39 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Sep 9 19:34:39 2020 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Wed Sep 9 19:34:39 2020 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Sep 9 19:34:39 2020 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Wed Sep 9 19:34:39 2020 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Sep 9 19:34:39 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]173.212.232.140:56478
Wed Sep 9 19:34:39 2020 Socket Buffers: R=[87380->87380] S=[16384->16384]
Wed Sep 9 19:34:39 2020 Attempting to establish TCP connection with [AF_INET]173.212.232.140:56478 [nonblock]
Wed Sep 9 19:34:40 2020 TCP connection established with [AF_INET]173.212.232.140:56478
Wed Sep 9 19:34:40 2020 TCP_CLIENT link local: (not bound)
Wed Sep 9 19:34:40 2020 TCP_CLIENT link remote: [AF_INET]173.212.232.140:56478
Wed Sep 9 19:34:40 2020 TLS: Initial packet from [AF_INET]173.212.232.140:56478, sid=2a3f8335 8854e4ec

**Comment by jaygun** [comment]
Try removing the "block-outside-dns" from your ovpn file. This is a Windows-specific option whereas this container is Linux-based.

See: https://github.com/kylemanna/docker-openvpn/issues/330
