### ISSUE TITLE
Can't start with Mullvad? RTNETLINK answers: Permission denied

### ISSUE THREAD

**Issue by balogan** [haugene/docker-transmission-openvpn#1359]
**Describe the problem**

Switching from PIA to Mullvad and, can't start the container after provider switch. I run the container with Portainer.

**Add your docker run command**

Here are my environemntal variables
PGID 	1001
VIRTUAL_HOST 	**REDACTED**
VIRTUAL_PORT 	9091
OPENVPN_PROVIDER 	MULLVAD
LOCAL_NETWORK 	192.168.0.0/16
PUID 	1000
LETSENCRYPT_HOST 	**REDACTED**
LETSENCRYPT_EMAIL 	**REDACTED**
CREATE_TUN_DEVICE 	true
OPENVPN_CONFIG 	mullvad_nl_udp
OPENVPN_USERNAME 	**REDACTED**
WEBPROXY_ENABLED 	false
PATH 	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBIAN_FRONTEND 	noninteractive
GLOBAL_APPLY_PERMISSIONS 	true
TRANSMISSION_ALT_SPEED_DOWN 	50
TRANSMISSION_ALT_SPEED_ENABLED 	false
TRANSMISSION_ALT_SPEED_TIME_BEGIN 	540
TRANSMISSION_ALT_SPEED_TIME_DAY 	127
TRANSMISSION_ALT_SPEED_TIME_ENABLED 	false
TRANSMISSION_ALT_SPEED_TIME_END 	1020
TRANSMISSION_ALT_SPEED_UP 	50
TRANSMISSION_BIND_ADDRESS_IPV4 	0.0.0.0
TRANSMISSION_BIND_ADDRESS_IPV6 	::
TRANSMISSION_BLOCKLIST_ENABLED 	false
TRANSMISSION_BLOCKLIST_URL 	http://www.example.com/blocklist
TRANSMISSION_CACHE_SIZE_MB 	4
TRANSMISSION_DHT_ENABLED 	true
TRANSMISSION_DOWNLOAD_DIR 	/downloads/torrents
TRANSMISSION_DOWNLOAD_LIMIT 	150
TRANSMISSION_DOWNLOAD_LIMIT_ENABLED 	0
TRANSMISSION_DOWNLOAD_QUEUE_ENABLED 	false
TRANSMISSION_DOWNLOAD_QUEUE_SIZE 	5
TRANSMISSION_ENCRYPTION 	1
TRANSMISSION_IDLE_SEEDING_LIMIT 	30
TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED 	false
TRANSMISSION_INCOMPLETE_DIR 	/data/incomplete
TRANSMISSION_INCOMPLETE_DIR_ENABLED 	true
TRANSMISSION_LPD_ENABLED 	false
TRANSMISSION_MAX_PEERS_GLOBAL 	400
TRANSMISSION_MESSAGE_LEVEL 	2
TRANSMISSION_PEER_ID_TTL_HOURS 	6
TRANSMISSION_PEER_LIMIT_GLOBAL 	400
TRANSMISSION_PEER_LIMIT_PER_TORRENT 	50
TRANSMISSION_PEER_PORT 	51413
TRANSMISSION_PEER_PORT_RANDOM_HIGH 	65535
TRANSMISSION_PEER_PORT_RANDOM_LOW 	49152
TRANSMISSION_PEER_PORT_RANDOM_ON_START 	false
TRANSMISSION_PEER_SOCKET_TOS 	default
TRANSMISSION_PEX_ENABLED 	true
TRANSMISSION_PORT_FORWARDING_ENABLED 	false
TRANSMISSION_PREALLOCATION 	1
TRANSMISSION_PREFETCH_ENABLED 	1
TRANSMISSION_QUEUE_STALLED_ENABLED 	true
TRANSMISSION_QUEUE_STALLED_MINUTES 	30
TRANSMISSION_RATIO_LIMIT 	1
TRANSMISSION_RATIO_LIMIT_ENABLED 	false
TRANSMISSION_RENAME_PARTIAL_FILES 	true
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED 	true
TRANSMISSION_RPC_BIND_ADDRESS 	0.0.0.0
TRANSMISSION_RPC_ENABLED 	true
TRANSMISSION_RPC_HOST_WHITELIST_ENABLED 	false
TRANSMISSION_RPC_PASSWORD 	**REDACTED**
TRANSMISSION_RPC_PORT 	9091
TRANSMISSION_RPC_URL 	/transmission/
TRANSMISSION_RPC_USERNAME 	**REDACTED**
TRANSMISSION_RPC_WHITELIST 	127.0.0.1
TRANSMISSION_RPC_WHITELIST_ENABLED 	false
TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED 	true
TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED 	false
TRANSMISSION_SEED_QUEUE_ENABLED 	false
TRANSMISSION_SEED_QUEUE_SIZE 	10
TRANSMISSION_SPEED_LIMIT_DOWN 	100
TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED 	false
TRANSMISSION_SPEED_LIMIT_UP 	100
TRANSMISSION_SPEED_LIMIT_UP_ENABLED 	false
TRANSMISSION_START_ADDED_TORRENTS 	true
TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES 	false
TRANSMISSION_UMASK 	2
TRANSMISSION_UPLOAD_LIMIT 	100
TRANSMISSION_UPLOAD_LIMIT_ENABLED 	0
TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT 	14
TRANSMISSION_UTP_ENABLED 	true
TRANSMISSION_WATCH_DIR 	/data/watch
TRANSMISSION_WATCH_DIR_ENABLED 	true
TRANSMISSION_HOME 	/data/transmission-home
TRANSMISSION_WATCH_DIR_FORCE_GENERIC 	false
ENABLE_UFW 	false
UFW_ALLOW_GW_NET 	false
UFW_DISABLE_IPTABLES_REJECT 	false
WEBPROXY_PORT 	8888
HEALTH_CHECK_HOST 	google.com
DOCKER_LOG 	false
OPENVPN_PASSWORD 	m
TRANSMISSION_WEB_HOME 	/data/transmission-home/Shift
TRANSMISSION_PEER_CONGESTION_ALGORITHM 	
TRANSMISSION_RPC_HOST_WHITELIST 	
TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME 	
UFW_EXTRA_PORTS 	
TRANSMISSION_WEB_UI 	
DROP_DEFAULT_ROUTE 	
WEBPROXY_USERNAME 	
WEBPROXY_PASSWORD 	

**Logs**

adding route to local network 192.168.0.0/16 via 172.18.0.1 dev eth0,
Fri Sep 11 15:34:18 2020 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.,
Fri Sep 11 15:34:18 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020,
Fri Sep 11 15:34:18 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10,
Fri Sep 11 15:34:18 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Fri Sep 11 15:34:18 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.134.135:1197,
Fri Sep 11 15:34:18 2020 Socket Buffers: R=[212992->1048576] S=[212992->1048576],
Fri Sep 11 15:34:18 2020 UDP link local: (not bound),
Fri Sep 11 15:34:18 2020 UDP link remote: [AF_INET]185.65.134.135:1197,
Fri Sep 11 15:34:18 2020 TLS: Initial packet from [AF_INET]185.65.134.135:1197, sid=cdecd369 3ba1946a,
Fri Sep 11 15:34:18 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Fri Sep 11 15:34:18 2020 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net,
Fri Sep 11 15:34:18 2020 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v2, emailAddress=security@mullvad.net,
Fri Sep 11 15:34:18 2020 VERIFY KU OK,
Fri Sep 11 15:34:18 2020 Validating certificate extended key usage,
Fri Sep 11 15:34:18 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Fri Sep 11 15:34:18 2020 VERIFY EKU OK,
Fri Sep 11 15:34:18 2020 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=nl-ams-005.mullvad.net, emailAddress=security@mullvad.net,
Fri Sep 11 15:34:18 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558',
Fri Sep 11 15:34:18 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo',
Fri Sep 11 15:34:18 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA,
Fri Sep 11 15:34:18 2020 [nl-ams-005.mullvad.net] Peer Connection Initiated with [AF_INET]185.65.134.135:1197,
Fri Sep 11 15:34:19 2020 SENT CONTROL [nl-ams-005.mullvad.net]: 'PUSH_REQUEST' (status=1),
Fri Sep 11 15:34:19 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.11.0.1,redirect-gateway def1 bypass-dhcp,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,comp-lzo no,route-gateway 10.11.0.1,topology subnet,socket-flags TCP_NODELAY,ifconfig-ipv6 fdda:d0d0:cafe:1197::1001/64 fdda:d0d0:cafe:1197::,ifconfig 10.11.0.3 255.255.0.0,peer-id 3,cipher AES-256-GCM',
Fri Sep 11 15:34:19 2020 OPTIONS IMPORT: compression parms modified,
Fri Sep 11 15:34:19 2020 OPTIONS IMPORT: --socket-flags option modified,
Fri Sep 11 15:34:19 2020 NOTE: setsockopt TCP_NODELAY=1 failed,
Fri Sep 11 15:34:19 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Fri Sep 11 15:34:19 2020 OPTIONS IMPORT: route options modified,
Fri Sep 11 15:34:19 2020 OPTIONS IMPORT: route-related options modified,
Fri Sep 11 15:34:19 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Fri Sep 11 15:34:19 2020 OPTIONS IMPORT: peer-id set,
Fri Sep 11 15:34:19 2020 OPTIONS IMPORT: adjusting link_mtu to 1624,
Fri Sep 11 15:34:19 2020 OPTIONS IMPORT: data channel crypto options modified,
Fri Sep 11 15:34:19 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Fri Sep 11 15:34:19 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Fri Sep 11 15:34:19 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Fri Sep 11 15:34:19 2020 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:12:00:05,
Fri Sep 11 15:34:19 2020 GDG6: remote_host_ipv6=n/a,
Fri Sep 11 15:34:19 2020 ROUTE6: default_gateway=UNDEF,
Fri Sep 11 15:34:19 2020 TUN/TAP device tun0 opened,
Fri Sep 11 15:34:19 2020 TUN/TAP TX queue length set to 100,
Fri Sep 11 15:34:19 2020 /sbin/ip link set dev tun0 up mtu 1500,
Fri Sep 11 15:34:19 2020 /sbin/ip addr add dev tun0 10.11.0.3/16 broadcast 10.11.255.255,
Fri Sep 11 15:34:19 2020 /sbin/ip -6 addr add fdda:d0d0:cafe:1197::1001/64 dev tun0,
RTNETLINK answers: Permission denied,
Fri Sep 11 15:34:19 2020 Linux ip -6 addr add failed: external program exited with error status: 2,
Fri Sep 11 15:34:19 2020 Exiting due to fatal error,
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: MULLVAD,
Starting OpenVPN using config mullvad_nl_udp.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.0.0/16 via 172.18.0.1 dev eth0,
Fri Sep 11 15:35:22 2020 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.,
Fri Sep 11 15:35:22 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020,
Fri Sep 11 15:35:22 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10,
Fri Sep 11 15:35:22 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Fri Sep 11 15:35:22 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.134.132:1197,
Fri Sep 11 15:35:22 2020 Socket Buffers: R=[212992->1048576] S=[212992->1048576],
Fri Sep 11 15:35:22 2020 UDP link local: (not bound),
Fri Sep 11 15:35:22 2020 UDP link remote: [AF_INET]185.65.134.132:1197,
Fri Sep 11 15:35:22 2020 TLS: Initial packet from [AF_INET]185.65.134.132:1197, sid=47c8c638 a818ef0e,
Fri Sep 11 15:35:22 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Fri Sep 11 15:35:22 2020 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net,
Fri Sep 11 15:35:22 2020 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v2, emailAddress=security@mullvad.net,
Fri Sep 11 15:35:22 2020 VERIFY KU OK,
Fri Sep 11 15:35:22 2020 Validating certificate extended key usage,
Fri Sep 11 15:35:22 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Fri Sep 11 15:35:22 2020 VERIFY EKU OK,
Fri Sep 11 15:35:22 2020 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=nl-ams-002.mullvad.net, emailAddress=security@mullvad.net,
Fri Sep 11 15:35:22 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558',
Fri Sep 11 15:35:22 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo',
Fri Sep 11 15:35:22 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA,
Fri Sep 11 15:35:22 2020 [nl-ams-002.mullvad.net] Peer Connection Initiated with [AF_INET]185.65.134.132:1197,
Fri Sep 11 15:35:24 2020 SENT CONTROL [nl-ams-002.mullvad.net]: 'PUSH_REQUEST' (status=1),
Fri Sep 11 15:35:24 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.11.0.1,redirect-gateway def1 bypass-dhcp,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,comp-lzo no,route-gateway 10.11.0.1,topology subnet,socket-flags TCP_NODELAY,ifconfig-ipv6 fdda:d0d0:cafe:1197::1002/64 fdda:d0d0:cafe:1197::,ifconfig 10.11.0.4 255.255.0.0,peer-id 1,cipher AES-256-GCM',
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: compression parms modified,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: --socket-flags option modified,
Fri Sep 11 15:35:24 2020 NOTE: setsockopt TCP_NODELAY=1 failed,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: route options modified,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: route-related options modified,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: peer-id set,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: adjusting link_mtu to 1624,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: data channel crypto options modified,
Fri Sep 11 15:35:24 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Fri Sep 11 15:35:24 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Fri Sep 11 15:35:24 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Fri Sep 11 15:35:24 2020 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:12:00:05,
Fri Sep 11 15:35:24 2020 GDG6: remote_host_ipv6=n/a,
Fri Sep 11 15:35:24 2020 ROUTE6: default_gateway=UNDEF,
Fri Sep 11 15:35:24 2020 TUN/TAP device tun0 opened,
Fri Sep 11 15:35:24 2020 TUN/TAP TX queue length set to 100,
Fri Sep 11 15:35:24 2020 /sbin/ip link set dev tun0 up mtu 1500,
Fri Sep 11 15:35:24 2020 /sbin/ip addr add dev tun0 10.11.0.4/16 broadcast 10.11.255.255,
Fri Sep 11 15:35:24 2020 /sbin/ip -6 addr add fdda:d0d0:cafe:1197::1002/64 dev tun0,
RTNETLINK answers: Permission denied,
Fri Sep 11 15:35:24 2020 Linux ip -6 addr add failed: external program exited with error status: 2,
Fri Sep 11 15:35:24 2020 Exiting due to fatal error,

**Host system:**

Running on a dedicated server
Linux **REDACTED** 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by lukegg** [comment]
Check out #1355. Had the same problem earlier.

**Comment by balogan** [comment]
@lukegg Is there a way to disable ipv6 for just the container?

**Comment by rnyn** [comment]
@balogan I just ran into this issue, and had to disable ipv6 for the container. Im using docker-compose not a docker run command, so rather than a --sysctl flag, I had to use the solution in #847 to comment out the ipv6 line and add pull-filters in the containers config, then it worked.

**Comment by balogan** [comment]
@ryn I'm using a docker run command, I realized I was trying to change it at the host os level instead of the container, once I changed it at the container it began working. It seems to work regardless of if its done with a docker run command or docker compose. I'm closing this issue now.
