### ISSUE TITLE
Transmission variables

### ISSUE THREAD

**Issue by notjoenotjoe** [haugene/docker-transmission-openvpn#1361]
When I add transmission environment variables in the docker run script it runs and starts the container. But nothing is changed. Am I doing something wrong?

docker run --cap-add=NET_ADMIN -d \
              -v /media/2/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=PIA \
              -e OPENVPN_CONFIG=Netherlands \
              -e OPENVPN_USERNAME=nameblahblah \
              -e OPENVPN_PASSWORD=passwordblahblah \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=10.0.0.0/16 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              -e "TRANSMISSION_DOWNLOAD_DIR: /data/Downloads/tmp" \
              -e "TRANSMISSION_INCOMPLETE_DIR_ENABLED: FALSE" \
              haugene/transmission-openvpn

**Comment by readstead** [comment]
Any reason you're using colons instead of equals signs in your Transmission variables?
