### ISSUE TITLE
/scripts/transmission-pre-stop.sh runs after tunnel down

### ISSUE THREAD

**Issue by YujiShen** [haugene/docker-transmission-openvpn#1362]
**Describe the problem**

I would like to paused all my torrents when I kill the container, because some trackers will not allow you to download from multiple IP addresses. If torrents are not paused correctly, the tracker will still have previous records and I have to wait several hours for it to clear.

I put `transmission-remote --torrent all --stop` in /scripts/transmission-pre-stop.sh, but it does not work. First, I suspect the torrents are not really paused after the command. So I wrote a more complex script to make sure all torrents state are "Stopped", I even add sleep after that. But it does not work when I kill the container (tracker still has record). It does work when I call the script directly in the container. 

So I think the /scripts/transmission-pre-stop.sh is running after VPN tunnel is down. Is there a way to run script before the tunnel is down (and before stop transmission)?

**Comment by RickyXwang** [comment]
Hi, I might want something similar as well. Have a couple of questions for you:
Assuming your script works when running manually to have all torrent stopped. 
What triggers your script to run? Also, in which way you are killing the container?

**Comment by YujiShen** [comment]
@RickyXwang Thanks for attention.
1. I went inside container and run the script `/scripts/transmission-pre-stop.sh`.
2. I kill container with docker-compose stop or docker-compose down.

**Comment by haugene** [comment]
Well, sounds reasonable. We need an event to react to though. From what I see in the OpenVPN manual it might look like `down-pre` is an option we might want to try in that case. https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage

**Comment by clement-z** [comment]
I think the `--route-pre-down` option is more suited than `down-pre`:

```
--route-pre-down cmd
    Run command cmd before routes are removed upon disconnection. 
```

It is the behavior I would have expected from the container (and I think other users as well).

An easy fix is to change `--down tunnelDown.sh` to `--route-pre-down tunnelDown.sh` in [openvpn/start.sh#L124](https://github.com/haugene/docker-transmission-openvpn/blob/93d0141d928ec661411e2c6f0e079aeff2c018dd/openvpn/start.sh#L124)

I doubt this could be considered a breaking change, but 🤷

**Comment by haugene** [comment]
I agree @clement-z. I think this will both solve @YujiShen's issue and be more in line with what to expect from the container.
Transmission should be stopped at the first sign of a shutdown coming.

Looking at the [OpenVPN documentation](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage):
```
Script Order of Execution
--up
    Executed after TCP/UDP socket bind and TUN/TAP open.
--tls-verify
    Executed when we have a still untrusted remote peer.
--ipchange
    Executed after connection authentication, or remote IP address change.
--client-connect
    Executed in --mode server mode immediately after client authentication.
--route-up
    Executed after connection authentication, either immediately after, or some number of seconds after as defined by the --route-delay option.
--route-pre-down
    Executed right before the routes are removed.
--client-disconnect
    Executed in --mode server mode on client instance shutdown.
--down
    Executed after TCP/UDP and TUN/TAP close.
--learn-address
    Executed in --mode server mode whenever an IPv4 address/route or MAC address is added to OpenVPN's internal routing table.
--auth-user-pass-verify
    Executed in --mode server mode on new client connections, when the client is still untrusted.
```

Should we change both the --up and --down options for --route-up and --route-pre-down? It seems to be a better fit, and in addition it could save us some trouble with provider config compatibility. Some providers use the up/down for resolv-conf stuff.

**Comment by pkishino** [comment]
I agree with above, simple fix and more useful for the transmission case

**Comment by haugene** [comment]
I created a draft PR for the change @clement-z proposed. I think that should be added for sure. But I'm also thinking of the --up and changing it for --route-up. Seems like the latter doesn't get called with the tun0 ip address. And we use that [here](https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/start.sh#L9) to determine the bind address for Transmission. 

But at that point there are other ways of getting that IP. And as far as I remember we don't use those parameters for anything else.

**Comment by pkishino** [comment]
please try this again with latest release, otherwise create a new issue, thanks
