### ISSUE TITLE
Update transmission-web-control to version 1.6.1

### ISSUE THREAD

**Issue by bperel** [haugene/docker-transmission-openvpn#1367]
A stable version of [transmission-web-control](https://github.com/ronggang/transmission-web-control/releases/tag/v1.6.1-update1) has been released.

Rebuilding the `docker-transmission-openvpn` image should update it.

**Comment by qhartman** [comment]
In the meantime, if you want to get an update in a running container, executing the following will update it:
```
curl -sL `curl -s https://api.github.com/repos/ronggang/transmission-web-control/releases/latest | jq --raw-output '.tarball_url'` | tar -C /opt/transmission-ui/transmission-web-control/ --strip-components=2 -xz 
```

**Comment by haugene** [comment]
Hey guys, thanks for nudging this. I've been a bit AFK the last month. But this should have solved itself by now, right?
Latest tag is built 6 days ago, dev is built 2 days ago. Or do you think I should tag a new release?

**Comment by qhartman** [comment]
When I manually pull a new "latest" it does update, and yes, it seems fixed.

**Comment by qhartman** [comment]
Oh, and to answer your last question, it's probably worth tagging a minor or patch release so people will know that something noteworthy changed. I don't know what formally changed in this version of transmission-web-control, but anecdotally it seems much more well behaved than the previous version.

**Comment by bperel** [comment]
Solved for me as well :-)
