### ISSUE TITLE
Auth fails when using VPNBOOK as vpn provider

### ISSUE THREAD

**Issue by fdisamuel** [haugene/docker-transmission-openvpn#1370]
**Describe the problem**
My container does not start when I use VPNBook as vpn provider because of the failed authentication.

Details
After some research in /openvpn/start.sh I figured out what is wrong: the script uses a credential renewing mechanism to renew vpnbooks's password, which automatically changes over time. Howewer, this password is showed as a picture on the website, so the script uses an OCR api to convert it into text format. In my case the OCR api can not read properly the "password picture" grabbed from the vpnbook website, so it can not authenticate because of using wrong password. 

My question: Is there any method to bypass the OCR part of the script and enter the password manually(with the help of OPENVPN_PASSWORD env. variable)? 

Any help to get this working would be great.

**Comment by haugene** [comment]
Saw this got closed, been a bit hectic here for a while. This seems like something we can fix. Still interested?

**Comment by pkishino** [comment]
no responsem please respond and provide further details for more action
