### ISSUE TITLE
Raspberry Pi image issues - TLS errors upon restart 

### ISSUE THREAD

**Issue by andsoitgoes** [haugene/docker-transmission-openvpn#1372]
**Describe the problem**
This seems to be a relatively constant issue that does tend to resolve itself, but I want to try and understand what’s going on and nip it in the bud so I’m not fighting with this going forward. 

It seems to happen when my Pi has gone and run out of space and I have to clear everything out and restart it.

Everything else is running perfectly, but transmission is just... stuck and the log is full of the TLS errors. 

Thanks in advance everyone. 

**Add your docker run command**

sudo docker run --name=transmission \
--cap-add=NET_ADMIN -d \
--restart=always \
-v /mnt/***:/data \
-v /mnt/***:/\

-v /mnt/Volume_2/TV:/tv \
-v /etc/localtime:/etc/localtime:ro \
-e CREATE_TUN_DEVICE=true \
-e OPENVPN_PROVIDER=NORDVPN \
-e OPENVPN_USERNAME=******* \
-e OPENVPN_PASSWORD=******* \
-e WEBPROXY_ENABLED=false \
-e TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete \
-e TRANSMISSION_INCOMPLETE_DIR_ENABLED=true \
-e TRANSMISSION_DOWNLOAD_DIR=/downloads \
-e LOCAL_NETWORK=10.0.0.0/24 \
--log-driver json-file \
--log-opt max-size=10m \
-p 9091:9091 \
haugene/transmission-openvpn:latest-armhf

**Logs**

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Sun Sep 20 21:26:04 2020 /sbin/ip route add 107.181.177.3/32 via 172.17.0.1
Sun Sep 20 21:26:04 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.3.1
Sun Sep 20 21:26:04 2020 /sbin/ip route add 128.0.0.0/1 via 10.8.3.1
Sun Sep 20 21:26:04 2020 Initialization Sequence Completed
Sun Sep 20 21:26:26 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:26 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:26 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:27 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:27 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:29 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:32 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:36 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:51 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:51 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:51 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:51 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:51 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:51 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:52 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:54 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:56 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:26:57 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:27:04 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [3]
Sun Sep 20 21:27:42 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:42 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:45 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:45 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:45 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:45 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:46 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:46 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:46 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:46 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:46 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:46 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:46 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:47 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:47 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:48 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:49 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:52 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:52 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:58 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]
Sun Sep 20 21:27:59 2020 TLS Error: local/remote TLS keys are out of sync: [AF_INET]107.181.177.3:1194 [4]

**Host system:**
Raspberry pi
Docker version 19.03.12

**Comment by haugene** [comment]
Hmm. Not sure why this happens, and I can help you in debugging. But first I want you to pull and run the newest version of the image. I've just changed the base image for the ARM builds so we're running on Alpine instead of debian. I'm posting a message here that I've posted in other issues regarding arm images. I'm not sure it will fix your issue but platform changes and Transmission upgrades can shake things loose. And I need people to test the new images :smile: 

But you're saying this only happens when the pi gets a full disk? Or can it be that the logs fill it? Have you checked the size of the Transmission logs? There has been a couple of issues filed that it can grow a lot. It will be stored in /data/transmission-home

>I've created #1487 that sets up new builds creating multi architecture manifests in Docker Hub. Can you test it by running the `haugene/transmission-openvpn:multiarch` tag and see what results you get?
PS: When this is merged I will delete the multiarch tag and go back to dev/latest and version tags.
