### ISSUE TITLE
Mullvad has decommed some servers it looks like in NY and NJ

### ISSUE THREAD

**Issue by CyberDefenseTiger** [haugene/docker-transmission-openvpn#1376]
**Which provider?**
Mullvad

**Where are the configs?**
https://mullvad.net/en/account/#/openvpn-config/

They seemed to have decommissioned some old servers for new york and new jersy  as my logs say name resolution failed and when i looked on there site they were no longer listed.
[mullvad_openvpn_windows_us_uyk.1.zip](https://github.com/haugene/docker-transmission-openvpn/files/5283687/mullvad_openvpn_windows_us_uyk.1.zip)
[mullvad_openvpn_windows_us_nyc.zip](https://github.com/haugene/docker-transmission-openvpn/files/5283694/mullvad_openvpn_windows_us_nyc.zip)

**Comment by haugene** [comment]
#1433

**Comment by haugene** [comment]
#1509 is merged to dev. It can be tested with the :dev tag until it is merged to master and included in a release.
