### ISSUE TITLE
Route other containers' web traffic through transmission-openvpn (Synology)

### ISSUE THREAD

**Issue by RafaelGPinto** [haugene/docker-transmission-openvpn#1378]
Hi!
I think I have my docker transmission-openvpn already working properly but I would like that other container also uses the openvpn connection.
I already set up the ports on transmission-openvpn docker and added the environment variable:

LOCAL_NETWORK=192.168.0.0/24

I saw in other topics to include --net container:transmission (assuming transmission is the container where I'm running openvpn) but although the other containers starts without issues (Sonarr, radarr & jacket), I can't access to WEB UI of any of them.

Any idea? 

How I can test afterward if it's working?

Thanks in advance

**Comment by Navino16** [comment]
I already done something like that.

Include --net container:transmission is the right way to do it BUT your containers who use the openvpn container as internet connection are not directly accessible. You have to access them trought your openvpn container.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/9685 - see also the linked issues in that discussion

**Comment by RafaelGPinto** [comment]
Hello!
Thanks for the support so far.
I was unable to solve my issue so far.

I'm trying now with docker compose but still I have some issues. Can you please check my compose file and check if everything is fine?

> `services:
    transmission:
        container_name: transmission
        volumes:
            - /volume1/docker/transmission:/config
            - /volume1/downloads/torrents:/downloads/torrents
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=NORDVPN
            - NORDVPN_PROTOCOL=tcp
            - NORDVPN_COUNTRY=XX
            - OPENVPN_USERNAME=XXXXXXXXXXXXX
            - OPENVPN_PASSWORD=XXXXXXXXXXXXX
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.1.0/16
            - PUID=1031
            - PGID=65539
            - TRANSMISSION_WATCH_DIR=/downloads/torrents/inQueue
            - TRANSMISSION_INCOMPLETE_DIR=/downloads/torrents/inProgress
            - TRANSMISSION_DOWNLOAD_DIR=/downloads/torrents/completed

        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m

        networks:
            - mediaNet
                driver: bridge
        ports:
            - 9091:9091 # Transmission WebUI
            - 9117:9117 # Jackett Ports
            - 8989:8989 # Sonarr Ports
            - 7878:7878 # Radarr Ports

        image: haugene/transmission-openvpn

services:
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1031
            - PGID=65539
            - TZ=Europe/Lisbon
            - UMASK_SET=022 #optional
        volumes:
            - /Volume1/docker/sonarr:/config
            - /volume1/TV series:/TVSeries
            - /Volume1/downloads:/downloads
    
        network_mode: "service:transmission"
        
   # --net container:transmission
        restart: unless-stopped

services:
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1031
            - PGID=65539
            - TZ=Europe/Lisbon
            - UMASK_SET=022 #optional
        volumes:
            - /Volume1/docker/radarr:/config
            - /Volume1/movies:/movies
            - /Volume1/downloads:/downloads
        network_mode: "service:transmission"
        
        #--net container:transmission

        restart: unless-stopped

services:
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        environment:
            - PUID=1031
            - PGID=65539
            - TZ=Europe/Lisbon
            #- AUTO_UPDATE=true #optional
            #- RUN_OPTS=run options here #optional
        volumes:
            - /volume1/docker/jacket:/config
            - /volume1/downloads/torrents:/downloads/torrents
        network_mode: "service:transmission"
        
    #--net container:transmission
        restart: unless-stopped`

**Comment by ilike2burnthing** [comment]
Add NORDVPN_CATEGORY - https://haugene.github.io/docker-transmission-openvpn/nordvpn-script/

**Comment by RafaelGPinto** [comment]
Thanks.

But still I'm not able to even start. Mentions a error on network. There is any syntax error?

**Comment by RafaelGPinto** [comment]
The error is:

ERROR: Service 'jackett' uses the network stack of service 'transmission' which is undefined.

**Comment by edgd1er** [comment]
@RafaelGPinto 

Transmission service has no network defined. In your docker-composer, I guess there a mix between a network definition and a network assignement.

this kind of block is a network definition and is expected to be outside of a service
```
    networks:
        - mediaNet
            driver: bridge
```
a network bound is expected inside the service block:
```
 networks:
    - mediaNet
```

I'm not familiar with network_mode: "service:xxx" notation but I've found a docker-compose example that may help you, it shows how are defined network and how they are attached to a service.
https://community.traefik.io/t/docker-compose-with-network-mode-service-service-name/3395

**Comment by RafaelGPinto** [comment]
Cheers! Thanks! I no longer received that error but I have now a permission error. Strange.

I've created a new user and group (those UID and PGID I'm using) with write access to all needed folders. I also included admin user into this group.

I'm accessing ssh with my admin user but I'm receiving the error: "Permission denied".

What I've missed?

**Comment by RafaelGPinto** [comment]
I'm still with issues regarding network mode.
[docker-compose.txt](https://github.com/haugene/docker-transmission-openvpn/files/5321948/docker-compose.txt)

I'm real lost here :(

**Comment by ilike2burnthing** [comment]
See - https://github.com/haugene/docker-transmission-openvpn/issues/991#issuecomment-569429425

The only lines which appear to be of note, and are missing from yours, seem to be:
```
services:
  transmission:
    devices:
      - "/dev/net/tun"
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${MOUNT_POINT}/transmission:/data
    environment:
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
```

They also don't use separate `services:` entries for each container, but I'm not sure if that actually makes any difference (I doubt it).

**Comment by edgd1er** [comment]
@RafaelGPinto 

As for the network problem, your docker-compose (external: true) is saying "network is created in another docker-compose or docker network command". I guess it's not true.
Either you create the network before launching the docker-compose up or you remove the external=true.

**Comment by RafaelGPinto** [comment]
@edgd1er @ilike2burnthing 
Thanks to both. I finally got my dock compose running :)

Now I can't login into transmission, sonarr etc GUI. How I can access it?
Thanks

**Comment by ilike2burnthing** [comment]
You need to add radarr's port under radarr, sonarr's port under sonarr, and jackett's port under jackett, as well as having them all under transmission.

Can you not access transmission? Anything showing up in the logs?

**Comment by RafaelGPinto** [comment]
I was thinking that sonarr/radarr containers wouldn't have any port assignment, and all of them are under transmission.

No, using my local network + transmission port doesn't work (192.168... ) 

I also noticed something strange: I can't access to NAS using mac or windows SMB. Strange! :(

**Comment by ilike2burnthing** [comment]
Anything in Transmission's logs?
