### ISSUE TITLE
Humongous transmission.log causes container to go unhealthy and unresponsive.

### ISSUE THREAD

**Issue by dpellegr** [haugene/docker-transmission-openvpn#1391]
Hello,

I have been running the container for a couple of years and noted that recently, although apparently up and running, the container was reported unhealthy and I had a lot of issues managing it (stopping, updating, ...).

I had found that `transmission-home/transmission.log` had grown past 1.5 GB. After deleting it and restarting the container, this is now healthy and resposive.

Any advice to prevent the same in the future?

Thanks!

**Comment by ksurl** [comment]
set the log size to something reasonable. the example docker compose sets it 10mb.

**Comment by mhbates** [comment]
> set the log size to something reasonable. the example docker compose sets it 10mb.

Strange, I'm using docker run with the "--log-opt max-size=10m" and it doesn't seem to work. In fact, I can't remember the last time it actually worked, if it ever did. I had to set up a cron a long time ago to periodically delete the log file because of how large it got.

Is it working for anybody else using docker run?

**Comment by pkishino** [comment]
Works fine for me, docket on mac, log stays nice and small, rotates after 10mb about, creates a few logs then deletes oldest I believe.. have to check how many

**Comment by vorwrath** [comment]
Isn't that configuration option for docker's log, whereas the ticket relates to transmission's log?

Does setting the LOG_TO_STDOUT environment variable to true and then rotating docker's log as discussed solve the problem?

**Comment by pkishino** [comment]
hmm, I just checked and my transmission-daemon.log was only around 150mb since march last year.. anyway,
did a quick check and transmission itself doesn't have log rotate..but easy to setup a cron job that cleans every now and then or if over a certain size..

**Comment by mhbates** [comment]
It's probably related to number of torrents. I had a cron job just wipe the log weekly, but I'll bump it up to daily now. That should be enough.
