### ISSUE TITLE
Raspberry Pi Dockerfile.armhf fails to build

### ISSUE THREAD

**Issue by nuTTeLLo** [haugene/docker-transmission-openvpn#1394]
**Describe the problem**

Have been trying for a few days trying to get the official image (latest-armhf) to work with system but it keeps getting disconnected after a minute and restarts, even when it is connected, trackers themselves are unconnectable via expressvpn (I might submit another bug report for this after I try a few other options) so thought I would try building from source instead. But using the current master branch, this fails to build due to some issues in the dependency tree.
Thinking it could be a connection issue from the logs but unsure if this is really the case or an issue where the repo has moved and it has not been updated.

**Add your docker run command**

`docker build -f Dockerfile.armhf -t local/expressvpntransmission .`

**Logs**

This is the docker build log (cropped to the failed step):
`   
Step 5/13 : RUN apt-get update     && apt-get -y install apt-utils transmission-cli transmission-common transmission-daemon     && apt-get install -y dumb-init unzip
 p7zip-full p7zip openvpn curl ufw git tinyproxy jq bash     && apt-get -y upgrade     && curl -L -o /tmp/release.zip https://github.com/Secretmapper/combustion/arch
ive/release.zip     && unzip /tmp/release.zip -d /opt/transmission-ui/     && rm /tmp/release.zip     && git clone git://github.com/endor/kettu.git /opt/transmission
-ui/kettu     && mkdir /opt/transmission-ui/transmission-web-control     && curl -sL `curl -s https://api.github.com/repos/ronggang/transmission-web-control/releases
/latest | jq --raw-output '.tarball_url'` | tar -C /opt/transmission-ui/transmission-web-control/ --strip-components=2 -xz     && ln -s /usr/share/transmission/web/s
tyle /opt/transmission-ui/transmission-web-control     && ln -s /usr/share/transmission/web/images /opt/transmission-ui/transmission-web-control     && ln -s /usr/sh
are/transmission/web/javascript /opt/transmission-ui/transmission-web-control     && ln -s /usr/share/transmission/web/index.html /opt/transmission-ui/transmission-w
eb-control/index.original.html     && apt-get purge git     && apt-get autoremove --purge     && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*     &
& curl -L https://github.com/jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-armhf-v0.6.0.tar.gz     | tar -C /usr/local/bin -xzv     && groupmod -g 10  Connection failed [IP: 93.93.128.191 80]                                       Fetched 16.2 kB in 1min 28s (183 B/s)                                            R  Connection failed [IP: 93.93.128.191 80]                                        Fetched 16.2 kB in 1min 28s (183 B/s)                                             
Reading package lists...                                                          W: Failed to fetch http://archive.raspberrypi.org/debian/dists/buster/InRelease   Connection failed [IP: 176.126.240.84 80]                                         
W: Failed to fetch http://archive.raspbian.org/raspbian/dists/buster/non-free/bin ary-armhf/Packages  Connection failed [IP: 93.93.128.191 80]                      W: Failed to fetch http://archive.raspbian.org/raspbian/dists/buster/main/binary- 
armhf/Packages  Connection failed [IP: 93.93.128.191 80]                          W: Failed to fetch http://archive.raspbian.org/raspbian/dists/buster/contrib/bina ry-armhf/Packages  Connection failed [IP: 93.93.128.191 80]                       
  Connection failed [IP: 93.93.128.191 80]                                       Fetched 16.2 kB in 1min 28s (183 B/s)                                            Reading package lists...                                                         Reading package lists...                                                         W: Failed to fetch http://archive.raspberrypi.org/debian/dists/buster/InRelease  Connection failed [IP: 176.126.240.84 80]                                        W: Failed to fetch http://archive.raspbian.org/raspbian/dists/buster/non-free/binary-armhf/Packages  Connection failed [IP: 93.93.128.191 80]                     W: Failed to fetch http://archive.raspbian.org/raspbian/dists/buster/main/binary-armhf/Packages  Connection failed [IP: 93.93.128.191 80]                         W: Failed to fetch http://archive.raspbian.org/raspbian/dists/buster/contrib/binary-armhf/Packages  Connection failed [IP: 93.93.128.191 80]                      W: Failed to fetch http://archive.raspbian.org/raspbian/dists/buster/rpi/binary-armhf/Packages  Connection failed [IP: 93.93.128.191 80]                          W: Some index files failed to download. They have been ignored, or old ones used instead.                                                                         Reading package lists...                                                         Building dependency tree...                                                      Reading state information...                                                     Package apt-utils is not available, but is referred to by another package.       This may mean that the package is missing, has been obsoleted, or                is only available from another source                                            However the following packages replace it:                                         apt                                                                                                                                                             E: Package 'apt-utils' has no installation candidate                             E: Unable to locate package transmission-cli                                     E: Unable to locate package transmission-common                                  E: Unable to locate package transmission-daemon                                  The command '/bin/sh -c apt-get update     && apt-get -y install apt-utils transmission-cli transmission-common transmission-daemon     && apt-get install -y dumb-init unzip p7zip-full p7zip openvpn curl ufw git tinyproxy jq bash     && apt-get -y upgrade     && curl -L -o /tmp/release.zip https://github.com/Secretmapper/combustion/archive/release.zip     && unzip /tmp/release.zip -d /opt/transmission-ui/     && rm /tmp/release.zip     && git clone git://github.com/endor/kettu.git /opt/transmission-ui/kettu     && mkdir /opt/transmission-ui/transmission-web-control     && curl -sL `curl -s https://api.github.com/repos/ronggang/transmission-web-control/releases/latest | jq --raw-output '.tarball_url'` | tar -C /opt/transmission-ui/transmission-web-control/ --strip-components=2 -xz     && ln -s /usr/share/transmission/web/style /opt/transmission-ui/transmission-web-control     && ln -s /usr/share/transmission/web/images /opt/transmission-ui/transmission-web-control     && ln -s /usr/share/transmission/web/javascript /opt/transmission-ui/transmission-web-control     && ln -s /usr/share/transmission/web/index.html /opt/transmission-ui/transmission-web-control/index.original.html     && apt-get purge git     && apt-get autoremove --purge     && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*     && curl -L https://github.com/jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-armhf-v0.6.0.tar.gz     | tar -C /usr/local/bin -xzv     && groupmod -g 1000 users     && useradd -u 911 -U -d /config -s /bin/false abc     && usermod -G users abc' returned a non-zero code: 100 `

**Host system:**

Running on Raspberry Pi 4B 4GB
Docker version 19.03.12, build 48a6621

**Comment by haugene** [comment]
Hmm. Just merged changes to these images and they build on CircleCI. You're getting a lot of "connection failed" and "failed to fetch" from the raspbian archive apt repository. This could be a temporary outage on their side, but if not it looks to me like connectivity issues from your side.

Anyways. I'm not too well versed in the Raspberry Pi architecture sphere but. With a raspberry pi 4b shouldn't you run the 64 bit version? I just merged #1351 that fixes an issue in the arm64 image but it's currently only on the dev branch.

Can you try to run again using the tag `dev-arm64`?

**Comment by nuTTeLLo** [comment]
Unfortunately I can't use arm64 as I am running on raspbian which is still a 32-bit OS.
The 64-bit version is currently still in beta and not on official channels yet.
Let me try mucking about a bit more see what I can figure out.

**Comment by haugene** [comment]
Hey again @nuTTeLLo. Have you had any progress? I've been running around putting out minor fires after the update to 3.0 of this image. Anyways, I was planning to have a thorough look at the arm based images now.

So I was wondering if you were still interested in getting this up and running and if you maybe could do some testing along the way, as I don't have a Raspberry Pi to test on?

I can build a bunch of versions and then you can test what works. A Raspberry Pi 4B with Raspbian should be a very popular combination and I want it to be supported. I've also looked at switching the arm base image to alpine so that we can re-use the same Dockerfile across all distros. That would be maintenance heaven :smile: 

I've been looking at base images by balena: https://www.balena.io/docs/reference/base-images/base-images/
And also their device types: https://www.balena.io/docs/reference/base-images/devicetypes/
What is the combo that you want here?

Have you tried running the `latest-armhf` image? It would be 32 bit, but there could possibly be a problem because it is `armv7hf` based?

**Comment by haugene** [comment]
I've created #1487 that sets up new builds creating multi architecture manifests in Docker Hub. Can you test it by running the `haugene/transmission-openvpn:multiarch` tag and see what results you get?
PS: When this is merged I will delete the multiarch tag and go back to dev/latest and version tags.
