### ISSUE TITLE
PIA NextGen servers

### ISSUE THREAD

**Issue by TheDutchMC** [haugene/docker-transmission-openvpn#1401]
**Which provider?**

PIA

PIA is switching off their Legacy servers, I'm not sure if this docker image already uses the NextGen servers (with portforwarding), but if not, it'll break for PIA at the end of the month

**Where are the configs?**

[OVPN files](https://www.privateinternetaccess.com/openvpn/openvpn-nextgen.zip)
[NextGen PF](https://www.privateinternetaccess.com/helpdesk/news/posts/introducing-next-generation-port-forwarding)

**Comment by ilike2burnthing** [comment]
https://github.com/haugene/docker-transmission-openvpn/pull/1398
