### ISSUE TITLE
Developer tag v3

### ISSUE THREAD

**Issue by mouzzampk2014** [haugene/docker-transmission-openvpn#1409]
Hi, I thought any changes made in settings.json file will revert back after I restart the container or new image build. 

Today I recieved a new update and restarted the container but settings didn't revert back :) that means I can make changes in the settings without using environment variables? :)

Thank you

**Comment by ilike2burnthing** [comment]
Persistent settings were added about 2 months ago - https://github.com/haugene/docker-transmission-openvpn/pull/1323 and https://github.com/haugene/docker-transmission-openvpn/pull/1324
