### ISSUE TITLE
I am sure I am an idiot....

### ISSUE THREAD

**Issue by crsavage1** [haugene/docker-transmission-openvpn#141]
I have configured the container and entered all of the variables for PIA.  When I start the container though, the logs show "Could not find OpenVPN provider: PIA".  My issue is, if I start openvpn on the host, it obviously locks me out remotely from the server and I do not want all of the internet traffic to traverse the tunnel, but rather just transmission which is my understanding of how the container works.  I sincerely apologize as I relatively new to openvpn but I am interested in just having the transmission use openvpn.  I installed the packages from PIA and it successfully will connect to the vpn, but as I mention then I lose the ability to manage the host.  I am missing a simply step I am sure....thanks for any insight.

**Comment by haugene** [comment]
Please post your `docker run ...` command, anonymizing your username/password of course. And the logs.

**Comment by haugene** [comment]
Closed due to inactivity, reopen if it's still an issue and provide command and logs.
