### ISSUE TITLE
unknown bug

### ISSUE THREAD

**Issue by etnaaflonne123** [haugene/docker-transmission-openvpn#1410]
this is gonna get complex so buckle up

ok if i get and start transmission i have 0 issues 
if i get and start "nordvpn" via docker even if its though open vpn that i also have a 2nd copy of i get 0 issues 

however if i get and start your copy i cannot connect to nord i get a password incorrect issue no matter what i do (i have to run with priv mode) then i get errors all over the place.

so i changed the settings and added prov mode + changed pid  now it says wrong user so i tried 10 pids (mostly wrong ones) 998 works but then i get another error about a missing port  i have ask 30 ppl and nobody has a clue.

id also like to add if i start this container with bad info it starts and is "running" just fine however nothing works AT ALL and nothing connects 

if i add in correct info and fix all the ports right it never starts it says"starting"  but never gets to green. 
i also see it log into nordvpn with 0 issues  and i can even pull up the transmission page however nothing will ever download i get 0 though put on any channel  no matter the setting 

(my OS is  OMV 5  im using portainer tho i have tried yacht  both have the very same issue)
i dont check this much i do have discord if u have it im open to contact all i wanna do is replace some things i already own or share with myself from home when im out and forgot a iso but my isp blocks everything and counts even legal torrenting as illegal and swats u with threats and fines ;/  

please help me (discord is twintailterror 1818 id love to request a few other dockers if your up for it or maybe you can help me get my nord and traffic to talk via separate container my goal here is to get sonarr working so i can get tv or movies and also share home iso's with myself  radarr might be cool to 

im trying to simplify it for my pc dumb family anybody willing to help a docker newb welcome to contact me =3

[[[[[[[[ side note my actual interal ip is 10.0.0.0/24  and docker is normal 172.x.x.x so i did change that but i have tried the 192 and 0.0.0.0 as well most yeld random errors but the 10.  will give you this error ]]]]]]]]]]   i cannot find any info on this you are my last hope.

![a1](https://user-images.githubusercontent.com/46465728/96744766-3c16d800-137a-11eb-9c85-aa8e418b6a43.png)
![a2](https://user-images.githubusercontent.com/46465728/96744770-3d480500-137a-11eb-9d26-25d55f834c9e.png)
![a3](https://user-images.githubusercontent.com/46465728/96744773-3d480500-137a-11eb-935d-5ab7a2d2e9e5.png)
![a4](https://user-images.githubusercontent.com/46465728/96744776-3de09b80-137a-11eb-801a-71bcf169e5df.png)

 
[best of logs.txt](https://github.com/haugene/docker-transmission-openvpn/files/5417155/best.of.logs.txt)

logs are as follows

**Comment by etnaaflonne123** [comment]
ok so i found the issue and its not that simple.

the main issue is my dns and your current layout wont allow me to change that ok so comcast iin my area blocks all sorts of things one be 1194 and another 1080,   so i need to change my dns to 1.1.1.1  the only current way to do this is to go into the container and change it with vim (and its not easy) and this has to be repeated every single time i restart.

oddly enough i have tried the other 4 combo containers and they are worse they say the "open vpn file is missing"  even if i add one nothing happens.  this is the only one that allows me to just type "nord"  and have it work.


i did get a TON of help from selfhostedpro (the maker of yacht) with out him id a never known it was both the container AND my isp that were causing issues so it currently works but if i reboot or repull i have to do it all over again.

can you pls add in the change my dns feature so i can pick 1.1.1.1 with out a ton of editing ? pretty pls with sugar on top.

**Comment by etnaaflonne123** [comment]
(side note the fix went something like this ) 
pip install docker-compose
cd /config
mkdir compose
mkdir compose/openvpn
 apk add g++ make
wget https://drop.sklu3.us/iwFVpcSk/requirements.txt
pip install -r requirements.txt

lastly connect to container and type 
vi /etc/resolv.conf  del the real ip and add 1.1.1.1
then !wq but delete the period it auto adds.

**Comment by pkishino** [comment]
Look at the wiki, you can set dns for the container in the docker run command.. from top of my head I think it’s just —dns 1.1.1.1

**Comment by ilike2burnthing** [comment]
In Portainer you can edit the container settings, click on the Network tab, and add your primary and secondary DNS servers, then redeploy.

**Comment by etnaaflonne123** [comment]
> 
> 
> Look at the wiki, you can set dns for the container in the docker run command.. from top of my head I think it’s just —dns 1.1.1.1

can you link where it says this so i can get the wording on the "dns" part just right? if it works that would be freaking fantastic !!!!!!

me and a few other ppl are having some issues so it really help

**Comment by pkishino** [comment]
Did you try —dns cause that’s all there is..
http://haugene.github.io/docker-transmission-openvpn/known-issues/

**Comment by haugene** [comment]
The official way to set dns servers is as has been mentioned here. You add `--dns x.x.x.x` to the run command and there is a similar option for docker-compose.

Docker enables DNS entries for other services running in the same Docker network. If you don't need that then you can also use:
```
OVERRIDE_DNS_1=8.8.8.8
OVERRIDE_DNS_2=8.8.4.4
```
This will override /etc/resolv.conf on each startup.
