### ISSUE TITLE
PIA legacy infrastructure support ends 31st of October

### ISSUE THREAD

**Issue by vosdev** [haugene/docker-transmission-openvpn#1412]
**Which provider?**
PIA

**What changed?**

The new infrastructure replaced the domainname from privateinternetaccess.com to privacy.network
```diff
-remote spain.privateinternetaccess.com 1198
+remote spain.privacy.network 1198
```

Changes can be seen here:

https://www.privateinternetaccess.com/pages/network/

A lot of locations already no longer work such as:
- Spain
- Swiss
- Italy
- France
- Austria
- Romania

**Comment by haugene** [comment]
See #1334

**Comment by vosdev** [comment]
Already fixed in the dev branch, oopsie! 👍
