### ISSUE TITLE
Remove torrents that have been seeding for longer than a certain period

### ISSUE THREAD

**Issue by HotBlack77** [haugene/docker-transmission-openvpn#1422]
**Is your feature request related to a problem? Please describe.**
Transmission lacks a feature to remove a torrent that has been completed and been seeding for some chosen period of time. It is a feature that has been frequently requested to be added to Transmission (see https://trac.transmissionbt.com/ticket/3779 https://github.com/transmission/transmission/issues/111 https://github.com/transmission/transmission/issues/217 https://github.com/transmission/transmission/issues/575 ), but it seems that the developers dont want to implement it. The best explanation I have been able to find is that it is "against torrent netiquete". 

**Describe the solution you'd like**
Run a cron job within the Docker container that runs a script which uses transmission-remote (already in place) and the various environment variables defined within the container to compare the seeding time (only defined for completed torrents) with a cutoff time, defined as a new environment variable, if the torrent has been seeding for longer than the chosen time the torrent, but not the associated data, is removed . 

**Describe alternatives you've considered**
I wrote a script that does this, but only after getting frustrated with Sonarr and Radarr's frequently broken functionaity to handle this and discovering that Transmission really does not already support this (almost all other torrent clients do). It should be noted that using an "after torrent complete script" hangs transmission if you want a delay before the torrent is removed and removing a torrent too quickly messes up Sonarr and Radarr's handling of completed torrents.

**Additional context**
Here is the script I am using, it is set to run as an hourly cron job on the host which then uses docker exec to run it within the container (the script is placed in the config volume which is mounted within the container). Currently it does not get the seeding cutoff time from an environment variable inside the container, as such a variable is not currently defined. Instead it just uses a time defined in the script. If you want to add the script to the container the new environment variable should be defined and a check added that if the variable is empty the script should exit. The environment variable needed takes the cutoff time in seconds and is intended to be quite a large value (e.g. 60 days in seconds). The script just does what I described above and also produces output to docker logs when it is run. 

```
#!/bin/sh
# Automatically remove a torrent after a specified period of time
# Written to work with the environment variables of the Haugene transmission docker container
#===USER VARIABLES===
#Seconds that torrents seed for [5184000 = 60 days] [864000 = 10 days] [43200 = 12 hours]
SEED_CUTOFF=14400
#===SCRIPT===
if [[ "${SEED_CUTOFF}" == "" ]]; then exit 1; fi
#Build connection string
TRANSMISSION_COMMAND="/usr/bin/transmission-remote localhost:${TRANSMISSION_RPC_PORT} --auth ${TRANSMISSION_RPC_USERNAME}:${TRANSMISSION_RPC_PASSWORD}"
TORRENT_ID_LIST=`$TRANSMISSION_COMMAND -l | sed -e '1d' -e '$d' | awk '{print }' | sed -e 's/[^0-9]*//g'`
# Show output header
printf '%-3.3s %-50.50s  %-8.8s  %-6.6s  %s \n' "ID" "NAME" "SEEDTIME" "ACTION" "RESULT"
# Write to docker log
NOW=$(date)
printf '%s Running torrent cleanup script with cutoff: %ds \n' "$NOW" $SEED_CUTOFF >/proc/1/fd/1
# Parse all torrents in client
for TORRENT_ID in $TORRENT_ID_LIST; do
    # Get Torrent name and seeding time in seconds
    TORRENT_NAME=`$TRANSMISSION_COMMAND --torrent $TORRENT_ID --info | grep "Name:" | sed 's/.*Name: \(.*\)/\1/'`
    TORRENT_SEEDTIME=`$TRANSMISSION_COMMAND --torrent $TORRENT_ID --info | grep "Seeding Time" | sed 's/.*(\(.*\) seconds)/\1/'`
    # Set seedtime to Zero if incomplete
    if [[ "${TORRENT_SEEDTIME}" == "" ]]; then TORRENT_SEEDTIME=0; fi
    # Compare torrent seedtime to cutoff
    if [ $TORRENT_SEEDTIME -gt $SEED_CUTOFF ]; then TORRENT_ACTION="remove"; else TORRENT_ACTION="keep"; fi
    # Perform Action
    ACTION_RESULT="(no action taken)"
    if [[ "${TORRENT_ACTION}" == "remove" ]]; then
        # Remove torrent (does not delete data)
        ACTION_RESULT=`$TRANSMISSION_COMMAND --torrent $TORRENT_ID --remove | sed 's/^.\{33\}//'`
        # Write entry in docker log
        printf 'Removed %s (seed time: %ds) [%s] \n' "${TORRENT_NAME}" $TORRENT_SEEDTIME "${ACTION_RESULT}" >/proc/1/fd/1    
    fi
    # Show item status
    printf '%-3d %-50.50s  %7ds  %-6.6s  %s \n' $TORRENT_ID "${TORRENT_NAME}"  $TORRENT_SEEDTIME "${TORRENT_ACTION}" "${ACTION_RESULT}"
done
```

**Comment by pkishino** [comment]
Hmmm, not so active these days on here but saw this...I must say I agree with t transmission devs, this behavior should be external to the client. Radar and sonarr, at least in my opinion, work fine with this. I’ve set idle to 1 month and seed to 10:1 and it works pretty well, now and then some strange behavior where it misses to remove one but otherwise fine

**Comment by HotBlack77** [comment]
Hmm... I found lots of strange behaviour with Sonarr and Radarr v3, are you running v2 or v3?
Anyway, I thought my script might help some users, especially if you are prone to also manually adding some torrents now and then. A key point in what I sketched above, was that if a user did not want to use the feature they would not need to anything, only users who want this would need to set a new docker environment variable for the cutoff time. This is strictly meant as an optional extra for those who want this feature.

**Comment by pkishino** [comment]
FYI I’m using v3 since a few months ago without issue, running in macOS

**Comment by d4g79** [comment]
i added the script to the mounted folder of the Transmission container. Then entered the console in Portainer for Transmission created a new cronjob and had the script run every hour. Hope this work i am testing currently. I have chmod the script also. If i wanted to have the option to remove and delete where would i change this in the script.

**Comment by HotBlack77** [comment]
@d4g79 Yeah, I had this in my original script, but when posting here I removed it as to incorporate it into the container would then require two new environment variables. 

Below is a version of the script which has a new "user variable" on line 7, just set it to either remove or remove & delete and the script will behave accordingly. There is also a check that you choose one of the two valid choices or it exits, this is again more in place to support the user variable being set from an environment variable, but also to make sure a typo does not lead to the script doing something crazy with your torrents.

```
#!/bin/sh
# Automatically remove a torrent after a specified period of time
# Written to work with the environment variables of the Haugene transmission docker container
#===USER VARIABLES===
#Seconds that torrents seed for [5184000 = 60 days] [864000 = 10 days] [43200 = 12 hours]
SEED_CUTOFF=14400
#Choose between "--remove" or "--remove-and-delete"
REMOVAL_COMMAND="--remove"
#===SCRIPT===
if [[ "${SEED_CUTOFF}" == "" ]]; then exit 1; fi
if ! ( [[ "${REMOVAL_COMMAND}" == "--remove" ]] || [[ "${REMOVAL_COMMAND}" == "--remove-and-delete" ]] ); then exit 2; fi
#Build connection string
TRANSMISSION_COMMAND="/usr/bin/transmission-remote localhost:${TRANSMISSION_RPC_PORT} --auth ${TRANSMISSION_RPC_USERNAME}:${TRANSMISSION_RPC_PASSWORD}"
TORRENT_ID_LIST=`$TRANSMISSION_COMMAND -l | sed -e '1d' -e '$d' | awk '{print }' | sed -e 's/[^0-9]*//g'`
# Show output header
printf '%-3.3s %-50.50s  %-8.8s  %-6.6s  %s \n' "ID" "NAME" "SEEDTIME" "ACTION" "RESULT"
# Write to docker log
NOW=$(date)
printf '%s Running torrent cleanup script with cutoff: %ds \n' "$NOW" $SEED_CUTOFF >/proc/1/fd/1
# Parse all torrents in client
for TORRENT_ID in $TORRENT_ID_LIST; do
    # Get Torrent name and seeding time in seconds
    TORRENT_NAME=`$TRANSMISSION_COMMAND --torrent $TORRENT_ID --info | grep "Name:" | sed 's/.*Name: \(.*\)/\1/'`
    TORRENT_SEEDTIME=`$TRANSMISSION_COMMAND --torrent $TORRENT_ID --info | grep "Seeding Time" | sed 's/.*(\(.*\) seconds)/\1/'`
    # Set seedtime to Zero if incomplete
    if [[ "${TORRENT_SEEDTIME}" == "" ]]; then TORRENT_SEEDTIME=0; fi
    # Compare torrent seedtime to cutoff
    if [ $TORRENT_SEEDTIME -gt $SEED_CUTOFF ]; then TORRENT_ACTION="remove"; else TORRENT_ACTION="keep"; fi
    # Perform Action
    ACTION_RESULT="(no action taken)"
    if [[ "${TORRENT_ACTION}" == "remove" ]]; then
        # Remove torrent (does not delete data)
        ACTION_RESULT=`$TRANSMISSION_COMMAND --torrent $TORRENT_ID $REMOVAL_COMMAND | sed 's/^.\{33\}//'`
        # Write entry in docker log
        printf 'Removed %s (seed time: %ds) [%s] \n' "${TORRENT_NAME}" $TORRENT_SEEDTIME "${ACTION_RESULT}" >/proc/1/fd/1    
    fi
    # Show item status
    printf '%-3d %-50.50s  %7ds  %-6.6s  %s \n' $TORRENT_ID "${TORRENT_NAME}"  $TORRENT_SEEDTIME "${TORRENT_ACTION}" "${ACTION_RESULT}"
done
```

**Comment by d4g79** [comment]
Thanks heaps for the update script. My issue is now I cannot get got to run via a cronjob on the Docker-compose Portioner.

I use the Portainer web GUI  and I enter the Transmission Stack and use console to bring up the cmd line. 

I did a vi cronjob -e and the type visual to see the cronjobs. 

I entered 

* 1 * * * /data/autoremove.sh

Even tried 

* 1 * * * /bin/bash /data/autoremove.sh

But the from does not run. I have a feeling that in the portainer stack for transmission that cron is not dining the daemon. How would you go about run this via a schedule in that portainer transmission stack. 

Any ideas. 

Thanks.

**Comment by d4g79** [comment]
Forgot to add while I am in the console and run sh /data/autoremove in runs but fails on 2 lines [[: not found but this is due to using sh not bash. 

Did bash /data/autoremove and the script ran properly.

**Comment by HotBlack77** [comment]
Ooops there was a mistake in the script

```
#!/bin/sh
# Automatically remove a torrent and delete its data after a specified period of time
# Written to work with the enviroment variables of the Haugene transmission docker container
#===USER VARIABLES===
#Seconds that torrents seed for [5184000 = 60 days] [864000 = 10 days] [43200 = 12 hours]
SEED_CUTOFF=14400
#Choose between "--remove" or "--remove-and-delete"
REMOVAL_COMMAND="--remove"
#
#===SCRIPT===
if [[ "${TORRENT_SEEDTIME}" == "" ]]; then TORRENT_SEEDTIME=0; fi
if ! ( [[ "${REMOVAL_COMMAND}" == "--remove" ]] || [[ "${REMOVAL_COMMAND}" == "--remove-and-delete" ]] ); then exit 2; fi
#Build connection string
TRANSMISSION_COMMAND="/usr/bin/transmission-remote localhost:${TRANSMISSION_RPC_PORT} --auth ${TRANSMISSION_RPC_USERNAME}:${TRANSMISSION_RPC_PASSWORD}"
TORRENT_ID_LIST=`$TRANSMISSION_COMMAND -l | sed -e '1d' -e '$d' | awk '{print $1}' | sed -e 's/[^0-9]*//g'`
# Show output header
printf '%-3.3s %-50.50s  %-8.8s  %-6.6s  %s \n' "ID" "NAME" "SEEDTIME" "ACTION" "RESULT"
# Write to docker log
NOW=$(date)
printf '%s Running torrent cleanup script with cutoff: %ds \n' "$NOW" $SEED_CUTOFF >/proc/1/fd/1
# Parse all torrents in client
for TORRENT_ID in $TORRENT_ID_LIST; do
    # Get Torrent name and seeding time in seconds
    TORRENT_NAME=`$TRANSMISSION_COMMAND --torrent $TORRENT_ID --info | grep "Name:" | sed 's/.*Name: \(.*\)/\1/'`
    TORRENT_SEEDTIME=`$TRANSMISSION_COMMAND --torrent $TORRENT_ID --info | grep "Seeding Time" | sed 's/.*(\(.*\) seconds)/\1/'`
    # Set seedtime to Zero if incomplete
    if [[ "${TORRENT_SEEDTIME}" == "" ]]; then TORRENT_SEEDTIME=0; fi
    # Compare torrent seedtime to cutoff
    if [ $TORRENT_SEEDTIME -gt $SEED_CUTOFF ]; then TORRENT_ACTION="remove"; else TORRENT_ACTION="keep"; fi
    # Perform Action
    ACTION_RESULT="(no action taken)"
    if [[ "${TORRENT_ACTION}" == "remove" ]]; then
        # Remove torrent (does not delete data)
        ACTION_RESULT=`$TRANSMISSION_COMMAND --torrent $TORRENT_ID $REMOVAL_COMMAND | sed 's/^.\{33\}//'`
        # Write entry in docker log
        printf 'Removed %s (seed time: %ds) [%s] \n' "${TORRENT_NAME}" $TORRENT_SEEDTIME "${ACTION_RESULT}" >/proc/1/fd/1
    fi
    # Show item status
    printf '%-3d %-50.50s  %7ds  %-6.6s  %s \n' $TORRENT_ID "${TORRENT_NAME}"  $TORRENT_SEEDTIME "${TORRENT_ACTION}" "${ACTION_RESULT}"
done
```

**Comment by SashaRyder** [comment]
I also use sonarr and radarr, my solution was to use NodeJS and spin the code up in another container on the same network, gist is here: https://gist.github.com/SashaRyder/9e22c43b60e710e3494b451c96217fbe

Mine just stops them when they reach a seed ratio of 1, and I go in every now and again and clear away the ones that are paused, but editing the code for time isnt that difficult of a change.

**Comment by alaorath** [comment]
I notice the container is using crontabs.... (but I'm not a Docker expert...) Wouldn't it be possible to create a volume to mount the /etc/periodic/ path ?

-v /path/to/Data/:/etc/periodic:ro

Add the 5 folders (15min, hourly, daily, weekly, monthly) under that volume mount. Then you can add whatever scripts outside the container and have them happily execute on the schedule.

I don't think this is a container issue to solve, but should be pushed back to the owners of Transmission.

**Comment by ksurl** [comment]
you can add a cron job on the host to run the command except you need to set the command as `docker exec CONTAINER_NAME transmission-remote`

easy way to set it is to save it as variable and then call the variable when you need to do various tasks like list then grep and remove the completed downloads.

**Comment by thundergreen** [comment]
> I also use sonarr and radarr, my solution was to use NodeJS and spin the code up in another container on the same network, gist is here: https://gist.github.com/SashaRyder/9e22c43b60e710e3494b451c96217fbe
> 
> Mine just stops them when they reach a seed ratio of 1, and I go in every now and again and clear away the ones that are paused, but editing the code for time isnt that difficult of a change.

Could you maybe share how to setup this correctly?

**Comment by SashaRyder** [comment]
> > I also use sonarr and radarr, my solution was to use NodeJS and spin the code up in another container on the same network, gist is here: https://gist.github.com/SashaRyder/9e22c43b60e710e3494b451c96217fbe
> > Mine just stops them when they reach a seed ratio of 1, and I go in every now and again and clear away the ones that are paused, but editing the code for time isnt that difficult of a change.
> 
> Could you maybe share how to setup this correctly?

Sure, I converted the code to c#, but check out this repo if you want to know how it all works:

https://github.com/SashaRyder/csharp-transmission-watcher

**Comment by thundergreen** [comment]
So i just need the docker-compose to run? my goal is to stop torrents and not to pause as i want that radarr etc will delete the downloaded files then. Is this somehow possible?

**Comment by SashaRyder** [comment]
This stops them, radarr and sonarr have never deleted my torrents
