### ISSUE TITLE
Run other services behind VPN

### ISSUE THREAD

**Issue by steff2632** [haugene/docker-transmission-openvpn#1426]
This isn't a bug or even something this project is aimed at but any help would be appreciated.

Would it be possible to create new containers that use this ones VPN connection to connect to the internet while also using this ones proxy to be accessible on the host?

I'm using Synology & I want to run sickgear & coachpotato behind a VPN & still need them able to connect to transmission currently I have all 3 services running directly (Download Station rather than Transmission) but want to switch to using docker to contain them. Have spent all day trying to get it to work but can't make transmission (standard transmission container, not this container - this container works fine) accessible on my laptop.

Any advice on getting sickgear/coachpotato/any container to work behind this one's VPN or the knowledge on getting containers that are behind VPNs reverse proxied to the local network would be appreciated.

Thanks in advance

**Comment by haugene** [comment]
Hey. Have a look at #991 and some of the related issues and see if that helps you forward. The simple answer is that --network=container:<vpn-container-id> is a built in function in Docker. See https://docs.docker.com/engine/reference/run/#network-settings

Then about the reverse proxy. Our current proxy image only supports one port for now. If you were using Traefik or something similar then that could solve this for you in the mean time. See a guide like this for example https://blog.linuxserver.io/2018/02/03/using-traefik-as-a-reverse-proxy-with-docker/

Just remember that when you attach a new container to the vpn container, it's ports are exposed there. So you would have to open all the other apps ports on the VPN container. Good luck :+1:

**Comment by jsloan117** [comment]
I do this I run a forked version of this where I had removed tinyproxy/transmission bits and mainly kept the OVPN files and OpenVPN pieces and attach 2 other containers (transmission & sabnzbd) to the VPN container as their network. As long as I've set the LOCAL_NET var correctly it works flawlessly.

As @haugene  said if you want more advanced proxying capabilities Traefik deff seems like the way to go. Its very powerful and I still need to re-learn how to use it.

**Comment by steff2632** [comment]
just wanted to come back and stay I gave up with this. Went back to running it on the metal. Think Docker on Synology is limited in certain ways. Only wanted to do it so I could run a pi-hole docker container, oh well ads aren't that bad!

**Comment by haugene** [comment]
I see. Haven't used one of those NAS Docker GUIs but I guess you could also ssh into the NAS and use a Docker command directly. Anyways - thanks for the update.
