### ISSUE TITLE
Can't access web interface with latest version

### ISSUE THREAD

**Issue by mhbates** [haugene/docker-transmission-openvpn#1430]
**Describe the problem**
Since the latest update, the web interface no longer loads. It seems to just time out.

I've tried the following:

- Using my usual custom web UI (TRANSMISSION_WEB_HOME variable), and also with TRANSMISSION_WEB_UI set instead of HOME. I did not set both together.
- Dev branch
- With and without CREATE_TUN_DEVICE=true, which is apparently no longer needed as it's set to true by default now?
- Deleted settings.json and let it regenerate
- When I exec into the container and enter "curl -I localhost:9091", it returns 301, location /transmission/web
- Unable to curl it from LAN. Makes me think it's some docker networking issue.

May be related or not, but I also had to switch the container DNS after the update due to name resolution issues; I think this was just an issue with Mullvad's DNS server, as it seems to launch correctly using 1.1.1.1.

**Add your docker run command**
docker run -d --cap-add=NET_ADMIN \
	--cpus=1.0 \
	-v /xxx:/data \
	-v /etc/localtime:/etc/localtime:ro \
	-e OPENVPN_PROVIDER=MULLVAD \
	-e OPENVPN_CONFIG=mullvad_us-ca_udp \
	-e OPENVPN_USERNAME=x \
	-e OPENVPN_PASSWORD=x \
	-e ENABLE_UFW=true \
	-e WEBPROXY_ENABLED=false \
	-e LOCAL_NETWORK=192.168.1.0/24 \
	-e TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=true \
	-e TRANSMISSION_SPEED_LIMIT_UP=1000 \
	-e TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true \
	-e TRANSMISSION_SPEED_LIMIT_DOWN=45000 \
	-e TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true \
	-e TRANSMISSION_RATIO_LIMIT_ENABLED=true \
	-e TRANSMISSION_ALT_SPEED_DOWN=45000 \
	-e TRANSMISSION_ALT_SPEED_UP=100 \
	-e TRANSMISSION_ALT_SPEED_TIME_BEGIN=1020 \
	-e TRANSMISSION_ALT_SPEED_TIME_END=1320 \
	-e TRANSMISSION_ALT_SPEED_TIME_ENABLED=false \
	-e TRANSMISSION_DOWNLOAD_QUEUE_SIZE=200 \
    -e TRANSMISSION_PEER_PORT=63504 \
    -e TRANSMISSION_WEB_UI=transmission-web-control \
	-e PUID=1000 -e PGID=1000 \
	-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings" \
	--log-driver json-file \
	--log-opt max-size=10m \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --dns 1.1.1.1 \
	--restart=always \
	--name transmission-openvpn \
	-p 9091:9091 \
	haugene/transmission-openvpn

**Logs**

**Docker:**
Using OpenVPN provider: MULLVAD
Starting OpenVPN using config mullvad_us-ca_udp.ovpn
Setting OpenVPN credentials...
enabling firewall
Firewall is active and enabled on system startup
allowing 63504 through the firewall
Rule added
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Thu Oct 29 09:12:21 2020 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
Thu Oct 29 09:12:21 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Thu Oct 29 09:12:21 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Thu Oct 29 09:12:21 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Oct 29 09:12:21 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]89.46.114.28:1197
Thu Oct 29 09:12:21 2020 Socket Buffers: R=[212992->425984] S=[212992->425984]
Thu Oct 29 09:12:21 2020 UDP link local: (not bound)
Thu Oct 29 09:12:21 2020 UDP link remote: [AF_INET]89.46.114.28:1197
Thu Oct 29 09:12:21 2020 TLS: Initial packet from [AF_INET]89.46.114.28:1197, sid=9924335f 7e8f77e2
Thu Oct 29 09:12:21 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Oct 29 09:12:21 2020 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net
Thu Oct 29 09:12:21 2020 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v3, emailAddress=security@mullvad.net
Thu Oct 29 09:12:21 2020 VERIFY KU OK
Thu Oct 29 09:12:21 2020 Validating certificate extended key usage
Thu Oct 29 09:12:21 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Oct 29 09:12:21 2020 VERIFY EKU OK
Thu Oct 29 09:12:21 2020 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=us-lax-002.mullvad.net, emailAddress=security@mullvad.net
Thu Oct 29 09:12:21 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558'
Thu Oct 29 09:12:21 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
Thu Oct 29 09:12:21 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA
Thu Oct 29 09:12:21 2020 [us-lax-002.mullvad.net] Peer Connection Initiated with [AF_INET]89.46.114.28:1197
Thu Oct 29 09:12:22 2020 SENT CONTROL [us-lax-002.mullvad.net]: 'PUSH_REQUEST' (status=1)
Thu Oct 29 09:12:27 2020 SENT CONTROL [us-lax-002.mullvad.net]: 'PUSH_REQUEST' (status=1)
Thu Oct 29 09:12:27 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.11.0.1,redirect-gateway def1 bypass-dhcp,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,comp-lzo no,route-gateway 10.11.0.1,topology subnet,socket-flags TCP_NODELAY,ifconfig-ipv6 fdda:d0d0:cafe:1197::1008/64 fdda:d0d0:cafe:1197::,ifconfig 10.11.0.10 255.255.0.0,peer-id 9,cipher AES-256-GCM'
Thu Oct 29 09:12:27 2020 OPTIONS IMPORT: compression parms modified
Thu Oct 29 09:12:27 2020 OPTIONS IMPORT: --socket-flags option modified
Thu Oct 29 09:12:27 2020 NOTE: setsockopt TCP_NODELAY=1 failed
Thu Oct 29 09:12:27 2020 OPTIONS IMPORT: --ifconfig/up options modified
Thu Oct 29 09:12:27 2020 OPTIONS IMPORT: route options modified
Thu Oct 29 09:12:27 2020 OPTIONS IMPORT: route-related options modified
Thu Oct 29 09:12:27 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Thu Oct 29 09:12:27 2020 OPTIONS IMPORT: peer-id set
Thu Oct 29 09:12:27 2020 OPTIONS IMPORT: adjusting link_mtu to 1624
Thu Oct 29 09:12:27 2020 OPTIONS IMPORT: data channel crypto options modified
Thu Oct 29 09:12:27 2020 Data Channel: using negotiated cipher 'AES-256-GCM'
Thu Oct 29 09:12:27 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Thu Oct 29 09:12:27 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Thu Oct 29 09:12:27 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:11
Thu Oct 29 09:12:27 2020 GDG6: remote_host_ipv6=n/a
Thu Oct 29 09:12:27 2020 ROUTE6: default_gateway=UNDEF
Thu Oct 29 09:12:27 2020 TUN/TAP device tun0 opened
Thu Oct 29 09:12:27 2020 TUN/TAP TX queue length set to 100
Thu Oct 29 09:12:27 2020 /sbin/ip link set dev tun0 up mtu 1500
Thu Oct 29 09:12:27 2020 /sbin/ip addr add dev tun0 10.11.0.10/16 broadcast 10.11.255.255
Thu Oct 29 09:12:27 2020 /sbin/ip -6 addr add fdda:d0d0:cafe:1197::1008/64 dev tun0
Thu Oct 29 09:12:27 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1552 10.11.0.10 255.255.0.0 init
Up script executed with tun0 1500 1552 10.11.0.10 255.255.0.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.11.0.10
Using Transmission Web Control  UI, overriding TRANSMISSION_WEB_HOME
Updating Transmission settings.json with values from env variables
Generating settings.json for Transmission from environment and defaults /etc/transmission/default-settings.json
Overriding alt-speed-down because TRANSMISSION_ALT_SPEED_DOWN is set to 45000
Overriding alt-speed-time-begin because TRANSMISSION_ALT_SPEED_TIME_BEGIN is set to 1020
Overriding alt-speed-time-enabled because TRANSMISSION_ALT_SPEED_TIME_ENABLED is set to False
Overriding alt-speed-time-end because TRANSMISSION_ALT_SPEED_TIME_END is set to 1320
Overriding alt-speed-up because TRANSMISSION_ALT_SPEED_UP is set to 100
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.11.0.10
Overriding download-queue-size because TRANSMISSION_DOWNLOAD_QUEUE_SIZE is set to 200
Overriding peer-port because TRANSMISSION_PEER_PORT is set to 63504
Overriding ratio-limit-enabled because TRANSMISSION_RATIO_LIMIT_ENABLED is set to True
Overriding scrape-paused-torrents-enabled because TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED is set to True
Overriding speed-limit-down because TRANSMISSION_SPEED_LIMIT_DOWN is set to 45000
Overriding speed-limit-down-enabled because TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED is set to True
Overriding speed-limit-up because TRANSMISSION_SPEED_LIMIT_UP is set to 1000
Overriding speed-limit-up-enabled because TRANSMISSION_SPEED_LIMIT_UP_ENABLED is set to True
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1000:1000
BusyBox v1.31.1 () multi-call binary.

Usage: chown [-RhLHPcvf]... USER[:[GRP]] FILE...

Change the owner and/or group of each FILE to USER and/or GRP

	-R	Recurse
	-h	Affect symlinks instead of symlink targets
Setting permission for files (644) and directories (755)
	-L	Traverse all symlinks to directories
	-H	Traverse symlinks on command line only
	-P	Don't traverse symlinks (default)
	-c	List changed files
	-v	List all files
	-f	Hide errors
BusyBox v1.31.1 () multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

Each MODE is one or more of the letters ugoa, one of the
symbols +-= and one or more of the letters rwxst

	-R	Recurse
	-c	List changed files
	-v	List all files
	-f	Hide errors
Setting permission for watch directory (775) and its files (664)
BusyBox v1.31.1 () multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

Each MODE is one or more of the letters ugoa, one of the
symbols +-= and one or more of the letters rwxst

	-R	Recurse
	-c	List changed files
	-v	List all files
	-f	Hide errors

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------

STARTING TRANSMISSION
Transmission startup script complete.
Thu Oct 29 09:12:28 2020 /sbin/ip route add 89.46.114.28/32 via 172.17.0.1
Thu Oct 29 09:12:28 2020 /sbin/ip route add 0.0.0.0/1 via 10.11.0.1
Thu Oct 29 09:12:28 2020 /sbin/ip route add 128.0.0.0/1 via 10.11.0.1
Thu Oct 29 09:12:28 2020 add_route_ipv6(::/2 -> fdda:d0d0:cafe:1197:: metric -1) dev tun0
Thu Oct 29 09:12:28 2020 /sbin/ip -6 route add ::/2 dev tun0
Thu Oct 29 09:12:28 2020 add_route_ipv6(4000::/2 -> fdda:d0d0:cafe:1197:: metric -1) dev tun0
Thu Oct 29 09:12:28 2020 /sbin/ip -6 route add 4000::/2 dev tun0
Thu Oct 29 09:12:28 2020 add_route_ipv6(8000::/2 -> fdda:d0d0:cafe:1197:: metric -1) dev tun0
Thu Oct 29 09:12:28 2020 /sbin/ip -6 route add 8000::/2 dev tun0
Thu Oct 29 09:12:28 2020 add_route_ipv6(c000::/2 -> fdda:d0d0:cafe:1197:: metric -1) dev tun0
Thu Oct 29 09:12:28 2020 /sbin/ip -6 route add c000::/2 dev tun0
Thu Oct 29 09:12:28 2020 Initialization Sequence Completed

**Running "ip r" in the container:**
0.0.0.0/1 via 10.11.0.1 dev tun0 
default via 172.17.0.1 dev eth0 
10.11.0.0/16 dev tun0 proto kernel scope link src 10.11.0.10 
89.46.114.28 via 172.17.0.1 dev eth0 
128.0.0.0/1 via 10.11.0.1 dev tun0 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.17 
192.168.1.0/24 via 172.17.0.1 dev eth0 

**settings.json:**
{
    "alt-speed-down": 45000,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 1020,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1320,
    "alt-speed-up": 100,
    "bind-address-ipv4": "10.11.0.10",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/data/completed",
    "download-limit": 100,
    "download-limit-enabled": 0,
    "download-queue-enabled": true,
    "download-queue-size": 200,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/data/incomplete",
    "incomplete-dir-enabled": true,
    "lpd-enabled": false,
    "max-peers-global": 240,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 63504,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": false,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": true,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "{df8f19c0c0a98c5bb57ee58410973f71e39695a7igpx2.7T",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "username",
    "rpc-whitelist": "127.0.0.1,::1",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 45000,
    "speed-limit-down-enabled": true,
    "speed-limit-up": 1000,
    "speed-limit-up-enabled": true,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 2,
    "upload-slots-per-torrent": 14,
    "utp-enabled": false,
    "watch-dir": "/data/watch",
    "watch-dir-enabled": true,
    "watch-dir-force-generic": false
}

**Host system:**
Debian 10. Docker 19.03.13

**Comment by mhbates** [comment]
I went back to 2.14 and it's working again. Some key differences I noticed in the docker logs below, hope this helps.

- Version 3.0 is missing the following:
--allowing 172.17.0.1 through the firewall to port 9091
Rule added
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
allowing 192.168.1.0/24 through the firewall to port 9091
Rule added
- Version 3.0 has more noise re: permissions (BusyBox) compared to 2.14

**Comment by mhbates** [comment]
Okay, just confirmed it's a container firewall issue. For some reason, the LOCAL_NETWORK env variable isn't triggering the firewall actions I mentioned above. Exec'ing into the container and manually adding them gets it working.

**Comment by mhbates** [comment]
I'm wondering if the problem is in the line 190 block in OpenVPN's start.sh. https://github.com/haugene/docker-transmission-openvpn/blob/c51c5431fa268d2c7607fd69a4d339b8085aca45/openvpn/start.sh#L190-L205


I see the echo in the docker log, but not the command return. Is the if statement failing, or the ufwAllowPortLong function not working possibly?

**Comment by andsoitgoes** [comment]
What’s the command to set thr variable? I’m barely capable of this sort of stuff and I can probably do it if someone holds my hand. 

Thanks in advance. Glad I’m not insane.

**Comment by s4b3rt0oth** [comment]
> Okay, just confirmed it's a container firewall issue. For some reason, the LOCAL_NETWORK env variable isn't triggering the firewall actions I mentioned above. Exec'ing into the container and manually adding them gets it working.

I, too, got the new version to work with:

`ufw allow from X.X.X.X/24 from any port 9091`

Started working again. Definitely an issue with setup/startup running the ufw commands.

@andsoitgoes You should be able to tack on:

`-e TRANSMISSION_RPC_PORT=9091`

Substitute with your port number if it's different. I can't verify this would work but that's what I'd imagine sets it from the start.

Alternatively, I got mine to work by SSH'ing into my host and running:

`docker exec -it transmission /bin/bash`

Then:

`ufw allow from X.X.X.X/24 to any port 9091`

Substitute X.X.X.X for your internal subnet and 9091 for your port, if different.

You can verify the UFW rule is in place with:

`ufw status`

**Comment by Anon0ne** [comment]
Even with the UFW disabled, i cannot access WebGUI.
I tried to enable it, and add some rules to allow it; still no WebGUI now. It worked yesterday, now it doesn't.

**Comment by haugene** [comment]
@mhbates @andsoitgoes @s4b3rt0oth A fix for this has been merged now in #1439. Please try again after pulling the latest version. (both :latest and :dev versions are now the same). This was indeed a bug in the lines @mhbates were pointing to, because TRANSMISSION_RPC_PORT was no longer set. The PR adds a default value (which there should be no need to change).

@Anon0ne What you're dealing with seems different. If you can't even access WebUI without UFW enabled then it's not the same bug. Can you try running the 2.14 tag and see if it works then? Also provide your docker run command or compose file, in addition to logs like @mhbates has done when opening this issue.

PS: I see there are other errors on your startup @mhbates and I'll have a look at them later. They don't seem to break the startup, and it probably works because persmissions has been set multiple times before. But for new user they could pose a problem. In genereal there is more noise in the logs now than it's been before. Getting to it :nerd_face:

**Comment by mhbates** [comment]
Latest version is working, thank you for the quick fix!

**Comment by StormPooper** [comment]
Updated to 3.0.1 (latest) and I still get the same 401 error. UFW is not enabled on my version.

**Comment by haugene** [comment]
401? That's `Unauthorized`. Are you running with Transmission auth? Try without it and see? Special characters in username or password can be an issue.

**Comment by StormPooper** [comment]
@haugene without worked, so I modified my password and that also worked - for some reason 2.14 was fine with spaces in the password, 3.0.1 wasn't.

**Comment by haugene** [comment]
Aha, might have been some quotations present in the previous settings template that are not handled the same way with the new script. I assume there will be some hardening to these scripts going forward, but at least for now it works :+1:
