### ISSUE TITLE
No Web UI access if UFW is enabled without TRANSMISSION_RPC_PORT

### ISSUE THREAD

**Issue by dcardin** [haugene/docker-transmission-openvpn#1431]
I have been using the UFW_ENABLE=true option in the 2.x series, but I couldn't connect to the web interface in 3.x
Checking the ufw firewall rules, I noticed the 9091 port wasn't open anymore. 
Looking at the script I realized it was relying on the env var TRANSMISSION_RPC_PORT

When I added it to my dockerfile, the firewall was configured properly and access was restored.
I guess the var should default to the binding port for the app...

**Comment by haugene** [comment]
Thanks for pinpointing the issue to UFW @dcardin, the PR from @DevonKupiec is now merged and that should fix it :+1:
