### ISSUE TITLE
:dev-armhf tag and CREATE_TUN_DEVICE=true by default

### ISSUE THREAD

**Issue by mouzzampk2014** [haugene/docker-transmission-openvpn#1432]
Hi, 

I am currently using :dev-armhf 

I have these two variables, I already received enough information in my previous post. 

`CREATE_TUN_DEVICE=true` 
```
    devices:
      - /dev/net/tun
```

Shall I remove both of them now from my compose as this is already set by default `CREATE_TUN_DEVICE=true`  in `:dev` tag and not require anymore and this one `/dev/net/tun` also doesn't need anymore if `CREATE_TUN_DEVICE=true`?

Thank you

Here is my compose

  transmissionvpn:
    image: haugene/transmission-openvpn:dev-armhf
    hostname: Tail
    ports:
      - 51413:51413
      - 51413:51413/udp
      - 6881:6881
      - 6881:6881/udp
      - 9091:9091
    cap_add:
      - NET_ADMIN
    container_name: transmissionvpn
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - CREATE_TUN_DEVICE=true
      - LOCAL_NETWORK=192.168.1.0/24
      - OPENVPN_OPTS=
      - OPENVPN_PASSWORD=${VPN_PASS}
      - OPENVPN_PROVIDER=TORGUARD
      - OPENVPN_USERNAME=${VPN_USER}
      - PGID=1000
      - PUID=1000
      - TRANSMISSION_DOWNLOAD_DIR=/storage/downloads
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_INCOMPLETE_DIR=/storage/downloads
      - TRANSMISSION_WATCH_DIR=/storage/downloads
      - TZ=Europe/London
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/.config/appdata/transmissionvpn:/config
      - /mnt:/storage
      - /home/pi/.config/appdata/.openvpn:/config/openvpn
      - /home/pi/.config/appdata/.openvpn:/etc/openvpn/custom/

**Comment by haugene** [comment]
Hi @mouzzampk2014. Yes, you should remove them both :+1:

**Comment by mouzzampk2014** [comment]
All sorted. Thank you so much
