### ISSUE TITLE
<inside the container> ssh: command not found

### ISSUE THREAD

**Issue by alneven** [haugene/docker-transmission-openvpn#1436]
hello there,

I have portainer to login per web management and check out my containers. Sometimes I'm using it to access the console from the docker container to SSH back to the main machine (per portainer web). Which worked very well the past 2 years.
As I'm not using this daily, maybe 2-3 times per month I don't know if it's now a "security feature" or a new update, or something on the main machine (but it wasn't rebooted the past 78 days).

Just asking...

As now I have this problem:
![image](https://user-images.githubusercontent.com/16620485/97682818-87c33300-1a98-11eb-83d5-32cb9f34c7f0.png)

It looks like bash is not working anymore correctly and SSH as "app" is not available anymore.
Do you have any idea?

As far as I can see the docker container was started yesterday (2020-10-29 05:00:41).
Thanks!

![image](https://user-images.githubusercontent.com/16620485/97685349-4ed78e00-1a99-11eb-8db4-f9cb35aa004f.png)

In Logs I cannot see anything regarding of the missing ssh command.

**Comment by haugene** [comment]
Hey @alneven. You're right that the ssh command is now gone. We released version 3.0 yesterday and it is based off Alpine and not Ubuntu and is more minimal when it comes to pre-installed commands.
I do however not see any reason why we shouldn't have ssh installed in the container. We try to have a basic set of tools that can be handy in common scripting use cases and ssh is one of them IMO. I'll add it...

**Comment by haugene** [comment]
Pushed to both dev and master branch. If you pull again it should work :crossed_fingers:

**Comment by alneven** [comment]
@haugene you are great! thanks for the quick fix. I will check it later.
