### ISSUE TITLE
Is there an explanation of the difference between transmission-openvpn and transmission-openvpn-proxy?

### ISSUE THREAD

**Issue by ovizii** [haugene/docker-transmission-openvpn#1438]
The description on both https://hub.docker.com/r/haugene/transmission-openvpn and here https://hub.docker.com/r/haugene/transmission-openvpn-proxy are identical except for this sentence:

`Proxy for the transmission-openvpn container. See that for README and instructions on how to use. `

**Comment by haugene** [comment]
Well. The use of the proxy is explained here: https://haugene.github.io/docker-transmission-openvpn/access/

`haugene/transmission-openvpn` is the main image. That is the container that has openvpn and Transmission.
`haugene/transmission-openvpn-proxy` is just an Nginx reverse proxy with built in configuration to do reverse proxying in front of the VPN container.

You're right that this could be more thoroughly explained in the documentation. The whole networking part and LOCAL_NETWORK vs proxy should probably get it's own section.

I have a explained a bit about the proxy and why it is needed multiple times. Here are a couple that are more thorough:
https://github.com/haugene/docker-transmission-openvpn/issues/354#issuecomment-376326285
https://github.com/haugene/docker-transmission-openvpn/issues/687#issuecomment-457820130

If you read those and related issues I hope you get the problem that the proxy is trying to solve. Is simply a combination of the Dockerfile and nginx.conf here: https://github.com/haugene/docker-transmission-openvpn/tree/master/proxy

**Comment by haugene** [comment]
I could probably save myself a lot of time by rewriting the docs "once and for all". But it is not a tempting task :thinking:

**Comment by ovizii** [comment]
thanks @haugene I am busy reading the links you provided. I didn't even know you had 2 images until my instance broke when automatically upgrading to v3 - I have gone back to your latest v2 version and plan on staying here until I have more time to figure out what broke. I guess I will open a completely new thread so I am closing this one.
