### ISSUE TITLE
Restart container if connection is lost

### ISSUE THREAD

**Issue by PeteB1983** [haugene/docker-transmission-openvpn#144]
Hi,

I am trying to get this running on my qnap ts-853A using container station... I think i have it all set but Im not sure where to input --restart=always to finish the auto restart setup..

I am setting this up within the gui.....
also I'm not sure if it is a vpn failure or a transmission one, I just loose all up and down connection... what I would expect from the killswitch...

**Comment by PeteB1983** [comment]
I am very new at all this ant trying to stick to GUI so I don't Brick my shiny new NAS

**Comment by haugene** [comment]
This is a default docker flag, it should be a dropdown where you can choose this in the UI. Probably in some sort of "advanced" tab.

You lose up/down speed in Transmission? Or the Transmission UI itself disappears? If the openvpn connection dies it should kill transmission and the container should stop.

If you post your logs it's easier to see what's happening...

**Comment by PeteB1983** [comment]
hi thanks for the response... 
so i have tried to reinstall and cant see anything like that, I have added it as one of the environment variables, btu now cant access the web ui so i think i put a square peg in a round hole... 

transmission looses all upload and wdownload but the UI still operates normally...

can you let me know where i can find the log you are looking for?

**Comment by haugene** [comment]
Haha, square peg :) I don't have a qnap myself, so I'm not sure where you could look for that option.

Anyways, as long as you can still access the web ui it means that the container hasn't exited and is still running. So I'm guessing what's happening is that the container loses Internet connection somehow and then just stays idle.

A couple of things you should try is listed under "known issues, tips and tricks" in the Readme. Number one is setting the dns servers to use. This might fix the connection drop.
The second is to specify the OPENVPN_OPTS environment variable as the example shows. This will cause the container to fail and exit when the connection drops, and then you'll see if it comes back up again. If not, you're back at figuring out the --restart flag as that's where it becomes useful. 

As for the logs, they're always helpful to figure out what's wrong. There should be a way to see the console log somehow. But both this and the restart flag are qnap issues, best asked on their forums. 

Check if you get anywhere with the tricks above. And if not I hope this helpes you with a couple of peg shapes and that you'll get a step closer.

**Comment by PeteB1983** [comment]
hi - sorry been away for a few days, so yes the UI is still running I think i have set the dns to google but i will  double check and I also thought I had set the openvpn_opts...

**Comment by PeteB1983** [comment]
I have gained  more info on this... at the point the connection dies the console in the GUI asks for
Enter Auth Username:
then once a username has been entered...                                                                                   
Enter Auth Password:

any ideas on this? Is it a VPN issue?

**Comment by haugene** [comment]
Which provider and config are you using? And you're running the latest tag, right?

**Comment by PeteB1983** [comment]
yep im on latest and Im using Ivacy without any special config so its using the default setup i think?

these are the variables i am using
LOCAL_NETWORK	192.168.0.0/24	
OPENVPN_PASSWORD	*****
OPENVPN_PROVIDER	ivacy	
OPENVPN_USERNAME	*****
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin	
TRANSMISSION_ALT_SPEED_DOWN	50	
TRANSMISSION_ALT_SPEED_ENABLED	false	
TRANSMISSION_ALT_SPEED_TIME_BEGIN	540	
TRANSMISSION_ALT_SPEED_TIME_DAY	127	
TRANSMISSION_ALT_SPEED_TIME_ENABLED	false	
TRANSMISSION_ALT_SPEED_TIME_END	1020	
TRANSMISSION_ALT_SPEED_UP	50	
TRANSMISSION_BIND_ADDRESS_IPV4	0.0.0.0	
TRANSMISSION_BIND_ADDRESS_IPV6	::	
TRANSMISSION_BLOCKLIST_ENABLED	false	
TRANSMISSION_BLOCKLIST_URL	http://www.example.com/blocklist	
TRANSMISSION_CACHE_SIZE_MB	8	
TRANSMISSION_DHT_ENABLED	true	
TRANSMISSION_DOWNLOAD_DIR	/data/completed	
TRANSMISSION_DOWNLOAD_LIMIT	100	
TRANSMISSION_DOWNLOAD_LIMIT_ENABLED	0	
TRANSMISSION_DOWNLOAD_QUEUE_ENABLED	true	
TRANSMISSION_DOWNLOAD_QUEUE_SIZE	50	
TRANSMISSION_ENCRYPTION	1	
TRANSMISSION_HOME	/data/transmission-home	
TRANSMISSION_IDLE_SEEDING_LIMIT	30	
TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED	false	
TRANSMISSION_INCOMPLETE_DIR	/data/incomplete	
TRANSMISSION_INCOMPLETE_DIR_ENABLED	true	
TRANSMISSION_LPD_ENABLED	false	
TRANSMISSION_MAX_PEERS_GLOBAL	2000	
TRANSMISSION_MESSAGE_LEVEL	2	
TRANSMISSION_PEER_CONGESTION_ALGORITHM		
TRANSMISSION_PEER_ID_TTL_HOURS	6	
TRANSMISSION_PEER_LIMIT_GLOBAL	2000	
TRANSMISSION_PEER_LIMIT_PER_TORRENT	100	
TRANSMISSION_PEER_PORT	51413	
TRANSMISSION_PEER_PORT_RANDOM_HIGH	65535	
TRANSMISSION_PEER_PORT_RANDOM_LOW	49152	
TRANSMISSION_PEER_PORT_RANDOM_ON_START	false	
TRANSMISSION_PEER_SOCKET_TOS	default	
TRANSMISSION_PEX_ENABLED	true	
TRANSMISSION_PORT_FORWARDING_ENABLED	false	
TRANSMISSION_PREALLOCATION	1	
TRANSMISSION_PREFETCH_ENABLED	1	
TRANSMISSION_QUEUE_STALLED_ENABLED	true	
TRANSMISSION_QUEUE_STALLED_MINUTES	1	
TRANSMISSION_RATIO_LIMIT	1	
TRANSMISSION_RATIO_LIMIT_ENABLED	false	
TRANSMISSION_RENAME_PARTIAL_FILES	true	
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED	false	
TRANSMISSION_RPC_BIND_ADDRESS	0.0.0.0	
TRANSMISSION_RPC_ENABLED	true	
TRANSMISSION_RPC_PASSWORD ******
TRANSMISSION_RPC_PORT	9091	
TRANSMISSION_RPC_URL	/transmission/	
TRANSMISSION_RPC_USERNAME	*******
TRANSMISSION_RPC_WHITELIST	127.0.0.1	
TRANSMISSION_RPC_WHITELIST_ENABLED	false	
TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED	true	
TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED	false	
TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME		
TRANSMISSION_SEED_QUEUE_ENABLED	false	
TRANSMISSION_SEED_QUEUE_SIZE	10	
TRANSMISSION_SPEED_LIMIT_DOWN	100	
TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED	false	
TRANSMISSION_SPEED_LIMIT_UP	100	
TRANSMISSION_SPEED_LIMIT_UP_ENABLED	false	
TRANSMISSION_START_ADDED_TORRENTS	true	
TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES	false	
TRANSMISSION_UMASK	2	
TRANSMISSION_UPLOAD_LIMIT	100	
TRANSMISSION_UPLOAD_LIMIT_ENABLED	0	
TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT	14	
TRANSMISSION_UTP_ENABLED	true	
TRANSMISSION_WATCH_DIR	/data/watch	
TRANSMISSION_WATCH_DIR_ENABLED	true

**Comment by PeteB1983** [comment]
mostly it was preconfigured

here is the console output... when it fails the user & password request comes at the end of this

Using OpenVPN provider: ivacy                                                                                                                                                                                                                                                              
No VPN configuration provided. Using default.                                                                                                                                                                                                                                              
Setting OPENVPN credentials...                                                                                                                                                                                                                                                             
adding route to local network 192.168.0.0/24 via 10.0.3.1 dev eth0                                                                                                                                                                                                                         
Fri Oct 14 06:56:11 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014                                                                                                                                              
Fri Oct 14 06:56:11 2016 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.                                                                                                                                       
Fri Oct 14 06:56:11 2016 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts                                                                                                                                                             
Fri Oct 14 06:56:11 2016 WARNING: file '/etc/openvpn/ivacy/Wdc.key' is group or others accessible                                                                                                                                                                                          
Fri Oct 14 06:56:11 2016 Control Channel Authentication: using '/etc/openvpn/ivacy/Wdc.key' as a OpenVPN static key file                                                                                                                                                                   
Fri Oct 14 06:56:11 2016 UDPv4 link local: [undef]                                                                                                                                                                                                                                         
Fri Oct 14 06:56:11 2016 UDPv4 link remote: [AF_INET]*.5.68.22:53                                                                                                                                                                                                                        
Fri Oct 14 06:56:13 2016 [Secure-Server] Peer Connection Initiated with [AF_INET]*.5.68.22:53                                                                                                                                                                                            
Fri Oct 14 06:56:15 2016 TUN/TAP device tun0 opened                                                                                                                                                                                                                                        
Fri Oct 14 06:56:15 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0                                                                                                                                                                                                            
Fri Oct 14 06:56:15 2016 /sbin/ip link set dev tun0 up mtu 1500                                                                                                                                                                                                                            
Fri Oct 14 06:56:15 2016 /sbin/ip addr add dev tun0 *.5.68.205/27 broadcast *.5.68.223                                                                                                                                                                                                 
Fri Oct 14 06:56:15 2016 /etc/transmission/start.sh tun0 1500 1558 *.5.68.205 255.255.255.224 init                                                                                                                                                                                       
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : *.5.68.205                                                                                                                                                                                                                   
Generating transmission settings.json from env variables                                                                                                                                                                                                                                   
STARTING TRANSMISSION                                                                                                                                                                                                                                                                      
NO PORT UPDATER FOR THIS PROVIDER                                                                                                                                                                                                                                                          
Transmission startup script complete.                                                                                                                                                                                                                                                      
Fri Oct 14 06:56:17 2016 Initialization Sequence Completed                                                                                                                                                                                                                                 
Fri Oct 14 06:56:41 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #6642 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                     
Fri Oct 14 06:56:41 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #6643 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                     
Fri Oct 14 06:56:41 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #6644 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                     
Fri Oct 14 06:56:41 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #6645 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                     
Fri Oct 14 06:56:41 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #6646 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                     
Fri Oct 14 06:56:52 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #24240 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26130 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26131 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26132 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26133 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26134 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26135 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26136 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26137 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26138 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26139 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26140 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26141 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26142 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #26143 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings                                                    
Fri Oct 14 06:56:53 2016 NOTE: --mute triggered...

**Comment by PeteB1983** [comment]
Anyone got any suggestions?

**Comment by turban0** [comment]
In QNAP Container station there is no way to set --restart=always flag. The better approach is to start container from console (via ssh or whatever), then it will be normally visibile in container station. If somehow you don't want to start new container you can edit restart policy on the fly by executing 
```docker update --restart=always <containerId>```
