### ISSUE TITLE
constant restart with PIA

### ISSUE THREAD

**Issue by mcmaxl** [haugene/docker-transmission-openvpn#1441]
**Describe the problem**
the container is constantly restarting, see log below. persists after pulling the image again and recreating

**Add your docker run command**
# TransmissionBT - Torrent Downloader
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ${USERDIR}/resolv.conf:/etc/resolv.conf
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/transmission-vpn:/data
      - ${USERDIR}/shared:/shared
      - ${USERDIR}/downloads:/downloads
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_CONFIG="yyyyyyyy"
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.3.0/16
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
      - TRANSMISSION_UMASK=2
      - TRANSMISSION_RATIO_LIMIT=0.01
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_ALT_SPEED_DOWN=2000
      - TRANSMISSION_ALT_SPEED_ENABLED=false
      - TRANSMISSION_ALT_SPEED_UP=15
      - TRANSMISSION_SPEED_LIMIT_DOWN=6000
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false
      - TRANSMISSION_SPEED_LIMIT_UP=1000
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/downloads
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/downloads/completed
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

**Logs**
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom startup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.Lgglcc
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Modify configs for this container
Supplied config "yyyyyyyy".ovpn could not be found.

**Host system:**
Running on Synology

Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.11
 Git commit:        bfed4f5
 Built:             Fri Mar 13 06:46:11 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11
  Git commit:       3a371f3
  Built:            Fri Mar 13 06:44:35 2020
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by mcmaxl** [comment]
specifying a server and changing localip/16 to localip/32 fixed it...

**Comment by haugene** [comment]
Great :+1: I would believe that it was mostly about the server name. As it logs that it can't find whatever you referred to before. We have changed to the nextgen server bundle from PIA so some of the old ones might no longer exist.

Changing to localip/32 will mean that only one of the hosts on your local lan will have access and not all within your network. If that one is set to be the router it might still work but I don't see why that should help.

I've seen in other issues that people are commenting that they are setting it, but it just sounds to limited to be practical IMO.
