### ISSUE TITLE
PIA: Supplied config could not be found.

### ISSUE THREAD

**Issue by zellkou** [haugene/docker-transmission-openvpn#1442]
**Describe the problem**
Unable to find supplied config for any PIA region using ovpn-nextgen on 3.0 and 3.0.1. I have not tested stong, ip, etc.

**Add your docker run command**
version: "3"
services:
  transmission-openvpn:
    container_name: transmission
    restart: unless-stopped
    volumes:
      - /transmission:/data
      - /etc/localtime:/etc/localtime:ro
      - /docker/transmissiont/config:/config
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=US\ Atlanta
      - OPENVPN_USERNAME=$USER
      - OPENVPN_PASSWORD=$PASS
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=9999
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_WEB_UI=combustion
      - DROP_DEFAULT_ROUTE=true
      - TRANSMISSION_MAX_PEERS_GLOBAL=2000
      - TRANSMISSION_SPEED_LIMIT_DOWN=10000
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=1000
      - PGID=1000
      - PUID=1000
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
      - 9999:9999
    image: haugene/transmission-openvpn:latest

**Logs**
transmission-test       | Using OpenVPN provider: PIA
transmission-test       | Provider PIA has a custom startup script, executing it
transmission-test       | Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.mOebGH
transmission-test       | Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
transmission-test       | Modify configs for this container
transmission-test       | Supplied config US\ Atlanta.ovpn could not be found.

**Host system:**
Docker version 19.03.13, build 4484c46d9d
Devuan linux kernel 5.4.0-2-amd64

**Comment by haugene** [comment]
Version 3.x has a new way of handling environment variables. Use `US Atlanta` instead of `US\ Atlanta`. Also FYI, Transmission settings are now persistent. So you don't need to specify them as environment variables unless you prefer to. They will stay after rebooting the container if you configure them from the web ui.

**Comment by zellkou** [comment]
Thank you. Keep up the awesome work.
