### ISSUE TITLE
Missing files, env variables, etc.

### ISSUE THREAD

**Issue by markfaine** [haugene/docker-transmission-openvpn#1444]
**Describe the problem**
I had to rebuild the container to get it working, there were a few things that were preventing it from starting.  See attached tarball with the modifications that were required.  I don't know why, but for whatever reason the container that I am pulling required these changes to get it to start.

[transmission-modified.tar.gz](https://github.com/haugene/docker-transmission-openvpn/files/5469966/transmission-modified.tar.gz)

**Comment by haugene** [comment]
Hey. Thanks for wanting to contribute here and report errors. Could you be a bit more specific as to which changes you have had to make, and what errors you were getting? I have not looked through your tarball, sorry about that. But I'm a bit skeptical to downloading and opening everything that is posted here, and I thing that issues should be detailed and not require me or other readers to find the errors for ourselves.

If you update this issue with concrete logs, docker run commands or something like that I'll happily take a look.

**Comment by markfaine** [comment]
Not worth it
