### ISSUE TITLE
Supplied config USA - Austin.ovpn could not be found.

### ISSUE THREAD

**Issue by hawaiianhacker** [haugene/docker-transmission-openvpn#1446]
I didn't change any of my config files, just updated to the latest image version and get this message. When I leave out the OPENVPN_CONFIG line it works, but it's connected to a European server instead of USA.

Supplied config USA - Austin.ovpn could not be found.

Using OpenVPN provider: GIGANEWS
Supplied config USA - Austin.ovpn could not be found.

**Comment by hawaiianhacker** [comment]
Here what's in my docker-compose.yml file
`  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
#    ports:
#      - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - OPENVPN_PROVIDER=GIGANEWS
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_CONFIG=USA - Austin
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
      - TRANSMISSION_UMASK=2
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
`

**Comment by whit-tj** [comment]
My error sounds very similar, instead of Austin.ovpn mine is Vancouver.ovpn. I'm using PIA however, but this error started 2 days ago after getting a latest image. I assumed it had to do with PIA's nextgen servers and the associated changes they've been making, but I'm not really sure, my error sounded a lot like yours.

```
Using OpenVPN provider: PIA
Provider PIA has a custom startup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.lcGcGF
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Modify configs for this container
Supplied config CA Vancouver.ovpn could not be found.
```

**Comment by taylorcox75** [comment]
FYI for @whit-tj next gen server's ovpn can be found in openvpn/pia/configure-openvpn

By default downloads the basic next gen

https://www.privateinternetaccess.com/openvpn/openvpn-nextgen.zip

**Comment by Kmanxx** [comment]
How can you apply this fix to the unraid version?

**Comment by hawaiianhacker** [comment]
I found the fix for me. If I look into /etc/openvpn/giganews they renamed the ovpn files. So in my case changing the OPENVPN_CONFIG to USA-Austin-256.ovpn worked

**Comment by glitchsys** [comment]
I'm having the same problem as @whit-tj  no changes were made on my end but the container got updated, and now "Supplied config CA Vancouver.ovpn could not be found"

It then goes on to list the ovpn files available and sure enough, there is no "CA Vancouver.ovpn" file, there are others like "CA Montreal.ovpn" and "CA Toronto.ovpn" it's like they just up and removed Vancouver.

I don't know what @hawaiianhacker  is looking at, in the list of ovpn files presented I do not see "USA-Austin-256.ovpn" listed in the list of available ovpn files.

**Comment by taylorcox75** [comment]
There are other "next generation" from https://github.com/pia-foss/manual-connections

That's the official PIA terminal connection way and this docker implements parts of the script (port forwarding, tokens, etc)

Vancouver is there

https://pastebin.com/hqeyeggu

Master list 

https://pastebin.com/m30eaTLS

Recommend running setup to get an .ovpn from 

https://github.com/pia-foss/manual-connections
Then manually using that

**Comment by haugene** [comment]
We're just downloading the configs from PIA on the link that @taylorcox75 provided. If there are any servers missing there then that's a question for PIA. I find it odd that they would have it available from some other script but I'll let them answer that.

I'm not sure they've got things 100% under control yet either. I've gotten AUTH_FAIL from one server and not another using the same credentials etc.
