### ISSUE TITLE
Documentation still requires TUN.sh?

### ISSUE THREAD

**Issue by braunsonm** [haugene/docker-transmission-openvpn#1449]
**Describe the problem**
I could be wrong but with the CREATE_TUN environment variables are the steps for synology still accurate? https://haugene.github.io/docker-transmission-openvpn/synology-nas/

Since i believe it will create the tunnel now right?

**Comment by haugene** [comment]
Yeah. That looks quite deprecated to me. You're running on Synology, right? Is there anything of this that is needed anymore?

**Comment by braunsonm** [comment]
Yea I'm on Synology and none of these steps are required anymore. I'd just make sure to note that you need CREATE_TUN enabled.

**Comment by haugene** [comment]
Yes, but now in version 3.0 and forward this is set to true as default. So you no longer need to specify it.
I guess I'll just remove the whole page then :+1: Thanks for confirming!

**Comment by iFredOS** [comment]
> Yea I'm on Synology and none of these steps are required anymore. I'd just make sure to note that you need CREATE_TUN enabled.

After I read your post I tried and this is **NOT** true. Sorry false positive. I disabled my schedule (sh) script for the TUN. Restart my NAS. I created a new container with and without "CREATE_TUN_DEVICE=true" and here is what the result:

```
Thu Nov 12 04:48:46 2020 [toronto403] Peer Connection Initiated with [AF_INET]66.115.142.81:1198

Thu Nov 12 04:48:47 2020 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)

Thu Nov 12 04:48:47 2020 Exiting due to fatal error
```

You probably tested it while the TUN script was used.

**Comment by braunsonm** [comment]
Incorrect @iFredOS 

I've been running this without the tun script for weeks now. Check your configuration,

`Thu Nov 12 13:44:56 2020 TUN/TAP device tun0 opened`

**Comment by pchristod** [comment]
Like @iFredOS I couldn't get this to work either (never could) with creating the TUN Device inside the container. Same with 3.0, I've always had to mount the host device by using "--device=/dev/net/tun". However I also never used the Script, you can simply install the Synology VPN Server Package and start the OpenVPN Server, this will create the Host Device.

@braunsonm Could you please specify what options you are using? I would like to understand how this works if you got it working.

**Comment by braunsonm** [comment]
@pchristod Good insight! That's probably why I don't have the issue. I use the Synology OpenVPN server.

**Comment by pchristod** [comment]
@braunsonm Thanks for confirming!

However I'm still curious, if you are using the VPN Server you should be mounting the host device (would correspond to 2) below). Am I correct?

As far as my knowledge goes on Synology there are three possible options as of today:

1) Use the Container provided configuration which will set CREATE_TUN=true and **without** mounting the host device via ("--device=/dev/net/tun") -> this will result in a failure to start the container as seen in the logfile snippet in one of the above comments

2) Install Synology VPN Server Package, start OpenVPN Server, set CREATE_TUN=false (to get rid of the errors in the logfile) and mount host device via "--device=/dev/net/tun" -> this is how I'm using it and it's working fine

3) use the TUN script to create the host device and mount via "--device=/dev/net/tun" -> outdated(?) procedure but should still work as it is basically the same as 2)

**Comment by braunsonm** [comment]
I don't think you can even mount host devices with the Synology implementation. The UI doesn't expose it. I simply have the create tun variable set to true and no issues.

**Comment by pchristod** [comment]
Thanks, very interesting. I'll have to try this again myself sometimes to check. Not sure whats different.
Yeah, the UI is pretty barebones, you are right. I'm using "docker run" via CLI on the NAS to achieve it.

**Comment by haugene** [comment]
@pchristod and @iFredOS: If you can't get it to work without the create tun script then we need to have another look at that. Are you running the latest version? Can you share your logs?

**Comment by pchristod** [comment]
Hi @haugene 
Yes, this is with the latest release, but to be clear, I'v never had it working without mounting the host device, even with older releases. But then again, maybe this is just a matter of wrong configuration on my side. I can try to replay and reproduce maybe this weekend to get (full) logs. Last log lines are the same as iFredOS's earlier.
In the meantime I can share what I tried to use and how I'm using it normally (working) via Docker run.

Not starting up due to tun error:
[Container startup not working.txt](https://github.com/haugene/docker-transmission-openvpn/files/5535671/Container.startup.not.working.txt)

Starting up normally (how I'm using it now) while simply having the Synology VPN Server installed **without** using any TUN Script.
[Container startup working.txt](https://github.com/haugene/docker-transmission-openvpn/files/5535699/Container.startup.working.txt)

**Comment by elisimpson** [comment]
Here what I'm seeing:
1. Run TUN.sh or VPN Server equivalent with "privileged" set in the Synology Docker GUI will work.
2. Run TUN.sh or VPN Server with --cap-add=NET_ADMIN _and_ --device=/dev/net/tun will work. Can't do this in Synology GUI, have to use command line or Portainer. If you want to avoid setting "privileged" this is the only way I found that works.
3. I haven't found any way to use CREATE_TUN_DEVICE=true that works
