### ISSUE TITLE
rpc timeout reached / slow speed / freeze of Docker

### ISSUE THREAD

**Issue by eephrati** [haugene/docker-transmission-openvpn#145]
First off, amazing job at this docker transmission  openvpn container. It's really awesome and is truly well put together.

I had a few issues concerning container. 
1. After installation, it works well, and i can access it via browser. However, it tends to disconnect with a 'the server isn't available' and hangs for a while, then works again a minute later. 
2. After a while though, like an hour maybe? It just stops working and i can't access it at all anymore. It just loads and the server just hangs and it even froze my docker. As you can see, I gave 4G of memory and more of the cpu shares (800 out of 1024) which I feel is enough for this container.

I just want to note a few things:
- I am not running any other containers while running this one.
- I cleared all external activities with this computer to get it to its optimal power
- The Mac Mini doesn't go to sleep
- I am reverse proxying the localhost:9091 to a subdomain of a website

If you can help, that would be amazing! I am working on the project and this container is crucial!

Let me know if you need more information!
Thank you in advance!

**Current Setup**
I am on a Mac mini with those settings:
2.6GHz Processor 
1TB Storage
2.6GHz dual-core Intel Core i5
8GB memory (RAM)
Running on Sierra.

**Docker**
Running the Mac Docker (Stable Version)
Version 1.12.1 (build: 12133)
CPUs: 4
Memory: 8GB

**Here is the code i used to install it**
docker run --privileged  -d \
-v /path/to/data/:/data/ \
-e "OPENVPN_PROVIDER=PIA" \
-e 'OPENVPN_CONFIG=Switzerland' \
-e "OPENVPN_USERNAME=username" \
-e 'OPENVPN_PASSWORD=password' \
-e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true" \
-e "TRANSMISSION_RPC_USERNAME=username" \
-e 'TRANSMISSION_RPC_PASSWORD=password' \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
-e "TRANSMISSION_UMASK=0" \
-p 9091:9091 \
--dns 8.8.8.8 --dns 8.8.4.4 \
--restart=always --name vpntorrent \
--memory="4G" --cpu-shares=800 \
haugene/transmission-openvpn

**here are the logs:**
Using OpenVPN provider: PIA
 Starting OpenVPN using config Switzerland.ovpn
 Setting OPENVPN credentials...
 Wed Oct  5 02:28:05 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
 Wed Oct  5 02:28:05 2016 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
 Wed Oct  5 02:28:05 2016 UDPv4 link local: [undef]
 Wed Oct  5 02:28:05 2016 UDPv4 link remote: [AF_INET]179.43.169.130:1198
 Wed Oct  5 02:28:05 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
 Wed Oct  5 02:28:05 2016 [ef3eb6b3717fb2e179d01c3987bd205b] Peer Connection Initiated with [AF_INET]179.43.169.130:1198
 Wed Oct  5 02:28:08 2016 TUN/TAP device tun0 opened
 Wed Oct  5 02:28:08 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
 Wed Oct  5 02:28:08 2016 /sbin/ip link set dev tun0 up mtu 1500
 Wed Oct  5 02:28:08 2016 /sbin/ip addr add dev tun0 local 10.3.10.6 peer 10.3.10.5
 Wed Oct  5 02:28:08 2016 /etc/transmission/start.sh tun0 1500 1558 10.3.10.6 10.3.10.5 init
 Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.3.10.6
 Generating transmission settings.json from env variables
 STARTING TRANSMISSION
 STARTING PORT UPDATER
 Transmission startup script complete.
 Wed Oct  5 02:28:08 2016 Initialization Sequence Completed
 Generating new client id for PIA
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed
100   104  100    14  100    90      9     58  0:00:01  0:00:01 --:--:--    58
 Got new port 54874 from pia
 transmission auth required
 localhost:9091/transmission/rpc/ responded: "success"
 Checking port...
 Port is open: Yes
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed
100   104  100    14  100    90     10     65  0:00:01  0:00:01 --:--:--    65
 Got new port 54874 from pia
 transmission auth required
 [2016-10-05 03:31:27.706] transmission-remote:  (http://localhost:9091/transmission/rpc/) Timeout was reached
 [2016-10-05 03:32:27.715] transmission-remote:  (http://localhost:9091/transmission/rpc/) Timeout was reached
 Checking port...
 [2016-10-05 03:33:37.742] transmission-remote:  (http://localhost:9091/transmission/rpc/) Timeout was reached
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed
100   104  100    14  100    90      8     56  0:00:01  0:00:01 --:--:--    56
 Got new port 54874 from pia
 transmission auth required
 [2016-10-05 04:35:44.731] transmission-remote:  (http://localhost:9091/transmission/rpc/) Timeout was reached
 [2016-10-05 04:36:44.741] transmission-remote:  (http://localhost:9091/transmission/rpc/) Timeout was reached
 Checking port...
 [2016-10-05 04:37:54.753] transmission-remote:  (http://localhost:9091/transmission/rpc/) Timeout was reached

**Comment by haugene** [comment]
Hey there! Glad you like the container, and weird that it hangs...

I've been looking over your logs and it seems transmission freezes between the first and second running hour as you say. I see that the port update script runs first at init, then once more an hour later but fails after that.

I've never seen this behavior, and I don't get why it messes with your docker daemon. Have you tried running it without the resource caps on cpu-shares and memory? Docker for Mac is quite new, and there's something about the instability of your docker daemon that makes me curious if that might have something to do with it. I guess the container will use much less than the limits you are setting anyways.

**Comment by eephrati** [comment]
With the experiments I tried, leaving the mem and cpu share infinite, somehow crashes my entire Docker (not just the container) and it renders my whole Docker Daemon unresponsive when I try to stop and remove the container.

After a fresh install of the Docker with a mem limit and a cpu share limit, I restarted it with no other container running. And it's actually been working pretty well and hasn't crashed.

However, it still hangs and gives me a (server is not responsive) right after I start adding torrent files. After waiting for a while, it will come back on and work. Do you know why this happens? this hang after adding the torrent? 

How much mem/cpu does this container would need?

**Comment by pkishino** [comment]
Hey guys, I'm also running Docker for Mac on my server with this container and also have the crashing behaviour, but for me it's usually around a week, at least 4-5 days of use. Then suddenly the container freezes and I need to restart docker, remove container then rerun..then everything fine.
My guess it's something to do with the mac version of docker and should be fixed in later updates.

**Comment by eephrati** [comment]
@pkishino you might be right. I tried the container with limitations and it still hung without a timeout log.

I checked the release notes of the Beta and these are their latest notes (that the stable version doesn't have):
* Import certificates in etc/ssl/certs/ca-certificates.crt
* DNS: reduce the number of UDP sockets consumed on the host
* VPNkit: improve the connection-limiting code to avoid running out of sockets on the host
* UDP: handle diagrams bigger than 2035, up to the configured macOS kernel limit
* UDP: make the forwarding more robust; drop packets and continue rather than stopping

Maybe those updates might solve the hanging/freeze/crash problem?

I just installed the Beta version and reinstalled the container without any mem or CPU limitations. For now, it's been working perfectly with no lagging. I will try to push it and see what happens. I will come back in a few days and write my results.

**Comment by pkishino** [comment]
Yeah, cool

**Comment by eephrati** [comment]
Ok, so it's been a couple of days, and I haven't had a drop nor a timeout with the new beta! So i'm very happy with it! Also, turning it off and on has been a breeze. No freeze on the container. On docker stop <transmission-container>, it did it without any problem!

Findings:
- Taking off RPC Authentication takes a considerable load off the container's process
- Updating to the newest Beta solves a lot of the network issues
- If you want to update settings (like SEED_RATIO) you have to make it at a Docker level and not inside the container's settings. ( @haugene - I'll open another issue for that one)

**Comment by eephrati** [comment]
I thought this was over, but I just got this issue:

 Fri Oct 14 20:49:34 2016 [4e2ce1eb0c95f1b42a368ee77cf57e65] Inactivity timeout (--ping-exit), exiting
 Fri Oct 14 20:49:34 2016 /sbin/ip addr del dev tun0 local 10.72.10.6 peer 10.72.10.5
 Fri Oct 14 20:49:34 2016 /etc/transmission/stop.sh tun0 1500 1558 10.72.10.6 10.72.10.5 init
 Fri Oct 14 20:49:34 2016 SIGTERM[soft,ping-exit] received, process exiting

and it's been hung!

**Comment by eephrati** [comment]
also i keep getting this repeatedly in my transmission log:

watchdir Failed to open directory "/data/watch" (2): No such file or directory (watchdir.c:354)

**Comment by haugene** [comment]
So the part where everything hangs I think we've concluded is a Docker on Mac thing, so not related to this container.

As for the watch directory. As it states in the readme, the container expects a watch directory for new .torrent files. That is also reflected in the default transmission-settings. Either create a watch directory beside your completed and incomplete dirs, or disable watch dir using the TRANSMISSION_WATCH_DIR_ENABLED env variable.

**Comment by haugene** [comment]
Closing this now. It seems to be a Docker on Mac issue anyways. Feel free to reopen if more issues/questions arise.
