### ISSUE TITLE
3.x does not include unrar in base image

### ISSUE THREAD

**Issue by phasma343** [haugene/docker-transmission-openvpn#1453]
**Describe the problem**

Torrent complete script no longer works in 3.x. Looks to be due to the rebase on Alpine not including unrar. (Also the busybox version of the find command breaks things in my script, but I can work around that).

The Ubuntu base seemed to have a few more additional tools. Would be good to add some of them like unrar back into the base for this reason. 

Or have an environment variable method for installing additional packages at container startup time.

**Add your docker run command**

  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    networks:
      - torrents
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    devices:
      - /dev/net/tun
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - OVERRIDE_DNS_1=1.1.1.1
      - OVERRIDE_DNS_2=1.0.0.1
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=${OPENVPNCONFIG}
      - OPENVPN_USERNAME=${OPENVPNUSER}
      - OPENVPN_PASSWORD=${OPENVPNPASS}
      - CREATE_TUN_DEVICE=false
      - WEBPROXY_ENABLED=true
      - LOCAL_NETWORK=${LOCALNET}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_SPEED_LIMIT_DOWN=4500
      - TRANSMISSION_SPEED_LIMIT_UP=450
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_ALT_SPEED_DOWN=1000
      - TRANSMISSION_ALT_SPEED_UP=200
      - TRANSMISSION_ALT_SPEED_ENABLED=false
      - TRANSMISSION_MAX_PEERS_GLOBAL=350
      - TRANSMISSION_PEER_LIMIT_GLOBAL=350
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=75
      - TRANSMISSION_RATIO_LIMIT=2
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - DROP_DEFAULT_ROUTE=true
      - TRANSMISSION_IDLE_SEEDING_LIMIT=43200
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME="/config/scripts/unrar.sh"
    volumes:
      - /volumeUSB1/usbshare/Torrents:/data
      - ${DOCKERDIR}/transmission/config:/config
      #- ${DOCKERDIR}/transmission/resolv.conf:/etc/resolv.conf:ro
    ports:
      - 9091:9091
    #dns:
    #  - 1.1.1.1
    #  - 1.0.0.1
    restart: unless-stopped
    labels:
      - traefik.http.routers.transmission.rule=Host(`transmission.local`)
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - traefik.http.routers.transmission.tls=true
      - traefik.http.routers.transmission.entrypoints=websecure

**Logs**

No docker logs for this. Attaching my script for reference though.

```
#!/bin/bash
#A simple script to extract a rar file inside a directory downloaded by Transmission.
#It uses environment variables passed by the transmission client to find and extract any rar files from a downloaded torrent into the folder they were found in.
find /$TR_TORRENT_DIR/$TR_TORRENT_NAME -name "*.rar" -execdir unrar e -o- "{}" \;
```

**Host system:**

Docker on Synology, Can replicate on multiple other docker hosts in a VMs though.

**Comment by haugene** [comment]
You're right. That has been lost in the transition to alpine. I added it now and hopefully that fixes your problem for now.
I'm up for a discussion of what tools should be available in an image like this and maybe have a separate version that has a bunch more tools pre-installed. Right now there are a lot of issues arising after the change to alpine and release of 3.x. But after the dust settles I'm up for looking at alternatives :smile: 

Closing this for now. Let me know how it goes, and re-open if there are still any issues.

**Comment by phasma343** [comment]
> You're right. That has been lost in the transition to alpine. I added it now and hopefully that fixes your problem for now.
> I'm up for a discussion of what tools should be available in an image like this and maybe have a separate version that has a bunch more tools pre-installed. Right now there are a lot of issues arising after the change to alpine and release of 3.x. But after the dust settles I'm up for looking at alternatives 😄
> 
> Closing this for now. Let me know how it goes, and re-open if there are still any issues.

Finally had a chance to test today. After a quick modification to my script to account for the change in the find command (exec vs execdir) everything is working great. Thanks for getting that added back into the base image.

Long term, would it make more sense to have an environment variable flag to install extra packages like this, or leave them in the base image?

Seems like you are trying to get away from having to maintain multiple branches right now. To me it would make sense to either include utilities like unrar, or just make them a quick setting change when deploying the container. Keep from having maintenance spread and stick to one base image.

**Comment by haugene** [comment]
Yeah. You're probably right. I thought I could do it with a different base-image the way I do with the arm builds. The Dockerfile take the base image as argument and that way we could use a very full featured image as another base and still just maintain one Dockerfile.

But. Even in a world where you have "slim" or "fat" image choices it will not cater to all variants of peoples needs. So the most flexible options is probably to just add an environment variable where additional packages can be installed on startup :+1:
