### ISSUE TITLE
How do I update the container?

### ISSUE THREAD

**Issue by ascheel319** [haugene/docker-transmission-openvpn#1458]
I don't use dockers besides this one so I'm still a bit new to it. I have been running into issues with the image I have, I have PIA and I know they are switching from their Legacy servers to their Next-Gen ones so that's why I am having issues. I tried `docker-compose up` and that didn't seem to help. I did switch the server I was connecting to from Toronto to Montreal and that worked but that is more of a temporary fix. I also tried deleting the docker with `docker rm dockerName` and remaking it but that also didn't update it. Is there a way to check to see what version of it I am on?

**Comment by Biggus-Geeus** [comment]
Use `docker-compose pull` to pull the latest image then use `docker-compose up -d` to recreate the container with the new image.

**Comment by ascheel319** [comment]
> Use `docker-compose pull` to pull the latest image then use `docker-compose up -d` to recreate the container with the new image.

Thank you
