### ISSUE TITLE
"OPEN_VPN_PROVIDER=pia" ignores "OPENVPN_CONFIG"

### ISSUE THREAD

**Issue by whezzel** [haugene/docker-transmission-openvpn#1466]
**Describe the problem**
When `OPENVPN_PROVIDER=pia` this runs the custom start script located at `/etc/openvpn/pia/configure-openvpn.sh`. Line 34 of this startup script finds all `*.ovpn` in `/etc/openvpn/pia`, shuffles them, then selects a random config file to use when connecting to endpoints. This behavior completely ignores the endpoints set in the `OPENVPN_CONFIG=<config_name>` variable which is required to be set for the container to start.

**Add your docker-compose.yml**
>---
>version: '3.7'
>services:
>
>  transmission-ovpn:
>    container_name: transmission
>    hostname: transmission.example.com
>    image: haugene/transmission-openvpn:latest
>    ports:
>      - "9091:9091"
>    volumes:
>      - ./data:/data
>      - /netstorage/media/downloads:/downloads
>      - /etc/localtime:/etc/localtime:ro
>    cap_add:
>      - NET_ADMIN
>    environment:
>      - DISABLE_PORT_UPDATER=yes
>      - OPENVPN_PROVIDER=PIA
>      - OPENVPN_CONFIG=Sweden
>      - OPENVPN_USERNAME=USERNAME
>      - OPENVPN_PASSWORD=PASSWORD     
>      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
>      - TRANSMISSION_WEB_UI=transmission-web-control
>      - WEBPROXY_ENABLED=false
>      - LOCAL_NETWORK=<local_network>
>    restart: unless-stopped`

**Logs**

>transmission         | Starting container with revision: 1970f54b88424bf92bc782c3df87310336adf8f4
>transmission         | Using OpenVPN provider: PIA
>transmission         | Provider PIA has a custom startup script, executing it
>transmission         | Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.eLlFKn
>transmission         | Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
>transmission         | Modify configs for this container
>transmission         | 1 servers found in OPENVPN_CONFIG, Sweden chosen randomly
>transmission         | Starting OpenVPN using config Sweden.ovpn
>transmission         | Setting OpenVPN credentials...
>transmission         | adding route to local network XXX.XXX.XXX.XXX/24 via 172.3.0.1 dev eth0
>transmission         | Thu Nov  5 19:33:49 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
>transmission         | Thu Nov  5 19:33:49 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
>transmission         | Thu Nov  5 19:33:49 2020 NOTE: the current --script-security setting may allow this configuration to call >user-defined scripts
>transmission         | Thu Nov  5 19:33:49 2020 CRL: loaded 1 CRLs from file [[INLINE]]
>transmission         | Thu Nov  5 19:33:49 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]XXX.XXX.XXX.XXX:1198
>transmission         | Thu Nov  5 19:33:49 2020 UDP link local: (not bound)
>transmission         | Thu Nov  5 19:33:49 2020 UDP link remote: [AF_INET]XXX.XXX.XXX.XXX:1198
>transmission         | Thu Nov  5 19:33:49 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
>transmission         | Thu Nov  5 19:33:50 2020 [dallas407] Peer Connection Initiated with [AF_INET]XXX.XXX.XXX.XXX:1198
>transmission         | Thu Nov  5 19:33:51 2020 TUN/TAP device tun0 opened
>transmission         | Thu Nov  5 19:33:51 2020 /sbin/ip link set dev tun0 up mtu 1500
>transmission         | Thu Nov  5 19:33:51 2020 /sbin/ip addr add dev tun0 XXX.XXX.XXX.XXX/24 broadcast XXX.XXX.XXX.XXX
>transmission         | Thu Nov  5 19:33:51 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1558 XXX.XXX.XXX.XXX 255.255.255.0 init
>transmission         | Up script executed with tun0 1500 1558 XXX.XXX.XXX.XXX 255.255.255.0 init
>transmission         | Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : XXX.XXX.XXX.XXX
>transmission         | Using Transmission Web Control  UI, overriding TRANSMISSION_WEB_HOME
>transmission         | Updating Transmission settings.json with values from env variables
>transmission         | Using existing settings.json for Transmission /data/transmission-home/settings.json
>transmission         | Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to XXX.XXX.XXX.XXX
>transmission         | Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
>transmission         | Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
>transmission         | Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
>transmission         | Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
>transmission         | sed'ing True to true
>transmission         | Enforcing ownership on transmission config directories
>transmission         | Applying permissions to transmission config directories
>transmission         | Setting owner for transmission paths to 1005:1005
>transmission         | Setting permission for files (644) and directories (755)
>transmission         | Setting permission for watch directory (775) and its files (664)
>transmission         | -------------------------------------
>transmission         | Transmission will run as
>transmission         | -------------------------------------
>transmission         | User name:   abc
>transmission         | User uid:    1005
>transmission         | User gid:    1005
>transmission         | -------------------------------------
>transmission         | STARTING TRANSMISSION
>transmission         | Transmission startup script complete.
>transmission         | Thu Nov  5 19:33:51 2020 Initialization Sequence Completed

**Host system:**
Host: `CentOS Linux release 7.8.2003 (Core)`
Docker: `Docker version 19.03.13, build 4484c46d9d`
Docker compose: `docker-compose version 1.24.1, build 4667896b`

**Comment by RickyXwang** [comment]
I see that you set `- OPENVPN_CONFIG=Sweden`, and if you look at your log you will see `transmission | Starting OpenVPN using config Sweden.ovpn`, it used the config file you provided. Line 34 in pia/configure-openvpn.sh does randomly chose a config and name it default.ovpn, but that is not what you are using.

**Comment by haugene** [comment]
This is the line you're seeing: https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L81
For some reason the script thinks there are multiple values to choose from. I might have cluttered this up when refactoring. The log line is misleading given your input, but it does use the server that you specify. Will have another look :nerd_face:
