### ISSUE TITLE
Can we have Cyberghost VPN as a listed VPN provider please?

### ISSUE THREAD

**Issue by argaume** [haugene/docker-transmission-openvpn#1473]

**Comment by haugene** [comment]
Do you have a link to their bundle of configs? Should be a .zip file that contains all .ovpn files and certificates.

**Comment by argaume** [comment]
I don't think there's any available like that but i can create a config and send you one privately ?

**Comment by haugene** [comment]
Hmm. We're planning to get rid of all checked in configs to this project. They just require future maintenance.
We won't be able to completely remove it of course. Some providers only list their servers on logged-in pages so we can't have a script to fetch them.

If Cyberghost use embedded ca certificates then you can use the `OPENVPN_CONFIG_URL` option. Simply upload the config to Google drive or Dropbox and generate a download url and paste it in that environment variable. Then you don't have to set OPENVPN_PROVIDER or OPENVPN_CONFIG.

**Comment by argaume** [comment]
ok takk, I will check it is may be beyond my capabilities :D

**Comment by haugene** [comment]
#1313
