### ISSUE TITLE
Trying to find OPENVPN_CONFIG variable names

### ISSUE THREAD

**Issue by WormChickenWizard** [haugene/docker-transmission-openvpn#1478]
I'm trying to find the server name for Windscribe's windflix-us server and I can't seem to find it in the documentation. Could perhaps a list of all the servers for each provider be added to the documentation?

Edit: I found the name of the windflix us server which was `WINDFLIX-US-udp`. I found it by going to `openvpn/windscribe` and looking at the .ovpn file names. I do still think that the documentation should be updated to either consult the directory or have a list of all the providers and their subsequent servers.

**Comment by haugene** [comment]
Hey @WormChickenWizard. Glad you found the config, but I'm not entirely agreeing with you on listing the server names in the documentation. One reason for this is that we as of today have over 10.000 configs in the repo and the rate of updates is so high that we would have to update yet another place.

I will also say that there is a section on this today: https://haugene.github.io/docker-transmission-openvpn/run-from-docker-registry/
>The OPENVPN_CONFIG is an optional variable. If no config is given, a default config will be selected for the provider you have chosen. Find available OpenVPN configurations by looking in the openvpn folder of the GitHub repository. The value that you should use here is the filename of your chosen openvpn configuration without the .ovpn file extension. For example:

But I can agree that it possibly should also be linked from the "Supported Providers" page. I have also added a feature that prints the names of all configs if you try to provide one that doesn't exist.
