### ISSUE TITLE
Failed to start with empty settings.json 

### ISSUE THREAD

**Issue by peeter123** [haugene/docker-transmission-openvpn#1484]
**Describe the problem**
My drive was out of storage and a 0 byte settings.json was present. This causes an error when the container tries to start. After removing the file there were no issues in starting.

**Logs**
```Using existing settings.json for Transmission /data/transmission-home/settings.json,
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0),
Traceback (most recent call last):,
  File "/etc/transmission/updateSettings.py", line 45, in <module>,
    settings_dict = json.load(input_file),
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load,
    return loads(fp.read(),,
    obj, end = self.raw_decode(s, idx=_w(s, 0).end()),
    raise JSONDecodeError("Expecting value", s, err.value) from None,
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode,
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode,
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads,
    return _default_decoder.decode(s),
Updating Transmission settings.json with values from env variables
```

**Host system**
```Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:59 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:30 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by haugene** [comment]
Hmm. In this scenario it will fail one way or the other, right? Do you have a proposal for a fix?
One could test that the file exists, has bytes and is valid JSON. But an explicit error message could maybe do just as well. Maybe improve on the log statements?

**Comment by clement-z** [comment]
The standard way would be to catch `JSONDecodeError` rather than try to look at the file directly.

On error `settings.json` can be moved to `settings.json.bk` or something along those lines.

I will submit a PR when I have the time.

**Comment by peeter123** [comment]
I think we need to separate two cases here:
1. There is a 0-byte file which does not contain valid json -> catch JSONDecodeError and try to recreate the settings.json file
2. There is no disk space left (with an invalid file) -> catch JSONDecodeError and try to recreate the settings.json file -> fails on IOError: [Errno 28] No space left on device -> catch that error and exit gracefully with a descriptive error message?

**Comment by clement-z** [comment]
There are two issues which are unrelated here.

1. Empty or not, if `settings.json` is invalid we need to re-create it 
    - Solution: catch `JSONDecodeError` and recreate settings using `default-settings.json`
2. If the write fails (on either `open()` or `json.dump()`), there is no space left or `file/folder` is not writeable
    - Solution: catch the relevant exceptions and exit `transmission/updateSettings.py` with an error code → try to write to logs and exit `transmission/start.sh`.

Rationale for solution to 2. is that as return code is not handled in [transmission/tunnelUp.sh](https://github.com/haugene/docker-transmission-openvpn/blob/93d0141d928ec661411e2c6f0e079aeff2c018dd/openvpn/tunnelUp.sh) (nor is it taken into account by `openvpn`'s `--up` directive). So it will have no effect on the rest of the container which IMO is the best behaviour: even if there is a problem in writing `settings.json`, both `openvpn` and `tinyproxy` might still boot and work (for example if permissions on `settings.json` are wrong). There would still be a message in the logs explaining why transmission did not start and the container would show up as unhealthy.

https://github.com/haugene/docker-transmission-openvpn/blob/93d0141d928ec661411e2c6f0e079aeff2c018dd/openvpn/tunnelUp.sh#L1-L3

**Comment by pkishino** [comment]
@clement-z I believe there was a PR relating to this? otherwise, could you add one please?

**Comment by clement-z** [comment]
I have not gotten around to it yet, no.
I can do it soon.

**Comment by xeorion** [comment]
> There are two issues which are unrelated here.
> 
> 1. Empty or not, if `settings.json` is invalid we need to re-create it
>    
>    * Solution: catch `JSONDecodeError` and recreate settings using `default-settings.json`
> 2. If the write fails (on either `open()` or `json.dump()`), there is no space left or `file/folder` is not writeable
>    
>    * Solution: catch the relevant exceptions and exit `transmission/updateSettings.py` with an error code → try to write to logs and exit `transmission/start.sh`.
> 
> Rationale for solution to 2. is that as return code is not handled in [transmission/tunnelUp.sh](https://github.com/haugene/docker-transmission-openvpn/blob/93d0141d928ec661411e2c6f0e079aeff2c018dd/openvpn/tunnelUp.sh) (nor is it taken into account by `openvpn`'s `--up` directive). So it will have no effect on the rest of the container which IMO is the best behaviour: even if there is a problem in writing `settings.json`, both `openvpn` and `tinyproxy` might still boot and work (for example if permissions on `settings.json` are wrong). There would still be a message in the logs explaining why transmission did not start and the container would show up as unhealthy.
> 
> https://github.com/haugene/docker-transmission-openvpn/blob/93d0141d928ec661411e2c6f0e079aeff2c018dd/openvpn/tunnelUp.sh#L1-L3

I have the same issue. My  settings.json file is empty but I don't understand how recreate it. Can you explain a little bit more please ?

**Comment by pkishino** [comment]
> > There are two issues which are unrelated here.
> > 
> > 1. Empty or not, if `settings.json` is invalid we need to re-create it
> >    
> >    * Solution: catch `JSONDecodeError` and recreate settings using `default-settings.json`
> > 2. If the write fails (on either `open()` or `json.dump()`), there is no space left or `file/folder` is not writeable
> >    
> >    * Solution: catch the relevant exceptions and exit `transmission/updateSettings.py` with an error code → try to write to logs and exit `transmission/start.sh`.
> > 
> > Rationale for solution to 2. is that as return code is not handled in [transmission/tunnelUp.sh](https://github.com/haugene/docker-transmission-openvpn/blob/93d0141d928ec661411e2c6f0e079aeff2c018dd/openvpn/tunnelUp.sh) (nor is it taken into account by `openvpn`'s `--up` directive). So it will have no effect on the rest of the container which IMO is the best behaviour: even if there is a problem in writing `settings.json`, both `openvpn` and `tinyproxy` might still boot and work (for example if permissions on `settings.json` are wrong). There would still be a message in the logs explaining why transmission did not start and the container would show up as unhealthy.
> > https://github.com/haugene/docker-transmission-openvpn/blob/93d0141d928ec661411e2c6f0e079aeff2c018dd/openvpn/tunnelUp.sh#L1-L3
> 
> I have the same issue. My settings.json file is empty but I don't understand how recreate it. Can you explain a little bit more please ?

Stop container, delete settings.json, start container

**Comment by xeorion** [comment]
> > > There are two issues which are unrelated here.
> 
> > > 
> 
> > > 1. Empty or not, if `settings.json` is invalid we need to re-create it
> 
> > >    
> 
> > >    * Solution: catch `JSONDecodeError` and recreate settings using `default-settings.json`
> 
> > > 2. If the write fails (on either `open()` or `json.dump()`), there is no space left or `file/folder` is not writeable
> 
> > >    
> 
> > >    * Solution: catch the relevant exceptions and exit `transmission/updateSettings.py` with an error code → try to write to logs and exit `transmission/start.sh`.
> 
> > > 
> 
> > > Rationale for solution to 2. is that as return code is not handled in [transmission/tunnelUp.sh](https://github.com/haugene/docker-transmission-openvpn/blob/93d0141d928ec661411e2c6f0e079aeff2c018dd/openvpn/tunnelUp.sh) (nor is it taken into account by `openvpn`'s `--up` directive). So it will have no effect on the rest of the container which IMO is the best behaviour: even if there is a problem in writing `settings.json`, both `openvpn` and `tinyproxy` might still boot and work (for example if permissions on `settings.json` are wrong). There would still be a message in the logs explaining why transmission did not start and the container would show up as unhealthy.
> 
> > > https://github.com/haugene/docker-transmission-openvpn/blob/93d0141d928ec661411e2c6f0e079aeff2c018dd/openvpn/tunnelUp.sh#L1-L3
> 
> > 
> 
> > I have the same issue. My settings.json file is empty but I don't understand how recreate it. Can you explain a little bit more please ?
> 
> 
> 
> Stop container, delete settings.json, start container

I just did it. I stopped the container, deleted the file and and restart the container but a new settings.json empty file est created. My problem is not solved, do you have an idea ?

**Comment by pkishino** [comment]
Create a new discussion q&a(not a new issue..) and post your complete config and log output.
Most likely permission problems
