### ISSUE TITLE
PIA not working with special characters in the password

### ISSUE THREAD

**Issue by redlukas** [haugene/docker-transmission-openvpn#1486]
**Describe the problem**
The VPN connection fails if the VPN provider is PIA and the Password has special characters in it (I have not tested it for other VPN providers)

**Add your docker run command**
sudo docker run --cap-add=NET_ADMIN -d \
              -v /home/studi/Downloads/Transmission/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=PIA \
              -e OPENVPN_CONFIG=Switzerland \
              -e OPENVPN_USERNAME=***redacted*** \
              -e OPENVPN_PASSWORD=8m9K0EnnhC%$S%%blLf* \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=10.0.0.0/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9099:9091 \
              haugene/transmission-openvpn

**Logs**
Starting container with revision: eea5f085923e56a815932e6e1b69856ba151449e

Using OpenVPN provider: PIA

Provider PIA has a custom startup script, executing it

Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.ElPPeo

Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia

Modify configs for this container

Starting OpenVPN using config Switzerland.ovpn

Setting OpenVPN credentials...

adding route to local network 10.0.0.0/24 via 172.17.0.1 dev eth0

Mon Nov  9 18:08:57 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020

Mon Nov  9 18:08:57 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10

Mon Nov  9 18:08:57 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts

Mon Nov  9 18:08:57 2020 CRL: loaded 1 CRLs from file [[INLINE]]

Mon Nov  9 18:08:57 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]212.102.36.171:1198

Mon Nov  9 18:08:57 2020 UDP link local: (not bound)

Mon Nov  9 18:08:57 2020 UDP link remote: [AF_INET]212.102.36.171:1198

Mon Nov  9 18:08:57 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Mon Nov  9 18:08:57 2020 [zurich408] Peer Connection Initiated with [AF_INET]212.102.36.171:1198

Mon Nov  9 18:08:58 2020 AUTH: Received control message: AUTH_FAILED

Mon Nov  9 18:08:58 2020 SIGTERM[soft,auth-failure] received, process exiting>

**Host system:**
Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-48-generic x86_64)

**Troubleshooting**
I have changed the password to an alphanumeric one (upper- and lowercase letters) and now it works like a charm. This is the only setting i changed to make it work.

**Comment by haugene** [comment]
Seems I've re-introduced #245 when going to 3.0.

**Comment by Xaimerr** [comment]
Any luck on this?
