### ISSUE TITLE
Separate providers into a 2nd repo

### ISSUE THREAD

**Issue by ksurl** [haugene/docker-transmission-openvpn#1489]
The linuxserver/swag repo (nginx reverse proxy with text based config) has a separate repo for sample reverse proxy config files that are downloaded and copied into the image at build and updated on every container start. This dissociates the changes to config files from the functionality of the core image. I think this principle will carry over nicely for the transmission image so vpn config changes won't need a new build of the container. PR and updates can be handled at the 2nd repo independently of the main repo. This is in line with simplifying the config maintenance with 3.x

What do you think?

**Comment by haugene** [comment]
I like it :+1: Have been thinking a bit about a solution like that myself. See #1427 that also tries to address this.
It's a good idea to clone it on build time and update it on run time. But I have also been thinking that if we clone it on run time then we can also allow for people to use different repositories. That could be handy when doing a PR to the config-repo and be able to specify your own fork as the source.

That can also be done if we pre-clone as well. But I'm worried about size. Not that it matters too much but the image is today ~28MB and the repo is 100MB. So much historic config files I guess.

And lastly as mentioned in the other issue. It would be nice if this could be set up in a way with the codeowners stuff from Github to distribute ownership.

**Comment by ksurl** [comment]
I guess we could start if you create a repo for the configs (something like haugene/docker-vpn-configs or providers, keeping it agnostic since WireGuard is on the roadmap as well. Though that may be a little different since each conf file has a unique private key? Unless WireGuard supports merging configs since it would have a common server fqdn and psk).

Then work can begin on a branch that downloads it on build and boot. wget or curl with tar and gzip can work so we don't have git files laying around.

As for custom repo, we could use another environment variable that defaults to the main one.

**Comment by haugene** [comment]
Yes. That sounds good. I was about to name it "openvpn-configs" and didn't think of wireguard. could have a "wireguard-configs" repo as well I guess. What do you think about git history? Should we start from scratch, or make it like a fork of the main repo and just re-structure it so that we keep a history of who has maintained a provider in the past as well?

**Comment by ksurl** [comment]
Should it be separated by provider or by vpn type? Do they have to be separate repo's?

That sounds good. I didn't think of that, who has been submitting PR for various providers.

**Comment by haugene** [comment]
https://github.com/haugene/vpn-configs

I started here. Has the complete history, but completely wiped for anything that's not .ovpn or txt, crt, ca, key files.
I'm not sure about what's the best approach. per provider or per technology. Let the original structure stand now. So it's just "openvpn"/"provider" like before. Outlined a structure with bundles though. We'll see :+1: 

It's late here in Norway, I'm logging off. But hopefully it's a good starting point. I'll close the other linked issue and we'll follow up here.

**Comment by ksurl** [comment]
great! I think we should try to get something up and running first before redesigning how it chooses how to get providers.

git would be the most efficient now that I think about it since a pull will just grab the delta rather than downloading a zip and extracting/overwriting the version from the last image build. is git already an installed package?

**Comment by haugene** [comment]
Doesn't seem git is included. But it can be, and then do a shallow clone on build I guess. To not get the whole state.
Tested locally. Cloning shallow takes half the time but we're talking seconds. It also takes half the space, 50 MB instead of 100. Which is good. When checking the providers there are some that are consuming way more space than others with ProtonVPN at 13 MB. Hopefully a candidate for scripting :crossed_fingers: 

Adding git now and then I really have to get to bed :laughing:

**Comment by ksurl** [comment]
I've played around with different methods to do this. here are some brief notes:

* Either way, move provider folders to root of vpn-configs repo and get rid of openvpn top level folder. makes it easier to deal with when either cloning or downloading the archive and extracting.

* Use 2 folders /etc/openvpn/dynamic and static
git clone in Dockerfile to static folder: `RUN git clone --depth 1 https://github.com/haugene/vpn-configs /etc/openvpn/static`
git pull in /etc/openvpn/start.sh script before defining vpn provider folder (pushd and popd to get context?)
need to detect type in start.sh script to set vpn provider home
detect by checking if provider folder exists in either static or dynamic or set custom with case or if else statement
```
case $VPN_PROVIDER in 
  [[ -d /etc/openvpn/static/$VPN_PROVIDER ]])
    VPN_PROVIDER_HOME="/etc/openvpn/static/${VPN_PROVIDER}"
and so on for dynamic and custom
esac
```
if custom, use separate folder /etc/openvpn/custom
have to check all usage of vpn_provider_home and openvpn_config used in path for transmission scripts. there is one path used in /etc/transmission/start.sh

* Use the same folder for both types like it was before, but in a subfolder like /etc/openvpn/configs
can't clone to non empty folder if dynamic configs are in there
use wget or curl to get archive of vpn-configs main branch and extract to folder
create subfolder so it doesn't pollute /etc/openvpn
downloads 47mb every time on build and boot so it is not ideal
the workaround for git would be to have dynamic configs in a known folder like /etc/openvpn/dynamic and copy them after cloning
delete the known list of dynamic types on boot and pull on boot and copy them again

we could also detect type by keeping a known list to read from (dict?) and using the appropriate folder

**Comment by ksurl** [comment]
Moving the dynamic configs to the config repo would solve the detection issue since it would keep the path the same and the only change would be to git clone on build and pull on boot

**Comment by ksurl** [comment]
While reading through the code, I was thinking of Wireguard integration and at first I was thinking of using something like /etc/vpn/openvpn,wireguard, but it doesn't really matter if they're sub or top level folders. It can have /etc/openpvn,wireguard. There will also be a lot of untangling non-openvpn stuff from the start script and the initial script would have to detect probably based on an environment variable which vpn to use and call the appropriate scripts and configs. I think keeping the folder structure and startup architecture as is will be fine until it needs to be redesigned for wireguard. Shipping the config import is a good start.

**Comment by spar01** [comment]
Not sure if this is the right place to ask this question:
If I want to help out with updating the protonvpn ovpn configs since they added some more p2p servers, should that be done in this repository or the new one you created above? Not sure if you are still accepting updates for ovpn into this repo.

**Comment by ksurl** [comment]
Probably submit to the main repo for now. The new repo is a placeholder until it's ready ro cutover and it's not that much work to copy the latest version to the repo once it is ready.

**Comment by haugene** [comment]
Made a first attempt at the separation logic :point_up: @ksurl. Have a look and let me know what you think.

**Comment by pkishino** [comment]
closing this as work is in progress
