### ISSUE TITLE
docker-wireguard-openvpn

### ISSUE THREAD

**Issue by MrEaoP** [haugene/docker-transmission-openvpn#1492]
So Wireguard seems to be the new cool kid on the block...

Have you ever considered making a docker container with Transmission & Tinyproxy & Wireguard?

I've tried several different solutions to this, running them as three different containers, but for some reason I just can't get it to work... so for that reason a single container running all three might be the best option?

Just a thought - the current container works fine, many thanks!

**Comment by haugene** [comment]
Let's follow up in #1107 ;) I do plan to include it here actually. The plan is that you should be able to choose Wireguard or OpenVPN. Closing this as a duplicate.
