### ISSUE TITLE
Too many unsuccessful login attempts. Please restart transmission-daemon.

### ISSUE THREAD

**Issue by mdstoll** [haugene/docker-transmission-openvpn#1493]
Not sure if this is entirely related to the docker image or just transmission itself, but although this worked perfectly before, right now I get the error:

**403: Forbidden
Too many unsuccessful login attempts. Please restart transmission-daemon.**

After restart, everything works fine again. I also believe the program keeps running in the background, I just can't manage it. Probably noteworthy: I haven't forwarded the port number through my router (NAT), so technically no-one outside of my network could cause 'unsuccessful login attempts'

Also added the following environmental values in an attempt to fix this:
TRANSMISSION_RPC_WHITELIST_ENABLED | true
TRANSMISSION_RPC_WHITELIST | *
But unfortunately, without result.

If any additional information is required, I'm happy to supply. Thanks!

**Comment by RickyXwang** [comment]
Please post the docker/transmission log, and your start configuration/docker-compose.

**Comment by mdstoll** [comment]
Is this useful?

**Log:**
[transmission-openvpn_log_20201110.txt](https://github.com/haugene/docker-transmission-openvpn/files/5520154/transmission-openvpn-syno_log_20201110.txt)

**Docker Run:**
docker run \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    -d \
    -v /volume1/scripts/transmissionsupport/resolv.conf:/etc/resolv.conf \
    -v /volume2/downloads/:/data \
    -e "OPENVPN_PROVIDER=PIA" \
    -e "OPENVPN_CONFIG=Netherlands" \
    -e "OPENVPN_USERNAME=censored" \
    -e "OPENVPN_PASSWORD=censored" \
    -e "LOCAL_NETWORK=192.168.0.0/24" \
    -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
    -e "PGID=100" \
    -e "PUID=1027" \
    -e "TRANSMISSION_WEB_UI=transmission-web-control" \
    -e "TRANSMISSION_BLOCKLIST_ENABLED=true" \
    -e "TRANSMISSION_BLOCKLIST_URL=http://john.bitsurge.net/public/biglist.p2p.gz" \
    -e "TRANSMISSION_CACHE_SIZE_MB=16" \
    -e "TRANSMISSION_DOWNLOAD_QUEUE_SIZE=50" \
    -e "TRANSMISSION_ENCRYPTION=2" \
    -e "TRANSMISSION_PEER_LIMIT_GLOBAL=400" \
    -e "TRANSMISSION_RATIO_LIMIT=5" \
    -e "TRANSMISSION_RATION_LIMIT_ENABLED=true" \
    -e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true" \
    -e "TRANSMISSION_RPC_PASSWORD="censored" \
    -e "TRANSMISSION_RPC_USERNAME="censored"" \
    -e "TRANSMISSION_SPEED_LIMIT_UP=10000" \
    -e "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true" \
    -e "TRANSMISSION_UTP_ENABLED=false" \
    -e "TRANSMISSION_QUEUE_STALLED_ENABLED=false" \
    -p 9091:9091 \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --name "transmission-openvpn-syno" \
    haugene/transmission-openvpn:latest

**Comment by haugene** [comment]
Yes. Do you have any special characters in your TRANSMISSION_RPC_PASSWORD? Or in the username for that matter.
The port update script is hammering Transmission and getting auth failure.

There are issues with the port forwarding script these days so you could disable it, but the long term solution is to change the password.

**Comment by mdstoll** [comment]
In the config my 'normal' username is listed (plain text) and my password is listed as a hash. If i start the container I can actually login, but later on it bounces all attempts.

There is a { symbol in the hashed pass but I don't recon that should be an issue right? As logging in does work at first. It just seems as if some process is trying to connect but bounces. 

How ould I disable the port forwarding script? Maybe that works. Thanks for the help!

**Comment by haugene** [comment]
Yeah. You can't use the hashed version. We need the password in plaintext to connect to Transmission in order to automatically update your port. So you either have to set it to the plaintext version (and then it will be hashed by Transmission in the settings.json file) or you can set `DISABLE_PORT_UPDATER=yes`. But then you won't get an open port later when we fix the script.

**Comment by mdstoll** [comment]
Thanks for the responses! I've added DISABLE_PORT_UPDATER=yes for now. Seems to have solved the problem!
Will check in later when the open port script is fixed :)

**Comment by haugene** [comment]
:+1:

**Comment by adocampo** [comment]
I'm having the very same issue. Container worked fine for weeks, but now I cannot even connect with the same error..
![imagen](https://user-images.githubusercontent.com/2266612/104852927-af8aa000-58fd-11eb-8906-93c3bcc5f21b.png)

It even doesn't ask for credentials, just this page appears.
I've tried the environment variable `DISABLE_PORT_UPDATER=yes` but doesn't work either.

This is how I created the docker container.

```
docker create --name transmission \
--restart=unless-stopped \
--cap-add=NET_ADMIN \
-e DISABLE_PORT_UPDATER=yes \
-v /data/files/Downloads:/data \
-e OPENVPN_PROVIDER=FASTESTVPN \
-e OPENVPN_CONFIG=Spain-UDP \
-e OPENVPN_USERNAME=<username> \
-e OPENVPN_PASSWORD=<password> \
-e LOCAL_NETWORK=192.168.1.0/24 \
--log-driver json-file \
--log-opt max-size=10m \
-p 9091:9091 \
haugene/transmission-openvpn
```
I copied my settings.json from my older docker container, and it worked as I said, for weeks, and it asked for the credentials. What I noticed is until two days the proper username was the one who connected to transmission, and now is my email (which is the FASTESTVPN username) who is trying, and this isn't the correct username. I don't know if it is grabbing the wrong username.

I event tried the `docker run` command from @mdstoll, adapted for my VPN provider and scenario, but the error persists.

**Comment by dmishne** [comment]
> I'm having the very same issue. Container worked fine for weeks, but now I cannot even connect with the same error..
> ![imagen](https://user-images.githubusercontent.com/2266612/104852927-af8aa000-58fd-11eb-8906-93c3bcc5f21b.png)
> 
> It even doesn't ask for credentials, just this page appears.
> I've tried the environment variable `DISABLE_PORT_UPDATER=yes` but doesn't work either.
> 
> This is how I created the docker container.
> 
> ```
> docker create --name transmission \
> --restart=unless-stopped \
> --cap-add=NET_ADMIN \
> -e DISABLE_PORT_UPDATER=yes \
> -v /data/files/Downloads:/data \
> -e OPENVPN_PROVIDER=FASTESTVPN \
> -e OPENVPN_CONFIG=Spain-UDP \
> -e OPENVPN_USERNAME=<username> \
> -e OPENVPN_PASSWORD=<password> \
> -e LOCAL_NETWORK=192.168.1.0/24 \
> --log-driver json-file \
> --log-opt max-size=10m \
> -p 9091:9091 \
> haugene/transmission-openvpn
> ```
> 
> I copied my settings.json from my older docker container, and it worked as I said, for weeks, and it asked for the credentials. What I noticed is until two days the proper username was the one who connected to transmission, and now is my email (which is the FASTESTVPN username) who is trying, and this isn't the correct username. I don't know if it is grabbing the wrong username.
> 
> I event tried the `docker run` command from @mdstoll, adapted for my VPN provider and scenario, but the error persists.

Did you figure out how to resolve it?

**Comment by rlch** [comment]
Any updates on this?

**Comment by G4Zz0L1** [comment]
Same story here, and I don't know why. I don't have docker though, it's a normal install.

**Comment by pkishino** [comment]
> Same story here, and I don't know why. I don't have docker though, it's a normal install.

so you are just straight using transmission..in that case, which version? Clearly sounds like a bug with transmission then..

**Comment by G4Zz0L1** [comment]
Uh, sorry for that, I've struggling with this for a while now, and I've found this issue via google, didn't even read that it's not transmission main repo.
I'll try asap to open an issue on the official repo, maybe it's worth something.
If it helps, I'm on arch linux, with the standard package in the extra repository, now on version 3.0.
https://archlinux.org/packages/extra/x86_64/transmission-cli/

**Comment by simonpie** [comment]
I have had the same problem with transmission running as a plugin on FreeNAS for a while.  My password does not contain any special caracters.

**Comment by ralyodio** [comment]
I also get this just running cli on ubuntu.

**Comment by pkishino** [comment]
Please see the limited issue above

**Comment by Snuffsis** [comment]
I have started getting this issue as well.
Apparently there is a supposed fix with a variable named "anti-brute-force-enabled", but setting this as environment variable doesn't seem to do anything.

**Comment by rlch** [comment]
I indirectly fixed this by adding authentication middleware to the endpoint I expose transmission at, and removed the authentication provided by transmission

**Comment by bw118** [comment]
Same problem here with PIA and no special character. Tried the "anti-brute-force-enabled" no luck.

**Comment by davidszp** [comment]
The anti-brute-force-enabled setting was only released in Transmission 4.0beta1, I believe we're still on 3.00, so the setting  wouldn't have an effect yet.

**Comment by davidszp** [comment]
I downgraded to haugene/transmission-openvpn:4.2 (transmission 2.94) and the problem as disappeared for now.

**Comment by BenPicard** [comment]
Also downgrade to 4.2 to remove this problem from latest build.

**Comment by UltimateByte** [comment]
> The anti-brute-force-enabled setting was only released in Transmission 4.0beta1, I believe we're still on 3.00, so the setting wouldn't have an effect yet.

transmission-common/stable,now 3.00-1 all [installed,automatic]
Upon logging to Transmission Remote GUI : 
![image](https://user-images.githubusercontent.com/8805941/229997625-5c46e579-19ae-4b7f-9c2d-65936e0e6026.png)

**Comment by CrazyWolf13** [comment]
Please fix this, getting the same!

**Comment by pkishino** [comment]
> Please fix this, getting the same!

This is an issue with transmission, not this container
