### ISSUE TITLE
Share VPN tunnel outside docker

### ISSUE THREAD

**Issue by jorgelsaba** [haugene/docker-transmission-openvpn#1500]
Is it possible to share this container's VPN tunnel outside docker, with LAN devices? For instance, use this container as a Internet gateway for my notebook?
Thank you!

**Comment by zellenberg** [comment]
webproxy

**Comment by mouzzampk2014** [comment]
@jorgelsaba put these in your ompose
```
    environment:
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888
```
```
    ports:
      - 9091:9091
      - 8888:8888
```
Then in your browser settings change the proxy settings and add the ip address of the machine where `transmissionvpn` is installed and the port.

**Comment by jorgelsaba** [comment]
Thank you both!!
