### ISSUE TITLE
Seeing slow speeds from all hide.me servers

### ISSUE THREAD

**Issue by zellenberg** [haugene/docker-transmission-openvpn#1501]
Hello all - not sure if this is just me so filing an issue to see if anyone else is having this problem. About a week or so ago I saw my download speeds drop from 30 - 40 MBps down to 2 MBps when using the default hide.me servers. I tried a few other hide.me servers and saw the same speed drop. Is anybody else experiencing this?

**Comment by RickyXwang** [comment]
Can you ssh into the container and do a speed test from cmd? 
`apk add speedtest-cli`
`speedtest-cli`

**Comment by zellenberg** [comment]
Turns out that it was an issue with my hide.me account
