### ISSUE TITLE
Raspi4 - failing on TUN Device Create

### ISSUE THREAD

**Issue by tjcrandley** [haugene/docker-transmission-openvpn#1503]
**Describe the problem**
I'm trying to get transmission working on my Raspi4 (4GB) and I'm running into some log errors when it tries to create the TUN device.  I've tried it both with the "CREATE_TUN_DEVICE=true" in the script and out of the docker-compose script.  I tested this same docker compose on an intel based ubuntu 20.04 machine and it works as expected, so I believe it's either something A) something to do with the RasPi or B) something to do with the DietPi distro (an optimized Rasbian based distro) I'm using.

**Add your docker run command**
  transmission-openvpn: #Updated V3 https://github.com/haugene/docker-transmission-openvpn/
    container_name: transmission
    image: haugene/transmission-openvpn:3.1
    restart: always
    ports: 
      - "9091:9091"
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/transmission-vpn/data:/data
      - $DOCKERDIR/transmission-vpn/config:/config
      - $USERDIR/Downloads:/downloads
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    environment: 
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: US Seattle
      OPENVPN_USERNAME: <removed>
      OPENVPN_PASSWORD: <removed>
      WEBPROXY_ENABLED: 'false'
      LOCAL_NETWORK: 10.0.0.0/8

**Logs**
Starting container with revision: 3d97cd5302985c1a710f46ab0c311f721f224fc6,
Using OpenVPN provider: PIA,
Provider PIA has a custom startup script, executing it,
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.NkUqVVcuR4,
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia,
Modify configs for this container,
Starting OpenVPN using config US Seattle.ovpn,
Setting OpenVPN credentials...,
adding route to local network 10.0.0.0/8 via 172.18.0.1 dev eth0,
Wed Nov 11 22:18:45 2020 OpenVPN 2.4.7 aarch64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019,
Wed Nov 11 22:18:45 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10,
Wed Nov 11 22:18:45 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Wed Nov 11 22:18:45 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]154.21.20.161:1198,
Wed Nov 11 22:18:45 2020 UDP link local: (not bound),
Wed Nov 11 22:18:45 2020 UDP link remote: [AF_INET]154.21.20.161:1198,
Wed Nov 11 22:18:45 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Wed Nov 11 22:18:45 2020 [seattle417] Peer Connection Initiated with [AF_INET]154.21.20.161:1198,
Wed Nov 11 22:18:46 2020 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19),
Wed Nov 11 22:18:46 2020 Exiting due to fatal error

**Host system:**
Linux DietPi 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Wed Sep 16 17:03:56 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46
  Built:            Wed Sep 16 17:02:25 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by RickyXwang** [comment]
Hi, can you try creating the tun dev in the host and then bind it to the container? 
Tun dev is created by the following:

  `mkdir -p /dev/net
  mknod /dev/net/tun c 10 200
  chmod 0666 /dev/net/tun`

Check if it's compatible with your setup.

FYI, here is a script that does it for Synology, .
`#!/bin/sh

# Create the necessary file structure for /dev/net/tun
if ( [ ! -c /dev/net/tun ] ); then
	if ( [ ! -d /dev/net ] ); then
		mkdir -m 755 /dev/net
	fi
	mknod /dev/net/tun c 10 200
	chmod 0755 /dev/net/tun
fi

# Load the tun module if not already loaded
if ( !(lsmod | grep -q "^tun\s") ); then
	insmod /lib/modules/tun.ko
fi`

**Comment by haugene** [comment]
This is strange... For several reasons. First off, it doesn't report an error on creating the TUN device, but in opening it. Because it's not there. Does that mean it's just [skipped this step](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L30)? It should only skip it if it's not set...

Anyways. Another thing is that you have `haugene/transmission-openvpn:3.1` in your compose file, but your logs say
```
Starting container with revision: 3d97cd5
```
which is older.

Can you try to do a `docker pull haugene/transmission-openvpn` and just use latest?
And... 3.1 is a multiarch build. But I don't think 3d97cd5 was. I don't get it :thinking: 

Pull a new image, try again and lets see some new logs :smile:

**Comment by tjcrandley** [comment]
It doesn't really make sense to me either.  I tried that script (and manually creating the files) and got the same result.  My next step will be to create a new RasPi instance using ubuntu 20.04 and see if it's the same result (I doubt it) - I'm only using DietPi because it was 64bit before anyone else.  For history, here are the steps I took and the logs

1) Using portainer, removed Transmission container
2) Using portainer, removed all transmission-vpn images
3) Run these bash commands:
dietpi@DietPi:~/docker$ sudo rm -Rf transmission-vpn/
dietpi@DietPi:~/docker$ docker-compose -f docker-compose.yml up -d --remove-orphans
Pulling transmission-openvpn (haugene/transmission-openvpn:3.1)...
3.1: Pulling from haugene/transmission-openvpn
5f621e34cdf4: Pull complete
0854aaaea3db: Pull complete
b307e1e6079a: Pull complete
34394ff83d2a: Pull complete
3badc91ee140: Pull complete
72b5d3828a6b: Pull complete
Digest: sha256:4958d92b06db8fd91938f171e9bd82aa3914a3e40a490c82d58c948aa195a999
Status: Downloaded newer image for haugene/transmission-openvpn:3.1
pihole is up-to-date
portainer is up-to-date
Creating transmission ... done

4) Transmission logs (pulled using portainer):
Starting container with revision: baa14dbe3d030306dd3bc0a79570c6aaf7124390,
Using OpenVPN provider: PIA,
Provider PIA has a custom startup script, executing it,
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.lHhmOE,
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia,
Modify configs for this container,
Starting OpenVPN using config US Seattle.ovpn,
Setting OpenVPN credentials...,
adding route to local network 10.0.0.0/8 via 172.18.0.1 dev eth0,
Fri Nov 13 16:44:04 2020 OpenVPN 2.4.9 aarch64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020,
Fri Nov 13 16:44:04 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10,
Fri Nov 13 16:44:04 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Fri Nov 13 16:44:04 2020 CRL: loaded 1 CRLs from file [[INLINE]],
Fri Nov 13 16:44:04 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]154.21.20.141:1198,
Fri Nov 13 16:44:04 2020 UDP link local: (not bound),
Fri Nov 13 16:44:04 2020 UDP link remote: [AF_INET]154.21.20.141:1198,
Fri Nov 13 16:44:04 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Fri Nov 13 16:44:04 2020 [seattle416] Peer Connection Initiated with [AF_INET]154.21.20.141:1198,
Fri Nov 13 16:44:06 2020 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options,
Fri Nov 13 16:44:06 2020 OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3,
Fri Nov 13 16:44:06 2020 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19),
Fri Nov 13 16:44:06 2020 Exiting due to fatal error,

My docker-compose snippet:
  transmission-openvpn: #Updated V3 https://github.com/haugene/docker-transmission-openvpn/
    container_name: transmission
    image: haugene/transmission-openvpn:3.1
    restart: always
    ports: 
      - "9091:9091"
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/transmission-vpn/data:/data
      - $DOCKERDIR/transmission-vpn/config:/config
      - $USERDIR/Downloads:/downloads
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    environment: 
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CREATE_TUN_DEVICE: 'true'
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: US Seattle
      OPENVPN_USERNAME: removed-for-post
      OPENVPN_PASSWORD: removed-for-post
      WEBPROXY_ENABLED: 'false'
      LOCAL_NETWORK: 10.0.0.0/8

**Comment by RickyXwang** [comment]
Are you able to create the tun dev on the host? ie: do you see the tun in `/dev/net` 
Try pull the new version which log the create tun script.
Also, try reboot the host.

**Comment by barnscott** [comment]
Also seeing this same issue. Using podman on x86_64.
Did not previously have any issues using podman, but this is on new server/pc that is using same config/external-disk/mounts.

```
$ podman logs tguard
Starting container with revision: 4b72fa07ca3258f9226c27726c0cbe8ce5e127f5
mknod: /dev/net/tun: Operation not permitted
chmod: /dev/net/tun: No such file or directory
Using OpenVPN provider: PIA
Provider PIA has a custom startup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.nncBJj
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Modify configs for this container
Starting OpenVPN using config US Texas.ovpn
Setting OpenVPN credentials...
adding route to local network 192.168.1.0/24 via 10.0.2.2 dev tap0
Mon Nov 16 21:01:55 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Mon Nov 16 21:01:55 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Mon Nov 16 21:01:55 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Nov 16 21:01:55 2020 CRL: loaded 1 CRLs from file [[INLINE]]
Mon Nov 16 21:01:55 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]154.29.131.141:1198
Mon Nov 16 21:01:55 2020 UDP link local: (not bound)
Mon Nov 16 21:01:55 2020 UDP link remote: [AF_INET]154.29.131.141:1198
Mon Nov 16 21:01:55 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Nov 16 21:01:55 2020 [dallas412] Peer Connection Initiated with [AF_INET]154.29.131.141:1198
Mon Nov 16 21:01:56 2020 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
Mon Nov 16 21:01:56 2020 OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3
Mon Nov 16 21:01:56 2020 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Mon Nov 16 21:01:56 2020 Exiting due to fatal error
```

I reverted back to v2.14, and do not see this issue, _however_, I get [this](https://github.com/haugene/docker-transmission-openvpn/issues/1520) error instead when using v2.14.

**Comment by haugene** [comment]
Hmm. Yes, using PIA on 2.14 will not work. Or if it does it's not permanent. It contains the old set of configs for PIA for their legacy network. They were supposed to shut it down by the end of October but some servers seems to have stayed up a bit longer.

You're getting `mknod: /dev/net/tun: Operation not permitted` though. Have you given the container the NET_ADMIN capability?

**Comment by barnscott** [comment]
@haugene Yup, sorry i wasn’t clear:
The logs i shared are using "_latest_". After "_latest_" failed with the previously posted log error, i attempted v2.14, as i suspected the error in "_latest_" may be a breaking change related to v3+, but as I mentioned, v2.14 also gave me different problems. I still think it is of interest that I do not see the _tun_ error in v2.14.

This is my run command which ive been using via podman, previously without error (before my system migration):

podman run -d \
    --cap-add=NET_ADMIN \
    -e CREATE_TUN_DEVICE=true \
    --name tguard \
    -v /patha:/data/transmission-home \
    -v /pathb:/data/completed \
    -v /pathc:/data/incomplete \
    -v /pathd:/data/watch \
    -v /etc/localtime:/etc/localtime:ro \
    --env-file /pathe/DockerEnv \
    -e "PUID=1001" \
    -e "PGID=1001" \
    -p 9091:9091 \
    --dns 8.8.8.8 \
    --dns 8.8.4.4 \
    haugene/transmission-openvpn:latest

**Comment by haugene** [comment]
What about running it will full `--privileged` just to see if that makes a difference. Of course since I don't see your DockerEnv file I'm curious what's in there. And btw CREATE_TUN_DEVICE=true is default from 3.0 so you don't need it.

What do you get if you only do:
```
podman run -d --privileged --name test \
  OPENVPN_PROVIDER=provider \
  OPENVPN_USERNAME=username \ 
  OPENVPN_PASSWORD=password \ 
  haugene/transmission-openvpn
```

I.e a really minimal start. If it does not give an error, then try replacing privileged with NET_ADMIN.

**Comment by barnscott** [comment]
Yup you got it.

I had tried:
_podman run -d  --cap-add=NET_ADMIN ..._
and i had attempted this without luck either...
_sudo podman run -d  --cap-add=NET_ADMIN ..._

but I hadnt tried using --privileged instead of --cap-add=NET_ADMIN. That resolved my tun issue with and without sudo.

Not sure what changed regarding why I didn’t use --privileged before, but Ill dig into that later.
Thanks!

**Comment by nicbou** [comment]
I didn't want to run with `- privileged: true`. I added the device to docker-compose, and it works. @haugene, since I'm not familiar with networking, could you confirm that I'm not shooting myself in the foot, and exposing myself to a salty fine?

```
  torrents:
    image: haugene/transmission-openvpn:latest
    environment:
      - OPENVPN_PROVIDER
      - OPENVPN_USERNAME
      - OPENVPN_PASSWORD
      - OPENVPN_CONFIG=netherlands
      - PIA_OPENVPN_CONFIG_BUNDLE=openvpn
      ...
      - LOCAL_NETWORK=192.168.0.0/16
    volumes:
      - ${TRANSMISSION_DATA_PATH}:/data
      - ${MOVIE_LIBRARY_PATH}/triage:/triage
    restart: on-failure
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
```

This correctly changed my IP address to one in another country.

**Comment by haugene** [comment]
@nicbou Well, you have a `...` block there that I don't know the contents of. But assuming that is mostly about transmission config options then everything looks good to me. The most important part is that LOCAL_NETWORK does not include a range that includes public IPs. You could have some DNS leaks though. That depends on how the Docker daemon routes your DNS and if an address within your LOCAL_NETWORK is set as dns server.

You can use the OVERRIDE_DNS options [described here](https://haugene.github.io/docker-transmission-openvpn/faq/#error_resolving_host_address) to not allow Docker to handle your DNS but set it explicitly for yourself. This has the downside that you lose inter-container dns from this container but that is not something you need unless you have a more advanced setup. Most setups have other services contacting Transmission and not the other way around, other services will still be able to resolve this container through DNS in a docker network.

**Comment by lucasbanting** [comment]
I still have this same issue on raspberry pi 4, running raspbian 10:

`transmission            | 2023-01-06 16:59:08 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
transmission            | 2023-01-06 16:59:08 Exiting due to fatal error`

Here is my docker compose, not much different than the other containers here:

`version: '3.3'
services:
    transmission-openvpn:
        container_name: 'transmission'
        privileged: true
        cap_add:
            - NET_ADMIN
        volumes:
            - /mnt/torrents/downloading:/data
            - /home/pi/apps/docker/transmission/config:/config
        devices:
            - /dev/net/tun
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        environment:
            - OPENVPN_PROVIDER=PROTONVPN
            - OPENVPN_CONFIG=is.protonvpn.net.udp
            - OPENVPN_USERNAME=xx
            - OPENVPN_PASSWORD=xx
            - LOCAL_NETWORK=192.168.0.0/16
            - TZ=yy
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        image: haugene/transmission-openvpn:latest`
