### ISSUE TITLE
V3 - NORDVPN Not Connecting

### ISSUE THREAD

**Issue by Evaske** [haugene/docker-transmission-openvpn#1510]
Hi,

Had this setup working fine for months. It obviously upgraded to V3 and now I can no longer connect to any trackers using NORDVPN.

As soon as I revert back to 2.14 my downloads start again.

What changed between 2.14 and V3 that I need to be aware of related to NORDVPN?

Thanks

**Comment by haugene** [comment]
I think we're trying to figure this out now. The container connects to NordVPN and you can access Transmission, but you can't connect to trackers? See #1507 and let's follow up there.

There shouldn't be any changes to NordVPN specifically. But there is a change in base os (from ubuntu to alpine) and possible some setup and packages around that. Is it OK if we close this for now and use the other thread?

**Comment by Evaske** [comment]
Yeah sounds like the same issue :)
