### ISSUE TITLE
 OpenVPN credentials not set. Exiting with Privado on a QNAP

### ISSUE THREAD

**Issue by garylzimmer** [haugene/docker-transmission-openvpn#1516]
**Describe the problem**

I'm getting this error in my log.
`OpenVPN credentials not set. Exiting.
`
I have a QNAP (see below) and I read about the daemon issues. I believe I did everything to solve that issue, but I think that would cause a separate issue anyway.

**Add your docker run command**
```

          docker run --cap-add=NET_ADMIN -d \
          --name=transmission \
          -v /share/CACHEDEV2_DATA/Download:/data \
          -v /etc/localtime:/etc/localtime:ro \
          -e CREATE_TUN_DEVICE=true \
          -e OPENVPN_PROVIDER=PRIVADO \
          -e OPENVPN_CONFIG=dub-001 \
          -e OPENVPN_USERNAME=USERNAME\
          -e OPENVPN_PASSWORD=PASSWORD \
          -e WEBPROXY_ENABLED=false \
          -e LOCAL_NETWORK=192.168.1.0/24 \
          --log-driver json-file \
          --log-opt max-size=10m \
          -p 9091:9091 \
          haugene/transmission-openvpn
```

**Logs**
```
Using OpenVPN provider: PRIVADO

Starting OpenVPN using config dub001.ovpn

OpenVPN credentials not set. Exiting.
```

**Host system:**
QNAP TS-251

**Comment by haugene** [comment]
Very strange. What do you get if you actually just run this (not put in your own username/password):
```
 docker run --rm --cap-add=NET_ADMIN \
          -e OPENVPN_PROVIDER=PRIVADO \
          -e OPENVPN_USERNAME=USERNAME \
          -e OPENVPN_PASSWORD=PASSWORD \
          -p 9091:9091 \
          haugene/transmission-openvpn
```

And do a `docker pull haugene/transmission-openvpn` first. You seem to be running an old version.

**Comment by garylzimmer** [comment]
Thanks for your quick response!
So when I paste the docker run command in, I get this weird error.
'''           -e OPENVPN_PASSWORD=PASSWORD \
-sh: PASSWORD: event not found'''
But when I run it, I get the same error as above.

**Comment by garylzimmer** [comment]
Okay, I added the quotes around the original command and it seems to work fine now. Didn't know weird passwords could have that effect!
