### ISSUE TITLE
(http://localhost:9091/transmission/rpc/) Couldn't connect to server

### ISSUE THREAD

**Issue by albatross1** [haugene/docker-transmission-openvpn#1517]
This was working with no issues for so long. I updated the docker image an now I"m getting "Couldn't connect to server" no matter what I do. I can't get this to work, any suggestions of wait I can do to fix this issue?

Countless people have the issue, an I use each one of their fixes, whether it's changing the local network to changing the Transmission_UnMask to 2. Still having this issue.

Below are my environmental an to follow the log that outputs. Any help would be appreciated.

<<<<<<<<Environmentals>>>>>>>>> for my docker image in Portainer.

`TRANSMISSION_ALT_SPEED_UP 	15
CREATE_TUN_DEVICE 	true
OPENVPN_PASSWORD 	[Password]
TRANSMISSION_BLOCKLIST_ENABLED 	true
TRANSMISSION_ALT_SPEED_DOWN 	2000
TRANSMISSION_BLOCKLIST_URL 	http://john.bitsurge.net/public/biglist.p2p.gz
WEBPROXY_ENABLED 	true
TRANSMISSION_SPEED_LIMIT_UP_ENABLED 	false
OPENVPN_USERNAME 	[Username]
WEBPROXY_PORT 	8888
TRANSMISSION_UMASK 	2
TRANSMISSION_INCOMPLETE_DIR 	/mnt/incomplete/transmission-vpn
TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED 	false
TRANSMISSION_RATIO_LIMIT_ENABLED 	true
OPENVPN_CONFIG 	Denmark
TRANSMISSION_HOME 	/config/home
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED 	false
PGID 	1000
LOCAL_NETWORK 	192.168.0.0/24
TRANSMISSION_WATCH_DIR_ENABLED 	false
TRANSMISSION_DOWNLOAD_DIR 	/mnt/downloads/transmission-vpn
TRANSMISSION_RPC_PORT 	9091
TRANSMISSION_WEB_UI 	combustion
UMASK_SET 	000
TRANSMISSION_WATCH_DIR 	/mnt/torrent/
TRANSMISSION_ALT_SPEED_ENABLED 	false
OPENVPN_OPTS 	--inactive 3600 --ping 10 --ping-exit 60
TRANSMISSION_INCOMPLETE_DIR_ENABLED 	true
TRANSMISSION_SPEED_LIMIT_DOWN 	6000
TRANSMISSION_DHT_ENABLED 	false
TRANSMISSION_RATIO_LIMIT 	1.01
PUID 	1000
TRANSMISSION_SPEED_LIMIT_UP 	30
OPENVPN_PROVIDER 	PIA
PATH 	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GLOBAL_APPLY_PERMISSIONS 	true
ENABLE_UFW 	false
UFW_ALLOW_GW_NET 	false
UFW_DISABLE_IPTABLES_REJECT 	false
LOG_TO_STDOUT 	false
HEALTH_CHECK_HOST 	google.com
REVISION 	93d0141d928ec661411e2c6f0e079aeff2c018dd
UFW_EXTRA_PORTS 	
DROP_DEFAULT_ROUTE 	
WEBPROXY_USERNAME 	
WEBPROXY_PASSWORD 	
Labels 	
autoheal 	true
org.opencontainers.image.revision 	93d0141d928ec661411e2c6f0e079aeff2c018dd
org.opencontainers.image.source 	https://github.com/haugene/docker-transmission-openvpn
traefik.enable 	true
traefik.frontend.auth.forward.address 	
traefik.frontend.headers.SSLHost 	[Sub-Domain]
traefik.frontend.headers.SSLRedirect 	true
traefik.frontend.headers.STSIncludeSubdomains 	true
traefik.frontend.headers.STSPreload 	true
traefik.frontend.headers.STSSeconds 	315360000
traefik.frontend.headers.browserXSSFilter 	true
traefik.frontend.headers.contentTypeNosniff 	true
traefik.frontend.headers.customResponseHeaders 	X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
traefik.frontend.headers.forceSTSHeader 	true
traefik.frontend.rule 	Host:[MySubdomain]
traefik.port 	9091

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Log >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Starting container with revision: 93d0141d928ec661411e2c6f0e079aeff2c018dd
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom startup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.AciCGE
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Modify configs for this container
Starting OpenVPN using config Denmark.ovpn
Setting OpenVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Sat Nov 14 22:04:48 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Sat Nov 14 22:04:48 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Sat Nov 14 22:04:48 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Nov 14 22:04:48 2020 CRL: loaded 1 CRLs from file [[INLINE]]
Sat Nov 14 22:04:48 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]188.126.94.171:1198
Sat Nov 14 22:04:48 2020 UDP link local: (not bound)
Sat Nov 14 22:04:48 2020 UDP link remote: [AF_INET]188.126.94.171:1198
Sat Nov 14 22:04:48 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Nov 14 22:04:48 2020 [copenhagen404] Peer Connection Initiated with [AF_INET]188.126.94.171:1198
Sat Nov 14 22:04:49 2020 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
Sat Nov 14 22:04:49 2020 OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3
Sat Nov 14 22:04:49 2020 TUN/TAP device tun0 opened
Sat Nov 14 22:04:49 2020 /sbin/ip link set dev tun0 up mtu 1500
Sat Nov 14 22:04:49 2020 /sbin/ip addr add dev tun0 10.9.112.184/24 broadcast 10.9.112.255
Sat Nov 14 22:04:49 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.9.112.184 255.255.255.0 init
Up script executed with tun0 1500 1553 10.9.112.184 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.9.112.184
Using Combustion UI, overriding TRANSMISSION_WEB_HOME
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /config/home/settings.json
Traceback (most recent call last):

File "/etc/transmission/updateSettings.py", line 45, in <module>
settings_dict = json.load(input_file)
File "/usr/lib/python3.8/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 68 column 15 (char 2230)
sed'ing True to true

Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1000:1000
Setting permission for files (644) and directories (755)
Setting permission for watch directory (775) and its files (664)

-------------------------------------

Transmission will run as

-------------------------------------

User name:   abc
User uid:    1000
User gid:    1000

-------------------------------------

STARTING TRANSMISSION

Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=yes
Transmission startup script complete.

STARTING TINYPROXY
Found config file /etc/tinyproxy/tinyproxy.conf, updating settings.
Setting tinyproxy port to 8888
[2020-11-14 22:04:49.643] JSON parse failed in /config/home/settings.json at pos 2230: INVALID_NUMBER -- remaining text "00,

"upload-"

tinyproxy is on the PATH, run it
WARNING: logging deactivated (can't log to stdout when daemonized)
Tinyproxy startup script complete.

Sat Nov 14 22:04:49 2020 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
Sat Nov 14 22:04:49 2020 Initialization Sequence Completed

yes: Broken pipe
port is 41536

the port has been bound to 41536  Sat Nov 14 22:04:55 CET 2020
transmission auth not required

waiting for transmission to become responsive

[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-14 22:04:55.721] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server`

**Comment by albatross1** [comment]
This was fixed by using the openvpn-nextgen PIA servers addresses.

**Comment by haugene** [comment]
Glad you got it working. Not sure if you've already done it, but since version 3.x you could clean up a lot of the environment variables as Transmission settings are not rewritten on restart as before. We also have an issue with decimal numbers in the Transmission settings so your TRANSMISSION_RATIO_LIMIT is causing an issue I see in the logs.

**Comment by albatross1** [comment]
Funny enough, I've gone back to have the same issue again. I'll try the
decimal point an move that.

**Comment by albatross1** [comment]
Still getting 


Transmission will run as


------------------------------------

User name:   abc
User uid:    1000
User gid:    1000

-------------------------------------



STARTING TRANSMISSION


Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=yes
Transmission startup script complete.


STARTING TINYPROXY
Found config file /etc/tinyproxy/tinyproxy.conf, updating settings.
Setting tinyproxy port to 8888
[2020-11-16 23:38:35.196] JSON parse failed in /config/home/settings.json at pos 2230: INVALID_NUMBER -- remaining text "00,


"upload-"


tinyproxy is on the PATH, run it
WARNING: logging deactivated (can't log to stdout when daemonized)
Tinyproxy startup script complete.


Mon Nov 16 23:38:35 2020 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.

Mon Nov 16 23:38:35 2020 Initialization Sequence Completed

yes: Broken pipe
port is 44439
the port has been bound to 44439  Mon Nov 16 23:38:41 CET 2020
transmission auth not required
waiting for transmission to become responsive


[2020-11-16 23:38:41.316] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-16 23:38:51.325] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-11-16 23:39:01.338] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server

**Comment by albatross1** [comment]
An the thing is, I've tried other locations lots of them, an the password for my PIA, its for the most part simply, with the weird char that would freak anything out.

**Comment by albatross1** [comment]
I've tried all the locations stated here [1495#](https://github.com/haugene/docker-transmission-openvpn/issues/1495#issuecomment-726388157)

**Comment by clement-z** [comment]
The VPN server is not the issue, or at least not anymore. When you look at other issues, don't blindly try the solutions but check whether it applies to you (same messages, similar configuration, etc). Otherwise you will bring more and more problems.

The problem is that your `settings.json` is invalid and transmission cannot start.

Can you post your `settings.json` here? I could reproduce a similar issue by changing

```json
"umask": 2,
```

to 

```json
"umask": 2,00,
```

In any case, it will be easy to locate the wrong line in `settings.json`  so paste it here (attach it to your message).

**Comment by clement-z** [comment]
#1210

**Comment by haugene** [comment]
:point_up: what he said. But also. Try running a more minimal setup. Start with only defining OPENVPN_PROVIDER, OPENVPN_CONFIG, OPENVPN_USERNAME, OPENVPN_PASSWORD and work from there. You don't even have to mount any volumes. Just see from the logs if it starts correctly and if the logs have fewer errors. Then you can add LOCAL_NETWORK and try to access the UI. If that seems to work fine then try to mount your disk again - possibly moving transmission-home out of the way so that it can start from a fresh settings.json file.

If you gradually rebuild you might find where the error comes from.

**Comment by albatross1** [comment]
Sounds good, let me try that. I'll report back! Thank you!

**Comment by albatross1** [comment]
Sadly, I'm not sure what fixed it the most. I deleted the settings.json file so it would rebuild based on enviro, that changed my error, next I took @haugene advice, and simply slimmed down my setup, with very minimal environmentals and bam. That worked. I had something messed up, but I slowly added stuff back an it's solid now.

THANK YOU BOTH!  @clement-z & @haugene I love this setup.

**Comment by ritaashiego533-ops** [comment]
I hate this
