### ISSUE TITLE
How to upgrade docker without loosing torrents

### ISSUE THREAD

**Issue by vchatela** [haugene/docker-transmission-openvpn#1519]
Hi,
Could you please define the path that can be mount into the docker to save the configuration of the transmission (like a /config).
Because while trying to upgrade docker, I clean and mount a new version but all torrent and configuration is lost..
Thanks for that amazing docker !
Valentin

**Comment by mouzzampk2014** [comment]
@vchatela should be by default, but you need one environment variable and you also need to create a config. Ta
```
    environment:
      - TRANSMISSION_HOME=/config
```
```
    volumes:
      - ${DOCKERCONFDIR}/transmissionvpn:/config
```

**Comment by vchatela** [comment]
I hadn't even thought of the TRANSMISSION_HOME .. Thank you a lot @mouzzampk2014 I'll try !

**Comment by haugene** [comment]
Transmission home is by default set to /data/transmission-home so mounting /data should also suffice.
We're using the /config directory today to store some pretty temporary content with the `/config/openvpn-credentials.txt` (as it is rewritten on each start).

But yeah. You can set the transmission home to `/whatever` and then mount /whatever

**Comment by vchatela** [comment]
Indeed I saw the default TRANSMISSION_HOME value after mouzzampk2014 gave me the insight. Clear for me thanks a lot for all of your work!
