### ISSUE TITLE
Allow password authentication

### ISSUE THREAD

**Issue by cgrima** [haugene/docker-transmission-openvpn#152]
Activation of the username/password authentication is done in the transmission/settings.json file. However, Transmission reset this file automatically when the container is restarted. Currently, we have to stop the daemon, change the settings.json file, and start the daemon manually from within the container to use authentication.
Would be nice to implement a way to activate and set username/password authentication through docker environments.

PS: you work is awesome!

**Comment by logaritmisk** [comment]
I think you can set authentication details with environment options.
Check out https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile for available options and their default values.

**Comment by cgrima** [comment]
Nevermind, you're right. the dockerfile enables to tweak all the settings.json variable.
