### ISSUE TITLE
NordVPN is not working

### ISSUE THREAD

**Issue by roysubs** [haugene/docker-transmission-openvpn#1524]
**Which provider?**
NordVPN

**Where are the configs?**
I don't have the .ovpn for this, but we were trying to use my working credentials and it just throws errors. It looks like one of your standard supported VPN's (and it is a major VPN) so I was hoping that you already know where to get the latest details to update this?

**Comment by ilike2burnthing** [comment]
https://haugene.github.io/docker-transmission-openvpn/nordvpn-script/
