### ISSUE TITLE
Container not starting when using IPVanish

### ISSUE THREAD

**Issue by avDownloads** [haugene/docker-transmission-openvpn#1526]
Trying to run the container using IPVanish as my VPN. Running the container under unraid, fresh installation. Version 2.14 was running OK (and in fact I can deploy that without issue).

It appears to hang during the initial setup of openvpn

Run command (via unraid):
```
docker run -d --name='Transmission_VPN' --net='bridge' --privileged=true \
  -e TZ="UTC" -e HOST_OS="Unraid" -e 'OPENVPN_USERNAME'='<myusername>' \
  -e 'OPENVPN_PASSWORD'='<mypassword>' -e 'OPENVPN_CONFIG'='ipvanish-IE-Dublin-dub-c04' \
  -e 'OPENVPN_PROVIDER'='IPVANISH' -e 'LOCAL_NETWORK'='192.168.20.0/24' \
  -e 'TRANSMISSION_RPC_USERNAME'='admin' -e 'TRANSMISSION_RPC_PASSWORD'='password' \
  -e 'OPENVPN_OPTS'='--inactive 3600 --ping 10 --ping-exit 60' -e 'PUID'='99' -e 'PGID'='100' \
  -e 'TRANSMISSION_DOWNLOAD_DIR'='/downloads' -e 'TRANSMISSION_RPC_AUTHENTICATION_REQUIRED'='true' \
  -e 'TRANSMISSION_RATIO_LIMIT'='1.1' -e 'TRANSMISSION_RATIO_LIMIT_ENABLED'='true' \
  -e 'TRANSMISSION_DOWNLOAD_QUEUE_SIZE'='15' -e 'TRANSMISSION_CACHE_SIZE_MB'='10' \
  -e 'TRANSMISSION_INCOMPLETE_DIR'='/downloads/incomplete' -e 'TRANSMISSION_WEB_UI'='transmission-web-control' \
  -e 'GLOBAL_APPLY_PERMISSIONS'='false' -p '9091:9091/tcp' \
  -p '1198:1198/udp' -v '/mnt/user/T_Media/Torrent/':'/data':'rw' -v '/mnt/user/T_Media/Torrent/':'/downloads':'rw' \
  -v '/mnt/user/T_Media/Torrent/watch/':'/watch':'rw' -v '/mnt/user/T_Media/Torrent/':'/mnt/user/T_Media/Torrent/':'rw' \
  -v '/mnt/user/appdata/Transmission_VPN':'/config':'rw' --restart=always --log-opt max-size=50m \
  --log-opt max-file=1 'haugene/transmission-openvpn' 
```

Logs:
```
Starting container with revision: 4b72fa07ca3258f9226c27726c0cbe8ce5e127f5
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom startup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.afanje
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
Modify configs for this container
```

Host System:
Unraid 6.8.3

I believe the issue lies with the number of ovpn files - in the last line of 
https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/ipvanish/configure-openvpn.sh

`find "$VPN_PROVIDER_HOME" -type f -name "*.ovpn" -print0 | xargs -n 1 -r0 /etc/openvpn/modify-openvpn-config.sh`

This command hangs if I run it from the command line (replacing the variable with /etc/openvpn/ipvanish. 

Any ideas?

**Comment by rdfedor** [comment]
Try downloading the ipvanish configs.zip and check if a config exists in that zip w/ the OPENVPN_CONFIG name.  The project downloads the configs file and uses those from the ipvanish website.

**Comment by RickyXwang** [comment]
If there are many ovpn files, it might take a long time to process them all. 
There are 1594 ovpn files in that configs.zip. Need to update the code to only modify-openvpn-config that is required. @haugene

**Comment by haugene** [comment]
Aha. Yes, I've actually already done that: https://github.com/haugene/docker-transmission-openvpn/commit/c42e60cda031c612c9f572d87664f7dbdb9314fc but it's only on the `dev` branch/tag.
Merging to master now. Try pulling the image again and it should work :crossed_fingers:

**Comment by avDownloads** [comment]
Sorted! Thanks for fixing it so quickly too!
