### ISSUE TITLE
Docker freezes in Starting Sequence: Initialization Sequence Completed...

### ISSUE THREAD

**Issue by C0nvert** [haugene/docker-transmission-openvpn#1528]
System: Armlogic
OS: Coreelec with Docker

Docker Image freezes after: Initialization Sequence Completed

Uploaded log to this site:
https://paste.osmc.tv/raw/wocesoduxi

used these comments with Nordvpn as Provider

```
docker run --cap-add=NET_ADMIN -d \
              -v /your/storage/path/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=NORDVPN \
              -e OPENVPN_USERNAME=user \
              -e OPENVPN_PASSWORD=pass \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.0.0/24 \
              --log-driver json-file \
              -p 9091:9091 \
              haugene/transmission-openvpn
```

**Comment by C0nvert** [comment]
I got this working as a Stack in Portainer.
But container shows as healthy. 
How can i fix this?

**Comment by Americanzer0** [comment]
I am having similar issues when using Mullvad VPN; stuck at:

`STARTING TRANSMISSION
Transmission startup script complete.
Wed Nov 18 11:25:30 2020 /sbin/ip route add 185.65.134.147/32 via 172.17.0.1
Wed Nov 18 11:25:30 2020 /sbin/ip route add 0.0.0.0/1 via 10.9.0.1
Wed Nov 18 11:25:30 2020 /sbin/ip route add 128.0.0.0/1 via 10.9.0.1
Wed Nov 18 11:25:30 2020 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
Wed Nov 18 11:25:30 2020 Initialization Sequence Completed`

cannot access the web gui even though it appears to be ready to...

**Comment by haugene** [comment]
@C0nvert It looks to me like it works as intended. What is your IP though? The 192.168.1.x is much more common than 192.168.0.x space so I'm wondering if you have configured LOCAL_NETWORK wrong? If client your IP is 192.168.1.x then `LOCAL_NETWORK=192.168.1.0/24` is correct. If you want to catch them both you can do `LOCAL_NETWORK=192.168.0.0/16`

**Comment by haugene** [comment]
The same might go for you  @Americanzer0. If you're wondering about the whole LOCAL_NETWORK stuff, read my comment here https://github.com/haugene/docker-transmission-openvpn/issues/1334#issuecomment-726398297 and ask if it's still unclear.

It's also documented here: https://haugene.github.io/docker-transmission-openvpn/access/

**Comment by Americanzer0** [comment]
I was able to get transmission up and running, now I am running into needing to whitelist my IP address apparently...

I am by far a much more hardware orientated person than coding, and it's mildly frustrating to recognize your own shortcomings on trouble shooting these issues, more so when your transitioning from a Synology setup that ran without issues for years on PIA and now on Unraid everything seems to be broken (I swapped over to unraid right as PIA did their thing doing away with legacy support)....

**Comment by C0nvert** [comment]
I was able to fix it through Docker compose 
Configured it as a stack in portain.

My local network ist 192.168.80.X

**Comment by haugene** [comment]
@C0nvert Glad you got it working. And thanks for your contribution. Much appreciated 🍻

As for your docker ssh command, it looks good to me. That should work. With the right LOCAL_NETWORK of course and changing /your/storage/path for a real one.
