### ISSUE TITLE
Best setup for this docker container

### ISSUE THREAD

**Issue by eephrati** [haugene/docker-transmission-openvpn#153]
Anyone who has no problems whatsoever with this container, what are your setups? Ubuntu? MacOS? Windows?

While waiting for Mac Docker to work better, I am going to go with VirtualBox + Vagrant and go with the best VM.

I tried a lightweight Linux distribution built with Buildroot apparently to run specifically Docker containers. It works... but lags a lot when the download occurs.

any advices welcome!

**Comment by pkishino** [comment]
Since updating to the beta branch of MacDocker ive got no problems, stable and fast with latest release
