### ISSUE TITLE
yes: broken pipe error

### ISSUE THREAD

**Issue by clement-z** [haugene/docker-transmission-openvpn#1532]
Since 56a6a6f6196, the PIA port forwarding script (always?) prints a `yes: Broken pipe` message, which often confuses people reporting issues.

From what I can see, it is just stemming from this:

https://github.com/haugene/docker-transmission-openvpn/blob/baed33520630e88ba34842cab05f2cd3fd6cf28f/openvpn/pia/update-port.sh#L39

This essentially is equivalent to `echo -e "\n\n\n"`. I don't think it serves any other purpose. Can we delete it?

**Comment by haugene** [comment]
Great catch :+1:  I've seen this in the logs as well, but have postponed checking out why. I expected there to be some other error involved. Merging now, this line has to go :smile:
