### ISSUE TITLE
Support WeVPN Please :)

### ISSUE THREAD

**Issue by arnonel** [haugene/docker-transmission-openvpn#1535]
Hi there

Could you support https://wevpn.com/ please?

**Comment by steve-spiteri** [comment]
It would be possible to put together pull request but whoever undertakes the task would need the crt/key and all the combinations of the .ovpn files.

They can be created but you need to be a member to access the generator.
https://wevpn.com/support/hc/en-us/articles/360051965093-Generating-OVPN-files
