### ISSUE TITLE
Add support for Njalla

### ISSUE THREAD

**Issue by Gyppie** [haugene/docker-transmission-openvpn#1538]
Hi,

Could you please add support for njalla? Or has anyone got it to work?

Stein

**Comment by haugene** [comment]
Hi there. See #1491 
It seems Njalla uses key auth and that the key is included in the .ovpn configs that you download. They can therefore not be embedded into this image.
You can use the config-url method outlined in my reply in the other thread or use the instructions for running with a custom provider: https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_custom_provider
