### ISSUE TITLE
Transmission RPC Whitelist

### ISSUE THREAD

**Issue by JohnPTobe** [haugene/docker-transmission-openvpn#1540]
**Describe the problem**
The existing docker-compose doesn't work because it tries to talk to transmission using its hostname but transmission responds with an error because that hostname isn't in the whitelist and is blocked for security reasons.

**Add your docker run command**
I ran it using the sample compose (with my account settings, etc)

**Logs**
don't have the logs but the error was transmission-rss was unable to get the session id with a 429 error code

**Host system:**
synology

**Comment by JohnPTobe** [comment]
I fixed the issue by adding this environment variable: 
- TRANSMISSION_RPC_HOST_WHITELIST=transmission

I don't know if this is a better fix or whether the config should be updated directly.

**Comment by haugene** [comment]
Hey. Thanks for reporting this and sorry about the late reply. It's good that you got it working and we might add another default entry, or maybe a note in the documentation. But this shouldn't happen with the default settings? The rpc-host-whitelist is disabled by default: https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/default-settings.json#L47

Have you enabled it? You're running the latest version? Have you been running the container for a long time? Could you try to stop the container, remove the settings.json file (or back it up somewhere) and then restart it and see if it works then? If it works -  check the difference between the old and new config. We're seeing multiple errors these days where re-creating the settings file fixes the issue. Trying to get to the bottom of why :)

**Comment by JohnPTobe** [comment]
Ok, I think I found the problem. I switched to this docker image after PIA updated recently and the docker image I had previously been using (sol23/docker-transmission-openvpn-rss) stopped working.  I mounted the same directory structure I had been using with that image and the settings file it picked up had it enabled when I checked just now.
