### ISSUE TITLE
Anyone else getting INACTIVITY TIMEOUT on v2.14?

### ISSUE THREAD

**Issue by superkrups20056** [haugene/docker-transmission-openvpn#1545]
It was working perfectly until this morning. Happening to a friend of mine as well.  Both using PIA. I tried 8 different servers. Port forwarding is enabled. We are both using docker on Synology devices.

**Comment by RickyXwang** [comment]
Will need more information to debug. Your startup setting. Which provider? How's the log look like, etc.

**Comment by superkrups20056** [comment]
@RickyXwang I can tell you, but it's probably not my startup settings as it was working for the past months with these settings without issue. Honestly it is probably server side because it is happening to my friend as well and we have similar setups, albeit different synology devices. In any case, here they are:

**_LOG:_**
  
      
Starting OpenVPN using config Sweden.ovpn


Setting OPENVPN credentials...


adding route to local network 192.168.56.0/24 via 172.17.0.1 dev eth0


Mon Nov 23 22:49:51 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020


Mon Nov 23 22:49:51 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10


Mon Nov 23 22:49:51 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts


Mon Nov 23 22:49:56 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]46.246.3.253:1198


Mon Nov 23 22:49:56 2020 UDP link local: (not bound)


Mon Nov 23 22:49:56 2020 UDP link remote: [AF_INET]46.246.3.253:1198


Mon Nov 23 22:50:56 2020 [UNDEF] Inactivity timeout (--ping-exit), exiting


Mon Nov 23 22:50:56 2020 SIGTERM[soft,ping-exit] received, process exiting


Using OpenVPN provider: PIA


8 servers found in OPENVPN_CONFIG, France chosen randomly


Starting OpenVPN using config France.ovpn


Setting OPENVPN credentials...


adding route to local network 192.168.56.0/24 via 172.17.0.1 dev eth0


Mon Nov 23 22:50:57 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020


Mon Nov 23 22:50:57 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10


Mon Nov 23 22:50:57 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts


Mon Nov 23 22:51:02 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]156.146.63.65:1198


Mon Nov 23 22:51:02 2020 UDP link local: (not bound)


Mon Nov 23 22:51:02 2020 UDP link remote: [AF_INET]156.146.63.65:1198


Mon Nov 23 22:52:02 2020 [UNDEF] Inactivity timeout (--ping-exit), exiting


Mon Nov 23 22:52:02 2020 SIGTERM[soft,ping-exit] received, process exiting


Using OpenVPN provider: PIA


8 servers found in OPENVPN_CONFIG, France chosen randomly


Starting OpenVPN using config France.ovpn


Setting OPENVPN credentials...


adding route to local network 192.168.56.0/24 via 172.17.0.1 dev eth0


Mon Nov 23 22:52:04 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020


Mon Nov 23 22:52:04 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10


Mon Nov 23 22:52:04 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts


Mon Nov 23 22:52:09 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]156.146.63.1:1198


Mon Nov 23 22:52:09 2020 UDP link local: (not bound)


Mon Nov 23 22:52:09 2020 UDP link remote: [AF_INET]156.146.63.1:1198


Mon Nov 23 22:53:09 2020 [UNDEF] Inactivity timeout (--ping-exit), exiting


Mon Nov 23 22:53:09 2020 SIGTERM[soft,ping-exit] received, process exiting


Using OpenVPN provider: PIA


8 servers found in OPENVPN_CONFIG, Denmark chosen randomly


Starting OpenVPN using config Denmark.ovpn


Setting OPENVPN credentials...


adding route to local network 192.168.56.0/24 via 172.17.0.1 dev eth0


Mon Nov 23 22:53:11 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020


Mon Nov 23 22:53:11 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10


Mon Nov 23 22:53:11 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts


Mon Nov 23 22:53:16 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]188.126.94.34:1198


Mon Nov 23 22:53:16 2020 UDP link local: (not bound)


Mon Nov 23 22:53:16 2020 UDP link remote: [AF_INET]188.126.94.34:1198


Mon Nov 23 22:54:16 2020 [UNDEF] Inactivity timeout (--ping-exit), exiting


Mon Nov 23 22:54:16 2020 SIGTERM[soft,ping-exit] received, process exiting


Using OpenVPN provider: PIA


8 servers found in OPENVPN_CONFIG, Ireland chosen randomly


Starting OpenVPN using config Ireland.ovpn


Setting OPENVPN credentials...


adding route to local network 192.168.56.0/24 via 172.17.0.1 dev eth0


Mon Nov 23 22:54:18 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020


Mon Nov 23 22:54:18 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10


Mon Nov 23 22:54:18 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts


Mon Nov 23 22:54:23 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]193.56.252.252:1198


Mon Nov 23 22:54:23 2020 UDP link local: (not bound)


Mon Nov 23 22:54:23 2020 UDP link remote: [AF_INET]193.56.252.252:1198


Mon Nov 23 22:54:23 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this


Mon Nov 23 22:54:26 2020 [dublin408] Peer Connection Initiated with [AF_INET]193.56.252.252:1198


Mon Nov 23 22:54:27 2020 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options


Mon Nov 23 22:54:27 2020 OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3


Mon Nov 23 22:54:27 2020 TUN/TAP device tun0 opened


Mon Nov 23 22:54:27 2020 /sbin/ip link set dev tun0 up mtu 1500


Mon Nov 23 22:54:27 2020 /sbin/ip addr add dev tun0 10.10.112.156/24 broadcast 10.10.112.255


Mon Nov 23 22:54:27 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.10.112.156 255.255.255.0 init


Up script executed with tun0 1500 1553 10.10.112.156 255.255.255.0 init


Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.10.112.156


Using Transmission Web Control  UI, overriding TRANSMISSION_WEB_HOME


Generating transmission settings.json from env variables


sed'ing True to true


Enforcing ownership on transmission config directories


Applying permissions to transmission config directories


Setting owner for transmission paths to 1027:100


Setting permission for files (644) and directories (755)


Setting permission for watch directory (775) and its files (664)




-------------------------------------


Transmission will run as


-------------------------------------


User name:   abc


User uid:    1027


User gid:    100


-------------------------------------




STARTING TRANSMISSION


CONFIGURING PORT FORWARDING


Transmission startup script complete.


Wait for tunnel to be fully initialized and PIA is ready to give us a port


Mon Nov 23 22:54:27 2020 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.


Mon Nov 23 22:54:27 2020 Initialization Sequence Completed


Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding


curl encountered an error looking up new port: 7


Mon Nov 23 22:54:49 2020 event_wait : Interrupted system call (code=4)


Mon Nov 23 22:54:49 2020 /sbin/ip addr del dev tun0 10.10.112.156/24


Mon Nov 23 22:54:49 2020 /etc/openvpn/tunnelDown.sh tun0 1500 1553 10.10.112.156 255.255.255.0 init


Mon Nov 23 22:54:49 2020 SIGTERM[hard,] received, process exiting

**_SETTINGS:_**

PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-- | --
DEBIAN_FRONTEND | noninteractive
OPENVPN_USERNAME | HIDDEN
OPENVPN_PASSWORD | HIDDEN
OPENVPN_PROVIDER | PIA
GLOBAL_APPLY_PERMISSIONS | true
TRANSMISSION_ALT_SPEED_DOWN | 200
TRANSMISSION_ALT_SPEED_ENABLED | true
TRANSMISSION_ALT_SPEED_TIME_BEGIN | 945
TRANSMISSION_ALT_SPEED_TIME_DAY | 124
TRANSMISSION_ALT_SPEED_TIME_ENABLED | true
TRANSMISSION_ALT_SPEED_TIME_END | 1395
TRANSMISSION_ALT_SPEED_UP | 200
TRANSMISSION_BIND_ADDRESS_IPV4 | 0.0.0.0
TRANSMISSION_BIND_ADDRESS_IPV6 | ::
TRANSMISSION_BLOCKLIST_ENABLED | false
TRANSMISSION_BLOCKLIST_URL | http://www.example.com/blocklist
TRANSMISSION_CACHE_SIZE_MB | 4
TRANSMISSION_DHT_ENABLED | true
TRANSMISSION_DOWNLOAD_DIR | /data/torrents
TRANSMISSION_DOWNLOAD_LIMIT | 100
TRANSMISSION_DOWNLOAD_LIMIT_ENABLED | 0
TRANSMISSION_DOWNLOAD_QUEUE_ENABLED | true
TRANSMISSION_DOWNLOAD_QUEUE_SIZE | 6
TRANSMISSION_ENCRYPTION | 1
TRANSMISSION_IDLE_SEEDING_LIMIT | 30
TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED | false
TRANSMISSION_INCOMPLETE_DIR | /data/torrents/incomplete
TRANSMISSION_INCOMPLETE_DIR_ENABLED | false
TRANSMISSION_LPD_ENABLED | false
TRANSMISSION_MAX_PEERS_GLOBAL | 200
TRANSMISSION_MESSAGE_LEVEL | 2
TRANSMISSION_PEER_CONGESTION_ALGORITHM |  
TRANSMISSION_PEER_ID_TTL_HOURS | 6
TRANSMISSION_PEER_LIMIT_GLOBAL | 200
TRANSMISSION_PEER_LIMIT_PER_TORRENT | 50
TRANSMISSION_PEER_PORT | 51413
TRANSMISSION_PEER_PORT_RANDOM_HIGH | 65535
TRANSMISSION_PEER_PORT_RANDOM_LOW | 49152
TRANSMISSION_PEER_PORT_RANDOM_ON_START | false
TRANSMISSION_PEER_SOCKET_TOS | default
TRANSMISSION_PEX_ENABLED | true
TRANSMISSION_PORT_FORWARDING_ENABLED | true
TRANSMISSION_PREALLOCATION | 1
TRANSMISSION_PREFETCH_ENABLED | 1
TRANSMISSION_QUEUE_STALLED_ENABLED | true
TRANSMISSION_QUEUE_STALLED_MINUTES | 30
TRANSMISSION_RATIO_LIMIT | 2
TRANSMISSION_RATIO_LIMIT_ENABLED | false
TRANSMISSION_RENAME_PARTIAL_FILES | false
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED | false
TRANSMISSION_RPC_BIND_ADDRESS | 0.0.0.0
TRANSMISSION_RPC_ENABLED | true
TRANSMISSION_RPC_HOST_WHITELIST |  
TRANSMISSION_RPC_HOST_WHITELIST_ENABLED | false
TRANSMISSION_RPC_PASSWORD | password
TRANSMISSION_RPC_PORT | 9091
TRANSMISSION_RPC_URL | /transmission/
TRANSMISSION_RPC_USERNAME | username
TRANSMISSION_RPC_WHITELIST | 127.0.0.1
TRANSMISSION_RPC_WHITELIST_ENABLED | false
TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED | false
TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED | false
TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME |  
TRANSMISSION_SEED_QUEUE_ENABLED | false
TRANSMISSION_SEED_QUEUE_SIZE | 10
TRANSMISSION_SPEED_LIMIT_DOWN | 100
TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED | false
TRANSMISSION_SPEED_LIMIT_UP | 100
TRANSMISSION_SPEED_LIMIT_UP_ENABLED | false
TRANSMISSION_START_ADDED_TORRENTS | true
TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES | false
TRANSMISSION_UMASK | 22
TRANSMISSION_UPLOAD_LIMIT | 100
TRANSMISSION_UPLOAD_LIMIT_ENABLED | 0
TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT | 14
TRANSMISSION_UTP_ENABLED | false
TRANSMISSION_WATCH_DIR | /data/torrents/watch
TRANSMISSION_WATCH_DIR_ENABLED | true
TRANSMISSION_HOME | /data/transmission-home
TRANSMISSION_WATCH_DIR_FORCE_GENERIC | false
ENABLE_UFW | false
UFW_ALLOW_GW_NET | false
UFW_EXTRA_PORTS |  
UFW_DISABLE_IPTABLES_REJECT | false
TRANSMISSION_WEB_UI | transmission-web-control
PUID | 1027
PGID | 100
TRANSMISSION_WEB_HOME |  
DROP_DEFAULT_ROUTE |  
WEBPROXY_ENABLED | false
WEBPROXY_PORT | 8888
WEBPROXY_USERNAME |  
WEBPROXY_PASSWORD |  
HEALTH_CHECK_HOST | google.com
DOCKER_LOG | false
LOG_TO_STDOUT | false
LOCAL_NETWORK | 192.168.56.0/24
OPENVPN_CONFIG | Israel
OPENVPN_OPTS | --inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping

**Comment by ohbigun** [comment]
Isn't just Synology. Mine is doing the same thing within Docker on OpenMediaVault. PIA seems to be the common denominator (imagine that). 

Using OpenVPN provider: pia
Starting OpenVPN using config CA Toronto.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Mon Nov 23 20:48:59 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Mon Nov 23 20:48:59 2020 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Nov 23 20:48:59 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Nov 23 20:48:59 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]66.115.145.199:1198
Mon Nov 23 20:48:59 2020 UDP link local: (not bound)
Mon Nov 23 20:48:59 2020 UDP link remote: [AF_INET]66.115.145.199:1198
Mon Nov 23 20:49:59 2020 Inactivity timeout (--inactive), exiting
Mon Nov 23 20:49:59 2020 SIGTERM[soft,inactive] received, process exiting

**Comment by paulstride** [comment]
I'm also seeing this.  Could I am guessing it is related to this? https://www.privateinternetaccess.com/blog/private-internet-access-legacy-vpn-network-sunset-announcement-30-september

**Comment by superkrups20056** [comment]
@obhigun @paulstride Have you got it working? Does it work on 3.2? Is that our only option at this point?

**Comment by superkrups20056** [comment]
@paulstride I thought 2.14 was updated to support the next gen servers...

**Comment by paulstride** [comment]
> @ohbigun @paulstride Have you got it working? Does it work on 3.2? Is that our only option at this point?

I've just updated to 3.2 and after some minor config changes it's all good.

**Comment by superkrups20056** [comment]
> > @ohbigun @paulstride Have you got it working? Does it work on 3.2? Is that our only option at this point?
> 
> I've just updated to 3.2 and after some minor config changes it's all good.

How were you able to carry all your seedings to 3.2????

**Comment by paulstride** [comment]
> @paulstride did you include the OPTS environmental variable or something similar when you carried it over? It still is not working for me, I've tried copying my env variables exactly but it keeps crashing.

I left OPENVPN_OPTS the same ... --inactive 3600 --ping 10 --ping-exit 60

I had to delete TRANSMISSION_WEB_HOME which I previously had as empty and I had to change OPENVPN_CONFIG to a new end point.  The log outputted the possible options for this value.

**Comment by superkrups20056** [comment]
@paulstride, thanks I got it to work. Is there any way to boot it up while preserving all the seeding torrents from 2.14 so I don’t have to add anything?

Also, I think I found the reason. I think it’s because curl was recently disabled @haugene. 

https://reddit.com/r/PrivateInternetAccess/comments/k0mulx/idea_for_how_to_get_forwarded_port_in_next_gen/

Will we see a 2.15 on the horizon?

**Comment by superkrups20056** [comment]
@paulstride I figured out that i need the transmission-home folder to migrate to 3.x. I never mounted that folder so it looks like I'm out of luck and need to redownload everything again.
