### ISSUE TITLE
Transmission web UI won't load - Site can't be reached/refused to connect

### ISSUE THREAD

**Issue by d4real** [haugene/docker-transmission-openvpn#1549]
**Describe the problem**
 Over the past several weeks the Transmission web UI will not load with the error "Site can't be reached" and "ERR connection refused" on Chrome browser.  It looks like the issue started around Oct. 23rd as nothing has downloaded since that date in the transmission.log file.  Nothing has changed on my side so I'm assuming it has something to do with PIA.

**Add your docker run command**
 The container is spun up using a YAML config.  Please see the config below; I also tried setting DNS to Google's (8.8.8.8 & 8.8.4.4) but no change.

transmission-vpn:
      container_name: transmission-vpn
      image: haugene/transmission-openvpn
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun
      restart: always
      ports:
      - "9091:9091"
      dns:
        - 1.1.1.1
        - 1.0.0.1
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ${USERDIR}/docker/transmission-vpn:/data
        - ${USERDIR}/docker/shared:/shared
        - ${USERDIR}/Downloads:/data/watch
        - ${USERDIR}/Downloads/completed:/data/completed
        - ${USERDIR}/Downloads/incomplete:/data/incomplete
      environment:
        - OPENVPN_PROVIDER=PIA
        - OPENVPN_USERNAME=HIDDEN
        - OPENVPN_PASSWORD=HIDDEN
        - OPENVPN_CONFIG=US East
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - LOCAL_NETWORK=192.168.0.0/24
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
        - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.0.20"
        - TRANSMISSION_RPC_PASSWORD=HIDDEN
        - TRANSMISSION_RPC_USERNAME=HIDDEN
        - TRANSMISSION_UMASK=2
        - TRANSMISSION_RATIO_LIMIT=1.00
        - TRANSMISSION_RATIO_LIMIT_ENABLED=true

**Logs**
  The logs appear to just be spitting out the same few lines over and over again but I'm not sure what it means:

Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.KMiKEC
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
unzip: short read
Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.fPCaIn
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
unzip: short read
Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.pppAiO
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
unzip: short read
Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.CeInLJ
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
unzip: short read
Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.CdGjBM
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
unzip: short read
Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.JdbaOi
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
unzip: short read
Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.gojiPK
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
unzip: short read
Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.CcoCba
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
unzip: short read
Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.GdGENA
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
unzip: short read

**Host system:**
 Ubuntu server 16 is the host OS

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

Docker version:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by ganastor** [comment]
Ditto since I updated it:

Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.PHlBAO
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
unzip: short read
disconnected

**Comment by trowgundam** [comment]
This is due to a recent change by PIA. See my issue #1548 . There is a fix there for this.

**Comment by d4real** [comment]
> 
> 
> This is due to a recent change by PIA. See my issue #1548 . There is a fix there for this.

Thanks, that seems to be the fix for several people.  In the replies there I'm seeing: `- PIA_OPENVPN_CONFIG_BUNDLE=openvpn` but my environment file doesn't have that line, do I need to add it?  

I saw you noted also changing the OPENVPN_CONFIG= to ca_montreal, I assume mine would then be us_east.

**Comment by ganastor** [comment]
> This is due to a recent change by PIA. See my issue #1548 . There is a fix there for this.

Thanks, resolved it for me.

@d4real I'm in the US as well, I added this if it helps:

  -e PIA_OPENVPN_CONFIG_BUNDLE=openvpn \
  -e OPENVPN_CONFIG=us_west,us_texas,us_seattle,us_east,us_florida,us_chicago,us_atlanta, \

**Comment by d4real** [comment]
@trowgundam Disregard, I did need to add the `- PIA_OPENVPN_CONFIG_BUNDLE=openvpn` variable to the config file.  All good and working now.  I am able to load the Transmission web UI now, thanks for the help!

**Comment by haugene** [comment]
For future reference. This is not fixed on both dev and master branch after merging #1552 
Keeping PIA_OPENVPN_CONFIG_BUNDLE=openvpn does not hurt, but it is now the default value.
