### ISSUE TITLE
can't resolve after restart on Synology

### ISSUE THREAD

**Issue by rogstro** [haugene/docker-transmission-openvpn#155]
After connection drop the VPN can´t resolve OVPN provider
My config looks like this:
docker run --privileged -d -v /volume1/transdock/resolv.conf:/etc/resolv.conf -v /volume1/transmission/:/data --restart=always --dns 8.8.8.8 --dns 8.8.4.4 -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" -e "OPENVPN_PROVIDER=OVPN" -e "OPENVPN_CONFIG=Sweden" -e "OPENVPN_USERNAME=***_" -e "OPENVPN_PASSWORD=**_**" -e "LOCAL_NETWORK=192.168.1.0/24"

And the logfile shows this:
Tue Oct 18 17:39:42 2016 us=355097 PID_ERR replay-window backtrack occurred [1] [SSL-0] [0_0000011111111111112222222222222233333333333444444444444444444555555555555555555666667777777777777777888888888888888899999999999999999999&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;
stdout
21:30:01
Tue Oct 18 21:30:01 2016 us=287195 PID_ERR replay-window backtrack occurred [2] [SSL-0] [0__0000000000022223333333344444444555555566666666777777777888888888899999999999&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
stdout
22:18:41
Tue Oct 18 22:18:41 2016 us=297648 [ovpn.se] Inactivity timeout (--ping-restart), restarting
stdout
22:18:41
Tue Oct 18 22:18:41 2016 us=298016 TCP/UDP: Closing socket
stdout
22:18:41
Tue Oct 18 22:18:41 2016 us=298126 SIGUSR1[soft,ping-restart] received, process restarting
stdout
22:18:41
Tue Oct 18 22:18:41 2016 us=298191 Restart pause, 2 second(s)
stdout
22:18:43
Tue Oct 18 22:18:43 2016 us=298644 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
stdout
22:18:43
Tue Oct 18 22:18:43 2016 us=298744 Re-using SSL/TLS context
stdout
22:18:43
Tue Oct 18 22:18:43 2016 us=298826 LZO compression initialized
stdout
22:18:43
Tue Oct 18 22:18:43 2016 us=298953 Control Channel MTU parms [ L:1558 D:166 EF:66 EB:0 ET:0 EL:0 ]
stdout
22:18:43
Tue Oct 18 22:18:43 2016 us=299022 Socket Buffers: R=[212992-&gt;131072] S=[212992-&gt;131072]
stdout
22:19:23
Tue Oct 18 22:19:23 2016 us=359683 RESOLVE: Cannot resolve host address: pool.prd.se.ovpn.se: Temporary failure in name resolution
stdout
22:19:23
Tue Oct 18 22:19:23 2016 us=359767 Data Channel MTU parms [ L:1558 D:1450 EF:58 EB:135 ET:0 EL:0 AF:3/1 ]
stdout
22:19:23
Tue Oct 18 22:19:23 2016 us=359854 Local Options String: 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-client'
stdout
22:19:23
Tue Oct 18 22:19:23 2016 us=359888 Expected Remote Options String: 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-server'
stdout
22:19:23
Tue Oct 18 22:19:23 2016 us=359935 Local Options hash (VER=V4): '9e7066d2'
stdout
22:19:23
Tue Oct 18 22:19:23 2016 us=359975 Expected Remote Options hash (VER=V4): '162b04de'
stdout
22:20:03
Tue Oct 18 22:20:03 2016 us=412681 RESOLVE: Cannot resolve host address: pool.prd.se.ovpn.se: Temporary failure in name resolution
stdout
22:20:03
Tue Oct 18 22:20:03 2016 us=412817 TCP/UDP: Closing socket

what am i doing wrong?
Regards Roger

**Comment by haugene** [comment]
Hmm, can't say for certain but you're both setting `-v /volume1/transdock/resolv.conf:/etc/resolv.conf` and doing `--dns 8.8.8.8 --dns 8.8.4.4`. Maybe there's a conflict somehow?

Try with just one of them at a time. And if you're using the /volume1/transdock/resolv.conf option, verify its content and that it doesn't contain windows line-endings etc.

**Comment by rogstro** [comment]
ahh, seams like thats the problem, only --dns 8.8.8.8 --dns 8.8.4.4 now, rock steady!
thanks for a great solution :-)

**Comment by rogstro** [comment]
i was wrong, seams like the container not being restarted at all?
If i do a manual restart of the container in DSM, it works again.

Fri Oct 21 01:31:29 2016 us=101238 TLS: tls_process: killed expiring key
stdout
01:53:02
Fri Oct 21 01:53:02 2016 us=474883 PID_ERR replay-window backtrack occurred [9] [SSL-5] [0_________00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
stdout
04:01:30
Fri Oct 21 04:01:30 2016 us=429039 [ovpn.se] Inactivity timeout (--ping-restart), restarting
stdout
04:01:30
Fri Oct 21 04:01:30 2016 us=468932 TCP/UDP: Closing socket
stdout
04:01:30
Fri Oct 21 04:01:30 2016 us=469125 SIGUSR1[soft,ping-restart] received, process restarting
stdout
04:01:30
Fri Oct 21 04:01:30 2016 us=469191 Restart pause, 2 second(s)
stdout
04:01:32
Fri Oct 21 04:01:32 2016 us=469716 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
stdout
04:01:32
Fri Oct 21 04:01:32 2016 us=469907 Re-using SSL/TLS context
stdout
04:01:32
Fri Oct 21 04:01:32 2016 us=478748 LZO compression initialized
stdout
04:01:32
Fri Oct 21 04:01:32 2016 us=479085 Control Channel MTU parms [ L:1558 D:166 EF:66 EB:0 ET:0 EL:0 ]
stdout
04:01:32
Fri Oct 21 04:01:32 2016 us=479235 Socket Buffers: R=[212992-&gt;131072] S=[212992-&gt;131072]
stdout
04:02:12
Fri Oct 21 04:02:12 2016 us=744700 RESOLVE: Cannot resolve host address: pool.prd.se.ovpn.se: Temporary failure in name resolution
stdout
04:02:12
Fri Oct 21 04:02:12 2016 us=744793 Data Channel MTU parms [ L:1558 D:1450 EF:58 EB:135 ET:0 EL:0 AF:3/1 ]
stdout
04:02:12
Fri Oct 21 04:02:12 2016 us=744927 Local Options String: 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-client'
stdout
04:02:12
Fri Oct 21 04:02:12 2016 us=744973 Expected Remote Options String: 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-server'
stdout
04:02:12
Fri Oct 21 04:02:12 2016 us=745067 Local Options hash (VER=V4): '9e7066d2'
stdout
04:02:12
Fri Oct 21 04:02:12 2016 us=745129 Expected Remote Options hash (VER=V4): '162b04de'

**Comment by haugene** [comment]
Hmm, unsure why that is... But it shouldn't do a --ping-restart, we want it to do a ping-exit. Restarting the openvpn process won't reload everything like we want. Also we want to rewrite the settings.json with the new tun0 interface IP. The container should exit with an error and then --restart=always should bring it back up.

When you say the container isn't restarting, is it just hanging? Or not starting up again after an exit?

**Comment by rogstro** [comment]
The container/transmission keeps running and i can connect to it, but the VPN seams to die
RESOLVE: Cannot resolve host address: pool.prd.se.ovpn.se: Temporary failure in name resolution

**Comment by sl0n** [comment]
@rogstro I have exactly the same problem. What I observe:

1. Container starts and runs fine.
2. At some point, I guess, tun interface hangs, eg I can not ping the tun's interface endpoint. I see the following log entries for openvpn process:

 Mon Jan 16 09:02:52 2017 [PureVPN] Inactivity timeout (--ping-restart), restarting
Mon Jan 16 09:02:52 2017 SIGUSR1[soft,ping-restart] received, process restarting
Mon Jan 16 09:02:57 2017 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Mon Jan 16 09:02:57 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jan 16 09:03:37 2017 RESOLVE: Cannot resolve host address: MY-VPN-SERVER-NAME: Temporary failure in name resolution
....
Mon Jan 16 09:18:33 2017 NOTE: --mute triggered...

This issue can be resolved by restarting the whole container, however it's not being triggered, ie 

"OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"
+
"--restart always" flag for the container
is not enough to trigger the container restart.

Just my observations so far.

**Comment by haugene** [comment]
As @himred pointed out in #438 some configs have the `pull` option enabled which means that the client might get updated options from the server which in turn can override the ping-exit flag. Worth taking a look.

I'm cleaning old issues. Re-open or create a new issue if it's still a problem. Remember logs and steps to reproduce.

**Comment by haugene** [comment]
#454
