### ISSUE TITLE
Not publishing ports

### ISSUE THREAD

**Issue by putergod** [haugene/docker-transmission-openvpn#1550]
Was working fine the past few days, but now isn’t publishing ports. Upon container restart, it’ll show all the ports configured as published initially, but once fully restarted goes back to none. Note that I had to rebuild everything because OMV4 buggered up when trying to upgrade to OMV5, which I did because TransmissionVPN stopped connecting to PIA and nothing was working.

Using portainer on OMV 5.5. Created a stack to include Radarr, Sonarr, Lidarr, and LazyLibrarian so that they all run through the VPN in the transmission container. At first I restarted everything, and that changed nothing. Then I created a template of the stack and deployed the template (after renaming the variables for container name) and still had the same problem, but I also started getting “container does not exist” errors. So, I deleted all the containers, the stack, and the images, and started over with a new stack, and the results as the same.

Below is my docker compose file:

version: '2.1'
services:
 transmission-openvpn:
    volumes:
        - /srv/dev-disk-by-label-DATA/Downloads/:/data
        - /srv/dev-disk-by-label-DATA/AppData/TransmissionVPN/:/config
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=1000
        - PGID=100
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=PIA
        #- OPENVPN_CONFIG=Canada,Netherlands,France,Sweden,Italy,Belgium,Austria,Denmark,Norway,Ireland (commented out when issues began)
        - OPENVPN_USERNAME=pXXXXXXX
        - OPENVPN_PASSWORD=XxXxXxXxXxXxXxXxXxXxXxX
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=192.168.1.0/24
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - DNS=1.1.1.1,8.8.8.8
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
        - 9117:9117
        - 7878:7878
        - 8989:8989
        - 8686:8686
        - 5299:5299
    restart: always
    image: haugene/transmission-openvpn

 jackett:
    image: linuxserver/jackett
    container_name: Jackett
    network_mode: "service:transmission-openvpn"
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/New_York
        - AUTO_UPDATE=true #optional
        - RUN_OPTS=#optional
    volumes:
        - /srv/dev-disk-by-label-DATA/AppData/Jackett:/config
        - /srv/dev-disk-by-label-DATA/Downloads/watch:/downloads
    restart: unless-stopped

 radarr:
    image: linuxserver/radar
    network_mode: "service:transmission-openvpn"
    container_name: Radarr
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/New_York
        - UMASK_SET=022 #optional
    volumes:
        - /srv/dev-disk-by-label-DATA/AppData/Radarr:/config
        - /srv/dev-disk-by-label-DATA/Media/Movies:/movies
        - /srv/dev-disk-by-label-DATA/Downloads/completed:/downloads
    restart: unless-stopped

 sonarr:
    image: linuxserver/sonar
    network_mode: "service:transmission-openvpn"
    container_name: Sonarr
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/New_York
        - UMASK_SET=022 #optional
    volumes:
        - /srv/dev-disk-by-label-DATA/AppData/Sonarr:/config
        - /srv/dev-disk-by-label-DATA/Media/TV Shows:/tv
        - /srv/dev-disk-by-label-DATA/Downloads/completed:/downloads
    restart: unless-stopped

 lidarr:
    image: linuxserver/lidarr
    network_mode: "service:transmission-openvpn"
    container_name: Lidarr
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/New_York
        - UMASK_SET=022 #optional
    volumes:
        - /srv/dev-disk-by-label-DATA/AppData/Lidarr:/config
        - /srv/dev-disk-by-label-DATA/Media/Music:/music
        - /srv/dev-disk-by-label-DATA/Downloads/completed:/downloads
    restart: unless-stopped

 lazylibrarian:
    image: linuxserver/lazylibrarian
    network_mode: "service:transmission-openvpn"
    container_name: Lazylibrarian
    environment:
        - PUID=1000
        - PGID=100
         - TZ=America/New_York
        #- DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
        - /srv/dev-disk-by-label-DATA/AppData/Lazylibrarian:/config
        - /srv/dev-disk-by-label-DATA/Downloads/completed:/downloads
        - /srv/dev-disk-by-label-DATA/Media/Books:/books
    restart: unless-stopped

Container logs:
2020-11-24T19:09:51.147860773Z Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e,
2020-11-24T19:09:51.148451686Z Creating TUN device /dev/net/tun,
2020-11-24T19:09:51.150843979Z Using OpenVPN provider: PIA,
2020-11-24T19:09:51.150860788Z Provider PIA has a custom setup script, executing it,
2020-11-24T19:09:51.151980262Z Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.McPlll,
2020-11-24T19:09:51.322776182Z Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia,
2020-11-24T19:09:51.324677911Z unzip: short read,
2020-11-24T19:10:51.722114883Z Starting container with revision: 430e1d9629f79cda2afddc0545e2ecf8d090865e,
2020-11-24T19:10:51.723125282Z Creating TUN device /dev/net/tun,
2020-11-24T19:10:51.725581946Z Using OpenVPN provider: PIA,
2020-11-24T19:10:51.725625039Z Provider PIA has a custom setup script, executing it,
2020-11-24T19:10:51.727126014Z Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.OgPEIA,
2020-11-24T19:10:51.978972858Z Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia,
2020-11-24T19:10:51.981249489Z unzip: short read,

This keeps repeating.

**Comment by putergod** [comment]
Tried the fix in issue #1548 (setting  - PIA_OPENVPN_CONFIG_BUNDLE=openvpn) and it appears to be working at this time. I will update if I continue to have issues.

**Comment by d4real** [comment]
> 
> 
> Tried the fix in issue #1548 (setting - PIA_OPENVPN_CONFIG_BUNDLE=openvpn) and it appears to be working at this time. I will update if I continue to have issues.

Did this fix your issue?  Mine was I couldn't get the transmission web UI to connect/load.  The fix noted in #1548 corrected the web UI issue but nothing seems to be downloading.

**Comment by haugene** [comment]
@d4real Try with a clean mount, or skip mounting to /data at all. That way you can see if it's something in the image/Transmission or if there are any local settings you've done. Also it's very hard to debug your setup without run configuration or logs.

The original issue seems to be fixed, glad you got it working @putergod :+1: I'll close this for now and you should create a new issue if you still have issues @d4real. But include logs and config.
