### ISSUE TITLE
Transmission daemon down, but network is up 

### ISSUE THREAD

**Issue by Esteidinger** [haugene/docker-transmission-openvpn#1551]
**Describe the problem**
My long running docker container is no longer working. 
I use NordVPN and I am aware that they use a different login process these days, I have tried both sets of credentials with no luck. 

If I try to wget from inside the container I get a 403 error. 

If I check the container health I get this error: 

PING google.com (142.250.80.14): 56 data bytes 64 bytes from 142.250.80.14: seq=0 ttl=119 time=21.433 ms 64 bytes from 142.250.80.14: seq=1 ttl=119 time=22.601 ms --- google.com ping statistics --- 2 packets transmitted, 2 packets received, 0% packet loss round-trip min/avg/max = 21.433/22.017/22.601 ms Network is up transmission-daemon process not running 

In the log I see that a kill signal was sent. I don't know why. 
Sending kill signal to transmission-daemon

**Add your docker run command**
docker create \
  --cap-add=NET_ADMIN \
  --name=vpntransmission \
  -v /media/downloads:/data \
  -v /media/downloads/watch:/data/watch \
  -v /etc/localtime:/etc/localtime:ro \
  -e CREATE_TUN_DEVICE=true \
  -e OPENVPN_PROVIDER=NORDVPN \
  -e OPENVPN_USERNAME=USERNAME \
  -e OPENVPN_PASSWORD=PASSWORD \
  -e WEBPROXY_ENABLED=false \
  -e LOCAL_NETWORK=192.168.1.0/24 \
  -e HEALTH_CHECK_HOST=google.com \
  -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
  --log-driver json-file \
  --log-opt max-size=10m \
  -p 9091:9091 \
  --restart unless-stopped \
    haugene/transmission-openvpn

**Logs**
Tue Nov 24 15:06:06 2020 /sbin/ip route del 86.107.55.236/32,
Tue Nov 24 15:06:06 2020 /sbin/ip route del 0.0.0.0/1,
Tue Nov 24 15:06:06 2020 /sbin/ip route del 128.0.0.0/1,
Tue Nov 24 15:06:06 2020 Closing TUN/TAP interface,
Tue Nov 24 15:06:06 2020 /sbin/ip addr del dev tun0 10.8.0.2/24,
Tue Nov 24 15:06:06 2020 /etc/openvpn/tunnelDown.sh tun0 1500 1654 10.8.0.2 255.255.255.0 init,
Sending kill signal to transmission-daemon,
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec],
Tue Nov 24 15:06:06 2020 SIGTERM[soft,auth-failure] received, process exiting,
Starting container with revision: baed33520630e88ba34842cab05f2cd3fd6cf28f,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: NORDVPN,
Provider NORDVPN has a custom setup script, executing it,
2020-11-24 15:06:09 Checking curl installation,
2020-11-24 15:06:09 Removing existing configs,
2020-11-24 15:06:09 Selecting the best server...,
2020-11-24 15:06:09 Searching for group: legacy_p2p,
2020-11-24 15:06:09 Searching for technology: openvpn_udp,
2020-11-24 15:06:09 Best server : us6482.nordvpn.com,
2020-11-24 15:06:09 Downloading config: default.ovpn,
2020-11-24 15:06:09 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/us6482.nordvpn.com.udp.ovpn,
Starting OpenVPN using config default.ovpn,
Modifying /etc/openvpn/nordvpn/default.ovpn for best behaviour in this container,
Setting OpenVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0,
Tue Nov 24 15:06:14 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020,
Tue Nov 24 15:06:14 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10,
Tue Nov 24 15:06:14 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Tue Nov 24 15:06:14 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Tue Nov 24 15:06:14 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Tue Nov 24 15:06:14 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]5.181.234.163:1194,
Tue Nov 24 15:06:14 2020 Socket Buffers: R=[212992->212992] S=[212992->212992],
Tue Nov 24 15:06:14 2020 UDP link local: (not bound),
Tue Nov 24 15:06:14 2020 UDP link remote: [AF_INET]5.181.234.163:1194,
Tue Nov 24 15:06:14 2020 TLS: Initial packet from [AF_INET]5.181.234.163:1194, sid=58219716 df0c7e9f,
Tue Nov 24 15:06:14 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Tue Nov 24 15:06:14 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Tue Nov 24 15:06:14 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5,
Tue Nov 24 15:06:14 2020 VERIFY KU OK,
Tue Nov 24 15:06:14 2020 Validating certificate extended key usage,
Tue Nov 24 15:06:14 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Tue Nov 24 15:06:14 2020 VERIFY EKU OK,
Tue Nov 24 15:06:14 2020 VERIFY OK: depth=0, CN=us6482.nordvpn.com,
Tue Nov 24 15:06:14 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Tue Nov 24 15:06:14 2020 [us6482.nordvpn.com] Peer Connection Initiated with [AF_INET]5.181.234.163:1194,
Tue Nov 24 15:06:15 2020 SENT CONTROL [us6482.nordvpn.com]: 'PUSH_REQUEST' (status=1),
Tue Nov 24 15:06:15 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.8.3.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.3.6 255.255.255.0,peer-id 4,cipher AES-256-GCM',
Tue Nov 24 15:06:15 2020 OPTIONS IMPORT: timers and/or timeouts modified,
Tue Nov 24 15:06:15 2020 OPTIONS IMPORT: explicit notify parm(s) modified,
Tue Nov 24 15:06:15 2020 OPTIONS IMPORT: compression parms modified,
Tue Nov 24 15:06:15 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified,
Tue Nov 24 15:06:15 2020 Socket Buffers: R=[212992->425984] S=[212992->425984],
Tue Nov 24 15:06:15 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Tue Nov 24 15:06:15 2020 OPTIONS IMPORT: route options modified,
Tue Nov 24 15:06:15 2020 OPTIONS IMPORT: route-related options modified,
Tue Nov 24 15:06:15 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Tue Nov 24 15:06:15 2020 OPTIONS IMPORT: peer-id set,
Tue Nov 24 15:06:15 2020 OPTIONS IMPORT: adjusting link_mtu to 1657,
Tue Nov 24 15:06:15 2020 OPTIONS IMPORT: data channel crypto options modified,
Tue Nov 24 15:06:15 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Tue Nov 24 15:06:15 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Tue Nov 24 15:06:15 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Tue Nov 24 15:06:15 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:03,
Tue Nov 24 15:06:15 2020 TUN/TAP device tun0 opened,
Tue Nov 24 15:06:15 2020 TUN/TAP TX queue length set to 100,
Tue Nov 24 15:06:15 2020 /sbin/ip link set dev tun0 up mtu 1500,
Tue Nov 24 15:06:15 2020 /sbin/ip addr add dev tun0 10.8.3.6/24 broadcast 10.8.3.255,
Tue Nov 24 15:06:15 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1585 10.8.3.6 255.255.255.0 init,
Up script executed with tun0 1500 1585 10.8.3.6 255.255.255.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.3.6,
Updating Transmission settings.json with values from env variables,
Using existing settings.json for Transmission /data/transmission-home/settings.json,
Traceback (most recent call last):,
  File "/etc/transmission/updateSettings.py", line 45, in <module>,
    settings_dict = json.load(input_file),
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load,
    return loads(fp.read(),,
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads,
    return _default_decoder.decode(s),
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode,
    obj, end = self.raw_decode(s, idx=_w(s, 0).end()),
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode,
    raise JSONDecodeError("Expecting value", s, err.value) from None,
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0),
sed'ing True to true,
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   root,
User uid:    0,
User gid:    0,
-------------------------------------,
,
STARTING TRANSMISSION,
Transmission startup script complete.,
Tue Nov 24 15:06:15 2020 /sbin/ip route add 5.181.234.163/32 via 172.17.0.1,
Tue Nov 24 15:06:15 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.3.1,
Tue Nov 24 15:06:15 2020 /sbin/ip route add 128.0.0.0/1 via 10.8.3.1,
Tue Nov 24 15:06:15 2020 Initialization Sequence Completed,

**Host system:**
Running on a Dell Poweredge system. 

Which version of Docker are you using? -->
19.03.13

**Comment by nicbou** [comment]
As the logs say, it looks like your JSON config is not valid

**Comment by haugene** [comment]
Or if you're not too fond of any settings in Transmission (they will be restored to the default) - just delete the settings.json from transmission-home. Because you mount it like this ` /media/downloads:/data` you should find it at  /media/downloads/transmission-home/settings.json

PS: You can also just rename or move that settings.json file somewhere else. Then when you restart the container it will generate a new one and you can have a look at the difference which can tell us why it failed

**Comment by Esteidinger** [comment]
Thanks @haugene , That was good advice. I didn't see where the error for the JSON file was. So I appreciate the advice all around.
