### ISSUE TITLE
Can't start container with latest update 

### ISSUE THREAD

**Issue by kornflex** [haugene/docker-transmission-openvpn#1554]
Hello, 

I have updated the container on my synology. 

Now, I have this error in cli:
 
Error response from daemon: failed to initialize logging driver: database is lockedError: failed to start containers: transmission-openvpn-syno 

I'm using it for a long time and it's the first time I can't start it :/
Could you help me ?

Thank you

**Comment by wireddirect** [comment]
Looks like they renamed the .ovpn files. If you were "CA Toronto" before it needs to be "ca_toronto" now.

Try "docker container logs transmission-vpn" and it should verify this for you.

**Comment by tjcrandley** [comment]
I also had the same issue where my old PIA config of "US Seattle" needed to be updated to us_seattle.  I suspect something changed in the download script where now there isn't any preprocessing of the values for the VPN providers.

**Comment by mspencerl87** [comment]
If you are dumb like me change the following

        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=Toronto   CHANGE TO ca_toronto or your corresponding VPN
            - OPENVPN_USERNAME=user
            - OPENVPN_PASSWORD=pass
            - WEBPROXY_ENABLED=false

**Comment by kornflex** [comment]
Thank you for your help !
I had to correct this but I had to restart Docker to get my container working...
