### ISSUE TITLE
using arm image - posted fixes for PIA not working currently

### ISSUE THREAD

**Issue by rednaxelap** [haugene/docker-transmission-openvpn#1555]
**Describe the problem**
transmission stopped working, could not access the web gui. portainer wasn't working either. Updated both docker and portainer and this transmission/vpn container fails.

I updated my OPENVPN_CONFIG label to reflect the new naming conventions
I tried removing the LOCAL_NETWORK label
I tried changing the version to 3.3 and was told by portianer that it did not support it

**Add your docker run command**
---
version: "2"
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest-armhf
    container_name: transmission-openvpn-syno
    restart: always
    cap_add:
      - NET_ADMIN 
    devices:
      - /dev/net/tun 
    volumes:
      - /srv/dev-disk-by-label-LiLBox/Torrents:/data
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=ca_toronto
      - OPENVPN_USERNAME=********
      - OPENVPN_PASSWORD=********
      - LOCAL_NETWORK=192.168.2.0/24
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 
      - PUID=1000 
      - PGID=100 
    ports:
      - 9091:9091 
      - 8888:8888
    dns:
      - 209.222.18.222 
      - 209.222.18.218 

**Logs**
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.XzMbyoMVv7
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
[/tmp/tmp.XzMbyoMVv7]
End-of-central-directory signature not found.  Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive.  In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tmp.XzMbyoMVv7 or
/tmp/tmp.XzMbyoMVv7.zip, and cannot find /tmp/tmp.XzMbyoMVv7.ZIP, period.
Starting container with revision: 3d97cd5302985c1a710f46ab0c311f721f224fc6
knod: /dev/net/tun: File exists
Using OpenVPN provider: PIA.

**Host system:**
 
Odroid XU4
OMV 5.5.17-3
Docker Version 5:19.03.13~3-0~debian-buster

**Comment by haugene** [comment]
PIA changed their URLs. This is now updated but you have to pull the latest image again.
This was fixed in #1552

**Comment by haugene** [comment]
Also I think this can be closed as a duplicate of #1548

**Comment by rednaxelap** [comment]
> PIA changed their URLs (again). This is now updated but you have to pull the latest image again.
> This was fixed in #1552

does this apply to arm based images? I referenced that I was using image: haugene/transmission-openvpn:latest-armhf

**Comment by rednaxelap** [comment]
> Also I think this can be closed as a duplicate of #1548

I believe this is the same issue but my platform appears unique compared to that of the other users. Was there an update to the arm based image? In my stack I referenced image: haugene/transmission-openvpn:latest-armhf 

Also because I am running this on an odroid i have slightly different builds of OMV and portainer. Is there a way that I can place the config locally and prevent the  script from trying to download it maybe?

I apologized if I missed that info, I have been working on this for hours and am loosing track of what I did/didn't try.

Thank you!

**Comment by rednaxelap** [comment]
> Aha. Well yes, this also applies to the arm images. They have been merged now though. So we build a multiarch manifest tagged as :latest. So even if you're on arm you should be able to use that image and docker should pull the correct one based on the host architecture. It supports armv7 and armv8.
> 
> It is possible to provide your own config and it is described in the docs as using a custom provider. The container will then not know that you're actually using pia and it will not do port forwarding. To support that combo I would need to implement it.
> 
> But test the multiarch first 🤞
> I will delete the old latest-armhf images. They will no longer be updated.

So I was just coming back here to say that I decided to try the "latest" image. I went into the stack I had created and removed the '-armhf' and updated the stack. That and correcting the OPENVPN_CONFIG resolved the issue. I only know enough to ask more questions it seems and have always been terrified of breaking things if they weren't specifically made for arm processors. Thank you for your prompt response!
