### ISSUE TITLE
Bootloop with purevpn

### ISSUE THREAD

**Issue by razmoket89** [haugene/docker-transmission-openvpn#1557]
**PROBLEM**
Long-time running container suddenly bootloops.

**ENVIRONENT** 

PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-- | --
OPENVPN_USERNAME | XXXXXX
OPENVPN_PASSWORD | XXXXXX
OPENVPN_PROVIDER | PUREVPN
GLOBAL_APPLY_PERMISSIONS | true
TRANSMISSION_HOME | /data/transmission-home
TRANSMISSION_RPC_PORT | 9091
TRANSMISSION_DOWNLOAD_DIR | /data/completed
TRANSMISSION_INCOMPLETE_DIR | /data/incomplete
TRANSMISSION_WATCH_DIR | /data/watch
CREATE_TUN_DEVICE | true
ENABLE_UFW | false
UFW_ALLOW_GW_NET | false
UFW_DISABLE_IPTABLES_REJECT | false
PUID | 1000
PGID | 1000
WEBPROXY_ENABLED | false
WEBPROXY_PORT | 8888
LOG_TO_STDOUT | false
HEALTH_CHECK_HOST | google.com
REVISION | 05f657435af4ca118b8cdf6a03f5ce895149cbc8
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED | true
TRANSMISSION_RPC_PASSWORD | XXXXX
TRANSMISSION_RPC_USERNAME | XXXXX
OPENVPN_CONFIG | ch2-ovpn-tcp,de2-ovpn-tcp,nl2-ovpn-tcp
LOCAL_NETWORK | 192.168.0.0/24
TRANSMISSION_WEB_UI | transmission-web-control
TZ | Europe/Paris
TRANSMISSION_RPC_ENABLED | true

**LOGS**
Starting container with revision: 05f657435af4ca118b8cdf6a03f5ce895149cbc8,
Creating TUN device /dev/net/tun,
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: PUREVPN,
3 servers found in OPENVPN_CONFIG, de2-ovpn-tcp chosen randomly,
Starting OpenVPN using config de2-ovpn-tcp.ovpn,
Setting OpenVPN credentials...,
adding route to local network 192.168.0.0/24 via 192.168.0.1 dev ens18,
RTNETLINK answers: File exists,
Thu Nov 26 22:06:29 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020,
Thu Nov 26 22:06:29 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10,
Thu Nov 26 22:06:29 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Nov 26 22:06:29 2020 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication,
Thu Nov 26 22:06:29 2020 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication,
Thu Nov 26 22:06:29 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]82.102.16.107:80,
Thu Nov 26 22:06:29 2020 Socket Buffers: R=[131072->131072] S=[16384->16384],
Thu Nov 26 22:06:29 2020 Attempting to establish TCP connection with [AF_INET]82.102.16.107:80 [nonblock],
Thu Nov 26 22:06:30 2020 TCP connection established with [AF_INET]82.102.16.107:80,
Thu Nov 26 22:06:30 2020 TCP_CLIENT link local: (not bound),
Thu Nov 26 22:06:30 2020 TCP_CLIENT link remote: [AF_INET]82.102.16.107:80,
Thu Nov 26 22:06:30 2020 TLS: Initial packet from [AF_INET]82.102.16.107:80, sid=36404994 5146f6d9,
Thu Nov 26 22:06:30 2020 VERIFY OK: depth=1, C=HK, ST=Central, L=HK, O=Secure-ServerCA, OU=IT, CN=Secure-ServerCA, name=Secure-ServerCA, emailAddress=mail@host.domain,
Thu Nov 26 22:06:30 2020 VERIFY KU OK,
Thu Nov 26 22:06:30 2020 Validating certificate extended key usage,
Thu Nov 26 22:06:30 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Thu Nov 26 22:06:30 2020 VERIFY EKU OK,
Thu Nov 26 22:06:30 2020 VERIFY OK: depth=0, C=HK, ST=Central, L=HK, O=Secure-Server, OU=IT, CN=Secure-Server, name=changeme, emailAddress=mail@host.domain,
Thu Nov 26 22:06:31 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1560', remote='link-mtu 1552',
Thu Nov 26 22:06:31 2020 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM',
Thu Nov 26 22:06:31 2020 WARNING: 'auth' is used inconsistently, local='auth SHA1', remote='auth [null-digest]',
Thu Nov 26 22:06:31 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA,
Thu Nov 26 22:06:31 2020 [Secure-Server] Peer Connection Initiated with [AF_INET]82.102.16.107:80,
Thu Nov 26 22:06:32 2020 SENT CONTROL [Secure-Server]: 'PUSH_REQUEST' (status=1),
Thu Nov 26 22:06:33 2020 AUTH: Received control message: AUTH_FAILED,
Thu Nov 26 22:06:33 2020 SIGTERM[soft,auth-failure] received, process exiting,

**Host system:**
Debian 10 - Proxmox VM - Docker version 19.03.13, build 4484c46d9d

**Comment by haugene** [comment]
I have not yet seen a case of AUTH_FAILED that is not due to actual username/password errors. It's either that or an error on the VPN provider side with a faulty server or something.

The username/password error could come from the container though. We have some issues with special characters. Does your username or password contain that? If you exec into the container and do `cat /config/openvpn-credentials.txt` you see the username/password that will be used. If it's not looking right then something has happened when it's written to file.

You might not have time to exec anything as the container fails. Try to mount a volume to /config and you'll get the file there.

Another thing. I see you get an `mknod: /dev/net/tun: File exists` error. It's not breaking anything, but I'm curious. Are you mounting /dev/net/tun? If you are then you don't have to. And if you want to mount it you can set CREATE_TUN_DEVICE=false.

**Comment by razmoket89** [comment]
Thanks for the quick reply.

My password only contains letters and numbers. I changed it already, still the same problem.
I specified 3 different server location in OPENVPN_CONFIG, I can't imagine they're all down at the same time, and since 3 days.

About dev/net/tun, I don't remember setting anything about that. I juste noticed I have CREATE_TUN_DEVICE set to " true " but I can't remember if i set that or if it's default config.

**Comment by sl0n** [comment]
@razmoket89 PureVPN seem to have changed something at their end, I have the same errors ..

Some time ago they sent me a message asking if I'd like to have one single username-password pair ..

**Comment by razmoket89** [comment]
@sl0n Ok, glad not to be the only one. Though would be better to have a solution ;)
I'll email them next week to get explanations.

**Comment by razmoket89** [comment]
@haugene you can close the issue, it's coming from à disagreement between stacksocial (to which I bought à lifetime purevpn account) and purevpn, so they Just disabled my account. @sl0n you might have thé same problem.

**Comment by beneix** [comment]
@haugene before closing, note that the bootloop symptom is also occurring with other VPN providers - in my case PIA (see issue #1560).

**Comment by sl0n** [comment]
@razmoket89 pls check https://support.purevpn.com/how-to-change-client-area-or-vpn-password to reset your OpenVPN password, it helped me.

**Comment by razmoket89** [comment]
> @razmoket89 pls check https://support.purevpn.com/how-to-change-client-area-or-vpn-password to reset your OpenVPN password, it helped me.
> 
> And my "lifetime" account became "5 years long" as I discovered it -)

If you contact stacksocial, they'll offer you to switch to a new "lifetime" with KeepSolid Vpn Unlimited, which I did. Works like a charm.

**Comment by haugene** [comment]
Closing this, as per request :point_up:
