### ISSUE TITLE
Expand and clean up documentation

### ISSUE THREAD

**Issue by haugene** [haugene/docker-transmission-openvpn#1558]
The documentation contains a lot of good stuff, but it's not well structured and there are a lot of blank spots.
To reduce the amount of repeated questions here in the issues we should do a re-write and try to cover all the top asked questions in a FAQ.

At the time of writing this I have already started but I won't be "done" very soon. I want to push what I have anyways because I think it's better than what is there now. Also it puts a bit of pressure on myself to get the rest done. I'll drop a few links to this issue in them as well so that others might want to elaborate where I've fallen short.

**Comment by ajhorvath20** [comment]
Great work @haugene and much appreciated

**Comment by clement-z** [comment]
Hi @haugene, do you have a checklist/todolist for the rewrite ? If not maybe you can consider adding it as a comment on this issue ?

Although short on time currently, I'm down to help where I can.

**Comment by haugene** [comment]
I have to continue here later. But it's not done. So I'm opening it again. If nothing else, dear stalebot will remind me in a couple of month.
