### ISSUE TITLE
Transmission OVPN No Longer Working - ARM Build, Portainer, PIA

### ISSUE THREAD

**Issue by SLChang3** [haugene/docker-transmission-openvpn#1562]
**Describe the problem**
Apologies in advance for any misunderstanding but Transmission was working on my RPi4 ARM build, but now I am getting errors that I don't know how to resolve. This could be a configuration issue --- I just don't know for sure. This docker build was made by TechnoDad on Youtube via: https://www.youtube.com/watch?v=5rtGBwBuzQE&ab_channel=TechnoDadLife. 

**docker run command**
version: '2.1'
services:
    transmission-openvpn:
        volumes:
            - /srv/dev-disk-by-label-easystore/downloads:/data
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PUID=1000
            - PGID=100
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=default
            - OPENVPN_USERNAME=********
            - OPENVPN_PASSWORD=********
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.0.0/24
            - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        dns:
            - 8.8.8.8
            - 8.8.4.4
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
            - 9117:9117
            - 7878:7878
            - 8989:8989
            - 8686:8686
            - 5299:5299
        restart: always
        image: haugene/transmission-openvpn:latest-armhf
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        network_mode: "service:transmission-openvpn"
        environment:
            - PUID=1000
            - PGID=100
            - TZ=America/ Eastern
            - AUTO_UPDATE=true #optional
            - RUN_OPTS=#optional
        volumes:
            - /srv/dev-disk-by-label-easystore/Config/jackett:/config
            - /srv/dev-disk-by-label-easystore/downloads:/downloads
        restart: unless-stopped
    radarr:
        image: linuxserver/radarr
        network_mode: "service:transmission-openvpn"
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=100
            - TZ=America/ Eastern
            - UMASK_SET=022 #optional
        volumes:
            - /srv/dev-disk-by-label-easystore/Config/radarr:/config
            - /srv/dev-disk-by-label-easystore/Movies:/movies
            - /srv/dev-disk-by-label-easystore/downloads:/downloads
        restart: unless-stopped
    sonarr:
        image: linuxserver/sonarr
        network_mode: "service:transmission-openvpn"
        container_name: sonarr
        environment:
          - PUID=1000
          - PGID=100
          - TZ=America/ Eastern
          - UMASK_SET=022 #optional
        volumes:
         - /srv/dev-disk-by-label-easystore/Config/sonarr:/config
         - /srv/dev-disk-by-label-easystore/TV-Shows:/tv
         - /srv/dev-disk-by-label-easystore/downloads:/downloads
        restart: unless-stopped
    lidarr:
        image: linuxserver/lidarr
        network_mode: "service:transmission-openvpn"
        container_name: lidarr
        environment:
            - PUID=1000
            - PGID=100
            - TZ=America/ Eastern
            - UMASK_SET=022 #optional
        volumes:
            - /srv/dev-disk-by-label-easystore/Config/lidarr:/config
            - /srv/dev-disk-by-label-easystore/Music:/music
            - /srv/dev-disk-by-label-easystore/downloads:/downloads
        restart: unless-stopped
    lazylibrarian:
        image: linuxserver/lazylibrarian
        network_mode: "service:transmission-openvpn"
        container_name: lazylibrarian
        environment:
            - PUID=1000
            - PGID=100
            - TZ=America/ Eastern
           #- DOCKER_MODS=linuxserver/calibre-web:calibre #optional
        volumes:
            - /srv/dev-disk-by-label-easystore/Config/lazylibrarian:/config
            - /srv/dev-disk-by-label-easystore/downloads:/downloads
            - /srv/dev-disk-by-label-easystore/eBooks:/books
        restart: unless-stopped

**Errors/Logs**
![image](https://user-images.githubusercontent.com/59141808/100463601-19bf5b00-309a-11eb-96da-38e33b23a2b5.png)
![image](https://user-images.githubusercontent.com/59141808/100463676-365b9300-309a-11eb-9994-935e0ef10d8d.png)

Starting container with revision: 3d97cd5302985c1a710f46ab0c311f721f224fc6,
Using OpenVPN provider: PIA,
Provider PIA has a custom startup script, executing it,
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.H10XcfQwZf,
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia,
[/tmp/tmp.H10XcfQwZf],
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of /tmp/tmp.H10XcfQwZf or,
        /tmp/tmp.H10XcfQwZf.zip, and cannot find /tmp/tmp.H10XcfQwZf.ZIP, period.,

**Host system:**
Raspberry Pi 4 with an easystore external hard drive. Running OpenMediaVault with Portainer 1.24.1

**Comment by haugene** [comment]
Yeah. PIA have changed their vpn config URL again. It used to be called openvpn.zip, then openvpn-nextgen.zip (during migration) and now back to openvpn.zip because they have finished migration.

The image tag you are using is deprecated. :latest is now multiarch and should work from ARM as well. So remove `:latest-armhf` or set just `:latest` (which is the same) and then do a pull. I think that should fix it. Because the URL is fixed in the newest version.

**Comment by SLChang3** [comment]
You, sir, are a legend. I've been reading about the server migration, but I didn't realize that it was that simple of a fix... Thank you for the quick response. This fixed this problem but now I'm checking the logs for the VPN container and it's giving me this error (down at the bottom): 

Starting container with revision: 42d00652323b7b7fbee1689a54219599f4795a04,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: PIA,
Provider PIA has a custom setup script, executing it,
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.CfhJca,
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia,
Starting OpenVPN using config default.ovpn,
Modifying /etc/openvpn/pia/default.ovpn for best behaviour in this container,
Setting OpenVPN credentials...,
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0,
Fri Nov 27 16:33:18 2020 OpenVPN 2.4.9 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020,
Fri Nov 27 16:33:18 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10,
Fri Nov 27 16:33:18 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Fri Nov 27 16:33:18 2020 CRL: loaded 1 CRLs from file [[INLINE]],
Fri Nov 27 16:33:18 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]143.244.45.62:1198,
Fri Nov 27 16:33:18 2020 UDP link local: (not bound),
Fri Nov 27 16:33:18 2020 UDP link remote: [AF_INET]143.244.45.62:1198,
Fri Nov 27 16:33:18 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Fri Nov 27 16:33:18 2020 [newjersey402] Peer Connection Initiated with [AF_INET]143.244.45.62:1198,
Fri Nov 27 16:33:20 2020 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options,
Fri Nov 27 16:33:20 2020 OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3,
Fri Nov 27 16:33:20 2020 TUN/TAP device tun0 opened,
Fri Nov 27 16:33:20 2020 /sbin/ip link set dev tun0 up mtu 1500,
Fri Nov 27 16:33:20 2020 /sbin/ip addr add dev tun0 10.2.112.108/24 broadcast 10.2.112.255,
Fri Nov 27 16:33:20 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.2.112.108 255.255.255.0 init,
Up script executed with tun0 1500 1553 10.2.112.108 255.255.255.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.2.112.108,
Updating Transmission settings.json with values from env variables,
Using existing settings.json for Transmission /data/transmission-home/settings.json,
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.2.112.108,
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed,
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete,
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091,
Overriding scrape-paused-torrents-enabled because TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED is set to false,
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch,
sed'ing True to true,
Enforcing ownership on transmission config directories,
Applying permissions to transmission config directories,
Setting owner for transmission paths to 1000:100,
Setting permission for files (644) and directories (755),
Setting permission for watch directory (775) and its files (664),
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   abc,
User uid:    1000,
User gid:    100,
-------------------------------------,
,
STARTING TRANSMISSION,
Provider PIA has a script for automatic port forwarding. Will run it now.,
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=yes,
Transmission startup script complete.,
Fri Nov 27 16:33:26 2020 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.,
Fri Nov 27 16:33:26 2020 Initialization Sequence Completed,
curl: (7) Failed to connect to 10.2.112.1 port 19999: Connection refused,
Fri Nov 27 16:33:32 GMT 2020: getSignature error,
,
the has been a fatal_error,
date: invalid date '',
port is ,
curl: (7) Failed to connect to 10.2.112.1 port 19999: Connection refused,
Fri Nov 27 16:33:32 GMT 2020: bindPort error,
,
the has been a fatal_error,
transmission auth not required,
waiting for transmission to become responsive,
transmission became responsive,
setting transmission port to ,
localhost:9091/transmission/rpc/ responded: "success",
Checking port...,
Error: portTested: http error 400: Bad Request,
,
initial setup complete!,
,
waiting for rebind loop.................,
token expiry ,
remaining = -1606494823,
Fri Nov 27 16:33:43 GMT 2020: Getting PF token,
curl: (7) Failed to connect to 10.2.112.1 port 19999: Connection refused,
Fri Nov 27 16:33:43 GMT 2020: getSignature error,
,
the has been a fatal_error,
date: invalid date '',
Fri Nov 27 16:33:44 GMT 2020: Obtained PF token. Expires at ,
curl: (7) Failed to connect to 10.2.112.1 port 19999: Connection refused,
Fri Nov 27 16:33:44 GMT 2020: bindPort error,
,
the has been a fatal_error,
Fri Nov 27 16:33:44 GMT 2020: Server accepted PF bind,
Fri Nov 27 16:33:44 GMT 2020: Forwarding on port ,
Fri Nov 27 16:33:44 GMT 2020: Rebind interval: 1800 seconds,

**Comment by SLChang3** [comment]
Thank you so much for your help! You, sir, are a legend.
