### ISSUE TITLE
Fatal Error, date: invalid date ''

### ISSUE THREAD

**Issue by ShadowBullet** [haugene/docker-transmission-openvpn#1569]
My transmission container keeps throwing this error, unknown as to why. I am running it on Synology DSM through Docker. I am also unable to download anything through the container. The Web GUI shows up and the VPN is connected however I am unsure if this is due to the fatal error I am experiencing. I have uploaded my logs and also my docker config file. Please let me know of any additional information you may need. 

[Transmission Docker Logs & Config.zip](https://github.com/haugene/docker-transmission-openvpn/files/5611630/Transmission.Docker.Logs.Config.zip)

**Comment by Ni-k0** [comment]
getting the same error with the same setup. Docker on Synology.

**Comment by steve-spiteri** [comment]
Can you try to adding the environment variable `DISABLE_PORT_UPDATER=yes`?
If this removes the error (and has no other negative impact) then it further justifies the fix in #1570 regarding the default behavior for US based PIA servers.

**Comment by ShadowBullet** [comment]
> 
> 
> Can you try to adding the environment variable `DISABLE_PORT_UPDATER=yes`?
> If this removes the error (and has no other negative impact) then it further justifies the fix in #1570 regarding the default behavior for US based PIA servers.

That seemed to fix the error in the logs, but I am still unable to download any torrents it would seem

**Comment by SM60ma** [comment]
So I have had this same problem with PIA. I just solved it by changing my "OPENVPN_CONFIG" from a US server to any server that supports port forwarding. Currently none of the US servers support port forwarding (according to the desktop app). I removed "DISABLE_PORT_UPDATER=yes" completely and changed to "OPENVPN_CONFIG" to ca_ontario. Not an ideal solution but a workable one until the issue can be resolved with US servers.

**Comment by lardbit** [comment]
@SM60ma thanks, that worked great for me as well.

**Comment by trentclinton** [comment]
> > Can you try to adding the environment variable `DISABLE_PORT_UPDATER=yes`?
> > If this removes the error (and has no other negative impact) then it further justifies the fix in #1570 regarding the default behavior for US based PIA servers.
> 
> That seemed to fix the error in the logs, but I am still unable to download any torrents it would seem

I second this...

**Comment by trentclinton** [comment]
> > Can you try to adding the environment variable `DISABLE_PORT_UPDATER=yes`?
> > If this removes the error (and has no other negative impact) then it further justifies the fix in #1570 regarding the default behavior for US based PIA servers.
> 
> That seemed to fix the error in the logs, but I am still unable to download any torrents it would seem

Alright, now I am downloading. I changed the image from :latest to :dev, & it started downloading!

**Comment by haugene** [comment]
Hey guys. Just wanted to give you a heads up that I've merged #1602 and that should fix the port-forwarding issues :crossed_fingers: You still need to select a server that supports it though.

Please test and report back how it goes. Remember to `docker pull` the latest tag again first :smile:

**Comment by pkishino** [comment]
that seems to be default POSIX format for $(date) as per locale
