### ISSUE TITLE
Document DISABLE_PORT_UPDATER

### ISSUE THREAD

**Issue by bamItsCam** [haugene/docker-transmission-openvpn#1570]
**Is your feature request related to a problem? Please describe.**

I just spent a _really_ long time debugging why my container that was configured to use US-based vpns was failing on `curl: (7) Failed to connect to 10.33.112.1 port 19999: Connection refused`, and it turns out it was all because i didn't set `DISABLE_PORT_UPDATER=yes`... :unamused: 

This default behavior for US based pia servers is a little unintuitive, especially since previous versions worked fine with no additional config for servers that didn't support port forwarding.

**Describe the solution you'd like**

A documentation change that explains DISABLE_PORT_UPDATER and where you'd probably like to use it.

**Describe alternatives you've considered**

One alternative would be to set `DISABLE_PORT_UPDATER=yes` as default, but that would probably mess up those that have already gotten used to this change :smile: 

**Additional context**

I'm a huge fan of your work with this image, especially considering the recent "next gen" stuff that pia has put developers through.

**Comment by steve-spiteri** [comment]
Was actually coming to see if anyone posted about the curl issue since it was plaguing my container as well. Thank for posting this, got my container running error free! (y)

**Comment by haugene** [comment]
Hmm, I tested it with the US locations now and I see that's failing not so gracefully. I must admit that I haven't got into the new port forwarding script after the PIA changes, there's been a lot going on. But there has been repeated instability there and I'm not too happy about the whole setup with these port-forwarders and how it sometimes even stops the containers from starting.

Here it seems to be about spam in the logs right? I'm not sure what to do. We can add it to the docs, but with a growing list of configs options I feel we're making it hard to spot either way. It is logged that it can be turned off, but I see that's not as helpful as I thought it would be. Disabling it by default could be a temporary fix but I think the long term solution is to have it with the automatic port forwarding for the providers that support it.

In any case it should fail much more gracefully. We should be able to detect on the first response that it is not supported :thinking:

**Comment by bamItsCam** [comment]
Hi haugene, appreciate you looking at this. I agree there isn't an easy elegant solution here. I also agree that long term, auto port forwarding support detection would be great. Brainstorming solutions, could we try using port forwarding, but if it fails/gets a non-zero return code, try again without port forwarding? Could this failover behavior be unintuitive to those that aren't expecting it? One way to address that could be to have a `PORT_FORWARD` variable with the enum options of `on`, `off`, and `auto`, where `auto` would attempt a connection w/port forwarding, but on a connection refused would fall back to no port forwarding. `on` would require port forwarding to work, and error if unsuccessful, and `off` wouldn't even try to connect with port forwarding. The default behavior could be `auto`, and bonus points is that you'd have a more general env var that would make documentation easier. I'm still reading up on vpn port forwarding so some of my terminology might not be exact, but I hope it's close enough to spark ideas.

**Comment by haugene** [comment]
Coming back to this. I like your `on`, `off` and `auto` thoughts @bamItsCam 
It should be said that @taylorcox75 has really taken up the mantle when it comes to PIA server configurations and port-forwarding. I just merged #1602 that should reduce the errors in the scripts and there's a discussion related to the one we're having here unfolding in #1592 

It might be that the new PIA API could be the solution here. It marks the servers as having port-forwarding or not.

**Comment by taylorcox75** [comment]
This is why I care so much haha

![Screenshot_20201209-162643](https://user-images.githubusercontent.com/10939863/101705094-75e39100-3a43-11eb-8918-225d3c4ba17b.png)
