### ISSUE TITLE
OPENVPN_CONFIG suddenly became case sensitive (or the case changed for PIA)

### ISSUE THREAD

**Issue by khad** [haugene/docker-transmission-openvpn#1572]
My Docker container kept unexpectedly terminating and restarting itself. I checked the logs and found that none of the [suggested PIA servers](https://github.com/haugene/docker-transmission-openvpn/issues/1522#issuecomment-729205947) were working (France,Sweden,Italy,Belgium,Austria,Denmark,Norway,Ireland). The logs indicated that the same servers in all lowercase were valid options. So I changed the case, and things are working now:

```
OPENVPN_CONFIG=france,sweden,italy,belgium,austria,denmark,norway,ireland
```

Perhaps consider normalizing the value before parsing it?

**Comment by ammmze** [comment]
I'm also seeing this. The last line before it exits says:

```
NB: Remember to not specify .ovpn as part of the config name.
```

I previously had `CA Toronto`, but now needs to be `ca_toronto`

**Comment by haugene** [comment]
Yeah. PIA changed the name of all of their configs. As we're moving towards a more automated world where the configs are fetched on container runtime, reducing the maintenance required to keep them up to date, these errors can occur whenever a config is removed from the bundle or they're renamed.

I agree that we could try to look past case sensitivity and pick the config if it matches a case insensitive find/grep. But that will not solve the case for "CA Toronto" becoming "ca_toronto" and at that point I don't think we want to start fuzzy-finding configs. It feels outside the scope of the container, and could lead to unwanted behavior.

But yes to case-insensitive matching :+1: I'm going to have to leave this open for now. Maybe someone picks it up as a nice task for a first contribution.

**Comment by ammmze** [comment]
I would suggest maybe having the script rename all the files as well if that doesn't functionally break things. But then we can uppercase the filenames, replace sequential non-alphanumeric characters with an underscore and then the env variable can do the same after splitting by commas. That should give more predictable results unless they actually be it different, but probably easier than some fuzzy matching.
