### ISSUE TITLE
update-port.sh fails if the RPC port is not the default

### ISSUE THREAD

**Issue by gawindx** [haugene/docker-transmission-openvpn#1575]
When the RPC port is not the default one (9091), the update-port.sh scripts ignore this configuration and the script fails with the following error message:
`transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server`

I attach the pull request correcting this problem (#1574)

thank you in advance

**Comment by ksurl** [comment]
don't use non default port in the actual config settings.json. just use a different external port in your ports settings for the container or docker-compose.

**Comment by ksurl** [comment]
fair enough. but typically you would leave internal configs to default ports and handle custom ports at the container networking level. I would imagine podman has similar functionality? you could also add a custom script on pre-transmission startup to replace the update script with your version until it's fixed.

**Comment by gawindx** [comment]
On the principle of leaving the default ports, I am not saying the opposite, but as I monitor via RPC both at home and remotely on iOS, it was easier and more secure not to leave the default port.

For the script, this is already what I set up on my side and it works perfectly (this is the reason for the 3 commits in the PR, I first started with the PIA script that I I tested on my config before checking the update-port scripts for other VPN providers and correcting them as well).

At podman level, the principle is the same as Docker.
The controls are largely the same to be able to make a smooth transition.
The major difference is that podman does not need a daemon to run, unlike Docker (in addition to recent security tools better supported by podman than Docker)

**Comment by ksurl** [comment]
regardless of port, isn't it authenticated in plain text? or http. I use a reverse proxy to use https connection.

**Comment by gawindx** [comment]
I'm not telling you the opposite, but my config suits me as it is.
I could have done my config otherwise, that's for sure.

But it works very well like that and I do not necessarily want to put my hands in it.

I thank you for your advice but I remind you that the problem I am reporting is not that I cannot use a custom RPC port but that "when using a custom RPC port, the update-port scripts encounter a fault".

I have overcome this problem myself for my configuration but I propose the modification so that others who would be in the same case do not encounter this problem.
