### ISSUE TITLE
loadbalancing VPN's (enhancement)

### ISSUE THREAD

**Issue by laandennis** [haugene/docker-transmission-openvpn#1577]
please make an enhancement to support load balancing for OpenVPN with config flags
(https://openvpn.net/community-resources/implementing-a-load-balancing-failover-configuration/)
maybe this way we can get an higher download speed

**Comment by haugene** [comment]
Well, this seems to be entirely up to the .ovpn config so you can do this today. Or you can override `remote` or any other option you want by adding it to OPENVPN_OPTS.
Many of the providers do this already. A random example is this ProtonVPN config: https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/protonvpn/ch-05.protonvpn.com.udp.ovpn - lots of remotes and `remote-random` is specified.

Whether or not you have it will depend on what provider you have, and which config you use. And you can always override it if you want.
