### ISSUE TITLE
settings.json reset to default after restarting container

### ISSUE THREAD

**Issue by joeknock90** [haugene/docker-transmission-openvpn#158]
So I've got this container set up as such.

Data is stored in `/mnt/docker/data/transmission:/data`

but I want my downloads going to a fileshare so I mounted this: `/mnt/share/Share/Downloads:/downloads`

I edit the settings.json to make sure that all downloads go to `/downloads/Completed`

This works fine until I restart. 

I also can't set an RPC user or password because of this. Is there a workaround?

**Comment by haugene** [comment]
Yes, settings are reloaded on container restart and is based on environment variables. To set directory for downloaded files and rpc auth, see the readme and set your environment values accordingly.

**Comment by haugene** [comment]
First read the README, then maybe #150
