### ISSUE TITLE
FastestVPN - Outdated Configurations

### ISSUE THREAD

**Issue by kaldevo** [haugene/docker-transmission-openvpn#1581]
The remote hosts in .OVPN configurations are all outdated and won't work anymore.

**Which provider?**
FastestVPN

**Where are the configs?**
[https://support.fastestvpn.com/download/openvpn-tcp-udp-config-files/](https://support.fastestvpn.com/download/openvpn-tcp-udp-config-files/)

**Comment by haugene** [comment]
Hey @kaldevo. This took some time but FastestVPN should now be updated on the dev branch/tag.
See #1637 and https://github.com/haugene/vpn-configs-contrib/issues/1 for more info.
