### ISSUE TITLE
Cannot connect to PIA

### ISSUE THREAD

**Issue by erikjunker** [haugene/docker-transmission-openvpn#1584]
**Describe the problem**
Cannot connect to PIA

I'll just pre-face all of this by saying I'm a complete rookie.

This is almost definitely an issue on my end, but I've been struggling for days to get this to work, so I'm really hoping someone will be able to point me in the right direction.

In the logs it says "Cannot resolve host address: sweden.privacy.network:1198 (Try again)", which indicates that there is a DNS issue, but how do I verify? How can I change the DNS on the Synology NAS docker version?

Appreciate any help!

**Add your docker run command**
`docker run --name=haugene-transmission-openvpn --hostname=haugene-transmission-openvpn --mac-address=******** --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=OPENVPN_USERNAME=******* --env=OPENVPN_PASSWORD=*********** --env=OPENVPN_PROVIDER=PIA --env=GLOBAL_APPLY_PERMISSIONS=true --env=TRANSMISSION_HOME=/data/transmission-home --env=TRANSMISSION_RPC_PORT=9091 --env=TRANSMISSION_DOWNLOAD_DIR=/data/completed --env=TRANSMISSION_INCOMPLETE_DIR=/data/incomplete --env=TRANSMISSION_WATCH_DIR=/data/watch --env=CREATE_TUN_DEVICE=true --env=ENABLE_UFW=false --env=UFW_ALLOW_GW_NET=false --env=UFW_EXTRA_PORTS= --env=UFW_DISABLE_IPTABLES_REJECT=false --env=PUID=1029 --env=PGID=101 --env=DROP_DEFAULT_ROUTE= --env=WEBPROXY_ENABLED=false --env=WEBPROXY_PORT=8888 --env=WEBPROXY_USERNAME= --env=WEBPROXY_PASSWORD= --env=LOG_TO_STDOUT=false --env=HEALTH_CHECK_HOST=google.com --env=REVISION=42d00652323b7b7fbee1689a54219599f4795a04 --env=OPENVPN_CONFIG=sweden --volume=/volume1/Video/library:/data:rw --volume=/config --volume=/data --network=bridge --privileged -p 0.0.0.0:9091:9091 --restart=no --label='autoheal=true' --label='org.opencontainers.image.revision=42d00652323b7b7fbee1689a54219599f4795a04' --label='org.opencontainers.image.source=https://github.com/haugene/docker-transmission-openvpn' --log-driver=db --detach=true -t haugene/transmission-openvpn:latest dumb-init /etc/openvpn/start.sh
`

**Logs**
https://pastebin.com/2Fmrx1Wd

**Host system:**
Synology NAS
Docker version 18.09.0-0513

**Comment by FrouStyLe** [comment]
Hi
https://haugene.github.io/docker-transmission-openvpn/tips-tricks/

**Comment by abkierstein** [comment]
@erikjunker switching to the dev branch today fixed my resolution issue
```bash
# try switching this:
-t haugene/transmission-openvpn:latest

# to this:
-t haugene/transmission-openvpn:dev
```

**Comment by erikjunker** [comment]
> Hi
> https://haugene.github.io/docker-transmission-openvpn/tips-tricks/

So this might be where my lack of experience shows, but how do I add the dns parameter to the docker instance on my Synology NAS? I cannot find anywhere to input custom docker run commands. I can only use the GUI to create containers and it only allows me to add volumes, ports and environment variables



> @erikjunker switching to the dev branch today fixed my resolution issue
> 
> ```shell
> # try switching this:
> -t haugene/transmission-openvpn:latest
> 
> # to this:
> -t haugene/transmission-openvpn:dev
> ```

I did try a fresh copy of the dev branch yesterday, however it was the same result. I see no changes has been made to dev in the meantime, so I doubt it will fix whatever mess I have created here. Thanks for the suggestion though.

**Comment by slovenec88** [comment]
I am having the same issue. I switched from NordVPN to PIA today. I am running this on Ubuntu server on arm64 raspberrypi 4.

transmissionvpn    | Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.AaNEOm
transmissionvpn    | Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
transmissionvpn    | Starting OpenVPN using config austria.ovpn
transmissionvpn    | Modifying /etc/openvpn/pia/austria.ovpn for best behaviour in this container
transmissionvpn    | Setting OpenVPN credentials...
transmissionvpn    | adding route to local network 192.168.86.0/24 via 172.18.0.1 dev eth0
transmissionvpn    | Fri Dec  4 13:53:04 2020 OpenVPN 2.4.9 aarch64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
transmissionvpn    | Fri Dec  4 13:53:04 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
transmissionvpn    | Fri Dec  4 13:53:06 2020 AUTH: Received control message: AUTH_FAILED

  transmissionvpn:
    image: haugene/transmission-openvpn:dev (or latest)


    environment:
      - CREATE_TUN_DEVICE=true
      - LOCAL_NETWORK=${LAN_NETWORK}
      - OPENVPN_OPTS=${VPN_OPTIONS}
      - OPENVPN_PASSWORD=password
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=username
      - PGID=${PGID}
      - PUID=${PUID}
      - TRANSMISSION_DOWNLOAD_DIR=${TRANSMISSIONVPN_DOWNLOAD_DIR}
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_INCOMPLETE_DIR=${TRANSMISSIONVPN_INCOMPLETE_DIR}
      - TRANSMISSION_WATCH_DIR=${TRANSMISSIONVPN_WATCH_DIR}
      - TZ=${TZ}
      - OPENVPN_CONFIG=austria
      - PIA_OPENVPN_CONFIG_BUNDLE=openvpn

**Comment by haugene** [comment]
@erikjunker How to add DNS options on Synology is not an issue that I'm going to get into. I don't have a Synology so I don't know, but it's a default part of Docker to be able to specify this per container and it should be under networking somewhere. Possibly in an advanced tab or something. I'll let the issue stay open in case someone with a Synology is able to help you.

Also - when do you figure it out. It would be great if you could do some screenshots and maybe add it to the documentation as we get several questions on how to do this on NAS servers.

@slovenec88 Have you tried what is described in the FAQ? https://haugene.github.io/docker-transmission-openvpn/faq/#auth_received_control_message_auth_failed

**Comment by erikjunker** [comment]
I have just verified that my DNS server is set to 1.1.1.1 / 8.8.8.8, so it definitely shouldn't be the issue.
(For anyone else with DNS issues on the Synology NAS, you just need to map a custom resolv.conf file to /etc/resolv.conf under "Volumes").

I'm still getting the same error:

> Tracker error: "Tracker gave HTTP response code 0 (No Response)" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/torrent.c:623)
> Tracker gave HTTP response code 0 (No Response) (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
> Retrying announce in 308 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)

> Starting container with revision: 42d00652323b7b7fbee1689a54219599f4795a04
> Creating TUN device /dev/net/tun
> mknod: /dev/net/tun: File exists
> Using OpenVPN provider: PIA
> Provider PIA has a custom setup script, executing it
> Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.OLJkEF
> Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
> Starting OpenVPN using config sweden.ovpn
> Modifying /etc/openvpn/pia/sweden.ovpn for best behaviour in this container
> Setting OpenVPN credentials...
> adding route to local network 192.168.87.0/24 via 172.17.0.1 dev eth0
> Sat Dec  5 17:20:52 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
> Sat Dec  5 17:20:52 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
> Sat Dec  5 17:20:52 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Sat Dec  5 17:20:52 2020 CRL: loaded 1 CRLs from file [[INLINE]]
> Sat Dec  5 17:20:52 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]195.246.120.81:1198
> Sat Dec  5 17:20:52 2020 UDP link local: (not bound)
> Sat Dec  5 17:20:52 2020 UDP link remote: [AF_INET]195.246.120.81:1198
> Sat Dec  5 17:20:52 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Sat Dec  5 17:20:52 2020 [stockholm403] Peer Connection Initiated with [AF_INET]195.246.120.81:1198
> Sat Dec  5 17:20:53 2020 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
> Sat Dec  5 17:20:53 2020 OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3
> Sat Dec  5 17:20:53 2020 TUN/TAP device tun0 opened
> Sat Dec  5 17:20:53 2020 /sbin/ip link set dev tun0 up mtu 1500
> Sat Dec  5 17:20:53 2020 /sbin/ip addr add dev tun0 10.6.112.187/24 broadcast 10.6.112.255
> Sat Dec  5 17:20:53 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.6.112.187 255.255.255.0 init
> Up script executed with tun0 1500 1553 10.6.112.187 255.255.255.0 init
> Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.6.112.187
> Updating Transmission settings.json with values from env variables
> Using existing settings.json for Transmission /data/transmission-home/settings.json
> Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.6.112.187
> Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
> Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
> Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
> Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
> sed'ing True to true
> Enforcing ownership on transmission config directories
> Applying permissions to transmission config directories
> Setting owner for transmission paths to 1029:101
> Setting permission for files (644) and directories (755)
> Setting permission for watch directory (775) and its files (664)
> 
> 
> Transmission will run as
> 
> User name:   abc
> User uid:    1029
> User gid:    101
>
> 
> STARTING TRANSMISSION
> Provider PIA has a script for automatic port forwarding. Will run it now.
> If you want to disable this, set environment variable DISABLE_PORT_UPDATER=yes
> Transmission startup script complete.
> Sat Dec  5 17:20:54 2020 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
> Sat Dec  5 17:20:54 2020 Initialization Sequence Completed
> port is 31003
> the port has been bound to 31003  Sat Dec  5 17:21:01 UTC 2020
> transmission auth not required
> waiting for transmission to become responsive
> transmission became responsive
>      4     0%       None  Unknown      0.0     0.0   None  Idle        
> Sum:            39.97 GB               0.0     0.0
> setting transmission port to 31003
> localhost:9091/transmission/rpc/ responded: "success"
> Checking port...
> Port is open: Yes
> 
> initial setup complete!
> 
> waiting for rebind loop.................
> token expiry 1612588953
> remaining = 5400081
> the port has been bound to 31003  Sat Dec  5 17:51:12 UTC 2020
> the port has been bound to 31003  Sat Dec  5 18:21:12 UTC 2020


Is my error possibly related to this?

**Sat Dec 5 17:20:53 2020 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
Sat Dec 5 17:20:53 2020 OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3**

**Comment by mdgnys** [comment]
I was having similar issues with PIA.  Did a fresh install today to undo all of the changes I made the past few days trying to get it working.  Seems like the release today did some things to fix it (something about PIA changing URLs).

**Comment by UniverseXXX** [comment]
yet again, after today's container update, I'm getting `curl: (6) Could not resolve host: www.privateinternetaccess.com`
I've tried to apply the above workaround, but it won't help.
Falling back to 3.3/3.2/dev doesn't fix the issue either.

**Comment by haugene** [comment]
Now I'm not sure what issue you're having @erikjunker? You started with an issue not being able to connect to PIA due to DNS issues, but from your last logs it seems to connect just fine. Even updates Transmission with an open port from PIA so we know that Transmission is running.

So what is not working now?

**Comment by erikjunker** [comment]
@haugene It seems I'm able to connect to PIA now and both download/upload from the tracker, but it's still throwing an error:

![image](https://user-images.githubusercontent.com/57944222/101321815-49bee900-3866-11eb-8c56-93c313d84879.png)

This error is causing Radarr/Sonarr to not automatically import the content, since it thinks something is wrong. How can I resolve this?

**Comment by erikjunker** [comment]
I'm still having this issue 1½ months later. I tried updating my docker image to the latest version, but it's still returning the same error. I'm unable to download anything at all. Transmission seems to start up and connect to PIA just fine, but I cannot connect to the trackers (and I know it's not an issue with the trackers). This is my transmission log file:

> [2021-01-14 18:14:35.018] Transmission 3.00 (bb6b5a062e) started (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/session.c:769)
[2021-01-14 18:14:35.018] RPC Server Adding address to whitelist: 127.0.0.1 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956)
[2021-01-14 18:14:35.018] RPC Server Adding address to whitelist: ::1 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956)
[2021-01-14 18:14:35.018] RPC Server Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:1243)
[2021-01-14 18:14:35.018] Port Forwarding Stopped (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/port-forwarding.c:196)
[2021-01-14 18:14:35.018] UDP Failed to set receive buffer: requested 4194304, got 425984 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:97)
[2021-01-14 18:14:35.018] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:99)
[2021-01-14 18:14:35.018] UDP Failed to set send buffer: requested 1048576, got 425984 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:105)
[2021-01-14 18:14:35.018] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:107)
[2021-01-14 18:14:35.018] DHT Reusing old id (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:383)
[2021-01-14 18:14:35.018] DHT Bootstrapping from 140 IPv4 nodes (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:172)
[2021-01-14 18:14:35.018] Using settings from "/data/transmission-home" (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:646)
[2021-01-14 18:14:35.018] Saved "/data/transmission-home/settings.json" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/variant.c:1221)
[2021-01-14 18:14:35.018] Watching "/data/watch" for new .torrent files (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:698)
[2021-01-14 18:14:35.019] Loaded 1 torrents (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/session.c:2170)
[2021-01-14 18:14:35.019] web will verify tracker certs using envvar CURL_CA_BUNDLE: none (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/web.c:455)
[2021-01-14 18:14:35.019] web NB: this only works if you built against libcurl with openssl or gnutls, NOT nss (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/web.c:457)
[2021-01-14 18:14:35.019] web NB: invalid certs will show up as 'Could not connect to tracker' like many other errors (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/web.c:458)
[2021-01-14 18:14:38.019] Unable to create session lock file (22): Invalid argument (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/session-id.c:96)
[2021-01-14 18:14:51.019] Changed open file limit from 524288 to 1024 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/fdlimit.c:408)
[2021-01-14 18:15:06.020] Druk (2020) Tracker error: "Tracker gave HTTP response code 0 (No Response)" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/torrent.c:623)
[2021-01-14 18:15:06.020] Druk (2020) Tracker gave HTTP response code 0 (No Response) (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
[2021-01-14 18:15:06.020] Druk (2020) Retrying announce in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
[2021-01-14 18:15:57.019] Druk (2020) Tracker error: "Tracker gave HTTP response code 0 (No Response)" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/torrent.c:623)
[2021-01-14 18:15:57.019] Druk (2020) Tracker gave HTTP response code 0 (No Response) (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
[2021-01-14 18:15:57.019] Druk (2020) Retrying announce in 328 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)


I have disabled all firewall and anything that might be blocking it really, but I'm still unable to connect. Do you have any idea @haugene or is there any other logs that I can post here to help resolve the issue?

**Comment by pkishino** [comment]
try to delete images and storage for docker for this container then start fresh

**Comment by erikjunker** [comment]
Thanks @pkishino, however I tried that and every other option I could think of.

I ended up abandoning this project and going for a qbittorrent-openvpn image here on github instead. It worked flawlessly and immediately without any issues, so I'm 100% certain there's issues with this project :-(
I will close this issues now, since I am no longer looking for a solution..

**Comment by veganbeef** [comment]
I'm having the exact same issue as @erikjunker with my docker installation, and I'm also seeing the tracker error on my macOS transmission app. I wonder if it's something related to transmission itself and not this project.
