### ISSUE TITLE
Email notification on torrent complete

### ISSUE THREAD

**Issue by roupenig** [haugene/docker-transmission-openvpn#1586]
I am trying to set up a script that sends emails once torrents are completed.
I think I have set up everything correctly, but I'm not sure if the docker container is able to send emails.

I have a `transmission-pre-start.sh` script, which I know runs as it's outputting a text:
```
#!/bin/bash
chmod +x /scripts/on-complete.sh
echo "test" > /data/test1.txt
```

I have the `on-complete.sh` which I also know runs as I have tested below:
```
#!/bin/sh -xu
echo "test" > /data/test.txt
```

But once I try to exchange the text output by a command to send email, I don't get it. Here are a few I've tested which run well outside the docker container:
`printf "Subject: Test\nhello there a." | msmtp -a default a@gmail.com`
`echo "hello there username." | msmtp -a default a@gmail.com`

I'm quite the beginner when it comes to docker and I'm guessing the container doesn't have msmtp, or cannot access the msmtp settings.
Is there any way to send email from inside the docker (by some variables that I may have missed in docker-compose) or pass the command to outside and use msmtp?

Thanks.

**Comment by haugene** [comment]
There is no email support today. I'm a bit reluctant to add it as well as the container already is responsible for "enough". A container is meant to have a single responsibility and I think we're already pushing it to have a "one-stop-shop" solution for VPN, Torrent and Web proxy.

If I were doing a setup like this I think I would use Pushover and simply do a curl POST to their API to send emails. https://pushover.net/api

If not I would recommend that you build an email sender outside of the container on the local network and ping that to send emails for you. Or just echo output to a file and have inotify on the host run the email sending command for you.

**Comment by roupenig** [comment]
Using Pushover was a much easier and neater solution.
Thanks!
