### ISSUE TITLE
Torrent Done Script not running

### ISSUE THREAD

**Issue by d4g79** [haugene/docker-transmission-openvpn#1589]
This used to work but not sure why it is not working now. Every since the new updates were done this seemed to have stopped.

    "script-torrent-done-enabled": true,
    "script-torrent-done-filename": "/data/unrar.sh",

Thanks

**Comment by d4g79** [comment]
Has this something to do with busy box?

**Comment by d4g79** [comment]
seems the script does not work the simple script, as i think the latest transmission handles it differently.

using the below now and it is working again. Please close this.

#!/bin/bash

# The script could use more tesing, but it works well for my needs
function extract_rar() {
  isRar=$(ls | grep *.rar)
  if [ -n "$isRar" ]; then
    # Handle an edge case with some distributors
    isPart01="$(ls *.rar | egrep -i 'part01.rar|part1.rar')"
    if [ -n "$isPart01" ]; then
      isRar=$isPart01
    fi
    toUnrar="$(pwd)/$isRar"
    # we need to move to new location so sonarr doesn't try to mv before its done
    # also, unrar doesn't support changing the filename on extracting, makes sense a little bit
    pushd /mnt/media/Bittorrent/unrar_staging
    fileName="$(unrar e -y $toUnrar | egrep "^\.\.\..*OK" | awk '{ print $2 }')"
    # put it back so sonarr can now find it
    mv $fileName $(dirname $toUnrar)
    popd
  fi
}

echo "Starting  - $(date)"

cd "$TR_TORRENT_DIR"

if [ -d "$TR_TORRENT_NAME" ]; then
  cd "$TR_TORRENT_NAME"
  #handle multiple episode packs, like those that contain a whole season, or just a single episode
  for rar in $(find . -name '*.rar' -exec dirname {} \; | sort -u);
  do
    pushd $rar
    extract_rar
    popd
  done
fi

**Comment by d4g79** [comment]
If anyone can look at this script and see if there is anything wrong with it? it seems to work as intended.

#!/bin/bash
#
# Unrar script for extracting files when torrent completes in transmission.
#
function extract_rar() {
  isRar=$(ls | grep *.rar)
  if [ -n "$isRar" ]; then
    # Mutli-part handeling.
    isPart01="$(ls *.rar | egrep -i 'part01.rar|part1.rar')"
    if [ -n "$isPart01" ]; then
      isRar=$isPart01
    fi
    toUnrar="$(pwd)/$isRar"
    # Move to new location so sonarr does not try to process, as unrar does not support name changing during extraction.
    pushd /torrents/unrar_staging
    fileName="$(unrar e -y $toUnrar | egrep "^\.\.\..*OK" | awk '{ print $2 }')"
    # Move the file back for sonarr to locate and process.
    mv $fileName $(dirname $toUnrar)
    popd
  fi
}

echo "Starting  - $(date)"

cd "$TR_TORRENT_DIR"

if [ -d "$TR_TORRENT_NAME" ]; then
  cd "$TR_TORRENT_NAME"
  # Multiple-episode packs handeling, those that contain a whole season, or just a single episode.
  for rar in $(find . -name '*.rar' -exec dirname {} \; | sort -u);
  do
    pushd $rar
    extract_rar
    popd
  done
fi

**Comment by haugene** [comment]
I would guess this has to do with the busybox version of the tools as you say. Was the conclusion here that you got it working again and that we can close the issue? There seems to be another question after that, can you make it a bit more clear what you are asking for here?

**Comment by d4g79** [comment]
Please close ticket.
