### ISSUE TITLE
New vpn provider

### ISSUE THREAD

**Issue by notkaa** [haugene/docker-transmission-openvpn#160]
Is someone can add my vpn provider please ?

I use this one https://ra4wvpn.com I can give all the configuration. 
Many thank's

**Comment by notkaa** [comment]
Thank's for the add Haugene, here's the oven config : 
https://ra4wvpn.com/dl/RA4WVPN%20Client.zip

**Comment by notkaa** [comment]
[RA4WVPN config.zip](https://github.com/haugene/docker-transmission-openvpn/files/585573/RA4WVPN.config.zip)
I've made a mistake, here you have the good one (I've use this one on Tunnelblick)

Regards

**Comment by haugene** [comment]
Perfect, added it now. Test it out using the dev tag and let me know how it goes :)

**Comment by notkaa** [comment]
Thank's Illl test

**Comment by notkaa** [comment]
It work !!

**Comment by haugene** [comment]
Great stuff! Closing this issue then. It will only be available on the dev tag for a while until I make another release. There's a couple of improvements I want to do before so we'll see when that is :) But the dev tag is quite stable as well, so shouldn't be a problem.
