### ISSUE TITLE
PIA Port binding check needs to be every 14 mins not 30 mins

### ISSUE THREAD

**Issue by ensignvorik** [haugene/docker-transmission-openvpn#1601]
**Before creating this issue I have:**

- [X ] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X ] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X ] Tried to add as much relevant information to the issue as possible

**Describe the problem**
Currently the rebind of the port forward with PIA is done every 30 minutes. PIAs new documentation says the port is released if token is not renewed in 15 minutes. Therefore every 15 minutes the port is getting bind and unbound causing an adverse effect on torrent speeds.

"If you are using the Port Forwarding feature, you must leave the script window open. Port forwarding will time out after 15 minutes or less if the script window is closed. The terminal output will provide the forwarded port you have been assigned, as well as when it will time-out."

Source: https://www.privateinternetaccess.com/helpdesk/kb/articles/manual-connection-and-port-forwarding-scripts

![Screenshot 2020-12-09 125421](https://user-images.githubusercontent.com/16239702/101632602-0b6c2a00-3a1e-11eb-9aa2-f8f7c22e5ee8.jpg)

![Screenshot 2020-12-09 130807](https://user-images.githubusercontent.com/16239702/101633815-ba5d3580-3a1f-11eb-89a2-7c62ac6d23b6.jpg)

To fix this the rebind check needs to be done every 14 minutes to keep the port open.

Apologies if this is mentioned elsewhere or part of bigger PIA bug report, I did search but nothing stuck out like a sore thumb.

**Host system:**
QNAP NAS

**Comment by taylorcox75** [comment]
I got you covered. 
Initial issue I accidentally found this in #1479 

Since #1479  was unrelated to the timing issue **keep this issue open** and I'll use this as the one for my pull request fix.  Been running it about 6 days and will submit sometime today for you. 

#1592 is going to be a move to official scripts to avoid issues like this (with changes so you can still specify servers)

But the problem you might also have is the math for expiration is wrong and every 24 hours we think it's been 60 days and grab you a new port (not sure if transmission uses this new one or if it changes. Regardless all of the ones you are assigned are open assuming you have activity)

**Comment by taylorcox75** [comment]
@haugene  opened #1602 as a PR

**Comment by ensignvorik** [comment]
Thanks.

It defiantly still closes the port regardless of activity in the client around every 16/17 minutes, at least for me anyway, which seems to tie in with PIAs 15 minute limit. 

Previously on QNAP when I used Transmission physically on the NAS I'd set a cron job to rebind the port every 14 minutes which worked well, however for whatever reason I was getting terrible speeds via QNAPs QVPN tool so tried via Docker and it's much faster again, but that's by the by. Now just got this port forwarding binding issue, but I can live it for now knowing a fix is in the works.

Thanks

**Comment by ensignvorik** [comment]
PS> @taylorcox75  Think you've tagged a 4 year old enhancement above.

**Comment by haugene** [comment]
Yeah, I guess he meant #1602 :smile: After all, 2 is where the @ is at (pun intended)

**Comment by haugene** [comment]
@ensignvorik It's merged now at least. So you can pull the latest image and that should hopefully solve it :crossed_fingers:

**Comment by taylorcox75** [comment]
@ensignvorik out of curiosity what happens on other servers?  I essentially massaged their official headless scripts
https://github.com/pia-foss/manual-connections/blob/master/port_forwarding.sh
As you mentioned the function header says
```
# Now we have all required data to create a request to bind the port.
# We will repeat this request every 15 minutes, in order to keep the port
# alive. The servers have no mechanism to track your activity, so they
# will just delete the port forwarding if you don't send keepalives.
```
Last line of above link

```
    # sleep 15 minutes
    sleep 900
```

The only major difference in our curl function is they send a certificate which we don't have implemented yet. But  I wonder if your issue could be server specific, or something else.

If you have the time could you run their script 
Set bestRegion on line 145 of the get_region_and_token to your server name (sweden, panama,etc)

`wget https://github.com/pia-foss/manual-connections/archive/master.zip`

`./run_setup.sh` 

That way we can narrow it down to our end or theirs

**Comment by ensignvorik** [comment]
Thanks @taylorcox75 & @haugene for such a quick turnaround, looking loads better, randomly been checking port during that time including in the seconds before the next check and port remains open. 

![Screenshot 2020-12-10 053051](https://user-images.githubusercontent.com/16239702/101725780-2637b080-3aa9-11eb-8c5d-10c1634931b7.jpg)

Leave up to you if you want to close this right away or leave for a few days, but if you hear nothing back from me within several days you can assume all good.

**Comment by taylorcox75** [comment]
You're call. If something broke, honestly it would probably be related to the code restructuring I did and not the actual port problem.

**Comment by ensignvorik** [comment]
Keeping the port forward open for longer than 15 minutes is now resolved. Thank you.
