### ISSUE TITLE
Problem with DSM 7 

### ISSUE THREAD

**Issue by martin4eel** [haugene/docker-transmission-openvpn#1603]
**Before creating this issue I have:**

- [ X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X ] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X ] Tried to add as much relevant information to the issue as possible

**Describe the problem**
Transmission will not start after upgrading synology to DSM 7. 

**Host system:**
Synology DSM 7 (beta)

However the fix is:
Completely remove this line: --device = /dev/net/tun -d \

and add this instead: CREATE_TUN_DEVICE = true

Might be useful for someone else  :) 

/Martin

**Comment by martin4eel** [comment]
The fix is:
Completely remove this line: --device = /dev/net/tun -d \

and add this instead: CREATE_TUN_DEVICE = true

**Comment by Larosen** [comment]
> The fix is:
> 
> Completely remove this line: --device = /dev/net/tun -d \
> 
> 
> 
> and add this instead: CREATE_TUN_DEVICE = true

How do I remove and add a new line?

**Comment by venux92** [comment]
> The fix is:
> Completely remove this line: --device = /dev/net/tun -d \
> 
> and add this instead: CREATE_TUN_DEVICE = true

Same for me how do we remove `--device = /dev/net/tun -d \`
Thank you
