### ISSUE TITLE
Combustion favicon.ico not referenced properly in index.html

### ISSUE THREAD

**Issue by apoplol** [haugene/docker-transmission-openvpn#1604]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/) to a reasonable degree

**Describe your request**
/opt/transmission-ui/combustion-release/index.html references /favicon.ico when it should probably reference ./favicon.ico

Results in the favicon not loading

**Contextual information**
Not a big deal, but a nice-to-have.

**Comment by taylorcox75** [comment]
Unfortunately combustion is pulled from another repository, and that one hasn't had a new release since 2017

https://github.com/Secretmapper/combustion

**Comment by apoplol** [comment]
Ah, that's a shame. Thanks!
