### ISSUE TITLE
Whitelist keeps getting enabled

### ISSUE THREAD

**Issue by jsaltzman** [haugene/docker-transmission-openvpn#1605]
I am trying to connect to a new transmission container. I get the error that I am accessing from an unauthorized IP address. When I passthrough RPC_WHITELIST_ENABLED=false I get the same problem. When I delete the container and use the basic setup provided in the github docker compose file, I get the same problem. When I edit settings.json I get the same issue and when I reboot it is flagged to on. Can someone please help me? This is making my hair fallout. Running on a RPI4 if it matters.

**Comment by haugene** [comment]
Tried going through the debug instructions? https://haugene.github.io/docker-transmission-openvpn/debug/

**Comment by jsaltzman** [comment]
@haugene so - I know that Docker is running because portainer works. I know that the transmissions container is running because I see the log/terminal in portainer and it says that it is started.

**Comment by haugene** [comment]
Yes, it usually runs. But that's not your problem either is it? This is about accessing the web ui.
The minimal examples are made to separate networking issues in the container and configuration or application state errors on the host machine. But you haven't tried it?

I don't have much to go on here. The variable you're referring to should be TRANSMISSION_RPC_WHITELIST_ENABLED but it doesn't matter because it's false by default. That you have edited your settings.json file is great or not, I don't know the contents so it's hard to know. That is also the reason why the guide suggests to start the container without a volume because it limits the sources of error. It's all about locating the bug :)

You have to give some info about your setup at least. Logs, docker run command or docker-compose file. As it sounds like you're running this through portainer you can give the output of docker inspect?

**Comment by MayeulC** [comment]
I can confirm this issue. The settings generation works fine. Transmission itself overrides the file at startup. I confirmed that:

```
$ killall transmission-daemon
$ vi $TRANSMISSION_HOME/settings.json # edit whitelist to false
$ /usr/bin/transmission-daemon -g /data/transmission-home --logfile /data/transmission-home/transmission.log
```

Rolls back my edits to the file. This seems related to https://github.com/transmission/transmission/issues/929

As a workaround, setting another web UI prevents that setting from being overriden.

I have a bigger issue with the download location being shuffled around (it resets to `/root/downloads`), but it doesn't seem to be the same issue as doing the same procedure as above didn't reset it.

**Comment by MayeulC** [comment]
I tracked down my issue to #1615, though I do not have a complete explanation of the symptoms yet (it could also be another issue on top of it). I'll fix #1615 locally first, then report back.

@jsaltzman, what is your VPN provider? It could be related.

**Comment by clement-z** [comment]
Transmission sets the rpc whitelist setting to true by default [1], so it might very well be that if copying `default-settings.json` failed, transmission generated its own `settings.json` from the compiled-in defaults.

[1]: https://github.com/transmission/transmission/blob/cfce6e2e3a9b9d31a9dafedd0bdc8bf2cdb6e876/libtransmission/session.c#L381

**Comment by jsaltzman** [comment]
I’m using torguard. When I stripped down my docket compose to the bare minimum i was able to access without the whitelist but there is still some sort of bug.

**Comment by AKDub** [comment]
Same issue for me on a freshly spun up container on a new NUC. The workaround mentioned above about setting another web UI doesn't seem to work for me either.

**Comment by clement-z** [comment]
@AKDub see the related issue.

Also, the OP describes too little of his setup to really be sure about what's going on there. No logs, no `settings.json`, no `docker-compose.yml`, no info on which provider...

**Comment by Jack28** [comment]
There is a `settings.json` in `-v /your/storage/path/:/data` `transmission-home/settings.json` have you checked that?

**Comment by jsaltzman** [comment]
@Jack28 i did check that. Even with the whitelist flag off when I checked the settings.JSON it had whitelist enabled. When I manually changed the file it would get enabled right away.

**Comment by Jack28** [comment]
That change did it for me. There are only so many places to check.
I'm sure you know about the difference between `rpc-whitelist` and `rpc-host-whitelist` which seems to be a common mistake.
Sorry I couldn't help you.

**Comment by blddmnd** [comment]
It looks like @clement-z is right, transmission overrides my config file to default (with whitelist enabled) in case if I have some invalid env variables, e.g. `TRANSMISSION_RATIO_LIMIT=0.01`
In logs i can see this:
```
transmission-openvpn_1  | Could not coerce TRANSMISSION_RATIO_LIMIT value 0.01 to expected type <class 'int'>
transmission-openvpn_1  | sed'ing True to true
transmission-openvpn_1  | sed: /data/transmission-home/settings.json: No such file or directory
transmission-openvpn_1  |
```

But if I use the correct value (`TRANSMISSION_RATIO_LIMIT=1`) it works fine.

**Comment by clement-z** [comment]
Yes, there is some work on this side in PR #1610  so that you can specify floats. Another change is waiting for merge that stops the container when it fails to parse the settings (so that you don't use the compiled in defaults from transmission).

**Comment by IHadAThoth** [comment]
[As blddmnd said](https://github.com/haugene/docker-transmission-openvpn/issues/1605#issuecomment-751281036), i had "- TRANSMISSION_RATIO_LIMIT=1.2" as an option set in my docker-compose.yaml file. That caused the problem. 

What's the solution for setting the ratio limit via environment variables?

**Comment by clement-z** [comment]
Set it to a float value in `settings.json` first. Then always make the environment variable represent a float (e.g. don't use `2` but `2.0`).
