### ISSUE TITLE
Error using specific vpn conf file: Supplied config ch-08.protonvpn.com.tcp.ovpn.ovpn could not be found.

### ISSUE THREAD

**Issue by mrponzo** [haugene/docker-transmission-openvpn#1607]
Hello! I'm trying to use a specific country conf for PROTON VPN but there seems to be a problem and after trying with others and researching before posting this I could not find a sollution. 
If anyone could point me in the right direction I would be forever grateful. I'm a newbie but willing to learn :)

Thanks a lot!

```
Using OpenVPN provider: PROTONVPN
Supplied config ch-08.protonvpn.com.tcp.ovpn.ovpn could not be found.
Using default OpenVPN gateway for provider protonvpn
...
...
....
[nl-01.protonvpn.com] Peer Connection Initiated with [AF_INET]62.112.9.165:443
```

**Comment by haugene** [comment]
Hey. First of all it seems like you're using an old version of the image? You should do a docker pull of the image first. Secondly .ovpn is added automatically to the config you supply. I'm guessing that you are specifying the name with the extension, but you should not.

If it doesn't work after pulling and removing the file extention please post you run configuration. It's not always easy to say what you have configured wrong without seeing the setup.

**Comment by mrponzo** [comment]
First of all: thanks so much for replying!
If I'm not mistaken I'm running tag:latest
I've tried to search for how to print the configuration but trying "docker config ls--format string" I get an error. I really don't know how to access it... so sorry.

**Comment by mrponzo** [comment]
"Config": {
            "Hostname": "Transmission",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8888/tcp": {},
                "9091/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "OPENVPN_USERNAME=++++++",
                "OPENVPN_PASSWORD=++++++",
                "OPENVPN_PROVIDER=PROTONVPN",
                "GLOBAL_APPLY_PERMISSIONS=true",
                "TRANSMISSION_ALT_SPEED_DOWN=50",
                "TRANSMISSION_ALT_SPEED_ENABLED=false",
                "TRANSMISSION_ALT_SPEED_TIME_BEGIN=540",
                "TRANSMISSION_ALT_SPEED_TIME_DAY=127",
                "TRANSMISSION_ALT_SPEED_TIME_ENABLED=false",
                "TRANSMISSION_ALT_SPEED_TIME_END=1020",
                "TRANSMISSION_ALT_SPEED_UP=50",
                "TRANSMISSION_BIND_ADDRESS_IPV4=0.0.0.0",
                "TRANSMISSION_BIND_ADDRESS_IPV6=::",
                "TRANSMISSION_BLOCKLIST_ENABLED=false",
                "TRANSMISSION_BLOCKLIST_URL=http://www.example.com/blocklist",
                "TRANSMISSION_CACHE_SIZE_MB=4",
                "TRANSMISSION_DHT_ENABLED=true",
                "TRANSMISSION_DOWNLOAD_DIR=/data/completed",
                "TRANSMISSION_DOWNLOAD_LIMIT=100",
                "TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0",
                "TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true",
                "TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5",
                "TRANSMISSION_ENCRYPTION=1",
                "TRANSMISSION_IDLE_SEEDING_LIMIT=0",
                "TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false",
                "TRANSMISSION_INCOMPLETE_DIR=/data/incomplete",
                "TRANSMISSION_INCOMPLETE_DIR_ENABLED=true",
                "TRANSMISSION_LPD_ENABLED=false",
                "TRANSMISSION_MAX_PEERS_GLOBAL=200",
                "TRANSMISSION_MESSAGE_LEVEL=2",
                "TRANSMISSION_PEER_CONGESTION_ALGORITHM=",
                "TRANSMISSION_PEER_ID_TTL_HOURS=6",
                "TRANSMISSION_PEER_LIMIT_GLOBAL=200",
                "TRANSMISSION_PEER_LIMIT_PER_TORRENT=50",
                "TRANSMISSION_PEER_PORT=51413",
                "TRANSMISSION_PEER_PORT_RANDOM_HIGH=65535",
                "TRANSMISSION_PEER_PORT_RANDOM_LOW=49152",
                "TRANSMISSION_PEER_PORT_RANDOM_ON_START=false",
                "TRANSMISSION_PEER_SOCKET_TOS=default",
                "TRANSMISSION_PEX_ENABLED=true",
                "TRANSMISSION_PORT_FORWARDING_ENABLED=false",
                "TRANSMISSION_PREALLOCATION=1",
                "TRANSMISSION_PREFETCH_ENABLED=1",
                "TRANSMISSION_QUEUE_STALLED_ENABLED=true",
                "TRANSMISSION_QUEUE_STALLED_MINUTES=30",
                "TRANSMISSION_RATIO_LIMIT=0",
                "TRANSMISSION_RATIO_LIMIT_ENABLED=true",
                "TRANSMISSION_RENAME_PARTIAL_FILES=true",
                "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true",
                "TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0",
                "TRANSMISSION_RPC_ENABLED=true",
                "TRANSMISSION_RPC_HOST_WHITELIST=",
                "TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=false",
                "TRANSMISSION_RPC_PASSWORD=++++++",
                "TRANSMISSION_RPC_PORT=9091",
                "TRANSMISSION_RPC_URL=/transmission/",
                "TRANSMISSION_RPC_USERNAME=++++++",
                "TRANSMISSION_RPC_WHITELIST=127.0.0.1",
                "TRANSMISSION_RPC_WHITELIST_ENABLED=false",
                "TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=true",
                "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=false",
                "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=",
                "TRANSMISSION_SEED_QUEUE_ENABLED=false",
                "TRANSMISSION_SEED_QUEUE_SIZE=10",
                "TRANSMISSION_SPEED_LIMIT_DOWN=100",
                "TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false",
                "TRANSMISSION_SPEED_LIMIT_UP=100",
                "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false",
                "TRANSMISSION_START_ADDED_TORRENTS=true",
                "TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false",
                "TRANSMISSION_UMASK=2",
                "TRANSMISSION_UPLOAD_LIMIT=100",
                "TRANSMISSION_UPLOAD_LIMIT_ENABLED=0",
                "TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=14",
                "TRANSMISSION_UTP_ENABLED=true",
                "TRANSMISSION_WATCH_DIR=/data/watch",
                "TRANSMISSION_WATCH_DIR_ENABLED=true",
                "TRANSMISSION_HOME=/data/transmission-home",
                "TRANSMISSION_WATCH_DIR_FORCE_GENERIC=false",
                "ENABLE_UFW=false",
                "UFW_ALLOW_GW_NET=false",
                "UFW_EXTRA_PORTS=",
                "UFW_DISABLE_IPTABLES_REJECT=false",
                "TRANSMISSION_WEB_UI=transmission-web-control",
                "PUID=1032",
                "PGID=100",
                "TRANSMISSION_WEB_HOME=",
                "DROP_DEFAULT_ROUTE=",
                "WEBPROXY_ENABLED=false",
                "WEBPROXY_PORT=8888",
                "HEALTH_CHECK_HOST=google.com",
                "TZ=Europe/Vienna",
                "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60",
                "OPENVPN_CONFIG=ch-08.protonvpn.com.tcp.ovpn",
                "LOCAL_NETWORK=192.168.1.0/24"
            ]

**Comment by haugene** [comment]
Using tag "latest" does not mean that you have the newest build. Run `docker pull haugene/transmission-openvpn` to update.
The file extension part I was referring to is this `"OPENVPN_CONFIG=ch-08.protonvpn.com.tcp.ovpn"` that should be without .ovpn at the end. But I think you have to pull the image anyways, because protonvpn got new configs relatively recently if I remember correctly.

**Comment by mrponzo** [comment]
Thanks a lot @haugene. It did work :)

**Comment by slopsjon** [comment]
I have a similar problem with the latest, works ok with 2.14. I'm connecting to my own server which runs openvpn. I have left off the .ovpn in the config setting and run docker pull haugene/transmission-openvpn.

Starting container with revision: 3d97cd5302985c1a710f46ab0c311f721f224fc6
Creating TUN device /dev/net/tun
Using OpenVPN provider: CUSTOM
Supplied config aws.ovpn could not be found.
Your options for this provider are:
default.ovpn

CREATE_TUN_DEVICE | true
-- | --
OPENVPN_PROVIDER | CUSTOM
OPENVPN_CONFIG | aws
LOCAL_NETWORK | 192.168.1.0/24
OPENVPN_USERNAME | xxxxxx
OPENVPN_PASSWORD | xxxxxx
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LC_ALL | C.UTF-8
DEBIAN_FRONTEND | noninteractive
UDEV | off
QEMU_CPU | arm1176
GLOBAL_APPLY_PERMISSIONS | true
TRANSMISSION_ALT_SPEED_DOWN | 50
TRANSMISSION_ALT_SPEED_ENABLED | false
TRANSMISSION_ALT_SPEED_TIME_BEGIN | 540
TRANSMISSION_ALT_SPEED_TIME_DAY | 127
TRANSMISSION_ALT_SPEED_TIME_ENABLED | false
TRANSMISSION_ALT_SPEED_TIME_END | 1020
TRANSMISSION_ALT_SPEED_UP | 50
TRANSMISSION_BIND_ADDRESS_IPV4 | 0.0.0.0
TRANSMISSION_BIND_ADDRESS_IPV6 | ::
TRANSMISSION_BLOCKLIST_ENABLED | false
TRANSMISSION_BLOCKLIST_URL | http://www.example.com/blocklist
TRANSMISSION_CACHE_SIZE_MB | 4
TRANSMISSION_DHT_ENABLED | true
TRANSMISSION_DOWNLOAD_DIR | /data/completed
TRANSMISSION_DOWNLOAD_LIMIT | 100
TRANSMISSION_DOWNLOAD_LIMIT_ENABLED | 0
TRANSMISSION_DOWNLOAD_QUEUE_ENABLED | true
TRANSMISSION_DOWNLOAD_QUEUE_SIZE | 5
TRANSMISSION_ENCRYPTION | 1
TRANSMISSION_IDLE_SEEDING_LIMIT | 30
TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED | false
TRANSMISSION_INCOMPLETE_DIR | /data/incomplete
TRANSMISSION_INCOMPLETE_DIR_ENABLED | true
TRANSMISSION_LPD_ENABLED | false
TRANSMISSION_MAX_PEERS_GLOBAL | 200
TRANSMISSION_MESSAGE_LEVEL | 2
TRANSMISSION_PEER_ID_TTL_HOURS | 6
TRANSMISSION_PEER_LIMIT_GLOBAL | 200
TRANSMISSION_PEER_LIMIT_PER_TORRENT | 50
TRANSMISSION_PEER_PORT | 51413
TRANSMISSION_PEER_PORT_RANDOM_HIGH | 65535
TRANSMISSION_PEER_PORT_RANDOM_LOW | 49152
TRANSMISSION_PEER_PORT_RANDOM_ON_START | false
TRANSMISSION_PEER_SOCKET_TOS | default
TRANSMISSION_PEX_ENABLED | true
TRANSMISSION_PORT_FORWARDING_ENABLED | false
TRANSMISSION_PREALLOCATION | 1
TRANSMISSION_PREFETCH_ENABLED | 1
TRANSMISSION_QUEUE_STALLED_ENABLED | true
TRANSMISSION_QUEUE_STALLED_MINUTES | 30
TRANSMISSION_RATIO_LIMIT | 2
TRANSMISSION_RATIO_LIMIT_ENABLED | false
TRANSMISSION_RENAME_PARTIAL_FILES | true
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED | false
TRANSMISSION_RPC_BIND_ADDRESS | 0.0.0.0
TRANSMISSION_RPC_ENABLED | true
TRANSMISSION_RPC_HOST_WHITELIST_ENABLED | false
TRANSMISSION_RPC_PASSWORD | password
TRANSMISSION_RPC_PORT | 9091
TRANSMISSION_RPC_URL | /transmission/
TRANSMISSION_RPC_USERNAME | username
TRANSMISSION_RPC_WHITELIST | 127.0.0.1
TRANSMISSION_RPC_WHITELIST_ENABLED | false
TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED | true
TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED | false
TRANSMISSION_SEED_QUEUE_ENABLED | false
TRANSMISSION_SEED_QUEUE_SIZE | 10
TRANSMISSION_SPEED_LIMIT_DOWN | 100
TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED | false
TRANSMISSION_SPEED_LIMIT_UP | 100
TRANSMISSION_SPEED_LIMIT_UP_ENABLED | false
TRANSMISSION_START_ADDED_TORRENTS | true
TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES | false
TRANSMISSION_UMASK | 2
TRANSMISSION_UPLOAD_LIMIT | 100
TRANSMISSION_UPLOAD_LIMIT_ENABLED | 0
TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT | 14
TRANSMISSION_UTP_ENABLED | false
TRANSMISSION_WATCH_DIR | /data/watch
TRANSMISSION_WATCH_DIR_ENABLED | true
TRANSMISSION_HOME | /data/transmission-home
TRANSMISSION_WATCH_DIR_FORCE_GENERIC | false
ENABLE_UFW | false
UFW_ALLOW_GW_NET | false
UFW_DISABLE_IPTABLES_REJECT | false
WEBPROXY_ENABLED | false
WEBPROXY_PORT | 8888
DOCKER_LOG | false
HEALTH_CHECK_HOST | google.com
LOG_TO_STDOUT | false
REVISION | 3d97cd5302985c1a710f46ab0c311f721f224fc6
UFW_EXTRA_PORTS |  
PUID |  
PGID |  
DROP_DEFAULT_ROUTE |  
WEBPROXY_USERNAME |  
WEBPROXY_PASSWORD |
