### ISSUE TITLE
LOCAL_NETWORK is broken for multiple interfaces

### ISSUE THREAD

**Issue by vtavernier** [haugene/docker-transmission-openvpn#1609]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X] Tried to add as much relevant information to the issue as possible

**Describe the problem**

The `LOCAL_NETWORK` configuration option supports, according to the docs, multiple local networks CIDRs separated by commas. This works if the relevant networks are *outside* Docker, i.e. they're network from outside the container host.

However, if a Docker container is added to multiple Docker networks, each network will result in one network interface created (and the corresponding IP/routes assigned to that interface).

The problem is caused by these lines: https://github.com/haugene/docker-transmission-openvpn/blob/53d3f05b7a1cad1a93f98fb99dec4fc9fee5ba6e/openvpn/start.sh#L204-L219

If a local network is specified and doesn't use the same interface (`$INT` in the above script) as the default route, this breaks when trying to call `ip route add` since we generate an invalid route.

**systemd unit starting the container**

```systemd
# From systemd unit
ExecStartPre=/usr/bin/docker create \
    --cap-add=NET_ADMIN \
#  [...]
    -e CREATE_TUN_DEVICE=true \
    -e OPENVPN_PROVIDER=PIA \
    -e OPENVPN_CONFIG=switzerland \
#  [...]
    -e LOCAL_NETWORK=192.168.55.0/24,172.100.0.0/24,127.0.0.0/8 \
    -e ENABLE_UFW=true \
    -e GLOBAL_APPLY_PERMISSIONS=false \
    -e WEBPROXY_ENABLED=false \
#  [...]
    --name=transmission-openvpn \
    --hostname=transmission-openvpn \
    haugene/transmission-openvpn:dev
ExecStartPre=/usr/bin/docker network connect my-net transmission-openvpn
ExecStart=/usr/bin/docker start -a transmission-openvpn
```

**Logs**

```
[output from systemd for the unit controlling the container]
déc. 15 13:07:25 nas systemd[1]: Started Transmission-OpenVPN container.
déc. 15 13:07:26 nas docker[2354]: Starting container with revision: 53d3f05b7a1cad1a93f98fb99dec4fc9fee5ba6e
déc. 15 13:07:26 nas docker[2354]: Creating TUN device /dev/net/tun
déc. 15 13:07:26 nas docker[2354]: Using OpenVPN provider: PIA
déc. 15 13:07:26 nas docker[2354]: Provider PIA has a custom setup script, executing it
déc. 15 13:07:26 nas docker[2354]: Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.FoaglE
déc. 15 13:07:27 nas docker[2354]: Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
déc. 15 13:07:27 nas docker[2354]: Starting OpenVPN using config switzerland.ovpn
déc. 15 13:07:27 nas docker[2354]: Modifying /etc/openvpn/pia/switzerland.ovpn for best behaviour in this container
déc. 15 13:07:27 nas docker[2354]: Setting OpenVPN credentials...
déc. 15 13:07:27 nas docker[2354]: enabling firewall
déc. 15 13:07:28 nas docker[2354]: Firewall is active and enabled on system startup
déc. 15 13:07:28 nas docker[2354]: allowing 172.17.0.1 through the firewall to port 9091
déc. 15 13:07:28 nas docker[2354]: Rule added
déc. 15 13:07:28 nas docker[2354]: adding route to local network 192.168.55.0/24 via 172.17.0.1 dev eth0
déc. 15 13:07:28 nas docker[2354]: allowing 192.168.55.0/24 through the firewall to port 9091
déc. 15 13:07:29 nas docker[2354]: Rule added
déc. 15 13:07:29 nas docker[2354]: adding route to local network 172.100.0.1/24 via 172.17.0.1 dev eth0 <---- should be eth1, gw is wrong, and route is actually not needed
déc. 15 13:07:29 nas docker[2354]: RTNETLINK answers: Invalid argument
déc. 15 13:07:30 nas systemd[1]: transmission-openvpn.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
déc. 15 13:07:30 nas systemd[1]: transmission-openvpn.service: Failed with result 'exit-code'.
[rest truncated, container just exiting]
```

**Host system:**

    Debian 10: kernel 4.19.160-2 (2020-11-28) x86_64
    Docker: 18.09.1+dfsg1-7.1+deb10u2

**Proposed solution**
Extract the network information (`$GW`, `$INT`) for each local network in the loop using the same kind of strategy (`ip route list match $localNet` probably). I tried implementing a solution but I have the following question: what is the purpose of the `LOCAL_NETWORK` option?

In my case, I am interested in allowing RPC access to all the specified local networks through ufw. However, what is the use case for adding routes to these networks through the default gateway? If the network interface is managed by docker, it will already have the right routes set up. I'm interested in comments on this fact.

We might want a distinct option for local network routes and ufw rules if adding routes was to be made optional?

**Comment by clement-z** [comment]
I think the idea is that if `DROP_DEFAULT_ROUTE` is true, only routes to the local network defined by `LOCAL_NETWORK` will remain.

I think the network section and possibly more would benefit from a redesign with a clearly defined architecture...
