### ISSUE TITLE
torrents won't start download

### ISSUE THREAD

**Issue by tvdu29** [haugene/docker-transmission-openvpn#161]
Can please somebody help me ?

Every torrent i try have peers connections but no data is downloaded.
I'm using this container with private internet access set by default on UK-Southampton.

here is the log 
`Got new port  from piam
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 400: Bad Request`

thanks in advance.

**Comment by fdecourt** [comment]
Maybe you can check my investigation there https://github.com/haugene/docker-transmission-openvpn/issues/135
I have a problem updating the DNS table, so I need a script after package launch.
Good luck

**Comment by haugene** [comment]
Could be DNS issue. Don't think the rpc calls have much to do with it though. Worst case it wouldn't open the port. Please provide the complete log...

**Comment by tvdu29** [comment]
thanks for your responses but this problem was apparently time-related as the downloads started the day next my post (sorry for the wait i was afk of the computer running the container =S ).
Now it seems that an other problem as occured becase it will download correctly every torrent I mannualy give to it but when Sickrage throw a torrent at it, it will appear as the container is doing is job correctly (numbers of peers shown, downloading...) but the file isn't downloaded. Also, the log keep showing this error : 

`Thu Nov 10 17:58:28 2016 RESOLVE: Cannot resolve host address: uk-southampton.privateinternetaccess.com: Temporary failure in name resolution`

I run the container with the following command :

`docker run --privileged -d -v /Volumes/LaCie/sickrage/downloads/:/data -e "OPENVPN_PROVIDER=PIA" -e "OPENVPN_CONFIG=UK Southampton" -e "OPENVPN_USERNAME=XXXXXXXX" -e "OPENVPN_PASSWORD=XXXXXXXX" -e "LOCAL_NETWORK=192.168.1.0/24" --dns 8.8.8.8 --dns 8.8.4.4 --name "transmission" -p 9091:9091 haugene/transmission-openvpnls`

**Comment by haugene** [comment]
So definitely a dns issue then. I'm going to be short as I'm on my phone, but try the --ping-exit flags described in the readme and --restart=always.

**Comment by pkishino** [comment]
Closing for now as answer provided
