### ISSUE TITLE
Infinitely stuck in "health: starting" with "Uptime" under 1 minute even after a week

### ISSUE THREAD

**Issue by runeb6** [haugene/docker-transmission-openvpn#1618]
After a bug a few weeks ago I experienced a power outage then a random Kernel panic a week later (non repeated, probably random a month later no reoccurance)

Since I haven't been able to get Transmission to start and run, even deleted the container and repulled it with the same config (didn't change before or after the issue started)

Any ideas on what could have happened or what places I could look for logs to find the root issue?
![image](https://user-images.githubusercontent.com/64443113/102680138-5bb05e00-417b-11eb-9298-2cdb47e5bcb9.png)

**Comment by ilike2burnthing** [comment]
Rename settings.json (or the whole transmission-home folder) and restart the container. See if you can find any significant differences in between the old and new settings files.

**Comment by runeb6** [comment]
> Rename settings.json (or the whole transmission-home folder) and restart the container. See if you can find any significant differences between the old and new settings files.

I managed to rename the old directory, then I completely wiped and reloaded the docker entirely and redid the configuration, It seems that the interface changed on me so something might have partly updated and failed an a weird way and may have also broken the configuration?
can't fully explain it, but there is now a new UI (old one behind a button) so I am not sure if that is related or not?

**Comment by ilike2burnthing** [comment]
Sounds like you're using the Transmission-Web-Control UI - https://haugene.github.io/docker-transmission-openvpn/config-options/#alternative_web_uis

**Comment by clement-z** [comment]
@runeb6 What provider are you using ? It may be related to #1615
