### ISSUE TITLE
PIA config download failed: `curl: (47) Maximum (50) redirects followed`

### ISSUE THREAD

**Issue by clement-z** [haugene/docker-transmission-openvpn#1619]
This morning, my container was unable to start due to failing to download the PIA config files. I tested and the command line, and I had the same error:

```
$ curl -sSL https://www.privateinternetaccess.com/openvpn/openvpn.zip -O
curl: (47) Maximum (50) redirects followed
```

However, it worked in the browser. Following info from [here](https://superuser.com/questions/1607731/a-site-getting-too-many-redirects-response-on-curl-but-works-fine-in-a-browser) and [here](https://unix.stackexchange.com/questions/497741/what-is-the-purpose-of-use-curl-cookie-with-a-file-that-doesnt-exist), I added the `--cookie` switch:

`curl -sSL --cookie /dev/null https://www.privateinternetaccess.com/openvpn/openvpn.zip -O`

This essentially tells curl to send back the cookies, thus avoiding the infinite redirect.

Curiously though, now it seems to work correctly without the fix, so I am not sure whether we need to do something about it... Was it a momentary mistake on the PIA side ? I have no idea. 🤷

**Comment by XenHat** [comment]
Getting this issue after updating my container today. Not sure why.

**Comment by ppeter10** [comment]
same for me as @XenHat
