### ISSUE TITLE
docker-compose broken on armh

### ISSUE THREAD

**Issue by bgulla** [haugene/docker-transmission-openvpn#162]
Latest & Greatest Kernel & Docker.

pirate@black-pearl[~/builds/docker-transmission-openvpn] > docker-compose -f docker-compose-armhf.yml up
ERROR: The Compose file './docker-compose-armhf.yml' is invalid because:
transmission.build contains an invalid type, it should be a string

**Comment by pkishino** [comment]
Please try out the PR I made, it looks like it works for me but I only tried the non-arm version.
I was getting same error on both versions.
