### ISSUE TITLE
TLS handshake error with PIA

### ISSUE THREAD

**Issue by TheDowdy** [haugene/docker-transmission-openvpn#1622]
**Before creating this issue I have:**

- [X ] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [ X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [ X] Tried to add as much relevant information to the issue as possible

**Describe the problem**

I've searched for others with this issue but still can't figure out what the solution ought to be. Also I'm a bit of a noob with this kind of stuff so apologies if I'm being an idiot.

The container was running perfectly all year, but recently I noticed I couldn't connect to Transmission. Checked the container and the log is looping through the TLS handshake issue. I'm with PIA as the provider.

It's driving me kind of mad here now trying to figure out how to resolve this so I'd appreciate any assistance!

**Add your docker run command or docker-compose file**

I'm running from the Synology GUI so exported the container settings as follows:
{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "dumb-init /etc/openvpn/start.sh",
   "cpu_priority" : 50,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : true,
   "env_variables" : [
      {
         "key" : "OPENVPN_CONFIG",
         "value" : "France"
      },
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "DEBIAN_FRONTEND",
         "value" : "noninteractive"
      },
      {
         "key" : "OPENVPN_USERNAME",
         "value" : "<redacted>"
      },
      {
         "key" : "OPENVPN_PASSWORD",
         "value" : "<redacted>"
      },
      {
         "key" : "OPENVPN_PROVIDER",
         "value" : "PIA"
      },
      {
         "key" : "GLOBAL_APPLY_PERMISSIONS",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_DOWN",
         "value" : "50"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_BEGIN",
         "value" : "540"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_DAY",
         "value" : "127"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_END",
         "value" : "1020"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_UP",
         "value" : "50"
      },
      {
         "key" : "TRANSMISSION_BIND_ADDRESS_IPV4",
         "value" : "0.0.0.0"
      },
      {
         "key" : "TRANSMISSION_BIND_ADDRESS_IPV6",
         "value" : "::"
      },
      {
         "key" : "TRANSMISSION_BLOCKLIST_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_BLOCKLIST_URL",
         "value" : "http://www.example.com/blocklist"
      },
      {
         "key" : "TRANSMISSION_CACHE_SIZE_MB",
         "value" : "4"
      },
      {
         "key" : "TRANSMISSION_DHT_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_DIR",
         "value" : "/data/completed"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_LIMIT",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_LIMIT_ENABLED",
         "value" : "0"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_QUEUE_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_QUEUE_SIZE",
         "value" : "5"
      },
      {
         "key" : "TRANSMISSION_ENCRYPTION",
         "value" : "1"
      },
      {
         "key" : "TRANSMISSION_IDLE_SEEDING_LIMIT",
         "value" : "30"
      },
      {
         "key" : "TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_INCOMPLETE_DIR",
         "value" : "/data/incomplete"
      },
      {
         "key" : "TRANSMISSION_INCOMPLETE_DIR_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_LPD_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_MAX_PEERS_GLOBAL",
         "value" : "200"
      },
      {
         "key" : "TRANSMISSION_MESSAGE_LEVEL",
         "value" : "2"
      },
      {
         "key" : "TRANSMISSION_PEER_CONGESTION_ALGORITHM",
         "value" : ""
      },
      {
         "key" : "TRANSMISSION_PEER_ID_TTL_HOURS",
         "value" : "6"
      },
      {
         "key" : "TRANSMISSION_PEER_LIMIT_GLOBAL",
         "value" : "200"
      },
      {
         "key" : "TRANSMISSION_PEER_LIMIT_PER_TORRENT",
         "value" : "50"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT",
         "value" : "51413"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT_RANDOM_HIGH",
         "value" : "65535"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT_RANDOM_LOW",
         "value" : "49152"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT_RANDOM_ON_START",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_PEER_SOCKET_TOS",
         "value" : "default"
      },
      {
         "key" : "TRANSMISSION_PEX_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_PORT_FORWARDING_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_PREALLOCATION",
         "value" : "1"
      },
      {
         "key" : "TRANSMISSION_PREFETCH_ENABLED",
         "value" : "1"
      },
      {
         "key" : "TRANSMISSION_QUEUE_STALLED_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_QUEUE_STALLED_MINUTES",
         "value" : "30"
      },
      {
         "key" : "TRANSMISSION_RATIO_LIMIT",
         "value" : "2"
      },
      {
         "key" : "TRANSMISSION_RATIO_LIMIT_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_RENAME_PARTIAL_FILES",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_RPC_BIND_ADDRESS",
         "value" : "0.0.0.0"
      },
      {
         "key" : "TRANSMISSION_RPC_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_RPC_HOST_WHITELIST",
         "value" : ""
      },
      {
         "key" : "TRANSMISSION_RPC_HOST_WHITELIST_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_RPC_PASSWORD",
         "value" : "password"
      },
      {
         "key" : "TRANSMISSION_RPC_PORT",
         "value" : "9091"
      },
      {
         "key" : "TRANSMISSION_RPC_URL",
         "value" : "/transmission/"
      },
      {
         "key" : "TRANSMISSION_RPC_USERNAME",
         "value" : "username"
      },
      {
         "key" : "TRANSMISSION_RPC_WHITELIST",
         "value" : "127.0.0.1"
      },
      {
         "key" : "TRANSMISSION_RPC_WHITELIST_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME",
         "value" : ""
      },
      {
         "key" : "TRANSMISSION_SEED_QUEUE_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SEED_QUEUE_SIZE",
         "value" : "10"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_DOWN",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_UP",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_UP_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_START_ADDED_TORRENTS",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_UMASK",
         "value" : "2"
      },
      {
         "key" : "TRANSMISSION_UPLOAD_LIMIT",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_UPLOAD_LIMIT_ENABLED",
         "value" : "0"
      },
      {
         "key" : "TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT",
         "value" : "14"
      },
      {
         "key" : "TRANSMISSION_UTP_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_WATCH_DIR",
         "value" : "/data/watch"
      },
      {
         "key" : "TRANSMISSION_WATCH_DIR_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_HOME",
         "value" : "/data/transmission-home"
      },
      {
         "key" : "TRANSMISSION_WATCH_DIR_FORCE_GENERIC",
         "value" : "false"
      },
      {
         "key" : "ENABLE_UFW",
         "value" : "false"
      },
      {
         "key" : "UFW_ALLOW_GW_NET",
         "value" : "false"
      },
      {
         "key" : "UFW_EXTRA_PORTS",
         "value" : ""
      },
      {
         "key" : "UFW_DISABLE_IPTABLES_REJECT",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_WEB_UI",
         "value" : ""
      },
      {
         "key" : "PUID",
         "value" : ""
      },
      {
         "key" : "PGID",
         "value" : ""
      },
      {
         "key" : "TRANSMISSION_WEB_HOME",
         "value" : ""
      },
      {
         "key" : "DROP_DEFAULT_ROUTE",
         "value" : ""
      },
      {
         "key" : "WEBPROXY_ENABLED",
         "value" : "false"
      },
      {
         "key" : "WEBPROXY_PORT",
         "value" : "8888"
      },
      {
         "key" : "WEBPROXY_USERNAME",
         "value" : ""
      },
      {
         "key" : "WEBPROXY_PASSWORD",
         "value" : ""
      },
      {
         "key" : "HEALTH_CHECK_HOST",
         "value" : "google.com"
      },
      {
         "key" : "DOCKER_LOG",
         "value" : "false"
      }
   ],
   "exporting" : false,
   "id" : "2e3dc5e843685649a8d164078a095511883ce77e32ed30ea1fead781254f16a0",
   "image" : "haugene/transmission-openvpn:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "haugene-transmission-openvpn1",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 8888,
         "host_port" : 30000,
         "type" : "tcp"
      },
      {
         "container_port" : 9091,
         "host_port" : 30001,
         "type" : "tcp"
      }
   ],
   "privileged" : true,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/transmission-openvpn/resolv.conf",
         "mount_point" : "/etc/resolv.conf",
         "type" : "ro"
      },
      {
         "host_volume_file" : "/downloads",
         "mount_point" : "/data/completed",
         "type" : "rw"
      }
   ]
}

**Logs**

2020-12-19 21:34:19 | stdout | Sat Dec 19 21:34:19 2020 SIGUSR1[soft,tls-error] received, process restarting
-- | -- | --
2020-12-19 21:34:19 | stdout | Sat Dec 19 21:34:19 2020 TLS Error: TLS handshake failed
  |   |  
2020-12-19 21:34:19 | stdout | Sat Dec 19 21:34:19 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
  |   |  
2020-12-19 21:33:18 | stdout | Sat Dec 19 21:33:18 2020 UDP link remote: [AF_INET]******:1198
  |   |  
2020-12-19 21:33:18 | stdout | Sat Dec 19 21:33:18 2020 UDP link local: (not bound)
  |   |  
2020-12-19 21:33:18 | stdout | Sat Dec 19 21:33:18 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]*****:1198
  |   |  
2020-12-19 21:33:18 | stdout | Sat Dec 19 21:33:18 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
  |   |  
2020-12-19 21:31:58 | stdout | Sat Dec 19 21:31:58 2020 SIGUSR1[soft,tls-error] received, process restarting
2020-12-19 21:31:58 | stdout | Sat Dec 19 21:31:58 2020 TLS Error: TLS handshake failed
  |   |  
2020-12-19 21:31:58 | stdout | Sat Dec 19 21:31:58 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
  |   |  
2020-12-19 21:30:58 | stdout | Sat Dec 19 21:30:58 2020 UDP link remote: [AF_INET]*****:1198
  |   |  
2020-12-19 21:30:58 | stdout | Sat Dec 19 21:30:58 2020 UDP link local: (not bound)
  |   |  
2020-12-19 21:30:58 | stdout | Sat Dec 19 21:30:58 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]*****:1198
  |   |  
2020-12-19 21:30:58 | stdout | Sat Dec 19 21:30:58 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
  |   |  
2020-12-19 21:30:18 | stdout | Sat Dec 19 21:30:18 2020 SIGUSR1[soft,tls-error] received, process restarting
2020-12-19 21:30:18 | stdout | Sat Dec 19 21:30:18 2020 TLS Error: TLS handshake failed
  |   |  
2020-12-19 21:30:18 | stdout | Sat Dec 19 21:30:18 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
  |   |  
2020-12-19 21:29:18 | stdout | Sat Dec 19 21:29:18 2020 UDP link remote: [AF_INET]*****:1198
  |   |  
2020-12-19 21:29:18 | stdout | Sat Dec 19 21:29:18 2020 UDP link local: (not bound)

**Host system:**

Running on a Synology NAS. Not sure what version of Docker, whatever the latest on Synology NAS is I guess.

**Comment by haugene** [comment]
Have you pulled the latest version of the image recently? Please post complete logs in that case. PIA has replaced all their servers(#1334) and I'm guessing you are still running an old version of the image and then also old configs.

**Comment by TheDowdy** [comment]
Thanks Kristian. I hadn't manually pulled anything — I was trying to figure out how to do that but was under the assumption that it was automatically pulling the latest version when it is stopped and restarted?

![image](https://user-images.githubusercontent.com/21304646/102710463-60276480-42aa-11eb-8250-6bd8bcf1687c.png)

ssh'd into the NAS there now and pulled the image, not sure if it is telling me it updated it or was already up-to-date prior to the pull:

```
Using default tag: latest
latest: Pulling from haugene/transmission-openvpn
Digest: sha256:2e43acf370d98832dd466372b796365fcc6cb23bfd230de699946168f370487b
Status: Image is up to date for haugene/transmission-openvpn:latest
```

**Comment by TheDowdy** [comment]
Also, forgive my ignorance but what would consitute "complete logs" to post? When I export the logs there are over a hundred thousand lines in it, I was guessing any lines outside of the recent ones that keep repeating in a loop would be redundant.

**Comment by w1ser** [comment]
I had the same problem which was fixed when I pulled the latest image.  @TheDowdy is your openvpn config file France (Uppercase F).  I had to change it to lowercase and then it worked for me

**Comment by TheDowdy** [comment]
Hi @w1ser , thanks for the pointer — I noticed others mention the lowercase thing on other threads but when I change it to lowercase I get this in my logs: `Supplied config france.ovpn could not be found.`

Do I need to just trash my current container and restart again with a fresh latest (or dev) container? I would prefer not having to lose all seeding torrents etc.

**Comment by w1ser** [comment]
I don't know what you might lose if you started over.  I'm figuring this docker stuff out myself.  FWIW, here's the set of commands I use to start my container, without my pia user credentials. Happy New Year 😎

docker run --cap-add=NET_ADMIN -d \
              --name transdock \
              -v /mnt/Media1/DockerTrans/:/data \
              -v /mnt/Media1/DockerTrans/config:/config \
              -e "OPENVPN_CONFIG=france" \
              -e "LOCAL_NETWORK=192.168.1.0/24" \
                -e "TRANSMISSION_RPC_WHITELIST_ENABLED=false"\
              -e PUID=1000 -e PGID=1000 \
              -p 9091:9091 \
              -e DISABLE_PORT_UPDATER=true \
              haugene/transmission-openvpn

**Comment by Valdhor** [comment]
Did you change it to just france or was it france.ovpn? Do not add the .ovpn. That is added for you.

**Comment by TheDowdy** [comment]
Thanks - I just used "france", but you know what, I just thought of
something that may be causing this. Will investigate if I get the time and
report back.

**Comment by digeratum** [comment]
Hi there, have you tried clearing your docker image cache?

docker image prune -a

This will remove all cached docker images that aren't tied to an active container. 

I was having the same issue you mentioned. I realized I had never cleared the image cache, and on a whim I gave it a try to see if it resolved it. I'm now able to run this image without getting the TLS handshake error. Hope this helps.

**Comment by TheDowdy** [comment]
So I finally got it working. I deleted my container and just pulled a new one, set it up again, still no joy. I had initially set it using the guide [here](https://lejimmy.com/setting-up-transmission-bittorrent-with-openvpn-on-a-synology-nas-and-docker/), so I went through it again and once I ran the TUN.sh script again it all started working again for me.

Thanks everyone for your help!
