### ISSUE TITLE
Add ZorroVPN as provider

### ISSUE THREAD

**Issue by hallmichael868** [haugene/docker-transmission-openvpn#1624]
**Which provider?**
zorrovpn.com

**Where are the configs?**
https://ufile.io/28l98gm8

**Comment by hallmichael868** [comment]
Please consider adding this provider

**Comment by haugene** [comment]
The ovpn zip bundle is not available on their official website @hallmichael868 ? You have to be logged in to get it?
I've finally taken next steps to separate configs into its own repo. A lot of the provider-config tasks has been put on hold in the meantime. Opened this again for now.

**Comment by haugene** [comment]
Aha. You created a new one #1746 
Closing this as duplicate then.
