### ISSUE TITLE
Document Transmission settings persistence

### ISSUE THREAD

**Issue by MikeBishop** [haugene/docker-transmission-openvpn#1630]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/) to a reasonable degree

**Describe your request**
The docs [say](https://haugene.github.io/docker-transmission-openvpn/config-options/#transmission_configuration_options) that Transmission settings don't survive a container restart.  However, the final comment on #1130 indicates that support for persisted settings is in the 3.0+ releases.

**Contextual information**

Ideally, docs are accurate.  Also, how is persistence achieved?  Should there be a config volume mounted from the host for this?

**Comment by clement-z** [comment]
I think the docs are being re-worked, but yes, the current is wrong with 3.0+.

A comment on the situation, if someone other than @haugene is working on the docs:

The config directory you speak of is defined by the `TRANSMISSION_HOME` environment variable, which defaults to `/data/transmission-home` if I remember correctly. Therefore, if you bind `/data` to the host (as opposed to binding `/data/completed` et al. specifically), you will have settings persistence by default (so you save the settings which are set from the UI). 

Note however that on starting the container, settings which are specified as environment variables will overwrite those stored in the persistent transmission settings file (`$TRANSMISSION_HOME/settings.json`).

See below for the current default folder structure. (image can be re-used if needed, and the png should be editable in drawio)

![transmission-openvpn default folder structure](https://user-images.githubusercontent.com/6691770/102870883-f3dd6a00-443d-11eb-8256-820617cbc9e7.png)

**Comment by haugene** [comment]
Right you are @MikeBishop, thanks for the heads up :+1: I edited the docs now and also pushed the transmission config section down under the user setup part. This is less relevant now that it is not the default/recommended/only way of configuring Transmission :smile: 

And thank you for the diagram @clement-z. My documentation update push came to an end, but I hope to do another one "soon". And today I learned that you could actually just open the .png in draw.io :bulb: Did you have to export it in a special way or is that default for png exports from draw? I'll make a note of this issue and maybe include the diagram somewhere :pray: Thanks!

**Comment by haugene** [comment]
Oh yeah. And please read the updated version @MikeBishop and close this issue if you think that should do it. Let me know if you spot any errors.

**Comment by MikeBishop** [comment]
Looks good to me.  Thanks!
