### ISSUE TITLE
New config for Integrity VPN

### ISSUE THREAD

**Issue by matteh80** [haugene/docker-transmission-openvpn#1631]
**Which provider?**
Integrity VPN

**Where are the configs?**
# integrity, tunneblick, 20190527

client
dev tun
proto udp

remote openvpn.integrity.st 1197

remote-random
resolv-retry infinite
reneg-sec 0
nobind
persist-key
persist-tun
verb 3
mute 10
auth-user-pass
explicit-exit-notify 2

cipher aes-256-cbc
auth SHA512

script-security 2

remote-cert-tls server
compress lzo

key-direction 1
<ca>
-----BEGIN CERTIFICATE-----
MIIG6zCCBNOgAwIBAgIJAIw5wPIr22G7MA0GCSqGSIb3DQEBCwUAMIGpMQswCQYD
VQQGEwJTRTEKMAgGA1UECBMBUzESMBAGA1UEBxMJU3RvY2tob2xtMRIwEAYDVQQK
Ewk1anVseS5vcmcxFTATBgNVBAsTDGludGVncml0eXZwbjEVMBMGA1UEAxMMNWp1
bHkub3JnIENBMRUwEwYDVQQpEwxpbnRlZ3JpdHl2cG4xITAfBgkqhkiG9w0BCQEW
EmFkbWluQGludGVncml0eS5zdDAeFw0xODA0MTAxNDU3NDRaFw0yODA0MDcxNDU3
NDRaMIGpMQswCQYDVQQGEwJTRTEKMAgGA1UECBMBUzESMBAGA1UEBxMJU3RvY2to
b2xtMRIwEAYDVQQKEwk1anVseS5vcmcxFTATBgNVBAsTDGludGVncml0eXZwbjEV
MBMGA1UEAxMMNWp1bHkub3JnIENBMRUwEwYDVQQpEwxpbnRlZ3JpdHl2cG4xITAf
BgkqhkiG9w0BCQEWEmFkbWluQGludGVncml0eS5zdDCCAiIwDQYJKoZIhvcNAQEB
BQADggIPADCCAgoCggIBAK7DHUjBogO8WdAqImzlTi2O1o/IVMVH1iMYe5tVFhkc
YBE1p538KXYanicS/V5I9KRxi38a/48uynzdKvxX9RGL7i9A1J3PugYjLWOvBlNk
6p7g4MuyTrR4tMPh9CW9mIM8j9UJDRvj3+lbzu9UzX/2MbVhfKZnh3zh/npYqOH3
BUNl0s8CQFmC52uxMN/Hc08SZF2x1Zx/VZvTcqK6+GOZvDdAgZsUc0THKu6YoT2Y
13F49T1A9ACRUR3OOQHHH3lwxPQBxFdP9ObtBlORMVI5/rQxtniZUQlOuRPrxIbg
SD9cPGcNdrM/3yxnjbL38XuWL0JboXWQ06LRcHP5/zvaYOhAJJvtMNQQT4U0CdPY
JUhidmkvOkzaMxu2m5YQOeqHe8uAdEprDDGjSlSLGgqpCHQNaURviet490gAtv9X
aHF+sElmpyoMzpiF93J5LPO4BS4IQ4JV+47t5yjBwIBIuKNEzEUbe5AR9tmqy7WZ
dHryqgr54wdbJ5KpT0y5QIvj5mGX2P/MCvYRU6NvqC5mkrN5f2J8043geSMOuyRt
LTKF0M4JlC5+I3FiYPfAgb6qXmN1tCb/fxMlTFHfEG7HHR8uChLSlDQc4Vv/9ZDk
TTcs1tU8/arJBatGxVkH0GPI6h3O74EjrQ9Q41F9AN+SZiAMmcKY6Rq511y9HWqv
AgMBAAGjggESMIIBDjAdBgNVHQ4EFgQUwz6yZtAMJnBpanHX43YrLz6ma1kwgd4G
A1UdIwSB1jCB04AUwz6yZtAMJnBpanHX43YrLz6ma1mhga+kgawwgakxCzAJBgNV
BAYTAlNFMQowCAYDVQQIEwFTMRIwEAYDVQQHEwlTdG9ja2hvbG0xEjAQBgNVBAoT
CTVqdWx5Lm9yZzEVMBMGA1UECxMMaW50ZWdyaXR5dnBuMRUwEwYDVQQDEww1anVs
eS5vcmcgQ0ExFTATBgNVBCkTDGludGVncml0eXZwbjEhMB8GCSqGSIb3DQEJARYS
YWRtaW5AaW50ZWdyaXR5LnN0ggkAjDnA8ivbYbswDAYDVR0TBAUwAwEB/zANBgkq
hkiG9w0BAQsFAAOCAgEAkdtwoGpxmDljmCBwiz/Y+y6YFYjRo12LcXTzsRrcG0D7
3aaOljNotcrEZynXcQP68rB/7r/fn1xyEnNYlphkhReFoyO94Ke3+YPIvHTRQUgQ
2wKudIqmA6E//LP2HDN1ahYWVN45+kyd4MJi6zGoPSNHtUO311DvF6cQpUcWIewk
wj012ho/EZ3QsQVIDbsxN8EKPKckbfK5vuGVscB1IwtS/i2CO6XqjGcNxOeG9e8m
pRkp9Q7CE0hZGNTKtJWcL0cKmthywuznjcwBtFbUcCLWg9CWe21Kuf7gfXJaHN+F
abEitUKNyB2mlUIyHezPH8ZnliDlt4baBnoGF9ARmMayF0ZVdI3faw5sIemY5wNx
hSzGzF16PtCKPHm5Nqpxbux0Xr4ifdcIJjoXiA1X3tvFaCSJTNZxn+xyNUqQ82W2
0pERwfletnrGZ/N+ArN1el4hLKE5H1uXCVnpQiFqp9k8/UaHbdVVBqZ6/jkR9VN+
GeR5TGsr3eNnjziMwhays3M8la2TpyY0P4QuB89Ax8ewnLvEgvVmhsdsdXG9rg53
tsoaNEt8HkM1Cz8hUKNevZZVaKm2rt5tkbdAzzzvyO9dmKh5uglBMTVMQryBgRdW
rT0UovJPdf0uIwmhHV6XF13qbI8VhMYb4fESL+X1zd3FH2orYNzek8NAEOwKFBQ=
-----END CERTIFICATE-----
</ca>
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
f429b8722f99584ab10b3a83f68cc947
0cc252656dc6153077d377a6d54b59eb
afe4975d5def345f961794e043a5471c
91b3119e46ab8421117e046f58d07df4
ebd5d0fe535739482c1b3a4cb211adff
a3e7cbb040c0dff76e4f77b2de58df73
8a661db55e990e7aa8d2236ac724c54a
176fe4980d3862dfe4133e4faf2e363d
fbe4abee81fe45bed7e524e24b414306
09a678aee213bac00790820debc31a37
5931a10d2e4a3412cda2f6a371e46d8d
0f2140e1bc5d2986bcaf541f12ebc398
fc0d3ba7b03bcdf702a0c74f99be23dc
ece2ac23bcb265530001df288f9fc76f
4f5a5ad41df833133fd9005539f51c65
8bd3c0c4849c4f94f14465f1ad12b135
-----END OpenVPN Static key V1-----
</tls-auth>

**Comment by albinlundmark** [comment]
Have added a PR that fixes this: #1742

**Comment by pkishino** [comment]
closed by #1742
