### ISSUE TITLE
Provide image via ghcr.io as part of build/publish CI

### ISSUE THREAD

**Issue by ksurl** [haugene/docker-transmission-openvpn#1633]
add ghcr.io as a source for the image in addition to docker hub. it would just be a couple extra steps in ci (login to ghcr.io via token, push).

**Comment by pkishino** [comment]
feel free to create a PR for this

**Comment by ksurl** [comment]
I’ll take a look at the circle ci config tomorrow. Though some tokens and secrets setup will probably be needed by someone who has admin access. My own repo uses github actions to do build and push so it should be a similar logic.

**Comment by haugene** [comment]
Hey guys. Very sorry about the late follow-up here. I just reverted the changes to get things running again and thought I'd just try to get an overview here before enabling ghcr again. Also sync'ed dev and master branches so they are not behind/ahead of each other.

I left a new revision of the CircleCI config on the dev branch in December. I had a good period of contributions here and I was waiting for some feedback and then I never got back to it. Now your addition should probably work either way @ksurl, but I'm now building all the images (rss plugin and proxy as well) with the same build step. So the image name is now parameterized.

Anyways. Before fixing that, creating a token and pushing it out. I see that pushing the image to ghcr doesn't hurt, but what is the motivation? I'm just curious. I'm not necessarily opposed. I mean, why not? But I'm also curious to why we need it?

**Comment by ksurl** [comment]
thanks. this was just a response to the docker hub rate limiting for anonymous and free account tier pulls since github has yet to implement a pull rate limit.

**Comment by haugene** [comment]
Aha, I understand. I read about that at the end of last year. But they started out strict and then eased up a bit. I must admit I thought the limit was high enough. But if people have issues with it then I agree that ghcr should be a simple and good solution.

I've made a note here and will follow up soon. And I'll try my best to not disappear for 2 months. But it's getting late here and I have to get back to this later.

**Comment by ilike2burnthing** [comment]
Re: Watchtower and rate limits, resolved in https://github.com/containrrr/watchtower/pull/674

**Comment by haugene** [comment]
Hmm... Been thinking about this and I think we'll postpone this for now and stick to Docker Hub only.
If there are other arguments for pushing to ghcr.io later then we can revisit this.

From the [post](https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/) on rate limiting:
> Anonymous free users will be limited to 100 pulls per six hours, and authenticated free users will be limited to 200 pulls per six hours.

I don't think anyone should pull images 400 times per day. Tools like watchtower should then adapt (as they do :point_up:) and all should be fine. But I am open to adding ghcr.io later if there are other needs. I'm looking more to the image retention policy that is coming at some point. We want a long version history of the image to be retained.
