### ISSUE TITLE
Files downloading that shouldn't be

### ISSUE THREAD

**Issue by Shadzae** [haugene/docker-transmission-openvpn#1635]
I've been unchecking files to *not* download in a torrent and they download anyway. This includes files using the web-ui as well as the trans-gui native app.

Newest versions of transmission-openvpn, trans-remote, on W10 x64.

Thanks!

**Comment by pkishino** [comment]
This is not uncommon for torrents

**Comment by Shadzae** [comment]
But qbittorrent doesn't? When qbt downloads, it may download part of those files, but delete them (or put it into some temp file). But transmission is downloading them and not marking them as partial files...?

**Comment by rutravis** [comment]
Note that transmission doesn't control the use of the .part files.  This is configured in Radarr, Sonarr, and Lidarr.  Need to set it up there.
