### ISSUE TITLE
Web GUI Authentication user/password?

### ISSUE THREAD

**Issue by NovaCyntax** [haugene/docker-transmission-openvpn#1636]
**Before creating this issue I have:**
- [x] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [x] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/) to a reasonable degree

**Describe your request**
I've configured Transmission for external monitoring via a reverse proxy. However, the GUI is not protected by a user/password. I can't seem to find an option for enabling this within the GUI, and I also haven't found a relevant environment variable within Docker. I'm almost positive that I have to be missing something, either the setting or a previous issue discussing the topic, but my quick search didn't return anything.

**Contextual information**
I don't want my torrents to be viewed/controlled publicly without authentication, while also being able to view/control them remotely.

**Comment by ilike2burnthing** [comment]
Set the environment variables:
- TRANSMISSION_RPC_USERNAME - _username_
- TRANSMISSION_RPC_PASSWORD - _password_
- TRANSMISSION_RPC_AUTHENTICATION_REQUIRED - _true_

Redeploy the container.

**Comment by NovaCyntax** [comment]
That worked, thank you. I was previously using Deluge, and the "WEBPROXY" environment variables in this image for whatever reason had misled me.

**Comment by ilike2burnthing** [comment]
That's the problem with such a subpar alternative...
/s

Much love to binhex 😋

**Comment by hoxu** [comment]
I think this should be covered in https://haugene.github.io/docker-transmission-openvpn/faq/

**Comment by ilike2burnthing** [comment]
@haugene ^

**Comment by gregbert42** [comment]
I am sooo glad someone posted and clarified this. i just went through all the documentation and couldnt find it anywhere. thank you @NovaCyntax  and @ilike2burnthing

**Comment by sarvesh-lad** [comment]
HI,

I know this is closed, but is there a list of all available environment variables that can be set?

Each time I have to do something, I gotta google or search under issues to find it and it is cumbersome.

**Comment by haugene** [comment]
I know this is closed, but wanted to comment as I was mentioned. @ilike2burnthing has already given all the answers here. I thought now that this could also be controlled in the WebUI and that you don't have to set the env vars, but you do. It is not possible to do that from the UI and so it should probably be in the FAQ. I agree.
