### ISSUE TITLE
Having trouble setting this up on a Raspberry Pi 4 with Mullvad

### ISSUE THREAD

**Issue by Wrimel** [haugene/docker-transmission-openvpn#1640]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/) to a reasonable degree

**Describe your request**
Im following this [guide](https://dbtechreviews.com/2020/04/how-to-install-transmission-with-vpn-on-omv/).
These are my settings:

OPENVPN_PROVIDER=MULLVAD
OPENVPN_CONFIG=de_all
OPENVPN_USERNAME=****************
OPENVPN_PASSWORD=m

This is the error i get:

```
Starting container with revision: a4d65774f855a04070766e53346661f48c76fa0e


Creating TUN device /dev/net/tun


mknod: /dev/net/tun: File exists


Using OpenVPN provider: MULLVAD


Starting OpenVPN using config de_all.ovpn


Setting OpenVPN credentials...


adding route to local network 192.168.178.0/24 via 172.20.0.1 dev eth0


Tue Dec 29 03:55:18 2020 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.


Tue Dec 29 03:55:18 2020 OpenVPN 2.4.9 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020


Tue Dec 29 03:55:18 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10


Tue Dec 29 03:55:18 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts


Tue Dec 29 03:55:18 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]193.27.14.34:1300


Tue Dec 29 03:55:18 2020 Socket Buffers: R=[180224->360448] S=[180224->360448]


Tue Dec 29 03:55:18 2020 UDP link local: (not bound)


Tue Dec 29 03:55:18 2020 UDP link remote: [AF_INET]193.27.14.34:1300


Tue Dec 29 03:55:18 2020 TLS: Initial packet from [AF_INET]193.27.14.34:1300, sid=5759a823 6f95dc96


Tue Dec 29 03:55:18 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this


Tue Dec 29 03:55:19 2020 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net


Tue Dec 29 03:55:19 2020 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v3, emailAddress=security@mullvad.net


Tue Dec 29 03:55:19 2020 VERIFY KU OK


Tue Dec 29 03:55:19 2020 Validating certificate extended key usage


Tue Dec 29 03:55:19 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication


Tue Dec 29 03:55:19 2020 VERIFY EKU OK


Tue Dec 29 03:55:19 2020 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=de-fra-203.mullvad.net, emailAddress=security@mullvad.net


Tue Dec 29 03:55:19 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558'


Tue Dec 29 03:55:19 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'


Tue Dec 29 03:55:19 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA


Tue Dec 29 03:55:19 2020 [de-fra-203.mullvad.net] Peer Connection Initiated with [AF_INET]193.27.14.34:1300


Tue Dec 29 03:55:20 2020 SENT CONTROL [de-fra-203.mullvad.net]: 'PUSH_REQUEST' (status=1)


Tue Dec 29 03:55:20 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.14.0.1,redirect-gateway def1 bypass-dhcp,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,comp-lzo no,route-gateway 10.14.0.1,topology subnet,socket-flags TCP_NODELAY,ifconfig-ipv6 fdda:d0d0:cafe:1300::1001/64 fdda:d0d0:cafe:1300::,ifconfig 10.14.0.3 255.255.0.0,peer-id 1,cipher AES-256-GCM'


Tue Dec 29 03:55:20 2020 OPTIONS IMPORT: compression parms modified


Tue Dec 29 03:55:20 2020 OPTIONS IMPORT: --socket-flags option modified


Tue Dec 29 03:55:20 2020 NOTE: setsockopt TCP_NODELAY=1 failed


Tue Dec 29 03:55:20 2020 OPTIONS IMPORT: --ifconfig/up options modified


Tue Dec 29 03:55:20 2020 OPTIONS IMPORT: route options modified


Tue Dec 29 03:55:20 2020 OPTIONS IMPORT: route-related options modified


Tue Dec 29 03:55:20 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified


Tue Dec 29 03:55:20 2020 OPTIONS IMPORT: peer-id set


Tue Dec 29 03:55:20 2020 OPTIONS IMPORT: adjusting link_mtu to 1624


Tue Dec 29 03:55:20 2020 OPTIONS IMPORT: data channel crypto options modified


Tue Dec 29 03:55:20 2020 Data Channel: using negotiated cipher 'AES-256-GCM'


Tue Dec 29 03:55:20 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key


Tue Dec 29 03:55:20 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key


Tue Dec 29 03:55:20 2020 ROUTE_GATEWAY 172.20.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:14:00:02


Tue Dec 29 03:55:20 2020 GDG6: remote_host_ipv6=n/a


Tue Dec 29 03:55:20 2020 ROUTE6: default_gateway=UNDEF


Tue Dec 29 03:55:20 2020 TUN/TAP device tun0 opened


Tue Dec 29 03:55:20 2020 TUN/TAP TX queue length set to 100


Tue Dec 29 03:55:20 2020 /sbin/ip link set dev tun0 up mtu 1500


Tue Dec 29 03:55:20 2020 /sbin/ip addr add dev tun0 10.14.0.3/16 broadcast 10.14.255.255


Tue Dec 29 03:55:20 2020 /sbin/ip -6 addr add fdda:d0d0:cafe:1300::1001/64 dev tun0


RTNETLINK answers: Permission denied


Tue Dec 29 03:55:20 2020 Linux ip -6 addr add failed: external program exited with error status: 2


Tue Dec 29 03:55:20 2020 Exiting due to fatal error
```

**Contextual information**

Raspberry Pi 4 is running Raspbian and Openmediavault 5 

Im new to Linux and i have no idea how to fix this. 

Thankful to any help i can get. Cheers.

**Comment by rcarriga** [comment]
Looks like common mullvad issue. See #847 if you're using `docker-compose` or #1355 if you're just using `docker run`

**Comment by Wrimel** [comment]
> 
> 
> Looks like common mullvad issue. See #847 if you're using `docker-compose` or #1355 if you're just using `docker run`

I THINK im using `docker-compose`? Im using Portainer with [this guide](https://dbtechreviews.com/2020/04/how-to-install-transmission-with-vpn-on-omv/). 

Having a hard time understanding the solutions from #847. As far as i understand the docker already has existing mullvad configs, where do i access them?

**Comment by rcarriga** [comment]
Yep you're using compose. I'm using the same so I'll show you how I solved it.

First you need to understand how docker works a bit more. I'd recommend looking into it as it is very useful info for a lot of home networking/automation/scripting etc. But for right now you can just imagine an image as a totally separate filesystem. You **should** only access this filesystem through the docker cli. Don't try to read files from `/var`.

What we want to do is overwrite the existing config you're using to add these lines
```
# Fix for mullvad see https://github.com/haugene/docker-transmission-openvpn/issues/847
pull-filter ignore "dhcp-option DNS6"·
pull-filter ignore "tun-ipv6"·
pull-filter ignore "ifconfig-ipv6"
```

To do this we're going to copy the config file to our local machine, add the lines and then mount them into the `/etc/openvpn/mullvad` directory of the container.

First copy the config file from the image into a `mullvad` directory. This directory will be the one you will be mounting so place it with your compose yaml file.
```sh
mkdir mullvad

# Create a container from the image to be able to extract files
container=$(docker create haugene/transmission-openvpn)

# Get the ovpn config file. Make sure to set the OPENVPN_CONFIG var as it is in your compose yaml.
docker cp $container:/etc/openvpn/mullvad/${OPENVPN_CONFIG}.ovpn mullvad/

# We also need the ca.crt file as the entire directory is overwritten when replaced by the mount
docker cp $container:/etc/openvpn/mullvad/ca.crt mullvad/

# Clean up container
docker rm $container
```

Now we have the files we need, open the `ovpn` config and add the lines to the bottom of the file with your editor of choice.
```
...
# Fix for mullvad see https://github.com/haugene/docker-transmission-openvpn/issues/847
pull-filter ignore "dhcp-option DNS6"·
pull-filter ignore "tun-ipv6"·
pull-filter ignore "ifconfig-ipv6"
```

Now you just add a new volume mount to your config to override the config in the container
```yaml
...
    volumes:
      - $TORRENT_DIRECTORY/:/data
      - ./mullvad:/etc/openvpn/mullvad
```

That should solve the issue for you, let me know if there's any problems

**Comment by Wrimel** [comment]
@rcarriga thank you very much for your help. i actually managed to do it before seeing your comment by downloading the de_all.ovpn file from github, adding the ipv6 commands and letting the docker use that file instead of the original one via a `:ro` command. 

I actually have a different problem now, i want to use multiple external HDDs but i dont know how to do this. I currently only use a 2TB WD Passport which is set as `:data ` and keeps the torrents and transmission data. 

However, i want to add my other 2TB WD Elements and a future 5-10TB HDD as well. Perhaps you could help me with this too?

Thanks again.

**Comment by rcarriga** [comment]
This is out of scope of this repo. I would say the solution would be using [LVM](https://wiki.archlinux.org/index.php/LVM) which allows you to use multiple devices as a single unit. You can use [RAID with LVM](https://wiki.archlinux.org/index.php/LVM#RAID) if you want to have redundancy. I link to the Arch wiki as it's what I use and it's also mostly applicable to other repos. It should have all of the information you need

**Comment by Wrimel** [comment]
@rcarriga That looks really helpful! 

Will this work with Raspbian and the haugene docker? This looks like a better option than going for SATA to USB and using RAID but i want to make sure what i should go for before i buy my next USB 3.0 HDD

**Comment by rcarriga** [comment]
I'm not familiar with omv but it looks like it's just a light wrapper around basic linux utilities so it should have no issue alright :+1: 

LVM works on Raspbian but the docker image doesn't care about what the underlying file system is like. As long as you point it at a directory, it'll work. I'm not too familiar with using RAID so can't offer much help with that I'm afraid

Don't forget to close this issue btw!
