### ISSUE TITLE
Cannot access GUI in browser

### ISSUE THREAD

**Issue by 0n11san** [haugene/docker-transmission-openvpn#1641]
**Before creating this issue I have:**

- [ X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [ X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X ] Tried to add as much relevant information to the issue as possible

**Describe the problem**

I cannot seem to get the Transmission web GUI to load in my browser. I originally started (and made some progress) setting things up by following 2 guides I found on Reddit ([guide 1](https://www.reddit.com/r/VPNTorrents/comments/900w78/xpost_rsynology_setting_up_the/) and [guide 2](https://www.reddit.com/r/synology/comments/aqdsn2/haugene_transmissionvpn_with_expressvpn/egfgk7i/?utm_source=share&utm_medium=web2x&context=3)). Then I came here and made a bit more progress (eventually getting program to seemingly run w/o shutting off).
This is my first NAS setup (Synology). I'm using ExpressVPN. 

**Add your docker run command or docker-compose file**

<img width="458" alt="Screen Shot 2020-12-30 at 7 43 22 PM" src="https://user-images.githubusercontent.com/9022899/103388499-49b5b000-4ad7-11eb-8a86-2a075c2a383b.png">

**Logs**

[haugene-transmission-openvpn1.pdf](https://github.com/haugene/docker-transmission-openvpn/files/5756122/haugene-transmission-openvpn1.pdf)

**Host system:**

Synology via Mac OS

**Comment by 0n11san** [comment]
I've tried changing the CIDR address within my environmental variables, per the comment on this [post](https://github.com/haugene/docker-transmission-openvpn/issues/1334) ie /24 ... /32 etc but no dice so far

<img width="404" alt="Screen Shot 2020-12-30 at 7 49 09 PM" src="https://user-images.githubusercontent.com/9022899/103388665-5b4b8780-4ad8-11eb-940e-f69134514b61.png">

**Comment by 0n11san** [comment]
Some additional variables (OPENVPN_USERNAME and OPENVPN_PASSWORD removed, for obvious reasons)

<img width="577" alt="Screen Shot 2020-12-30 at 7 49 21 PM" src="https://user-images.githubusercontent.com/9022899/103388699-8a61f900-4ad8-11eb-8f45-ee3bdcde465c.png">

<img width="564" alt="Screen Shot 2020-12-30 at 7 49 28 PM" src="https://user-images.githubusercontent.com/9022899/103388702-8f26ad00-4ad8-11eb-97e8-2c17ce74b601.png">

<img width="573" alt="Screen Shot 2020-12-30 at 7 49 40 PM" src="https://user-images.githubusercontent.com/9022899/103388705-96e65180-4ad8-11eb-9140-71448b6ace70.png">

<img width="552" alt="Screen Shot 2020-12-30 at 7 49 48 PM" src="https://user-images.githubusercontent.com/9022899/103388709-9c439c00-4ad8-11eb-87b1-85cda3408b04.png">

**Comment by 0n11san** [comment]
the "RTNETLINK answers: Invalid argument" portion of the log is where my eyes are drawn to and what makes me think the problem lies in the ports, but I'm not sure how to proceed

a PDF log of (what I believe) is one instance of me trying to run the program is attached up top. I can supply a longer log, if necessary as well

<img width="1044" alt="Screen Shot 2020-12-30 at 12 21 56 AM" src="https://user-images.githubusercontent.com/9022899/103388815-268c0000-4ad9-11eb-92ce-8c9acc4c339a.png">


<img width="1056" alt="Screen Shot 2020-12-30 at 12 21 41 AM" src="https://user-images.githubusercontent.com/9022899/103388827-2d1a7780-4ad9-11eb-8418-e9fb24e757e3.png">

**Comment by 0n11san** [comment]
Also, I saw @haugene mention a potential workaround in this [comment](https://github.com/haugene/docker-transmission-openvpn/issues/1495#issuecomment-725674533) but the link appears to be dead

**Comment by ilike2burnthing** [comment]
I assume it was something along the lines of - https://haugene.github.io/docker-transmission-openvpn/vpn-networking/

**Comment by 0n11san** [comment]
> I assume it was something along the lines of - https://haugene.github.io/docker-transmission-openvpn/vpn-networking/

thanks for replying! yes, I think so (tho it appears the page is not yet done)?

I've tried changing the environmental variable in the docker container (eg "/16" ... "/24"... "/32" etc) but no luck. 

Have also tried running the described commands via Mac's terminal after SSH'ing into the directory (I think I did this part correctly, but I confess that I am a bit of a novice). Still nothing

**Comment by ilike2burnthing** [comment]
Try using `10.0.0.0` with `/16`, `/24` or `/32` see if any of those work. Otherwise you'd probably have to look into using a reverse proxy.

**Comment by 0n11san** [comment]
Just tried that. No dice, unfortunately. (I assume I would still try to access via this URL "https://10.0.0.56:32770")

Where can I run a reverse proxy? Can I do this via the Synology DSM or via SSH?

**Comment by 0n11san** [comment]
This is what I tried via SSH

<img width="570" alt="Screen Shot 2021-01-01 at 1 24 40 AM" src="https://user-images.githubusercontent.com/9022899/103434506-3afef400-4bd0-11eb-9fb6-f84a64cabd11.png">

**Comment by ilike2burnthing** [comment]
You can set up a reverse proxy in DSM - https://mariushosting.com/synology-how-to-use-reverse-proxy/ (plenty of other guides are available in case that one is outdated or unhelpful)

**Comment by 0n11san** [comment]
I'm not sure why I'm not understanding this.

So many of these guides confuse me. For instance, the aforementioned one talks about the importance of getting a static IP and yet then proceeds to talk about how to set things up w/ dynamic, for a good bit of the article.

I'm trying to do what I can but...

<img width="563" alt="Screen Shot 2021-01-01 at 7 18 01 PM" src="https://user-images.githubusercontent.com/9022899/103448379-ea86a580-4c66-11eb-89e6-0309e82d14ba.png">

**Comment by ilike2burnthing** [comment]
The above doesn't mention static or dynamic IPs, just local.

I don't have a Synology NAS (Asustor instead), so I can't check which of the Google search 'solutions' for that error makes more sense. Have a look at them, see if they help, otherwise you'll have to reach out to Synology forums or support.

**Comment by 0n11san** [comment]
Thank you for your help, regardless. I'll keep trying

**Comment by jvdsypt** [comment]
I had exactly the same issue as 0n11san describes. 
Also tried to set the LOCAL_NETWORK environment parameter to my local network but this was not doing the trick.

What I ended up doing is making use of the Transmission-openvpn-proxy image in docker that Haugene has. 
This is described here ([https://haugene.github.io/docker-transmission-openvpn/vpn-networking/#how_to_fix_this](ulr))

Although I found online that the --link flag that is used in this method might be removed in the future and that it shouldn't be used.
So I would like to find why the LOCAL_NETWORK variable didn't did the trick but I don't have an idea

**Comment by Cyberlane** [comment]
I just thought I would share this...

Previously I was using 2.7 (due to an old NordVPN issue, I didn't bother upgrading for a long time).

Upgraded to 3.3 today, and web did not work (or so I thought)

`http://my-server:9091` times out

`http://my-server:9091/transmission/web/` works, please take note of the trailing `/` at the end of `web/`, it *is* needed.

**Comment by jvdsypt** [comment]
> I just thought I would share this...
> 
> Previously I was using 2.7 (due to an old NordVPN issue, I didn't bother upgrading for a long time).
> 
> Upgraded to 3.3 today, and web did not work (or so I thought)
> 
> `http://my-server:9091` times out
> 
> `http://my-server:9091/transmission/web/` works, please take note of the trailing `/` at the end of `web/`, it _is_ needed.

I tried it but for me, still not working.

**Comment by jvdsypt** [comment]
as from today, I can't access anymore with the Transmission-openvpn-proxy method.
It was working before but without changing anything, I receive the following page now

403: Forbidden
Unauthorized IP Address.
Either disable the IP address whitelist or add your address to it.
If you're editing settings.json, see the 'rpc-whitelist' and 'rpc-whitelist-enabled' entries.
If you're still using ACLs, use a whitelist instead. See the transmission-daemon manpage for details.

I have no idea anymore what to do

**Comment by ilike2burnthing** [comment]
Post your container settings.

**Comment by countstex** [comment]
I've just installed this for the first time and am hitting that same issue of 403: Forbidden. Seems I can access the server ok on 9091 but then it's refusing access to my local IP. It would suggest I need to add my local ranges to the whitelist in the config file, but not sure how to access them in the container.

**Comment by pkishino** [comment]
people, please, separate issues into separate threads..
@0n11san why are you trying to access via 32770 port??

**Comment by haugene** [comment]
what he said :point_up: 

@0n11san I don't see why you're using the 32770 port. Try to exec into the container and run `curl localhost:9091` just to make sure that Transmission is running. Or better yet. Run through this guide(https://haugene.github.io/docker-transmission-openvpn/debug/) and create a new issue using the "bug report" issue if you can't make it work.

You are welcome to submit a new issue, but we need more info and in a structured way so that we can help people more efficiently.

**Comment by Hellaren** [comment]
I had pretty much the same problem until I saw the comment from @Cyberlane.
By default I tried to access the GUI using HTTPS, however, it is run over HTTP in my case.

Probably it won't help the majority of people facing the same issue, but there is still a chance so I thought I would share anyway.
