### ISSUE TITLE
Transmission starting but not downloading (using ProtonVPN)

### ISSUE THREAD

**Issue by thisislex** [haugene/docker-transmission-openvpn#1644]
Hi there,

So I've looked around for similar ProtonVPN (or adjacent) issues regarding downloading, however the common solutions (e.g. OpenVPN config, config folder, redownloading images, etc.) do not seem to have solved anything,

**Describe the problem**
Transmission boots up and gets torrents through something like Sonarr or other platforms (magnetized), but it doesn't download anything or doesn't really connect.
Docker settings appear correct, and since I'm on ProtonVPN I've tried with various "protonvpn config" location sources, but same result.
I've also reinstalled the image (both dev and latest versions) and deleted the config folders/reconstructed them to no avail.

**Host system:**
Synology DS1019+

**Settings**
Here is a screenshot of the environment variables
https://i.ibb.co/Q6kW2R2/eenvar.png

I've tried with local port/container port matching and not matching - they're currently TCP.

**Logs**

Here's an example of the logs before I stop the container
https://justpaste.it/6q9cq

Thanks in advance for any help!

**Comment by w1ll1am23** [comment]
I believe I am seeing something similar using PIA.

**Comment by Unnamend01** [comment]
I'm having the same problem with NordVPN

**Comment by dinosmm** [comment]
Hello, I'm just trying out this container first time, it runs well and I can access Transmission's Web UI but no connection to peers and downloads are not starting.

**Comment by vukani-dev** [comment]
Having the same problem with Mullvad

**Comment by Shalar** [comment]
I have this same problem with PIA. It starts up fine and grabs a port, but no seeds appear to any torrent.

**Comment by Shalar** [comment]
I was able to resolve my issue by deleting my config folder and starting with a minimal set of environment variables in my docker file.

**Comment by tmilner** [comment]
I have the same issue with PIA. I started taking a look at whats going on and see this in the docker logs 

`Running functions for token based port fowarding
transmission_1  | curl: (6) Could not resolve host: www.privateinternetaccess.com
transmission_1  | Wed Jan 20 17:44:49 UTC 2021: getSignature error
transmission_1  | { "status": "ERROR", "message": "Login failed!" }
transmission_1  | the has been a fatal_error
transmission_1  | parse error: Invalid numeric literal at EOF at line 1, column 3
transmission_1  | parse error: Invalid numeric literal at EOF at line 1, column 3
transmission_1  | date: invalid date ''
transmission_1  | Wed Jan 20 17:44:50 UTC 2021: bindPort error
transmission_1  | { "status": "", "message": "bad signature" }
transmission_1  | the has been a fatal_error`

The credentials are correct though so I am not sure whats going on.

**Comment by dinosmm** [comment]
I have not looked at my logs but I know for a fact that I am connecting to my VPN, as I can see the session on the VPN's user area, and I can connect to the Transmission web UI using the VPN IP and the forwarded port. It's just that transfers never start. If I use my own Transmission install outside this container with the same VPN connection, on the same machine, it works fine.

**Comment by vukani-dev** [comment]
Downloading latest Image and removing ratio limit from the environment settings fixed my issue.
Don't know which exactly did it.

**Comment by pkishino** [comment]
check your settings.json in the container, and check that the ratio is set properly to X.X ..transmission 3 made some changes to this..

**Comment by dinosmm** [comment]
I downloaded the latest image and checked my settings.json, ratio-limit is set to false. Is there any other ratio setting that should be in there?

**Comment by pkishino** [comment]
can you please share the whole settings.json?

**Comment by dinosmm** [comment]
`{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-updates-enabled": true,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "compact-view": false,
    "dht-enabled": true,
    "download-dir": "/home/xxxxxxx/Downloads",
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/home/xxxxxxx/Downloads",
    "incomplete-dir-enabled": false,
    "inhibit-desktop-hibernation": false,
    "lpd-enabled": false,
    "main-window-height": 572,
    "main-window-is-maximized": 0,
    "main-window-width": 1214,
    "main-window-x": 644,
    "main-window-y": 397,
    "message-level": 2,
    "open-dialog-dir": "/home/dinosm",
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "recent-download-dir-1": "/home/xxxxxxx/Downloads",
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": false,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "xxxxxxxxxxx",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": true,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "show-backup-trackers": false,
    "show-extra-peer-details": false,
    "show-filterbar": true,
    "show-notification-area-icon": false,
    "show-options-window": true,
    "show-statusbar": true,
    "show-toolbar": true,
    "show-tracker-scrapes": false,
    "sort-mode": "sort-by-name",
    "sort-reversed": false,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "statusbar-stats": "total-ratio",
    "torrent-added-notification-enabled": true,
    "torrent-complete-notification-enabled": true,
    "torrent-complete-sound-command": "canberra-gtk-play -i complete-download -d 'transmission torrent downloaded'",
    "torrent-complete-sound-enabled": true,
    "trash-can-enabled": true,
    "trash-original-torrent-files": false,
    "umask": 18,
    "upload-slots-per-torrent": 14,
    "user-has-given-informed-consent": true,
    "utp-enabled": true,
    "watch-dir": "/home/xxxxxxx/Downloads",
    "watch-dir-enabled": false
}

`

**Comment by pkishino** [comment]
change "ratio-limit": 2, to "ratio-limit": 2.0 ,

**Comment by matt-shepherd** [comment]
I have the same issue..  tried `curl` requests from a remote shell inside the container and the connection just times out..  could outbound traffic be being blocked?

**Comment by pkishino** [comment]
try doing a resolve and see if it works,could just be dns issue

**Comment by matt-shepherd** [comment]
`bash-5.0# ping bbc.co.uk`

`PING bbc.co.uk (151.101.128.81): 56 data bytes
ping: sendto: Operation not permitted`

also doesnt work

**Comment by pkishino** [comment]
please open a new issue and attach the necessary details.
thanks

**Comment by simonalger** [comment]
Had exaclty this problem and tried for days to fix it. In the end what fixed it was deleting settings.json (modifying it didn't help) after which it got replaced by a default and everything worked as before.

**Comment by pkishino** [comment]
Please try with latests releases, providers have been updated
