### ISSUE TITLE
Unraid haugene/docker-transmission-openvpn cannot connect

### ISSUE THREAD

**Issue by nosni1** [haugene/docker-transmission-openvpn#1646]
When attempting to connect with my browser it does not connect. 

ErrorWarningSystemArrayLogin

Starting container with revision: 53d3f05b7a1cad1a93f98fb99dec4fc9fee5ba6e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: NORDVPN
Starting OpenVPN using config default.ovpn
Setting OpenVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Tue Jan 5 21:25:25 2021 WARNING: file '/config/credentials.conf' is group or others accessible

Tue Jan 5 21:25:25 2021 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Tue Jan 5 21:25:25 2021 library versions: OpenSSL 1.1.1g 21 Apr 2020, LZO 2.10
Tue Jan 5 21:25:25 2021 WARNING: --ping should normally be used with --ping-restart or --ping-exit

Tue Jan 5 21:25:25 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Jan 5 21:25:25 2021 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jan 5 21:25:25 2021 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jan 5 21:25:25 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]148.72.166.26:1194
Tue Jan 5 21:25:25 2021 Socket Buffers: R=[212992->212992] S=[212992->212992]
Tue Jan 5 21:25:25 2021 UDP link local: (not bound)
Tue Jan 5 21:25:25 2021 UDP link remote: [AF_INET]148.72.166.26:1194
Tue Jan 5 21:25:25 2021 TLS: Initial packet from [AF_INET]148.72.166.26:1194, sid=222c007e 1abeb936
Tue Jan 5 21:25:25 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Tue Jan 5 21:25:25 2021 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Tue Jan 5 21:25:25 2021 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5
Tue Jan 5 21:25:25 2021 VERIFY KU OK
Tue Jan 5 21:25:25 2021 Validating certificate extended key usage
Tue Jan 5 21:25:25 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue Jan 5 21:25:25 2021 VERIFY EKU OK
Tue Jan 5 21:25:25 2021 VERIFY OK: depth=0, CN=us8339.nordvpn.com
Tue Jan 5 21:25:25 2021 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 4096 bit RSA
Tue Jan 5 21:25:25 2021 [us8339.nordvpn.com] Peer Connection Initiated with [AF_INET]148.72.166.26:1194
Tue Jan 5 21:25:26 2021 SENT CONTROL [us8339.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Tue Jan 5 21:25:26 2021 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.8.3.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.3.4 255.255.255.0,peer-id 0,cipher AES-256-GCM'
Tue Jan 5 21:25:26 2021 OPTIONS IMPORT: timers and/or timeouts modified
Tue Jan 5 21:25:26 2021 OPTIONS IMPORT: explicit notify parm(s) modified
Tue Jan 5 21:25:26 2021 OPTIONS IMPORT: compression parms modified
Tue Jan 5 21:25:26 2021 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Tue Jan 5 21:25:26 2021 Socket Buffers: R=[212992->1048576] S=[212992->1048576]
Tue Jan 5 21:25:26 2021 OPTIONS IMPORT: --ifconfig/up options modified
Tue Jan 5 21:25:26 2021 OPTIONS IMPORT: route options modified
Tue Jan 5 21:25:26 2021 OPTIONS IMPORT: route-related options modified
Tue Jan 5 21:25:26 2021 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Tue Jan 5 21:25:26 2021 OPTIONS IMPORT: peer-id set
Tue Jan 5 21:25:26 2021 OPTIONS IMPORT: adjusting link_mtu to 1657
Tue Jan 5 21:25:26 2021 OPTIONS IMPORT: data channel crypto options modified
Tue Jan 5 21:25:26 2021 Data Channel: using negotiated cipher 'AES-256-GCM'
Tue Jan 5 21:25:26 2021 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Jan 5 21:25:26 2021 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Jan 5 21:25:26 2021 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:0a
Tue Jan 5 21:25:26 2021 TUN/TAP device tun0 opened
Tue Jan 5 21:25:26 2021 TUN/TAP TX queue length set to 100
Tue Jan 5 21:25:26 2021 /sbin/ip link set dev tun0 up mtu 1500
Tue Jan 5 21:25:26 2021 /sbin/ip addr add dev tun0 10.8.3.4/24 broadcast 10.8.3.255
Tue Jan 5 21:25:26 2021 /etc/openvpn/tunnelUp.sh tun0 1500 1585 10.8.3.4 255.255.255.0 init
Up script executed with tun0 1500 1585 10.8.3.4 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.3.4
Using Transmission Web Control UI, overriding TRANSMISSION_WEB_HOME
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.8.3.4
Overriding cache-size-mb because TRANSMISSION_CACHE_SIZE_MB is set to 10
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /downloads
Overriding download-queue-size because TRANSMISSION_DOWNLOAD_QUEUE_SIZE is set to 15
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /downloads/incomplete
Overriding ratio-limit-enabled because TRANSMISSION_RATIO_LIMIT_ENABLED is set to false
Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to true
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to nosni1
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories

-------------------------------------
Transmission will run as
-------------------------------------
User name: abc
User uid: 99
User gid: 100
-------------------------------------

STARTING TRANSMISSION
Transmission startup script complete.
Tue Jan 5 21:25:27 2021 /sbin/ip route add 148.72.166.26/32 via 172.17.0.1
Tue Jan 5 21:25:27 2021 /sbin/ip route add 0.0.0.0/1 via 10.8.3.1
Tue Jan 5 21:25:27 2021 /sbin/ip route add 128.0.0.0/1 via 10.8.3.1
Tue Jan 5 21:25:27 2021 Initialization Sequence Completed

**Comment by pkishino** [comment]
most likely your local network isn't set correctly.. please attach your config
