### ISSUE TITLE
Dns is leaking using mullvad or PrivateVPN

### ISSUE THREAD

**Issue by klusbert** [haugene/docker-transmission-openvpn#1648]
I created two diffrent docker containers, one for mullvad and one for privatevpn using following setup.

docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn -d\
              -v /home/htpc/Transmission/:/data \
              -v /home/htpc/server/Downloads/:/Download \
              -e OPENVPN_PROVIDER=MULLVAD \
              -e OPENVPN_CONFIG=se_all\
              -e OPENVPN_USERNAME=000000000000 \
              -e OPENVPN_PASSWORD=m \
              -e TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true \
              -e TRANSMISSION_RPC_USERNAME=asd \
              -e TRANSMISSION_RPC_PASSWORD=asd \
              -e TRANSMISSION_DOWNLOAD_DIR=/Download/ \
	          -e TRANSMISSION_INCOMPLETE_DIR=/Download/incomplete/ \
              -e WEBPROXY_ENABLED=true \
              -e WEBPROXY_PORT=8888 \
              -e LOCAL_NETWORK=192.168.0.0/16 \
	          -e PUID=1000 \
	          -e PGID=1000 \
              --sysctl net.ipv6.conf.all.disable_ipv6=0 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              -p 8888:8888 \
              haugene/transmission-openvpn

Then I tried this script https://github.com/macvk/dnsleaktest. 
I can see my dns is leaking on both privatevpn and mullvad.

Since mullvad provide their own dns, is there anywere I can specify it?

**Comment by aaronblair** [comment]
If you add `--dns 8.8.8.8 --dns 8.8.4.4` to your command, does that resolve the IP leak issue? Might be related to #1455.

**Comment by klusbert** [comment]
PrivateVPN only provide dns from vpn server, mullvad however have a public accessible dns which can replace with the default. 
In ubuntu I always used update-resolv.conf to get dns IP from the provider.

**Comment by Xenov-X** [comment]
@klusbert , see pull req #1621

**Comment by klusbert** [comment]
Xenov-x replied with good anwser
