### ISSUE TITLE
When using TRANSMISSION_RPC_WHITELIST i could not access webpage

### ISSUE THREAD

**Issue by user-1984** [haugene/docker-transmission-openvpn#1653]
Hi, i im running lastest version in docker of transmission-openvpn and all is running very well except that i want to limit webui to my local ip.

I added these two parameters to container:

`TRANSMISSION_RPC_WHITELIST_ENABLED		true
TRANSMISSION_RPC_WHITELIST			       127.0.0.1,192.168.*.*`

But i always get this message:

`403: Forbidden
Unauthorized IP Address.

Either disable the IP address whitelist or add your address to it.

If you're editing settings.json, see the 'rpc-whitelist' and 'rpc-whitelist-enabled' entries.

If you're still using ACLs, use a whitelist instead. See the transmission-daemon manpage for details.`

My local PC that i want to only allow access to WebUI is: 192.168.1.16

What i need to be done to make i work?

Thanks

**Comment by pkishino** [comment]
config and logs missing
