### ISSUE TITLE
Non-issue/question - Downloading within docker (i.e. all in one solution)

### ISSUE THREAD

**Issue by Ryland0** [haugene/docker-transmission-openvpn#1654]
Discussion only!

Has anyone come up with a way to initiate downloads from within the container. A simple browser or whatnot. My reasoning is, even if I send a magnet link to this container, I'm still getting to that magnet link from my local system that is not behind the VPN. As mentioned in the title, this is totally a non issue as a) I can run a VPN session from my local system if I need to, and b) I am not using my ISP DNS anywhere on my network.

**Comment by pkishino** [comment]
what would be the point in this as you already mention points a and b ?
you still need to access the container etc? this sounds more like you would be better of spinning up a vm ..

**Comment by clement-z** [comment]
The container optionally runs an HTTP proxy which allows you to use the VPN using browsers extensions such as FoxyProxy. It might sound like what you want?

**Comment by Ryland0** [comment]
> The container optionally runs an HTTP proxy which allows you to use the VPN using browsers extensions such as FoxyProxy. It might sound like what you want?

I'll look into this. I believe that is the exact answer to my query. Thank you!

**Comment by clement-z** [comment]
* Wiki section: https://haugene.github.io/docker-transmission-openvpn/web-proxy/
* Tiny proxy web page: https://tinyproxy.github.io/

If you use UFW inside the container, don't forget to open the port there.

**Comment by Ryland0** [comment]
Wow, this is great. Thank you very much for your help. For anyone else interested, I found this extension that will work nicely.

https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif/related
