### ISSUE TITLE
My VPN subscription ran out for PIA, but my container is still uploading

### ISSUE THREAD

**Issue by ajutras** [haugene/docker-transmission-openvpn#1655]
**Describe the problem**
Hello everyone, my subscription ran out on PIA 3 days ago (planned, I wanted to switch to another provider). I didn't bother to stop my container, thinking that if my sub would ran out I would simply stop downloading/uploading. From what I understood of docker-transmission-openvpn is that if the VPN connection fails everything stop and I don't expose myself.

I checked my Transmission GUI and surprisingly I'm still uploading on my last torrent open. I stopped the torrent, then started it again and it started uploading again. Is it supposed to do so? I thought it would stop, am I exposing myself right now? Could it be an issue at PIA where they were slow to remove my VPN access? How can I verify if I'm exposing myself right now? Do the OpenVPN access just remain open as long as I don't close it?

Screenshot from PIA account interface:

![image](https://user-images.githubusercontent.com/3429155/104214486-7e920300-5405-11eb-84a3-961dc4592297.png)

Screenshot from the Transmission remote GUI:

![image](https://user-images.githubusercontent.com/3429155/104214538-89e52e80-5405-11eb-85c1-af88bb775462.png)

**Add your docker run command or docker-compose file**
I'm running Windows Docker, I use this docker-compose file:

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - 'F:\dto-download:/data'
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=CENSORED
            - OPENVPN_USERNAME=CENSORED
            - OPENVPN_PASSWORD=CENSORED
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

**Logs**
Noting interesting. Since the last 5 days it's always the same every 15 minutes:
Reserved Port: 45619  Mon Jan 11 00:36:42 UTC 2021
Reserved Port: 45619  Mon Jan 11 00:51:43 UTC 2021
Reserved Port: 45619  Mon Jan 11 01:06:43 UTC 2021
Reserved Port: 45619  Mon Jan 11 01:21:43 UTC 2021

**Host system:**
Windows 10 with Docker version 20.10.0 build 7287ab3

**Comment by Xenov-X** [comment]
Try this - http://checkmyip.torrentprivacy.com/

Most likely is PIA being slow to block openvpn creds. May not terminate openvpn sessions that are already running.

**Comment by ajutras** [comment]
Tried the website you linked Xenov-X and it shows that I am still protected.

I closed my container, opened it again and surprise it was still connecting, it resumed my upload and re-doing the test of your link showed that I was still protected.

So I guess we can chalk this to PIA not being super great at cancelling their service. Thx!
