### ISSUE TITLE
Findutils?

### ISSUE THREAD

**Issue by purplefis** [haugene/docker-transmission-openvpn#1656]
**Before creating this issue I have:**

- [x ] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [ x] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/) to a reasonable degree

Hi all

Thanks for a great image, I for one really appreciate your work.

I'm trying to make the simple on download complete script to unrar rar files recursively. But it seems that find is referring to the busybox find which does not support the -execdir option. 

Seems that I need to login to the container and install findutils. Is that right or am I missing something?

Thanks
**Describe your request**

**Contextual information**

**Comment by pkishino** [comment]
you are free to built your own version and test it, if it works (just add findutils to the dockerfile) feel free to submit a PR

**Comment by davida72** [comment]
I'd love to see an unpack-on-complete feature. I can't find any scripts in the docs that sound suitable.

**Comment by pkishino** [comment]
I'm open to adding this if someone creates this feature and adds a PR, closing as not an issue for now
