### ISSUE TITLE
Adding environment blocklist-url resolves to '<no-value>'

### ISSUE THREAD

**Issue by tomhumphrey** [haugene/docker-transmission-openvpn#166]
Trying to add a blocklist url using the environment variables on a synology nas resolves to '<no-value>'

I'm trying to use this link:
http://list.iblocklist.com/?list=ydxerpxkpcfqjaybcssw&fileformat=p2p&archiveformat=gz

**Comment by haugene** [comment]
Hey, sorry for the late reply but as this container has gained some popularity keeping up isn't always easy.

Did a quick test now, and I see the <no value> being inserted as well. But if I set TRANSMISSION_BLOCKLIST_URL=asdasd it is correctly populated. So this probably has to do with some of the characters in the string and a need to escape them.

I don't have the time to find a fix right now, but hopefully this will point you in the right direction. The image is using [dockerize](https://github.com/jwilder/dockerize) to populate the settings.json from environment variables which in turn uses  Golang [text/template](https://golang.org/pkg/text/template/) for templates.

I can have a closer look later, we're also using a quite old release of dockerize so updating it could be a possible solution. If you have time before me, reading up on character escaping in the templates should be the way to go.

**Comment by mikumi** [comment]
Hi @tomhumphrey, have you found a solution for the blacklist url? I know that the ampersand (&) is causing the issue, but I can't find out how to escape it with dockerize. `\&` does not work.

**Comment by haugene** [comment]
Created a new issue for this, closing.
