### ISSUE TITLE
Upgrade from 2.1.4 to 3.x - yes or no? Is there a guide?

### ISSUE THREAD

**Issue by ovizii** [haugene/docker-transmission-openvpn#1660]
**Before creating this issue I have:**

- [ X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [ X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/) to a reasonable degree

**Describe your request**
I am happily running the docker image version 2.1.4 and have 2 questions:

a) Is there a benefit to upgrading to version 3.x or is there a drawback to staying with 2.1.4?
b) Is there a guide on how to upgrade and keep everything running?

**Comment by ilike2burnthing** [comment]
a) See the release changelogs, notably that for 3.0 - https://github.com/haugene/docker-transmission-openvpn/releases
b) It should just be a case of pulling a new image. There have been some issues with old ENVs and settings, so it may be best to delete `settings.json` in `transmission-home` and strip back your environment variables to what is actually needed - https://github.com/haugene/docker-transmission-openvpn/blob/master/README.md

**Comment by ovizii** [comment]
Thanks, I had read the changelogs but didn't notice anything I particularly "needed". 

Thanks for the hint of stripping back the env variables, I guess I'll take a snapshot then do that and give it a try. Lets close this thread as my question is answered. 

I will open new threads in case I run into trouble.
