### ISSUE TITLE
Support Flood for Transmission Web UI

### ISSUE THREAD

**Issue by ylor** [haugene/docker-transmission-openvpn#1661]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Implement support for the [Flood for Transmission](https://github.com/johman10/flood-for-transmission) web UI.

**Describe alternatives you've considered**
I have tried all other available Web UIs, even those not included as part of this docker image.

**Additional context**
The Flood for Transmission web UI is unequivocally (imo) better than all other projects of this kind. It seems to match the default web ui functionality, it's fast, modern, information-dense, and easy on the eyes.

**Personal note**
Thank you for all your work on this image.

**Comment by deimosian** [comment]
The 'for Transmission' fork of the old Flood burns my eyes with its lack of dark mode.

The current Flood supports Transmission, eliminating the need for the fork and should replace this.

**Comment by garret** [comment]
@deimosian Flood for transmission just got updated and dark mode was added in https://github.com/johman10/flood-for-transmission/pull/76. 

Hope to see it soon on this wonderful image.

**Comment by haugene** [comment]
@garret Triggered a new build now. We pull from the master branch so should be available in 15 min (flood build takes time)

**Comment by haugene** [comment]
@deimosian Interesting. Maybe we should add them both... 🤔

**Comment by ilike2burnthing** [comment]
@haugene us poor dev users are missing out 😋

**Comment by haugene** [comment]
@ilike2burnthing That's not fair of course. The dev branch should always be first, that's just the way it is 😅 Triggered now, and noted to avoid future blunders.
