### ISSUE TITLE
Could not find OpenVPN provider: PROTONVPN

### ISSUE THREAD

**Issue by RedSpid3r** [haugene/docker-transmission-openvpn#1664]
**Before creating this issue I have:**

- [ x] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [x ] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [x ] Tried to add as much relevant information to the issue as possible

**Describe the problem**
Container does not start because `PROTONVPN` is not recognised as a valid provider even though it is listed in the supported providers page

**Add your docker run command or docker-compose file**

**Logs**
```
Could not find OpenVPN provider: PROTONVPN
Please check your settings.
```

**Host system:**
Synology NAS

**Comment by pkishino** [comment]
missing config
