### ISSUE TITLE
Not able to connect to Web Proxy

### ISSUE THREAD

**Issue by realdeeguy** [haugene/docker-transmission-openvpn#1666]
[_VPN-Test_logs.txt](https://github.com/haugene/docker-transmission-openvpn/files/5833574/_VPN-Test_logs.txt)
Not able to connect to the web proxy. Everything was working fine yesterday (when I last used it) and today the only thing I changed was moved the docker folder "/var/lib/docker" to my ssd (connected via usb). All the containers are working fine after that move. I don't feel the move has anything to do with it but I thought of mentioning this as I am still learning the docker world and might not be aware of other things that I should have done with the move.

About the environment: Running Docker under OMV 5.5 on a RPi4

- Able to connect to internet from inside the container.
- curl ifconfig.io shows the VPN Public IP via PIA
- Able to ping 4.2.2.2
- Able to telnet & also browse transmission web ui via port 9092
- Not able to telnet webproxy port 9899
- Below is the docker compose file I am using.
===========
version: 2.4
services:
    VPN:
        container_name: VPN-Trans
        network_mode: bridge
        image: haugene/transmission-openvpn:latest
        volumes:
            - /srv/dev-disk-by-label-data01/downloads/trans:/data
            - /srv/dev-disk-by-label-data01/appdata/trans:/config
            - /srv/dev-disk-by-label-data01/appdata/pia:/etc/openvpn/pia
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=PIA
            - PUID=1000
            - PGID=100
            - OPENVPN_CONFIG=switzerland
            - OPENVPN_USERNAME=xxxxxxxxxxxxx
            - PIA_OPENVPN_CONFIG_BUNDLE=openvpn-ip-nextgen
            - OPENVPN_PASSWORD=xxxxxxxxxxxxx
            - WEBPROXY_ENABLED=true
            - WEBPROXY_PORT=9899
            - WEBPROXY_USERNAME=xxxxxxxxxxxxx
            - WEBPROXY_PASSWORD=xxxxxxxxxxxxx
            - LOCAL_NETWORK=192.168.1.0/24
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0
            - TRANSMISSION_RPC_ENABLED=true
            - TRANSMISSION_RPC_USERNAME=xxxxxxxxxxxxx
            - TRANSMISSION_RPC_PASSWORD=xxxxxxxxxxxxx
            - TRANSMISSION_RPC_PORT=9092
            - TRANSMISSION_UMASK=000
            - DROP_DEFAULT_ROUTE=true
            - TRANSMISSION_WEB_UI=transmission-web-control
            - TRANSMISSION_PEER_PORT_RANDOM_ON_START=true
            - TRANSMISSION_PEER_PORT_RANDOM_LOW=49152
            - TRANSMISSION_PEER_PORT_RANDOM_HIGH=65535
            - TRANSMISSION_PORT_FORWARDING_ENABLED=true
            - TRANSMISSION_LPD_ENABLED=false
            - TRANSMISSION_DOWNLOAD_DIR=/data/completed
            - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
            - TRANSMISSION_WATCH_DIR=/data/watch
            - TRANSMISSION_HOME=/data/transmission-home
            - ENABLE_UFW=true
            - UFW_ALLOW_GW_NET=false
            - UFW_DISABLE_IPTABLES_REJECT=false
            - HEALTH_CHECK_HOST=google.com
            - OPENVPN_OPTS=--inactive 0 --ping 10 --ping-exit 60 --pull-filter ignore ping
            - TZ=CAT
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 1m
        ports:
            - 9092:9092
            - 9899:9899
        dns:
            - 1.1.1.1
        restart: always

**Comment by pkishino** [comment]
what are you using the webproxy for?

**Comment by realdeeguy** [comment]
> what are you using the webproxy for?

Web Browsing ... Does that matter ?

**Comment by pkishino** [comment]
no, just curious as I've not seen the need to use it for anything

**Comment by realdeeguy** [comment]
> no, just curious as I've not seen the need to use it for anything

I have webproxy added in firefox as proxy when I need to go that route.

**Comment by pkishino** [comment]
I take it it’s for using the VPN connection? Why not just use the VPN
directly then?
Well, anyway, this is beside the point.
I don’t see any config issues

**Comment by pkishino** [comment]
But as no logging is attached to issue it’s hard to see.. please use the
issue template that we created..

**Comment by realdeeguy** [comment]
Thanks. I have attached the logs now

I need specific web traffic to go via VPN and not everything hence using it as web proxy via browser only.

[_VPN-Test_logs.txt](https://github.com/haugene/docker-transmission-openvpn/files/5833576/_VPN-Test_logs.txt)

**Comment by pkishino** [comment]
check the tinyproxy config file inside the container to check if the config is correct

**Comment by realdeeguy** [comment]
> check the tinyproxy config file inside the container to check if the config is correct

I have checked the tinyproxy.conf file and have also attached a copy. Don't see any issues.

[tinyproxy.log](https://github.com/haugene/docker-transmission-openvpn/files/5833961/tinyproxy.log)

**Comment by clanthier** [comment]
I have the same problem. After an update to latest, proxy stopped working. I use it a lot. Turned on log files in config and this is what I found ... got this error from a clean install on debian 10 and OMV5.5. 
CONNECT   Jan 24 17:29:21 [52]: Connect (file descriptor 7): 172.16.5.109 [172.16.5.109]
CONNECT   Jan 24 17:29:21 [50]: Connect (file descriptor 7): 172.16.5.109 [172.16.5.109]
ERROR     Jan 24 17:29:51 [52]: read_request_line: Client (file descriptor: 7) closed socket before read.
ERROR     Jan 24 17:29:51 [50]: read_request_line: Client (file descriptor: 7) closed socket before read.
ERROR     Jan 24 17:29:51 [50]: Error reading readable client_fd 7
ERROR     Jan 24 17:29:51 [52]: Error reading readable client_fd 7
WARNING   Jan 24 17:29:51 [52]: Could not retrieve request entity
WARNING   Jan 24 17:29:51 [50]: Could not retrieve request entity

**Comment by pkishino** [comment]
closing this, please create a new issue (and fill in issue template) if this is still a problem
