### ISSUE TITLE
PIA dns resolv.conf misconfiguration

### ISSUE THREAD

**Issue by izenn** [haugene/docker-transmission-openvpn#1667]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X] Tried to add as much relevant information to the issue as possible

**Describe the problem**

Resolv.conf changed to PIA-internal dns (10.0.0.243) before the VPN tunnel is established causing the curl to fail when starting the container

**Add your docker run command or docker-compose file**

Attached

**Logs**

Starting container with revision: 7b453b9d31ca11be10eca5e5abe744ef1bb0708b
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn-strong into temporary file /tmp/tmp.PIJEml
curl: (6) Could not resolve host: www.privateinternetaccess.com

**Host system:**

Synology nas Docker version 18.09.8, build bfed4f5

**Comment by izenn** [comment]
<img width="644" alt="Origin - Synology DiskStation1" src="https://user-images.githubusercontent.com/744288/104989490-331cbd80-59e0-11eb-9e77-f0e44f3ff2f9.png">
<img width="645" alt="Origin - Synology DiskStation2" src="https://user-images.githubusercontent.com/744288/104989501-37e17180-59e0-11eb-85bd-db6ad7d01cf7.png">
<img width="640" alt="Origin - Synology DiskStation3" src="https://user-images.githubusercontent.com/744288/104989509-3b74f880-59e0-11eb-8d4f-504872e9fcd7.png">

**Comment by izenn** [comment]
additional investigation shows that it is not the initial run/dns settings that causes the dns issue, but after the first stop/start the dns is not reverted from the 10.0.0.243 to a publicly available dns server

**Comment by derekn** [comment]
i'm experiencing this issue also. i have 2 different boxes running the same image and config, one works and the other cannot resolve www.privateinternetaccess.com... weird. did a down/up and still not working. switching to the dev image fixed it, but hope it gets resolved in latest

**Comment by huntastikus** [comment]
Same here!

**Comment by pkishino** [comment]
I reverted the dns fix, please let me know if it works (I was not having any issues with this..)

**Comment by izenn** [comment]
did you push the new version to docker hub?  i'm seeing:
haugene/transmission-openvpn   latest              8a3a954e4723        45 minutes ago      123MB

but the issue is still persisting in that version.

**Comment by pkishino** [comment]
circle ci build issues..

**Comment by pkishino** [comment]
latests is 
https://hub.docker.com/r/haugene/transmission-openvpn/tags?page=1&ordering=last_updated
123mb doesnt seem right..
please check

**Comment by izenn** [comment]
i have version 69c0a090c366 and it looks like it is not touching the resolv.conf now (i manually set it to 1.1.1.1 and let watchtower to do the update and stopped started and restarted multiple times to see success)

**Comment by pkishino** [comment]
ok, ..yeah, that commit needs some more work then to cover this case

**Comment by izenn** [comment]
what about setting dns to 209.222.18.222 and 209.222.18.218 (pia public dns servers)?

**Comment by pkishino** [comment]
you are saying that it still does not work after reverting the commit? then it wasn't working before either then, right?
you can set your dns for your container directly using the --dns parameter.

**Comment by izenn** [comment]
oh no -- sorry, it works after the reversion, i commented in the wrong issue -- i meant to comment in the dns leak issue by recommending to set the dns to pia's public dns servers before the vpn kicks in and changes the dns to the internal servers

**Comment by pkishino** [comment]
ok, let's close this issue then.. but rather use cloudflare or google dns until vpn starts than a specific vpn dns..

**Comment by b055k060644** [comment]
I have success after changing resolv.cong to cloudflare DNS.

**Comment by enorme75** [comment]
> I have success after changing resolv.conf to cloudflare DNS.

Same here ! thanks !
