### ISSUE TITLE
No port forwarding?

### ISSUE THREAD

**Issue by ouafnico** [haugene/docker-transmission-openvpn#167]
Hi

Using PIA, it seems the port forwarding does not work anymore.

root@b5ef704dd9bc:/# /etc/transmission/updatePort.sh MYIP
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   149  100    57  100    92     66    106 --:--:-- --:--:-- --:--:--   106
Got new port  from pia
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 400: Bad Request

Any idea how to fix?
It seems the URL https://www.privateinternetaccess.com/vpninfo/port_forward_assignment is not good anymore.

**Comment by blakejohnson86** [comment]
While running that command, I got a new port assignment back, it does not automatically set it in Transmissioin anymore.

> root@4bab00549c2f:/# /etc/transmission/updatePort.sh IP
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   105  100    14  100    91      2     13  0:00:07  0:00:06  0:00:01    26
> Got new port 34*** from pia
> transmission auth required
> Unexpected response: <h1>301: Moved Permanently</h1>t: transmission-remote/2.92 (14714)
> Host: localhost:9091
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
> Unexpected response: <h1>301: Moved Permanently</h1>t: transmission-remote/2.92 (14714)
> Host: localhost:9091
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
> Checking port...
> Unexpected response: <h1>301: Moved Permanently</h1>t: transmission-remote/2.92 (14714)
> Host: localhost:9091
> Accept: */*
> Accept-Encoding: deflate, gzip

**Comment by ouafnico** [comment]
It seems to work for me using France pia server. Using other does not work

**Comment by rosshettel** [comment]
I'm seeing this issue too - not getting any port back from updatePort.sh

**Comment by rosshettel** [comment]
Just tried the France PIA server as @ouafnico reported, and that worked fine

**Comment by haugene** [comment]
Thanks to @rosshettel for providing a fix for this issue. The script is updated so that it doesn't mess with the transmission port configuration if the port call to PIA fails or times out.

The code is merged and available on the latest tag. Please pull the image again and let us know how it works :smile:
