### ISSUE TITLE
CyberGhost

### ISSUE THREAD

**Issue by zockerei** [haugene/docker-transmission-openvpn#1674]
**Which provider?**

CyberGhost

**Where are the configs?**

[openvpn.zip](https://github.com/haugene/docker-transmission-openvpn/files/5839409/openvpn.zip)

**Comment by Justdigit** [comment]
> **Which provider?**
> 
> CyberGhost
> 
> **Where are the configs?**
> 
> [openvpn.zip](https://github.com/haugene/docker-transmission-openvpn/files/5839409/openvpn.zip)

Did you found out how to connect i just keeping the AUth failure each time
