### ISSUE TITLE
"bad signature" over and over in logs, new torrents won't start after some time

### ISSUE THREAD

**Issue by mikeymasonic** [haugene/docker-transmission-openvpn#1680]
**Before creating this issue I have:**
- [ X ] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [ X ][Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [ X ] Tried to add as much relevant information to the issue as possible

**Describe the problem**

I've been using this docker image for years now (THANK YOU FOR YOUR HARD WORK!).  Recently just updated everything to version 3.3, using PIA as my vpn.  Everything seems to work at first, but then after some time my any new torrents I add never start downloading and I see the following repeated over and over again in the logs:

2021-01-19 13:53:09 | stdout | Tue Jan 19 13:53:09 UTC 2021: Rebind interval: 1800 seconds
-- | -- | --
2021-01-19 13:53:09 | stdout | Tue Jan 19 13:53:09 UTC 2021: Forwarding on port
2021-01-19 13:53:09 | stdout | Tue Jan 19 13:53:09 UTC 2021: Server accepted PF bind
2021-01-19 13:53:09 | stdout | the has been a fatal_error
2021-01-19 13:53:09 | stdout | { "status": "", "message": "bad signature" }
2021-01-19 13:53:09 | stdout | Tue Jan 19 13:53:09 UTC 2021: bindPort error
2021-01-19 13:53:08 | stdout | Tue Jan 19 13:53:08 UTC 2021: Obtained PF token. Expires at
2021-01-19 13:53:08 | stdout | date: invalid date ''
2021-01-19 13:53:08 | stdout | parse error: Invalid numeric literal at EOF at line 1, column 3
2021-01-19 13:53:08 | stdout | parse error: Invalid numeric literal at EOF at line 1, column 3
2021-01-19 13:53:08 | stdout | the has been a fatal_error
2021-01-19 13:53:08 | stdout | { "status": "ERROR", "message": "Login failed!" }
2021-01-19 13:53:08 | stdout | Tue Jan 19 13:53:08 UTC 2021: getSignature error
2021-01-19 13:53:06 | stdout | Tue Jan 19 13:53:06 UTC 2021: PF token will expire soon. Getting new one.
2021-01-19 13:53:06 | stdout | the has been a fatal_error
2021-01-19 13:53:06 | stdout | { "status": "", "message": "bad signature" }
2021-01-19 13:53:06 | stdout | Tue Jan 19 13:53:06 UTC 2021: bindPort error
2021-01-19 13:23:05 | stdout | Tue Jan 19 13:23:05 UTC 2021: Rebind interval: 1800 seconds

hoping I just have a bad setting somewhere.  thank you so much for your help!

**Add your docker run command or docker-compose file (please paste into a code block using "\`")**
![haugene1](https://user-images.githubusercontent.com/35716186/105222100-de2b9500-5b0e-11eb-9dd5-4edf04648dbc.png)
![haugene2](https://user-images.githubusercontent.com/35716186/105222105-e08def00-5b0e-11eb-8eea-eaf796321715.png)
![haugene3](https://user-images.githubusercontent.com/35716186/105222107-e08def00-5b0e-11eb-855b-dbae0c5b41be.png)
![haugene4](https://user-images.githubusercontent.com/35716186/105222109-e1268580-5b0e-11eb-9c6f-97f1ac7cabd8.png)

**Host system:**
Synology NAS Docker App

**Comment by mikeymasonic** [comment]
added us_california to OPENVPN_CONFIG in the environment, these are the latest logs:

curl: (7) Failed to connect to 10.40.112.1 port 19999: Connection refused                 
Wed Jan 20 20:11:04 UTC 2021: bindPort error                                              
                                                                                          
the has been a fatal_error                                                                
Wed Jan 20 20:11:04 UTC 2021: PF token will expire soon. Getting new one.                 
curl: (7) Failed to connect to 10.40.112.1 port 19999: Connection refused                 
Wed Jan 20 20:11:04 UTC 2021: getSignature error                                          
                                                                                          
the has been a fatal_error                                                                
date: invalid date ''                                                                     
Wed Jan 20 20:11:04 UTC 2021: Obtained PF token. Expires at                               
curl: (7) Failed to connect to 10.40.112.1 port 19999: Connection refused                 
Wed Jan 20 20:11:04 UTC 2021: bindPort error                                              
                                                                                          
the has been a fatal_error                                                                
Wed Jan 20 20:11:04 UTC 2021: Server accepted PF bind                                     
Wed Jan 20 20:11:04 UTC 2021: Forwarding on port                                          
Wed Jan 20 20:11:04 UTC 2021: Rebind interval: 1800 seconds

**Comment by pkishino** [comment]
I think this has to do with pia changes to their setup, please search for the pia threads, the current configs in the container don’t work I think

**Comment by mikeymasonic** [comment]
adding the following made torrents start downloading for me.
```
OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
```
override dns server to PIA's dns servers
```
OVERRIDE_DNS_1=209.222.18.222
OVERRIDE_DNS_2=209.222.18.218
```

A few interesting notes: when I started my container with this configuration, I had no weird error messages (bad request, etc).  Only 1 of four torrents started downloading.  That one torrent finished, the rest sat there.  Stopped and started the container, one torrent started and finished.  Added another torrent while the one torrent was downloading, it started, but there was another torrent in there that _should_ have started, after a few minutes, that torrent started up.

I got rid of OPENVPN_CONFIG and just let the container choose a server, if I had OPENVPN_CONFIG in my env, I would get errors, I tried 'us_seattle' and 'us_california', neither worked well.

I'm using the latest dev build as of 01-21-2021.  hope this helps someone out there!

**Comment by entropical** [comment]
> hope this helps someone out there!

It helped me. Thanks @mikeymasonic
