### ISSUE TITLE
Issue with latest build

### ISSUE THREAD

**Issue by fatbob01** [haugene/docker-transmission-openvpn#1681]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X] Tried to add as much relevant information to the issue as possible

**Describe the problem**

Docker container keeps restarting.  This only happened a few days ago.  Tried rolling back to 3.3, issue persists

**Add your docker run command or docker-compose file (please paste into a code block using "\`")**

ENV	
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin	
OPENVPN_PROVIDER	IPVANISH
GLOBAL_APPLY_PERMISSIONS	true
TRANSMISSION_HOME	/data/transmission-home
TRANSMISSION_RPC_PORT	9091
TRANSMISSION_DOWNLOAD_DIR	/data/completed
TRANSMISSION_INCOMPLETE_DIR	/data/incomplete
TRANSMISSION_WATCH_DIR	/data/watch
CREATE_TUN_DEVICE	true
ENABLE_UFW	false
UFW_ALLOW_GW_NET	false
UFW_EXTRA_PORTS	
UFW_DISABLE_IPTABLES_REJECT	false
PUID	1000
PGID	1000
DROP_DEFAULT_ROUTE	
WEBPROXY_ENABLED	false
WEBPROXY_PORT	8888
WEBPROXY_USERNAME	
WEBPROXY_PASSWORD	
LOG_TO_STDOUT	false
HEALTH_CHECK_HOST	google.com
REVISION	afdf1acb6a891b93e292e46279ad97bf1c19156b
LOCAL_NETWORK	192.168.2.0/24
OPENVPN_OPTS	--inactive 3600 --ping 10 --ping-exit 60
OPENVPN_CONFIG	ipvanish-CA-Montreal-yul-c01,ipvanish-SE-Stockholm-sto-a08,ipvanish-NO-Oslo-osl-c01

**Logs (please paste into a code block using "\`")**

Starting container with revision: afdf1acb6a891b93e292e46279ad97bf1c19156b,
Creating TUN device /dev/net/tun,
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: IPVANISH,
Provider IPVANISH has a custom setup script, executing it,
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.dOAFGK,
curl: (6) Could not resolve host: www.ipvanish.com,

**Host system:**

Synology running docker container

**Comment by pkishino** [comment]
Please check again with latest, I do believe you have a slightly older built, it should be fixed in latest, otherwise set —dns to docker run (or compose)

**Comment by fatbob01** [comment]
Managed to resolve it by editing resolv.conf and changing DNS servers

**Comment by paulr24** [comment]
> Managed to resolve it by editing resolv.conf and changing DNS servers

Thanks, this worked for me as well!
