### ISSUE TITLE
Container wont run -- Might be a NORDVPN connection issue

### ISSUE THREAD

**Issue by cjchiarello** [haugene/docker-transmission-openvpn#1684]
**Before creating this issue I have:**

- [x ] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [ x] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/) to a reasonable degree

I had to recently rebuild my vm that runs my docker containers and when trying to redeploy Transmission with my below build I get an deployment error with the following logs (attached)
[_practical_kowalevski_logs.txt](https://github.com/haugene/docker-transmission-openvpn/files/5852250/_practical_kowalevski_logs.txt)

What am I missing to get this running - its was running find for years before.

`docker run --cap-add=NET_ADMIN -d \
              -v /home/carmen/downloads/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=NORDVPN \
              -e NORDVPN_COUNTRY=CA \
              -e OPENVPN_USERNAME=xxxxxxxx@xxxxx.com \
              -e OPENVPN_PASSWORD=xxxxxxxxxxxxxxx \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.3.0/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn>`

**Comment by pkishino** [comment]
Please use the complete issue template..don't just delete parts of it
