### ISSUE TITLE
Multiple endpoints for VPN hostname

### ISSUE THREAD

**Issue by davida72** [haugene/docker-transmission-openvpn#1688]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/) to a reasonable degree

**Describe your request**

Great container. Thank you.

I'm using TorGuard as a VPN which is supported. 

My issue is that a VPN hostname can point to multiple IPs, which makes port forwarding at the VPN unreliable.

e.g. When I connect to ger.torguard.net I get one of three IP addresses. The VPN requires a specific IP for port forwarding to work.

Three possible solutions:
1) set up a custom OVPN which uses IPs instead of a hostname. This is what I do with another Torrent client.
2) amend the OVPN files in the container to use a fixed IP
3) duplicate port forwarding entries for each IP at the VPN

Maybe there's a better option that I'm missing?

Thanks

**Comment by pkishino** [comment]
moving forward I'd recommend you use 1) with CUSTOM provider option for this as we will be removing all ovpns once we finish the solution
