### ISSUE TITLE
New VPN provider

### ISSUE THREAD

**Issue by gabe9** [haugene/docker-transmission-openvpn#169]
Hi:

Would it be possible to add CyberGohst as a VPN provider?

I tried but was not successful. I used the attached .ovpn file.
[openvpn.ovpn.txt](https://github.com/haugene/docker-transmission-openvpn/files/642837/openvpn.ovpn.txt)

https://www.cyberghostvpn.com/ 

Thanks,

**Comment by haugene** [comment]
Hi,

It's been a while, but maintaining this project has become more work over the years with the increasing popularity.

The ovpn file you've sent me references three key files and certificates:
```
ca ca.crt
cert client.crt
key client.key
```

Would need these as well to make it work. Doesn't seem like I can download configuration without an accout. Please provide them as well as ovpn files for a couple of more locations and I can add them for you.

**Comment by Gomilo** [comment]
Hi,

I though I would respond to this. I am in the same situation and being my first experience ever with docker I have not been able to do it myself. I don't know where my error is. I try to add a cyberghost folder inside openvpn and provide the required files inside that folder (ca.crt, client.crt, client.key and Netherlands.ovpn) and rebuild the container (using the command `sudo docker build .`). When I try to run the docker with this code:
`sudo docker run --privileged  -d \
              -v /home/Storage/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e "OPENVPN_PROVIDER=cyberghost" \
              -e "OPENVPN_CONFIG=Netherlands" \
              -e "OPENVPN_USERNAME=username" \
              -e "OPENVPN_PASSWORD=password" \
              -p 9091:9091 \
              haugene/transmission-openvpn`
I get an error saying:
"Could not find OpenVPN provider: cyberghost
Please check your settings."

I though I would try setting up the custom vpn instead using the following command:
`sudo docker run --privileged  -d \
              -v /home/Documents/cyberghost/Netherlands.ovpn:/etc/openvpn/custom/defaults.ovpn \
              -v /home/Storage/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e "OPENVPN_PROVIDER=CUSTOM" \
              -e "OPENVPN_CONFIG=Netherlands" \
              -e "OPENVPN_USERNAME=username" \
              -e "OPENVPN_PASSWORD=password" \
              -p 9091:9091 \
              haugene/transmission-openvpn`

I receive an error saying that "Supplied config Netherlands.ovpn could not be found."

It might just be me, as a first timer, that can't figure this out, but I could use some help.
I attached the files I am having troubles with. (The first zip is for Netherlands, second is for Sweden, third is for Germany and fourth is for Poland).

[CyberGhost.ovpn.zip](https://github.com/haugene/docker-transmission-openvpn/files/911600/CyberGhost.ovpn.zip)
[CyberGhost.ovpn(1).zip](https://github.com/haugene/docker-transmission-openvpn/files/911607/CyberGhost.ovpn.1.zip)
[CyberGhost.ovpn(2).zip](https://github.com/haugene/docker-transmission-openvpn/files/911609/CyberGhost.ovpn.2.zip)
[CyberGhost.ovpn(3).zip](https://github.com/haugene/docker-transmission-openvpn/files/911610/CyberGhost.ovpn.3.zip)

I hope you can help with this setup and maybe point me in the right direction of what I was doing wrong and thank you for creating this container.
