### ISSUE TITLE
Removal of Perfect Privacy as a Provider

### ISSUE THREAD

**Issue by pchristod** [haugene/docker-transmission-openvpn#1695]
**Before creating this issue I have:**
- [ x] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [ x] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/) to a reasonable degree

Hi,

I updated the container today and surprisingly found PP to be removed. I've read up on it and I know this might be a hot topic due to https://github.com/haugene/docker-transmission-openvpn/pull/1662 which I found and I do not want to start any (further) political discussion here whatsoever, however the issue was (maybe understandibly?) closed very fast without any further factual discussion which is a bit disappointing to me imho because it leaves PP users without native support. 

It seems the decision in the initially linked PR is mostly based on (linked) articles from around 2012, while also the 1-2 newer ones in this link-collection will cite back to the articles from 2012 as source. After a bit of research it seems also untrue that PP has never responded to this. Actually the most recent source on this matter I could find is an interview with the company from a well know german website focused on privacy, called tarnkappe.info. It can be easily translated via Google Translate, important stuff is in the middle. This is from 2015. Source: https://tarnkappe.info/vpn-anbieter-perfect-privacy-im-interview/
The key message is basically that PP denies having any right background, stating they are politically neutral and let go of questionable employees a while back (remember this is from 2015).

This is of course not my decision, nor do I want to force anything, however I felt the removal of PP was and is a bit unlucky cause it seems very one sided. I agree this would be on a different scale, but if it would go by political controversies in a provider you would also need to consider removing NordVPN since they seemed to have sponsor(ed) willingly a white nationalist last year https://twitter.com/NordVPN/status/1278606760329261059
 
While I of course do not know exactly a 100% what these companies are up to I felt at least the need to clarify my further findings on this topic. Please feel free to close this issue if you see fit, altough I would still be very happy to see a short response if possible. I will accept that and will not bother you again regarding this topic. After all I really enjoy all the stuff you put together here, which is an amazing piece of work and imho one of the best Docker Images I've seen out here. So please don't kill me for bringing this up :)

**Comment by ilike2burnthing** [comment]
>Hello,
>just a quick comment,
>considering there is a clear connection to ILLEGAL and CRIMINAL (not political or ideological) activity of this provider by its founders **there will be no further discussion around this.**
>anyone that still feels the need to support that kind of company is free to either look elsewhere or use the custom provider option
@pkishino 

Re: NordVPN, a mistake/oversight in vetting a youtuber for a sponsor link (which has since been disabled) isn't really the same.

**Comment by pchristod** [comment]
Which is what I said ("different scale), it's merely an example to demonstrate that if you go looking for something you will most likely find something. And I'm sure people will react in different ways about this stuff. Some wont care, some will.

Of course I know the post you quoted (since I even linked it), I still feel this original PR was missing information/proper discussion since it only mentions a few articles from 9 years ago which all ping back to the same source, even the 2 newer ones in there. Additionally they are mostly in German so I doubt non german speaking folks would read up on this subject much beyond what was provided as description in the PR.

**Comment by ilike2burnthing** [comment]
I assumed you has missed the part where a maintainer of the project had said there was to be no further discussion on the issue, rather than you deciding to just ignore it. I'd suggest deleting this.

**Comment by pchristod** [comment]
Let me decide what I do and what not. Additionally I'd suggest you leave this issue if you have nothing to contribute of value nor being able to read and understand my text fully.

@everyone else: I still don't see anything wrong with opening an issue here. Something was presented initially, I present additonal background in a calm structured manner, simple as that.

**Comment by ilike2burnthing** [comment]
I'm sure the digital communications agency based in Glasgow, Scotland appreciate the tag.

**Comment by tfehren** [comment]
any update on this?

**Comment by pkishino** [comment]
All providers will be removed moving forward anyway, once we can settle down on the split and get the provider repo working as we want. 
No further discussion needed
