### ISSUE TITLE
Trying to connect to NordVPN: parse error: Invalid numeric literal at line 1, column 7

### ISSUE THREAD

**Issue by teuteuguy** [haugene/docker-transmission-openvpn#1697]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X] Tried to add as much relevant information to the issue as possible

**Describe the problem**

**Add your docker run command or docker-compose file**

 
 ```
 <!-- Paste here -->
 ```

**Logs**

 ```
Starting container with revision: 5bf2162e3af0eb5343b677369af93f40299eaa91


Creating TUN device /dev/net/tun


Using OpenVPN provider: NORDVPN


Provider NORDVPN has a custom setup script, executing it


2021-02-02 15:24:42 Checking curl installation


2021-02-02 15:24:42 Removing existing configs


2021-02-02 15:24:42 Selecting the best server...


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:24:42 Searching for technology: openvpn_tcp


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:24:42 Unable to find a server with the specified parameters, using any recommended server


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:24:42 Best server : 


2021-02-02 15:24:42 Downloading config: default.ovpn


2021-02-02 15:24:42 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn


2021-02-02 15:24:42 Selecting the best server...


parse error: Invalid numeric literal at line 1, column 7


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:24:42 Searching for technology: openvpn_tcp


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:24:42 Unable to find a server with the specified parameters, using any recommended server


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:24:42 Best server : 


2021-02-02 15:24:42 Downloading config: .ovpn


2021-02-02 15:24:42 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn


No VPN configuration provided. Using default.


Modifying /etc/openvpn/nordvpn/default.ovpn for best behaviour in this container


Setting OpenVPN credentials...


adding route to local network 192.168.0.0/16 via 172.17.0.1 dev eth0


Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.10)


Use --help for more information.


Starting container with revision: 5bf2162e3af0eb5343b677369af93f40299eaa91


Creating TUN device /dev/net/tun


Using OpenVPN provider: NORDVPN


Provider NORDVPN has a custom setup script, executing it


2021-02-02 15:26:33 Checking curl installation


2021-02-02 15:26:33 Removing existing configs


2021-02-02 15:26:33 Selecting the best server...


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:26:33 Searching for technology: openvpn_tcp


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:26:33 Unable to find a server with the specified parameters, using any recommended server


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:26:33 Best server : 


2021-02-02 15:26:33 Downloading config: default.ovpn


2021-02-02 15:26:33 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn


2021-02-02 15:26:33 Selecting the best server...


parse error: Invalid numeric literal at line 1, column 7


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:26:33 Searching for technology: openvpn_tcp


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:26:33 Unable to find a server with the specified parameters, using any recommended server


parse error: Invalid numeric literal at line 1, column 7


2021-02-02 15:26:33 Best server : 


2021-02-02 15:26:33 Downloading config: .ovpn


2021-02-02 15:26:33 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn


No VPN configuration provided. Using default.


Modifying /etc/openvpn/nordvpn/default.ovpn for best behaviour in this container


Setting OpenVPN credentials...


adding route to local network 192.168.0.0/16 via 172.17.0.1 dev eth0


Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.10)
 ```

**Host system:**

 ```
Ubuntu on an Intel box.
 ```

**Comment by pchristod** [comment]
Hi,

just a suggestion, but it looks to me that the server is down which is used to download the config from: https://downloads.nordcdn.com/configs/files
Is there something created under /etc/openvpn/nordvpn in the container?

**Comment by ilike2burnthing** [comment]
NordVPN-specific ENV variables - https://haugene.github.io/docker-transmission-openvpn/provider-specific/

It isn't down, it just blocks access to parent directories, the files are still accessible though, e.g. https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us2900.nordvpn.com.tcp.ovpn

**Comment by fredericrous** [comment]
I am getting the same issue, according to the documentation the URL should be something like `https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/[ANSWER.0.HOSTNAME].tcp.ovpn` however ANSWER.0.HOSTNAME seems to be empty because the resulting URL is https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn and it gives me a 404 if I try to navigate to it from chrome

**Comment by ilike2burnthing** [comment]
>Add your docker run command or docker-compose file

**Comment by teuteuguy** [comment]
I managed to "fix" the problem, by re-pulling the latest image.
Doing so, problem went away. But still odd.

**Comment by fredericrous** [comment]
I bet there is simpler than the config I use. I'm sure you should be able to reproduce without the traefik_network stuff, but here is my config:

```yaml
version: "3.6"

networks:
  internal:
  traefik_public:
    external: true

services:
  transmission:
    image: haugene/transmission-openvpn:latest
    volumes:
      - ${SHARED_MEDIA}/transmission:/data
      - ${ETC_LOCALTIME}:/etc/localtime:ro
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=NORDVPN
      - NORDVPN_COUNTRY=FR
      - NORDVPN_PROTOCOL=tcp
      - NORDVPN_CATEGORY=P2P
      - OPENVPN_USERNAME=my@ema.il
      - "OPENVPN_PASSWORD=My Password"
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/24
    cap_add:
      - NET_ADMIN
    networks:
      internal:
      traefik_public:
        aliases:
          - transmission
    restart: unless-stopped
```

the command line to run the container:

```sh
docker-compose --compatibility -f "$file" up --force-recreate -d &
```

The traefik_public network was created with the below command:

```sh
docker network create --driver=overlay --subnet=172.1.1.0/22 --attachable traefik_public
```

the image I use:

```sh
> docker images | grep transmi
haugene/transmission-openvpn         latest       60489e348108   6 days ago      123MB
```

**Comment by pkishino** [comment]
fixed

**Comment by omeryagmurlu** [comment]
I'm having the exact same issue with the latest container

**Comment by markdchurchill** [comment]
This issue can occur when the server selection API endpoint returns a 429 (Too many requests) if you've been hammering it with an autorestarting container.

**Comment by kiwidoggie** [comment]
This issue is happening again with the latest image.

**Comment by edgd1er** [comment]
@kiwidoggie 
* Commenting on a closed issue, is not a very good idea.
* giving no information about your configuration nor the log file is not helping
* the nordvpn script has changed, caching requests, especially, to avoid api hammering has been developed
* errror/warning message are more detailed.
* You are not the only one to use nordvpn, but seems the only one to have the problem. is it a new issue, a improper configuration , a start loop of the container ?

Based on all this information, I suggest you open a proper issue with all the information that may help. the issue has a template to guide you.

**Comment by pkishino** [comment]
@edgd1er  he did open a new issue,I transferred it to the provider repo ;)

**Comment by jonnyparris** [comment]
@pkishino - which provider repo, where? I'm tumbling down a similar rabbit hole with the same problem

**Comment by jonnyparris** [comment]
nvm, found my answer in discussions: https://github.com/haugene/docker-transmission-openvpn/discussions/2203

Nord account password change prompted bootloop which triggered throttle error reponse from nord. Letting it cool off after updating the password worked a charm

**Comment by kevle1** [comment]
Also could also be caused by the NordVPN config file endpoint being down. https://downloads.nordcdn.com/configs/files 
![image](https://github.com/haugene/docker-transmission-openvpn/assets/36955177/e424e91f-2c22-4d1d-8880-3d167ffc8df0)

**Comment by mushuthecat** [comment]
Hello,

im having the same issue, is it related to nord vpn side ?

Regards

**Comment by ilike2burnthing** [comment]
For anyone else coming across this - https://github.com/haugene/docker-transmission-openvpn/issues/2638
