### ISSUE TITLE
Combustion web UI empty

### ISSUE THREAD

**Issue by particulier56** [haugene/docker-transmission-openvpn#1699]
Hi,
When I put TRANSMISSION_WEB_UI=combustion, my UI changes but I have nothing in my torrent list.

When I put kettu, it’s working fine (my actual torrent list display well).

Did I miss something in combustion configuration?

I’m looking for a web responsive UI working on iOS, but is there an iOS native app existing to monitor my torrents?

thanks for your help.

**Comment by pkishino** [comment]
Clear cache?

**Comment by particulier56** [comment]
I tried but no (even in private navigation).

**Comment by pkishino** [comment]
Please attach the logs as per template

**Comment by pkishino** [comment]
issue template not followed
