### ISSUE TITLE
ARM - automated

### ISSUE THREAD

**Issue by nd4pa** [haugene/docker-transmission-openvpn#170]
Hi,

It would be nice to have another repository for ARM, that way it would be easy to have an automated build,
in the aim to integrated it in docker-compose for example, i could have done that on my own, but since i use your amazing work i find better to submit you the idea, if you want to do it but don't find time / motivation, i'm at your disposal.

Otherwise amazing job, keep up the good work.

**Comment by haugene** [comment]
Hey, a busy season with Christmas and all. Sorry for the late reply.

I tried setting up a new automated build with tag dev-armhf that would build the ARM Dockerfile. But the build returned an error:
```
Step 5 : RUN apt-get update     && apt-get install -y transmission-cli transmission-common transmission-daemon     && apt-get install -y openvpn curl     && curl -sLO https://archive.raspbian.org/raspbian/pool/main/d/dumb-init/dumb-init_1.0.3-1_armhf.deb     && dpkg -i dumb-init_*.deb     && rm -rf dumb-init_*.deb     && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*     && curl -L https://github.com/jwilder/dockerize/releases/download/v0.2.0/dockerize-linux-armhf-v0.2.0.tar.gz | tar -C /usr/local/bin -xzv     && groupmod -g 1000 users     && useradd -u 911 -U -d /config -s /bin/false abc     && usermod -G users abc

 ---> Running in 7fd07b86cd7d

[91mpanic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "exec format error"
```

I thought I'd heard something about ARM images needing to be built on the ARM platform, and that [seems to be correct](https://forums.docker.com/t/automated-build-raspberry-pi-based-image-on-docker-hub/4155).

I'm all for an automated build for the ARM versions. But could be tricky until the hub supports it. I could buy a raspberry and set up a CI server that builds and pushes the images to the hub. But I'm not sure when or if I'll find the time or motivation as you put it. Any suggestions are welcome :)

**Comment by nd4pa** [comment]
Hey :) 
Thanks for the reply, i understand why it's not automated now ! 
It may be not that usefull now, considering that raspberry pi 2 is a bit low on hardware for that stack ( i tried with mine, and the apache server does not seems to serve the webpage correctly when download / seeding is running : 4 to 5 torrent downloading and seeding ), don't know, maybe network is choking ..... ( considering that raspberry ethernet's port is a 100M ), i'll try a new solution ( maybe dev a torrent solution with this amazing lib : https://github.com/feross/webtorrent ),or find another ARM hardware to do the job and will tell you if i found a viable solution :) until then, thanks for all and keep up the good work !

**Comment by haugene** [comment]
Update: #582 adds support for automatic builds on Docker Hub. New tag dev-armhf is [built and available](https://hub.docker.com/r/haugene/transmission-openvpn/tags/).
