### ISSUE TITLE
RPC Authentication Not Working

### ISSUE THREAD

**Issue by dn8sh6HY** [haugene/docker-transmission-openvpn#1703]
Hi, I would like to have password authentication to access the transmission web GUI. I'm running this container on OpenMediaVault 5 through Portainer. I've set the following environment variables: 
TRANSMISSION_RPC_USERNAME = foo
TRANSMISSION_RPC_PASSWORD = bar
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED = true
TRANSMISSION_RPC_ENABLED = true
I see that they have the correct values in the settings.json file. However, I am never actually asked for a password. Am I missing something?

**Comment by pkishino** [comment]
please fill out the issue template properly as detailed..
