### ISSUE TITLE
Can any one see were i'am going wrong

### ISSUE THREAD

**Issue by tuxxy132** [haugene/docker-transmission-openvpn#1704]
STARTING TRANSMISSION

Provider PIA has a script for automatic port forwarding. Will run it now.

If you want to disable this, set environment variable DISABLE_PORT_UPDATER=true

Transmission startup script complete.

2021-02-06 17:08:07 WARNING: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.

2021-02-06 17:08:07 add_route_ipv6(2000::/3 -> :: metric -1) dev tun0

2021-02-06 17:08:07 Initialization Sequence Completed

Running functions for token based port fowarding

curl: (6) Could not resolve host: www.privateinternetaccess.com

Sat Feb  6 17:08:17 UTC 2021: getSignature error

{ "status": "ERROR", "message": "Login failed!" }

the has been a fatal_error

parse error: Invalid numeric literal at EOF at line 1, column 3

parse error: Invalid numeric literal at EOF at line 1, column 3

date: invalid date ''

Sat Feb  6 17:08:18 UTC 2021: bindPort error

{ "status": "", "message": "bad signature" }

the has been a fatal_error

transmission auth not required

waiting for transmission to become responsive

transmission became responsive

    ID   Done       Have  ETA           Up    Down  Ratio  Status       Name

Sum:                None               0.0     0.0

setting transmission port to 

localhost:9091/transmission/rpc/ responded: "success"

Checking port...

**Comment by SomberJack** [comment]
I had the same problem a day or two ago. Try changing the image from *latest* to *3.3* (the prior release).  That worked for me as did *dev*.

**Comment by tuxxy132** [comment]
thanks somber will try prior image :)

**Comment by heinsenberg82** [comment]
I'm having the exact same issue with the latest version. Is this already a recognized bug?
