### ISSUE TITLE
External IP not what I expected

### ISSUE THREAD

**Issue by brucefan42** [haugene/docker-transmission-openvpn#1721]
I am trying to learn Docker and I successfully set up haugene/transmission-openvpn. The container is on 172.0.0.0 and from the console "curl ifconfig.io" shows a valid VPN ip. The container is "Healthy". I created a Jackett container with network_mode: "container:transmission" and added port 9117 to transmission-openvpn . The Jackett container shows the exact same valid VPN ip in the console (using curl ifconfig.io) and ifconfig shows the same 172.0.0.0 address that transmission-openvpn is using. I thought everything was working perfectly. However, if I go to http://localhost:9117 and do a manual search in Jackett, the link I click on shows my ACTUAL non-VPN IP address (so it seems the request is going out the 172.0.0.0 connection and not using the VPN tunnel if that makes sense). Although the transmission container is successfully pinging the VPN provider (thus the Healthy status), I'm worried that the transmission requests are in the open. Any suggestions or recommendations as to how I can further confirm my setup?

**Comment by pkishino** [comment]
Try running this inside both containers
https://github.com/macvk/dnsleaktest
Perhaps your default route is still active and needs to be dropped etc.. there should be no leaking since latest update

**Comment by brucefan42** [comment]
I wish you didn't close my issue when I still have an issue. dnsleak works great. It shows me that my IP is my VPN but the DNS lookup is not (so the status is "DNS may be leaking". Unfortunately, I don't know how to fix that. Looking at my containers, they don't have their own network (only transmission-openvpn does). So by extension, my only conclusion can be that transmission-openvpn is leaking my DNS lookups? Please correct me if I am wrong.

**Comment by pkishino** [comment]
If there is an issue please post using the issue template with all config details. 
Does dnsleak show the same for other containers etc? Check the default route etc in the containers

**Comment by brucefan42** [comment]
> Try running this inside both containers
> https://github.com/macvk/dnsleaktest
> Perhaps your default route is still active and needs to be dropped etc.. there should be no leaking since latest update

**Comment by brucefan42** [comment]
Upon further review, I think I may be ok as all the IPs listed by dnsleak are not my IP. However, I do find it curious that somehow 1337x was able to figure out and display my IP address.

**Comment by brucefan42** [comment]
I would be interested to know if you could repeat my experiment. I installed jackett with network_mode: "container:transmission". I then brought up jackett in the browser http://localhost:9117. From there I clicked on the "Manual Search" button and entered "return of the jedi" for my Query. I then selected a 1337x link and clicked on it. It showed me my IP address and location on the resulting page.

**Comment by pkishino** [comment]
I’ll try later today

**Comment by pkishino** [comment]
that makes sense though..
I just tried this but can't see any ip or location on the 1337x page..
but obviously you are opening the link in YOUR browser on YOUR
machine, not INSIDE the docker container..that's why it would see your
ip

**Comment by edgd1er** [comment]
@pkishino , @brucefan42 

Would a dnsleaktest successful run between the openvpn launch and transmission start, and/or after a tunnelUp , be a good idea ?

**Comment by pkishino** [comment]
for what purpose? 
there is no issue here, just seems like a misunderstanding of usage..
clicking a jacket link opens it in a new tab..this tab is not sending traffic through the vpn..

**Comment by edgd1er** [comment]
I agree, there is no issue.
the aim would to stop  container before starting transmission if traffic is leaking, and/or have an env variable to define action : warning or exit.

**Comment by pkishino** [comment]
there is already dns leak prevention and such in place since a few commits back, this was improved on..if one adds DROP_DEFAULT_ROUTE=true then this will drop this route in case the vpn provider doesn't sort this out when setting up the tunnel.

**Comment by edgd1er** [comment]
ok, no need to add twice the same feature. Thanks for your kind answer. I'll try to keep up with the commits and the doc ;)
