### ISSUE TITLE
Transmission Docker containers suddenly stopped working.

### ISSUE THREAD

**Issue by ItsRainingHP** [haugene/docker-transmission-openvpn#1724]
I have successfully been using this container for almost a year now with no issues. Suddenly, last night my Transmission containers fail to start up (by this I mean it gets to the point below and does nothing, no restart, crash, etc) and the GUI is never accessible. I have spent hours searching for a similar log as mine but cannot find anyone having my issues. I know for a fact my VPN credentials are solid. Nothing on the VPN side changed so I am clueless as to the cause of this sudden error. I have tried deleting an remaking my container (including redownloading the latest image) and I still have the same issue. I have also tried changing ovpn server/files. I have tried using CUSTOM and EXPRESSVPN as the provider variable. In the past I have been using CUSTOM this entire time without issues. Below is my log and JSON file. For obvious reasons I removed my user/pass from the JSON.

2021-02-17 15:17:22 | stdout | 2021-02-17 15:17:22 library versions: OpenSSL 1.1.1i  8 Dec 2020, LZO 2.10
-- | -- | --
2021-02-17 15:17:22 | stdout | 2021-02-17 15:17:22 OpenVPN 2.5.0 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Dec 26 2020
2021-02-17 15:17:22 | stdout | 2021-02-17 15:17:22 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
2021-02-17 15:17:22 | stdout | 2021-02-17 15:17:22 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
2021-02-17 15:17:22 | stdout | adding route to local network 192.168.50.0/24 via 172.17.0.1 dev eth0
2021-02-17 15:17:21 | stdout | Setting OpenVPN credentials...
2021-02-17 15:17:21 | stdout | No VPN configuration provided. Using default.
2021-02-17 15:17:21 | stdout | Using OpenVPN provider: CUSTOM
2021-02-17 15:17:21 | stdout | mknod: /dev/net/tun: File exists
2021-02-17 15:17:21 | stdout | Creating TUN device /dev/net/tun
2021-02-17 15:17:21 | stdout | WARNING: initial DNS resolution test failed
2021-02-17 15:17:16 | stdout | Starting container with revision: b68db41955e7b444795fa38ec4d268318f63d0c7

{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "dumb-init /etc/openvpn/start.sh",
   "cpu_priority" : 50,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : false,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "OPENVPN_USERNAME",
         "value" : "###################"
      },
      {
         "key" : "OPENVPN_PASSWORD",
         "value" : "################"
      },
      {
         "key" : "OPENVPN_PROVIDER",
         "value" : "CUSTOM"
      },
      {
         "key" : "GLOBAL_APPLY_PERMISSIONS",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_HOME",
         "value" : "/downloads/transmission-home"
      },
      {
         "key" : "TRANSMISSION_RPC_PORT",
         "value" : "9091"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_DIR",
         "value" : "/downloads/completed"
      },
      {
         "key" : "TRANSMISSION_INCOMPLETE_DIR",
         "value" : "/downloads/incomplete"
      },
      {
         "key" : "TRANSMISSION_WATCH_DIR",
         "value" : "/downloads/watch"
      },
      {
         "key" : "CREATE_TUN_DEVICE",
         "value" : "true"
      },
      {
         "key" : "ENABLE_UFW",
         "value" : "false"
      },
      {
         "key" : "UFW_ALLOW_GW_NET",
         "value" : "false"
      },
      {
         "key" : "UFW_EXTRA_PORTS",
         "value" : ""
      },
      {
         "key" : "UFW_DISABLE_IPTABLES_REJECT",
         "value" : "false"
      },
      {
         "key" : "PUID",
         "value" : "1024"
      },
      {
         "key" : "PGID",
         "value" : "101"
      },
      {
         "key" : "DROP_DEFAULT_ROUTE",
         "value" : ""
      },
      {
         "key" : "WEBPROXY_ENABLED",
         "value" : "false"
      },
      {
         "key" : "WEBPROXY_PORT",
         "value" : "8888"
      },
      {
         "key" : "WEBPROXY_USERNAME",
         "value" : ""
      },
      {
         "key" : "WEBPROXY_PASSWORD",
         "value" : ""
      },
      {
         "key" : "LOG_TO_STDOUT",
         "value" : "false"
      },
      {
         "key" : "HEALTH_CHECK_HOST",
         "value" : "google.com"
      },
      {
         "key" : "REVISION",
         "value" : "b68db41955e7b444795fa38ec4d268318f63d0c7"
      },
      {
         "key" : "TRANSMISSION_WEB_UI",
         "value" : "transmission-web-control"
      },
      {
         "key" : "LOCAL_NETWORK",
         "value" : "192.168.50.0/24"
      }
   ],
   "exporting" : false,
   "id" : "b48fa7810fe5c865ac34ae403cf286f8e54a042268ce7266aa5675aaaa8aebd4",
   "image" : "haugene/transmission-openvpn:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "transmission-manual",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 9091,
         "host_port" : 9091,
         "type" : "tcp"
      }
   ],
   "privileged" : true,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/downloads",
         "mount_point" : "/downloads",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/transmission",
         "mount_point" : "/config",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/transmission/resolv.conf",
         "mount_point" : "/etc/resolv.conf",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/transmission/my_expressvpn_usa_-_los_angeles_-_1_udp.ovpn",
         "mount_point" : "/etc/openvpn/custom/default.ovpn",
         "type" : "rw"
      }
   ]
}

**Comment by b055k060644** [comment]
Same issue.

**Comment by pkishino** [comment]
Seriously.. we have a clear issue template that explains exactly how to fill it in to make it easy to read and parse.. and you just completely ignore it..
