### ISSUE TITLE
Transmission containers suddenly stopped working. No changes to configs.

### ISSUE THREAD

**Issue by ItsRainingHP** [haugene/docker-transmission-openvpn#1729]
**Before creating this issue I have:**
- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible

**Describe the problem**
I have successfully been using this container for almost a year now with no issues. Suddenly, last night my Transmission containers fail to start up (by this I mean it gets to the point below and does nothing, no restart, crash, etc) and the GUI is never accessible. I have spent hours searching for a similar log as mine but cannot find anyone having my issues. I know for a fact my VPN credentials are solid. Nothing on the VPN side changed so I am clueless as to the cause of this sudden error. I have tried deleting an remaking my container (including redownloading the latest image) and I still have the same issue. I have also tried changing ovpn server/files. I have tried using CUSTOM and EXPRESSVPN as the provider variable. In the past I have been using CUSTOM this entire time without issues. Below is my log and JSON file. For obvious reasons I removed my user/pass from the JSON.

**Add your docker run command or docker-compose file**

 
 ```
{
"cap_add" : null,
"cap_drop" : null,
"cmd" : "dumb-init /etc/openvpn/start.sh",
"cpu_priority" : 50,
"devices" : null,
"enable_publish_all_ports" : false,
"enable_restart_policy" : true,
"enabled" : false,
"env_variables" : [
{
"key" : "PATH",
"value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
},
{
"key" : "OPENVPN_USERNAME",
"value" : "###################"
},
{
"key" : "OPENVPN_PASSWORD",
"value" : "################"
},
{
"key" : "OPENVPN_PROVIDER",
"value" : "CUSTOM"
},
{
"key" : "GLOBAL_APPLY_PERMISSIONS",
"value" : "true"
},
{
"key" : "TRANSMISSION_HOME",
"value" : "/downloads/transmission-home"
},
{
"key" : "TRANSMISSION_RPC_PORT",
"value" : "9091"
},
{
"key" : "TRANSMISSION_DOWNLOAD_DIR",
"value" : "/downloads/completed"
},
{
"key" : "TRANSMISSION_INCOMPLETE_DIR",
"value" : "/downloads/incomplete"
},
{
"key" : "TRANSMISSION_WATCH_DIR",
"value" : "/downloads/watch"
},
{
"key" : "CREATE_TUN_DEVICE",
"value" : "true"
},
{
"key" : "ENABLE_UFW",
"value" : "false"
},
{
"key" : "UFW_ALLOW_GW_NET",
"value" : "false"
},
{
"key" : "UFW_EXTRA_PORTS",
"value" : ""
},
{
"key" : "UFW_DISABLE_IPTABLES_REJECT",
"value" : "false"
},
{
"key" : "PUID",
"value" : "1024"
},
{
"key" : "PGID",
"value" : "101"
},
{
"key" : "DROP_DEFAULT_ROUTE",
"value" : ""
},
{
"key" : "WEBPROXY_ENABLED",
"value" : "false"
},
{
"key" : "WEBPROXY_PORT",
"value" : "8888"
},
{
"key" : "WEBPROXY_USERNAME",
"value" : ""
},
{
"key" : "WEBPROXY_PASSWORD",
"value" : ""
},
{
"key" : "LOG_TO_STDOUT",
"value" : "false"
},
{
"key" : "HEALTH_CHECK_HOST",
"value" : "google.com"
},
{
"key" : "REVISION",
"value" : "b68db41955e7b444795fa38ec4d268318f63d0c7"
},
{
"key" : "TRANSMISSION_WEB_UI",
"value" : "transmission-web-control"
},
{
"key" : "LOCAL_NETWORK",
"value" : "192.168.50.0/24"
}
],
"exporting" : false,
"id" : "b48fa7810fe5c865ac34ae403cf286f8e54a042268ce7266aa5675aaaa8aebd4",
"image" : "haugene/transmission-openvpn:latest",
"is_ddsm" : false,
"is_package" : false,
"links" : [],
"memory_limit" : 0,
"name" : "transmission-manual",
"network" : [
{
"driver" : "bridge",
"name" : "bridge"
}
],
"network_mode" : "bridge",
"port_bindings" : [
{
"container_port" : 9091,
"host_port" : 9091,
"type" : "tcp"
}
],
"privileged" : true,
"shortcut" : {
"enable_shortcut" : false
},
"use_host_network" : false,
"volume_bindings" : [
{
"host_volume_file" : "/downloads",
"mount_point" : "/downloads",
"type" : "rw"
},
{
"host_volume_file" : "/transmission",
"mount_point" : "/config",
"type" : "rw"
},
{
"host_volume_file" : "/transmission/resolv.conf",
"mount_point" : "/etc/resolv.conf",
"type" : "rw"
},
{
"host_volume_file" : "/transmission/my_expressvpn_usa_-los_angeles-_1_udp.ovpn",
"mount_point" : "/etc/openvpn/custom/default.ovpn",
"type" : "rw"
}
]
}
 ```

**Logs**

 ```
2021-02-17 15:17:22 | stdout | 2021-02-17 15:17:22 library versions: OpenSSL 1.1.1i  8 Dec 2020, LZO 2.10
-- | -- | --
2021-02-17 15:17:22 | stdout | 2021-02-17 15:17:22 OpenVPN 2.5.0 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Dec 26 2020
2021-02-17 15:17:22 | stdout | 2021-02-17 15:17:22 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
2021-02-17 15:17:22 | stdout | 2021-02-17 15:17:22 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
2021-02-17 15:17:22 | stdout | adding route to local network 192.168.50.0/24 via 172.17.0.1 dev eth0
2021-02-17 15:17:21 | stdout | Setting OpenVPN credentials...
2021-02-17 15:17:21 | stdout | No VPN configuration provided. Using default.
2021-02-17 15:17:21 | stdout | Using OpenVPN provider: CUSTOM
2021-02-17 15:17:21 | stdout | mknod: /dev/net/tun: File exists
2021-02-17 15:17:21 | stdout | Creating TUN device /dev/net/tun
2021-02-17 15:17:21 | stdout | WARNING: initial DNS resolution test failed
2021-02-17 15:17:16 | stdout | Starting container with revision: b68db41955e7b444795fa38ec4d268318f63d0c7
 ```

**Host system:**

 ```
 Synology DS918+
DSM Docker Version 18.09.0-0513
Docker Daemon 18.09.8
Using both Haugene/docker-transmission-openvpn latest, 3.4 and 3.3.
 ```

**Comment by pkishino** [comment]
Hasn’t looked through issues, hasn’t looked through wiki (http://haugene.github.io/docker-transmission-openvpn/tips-tricks/),
Not complete logs, logs posted clearly indicate there could be a DNA issue..

**Comment by ItsRainingHP** [comment]
Can you try and help me instead of pointing me to an article that doesn't help at all just so you can close it? I am not even getting the DNS error anymore. I did a fresh install to try and add some more info. Are you going to make me reposting the issue until I get help?

**Comment by haugene** [comment]
> Are you going to make me keep reposting the issue until I get help?

Let's not go down that path. I understand that it is frustrating when stuff doesn't work, but @pkishino is using his spare time to try and help people set this up (and he has helped countless). But just as it is frustrating to you to not get help, we're sometimes frustrated that people ask for the same stuff - and many do not read or search anything. But I believe that you have so I'll try to help you. Mention me in your responses, that will help flag it.

So you say you've gotten further. And that the DNS warning is no longer there. Do you have those logs? And just so we can start debugging at the right level here, how comfortable are you with Docker, ssh and the command line? Have you read this one http://haugene.github.io/docker-transmission-openvpn/debug/ and can you try to do something similar on your Synology? You probably have to mount your configs as well - but the steps are still valid to see where it fails.

You say you haven't changed anything and then suddenly it dies. Are you running something that continuously updates the container? Has Synology been updated? Have you rebooted it to see if that could help. It seems OpenVPN can't connect - networking might have gone wrong somehow.

**Comment by pkishino** [comment]
I was in the middle of a reply when @haugene posted, thanks for writing things out more clearly :)
Anyway, please edit your first post with the updated logs/details
Regarding Synology, I see you are mounting your resolv.conf.. perhaps this is some Synology specific problem, please 
- verify the resolv.conf before/after the container is up (is it the same/what changes?)
- that you can resolve dns from inside the container
- that route shows the correct routes needed

Also,
if you were running the container for a long time without problems and it suddenly stopped, something changed. Did you update the container before the issue started? Why ? 
Did you try going back to the previous working version?

**Comment by ItsRainingHP** [comment]
Thank you both for taking the time to give some clear direction. I apologize for coming off as rude and frustrated. I will follow both of your suggestions/guidance and report back with further logs and information. Thank you again for taking the time to help the community with their issues. @haugene @pkishino

**Comment by ItsRainingHP** [comment]
Thank you again for your patience. After going through the Debugging guide. I was able to set up a transmission client and access it via browser. I believe I see where my container is suddenly hanging.

After the following log entry:

`2021-02-19 15:44:09 library versions: OpenSSL 1.1.1j  16 Feb 2021, LZO 2.10`

I am asked for a username and password authentication. I enter my ExpressVPN login details again (I passed it as a variable) and it successfully continues. I used the following command:

`sudo docker run --rm -it --cap-add=NET_ADMIN -v /volume1/transmission/my_expressvpn_usa_-_los_angeles_-_1_udp.ovpn:/etc/openvpn/custom/default.ovpn -p 9091:9091 -e LOCAL_NETWORK=192.1668.50.0/24 -e OPENVPN_PROVIDER=CUSTOM -e OPENVPN_USERNAME=XXXXXXXXXXXXXXXXXXXXXX-e OPENVPN_PASSWORD=XXXXXXXXXXXXXXXXXXXXXX-e DISABLE_PORT_UPDATER=true haugene/transmission-openvpn`

I have the username and password correctly assigned in the environment variables within the Synology GUI and in the above SSH command. However it does not use them and requires me to input the user and pass when I run the script.

**Comment by haugene** [comment]
Well, then I think the solution is near 🤞 If you are prompted for a password then it cannot read the one you provide in the env vars.

See: https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_custom_provider

> NOTE: Your .ovpn config file probably contains a line that says auth-user-pass. This will prompt OpenVPN to ask for the username and password. As this is running in a scripted environment that is not possible. Change it for auth-user-pass /config/openvpn-credentials.txt which is the file where your OPENVPN_USERNAME and OPENVPN_PASSWORD variables will be written to.

This function of persisting env vars is also described here https://haugene.github.io/docker-transmission-openvpn/building-blocks/#starting_openvpn

There is no native way in openvpn to read credentials from env vars.

**Comment by ItsRainingHP** [comment]
Please close this again. Adding auth-user-pass /config/openvpn-credentials.txt to the ovpn corrected the issue. I am not sure how my config changed. Thank you for the help again @haugene @pkishino.

@b055k060644 I believe you were having the same issue so I am pinging you here.

**Comment by b055k060644** [comment]
> Please close this again. Adding auth-user-pass /config/openvpn-credentials.txt to the ovpn corrected the issue. I am not sure how my config changed. Thank you for the help again @haugene @pkishino.
> 
> 
> 
> @b055k060644 I believe you were having the same issue so I am pinging you here.

Thanks for the tag, I'll give it a shot. 

I did resolve my issue by recreating resolv.conf and using cloud flare DNS.

**Comment by b055k060644** [comment]
This is happening with every update. Is there a permanent fix?

**Comment by pkishino** [comment]
what is happening? the ovpn file resetting or what?

**Comment by b055k060644** [comment]
> what is happening? the ovpn file resetting or what?
> 
> 
Cannot access the container, resolv.conf constantly resets back to 'nameserver 10.10.0.1' instead of '1.1.1.1'.

**Comment by ItsRainingHP** [comment]
> > please create a new issue with complete config (including resolv.conf) and other details..
> > I think there is some issue with the resolv thing and should add a check if resolv.conf is mounted
> 
> Will do, won't be till this evening though.

I am not sure what OS or platform you are using. But when using CustomVPN I set resolv.conf to read only. So the container cannot change it. This worked for me.

**Comment by b055k060644** [comment]
I'm using Docker on Synology DSM. Resolv.conf is within the 'docker > transmission' folder so changing permissions will no doubt crash the entire container.

**Comment by ItsRainingHP** [comment]
No it will not. I am using docker with DSM. Within DSM GUI you can set resolv.conf to read only. I am not at my computer right now or I would attach a Screencast. Go to Docker > transmission container > edit container > go to environment variables > check read only for your mounted resolv.conf.

**Comment by ItsRainingHP** [comment]
No problem glad it worked. I has the same issues as you back in the day I understand. It gets frustrating.

**Comment by pkishino** [comment]
I know this has been up before but could someone who has some time help me
debut this?
It shouldn’t be necessary to mount resolv.conf.. if you do, can you tell me
why?
As mentioned, I’m thinking to add a check for the mount but also want to
fix the issue that makes you mount it in the first place
