### ISSUE TITLE
Custom VPN errors

### ISSUE THREAD

**Issue by pompeytir** [haugene/docker-transmission-openvpn#1731]
I keep getting the errors below when trying to run the docker in a stack. I'm attempting to use Torguard config file with port forwarding. Any help would be greatly appreciated!! 
```
Starting container with revision: 7a805f3932174846dae73b06b49571070c807ccb

Creating TUN device /dev/net/tun

Using OpenVPN provider: CUSTOM

No VPN configuration provided. Using default.

Found existing OPENVPN credentials at /config/openvpn-credentials.txt

adding route to local network 192.168.4.0/24 via 172.18.0.1 dev eth0

Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/custom/default.ovpn

Use --help for more information.

Starting container with revision: 7a805f3932174846dae73b06b49571070c807ccb

Creating TUN device /dev/net/tun

Using OpenVPN provider: CUSTOM

No VPN configuration provided. Using default.

OpenVPN credentials not set. Exiting.

```

My docker stack is:

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - /srv/dev-disk-by-uuid-d84440fe-b396-4c0a-9ec2-ada4d0218abf/Complete/Transmission/:/data
        environment:
            - OPENVPN_PROVIDER=custom
            - OPENVPN_USERNAME=****
            - OPENVPN_PASSWORD=****
            - LOCAL_NETWORK=192.168.4.0/24
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        image: haugene/transmission-openvpn

**Comment by pkishino** [comment]
Edit your post and follow the template properly,
then I will consider reopening this

**Comment by haugene** [comment]
You are specifying that you want to use a custom provider:
```
- OPENVPN_PROVIDER=custom
```

But you are not mounting any config files:
```
volumes:
  - /srv/dev-disk-by-uuid-d84440fe-b396-4c0a-9ec2-ada4d0218abf/Complete/Transmission/:/data
```

And that is why the container logs `Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/custom/default.ovpn`

Please read the docs on how to use a custom provider: https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_custom_provider
Then if you can't get it to work try going through the debug guide: http://haugene.github.io/docker-transmission-openvpn/debug/

And if that doesn't work then create a new issue and follow the template.
