### ISSUE TITLE
Automated or quick method to change vpn servers

### ISSUE THREAD

**Issue by derekcentrico** [haugene/docker-transmission-openvpn#1732]
**Is your feature request related to a problem? Please describe.**

The selected NordVPN is downloading consistently at least than 2Mbps. Many other faster ones out there. There's no automated speed test to effectuate a server change nor a simple method I can see to change on the fly without killing the container.

**Describe the solution you'd like**

Change the server's selected VPN server when the selected one is too slow. 

**Describe alternatives you've considered**

Manually restarting the container and hope a new server is picked.

**Additional context**

Nothing.

**Comment by pkishino** [comment]
This is highly provider specific and will not be part going forward anyway, thanks for the suggestion. One were completely remove and decouple all providers from the container and have them as a separate project this might be something someone using nordvpn might be interested in contributing.
So, tagged as future item but not relevant for this container

**Comment by derekcentrico** [comment]
Understood. Would there be a way to easily cause a server change via console?

**Comment by haugene** [comment]
Well. Right now our start script ends up with doing `exec openvpn ...` [here](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L231).

If we had run openvpn from our script then we could also control, stop and start openvpn as we'd like. But right now our scripts are just preparing the runtime environment, modifying files and adding a line here and there based on the users config - and then we release the shell and give it to openvpn. So when openvpn is running we're out of the mix. It's just Docker running OpenVPN , the end (through dumb-init admittedly). And there's a simplicity to that, keeping ourselves out of the mix after doing initial setup, that I think we will not stray away from.

So then the question becomes: Does OpenVPN have a way to change the configs on runtime? And it does not as far as I know.
You have to stop OpenVPN and start it again with another config and that's what has to happen here as well.

What you could do I guess, is to write your own custom script and mount it. https://haugene.github.io/docker-transmission-openvpn/config-options/#custom_scripts
Then you could have that script test the speeds and kill openvpn if it's too low. Then set Docker to automatically restart the container and you're on. I'd have a good `sleep 60` or something in that script before testing/killing so you avoid very rapid restart-loops if anything fails. But you could test every hour and do something if it's too bad.
