### ISSUE TITLE
Flood UI hyperlinked to the wrong github project

### ISSUE THREAD

**Issue by gigawatts** [haugene/docker-transmission-openvpn#1734]
The hyperlink for the Flood UI, as linked from the following page in your doc, is pointing to the wrong github project.

https://haugene.github.io/docker-transmission-openvpn/config-options/

This should be the correct link
https://github.com/johman10/flood-for-transmission

Reference:
https://github.com/jesec/flood/discussions/213#discussioncomment-392146

**Comment by pkishino** [comment]
Please feel free to edit the file (can do it via the browser) and submit the pr and I’ll approve it, thanks

**Comment by johman10** [comment]
I want to take this opportunity to thank you @pkishino and @haugene for including my project into yours and properly linking to my project. :D

**Comment by haugene** [comment]
Just loaded the new UI now, looks really good @johman10 :clap: So thank you for making it available :pray:
