### ISSUE TITLE
PIA Port Forwarding - Error Code 6

### ISSUE THREAD

**Issue by cbruscato** [haugene/docker-transmission-openvpn#174]
-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
STARTING PORT UPDATER
Transmission startup script complete.
Fri Dec 23 14:27:24 2016 Initialization Sequence Completed
curl encountered an error looking up new port: 6
Could not find new port from PIA

**Comment by cbruscato** [comment]
Manually running the script, generates the same error:

root@114fd8c1b8d1:/etc/transmission# ./updatePort.sh
curl encountered an error looking up new port: 6
Could not find new port from PIA

**Comment by haugene** [comment]
Pulled the new image and updated my running container, works fine here.
Curl error 6 is "couldn't resolve host", so it seems you have a dns issue.

Please read old issues relating to DNS and create a new issue if you still have problems. This issue is a duplicate of #167
