### ISSUE TITLE
Question - Behavior on VPN Disconnect?

### ISSUE THREAD

**Issue by Emalton** [haugene/docker-transmission-openvpn#1752]
I'm not able to find information on what happens if the VPN connection fails. I'd like to know if there's like a kill switch of some sort that stops Transmission if the VPN connection is lost to ensure my IP is protected. Any insight on this is appreciated!

**Comment by haugene** [comment]
https://github.com/haugene/docker-transmission-openvpn/issues/196#issuecomment-373678394

**Comment by Emalton** [comment]
Thanks!
