### ISSUE TITLE
Add GitHub action to automatically close issues that don't follow issue templates

### ISSUE THREAD

**Issue by haugene** [haugene/docker-transmission-openvpn#1754]
### Is your feature request related to a problem? Please describe.
The problem is that we have a lot of issues that are created without providing the necessary details.

### Describe the solution you'd like
A bot that could automatically close issues that did not conform. Reduce the manual overhead of asking for more information.

### Describe alternatives you've considered
Better documentation. But we probably need a combination here.

### Additional context
Tried to add this action https://github.com/lucasbento/auto-close-issues and tested it in #1753. It didn't work. It output some error about invalid input options.

There are multiple issues filed with the repo, but it seems to have gone stale. I tested other forks and I think this is the closest one and the best starting point for a possible fix:  https://github.com/Stanzilla/auto-close-issues. It also seems to have died out.

So I guess we have to consider fixing it ourselves? Adding this issue as a reminder for later, and maybe someone with a bit of JavaScript experience could give it a go? It would help us maintain this project more efficiently.

I think it should be tested on another temporary repo though. I pushed a handful of tests to master and it would make a mess of the git history before we got it running I'm afraid :laughing:

**Comment by ilike2burnthing** [comment]
Jackett's issue bot may be of some use here - https://github.com/Jackett/Issue-Bot/tree/master/lib (namely `no-info.js`)

**Comment by pkishino** [comment]
good news, I have something soon done that is working on my private repo..adding a few more things before sharing

**Comment by pkishino** [comment]
well, I was working on a github action on my repo for this..then I found out github is working on a new https://gh-community.github.io/issue-template-feedback/structured/
issue template with yaml config that allows for required and much better handling..Home assistant uses this:
https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml&title=
but it's still in beta :/ @haugene perhaps you can swing something so we can get beta access? :)

**Comment by haugene** [comment]
This looks really good! If there's a "request beta access" button I will definitely press it. 
But in the "How do I get started" section it just says create a .yaml and put it in your ISSUE_TEMPLATES directory: https://gh-community.github.io/issue-template-feedback/welcome/#how-do-i-get-started

Maybe it's a public beta so we can just start using it?

**Comment by pkishino** [comment]
I already tried that but no :/
I’m nearly done with my action.. by tomorrow I’ll make a PR

**Comment by pkishino** [comment]
I already have updated issue templated for the new format, so once the feature is enabled we can switch to that, closing this for now as PR submitted
