### ISSUE TITLE
Container starts but is unhealthy - openvpn running but transmission will not start

### ISSUE THREAD

**Issue by oddsrule** [haugene/docker-transmission-openvpn#1757]
## Before creating this issue I have:

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well

### Container version & last working release (if known)

Problem occurs in : latest
<br>
Last working version: unknown - has been an issue for two weeks or so

### Describe the problem
Container starts but is unhealthy. Inside the container the transmission process will not start.
Outbound IP address matches what is provided from VPN provider - no issues with the openvpn setup that I can see.

### Describe the steps you have tried to solve the problem
 ```
1) Have tried removing all "non-vanilla" environment variables that are passed in. Even using only what is in the new user walkthrough results in an unhealthy container.
2) Have fully disabled ipv6 in the host as some warning messages hint at that being an issue.
3) Have tried using version 3.3 and 3.2 both with my desired configuration and a vanilla configuration.
 ```

### Add your docker run command or docker-compose file

 
 ```
# transmission - torrent client bound to a VPN provider - this one is for radarr
  transmission-vpn-radarr:
    container_name: transmission-vpn-radarr
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_DIR}/transmission-radarr:/data
      - ${USERDIR}/docker/shared:/shared
      - ${MEDIA_ROOT_DIR}/transmission-radarr/downloads:/data/watch
      - ${MEDIA_ROOT_DIR}/transmission-radarr/downloads/completed:/data/completed
      - ${MEDIA_ROOT_DIR}/transmission-radarr/downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=usernameobfuscated
      - OPENVPN_PASSWORD=passwordobfuscated
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=passwordobfuscated
      - TRANSMISSION_RPC_USERNAME=usernameobfuscated
      - TRANSMISSION_UMASK=2
      - TRANSMISSION_RATIO_LIMIT=0.20
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
 ```

### Logs

 ```
Starting container with revision: 69d098b9d9e29d7c0b6e40a564ccc96b5afd5fc5
Creating TUN device /dev/net/tun
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
mknod: /dev/net/tun: File exists
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.OoPHCe
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
No VPN configuration provided. Using default.
Modifying /etc/openvpn/pia/default.ovpn for best behaviour in this container
Setting OpenVPN credentials...
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0
2021-03-05 17:11:57 DEPRECATED OPTION: --cipher set to 'aes-128-cbc' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'aes-128-cbc' to --data-ciphers or change --cipher 'aes-128-cbc' to --data-ciphers-fallback 'aes-128-cbc' to silence this warning.
2021-03-05 17:11:57 OpenVPN 2.5.0 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Dec 26 2020
2021-03-05 17:11:57 library versions: OpenSSL 1.1.1j  16 Feb 2021, LZO 2.10
2021-03-05 17:11:57 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2021-03-05 17:11:57 CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
MIICWDCCAUAwDQYJKoZIhvcNAQENBQAwgegxCzAJBgNVBAYTAlVTMQswCQYDVQQI
EwJDQTETMBEGA1UEBxMKTG9zQW5nZWxlczEgMB4GA1UEChMXUHJpdmF0ZSBJbnRl
cm5ldCBBY2Nlc3MxIDAeBgNVBAsTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMSAw
HgYDVQQDExdQcml2YXRlIEludGVybmV0IEFjY2VzczEgMB4GA1UEKRMXUHJpdmF0
ZSBJbnRlcm5ldCBBY2Nlc3MxLzAtBgkqhkiG9w0BCQEWIHNlY3VyZUBwcml2YXRl
aW50ZXJuZXRhY2Nlc3MuY29tFw0xNjA3MDgxOTAwNDZaFw0zNjA3MDMxOTAwNDZa
MCYwEQIBARcMMTYwNzA4MTkwMDQ2MBECAQYXDDE2MDcwODE5MDA0NjANBgkqhkiG
9w0BAQ0FAAOCAQEAQZo9X97ci8EcPYu/uK2HB152OZbeZCINmYyluLDOdcSvg6B5
jI+ffKN3laDvczsG6CxmY3jNyc79XVpEYUnq4rT3FfveW1+Ralf+Vf38HdpwB8EW
B4hZlQ205+21CALLvZvR8HcPxC9KEnev1mU46wkTiov0EKc+EdRxkj5yMgv0V2Re
ze7AP+NQ9ykvDScH4eYCsmufNpIjBLhpLE2cuZZXBLcPhuRzVoU3l7A9lvzG9mjA
5YijHJGHNjlWFqyrn1CfYS6koa4TGEPngBoAziWRbDGdhEgJABHrpoaFYaL61zqy
MR6jC0K2ps9qyZAN74LEBedEfK7tBOzWMwr58A==
-----END X509 CRL-----

2021-03-05 17:11:57 TCP/UDP: Preserving recently used remote address: [AF_INET]212.102.36.61:1198
2021-03-05 17:11:57 UDP link local: (not bound)
2021-03-05 17:11:57 UDP link remote: [AF_INET]212.102.36.61:1198
2021-03-05 17:11:57 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2021-03-05 17:11:58 [zurich405] Peer Connection Initiated with [AF_INET]212.102.36.61:1198
2021-03-05 17:11:59 sitnl_send: rtnl: generic error (-95): Not supported
2021-03-05 17:11:59 TUN/TAP device tun0 opened
2021-03-05 17:11:59 /sbin/ip link set dev tun0 up mtu 1500
2021-03-05 17:11:59 /sbin/ip link set dev tun0 up
2021-03-05 17:11:59 /sbin/ip addr add dev tun0 10.60.112.237/24
2021-03-05 17:11:59 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.60.112.237 255.255.255.0 init
Up script executed with tun0 1500 1553 10.60.112.237 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.60.112.237
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Traceback (most recent call last):
  File "/etc/transmission/updateSettings.py", line 45, in <module>
    settings_dict = json.load(input_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-03-05 17:11:59 WARNING: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.
2021-03-05 17:11:59 add_route_ipv6(2000::/3 -> :: metric -1) dev tun0
RTNETLINK answers: Not supported
2021-03-05 17:11:59 ERROR: Linux route -6 add command failed: external program exited with error status: 2
2021-03-05 17:11:59 Initialization Sequence Completed
 ```

### Host system
Centos 7.9.2009
Which version of Docker are you using? -->
 ```
Docker version 17.05.0-ce, build 89658be
 ```

**Comment by pkishino** [comment]
if you look at the log you should be able to see that transmission is failing to start due to problems with settings.json file..
can you please take a look at the settings file (even post it here) as it seems there is an invalid value there..
alternatively delete your transmission settings.json file and reload

**Comment by oddsrule** [comment]
I've removed the settings.json file that was present in a shared folder that was mounted in the container.

when connected to the running container there are two identical settings.json files - here is one of them with its path.
'''
bash-5.1# cat /data/watch/transmission-home/settings.json
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "10.60.112.237",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/data/completed",
    "download-limit": 100,
    "download-limit-enabled": 0,
    "download-queue-enabled": true,
    "download-queue-size": 10,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": true,
    "incomplete-dir": "/data/incomplete",
    "incomplete-dir-enabled": true,
    "lpd-enabled": false,
    "max-peers-global": 200,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": false,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 0.2000,
    "ratio-limit-enabled": true,
    "rename-partial-files": true,
    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "127.0.0.1,192.168.*.*",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "{599e2691e2fa1aafe566f85a1fd0f646b3f172a2n7mAA3uK",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "username",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 2,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true,
    "watch-dir": "/data/watch",
    "watch-dir-enabled": true,
    "watch-dir-force-generic": false
}
'''

**Comment by pkishino** [comment]
hmm, settings.json should only be in /data/transmission-home/settings.json 
not sure how it's ended up in your watched directory.
I recommend setting utp-enabled to false btw..

**Comment by oddsrule** [comment]
Thanks - I wish I knew what what changed - truthfully don't recall ever creating a settings file, but maybe docker creates one and stores it?

Anyways, after removing the settings.json from the volume that is passed into the container I can start things up normally.

**Comment by pkishino** [comment]
Yeah, the container creates one and most likely the one that was passed in
had some bad setting or so, after you removed it the container creates a
new fresh one

**Comment by oddsrule** [comment]
Good to know - thanks again for the help!
