### ISSUE TITLE
Privoxy alternative in place of tinyproxy

### ISSUE THREAD

**Issue by jay-to-the-dee** [haugene/docker-transmission-openvpn#1758]
### Is your feature request related to a problem? Please describe.
This is a `privoxy` alternative for the HTTP proxy in place of `tinyproxy`. I did this because you then get ad blocking and privacy enhancing features etc. that tinyproxy lacks :) As well as more control with using the web driven privoxy rules what you then do and don't permit via the built in HTTP proxy.

### Describe the solution you'd like
https://github.com/jay-to-the-dee/docker-transmission-openvpn/tree/privoxy is my working implementation of this (based off current master branch) if you want to give it a try and see it working for yourself! Maybe could be mergd into `dev` or `beta` at some point?

### Describe alternatives you've considered
Squid may well give better performance in some configs because of the superior caching. But I think privoxy is easier to set up, has a smaller footprint and less steep learning curve overall for now! :)

### Additional context
It's optional, but I find this useful and I got it working for myself, so why not share? 😁

**Comment by jay-to-the-dee** [comment]
We can also do HTTP header modifciation very easily with Privoxy which I noticed the current TinyProxy config has as an option.

**Comment by pkishino** [comment]
I think this is a valid enhancement request, why not create a PR for this for review ?

**Comment by jay-to-the-dee** [comment]
Will do :)

**Comment by jay-to-the-dee** [comment]
https://github.com/haugene/docker-transmission-openvpn/pull/1760 PR here for further discussion :)
