### ISSUE TITLE
Port Forwarding Error with PIA

### ISSUE THREAD

**Issue by cbruscato** [haugene/docker-transmission-openvpn#176]
root@5e1bc7d0326b:/# /etc/transmission/updatePort.sh
PIA returned an error: "error":"Invalid parameter: local_ip "

I previously was getting Curl Error 6, after specifying the DNS through my Docker RUN command, I was able to get DNS resolution working; now I get this error.

**Comment by cbruscato** [comment]
It looks like this is actually working, I can see the port open now in Transmission. It just always throws this error when I run the script.

**Comment by haugene** [comment]
That makes sense. The updatePort.sh takes the vpn interface IP as parameter, it is passed from openvpn when starting the periodic updates. When you call it without that the local_ip will be empty and thus invalid.

**Comment by cbruscato** [comment]
Perfect, thanks for the help. Glad to have it working again.

**Comment by haugene** [comment]
Np!
