### ISSUE TITLE
minor change for capitalization //MEMO

### ISSUE THREAD

**Issue by sefa0888** [haugene/docker-transmission-openvpn#1762]
## Before creating this issue I have:
- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well

### Describe the problem:
My dock broke down, so I removed and initialized a new latest instance as a typical personal troubleshooting step. It was after that, that i realized that my PIA subscription had expired causing the failure. As I initialized a new [LATEST] instance i realized that the capitalization of the OVPN changed.

The following for example which I probably used for over a year:
-e OPENVPN_CONFIG=Switzerland \
Had to become:
-e OPENVPN_CONFIG=switzerland \
I’m not sure if something changed in the script or in PIA's OVPN zip

I just felt it was appropriate to make a report regarding it.

**Comment by pkishino** [comment]
this must be on pias end as the script hasnt changed and only fetches the ovpn files.. so not really container issue..
