### ISSUE TITLE
PureVPN & tunnelUp.sh fail to get Tunnel Address

### ISSUE THREAD

**Issue by jlong23** [haugene/docker-transmission-openvpn#1770]
## Before creating this issue I have:

- [x] Read through the pinned issues for related problems
- [x] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [x] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the issue as possible
- [x] Verified I have tried using newest release as well

### Container version & last working release (if known)

Problem occurs in : 
<br>
Last working version: 

### Describe the steps you have tried to solve the problem

```
 <!-- Paste here -->
 <!--
 e.g 1) tried other release/build (which ones?)
     2) verified container can resolve DNS (added --dns?)
     3) check .ovpn is valid (outdated?)
     4) check settings.json is valid (try with clean container?)
     5) Checked issues #XXX and #XXX and tried XXX
     6) ...
 -->
 ```

### Add your docker run command or docker-compose file

 
 ```
 <!-- Paste here -->
 ```

### Logs

 ```
 <!-- Paste here 
 This should start with
 e.g 
 Starting container with revision: 6ce64c4f367e509cbf018296e170cd08c0a93319
 Creating TUN device /dev/net/tun -->
 <!-- And end with as below (if not problem occurs earlier)
 e.g.
 Transmission startup script complete.
2021-02-19 08:41:43 /sbin/ip route add xx.xx.xx.xx/32 via 172.20.10.11
2021-02-19 08:41:43 /sbin/ip route add 0.0.0.0/1 via xx.xx.xx.xx
2021-02-19 08:41:43 /sbin/ip route add 128.0.0.0/1 via xx.xx.xx.xx
2021-02-19 08:41:43 Initialization Sequence Completed
 -->
 ```

### Host system

 ```
 <!-- Paste here -->
 ```

I see that the up script is not getting an IP address, I get connected on other workstations using OpenVPN and the same ovpn configs.

$ docker-compose up
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Starting docker-transmission-openvpn_transmission_1 ... done
Attaching to docker-transmission-openvpn_transmission_1
transmission_1  | Using OpenVPN provider: purevpn
transmission_1  | Supplied config uk2-ovpn-udp.ovpn could not be found.
transmission_1  | Using default OpenVPN gateway for provider purevpn
transmission_1  | Setting OPENVPN credentials...
transmission_1  | adding route to local network 10.4.0.0/21 via 172.24.0.1 dev eth0
transmission_1  | Sun Mar 14 13:53:50 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
transmission_1  | Sun Mar 14 13:53:50 2021 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
transmission_1  | Sun Mar 14 13:53:50 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission_1  | Sun Mar 14 13:53:50 2021 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
transmission_1  | Sun Mar 14 13:53:50 2021 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
transmission_1  | Sun Mar 14 13:53:50 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]5.254.73.172:80
transmission_1  | Sun Mar 14 13:53:50 2021 Socket Buffers: R=[131072->131072] S=[16384->16384]
transmission_1  | Sun Mar 14 13:53:50 2021 Attempting to establish TCP connection with [AF_INET]5.254.73.172:80 [nonblock]
transmission_1  | Sun Mar 14 13:53:51 2021 TCP connection established with [AF_INET]5.254.73.172:80
transmission_1  | Sun Mar 14 13:53:51 2021 TCP_CLIENT link local: (not bound)
transmission_1  | Sun Mar 14 13:53:51 2021 TCP_CLIENT link remote: [AF_INET]5.254.73.172:80
transmission_1  | Sun Mar 14 13:53:51 2021 TLS: Initial packet from [AF_INET]5.254.73.172:80, sid=885ad764 6bba528c
transmission_1  | Sun Mar 14 13:53:52 2021 VERIFY OK: depth=1, C=HK, ST=Central, L=HK, O=Secure-ServerCA, OU=IT, CN=Secure-ServerCA, name=Secure-ServerCA, emailAddress=mail@host.domain
transmission_1  | Sun Mar 14 13:53:52 2021 VERIFY KU OK
transmission_1  | Sun Mar 14 13:53:52 2021 Validating certificate extended key usage
transmission_1  | Sun Mar 14 13:53:52 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
transmission_1  | Sun Mar 14 13:53:52 2021 VERIFY EKU OK
transmission_1  | Sun Mar 14 13:53:52 2021 VERIFY OK: depth=0, C=HK, ST=Central, L=HK, O=Secure-Server, OU=IT, CN=Secure-Server, name=changeme, emailAddress=mail@host.domain
transmission_1  | Sun Mar 14 13:53:52 2021 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1560', remote='link-mtu 1552'
transmission_1  | Sun Mar 14 13:53:52 2021 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'
transmission_1  | Sun Mar 14 13:53:52 2021 WARNING: 'auth' is used inconsistently, local='auth SHA1', remote='auth [null-digest]'
transmission_1  | Sun Mar 14 13:53:52 2021 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
transmission_1  | Sun Mar 14 13:53:52 2021 [Secure-Server] Peer Connection Initiated with [AF_INET]5.254.73.172:80
transmission_1  | Sun Mar 14 13:53:53 2021 SENT CONTROL [Secure-Server]: 'PUSH_REQUEST' (status=1)
transmission_1  | Sun Mar 14 13:53:54 2021 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 188.72.82.3,dhcp-option DNS 188.72.82.5,sndbuf 393216,rcvbuf 393216,comp-lzo no,route-gateway 188.72.82.81,topology subnet,ping 10,ping-restart 120,peer-id 0,cipher AES-256-GCM'
transmission_1  | Sun Mar 14 13:53:54 2021 OPTIONS IMPORT: timers and/or timeouts modified
transmission_1  | Sun Mar 14 13:53:54 2021 OPTIONS IMPORT: compression parms modified
transmission_1  | Sun Mar 14 13:53:54 2021 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
transmission_1  | Sun Mar 14 13:53:54 2021 Socket Buffers: R=[131072->425984] S=[87040->425984]
transmission_1  | Sun Mar 14 13:53:54 2021 OPTIONS IMPORT: --ifconfig/up options modified
transmission_1  | Sun Mar 14 13:53:54 2021 OPTIONS IMPORT: route options modified
transmission_1  | Sun Mar 14 13:53:54 2021 OPTIONS IMPORT: route-related options modified
transmission_1  | Sun Mar 14 13:53:54 2021 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
transmission_1  | Sun Mar 14 13:53:54 2021 OPTIONS IMPORT: peer-id set
transmission_1  | Sun Mar 14 13:53:54 2021 OPTIONS IMPORT: adjusting link_mtu to 1627
transmission_1  | Sun Mar 14 13:53:54 2021 OPTIONS IMPORT: data channel crypto options modified
transmission_1  | Sun Mar 14 13:53:54 2021 Data Channel: using negotiated cipher 'AES-256-GCM'
transmission_1  | Sun Mar 14 13:53:54 2021 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
transmission_1  | Sun Mar 14 13:53:54 2021 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
transmission_1  | Sun Mar 14 13:53:54 2021 ROUTE_GATEWAY 172.24.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:18:00:02
transmission_1  | Sun Mar 14 13:53:54 2021 TUN/TAP device tun0 opened
transmission_1  | Sun Mar 14 13:53:54 2021 TUN/TAP TX queue length set to 100
transmission_1  | Sun Mar 14 13:53:54 2021 /etc/openvpn/tunnelUp.sh tun0 1500 1555   init
transmission_1  | Up script executed with tun0 1500 1555   init
transmission_1  | ERROR, unable to obtain tunnel address
transmission_1  | killing 19
transmission_1  | Sun Mar 14 13:53:54 2021 WARNING: Failed running command (--up/--down): external program did not exit normally
transmission_1  | Sun Mar 14 13:53:54 2021 Exiting due to fatal error
docker-transmission-openvpn_transmission_1 exited with code 1

version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn:latest
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
#  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/user/.docker/data/transmission2/:/data
  environment:
    - OPENVPN_PROVIDER=purevpn
    - OPENVPN_CONFIG=uk2-ovpn-udp
    - OPENVPN_USERNAME=puresecret
    - OPENVPN_PASSWORD=puresecret
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - GLOBAL_APPLY_PERMISSIONS=false
    - WEBPROXY_ENABLED=false
    - LOCAL_NETWORK=10.4.0.0/21
    - PUID=1000
    - PGID=9000
    - TRANSMISSION_MAX_PEERS_GLOBAL=600
    - TRANSMISSION_PEER_LIMIT_GLOBAL=600
    - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
  logging:
    driver: json-file
    options:
      max-size: 10m

Usually the stack just runs, rarely need to restart it unless docker itself gets updated.

**Comment by LoNicoM** [comment]
I too am having issuses with the latest build, this script tunnelUp.sh messes up my resolv.conf and lookups fail.
Reverting to 3.3 tag resolves the issue.

**Comment by mrjackyliang** [comment]
Just realized this also happened to me

**Comment by canzone** [comment]
I'm having the same issue after upgrading to latest version. Downgrading to 3.3 did not solve. Using purevpn with config pl2-ovpn-udp

**Comment by mrjackyliang** [comment]
I have version 3.3. It took a few tries, but the docker is fine now. Not sure if PureVPN made some changes. I am using `nl2-ovpn-udp.ovpn` right now. Connected for 10 days, just disconnected once.

**Comment by mrjackyliang** [comment]
It's very random. Not sure why that's happening

**Comment by canzone** [comment]
Hello everyone. Since Friday I've been unable to use the solution. I've tried EVERY config file (every country) and the ones that don't throw the "fail to get tunnel address" simply don't scrape trackers (unable to connect to any tracker).
Anyone facing the same issue? Did someone get lucky connecting? Thanks!

**Comment by ChipH1** [comment]
I just ran in to this and pulled the latest version and tried a few configs before I found this thread. Came right up using pt2-ovpn-udp like @canzone said a couple posts up. No other trackers I tried (which was just a random sampling) worked at all.

**Comment by rjblake** [comment]
I use PureVPN too, but seems that they have a number of issues with their OpenVPN connections. It seems to be hit and miss (I've tried a number of locations, sometimes work, sometimes not). The servers work using L2TP and IKEv2 manual configs. I contacted their support, but have yet to receive an update. Seems their scripts are not entirely correct as have a number of inconsistencies with backend - example below:
```
Mon May 17 16:22:27 2021 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1559', remote='link-mtu 1552'
Mon May 17 16:22:27 2021 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'
Mon May 17 16:22:27 2021 WARNING: 'auth' is used inconsistently, local='auth SHA1', remote='auth [null-digest]'
Mon May 17 16:22:27 2021 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
```

**Comment by 9Mad-Max5** [comment]
I have the same Issue.
Today I got a response from the purevpn support they advised me to change the port to 1194 instead of 53.
In the original files it is still 53 for udp...
It is now connected stable for over an hour which is compared to the issues I had before quite a long time.

**Comment by pkishino** [comment]
> I have the same Issue.
> Today I got a response from the purevpn support they advised me to change the port to 1194 instead of 53.
> In the original files it is still 53 for udp...
> It is now connected stable for over an hour which is compared to the issues I had before quite a long time.

you could open a PR on the new config repo with the correct port udpated

**Comment by 9Mad-Max5** [comment]
> you could open a PR on the new config repo with the correct port udpated

Sadly, I didn't find till now a repo or a place where those files are stored. Even on the site from purevpn they still provide the same ones.
So I had to manually change them with vim to fix this issue.

**Comment by pkishino** [comment]
https://github.com/haugene/vpn-configs-contrib

**Comment by 9Mad-Max5** [comment]
OK I see I will try tomorrow to mass edit those purevpn files and push them back.
