### ISSUE TITLE
Access Transmission from a VPN

### ISSUE THREAD

**Issue by neil123454** [haugene/docker-transmission-openvpn#1771]
I have installed transmission-open vpn on by OMV RPI which is working well. It is in bridge mode with most of my other apps. When I run this in host it makes the whole RPI run behind the VPN but when I run it in Bridge it only runs itself behind the VPN.

I also have wireguard installed which lets me vpn into the rpi from away which lets me access all my dockers except transmission. I assume it is because wire guard assigns me an IP that Transmission-openVPN does not like so it gets blocked. The ports are exposed and I have even used the networked port.  I even changed the local network value to the wireguard ip (10.6.0.2)

Is there something I am missing? If this isnt possible is there a way to run a second torrent client behind the vpn and expose those ports?

**Comment by pkishino** [comment]
Hmm, I also have transmission running on docker on my mac server, local access only, and then setup a WG server that works great for remote access but no issues with transmission access..
no ports exposed or anything,
so either re-create this as an issue and follow the issue template to provide all details or look at your wg server config which might not be correct.

**Comment by wedemmoez** [comment]
It might be due to your WG setup, and what IP range its being given. I wasn't able to access my transmission instance from a VPN until I added the VPN's subnet to my local networks environment variable
![image](https://user-images.githubusercontent.com/7355157/111543139-a6bd1b80-8740-11eb-9519-21be7774840c.png)

**Comment by neil123454** [comment]
Yes thanks! This was the issue I only added the local subnet rather than the VPN subnet. Thanks!!
