### ISSUE TITLE
New VPN Provider

### ISSUE THREAD

**Issue by Khabarakh** [haugene/docker-transmission-openvpn#178]
Hi all, i wondering if someone can tell me how i can use this Docker with vpntunnel i have a 1year subscription and don't want to change provider.

thank you for that good work so far. i really enjoy it.

**Comment by haugene** [comment]
Hey. Have you got it up and running yet?

You can set it up using the instructions in the README for a custom provider. If you provide a link to .zip file or something with configs for your provider, I can add it for you.

**Comment by haugene** [comment]
Closing this issue for now. I can add this provider if someone provides a link to the ovpn config files for a linux setup.
