### ISSUE TITLE
OpenVPN failing when not able to retrieve IPv6 addresses for PIA servers

### ISSUE THREAD

**Issue by jpringle03** [haugene/docker-transmission-openvpn#1780]
## Before creating this issue I have:

**REQUIRED**
- [X ] Read through the pinned issues for related problems
- [X ] Searched for similar [provider issues][pi] and [container issues][ci]
- [ X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X ] Tried to add as much relevant information to the issue as possible
- [X ] Verified I have tried using newest release as well
- X[ ] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in :** v3.6
 

*If possible, last working version:* 
 

### Describe the problem

**REQUIRED**
All of the sudden on reboot of my container would not start up anymore and instead showed an error related to not being able to decide if IPv4/IPv6 was used.

### Describe the steps you have tried to solve the problem

**REQUIRED**
1. Attempted to switch to older docker images `88535539d5c9` and `337c2a61e1cb` but neither worked
2. Attempted to pull latest images but did not work
3. Attempted to change DNS both inside and outside of docker & the container.
4. Checked .ovpn files for PIA and they seemed fine.
5. Did a pcap of port 53 on my server and found that OpenVPN was sending lookups for A and AAAA records. It got responses from A records but errors on the AAAA records. I'd then see the error in the logs `Could not determine IPv4/IPv6 protocol`.
6. My current "solution" to the problem was copying the opvn file I use and modifying it to use `proto udp4` and then mapping it back into the container. This allowed my container to run successfully. 

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/container_configs/transmission:/data/transmission-home
      - /storage/container_configs/ca-toronto-modified.ovpn:/etc/openvpn/pia/ca-toronto-modified.ovpn
    ports:
      - "9091:9091"
    devices:
      - /dev/net/tun:/dev/net/tun
    dns:
     - 8.8.8.8
     - 8.8.4.4
    cap_add:
      - NET_ADMIN
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=ca_toronto
      - OPENVPN_USERNAME=XXX
      - OPENVPN_PASSWORD=XXX
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings
      - TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=false
      - LOCAL_NETWORK=192.168.7.0/24
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/data/transmission-home/unrar.sh
```

### Logs

 

**REQUIRED**
```Attaching to transmission
transmission       | Starting container with revision: 35dbf5a43fcf142823c87654eb69dca543309695
transmission       | Creating TUN device /dev/net/tun
transmission       | mknod: /dev/net/tun: File exists
transmission       | Using OpenVPN provider: PIA
transmission       | Provider PIA has a custom setup script, executing it
transmission       | Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.GnapaF
transmission       | Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
transmission       | Starting OpenVPN using config ca_toronto.ovpn
transmission       | Modifying /etc/openvpn/pia/ca_toronto.ovpn for best behaviour in this container
transmission       | Setting OpenVPN credentials...
transmission       | adding route to local network 192.168.7.0/24 via 172.18.0.1 dev eth0
transmission       | 2021-03-18 20:30:01 DEPRECATED OPTION: --cipher set to 'aes-128-cbc' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'aes-128-cbc' to --data-ciphers or change --cipher 'aes-128-cbc' to --data-ciphers-fallback 'aes-128-cbc' to silence this warning.
transmission       | 2021-03-18 20:30:01 OpenVPN 2.5.0 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Dec 26 2020
transmission       | 2021-03-18 20:30:01 library versions: OpenSSL 1.1.1j  16 Feb 2021, LZO 2.10
transmission       | 2021-03-18 20:30:01 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission       | 2021-03-18 20:30:01 CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
transmission       | MIICWDCCAUAwDQYJKoZIhvcNAQENBQAwgegxCzAJBgNVBAYTAlVTMQswCQYDVQQI
transmission       | EwJDQTETMBEGA1UEBxMKTG9zQW5nZWxlczEgMB4GA1UEChMXUHJpdmF0ZSBJbnRl
transmission       | cm5ldCBBY2Nlc3MxIDAeBgNVBAsTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMSAw
transmission       | HgYDVQQDExdQcml2YXRlIEludGVybmV0IEFjY2VzczEgMB4GA1UEKRMXUHJpdmF0
transmission       | ZSBJbnRlcm5ldCBBY2Nlc3MxLzAtBgkqhkiG9w0BCQEWIHNlY3VyZUBwcml2YXRl
transmission       | aW50ZXJuZXRhY2Nlc3MuY29tFw0xNjA3MDgxOTAwNDZaFw0zNjA3MDMxOTAwNDZa
transmission       | MCYwEQIBARcMMTYwNzA4MTkwMDQ2MBECAQYXDDE2MDcwODE5MDA0NjANBgkqhkiG
transmission       | 9w0BAQ0FAAOCAQEAQZo9X97ci8EcPYu/uK2HB152OZbeZCINmYyluLDOdcSvg6B5
transmission       | jI+ffKN3laDvczsG6CxmY3jNyc79XVpEYUnq4rT3FfveW1+Ralf+Vf38HdpwB8EW
transmission       | B4hZlQ205+21CALLvZvR8HcPxC9KEnev1mU46wkTiov0EKc+EdRxkj5yMgv0V2Re
transmission       | ze7AP+NQ9ykvDScH4eYCsmufNpIjBLhpLE2cuZZXBLcPhuRzVoU3l7A9lvzG9mjA
transmission       | 5YijHJGHNjlWFqyrn1CfYS6koa4TGEPngBoAziWRbDGdhEgJABHrpoaFYaL61zqy
transmission       | MR6jC0K2ps9qyZAN74LEBedEfK7tBOzWMwr58A==
transmission       | -----END X509 CRL-----
transmission       |
transmission       | 2021-03-18 20:30:06 RESOLVE: Cannot resolve host address: ca-toronto.privacy.network:1198 (Try again)
transmission       | 2021-03-18 20:30:11 RESOLVE: Cannot resolve host address: ca-toronto.privacy.network:1198 (Try again)
transmission       | 2021-03-18 20:30:11 Could not determine IPv4/IPv6 protocol
transmission       | 2021-03-18 20:30:11 SIGUSR1[soft,init_instance] received, process restarting
transmission       | 2021-03-18 20:30:16 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission       | 2021-03-18 20:30:21 RESOLVE: Cannot resolve host address: ca-toronto.privacy.network:1198 (Try again)
transmission       | 2021-03-18 20:30:26 RESOLVE: Cannot resolve host address: ca-toronto.privacy.network:1198 (Try again)
transmission       | 2021-03-18 20:30:26 Could not determine IPv4/IPv6 protocol
transmission       | 2021-03-18 20:30:26 SIGUSR1[soft,init_instance] received, process restarting
transmission       | 2021-03-18 20:30:31 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission       | 2021-03-18 20:30:36 RESOLVE: Cannot resolve host address: ca-toronto.privacy.network:1198 (Try again)
transmission       | 2021-03-18 20:30:41 RESOLVE: Cannot resolve host address: ca-toronto.privacy.network:1198 (Try again)
transmission       | 2021-03-18 20:30:41 Could not determine IPv4/IPv6 protocol
transmission       | 2021-03-18 20:30:41 SIGUSR1[soft,init_instance] received, process restarting
transmission       | 2021-03-18 20:30:46 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission       | 2021-03-18 20:30:51 RESOLVE: Cannot resolve host address: ca-toronto.privacy.network:1198 (Try again)
transmission       | 2021-03-18 20:30:56 RESOLVE: Cannot resolve host address: ca-toronto.privacy.network:1198 (Try again)
transmission       | 2021-03-18 20:30:56 Could not determine IPv4/IPv6 protocol
transmission       | 2021-03-18 20:30:56 SIGUSR1[soft,init_instance] received, process restarting
transmission       | 2021-03-18 20:31:01 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
```

### Host system

**REQUIRED**
```Docker version 18.09.2, build 6247962
Linux ServerName 4.15.0-137-generic #141~16.04.1-Ubuntu SMP Wed Feb 24 10:47:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by SuperJakish** [comment]
Hi there! I'm no expert, but it looks like you're pointing to `ca-toronto` where it should be `ca_toronto`. Why don't you try changing the OPENVPN_CONFIG variable and seeing if that helps?

**Comment by Silversurfer79** [comment]
Other than PIA and PureVPN, is there a list of supported VPN providers that can be used with TOVPN? Im just conditions that PIA had recently been bought out. I do apologies if this isn’t he correct forum but this is not a bug but a concern for us all.

**Comment by mvittiglio** [comment]
I'm also experiencing this problem. It's such a bummer because this was working so well up until now. Any ETA on when work to resolve this can happen?

**Comment by Marauder0408** [comment]
I'm getting this same issue, any way to resolve it?

**Comment by Xaelias** [comment]
> Other than PIA and PureVPN, is there a list of supported VPN providers that can be used with TOVPN? Im just conditions that PIA had recently been bought out. I do apologies if this isn’t he correct forum but this is not a bug but a concern for us all.

https://haugene.github.io/docker-transmission-openvpn/supported-providers/

**Comment by Silversurfer79** [comment]
Thanks so much!

**Comment by CurtC2** [comment]
Can you try a restart of your container and see if that resolves as in https://github.com/haugene/docker-transmission-openvpn/issues/1710

**Comment by ItsRainingHP** [comment]
This issue likely stems from using the incorrect DNS nameservers for PIA. When using PIA you need to set your DNS servers to:

nameserver 209.222.18.222
nameserver 209.222.18.218

**Comment by mvittiglio** [comment]
Just did a docker pull and recreated the images. I'm using Google DNS 8.8.8.8/4.4.  How can I verify DNS? I've been just going into the container and doing a curl on google.com.

**Comment by pkishino** [comment]
Check the /etc/resolv.conf file

**Comment by mvittiglio** [comment]
Hey, here are the contents:

```
nameserver 127.0.0.11
options edns0 trust-ad ndots:0
```

**Comment by pkishino** [comment]
how are you setting the dns?
try using 
OVERRIDE_DNS_1: 1.1.1.1
OVERRIDE_DNS_2: 8.8.8.8
and check if they are written to resolv
also,
PEER_DNS=true (this will force openvpn to use the provider dns if they provide them)

**Comment by mvittiglio** [comment]
Hmmm... this seems to have fixed that problem. Thanks! Now to see why we're
still not downloading from peers. :-/


- Regards
- Michael Vittiglio

P Please consider the environment before printing this e-mail.

**Comment by pkishino** [comment]
Is your resolv.conf populated with correct dns now?
Great
