### ISSUE TITLE
Unrar / decompress

### ISSUE THREAD

**Issue by Samelitho** [haugene/docker-transmission-openvpn#1786]
Sorry if this not the  correct form, new to github.

Is it possible to make transmission decompress / unrar a downloaded file?

I have setup jackett / sonarr and it works like a charm, i just need transmission to unpack.

Any help would be appreciated

**Comment by Samelitho** [comment]
Im using it on synology, and i would like for the file to be extracted into the folder i downloaded

**Comment by pkishino** [comment]
#1283 #745
