### ISSUE TITLE
config file location

### ISSUE THREAD

**Issue by The-pace** [haugene/docker-transmission-openvpn#1794]
Where can i find the config file location for the VPN provider? 

Cause i'm getting this error while starting the container.

UnitedStatesVirginiaTCP.ovpn,
UnitedStatesVirginiaUDP.ovpn,
UnitedStatesWashingtonDCTCP.ovpn,
UnitedStatesWashingtonDCUDP.ovpn,
default.ovpn,
NB: Remember to not specify .ovpn as part of the config name.,

**Comment by haugene** [comment]
I mean... You don't even specify the VPN provider you're using :man_shrugging: 
Based on the filenames suggested by the container I guess you're running with Ivacy.

The Ivacy configs are here:
https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/ivacy

But we are moving all configs to a new repo, so pretty soon they will be here instead.
https://github.com/haugene/vpn-configs-contrib/tree/main/openvpn/ivacy

Don't comment back here. Open a new issue and give details about what you're trying to achieve and what issues you are facing if you have any further issues.

**Comment by The-pace** [comment]
Hi kristian,

yes i'm using the ivacy vpn but while using the configuration files in the
container its showing me this error in the log.  Can you please help me.
Thank you in advance.

[image: image.png]
[image: image.png]
