### ISSUE TITLE
Mullvad - DNS issue - tried the usual fixes

### ISSUE THREAD

**Issue by Sabb0** [haugene/docker-transmission-openvpn#1802]
## Before creating this issue I have:

**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release
<2.4>
**Required, problem occurs in :** 
<not sure, the most recent from portainer> 
```<I'm trying!>```

### Describe the problem

**REQUIRED**
```txt
<Hi everyone, I feel I have tried as many fixes as possible, but as I'm new to this all I sometimes struggle to implement them. I would really like a bit of help with everything, so apologies if this seems rather simple.>
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt
<1) I've tried override DNS
2) Using SSH I've also disabled IPV6 using the command "sudo sysctl net.ipv6.conf.all.disable_ipv6=1". >
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
<
Stack:

version: '2.4'
services:
transmission-openvpn:
volumes:
- /srv/dev-disk-by-uuid-64db560a-452b-4814-905e-2120a693f518/data/Torrents:/downloads
- /etc/localtime:/etc/localtime:ro
environment:
- PUID=1000
- PGID=100
- CREATE_TUN_DEVICE=true
- OPENVPN_PROVIDER=MULLVAD
- OPENVPN_CONFIG=gb_all
- OPENVPN_USERNAME=xxxI'm using my username number for Mullvadxxx
- OPENVPN_PASSWORD=m
- OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
- WEBPROXY_ENABLED=false
- LOCAL_NETWORK=192.168.1.XX/24 #Is this supposed to be the IP that I want the VPN to work on, or the RPi my docker is running on?
- TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
- OVERRIDE_DNS_1=8.8.8.8
- OVERRIDE_DNS_2=8.8.4.4
cap_add:
- NET_ADMIN
logging:
driver: json-file
options:
max-size: 10m
restart: always
image: haugene/transmission-openvpn>
```

### Logs

 

**REQUIRED**
```txt
<Starting container with revision: fa1bc21e929e465a79114c32a2fc44fe7c59a72a,
One or more OVERRIDE_DNS addresses found. Will use them to overwrite /etc/resolv.conf,
WARNING: initial DNS resolution test failed,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: MULLVAD,
Starting OpenVPN using config gb_all.ovpn,
Setting OpenVPN credentials...,
Fatal Python error: pyinit_main: can't initialize time,
Python runtime state: core initialized,
PermissionError: [Errno 1] Operation not permitted,
,
Current thread 0xb6f87390 (most recent call first):,
<no Python frame>,
adding route to local network 192.168.1.95/24 via 172.17.0.1 dev eth0,
RTNETLINK answers: Invalid argument,
2071-07-17 10:08:32 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.,
2071-07-17 11:06:24 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.,
2071-07-17 11:10:16 OpenVPN 2.5.0 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Dec 26 2020,
2071-07-17 11:09:52 library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10,
2071-07-17 11:07:12 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
2071-07-17 11:03:36 RESOLVE: Cannot resolve host address: gb-lon-003.mullvad.net:1196 (Try again),
2071-07-17 11:01:28 RESOLVE: Cannot resolve host address: gb-lon-003.mullvad.net:1196 (Try again),
2071-07-17 11:05:04 Could not determine IPv4/IPv6 protocol,
2071-07-17 11:09:44 SIGUSR1[soft,init_instance] received, process restarting,
2071-07-17 11:07:12 Restart pause, 5 second(s),
2071-07-17 11:07:12 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
2071-07-17 11:03:36 RESOLVE: Cannot resolve host address: gb-lon-005.mullvad.net:1196 (Try again),
2071-07-17 11:01:28 RESOLVE: Cannot resolve host address: gb-lon-005.mullvad.net:1196 (Try again),
2071-07-17 11:05:04 Could not determine IPv4/IPv6 protocol,
2071-07-17 11:09:44 SIGUSR1[soft,init_instance] received, process restarting,
2071-07-17 11:07:12 Restart pause, 5 second(s),
2071-07-17 11:07:12 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
2071-07-17 11:03:36 RESOLVE: Cannot resolve host address: gb-mnc-101.mullvad.net:1196 (Try again),
2071-07-17 11:01:28 RESOLVE: Cannot resolve host address: gb-mnc-101.mullvad.net:1196 (Try again),
2071-07-17 11:05:04 Could not determine IPv4/IPv6 protocol,
2071-07-17 11:09:44 SIGUSR1[soft,init_instance] received, process restarting,
2071-07-17 11:07:12 Restart pause, 5 second(s),

>
```

### Host system

**REQUIRED**
```txt
<Raspberry Pi - Open Media Vault 5 - the docker that is installed by OMV>
```

**Comment by bijfy** [comment]
Use image haugene/transmission-openvpn:3.3

**Comment by Sabb0** [comment]
@bijfy something so simple! Thank you! I tried to put in "image: haugene/transmission-openvpn:latest-armhf" at the beginning but it didn't like it for some reason.

I've run into a new problem....

> Starting container with revision: de2598df732811bfb4ac25395c5f27d6fa3b0d87,
> One or more OVERRIDE_DNS addresses found. Will use them to overwrite /etc/resolv.conf,
> Creating TUN device /dev/net/tun,
> Using OpenVPN provider: MULLVAD,
> Starting OpenVPN using config gb_all.ovpn,
> Setting OpenVPN credentials...,
> adding route to local network 192.168.1.95/24 via 172.17.0.1 dev eth0,
> RTNETLINK answers: Invalid argument,
> Mon Apr 12 07:40:20 2021 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.,
> Mon Apr 12 07:40:20 2021 OpenVPN 2.4.9 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020,
> Mon Apr 12 07:40:20 2021 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10,
> Mon Apr 12 07:40:20 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
> Mon Apr 12 07:40:20 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]185.195.232.85:1196,
> Mon Apr 12 07:40:20 2021 Socket Buffers: R=[180224->360448] S=[180224->360448],
> Mon Apr 12 07:40:20 2021 UDP link local: (not bound),
> Mon Apr 12 07:40:20 2021 UDP link remote: [AF_INET]185.195.232.85:1196,
> Mon Apr 12 07:40:20 2021 TLS: Initial packet from [AF_INET]185.195.232.85:1196, sid=dc52e433 33f3a69d,
> Mon Apr 12 07:40:20 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
> Mon Apr 12 07:40:20 2021 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net,
> Mon Apr 12 07:40:20 2021 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v3, emailAddress=security@mullvad.net,
> Mon Apr 12 07:40:20 2021 VERIFY KU OK,
> Mon Apr 12 07:40:20 2021 Validating certificate extended key usage,
> Mon Apr 12 07:40:20 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
> Mon Apr 12 07:40:20 2021 VERIFY EKU OK,
> Mon Apr 12 07:40:20 2021 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=gb-lon-005.mullvad.net, emailAddress=security@mullvad.net,
> Mon Apr 12 07:40:20 2021 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558',
> Mon Apr 12 07:40:20 2021 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo',
> Mon Apr 12 07:40:20 2021 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA,
> Mon Apr 12 07:40:20 2021 [gb-lon-005.mullvad.net] Peer Connection Initiated with [AF_INET]185.195.232.85:1196,
> Mon Apr 12 07:40:21 2021 SENT CONTROL [gb-lon-005.mullvad.net]: 'PUSH_REQUEST' (status=1),
> Mon Apr 12 07:40:22 2021 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.10.0.1,redirect-gateway def1 bypass-dhcp,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,comp-lzo no,route-gateway 10.10.0.1,topology subnet,socket-flags TCP_NODELAY,ifconfig-ipv6 fdda:d0d0:cafe:1196::100e/64 fdda:d0d0:cafe:1196::,ifconfig 10.10.0.16 255.255.0.0,peer-id 14,cipher AES-256-GCM',
> Mon Apr 12 07:40:22 2021 OPTIONS IMPORT: compression parms modified,
> Mon Apr 12 07:40:22 2021 OPTIONS IMPORT: --socket-flags option modified,
> Mon Apr 12 07:40:22 2021 NOTE: setsockopt TCP_NODELAY=1 failed,
> Mon Apr 12 07:40:22 2021 OPTIONS IMPORT: --ifconfig/up options modified,
> Mon Apr 12 07:40:22 2021 OPTIONS IMPORT: route options modified,
> Mon Apr 12 07:40:22 2021 OPTIONS IMPORT: route-related options modified,
> Mon Apr 12 07:40:22 2021 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
> Mon Apr 12 07:40:22 2021 OPTIONS IMPORT: peer-id set,
> Mon Apr 12 07:40:22 2021 OPTIONS IMPORT: adjusting link_mtu to 1624,
> Mon Apr 12 07:40:22 2021 OPTIONS IMPORT: data channel crypto options modified,
> Mon Apr 12 07:40:22 2021 Data Channel: using negotiated cipher 'AES-256-GCM',
> Mon Apr 12 07:40:22 2021 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
> Mon Apr 12 07:40:22 2021 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
> Mon Apr 12 07:40:22 2021 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02,
> Mon Apr 12 07:40:22 2021 GDG6: remote_host_ipv6=n/a,
> Mon Apr 12 07:40:22 2021 ROUTE6: default_gateway=UNDEF,
> Mon Apr 12 07:40:22 2021 TUN/TAP device tun0 opened,
> Mon Apr 12 07:40:22 2021 TUN/TAP TX queue length set to 100,
> Mon Apr 12 07:40:22 2021 /sbin/ip link set dev tun0 up mtu 1500,
> Mon Apr 12 07:40:22 2021 /sbin/ip addr add dev tun0 10.10.0.16/16 broadcast 10.10.255.255,
> Mon Apr 12 07:40:22 2021 /sbin/ip -6 addr add fdda:d0d0:cafe:1196::100e/64 dev tun0,
> RTNETLINK answers: Permission denied,
> Mon Apr 12 07:40:22 2021 Linux ip -6 addr add failed: external program exited with error status: 2,
> Mon Apr 12 07:40:22 2021 Exiting due to fatal error

Which I think is related to #847. I'm trying to figure out how to edit the container: https://github.com/haugene/docker-transmission-openvpn/issues/847#issuecomment-508707104. Would this be through SSH? Or can I put it into the stack code?

Again, apologies if this is very obvious for people. I've been going around in circles for a week so any help is hugely appreciated :)

**Comment by pkishino** [comment]
in #847 haugene explains how to do it inside the container.. but you can also just download an ovpn file and modify this and use only this one as a custom profile, see the wiki for details.
the LOCAL_NETWORK is also explained in the wiki. it should be the local network range your access machine is on .. e.g. my mac has ip 10.1.125.3 and my transmission docker container has some 172.xxx.. so my local_network should be 10.1.125.0/24 (to allow any machine on the 10.1.125.(1-255) access to the container) 
no need to port forward anything as it will all be tunneled through ovpn..
this should all be in the wiki, if not, please point out what is missing :)

**Comment by Sabb0** [comment]
@pkishino I appreciate the answers! 

I've really tried to run a custom profile, but after many hours of trying to get it running, researching answers, I just can't get it to work. I follow the custom provider wiki, but then it says how it can't find the "update-resolv-conf". I'm going insane.....

**Comment by Sabb0** [comment]
I have tried #847's way, but the container keeps refreshing so I can't exec into it. Is there a way I can point the container purely to the OVPN file with the pull lines in, and not have to deal with all the other file configs?

**Comment by pkishino** [comment]
Yes, it’s all in the wiki.. custom provider, mount your ovpn folder etc

**Comment by pkishino** [comment]
Add a new volume mount to your docker runcommand that mounts your config
file: -v /path/to/your/config.ovpn:/etc/openvpn/custom/default.ovpn

I don’t see how the resolve has anything to do with it

**Comment by Sabb0** [comment]
> Add a new volume mount to your docker run command that mounts your config file: -v /path/to/your/config.ovpn:/etc/openvpn/custom/default.ovpn
> 
Done in stack:
 - /srv/dev-disk-by-uuid-64db560a-452b-4814-905e-2120a693f518/data/appdata/TVPN:/etc/openvpn/custom/default.ovpn

> Then you can set OPENVPN_PROVIDER=CUSTOMand the container will use the config you provided. NOTE: Your .ovpn config file probably contains a line that says auth-user-pass. This will prompt OpenVPN to ask for the username and password. As this is running in a scripted environment that is not possible. Change it for auth-user-pass /config/openvpn-credentials.txt which is the file where your OPENVPN_USERNAME and OPENVPN_PASSWORD variables will be written to.
> 
Done in the OVPN file:
auth-user-pass /config/mullvad_userpass.txt

> If you are using AirVPN or other provider with credentials in the config file, you still need to set OPENVPN_USERNAME and OPENVPN_PASSWORD as this is required by the startup script. They will not be read by the .ovpn file, so you can set them to whatever.
> 
I've left this in the stack anyways, as I thought it wouldn't hurt.

> Note that you still need to modify your .ovpn file as described in the previous section. If you have an separate ca.crt, client.key or client.crt file in your volume mount should be a folder containing both the ca.crt and the .ovpn config.
> 

Done in OVPN file:
ca /etc/openvpn/custom/mullvad_ca.crt

> Mount the folder contianing all the required files instead of the openvpn.ovpn file. -v /path/to/your/config/:/etc/openvpn/custom/
> 
Done in stack:
 /srv/dev-disk-by-uuid-64db560a-452b-4814-905e-2120a693f518/data/appdata/TVPN/config:/etc/openvpn/custom/ 
 
> Additionally the .ovpn config should include the full path on the docker container to the ca.crt and additional files. ca /etc/openvpn/custom/ca.crt

Doing all that gives me:

> 

> Starting container with revision: de2598df732811bfb4ac25395c5f27d6fa3b0d87,
> One or more OVERRIDE_DNS addresses found. Will use them to overwrite /etc/resolv.conf,
> Creating TUN device /dev/net/tun,
> Using OpenVPN provider: CUSTOM,
> Starting OpenVPN using config mullvad_gb_all.ovpn,
> Setting OpenVPN credentials...,
> adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0,
> Thu Apr 15 08:31:26 2021 Multiple --up scripts defined.  The previously configured script is overridden.,
> Options error: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory (errno=2),
> Options error: Please correct this error.,
> Use --help for more information.

**Comment by Sabb0** [comment]
Full stack is this:

> 

> version: '2.4'
> services:
>  transmission-openvpn:
>     volumes:
>         - /srv/dev-disk-by-uuid-64db560a-452b-4814-905e-2120a693f518/data/Torrents:/downloads
>         - /srv/dev-disk-by-uuid-64db560a-452b-4814-905e-2120a693f518/data/appdata/TVPN:/etc/openvpn/custom/default.ovpn
>         - /srv/dev-disk-by-uuid-64db560a-452b-4814-905e-2120a693f518/data/appdata/TVPN/config:/etc/openvpn/custom/
>         - /etc/localtime:/etc/localtime:ro
>     environment:
>         - PUID=998
>         - PGID=100
>         - CREATE_TUN_DEVICE=true
>         - OPENVPN_PROVIDER=CUSTOM
>         - OPENVPN_CONFIG=mullvad_gb_all
>         - OPENVPN_USERNAME=XXXXXXXX
>         - OPENVPN_PASSWORD=m
>         - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
>         - WEBPROXY_ENABLED=false
>         - LOCAL_NETWORK=192.168.1.0/24
>         - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
>         - OVERRIDE_DNS_1=8.8.8.8
>         - OVERRIDE_DNS_2=8.8.4.4
>         - TRANSMISSION_WEB_UI=transmission-web-control
>     cap_add:
>         - NET_ADMIN
>     logging:
>         driver: json-file
>         options:
>             max-size: 10m
>     image: haugene/transmission-openvpn:3.3

**Comment by Sabb0** [comment]
This is my mullvad_gb_all conf file, and it's the same for the OVPN file I made.

```
client
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
remote-cert-tls server
ping 10
ping-restart 60
sndbuf XXXXX
rcvbuf XXXXX
cipher XXXXX
tls-cipher XXXXX
proto udp
auth-user-pass /config/mullvad_userpass.txt
ca /etc/openvpn/custom/mullvad_ca.crt
#tun-ipv6
script-security 2
up /etc/openvpn/custom/update-resolv-conf
down /etc/openvpn/custom/update-resolv-conf
fast-io
remote-random
remote gb-lon-101.mullvad.net 1300
remote gb-lon-006.mullvad.net 1300
remote gb-mnc-106.mullvad.net 1300
remote gb-mnc-103.mullvad.net 1300
remote gb-mnc-101.mullvad.net 1300
remote gb-mnc-102.mullvad.net 1300
remote gb-lon-001.mullvad.net 1300
remote gb-lon-002.mullvad.net 1300
remote gb-lon-009.mullvad.net 1300
remote gb-lon-008.mullvad.net 1300
remote gb-lon-102.mullvad.net 1300
remote gb-lon-004.mullvad.net 1300
remote gb-lon-003.mullvad.net 1300
remote gb-lon-005.mullvad.net 1300
pull-filter ignore "dhcp-option DNS6" 
pull-filter ignore "tun-ipv6" 
pull-filter ignore "ifconfig-ipv6"
```

**Comment by pkishino** [comment]
obviously it's failing here
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf

where are these lines from??

**Comment by pkishino** [comment]
remove those lines and try..

**Comment by pkishino** [comment]
the log clearly shows this:
Thu Apr 15 08:31:26 2021 Multiple --up scripts defined.  The previously configured script is overridden.,
it's overriding our defined up scripts (and down) which causes problems..

**Comment by Sabb0** [comment]
IT'S WORKING!!! God knows how many hours I've put into this haha. Thank you so SO much @pkishino. If you were here I would honestly kiss you 👍 

>
> obviously it's failing here
> up /etc/openvpn/update-resolv-conf
> down /etc/openvpn/update-resolv-conf
> 
> where are these lines from??

These lines were from Mullvad, which is why I didn't think to take them out.... I just thought they must be in there for a reason.

In the Mullvad_openvpn_linux file that one downloads off their site, it gives you 4 files:

mullvad_ca
mulllvad_gb_all - conf file
mullvad_userpass - username/password
update-resolve-conf 

the original conf file is this:

```
client
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
remote-cert-tls server
ping 10
ping-restart 60
sndbuf XXXXXX
rcvbuf XXXXXX
cipher XXXXXX
tls-cipher XXXXXXX
proto udp
auth-user-pass mullvad_userpass.txt
ca mullvad_ca.crt
tun-ipv6
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
fast-io
remote-random
remote gb-lon-101.mullvad.net 1300
remote gb-lon-006.mullvad.net 1300
remote gb-mnc-106.mullvad.net 1300
remote gb-mnc-103.mullvad.net 1300
remote gb-mnc-101.mullvad.net 1300
remote gb-mnc-102.mullvad.net 1300
remote gb-lon-001.mullvad.net 1300
remote gb-lon-002.mullvad.net 1300
remote gb-lon-009.mullvad.net 1300
remote gb-lon-008.mullvad.net 1300
remote gb-lon-102.mullvad.net 1300
remote gb-lon-004.mullvad.net 1300
remote gb-lon-003.mullvad.net 1300
remote gb-lon-005.mullvad.net 1300
```
I changed it to:

```
client
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
remote-cert-tls server
ping 10
ping-restart 60
sndbuf XXXXXX
rcvbuf XXXXXX
cipher XXXXXX
tls-cipher XXXXX
proto udp
auth-user-pass /config/openvpn-credentials.txt #should have changed this earlier, i thought it should reference the mullvad one
ca /etc/openvpn/custom/mullvad_ca.crt
#tun-ipv6
script-security 2
#up /etc/openvpn/custom/update-resolv-conf
#down /etc/openvpn/custom/update-resolv-conf
fast-io
remote-random
remote gb-lon-101.mullvad.net 1300
remote gb-lon-006.mullvad.net 1300
remote gb-mnc-106.mullvad.net 1300
remote gb-mnc-103.mullvad.net 1300
remote gb-mnc-101.mullvad.net 1300
remote gb-mnc-102.mullvad.net 1300
remote gb-lon-001.mullvad.net 1300
remote gb-lon-002.mullvad.net 1300
remote gb-lon-009.mullvad.net 1300
remote gb-lon-008.mullvad.net 1300
remote gb-lon-102.mullvad.net 1300
remote gb-lon-004.mullvad.net 1300
remote gb-lon-003.mullvad.net 1300
remote gb-lon-005.mullvad.net 1300
pull-filter ignore "dhcp-option DNS6" 
pull-filter ignore "tun-ipv6" 
pull-filter ignore "ifconfig-ipv6"
```

Removing the up/down part worked, and then it said it couldn't find the mullvad_userpass.txt. I didn't understand why it wouldn't work, or it couldn't find the file when it was right in the config file. Is that because I left the OPENVPN_username and OPENVPN_password in the ENV variables? So then I changed it to the one specified in the wiki, and bingo.

I know you must have gotten tired of saying "it's in the wiki"..... but I really appreciate you sticking with me!

**Comment by pkishino** [comment]
Please, if you couldn’t give some pointers on what could be improved in the
wiki, please add a PR or comment here and I’ll update

**Comment by Sabb0** [comment]
Yes sure thing. When I get some time I will write what I've learnt in a wiki format :)

**Comment by pbeliveau** [comment]
Just want to add that without the following lines at the end of the opvn file I use - wouldn't work:
```
pull-filter ignore "dhcp-option DNS6" 
pull-filter ignore "tun-ipv6" 
pull-filter ignore "ifconfig-ipv6"
```

Thanks for that @Sabb0

**Comment by raldnor** [comment]
Note that by commenting out the lines related to update-resolv-conf you're using your ISP's DNS servers. You can verify this by checking dnsleaktest.com.
