### ISSUE TITLE
Does the Mullvad config support port forwarding?

### ISSUE THREAD

**Issue by sofakng** [haugene/docker-transmission-openvpn#1803]
Mullvad VPN supports port forwarding but does the included OpenVPN config support it?

I've specified the forwarded port in Transmission but it's reporting as closed.

**Comment by kchelvan** [comment]
I am wondering the same as well.

**Comment by trevordavies095** [comment]
@sofakng @kchelvan Yes it does. 

Setup port forwarding in your Mullvad account here: https://mullvad.net/en/account/#/port-forwarding

For example, I opened port 55080 for Stockholm Sweden for OpenVPN.

Then add/change the following lines to your docker compose under environments
- TRANSMISSION_PEER_PORT_RANDOM_ENABLED="false"
- TRANSMISSION_PEER_PORT=55080
- OPENVPN_CONFIG=se_sto

The Mullvad Port forwarding is CITY SPECIFIC, so if you don't have the correct config set for OpenVPN the container may connect to another city which in return shows a closed port.

Hope this helps.
