### ISSUE TITLE
Error: No module named 'ufw'

### ISSUE THREAD

**Issue by ascheel319** [haugene/docker-transmission-openvpn#1811]
## Before creating this issue I have:

**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in :** 
 
```lastest (created 7 days ago)```

*If possible, last working version:* 
 
```<Leave empty if not known>```

### Describe the problem

**REQUIRED**
```txt
When I try and start the docker I get this error in the logs after updating to lastest

Traceback (most recent call last):
  File "/usr/sbin/ufw", line 25, in <module>
    import ufw.frontend
ModuleNotFoundError: No module named 'ufw'

```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt
I looked at the environment variables and made sure they were still valid. 
I double checked that I had valid values in the variables. 
I tried to start it up after stopping it.
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
version: '3.3'
services:
  openvpn:
    image: haugene/transmission-openvpn
    # name container whatever you want
    container_name: downloader
    ports:
      - 9091:9091
    # Configure your logging options
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: always
    dns:
      - 1.1.1.1
      - 1.0.0.1
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/andrew/Plex/shows/temp:/data
    # Configure all of your environment variables
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=ca_toronto
      - ENABLE_UFW=true
      - UFW_ALLOW_GW_NET=true
      - OPENVPN_USERNAME=CHANGED FOR REPORT
      - OPENVPN_PASSWORD=CHANGED FOR REPORT
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=1000
      - GPID=1000
 ```

### Logs

 

**REQUIRED**
```txt
Starting container with revision: 416541016b9b30149d8fcb56abe2bc325db4904b
Creating TUN device /dev/net/tun
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.KDcgJa
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Starting OpenVPN using config ca_toronto.ovpn
Modifying /etc/openvpn/pia/ca_toronto.ovpn for best behaviour in this container
Setting OpenVPN credentials...
enabling firewall
Traceback (most recent call last):
  File "/usr/sbin/ufw", line 25, in <module>
    import ufw.frontend
ModuleNotFoundError: No module named 'ufw'
```

### Host system

**REQUIRED**
```txt
Ubuntu
```

**Comment by pkishino** [comment]
duplicate...

**Comment by mnkhouri** [comment]
Perhaps this copy of the issue should remain open, since the duplicate was closed because it didn't follow the issue template?

I'm also observing this error on `latest`

**Comment by pkishino** [comment]
please continue any discussions on the original..
