### ISSUE TITLE
Check and rebuild image on dependency update

### ISSUE THREAD

**Issue by dgcampea** [haugene/docker-transmission-openvpn#1832]
## Before creating this request I have:

**REQUIRED**
- [x] Read through the pinned issues for related problems
- [x] Searched for similar [provider issues][pi] and [container issues][ci]
- [x] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the request as possible
- [x] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Is your feature request related to a problem? Please describe.

**REQUIRED**
```txt
Images are not being rebuilt when dependent upstream packages get new releases (such as Flood).
```
https://github.com/haugene/docker-transmission-openvpn/blob/d7e7a24fbb384df866c2e9ae0e31104895dd26ea/Dockerfile#L10

### Describe the solution you'd like

**REQUIRED**
```txt
Automatic rebuilding of images when dependencies get new releases.
```

### Describe alternatives you've considered

**REQUIRED**
```txt
Fix at CI level
```
### Additional context

*Optional*
```txt
<placeholder for optional>
```

**Comment by pkishino** [comment]
while I understand the wish for always up-2-date packages, this is not really viable nor efficient, as automatic updates such as this could lead to build problems or unexpected issues..
The correct way for this is to create PR's for such updates that then can be reviewed.

**Comment by dgcampea** [comment]
For Flood at least, every commit results in a new release (https://github.com/johman10/flood-for-transmission/pull/77). Not having it updated in a "regular" fashion risks missing out features and bug fixes (as well as its dependency updates since it uses dependabot).
See: https://github.com/johman10/flood-for-transmission/issues/67

> EDIT: I realised that the 4 guis that we pull, two havent had any updates in years.. the other two we pull latests when a new image is built. I honestly don't think this is the right way as this could introduce unwanted side-effects.

How about having some sort of bot or mechanism that automatically tracks upstream releases and opens PRs?
This would require using release tags instead of using the latest tarball though.

**Comment by dgcampea** [comment]
@pkishino Should this be re-opened until the concerns at https://github.com/haugene/docker-transmission-openvpn/issues/1832#issuecomment-845592535 are solved?

**Comment by pkishino** [comment]
Hmm, not sure why I closed this..

**Comment by pkishino** [comment]
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates
this looks usable

**Comment by ksurl** [comment]
What about adding an environment variable to enable checking and downloading the latest version on start

**Comment by dgcampea** [comment]
> riable to enable checking and downloading the latest version on start.
> 
> You can do this right now with the openvpn-pre

Having it download every time the container gets created seems wasteful and doesn't seem to be in line with how containers should handle their dependencies. Having it baked into the image is the correct way to go.
