### ISSUE TITLE
New webUI - Shift

### ISSUE THREAD

**Issue by SJ50** [haugene/docker-transmission-openvpn#1835]
## Before creating this request I have:

**REQUIRED**
- [x] Read through the pinned issues for related problems
- [x] Searched for similar [provider issues][pi] and [container issues][ci]
- [x] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the request as possible
- [x] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Is your feature request related to a problem? Please describe.

**REQUIRED**
```txt
NO
```

### Describe the solution you'd like

**REQUIRED**
```txt
Is it possible to add new well-maintained and minimalist web UI named Shift (https://github.com/killemov/Shift)?
```

### Describe alternatives you've considered

**REQUIRED**
```txt
No alternatives
```
### Additional context

*Optional*
```txt
<placeholder for optional>
```

**Comment by pkishino** [comment]
Thanks for the suggestion.
Before moving forward with this I would like to ask for that repo to produce releases to better manage adding this.. I want to do the same for the other UIs we use to avoid problems moving forward.

**Comment by SJ50** [comment]
I will open issue there asking for release.
