### ISSUE TITLE
Adding torrents to docker image

### ISSUE THREAD

**Issue by TRBrennan** [haugene/docker-transmission-openvpn#184]
Hi,

I may be missing something obvious but how do I add torrents to this docker image?

Also does anyone know a good way to get a remote UI working for Transmission using Private Internet access?

**Comment by haugene** [comment]
You can add torrents with the web ui or put them in the watch folder on your machine. This is all described in the readme.

**Comment by HotBlack77** [comment]
On windows this is an excellent Transmission remote admin gui: https://sourceforge.net/projects/transgui/

However clients are also available for Linux, android and many other platforms.
