### ISSUE TITLE
Can't 

### ISSUE THREAD

**Issue by kknkkn1** [haugene/docker-transmission-openvpn#1842]
Hello.
I am using Synology DS1819+ and updated newer OS from beta 7 to candidate release.

after then,  this docker doesn't work properly. 

I have tried deleted all my containers/images including docker package.

current error is as below. 

Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/custom/default.ovpn

-volume 

![image](https://user-images.githubusercontent.com/51122822/120734577-15ca3500-c524-11eb-80dd-89bb629a8641.png)

**Comment by pkishino** [comment]
duplicate #1839
