### ISSUE TITLE
[CMD-LINE]:1: Error opening configuration file

### ISSUE THREAD

**Issue by maxlech974** [haugene/docker-transmission-openvpn#1843]
**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

### Container version & last working release
haugene/transmission-openvpn:latest (3.6)
**Required, problem occurs in :** 
synology/linux

### Describe the problem
I am using Docker through my  Synology DS918+, and i have pulled the container to docker hub with my gui on DSM.

The problem occured when DSM (os from synology) has been updated. I have been running this container for 1 year without any trouble and the container has always been up to date by :latest.

Now my container always stop when starting and i check my log file! this seems to be the problem: 

```bash
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/fr797.nordvpn.com.ovpn 
```

Some people get these error messages when OPENVPN_CONFIG has not been configure. But here i have done it and it's downloading the config file i have try it with my browser, and each adress are good.

I didn't touche my config file from last time and all my env vars are set correctly for nordvpn

![log1](https://user-images.githubusercontent.com/67579663/120995733-f7637400-c785-11eb-8d7e-71eb1878ab1c.PNG)
![log2](https://user-images.githubusercontent.com/67579663/120995735-f7fc0a80-c785-11eb-8d11-b7dd7ab59242.PNG)

**Comment by pkishino** [comment]
please use search..this very likely has to to with #1839
