### ISSUE TITLE
openvpn process triggers "--ping-restart" instead of "--ping-exit"

### ISSUE THREAD

**Issue by sl0n** [haugene/docker-transmission-openvpn#185]
Hi All,

I have the following problem on CentOS 7.2 server, running docker v. 1.12.3.

What I observe:

1. Container starts and runs fine for quite a while, sometimes a few hours.

2. At some point, I guess, tun interface hangs, eg I can not ping the tun's interface endpoint anymore. I see the following log entries for openvpn process:
Mon Jan 16 09:02:52 2017 [PureVPN] Inactivity timeout (--ping-restart), restarting
Mon Jan 16 09:02:52 2017 SIGUSR1[soft,ping-restart] received, process restarting
Mon Jan 16 09:02:57 2017 WARNING: No server certificate verification method has been enabled. See http://openvpn.net/howto.html#mitm for more info.
Mon Jan 16 09:02:57 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jan 16 09:03:37 2017 RESOLVE: Cannot resolve host address: MY-VPN-SERVER-NAME: Temporary failure in name resolution
....
Mon Jan 16 09:18:33 2017 NOTE: --mute triggered...

This issue can be resolved by restarting the whole container, however the container restart is not being triggered automatically, ie the following options:

"OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"

cause "--ping-restart" action instead of expected "--ping-exit".

**Comment by sl0n** [comment]
I found a possible workaround by adding the following to "docker run" command:

--dns 8.8.8.8 --dns <your_router_IP>

8.8.8.8 is to ensure that resolving work ones "tun" interface is up and running, and "your_router_IP" makes resolving working when the "tun" interface gets stuck and Google'e DNS becomes not reachable, hence container can not resolve VPN server' hostname to reconnect. It works for me.

Important: there is an assumption that "your_router_IP" provides DNS service (which is usually the case).

**Comment by haugene** [comment]
Should be mentioned that this probably causes an IP leak. When you let your container do DNS lookups via your home router, those DNS queries will originate from your IP and not the VPN address.

**Comment by sl0n** [comment]
@haugene yes, you are correct.

According to openvpn man page:
" For example,

 openvpn [options...] --inactive 3600 --ping 10 --ping-exit 60

when used on both peers will cause OpenVPN to exit within 60 seconds if its peer disconnects, but will exit after one hour if no actual  tunnel data  is exchanged."

So *both* server and client need to set these flags. I contacted PureVPN's support and I was told they do not set anything like that on server side.

I think I'm going to investigate if something like 'supervisor' can be helpful here.

**Comment by stedju499** [comment]
I am having the same issue.
Did you find solution for this?

**Comment by jeff-kingston** [comment]
Same here

**Comment by braytoni** [comment]
I've had the same problem for a while.  After the ping-exit, DNS wouldn't resolve, and I ended up having to restart the container manually every day or so.  I ended up hardcoding the openvpn server's IP address into the remote command in the .ovpn file stored in /etc/openvpn/<provider>.  A hack, but problem seems to be resolved.

**Comment by haugene** [comment]
I think this can be followed up in #454 that I just created. If not, re-open this or create a new issue. Remember to provide logs and steps to reproduce.
