### ISSUE TITLE
"rename" command not found in updateConfigs.sh for Torguard

### ISSUE THREAD

**Issue by fshafique** [haugene/docker-transmission-openvpn#1856]
## Before creating this issue I have:

**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in :** 
 
```3.6```

*If possible, last working version:* 
 
``` ```

### Describe the problem

**REQUIRED**
```txt
I tried running "updateConfigs.sh" in /etc/openvpn/torguard and it failed trying to run the "rename" command in line 16:
./updateConfigs.sh: line 16: rename: command not found

As I understand it, the script needs to rename files from "TorGuard.xxxxxx.vpn" to "xxxxxx.vpn", where xxxxxx is the country.

Torguard's OVPN files need to be updated, as some of them have hardcoded IPv4 addresses that are no longer valid.
```

### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt
1) this particular config file is the same in the master branch as well as 3.6, which I'm running.
2) I've only found 2 update scripts - Surfshark and Torguard - that use the "rename" command.
3) I searched for a way to add the package, but most of the results I got were for distros using "apt", not "apk".
4) Searching Alpine's package repository, I couldn't find anything with "rename".
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
--irrelevant--
```

### Logs

 

**REQUIRED**
```txt
/etc/openvpn/torguard # ./updateConfigs.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 94695  100 94695    0     0   283k      0 --:--:-- --:--:-- --:--:--  283k
Archive:  OpenVPN-UDP.zip
  inflating: TorGuard.Australia.Sydney.ovpn
  inflating: TorGuard.Austria.ovpn
  inflating: TorGuard.Belarus.ovpn
  inflating: TorGuard.Belgium.ovpn
  inflating: TorGuard.Brazil.ovpn
  inflating: TorGuard.Bulgaria.ovpn
  inflating: TorGuard.Canada.Toronto.ovpn
  inflating: TorGuard.Canada.Vancouver.ovpn
  inflating: TorGuard.Chile.ovpn
  inflating: TorGuard.Cyprus.ovpn
  inflating: TorGuard.Czech.ovpn
  inflating: TorGuard.Denmark.ovpn
  inflating: TorGuard.Finland.ovpn
  inflating: TorGuard.France.ovpn
  inflating: TorGuard.Germany.ovpn
  inflating: TorGuard.Greece.ovpn
  inflating: TorGuard.Hong.Kong.ovpn
  inflating: TorGuard.Hungary.ovpn
  inflating: TorGuard.Iceland.ovpn
  inflating: TorGuard.India.Bangalore.ovpn
  inflating: TorGuard.Ireland.ovpn
  inflating: TorGuard.Israel.ovpn
  inflating: TorGuard.Italy.ovpn
  inflating: TorGuard.Japan.ovpn
  inflating: TorGuard.Latvia.ovpn
  inflating: TorGuard.Luxembourg.ovpn
  inflating: TorGuard.Mexico.ovpn
  inflating: TorGuard.Moldova.ovpn
  inflating: TorGuard.Netherlands.ovpn
  inflating: TorGuard.New.Zealand.ovpn
  inflating: TorGuard.Norway.ovpn
  inflating: TorGuard.Poland.ovpn
  inflating: TorGuard.Portugal.ovpn
  inflating: TorGuard.Romania.ovpn
  inflating: TorGuard.Singapore.ovpn
  inflating: TorGuard.Slovakia.ovpn
  inflating: TorGuard.South.Korea.ovpn
  inflating: TorGuard.Spain.ovpn
  inflating: TorGuard.Sweden.ovpn
  inflating: TorGuard.Switzerland.ovpn
  inflating: TorGuard.Taiwan.ovpn
  inflating: TorGuard.Thailand.ovpn
  inflating: TorGuard.UK.London.ovpn
  inflating: TorGuard.USA-ATLANTA.ovpn
  inflating: TorGuard.USA-CHICAGO.ovpn
  inflating: TorGuard.USA-DALLAS.ovpn
  inflating: TorGuard.USA-LAS-VEGAS.ovpn
  inflating: TorGuard.USA-LOS.ANGELES.ovpn
  inflating: TorGuard.USA-MIAMI.ovpn
  inflating: TorGuard.USA-NEW-JERSEY.ovpn
  inflating: TorGuard.USA-NEW-YORK.ovpn
  inflating: TorGuard.USA-SAN-FRANCISCO.ovpn
  inflating: TorGuard.USA-SEATTLE.ovpn
  inflating: ca.crt
./updateConfigs.sh: line 16: rename: command not found
```

### Host system

**REQUIRED**
```txt
Win10 + WSL2 w/ Ubuntu as a distro.
```

**Comment by pkishino** [comment]
good find, added missing package (util-linux)

**Comment by fshafique** [comment]
> good find, added missing package (util-linux)

Is the "rename" command in that package the correct one?
I manually ran this ```apk add util-linux``` in my container's shell,
and then I tried this command ```rename "s/^TorGuard\.//" *.ovpn```.
It didn't do anything!

I assume the command was supposed to rename "TorGuard.xxxxxx.ovpn" files to "xxxxxx.ovpn".
I added ```-v``` option for verbose output, and it doesn't show anything.

I checked the [source code](https://kernel.googlesource.com/pub/scm/utils/util-linux/util-linux.git/+/refs/heads/master/misc-utils/rename.c) for "rename" and it doesn't look like it can handle regular expressions.

**Comment by fshafique** [comment]
There's a few different solutions I can propose:

1. Change the command in the updateConfigs.sh file to `rename -v TorGuard. "" TorGuard*.ovpn`

     This is a sample of the output: 
     ```txt
     `TorGuard.Australia.Sydney.ovpn' -> `Australia.Sydney.ovpn'
     `TorGuard.Austria.ovpn' -> `Austria.ovpn'
     `TorGuard.Belarus.ovpn' -> `Belarus.ovpn'
     `TorGuard.Belgium.ovpn' -> `Belgium.ovpn'
     `TorGuard.Brazil.ovpn' -> `Brazil.ovpn'
     `TorGuard.Bulgaria.ovpn' -> `Bulgaria.ovpn'
     ```
     

2. There's a [package](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/perl-file-rename) called `perl-file-rename` in the `testing` repo. But I think it needs Perl to run.


3. Or, forget extra packages altogether, and just use this command:
      ```txt
      for old in TorGuard*.ovpn; do new=$(echo $old | sed -e 's/^TorGuard\.//'); mv "$old" "$new"; done
      ```

**Comment by pkishino** [comment]
hmm, you are right..my bad for trying to fix this with a quick google :P
anyway, I think you are right and 3. will be best as rename isn't used anywhere else from what I found..will fix thi

**Comment by pkishino** [comment]
pushed in 73ec516cc
