### ISSUE TITLE
Transmission not reporting user agent - libcurl fault (please update curl package)

### ISSUE THREAD

**Issue by xppx99** [haugene/docker-transmission-openvpn#1861]
## Before creating this issue I have:

**REQUIRED**
- [x] Read through the pinned issues for related problems
- [x] Searched for similar [provider issues][pi] and [container issues][ci]
- [x] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the issue as possible
- [x] Verified I have tried using newest release as well
- [x] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template:

### Container version & last working release
**Required, problem occurs in :** 
 
```latest```

### Describe the problem
Sometimes transmission does not report the user agent to the trackers. Some trackers consider this a non accepted client, and return an error (like banned client). 

The problem is well reported either in transmission issue tracker [issue1563](https://github.com/transmission/transmission/issues/1563) but specially in curl issue tracker [issue6312](https://github.com/curl/curl/issues/6312) which is the faulty software that is causing the problem. 

The solution should be simply to use an curl updated version, becauas the actual 7.74.0 version is affected by this bug. 

Thanks in advance.  

### Host system
Synology NAS

**REQUIRED**
```txt
<placeholder>
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt
<-- Paste here -->
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
<-- Paste here -->
```

### Logs

 

**REQUIRED**
```txt
<-- Paste here -->
```

### Host system

**REQUIRED**
```txt
<-- Paste here -->
```

**Comment by haugene** [comment]
We will soon be releasing version 4.0 of the image and that will change the base image from alpine to ubuntu. That's a longer discussion about image size versus distro familiarity and stability - but we've chosen to do it.

This will cause curl to be downgraded to 7.68.0 which is the current version in ubuntu 20.04. According to the libcurl issue you link to the error is introduced in 7.71.0 so we should hopefully be OK with 7.68.0 :crossed_fingers:
