### ISSUE TITLE
Transmission keeps redownloading deleted files every time the container reboots

### ISSUE THREAD

**Issue by jsaltzman** [haugene/docker-transmission-openvpn#1862]
Every time I reboot the container, transmissions starts downloading about 15 different files that were downloaded, moved, and then deleted. No there are no torrent files in the watch folder. I noticed in my transmission folder there was a resume folder so I deleted all the files, this did not resolve. I noticed in the transmission file there is a "torrents" (thats the name) folder. Should I delete all the files in there except for the 1 file I am currently downloading?

**Comment by lbesnard** [comment]
have you solved your issue? I'm still dealing with this similar issue.

**Comment by pkishino** [comment]
> have you solved your issue? I'm still dealing with this similar issue.

Have you checked the 4.0 discussion thread regarding changing versions triggering this? Also, clean those folders that above mentioned
