### ISSUE TITLE
Community Forum Support?

### ISSUE THREAD

**Issue by new112211** [haugene/docker-transmission-openvpn#1865]
## Before creating this issue I have:

**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in :** 
 
```<placeholder>```

*If possible, last working version:* 
 
```<Leave empty if not known>```

### Describe the problem

**REQUIRED**
```Hey guys, 
Hope everyone is keeping well and I'm sorry for posting this here. 

Does anyone know of any community forums that I could go to for assistance for this program? 

As a result of a disease, I have developed some brain trauma and haven't found an appropriate guide on the web. I've been trying for the past three months setting up and configuring it on a Synology NAS but am quite lost. 

Many thanks in advance for any advise provided and again sorry for the incorrect post. 

Cheers

<placeholder>
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt
<-- Paste here -->
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
<-- Paste here -->
```

### Logs

 

**REQUIRED**
```txt
<-- Paste here -->
```

### Host system

**REQUIRED**
```txt
<-- Paste here -->
```

**Comment by pkishino** [comment]
You havent actually stated what eactly your problem is.
There are some issues with Synology NAS setup, check the pinned issues or search the issues.
Have you tried setting it up on something else than your NAS?
you can try the github gitter chat linked on the main page

**Comment by new112211** [comment]
> You havent actually stated what eactly your problem is.
> There are some issues with Synology NAS setup, check the pinned issues or search the issues.
> Have you tried setting it up on something else than your NAS?
> you can try the github gitter chat linked on the main page

Apologies, I suppose I was looking for some assistance setting it up from the beginning really.  The brain damage makes it quite difficult to follow along without visual ques, Annoyingly frustrating. I will try posting the question on the gitter chat.
Thanks for the direction. 👍
