### ISSUE TITLE
curl: (6) Could not resolve host: www.privateinternetaccess.com

### ISSUE THREAD

**Issue by adamh98** [haugene/docker-transmission-openvpn#1866]
## Before creating this issue I have:

**REQUIRED**
- [x] Read through the pinned issues for related problems
- [x] Searched for similar [provider issues][pi] and [container issues][ci]
- [x] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the issue as possible
- [x] Verified I have tried using newest release as well
- [x] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in :** 
 
```<Docker Version : 20.10.2>```

*If possible, last working version:* 
 
```<Leave empty if not known>```

### Describe the problem

**REQUIRED**
```txt
I rebooted my machine with a Linux VM. Everything was working before, but after the reboot, and starting up the VM with Docker-Compose it would not finish starting.
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt
< I've searched on other posts that appear to be exactly the same error, however, with the remedies that I've seen and done it has not resolved my issue. I can verify the DNS is able to resolve www.privateinternetaccess.com from the host VM. I've added the parameters for DNS from the FAQ
I've tried both options, and the logs show the most recent with the OVERRIDE_DNS parameters.>
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
<Docker-Compose
version: '3.3'
services:
transmission-openvpn:
cap_add:
- NET_ADMIN
volumes:
- '/media/nfs/:/data'
environment:
- OPENVPN_PROVIDER=PIA
- PIA_OPENVPN_CONFIG_BUNDLE=openvpn
- OPENVPN_CONFIG=ca_vancouver
- OPENVPN_USERNAME=[]
- OPENVPN_PASSWORD=[]
- OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
- TRANSMISSION_RPC_USERNAME=admin
- TRANSMISSION_RPC_PASSWORD=
- OVERRIDE_DNS_1=8.8.8.8
- OVERRIDE_DNS_2=4.2.2.2
- LOCAL_NETWORK=10.20.30.0/24
logging:
driver: json-file
options:
max-size: 10m
ports:
- '9091:9091'
- '8888:8888'
image: haugene/transmission-openvpn>
```

### Logs

 

**REQUIRED**
```txt
<Container Logs:
Starting docker_transmission-openvpn_1 ... done
Attaching to docker_transmission-openvpn_1
transmission-openvpn_1 | Starting container with revision: baed33520630e88ba34842cab05f2cd3fd6cf28f
transmission-openvpn_1 | One or more OVERRIDE_DNS addresses found. Will use them to overwrite /etc/resolv.conf
transmission-openvpn_1 | Creating TUN device /dev/net/tun
transmission-openvpn_1 | Using OpenVPN provider: PIA
transmission-openvpn_1 | Provider PIA has a custom setup script, executing it
transmission-openvpn_1 | Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.Acckcm
transmission-openvpn_1 | curl: (6) Could not resolve host: www.privateinternetaccess.com
docker_transmission-openvpn_1 exited with code 6
>
```

### Host system

**REQUIRED**
```txt
<OS: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-147-generic x86_64)
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.2-0ubuntu1~18.04.2
 Built:             Tue Mar 30 21:24:16 2021
 OS/Arch:           linux/amd64>
```

**Comment by balupton** [comment]
I wonder if my encounter with this with nordvpn and generally is the same thing:

https://github.com/haugene/docker-transmission-openvpn/issues/1858#issuecomment-873502801

If so, maybe docker or ubuntu broke something?

**Comment by adamh98** [comment]
@balupton 
I'll give that a try. When I did the command to display the resolve information it appeared accurate. Thanks for the heads up.

**Comment by adamh98** [comment]
I just tried the - NET=HOST in the config and it didn't work.

**Comment by edgd1er** [comment]
@adamh98 

https://haugene.github.io/docker-transmission-openvpn/tips-tricks/

Some have encountered problems with DNS resolving inside the docker container. This causes trouble because OpenVPN will not be able to resolve the host to connect to. If you have this problem use Docker's --dns flag and try using Google's DNS servers by adding --dns 8.8.8.8 --dns 8.8.4.4 as parameters to the usual run command.

**Comment by adamh98** [comment]
I've been declaring the DNS for Google with the same result. 

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/media/nfs/:/data'
        environment:
            - OPENVPN_PROVIDER=PIA
            - PIA_OPENVPN_CONFIG_BUNDLE=openvpn
            - OPENVPN_CONFIG=ca_vancouver
            - OPENVPN_USERNAME=[]
            - OPENVPN_PASSWORD=[]
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - TRANSMISSION_RPC_USERNAME=admin
            - TRANSMISSION_RPC_PASSWORD=
            - NET=HOST
            - OVERRIDE_DNS_1= 8.8.8.8
            - OVERRIDE_DNS_2 = 8.8.4.4
            - LOCAL_NETWORK=10.20.30.0/24
        logging:
            driver: json-file
            options:
              max-size: 10m
        ports:
            - '9091:9091'
            - '8888:8888'
        image: haugene/transmission-openvpn
        
        
Recreating docker_transmission-openvpn_1 ...
Recreating docker_transmission-openvpn_1 ... done
Attaching to docker_transmission-openvpn_1
transmission-openvpn_1  | Starting container with revision: baed33520630e88ba34842cab05f2cd3fd6cf28f
transmission-openvpn_1  | **One or more OVERRIDE_DNS addresses found. Will use them to overwrite /etc/resolv.conf**
transmission-openvpn_1  | Creating TUN device /dev/net/tun
transmission-openvpn_1  | Using OpenVPN provider: PIA
transmission-openvpn_1  | Provider PIA has a custom setup script, executing it
transmission-openvpn_1  | Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.KjkmiH
transmission-openvpn_1  | curl: (6) Could not resolve host: www.privateinternetaccess.com
docker_transmission-openvpn_1 exited with code 6

**Comment by balupton** [comment]
Just a heads up from my side, apparently my DNS is being intercepted, and that is what is causing things to fail:

https://superuser.com/a/1660609/32418

I'm testing now if using an encrypted dns service on the host machine will resolve this.

Debugging scripts for others: https://gist.github.com/balupton/9a1bd98cc9de175f407dd4e543ee80ac

**Comment by adamh98** [comment]
That's really interesting. I'll sift through it.

**Comment by balupton** [comment]
Was able to get my setup going. I'll post the solution once I've cleaned everything up tomorrow.

**Comment by pkishino** [comment]
interesting.. hope to see the solution and look into this more at some point

**Comment by adamh98** [comment]
@balupton 
Congrats on getting it going. When it's convenient, I'd love to know what you did. Thanks!

**Comment by balupton** [comment]
@pkishino @adamh98 see the solution here:

https://github.com/haugene/docker-transmission-openvpn/issues/1858#issuecomment-874429497

**Comment by ItsRainingHP** [comment]
Good morning @adamh98. I have PIA too and have come accross this issue several times. Using Google as a DNS server for PIA will always result in the above error you received. You must use PIA's own DNS servers which currently are:

nameserver 209.222.18.222
nameserver 209.222.18.218

**Comment by adamh98** [comment]
@ItsRainingHP 
Thanks for the insight. I tried their DNS servers and still received the same result.

**Comment by ItsRainingHP** [comment]
Do you use a resolv.conf setup? I have to set mine to read-only. Otherwise it gets rewritten as 8.8.8.8 on startup.

**Comment by adamh98** [comment]
@ItsRainingHP 
I use the environmental command OVERRIDE_DNS_1= 209.222.18.222 Which will override the resolv.conf setup file and use the one I designate.

**Comment by ItsRainingHP** [comment]
Have you tried using a default ovpn file that the docker pulls rather then specifying one? Also, does your docker have proper permissions to /media/nfs/. Have you since tried using 3.6?

**Comment by adamh98** [comment]
@ItsRainingHP I'm not sure if I have used the default opencpn file. I know the permissions for the nfs is good. I have not tried 3.6. 
I think I started to go down the route of the resolv method, but from my troubleshooting everything was working for the host to resolve any given test. So it was just the container and it's inability to resolve the query. I figured the need for the override was to bypass what was thought to be the cause of the queries failing.

**Comment by ItsRainingHP** [comment]
I see. I would honestly try the resolv.conf method and set the file to read only. If that fails I would clear the docker setup entirely and build it using the debug guide:

https://haugene.github.io/docker-transmission-openvpn/debug/

Using the bare minimum setup (i would exclude the  -e OPENVPN_CONFIG=france \ altogether to determine if the default works)

**Comment by adamh98** [comment]
@ItsRainingHP 
Thank you for that! I'll check it out and give it a try. I did remove the openvpn config, and it still tried to pull the config from www.privateinternetaccess.com 
I'm assuming because I have not declared a local file it will pull from their site.

**Comment by rporotti** [comment]
Apparently it's a specific problem with Alpine and Docker (more on this [here](https://github.com/gliderlabs/docker-alpine/issues/334) 

I solved it with [this](https://github.com/gliderlabs/docker-alpine/issues/334#issuecomment-879368146)

**Comment by adamh98** [comment]
@rporotti 
Thank you for that! I found that it works when I don't use docker compose. I will try the solution you pointed out. Thank you!

**Comment by pkishino** [comment]
seems to be fixed
