### ISSUE TITLE
IPVanish: certificate verify failed

### ISSUE THREAD

**Issue by dmpcc** [haugene/docker-transmission-openvpn#187]
Hi 

I think the IPVanish certificate needs an update because it stopped working.

Below is an logfile extract.

Regards,

DMP
`
....
Wed Jan 18 17:21:31 2017 Restart pause, 2 second(s)
Wed Jan 18 17:21:31 2017 SIGUSR1[soft,tls-error] received, process restarting
Wed Jan 18 17:21:31 2017 TLS Error: TLS handshake failed
Wed Jan 18 17:21:31 2017 TLS Error: TLS object -> incoming plaintext read error
Wed Jan 18 17:21:31 2017 TLS_ERROR: BIO read tls_read_plaintext error: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Wed Jan 18 17:21:31 2017 VERIFY ERROR: depth=1, error=certificate has expired: /C=US/ST=FL/L=Winter Park/O=IPVanish/OU=IPVanish VPN/CN=IPVanish CA/emailAddress=support@ipvanish.com
Wed Jan 18 17:21:31 2017 TLS: Initial packet from [AF_INET]81.17.24.154:443, sid=effc19c4 75e896fe
Wed Jan 18 17:21:31 2017 UDPv4 link remote: [AF_INET]81.17.24.154:443
Wed Jan 18 17:21:31 2017 UDPv4 link local: [undef]
Wed Jan 18 17:21:31 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]81.17.24.154:443
Wed Jan 18 17:21:31 2017 Socket Buffers: R=[212992->131072] S=[212992->131072]
Wed Jan 18 17:21:31 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Jan 18 17:21:29 2017 Restart pause, 2 second(s)
Wed Jan 18 17:21:29 2017 SIGUSR1[soft,tls-error] received, process restarting
Wed Jan 18 17:21:29 2017 TLS Error: TLS handshake failed
Wed Jan 18 17:21:29 2017 TLS Error: TLS object -> incoming plaintext read error
Wed Jan 18 17:21:29 2017 TLS_ERROR: BIO read tls_read_plaintext error: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Wed Jan 18 17:21:29 2017 VERIFY ERROR: depth=1, error=certificate has expired: /C=US/ST=FL/L=Winter Park/O=IPVanish/OU=IPVanish VPN/CN=IPVanish CA/emailAddress=support@ipvanish.com
Wed Jan 18 17:21:29 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Jan 18 17:21:29 2017 TLS: Initial packet from [AF_INET]81.17.24.154:443, sid=eec7a5b8 5b9582d8
Wed Jan 18 17:21:29 2017 UDPv4 link remote: [AF_INET]81.17.24.154:443
Wed Jan 18 17:21:29 2017 UDPv4 link local: [undef]
Wed Jan 18 17:21:28 2017 Socket Buffers: R=[212992->131072] S=[212992->131072]
Wed Jan 18 17:21:28 2017 Deprecated TLS cipher name 'AES256-SHA', please use IANA name 'TLS-RSA-WITH-AES-256-CBC-SHA'
Wed Jan 18 17:21:28 2017 Deprecated TLS cipher name 'DHE-DSS-AES256-SHA', please use IANA name 'TLS-DHE-DSS-WITH-AES-256-CBC-SHA'
Wed Jan 18 17:21:28 2017 Deprecated TLS cipher name 'DHE-RSA-AES256-SHA', please use IANA name 'TLS-DHE-RSA-WITH-AES-256-CBC-SHA'
Wed Jan 18 17:21:28 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Jan 18 17:21:28 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Wed Jan 18 17:21:28 2017 DEPRECATED OPTION: --tls-remote, please update your configuration
+ exec openvpn --config /etc/openvpn/ipvanish/ipvanish-CH-Zurich-zur-c02.ovpn
+ dockerize -template /etc/transmission/environment-variables.tmpl:/etc/transmission/environment-variables.sh /bin/true
+ echo password
+ echo username
+ chmod 600 /config/openvpn-credentials.txt
+ echo xxxxxxx
+ echo xxxxxxx
+ mkdir -p /config
Setting OPENVPN credentials...
+ echo Setting OPENVPN credentials...
+ [ xxxxxxxx = **None** ]
+ [ xxxxxxxxx = **None** ]
+ OPENVPN_CONFIG=/etc/openvpn/ipvanish/ipvanish-CH-Zurich-zur-c02.ovpn
Starting OpenVPN using config ipvanish-CH-Zurich-zur-c02.ovpn
+ echo Starting OpenVPN using config ipvanish-CH-Zurich-zur-c02.ovpn
+ [ -f /etc/openvpn/ipvanish/ipvanish-CH-Zurich-zur-c02.ovpn ]
+ [ ! -z ipvanish-CH-Zurich-zur-c02 ]
Using OpenVPN provider: IPVANISH
+ echo Using OpenVPN provider: IPVANISH
+ [ ! -d /etc/openvpn/ipvanish ]
+ vpn_provider_configs=/etc/openvpn/ipvanish
+ vpn_provider=ipvanish
+ tr [A-Z] [a-z]
+ echo IPVANISH
`

**Comment by tsuyoi** [comment]
The cert and configurations were updated recently. Have you pulled the latest build? It looks like you might be using an old version by the look of this line: 
`Wed Jan 18 17:21:28 2017 Deprecated TLS cipher name 'DHE-RSA-AES256-SHA', please use IANA name 'TLS-DHE-RSA-WITH-AES-256-CBC-SHA' `

**Comment by dmpcc** [comment]
Ah yes sorry. The update I performed went wrong. Running the latest build now and it works 👍
