### ISSUE TITLE
Extension ".added" being added to all torrents in Watch folder

### ISSUE THREAD

**Issue by knocka91** [haugene/docker-transmission-openvpn#1903]
## Before creating this issue I have:

**REQUIRED**
- [ x] Read through the pinned issues for related problems
- [ x] Searched for similar [provider issues][pi] and [container issues][ci]
- [x ] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [x ] Tried to add as much relevant information to the issue as possible
- [ x] Verified I have tried using newest release as well
- [ x] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in :** 
 
``haugene transmission openvpn1:latest build

*If possible, last working version:* 
 
```<Leave empty if not known>```

### Describe the problem

Every time I add a torrent to the Watch folder, and Transmission auto loads the torrent, the extension ".added" is inserted at the end of the filename.  I use a folder on Box.com as my Watch folder, so that when I add a torrent to that folder on my Macbook, it automatically syncs to the Watch folder on the NAS.

The problem, of course, is that when Transmission inserted the ".added" extension at the end of the torrent, when that file gets deleted, the deletion does not sync, because the files on box.com do not have the .added extension.

I tested this with multiple Watch folders, including not in Box.com, and I have the same problem.

How can I stop Transmission from inserting .added after every torrent file.

```
### Describe the steps you have tried to solve the problem
<!-- A list of steps -->
<!--
 e.g 1) tried other release/build (which ones?) I am using latest
     2) verified container can resolve DNS (added --dns?) Yes
     3) check .ovpn is valid (outdated?) Yes.
     4) check settings.json is valid (try with clean container?) Yes,
     5) Checked issues #XXX and #XXX and tried XXX
     6) ...As described above, I ried using different folders as the Watch folder, but Transmission always inserts the .added extension at the end.
 -->
<!-- (please paste into the code block) -->

**REQUIRED**
```txt
<-- Paste here -->
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
<-- Paste here -->
 Config

    AttachStderr false
    AttachStdin false
    AttachStdout false
    Cmd [ dumb-init, /etc/openvpn/start.sh ]
    DDSM false
    Domainname
    Entrypoint
    Env [ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, OPENVPN_USERNAME=P6850212, OPENVPN_PASSWORD=jmc/2926, OPENVPN_PROVIDER=PIA, GLOBAL_APPLY_PERMISSIONS=true, TRANSMISSION_HOME=/data/transmission-home, TRANSMISSION_RPC_PORT=9091, TRANSMISSION_DOWNLOAD_DIR=/data/completed, TRANSMISSION_INCOMPLETE_DIR=/data/incomplete, TRANSMISSION_WATCH_DIR=/data/watch, CREATE_TUN_DEVICE=true, ENABLE_UFW=false, UFW_ALLOW_GW_NET=false, UFW_EXTRA_PORTS=, UFW_DISABLE_IPTABLES_REJECT=false, PUID=1026, PGID=100, DROP_DEFAULT_ROUTE=, WEBPROXY_ENABLED=false, WEBPROXY_PORT=8888, WEBPROXY_USERNAME=, WEBPROXY_PASSWORD=, LOG_TO_STDOUT=false, HEALTH_CHECK_HOST=google.com, REVISION=73ec516cc246972289c7b96ffa88c81e037fe364, TZ=America/New_York, PIA_OPENVPN_CONFIG_BUNDLE=openvpn, OPENVPN_CONFIG=ca_montreal ]
    ExposedPorts { 8888/tcp: [object Object], 9091/tcp: [object Object] }
    Healthcheck { Interval: 60000000000, Test: CMD-SHELL,/etc/scripts/healthcheck.sh }
    Hostname haugene-transmission-openvpn1
    Image haugene/transmission-openvpn:latest
    Labels { autoheal: true, org.opencontainers.image.revision: 73ec516cc246972289c7b96ffa88c81e037fe364, org.opencontainers.image.source: https://github.com/haugene/docker-transmission-openvpn }
    OnBuild
    OpenStdin true
    StdinOnce false
    Tty true
    User
    Volumes { /config: [object Object], /data: [object Object], /data/completed: [object Object], /data/incomplete: [object Object], /data/watch: [object Object], /etc/resolv.conf: [object Object] }
    WorkingDir

Created 2021-08-06T12:45:01.136417466Z
Driver btrfs
ExecIDs
[_haugene-transmission-openvpn1-Fixed_logs.txt](https://github.com/haugene/docker-transmission-openvpn/files/6974962/_haugene-transmission-openvpn1-Fixed_logs.txt)

```

### Logs

 

**REQUIRED**
```txt
<-- Paste here -->
```

### Host system

Synology NAS DS920+
Docker V. 20.10.3-1233
**REQUIRED**
```txt
<-- Paste here -->
```

**Comment by knocka91** [comment]
I edited it.  Is it OK now.

**Comment by pkishino** [comment]
Hello, I usually don’t check these issues as people don’t seem to bother to read the complete issue template.. you clearly have missed several bits and pieces (such as verifying the check boxes etc..) which will auto fail the bot..
But I will leave this closed as this is an issue with transmission and not this container. Transmission adds that and we can’t change that. Please raise the issue with the official transmission devs

**Comment by pkishino** [comment]
Oh, and you might want to sanitize your username and password…
