### ISSUE TITLE
Unable to access Transmission WEBUI

### ISSUE THREAD

**Issue by philippebezoteaux** [haugene/docker-transmission-openvpn#1906]
### Container version & last working release
Latest running in SYNOLOGY DSM7 docker 

### Describe the problem
Hi all, cannot access transmission webui for a few ours after a year perfectly working…

### Describe the steps you have tried to solve the problem
Updated my custom (CyberGhost) config files and did a fresh setup of my container,
Checked container logs without any major issues

### Add your docker run command or docker-compose file or env details
IMAGE | haugene/transmission-openvpn:latest@sha256:36a34a444076c1e0c55c1fc695b1183c8453632e15f7b67748084905491a5cea
-- | --
PORT CONFIGURATION | 0.0.0.0:30000  8888/tcp 0.0.0.0:30001  9091/tcp
CMD | dumb-init /etc/openvpn/start.sh
ENTRYPOINT | null

ENV | CREATE_TUN_DEVICEtrueDROP_DEFAULT_ROUTEENABLE_UFWfalseGLOBAL_APPLY_PERMISSIONStrueHEALTH_CHECK_HOSTgoogle.comLOG_TO_STDOUTfalseOPENVPN_PASSWORD**None**OPENVPN_PROVIDERCUSTOMOPENVPN_USERNAME**None**PATH/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binPGIDPUIDREVISION73ec516cc246972289c7b96ffa88c81e037fe364TRANSMISSION_DOWNLOAD_DIR/data/completedTRANSMISSION_HOME/data/transmission-homeTRANSMISSION_INCOMPLETE_DIR/data/incompleteTRANSMISSION_RPC_PORT9091TRANSMISSION_WATCH_DIR/data/watchTZEurope/ParisUFW_ALLOW_GW_NETfalseUFW_DISABLE_IPTABLES_REJECTfalseUFW_EXTRA_PORTSWEBPROXY_ENABLEDfalseWEBPROXY_PASSWORDWEBPROXY_PORT8888WEBPROXY_USERNAME | CREATE_TUN_DEVICE | true | DROP_DEFAULT_ROUTE |   | ENABLE_UFW | false | GLOBAL_APPLY_PERMISSIONS | true | HEALTH_CHECK_HOST | google.com | LOG_TO_STDOUT | false | OPENVPN_PASSWORD | **None** | OPENVPN_PROVIDER | CUSTOM | OPENVPN_USERNAME | **None** | PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin | PGID |   | PUID |   | REVISION | 73ec516cc246972289c7b96ffa88c81e037fe364 | TRANSMISSION_DOWNLOAD_DIR | /data/completed | TRANSMISSION_HOME | /data/transmission-home | TRANSMISSION_INCOMPLETE_DIR | /data/incomplete | TRANSMISSION_RPC_PORT | 9091 | TRANSMISSION_WATCH_DIR | /data/watch | TZ | Europe/Paris | UFW_ALLOW_GW_NET | false | UFW_DISABLE_IPTABLES_REJECT | false | UFW_EXTRA_PORTS |   | WEBPROXY_ENABLED | false | WEBPROXY_PASSWORD |   | WEBPROXY_PORT | 8888 | WEBPROXY_USERNAME |  
CREATE_TUN_DEVICE | true
DROP_DEFAULT_ROUTE |  
ENABLE_UFW | false
GLOBAL_APPLY_PERMISSIONS | true
HEALTH_CHECK_HOST | google.com
LOG_TO_STDOUT | false
OPENVPN_PASSWORD | **None**
OPENVPN_PROVIDER | CUSTOM
OPENVPN_USERNAME | **None**
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PGID |  
PUID |  
REVISION | 73ec516cc246972289c7b96ffa88c81e037fe364
TRANSMISSION_DOWNLOAD_DIR | /data/completed
TRANSMISSION_HOME | /data/transmission-home
TRANSMISSION_INCOMPLETE_DIR | /data/incomplete
TRANSMISSION_RPC_PORT | 9091
TRANSMISSION_WATCH_DIR | /data/watch
TZ | Europe/Paris
UFW_ALLOW_GW_NET | false
UFW_DISABLE_IPTABLES_REJECT | false
UFW_EXTRA_PORTS |  
WEBPROXY_ENABLED | false
WEBPROXY_PASSWORD |  
WEBPROXY_PORT | 8888
WEBPROXY_USERNAME |  
LABELS | autohealtrueorg.opencontainers.image.revision73ec516cc246972289c7b96ffa88c81e037fe364org.opencontainers.image.sourcehttps://github.com/haugene/docker-transmission-openvpn | autoheal | true | org.opencontainers.image.revision | 73ec516cc246972289c7b96ffa88c81e037fe364 | org.opencontainers.image.source | https://github.com/haugene/docker-transmission-openvpn
autoheal | true
org.opencontainers.image.revision | 73ec516cc246972289c7b96ffa88c81e037fe364
org.opencontainers.image.source | https://github.com/haugene/docker-transmission-openvpn

### Logs

2021-08-13 15:03:29 us=36040   push_ifconfig_remote_netmask = 0.0.0.0
,2021-08-13 15:03:29 us=36055   push_ifconfig_ipv6_defined = DISABLED
,2021-08-13 15:03:29 us=36084   push_ifconfig_ipv6_local = ::/0
,2021-08-13 15:03:29 us=36104   push_ifconfig_ipv6_remote = ::
,2021-08-13 15:03:29 us=36119   enable_c2c = DISABLED
,2021-08-13 15:03:29 us=36135   duplicate_cn = DISABLED
,2021-08-13 15:03:29 us=36149   cf_max = 0
,2021-08-13 15:03:29 us=36164   cf_per = 0
,2021-08-13 15:03:29 us=36179   max_clients = 1024
,2021-08-13 15:03:29 us=36194   max_routes_per_client = 256
,2021-08-13 15:03:29 us=36208   auth_user_pass_verify_script = '[UNDEF]'
,2021-08-13 15:03:29 us=36223   auth_user_pass_verify_script_via_file = DISABLED
,2021-08-13 15:03:29 us=36238   auth_token_generate = DISABLED
,2021-08-13 15:03:29 us=36253   auth_token_lifetime = 0
,2021-08-13 15:03:29 us=36268   auth_token_secret_file = '[UNDEF]'
,2021-08-13 15:03:29 us=36283   port_share_host = '[UNDEF]'
,2021-08-13 15:03:29 us=36298   port_share_port = '[UNDEF]'
,2021-08-13 15:03:29 us=36313   vlan_tagging = DISABLED
,2021-08-13 15:03:29 us=36327   vlan_accept = all
,2021-08-13 15:03:29 us=36342   vlan_pvid = 1
,2021-08-13 15:03:29 us=36356   client = ENABLED
,2021-08-13 15:03:29 us=36371   pull = ENABLED
,2021-08-13 15:03:29 us=36385   auth_user_pass_file = '/config/openvpn-credentials.txt'
,2021-08-13 15:03:29 us=36404 OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
,2021-08-13 15:03:29 us=36430 library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
,2021-08-13 15:03:29 us=36622 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
,2021-08-13 15:03:29 us=41704 Control Channel MTU parms [ L:1621 D:1212 EF:38 EB:0 ET:0 EL:3 ]
,2021-08-13 15:03:29 us=93699 Data Channel MTU parms [ L:1621 D:1450 EF:121 EB:406 ET:0 EL:3 ]
,2021-08-13 15:03:29 us=93834 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1569,tun-mtu 1500,proto UDPv4,cipher AES-256-CBC,auth SHA256,keysize 256,key-method 2,tls-client'
,2021-08-13 15:03:29 us=93867 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1569,tun-mtu 1500,proto UDPv4,cipher AES-256-CBC,auth SHA256,keysize 256,key-method 2,tls-server'
,2021-08-13 15:03:29 us=93920 TCP/UDP: Preserving recently used remote address: [AF_INET]5.253.204.6:443
,2021-08-13 15:03:29 us=93997 Socket Buffers: R=[212992->212992] S=[212992->212992]
,2021-08-13 15:03:29 us=94029 UDP link local: (not bound)
,2021-08-13 15:03:29 us=94063 UDP link remote: [AF_INET]5.253.204.6:443
,2021-08-13 15:03:29 us=110516 TLS: Initial packet from [AF_INET]5.253.204.6:443, sid=510808b4 e0da3a76
,2021-08-13 15:03:29 us=133743 VERIFY OK: depth=1, C=RO, L=Bucharest, O=CyberGhost S.A., CN=CyberGhost Root CA, emailAddress=info@cyberghost.ro
,2021-08-13 15:03:29 us=134513 VERIFY KU OK
,2021-08-13 15:03:29 us=134562 Validating certificate extended key usage
,2021-08-13 15:03:29 us=134590 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
,2021-08-13 15:03:29 us=134615 VERIFY EKU OK
,2021-08-13 15:03:29 us=134699 VERIFY OK: depth=0, CN=luxembourg-rack401.nodes.gen4.ninja
,2021-08-13 15:03:29 us=207941 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1569', remote='link-mtu 1549'
,2021-08-13 15:03:29 us=208023 WARNING: 'auth' is used inconsistently, local='auth SHA256', remote='auth [null-digest]'
,2021-08-13 15:03:29 us=208078 WARNING: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
,2021-08-13 15:03:29 us=208300 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 4096 bit RSA, signature: RSA-SHA256
,2021-08-13 15:03:29 us=208453 [luxembourg-rack401.nodes.gen4.ninja] Peer Connection Initiated with [AF_INET]5.253.204.6:443
,2021-08-13 15:03:30 us=265773 SENT CONTROL [luxembourg-rack401.nodes.gen4.ninja]: 'PUSH_REQUEST' (status=1)
,2021-08-13 15:03:30 us=290913 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,route-ipv6 2000::/3,dhcp-option DNS 10.0.0.243,route-gateway 10.4.4.1,topology subnet,ping 10,ping-restart 60,ifconfig 10.4.4.74 255.255.255.0,peer-id 16'
,2021-08-13 15:03:30 us=290990 WARNING: You have specified redirect-gateway and redirect-private at the same time (or the same option multiple times). This is not well supported and may lead to unexpected results
,2021-08-13 15:03:30 us=291096 OPTIONS IMPORT: timers and/or timeouts modified
,2021-08-13 15:03:30 us=291122 OPTIONS IMPORT: --ifconfig/up options modified
,2021-08-13 15:03:30 us=291144 OPTIONS IMPORT: route options modified
,2021-08-13 15:03:30 us=291166 OPTIONS IMPORT: route-related options modified
,2021-08-13 15:03:30 us=291189 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
,2021-08-13 15:03:30 us=291211 OPTIONS IMPORT: peer-id set
,2021-08-13 15:03:30 us=291233 OPTIONS IMPORT: adjusting link_mtu to 1624
,2021-08-13 15:03:30 us=291367 Outgoing Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
,2021-08-13 15:03:30 us=291404 Outgoing Data Channel: Using 256 bit message hash 'SHA256' for HMAC authentication
,2021-08-13 15:03:30 us=291432 Incoming Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
,2021-08-13 15:03:30 us=291469 Incoming Data Channel: Using 256 bit message hash 'SHA256' for HMAC authentication
,2021-08-13 15:03:30 us=291720 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
,2021-08-13 15:03:30 us=291770 GDG6: remote_host_ipv6=n/a
,2021-08-13 15:03:30 us=291799 net_route_v6_best_gw query: dst ::
,2021-08-13 15:03:30 us=291905 net_route_v6_best_gw result: via :: dev lo
,2021-08-13 15:03:30 us=291946 ROUTE6_GATEWAY :: ON_LINK IFACE=lo
,2021-08-13 15:03:30 us=292296 TUN/TAP device tun0 opened
,2021-08-13 15:03:30 us=292339 do_ifconfig, ipv4=1, ipv6=0
,2021-08-13 15:03:30 us=292378 /sbin/ip link set dev tun0 up mtu 1500
,2021-08-13 15:03:30 us=299132 /sbin/ip link set dev tun0 up
,2021-08-13 15:03:30 us=300767 /sbin/ip addr add dev tun0 10.4.4.74/24
,2021-08-13 15:03:30 us=302612 /etc/openvpn/tunnelUp.sh tun0 1500 1624 10.4.4.74 255.255.255.0 init
,Up script executed with tun0 1500 1624 10.4.4.74 255.255.255.0 init
,Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.4.4.74
,Updating Transmission settings.json with values from env variables
,Using existing settings.json for Transmission /data/transmission-home/settings.json
,Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.4.4.74
,Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
,Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
,Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
,Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
,sed'ing True to true
,
,-------------------------------------
,Transmission will run as
,-------------------------------------
,User name:   root
,User uid:    0
,User gid:    0
,-------------------------------------
,
,STARTING TRANSMISSION
,Transmission startup script complete.
,2021-08-13 15:03:35 us=575942 /sbin/ip route add 5.253.204.6/32 via 172.17.0.1
,2021-08-13 15:03:35 us=577316 /sbin/ip route add 0.0.0.0/1 via 10.4.4.1
,2021-08-13 15:03:35 us=578565 /sbin/ip route add 128.0.0.0/1 via 10.4.4.1
,2021-08-13 15:03:35 us=579745 WARNING: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.
,2021-08-13 15:03:35 us=579812 add_route_ipv6(2000::/3 -> :: metric -1) dev tun0
,2021-08-13 15:03:35 us=579862 /sbin/ip -6 route add 2000::/3 dev tun0
,2021-08-13 15:03:35 us=581174 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
,2021-08-13 15:03:35 us=581233 Initialization Sequence Completed
[_transmission-openvpn_logs 3.txt](https://github.com/haugene/docker-transmission-openvpn/files/6982651/_transmission-openvpn_logs.3.txt)

### Host system
DSM7:latest

**Comment by pkishino** [comment]
Wow.. duplicate issues created, first time total disregard of the explicit issue those, second time barely.. do people never stop and think why there is an issue template? Never use preview?
Sorry, but you haven’t even tried to search other issues as there is one explicitly referring to DSM that is pinned. Look there

**Comment by philippebezoteaux** [comment]
😄 nice answer… fact is that I was looking for a way to remove these. As I found the issue and does not relate to any issues mentioned (looked before but you might not have even really read my issue)


Do people are always that friendly with total disregard with welcoming manners ? Especially when a beginner learns how to operate the forum ?

**Comment by pkishino** [comment]
First of all, this is not a forum, this is an issue tracker..
Second, we do this in our free time.. in the past we had many many nonsense posts and people not providing requested details.. so we created a very detailed template people should follow. Detailed enough that anyone, even beginners, could clearly fill it in correctly. All that is needed is to READ it completely and preview your own issue to see that it looks good.. is that so hard?
This is so we can focus on the real issues and have all the necessary details right away, not waste time going back and forth.
None of us are payed to do this, so we expect people to actually put in some effort if they want help.
I know several other successful projects that I've supported or use that closed their issues trackers in the recent months due to the flood of bad,invalid, non-formatted, not-template following posts..
So, yes, it is quite frustrating when people not only ignore the template and then even create duplicate issues instead of editing their post..

now, to your issue.. if you actually did post the complete config, then you are missing at least LOCAL_NETWORK, which is a required variable.. please check and fix if necessary, that would explain why you cannot access the UI.
Otherwise, if you havent changed anything and it was working before (including NOT updating the container) then it's a provider issue, check the ovpn config.

**Comment by pkishino** [comment]
also, the other issue does discuss changes on DSM 7 ..so if you are running 7 then you should look through that to get the container running properly
