### ISSUE TITLE
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/privatevpn/new-york-usa-allportfwd.ovpn

### ISSUE THREAD

**Issue by Silversurfer79** [haugene/docker-transmission-openvpn#1923]
## Before creating this issue I have:

**REQUIRED**
- [x ] Read through the pinned issues for related problems
- [ x] Searched for similar [provider issues][pi] and [container issues][ci]
- [ x] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [ x] Tried to add as much relevant information to the issue as possible
- [ x] Verified I have tried using newest release as well
- [ x] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release
Latest from docker repo 
93d0141d928ec661411e2c6f0e079aeff2c018dd

*If possible, last working version:* 
 
Pre DSM7 upgrade (2 days back

### Describe the problem
Container wont start and fails after with "adding route to local network".

Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/privatevpn/new-york-usa-allportfwd.ovpn

It will also fail if I leave the OPENVPN_CONFIG blank witht he same error but ending in, default.ovpn

```
### Describe the steps you have tried to solve the problem
<!-- A list of steps -->
<!--
Tried different OPENVPN_CONFIG options
Pulled down the latest Image
check dns
check account
changed local netowrk from /24 to /16
 -->


**REQUIRED**
```txt
<-- Paste here -->
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
<-- Paste here -->
```

### Logs
See error message

</body>
</html>

 

**REQUIRED**
```txt
<-- Paste here -->
```

### Host system
Synology DSM 7

**REQUIRED**
```txt
<-- Paste here -->
```

**Comment by Silversurfer79** [comment]
please guys can i get some help

**Comment by reconman** [comment]
See #1839
