### ISSUE TITLE
aarch64 support for your container

### ISSUE THREAD

**Issue by snakefox666** [haugene/docker-transmission-openvpn#193]
Hello Haugene,
it's not really an issue but more a request in fact, is it possible to duplicate your container and adapt it for aarch64 platform ? :-)

**Comment by haugene** [comment]
Hey :)

It might be, haven't really run any containers on architectures other than x86. I guess we would have the same issue as with ARM when it comes to automated builds (#170). 

That being said, the Dockerfile and docker-compose.yml are duplicated in the repo now for x86 and ARM. So we could add another. PRs are welcome ;)

**Comment by haugene** [comment]
Update: #582 adds support for automatic builds on Docker Hub. New tag dev-armhf is [built and available](https://hub.docker.com/r/haugene/transmission-openvpn/tags/).
