### ISSUE TITLE
Use Github forms for bug reports

### ISSUE THREAD

**Issue by reconman** [haugene/docker-transmission-openvpn#1930]
## Before creating this request I have:

**REQUIRED**
- [x] Read through the pinned issues for related problems
- [x] Searched for similar [provider issues][pi] and [container issues][ci]
- [x] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the request as possible
- [x] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Is your feature request related to a problem? Please describe.

**REQUIRED**
```txt
Users keep ignoring the issue template.
```

### Describe the solution you'd like

**REQUIRED**
```txt
Use Github forms so users are forced to fill in the necessary details. They also can't mess up the checkboxes anymore.

See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms for the documentation and https://github.com/Fate-Grand-Automata/FGA/issues/new?labels=bug&template=bug_report.yml for a live demo in one of my repositories.
```

### Describe alternatives you've considered

**REQUIRED**
```txt
```

**Comment by reconman** [comment]
No matter how I update this issue, the bot keeps closing it. As I said, the bot is too aggressive and really unpredictable.

**Comment by pkishino** [comment]
well..back when I created the bot, forms was just in beta..i requested access several times but no response.. I know what the are and really want them..
@haugene can you please check if this is enabled yet for this repo and if so, please enable? or give me access? I will create the form then

**Comment by pkishino** [comment]
Ah, I see that they should be enabled for all public ones..so let me create one then.

**Comment by reconman** [comment]
I would remove the title default value, you can only report bugs now and you can still filter by the Bug label.
