### ISSUE TITLE
Mulvad issue seen with latest docker image

### ISSUE THREAD

**Issue by attzonko** [haugene/docker-transmission-openvpn#1939]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [x] I have tried using dev branch

### Config used

  transmission:
    # TransmissionBT - Torrent Downloader
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    healthcheck:
      disable: true
    networks:
      - t2_proxy
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
      - no-new-privileges:true
    ports:
      - "$TRANSMISSION_PORT:9091"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/transmission/data:/data
      - $DOCKERDIR/transmission/config:/config
      - $USERDIR/downloads:/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      OPENVPN_PROVIDER: MULLVAD
      OPENVPN_USERNAME: $MULLVAD_ACCOUNT
      OPENVPN_PASSWORD: m
      OPENVPN_CONFIG: ca_all
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60

      LOCAL_NETWORK: "$LOCAL_NETWORK"
      ENABLE_UFW: 'true'

      TRANSMISSION_PEER_PORT_RANDOM_ON_START: 'false'
      TRANSMISSION_PEER_PORT: $MULLVAD_PORT
      TRANSMISSION_RATIO_LIMIT: 0
      TRANSMISSION_RATIO_LIMIT_ENABLED: 'true'
      TRANSMISSION_ENCRYPTION: 2
      TRANSMISSION_UTP_ENABLED: 'false'
      TRANSMISSION_PEER_LIMIT_GLOBAL: 1000
      TRANSMISSION_PEER_LIMIT_PER_TORRENT: 100
      TRANSMISSION_RPC_WHITELIST_ENABLED: 'false'
      TRANSMISSION_RPC_HOST_WHITELIST_ENABLED: 'false'
      TRANSMISSION_UMASK: 2
      TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: 'true'
      TRANSMISSION_WATCH_DIR: /downloads
      TRANSMISSION_WATCH_DIR_ENABLED: 'true'
      TRANSMISSION_DOWNLOAD_DIR: /downloads/completed

      OVERRIDE_DNS_1: 1.1.1.1
      OVERRIDE_DNS_2: 8.8.8.8

    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.transmission-rtr.entrypoints=https"
      - "traefik.http.routers.transmission-rtr.rule=HostHeader(`trans.$DOMAINNAME`)"
      - "traefik.http.routers.transmission-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.transmission-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.transmission-rtr.service=transmission-svc"
      - "traefik.http.services.transmission-svc.loadbalancer.server.port=9091"
      - "traefik.docker.network=t2_proxy"

### Current Behavior

Seems the path to the mulvad ca.crt is broken.

### Expected Behavior

I believe the path should not be repeated (see log message)

### How have you tried to solve the problem?

Going to a previous docker image with tag 3.7.1 works as expected.

### Log output

Options error: --ca fails with '/etc/openvpn/mullvad//etc/openvpn/mullvad/ca.crt': No such file or directory (errno=2)

### Environment

```markdown
- OS: Ubuntu 20.04.2 LTS
- Docker: Docker version 20.10.7, build f0df350
```

**Comment by pkishino** [comment]
can you please check latest release again, @haugene fixed this I believe

**Comment by attzonko** [comment]
@pkishino thanks for the quick response. Indeed seems fixed in dev.

**Comment by haugene** [comment]
Yeah, I broke it and fixed it again. So actually the reason it worked in dev right now is not because it has the latest fix, but it is the version before I broke it. Just merged master -> dev so that the branches are now in sync and both have the latest fix for the ca cert stuff.
