### ISSUE TITLE
Issue with sharing server - Linux Mint 18.1

### ISSUE THREAD

**Issue by McJono** [haugene/docker-transmission-openvpn#194]
I honestly can't see what I'm doing wrong (Docker noob so sorry if this is obvious). I have both tried it through a Nginx container and using local_network variable and neither have had any success with allowing me to access the web URL. No matter what I seem to do it hasn't been sharing (I've been trying for 3 days so far -_- )

Attempting to access via localhost - 
jono@NAS ~ $ curl localhost:9091
curl: (56) Recv failure: Connection reset by peer

Attempting to access the ip will hang before timing out -
jono@NAS ~ $ curl 10.1.1.186:9091
curl: (7) Failed to connect to 10.1.1.186 port 9091: Connection timed out

Current init code:-
`sudo docker run --name openvpntrans --privileged -v /mnt/Backup/ToMove/:/data/completed -v /mnt/Backup/Incomplete:/data/incomplete -v /etc/localtime:/etc/localtime:ro --env-file /home/jono/.docker/transmission-enviro -p 9091:9091 haugene/transmission-openvpn`

Current Transmission config:- 
[transmission-enviro.txt](https://github.com/haugene/docker-transmission-openvpn/files/737535/transmission-enviro.txt)

Current log file:-
[openvpntrans.log.txt](https://github.com/haugene/docker-transmission-openvpn/files/737534/openvpntrans.log.txt)

**Comment by sl0n** [comment]
I've noticed one thing in the openvpntrans.log.txt (2nd line from the top):

Supplied config NETHERLANDS.ovpn could not be found.

I can see later on it actually picks up something, however it might be a wrong default conf file or so.

**Comment by McJono** [comment]
Unfortunately, that suggestion was a no go :(
Even with the supplied config file, it doesn't seem to allow access to it. I shall attempt to run a reverse proxy again when I get the time but so far, no cigar :(

**Comment by sl0n** [comment]
Actual problem occurs here:

Sun Jan 29 23:00:49 2017 event_wait : Interrupted system call (code=4)

Quickly googling it reveals that you are not alone with this problem, however most of those issues are not resolved ..

**Comment by McJono** [comment]
After looking into it I find it is still confusing me as the program and docker itself runs (Tested by using the watch list and downloading my shows that way) however I still can't find the reasoning behind the proxy to my network not working still.

Also, you are looking way too low. That event_wait code 4 is when someone hits ctrl + c.

**Comment by haugene** [comment]
Closing this as it is an old issue. The proxy solution should still work, or try using the LOCAL_NETWORK variable described in the readme.

Re-open or create a new issue if it's still a problem
