### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by Lester702** [haugene/docker-transmission-openvpn#1948]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

docker run --cap-add=NET_ADMIN -d \
              -v /your/storage/path/:/data \
              -e OPENVPN_PROVIDER=PIA \
              -e OPENVPN_CONFIG=us_chicago \
              -e OPENVPN_USERNAME= \
              -e OPENVPN_PASSWORD= \
              -e LOCAL_NETWORK=192.168.0.0/16 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn

### Current Behavior

I do not have any sort of network access in the container
When I logged into the container and tried to ping google nothing happened

### Expected Behavior

There should be a valid internet connection in the container

### How have you tried to solve the problem?

Tried the latest release branch
Changing config
I am new to docker so I'm not 100% sure on everything I am doing

### Log output

STARTING TRANSMISSION
Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=true
Transmission startup script complete.
Tue Sep 14 01:44:18 2021 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
Tue Sep 14 01:44:18 2021 Initialization Sequence Completed
Running functions for token based port fowarding
curl: (28) Resolving timed out after 15000 milliseconds
curl: (7) Failed to connect to 10.31.112.1 port 19999: Connection refused
Tue Sep 14 01:45:03 UTC 2021: getSignature error

the has been a fatal_error
curl: (7) Failed to connect to 10.31.112.1 port 19999: Connection refused
Tue Sep 14 01:45:04 UTC 2021: bindPort error

the has been a fatal_error
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
ID     Done       Have  ETA           Up    Down  Ratio  Status       Name
Sum:              None               0.0     0.0
setting transmission port to
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 0: No Response
#######################
        SUCCESS
#######################
Port:
Expiration Tue Sep 14 00:00:00 UTC 2021
#######################
Entering infinite while loop
Every 15 minutes, check port status
60 day port reservation reached
Getting a new one
curl: (28) Resolving timed out after 15000 milliseconds
curl: (7) Failed to connect to 10.31.112.1 port 19999: Connection refused
Tue Sep 14 01:46:34 UTC 2021: getSignature error

the has been a fatal_error
curl: (7) Failed to connect to 10.31.112.1 port 19999: Connection refused
Tue Sep 14 01:46:35 UTC 2021: bindPort error

the has been a fatal_error
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
ID     Done       Have  ETA           Up    Down  Ratio  Status       Name
Sum:              None               0.0     0.0
setting transmission port to
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 0: No Response

### Environment

```markdown
- OS: Ubuntu 20.04 LTS
- Docker: 20.10.8
```

**Comment by pkishino** [comment]
Not complete logs.. missing the whole first part about establishing the vpn tunnel.. also, please search and read through other issues regarding connection failed etc, most likely dns related. 
if you have questions about config and such prewar use the discussion area. Issues is for proper bugs/problems

**Comment by MartinHotmann** [comment]
Suddenly got the ver same error. Just sayin
