### ISSUE TITLE
Transmission downloads again previously deleted files at restart.

### ISSUE THREAD

**Issue by arkansis** [haugene/docker-transmission-openvpn#1955]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

custom hand made NAS server with Open Media Vault with Docker plugin
 haugene /docker-transmission-openvpn version is latest ghcr.io/linuxserver/jellyfin:latest

### Current Behavior

I have a problem with transmission. I have deleted several downloaded files and each time transmission is restarted, transmission downloads again the previously deleted files.
I remove files with transmission interface "Trash Data and Remove From List" option.

This problem appeared with the stable 4.0 version.

### Expected Behavior

I'm waiting for transmission to no longer redownload files already deleted before.

### How have you tried to solve the problem?

I search same issue on Internet.

### Log output

No log file for this issue

### Environment

```markdown
- OS:OMV last stable version
- Docker:5:20.10.8~3-0~debian-buster
```

**Comment by pkishino** [comment]
Please use search.. this has been discussed in the 4.0 release abs a separate discussion
