### ISSUE TITLE
Question regarding disconnects

### ISSUE THREAD

**Issue by dcrdev** [haugene/docker-transmission-openvpn#196]
Hi, I was wondering if someone could answer me a few questions regarding this container? Firstly let me say thanks very much for creating this in the first place - very well laid out!

I noticed that there's no mention of any kind of kill switch implemented in this container, other than setting these OpenVPN options "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" . I can't see anywhere within the repository any addition of iptables rules forcing traffic through the VPN. 

Based on the above assumptions surely there is one scenario where your going to remain indefinitely exposed? The "--ping-exit 60" is going to cause the container to exit every 60 seconds of not being able to establish a VPN connection, most likely you've configured the container to restart on failure either via systemd or docker, surely the container in that situation would stay up in a continuous start/stop loop indefinitely even if the VPN server is completely down.

Thanks

**Comment by haugene** [comment]
Hey, and thanks :)

There is a plan regarding disconnects, but I'd love to hear your inputs on it.
Openvpn will add iptables rules when it starts and that will force all traffic through the interface. So the assumption is that as long as the tun interface is up, traffic will be routed to the VPN server (even if it's not responding).

If and when a connection fails, the tun interface might go down. Starting and stopping transmission is hooked to openvpn by [adding them as up/down scripts](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L47). When the tun interface goes down, transmission is killed.

For the second part, I guess you're right. If the VPN server is down the container will start, fail to connect, then die and get restarted if you've set the "restart=always" flag. Adding this could be a nice feature, but as of now the container just dies and the restart is handled outside it. Docker doesn't have a restart-policy that includes a limit on retries if it fails within x second, which is probably what we're looking for here?

**Comment by nicbou** [comment]
This is a critical feature to some users, as a leaked IP can bring some hefty fines. It's important that everyone fully understands if a kill switch is present or not. For the sake of clarity, **is there currently a kill switch implemented or not?** Can a fresh build of this image somehow leak the user's IP? If so, how can it be prevented?

Please pardon the redundancy of this question. There are hefty fines associated with torrenting in my country of residence, so I want to make sure I fully understand your answer.

**Comment by CreamyCookie** [comment]
@haugene  I'd also be interested in this. Is there any way that this could leak your IP address?

**Comment by haugene** [comment]
I tried describing this in my previous post. Yes, there is a killswitch implemented that will kill transmission if the VPN tunnel goes down.

The whole reason for this Docker image is of course to avoid IP leaks and make sure that Transmission traffic is only routed through the VPN tunnel. We have several scripts trying to make this configuration as robust as possible.

There will always be a chance of leaking the IP but I don't see how as of now. And if anyone did, there would probably be an issue created for this. Security is a high priority and I think several contributors have improved this over the years.

If you have a concrete question or a point where you think the IP can be leaked from, let me know, create an issue. But I'm closing this for now as this is something we're constantly focusing on.

**Comment by nicbou** [comment]
That's actually precisely the answer I was looking for, a plain English answer for us dumb folks. Thank you, I really appreciate it!
