### ISSUE TITLE
Can't tell if the docker is tunneling my traffic to my VPN

### ISSUE THREAD

**Issue by Delvien** [haugene/docker-transmission-openvpn#197]

**Comment by tscibilia** [comment]
Try using the test torrent on this website for proof http://test.torrentprivacy.com/

**Comment by tsuyoi** [comment]
Also, on Linux (or macOS via Homebrew) you can install `iftop` (requires `sudo` access because it views interface data).  You can view inbound and outbound traffic usage. Limit usage outside of the container to check and see if your traffic is mostly going to the VPN address.

**Comment by haugene** [comment]
If you're on a desktop station you can use wireshark as well, and their tshark tool can be used for servers.

Several ways to monitor your traffic has been proposed, closing this issue. Re-open if necessary.
