### ISSUE TITLE
VPN PIA Private Internet Access - Netherlands gives me ip of UK

### ISSUE THREAD

**Issue by Danielvr** [haugene/docker-transmission-openvpn#199]
VPN PIA with country Netherlands gives me UK ip address.

Using these settings

        - OPENVPN_PROVIDER=PIA
        - OPENVPN_CONFIG=Netherlands
        - OPENVPN_USERNAME=***
        - OPENVPN_PASSWORD=****

When I chose Sweden I get an Estonia one.

**Comment by Delvien** [comment]
How do you even check the IP that its using

**Comment by Danielvr** [comment]
By checking my docker-compose logs or by entering the container in bash and use command

curl ipinfo.io/ip

**Comment by Delvien** [comment]
awesome, thank you

**Comment by haugene** [comment]
Can't seem to reproduce this one. When connecting to Netherlands I get an IP from there. Re-open if the problem persists. If so, please provide run command and logs from the container.
