### ISSUE TITLE
Won't Connect to Tracker

### ISSUE THREAD

**Issue by fc0712** [haugene/docker-transmission-openvpn#200]
I get the following error in Transmission: Downloading Ubuntu:

http://torrent.ubuntu.com:6969
Announce error: Could not connect to tracker - Today 03:59:34 PM
Next announce in 1 hour, 3 minutes
Scrape error: Could not connect to tracker - Today 04:01:10 PM

I'm using PIA as my VPN

<img width="637" alt="screen shot 2017-02-02 at 15 02 45" src="https://cloud.githubusercontent.com/assets/25506722/22552316/b3e9e5c0-e958-11e6-86b6-320c6f8a829c.png">

Can you guys see anything wrong?

I'm running windows 10 Pro as my host system with Docker + Kitematic

**Comment by haugene** [comment]
One hint is that curl is returning error no 6. [According to this](https://curl.haxx.se/libcurl/c/libcurl-errors.html) that means CURLE_COULDNT_RESOLVE_HOST. Which probably means that you have DNS issues. Try the fix described in [the readme](https://github.com/haugene/docker-transmission-openvpn#use-google-dns-servers)

**Comment by haugene** [comment]
Assuming the fix worked, re-open if not.
