### ISSUE TITLE
Synology Docker issues, made worse by noob level knowledge.

### ISSUE THREAD

**Issue by Thebroughfamily** [haugene/docker-transmission-openvpn#2001]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

`        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "OPENVPN_USERNAME=REMOVED",
            "OPENVPN_PASSWORD=REMOVED",
            "OPENVPN_PROVIDER=TORGUARD",
            "GLOBAL_APPLY_PERMISSIONS=true",
            "TRANSMISSION_HOME=/data/transmission-home",
            "TRANSMISSION_RPC_PORT=9091",
            "TRANSMISSION_DOWNLOAD_DIR=/data/completed",
            "TRANSMISSION_INCOMPLETE_DIR=/data/incomplete",
            "TRANSMISSION_WATCH_DIR=/data/watch",
            "CREATE_TUN_DEVICE=true",
            "ENABLE_UFW=false",
            "UFW_ALLOW_GW_NET=false",
            "UFW_EXTRA_PORTS=",
            "UFW_DISABLE_IPTABLES_REJECT=false",
            "PUID=",
            "PGID=",
            "PEER_DNS=true",
            "PEER_DNS_PIN_ROUTES=true",
            "DROP_DEFAULT_ROUTE=",
            "WEBPROXY_ENABLED=false",
            "WEBPROXY_PORT=8118",
            "WEBPROXY_USERNAME=",
            "WEBPROXY_PASSWORD=",
            "LOG_TO_STDOUT=false",
            "HEALTH_CHECK_HOST=google.com",
            "SELFHEAL=false",
            "REVISION=ae45b1f22178ddee089d9ea10d4732dbde2d8ef2",
            "OPENVPN_CONFIG=Switzerland",
            "TRANSMISSION_WEB_UI=transmission-web-control",
            "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"

### Current Behavior

Unable to get new transmission install working. Only added a few basic changes to config listed above. Very much new to docker so i do apologise for not knowing anything, its a step curve.

Followed a recent issue, where it was reported to wipe the container and rebuild with only the /data folder mapped in so thats what ive done. Ive got portainer installed now incase thats useful but it looks mighty complicated for me.

### Expected Behavior

For the container to start up and work.

### How have you tried to solve the problem?

Tried a fresh build.
Tried previous release build.
Tried stock settings with only user name and password added.
Tried specifying a location instead of default.

### Log output

Starting container with revision: ae45b1f22178ddee089d9ea10d4732dbde2d8ef2
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: TORGUARD
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for TORGUARD. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.3B3kOVDFKk
Extracting configs to /tmp/tmp.ayidJKNHWu
Found configs for TORGUARD in /tmp/tmp.ayidJKNHWu/vpn-configs-contrib-main/openvpn/torguard, will replace current content in /etc/openvpn/torguard
Cleanup: deleting /tmp/tmp.3B3kOVDFKk and /tmp/tmp.ayidJKNHWu
Starting OpenVPN using config Switzerland.ovpn
Modifying /etc/openvpn/torguard/Switzerland.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Setting OpenVPN credentials...
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/torguard/Switzerland.ovpn

### Environment

```markdown
- OS: Synology ds920
- Docker:
```

**Comment by midnightmercenary** [comment]
So I've implemented the DSM 7 workaround and the container is no longer stopping-restarting. However, I can't access the web GUI. "This page isnt working."

```
Starting container with revision: 6922dd6b112d63e099b98165d7cadeaf411b7800
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: CUSTOM
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for CUSTOM. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.zF5wSujHBY
Extracting configs to /tmp/tmp.vlLxWyE88E
ERROR: Could not find any configs for provider CUSTOM in downloaded configs
Cleanup: deleting /tmp/tmp.zF5wSujHBY and /tmp/tmp.vlLxWyE88E
No VPN configuration provided. Using default.
Modifying /etc/openvpn/custom/default.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
sed: cannot rename /etc/openvpn/custom/sedLNOl0h: Device or resource busy
Modification: Change ca certificate path
sed: cannot rename /etc/openvpn/custom/sedf1pOUq: Device or resource busy
Modification: Change ping options
sed: cannot rename /etc/openvpn/custom/sedZnUEBv: Device or resource busy
sed: cannot rename /etc/openvpn/custom/sedYbN1DA: Device or resource busy
sed: cannot rename /etc/openvpn/custom/sedTCnE4I: Device or resource busy
sed: cannot rename /etc/openvpn/custom/sedQrsgtN: Device or resource busy
Modification: Update/set resolv-retry to 15 seconds
sed: cannot rename /etc/openvpn/custom/sedFQqpXO: Device or resource busy
sed: cannot rename /etc/openvpn/custom/sedEZbjqV: Device or resource busy
Modification: Change tls-crypt keyfile path
sed: cannot rename /etc/openvpn/custom/sedfNO005: Device or resource busy
Modification: Set output verbosity to 3
sed: cannot rename /etc/openvpn/custom/sedywctfa: Device or resource busy
sed: cannot rename /etc/openvpn/custom/sedSq5Yme: Device or resource busy
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
sed: cannot rename /etc/openvpn/custom/sed1ewQLi: Device or resource busy
sed: cannot rename /etc/openvpn/custom/sedRhvSQo: Device or resource busy
Setting OpenVPN credentials...
Wed Nov  3 01:40:34 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Wed Nov  3 01:40:34 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
```

**Comment by pkishino** [comment]
Look at the log, still permission problems caused by DSM.. most likely Tunnel Isn’t even up hence no transmission started

**Comment by midnightmercenary** [comment]
Now it's stopping and restarting again after removing **read-only** from resolv.conf file. I was using [this guide](https://www.lejimmy.com/setting-up-transmission-bittorrent-with-openvpn-on-a-synology-nas-and-docker/) as reference. I also followed this instruction on [using local single .ovpn file from provider](https://github.com/haugene/docker-transmission-openvpn/blob/master/docs/supported-providers.md#using-a-local-single-ovpn-file-from-provider) (PerfectPrivacy).

Now my log is:

```
Starting container with revision: 6922dd6b112d63e099b98165d7cadeaf411b7800
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: CUSTOM
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for CUSTOM. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.H83gGiHnIM
./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable
```

**Comment by pkishino** [comment]
We try to provide documentation that works and is up to date.. external guides have time and time again been outdated and cause all kinds if issues..

@haugene  both QNAP and synology are doing various modifications and such to their docker use, causing annoying issues that should be directed towards them and not this container.. starting to feel we should put a disclaimer stating these two platforms have problems and users are urged to avoid and/or raise the problems with the platform provider instead..

**Comment by pkishino** [comment]
You shouldn’t have to mount resolv.conf at all if docker is setup properly..

**Comment by pkishino** [comment]
Again it looks like a permissions problem for synology due to /tmp not being writable I guess.. sigh..
