### ISSUE TITLE
Implement New PIA Private Internet Access port forwarding API

### ISSUE THREAD

**Issue by jakelee8** [haugene/docker-transmission-openvpn#201]
No longer needs to update port forwarding every hour. Previous API will be removed in the future.

https://www.privateinternetaccess.com/forum/discussion/23431/new-pia-port-forwarding-api

**Comment by haugene** [comment]
This is now merged to dev and is available with the dev tag. Gonna test it and bundle another change, then I'll merge it to master.

**Comment by MindTooth** [comment]
Needed to run `dev` to make PIA work.  So a welcoming change on `master` :-)

**Comment by haugene** [comment]
Merged ;)
