### ISSUE TITLE
Transmission not picking up download directory and re-verifying after restart

### ISSUE THREAD

**Issue by nervling** [haugene/docker-transmission-openvpn#2039]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='transmission_vpn_btn' --net='br0' --ip='192.168.86.29' --cpuset-cpus='11,27' --privileged=true -e TZ="America/Denver" -e HOST_OS="Unraid" -e 'TCP_PORT_9091'='9091' -e 'OPENVPN_USERNAME'='<redacted>' -e 'OPENVPN_PASSWORD'='<redacted>' -e 'OPENVPN_CONFIG'='ca_toronto' -e 'OPENVPN_PROVIDER'='PIA' -e 'UDP_PORT_1198'='1198' -e 'LOCAL_NETWORK'='192.168.86.0/32' -e 'TRANSMISSION_RPC_USERNAME'='<redacted>' -e 'TRANSMISSION_RPC_PASSWORD'='<redacted>' -e 'OPENVPN_OPTS'='--inactive 3600 --ping 10 --ping-exit 60' -e 'PUID'='99' -e 'PGID'='100' -e 'TRANSMISSION_DOWNLOAD_DIR'='/downloads' -e 'TRANSMISSION_RPC_AUTHENTICATION_REQUIRED'='false' -e 'TRANSMISSION_RATIO_LIMIT'='1.1' -e 'TRANSMISSION_RATIO_LIMIT_ENABLED'='false' -e 'TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED'='true' -e 'TRANSMISSION_SPEED_LIMIT_DOWN'='10000' -e 'TRANSMISSION_ALT_SPEED_TIME_BEGIN'='360' -e 'TRANSMISSION_ALT_SPEED_TIME_END'='720' -e 'TRANSMISSION_ALT_SPEED_DOWN'='20000' -e 'TRANSMISSION_SPEED_LIMIT_UP'='10000' -e 'TRANSMISSION_SPEED_LIMIT_UP_ENABLED'='true' -e 'TRANSMISSION_ALT_SPEED_UP'='20000' -e 'TRANSMISSION_DOWNLOAD_QUEUE_SIZE'='15' -e 'TRANSMISSION_CACHE_SIZE_MB'='11' -e 'TRANSMISSION_INCOMPLETE_DIR'='/downloads/incomplete' -e 'TRANSMISSION_WEB_UI'='transmission-web-control' -e 'GLOBAL_APPLY_PERMISSIONS'='false' -e 'WEBPROXY_ENABLED'='false' -e 'PIA_OPENVPN_CONFIG_BUNDLE'='openvpn-tcp' -v '/mnt/user/appdata/Transmission_VPN_BTN/':'/data':'rw' -v '/mnt/user/Torrents/TransmissionBTN/downloads':'/downloads':'rw' -v '/mnt/user/appdata/Transmission_VPN_BTN/watch':'/watch':'rw' -v '/mnt/user/Torrents/TransmissionBTN/incomplete':'/data/incomplete':'rw' -v '/mnt/user/T_Media/Torrent/':'/mnt/user/T_Media/Torrent/':'rw' -v '/mnt/user/appdata/Transmission_VPN_BTN':'/config':'rw' --restart=always --log-opt max-size=50m --log-opt max-file=1 'haugene/transmission-openvpn'
920d59717cf7d6f99415aceed6280bbb43af42b3f5bbedd44fdd68c906dbd77e

### Current Behavior

Each time I restart the docker, all of the download directories are set back to the default for every torrent(/downloads), this appears to cause everything to re-verify and download in the wrong directory.

### Expected Behavior

Find the updated download locations (/download/complete) and avoid re-verification.

### How have you tried to solve the problem?

I updated everything and let them all complete verification and then restart. Same behavior.

### Log output

Starting container with revision: 6922dd6b112d63e099b98165d7cadeaf411b7800
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Running with VPN_CONFIG_SOURCE auto
Provider PIA has a bundled setup script. Defaulting to internal config
Executing setup script for PIA
Downloading OpenVPN config bundle openvpn-tcp into temporary file /tmp/tmp.GgRX34aRLJ
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Starting OpenVPN using config ca_toronto.ovpn
Modifying /etc/openvpn/pia/ca_toronto.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Setting OpenVPN credentials...
adding route to local network 192.168.86.0/32 via 192.168.86.1 dev eth0
Thu Oct 28 10:15:44 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Thu Oct 28 10:15:44 2021 library versions: OpenSSL 1.1.1f 31 Mar 2020, LZO 2.10
Thu Oct 28 10:15:44 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Oct 28 10:15:44 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]154.3.40.122:502
Thu Oct 28 10:15:44 2021 Socket Buffers: R=[87380->87380] S=[65536->65536]
Thu Oct 28 10:15:44 2021 Attempting to establish TCP connection with [AF_INET]154.3.40.122:502 [nonblock]
Thu Oct 28 10:15:45 2021 TCP connection established with [AF_INET]154.3.40.122:502
Thu Oct 28 10:15:45 2021 TCP_CLIENT link local: (not bound)
Thu Oct 28 10:15:45 2021 TCP_CLIENT link remote: [AF_INET]154.3.40.122:502
Thu Oct 28 10:15:45 2021 TLS: Initial packet from [AF_INET]154.3.40.122:502, sid=c0b4954b 5848510b
Thu Oct 28 10:15:45 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Thu Oct 28 10:15:45 2021 VERIFY OK: depth=1, C=US, ST=CA, L=LosAngeles, O=Private Internet Access, OU=Private Internet Access, CN=Private Internet Access, name=Private Internet Access, emailAddress=secure@privateinternetaccess.com
Thu Oct 28 10:15:45 2021 VERIFY KU OK
Thu Oct 28 10:15:45 2021 Validating certificate extended key usage
Thu Oct 28 10:15:45 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Oct 28 10:15:45 2021 VERIFY EKU OK
Thu Oct 28 10:15:45 2021 VERIFY OK: depth=0, C=US, ST=CA, L=LosAngeles, O=Private Internet Access, OU=Private Internet Access, CN=toronto417, name=toronto417
Thu Oct 28 10:15:46 2021 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA
Thu Oct 28 10:15:46 2021 [toronto417] Peer Connection Initiated with [AF_INET]154.3.40.122:502
Thu Oct 28 10:15:47 2021 SENT CONTROL [toronto417]: 'PUSH_REQUEST' (status=1)
Thu Oct 28 10:15:47 2021 PUSH: Received control message: 'PUSH_REPLY,comp-lzo no,redirect-gateway def1,route-ipv6 2000::/3,dhcp-option DNS 10.0.0.243,route-gateway 10.28.111.1,topology subnet,ping 10,ping-restart 60,ifconfig 10.28.111.21 255.255.255.0,peer-id 0,cipher AES-128-GCM'
Thu Oct 28 10:15:47 2021 OPTIONS IMPORT: timers and/or timeouts modified
Thu Oct 28 10:15:47 2021 OPTIONS IMPORT: compression parms modified
Thu Oct 28 10:15:47 2021 OPTIONS IMPORT: --ifconfig/up options modified
Thu Oct 28 10:15:47 2021 OPTIONS IMPORT: route options modified
Thu Oct 28 10:15:47 2021 OPTIONS IMPORT: route-related options modified
Thu Oct 28 10:15:47 2021 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Thu Oct 28 10:15:47 2021 OPTIONS IMPORT: peer-id set
Thu Oct 28 10:15:47 2021 OPTIONS IMPORT: adjusting link_mtu to 1627
Thu Oct 28 10:15:47 2021 OPTIONS IMPORT: data channel crypto options modified
Thu Oct 28 10:15:47 2021 Data Channel: using negotiated cipher 'AES-128-GCM'
Thu Oct 28 10:15:47 2021 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Thu Oct 28 10:15:47 2021 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Thu Oct 28 10:15:47 2021 ROUTE_GATEWAY 192.168.86.1/255.255.255.0 IFACE=eth0 HWADDR=02:42:c0:a8:56:1d
Thu Oct 28 10:15:47 2021 GDG6: remote_host_ipv6=n/a
Thu Oct 28 10:15:47 2021 ROUTE6: default_gateway=UNDEF
Thu Oct 28 10:15:47 2021 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
Thu Oct 28 10:15:47 2021 OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3

Thu Oct 28 10:15:47 2021 TUN/TAP device tun0 opened
Thu Oct 28 10:15:47 2021 TUN/TAP TX queue length set to 100
Thu Oct 28 10:15:47 2021 /sbin/ip link set dev tun0 up mtu 1500
Thu Oct 28 10:15:47 2021 /sbin/ip addr add dev tun0 10.28.111.21/24 broadcast 10.28.111.255
Thu Oct 28 10:15:47 2021 /etc/openvpn/tunnelUp.sh tun0 1500 1555 10.28.111.21 255.255.255.0 init
Up script executed with tun0 1500 1555 10.28.111.21 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.28.111.21
Using Transmission Web Control UI, overriding TRANSMISSION_WEB_HOME
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding alt-speed-down because TRANSMISSION_ALT_SPEED_DOWN is set to 20000
Overriding alt-speed-time-begin because TRANSMISSION_ALT_SPEED_TIME_BEGIN is set to 360
Overriding alt-speed-time-end because TRANSMISSION_ALT_SPEED_TIME_END is set to 720
Overriding alt-speed-up because TRANSMISSION_ALT_SPEED_UP is set to 20000
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.28.111.21
Overriding cache-size-mb because TRANSMISSION_CACHE_SIZE_MB is set to 11
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /downloads
Overriding download-queue-size because TRANSMISSION_DOWNLOAD_QUEUE_SIZE is set to 15
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /downloads/incomplete
Overriding ratio-limit because TRANSMISSION_RATIO_LIMIT is set to 1.1
Overriding ratio-limit-enabled because TRANSMISSION_RATIO_LIMIT_ENABLED is set to false
Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to false
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to kyle
Overriding speed-limit-down because TRANSMISSION_SPEED_LIMIT_DOWN is set to 10000
Overriding speed-limit-down-enabled because TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED is set to true
Overriding speed-limit-up because TRANSMISSION_SPEED_LIMIT_UP is set to 10000
Overriding speed-limit-up-enabled because TRANSMISSION_SPEED_LIMIT_UP_ENABLED is set to true
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories

### Environment

```markdown
- OS: Unraid 6.9.2
- Docker: 20.10.5
```

### Anything else?

Note this started after I updated after some ~6 month period. My auto updates were broken and I didn't notice, so that may be related.

**Comment by rynoweiss** [comment]
Having the same issue as a couple weeks ago.

**Comment by nervling** [comment]
I believe this is related to the transmission 4.0 upgrade, the fix appears to be [this](https://github.com/haugene/docker-transmission-openvpn/discussions/1936#discussioncomment-1283809). Basically, I copied all of my `transmission-home/torrents` locally, fully deleted my config directory, restarted and re-added all my torrents. They all had to re-verify but once verified it persists through a reboot.

Some other things I did:
- Set the option in docker to change folder permissions. Not sure if that's required but it seemed to half fix things so I didn't undo it
- My files were spread across multiple directories, so I used the "change download location" in the transmission UI to move everything from location 1 to location 2, then back to location 1 so everything ended up in location 1. Then I could easily add all the torrents and set them to download in location 1.

This is quite a lot of pain to go through that doesn't seem to be well documented as far as I can see it, but at least I got things working again. I'm going to mark this closed, since it seems this is a known issue.

**Comment by theRealKLH** [comment]
this just happened to me. After 6+ months of no updates "because"... My torrents are in different directories mounted as subdirs of "/data". Only the ones that exist in "/data/completed" are verifying the other 1500+ torrents began redownloading. wiped out my drive before I realized what was going on. One.. remotegui took a long time to connect. Two.. I kept taking a double take at the version. not realizing you guys dropped from 3 back to 2.94.

**Comment by pkishino** [comment]
There’s a reason release notes exist..

**Comment by nervling** [comment]
Is that supposed to justify a breaking change like this? I'm not going to complain because I appreciate the great free software you folks provide, but saying "we can break you rather horribly because it's in patch notes" is a bad look imo. Many of us use auto update, and it would be one thing if downloads broke, but this was far from worse for the reasons provided above.

Anyways, thanks for the great software. Maybe I misinterpreted what you said, but if not, maybe try a bit more empathy for your users. I certainly try to in the software I build for a living.

**Comment by pkishino** [comment]
We had good reasons to go with the downgrade, we have provided a work
around to use 3.0 with 4.0 container version for those who need it and
provided a solution to fix the problem. Sorry, but what more do you want?
I get it,I used to be more heavily involved with writing and releasing
software, even then we would inform customers of any breaking changes,
provide support etc.. and still they complain..
To be honest, using auto upgrade, especially moving between major versions
is pretty silly behaviour.. that’s why we did add it to a major release,
stepping from 3.x to 4.0 and providing a last 3.7.1 release for those who
didn’t want to upgrade.
We can’t and won’t be holding peoples hands with this.. we’ll,I guess we
could introduce support subscriptions and such in the tune of a few $k per
hour, but I don’t feel that’s really the right approach.
Instead we believe users should be responsible with their use..

Just as we expect users to look read release notes, check issues and
discussions and try to contribute so we can and feel like continuing the
project.

Sorry, but in your case it seems like a few other things in your system
setup can and should be addressed to avoid this, first of all not using
auto update(at least between major versions) and second if all disk
management for containers etc..
And yeah, big difference between us providing our time for free (totally
free) and doing things for a living..
if you have suggestions to improve testing, regression testing etc, feel
free to submit a PR.
Until then, if you don’t like how things are in 4.x, revert to an older
version, use the workaround or feel free to use a different container

@haugene any comment?

**Comment by nervling** [comment]
As I said, my only real comment is not to be rude about it. I don't blame you for the way you did things, but when you are being a bit of an elitist IMO.

**Comment by theRealKLH** [comment]
> There’s a reason release notes exist..
> […](#)
I don't see any mention of "BREAKING CHANGE" (OR release notes) on dockerhub (GOOD GOD MAN you don't even mention on the front page of this github about any MAJOR change until AFTER you state "Just started having problems? well guess what we did...). I'm not doing an autoupgrade, but manually pulling the image (yeah so it's "latest", but still) and restarting container... AND FYI.. it just happened to me again after I had to shut down my container. So I'm not even sure what the hell I am missing (thought I read there was a fallback to using /data if defined in environment, so...?).

**Comment by pkishino** [comment]
> There’s a reason release notes exist..
> […](#)
> I don't see any mention of "BREAKING CHANGE" (OR release notes) on dockerhub (GOOD GOD MAN you don't even mention on the front page of this github about any MAJOR change until AFTER you state "Just started having problems? well guess what we did...). I'm not doing an autoupgrade, but manually pulling the image (yeah so it's "latest", but still) and restarting container... AND FYI.. it just happened to me again after I had to shut down my container. So I'm not even sure what the hell I am missing (thought I read there was a fallback to using /data if defined in environment, so...?).

Uhm, release notes are always created and attached to the release
https://github.com/haugene/docker-transmission-openvpn/releases/tag/4.0

**Comment by theRealKLH** [comment]
@pkishino Don't take my comments the wrong way, please... wasn't meaning it as an argument or war type of sitch. Just that, look at it from a "ordinary anonymous internet / github novice (don't know or care about standard GH practice) / blindly (what's this button do?) clicking / just using this because it's cool" user perspective and not a "dev/inet savvy/know better to not use latest tag" road warrior. 

If something like this happened to a production system that users were actually paying support for (and thank you very much for the freebie!) that would  "damn well" better be something on the front page proactively diverting all the "you broke me man!" noise. Otherwise... "Heads be rolling!"

Shit happens... "By the way, BIG change happened. make sure you read, blah blah, prior to any updating" (good PR) vs "Welcome to the issues page, you probably updated without reading tag specific release notes (since you were erroneously using latest) and got broke, ooops... here's the fix/workaround" (bad CS).. GRIN
