### ISSUE TITLE
Docker container fails to launch 

### ISSUE THREAD

**Issue by csayre** [haugene/docker-transmission-openvpn#2049]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/mnt/share:/data'
            - '/mnt/share/node-us-01.protonvpn.net.udp.ovpn:/etc/openvpn/custom/default.ovpn'
            - '/mnt/share/auth.txt:/etc/auth.txt'
        environment:
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=default
            - OPENVPN_USERNAME=username
            - OPENVPN_PASSWORD=pass
            - LOCAL_NETWORK=10.1.10.0/24
            - DNS=4.2.2.2
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '10000:10000'
        image: haugene/transmission-openvpn

### Current Behavior

Docker container launches but then fails. 

### Expected Behavior

Docker container should launch and run. 

### How have you tried to solve the problem?

Changed dns providers (4.2.2.2, 8.8.8.8, 1.1.1.1) 
Downloaded new Ovpn file from protonvpn
Verified DNS config. 
Tried passing creds in through the above settings. 
The cred file that is mounted has 2 lines with linux line breaks. First line user name second line password. 

Added /etc/docker/daemon.json and restarted docker. 

{
    "dns": ["1.1.1.1", "8.8.8.8"]
}

Installed portainer to verify that docker config file is correct and to get logs. That seems to be working well. 

### Log output

/etc/openvpn/start.sh: line 32:    10 Aborted                 (core dumped) nslookup ${HEALTH_CHECK_HOST:-"google.com"} > /dev/null 2>&1

WARNING: initial DNS resolution test failed

Creating TUN device /dev/net/tun

Using OpenVPN provider: CUSTOM

Running with VPN_CONFIG_SOURCE auto

No bundled config script found for CUSTOM. Defaulting to external config

Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.uAjnySbFiF

curl: (28) Timeout was reached

./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable

Starting OpenVPN using config default.ovpn

Modifying /etc/openvpn/custom/default.ovpn for best behaviour in this container

Modification: Point auth-user-pass option to the username/password file

sed: cannot rename /etc/openvpn/custom/sedTQhOHK: Device or resource busy

Modification: Change ca certificate path

sed: cannot rename /etc/openvpn/custom/sed1eM84T: Device or resource busy

Modification: Change ping options

sed: cannot rename /etc/openvpn/custom/sed5q1NLY: Device or resource busy

sed: cannot rename /etc/openvpn/custom/sedBAtcq3: Device or resource busy

sed: cannot rename /etc/openvpn/custom/seddPv887: Device or resource busy

sed: cannot rename /etc/openvpn/custom/sedh1KNPc: Device or resource busy

Modification: Update/set resolv-retry to 15 seconds

sed: cannot rename /etc/openvpn/custom/sedld0swh: Device or resource busy

sed: cannot rename /etc/openvpn/custom/sedppf8cm: Device or resource busy

Modification: Change tls-crypt keyfile path

sed: cannot rename /etc/openvpn/custom/sedxNJsAv: Device or resource busy

Modification: Set output verbosity to 3

sed: cannot rename /etc/openvpn/custom/sed3WbReA: Device or resource busy

sed: cannot rename /etc/openvpn/custom/sedFbeNXE: Device or resource busy

Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop

sed: cannot rename /etc/openvpn/custom/sedJntsEJ: Device or resource busy

sed: cannot rename /etc/openvpn/custom/sedNzI7kO: Device or resource busy

Setting OpenVPN credentials...

Fatal Python error: pyinit_main: can't initialize time

Python runtime state: core initialized

PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6f55460 (most recent call first):

<no Python frame>

adding route to local network 10.1.10.0/24 via 172.20.0.1 dev eth0

Thu Jan  1 00:00:00 1970 WARNING: cannot stat file '/etc/auth.txt': Value too large for defined data type (errno=75)

Thu Jan  1 00:00:00 1970 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021

Thu Jan  1 00:00:00 1970 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10

Thu Jan  1 00:01:04 1970 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts

Tue Aug 19 14:45:22 1980 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

Tue Aug 19 14:45:22 1980 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

Thu Jan  1 00:00:01 1970 TCP/UDP: Preserving recently used remote address: [AF_INET]162.210.192.144:80

Tue Nov 10 18:31:31 1992 Socket Buffers: R=[180224->180224] S=[180224->180224]

Thu Jan  1 00:00:01 1970 UDP link local: (not bound)

Thu Jan  1 00:00:01 1970 UDP link remote: [AF_INET]162.210.192.144:80

Thu Jan  1 00:00:01 1970 Inactivity timeout (--inactive), exiting

Thu Jan  1 00:00:01 1970 SIGTERM[soft,inactive] received, process exiting

### Environment

```markdown
- OS: PI OS 
cat /etc/debian_version
10.11
- Docker: Docker version 20.10.10, build b485636
```

**Comment by csayre** [comment]
Running the next version lower (3.7.1?) gives me this 


```
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712

WARNING: initial DNS resolution test failed

Creating TUN device /dev/net/tun

Using OpenVPN provider: CUSTOM

Starting OpenVPN using config default.ovpn

Setting OpenVPN credentials...

Fatal Python error: pyinit_main: can't initialize time

Python runtime state: core initialized

PermissionError: [Errno 1] Operation not permitted


Current thread 0xb6f7e390 (most recent call first):

<no Python frame>

adding route to local network 10.1.10.0/24 via 172.21.0.1 dev eth0

2071-05-20 18:02:32 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.

2071-05-20 17:59:20 WARNING: file '/etc/auth.txt' is group or others accessible

2071-05-20 18:06:00 OpenVPN 2.5.2 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021

2071-05-20 18:05:36 library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10

2071-05-20 18:02:56 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts

2071-05-20 17:42:08 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

2071-05-20 17:42:08 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

2071-05-20 17:59:28 TCP/UDP: Preserving recently used remote address: [AF_INET]162.210.192.144:4569

2071-05-20 17:58:40 Socket Buffers: R=[180224->180224] S=[180224->180224]

2071-05-20 18:00:48 UDP link local: (not bound)

2071-05-20 18:00:48 UDP link remote: [AF_INET]162.210.192.144:4569

2071-05-20 18:01:12 TLS: Initial packet from [AF_INET]162.210.192.144:4569, sid=f2012246 1551660d

2071-05-20 17:45:44 VERIFY ERROR: depth=2, error=format error in certificate's notBefore field: C=CH, O=ProtonVPN AG, CN=ProtonVPN Root CA, serial=1

2071-05-20 17:58:24 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

2071-05-20 17:58:48 TLS_ERROR: BIO read tls_read_plaintext error

2071-05-20 17:59:20 TLS Error: TLS object -> incoming plaintext read error

2071-05-20 17:59:20 TLS Error: TLS handshake failed

2071-05-20 18:05:28 SIGTERM[soft,tls-error] received, process exiting
```

**Comment by pkishino** [comment]
this is covered in #1726 
problem with arm7 based devices, fix is towards the bottom

also,
this mount does not make sense, not sure where you got that path from.
- '/mnt/share/auth.txt:/etc/auth.txt'

also
ports:
- '10000:10000'

does not make sense, by default transmission uses 9091 if you do not change it (which you have not)

**Comment by csayre** [comment]
Thanks for the help. Sorry I missed that. 

FYI, the file no longer exists on the external link. This is what worked for me. 

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee -a /etc/apt/sources.list.d/buster-backports.list
sudo apt update
sudo apt install -t buster-backports libseccomp2
```

**Comment by csayre** [comment]
I got this resolved. I would highly suggest using portainer to get this up and running. It really makes it easy to manage the config of the system.
