### ISSUE TITLE
Private Internet Access Port Forwarding Not Working?

### ISSUE THREAD

**Issue by coolspot18** [haugene/docker-transmission-openvpn#206]
Hello,

I just loaded the current master version of the docker image, and when I connect to PIA, I can't seem to obtain a port. This is shows up in my logs:

STARTING TRANSMISSION
STARTING PORT UPDATER
Transmission startup script complete.
Mon Feb 20 01:15:57 2017 Initialization Sequence Completed
Generating new client id for PIA
curl encountered an error looking up new port: 35

Could not find new port from PIA

This happens with CA Toronto, CA Montreal, and Netherlands. 

Any ideas - is this a PIA issue or a problem with the port script?

Thanks!

**Comment by coolspot18** [comment]
Looks like an error on my part - my pfSense firewall had a VPN tunnel, so it was double VPNing - this must have caused a problem with the port forwarding service that PIA provides.

Disconnecting the pfSense VPN fixed the issue.

**Comment by dccxxvi** [comment]
this is actually happening to me too but i am not running pfsense and this is happening for PIA NYC
