### ISSUE TITLE
Transmission container exiting with error status: 2

### ISSUE THREAD

**Issue by chrispalka** [haugene/docker-transmission-openvpn#2065]
### Is there a pinned issue for this?

- [x] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

version: "3.8"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - UMASK=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
      - /mnt/movie-store/LMDS/data:/data
    ports:
      - 8989:8989
    restart: always

  radarr:
    image: mdhiggins/radarr-sma
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - UMASK=022 #optional
    volumes:
      - ./volumes/radarr/config:/config
      - /opt/appdata/sma:/usr/local/sma/config
      - /mnt/movie-store/LMDS/data:/data
    ports:
      - 7878:7878
    restart: always

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ./volumes/jackett/config:/config
      - /mnt/movie-store/LMDS/data:/data
    ports:
      - 9117:9117
    restart: always
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/movie-store/LMDS/data/downloads:/data
      - ./vpn:/etc/openvpn/custom/
    environment:
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=myusername
      - OPENVPN_PASSWORD=mypass
      - LOCAL_NETWORK=192.168.0.0/16
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - "9091:9091"
    image: haugene/transmission-openvpn
    restart: always

### Current Behavior

Transmission starts and exits with error status 2.

### Expected Behavior

I expect transmission to launch and resolve via it's correct port.

### How have you tried to solve the problem?

Cleaned container and rebuilt fresh
Re-downloaded and imported fresh default.opvn, ta.key, client.key, client.crt files.
Confirmed user/pass is correct.

### Log output

Starting container with revision: d1ece1c5f36f275d5d950bd2557ec43f79a80d14

Creating TUN device /dev/net/tun

Using OpenVPN provider: CUSTOM

Running with VPN_CONFIG_SOURCE auto

No bundled config script found for CUSTOM. Defaulting to external config

Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.03opLydsxs

Extracting configs to /tmp/tmp.1u4GaWlqP6

ERROR: Could not find any configs for provider CUSTOM in downloaded configs

Cleanup: deleting /tmp/tmp.03opLydsxs and /tmp/tmp.1u4GaWlqP6

No VPN configuration provided. Using default.

Modifying /etc/openvpn/custom/default.ovpn for best behaviour in this container

Modification: Point auth-user-pass option to the username/password file

Modification: Change ca certificate path

Modification: Change ping options

Modification: Update/set resolv-retry to 15 seconds

Modification: Change tls-crypt keyfile path

Modification: Set output verbosity to 3

Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop

Setting OpenVPN credentials...

adding route to local network 192.168.0.0/16 via 172.20.0.1 dev eth0

Mon Nov 15 21:59:27 2021 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6

Mon Nov 15 21:59:27 2021 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021

Mon Nov 15 21:59:27 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10

Mon Nov 15 21:59:27 2021 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.

Mon Nov 15 21:59:27 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts

Mon Nov 15 21:59:27 2021 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

Mon Nov 15 21:59:27 2021 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

Mon Nov 15 21:59:27 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]191.96.206.207:1195

Mon Nov 15 21:59:27 2021 Socket Buffers: R=[180224->360448] S=[180224->360448]

Mon Nov 15 21:59:27 2021 UDP link local: (not bound)

Mon Nov 15 21:59:27 2021 UDP link remote: [AF_INET]191.96.206.207:1195

Mon Nov 15 21:59:27 2021 TLS: Initial packet from [AF_INET]191.96.206.207:1195, sid=48e875c1 83d2a59d

Mon Nov 15 21:59:27 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Mon Nov 15 21:59:27 2021 VERIFY OK: depth=1, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=ExpressVPN CA, emailAddress=support@expressvpn.com

Mon Nov 15 21:59:27 2021 VERIFY OK: nsCertType=SERVER

Mon Nov 15 21:59:27 2021 VERIFY X509NAME OK: C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-10524-0a, emailAddress=support@expressvpn.com

Mon Nov 15 21:59:27 2021 VERIFY OK: depth=0, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-10524-0a, emailAddress=support@expressvpn.com

Mon Nov 15 21:59:27 2021 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA

Mon Nov 15 21:59:27 2021 [Server-10524-0a] Peer Connection Initiated with [AF_INET]191.96.206.207:1195

Mon Nov 15 21:59:28 2021 SENT CONTROL [Server-10524-0a]: 'PUSH_REQUEST' (status=1)

Mon Nov 15 21:59:28 2021 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.139.0.1,comp-lzo no,route 10.139.0.1,topology net30,ping 10,ping-restart 60,ifconfig 10.139.0.62 10.139.0.61,peer-id 14,cipher AES-256-GCM'

Mon Nov 15 21:59:28 2021 OPTIONS IMPORT: timers and/or timeouts modified

Mon Nov 15 21:59:28 2021 OPTIONS IMPORT: compression parms modified

Mon Nov 15 21:59:28 2021 OPTIONS IMPORT: --ifconfig/up options modified

Mon Nov 15 21:59:28 2021 OPTIONS IMPORT: route options modified

Mon Nov 15 21:59:28 2021 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified

Mon Nov 15 21:59:28 2021 OPTIONS IMPORT: peer-id set

Mon Nov 15 21:59:28 2021 OPTIONS IMPORT: adjusting link_mtu to 1629

Mon Nov 15 21:59:28 2021 OPTIONS IMPORT: data channel crypto options modified

Mon Nov 15 21:59:28 2021 Data Channel: using negotiated cipher 'AES-256-GCM'

Mon Nov 15 21:59:28 2021 NCP: overriding user-set keysize with default

Mon Nov 15 21:59:28 2021 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key

Mon Nov 15 21:59:28 2021 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key

Mon Nov 15 21:59:28 2021 ROUTE_GATEWAY 172.20.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:14:00:06

Mon Nov 15 21:59:28 2021 TUN/TAP device tun0 opened

Mon Nov 15 21:59:28 2021 TUN/TAP TX queue length set to 100

Mon Nov 15 21:59:28 2021 /sbin/ip link set dev tun0 up mtu 1500

Mon Nov 15 21:59:28 2021 /sbin/ip addr add dev tun0 local 10.139.0.62 peer 10.139.0.61

Mon Nov 15 21:59:28 2021 /etc/openvpn/tunnelUp.sh tun0 1500 1557 10.139.0.62 10.139.0.61 init

Up script executed with tun0 1500 1557 10.139.0.62 10.139.0.61 init

Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.139.0.62

Updating Transmission settings.json with values from env variables

Using existing settings.json for Transmission /data/transmission-home/settings.json

Traceback (most recent call last):

  File "/etc/transmission/updateSettings.py", line 45, in <module>

    settings_dict = json.load(input_file)

  File "/lib/python3.8/json/__init__.py", line 293, in load

    return loads(fp.read(),

  File "/lib/python3.8/codecs.py", line 322, in decode

    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 141: invalid start byte

Mon Nov 15 21:59:30 2021 /sbin/ip route add 191.96.206.207/32 via 172.20.0.1

Mon Nov 15 21:59:30 2021 /sbin/ip route add 0.0.0.0/1 via 10.139.0.61

Mon Nov 15 21:59:30 2021 /sbin/ip route add 128.0.0.0/1 via 10.139.0.61

Mon Nov 15 21:59:30 2021 /sbin/ip route add 10.139.0.1/32 via 10.139.0.61

RTNETLINK answers: File exists

Mon Nov 15 21:59:30 2021 ERROR: Linux route add command failed: external program exited with error status: 2

Mon Nov 15 21:59:30 2021 Initialization Sequence Completed

### Environment

```markdown
- OS: Linux raspberrypi 5.10.63-v7l+ #1459
- Docker: Docker version 20.10.10, build b485636
```

### Anything else?

First, thanks for building such a great container! It's been working flawlessly for over a year.

I have changed absolutely nothing in regards to my network or config. This just began happening today. 

I'm not a novice when it comes to docker and or openvpn, however I wouldn't say I'm a professional. Any help is much appreciated, please see attached log and I can certainly take direction well with your assistance.

**Comment by rheard** [comment]
Not sure if related: My transmission docker stopped functioning on unRAID. The logs repeat `Unexpected response: <h1>401: Unauthorized</h1>Unauthorized User`

I'm not a docker expert, but after opening a shell I found that the config in `/etc/transmission-daemon/settings.json` had the default settings, not my given settings. Tried changing my settings to be the default, no use. 

Stopped the daemon, updated that config for just no rpc auth for now. Started it again, everything is working fine, though loaded data is missing because I *think* I forgot to provide the -g argument? 

I'm looking at `start.sh` now and I'm going to try that and continue investigating what might be going wrong

**Comment by pkishino** [comment]
both of you, stop the container, then check transmission-home/settings.json file (this should be inside your /data mount folder by default)
check for any strange settings or invalid ones, save then restart the container..
@rheard regarding the unauthorized user.. check your rpc whitelist (if enabled).
This is from the PIA port forwarding script, right?

**Comment by chrispalka** [comment]
Wow thanks @pkishino. I didn't really know what I was looking for so I did a backup of the settings.json, started the container back up and it created a new one, voila.

**Comment by rheard** [comment]
@pkishino Not sure what went wrong, but flashing the settings.json and moving my settings backed worked for me as well, though I'm leaving RPC auth off still

Appears the unRAID GUI is useless and doesn't change that json. Completely forgot about it, thanks!

NOTE: There were a few settings difference, such as `"download-dir":"/cinfig/Downloads"` now as opposed to `"download-dir":"/downloads"` before and UDP has been turned on now
