### ISSUE TITLE
container does not restart

### ISSUE THREAD

**Issue by duncanleo** [haugene/docker-transmission-openvpn#207]
Hi,

first of all - awesome work, the image works very well! However, I've been running into the following issue after having the container run for maybe 1-2 days. This line is repeated many times in the container logs:
`Wed Feb 22 15:32:14 2017 RESOLVE: Cannot resolve host address: swe.torguardvpnaccess.com: Temporary failure in name resolution`

I've started the container with the `OPENVPN_OPTS` environment variable specified in the README as well as the DNS options and the `--restart=always` flag, but they do not seem to fix the issue.

**Comment by fthouraud** [comment]
Hi,

I'm running into the same issue : "Cannot resolve host address: nl-ovpn-udp.pointtoserver.com: Temporary failure in name resolution".
I configured the container with a compose file where  the "OPENVPN_OPTS" environment, the DNS configuration and the "restart: always" option are present as explained in your documentation.

By the way, you did a real great job and I thank you for that !

Your help would be very appreciated.

Thanks in advance.

**Comment by Ashex** [comment]
I got around this by configuring the container to write to a log file then used monit to restart the container whenever this line popped up.

**Comment by MindTooth** [comment]
Can confirm this.  When I access the GUI next day, it says closed, and have not restarted to fix this.

**Comment by sl0n** [comment]
@Ashex dare to share ? =)
I've seen the same thing, resolved it by adding my router's IP as DNS, whoever it leads to as called "DNS leak".

**Comment by Ashex** [comment]
Sure, you first need to have the container configured to use the syslog driver and make sure you tag **and** name it it:
`--name=transmission --log-driver=syslog  --log-opt tag=docker/transmission`

Then add a pattern to rsyslog (which I use) so a log file is written:

```
# /etc/rsyslog.d/10-docker.conf
# Log Docker container logs to file per tag
$FileCreateMode 0644
template(name="DockerLogFileName" type="list") {
   constant(value="/var/log/docker/")
   property(name="syslogtag" securepath="replace" \
            regex.expression="docker/\\(.*\\)\\[" regex.submatch="1")
   constant(value="/docker.log")
}
if $programname == 'docker' then \
  /var/log/docker/combined.log
if $programname == 'docker' then \
  if $syslogtag contains 'docker/' then \
    ?DockerLogFileName
  else
    /var/log/docker/no_tag/docker.log
$FileCreateMode 0600
& stop
```

Then in monit configure the following rule:

```
check file docker.log with path /var/log/docker/transmission/docker.log
  if match "Cannot resolve host address" then exec "/usr/bin/docker restart transmission"
```

**Comment by sl0n** [comment]
@Ashex do you run rsyslog + monit outside of the container?

**Comment by bspinner** [comment]
I've added `--up-restart` to my `OPENVPN_OPTs`, so at least transmission will be killed when `--ping-restart` occurs.

From the docs:

> --up-restart
> Enable the --up and --down scripts to be called for restarts as well as initial program start.
> This option is > described more fully above in the --up option documentation.
>
>Normally the up script is called after the TUN/TAP device is opened. In this context, the last command line parameter passed to the script will be init. If the --up-restart option is also used, the up script will be called for restarts as well. A restart is considered to be a partial reinitialization of OpenVPN where the TUN/TAP instance is preserved (the --persist-tun option will enable such preservation). A restart can be generated by a SIGUSR1 signal, a --ping-restart timeout, or a connection reset when the TCP protocol is enabled with the --proto option. If a restart occurs, and --up-restart has been specified, the up script will be called with restart as the last parameter.

**Comment by maaraneasi** [comment]
Same issue here... I have configured the auto restart but even there is no connectivity and the container can't ping, no restart happens...

**Comment by jdfalk** [comment]
Wouldn't it be a lot easier to use the docker health command and openvpn management interface and just query status? If the status is up then it sleeps, if it's down it checks 3 times and finally restarts the container. Just my $0.02.

**Comment by nicomarti83** [comment]
@jdfalk this is what I do manually when I've got this problem... can we automatize this?

**Comment by jdfalk** [comment]
I run the container a little differently. This requires docker 1.2x. Here are my changes:
```
docker run \
--name transmission \
--device=/dev/net/tun \
--restart=always \
-d \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"
# Capabilities added from the ubuntu systemd openvpn start script.
--cap-add=NET_ADMIN \ 
--cap-add=NET_BIND_SERVICE \
--cap-add=NET_RAW \
--cap-add=SETGID \
--cap-add=SETUID \
--cap-add=SYS_CHROOT \
--cap-add=DAC_READ_SEARCH \
--cap-add=AUDIT_WRITE  \
```
After doing that it started restarting when the vpn dropped. 

As for health checks, here is the docker documentation on it. [https://docs.docker.com/engine/reference/builder/#healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck). 

The plex people use a simple script:
cat healthcheck.sh
```
#!/bin/sh -e

TARGET=localhost
CURL_OPTS="--connect-timeout 15 --silent --show-error --fail"

curl ${CURL_OPTS} "http://${TARGET}:32400/identity" >/dev/null
```
It would probably be better to have a health check that checks if the VPN is up, and that transmission is running. If either fails it restarts the container. It would also provide health status to docker ps. Example from plex:
`plexinc/pms-docker:plexpass    "/init"                  2 weeks ago         Up About a minute (health: starting)`

**Comment by haugene** [comment]
Created a new issue for this. #454 
Let's follow up there.
