### ISSUE TITLE
"Port is closed" after stop + start

### ISSUE THREAD

**Issue by vikekh** [haugene/docker-transmission-openvpn#2079]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

```{yml}
version: "3.7"

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: ${TRANSMISSION_CONTAINER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_UI=transmission-web-control
      - TRANSMISSION_DOWNLOAD_DIR=/downloads/complete
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/data/transmission-home/unrar.sh
      - TRANSMISSION_PEER_PORT=${TRANSMISSION_PEER_PORT}
      - TRANSMISSION_DHT_ENABLED=false
      - TRANSMISSION_PEX_ENABLED=false
      - TRANSMISSION_LPD_ENABLED=false
      - TRANSMISSION_SPEED_LIMIT_UP=${TRANSMISSION_SPEED_LIMIT_UP}
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=${TRANSMISSION_SPEED_LIMIT_UP_ENABLED}
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
    volumes:
      - transmission-config:/config
      - transmission-data:/data
      - ${TRANSMISSION_UNRAR_SCRIPT}:/data/transmission-home/unrar.sh
      - ${DOWNLOADS_DIR}:/downloads
      - /etc/localtime:/etc/localtime:ro
      - ./.transmission/${OPENVPN_CONFIG}.ovpn:/etc/openvpn/${OPENVPN_CONFIG_DIR}/${OPENVPN_CONFIG}.ovpn
    expose:
      - 9091
    cap_add:
      - NET_ADMIN
    dns:
      - 8.8.8.8
      - 8.8.4.4
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - reverse-proxy
      - torrent
    restart: unless-stopped

  transmission-rss:
    image: haugene/transmission-rss
    container_name: ${TRANSMISSION_RSS_CONTAINER_NAME}
    links:
      - transmission
    volumes:
      - ./.transmission-rss/config.yml:/etc/transmission-rss.conf
    networks:
      - torrent
    restart: unless-stopped

volumes:
  transmission-config:
    name: ${TRANSMISSION_CONFIG_VOLUME_NAME}
  transmission-data:
    name: ${TRANSMISSION_DATA_VOLUME_NAME}

networks:
  reverse-proxy:
    external: true
  torrent:
    name: ${NETWORK_NAME}
```

### Current Behavior

I am starting Transmission via Docker Compose. Early every morning I have a cronjob setup to do `docker stop` on the container(s), do backup of volumes and then do `docker start`. After every time Transmission reports "port is closed". If I do a `docker-compose restart` the port is open again.

I'm not very certain this is a bug, but I cannot for the life of me figure out what is the "deciding" factor. I would think `docker start` would start the container with the same input as last time.

### Expected Behavior

That port is open when I stop and start Docker container.

### How have you tried to solve the problem?

I don't know what to try.

### Log output

```
transmission        | -------------------------------------
transmission        | Transmission will run as
transmission        | -------------------------------------
transmission        | User name:   abc
transmission        | User uid:    1000
transmission        | User gid:    1000
transmission        | -------------------------------------
transmission        |
transmission        | STARTING TRANSMISSION
transmission        | Transmission startup script complete.
transmission        | Fri Nov 26 22:43:04 2021 /sbin/ip route add 185.213.154.137/32 via 172.27.0.1
transmission        | Fri Nov 26 22:43:04 2021 /sbin/ip route add 0.0.0.0/1 via 10.10.0.1
transmission        | Fri Nov 26 22:43:04 2021 /sbin/ip route add 128.0.0.0/1 via 10.10.0.1
transmission        | Fri Nov 26 22:43:04 2021 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
transmission        | Fri Nov 26 22:43:04 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
transmission        | Fri Nov 26 22:43:04 2021 Initialization Sequence Completed
```

### Environment

```markdown
- OS: Ubuntu 18.04.5 LTS
- Docker: Docker version 20.10.7, build f0df350
```

**Comment by pkishino** [comment]
Please post complete logs from first start and then from restart showing this behavior.
Are you sure it’s not due to time? If you leave the container up for a short while does the port open?

**Comment by edgd1er** [comment]
I'm afraid several lines are missing $ sign to get variable value in bash. It may explain why expected ports are still closed.

https://github.com/haugene/docker-transmission-openvpn/blob/25b9724178f48227084f5a462b82b1fbc087498d/openvpn/start.sh#L223
https://github.com/haugene/docker-transmission-openvpn/blob/25b9724178f48227084f5a462b82b1fbc087498d/openvpn/start.sh#L226
https://github.com/haugene/docker-transmission-openvpn/blob/25b9724178f48227084f5a462b82b1fbc087498d/openvpn/start.sh#L229

may other lines have the same issue.

Based on a [stackoverflow](https://stackoverflow.com/questions/1921279/how-to-get-a-variable-value-if-variable-name-is-stored-as-string) question, I wrote a litte script to expose the issue:

```bash
#!/usr/bin/bash

testVar(){
  echo "Direct: $1"
  echo "varofvar: ${!1}"
}

PEERPORT="this is peer port"
testVar PEERPORT
```
Output
```
root@transmission:~# bash ./t.sh 
Direct: PEERPORT
varofvar: this is peer port
```

Correction:
add $ or use [indirect parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) (just learned that ;) ):

**Comment by pkishino** [comment]
thanks for pointing this out
fixed those obvious ones here  d385df4

**Comment by pkishino** [comment]
the things is though this shouldnt be related to your problem as they are ufw related and you are not using UFW..still good find ;)

**Comment by ovizii** [comment]
I opened a related discussion: https://github.com/haugene/docker-transmission-openvpn/discussions/2073 in which I detailed my problems with UFW and ports in general and the latest release about 2 days ago now no longer allows 9091 through ufw by default. OR so it seems. Just thought I'd link it as it seems related.
