### ISSUE TITLE
Proxy - pass reverse proxy port

### ISSUE THREAD

**Issue by bkodzis** [haugene/docker-transmission-openvpn#212]
Would be nice if we could pass the reverse proxy port to be used. In my case I have another docker container using port 8080 that I can't change, but there really isn't a reason the nginx proxy couldn't use any port specified.

**Comment by haugene** [comment]
Which port nginx uses inside the container don't affect the port you choose to bind it on your host. Simply pass -p 9876:8080 and then it would bind to port 9876 on the host.

**Comment by bkodzis** [comment]
Duh of course. Thanks!
