### ISSUE TITLE
NordVPN CDN Server No Longer Active

### ISSUE THREAD

**Issue by outerepic** [haugene/docker-transmission-openvpn#2136]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

CREATE_TUN_DEVICE | true
-- | --
DROP_DEFAULT_ROUTE |  
ENABLE_UFW | false
GLOBAL_APPLY_PERMISSIONS | true
HEALTH_CHECK_HOST | google.com
LOCAL_NETWORK | 192.168.0.0/16
LOG_TO_STDOUT | false
NORDVPN_CATEGORY | legacy_p2p
NORDVPN_COUNTRY | US
NORDVPN_PROTOCOL | tcp
OPENVPN_PASSWORD | XXXXXXX
OPENVPN_PROVIDER | NORDVPN
OPENVPN_USERNAME | XXXXXXX
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PEER_DNS | true
PEER_DNS_PIN_ROUTES | true
PGID | 100
PUID | 1031
REVISION | 73ec516cc246972289c7b96ffa88c81e037fe364
SELFHEAL | false
TRANSMISSION_DOWNLOAD_DIR | /XXXXXXXX
TRANSMISSION_HOME | /config/transmission-home
TRANSMISSION_INCOMPLETE_DIR | /XXXXXXX
TRANSMISSION_RPC_PORT | 9091
TRANSMISSION_WATCH_DIR | /XXXXXXXXX
TZ | XXXXXXXXX
UFW_ALLOW_GW_NET | false
UFW_DISABLE_IPTABLES_REJECT | false
UFW_EXTRA_PORTS |  
WEBPROXY_ENABLED | false
WEBPROXY_PASSWORD |  
WEBPROXY_PORT | 8888
WEBPROXY_USERNAME |  

### Current Behavior

When starting the container it goes into an endless loop searching for a NordVPN config download. The "https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us9230.nordvpn.com.tcp.ovpn" website is no longer valid. I reached out to NordVPN support and they said that they have no active servers with the nordcdn.com URL. I was advised to use this URL for downloads instead: "https://nordvpn.com/ovpn"

It seems like an easy fix would just be to update line 27 in the nordvpn/configure-openvpn.sh file

"nordvpn_dl=downloads.nordcdn.com"

### Expected Behavior

The docker container should be able to locate and download a working NordVPN config file and start normally. 

### How have you tried to solve the problem?

1) tried recreating the docker container and pulling the latest image
2) reached out to NordVPN to see why the CDN link was no longer working
3) checked through the source code to see where the problem was originating
4) restarted the container several times to no avail 
5) searched GitHub and reddit for similar issues

### Log output

Creating TUN device /dev/net/tun

mknod: /dev/net/tun: File exists

Using OpenVPN provider: NORDVPN

Running with VPN_CONFIG_SOURCE auto

Provider NORDVPN has a bundled setup script. Defaulting to internal config

Executing setup script for NORDVPN

2021-12-31 10:11:36 Checking curl installation

2021-12-31 10:11:36 Removing existing configs

2021-12-31 10:11:36 Selecting the best server...

parse error: Invalid numeric literal at line 1, column 7

2021-12-31 10:11:36 Searching for technology: openvpn_tcp

parse error: Invalid numeric literal at line 1, column 7

2021-12-31 10:11:36 Unable to find a server with the specified parameters, using any recommended server

parse error: Invalid numeric literal at line 1, column 7

2021-12-31 10:11:36 Best server : 

2021-12-31 10:11:36 Downloading config: default.ovpn

2021-12-31 10:11:36 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn

2021-12-31 10:11:36 Selecting the best server...

parse error: Invalid numeric literal at line 1, column 7

parse error: Invalid numeric literal at line 1, column 7

2021-12-31 10:11:36 Searching for technology: openvpn_tcp

parse error: Invalid numeric literal at line 1, column 7

2021-12-31 10:11:36 Unable to find a server with the specified parameters, using any recommended server

parse error: Invalid numeric literal at line 1, column 7

2021-12-31 10:11:36 Best server : 

2021-12-31 10:11:36 Downloading config: .ovpn

2021-12-31 10:11:36 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn

No VPN configuration provided. Using default.

Modifying /etc/openvpn/nordvpn/default.ovpn for best behaviour in this container

Modification: Point auth-user-pass option to the username/password file

Modification: Change ca certificate path

Modification: Change ping options

Modification: Update/set resolv-retry to 15 seconds

Modification: Change tls-crypt keyfile path

Modification: Set output verbosity to 3

Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop

Setting OpenVPN credentials...

adding route to local network 192.168.0.0/16 via 172.29.0.1 dev eth0

Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/default.ovpn

Use --help for more information.

Starting container with revision: 73ec516cc246972289c7b96ffa88c81e037fe364

### Environment

```markdown
- OS: Synology DSM 7.01
- Docker: 20.10.3-1239
```

### Anything else?

Recently updated my Synology NAS from 6.2 to DSM 7. However transmission was working after the restart for several hours so I don't think the two are related. I did a container update overnight and when transmission restarted that's when the issue started.

**Comment by outerepic** [comment]
Waited a few hours and recreated the container - currently getting this error. Appears I was wrong about the website download being the cause of the issue. Now it can't seem to open the downloaded file.

Creating TUN device /dev/net/tun

mknod: /dev/net/tun: File exists

Using OpenVPN provider: NORDVPN

Running with VPN_CONFIG_SOURCE auto

Provider NORDVPN has a bundled setup script. Defaulting to internal config

Executing setup script for NORDVPN

2021-12-31 21:38:10 Checking curl installation

2021-12-31 21:38:10 Removing existing configs

2021-12-31 21:38:10 Selecting the best server...

2021-12-31 21:38:10 Searching for technology: openvpn_tcp

2021-12-31 21:38:10 Best server : us8440.nordvpn.com

2021-12-31 21:38:10 Downloading config: default.ovpn

2021-12-31 21:38:10 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us8440.nordvpn.com.tcp.ovpn

2021-12-31 21:38:10 Selecting the best server...

2021-12-31 21:38:10 Searching for country : US (228)

2021-12-31 21:38:10 Searching for technology: openvpn_tcp

2021-12-31 21:38:10 Best server : us8440.nordvpn.com

2021-12-31 21:38:10 Downloading config: us8440.nordvpn.com.ovpn

2021-12-31 21:38:10 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us8440.nordvpn.com.tcp.ovpn

Starting OpenVPN using config us8440.nordvpn.com.ovpn

Modifying /etc/openvpn/nordvpn/us8440.nordvpn.com.ovpn for best behaviour in this container

Modification: Point auth-user-pass option to the username/password file

Modification: Change ca certificate path

Modification: Change ping options

Modification: Update/set resolv-retry to 15 seconds

Modification: Change tls-crypt keyfile path

Modification: Set output verbosity to 3

Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop

Setting OpenVPN credentials...

adding route to local network 192.168.0.0/16 via 172.29.0.1 dev eth0

Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/us8440.nordvpn.com.ovpn

Use --help for more information.

**Comment by pkishino** [comment]
This is the same issue with synology as has been seen in several other issues. Please check and try those solutions
Eg
#1839
