### ISSUE TITLE
PIA returned an error: "error":"User not found"

### ISSUE THREAD

**Issue by MindTooth** [haugene/docker-transmission-openvpn#214]
Hi,

Just started to use the container today, and I often get:
`PIA returned an error: "error":"User not found"`

It works sometimes, but often not.

My run command: https://gist.github.com/MindTooth/3e0084bf770bba0c890cb8305b69e014
(Also log inside Gist.)

When I look inside the container and at the openvpn-conf file, it seems just fine.  With the username on the first line, the password on the second.

Thoughts?

**Comment by haugene** [comment]
I would guess that it has to do with PIA changing their forwarding script. Just merged #202 to master and you commented in #201 that you had problems with PIA on the master branch, but it worked on dev right?

In the run command from your gist you're using the latest tag and not dev. Have you pulled the latest image again after I did the merge?

**Comment by MindTooth** [comment]
`docker pull haugene/transmission-openvpn` did the trick :-)  Thank yoy for a fast response.
