### ISSUE TITLE
OpenVPN doesn't try new servers when one fails due to timeout

### ISSUE THREAD

**Issue by burgerga123** [haugene/docker-transmission-openvpn#2144]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

My current run command for testing:
```
sudo docker run --rm -it \
  -e OPENVPN_PROVIDER=SLICKVPN \
  -e OPENVPN_CONFIG=United-States-Palo-Alto \
  -e OPENVPN_USERNAME=donald \
  -e OPENVPN_PASSWORD=duck \
  haugene/transmission-openvpn
```

### Current Behavior

United-States-Palo-Alto.opvn has the following remote servers, only two of which are working:
```
remote gw1.pao1.slickvpn.com 443 udp  #Timeout Failure
remote gw1.pao2.slickvpn.com 443 udp  #DNS Falure - Server no longer exists
remote gw1.pao3.slickvpn.com 443 udp  #DNS Falure - Server no longer exists
remote gw2.pao1.slickvpn.com 443 udp  #Works
remote gw2.pao2.slickvpn.com 443 udp  #DNS Falure - Server no longer exists
remote gw2.pao3.slickvpn.com 443 udp  #DNS Falure - Server no longer exists
remote gw3.pao1.slickvpn.com 443 udp  #Works
remote gw3.pao2.slickvpn.com 443 udp  #DNS Falure - Server no longer exists
remote gw3.pao3.slickvpn.com 443 udp  #DNS Falure - Server no longer exists
```

The first server in the list has some sort of issue. The DNS resolves, but a minute after it tries to connect it gets a `--ping-exit` and the container quits.

Setting OPENVPN_OPTS=remote-random will sometimes work, if it happens to grab one of the working servers at random.

If instead it grabs one of the servers that doesn't exist, it tries and fails to resolve the DNS for 15 seconds and then quits the container.

### Expected Behavior

According to OpenVPN's resources [here](https://openvpn.net/community-resources/implementing-a-load-balancing-failover-configuration/). A failure of connection to a server should result in trying another from the list.

### How have you tried to solve the problem?

Connection to the VPN is possible with a custom .opvn file that gets one of the working servers, so my setup in general should be okay. I have not been able to find any issues or options that may fix this.

### Log output

When using the Palo Alto config it attempts to connect to `gw1.pao1.slickvpn.com` and fails as follows:
```
sudo docker run --rm -it \
  -e OPENVPN_PROVIDER=SLICKVPN \
  -e OPENVPN_CONFIG=United-States-Palo-Alto \
  -e OPENVPN_USERNAME=donald \
  -e OPENVPN_PASSWORD=duck \
  haugene/transmission-openvpn
Password:
Starting container with revision: 20877f1b168b6ff27fc58aeef40756572c562d47
Creating TUN device /dev/net/tun
Using OpenVPN provider: SLICKVPN                                                                                                                        
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for SLICKVPN. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.EbJxETZt3z
Extracting configs to /tmp/tmp.HMcyXXW4mo
Found configs for SLICKVPN in /tmp/tmp.HMcyXXW4mo/vpn-configs-contrib-main/openvpn/slickvpn, will replace current content in /etc/openvpn/slickvpn     Cleanup: deleting /tmp/tmp.EbJxETZt3z and /tmp/tmp.HMcyXXW4mo
Starting OpenVPN using config United-States-Palo-Alto.ovpn
Modifying /etc/openvpn/slickvpn/United-States-Palo-Alto.ovpn for best behaviour in this containerModification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Setting OpenVPN credentials...
Mon Jan 10 02:33:16 2022 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021       
Mon Jan 10 02:33:16 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Mon Jan 10 02:33:16 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jan 10 02:33:16 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]192.81.128.78:443
Mon Jan 10 02:33:16 2022 Socket Buffers: R=[212992->212992] S=[212992->212992]
Mon Jan 10 02:33:16 2022 UDP link local: (not bound)
Mon Jan 10 02:33:16 2022 UDP link remote: [AF_INET]192.81.128.78:443
Mon Jan 10 02:34:16 2022 [UNDEF] Inactivity timeout (--ping-exit), exiting
Mon Jan 10 02:34:16 2022 SIGTERM[soft,ping-exit] received, process exiting
```

When adding `OPENVPN_OPTS=--remote-random` if it gets a non-existent server:
```
sudo docker run --rm -it \
>   -e OPENVPN_PROVIDER=SLICKVPN \
>   -e OPENVPN_CONFIG=United-States-Palo-Alto \
>   -e OPENVPN_USERNAME=donald \
>   -e OPENVPN_PASSWORD=duck \
>   -e OPENVPN_OPTS=--remote-random \
>   haugene/transmission-openvpn
Password: 
Starting container with revision: 20877f1b168b6ff27fc58aeef40756572c562d47
Creating TUN device /dev/net/tun
Using OpenVPN provider: SLICKVPN
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for SLICKVPN. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.f8S85sWu88
Extracting configs to /tmp/tmp.I94IiJ7oW9
Found configs for SLICKVPN in /tmp/tmp.I94IiJ7oW9/vpn-configs-contrib-main/openvpn/slickvpn, will replace current content in /etc/openvpn/slickvpn
Cleanup: deleting /tmp/tmp.f8S85sWu88 and /tmp/tmp.I94IiJ7oW9
Starting OpenVPN using config United-States-Palo-Alto.ovpn
Modifying /etc/openvpn/slickvpn/United-States-Palo-Alto.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate pathModification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Setting OpenVPN credentials...
Mon Jan 10 02:14:30 2022 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Mon Jan 10 02:14:30 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Mon Jan 10 02:14:30 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jan 10 02:14:43 2022 RESOLVE: Cannot resolve host address: gw1.pao2.slickvpn.com:443 (Name or service not known)
Mon Jan 10 02:14:55 2022 RESOLVE: Cannot resolve host address: gw1.pao2.slickvpn.com:443 (Name or service not known)
Mon Jan 10 02:15:16 2022 RESOLVE: Cannot resolve host address: gw1.pao2.slickvpn.com:443 (Name or service not known)
Mon Jan 10 02:15:37 2022 RESOLVE: Cannot resolve host address: gw1.pao2.slickvpn.com:443 (Name or service not known)
Mon Jan 10 02:15:37 2022 Could not determine IPv4/IPv6 protocol
Mon Jan 10 02:15:37 2022 SIGTERM[soft,init_instance] received, process exiting
```

### Environment

```markdown
- OS: DSM 7.0.1-42218
- Docker: 20.10.3--1239
```

**Comment by reprz** [comment]
I have had this issue also lately. Last time was 10 hours ago. Here are last lines of my log:

```
2022-02-14T23:30:33.151984891Z Reserved Port: 57579  Tue Feb 15 01:30:33 EET 2022                                                                                     
2022-02-14T23:40:33.506420210Z Tue Feb 15 01:40:33 2022 [stockholm402] Inactivit                                                                                                 y timeout (--ping-restart), restarting
2022-02-14T23:40:33.506737077Z Tue Feb 15 01:40:33 2022 /etc/openvpn/tunnelDown.                                                                                                 sh tun0 1500 1553 10.30.112.131 255.255.255.0 init
2022-02-14T23:40:33.519452415Z resolv.conf was restored
2022-02-14T23:40:33.522772894Z Sending kill signal to transmission-daemon
2022-02-14T23:40:34.537402698Z Successfuly closed transmission-daemon
2022-02-14T23:40:34.543792459Z Tue Feb 15 01:40:34 2022 /sbin/ip route del 195.2                                                                                                 46.120.69/32
2022-02-14T23:40:34.545736598Z Tue Feb 15 01:40:34 2022 /sbin/ip route del 0.0.0                                                                                                 .0/1
2022-02-14T23:40:34.547665859Z Tue Feb 15 01:40:34 2022 /sbin/ip route del 128.0                                                                                                 .0.0/1
2022-02-14T23:40:34.549549486Z Tue Feb 15 01:40:34 2022 Closing TUN/TAP interfac                                                                                                 e
2022-02-14T23:40:34.549580021Z Tue Feb 15 01:40:34 2022 /sbin/ip addr del dev tu                                                                                                 n0 10.30.112.131/24
2022-02-14T23:40:34.572115617Z Tue Feb 15 01:40:34 2022 SIGTERM[soft,ping-restar                                                                                                 t] received, process exiting
```

**Comment by pkishino** [comment]
> I have had this issue also lately. Last time was 10 hours ago. Here are last lines of my log:
> 
> ```
> 2022-02-14T23:30:33.151984891Z Reserved Port: 57579  Tue Feb 15 01:30:33 EET 2022                                                                                     
> 2022-02-14T23:40:33.506420210Z Tue Feb 15 01:40:33 2022 [stockholm402] Inactivit                                                                                                 y timeout (--ping-restart), restarting
> 2022-02-14T23:40:33.506737077Z Tue Feb 15 01:40:33 2022 /etc/openvpn/tunnelDown.                                                                                                 sh tun0 1500 1553 10.30.112.131 255.255.255.0 init
> 2022-02-14T23:40:33.519452415Z resolv.conf was restored
> 2022-02-14T23:40:33.522772894Z Sending kill signal to transmission-daemon
> 2022-02-14T23:40:34.537402698Z Successfuly closed transmission-daemon
> 2022-02-14T23:40:34.543792459Z Tue Feb 15 01:40:34 2022 /sbin/ip route del 195.2                                                                                                 46.120.69/32
> 2022-02-14T23:40:34.545736598Z Tue Feb 15 01:40:34 2022 /sbin/ip route del 0.0.0                                                                                                 .0/1
> 2022-02-14T23:40:34.547665859Z Tue Feb 15 01:40:34 2022 /sbin/ip route del 128.0                                                                                                 .0.0/1
> 2022-02-14T23:40:34.549549486Z Tue Feb 15 01:40:34 2022 Closing TUN/TAP interfac                                                                                                 e
> 2022-02-14T23:40:34.549580021Z Tue Feb 15 01:40:34 2022 /sbin/ip addr del dev tu                                                                                                 n0 10.30.112.131/24
> 2022-02-14T23:40:34.572115617Z Tue Feb 15 01:40:34 2022 SIGTERM[soft,ping-restar                                                                                                 t] received, process exiting
> ```
> 
> Container stops after this and it will not restart. Seems that the Restart policy makes no difference here since I have tried different settings.

can you show how you  set restart-policy please?

**Comment by reprz** [comment]
> if you look at the log
> 
> ```
> Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
> ```
> 
> you can change this by setting
> 
> ```
> CONFIG_MOD_REMAP_USR1=false
> ```
> 
> and try

Thanks, I set up this change. Let´s see if it helps.

My restart policy is now "Always" it was previously "Unless stopped".

**Comment by hildebrau** [comment]
Did anyone ever figure out how to fix this issue?  I'm constantly getting inactivity timeouts.. same SLICKVPN provider as the OP.



 2023-01-02 13:00:46 [UNDEF] Inactivity timeout (--ping-exit), exiting
 2023-01-02 13:00:46 SIGTERM[soft,ping-exit] received, process exiting
