### ISSUE TITLE
PureVPN Servers Incorrect

### ISSUE THREAD

**Issue by ciphersh0rt** [haugene/docker-transmission-openvpn#2166]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

OPENVPN_PROVIDER=PUREVPN
OPENVPN_CONFIG=ustx2-auto-tcp

### Current Behavior

Log prompts a list of available PureVPN servers that are no longer consisted with current DNS names. Current server list can be found here: https://support.purevpn.com/vpn-servers. It appears that the list of .ovpn files downloaded for configuration are outdated.

### Expected Behavior

If valid server is set to variable OPENVPN_CONFIIG, then that should be used. 

### How have you tried to solve the problem?

I've tried to use servers listed in the configured downloaded file, however, they are invalid and authentication fails. 

### Log output

Starting container with revision: a2f99f41df498d83019c50c08a9fcb498e4bf929
Creating TUN device /dev/net/tun
Using OpenVPN provider: PUREVPN
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for PUREVPN. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.uVKgg9iLeS
Extracting configs to /tmp/tmp.rCP4ZTbAJL
Found configs for PUREVPN in /tmp/tmp.rCP4ZTbAJL/vpn-configs-contrib-main/openvpn/purevpn, will replace current content in /etc/openvpn/purevpn
Cleanup: deleting /tmp/tmp.uVKgg9iLeS and /tmp/tmp.rCP4ZTbAJL
Supplied config ustx2-auto-tcp.ovpn could not be found.
Your options for this provider are:
at2-ovpn-tcp.ovpn
at2-ovpn-udp.ovpn
au-sd2-ovpn-tcp.ovpn
au-sd2-ovpn-udp.ovpn
au2-ovpn-tcp.ovpn
au2-ovpn-udp.ovpn
au2-pe-ovpn-tcp.ovpn
au2-pe-ovpn-udp.ovpn
br2-ovpn-tcp.ovpn
br2-ovpn-udp.ovpn
ca2-ovpn-tcp.ovpn
ca2-ovpn-udp.ovpn
cav2-ovpn-tcp.ovpn
cav2-ovpn-udp.ovpn
ch2-ovpn-tcp.ovpn
ch2-ovpn-udp.ovpn
cz2-ovpn-tcp.ovpn
cz2-ovpn-udp.ovpn
de2-ovpn-tcp.ovpn
de2-ovpn-udp.ovpn
default.ovpn
dk2-ovpn-tcp.ovpn
dk2-ovpn-udp.ovpn
es2-ovpn-tcp.ovpn
es2-ovpn-udp.ovpn
fr2-ovpn-tcp.ovpn
fr2-ovpn-udp.ovpn
gr2-ovpn-tcp.ovpn
gr2-ovpn-udp.ovpn
hk2-ovpn-tcp.ovpn
hk2-ovpn-udp.ovpn
in2-ovpn-tcp.ovpn
in2-ovpn-udp.ovpn
it2-ovpn-tcp.ovpn
it2-ovpn-udp.ovpn
jp2-ovpn-tcp.ovpn
jp2-ovpn-udp.ovpn
kr2-ovpn-tcp.ovpn
kr2-ovpn-udp.ovpn
my2-ovpn-tcp.ovpn
my2-ovpn-udp.ovpn
nl2-ovpn-tcp.ovpn
nl2-ovpn-udp.ovpn
p2p-udp.ovpn
pl2-ovpn-tcp.ovpn
pl2-ovpn-udp.ovpn
pt2-ovpn-tcp.ovpn
pt2-ovpn-udp.ovpn
ru2-ovpn-tcp.ovpn
ru2-ovpn-udp.ovpn
se2-ovpn-tcp.ovpn
se2-ovpn-udp.ovpn
sg2-ovpn-tcp.ovpn
sg2-ovpn-udp.ovpn
tw2-ovpn-tcp.ovpn
tw2-ovpn-udp.ovpn
uk-obf-udp.ovpn
ukg2-ovpn-tcp.ovpn
ukg2-ovpn-udp.ovpn
ukl2-ovpn-tcp.ovpn
ukl2-ovpn-udp.ovpn
ukm2-ovpn-tcp.ovpn
ukm2-ovpn-udp.ovpn
us2-ovpn-tcp.ovpn
us2-ovpn-udp.ovpn
usfl2-ovpn-tcp.ovpn
usfl2-ovpn-udp.ovpn
usga2-ovpn-tcp.ovpn
usga2-ovpn-udp.ovpn
usil2-ovpn-tcp.ovpn
usil2-ovpn-udp.ovpn
usla2-ovpn-tcp.ovpn
usla2-ovpn-udp.ovpn
usnj2-ovpn-tcp.ovpn
usnj2-ovpn-udp.ovpn
usny2-ovpn-tcp.ovpn
usny2-ovpn-udp.ovpn
usphx2-ovpn-tcp.ovpn
usphx2-ovpn-udp.ovpn
ussa2-ovpn-tcp.ovpn
ussa2-ovpn-udp.ovpn
ussf2-ovpn-tcp.ovpn
ussf2-ovpn-udp.ovpn
ustx2-ovpn-tcp.ovpn
ustx2-ovpn-udp.ovpn
usut2-ovpn-tcp.ovpn
usut2-ovpn-udp.ovpn
usva2-ovpn-tcp.ovpn
usva2-ovpn-udp.ovpn
uswdc2-ovpn-tcp.ovpn
uswdc2-ovpn-udp.ovpn
vlap-ph2-ovpn-tcp.ovpn
vlap-ph2-ovpn-udp.ovpn
vlap-th2-ovpn-tcp.ovpn
vlap-th2-ovpn-udp.ovpn
vlap-vn2-ovpn-tcp.ovpn
vlap-vn2-ovpn-udp.ovpn
vleu-be2-ovpn-tcp.ovpn
vleu-be2-ovpn-udp.ovpn
vleu-no2-ovpn-tcp.ovpn
vleu-no2-ovpn-udp.ovpn
vlus-mx2-ovpn-tcp.ovpn
vlus-mx2-ovpn-udp.ovpn
vlus-pa2-ovpn-tcp.ovpn
vlus-pa2-ovpn-udp.ovpn
za2-ovpn-tcp.ovpn
za2-ovpn-udp.ovpn
NB: Remember to not specify .ovpn as part of the config name.

### Environment

```markdown
- OS: Ubuntu 20.04
- Docker: 20.10.12
```

**Comment by pkishino** [comment]
Seriously?? You opened a ticket clearly related to a provider by selecting to create a ticket here at the main repo, when the issue selector clearly links to the provider repo.. THEN you tick a box saying this is not provider related??
