### ISSUE TITLE
Mobile UI "select files to upload" part is gone in latest version.

### ISSUE THREAD

**Issue by caesarju** [haugene/docker-transmission-openvpn#2170]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn:latest #3.7.1
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/transmission-vpn/data:/data
      - $DOCKERDIR/appdata/transmission-vpn/config:/config
      - $DOCKERDIR/appdata/transmission-vpn/scripts:/scripts
      - $DOWNLOADDIR:/data/downloads

### Current Behavior

When I go to web UI using safari/chrome on iphone, I can't find "Select" button to select file to upload in latest version.
But, if I go to web UI using desktop chrome, I can find it, and it works. 

Also, I can find it in 3.7.1 version even if I go to web UI using mobile safari.

I've searching similar situation from google.
https://github.com/transmission/transmission/issues/431

< Latest version web UI - cannot find select button >
![KakaoTalk_20220129_192107048](https://user-images.githubusercontent.com/34831299/151657331-787d55de-adbc-48a6-b725-9f91b8c5801f.jpg)

### Expected Behavior

Even if I go to web UI using my iphone, there is a button selecting files to upload in latest version. (v4?)

< I can using select button to upload files in 3.7.1 >
![KakaoTalk_20220129_192106629](https://user-images.githubusercontent.com/34831299/151657347-3721c8a0-7b88-416e-bf10-3f0005721f50.jpg)

### How have you tried to solve the problem?

In 3.7.1 there is no problem at all. It works!

### Log output

No errors.

### Environment

```markdown
- OS: Ubuntu 20.04
- Docker: 20.10.12
```

**Comment by caesarju** [comment]
Since transmission-openvpn 4.0 uses transmission version 2.94, it seems to be used without inherently solving the problem.
So, if I use mobile often, I should use transmission-openvpn v3.7.1.
Am I right?

**Comment by pkishino** [comment]
This isn’ta container issue, is with the UI. We can’t do anything about that directly. I suggest you either stick with 3.7.1 or use a different UI (e.g. flood, see wiki) than default

**Comment by caesarju** [comment]
> This isn’ta container issue, is with the UI. We can’t do anything about that directly. I suggest you either stick with 3.7.1 or use a different UI (e.g. flood, see wiki) than default

I understood. Thank you.
