### ISSUE TITLE
Why use openvpn

### ISSUE THREAD

**Issue by turing-king** [haugene/docker-transmission-openvpn#218]
Is it for security? Or anything else

**Comment by turing-king** [comment]
Is it used for PT download?

**Comment by bspinner** [comment]
That's a very fundamental topic you maybe should read about before doing anything with this docker.

Basically, OpenVPN is used as a client for your VPN provider. So, yes, it's for security. Every connection that's established by the docker container to the internet will be tunneled through your VPN provider. By doing that (in a properly configured way), the outside world will never see your actual IP address but only the VPN provider's one.

Some links:
https://en.wikipedia.org/wiki/Virtual_private_network
https://en.wikipedia.org/wiki/OpenVPN
