### ISSUE TITLE
RTNETLINK answers: File exists ERROR: Linux route add command failed: external program exited with error status: 2

### ISSUE THREAD

**Issue by qu4542** [haugene/docker-transmission-openvpn#2192]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

version: '3,3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/srv/dev-disk-by-uuid-localdrive/configdata/TransmissionVPN:/data'
        environment:
            - OPENVPN_PROVIDER=PRIVADO
            - OPENVPN_CONFIG=arn-001
            - OPENVPN_USERNAME=username
            - OPENVPN_PASSWORD=password
            - LOCAL_NETWORK=192.168.178.0/24
        logging:
            driver: json-file
            options:
                max-size: 10m
        sysctls:
             - net.ipv6.conf.all.disable_ipv6=0
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

### Current Behavior

see log:

RTNETLINK answers: File exists
ERROR: Linux route add command failed: external program exited with error status: 2
WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.

### Expected Behavior

not giving error messages!

### How have you tried to solve the problem?

1) tried different:             - LOCAL_NETWORK=192.168.178.0/24
e.g.             - LOCAL_NETWORK=192.168.178.0/24, 172.0.0.0/16

2) added to docker-compose:       sysctls:             - net.ipv6.conf.all.disable_ipv6=0

------------------------------------------
this is my ip r

user@host:~$ ip r
default via 192.168.178.1 dev eth0 proto dhcp src 192.168.178.xx metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
172.23.0.0/16 dev br-bae8fee5ec85 proto kernel scope link src 172.23.0.1 linkdown
172.24.0.0/16 dev br-38d9466115de proto kernel scope link src 172.24.0.1
172.27.0.0/16 dev br-7d664f89862a proto kernel scope link src 172.27.0.1
172.28.0.0/16 dev br-92bafb23027d proto kernel scope link src 172.28.0.1
172.30.0.0/16 dev br-1622a13d3a7d proto kernel scope link src 172.30.0.1
192.168.178.0/24 dev eth0 proto kernel scope link src 192.168.178.xx
192.168.178.1 dev eth0 proto dhcp scope link src 192.168.178.xx metric 100

### Log output

Successfuly closed transmission-daemon
Tue Feb 15 03:03:44 2022 /sbin/ip route del 86.106.103.67/32
Tue Feb 15 03:03:44 2022 /sbin/ip route del 0.0.0.0/1
Tue Feb 15 03:03:44 2022 /sbin/ip route del 128.0.0.0/1
Tue Feb 15 03:03:44 2022 Closing TUN/TAP interface
Tue Feb 15 03:03:44 2022 /sbin/ip addr del dev tun0 172.21.24.34/23
Tue Feb 15 03:03:44 2022 SIGTERM[soft,exit-with-notification] received, process exiting
Starting container with revision: 20877f1b168b6ff27fc58aeef40756572c562d47
Creating TUN device /dev/net/tun
Using OpenVPN provider: PRIVADO
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for PRIVADO. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.8V3dPEeEJ4
Extracting configs to /tmp/tmp.d2ouNvxWaP
Found configs for PRIVADO in /tmp/tmp.d2ouNvxWaP/vpn-configs-contrib-main/openvpn/privado, will replace current content in /etc/openvpn/privado
Cleanup: deleting /tmp/tmp.8V3dPEeEJ4 and /tmp/tmp.d2ouNvxWaP
Starting OpenVPN using config arn-001.ovpn
Modifying /etc/openvpn/privado/arn-001.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Setting OpenVPN credentials...
adding route to local network 192.168.178.0/24 via 192.168.16.1 dev eth0
Tue Feb 15 11:18:56 2022 OpenVPN 2.4.7 aarch64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Tue Feb 15 11:18:56 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Tue Feb 15 11:18:56 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Feb 15 11:18:56 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]86.106.103.67:1194
Tue Feb 15 11:18:56 2022 Socket Buffers: R=[212992->212992] S=[212992->212992]
Tue Feb 15 11:18:56 2022 UDP link local: (not bound)
Tue Feb 15 11:18:56 2022 UDP link remote: [AF_INET]86.106.103.67:1194
Tue Feb 15 11:18:56 2022 TLS: Initial packet from [AF_INET]86.106.103.67:1194, sid=65694f0f 452b7910
Tue Feb 15 11:18:56 2022 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Feb 15 11:18:56 2022 VERIFY OK: depth=1, CN=Privado
Tue Feb 15 11:18:56 2022 VERIFY KU OK
Tue Feb 15 11:18:56 2022 Validating certificate extended key usage
Tue Feb 15 11:18:56 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue Feb 15 11:18:56 2022 VERIFY EKU OK
Tue Feb 15 11:18:56 2022 VERIFY X509NAME OK: CN=arn-001.vpn.privado.io
Tue Feb 15 11:18:56 2022 VERIFY OK: depth=0, CN=arn-001.vpn.privado.io
Tue Feb 15 11:18:56 2022 Control Channel: TLSv1.2, cipher SSLv3 DHE-RSA-AES256-SHA, 4096 bit RSA
Tue Feb 15 11:18:56 2022 [arn-001.vpn.privado.io] Peer Connection Initiated with [AF_INET]86.106.103.67:1194
Tue Feb 15 11:18:57 2022 SENT CONTROL [arn-001.vpn.privado.io]: 'PUSH_REQUEST' (status=1)
Tue Feb 15 11:18:57 2022 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 198.18.0.1,dhcp-option DNS 198.18.0.2,rcvbuf 493216,sndbuf 493216,explicit-exit-notify 5,route-gateway 172.21.46.1,topology subnet,ping 20,ping-restart 40,ifconfig 172.21.46.35 255.255.254.0,peer-id 2,cipher AES-256-GCM'
Tue Feb 15 11:18:57 2022 OPTIONS IMPORT: timers and/or timeouts modified
Tue Feb 15 11:18:57 2022 OPTIONS IMPORT: explicit notify parm(s) modified
Tue Feb 15 11:18:57 2022 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Tue Feb 15 11:18:57 2022 Socket Buffers: R=[212992->425984] S=[212992->425984]
Tue Feb 15 11:18:57 2022 OPTIONS IMPORT: --ifconfig/up options modified
Tue Feb 15 11:18:57 2022 OPTIONS IMPORT: route options modified
Tue Feb 15 11:18:57 2022 OPTIONS IMPORT: route-related options modified
Tue Feb 15 11:18:57 2022 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Tue Feb 15 11:18:57 2022 OPTIONS IMPORT: peer-id set
Tue Feb 15 11:18:57 2022 OPTIONS IMPORT: adjusting link_mtu to 1624
Tue Feb 15 11:18:57 2022 OPTIONS IMPORT: data channel crypto options modified
Tue Feb 15 11:18:57 2022 Data Channel: using negotiated cipher 'AES-256-GCM'
Tue Feb 15 11:18:57 2022 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Feb 15 11:18:57 2022 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Feb 15 11:18:57 2022 ROUTE_GATEWAY 192.168.16.1/255.255.240.0 IFACE=eth0 HWADDR=02:42:c0:a8:10:02
Tue Feb 15 11:18:57 2022 GDG6: remote_host_ipv6=n/a
Tue Feb 15 11:18:57 2022 ROUTE6: default_gateway=UNDEF
Tue Feb 15 11:18:57 2022 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
Tue Feb 15 11:18:57 2022 OpenVPN ROUTE: failed to parse/resolve route for host/network: ::/0
Tue Feb 15 11:18:57 2022 TUN/TAP device tun0 opened
Tue Feb 15 11:18:57 2022 TUN/TAP TX queue length set to 100
Tue Feb 15 11:18:57 2022 /sbin/ip link set dev tun0 up mtu 1500
Tue Feb 15 11:18:57 2022 /sbin/ip addr add dev tun0 172.21.46.35/23 broadcast 172.21.47.255
Tue Feb 15 11:18:57 2022 /etc/openvpn/tunnelUp.sh tun0 1500 1552 172.21.46.35 255.255.254.0 init
Up script executed with tun0 1500 1552 172.21.46.35 255.255.254.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 172.21.46.35
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 172.21.46.35
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------
STARTING TRANSMISSION
Transmission startup script complete.
Tue Feb 15 11:19:01 2022 /sbin/ip route add 86.106.103.67/32 via 192.168.16.1
Tue Feb 15 11:19:01 2022 /sbin/ip route add 0.0.0.0/1 via 172.21.46.1
Tue Feb 15 11:19:01 2022 /sbin/ip route add 128.0.0.0/1 via 172.21.46.1
Tue Feb 15 11:19:01 2022 /sbin/ip route add 0.0.0.0/0 via 172.21.46.1
RTNETLINK answers: File exists
Tue Feb 15 11:19:01 2022 ERROR: Linux route add command failed: external program exited with error status: 2
Tue Feb 15 11:19:01 2022 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
Tue Feb 15 11:19:01 2022 Initialization Sequence Completed

### Environment

```markdown
- OS: Armbian_20.10_Arm-64_buster_current_5.9.0
- Docker: Portainer Standalone 20.10.12
```

### Anything else?

I understand its supposed to have something to do with the routing and conflicting ip ranges?

**Comment by qu4542** [comment]
![route](https://user-images.githubusercontent.com/98687468/154064425-ee79ad05-c366-4914-a99e-15dc6c33da82.JPG)

**Comment by pkishino** [comment]
it's trying to add the same route twice as per log
```
Tue Feb 15 11:19:01 2022 /sbin/ip route add 0.0.0.0/1 via 172.21.46.1
Tue Feb 15 11:19:01 2022 /sbin/ip route add 128.0.0.0/1 via 172.21.46.1
Tue Feb 15 11:19:01 2022 /sbin/ip route add 0.0.0.0/0 via 172.21.46.1
```
I looked at the privado ovpn config and this line looks wrong
https://github.com/haugene/vpn-configs-contrib/blob/69879795bf674e56fe2f90e3c64ef703393e98bf/openvpn/privado/arn-001.ovpn#L18
route 0.0.0.0 0.0.0.0 vpn_gateway
can you try to set:
PEER_DNS_PIN_ROUTES=false
DROP_DEFAULT_ROUTE=true

**Comment by qu4542** [comment]
> can you try to set:
> PEER_DNS_PIN_ROUTES=false
> DROP_DEFAULT_ROUTE=true

hey thx a lot for the reply, should i put those into the docker-compose.yml or into the *ovpn?

**Comment by qu4542** [comment]
ok i tried to run this:
-----------------------------
version: '4'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/srv/dev-disk-by-uuid-xxxxxxx/appdata/TransmissionVPN:/data'
        environment:
            - OPENVPN_PROVIDER=PRIVADO
            - OPENVPN_CONFIG=arn-001
            - OPENVPN_USERNAME=*********
            - OPENVPN_PASSWORD=********
            - PEER_DNS_PIN_ROUTES=false
            - DROP_DEFAULT_ROUTE=true
            - LOCAL_NETWORK=192.168.0.0/16  **<- my local ip range is 168.178 though does it matter?**

        logging:
            driver: json-file
            options:
                max-size: 10m
        sysctls:
             - net.ipv6.conf.all.disable_ipv6=1
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

--------------------------------

now the log looks like this:

`Starting container with revision: 20877f1b168b6ff27fc58aeef40756572c562d47
Creating TUN device /dev/net/tun
Using OpenVPN provider: PRIVADO
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for PRIVADO. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.4DJskhr4Iq
Extracting configs to /tmp/tmp.CzSY9uUB4M
Found configs for PRIVADO in /tmp/tmp.CzSY9uUB4M/vpn-configs-contrib-main/openvpn/privado, will replace current content in /etc/openvpn/privado
Cleanup: deleting /tmp/tmp.4DJskhr4Iq and /tmp/tmp.CzSY9uUB4M
Starting OpenVPN using config arn-001.ovpn
Modifying /etc/openvpn/privado/arn-001.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Setting OpenVPN credentials...
adding route to local network 192.168.0.0/16 via 192.168.80.1 dev eth0
Wed Feb 16 12:57:13 2022 OpenVPN 2.4.7 aarch64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Wed Feb 16 12:57:13 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Wed Feb 16 12:57:13 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Feb 16 12:57:13 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]86.106.103.67:1194
Wed Feb 16 12:57:13 2022 Socket Buffers: R=[212992->212992] S=[212992->212992]
Wed Feb 16 12:57:13 2022 UDP link local: (not bound)
Wed Feb 16 12:57:13 2022 UDP link remote: [AF_INET]86.106.103.67:1194
Wed Feb 16 12:57:13 2022 TLS: Initial packet from [AF_INET]86.106.103.67:1194, sid=339220b6 941be5d5
Wed Feb 16 12:57:13 2022 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Feb 16 12:57:13 2022 VERIFY OK: depth=1, CN=Privado
Wed Feb 16 12:57:14 2022 VERIFY KU OK
Wed Feb 16 12:57:14 2022 Validating certificate extended key usage
Wed Feb 16 12:57:14 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Feb 16 12:57:14 2022 VERIFY EKU OK
Wed Feb 16 12:57:14 2022 VERIFY X509NAME OK: CN=arn-001.vpn.privado.io
Wed Feb 16 12:57:14 2022 VERIFY OK: depth=0, CN=arn-001.vpn.privado.io
Wed Feb 16 12:57:14 2022 Control Channel: TLSv1.2, cipher SSLv3 DHE-RSA-AES256-SHA, 4096 bit RSA
Wed Feb 16 12:57:14 2022 [arn-001.vpn.privado.io] Peer Connection Initiated with [AF_INET]86.106.103.67:1194
Wed Feb 16 12:57:15 2022 SENT CONTROL [arn-001.vpn.privado.io]: 'PUSH_REQUEST' (status=1)
Wed Feb 16 12:57:15 2022 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 198.18.0.1,dhcp-option DNS 198.18.0.2,rcvbuf 493216,sndbuf 493216,explicit-exit-notify 5,route-gateway 172.21.46.1,topology subnet,ping 20,ping-restart 40,ifconfig 172.21.46.35 255.255.254.0,peer-id 2,cipher AES-256-GCM'
Wed Feb 16 12:57:15 2022 OPTIONS IMPORT: timers and/or timeouts modified
Wed Feb 16 12:57:15 2022 OPTIONS IMPORT: explicit notify parm(s) modified
Wed Feb 16 12:57:15 2022 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Wed Feb 16 12:57:15 2022 Socket Buffers: R=[212992->425984] S=[212992->425984]
Wed Feb 16 12:57:15 2022 OPTIONS IMPORT: --ifconfig/up options modified
Wed Feb 16 12:57:15 2022 OPTIONS IMPORT: route options modified
Wed Feb 16 12:57:15 2022 OPTIONS IMPORT: route-related options modified
Wed Feb 16 12:57:15 2022 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed Feb 16 12:57:15 2022 OPTIONS IMPORT: peer-id set
Wed Feb 16 12:57:15 2022 OPTIONS IMPORT: adjusting link_mtu to 1624
Wed Feb 16 12:57:15 2022 OPTIONS IMPORT: data channel crypto options modified
Wed Feb 16 12:57:15 2022 Data Channel: using negotiated cipher 'AES-256-GCM'
Wed Feb 16 12:57:15 2022 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Feb 16 12:57:15 2022 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Feb 16 12:57:15 2022 ROUTE_GATEWAY 192.168.80.1/255.255.240.0 IFACE=eth0 HWADDR=02:42:c0:a8:50:02
Wed Feb 16 12:57:15 2022 GDG6: remote_host_ipv6=n/a
Wed Feb 16 12:57:15 2022 ROUTE6: default_gateway=UNDEF
Wed Feb 16 12:57:15 2022 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
Wed Feb 16 12:57:15 2022 OpenVPN ROUTE: failed to parse/resolve route for host/network: ::/0
Wed Feb 16 12:57:15 2022 TUN/TAP device tun0 opened
Wed Feb 16 12:57:15 2022 TUN/TAP TX queue length set to 100
Wed Feb 16 12:57:15 2022 /sbin/ip link set dev tun0 up mtu 1500
Wed Feb 16 12:57:15 2022 /sbin/ip addr add dev tun0 172.21.46.35/23 broadcast 172.21.47.255
Wed Feb 16 12:57:15 2022 /etc/openvpn/tunnelUp.sh tun0 1500 1552 172.21.46.35 255.255.254.0 init
Up script executed with tun0 1500 1552 172.21.46.35 255.255.254.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 172.21.46.35
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 172.21.46.35
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------
DROPPING DEFAULT ROUTE
STARTING TRANSMISSION
Transmission startup script complete.
Wed Feb 16 12:57:15 2022 write UDP: Network is unreachable (code=101)
Wed Feb 16 12:57:17 2022 write UDP: Network is unreachable (code=101)
Wed Feb 16 12:57:19 2022 /sbin/ip route add 86.106.103.67/32 via 192.168.80.1
Wed Feb 16 12:57:19 2022 /sbin/ip route add 0.0.0.0/1 via 172.21.46.1
Wed Feb 16 12:57:19 2022 /sbin/ip route add 128.0.0.0/1 via 172.21.46.1
Wed Feb 16 12:57:19 2022 /sbin/ip route add 0.0.0.0/0 via 172.21.46.1
Wed Feb 16 12:57:19 2022 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
Wed Feb 16 12:57:19 2022 Initialization Sequence Completed`

**Comment by qu4542** [comment]
ok it looks like im behind the tunnle, i used this to check:

http://ipmagnet.services.cbcdn.com/

**Comment by alarys** [comment]
Hi,

First off, huge thanks for all the work and support on this project!

This issue happened to me as well, using 4.0. I am also using Privado. The fix above worked for me.

            - PEER_DNS_PIN_ROUTES=false
            - DROP_DEFAULT_ROUTE=true

Thanks! I had actually down-graded to 3.3 which seemed to work as well. But I am much happier being on the latest 4.0 now.

**Comment by pkishino** [comment]
Great, I’ve put a mark on it to try and take a look at this to see if there is another way to fix this
