### ISSUE TITLE
High CPU

### ISSUE THREAD

**Issue by steveaggie** [haugene/docker-transmission-openvpn#2199]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

version: "2.1"
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    cap_add:
      - NET_ADMIN 
    devices:
      - /dev/net/tun
    environment:
      - OPENVPN_PROVIDER=PIA
#      - OPENVPN_CONFIG=us_houston
      - OPENVPN_USERNAME=XXXX
      - OPENVPN_PASSWORD=XXXX
      - LOCAL_NETWORK=172.16.10.0/23
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - PIA_OPENVPN_CONFIG_BUNDLE=openvpn-tcp
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - /mnt/media/:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9091:9091
    restart: unless-stopped

### Current Behavior

Transmission container consumes all remaining CPU cycles when running (CPU @ 100%).  If I shutdown the docker container it works fine.  I have several other docker containers running on this machine and they work fine.  Transmission used to work fine.  I don't know of any changes that occurred when this started happening.  It occurred before the latest release and also with the latest release.  I only have 5 torrents downloading at a time and none uploading.

### Expected Behavior

Reasonable CPU usage

### How have you tried to solve the problem?

Updated to latest version
Checked docker-compose.yml

### Log output

transmission    | Starting container with revision: 8cc1870cc039201e0e2f8b7684a9f4e96ae03ab9
transmission    | Creating TUN device /dev/net/tun
transmission    | mknod: /dev/net/tun: File exists
transmission    | Using OpenVPN provider: PIA
transmission    | Running with VPN_CONFIG_SOURCE auto
transmission    | Provider PIA has a bundled setup script. Defaulting to internal config
transmission    | Executing setup script for PIA
transmission    | Downloading OpenVPN config bundle openvpn-tcp into temporary file /tmp/tmp.NG22NTyF7p
transmission    | Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
transmission    | No VPN configuration provided. Using default.
transmission    | Modifying /etc/openvpn/pia/default.ovpn for best behaviour in this container
transmission    | Modification: Point auth-user-pass option to the username/password file
transmission    | Modification: Change ca certificate path
transmission    | Modification: Change ping options
transmission    | Modification: Update/set resolv-retry to 15 seconds
transmission    | Modification: Change tls-crypt keyfile path
transmission    | Modification: Set output verbosity to 3
transmission    | Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
transmission    | Setting OpenVPN credentials...
transmission    | adding route to local network 172.16.10.0/23 via 192.168.32.1 dev eth0
transmission    | Tue Mar  1 11:00:07 2022 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
transmission    | Tue Mar  1 11:00:07 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
transmission    | Tue Mar  1 11:00:07 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission    | Tue Mar  1 11:00:07 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]178.175.129.35:502
transmission    | Tue Mar  1 11:00:07 2022 Socket Buffers: R=[131072->131072] S=[16384->16384]
transmission    | Tue Mar  1 11:00:07 2022 Attempting to establish TCP connection with [AF_INET]178.175.129.35:502 [nonblock]
transmission    | Tue Mar  1 11:00:08 2022 TCP connection established with [AF_INET]178.175.129.35:502
transmission    | Tue Mar  1 11:00:08 2022 TCP_CLIENT link local: (not bound)
transmission    | Tue Mar  1 11:00:08 2022 TCP_CLIENT link remote: [AF_INET]178.175.129.35:502
transmission    | Tue Mar  1 11:00:09 2022 TLS: Initial packet from [AF_INET]178.175.129.35:502, sid=d120eb63 e3b8d208
transmission    | Tue Mar  1 11:00:09 2022 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
transmission    | Tue Mar  1 11:00:09 2022 VERIFY OK: depth=1, C=US, ST=CA, L=LosAngeles, O=Private Internet Access, OU=Private Internet Access, CN=Private Internet Access, name=Private Internet Access, emailAddress=secure@privateinternetaccess.com
transmission    | Tue Mar  1 11:00:09 2022 VERIFY KU OK
transmission    | Tue Mar  1 11:00:09 2022 Validating certificate extended key usage
transmission    | Tue Mar  1 11:00:09 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
transmission    | Tue Mar  1 11:00:09 2022 VERIFY EKU OK
transmission    | Tue Mar  1 11:00:09 2022 VERIFY OK: depth=0, C=US, ST=CA, L=LosAngeles, O=Private Internet Access, OU=Private Internet Access, CN=chisinau401, name=chisinau401
transmission    | Tue Mar  1 11:00:10 2022 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA
transmission    | Tue Mar  1 11:00:10 2022 [chisinau401] Peer Connection Initiated with [AF_INET]178.175.129.35:502
transmission    | Tue Mar  1 11:00:11 2022 SENT CONTROL [chisinau401]: 'PUSH_REQUEST' (status=1)
transmission    | Tue Mar  1 11:00:11 2022 PUSH: Received control message: 'PUSH_REPLY,comp-lzo no,redirect-gateway def1,route-ipv6 2000::/3,dhcp-option DNS 10.0.0.243,route-gateway 10.1.111.1,topology subnet,ping 10,ping-restart 60,ifconfig 10.1.111.16 255.255.255.0,peer-id 0,cipher AES-128-GCM'
transmission    | Tue Mar  1 11:00:11 2022 OPTIONS IMPORT: timers and/or timeouts modified
transmission    | Tue Mar  1 11:00:11 2022 OPTIONS IMPORT: compression parms modified
transmission    | Tue Mar  1 11:00:11 2022 OPTIONS IMPORT: --ifconfig/up options modified
transmission    | Tue Mar  1 11:00:11 2022 OPTIONS IMPORT: route options modified
transmission    | Tue Mar  1 11:00:11 2022 OPTIONS IMPORT: route-related options modified
transmission    | Tue Mar  1 11:00:11 2022 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
transmission    | Tue Mar  1 11:00:11 2022 OPTIONS IMPORT: peer-id set
transmission    | Tue Mar  1 11:00:11 2022 OPTIONS IMPORT: adjusting link_mtu to 1627
transmission    | Tue Mar  1 11:00:11 2022 OPTIONS IMPORT: data channel crypto options modified
transmission    | Tue Mar  1 11:00:11 2022 Data Channel: using negotiated cipher 'AES-128-GCM'
transmission    | Tue Mar  1 11:00:11 2022 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
transmission    | Tue Mar  1 11:00:11 2022 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
transmission    | Tue Mar  1 11:00:11 2022 ROUTE_GATEWAY 192.168.32.1/255.255.240.0 IFACE=eth0 HWADDR=02:42:c0:a8:20:02
transmission    | Tue Mar  1 11:00:11 2022 GDG6: remote_host_ipv6=n/a
transmission    | Tue Mar  1 11:00:11 2022 ROUTE6: default_gateway=UNDEF
transmission    | Tue Mar  1 11:00:11 2022 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
transmission    | Tue Mar  1 11:00:11 2022 OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3
transmission    | Tue Mar  1 11:00:11 2022 TUN/TAP device tun0 opened
transmission    | Tue Mar  1 11:00:11 2022 TUN/TAP TX queue length set to 100
transmission    | Tue Mar  1 11:00:11 2022 /sbin/ip link set dev tun0 up mtu 1500
transmission    | Tue Mar  1 11:00:11 2022 /sbin/ip addr add dev tun0 10.1.111.16/24 broadcast 10.1.111.255
transmission    | Tue Mar  1 11:00:11 2022 /etc/openvpn/tunnelUp.sh tun0 1500 1555 10.1.111.16 255.255.255.0 init
transmission    | Up script executed with tun0 1500 1555 10.1.111.16 255.255.255.0 init
transmission    | Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.1.111.16
transmission    | Updating Transmission settings.json with values from env variables
transmission    | Using existing settings.json for Transmission /data/transmission-home/settings.json
transmission    | Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.1.111.16
transmission    | Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
transmission    | Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
transmission    | Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
transmission    | Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
transmission    | sed'ing True to true
transmission    | Enforcing ownership on transmission config directories
transmission    | Applying permissions to transmission config directories
transmission    | Setting owner for transmission paths to 1000:1000
transmission    | Setting permissions for download and incomplete directories
transmission    | Mask: 002
transmission    | Directories: 775
transmission    | Files: 664
transmission    | Setting permission for watch directory (775) and its files (664)
transmission    | 
transmission    | -------------------------------------
transmission    | Transmission will run as
transmission    | -------------------------------------
transmission    | User name:   abc
transmission    | User uid:    1000
transmission    | User gid:    1000
transmission    | -------------------------------------
transmission    | 
transmission    | STARTING TRANSMISSION
transmission    | Provider PIA has a script for automatic port forwarding. Will run it now.
transmission    | If you want to disable this, set environment variable DISABLE_PORT_UPDATER=true
transmission    | Transmission startup script complete.
transmission    | Tue Mar  1 11:00:11 2022 /sbin/ip route add 178.175.129.35/32 via 192.168.32.1
transmission    | Tue Mar  1 11:00:12 2022 /sbin/ip route add 0.0.0.0/1 via 10.1.111.1
transmission    | Tue Mar  1 11:00:12 2022 /sbin/ip route add 128.0.0.0/1 via 10.1.111.1
transmission    | Tue Mar  1 11:00:12 2022 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
transmission    | Tue Mar  1 11:00:12 2022 Initialization Sequence Completed
transmission    | Running functions for token based port fowarding
transmission    | Reserved Port: 25199  Tue Mar  1 11:00:22 CST 2022
transmission    | transmission auth not required
transmission    | waiting for transmission to become responsive
transmission    | transmission became responsive
<snip>
transmission    | Sum:           8.82 GB               0.0     0.0
transmission    | setting transmission port to 25199
transmission    | localhost:9091/transmission/rpc/ responded: "success"
transmission    | Checking port...
transmission    | Port is open: Yes
transmission    | #######################
transmission    |         SUCCESS        
transmission    | #######################
transmission    | Port: 25199
transmission    | Expiration Mon May  2 23:51:38 CDT 2022
transmission    | #######################
transmission    | Entering infinite while loop
transmission    | Every 15 minutes, check port status
transmission    | Reserved Port: 25199  Tue Mar  1 11:15:35 CST 2022

### HW/SW Environment

```markdown
- OS: Ubuntu 20.04
- Docker: 20.10.12
```

**Comment by pkishino** [comment]
can you give some more detail such as docker setup etc? how much resources are allocated etc

**Comment by pkishino** [comment]
e.g, mine are
```
Hostname | docker-desktop
-- | --
OS Information | linux x86_64 Docker Desktop
Kernel Version | 5.10.47-linuxkit
Total CPU | 2
Total memory | 2.1 GB
```
and with around 300 torrents loaded currently, mem is stable around 100mb used,cached varies between 500-1gig, cpu stable around 30-35%
running latest

**Comment by steveaggie** [comment]
Hostname | ubuntu
-- | --
OS Information | Ubuntu 20.04
Kernel Version | Linux 5.4.0-100-generic x86_64
Total CPU | 4
Total memory | 8 GB

**Comment by steveaggie** [comment]
![image](https://user-images.githubusercontent.com/20982357/156578560-f680277e-c0f8-46d7-84a0-f4627b343d99.png)

**Comment by pkishino** [comment]
I see quite a bit of fluctuations, not anywhere near constant 100% use. You could look into limiting resource usage but based on above I don’t see anything unusual. Do you see the same behavior with the container in isolation? Ie no other containers running and evtl. On a separate machine or bms?

**Comment by steveaggie** [comment]
Yeah, I don't think it's Transmission anymore.  Seems like it might be Nextcloud.  They seem to run ok separately but not together.    Still investigating, but we can close this out.

**Comment by arthurEspooner** [comment]
same issue here, woke up the past few mornings to CPU locked at 100% but all torrents were finished downloading hours before. stop the container and i got to 5% cpu.

just switching to a qbittorent/vpn image. too many issues with transmission itself and then this on top of it makes it a PI(T)A.
