### ISSUE TITLE
PIA Port Forwarding - Error Code 7

### ISSUE THREAD

**Issue by tscibilia** [haugene/docker-transmission-openvpn#220]
I recently (in the past few days have seen this port forwarding error in my logs). 
```
Using OpenVPN provider: PIA
Starting OpenVPN using config US East.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Mon Mar 13 16:06:51 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Mon Mar 13 16:06:51 2017 WARNING: file '/config/openvpn-credentials.txt' is group or others accessible
Mon Mar 13 16:06:51 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Mar 13 16:06:51 2017 UDPv4 link local: [undef]
Mon Mar 13 16:06:51 2017 UDPv4 link remote: [AF_INET]107.191.36.23:1198
Mon Mar 13 16:06:51 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Mar 13 16:06:51 2017 [05e5fc69b93ecdbf68aab97c46196213] Peer Connection Initiated with [AF_INET]107.191.36.23:1198
Mon Mar 13 16:06:53 2017 TUN/TAP device tun0 opened
Mon Mar 13 16:06:53 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Mon Mar 13 16:06:53 2017 /sbin/ip link set dev tun0 up mtu 1500
Mon Mar 13 16:06:53 2017 /sbin/ip addr add dev tun0 local 10.54.10.6 peer 10.54.10.5
Mon Mar 13 16:06:53 2017 /etc/transmission/start.sh tun0 1500 1558 10.54.10.6 10.54.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.54.10.6
Generating transmission settings.json from env variables

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Mon Mar 13 16:06:53 2017 Initialization Sequence Completed
curl encountered an error looking up new port: 7
Could not find new port from PIA
```

I tried other curl and ping commands and i have no trouble accessing the web, but i can't seem to get this port forwarding script to run correctly. I tried running it manually in the console but it returns the same error. Any ideas?
```
curl -f "http://209.222.18.222:2000/?client_id=fec1464ae47cf2a0a512f1d4bcd97510 2>/dev/null"
curl: (7) Failed to connect to 209.222.18.222 port 2000: Connection refused
```

**Comment by R0GGER** [comment]
Same issue here...

**Comment by condour** [comment]
Try a different region -- mine wasn't working for New York City but just started working for US East.

**Comment by joshuaja** [comment]
I'm running into the same error code here using multiple OPENVPN_CONFIG locations. Any ideas?

**Comment by joshuaja** [comment]
I ended up switching from the `latest` tag back to `1.15` and it seems to be working

**Comment by R0GGER** [comment]
> Try a different region -- mine wasn't working for New York City but just started working for US East.

Doesn't work...

**Comment by NickAnderegg** [comment]
For this to work, you need to connect to a region that supports port forwarding.

[Here is the post discussing the new API](https://www.privateinternetaccess.com/forum/discussion/23431/new-pia-port-forwarding-api)

If you look at the shell script that they provide, if the URL doesn't return a value, the resulting error message is as follows:

> Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding

The fact that only certain regions support port forwarding isn't news, but the fact that this Docker now requires a response from the port forwarding is. I've been using this Docker connected to US regions successfully for quite a while, so it just needs to be changed to not require port forwarding.

**Comment by haugene** [comment]
Added a couple of improvements in handling the startup-script and port update. Can also verify that I get `curl encountered an error looking up new port: 7` when connecting to US East. Using Netherlands as provider works however.

The changes are only available with the dev tag for now. Will be merged later.

Closing this issue, re-open if the problem persists.

**Comment by mkempster22** [comment]
I am getting this issue, I have tried multiple regions including Netherlands and Germany that support port forwarding, I am using the proxy container to access the WebUI



Sat Nov 11 15:22:01 2017 Initialization Sequence Completed
Generating new client id for PIA
Got new port 27940 from PIA
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 0: No Response
Sat Nov 11 15:24:08 2017 event_wait : Interrupted system call (code=4)
Sat Nov 11 15:24:08 2017 /sbin/ip addr del dev tun0 local 10.12.10.6 peer 10.12.10.5
Sat Nov 11 15:24:08 2017 /etc/transmission/stop.sh tun0 1500 1558 10.12.10.6 10.12.10.5 init
Sat Nov 11 15:24:09 2017 SIGTERM[hard,] received, process exiting
Using OpenVPN provider: PIA
Starting OpenVPN using config Germany.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Sat Nov 11 15:24:09 2017 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
Sat Nov 11 15:24:09 2017 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sat Nov 11 15:24:09 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Nov 11 15:24:09 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]169.50.62.114:1198
Sat Nov 11 15:24:09 2017 UDP link local: (not bound)
Sat Nov 11 15:24:09 2017 UDP link remote: [AF_INET]169.50.62.114:1198
Sat Nov 11 15:24:10 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Nov 11 15:24:10 2017 [5bc529047ecee750ddfdc569fb8db806] Peer Connection Initiated with [AF_INET]169.50.62.114:1198
Sat Nov 11 15:24:11 2017 TUN/TAP device tun0 opened
Sat Nov 11 15:24:11 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Sat Nov 11 15:24:11 2017 /sbin/ip link set dev tun0 up mtu 1500
Sat Nov 11 15:24:11 2017 /sbin/ip addr add dev tun0 local 10.4.10.6 peer 10.4.10.5
Sat Nov 11 15:24:11 2017 /etc/transmission/start.sh tun0 1500 1558 10.4.10.6 10.4.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.4.10.6
Generating transmission settings.json from env variables

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Sat Nov 11 15:24:11 2017 Initialization Sequence Completed
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 56

**Comment by nwesthoff** [comment]
Yep, getting same error as @mkempster22 
logs:
```
STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Mon Nov 13 12:34:28 2017 Initialization Sequence Completed
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 56
Mon Nov 13 12:36:00 2017 event_wait : Interrupted system call (code=4)
Mon Nov 13 12:36:00 2017 /sbin/ip addr del dev tun0 local 10.37.10.6 peer 10.37.10.5
Mon Nov 13 12:36:00 2017 /etc/transmission/stop.sh tun0 1500 1558 10.37.10.6 10.37.10.5 init
Mon Nov 13 12:36:00 2017 SIGTERM[hard,] received, process exiting
Using OpenVPN provider: PIA
Starting OpenVPN using config Netherlands.ovpn
Setting OPENVPN credentials...
2017/11/13 12:36:01 Command finished successfully.
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0
Mon Nov 13 12:36:01 2017 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
Mon Nov 13 12:36:01 2017 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Nov 13 12:36:01 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Nov 13 12:36:01 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]109.201.154.160:1198
Mon Nov 13 12:36:01 2017 UDP link local: (not bound)
Mon Nov 13 12:36:01 2017 UDP link remote: [AF_INET]109.201.154.160:1198
Mon Nov 13 12:36:01 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Nov 13 12:36:01 2017 [6197eb223694c146a4fde52a9f8f6768] Peer Connection Initiated with [AF_INET]109.201.154.160:1198
Mon Nov 13 12:36:02 2017 TUN/TAP device tun0 opened
Mon Nov 13 12:36:02 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Mon Nov 13 12:36:02 2017 /sbin/ip link set dev tun0 up mtu 1500
Mon Nov 13 12:36:02 2017 /sbin/ip addr add dev tun0 local 10.69.10.6 peer 10.69.10.5
Mon Nov 13 12:36:02 2017 /etc/transmission/start.sh tun0 1500 1558 10.69.10.6 10.69.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.69.10.6
Generating transmission settings.json from env variables
2017/11/13 12:36:02 Command finished successfully.
Setting owner for transmission paths to 1000:1000

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Mon Nov 13 12:36:02 2017 Initialization Sequence Completed
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 56
Mon Nov 13 12:37:11 2017 event_wait : Interrupted system call (code=4)
Mon Nov 13 12:37:11 2017 /sbin/ip addr del dev tun0 local 10.69.10.6 peer 10.69.10.5
Mon Nov 13 12:37:11 2017 /etc/transmission/stop.sh tun0 1500 1558 10.69.10.6 10.69.10.5 init
Mon Nov 13 12:37:11 2017 SIGTERM[hard,] received, process exiting
Using OpenVPN provider: PIA
Starting OpenVPN using config Netherlands.ovpn
Setting OPENVPN credentials...
2017/11/13 12:37:11 Command finished successfully.
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0
Mon Nov 13 12:37:11 2017 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
Mon Nov 13 12:37:11 2017 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Nov 13 12:37:11 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Nov 13 12:37:11 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]109.201.154.160:1198
Mon Nov 13 12:37:11 2017 UDP link local: (not bound)
Mon Nov 13 12:37:11 2017 UDP link remote: [AF_INET]109.201.154.160:1198
Mon Nov 13 12:37:11 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Nov 13 12:37:11 2017 [6197eb223694c146a4fde52a9f8f6768] Peer Connection Initiated with [AF_INET]109.201.154.160:1198
Mon Nov 13 12:37:13 2017 TUN/TAP device tun0 opened
Mon Nov 13 12:37:13 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Mon Nov 13 12:37:13 2017 /sbin/ip link set dev tun0 up mtu 1500
Mon Nov 13 12:37:13 2017 /sbin/ip addr add dev tun0 local 10.36.10.6 peer 10.36.10.5
Mon Nov 13 12:37:13 2017 /etc/transmission/start.sh tun0 1500 1558 10.36.10.6 10.36.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.36.10.6
Generating transmission settings.json from env variables
2017/11/13 12:37:13 Command finished successfully.
Setting owner for transmission paths to 1000:1000

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Mon Nov 13 12:37:13 2017 Initialization Sequence Completed
Got new port 35438 from PIA
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Port is open: Yes
```
Sometimes it works, sometimes it doesn't. I'm on Netherlands as well. I can't connect to any peers if it doesn't find a port.

**Comment by nicbou** [comment]
This keeps happening to me too. I'm afraid I have no other information to add.

**Comment by grostim** [comment]
Same issue here. 

> transmission-openvpn_1  | Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
> transmission-openvpn_1  | curl encountered an error looking up new port: 56

I a using the Netherlands server
