### ISSUE TITLE
Error 502 when trying to access to web UI or rpc by transmission-openvpn-proxy

### ISSUE THREAD

**Issue by Glingling** [haugene/docker-transmission-openvpn#2208]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

  transmission:
    container_name: Transmission
    ports:
      - 9091:9091
    volumes:
      - transmission_config:/config
      - /media/Bobo4TO/Downloads:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OPENVPN_PASSWORD=MYPASS
      - OPENVPN_PROVIDER=PUREVPN
      - OPENVPN_USERNAME=MYUSER
      - TRANSMISSION_WEB_UI=combustion
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_PASSWORD=PASS
      - TRANSMISSION_RPC_PORT=9091
      - TRANSMISSION_RPC_USERNAME=ME
      - TRANSMISSION_DOWNLOAD_DIR=/data
      - OPENVPN_CONFIG='at2-ovpn-udp, gr2-ovpn-udp, tw2-ovpn-udp, ussf2-ovpn-udp, uk-obf-udp, au-sd2-ovpn-udp, hk2-ovpn-udp, ustx2-ovpn-udp, ukg2-ovpn-udp, au2-ovpn-udp, in2-ovpn-udp, usut2-ovpn-udp, ukl2-ovpn-udp, au2-pe-ovpn-udp, it2-ovpn-udp, usva2-ovpn-udp, ukm2-ovpn-udp, br2-ovpn-udp, jp2-ovpn-udp, uswdc2-ovpn-udp, us2-ovpn-udp, ca2-ovpn-udp, kr2-ovpn-udp, vlap-ph2-ovpn-udp, usfl2-ovpn-udp, cav2-ovpn-udp, my2-ovpn-udp, vlap-th2-ovpn-udp, usga2-ovpn-udp, ch2-ovpn-udp, nl2-ovpn-udp, vlap-vn2-ovpn-udp, p2p-udp, usil2-ovpn-udp, cz2-ovpn-udp, usla2-ovpn, vleu-be2-ovpn-udp, pl2-ovpn-udp, usla2-ovpn-udp, de2-ovpn-udp, vleu-no2-ovpn-udp, pt2-ovpn-udp, usnj2-ovpn-udp, vlus-mx2-ovpn-udp, dk2-ovpn-udp, ru2-ovpn-udp, usny2-ovpn-udp, vlus-pa2-ovpn-udp, es2-ovpn-udp, se2-ovpn-udp, usphx2-ovpn-udp, za2-ovpn-udp, fr2-ovpn-udp, sg2-ovpn-udp, ussa2-ovpn-udp'
      - LOCAL_NETWORK="192.168.1.0/24"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 8.8.8.8
      - 8.8.4.4
    logging:
      driver: json-file
      options:
        max-size: 10m
    image: haugene/transmission-openvpn
    networks: 
      - traefik
  
  transmission_proxy:
    container_name: Transmission_proxy
    restart : unless-stopped
    image: haugene/transmission-openvpn-proxy
    links:
      - transmission:transmission
    ports:
      - 8081:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.http.routers.transmission-proxy-http.rule: Host(`transmission-proxy.someurl`)
      traefik.http.routers.transmission-proxy-http.entryPoints: insecure
      traefik.http.routers.transmission-proxy-https.rule: "Host(`transmission-proxy.someurl`)"
      traefik.http.routers.transmission-proxy-http.middlewares: https-redirect@file
      traefik.http.routers.transmission-proxy-https.entrypoints: "secure"
      traefik.http.routers.transmission-proxy-https.middlewares: "security@file, compression@file"
      traefik.http.routers.transmission-proxy-https.service: "transmission-proxy-serverparisdocker"
      traefik.http.services.transmission-proxy-serverparisdocker.loadbalancer.server.port: "8080"
      traefik.http.routers.transmission-proxy-https.tls: "true"
      traefik.http.routers.transmission-proxy-https.tls.certresolver: "letsencrypt"
    networks: 
      - traefik

### Current Behavior

The docker and the vpn connect to the VPN provider.
I have an IP from the VPN provider.

When I try to access to the web UI or when I pass by the android app transmission, I have a 502 Bad Gateway.
I have this on the proxy container log : 
2022/03/04 18:16:30 [error] 24#24: *106 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.36, server: , request: "GET /transmission/rpc/ HTTP/1.1", upstream: "http://172.18.0.8:9091/transmission/rpc/", host: "192.168.1.26:8081", referrer: "http://192.168.1.26:8081/transmission/rpc/"

I can't add or delete torrents.... 

### Expected Behavior

Acces to Web UI and/or by the android app transmission 

### How have you tried to solve the problem?

1) Switch version 3.6,3.7,4.0,dev
2) Debug my server network 
3) change port
4) pray..

### Log output

From transmission-openvpn-proxy :
192.168.1.27 - baudouin [04/Mar/2022:18:24:54 +0100] "POST /transmission/rpc HTTP/1.1" 502 157 "-" "Google-HTTP-Java-Client/1.22.0 (gzip)"
2022/03/04 18:24:55 [error] 24#24: *111 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.27, server: , request: "POST /transmission/rpc HTTP/1.1", upstream: "http://172.18.0.8:9091/transmission/rpc", host: "192.168.1.26:8081"
192.168.1.27 - baudouin [04/Mar/2022:18:24:55 +0100] "POST /transmission/rpc HTTP/1.1" 502 157 "-" "Google-HTTP-Java-Client/1.22.0 (gzip)"
2022/03/04 18:24:56 [error] 24#24: *111 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.27, server: , request: "POST /transmission/rpc HTTP/1.1", upstream: "http://172.18.0.8:9091/transmission/rpc", host: "192.168.1.26:8081"
192.168.1.27 - baudouin [04/Mar/2022:18:24:56 +0100] "POST /transmission/rpc HTTP/1.1" 502 157 "-" "Google-HTTP-Java-Client/1.22.0 (gzip)"

From transmission-openvpn :
Starting container with revision: 8cc1870cc039201e0e2f8b7684a9f4e96ae03ab9
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PUREVPN
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for PUREVPN. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.4lFWX2dtVS
Extracting configs to /tmp/tmp.oRl7poBnAo
Found configs for PUREVPN in /tmp/tmp.oRl7poBnAo/vpn-configs-contrib-main/openvpn/purevpn, will replace current content in /etc/openvpn/purevpn
Cleanup: deleting /tmp/tmp.4lFWX2dtVS and /tmp/tmp.oRl7poBnAo
55 servers found in OPENVPN_CONFIG, usva2-ovpn-udp chosen randomly
Starting OpenVPN using config usva2-ovpn-udp.ovpn
Modifying /etc/openvpn/purevpn/usva2-ovpn-udp.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Setting OpenVPN credentials...
adding route to local network "192.168.1.0/24" via 172.18.0.1 dev eth0
Error: any valid prefix is expected rather than ""192.168.1.0/24"".
Fri Mar  4 17:59:37 2022 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Fri Mar  4 17:59:37 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Fri Mar  4 17:59:37 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Mar  4 17:59:37 2022 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Fri Mar  4 17:59:37 2022 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Fri Mar  4 17:59:37 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]37.221.173.211:1194
Fri Mar  4 17:59:37 2022 Socket Buffers: R=[212992->212992] S=[212992->212992]
Fri Mar  4 17:59:37 2022 UDP link local: (not bound)
Fri Mar  4 17:59:37 2022 UDP link remote: [AF_INET]37.221.173.211:1194
Fri Mar  4 17:59:37 2022 TLS: Initial packet from [AF_INET]37.221.173.211:1194, sid=8d23be91 5032e959
Fri Mar  4 17:59:37 2022 VERIFY OK: depth=1, C=HK, ST=Central, L=HK, O=Secure-ServerCA, OU=IT, CN=Secure-ServerCA, name=Secure-ServerCA, emailAddress=mail@host.domain
Fri Mar  4 17:59:37 2022 VERIFY KU OK
Fri Mar  4 17:59:37 2022 Validating certificate extended key usage
Fri Mar  4 17:59:37 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Fri Mar  4 17:59:37 2022 VERIFY EKU OK
Fri Mar  4 17:59:37 2022 VERIFY OK: depth=0, C=HK, ST=Central, L=HK, O=Secure-Server, OU=IT, CN=Secure-Server, name=changeme, emailAddress=mail@host.domain
Fri Mar  4 17:59:37 2022 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1558', remote='link-mtu 1550'
Fri Mar  4 17:59:37 2022 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'
Fri Mar  4 17:59:37 2022 WARNING: 'auth' is used inconsistently, local='auth SHA1', remote='auth [null-digest]'
Fri Mar  4 17:59:37 2022 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA
Fri Mar  4 17:59:37 2022 [Secure-Server] Peer Connection Initiated with [AF_INET]37.221.173.211:1194
Fri Mar  4 17:59:39 2022 SENT CONTROL [Secure-Server]: 'PUSH_REQUEST' (status=1)
Fri Mar  4 17:59:39 2022 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 172.94.28.3,dhcp-option DNS 172.94.28.5,sndbuf 393216,rcvbuf 393216,comp-lzo no,route-gateway 172.94.28.225,topology subnet,ping 10,ping-restart 120,ifconfig 172.94.28.228 255.255.255.224,peer-id 2,cipher AES-256-GCM'
Fri Mar  4 17:59:39 2022 OPTIONS IMPORT: timers and/or timeouts modified
Fri Mar  4 17:59:39 2022 OPTIONS IMPORT: compression parms modified
Fri Mar  4 17:59:39 2022 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Fri Mar  4 17:59:39 2022 Socket Buffers: R=[212992->425984] S=[212992->425984]
Fri Mar  4 17:59:39 2022 OPTIONS IMPORT: --ifconfig/up options modified
Fri Mar  4 17:59:39 2022 OPTIONS IMPORT: route options modified
Fri Mar  4 17:59:39 2022 OPTIONS IMPORT: route-related options modified
Fri Mar  4 17:59:39 2022 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Fri Mar  4 17:59:39 2022 OPTIONS IMPORT: peer-id set
Fri Mar  4 17:59:39 2022 OPTIONS IMPORT: adjusting link_mtu to 1625
Fri Mar  4 17:59:39 2022 OPTIONS IMPORT: data channel crypto options modified
Fri Mar  4 17:59:39 2022 Data Channel: using negotiated cipher 'AES-256-GCM'
Fri Mar  4 17:59:39 2022 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Mar  4 17:59:39 2022 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Mar  4 17:59:39 2022 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:12:00:08
Fri Mar  4 17:59:39 2022 TUN/TAP device tun0 opened
Fri Mar  4 17:59:39 2022 TUN/TAP TX queue length set to 100
Fri Mar  4 17:59:39 2022 /sbin/ip link set dev tun0 up mtu 1500
Fri Mar  4 17:59:39 2022 /sbin/ip addr add dev tun0 172.94.28.228/27 broadcast 172.94.28.255
Fri Mar  4 17:59:39 2022 /etc/openvpn/tunnelUp.sh tun0 1500 1553 172.94.28.228 255.255.255.224 init
Up script executed with tun0 1500 1553 172.94.28.228 255.255.255.224 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 172.94.28.228
Using Combustion UI, overriding TRANSMISSION_WEB_HOME
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 172.94.28.228
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding incomplete-dir-enabled because TRANSMISSION_INCOMPLETE_DIR_ENABLED is set to false
Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to true
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to ME
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
-------------------------------------'
Transmission will run as
-------------------------------------'
User name:   root
User uid:    0
User gid:    0
-------------------------------------'
STARTING TRANSMISSION
Transmission startup script complete.
Fri Mar  4 17:59:41 2022 /sbin/ip route add 37.221.173.211/32 via 172.18.0.1
Fri Mar  4 17:59:41 2022 /sbin/ip route add 0.0.0.0/1 via 172.94.28.225
Fri Mar  4 17:59:41 2022 /sbin/ip route add 128.0.0.0/1 via 172.94.28.225
Fri Mar  4 17:59:41 2022 Initialization Sequence Completed

### HW/SW Environment

```markdown
- OS: Debian 11 up to date
- Docker: 20.10.12
```

**Comment by edgd1er** [comment]
Thank you for giving all details, it is much easier to see what could be wrong.
openvpn and transmission are running ok. the problem is with the proxy.
I think your traefik.http.services.transmission-proxy-serverparisdocker.loadbalancer.server.port: `"8080"` should be set to `9091`, the transmission port.

**Comment by Glingling** [comment]
Hello thank you for your answer. I try but nothing change. I try local of things on my local network without passing by treafik !

**Comment by pkishino** [comment]
Your LOCAL_NETWORK is wrong..
check the logs again
```
Error: any valid prefix is expected rather than ""192.168.1.0/24"".
```
you added " to the valued :/

**Comment by Glingling** [comment]
Thanks you I remove the "" the error doesn't appear but still error 502 from the transmission-proxy :
```
192.168.1.127 - - [08/Mar/2022:14:27:40 +0100] "GET /favicon.ico HTTP/1.1" 502 559 "http://192.168.1.26:8081/transmission/rpc/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36"
```

**Comment by Glingling** [comment]
The first log from the transmission-proxy 
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```
and from logs transmission after adding the LOG_TO_STDOUT=true env : 
```
[2022-03-08 15:12:34.512] Transmission 2.94 (d8e60ee44f) started (session.c:740)
[2022-03-08 15:12:34.512] RPC Server Adding address to whitelist: 192.168.1.* (rpc-server.c:971)
[2022-03-08 15:12:34.512] RPC Server Adding address to whitelist: 172.18.*.* (rpc-server.c:971)
[2022-03-08 15:12:34.512] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
[2022-03-08 15:12:34.512] Port Forwarding Stopped (port-forwarding.c:180)
[2022-03-08 15:12:34.512] DHT Reusing old id (tr-dht.c:307)
[2022-03-08 15:12:34.512] DHT Bootstrapping from 63 IPv4 nodes (tr-dht.c:156)
[2022-03-08 15:12:34.512] Using settings from "/data/transmission-home" (daemon.c:528)
[2022-03-08 15:12:34.512] Saved "/data/transmission-home/settings.json" (variant.c:1266)
```
Same error 502.... from : 
- http://my-host:8081
- http://my-host:8081/transmission/
- http://my-host:8081/transmission/rpc/

And ERR_CONNECTION_REFUSED
- http://192.168.1.26:9091/
- http://192.168.1.26:9091/transmission/
- http://192.168.1.26:9091/transmission/rpc/

**Comment by edgd1er** [comment]
your logs are not alike the ones I see. somewhere I would expect something like:
transmission  | Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.3.7

but your are showing:
RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)

I'm afraid you got mixed in image names and are using another one.

Listening to localhost won't allow remote access, unless you have set up something particuliar.

**Comment by Glingling** [comment]
I find my problem... 
So on my conf I save the conf on /data/transmission-home and that is on the HDD in my server so I remove the transmission-home directory, reboot the docker and that work perfectly !

Sorry it's my fault ! 
Thanks for your help !
