### ISSUE TITLE
Problem CUSTOM provider

### ISSUE THREAD

**Issue by Jacopx** [haugene/docker-transmission-openvpn#223]
Hi, i'm trying to run this container with my AirVPN profile on my FreeNAS system... I've set a volume that point from my .ovpn downloaded from AirVPN to /etc/openvpn/custom/default.ovpn in my server. I have set:

OPENVPN_USERNAME="user of airvpn"
OPENVPN_PASSWORD="password of airvpn"
OPENVPN_PROVIDER=CUSTOM

My logs report this:
`ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)`

I don't understand where i'm wrong! :/

**Comment by rati0nal** [comment]
I'm having the same issue on FreeNAS, but I know others have it working. Just looking for a little clarification.

**Comment by Jacopx** [comment]
@rati0nal Thanks! 👍🏻

**Comment by Jacopx** [comment]
I have solved the problem checking the PRIVILEDG options in my system. Thanks! 👍🏻
