### ISSUE TITLE
Docker image digests don't match the ones in Docker Hub

### ISSUE THREAD

**Issue by alexvy86** [haugene/docker-transmission-openvpn#2241]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

N/A

### Current Behavior

The docker image digests I'm getting with `docker pull` do not match the ones in Docker Hub. I tried to understand why this could be but didn't find an explanation, if I'm missing something that explains it I'd be happy to close this issue.

### Expected Behavior

The image digests I get after running `docker pull` match the ones in Docker Hub.

### How have you tried to solve the problem?

N/A

### Log output

```
docker images "haugene/transmission-openvpn" --digests --all

REPOSITORY                     TAG       DIGEST                                                                    IMAGE ID       CREATED        SIZE
haugene/transmission-openvpn   latest    sha256:8fbca248dbb0ec68fda347c82a95776f6f967df3fc610f25791532df842ab04a   42536b71f066   7 weeks ago    265MB
haugene/transmission-openvpn   4.0       sha256:059216cfae4bfc9db6c93ddc0c0834d5d09ca97fe2eaab6b4094ebc8ad686829   c8ef207ebe9e   7 months ago   265MB
```

This is on a Raspberry Pi 4, ARM64.

From https://hub.docker.com/r/haugene/transmission-openvpn/tags:

![image](https://user-images.githubusercontent.com/716334/162603120-2c89d77b-512e-482d-a3ef-514be54a897d.png)

![image](https://user-images.githubusercontent.com/716334/162603123-f7c9ded4-a2dd-4461-b524-37513f750730.png)

### HW/SW Environment

```markdown
- OS: RaspberryPi OS
- Docker: Docker 20.10.12, build e91ed57
```

**Comment by pkishino** [comment]
See here https://github.com/docker/hub-feedback/issues/1925
Nothing to do on our end
