### ISSUE TITLE
ERR: neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Auth Username:'

### ISSUE THREAD

**Issue by Nathan1258** [haugene/docker-transmission-openvpn#2243]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/home/nathane/torrent-vpn/:/data'
            - '/home/nathane/torrent-vpn/config/openvpn/config.ovpn:/etc/openvpn/custom/default.ovpn'
        environment:
            - OPENVPN_PROVIDER=custom
            - OPENVPN_USERNAME=<username>
            - OPENVPN_PASSWORD=<password>
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

### Current Behavior

Try running with above docker-compose file, I use hotspotsheild so I can use a custom openvpn file that they give me to connect:

`neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Auth Username:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.
`

### Expected Behavior

Not sure, I guess hopefully connect? First time using this.

### How have you tried to solve the problem?

The .ovpn file is valid and is in the right location when the docker container has started, not sure what else would or could be the problem?

### Log output

transmission-openvpn_1  | Starting container with revision: 8cc1870cc039201e0e2f8b7684a9f4e96ae03ab9
transmission-openvpn_1  | Creating TUN device /dev/net/tun
transmission-openvpn_1  | Using OpenVPN provider: CUSTOM
transmission-openvpn_1  | Running with VPN_CONFIG_SOURCE auto
transmission-openvpn_1  | No bundled config script found for CUSTOM. Defaulting to external config
transmission-openvpn_1  | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.QlnU2Rm7Cp
transmission-openvpn_1  | Extracting configs to /tmp/tmp.JdNyPB92LX
transmission-openvpn_1  | ERROR: Could not find any configs for provider CUSTOM in downloaded configs
transmission-openvpn_1  | Cleanup: deleting /tmp/tmp.QlnU2Rm7Cp and /tmp/tmp.JdNyPB92LX
transmission-openvpn_1  | No VPN configuration provided. Using default.
transmission-openvpn_1  | Modifying /etc/openvpn/custom/default.ovpn for best behaviour in this container
transmission-openvpn_1  | Modification: Point auth-user-pass option to the username/password file
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sedHfg8Ok: Device or resource busy
transmission-openvpn_1  | Modification: Change ca certificate path
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sed5tpaXr: Device or resource busy
transmission-openvpn_1  | Modification: Change ping options
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sedjCXiYv: Device or resource busy
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sed7oTW6C: Device or resource busy
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sedFK3O9G: Device or resource busy
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sedWIUWrL: Device or resource busy
transmission-openvpn_1  | Modification: Update/set resolv-retry to 15 seconds
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sede8otjP: Device or resource busy
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sediBNjjU: Device or resource busy
transmission-openvpn_1  | Modification: Change tls-crypt keyfile path
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sedYPqzE5: Device or resource busy
transmission-openvpn_1  | Modification: Set output verbosity to 3
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sedhUX0e9: Device or resource busy
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sedwYXshg: Device or resource busy
transmission-openvpn_1  | Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sed87yNNk: Device or resource busy
transmission-openvpn_1  | sed: cannot rename /etc/openvpn/custom/sedYVyyFm: Device or resource busy
transmission-openvpn_1  | Setting OpenVPN credentials...
transmission-openvpn_1  | adding route to local network 192.168.0.0/16 via 172.23.0.1 dev eth0
transmission-openvpn_1  | Mon Apr 11 21:34:38 2022 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
transmission-openvpn_1  | Mon Apr 11 21:34:38 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
transmission-openvpn_1  | Mon Apr 11 21:34:38 2022 neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Auth Username:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.
transmission-openvpn_1  | Mon Apr 11 21:34:38 2022 Exiting due to fatal error
torrent-vpn_transmission-openvpn_1 exited with code 1

### HW/SW Environment

```markdown
- OS:Ubuntu Server LTS18
- Docker: Docker version 20.10.5, build 55c4c88
```

**Comment by pkishino** [comment]
please read the wiki
it's asking to input username and password but that doesn't work here..yu need to either change the ovpn file to read the auth details from file (as per the documentation for this container) or allow the permissions so the container scripts can fix your ovpn file (which it can't as per above log)

**Comment by Nathan1258** [comment]
@pkishino the details are in the file

**Comment by Nathan1258** [comment]
@pkishino how does one give permissions? all the errors I get are the fact the resource is busy, not that permission is denied.

**Comment by pkishino** [comment]
your container doesn't have permissions to edit the file,
check permissions of the ovpn file and what user is running the docker process ..
also, check that no other process has the ovpn file open as sed is trying to do an inplace edit
