### ISSUE TITLE
sigterm not being caught on reboot

### ISSUE THREAD

**Issue by lucserre** [haugene/docker-transmission-openvpn#2246]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - ./data:/data
            - /mnt/Media:/media
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=ca_toronto
            - OPENVPN_USERNAME=xxxxx
            - OPENVPN_PASSWORD=xxxxxxxxxxx
            - DROP_DEFAULT_ROUTE=true
            - LOCAL_NETWORK=192.168.1.0/24
            - TZ=America/Detroit
            - TRANSMISSION_DOWNLOAD_DIR=/media/torrents/complete
            - TRANSMISSION_INCOMPLETE_DIR=/media/torrents/incomplete
            - TRANSMISSION_WATCH_DIR=/media/torrents/watch
            - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
        restart: unless-stopped

### Current Behavior

Everything works, until I try to reboot. It hangs at shutdown for several (5+) minutes.
Seems not to be listening to the SIGTERM or SIGKILL signals being sent to it.
Using Debian 11.
When I reboot or shutdown the system, while the docker container is running:
I get this first one for about 3-4 minutes
 `systemd-shutdown[1]: Waiting for process: containerd-shim, dumb-init`
and then this one for an other 3-4 minutes.
`systemd-shutdown[1]: Waiting for process: dumb-init`

### Expected Behavior

SIGTERM signal to gracefully terminate the container.

### How have you tried to solve the problem?

updated to latest version
tried on new OS (new debian11 vm)

### Log output

log output in description

### HW/SW Environment

```markdown
- OS: Debian11
- Docker: whatever version is the latest on the debian servers
```

**Comment by darmach** [comment]
@lucserre Would you reopen this? I'm running into this on proxmox vm running ubuntu - proxmox reboots wait for the VM to shutdown, which in turn waits for dumb-init till it decides to kill it.

**Comment by darmach** [comment]
@haugene Could we reopen this? I run into this on Proxmox, and it considerably slows down hypervisor reboot. Which in case of transmission is not a tragedy - but in the meantime all the other VMs are already down, so I get longer downtime on everything on the hypervisor the transmission is on.
