### ISSUE TITLE
Custom provider: nameserver not set

### ISSUE THREAD

**Issue by grOGH** [haugene/docker-transmission-openvpn#225]
Running the docker image with the following command line:

`docker run --privileged -d --name transmission -v /mnt/ext/.downloads/transmission:/data -v /etc/localtime:/etc/localtime:ro -v /opt/transmission:/etc/openvpn/custom -e "OPENVPN_PROVIDER=CUSTOM" -p 9091:9091 -e PUID=1000 -e PGID=1000 -e "OPENVPN_USERNAME=" -e "OPENVPN_PASSWORD=" -e "TRANSMISSION_PEER_PORT=29454" haugene/transmission-openvpn:latest`

The custom provider ovpn looks like this:

```
client

dev tun0

proto udp
#proto udp
#proto tcp

link-mtu 1558

remote de.mullvad.net 1300
cipher AES-256-CBC

# Tunnel IPv6 traffic as well as IPv4
#tun-ipv6
# Keep trying indefinitely to resolve the
# host name of the OpenVPN server.  Very useful
# on machines which are not permanently connected
# to the internet such as laptops.
resolv-retry infinite

# Most clients don't need to bind to
# a specific local port number.
nobind

# Try to preserve some state across restarts.
#persist-key
#persist-tun

# Enable compression on the VPN link.
comp-lzo

# Set log file verbosity.
verb 3

remote-cert-tls server

ping-restart 60

# Allow calling of built-in executables and user-defined scripts.
script-security 2

# Parses DHCP options from openvpn to update resolv.conf
#up /etc/openvpn/update-resolv-conf
#down /etc/openvpn/update-resolv-conf

ping 10

ca /etc/openvpn/custom/ca.crt
cert /etc/openvpn/custom/mullvad.crt
key /etc/openvpn/custom/mullvad.key

crl-verify /etc/openvpn/custom/crl.pem

# Limit range of possible TLS cipher-suites
tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA:TLS-DHE-RSA-WITH-CAMELLIA-256-CBC-SHA:TLS-DHE-RSA-WITH-AES-128-CBC-SHA:TLS-DHE-RSA-WITH-SEED-CBC-SHA:TLS-DHE-RSA-WITH-CAMELLIA-128-CBC-SHA
```

The file supplies its own up/down script (update-resolv-conf) which is overwritten by the hardcoded params in the docker startup script.

However, the nameserver is not set after successfully connecting via openvpn, resulting in Transmission being unable to connect to any host. The resolv.conf contains the internal DNS of my network, which obviously cant be reached over VPN. Once I manually set a public nameserver in resolv.conf, Transmission works fine.

Even manually calling the update-resolv-conf (both the docker included and the one provided by the VPN) don't update the nameserver.

Is this a bug with the handling of custom providers or is something wrong on my end?

**Comment by bspinner** [comment]
Not sure, whether using an non-custom provider fixes this, but I've had the same problem - also using a custom provider.

I fixed it by
- Add a volume for custom scripts (can be readonly), e.g. to `/scripts`
- Add a script, that calls `update-resolv-conf` and then the normal script (see below)
- Overrride the default `--up` and `--down` scripts by adding the following line to the custom `default.ovpn` (see below)
- Replacing `resolvconf` by `openresolv` (`apt-get update && apt-get install openresolv`)

The last step was necessary for me. Not sure whether [masterkorps](https://github.com/masterkorp/openvpn-update-resolv-conf#usage) repo is the source, but there it's even listed as a dependency.

# My `start-stop.sh`
```bash
#!/bin/bash
# Sourcing everything, so variables are available in called scripts
# The paranthesis starts a subshell, so no modifications will be made to our variables (see http://stackoverflow.com/a/28490273)

# Call update-resolv-conf for updated /etc/resolv.conf
# It checks for script_type itself
( . /etc/openvpn/update-resolv-conf ) 

# Call everthing else

case "$script_type" in
    up)
        ( . /etc/transmission/start.sh )
        ;;
    down)
        ( . /etc/transmission/stop.sh )
        ;;
esac
```

# OVPN example
Just add the following lines at the very end of your `.ovpn` file
```
# script-security 2 isn't necessary, since already set in the openvpn start script

up /scripts/start-stop.sh

down /scripts/start-stop.sh
```

**Comment by MartinTerp** [comment]
This didt do it for me, i just tried to hardconf my router as a dns source in the resolvconf.conf to see if that helps

**Comment by haugene** [comment]
Multiple issues here. In the docker run command in the initial description of this issue the --dns flags are not provided, that is the usual fix for this.

Then we have the issue of dns after reconnect. And the update-resolv-conf from the provider. Don't know if this is still an issue. Closing for now, re-open or create a new issue with suggestions for improvements if needed.

There is also a new feature for custom pre/post scripts, maybe the update statement could be added there as well.
