### ISSUE TITLE
PIA provider cannot find certificates

### ISSUE THREAD

**Issue by joeknock90** [haugene/docker-transmission-openvpn#226]
Running in FreeNAS with the following

volumes:
/mnt/Data/Docker/transmission/openvpn:/etc/openvpn
/mnt/Data/Docker/transmission/data:/data
/mnt/Data/Docker/transmission/config:/config
/mnt/Data/Docker/transmission/scripts:/scripts

environment:
OPENVPN_PROVIDER=PIA
OPENVPN_USERNAME=usernamehere
OPENVPN_PASSWORD=passwordhere
OPENVPN_CONFIG=thespecificonehere
LAN_NETWORK=[LAN IP]/24

I was forced to pre-populate /mnt/Data/Docker/transmission/openvpn with the pia folder, as well as the start.sh script (for some reason those files were not downloaded automatically). Before that i was given the error "[dumb-init] /etc/openvpn/start.sh: No such file or directory"

After populating the directory I get the following:

Using OpenVPN provider: PIA                                                                                                                    
Starting OpenVPN using config [I don't want to tell you my gateway].ovpn                                                                                            
Setting OPENVPN credentials...                                                                                                                 
Options error: --ca fails with 'ca.rsa.2048.crt': No such file or directory                                                                    
Options error: --crl-verify fails with 'crl.rsa.2048.pem': No such file or directory                                                           
Options error: Please correct these errors.                                                                                                    
Use --help for more information. 

The files are there and all of the proper permissions are in order. Can't seem to see the certs either way.

**Comment by joeknock90** [comment]
Ok I don't know why I didn't think of this before but it seems that when I set the full path in the .ovpn file it works. Now I'm running into a different issue with the script being unable to read credentials from STDIN...

**Comment by haugene** [comment]
Why are you mounting folders to /etc/openvpn and /config? If these directories exist on your host you will override all the setup and configurations this container provides. And what is /scripts?

Try doing this with a minimal setup, **only** mounting a folder for /data. Then skip the OPENVPN_CONFIG parameter, it will choose a default one. And you need to specify LOCAL_NETWORK to access it from your host, not LAN_NETWORK.

Try that and post your run command and logs if it doesn't work.

**Comment by haugene** [comment]
Have a look at #230
