### ISSUE TITLE
PIA ovpn port numbers 1198 instead of 1194 

### ISSUE THREAD

**Issue by btuysser** [haugene/docker-transmission-openvpn#227]
Hi, 

Thanks for doing this!! My container running on a Synology keeps stopping with the following log : 

Using OpenVPN provider: PIA
Starting OpenVPN using config Netherlands.ovpn
Setting OPENVPN credentials...
adding route to local network 10.11.11.0/24 via 172.17.0.1 dev eth0
Sat Apr  1 00:41:36 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Sat Apr  1 00:41:36 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Apr  1 00:41:36 2017 UDPv4 link local: [undef]
Sat Apr  1 00:41:36 2017 UDPv4 link remote: [AF_INET]109.201.154.169:1198
Sat Apr  1 00:41:37 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Apr  1 00:41:37 2017 [b495a201c2a8dcbd462481107200f96d] Peer Connection Initiated with [AF_INET]109.201.154.169:1198
Sat Apr  1 00:41:40 2017 AUTH: Received control message: AUTH_FAILED
Sat Apr  1 00:41:40 2017 SIGTERM[soft,auth-failure] received, process exiting

I do have /dev/net/tun setup. 

Looking at https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/pia/Netherlands.ovpn I see that the port is set to 1198. With the vpn client running on my Synology natively I can only connect on 1194. This is true for other PIA servers as well.

Do you have any suggestions? 

Thanks,
   Bijan

**Comment by haugene** [comment]
Hi, 

This doesn't look to be a port issue to me. Your connection is set up correctly to the VPN server, but it shuts you out with a AUTH_FAILED. Are you using the correct credentials?

Using PIA it's not the same username/password used to log in with the windows client etc. You need to log in and find `PPTP/L2TP/SOCKS Username and Password`. You might already know this, in which case you should double-check that the credentials are passed correctly to the container. If you ssh into the NAS and then exec into the container you can check the contents of `/config/openvpn-credentials.txt`.

**Comment by btuysser** [comment]
I restarted the container and it seems to work now. Same command line.
