### ISSUE TITLE
RTNETLINK answers: File exists

### ISSUE THREAD

**Issue by astaplet** [haugene/docker-transmission-openvpn#2286]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

<img width="627" alt="Screen Shot 2022-06-25 at 8 28 33 PM" src="https://user-images.githubusercontent.com/17838229/175798213-cc313f66-e1da-4ee4-a09b-15881e9d920f.png">
<img width="597" alt="Screen Shot 2022-06-25 at 8 28 50 PM" src="https://user-images.githubusercontent.com/17838229/175798214-ed80ba9a-69aa-4e62-9b66-3f617a1203a3.png">
<img width="610" alt="Screen Shot 2022-06-25 at 8 28 59 PM" src="https://user-images.githubusercontent.com/17838229/175798217-26e0115d-0615-4b96-881b-b74988d41f1e.png">

### Current Behavior

I receive the following error upon startup:
`

STARTING TRANSMISSION

Transmission startup script complete.

Sun Jun 26 03:24:44 2022 /sbin/ip route add 193.29.107.19/32 via 172.17.0.1

Sun Jun 26 03:24:44 2022 /sbin/ip route add 0.0.0.0/1 via 10.196.1.33

Sun Jun 26 03:24:44 2022 /sbin/ip route add 128.0.0.0/1 via 10.196.1.33

Sun Jun 26 03:24:44 2022 /sbin/ip route add 10.196.0.1/32 via 10.196.1.33

RTNETLINK answers: File exists

Sun Jun 26 03:24:44 2022 ERROR: Linux route add command failed: external program exited with error status: 2

Sun Jun 26 03:24:44 2022 Initialization Sequence Completed

Sun Jun 26 03:28:07 2022 event_wait : Interrupted system call (code=4)

Sun Jun 26 03:28:07 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1557 10.196.1.34 10.196.1.33 init

resolv.conf was restored

Sending kill signal to transmission-daemon`

this particular error is listed in the FAQ, but its entry is merely a TODO to actually write the documentation. the result of the error is that the container can run, and if I look at the private tracker some of my torrents are from I can see them seeding, but the web interface is inaccessible. In Firefox this gives an array of bizarre and misleading errors, and in other browsers it just says connection failed.

When I tried the dev container it did start up and expose the web interface correctly, but none of the torrents that I had loaded were present despite me mapping the same set of directories into it.

### Expected Behavior

I expected the web interface to be accessible. What's bizarre is that the container had been working fine for ages and then suddenly just stopped working when I connected to it from a different computer than usual, a mac instead of a PC, bur once that happened i was unable to access it or make it work from my pc either.

### How have you tried to solve the problem?

I followed all the troubleshooting steps up until I hit the error mentioned in the FAQ in the step to start with a good config for my VPN.

### Log output

Here's the log output from the troubleshooting step to avoid needing screenshots:
`/$ sudo docker run --rm -it --cap-add=NET_ADMIN \
>   -e OPENVPN_PROVIDER=ExpressVPN \
>   -e OPENVPN_USERNAME=USERNAME \
>   -e OPENVPN_PASSWORD=PASSWORD \
>   -e DISABLE_PORT_UPDATER=true \
>   haugene/transmission-openvpn
Starting container with revision: 44c82aa1297b0f4473ad141f2cea326b407d9c22
Creating TUN device /dev/net/tun
Using OpenVPN provider: EXPRESSVPN
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for EXPRESSVPN. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.SCFyQZqvRP
Extracting configs to /tmp/tmp.TYXUmlw4nm
Found configs for EXPRESSVPN in /tmp/tmp.TYXUmlw4nm/vpn-configs-contrib-main/openvpn/expressvpn, will replace current content in /etc/openvpn/expressvpn
Cleanup: deleting /tmp/tmp.SCFyQZqvRP and /tmp/tmp.TYXUmlw4nm
No VPN configuration provided. Using default.
Modifying /etc/openvpn/expressvpn/default.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Setting OpenVPN credentials...
Sun Jun 26 03:08:55 2022 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Sun Jun 26 03:08:55 2022 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar 22 2022
Sun Jun 26 03:08:55 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Sun Jun 26 03:08:55 2022 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
Sun Jun 26 03:08:55 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun Jun 26 03:08:55 2022 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Sun Jun 26 03:08:55 2022 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Sun Jun 26 03:08:55 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]193.29.107.11:1195
Sun Jun 26 03:08:55 2022 Socket Buffers: R=[212992->425984] S=[212992->425984]
Sun Jun 26 03:08:55 2022 UDP link local: (not bound)
Sun Jun 26 03:08:55 2022 UDP link remote: [AF_INET]193.29.107.11:1195
Sun Jun 26 03:08:55 2022 TLS: Initial packet from [AF_INET]193.29.107.11:1195, sid=e67e00f1 c07a2a2c
Sun Jun 26 03:08:55 2022 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Jun 26 03:08:55 2022 VERIFY OK: depth=1, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=ExpressVPN CA, emailAddress=support@expressvpn.com
Sun Jun 26 03:08:55 2022 VERIFY OK: nsCertType=SERVER
Sun Jun 26 03:08:55 2022 VERIFY X509NAME OK: C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-8801-0a, emailAddress=support@expressvpn.com
Sun Jun 26 03:08:55 2022 VERIFY OK: depth=0, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-8801-0a, emailAddress=support@expressvpn.com
Sun Jun 26 03:08:55 2022 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA
Sun Jun 26 03:08:55 2022 [Server-8801-0a] Peer Connection Initiated with [AF_INET]193.29.107.11:1195
Sun Jun 26 03:08:56 2022 SENT CONTROL [Server-8801-0a]: 'PUSH_REQUEST' (status=1)
Sun Jun 26 03:08:56 2022 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.173.0.1,comp-lzo no,route 10.173.0.1,topology net30,ping 10,ping-restart 60,ifconfig 10.173.1.234 10.173.1.233,peer-id 45,cipher AES-256-GCM'
Sun Jun 26 03:08:56 2022 OPTIONS IMPORT: timers and/or timeouts modified
Sun Jun 26 03:08:56 2022 OPTIONS IMPORT: compression parms modified
Sun Jun 26 03:08:56 2022 OPTIONS IMPORT: --ifconfig/up options modified
Sun Jun 26 03:08:56 2022 OPTIONS IMPORT: route options modified
Sun Jun 26 03:08:56 2022 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sun Jun 26 03:08:56 2022 OPTIONS IMPORT: peer-id set
Sun Jun 26 03:08:56 2022 OPTIONS IMPORT: adjusting link_mtu to 1629
Sun Jun 26 03:08:56 2022 OPTIONS IMPORT: data channel crypto options modified
Sun Jun 26 03:08:56 2022 Data Channel: using negotiated cipher 'AES-256-GCM'
Sun Jun 26 03:08:56 2022 NCP: overriding user-set keysize with default
Sun Jun 26 03:08:56 2022 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Jun 26 03:08:56 2022 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Jun 26 03:08:56 2022 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
Sun Jun 26 03:08:56 2022 TUN/TAP device tun0 opened
Sun Jun 26 03:08:56 2022 TUN/TAP TX queue length set to 100
Sun Jun 26 03:08:56 2022 /sbin/ip link set dev tun0 up mtu 1500
Sun Jun 26 03:08:56 2022 /sbin/ip addr add dev tun0 local 10.173.1.234 peer 10.173.1.233
Sun Jun 26 03:08:56 2022 /etc/openvpn/tunnelUp.sh tun0 1500 1557 10.173.1.234 10.173.1.233 init
Up script executed with tun0 1500 1557 10.173.1.234 10.173.1.233 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.173.1.234
Updating Transmission settings.json with values from env variables
Generating settings.json for Transmission from environment and defaults /etc/transmission/default-settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.173.1.234
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
Transmission startup script complete.
Sun Jun 26 03:08:59 2022 /sbin/ip route add 193.29.107.11/32 via 172.17.0.1
Sun Jun 26 03:08:59 2022 /sbin/ip route add 0.0.0.0/1 via 10.173.1.233
Sun Jun 26 03:08:59 2022 /sbin/ip route add 128.0.0.0/1 via 10.173.1.233
Sun Jun 26 03:08:59 2022 /sbin/ip route add 10.173.0.1/32 via 10.173.1.233
RTNETLINK answers: File exists
Sun Jun 26 03:08:59 2022 ERROR: Linux route add command failed: external program exited with error status: 2
Sun Jun 26 03:08:59 2022 Initialization Sequence Completed`

### HW/SW Environment

```markdown
- OS:DSM7.0.1-42218 Update 3 on a DSM 920+
- Docker: Latest DSM7 release.
```

**Comment by astaplet** [comment]
bizarre, for no reason at all after restarting the container about 20 times i was able to access the web interface again despite the FILE EXISTS error persisting. I'll leave this issue open to document both issues I suppose.

**Comment by pkishino** [comment]
why is your LOCAL_NETWORK empty in the screenshot?
most likely it is trying to add a route that already exists.. I approved a PR yesterday, I believe, that replaces route add with route replace.. this would avoid the issue of duplicat

**Comment by astaplet** [comment]
I didn't know what to put there and leaving it empty hadn't caused me issues previously. Is there something specific I should have in there?

**Comment by pkishino** [comment]
yes, it is essential to get the container working properly..
https://haugene.github.io/docker-transmission-openvpn/run-container/#3_you_might_not_be_able_to_access_the_web_ui_on_the_first_try

**Comment by astaplet** [comment]
> yes, it is essential to get the container working properly..
> 
> https://haugene.github.io/docker-transmission-openvpn/run-container/#3_you_might_not_be_able_to_access_the_web_ui_on_the_first_try

thank you! not sure how I missed that when I set this up months ago. I'll close this issue.
