### ISSUE TITLE
Torrents don't resume on docker container stop/start

### ISSUE THREAD

**Issue by dougnukem** [haugene/docker-transmission-openvpn#23]
Torrents aren't resuming when the docker container is stopped/started, even though the `/data/incomplet` and `/data/watch` has `*.torrent.added` and `*.part` files.

I think there must be some other Transmission configuration or directory that is managing this state that needs to be located in the `/data` or `/config` volumes so it can be restored on docker container restart.

**Comment by dougnukem** [comment]
It looks like the `/etc/transmission-daemon` file contains some important state https://trac.transmissionbt.com/wiki/ConfigFiles
- `resume/` - This subfolder holds .resume files that hold information about a particular torrent, such as which parts have been downloaded, the folder the downloaded data was stored in, and so on. These follow an identical naming scheme to the files in the torrents subfolder.
- `torrents/` - This subfolder holds the .torrent files that have been added to Transmission. The files in this folder are named with a combination of the torrent's name (to make it human-readable) and a portion of the torrent's SHA1 hash (to avoid filename collisions from similarly-named torrents).

**Comment by haugene** [comment]
Fix merged
