### ISSUE TITLE
Freenas Corral unable to start

### ISSUE THREAD

**Issue by simonwhill** [haugene/docker-transmission-openvpn#230]
Hi, 

I cant get this to start, I am using Freenas Corral 10.0.0.2 (upgraded form 9.10)

I have mappings for the following Volumes

/mnt/Data/Config/Transmission/openvpn    /config
/mnt/Data/Config/Transmission/Confg        /data
/mnt/Data/Downloads/Transmission            /scripts
/mnt/Data/Config/Transmission/scripts       /etc/openvpn

I have a default.ovpn file but also have a copy of it in the folder named custom.ovpn  (my vpn provider is Express VPN) the files are in the /etc/openvpn folder
LOCAL_NETWORK is set to 192.168.1.0/24 which is my local subnet
OPENVPN_USERNAME is set to User (Express VPN use certs to authenticate
OPENVPN_PASSWORD is set to Pass
OPENVPN_PROVIDER is set to CUSTOM
OPENVPN_CONFIG is set to /etc/openvpn/default.ovpn i have tried default and custom 

I think thats everything i hope its just a simple config error but i just cant get it to start

Regards

Simon

**Comment by haugene** [comment]
Hi. See my comments in #226. And don't set OPENVPN_CONFIG the parameter. If your file is named default.ovpn it will be selected.

Also, note that the only mount you need in addition to /data is one for the openvpn config. That is /folder/where/ovpn/file/is/ /etc/openvpn/custom/

Don't mount to /etc/openvpn directly, then you'll override the openvpn installation. 

And try to provide logs if it still fails.

**Comment by simonwhill** [comment]
Hi 
there does not appear to be a way to get docker logs in freenas ? I removed the openvpn_config variable, i now only have data as a mount. but with out the mount how do i get the openvpn config into the docker?

i cant see a way to get data onto the docker? i must be missing something.

Running the container again i get a brief green light on the container then out again.

Sorry for the stupid questions

Simon

**Comment by haugene** [comment]
You might need to ssh into the nas to get the logs. As for the mounts, yes you need two. The one for /data and the one for the config that I described above.

**Comment by simonwhill** [comment]
ok so the logs say

Could not find OpenVPN provider: CUSTOM                                                                                                                   
Please check your settings. 

not sure how i missed the info above but /mnt/Data/Config/OpenVPN id mapped to /config and contains the default.ovpn file

**Comment by haugene** [comment]
As described above, the folder containing the default.ovpn file should be mounted to /etc/openvpn/custom/

Not /config 

This is also in the readme.

**Comment by simonwhill** [comment]
totally miss understood you! i thought if i mapped /mnt/Data/Config/OpenVPN to /etc/openvpn if /mnt/Data/Config/OpenVPN and a sub folder called custom that would be ok but instead i mapped

/mnt/Data/Config/OpenVPN/custom to /etc/openvpn/custom 

that has sorted it and its working just fine

thanks

Simon

**Comment by haugene** [comment]
Glad to hear it. Np ;)
