### ISSUE TITLE
cannot find zipfile directory in one of /tmp/tmp

### ISSUE THREAD

**Issue by tonybeatle** [haugene/docker-transmission-openvpn#2302]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - /srv/dev-disk-by-uuid-2bb3cf71-151d-47fc-9dcd-a0cd1d486e88/Downloads/Transmission Downloads:/data
            - /srv/dev-disk-by-uuid-2bb3cf71-151d-47fc-9dcd-a0cd1d486e88/AppData/Transmission:/config
        environment:
            - OPENVPN_PROVIDER=IPVANISH
            - OPENVPN_CONFIG=france
            - OPENVPN_USERNAME=
            - OPENVPN_PASSWORD=
            - LOCAL_NETWORK=192.168.51.0/24
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

### Current Behavior

transmission not loading. stuck in a loop to download config file zip and then cant open zip file

### Expected Behavior

it should download the config files and load transmission. transmission has been runnign fine for months but today it stopped working. nothing has been update on my nas in a few weeks

### How have you tried to solve the problem?

I pulled the latest version. still stuck in a loop. ive tried different config settings and still in loop

### Log output

Starting container with revision: 44c82aa1297b0f4473ad141f2cea326b407d9c22
Creating TUN device /dev/net/tun
Using OpenVPN provider: IPVANISH
Running with VPN_CONFIG_SOURCE auto
Provider IPVANISH has a bundled setup script. Defaulting to internal config
Executing setup script for IPVANISH
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.i3R0owvzJt
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
[/tmp/tmp.i3R0owvzJt]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tmp.i3R0owvzJt or
        /tmp/tmp.i3R0owvzJt.zip, and cannot find /tmp/tmp.i3R0owvzJt.ZIP, period.
Starting container with revision: 44c82aa1297b0f4473ad141f2cea326b407d9c22
Creating TUN device /dev/net/tun
Using OpenVPN provider: IPVANISH
Running with VPN_CONFIG_SOURCE auto
Provider IPVANISH has a bundled setup script. Defaulting to internal config
Executing setup script for IPVANISH
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.nZorG4ipVP
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
[/tmp/tmp.nZorG4ipVP]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tmp.nZorG4ipVP or
        /tmp/tmp.nZorG4ipVP.zip, and cannot find /tmp/tmp.nZorG4ipVP.ZIP, period.

### HW/SW Environment

```markdown
- OS:Oopen Meida vault
- Docker:protainer 2.14.2
```

**Comment by fatbob01** [comment]
check out https://github.com/haugene/docker-transmission-openvpn/issues/2301

**Comment by flebel** [comment]
Fixed on the dev branch.
```
git clone https://github.com/haugene/docker-transmission-openvpn.git
cd docker-transmission-openvpn
git checkout dev
docker build . --tag haugene/transmission-openvpn:latest
```
