### ISSUE TITLE
Rename doesn't persist after updating image

### ISSUE THREAD

**Issue by jhskim78** [haugene/docker-transmission-openvpn#2311]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

docker run --cap-add=NET_ADMIN -d -v <myhostfolder>:/data -e OPENVPN_PROVIDER={provider} -e OPENVPN_CONFIG={config file} -e OPENVPN_USERNAME={username} -e OPENVPN_PASSWORD={password} -e LOCAL_NETWORK=192.168.0.0/16 -e PUID=1005 -e PGID=1001 -e TZ=Australia/Melbourne --log-driver json-file --log-opt max-size=10m -p 9091:9091 --restart always --name transmission haugene/transmission-openvpn

### Current Behavior

In transmission, there is the "Rename" and "Set Location" options to rename a file or folder to something different to the torrent name, and seed from a location other than /data/completed/<torrent name>.

After an image upgrade, all renamed and relocated files cannot be found, and Transmission expects them in /data/completed/<torrent name>

The issue can be reproduced using the following steps:
1. in transmission, rename and/or relocate a torrent
2. docker stop transmission // when using --name transmission as per the docker config above
3. docker rm transmission
4. docker pull haugene/transmission-openvpn
5. docker run ... // as per docker run command above

### Expected Behavior

After an image upgrade, the renamed/relocated files can be found by transmission.

### How have you tried to solve the problem?

I've no idea how to solve this problem.  I assume the files that transmission use to track the location/rename do not live in the /data folder in the container.

### Log output

N/A

### HW/SW Environment

```markdown
- OS: Debian 10 (buster) 4.19.249-2
- Docker: Docker Engine - Community 20.10.17
```

**Comment by pkishino** [comment]
You haven’t set your data volume Mount correctly, please see the documentation.

**Comment by jhskim78** [comment]
Sorry I believe the data volume was mounted correctly.
The downloaded files were available in the mapped equivalent of /data/completed on the host, and the original torrent files were in /data/torrent.  The only loss of information were the file location data (current location if other than /data/completed, and name of file/folder if different to torrent name).

Perhaps it's something of note, but this issue only occured during an image update from 3.x (not sure which version but about 2 years old) -> 4.0.  I didn't have the issue when stopping/starting while on 3.x, nor did i have the issue when downgrading from 4.0 -> 3.7.

**Comment by pkishino** [comment]
please see here:
https://github.com/haugene/docker-transmission-openvpn/discussions/1937
due to diff in transmission versions and their hashing this affects existing torrents.
possibly this is your problem
