### ISSUE TITLE
Exits with code 2 every time in FreeNAS Corral 10.0.3

### ISSUE THREAD

**Issue by underpickled** [haugene/docker-transmission-openvpn#232]
I created this container within FreeNAS Corral. I already have a subsonic docker container working splendidly, so I know that docker is working in general.
I put in my NordVPN username/password, and set up a folder structure on the host to match the scripts, data, vpn config, etc, and put the desired NordVPN config file in the /vpn folder.
Am I missing something? I'm having trouble telling from the readme which of the extra steps are necessary on FreeNAS.

**Comment by haugene** [comment]
Have you checked #230?

**Comment by underpickled** [comment]
I thought I had looked through all of the issues, but I goofed and only had looked at the open issues. I had a few more issues than just this, but managed to find answers in the "closed" issue section. WebGUI works now... the windows transmission client is giving me trouble, but that's a battle for another day.
Thanks!
