### ISSUE TITLE
OVPN provider broken until release occurs

### ISSUE THREAD

**Issue by derekcentrico** [haugene/docker-transmission-openvpn#2332]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

N/A

### Current Behavior

The lack of a new release means that the merged OVPN changes on the contrib repo make the provider OVPN unusable.  There is no longer a default.ovpn because of my script work.  But, the current release does not have the new script added in it.  So, it's broke for all. 

### Expected Behavior

OVPN would work based upon new script additions.  

### How have you tried to solve the problem?

I suggest either releasing a new docker with the updates completed or reverting contrib until you are ready.

### Log output

Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Setting OpenVPN credentials...
adding route to local network 192.168.1.0/24 via 172.22.0.1 dev eth0
Fri Aug 26 10:33:05 2022 disabling NCP mode (--ncp-disable) because not in P2MP client or server mode
Options error: You must define TUN/TAP device (--dev)
Use --help for more information.
Starting container with revision: 901c0d2def15fcbd2e2cde2bddd1799678e85a31
One or more OVERRIDE_DNS addresses found. Will use them to overwrite /etc/resolv.conf
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: OVPN
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for OVPN. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.N2VPXXekdm
Extracting configs to /tmp/tmp.RHCkMvpcjV
Found configs for OVPN in /tmp/tmp.RHCkMvpcjV/vpn-configs-contrib-main/openvpn/ovpn, will replace current content in /etc/openvpn/ovpn
Cleanup: deleting /tmp/tmp.N2VPXXekdm and /tmp/tmp.RHCkMvpcjV
No VPN configuration provided. Using default.
Modifying /etc/openvpn/ovpn/default.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
sed: can't read /etc/openvpn/ovpn/default.ovpn: No such file or directory
Modification: Change ca certificate path
sed: can't read /etc/openvpn/ovpn/default.ovpn: No such file or directory
Modification: Change ping options
sed: can't read /etc/openvpn/ovpn/default.ovpn: No such file or directory
sed: can't read /etc/openvpn/ovpn/default.ovpn: No such file or directory
sed: can't read /etc/openvpn/ovpn/default.ovpn: No such file or directory
sed: can't read /etc/openvpn/ovpn/default.ovpn: No such file or directory

### HW/SW Environment

```markdown
- OS: Ubuntu 22.04
- Docker:  latest stable
```

**Comment by pkishino** [comment]
This should be working on dev branch release..

**Comment by derekcentrico** [comment]
For sure, but most users won't be on dev branch so not sure how many are/will be affected next time they mess with their docker which will download new data from the contrib that causes their OVPN connection to fail.  I'm good just worrying about others.

Also, still available to write up the variables and options per variable to post somewhere if you all tell me what you'd like.

**Comment by pkishino** [comment]
Updated readme stating :dev is to be used.
will pin this

**Comment by pkishino** [comment]
@derekcentrico please feel free to edit:
https://haugene.github.io/docker-transmission-openvpn/provider-specific/
with the ovpn variables etc
thanks!

**Comment by derekcentrico** [comment]
Submitted.

**Comment by pkishino** [comment]
Sorry, I do not see the PR for the docu updates anywhere. can you check agian please
