### ISSUE TITLE
Unnecessarily downloads config files, and tries to apply "custom" vpn when using OPENVPN_PROVIDER=custom 

### ISSUE THREAD

**Issue by UnconditionalLoop** [haugene/docker-transmission-openvpn#2338]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=US-Washington-UDP
      - OPENVPN_USERNAME=user
      - OPENVPN_PASSWORD=pass

### Current Behavior

It's always done this, and it makes no sense. There's no reason to waste time and bandwidth to find a "custom" provider that doesn't exist.

### Expected Behavior

It should skip downloading config files entirely when you have "custom" set as your vpn provider..

### How have you tried to solve the problem?

There's nothing to do.

### Log output

No` bundled config script found for CUSTOM. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.xpgGr6zoMU
Extracting configs to /tmp/tmp.FCAqY7new2
ERROR: Could not find any configs for provider CUSTOM in downloaded configs
Cleanup: deleting /tmp/tmp.xpgGr6zoMU and /tmp/tmp.FCAqY7new2

### HW/SW Environment

```markdown
- OS:Linux
- Docker:22
```

**Comment by pkishino** [comment]
this has been fixed on dev branch since long ago
