### ISSUE TITLE
Update provider FROOT

### ISSUE THREAD

**Issue by Extimor** [haugene/docker-transmission-openvpn#234]
Hi,
Could someone help me update the config files for the provider froot?
I'm using the Swedish one and the confi-files can be found at https://frootvpn.com/en/account/server-info
The ones provided in the container points to ports that are no longer in use it seems.

Thanks in advance.

**Comment by coolboiime** [comment]
Closing this for merging into issue #554! Please have all issues and updates directed towards that issue. Closing this for now, thanks!
