### ISSUE TITLE
Custom default.ovpn altered incorrectly

### ISSUE THREAD

**Issue by rocket4321** [haugene/docker-transmission-openvpn#2350]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

Docker-compose :

  transmission-openvpn:
    image: haugene/transmission-openvpn:latest
#    image: haugene/transmission-openvpn:3.7.1
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
    labels:
      - com.centurylinklabs.watchtower.enable="true"
      - autoheal:"true"
      - autoheal.stop.timeout=60
    environment:
      - PUID=1000
      - PGID=1000
      - GLOBAL_APPLY_PERMISSIONS=true
      - TRANSMISSION_UMASK=000
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=IGNORED
      - OPENVPN_PASSWORD=IGNORED
      - LOCAL_NETWORK=192.168.2.0/24
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
    volumes:
      # Fail if not avail
      #-  /home/docker/transmission-openvpn/data/debx64:/data
      - type: bind
        source: /media/share-disk1-nfs/torrents/debx64
        target: /data

      -  /home/docker/transmission-openvpn/config.7.canada:/etc/openvpn/custom

### Current Behavior

Failure on startup since cannot locate auth file after alteration in default.ovpn

The latest docker image updates a custom default.ovpn file to have the following line, ignoring any previous entry in the file. This blocks the custom config from working properly.

Using:
image: haugene/transmission-openvpn:latest

While including  the folloing in default.ovpn:
....
auth-user-pass /etc/openvpn/custom/openvpn-credentials.txt
....

Will be overwritten/altered by the docker image to:
....

auth-user-pass /config/openvpn-credentials.txt
...

Note the change in path directory from the original. 
This change is performed even if default.ovpn is read-only permissions. 
This alteration does not appear to have any disabling option, per the usage guidelines.

Works correctly under:
image: haugene/transmission-openvpn:3.7.1

I have NOT attempted my issue on dev branch.
I request insight from developer/maintainer about options to disable automatic modifications to openvpn custom config files.

### Expected Behavior

No alteration to auth file location

### How have you tried to solve the problem?

1) Tried latest docker image
2) Reviewed docs for method to disable auto modifications

### Log output

transmission-openvpn    | Wed Sep 28 14:30:21 2022 [toronto-rack401.nodes.gen4.ninja] Peer Connection Initiated with [AF_INET]154.3.42.148:443
transmission-openvpn    | Wed Sep 28 14:30:22 2022 SENT CONTROL [toronto-rack401.nodes.gen4.ninja]: 'PUSH_REQUEST' (status=1)
transmission-openvpn    | Wed Sep 28 14:30:22 2022 AUTH: Received control message: AUTH_FAILED
transmission-openvpn    | Wed Sep 28 14:30:22 2022 SIGTERM[soft,auth-failure] received, process exiting

### HW/SW Environment

```markdown
- OS: debian
- Docker:
```

**Comment by pkishino** [comment]
a) use dev branch
b) https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/modify-openvpn-config.sh
specifies how to disable modifications
