### ISSUE TITLE
Web UI not loading/Container in loop

### ISSUE THREAD

**Issue by Aj-Apps** [haugene/docker-transmission-openvpn#2352]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

transmission-openvpn:
    volumes:
        - /media/device:/media/downloads
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=1000
        - PGID=100
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=SURFSHARK
        - OPENVPN_USERNAME=**username**
        - OPENVPN_PASSWORD=**password**
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=192.168.86.0/24
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=50
    cap_add:
      - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091

    restart: always
    image: haugene/transmission-openvpn:dev

### Current Behavior

Deploy via stacks in portainer
Will say running then after 60 seconds will restart and spit out the log below also wont load UI interface as it is constantly restarting (even after I remove - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 and restart: always)

### Expected Behavior

UI to load and minimal log output

### How have you tried to solve the problem?

Re deployed
Tried normal and dev
rebuilt enviroment
double checked DNS setting

### Log output

Starting container with revision: **ContainerID**
WARNING: initial DNS resolution test failed
Creating TUN device /dev/net/tun
Using OpenVPN provider: SURFSHARK
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for SURFSHARK. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.ux3tMb71Vc
curl: (6) Could not resolve host: github.com
./etc/openvpn/fetch-external-configs.sh: line 18: config_repo_temp_dir: unbound variable
Starting container with revision: **ContainerID**
WARNING: initial DNS resolution test failed
Creating TUN device /dev/net/tun
Using OpenVPN provider: SURFSHARK
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for SURFSHARK. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.lJXLNyG41o
Extracting configs to /tmp/tmp.6c3Wiigtpt
Found configs for SURFSHARK in /tmp/tmp.6c3Wiigtpt/vpn-configs-contrib-main/openvpn/surfshark, will replace current content in /etc/openvpn/surfshark
Cleanup: deleting /tmp/tmp.lJXLNyG41o and /tmp/tmp.6c3Wiigtpt
No VPN configuration provided. Using default.
Modifying /etc/openvpn/surfshark/default.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
Modification: Change ca certificate path
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
Modification: Change ping options
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
Setting OpenVPN credentials...
adding route to local network 192.168.86.0/24 via 172.20.0.1 dev eth0
Fri Sep 30 09:43:21 2022 disabling NCP mode (--ncp-disable) because not in P2MP client or server mode
Options error: You must define TUN/TAP device (--dev)
Use --help for more information.

### HW/SW Environment

```markdown
- OS: Mint
- Docker:20.10.12
```

**Comment by pkishino** [comment]
1) you haven’t mounted a /data and/or /config mapping as required, see documentation
2) your DNS isn’t working soo it cannot fetch the ovpn
3) it seems you need to manually create the tun/tap interface or at least verify that it does get created
4) this is a user/config error, please don’t open issues for this, start a discussion
