### ISSUE TITLE
OpenVPN code transpose for Rutorrent

### ISSUE THREAD

**Issue by Vagabon666** [haugene/docker-transmission-openvpn#237]
Hello,

Sorry to ask you this but as your OpenVPN config is working like a charm on Transmission.
Would it be possible to get a tuto to use it with Rutorrent (for autotool usage) ?

A nice Rutorrent container is : diameter/rtorrent-rutorrent (there is a version also on unbutu)

Thank you very much.

**Comment by Fma965** [comment]
https://hub.docker.com/r/binhex/arch-rtorrentvpn/ ???

**Comment by haugene** [comment]
Yeah, using this container with rtorrent would require some re-writing. You could try the image linked above, or you would have to remove the transmission stuff from this image and in the openvpn up script have it start rtorrent instead. It needs to be installed and configured first of course.

As this image is focusing on Transmission, I will close this issue now. Feel free to ask if you give it a try, good luck :)
