### ISSUE TITLE
Error: Nexthop has invalid gateway.

### ISSUE THREAD

**Issue by himred** [haugene/docker-transmission-openvpn#2399]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

torrent:
  image: haugene/transmission-openvpn
  container_name: torrent
  hostname: torrent
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always

  dns:
    - 8.8.8.8
    - 8.8.4.4

  volumes:
    - /etc/localtime:/etc/localtime:ro
    - tor_data:/data
    - tor_scripts:/scripts

  logging:
    driver: "json-file"
    options:
      max-size: "50m"
      max-file: "2"

  environment:
    - OPENVPN_PROVIDER=NORDVPN
    - OPENVPN_USERNAME=****HIDDEN****
    - OPENVPN_PASSWORD=****HIDDEN****
    - OPENVPN_OPTS=
    - NORDVPN_COUNTRY=nl
    - NORDVPN_PROTOCOL=udp
    - NORDVPN_CATEGORY=legacy_p2p
    - HEALTH_CHECK_HOST=8.8.8.8
    - LOCAL_NETWORK=192.168.56.0/24

volumes:
  data:
  tor_data:
  tor_scripts:

### Current Behavior

Since latest version, the route to the VPN server cannot be setup by the container.
The error is: 
```
/sbin/ip route add 213.152.188.73/32 via 192.168.56.254
Error: Nexthop has invalid gateway.
Sat Nov 12 00:32:07 2022 ERROR: Linux route add command failed: external program exited with error status: 2
```

### Expected Behavior

The ip route command to succeed

### How have you tried to solve the problem?

1) I tried manually to type `/sbin/ip route add 213.152.188.73/32 via 192.168.56.254` and it failed

2) I typed `/sbin/ip route add 213.152.188.73/32 via 192.168.56.254 dev eth0 onlink` and it worked

3) Until a fix is found I added this lines in my transmission-post-start.sh
```
ip=$(grep "^remote " /etc/openvpn/nordvpn/*.ovpn | cut -f2 -d' ' | head -1)
/sbin/ip route add $ip/32 via 192.168.56.254 dev eth0 onlink
```

### Log output
```
Starting container with revision: f9cb4dea2da1a3aa63bd3945e0162c9b8a9789a4
Creating TUN device /dev/net/tun
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN
INFO: OVPN: Checking curl installation
INFO: OVPN: DNS resolution ok
INFO: OVPN: ok, configurations download site reachable
INFO: OVPN: Removing existing configs in /etc/openvpn/nordvpn
Checking NORDPVN API responses
INFO: OVPN:Selecting the best server...
INFO: OVPN: Searching for country : nl (153)
INFO: OVPN: Searching for group: legacy_p2p
INFO: OVPN:Searching for technology: openvpn_udp
INFO: OVPN: Best server : nl925.nordvpn.com, load: 7
INFO: OVPN: Downloading config: nl925.nordvpn.com.ovpn
INFO: OVPN: Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/nl925.nordvpn.com.udp.ovpn
Starting OpenVPN using config nl925.nordvpn.com.ovpn
Modifying /etc/openvpn/nordvpn/nl925.nordvpn.com.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
Setting OpenVPN credentials...
adding route to local network 192.168.56.0/24 via 192.168.56.254 dev eth0
Sat Nov 12 00:32:06 2022 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar 22 2022
Sat Nov 12 00:32:06 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Sat Nov 12 00:32:06 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Nov 12 00:32:06 2022 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Sat Nov 12 00:32:06 2022 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Sat Nov 12 00:32:06 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]213.152.188.73:1194
Sat Nov 12 00:32:06 2022 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sat Nov 12 00:32:06 2022 UDP link local: (not bound)
Sat Nov 12 00:32:06 2022 UDP link remote: [AF_INET]213.152.188.73:1194
Sat Nov 12 00:32:06 2022 TLS: Initial packet from [AF_INET]213.152.188.73:1194, sid=82681cc2 2f26c813
Sat Nov 12 00:32:06 2022 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Nov 12 00:32:06 2022 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Sat Nov 12 00:32:06 2022 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA7
Sat Nov 12 00:32:06 2022 VERIFY KU OK
Sat Nov 12 00:32:06 2022 Validating certificate extended key usage
Sat Nov 12 00:32:06 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sat Nov 12 00:32:06 2022 VERIFY EKU OK
Sat Nov 12 00:32:06 2022 VERIFY X509NAME OK: CN=nl925.nordvpn.com
Sat Nov 12 00:32:06 2022 VERIFY OK: depth=0, CN=nl925.nordvpn.com
Sat Nov 12 00:32:06 2022 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 4096 bit RSA
Sat Nov 12 00:32:06 2022 [nl925.nordvpn.com] Peer Connection Initiated with [AF_INET]213.152.188.73:1194
Sat Nov 12 00:32:07 2022 SENT CONTROL [nl925.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Sat Nov 12 00:32:07 2022 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.8.2.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.2.4 255.255.255.0,peer-id 7,cipher AES-256-GCM'
Sat Nov 12 00:32:07 2022 OPTIONS IMPORT: timers and/or timeouts modified
Sat Nov 12 00:32:07 2022 OPTIONS IMPORT: explicit notify parm(s) modified
Sat Nov 12 00:32:07 2022 OPTIONS IMPORT: compression parms modified
Sat Nov 12 00:32:07 2022 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Sat Nov 12 00:32:07 2022 Socket Buffers: R=[212992->425984] S=[212992->425984]
Sat Nov 12 00:32:07 2022 OPTIONS IMPORT: --ifconfig/up options modified
Sat Nov 12 00:32:07 2022 OPTIONS IMPORT: route options modified
Sat Nov 12 00:32:07 2022 OPTIONS IMPORT: route-related options modified
Sat Nov 12 00:32:07 2022 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sat Nov 12 00:32:07 2022 OPTIONS IMPORT: peer-id set
Sat Nov 12 00:32:07 2022 OPTIONS IMPORT: adjusting link_mtu to 1657
Sat Nov 12 00:32:07 2022 OPTIONS IMPORT: data channel crypto options modified
Sat Nov 12 00:32:07 2022 Data Channel: using negotiated cipher 'AES-256-GCM'
Sat Nov 12 00:32:07 2022 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Nov 12 00:32:07 2022 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Nov 12 00:32:07 2022 ROUTE_GATEWAY 192.168.56.254/255.255.255.0 IFACE=eth0 HWADDR=02:42:c0:a8:38:04
Sat Nov 12 00:32:07 2022 TUN/TAP device tun0 opened
Sat Nov 12 00:32:07 2022 TUN/TAP TX queue length set to 100
Sat Nov 12 00:32:07 2022 /sbin/ip link set dev tun0 up mtu 1500
Sat Nov 12 00:32:07 2022 /sbin/ip addr add dev tun0 10.8.2.4/24 broadcast 10.8.2.255
Sat Nov 12 00:32:07 2022 /sbin/ip route add 213.152.188.73/32 via 192.168.56.254
Error: Nexthop has invalid gateway.
Sat Nov 12 00:32:07 2022 ERROR: Linux route add command failed: external program exited with error status: 2
Sat Nov 12 00:32:07 2022 /sbin/ip route add 0.0.0.0/1 via 10.8.2.1
Sat Nov 12 00:32:07 2022 /sbin/ip route add 128.0.0.0/1 via 10.8.2.1
Up script executed with device=tun0 ifconfig_local=10.8.2.4
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.2.4

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

Updating Transmission settings.json with values from env variables
Attempting to use existing settings.json for Transmission
Successfully used existing settings.json /config/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.8.2.4
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
STARTING TRANSMISSION
Executing /scripts/transmission-post-start.sh
/scripts/transmission-post-start.sh returned 0
Transmission startup script complete.
Sat Nov 12 00:32:08 2022 Initialization Sequence Completed
```

### HW/SW Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- Docker: 20.10.21, build baeda1f
```

**Comment by gpnunes75** [comment]
I've got the same error. I had to downgrade to 4.0

**Comment by AndersVN** [comment]
Also experiencing this.

**Comment by BunnySweety** [comment]
As for the others, 4.2 does not work for me. I confirm that downgrade to 4.1 also works on my side.

**Comment by immortalyash** [comment]
+1 on the issue and downgrade worked for me

**Comment by ddprince17** [comment]
I have the same issue. Downgrading to 4.1 also fixed it for me.

**Comment by gpnunes75** [comment]
I have tested 4.3 and it is still not working.

**Comment by markchaik** [comment]
same issue for me.  Downgrade to 4.1 works.

**Comment by gpnunes75** [comment]
> same issue for me. Downgrade to 4.1 works.

Yes. 4.1 is the last functional version. 4.2 has broken and latest 4.3.2 still not working. 

I wonder if it is a situation with only few people

**Comment by peanutlasko** [comment]
Same issue here, 4.1 works but 4.2 and 4.3.2 are broken for me.

**Comment by haugene** [comment]
Hey guys and thanks for reporting this bug. I'll try to have a look at this over the weekend. I'm also running on an Ubuntu host (20.04 though) and same docker version as OP so it's a bit strange that I can't reproduce it. But routes created here is depending on the config so I guess there can be provider differences.

Since it's also failing in 4.2 that means that it's not because of the upgrade to ubuntu base image 22.04 and newer OpenVPN and Transmission like #2410 is. That makes me assume that #2285 might be the culprit. Have to do another look through the changes between 4.1 and 4.2 if that's not the case.

Just to support that hypothesis. Can you try running the container and just commenting out `LOCAL_NETWORK` and see if it starts fine then? You won't be able to connect to it of course, but you can see if the logs look good. Also you should be able to do something like:
```
➜  ~ docker exec -it openvpn bash -c "curl localhost:9091"
<h1>301: Moved Permanently</h1>
```
to see that Transmission is actually running in there.

**Comment by gpnunes75** [comment]
Hey, Great to hear from you

I believe your hypothesis is right. I've commented LOCAL_NETWORK and "Nexthop has invalid gateway" message has gone and container started fine. I was able to see "<h1>301: Moved Permanently</h1>"

**Comment by gpnunes75** [comment]
> Hey, Great to hear from you
> 
> I believe your hypothesis is right. I've commented LOCAL_NETWORK and "Nexthop has invalid gateway" message has gone and container started fine. I was able to see "
> 
> # 301: Moved Permanently
> "

I did some tests and:

my LOCAL_NETWORK env is like that: LOCAL_NETWORK=172.17.0.0/16, 192.168.86.0/24 (it doesn't work)

If I invert addresses like this: LOCAL_NETWORK=192.168.86.0/24, 172.17.0.0/16 (it works)

**Comment by rvaidya** [comment]
I am also affected by this, tried things from FAQ, debug guide, tips and tricks to no avail.  Downgrading to 4.1 works.

**Comment by TazySec** [comment]
> I am also affected by this, tried things from FAQ, debug guide, tips and tricks to no avail. Downgrading to 4.1 works. Host OS is Ubuntu 22.04, docker-ce upgraded to latest.
> 
> 4.3.2 doesn't give the "Error: Nexthop has invalid gateway" message but 4.2 does. 4.3.2 instead prints:
> 
> ```
> transmission  | 2022-12-09 17:44:33 sitnl_send: rtnl: generic error (-101): Network is unreachable
> transmission  | 2022-12-09 17:44:33 ERROR: Linux route add command failed
> ```
> 
> Here's my docker-compose:
> 
> And here are the logs from starting the container:

Did you manage to get this working again got the same error?

**Comment by edgd1er** [comment]
according to logs dev is null. Restarting container with env var DEBUG=True, you could have more information about the error.

**Comment by masseysan** [comment]
> > I am also affected by this, tried things from FAQ, debug guide, tips and tricks to no avail. Downgrading to 4.1 works. Host OS is Ubuntu 22.04, docker-ce upgraded to latest.
> > 4.3.2 doesn't give the "Error: Nexthop has invalid gateway" message but 4.2 does. 4.3.2 instead prints:
> > ```
> > transmission  | 2022-12-09 17:44:33 sitnl_send: rtnl: generic error (-101): Network is unreachable
> > transmission  | 2022-12-09 17:44:33 ERROR: Linux route add command failed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here's my docker-compose:
> > And here are the logs from starting the container:
> 
> Did you manage to get this working again got the same error?

Posting to share my findings. I had the same issue with the exact same errors

`2023-07-20 19:21:27 sitnl_send: rtnl: generic error (-101): Network is unreachable
2023-07-20 19:21:27 ERROR: Linux route add command failed`

I think the issue was with how the containers network was assigned to it (I was trying to use a macvlan network) Once I cleared those settings out and placed it back on the host, it has been running flawlessly without any errors. 

Granted this was all self-inflicted, but this is how we learn.

**Comment by ddprince17** [comment]
@masseysan you're right, I'm able to run the container just after following your advice. 

I was using another bridge network instead of the default one, but I never thought it would prevent the container to load. This is an insteresting discovery. I wonder why anything else than the default bridge network is not working. Someone has some clues on that?

**Comment by Ian-Costa18** [comment]
I'm still dealing with this, can confirm it works on 4.1 but not latest. My solution was to set LOCAL_NETWORK to a single IP range (172.0.0.0/8), rather than using a list. This means port forwarding doesn't work as the server is hosted on a 192.168 address, so I can only use my reverse proxy to access Transmission.

Strange thing I noticed is the container isn't attached to any networks while it's giving this error. Seems like it's having trouble grabbing an IP address or something. Not sure why it was doing that, but I gave up before figuring it out.

**Comment by dfredell** [comment]
I was deploying this on TureNAS Scale 24.10, right after they migrated from Kubernets to Docker. I was getting
```bash
adding route to local network 192.168.1.0/24 via 192.168.1.1 dev enp9s0
Error: Nexthop has invalid gateway.
```

What solved it for me was removing Host Networking, but leaving NET_ADMIN, LOCAL_NETWORK, and Privileged.
