### ISSUE TITLE
NordVPN broken in latest release

### ISSUE THREAD

**Issue by MastaG** [haugene/docker-transmission-openvpn#2400]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/volume1/shared/transmission:/data'
            - '/volume1/shared:/shared'
        environment:
            - OPENVPN_PROVIDER=NORDVPN
            - NORDVPN_COUNTRY=NL
            - NORDVPN_PROTOCOL=udp
            - NORDVPN_CATEGORY=legacy_p2p
            - OPENVPN_USERNAME=X
            - OPENVPN_PASSWORD=X
            - LOCAL_NETWORK=192.168.2.0/24
            - TZ=Europe/Amsterdam
            - PUID=X
            - PGID=X
            - TRANSMISSION_DOWNLOAD_DIR=/shared/videos
            - TRANSMISSION_INCOMPLETE_DIR=/shared/incomplete
            - GLOBAL_APPLY_PERMISSIONS=false
        command: sh -c " chmod 0755 /etc/openvpn/ovpn/configure-openvpn.sh && dumb-init /etc/openvpn/start.sh "
        logging:
            driver: json-file
            options:
                max-size: 10m
        restart: always
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn:latest

### Current Behavior

It seems to error out with:
OPENVPN_OPTS: unbound variable

### Expected Behavior

No errors..

### How have you tried to solve the problem?

Just tried to use the latest tag.

### Log output

Starting container with revision: f9cb4dea2da1a3aa63bd3945e0162c9b8a9789a4
Creating TUN device /dev/net/tun
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN
INFO: OVPN: Checking curl installation
INFO: OVPN: DNS resolution ok
INFO: OVPN: ok, configurations download site reachable
INFO: OVPN: Removing existing configs in /etc/openvpn/nordvpn
Checking NORDPVN API responses
INFO: OVPN:Selecting the best server...
INFO: OVPN: Searching for country : NL (153)
INFO: OVPN: Searching for group: legacy_p2p
INFO: OVPN:Searching for technology: openvpn_udp
INFO: OVPN: Best server : nl934.nordvpn.com, load: 4
INFO: OVPN: Downloading config: nl934.nordvpn.com.ovpn
INFO: OVPN: Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/nl934.nordvpn.com.udp.ovpn
Starting OpenVPN using config nl934.nordvpn.com.ovpn
Modifying /etc/openvpn/nordvpn/nl934.nordvpn.com.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
Setting OpenVPN credentials...
adding route to local network 192.168.2.0/24 via 172.21.0.1 dev eth0
/etc/openvpn/start.sh: line 321: OPENVPN_OPTS: unbound variable

### HW/SW Environment

```markdown
- OS: Synology DSM 7
- Docker:
```

**Comment by ilike2burnthing** [comment]
https://github.com/haugene/docker-transmission-openvpn/discussions/2395#discussioncomment-4119969

**Comment by haugene** [comment]
And now https://github.com/haugene/docker-transmission-openvpn/discussions/2395#discussioncomment-4123729
