### ISSUE TITLE
Migrated from DSM 6 to DSM 7.  Docker Container No Longer Works.

### ISSUE THREAD

**Issue by LL0001** [haugene/docker-transmission-openvpn#2429]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

I have removed my VPN U/P from the screenshots, but it is valid and working on other clients

![1](https://user-images.githubusercontent.com/95445299/203134378-b5eb148a-57b9-4969-9079-488713e42505.PNG)
![2](https://user-images.githubusercontent.com/95445299/203134406-1f027e55-cdd6-41ff-90e0-a4a2502834c4.PNG)
![7](https://user-images.githubusercontent.com/95445299/203134407-a7a16ee1-a6a8-475f-b4e5-70392407e96b.PNG)
![6](https://user-images.githubusercontent.com/95445299/203134409-00ba19ca-4743-42c7-a9d0-af8b4b184db3.PNG)
![5](https://user-images.githubusercontent.com/95445299/203134411-68c9f23f-40a0-48b9-9cf1-865edb8f24d9.PNG)
![4](https://user-images.githubusercontent.com/95445299/203134412-71c99da0-722c-44ce-954b-728f02078d04.PNG)
![3](https://user-images.githubusercontent.com/95445299/203134413-a13d6d95-4398-4e42-9658-b72b5f8634c3.PNG)

### Current Behavior

It fails trying to connect to the VPN config profile. Log output below:

### Expected Behavior

Expect it to run as expected

### How have you tried to solve the problem?

DNS is further defined on the hosts file.  My local DHCP also gives out the google DNS addresses for clients to use.
I have tried changing the region to france per your posted instructions, but there was no difference in the logged errors.  This was all working when it was running DMS6, but DSM 7 does not seem to be working.  I cannot go back, so need to get this working on DSM 7.

### Log output

haugene-transmission-openvpn		
date	stream	content
11/21/2022 18:01	stdout	Use --help for more information.
		
11/21/2022 18:01	stdout	Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/pia/ca_toronto.ovpn
		
11/21/2022 18:01	stdout	Setting OpenVPN credentials...
		
11/21/2022 18:01	stdout	Modification: Updating status for config failure detection
		
11/21/2022 18:01	stdout	"Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
"
11/21/2022 18:01	stdout	Modification: Set output verbosity to 3
		
11/21/2022 18:01	stdout	Modification: Change tls-crypt keyfile path
		
11/21/2022 18:01	stdout	Modification: Update/set resolv-retry to 15 seconds
		
11/21/2022 18:01	stdout	Modification: Change ping options
		
11/21/2022 18:01	stdout	Modification: Change ca certificate path
		
11/21/2022 18:01	stdout	Modification: Point auth-user-pass option to the username/password file
		
11/21/2022 18:01	stdout	Modifying /etc/openvpn/pia/ca_toronto.ovpn for best behaviour in this container
		
11/21/2022 18:01	stdout	Starting OpenVPN using config ca_toronto.ovpn
		
11/21/2022 18:01	stdout	Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
		
11/21/2022 18:01	stdout	Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.bKfU8Nalzk
		
11/21/2022 18:01	stdout	Executing setup script for PIA
		
11/21/2022 18:01	stdout	Provider PIA has a bundled setup script. Defaulting to internal config
		
11/21/2022 18:01	stdout	Running with VPN_CONFIG_SOURCE auto
		
11/21/2022 18:01	stdout	Using OpenVPN provider: PIA
		
11/21/2022 18:01	stdout	Creating TUN device /dev/net/tun
		
11/21/2022 18:01	stdout	Starting container with revision: 42d00652323b7b7fbee1689a54219599f4795a04

### HW/SW Environment

```markdown
- OS:Synology DSM 7
- Docker:Latest Image
```

**Comment by LL0001** [comment]
this magically resolved itself by turning off privileged launch, letting it fail, then re-enabling it.  I also ensured my tunnel.sh was launched.  Not sure why this was an issue after upgrade as it effectively didnt change overall.  My tunnel script was already running, and turning a setting off and on again should not have made a difference.

**Comment by khad** [comment]
> this magically resolved itself by turning off privileged launch, letting it fail, then re-enabling it.

My jaw just dropped. I'd been putting off the DSM 7 upgrade as long as possible, because I just didn't want to deal with a problem like this. I've been trying for hours to figure it out for hours. I was almost ready to give up, then I happened to see this issue.

I am in utter disbelief that what you described actually worked, but IT FIXED MY PROBLEM. For anyone else reading this:

1. Stop the container.
2. Turn off "Execute container using high privilege".
3. Start the container.
4. It will stop with this notification: "Docker container haugene-transmission-openvpn stopped unexpectedly."
5. Turn on "Execute container using high privilege".

Now it works.

I kind of don't even care, but WTF? How is that even possible?

THANK YOU!

**Comment by LL0001** [comment]
Khad,

I was very surprised  getting a notice on this very old issue I also had spent hours troubleshooting. Very happy it was useful to at least one other person out there 😁. I also cannot explain why it worked. I happened to just stumble on the solution when trying different things. I also have had no further issues with it since the upgrade to DSM7. 

Your note was kinda like a bonus feel good Christmas present for me.

Good luck on your projects!

**Comment by wildoracle** [comment]
I'm still stuck with a container that starts then stops. For some reason, Synology container manager won't allow me to have empty fields as you show here. It simply won't allow me to save the settings if the fields are empty! I've tried using "" instead. Nothing seems to work. Here's my log, I can't figure it out!
[haugene-transmission-openvpn.csv](https://github.com/haugene/docker-transmission-openvpn/files/13929140/haugene-transmission-openvpn.csv)

**Comment by khad** [comment]
@wildoracle I actually ended up going back to version 4.3.2 of the Docker image. Not sure it's a good long term solution, but I just wanted something that works.

Sorry I don't know anything about empty values. I hope you're able to get it resolved!

**Comment by wildoracle** [comment]
Thanks @khad - I've tried starting from scratch, using different versions (I'll try 4.3.2 next), using [the method shown here](https://youtu.be/4j08wtID_KA?si=vWh9uU7aY_CqcLf4) (using the "project" tab rather than the "container" tab), and nothing seems to work anymore.

**Comment by LL0001** [comment]
@wildoracle @khad 
So I saw this thread pop back up when I was out and about today, and decided to check my own container since I have been consistently running the container and updating to the latest version via Container Manager Image Updater as I see it flagged when there was an update.  Needless to say, since I have had no issues with it at all this time since my initial issue years ago, I thought it was a good idea to check my logs and make sure everything was actually running well/correctly.

I compared your screenshot above to my own config, and low and behold **I also did not have any entries loaded for those same items that are giving you issues.**  Since I had to correct an error I saw on my logs related to wanting the Transmission_Home directly to be run from the /config/Transmission_Home folder now (apparently my older mapping is now deprecated and may break in the future), when I updated my mapping those same entries above **also flagged as errors for me when I tried to save the new config**.

Not being one to admit defeat for something seemingly stupid, and considering my previous config was working fine, I knew that **those items were not actually needed so I deleted them, saved the config, and started the container as normal.  Everything is working perfectly for me now again**.

I will note however, that in your spreadsheet logs I noticed that you have several entries stating "configurations download site reachable", so you may be pointing to the wrong site, maybe your DNS resolution is not working right, or something else is going on for your container besides the configs above.

**Comment by wildoracle** [comment]
I got this thing working now and staying connected!
For the SYNOLOGY users out there, hopefully these two tips help:

1. you DO have to include LOCAL_NETWORK and for me that's `192.168.1.0/24` because my local IP of the Synology is 192.168.1.144
2. you DON'T want to use single or double quotes in the OPENVPN_OPTS settings. What worked for me is what @edgd1er shared: `--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore "ping"`

**Comment by LL0001** [comment]
Glad you got it working. I couldn't see your local network entry in your screenshot or probably would have flagged it. I have mine set to a /16 as seen at the top of the thread.

I don't have the OPENVPN_OPTS configured, never have, but recently deleted that line after getting the errors like you. Good to know what I can use it for if ever needed though. Thanks!

**Comment by wildoracle** [comment]
THIS THREAD https://github.com/haugene/docker-transmission-openvpn/discussions/2395 might help with some additional info

**Comment by LL0001** [comment]
Appreciate the link. Looks like it is for Nord specific use. I use PIA so can already specify which servers I want to use (not all servers support port reservation options). If I ever change over to Nord or another that has API query limiting, I'll keep this in mind.
