### ISSUE TITLE
Issue on RA4W, dev or latest version

### ISSUE THREAD

**Issue by gtrhayrug** [haugene/docker-transmission-openvpn#243]
Hi,

Using docker on Qnap 453A, i've download the dev or the latest build.
I have configured all the parameters in order to use RA4W (i've tried the RA4W on a virtual debian machine and of course my account works perfectly).

The console says : 

`1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
Tue May  2 15:58:32 2017 UDPv4 link remote: [AF_INET]45.76.87.233:1194                                                                                          
Tue May  2 15:58:32 2017 TLS: Initial packet from [AF_INET]45.76.87.233:1194, sid=72dc717c 795e4277                                                             
Tue May  2 15:58:32 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this                               
Tue May  2 15:58:32 2017 VERIFY OK: depth=1, CN=RA4WVPN                                                                                                         
Tue May  2 15:58:32 2017 VERIFY OK: depth=0, CN=RA4WVPN                                                                                                         
Tue May  2 15:58:33 2017 Data Channel Encrypt: Cipher 'AES-128-CBC' initialized with 128 bit key                                                                
Tue May  2 15:58:33 2017 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication                                                        
Tue May  2 15:58:33 2017 Data Channel Decrypt: Cipher 'AES-128-CBC' initialized with 128 bit key                                                                
Tue May  2 15:58:33 2017 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication                                                        
Tue May  2 15:58:33 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA                                                            
Tue May  2 15:58:33 2017 [RA4WVPN] Peer Connection Initiated with [AF_INET]45.76.87.233:1194                                                                    
Tue May  2 15:58:35 2017 SENT CONTROL [RA4WVPN]: 'PUSH_REQUEST' (status=1)                                                                                      
Tue May  2 15:58:35 2017 AUTH: Received control message: AUTH_FAILED                                                                                            
Tue May  2 15:58:35 2017 SIGTERM[soft,auth-failure] received, process exiting            `

If i try to take a look inside the dock... (with no login/password set) in the console mode.
I've try in latest version (provided by docker), dev version.
In the latest version, the config ovpn are not okay (remote server are not alive)
I've try to replace with the new zip version (using sh scripts inside the docker), not working, auth problem.
Using the dev version, same trouble but i can't access to the console.

I've sent the ovpn last version, please find attach.

[config.zip](https://github.com/haugene/docker-transmission-openvpn/files/971033/config.zip)

Using SSH to launch docker container, same issue of course, but i can change some options if needed.

https://i.imgur.com/QQBB146.png

https://i.imgur.com/OPWI7zS.png

**Comment by gtrhayrug** [comment]
Hi, any news ? any help ?

**Comment by haugene** [comment]
Hey!

Sorry about the slow response, haven't had much time to spare lately. But just to make sure, when you say you've tried RA4W on a virtual debian machine, that is using openvpn? Sometimes there is a different username/password pair for a desktop client application and using openvpn.

As it says `Peer Connection Initiated` it seems to connect fine. Then the `AUTH_FAILED` strongly suggest a username/password error. Do you have any special characters in your username or password? Can you check the contents of `/config/openvpn-credentials.txt` inside the container?

To check the content you can run `docker exec -it <container-name> cat /config/openvpn-credentials.txt`, changing container-name to your container.
