### ISSUE TITLE
Container freezing while deploying

### ISSUE THREAD

**Issue by lobf** [haugene/docker-transmission-openvpn#2452]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

version: '3.3'

services:
    transmission-openvpn:
        container_name: transmission-openvpn
        cap_add:
            - NET_ADMIN
        volumes:
            - '/media/:/media'
        environment:
            - OPENVPN_PROVIDER=NORDVPN
            - OPENVPN_CONFIG=default
            - OPENVPN_USERNAME=*****
            - OPENVPN_PASSWORD=*****
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

### Current Behavior

I used this stack to deploy the container earlier this evening. I stopped it a couple of times to do some experimenting with other containers, and now when I deploy the stack, it begins and then ends without anything happening in the log. Here's how the log looks:

`Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
WARNING: initial DNS resolution test failed
INFO: OVPN: Checking curl installation
Creating TUN device /dev/net/tun
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN`

After that nothing- it just stops running. Portainer will show me:

" Stopped for X minutes with exit code 9" 

### Expected Behavior

Earlier in the night, the container was showing as healthy. Now it ends without explanation. 

### How have you tried to solve the problem?

I'm a newbie, I'm just learning about containers, I'm really not sure how to diagnose this problem or who could help me, I'm sorry... 

### Log output

Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
WARNING: initial DNS resolution test failed
INFO: OVPN: Checking curl installation
Creating TUN device /dev/net/tun
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN

      
      
    

### HW/SW Environment

```markdown
- OS: QTS 5.0.1.2194
- Docker: If this if for the docker compose version, I'm seeing: 2.10.2
```

**Comment by ilike2burnthing** [comment]
https://haugene.github.io/docker-transmission-openvpn/provider-specific/#nordvpn

**Comment by pkishino** [comment]
Please don’t open issues for provider related things or something where you are unsure if you have a problem with your setup (which is what you look like you have)
