### ISSUE TITLE
Container exiting due to fatal error

### ISSUE THREAD

**Issue by exoplanettech** [haugene/docker-transmission-openvpn#2453]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [x] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

transmission-openvpn:
        container_name: Transmission-VPN
        image: haugene/transmission-openvpn
        restart: always
        volumes:
            - /home/administrator/docker/transmission/data:/data
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=vpnunlimited
            - OPENVPN_CONFIG=fr
            - OPENVPN_USERNAME=#########################
            - OPENVPN_PASSWORD=#########################
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - WEBPROXY_ENABLED=true
            - WEBPROXY_PORT=8118
            - LOCAL_NETWORK=192.168.1.0/24
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
            - 8888:8888
            - 8118:8118

### Current Behavior

The container starts but stops shortly afterward

### Expected Behavior

Container start without issue.started

### How have you tried to solve the problem?

1) Deleted container and rebuild
2) Deleted host folders and container, rebuild
3) Created new credentials from the provider (performed steps 1/2 again)
4) Followed troubleshooting instructions using Donald Duck and still get the same error.

### Log output

Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Creating TUN device /dev/net/tun
Using OpenVPN provider: VPNUNLIMITED
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for VPNUNLIMITED. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.uwJdADDBqI
Extracting configs to /tmp/tmp.KfkKWz2liM
Found configs for VPNUNLIMITED in /tmp/tmp.KfkKWz2liM/vpn-configs-contrib-main/openvpn/vpnunlimited, will replace current content in /etc/openvpn/vpnunlimited
Cleanup: deleting /tmp/tmp.uwJdADDBqI and /tmp/tmp.KfkKWz2liM
Starting OpenVPN using config fr.ovpn
Modifying /etc/openvpn/vpnunlimited/fr.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
Setting OpenVPN credentials...
2022-12-01 16:15:58 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
2022-12-01 16:15:58 OpenVPN 2.5.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 14 2022
2022-12-01 16:15:58 library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
2022-12-01 16:15:58 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2022-12-01 16:15:58 OpenSSL: error:0A00018E:SSL routines::ca md too weak
2022-12-01 16:15:58 Cannot load inline certificate file
2022-12-01 16:15:58 Exiting due to fatal error

### HW/SW Environment

```markdown
- OS: 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

- Docker:
Docker version 20.10.21, build baeda1f
```

### Anything else?

I'm running another container with the same docker-compose file (but different credentials) and this container is running fine. I have changed the login credentials on this working container and both sets work (old and new).

Any help would be appreciated. Was running with the same configuration for months without issue until last week.

**Comment by golgoth73** [comment]
I have the same issue.
On a pi4 debian bullseye rolling nicely 24/7 for on year.

**Comment by edgd1er** [comment]
well, as written in the logs this is certificate problem (openvpn config file): ```
2022-12-01 16:15:58 OpenSSL: error:0A00018E:SSL routines::ca md too weak```
contact your vpn provider to request an update of its config files.
this is not a project/container issue.

If you really want to use these low security config files, You may lower security settings to allow weak certificates.
Please note that I would not apply this to my container, I do not advise you to apply this fix.
```# allow weak certificates (certificate signed with SHA1)
# by downgrading OpenSSL security level from 2 to 1
sed -i 's/SECLEVEL=2/SECLEVEL=1/g' /etc/ssl/openssl.cnf
```

**Comment by pkishino** [comment]
As above, this is provider problem related with outdated config files.

**Comment by ahamill85** [comment]
@edgd1er  Do we have to build a new image to use that command? I doubt VPN Unlimited are going to update their configs any time soon.

**Comment by pkishino** [comment]
> @edgd1er Do we have to build a new image to use that command? I doubt VPN Unlimited are going to update their configs any time soon.

Contact their support and inform them of their outdated configs..

**Comment by edgd1er** [comment]
@ahamill85 , I would not recommend to build an image with such a weak setting. You can, as a workaround, either run the sed command in the container, or if the container does not run long enough to execute the command, you may export and mount the modified file.

Please note that this is only a workaround, and your provider should definitely update its config files. If security  appears not be important for your provider, you may consider to switch for a provider that is more prone to protect your data and privacy.

**Comment by ahamill85** [comment]
@edgd1er thank you for your insight. It is very much appreciated. I'm going to reach send a message to VPN Unlimited. Do you mind providing any additional details that I could include in my request? I'm not well-versed in VPN technology, so I'm not exactly sure what I'm asking them to do, other than "update their OpenVPN configuration". Also, once they update their config, is this something where we'll need to update something on our side or will our current configurations run smooth again?

**Comment by edgd1er** [comment]
@ahamill85 , certificates (ca, servers, clients) have to be regenerated with proper ciphers. I hope they know what to do.

Copied from stackoverflow: https://superuser.com/questions/1737052/openssl-error0a00018essl-routinesca-md-too-weak
```
The answer is in the error messages (error:0A00018E:SSL routines::ca md too weak). 
OpenSSL refuses to use the CA certificate because certain parameters are considered insecure nowadays.
 This could be caused by the certificate using MD5 or SHA1 for signing.

You should regenerate your CA and certificates with secure ciphers, as your current ciphers are considered not secure anymore.
```

**Comment by exoplanettech** [comment]
From my testing and tinkering around I have found the issue to be due to my underlying OS being at later version. 

When running the container on Ubuntu 20.04 I have no problems and container starts fine... however running the same compose file and provider details on Ubuntu 22.04 I then run into the issues. 

All workarounds I have come across have the assumption that OpenVPN is installed locally on the host OS which in this case it isn't.

As the container doesn't start long enough to SSH into it... You mention passing though the file to the host so we can edit it on the host before startup... do you know the exact location and file name inside the container I'd need to pass through?

Many Thanks

**Comment by exoplanettech** [comment]
Just had word back from VPN Unlimited and seems the issue should be resolved in the next 4 weeks "ish"

> Hello!
>  
> Thank you for contacting us.
>  
> Currently there is an issue with the performance of ovpn. settings on newer Linux OS versions that we support.
> In fact, our technical department has already generated new CAs and certificates, but in order to implement them, we need to update all our servers. 
> This process has already been planned and is expected to take place in the near future (to be precise, we expect to complete the process within a month).In the meantime,
> As a temporary workaround, you can add this line to your OVPN file:
> tls-cipher=DEFAULT:@SECLEVEL=0 
> This way you can turn off errors in the logs and this will help establish a VPN connection._
> 

I'm currently running my container on an older version of Ubuntu so will try again middle of Feb.

**Comment by rumym** [comment]
Has anyone confirmed that this was done by VPNUnlimited?

**Comment by 3dSquare** [comment]
I am running into the same issue and have gotten the same response as all others before from VPNUnlmited support:

> I confirm that we are aware of the issue with OpenSSL v.3.
> In fact, our technical department has already generated new CAs and certificates, but in order to implement them, we need to update all our servers. This process has already been planned and is expected to take place in the near future.

I have tried the workaround as mentioned by @edgd1er: Copied the `/etc/ssl/openssl.cnf` from the container, modified the last line to read: `CipherString = DEFAULT:@SECLEVEL=0` (tried `SECLEVEL=1` as well) and mapped the file into the location of the file inside the container via `docker-compose.yml`.

I am still getting the same error:
```
vpn                     | 2023-10-21 07:25:49 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
vpn                     | 2023-10-21 07:25:49 OpenVPN 2.5.5 aarch64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 14 2022
vpn                     | 2023-10-21 07:25:49 library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
vpn                     | 2023-10-21 07:25:49 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
vpn                     | 2023-10-21 07:25:49 OpenSSL: error:0A00018E:SSL routines::ca md too weak
vpn                     | 2023-10-21 07:25:49 Cannot load inline certificate file
vpn                     | 2023-10-21 07:25:49 Exiting due to fatal error
```

**Comment by pkishino** [comment]
@3dSquare  please add 
tls-cipher=DEFAULT:@SECLEVEL=0
To the ovpn config and try

**Comment by 3dSquare** [comment]
Didn't work either, unfortunatelly. The container exists with the same error message.

**Comment by pkishino** [comment]
> @pkishino Didn't work either, unfortunatelly. The container exists with the same error message.

Then you haven’t done that step properly.. use the CUSTOM provider, manually grab the ovpn file from the repo, follow above steps and the manual if necessary.. if all else then please your full config and full logs

**Comment by samdeviron** [comment]
@3dSquare adding the following lines to modify-openvpn-config.sh made it work for me:

`## Option 9 - Add or modify tls-cipher directive for adjusting OpenSSL security level
echo "Modification: Adjust OpenSSL security level"
# Remove any old tls-cipher option
sed -i "/^tls-cipher.*$/d" "$CONFIG"

# Add the new directive
sed -i "\$q" "$CONFIG" # Ensure config ends with a line feed
echo "tls-cipher DEFAULT:@SECLEVEL=0" >> "$CONFIG"`

Clone the repo, add the lines in ./openvpn/modify-openvpn-config.sh, re-run docker build:
`docker build -t transmission-openvpn .`
Then change docker-compose.yml to use your local build of the container:
**docker-compose.yml**
`image: transmission-openvpn`

**Comment by 3dSquare** [comment]
@samdeviron thanks a bunch! I copied the shell script out to the host, made the modification as you suggested, and use volume mapping to map the shell script to its location within the container. Now it's starting up fine again!
Hopefully VPN Unlimited fixes their issue soon though!

**Comment by will09122000** [comment]
So VPN Unlimited still haven't fixed this?

Getting this error on container startup:
`2024-04-06 13:29:20 VERIFY ERROR: depth=1, error=certificate has expired: C=US, ST=NY, L=New York, O=Simplex Solutions Inc., OU=Vpn Unlimited, CN=server.vpnunlimitedapp.com, name=server.vpnunlimitedapp.com, emailAddress=support@simplexsolutionsinc.com, serial=12327878784855983598`
