### ISSUE TITLE
Ubuntu 22.04 changed to nftables from iptables

### ISSUE THREAD

**Issue by RJSzynal** [haugene/docker-transmission-openvpn#2455]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

```
[Unit]
Description=Transmission Container
After=docker.service
Requires=docker.service
After=traefik.service
Requires=traefik.service

[Service]
Environment="TORRENT_IMAGE=haugene/transmission-openvpn:latest"
Environment="TORRENT_NAME=transmission"
Environment="LOCAL_USER=myuser"
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull ${TORRENT_IMAGE}
ExecStartPre=-/usr/bin/docker rm -fv ${TORRENT_NAME}
ExecStart=/usr/bin/docker run --rm -t --name ${TORRENT_NAME} \
        -h ${TORRENT_NAME} \
        --cap-add=NET_ADMIN --device=/dev/net/tun \
        --dns 8.8.8.8 --dns 8.8.4.4 \
        -p 9091:9091 \
        -l traefik.enable=true \
        -l traefik.http.routers.${TORRENT_NAME}.rule=Host(\"mydomain.co.uk\")&&PathPrefix(\"/transmission\") \
        -l traefik.http.routers.${TORRENT_NAME}.entrypoints=websecure \
        -l traefik.http.routers.${TORRENT_NAME}.tls=true \
        -l traefik.http.routers.${TORRENT_NAME}.tls.certresolver=mydomaincoukchallenge \
        -l traefik.http.routers.${TORRENT_NAME}.middlewares=internal-only@file \
        -l traefik.http.services.transmission.loadbalancer.server.port=9091 \
        -l traefik.http.services.transmission.loadbalancer.server.scheme=http \
        -v /etc/localtime:/etc/localtime:ro \
        -v /home/${LOCAL_USER}/torrent:/data \
        --env-file /home/${LOCAL_USER}/torrent/configs/${TORRENT_NAME}/DockerEnv \
        ${TORRENT_IMAGE}
ExecStop=-/usr/bin/docker rm -fv ${TORRENT_NAME}

[Install]
WantedBy=multi-user.target```

### Current Behavior

With Ubuntu 22 the default firewall was changed from iptables to nftables. The image appears to not have the iptables-legacy translation layer installed but rather the default iptables-nft translation layer (evidenced by the `ip6tables-restore v1.8.7 (nf_tables)` messages) which the script would need if it was to stay unchanged using the iptables commands instead of new nftables ones. I get the output attached to the "log output" section when using 4.3 or dev images

### Expected Behavior

The firewall rules should be set without error as they are in version 4.2 and earlier.

### How have you tried to solve the problem?

 I have worked through all tag versions starting with 3.7 working up until the image began failing to start up. The container is not sharing my host network stack so the local setup should have no impact however, for the sake of completeness, my host is running iptables and does not have nftables:
 `iptables v1.4.21`
 `nft: command not found`
 `nftables: command not found`

### Log output

```
Dec 03 12:07:18 myserver docker[15654]: Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Dec 03 12:07:18 myserver docker[15654]: Using OpenVPN provider: PIA
Dec 03 12:07:18 myserver docker[15654]: Running with VPN_CONFIG_SOURCE auto
Dec 03 12:07:18 myserver docker[15654]: Provider PIA has a bundled setup script. Defaulting to internal config
Dec 03 12:07:18 myserver docker[15654]: Executing setup script for PIA
Dec 03 12:07:18 myserver docker[15654]: Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.lG1QDIfiy3
Dec 03 12:07:18 myserver docker[15654]: Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Dec 03 12:07:18 myserver docker[15654]: Starting OpenVPN using config switzerland.ovpn
Dec 03 12:07:18 myserver docker[15654]: Modifying /etc/openvpn/pia/switzerland.ovpn for best behaviour in this container
Dec 03 12:07:18 myserver docker[15654]: Modification: Point auth-user-pass option to the username/password file
Dec 03 12:07:18 myserver docker[15654]: Modification: Change ca certificate path
Dec 03 12:07:18 myserver docker[15654]: Modification: Change ping options
Dec 03 12:07:18 myserver docker[15654]: Modification: Update/set resolv-retry to 15 seconds
Dec 03 12:07:18 myserver docker[15654]: Modification: Change tls-crypt keyfile path
Dec 03 12:07:18 myserver docker[15654]: Modification: Set output verbosity to 3
Dec 03 12:07:18 myserver docker[15654]: Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Dec 03 12:07:18 myserver docker[15654]: Modification: Updating status for config failure detection
Dec 03 12:07:18 myserver docker[15654]: Setting OpenVPN credentials...
Dec 03 12:07:18 myserver docker[15654]: enabling firewall
Dec 03 12:07:19 myserver docker[15654]: ERROR: problem running ufw-init
Dec 03 12:07:19 myserver docker[15654]: ip6tables-restore v1.8.7 (nf_tables):
Dec 03 12:07:19 myserver docker[15654]: line 7: CHAIN_UPDATE failed (No such file or directory): chain INPUT
Dec 03 12:07:19 myserver docker[15654]: line 7: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 7: CHAIN_UPDATE failed (No such file or directory): chain FORWARD
Dec 03 12:07:19 myserver docker[15654]: line 7: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 7: CHAIN_UPDATE failed (No such file or directory): chain OUTPUT
Dec 03 12:07:19 myserver docker[15654]: line 7: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 7: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: iptables-restore v1.8.7 (nf_tables):
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 42: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: li
Dec 03 12:07:19 myserver docker[15654]: iptables-restore: line 4 failed
Dec 03 12:07:19 myserver docker[15654]: iptables-restore v1.8.7 (nf_tables):
Dec 03 12:07:19 myserver docker[15654]: line 4: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: iptables-restore v1.8.7 (nf_tables):
Dec 03 12:07:19 myserver docker[15654]: line 8: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 8: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 8: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 8: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 8: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: iptables-restore v1.8.7 (nf_tables): Chain 'ufw-logging-deny' does not exist
Dec 03 12:07:19 myserver docker[15654]: Error occurred at line: 75
Dec 03 12:07:19 myserver docker[15654]: Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Dec 03 12:07:19 myserver docker[15654]: iptables-restore v1.8.7 (nf_tables): Chain 'ufw-skip-to-policy-input' does not exist
Dec 03 12:07:19 myserver docker[15654]: Error occurred at line: 30
Dec 03 12:07:19 myserver docker[15654]: Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Dec 03 12:07:19 myserver docker[15654]: iptables-restore v1.8.7 (nf_tables):
Dec 03 12:07:19 myserver docker[15654]: line 10: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 10: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 10: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 10: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 10: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 10: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 10: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: iptables-restore v1.8.7 (nf_tables):
Dec 03 12:07:19 myserver docker[15654]: line 11: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 11: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 11: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 11: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 11: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 11: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 11: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: iptables-restore v1.8.7 (nf_tables): Chain 'ufw-user-input' does not exist
Dec 03 12:07:19 myserver docker[15654]: Error occurred at line: 5
Dec 03 12:07:19 myserver docker[15654]: Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Dec 03 12:07:19 myserver docker[15654]: iptables-restore v1.8.7 (nf_tables):
Dec 03 12:07:19 myserver docker[15654]: line 6: CHAIN_UPDATE failed (No such file or directory): chain INPUT
Dec 03 12:07:19 myserver docker[15654]: line 6: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 6: CHAIN_UPDATE failed (No such file or directory): chain FORWARD
Dec 03 12:07:19 myserver docker[15654]: line 6: TABLE_ADD failed (No such file or directory): table filter
Dec 03 12:07:19 myserver docker[15654]: line 6: CHAIN_UPDATE failed (No such file or directory): chain OUTPUT
Dec 03 12:07:19 myserver docker[15654]: sysctl: setting key "net.ipv4.conf.all.accept_redirects", ignoring: Read-only file system
Dec 03 12:07:19 myserver docker[15654]: sysctl: setting key "net.ipv4.conf.default.accept_redirects", ignoring: Read-only file system
Dec 03 12:07:19 myserver docker[15654]: sysctl: setting key "net.ipv6.conf.all.accept_redirects", ignoring: Read-only file system
Dec 03 12:07:19 myserver docker[15654]: sysctl: setting key "net.ipv6.conf.default.accept_redirects", ignoring: Read-only file system
Dec 03 12:07:19 myserver docker[15654]: sysctl: setting key "net.ipv4.icmp_echo_ignore_broadcasts", ignoring: Read-only file system
Dec 03 12:07:19 myserver docker[15654]: sysctl: setting key "net.ipv4.icmp_ignore_bogus_error_responses", ignoring: Read-only file system
Dec 03 12:07:19 myserver docker[15654]: sysctl: setting key "net.ipv4.icmp_echo_ignore_all", ignoring: Read-only file system
Dec 03 12:07:19 myserver docker[15654]: sysctl: setting key "net.ipv4.conf.all.log_martians", ignoring: Read-only file system
Dec 03 12:07:19 myserver docker[15654]: sysctl: setting key "net.ipv4.conf.default.log_martians", ignoring: Read-only file system
Dec 03 12:07:19 myserver docker[15654]: Problem loading ipv6 (skipping)
Dec 03 12:07:19 myserver docker[15654]: Problem running '/etc/ufw/before.rules'
Dec 03 12:07:19 myserver docker[15654]: Problem running '/etc/ufw/after.rules'
Dec 03 12:07:19 myserver docker[15654]: Problem running '/etc/ufw/user.rules'
Dec 03 12:07:20 myserver systemd[1]: torrent.service: main process exited, code=exited, status=1/FAILURE
Dec 03 12:07:20 myserver systemd[1]: Unit torrent.service entered failed state.
Dec 03 12:07:20 myserver systemd[1]: torrent.service failed.
Dec 03 12:07:20 myserver systemd[1]: torrent.service holdoff time over, scheduling restart.
Dec 03 12:07:20 myserver systemd[1]: Stopped Transmission Container.
```

### HW/SW Environment

```markdown
- OS: CentOS Linux release 7.9.2009 (Core) / Linux myserver 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Docker: Docker version 20.10.21, build baeda1f
```

### Anything else?

My guess at the solution is to either re-write all the scripts that call iptables to the  new nftables equivalents or, as a quick fix, install iptables-legacy in the dockerfile.

**Comment by RJSzynal** [comment]
I have tested creating an image with the following and it appears to have solved the problem:
```
from haugene/transmission-openvpn:4.3

RUN update-alternatives --set iptables $(which iptables-legacy) && \
    update-alternatives --set ip6tables $(which ip6tables-legacy)
```

**Comment by RJSzynal** [comment]
I created a PR with a fix but I don't know how to attach it to this issue, if I even can.
https://github.com/haugene/docker-transmission-openvpn/pull/2456

**Comment by ilike2burnthing** [comment]
If you take the line `fixes #2455` out of quotes, it should link the issue and PR.

**Comment by lxz81** [comment]
your PR seems to be working indeed. Good job!

**Comment by pkishino** [comment]
PR merged into dev
