### ISSUE TITLE
Cannot read inline cert after v4.2 with custom provider

### ISSUE THREAD

**Issue by asignorino** [haugene/docker-transmission-openvpn#2464]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

  transmission:
   image: haugene/transmission-openvpn:latest
   cap_add:
     - NET_ADMIN
   devices:
     - /dev/net/tun
   restart: always
   ports:
     - ${TRANSMISSION_PORT}:9091
   dns:
     - 8.8.8.8
     - 8.8.4.4
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - ${NASTORRENTDATA}:/data
     - ${NASDOCKERCFG}/torrent_config/config/:/etc/openvpn/custom/
   environment:
     - OPENVPN_PROVIDER=CUSTOM
     - OPENVPN_USERNAME=user 
     - OPENVPN_PASSWORD=pass
     - CREATE_TUN_DEVICE=true 
     - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
     - LOCAL_NETWORK=192.168.1.0/24
     - PUID=${PUID}
     - PGID=${PGID}
     - TRANSMISSION_WEB_UI=flood-for-transmission
     - HEALTH_CHECK_HOST="google.com"
#    - DEBUG=true

### Current Behavior

transmission would exit for a fatal error

### Expected Behavior

start up properly (not trying to be sarcastic here, just don't know what else to put here)

### How have you tried to solve the problem?

Current workaround is to revert back to v4.2 and the container is running fine.

The issue looks fairly similar to https://github.com/haugene/docker-transmission-openvpn/discussions/1936#discussioncomment-1280562. I say this because I was seeing what looks like a similar ca.crt file error before generating a new openvpn config which was all stored in-line in the .ovpn file now. (I did not grab debug logs from then and cannot gather them now.)

Probably more related to https://github.com/haugene/docker-transmission-openvpn/discussions/1936#discussioncomment-1283008 which links to https://github.com/haugene/docker-transmission-openvpn/commit/8f0a92a2ff365521dfc1f4c529777017145fb0cf 

### Log output

transmission_1  | Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
transmission_1  | WARNING: initial DNS resolution test failed
transmission_1  | Creating TUN device /dev/net/tun
transmission_1  | Using OpenVPN provider: CUSTOM
transmission_1  | Modifying /etc/openvpn/custom/default.ovpn for best behaviour in this container
transmission_1  | Modification: Point auth-user-pass option to the username/password file
transmission_1  | Modification: Change ca certificate path
transmission_1  | Modification: Change ping options
transmission_1  | Modification: Update/set resolv-retry to 15 seconds
transmission_1  | Modification: Change tls-crypt keyfile path
transmission_1  | Modification: Set output verbosity to 3
transmission_1  | Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
transmission_1  | Modification: Updating status for config failure detection
transmission_1  | Setting OpenVPN credentials...
transmission_1  | adding route to local network 192.168.1.0/24 via 192.168.96.1 dev eth0
transmission_1  | 2022-12-11 09:41:30 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
transmission_1  | 2022-12-11 09:41:30 --cipher is not set. Previous OpenVPN version defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.
transmission_1  | 2022-12-11 09:41:30 OpenVPN 2.5.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 14 2022
transmission_1  | 2022-12-11 09:41:30 library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
transmission_1  | 2022-12-11 09:41:30 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission_1  | 2022-12-11 09:41:30 OpenSSL: error:0A00018E:SSL routines::ca md too weak
transmission_1  | 2022-12-11 09:41:30 Cannot load inline certificate file
transmission_1  | 2022-12-11 09:41:30 Exiting due to fatal error

### HW/SW Environment

```markdown
- OS: Ubuntu 22.04 with a Synology on latest DRM as the volume
- Docker: 20.10.12, build 20.10.12-0ubuntu4
```

### Anything else?

Obviously my setup still has some other issues to correct, but finding the commit that looks like my issue seemed worth submitting a bug report.

**Comment by ilike2burnthing** [comment]
https://github.com/haugene/docker-transmission-openvpn/issues/2453#issuecomment-1334813242
