### ISSUE TITLE
rm: cannot remove '/etc/openvpn/protonvpn/default.ovpn': Device or resource busy,

### ISSUE THREAD

**Issue by loughnane** [haugene/docker-transmission-openvpn#2465]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

  transmission-vpn:     container_name: transmission-vpn
    privileged: true
    image: haugene/transmission-openvpn:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - 9091:9091/tcp
      - 9091:9091/udp
      - 8888:8888
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/shared:/shared
      - ${DOCKER_DIR}/resolv.conf:/etc/resolv.conf
      - ${DOCKER_DIR}/transmission-vpn:/data
      - ${MEDIA_DIR}:/data/watch
      - ${MEDIA_DIR}/torrents:/data/completed
      - ${MEDIA_DIR}/incomplete:/data/incomplete
      - ${DOCKER_DIR}/transmission-vpn/ch-ca-01.protonvpn.com.udp.ovpn:/etc/openvpn/protonvpn/default.ovpn
    environment:
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_USERNAME=abcdefg
      - OPENVPN_PASSWORD=hijklmnop
      - LOCAL_NETWORK=192.168.3.0/24
      - PUID=1031 
      - PGID=65537
      - TZ=${TZ}
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RATIO_LIMIT_ENABLED=false
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=1000
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888

### Current Behavior

Container starts, but I can't access the web portal at http://192.168.3.100:9091/transmission/web/

### Expected Behavior

Should have the container start and let me access the web portal at http://192.168.3.100:9091/transmission/web/

### How have you tried to solve the problem?

1) Changing path to certificate from protonvpn/ to custom/
2) Changing permissions of all files to be owned by user running docker cofntainer
3) Upgrading to latest image

### Log output

Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: PROTONVPN,
Running with VPN_CONFIG_SOURCE auto,
No bundled config script found for PROTONVPN. Defaulting to external config,
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.gvzyjnoykn,
Extracting configs to /tmp/tmp.A1ZJHZEkow,
Found configs for PROTONVPN in /tmp/tmp.A1ZJHZEkow/vpn-configs-contrib-main/openvpn/protonvpn, will replace current content in /etc/openvpn/protonvpn,
Cleanup: deleting /tmp/tmp.gvzyjnoykn and /tmp/tmp.A1ZJHZEkow,
rm: cannot remove '/etc/openvpn/protonvpn/default.ovpn': Device or resource busy,
Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: PROTONVPN,
Running with VPN_CONFIG_SOURCE auto,
No bundled config script found for PROTONVPN. Defaulting to external config,
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.tXuvYGyaXX,
Extracting configs to /tmp/tmp.nFcqVULPdC,
Found configs for PROTONVPN in /tmp/tmp.nFcqVULPdC/vpn-configs-contrib-main/openvpn/protonvpn, will replace current content in /etc/openvpn/protonvpn,
rm: cannot remove '/etc/openvpn/protonvpn/default.ovpn': Device or resource busy,
Cleanup: deleting /tmp/tmp.tXuvYGyaXX and /tmp/tmp.nFcqVULPdC,
Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: PROTONVPN,
Running with VPN_CONFIG_SOURCE auto,
No bundled config script found for PROTONVPN. Defaulting to external config,
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.4FFeEElZm3,
Extracting configs to /tmp/tmp.8PvfhGlW4z,
Found configs for PROTONVPN in /tmp/tmp.8PvfhGlW4z/vpn-configs-contrib-main/openvpn/protonvpn, will replace current content in /etc/openvpn/protonvpn,
rm: cannot remove '/etc/openvpn/protonvpn/default.ovpn': Device or resource busy,
Cleanup: deleting /tmp/tmp.4FFeEElZm3 and /tmp/tmp.8PvfhGlW4z,
Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: PROTONVPN,
Running with VPN_CONFIG_SOURCE auto,
No bundled config script found for PROTONVPN. Defaulting to external config,
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.vKETbdCrfZ,
Extracting configs to /tmp/tmp.lzlB6MaOxc,
Found configs for PROTONVPN in /tmp/tmp.lzlB6MaOxc/vpn-configs-contrib-main/openvpn/protonvpn, will replace current content in /etc/openvpn/protonvpn,
rm: cannot remove '/etc/openvpn/protonvpn/default.ovpn': Device or resource busy,
Cleanup: deleting /tmp/tmp.vKETbdCrfZ and /tmp/tmp.lzlB6MaOxc,
Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: PROTONVPN,
Running with VPN_CONFIG_SOURCE auto,
No bundled config script found for PROTONVPN. Defaulting to external config,
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.up75Iuacuj,
Extracting configs to /tmp/tmp.LpL0U4CQmF,
Found configs for PROTONVPN in /tmp/tmp.LpL0U4CQmF/vpn-configs-contrib-main/openvpn/protonvpn, will replace current content in /etc/openvpn/protonvpn,
rm: cannot remove '/etc/openvpn/protonvpn/default.ovpn': Device or resource busy,
Cleanup: deleting /tmp/tmp.up75Iuacuj and /tmp/tmp.LpL0U4CQmF,
Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: PROTONVPN,
Running with VPN_CONFIG_SOURCE auto,
No bundled config script found for PROTONVPN. Defaulting to external config,
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.9fQo0XKEEY,
Extracting configs to /tmp/tmp.6GLqfnroo6,
Found configs for PROTONVPN in /tmp/tmp.6GLqfnroo6/vpn-configs-contrib-main/openvpn/protonvpn, will replace current content in /etc/openvpn/protonvpn,
rm: cannot remove '/etc/openvpn/protonvpn/default.ovpn': Device or resource busy,
Cleanup: deleting /tmp/tmp.9fQo0XKEEY and /tmp/tmp.6GLqfnroo6,
Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: PROTONVPN,
Running with VPN_CONFIG_SOURCE auto,
No bundled config script found for PROTONVPN. Defaulting to external config,
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.sPMMD6HD6z,

### HW/SW Environment

```markdown
- OS: Synology DSM 6.2.4-25556 Update 6 running on DS218+
- Docker: version 20.10.3, build b35e731
```

**Comment by svloosbroek** [comment]
I have the same problem when trying to use a custom VPN script. When reverting to a supplied script it all works fine.

**Comment by pkishino** [comment]
Why are you mounting a ovpn file AND specifying a provider?? Please choose either or.. read the documentation please.
