### ISSUE TITLE
Unresponsive Unhealthy Container

### ISSUE THREAD

**Issue by gwrichard** [haugene/docker-transmission-openvpn#2472]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to the container/transmission?

- [X] I have checked the container repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

version: '3.8'

services:
  transmission:
    image: haugene/transmission-openvpn:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
     - 1.1.1.1
     - 8.8.8.8
     - 8.8.4.4
    ports:
      - 9091:9091 # http://nas-ip:9091 to access ui
      - 8888:8888 # web-proxy
    environment:
      - LOCAL_NETWORK=192.168.0.0/16
      - OPENVPN_CONFIG=au_sydney # use <filename>.opvn 
      - OPENVPN_USERNAME=xxx
      - OPENVPN_PASSWORD=xxx
      - OPENVPN_PROVIDER=PIA # PIA or etc
      - CREATE_TUN_DEVICE=true
      - TRANSMISSION_WEB_UI=transmission-web-control
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888
      - WEBPROXY_USERNAME=xxx
      - WEBPROXY_PASSWORD=xxx
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TZ=Australia/Brisbane
      
    deploy:
      resources:
        limits:
          memory: 1024M
    volumes:
      - /volume1/docker/transmission-openvpn/resolv.conf:/etc/resolv.conf:ro # use to stop dns-leak
      - /volume1/Downloads/TransmissionVPN:/data # change to download dir
      - /volume1/docker/transmission-openvpn/config:/config
    network_mode: bridge

### Current Behavior

Transmission container never reports a health status to Docker. It eventually becomes unresponsive and is inaccessible via the web UI after a few hours.

Of note is that I can still attach the console to the container when it is unresponsive 

![image](https://user-images.githubusercontent.com/1514873/208389156-529fb194-fcce-4cb3-8e06-4c61d3d00fb3.png)

![image](https://user-images.githubusercontent.com/1514873/208390527-5c3d3698-b1d0-4edf-b507-0013d44ecf82.png)

### Expected Behavior

Container should report health to Docker and restart when unresponsive per the docker configuration. 

### How have you tried to solve the problem?

1) Tried different released of Transmission
2) Tried different containers and config

### Log output

2022-12-19 08:29:21 net_route_v4_add: 128.0.0.0/1 via 10.15.112.1 dev [NULL] table 0 metric -1
2022-12-19 08:29:21 WARNING: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.
2022-12-19 08:29:21 add_route_ipv6(2000::/3 -> :: metric -1) dev tun0
2022-12-19 08:29:21 net_route_v6_add: 2000::/3 via :: dev tun0 table 0 metric -1
/etc/openvpn/tunnelUp.sh: line 58: /etc/resolv.conf: Read-only file system
chmod: changing permissions of '/etc/resolv.conf': Read-only file system
Up script executed with device=tun0 ifconfig_local=10.15.112.178
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.15.112.178
Using Transmission Web Control UI, overriding TRANSMISSION_WEB_HOME
-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------
Updating Transmission settings.json with values from env variables
Attempting to use existing settings.json for Transmission
Successfully used existing settings.json /config/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.15.112.178
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to 
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
STARTING TRANSMISSION
Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=true
Transmission startup script complete.
Privoxy: Starting
Privoxy: Using config file at /etc/privoxy/config
Privoxy: Setting port to 8888
Privoxy: Running as PID 88
2022-12-19 08:29:24 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2022-12-19 08:29:24 Initialization Sequence Completed
Running functions for token based port fowarding
Reserved Port: 24193  Mon Dec 19 08:29:36 AEST 2022
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
    25   100%    9.99 GB  Done        50.0     0.0    0.0  Idle         Paradise.City.2022.1080p.BluRay.x264.DTS-HD.MA.5.1-MT
Sum:            138.6 GB              50.0     0.0
setting transmission port to 24193
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Port is open: Yes
#######################
        SUCCESS        
#######################
Port: 24193
Expiration Sun Feb 19 20:29:36 AEST 2023
#######################
Entering infinite while loop
Every 15 minutes, check port status
Reserved Port: 24193  Mon Dec 19 08:44:56 AEST 2022
Reserved Port: 24193  Mon Dec 19 08:59:56 AEST 2022
Reserved Port: 24193  Mon Dec 19 09:14:56 AEST 2022
Reserved Port: 24193  Mon Dec 19 09:29:57 AEST 2022
Reserved Port: 24193  Mon Dec 19 09:44:57 AEST 2022
Reserved Port: 24193  Mon Dec 19 09:59:57 AEST 2022
Reserved Port: 24193  Mon Dec 19 10:14:57 AEST 2022
Reserved Port: 24193  Mon Dec 19 10:29:57 AEST 2022
Reserved Port: 24193  Mon Dec 19 10:44:58 AEST 2022
Reserved Port: 24193  Mon Dec 19 10:59:58 AEST 2022
Reserved Port: 24193  Mon Dec 19 11:14:58 AEST 2022
Reserved Port: 24193  Mon Dec 19 11:29:58 AEST 2022
Reserved Port: 24193  Mon Dec 19 11:44:58 AEST 2022
Reserved Port: 24193  Mon Dec 19 11:59:59 AEST 2022
Reserved Port: 24193  Mon Dec 19 12:15:00 AEST 2022
Reserved Port: 24193  Mon Dec 19 12:30:01 AEST 2022
Reserved Port: 24193  Mon Dec 19 12:45:02 AEST 2022
Reserved Port: 24193  Mon Dec 19 13:00:04 AEST 2022
Reserved Port: 24193  Mon Dec 19 13:15:05 AEST 2022
Reserved Port: 24193  Mon Dec 19 13:30:07 AEST 2022
Reserved Port: 24193  Mon Dec 19 13:45:08 AEST 2022
Reserved Port: 24193  Mon Dec 19 14:00:08 AEST 2022
Reserved Port: 24193  Mon Dec 19 14:15:09 AEST 2022
Reserved Port: 24193  Mon Dec 19 14:30:10 AEST 2022
Reserved Port: 24193  Mon Dec 19 14:45:10 AEST 2022
Reserved Port: 24193  Mon Dec 19 15:00:12 AEST 2022
Reserved Port: 24193  Mon Dec 19 15:15:13 AEST 2022
Reserved Port: 24193  Mon Dec 19 15:30:16 AEST 2022
Reserved Port: 24193  Mon Dec 19 15:45:17 AEST 2022
Reserved Port: 24193  Mon Dec 19 16:00:18 AEST 2022
Reserved Port: 24193  Mon Dec 19 16:15:18 AEST 2022
Reserved Port: 24193  Mon Dec 19 16:30:19 AEST 2022
Reserved Port: 24193  Mon Dec 19 16:45:20 AEST 2022
Reserved Port: 24193  Mon Dec 19 17:00:21 AEST 2022
Reserved Port: 24193  Mon Dec 19 17:15:22 AEST 2022
Reserved Port: 24193  Mon Dec 19 17:30:22 AEST 2022
Reserved Port: 24193  Mon Dec 19 17:45:22 AEST 2022
Reserved Port: 24193  Mon Dec 19 18:00:22 AEST 2022
Reserved Port: 24193  Mon Dec 19 18:15:23 AEST 2022
Reserved Port: 24193  Mon Dec 19 18:30:23 AEST 2022
Reserved Port: 24193  Mon Dec 19 18:45:23 AEST 2022
Reserved Port: 24193  Mon Dec 19 19:00:23 AEST 2022

### Environment

```markdown
- OS: 	linux x86_64 (containerized)
- Docker: 20.10.3-1308
```

**Comment by crypticviper** [comment]
I have the exact same issue since this morning.

**Comment by gwrichard** [comment]
Bump -- I'm still having this problem with my container.

**Comment by defau1t** [comment]
I've also just started noticing this behaviour on my container. Using NordVPN as a VPN provider, with these log entries:

`2023-05-07 11:12:29 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #32954894 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings`
