### ISSUE TITLE
NORDVPN connection issues when setting credentials

### ISSUE THREAD

**Issue by goffy59** [haugene/docker-transmission-openvpn#2476]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

docker run --cap-add=NET_ADMIN -d \
-v /mnt/atm/torpi/data/:/data \
-v /mnt/atm/torpi/config/:/config \
-e NORDVPN_COUNTRY=NL \
-e NORDVPN_SERVER=nl1018.nordvpn.com \
-e NORDVPN_PROTOCOL=udp \
-e NORDVPN_CATEGORY=legacy_p2p \
-e OPENVPN_PROVIDER=NORDVPN \
-e OPENVPN_CONFIG=nl1018.nordvpn.com.udp1194.ovpn \
-e OPENVPN_USERNAME=*** \
-e OPENVPN_PASSWORD=*** \
-e LOCAL_NETWORK=192.168.1.0/24 \
--log-driver json-file \
--log-opt max-size=10m \
--name=transmission-openvpn \
-p 9091:9091 \
haugene/transmission-openvpn

### Current Behavior

Setting OpenVPN credentials...
/etc/openvpn/start.sh: line 194: /config/openvpn-credentials.txt: Permission denied

### Expected Behavior

being able to access the webui/etc

### How have you tried to solve the problem?

I've checked reddit, google and this github and your documentation. Either I am too stupid or too tired.

### Log output

Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Creating TUN device /dev/net/tun
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN
INFO: OVPN: Checking curl installation
INFO: OVPN: DNS resolution ok
INFO: OVPN: ok, configurations download site reachable
INFO: OVPN: Removing existing configs in /etc/openvpn/nordvpn
INFO: OVPN: server : nl1018.nordvpn.com, load: 15
INFO: OVPN: Downloading config: nl1018.nordvpn.com.ovpn
INFO: OVPN: Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/nl1018.nordvpn.com.udp.ovpn
Starting OpenVPN using config nl1018.nordvpn.com.ovpn
Modifying /etc/openvpn/nordvpn/nl1018.nordvpn.com.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
Setting OpenVPN credentials...
/etc/openvpn/start.sh: line 194: /config/openvpn-credentials.txt: Permission denied

### HW/SW Environment

```markdown
Ubuntu Server 22.04 > KVM: Ubuntu Server 22.04 > Docker Containers

- OS: ubuntu 22.04 server via KVM/Virtual Machine Manager (virtual machine)
- Docker: 
docker version
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:04 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Anything else?

I actually been doing ALOT of things today. I have 3 containers setup perfectly already and this is literally the last piece of the puzzle. Was going to setup VPN and torrent container individually but saw this and was impressed with the documentation. I am not sure why the permissions are not set and on another git hub issue ticket the user didn't actually say what fixed his issue. So I am at a loss as to why this 
"Setting OpenVPN credentials...
/etc/openvpn/start.sh: line 194: /config/openvpn-credentials.txt: Permission denied"
 happens.
Each time I run this I 

 docker stop transmission-openvpn && docker rm transmission-openvpn

**Comment by edgd1er** [comment]
https://github.com/haugene/docker-transmission-openvpn/blob/51e5f1bcbbbc3c6c54b09896a44b6165531a1305/openvpn/start.sh#L194

A simple echo cannot be executed => access denied. what are the mount option for the `-v /mnt/atm/torpi/config/:/config` ?
run `docker exec -it <container-id> bash` and checks rights, you may find some information in the [documentation](https://haugene.github.io/docker-transmission-openvpn/debug/). 

you problem is due to your setup, not to the project nor your provider (at the moment).

**Comment by goffy59** [comment]
That helps a lot, Been banging my head thinking it was something I did wrong in the docker run command. That mount point is an NFS share I mount in fstab: 192.168.1.234:/atm /mnt/atm nfs defaults 0 0

I agree that it is my setup being the issue at this point. I will try to googlefu some things some more now that I know its not the project/provider.

I used a similar setup with jackett and did not have issues like this before. If you have any other pointers let me know.

Thanks for your efforts!

**Comment by Justinzobel** [comment]
I am also coming across this issue. Docker is run as root, I've tried config/data directories in my home directory, on the root of the drive in /transmission and in a mounted storage drive.

**Comment by edgd1er** [comment]
> I am also coming across this issue. Docker is run as root, I've tried config/data directories in my home directory, on the root of the drive in /transmission and in a mounted storage drive.

any logs available ? You may wish to create a new issue, as this one is closed.

**Comment by Justinzobel** [comment]
Sorry I ended up rebuilding my server and haven't had issues since.
