### ISSUE TITLE
Error on startup.sh

### ISSUE THREAD

**Issue by itsdavee316** [haugene/docker-transmission-openvpn#2478]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - /home/chezbippy/new_docker/transmission-vpn:/data
            - /home/chezbippy/new_docker/shared:/shared
            - /home/chezbippy/downloads/completed:/data/completed
            - /home/chezbippy/downloads/incomplete:/data/incomplet
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=france
            - OPENVPN_USERNAME=p7226159
            - OPENVPN_PASSWORD=17-Rav4XLE
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

### Current Behavior

Container startup failure

### Expected Behavior

Container startup

### How have you tried to solve the problem?

Pulled new image, built new stack, 

### Log output

Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
WARNING: initial DNS resolution test failed
Creating TUN device /dev/net/tun
/etc/openvpn/start.sh: line 34:    11 Aborted                 (core dumped) nslookup ${HEALTH_CHECK_HOST:-"google.com"} > /dev/null 2>&1
Using OpenVPN provider: PIA
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for PIA. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.SndTmuPiqk
curl: (6) getaddrinfo() thread failed to start
./etc/openvpn/fetch-external-configs.sh: line 18: config_repo_temp_dir: unbound variable

### HW/SW Environment

```markdown
- OS: Ubuntu 22.04
- Docker: Docker version 19.03.13, build 4484c46d9d
```

**Comment by ilike2burnthing** [comment]
If you've posted your real username and password, I suggest changing them immediately.

**Comment by Forage** [comment]
See https://github.com/haugene/docker-transmission-openvpn/issues/2410#issuecomment-1319299598, either update your docker or add `--security-opt seccomp=unconfined` to your docker run options.
