### ISSUE TITLE
Can't reach the webUI

### ISSUE THREAD

**Issue by Zuescho** [haugene/docker-transmission-openvpn#248]
Hello, i'm trying out your container on an openmediavault machine and run into the problem that i can not reach the webinterface.

i set the LOCAL_NETWORK=192.168.0.0/24 but i still cant seem to reach it.
This is my first time with containers so i do not really know what i'm doing.

            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "OPENVPN_USERNAME=foobar",
                "OPENVPN_PASSWORD=foobar",
                "OPENVPN_PROVIDER=NORDVPN",
                "TRANSMISSION_ALT_SPEED_DOWN=50",
                "TRANSMISSION_ALT_SPEED_ENABLED=false",
                "TRANSMISSION_ALT_SPEED_TIME_BEGIN=540",
                "TRANSMISSION_ALT_SPEED_TIME_DAY=127",
                "TRANSMISSION_ALT_SPEED_TIME_ENABLED=false",
                "TRANSMISSION_ALT_SPEED_TIME_END=1020",
                "TRANSMISSION_ALT_SPEED_UP=50",
                "TRANSMISSION_BIND_ADDRESS_IPV4=0.0.0.0",
                "TRANSMISSION_BIND_ADDRESS_IPV6=::",
                "TRANSMISSION_BLOCKLIST_ENABLED=false",
                "TRANSMISSION_BLOCKLIST_URL=http://www.example.com/blocklist",
                "TRANSMISSION_CACHE_SIZE_MB=4",
                "TRANSMISSION_DHT_ENABLED=true",
                "TRANSMISSION_DOWNLOAD_DIR=/data/completed",
                "TRANSMISSION_DOWNLOAD_LIMIT=100",
                "TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0",
                "TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true",
                "TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5",
                "TRANSMISSION_ENCRYPTION=1",
                "TRANSMISSION_IDLE_SEEDING_LIMIT=30",
                "TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false",
                "TRANSMISSION_INCOMPLETE_DIR=/data/incomplete",
                "TRANSMISSION_INCOMPLETE_DIR_ENABLED=true",
                "TRANSMISSION_LPD_ENABLED=false",
                "TRANSMISSION_MAX_PEERS_GLOBAL=200",
                "TRANSMISSION_MESSAGE_LEVEL=2",
                "TRANSMISSION_PEER_CONGESTION_ALGORITHM=",
                "TRANSMISSION_PEER_ID_TTL_HOURS=6",
                "TRANSMISSION_PEER_LIMIT_GLOBAL=200",
                "TRANSMISSION_PEER_LIMIT_PER_TORRENT=50",
                "TRANSMISSION_PEER_PORT=51413",
                "TRANSMISSION_PEER_PORT_RANDOM_HIGH=65535",
                "TRANSMISSION_PEER_PORT_RANDOM_LOW=49152",
                "TRANSMISSION_PEER_PORT_RANDOM_ON_START=false",
                "TRANSMISSION_PEER_SOCKET_TOS=default",
                "TRANSMISSION_PEX_ENABLED=true",
                "TRANSMISSION_PORT_FORWARDING_ENABLED=false",
                "TRANSMISSION_PREALLOCATION=1",
                "TRANSMISSION_PREFETCH_ENABLED=1",
                "TRANSMISSION_QUEUE_STALLED_ENABLED=true",
                "TRANSMISSION_QUEUE_STALLED_MINUTES=30",
                "TRANSMISSION_RATIO_LIMIT=2",
                "TRANSMISSION_RATIO_LIMIT_ENABLED=false",
                "TRANSMISSION_RENAME_PARTIAL_FILES=true",
                "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true",
                "TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0",
                "TRANSMISSION_RPC_ENABLED=true",
                "TRANSMISSION_RPC_PASSWORD=foobar",
                "TRANSMISSION_RPC_PORT=9092",
                "TRANSMISSION_RPC_URL=/transmission/",
                "TRANSMISSION_RPC_USERNAME=foobar",
                "TRANSMISSION_RPC_WHITELIST=192.168.178.20",
                "TRANSMISSION_RPC_WHITELIST_ENABLED=false",
                "TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=true",
                "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=false",
                "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=",
                "TRANSMISSION_SEED_QUEUE_ENABLED=false",
                "TRANSMISSION_SEED_QUEUE_SIZE=10",
                "TRANSMISSION_SPEED_LIMIT_DOWN=100",
                "TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false",
                "TRANSMISSION_SPEED_LIMIT_UP=100",
                "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false",
                "TRANSMISSION_START_ADDED_TORRENTS=true",
                "TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false",
                "TRANSMISSION_UMASK=2",
                "TRANSMISSION_UPLOAD_LIMIT=100",
                "TRANSMISSION_UPLOAD_LIMIT_ENABLED=0",
                "TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=14",
                "TRANSMISSION_UTP_ENABLED=true",
                "TRANSMISSION_WATCH_DIR=/data/watch",
                "TRANSMISSION_WATCH_DIR_ENABLED=true",
                "TRANSMISSION_HOME=/data/transmission-home",
                "PUID=",
                "PGID=",
                "LOCAL_NETWORK=192.168.0.0/24",
                "OPENVPN_CONFIG=ca32.nordvpn.com.udp1194"

it seems to startup and also created the transmission folders in the right directory so it seems like it is running correctly.

`STARTING TRANSMISSION`
`NO PORT UPDATER FOR THIS PROVIDER`
`Transmission startup script complete.`
`Sun May 14 16:19:49 2017 /sbin/ip route add 184.75.214.83/32 via 172.17.0.1`
`Sun May 14 16:19:49 2017 /sbin/ip route add 0.0.0.0/1 via 10.8.8.1`
`Sun May 14 16:19:49 2017 /sbin/ip route add 128.0.0.0/1 via 10.8.8.1`
`Sun May 14 16:19:49 2017 Initialization Sequence Completed`

Any help would be gladly appreciated.

**Comment by Zuescho** [comment]
i just tested something and i can reach any IP on the outside like 8.8.8.8 but none on my local range.

**Comment by haugene** [comment]
Hmm, that's weird. Just to make sure, what is the ip of the local computer you are trying from? And could you also try the proxy approach listed in the readme?

**Comment by Zuescho** [comment]
Okay so my ip is 192.168.178.20 (PC not running docker)
MY OMV machine is 192.168.178.61 (Running docker)

from both machines i can not reach the container via ping or the other way around.
did not yet try the proxy approach.

**Comment by haugene** [comment]
In that case, at least your LOCAL_NETWORK is wrong. Should be 192.168.178.0/24

**Comment by Zuescho** [comment]
Yeah i was toying around with that, sadly still can not get a ping to it.

**Comment by Zuescho** [comment]
```
Using OpenVPN provider: NORDVPN
Starting OpenVPN using config ca32.nordvpn.com.udp1194.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Sun May 14 17:32:03 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Sun May 14 17:32:03 2017 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Sun May 14 17:32:03 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun May 14 17:32:03 2017 Control Channel Authentication: tls-auth using INLINE static key file
Sun May 14 17:32:03 2017 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun May 14 17:32:03 2017 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun May 14 17:32:03 2017 Socket Buffers: R=[212992->131072] S=[212992->131072]
Sun May 14 17:32:03 2017 UDPv4 link local: [undef]
Sun May 14 17:32:03 2017 UDPv4 link remote: [AF_INET]184.75.214.83:1194
Sun May 14 17:32:03 2017 TLS: Initial packet from [AF_INET]184.75.214.83:1194, sid=90a95216 2b04ab2f
Sun May 14 17:32:03 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun May 14 17:32:03 2017 VERIFY OK: depth=1, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=ca32.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
Sun May 14 17:32:03 2017 Validating certificate key usage
Sun May 14 17:32:03 2017 ++ Certificate has key usage  00a0, expects 00a0
Sun May 14 17:32:03 2017 VERIFY KU OK
Sun May 14 17:32:03 2017 Validating certificate extended key usage
Sun May 14 17:32:03 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sun May 14 17:32:03 2017 VERIFY EKU OK
Sun May 14 17:32:03 2017 VERIFY OK: depth=0, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=ca32.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
Sun May 14 17:32:04 2017 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Sun May 14 17:32:04 2017 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun May 14 17:32:04 2017 Data Channel Decrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Sun May 14 17:32:04 2017 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun May 14 17:32:04 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-SHA, 2048 bit RSA
Sun May 14 17:32:04 2017 [ca32.nordvpn.com] Peer Connection Initiated with [AF_INET]184.75.214.83:1194
Sun May 14 17:32:06 2017 SENT CONTROL [ca32.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Sun May 14 17:32:08 2017 AUTH: Received control message: AUTH_FAILED
Sun May 14 17:32:08 2017 SIGTERM[soft,auth-failure] received, process exiting
Using OpenVPN provider: NORDVPN
Starting OpenVPN using config ca32.nordvpn.com.udp1194.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Sun May 14 17:32:09 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Sun May 14 17:32:09 2017 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Sun May 14 17:32:09 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun May 14 17:32:09 2017 Control Channel Authentication: tls-auth using INLINE static key file
Sun May 14 17:32:09 2017 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun May 14 17:32:09 2017 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun May 14 17:32:09 2017 Socket Buffers: R=[212992->131072] S=[212992->131072]
Sun May 14 17:32:09 2017 UDPv4 link local: [undef]
Sun May 14 17:32:09 2017 UDPv4 link remote: [AF_INET]184.75.214.83:1194
Sun May 14 17:32:09 2017 TLS: Initial packet from [AF_INET]184.75.214.83:1194, sid=987f52af 72757122
Sun May 14 17:32:09 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun May 14 17:32:09 2017 VERIFY OK: depth=1, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=ca32.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
Sun May 14 17:32:09 2017 Validating certificate key usage
Sun May 14 17:32:09 2017 ++ Certificate has key usage  00a0, expects 00a0
Sun May 14 17:32:09 2017 VERIFY KU OK
Sun May 14 17:32:09 2017 Validating certificate extended key usage
Sun May 14 17:32:09 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sun May 14 17:32:09 2017 VERIFY EKU OK
Sun May 14 17:32:09 2017 VERIFY OK: depth=0, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=ca32.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
Sun May 14 17:32:10 2017 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Sun May 14 17:32:10 2017 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun May 14 17:32:10 2017 Data Channel Decrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Sun May 14 17:32:10 2017 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun May 14 17:32:10 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-SHA, 2048 bit RSA
Sun May 14 17:32:10 2017 [ca32.nordvpn.com] Peer Connection Initiated with [AF_INET]184.75.214.83:1194
Sun May 14 17:32:13 2017 SENT CONTROL [ca32.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Sun May 14 17:32:13 2017 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,sndbuf 524288,rcvbuf 524288,dhcp-option DNS 78.46.223.24,dhcp-option DNS 162.242.211.137,route-gateway 10.8.8.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.8.120 255.255.255.0'
Sun May 14 17:32:13 2017 OPTIONS IMPORT: timers and/or timeouts modified
Sun May 14 17:32:13 2017 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Sun May 14 17:32:13 2017 Socket Buffers: R=[131072->425984] S=[131072->425984]
Sun May 14 17:32:13 2017 OPTIONS IMPORT: --ifconfig/up options modified
Sun May 14 17:32:13 2017 OPTIONS IMPORT: route options modified
Sun May 14 17:32:13 2017 OPTIONS IMPORT: route-related options modified
Sun May 14 17:32:13 2017 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sun May 14 17:32:13 2017 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
Sun May 14 17:32:13 2017 TUN/TAP device tun0 opened
Sun May 14 17:32:13 2017 TUN/TAP TX queue length set to 100
Sun May 14 17:32:13 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Sun May 14 17:32:13 2017 /sbin/ip link set dev tun0 up mtu 1500
Sun May 14 17:32:13 2017 /sbin/ip addr add dev tun0 10.8.8.120/24 broadcast 10.8.8.255
Sun May 14 17:32:13 2017 /etc/transmission/start.sh tun0 1500 1590 10.8.8.120 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.8.120
Generating transmission settings.json from env variables

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Sun May 14 17:32:13 2017 /sbin/ip route add 184.75.214.83/32 via 172.17.0.1
Sun May 14 17:32:13 2017 /sbin/ip route add 0.0.0.0/1 via 10.8.8.1
Sun May 14 17:32:13 2017 /sbin/ip route add 128.0.0.0/1 via 10.8.8.1
Sun May 14 17:32:13 2017 Initialization Sequence Completed
```

**Comment by Zuescho** [comment]
Okay, i did a reset on everything and now it seems i can get a ping through.

**Comment by Zuescho** [comment]
Okay, so I'm able to reach all my Pcs from within the docker but only via the ip any dns resolve fail. I can live with that, but i can not seem to get a ping inside the docker or better said i still can not reach the RPC URL

**Comment by Zuescho** [comment]
Okay more progress.
I can now ping the machine from the host.
and i can get from the machine to any other on my network.
Now the last problem i have is that i need to connect a machine that is not the host to the transmission RPC.

**Comment by Zuescho** [comment]
Okay, got it to work. I now have connection to the client. had to change from bridge to host mode.

**Comment by haugene** [comment]
Good that you got it working, but be aware that by changing from bridge to host mode you're not setting up VPN isolated for the transmission container. By setting host mode the container will use the network stack on your host and all traffic from that host will then be tunneled.

**Comment by Zuescho** [comment]
Oh yeah, just tested it you are right... well this sucks. Seems like i have to test around a bit more then.

**Comment by Zuescho** [comment]
```
"Ports": {
                "9091/tcp": null,
                "9094/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "9094"
                    }
                ]
            },

Haha i think i did it. just checked seems to work fine. i can now reach both transmissions on the host and both have diffrent IP addresses (1 with VPN ) (1 without).
Thank you so much, for saving me trouble. I hope i did not open some other problem now but i think it works now.
1000 Thanks for the great work, i really need to learn more about this docker and container thing.
```

**Comment by haugene** [comment]
Sweet :) You're welcome, and yeah... Containers are awesome! Don't understand where port 9094 comes from in your setup, but I guess you changed your rpc address after posting your config stuff.

**Comment by Zuescho** [comment]
Yeah i change the RPC port to 9094 because the other transmission client is listening on 9091.
