### ISSUE TITLE
Private Internet Access - New Port Forwarding Script?

### ISSUE THREAD

**Issue by coolspot18** [haugene/docker-transmission-openvpn#250]
It seems that PIA port forward isn't working for me anymore - even with the latest image where I believe has the new 2017 port forwarding script implemented?

In my Docker logs, I am seeing the following:

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Mon May 15 01:28:33 2017 Initialization Sequence Completed
curl encountered an error looking up new port: 56

Could not find new port from PIA

Any other logs I can use to help debug the issue?

Thanks.

**Comment by coolspot18** [comment]
Update - I switched PIA servers and port forwarding is working again.

Maybe a PIA issue.

**Comment by haugene** [comment]
Hmm. Good it's working again. I've seen some issues with the script when restarting the container multiple times. I got an error saying something like "port forwarding is not available in this region or one already exists for this connection". Don't remember if it was with the same error code, but could be related. 

For now, let's assume it's a pia thing. And raise a new issue if you have reason to believe it's not :)

**Comment by coolspot18** [comment]
Also thanks for maintaining this container - it's an excellent tool!

**Comment by haugene** [comment]
Thanks :)
