### ISSUE TITLE
Problem establishing firewall

### ISSUE THREAD

**Issue by Integer93** [haugene/docker-transmission-openvpn#2504]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

```
Runtime:
runc


Environment:

ENABLE_UFW=true
OPENVPN_CONFIG=poland
OPENVPN_PASSWORD=XXX
OPENVPN_PROVIDER=PIA
OPENVPN_USERNAME=XXX
TRANSMISSION_DOWNLOAD_DIR=/downloaded
WEBPROXY_PORT=8118
```

### Current Behavior

The firewall rules do not get applied. The startup failes.

I have tried many settings and older images (before #2456) but couldnt enable the firewall. The issue is only related to the firewall rules. With `ENABLE_UFW=false`, i can start the container.

### Expected Behavior

Being able to use the firewall.

### How have you tried to solve the problem?

Tried Builds:
- master
- dev
- latest

Tried ENVs:
- UFW_DISABLE_IPTABLES_REJECT
- CREATE_TUN_DEVICE
- DROP_DEFAULT_ROUTE

There dosent seem to be a env/config that fixes my issue. I must admit that i dont quite understand what the problem is in the first place.

### Log output

`master` (4.3.2) tag output:
```
ERROR: problem running ufw-init
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
```

`dev` tag output:
```
enabling firewall
ERROR: problem running ufw-init
iptables-restore v1.8.7 (legacy): Couldn't load match `limit':No such file or directory

Error occurred at line: 63
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
iptables-restore v1.8.7 (legacy): Couldn't load match `limit':No such file or directory

Error occurred at line: 8
Try `iptables-restore -h' or 'iptables-restore --help' for more information.

Problem running '/etc/ufw/before.rules'
```

`latest` tag:
```
enabling firewall
ERROR: problem running ufw-init
iptables-restore v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
iptables-restore v1.8.7 (nf_tables): Couldn't load match `conntrack':No such file or directory
Error occurred at line: 2
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
iptables-restore v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
iptables-restore v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
iptables-restore v1.8.7 (nf_tables): Couldn't load match `conntrack':No such file or directory
Error occurred at line: 25
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
iptables-restore v1.8.7 (nf_tables): unknown option "--dport"
Error occurred at line: 19
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
iptables-restore v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
iptables-restore v1.8.7 (nf_tables): Couldn't load match `limit':No such file or directory
Error occurred at line: 8
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
iptables-restore v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
iptables-restore v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument


Problem running '/etc/ufw/before.rules'
Problem running '/etc/ufw/after.rules'
Problem running '/etc/ufw/user.rules'
```

### HW/SW Environment

```markdown
- OS: QTS 5.0.1 (QNAP Container Station)
- HW: QNAP NAS /w Intel Celeron J3455
- Runtime: runc
- Container RAM: 1024 MB
```

**Comment by jester-xbmc** [comment]
Same issue on synology, https://github.com/haugene/docker-transmission-openvpn/pull/2456 fixes it

for others, you can pull dev instead of latest, UFW_DISABLE_IPTABLES_REJECT=true still needed, be aware of config changes needed ( ie is manually set TRANSMISSION_HOME is not set to the default /config/transmission-home)

**Comment by kedryte** [comment]
> Same issue on synology, #2456 fixes it
> 
> for others, you can pull dev instead of latest, UFW_DISABLE_IPTABLES_REJECT=true still needed, be aware of config changes needed ( ie is manually set TRANSMISSION_HOME is not set to the default /config/transmission-home)

Hi @jester-xbmc, I was wondering what you meant by the configuration changes needed for TRANSMISSION_HOME, because I'm trying to follow your advice about the dev branch, but right now even on dev with Synology DSM 7.1.1 I get the following error when trying to use UFW and the container exits:

```
Disable and blank firewall
Firewall stopped and disabled on system startup
enabling firewall
ERROR: Could not load logging rules
```

This is my minimal example config that produces this error on Synology:

```
docker run -d \
	--cap-add=NET_ADMIN \
	-e OPENVPN_PROVIDER=PIA \
	-e OPENVPN_CONFIG=france \
	-e OPENVPN_USERNAME=xxx \
	-e OPENVPN_PASSWORD=xxx \
	-e ENABLE_UFW=true \
	-e UFW_DISABLE_IPTABLES_REJECT=true \
	--name transmission-test \
	haugene/transmission-openvpn:dev
```

However as a comparison the following without UFW enabled works and authenticates with the VPN provider:

```
docker run -d \
	--cap-add=NET_ADMIN \
	-e OPENVPN_PROVIDER=PIA \
	-e OPENVPN_CONFIG=france \
	-e OPENVPN_USERNAME=xxx \
	-e OPENVPN_PASSWORD=xxx \
	-e ENABLE_UFW=false \
	--name transmission-test \
	haugene/transmission-openvpn:dev
```

**Comment by jester-xbmc** [comment]
HI @kedryte you can ignore that, it was just me dealing with an older config where I didnt yet map /config and point TRANSMISSION_HOME to that folder.

what concerns your error, i'm not sure, try with --privileged

**Comment by kedryte** [comment]
Unfortunately that still doesn't work, but thank you for the advice. I will open a separate issue to track this.
