### ISSUE TITLE
Inactivity timeout

### ISSUE THREAD

**Issue by sgtsquiggs** [haugene/docker-transmission-openvpn#251]
I'm assuming this is a PIA issue, but just in case...

```
transmission_1      | Using OpenVPN provider: PIA
transmission_1      | Starting OpenVPN using config CA Toronto.ovpn
transmission_1      | Setting OPENVPN credentials...
transmission_1      | Wed May 17 19:19:48 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
transmission_1      | Wed May 17 19:19:48 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission_1      | Wed May 17 19:19:48 2017 UDPv4 link local: [undef]
transmission_1      | Wed May 17 19:19:48 2017 UDPv4 link remote: [AF_INET]10.0.0.1:1198
transmission_1      | Wed May 17 19:20:48 2017 [UNDEF] Inactivity timeout (--ping-exit), exiting
transmission_1      | Wed May 17 19:20:48 2017 SIGTERM[soft,ping-exit] received, process exiting
transmission_1      | Using OpenVPN provider: PIA
transmission_1      | Starting OpenVPN using config CA Toronto.ovpn
transmission_1      | Setting OPENVPN credentials...
transmission_1      | Wed May 17 19:20:49 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
transmission_1      | Wed May 17 19:20:49 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission_1      | Wed May 17 19:20:49 2017 UDPv4 link local: [undef]
transmission_1      | Wed May 17 19:20:49 2017 UDPv4 link remote: [AF_INET]10.0.0.1:1198
transmission_1      | Wed May 17 19:21:49 2017 [UNDEF] Inactivity timeout (--ping-exit), exiting
transmission_1      | Wed May 17 19:21:49 2017 SIGTERM[soft,ping-exit] received, process exiting
transmission_1      | Using OpenVPN provider: PIA
transmission_1      | Starting OpenVPN using config CA Toronto.ovpn
transmission_1      | Setting OPENVPN credentials...
transmission_1      | Wed May 17 19:21:50 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
transmission_1      | Wed May 17 19:21:50 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission_1      | Wed May 17 19:21:50 2017 UDPv4 link local: [undef]
transmission_1      | Wed May 17 19:21:50 2017 UDPv4 link remote: [AF_INET]10.0.0.1:1198
transmission_1      | Wed May 17 19:22:50 2017 [UNDEF] Inactivity timeout (--ping-exit), exiting
transmission_1      | Wed May 17 19:22:50 2017 SIGTERM[soft,ping-exit] received, process exiting
transmission_1      | Using OpenVPN provider: PIA
transmission_1      | Starting OpenVPN using config CA Toronto.ovpn
transmission_1      | Setting OPENVPN credentials...
transmission_1      | Wed May 17 19:22:51 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
transmission_1      | Wed May 17 19:22:51 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission_1      | Wed May 17 19:22:51 2017 UDPv4 link local: [undef]
transmission_1      | Wed May 17 19:22:51 2017 UDPv4 link remote: [AF_INET]10.0.0.1:1198
transmission_1      | Wed May 17 19:23:51 2017 [UNDEF] Inactivity timeout (--ping-exit), exiting
transmission_1      | Wed May 17 19:23:51 2017 SIGTERM[soft,ping-exit] received, process exiting
```

on and on and on... This was working earlier today!

**Comment by rwaesely** [comment]
same here !

**Comment by sgtsquiggs** [comment]
Eventually went away for me, but was in this state for a few hours.

**Comment by rwaesely** [comment]
I have this for several days. I noticed it this week end.
```
2017-05-22 20:36:32	stdout	Mon May 22 20:36:32 2017 SIGTERM[soft,ping-exit] received, process exiting
2017-05-22 20:36:32	stdout	Mon May 22 20:36:32 2017 [UNDEF] Inactivity timeout (--ping-exit), exiting
2017-05-22 20:36:02	stdout	Mon May 22 20:36:02 2017 UDPv4 link remote: [AF_INET]5.56.16.2:553
2017-05-22 20:36:02	stdout	Mon May 22 20:36:02 2017 UDPv4 link local: [undef]
2017-05-22 20:36:02	stdout	Mon May 22 20:36:02 2017 Socket Buffers: R=[212992->131072] S=[212992->131072]
2017-05-22 20:36:02	stdout	Mon May 22 20:36:02 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2017-05-22 20:36:02	stdout	Mon May 22 20:36:02 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
2017-05-22 20:36:02	stdout	adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
2017-05-22 20:36:02	stdout	Setting OPENVPN credentials...
2017-05-22 20:36:02	stdout	No VPN configuration provided. Using default.
2017-05-22 20:36:02	stdout	Using OpenVPN provider: HIDEMYASS
2017-05-22 20:34:53	stdout	Mon May 22 20:34:53 2017 SIGTERM[soft,ping-exit] received, process exiting
2017-05-22 20:34:53	stdout	Mon May 22 20:34:53 2017 [UNDEF] Inactivity timeout (--ping-exit), exiting
2017-05-22 20:34:23	stdout	Mon May 22 20:34:23 2017 UDPv4 link remote: [AF_INET]5.56.16.2:553
2017-05-22 20:34:23	stdout	Mon May 22 20:34:23 2017 UDPv4 link local: [undef]
2017-05-22 20:34:23	stdout	Mon May 22 20:34:23 2017 Socket Buffers: R=[212992->131072] S=[212992->131072]
2017-05-22 20:34:23	stdout	Mon May 22 20:34:23 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2017-05-22 20:34:23	stdout	Mon May 22 20:34:23 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
2017-05-22 20:34:23	stdout	adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
2017-05-22 20:34:23	stdout	Setting OPENVPN credentials...
2017-05-22 20:34:23	stdout	No VPN configuration provided. Using default.
2017-05-22 20:34:23	stdout	Using OpenVPN provider: HIDEMYASS
```

**Comment by rwaesely** [comment]
Hi guys,

I really need help. I tried to open everything on my routeur, disabled the firewall on my synology... still no luck with this issue. Any clue about this ? It was working fine last week :(

**Comment by rwaesely** [comment]
nobody can help me ? crap ^^
I'm stuck, no way I can use transmission without the vpn

**Comment by rwaesely** [comment]
I made it work by running again the container as root, which is not what I want. I used to run the container with PUID and PGID variables to match my synology user. Indeed, as soon as the download is complete, another container running filebot sort and rename the files... which does not work if they are owned by root. And security considerations make me think that giving 777 permissions is a bad thing.

**Comment by haugene** [comment]
Hmm. Just saw this error as well while merging #246 to update the HMA server list. Changed the default config symlink and it seemed to work fine then. Might be that some of the locations in the server list is not responding? Anyone having this problem should try a different config location using the `OPENVPN_CONFIG` variable.

@rwaesely: Try pulling the image again with the `dev` tag, does it work better now?

**Comment by rwaesely** [comment]
Well, I have a flag on this thread, in case my config breaks again. Though, I tried with a different location with OPENVPN_CONFIG and it didn't change anything. It started to run when I removed PUID and PGID variables from the docker run command. I'll give a try next time I meet this issue and will give a report. Thanks haugene anyway for your work; your dockerfile brings more happiness than pain ;-)

**Comment by axerontios** [comment]
same error here :( 

Mon May 17 16:18:52 2021 WARNING: file '/config/openvpn-credentials.txt' is group or others accessible
Mon May 17 16:18:52 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Mon May 17 16:18:52 2021 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon May 17 16:18:52 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon May 17 16:18:52 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]104.78.191.246:1198
Mon May 17 16:18:52 2021 UDP link local: (not bound)
Mon May 17 16:18:52 2021 UDP link remote: [AF_INET]104.78.191.246:1198
Mon May 17 16:19:52 2021 [UNDEF] Inactivity timeout (--ping-exit), exiting
Mon May 17 16:19:52 2021 SIGTERM[soft,ping-exit] received, process exiting

in a loop, the container keeps restarting 

docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \
>             --name="MD--TransN" \
>             -h Container_TransmissioN \
>             --network MacVlaN \
>             --ip=192.168.2.70 \
>             --restart=always \
>             --label=Media \
>             -m 1536M \
>             --cpus=0.5 \
>             -v /xx/:/config \
>             -v /xx:/watch \
>             -v /xx/data/completed \
>             -v /xx:/data/incomplete \
>             -v /xx:/shared \
>             -v /etc/localtime:/etc/localtime:ro \
>             -e OPENVPN_PROVIDER=PIA \
>             -e OPENVPN_CONFIG=CA\ Toronto \
>             -e "OPENVPN_USERNAME=xxxxx" \
>             -e "OPENVPN_PASSWORD=xxxxx" \
>             -e WEBPROXY_ENABLED=false \
>             -e LOCAL_NETWORK=192.168.0.0/16 \
>             -e TRANSMISSION_RATIO_LIMIT=0 \
>             -e TRANSMISSION_RATIO_LIMIT_ENABLED=true \
>             -e TRANSMISSION_SPEED_LIMIT_UP=250 \
>             -e TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true \
>             -e TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true \
>             -e TRANSMISSION_DOWNLOAD_QUEUE_SIZE=25 \
>             -e TRANSMISSION_IDLE_SEEDING_LIMIT=3 \
>             -e TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true \
>             -e TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true \
>             -e TRANSMISSION_RPC_USERNAME=xxxxx\
>             -e TRANSMISSION_RPC_PASSWORD=xxxx\
>             -e TRANSMISSION_ENCRYPTION=1 \
>             -e TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*" \
>             -e OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60" \
>             -e TRANSMISSION_WEB_UI=transmission-web-control \
>             --log-driver json-file \
>             --log-opt max-size=10m \
>             --dns 209.222.18.222 --dns 209.222.18.218 \
>             --sysctl net.ipv6.conf.all.disable_ipv6=0 \

latest version / haugene/transmission-openvpn:latest

**Comment by emphaticsunshine** [comment]
Did this get resolved?

**Comment by throny** [comment]
> Did this get resolved?

This is mentioned in the official docs:
https://haugene.github.io/docker-transmission-openvpn/faq/#set_the_ping-exit_option_for_openvpn_and_restart-flag_in_docker

However, this didn't solve it for me. I tried adding the pull-filter, as this gets set by the OpenVPN server (not your client) but even then, it still occurs. Strange, would love to get this stable.

**Comment by renhardy** [comment]
Starting having this issue about one month ago. 
I did try to add the pull-filter as well, but the container keeps restarting.
Any help would be appreciated.
