### ISSUE TITLE
PIA Port Issue

### ISSUE THREAD

**Issue by Fma965** [haugene/docker-transmission-openvpn#254]
Generating new client id for PIA
curl encountered an error looking up new port: 56
Could not find new port from PIA

Any ideas why? Thanks.

**Comment by haugene** [comment]
DNS? Or you might be using a location that does not support port forwarding?
Please supply your config options and logs if setting the dns options (ref readme) or changing locations does not work.

**Comment by Fma965** [comment]
`Thu Jun  8 20:13:50 2017 RESOLVE: Cannot resolve host address: nl.privateinternetaccess.com: Temporary failure in name resolution
Thu Jun  8 20:14:35 2017 RESOLVE: Cannot resolve host address: nl.privateinternetaccess.com: Temporary failure in name resolution
Thu Jun  8 20:15:20 2017 RESOLVE: Cannot resolve host address: nl.privateinternetaccess.com: Temporary failure in name resolution
Thu Jun  8 20:16:05 2017 RESOLVE: Cannot resolve host address: nl.privateinternetaccess.com: Temporary failure in name resolution
Thu Jun  8 20:16:50 2017 RESOLVE: Cannot resolve host address: nl.privateinternetaccess.com: Temporary failure in name resolution
Thu Jun  8 20:17:35 2017 RESOLVE: Cannot resolve host address: nl.privateinternetaccess.com: Temporary failure in name resolution
Thu Jun  8 20:18:20 2017 RESOLVE: signal received during DNS resolution attempt
Thu Jun  8 20:18:20 2017 /sbin/ip addr del dev tun0 local 10.44.10.6 peer 10.44.10.5
Thu Jun  8 20:18:20 2017 /etc/transmission/stop.sh tun0 1500 1558 10.44.10.6 10.44.10.5 init
Thu Jun  8 20:18:20 2017 SIGTERM[hard,init_instance] received, process exiting
Using OpenVPN provider: PIA
Starting OpenVPN using config Netherlands.ovpn
Setting OPENVPN credentials...
Thu Jun  8 20:18:21 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Thu Jun  8 20:18:21 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Jun  8 20:18:21 2017 UDPv4 link local: [undef]
Thu Jun  8 20:18:21 2017 UDPv4 link remote: [AF_INET]46.166.138.163:1198
Thu Jun  8 20:18:21 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Jun  8 20:18:21 2017 [5d9250ee5e356c71b846d7648cb82217] Peer Connection Initiated with [AF_INET]46.166.138.163:1198
Thu Jun  8 20:18:23 2017 TUN/TAP device tun0 opened
Thu Jun  8 20:18:23 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Thu Jun  8 20:18:23 2017 /sbin/ip link set dev tun0 up mtu 1500
Thu Jun  8 20:18:23 2017 /sbin/ip addr add dev tun0 local 10.36.10.6 peer 10.36.10.5
Thu Jun  8 20:18:23 2017 /etc/transmission/start.sh tun0 1500 1558 10.36.10.6 10.36.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.36.10.6
Generating transmission settings.json from env variables
Setting owner for transmission paths to 911:911
chown: cannot access '/data/watch': No such file or directory

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    911
User gid:    911
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Thu Jun  8 20:18:23 2017 Initialization Sequence Completed
curl encountered an error looking up new port: 56
Could not find new port from PIA`

**Comment by Fma965** [comment]
i've tried it with --dns 8.8.8.8 as suggested on the readme but still nothing

but actually trying it with --dns=8.8.8.8 as per the official docker documentation has worked.

**Comment by haugene** [comment]
Ok, so the API must have changed

**Comment by nicbou** [comment]
I'm still getting this exact issue as of October 20 2017. Did I miss something? The ticket was closed without any explanation or resolution.

**Comment by Fma965** [comment]
you need to add --dns=8.8.8.8 to the docker command line, i dont use torrents or this docker anymore as now use usenet so can't help further.

**Comment by nicbou** [comment]
I did. I managed to fix it by disconnecting my other laptop from a separate VPN service, oddly enough.
