### ISSUE TITLE
TRANSMISSION_WEB_HOME environmental variable

### ISSUE THREAD

**Issue by MWDelaney** [haugene/docker-transmission-openvpn#255]
Hi,
I'm probably doing this wrong, but I've tried passing TRANSMISSION_WEB_HOME to docker as an environmental variable and it doesn't seem to affect Transmission inside the container.

The environmental variable is definitely set (I set it to `/data/transmission-home/web`), and I tried putting [the latest release](https://github.com/Secretmapper/combustion/archive/release.zip) of [Combustion](https://github.com/Secretmapper/combustion) there, restarted the container (with the environmental variable set), but the web UI didn't change.

Is this variable simply not supported? Or am I doing something embarrassingly wrong?

Thanks!

**Comment by haugene** [comment]
Had a look at the template file we're generating the [settings file](https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/settings.tmpl) from. Seems web home is not one of them. 

Guessing that this setting came after the template was made. Need to update the template based on the settings.json for the current version of transmission.

**Comment by RagingRandy** [comment]
Any luck on this? I would like to use combustion as well.

**Comment by haugene** [comment]
Haven't had the time yet. But vacation starts today. Let's hope for a rainy day where I can fix this. Also want to upgrade openvpn and base image. Thanks for your patience.

**Comment by haugene** [comment]
I think I got it now. Try again using the dev tag?

**Comment by MWDelaney** [comment]
This worked. Sorry for the delay. Thank you!

**Comment by ylor** [comment]
Can this be rolled into master? Thanks!

**Comment by haugene** [comment]
Merged :)

**Comment by lazeekat** [comment]
Would you set a default value of **/usr/share/transmission/web** for the TRANSMISSION_WEB_HOME env var? That's the default docker install path. Thank you!
