### ISSUE TITLE
Inactivity timeout loop

### ISSUE THREAD

**Issue by Navino16** [haugene/docker-transmission-openvpn#2551]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

<details>
<summary>Docker compose</summary>

transmission:
    image: haugene/transmission-openvpn:dev
    container_name: transmission
    devices:
      - /dev/net/tun
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=my_username
      - OPENVPN_PASSWORD=my_password
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=172.20.0.0/16
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_WEB_UI=transmission-web-control
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false
      - TRANSMISSION_RATIO_LIMIT=10
      - TRANSMISSION_RATIO_LIMIT_ENABLED=false
      - TRANSMISSION_UPLOAD_LIMIT_ENABLED=false
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=50
      - TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=100
      - TRANSMISSION_QUEUE_STALLED_ENABLED=false
      - TZ=Europe/Paris
    volumes:
      - ../data/transmission/data:/data
      - ../data/transmission/config:/config
      - /home/serverdatsite/Downloads/Torrents/completed:/data/completed
      - /home/serverdatsite/Downloads/Torrents/incomplete:/data/incomplete
      - ./config/transmission/openvpn:/etc/openvpn/custom
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - NET_ADMIN
    networks:
      - my_network
    restart: unless-stopped

</details>

### Current Behavior

I'm using PROTON VPN as VPN provider and after 3 minutes VPN container crash with an "Inactivity timeout" error.

I also noticed this 2 errors on logs :
2023-03-09 11:41:51 sitnl_send: rtnl: generic error (-101): Network is unreachable
2023-03-09 11:41:51 ERROR: Linux route add command failed

### Expected Behavior

Stay connected or switch to another server

### How have you tried to solve the problem?

1) Tried both master and dev tag (was on latest)
2) Using VPN file from protonVPN (country and server) from 2 different country
3) Using VPN file from vpn-configs-contrib from 2 different country

### Log output
<details>
<summary>Log from dev container</summary>

transmission  | Starting container with revision: 1c6397e565921139f661be4597576e423fb7543e
transmission  | TRANSMISSION_HOME is currently set to: /config/transmission-home
transmission  | Creating TUN device /dev/net/tun
transmission  | Using OpenVPN provider: CUSTOM
transmission  | Modifying /etc/openvpn/custom/default.ovpn for best behaviour in this container
transmission  | Modification: Point auth-user-pass option to the username/password file
transmission  | Modification: Change ca certificate path
transmission  | Modification: Change ping options
transmission  | Modification: Update/set resolv-retry to 15 seconds
transmission  | Modification: Change tls-crypt keyfile path
transmission  | Modification: Set output verbosity to 3
transmission  | Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
transmission  | Modification: Updating status for config failure detection
transmission  | Setting OpenVPN credentials...
transmission  | adding route to local network 172.20.0.0/16 via 172.20.0.1 dev eth0
transmission  | 2023-03-09 11:41:50 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
transmission  | 2023-03-09 11:41:50 OpenVPN 2.5.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 14 2022
transmission  | 2023-03-09 11:41:50 library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
transmission  | 2023-03-09 11:41:50 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission  | 2023-03-09 11:41:50 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
transmission  | 2023-03-09 11:41:50 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
transmission  | 2023-03-09 11:41:50 TCP/UDP: Preserving recently used remote address: [AF_INET]138.199.6.177:80
transmission  | 2023-03-09 11:41:50 Socket Buffers: R=[212992->212992] S=[212992->212992]
transmission  | 2023-03-09 11:41:50 UDP link local: (not bound)
transmission  | 2023-03-09 11:41:50 UDP link remote: [AF_INET]138.199.6.177:80
transmission  | 2023-03-09 11:41:50 TLS: Initial packet from [AF_INET]138.199.6.177:80, sid=1b3fcc67 ef8f36e6
transmission  | 2023-03-09 11:41:50 VERIFY OK: depth=2, C=CH, O=ProtonVPN AG, CN=ProtonVPN Root CA
transmission  | 2023-03-09 11:41:50 VERIFY OK: depth=1, C=CH, O=ProtonVPN AG, CN=ProtonVPN Intermediate CA 1
transmission  | 2023-03-09 11:41:50 VERIFY KU OK
transmission  | 2023-03-09 11:41:50 Validating certificate extended key usage
transmission  | 2023-03-09 11:41:50 ++ Certificate has EKU (str) TLS Web Client Authentication, expects TLS Web Server Authentication
transmission  | 2023-03-09 11:41:50 ++ Certificate has EKU (oid) 1.3.6.1.5.5.7.3.2, expects TLS Web Server Authentication
transmission  | 2023-03-09 11:41:50 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
transmission  | 2023-03-09 11:41:50 VERIFY EKU OK
transmission  | 2023-03-09 11:41:50 VERIFY OK: depth=0, CN=node-ch-10.protonvpn.net
transmission  | 2023-03-09 11:41:50 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1633', remote='link-mtu 1634'
transmission  | 2023-03-09 11:41:50 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
transmission  | 2023-03-09 11:41:50 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 4096 bit RSA, signature: RSA-SHA256
transmission  | 2023-03-09 11:41:50 [node-ch-10.protonvpn.net] Peer Connection Initiated with [AF_INET]138.199.6.177:80
transmission  | 2023-03-09 11:41:51 SENT CONTROL [node-ch-10.protonvpn.net]: 'PUSH_REQUEST' (status=1)
transmission  | 2023-03-09 11:41:51 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.23.0.1,sndbuf 524288,rcvbuf 524288,redirect-gateway def1,explicit-exit-notify,comp-lzo no,route-gateway 10.23.0.1,topology subnet,ping 10,ping-restart 60,socket-flags TCP_NODELAY,ifconfig 10.23.0.7 255.255.0.0,peer-id 458757,cipher AES-256-GCM'
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: timers and/or timeouts modified
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: explicit notify parm(s) modified
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: compression parms modified
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
transmission  | 2023-03-09 11:41:51 Socket Buffers: R=[212992->425984] S=[212992->425984]
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: --socket-flags option modified
transmission  | 2023-03-09 11:41:51 NOTE: setsockopt TCP_NODELAY=1 failed
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: --ifconfig/up options modified
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: route options modified
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: route-related options modified
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: peer-id set
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: adjusting link_mtu to 1656
transmission  | 2023-03-09 11:41:51 OPTIONS IMPORT: data channel crypto options modified
transmission  | 2023-03-09 11:41:51 Data Channel: using negotiated cipher 'AES-256-GCM'
transmission  | 2023-03-09 11:41:51 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
transmission  | 2023-03-09 11:41:51 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
transmission  | 2023-03-09 11:41:51 net_route_v4_best_gw query: dst 0.0.0.0
transmission  | 2023-03-09 11:41:51 net_route_v4_best_gw result: via 172.20.0.1 dev eth0
transmission  | 2023-03-09 11:41:51 ROUTE_GATEWAY 172.20.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:14:00:02
transmission  | 2023-03-09 11:41:51 TUN/TAP device tun0 opened
transmission  | 2023-03-09 11:41:51 net_iface_mtu_set: mtu 1500 for tun0
transmission  | 2023-03-09 11:41:51 net_iface_up: set tun0 up
transmission  | 2023-03-09 11:41:51 net_addr_v4_add: 10.23.0.7/16 dev tun0
transmission  | 2023-03-09 11:41:51 net_route_v4_add: 138.199.6.177/32 via 172.20.0.1 dev [NULL] table 0 metric -1
transmission  | 2023-03-09 11:41:51 sitnl_send: rtnl: generic error (-101): Network is unreachable
transmission  | 2023-03-09 11:41:51 ERROR: Linux route add command failed
transmission  | 2023-03-09 11:41:51 net_route_v4_add: 0.0.0.0/1 via 10.23.0.1 dev [NULL] table 0 metric -1
transmission  | 2023-03-09 11:41:51 net_route_v4_add: 128.0.0.0/1 via 10.23.0.1 dev [NULL] table 0 metric -1
transmission  | Up script executed with device=tun0 ifconfig_local=10.23.0.7
transmission  | Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.23.0.7
transmission  | Using Transmission Web Control UI, overriding TRANSMISSION_WEB_HOME
transmission  | Enforcing ownership on transmission directories
transmission  | Applying permissions to transmission directories
transmission  | Setting owner for transmission paths to 1000:1000
transmission  | Setting permissions for download and incomplete directories
transmission  | umask: 2
transmission  | Directories: 775
transmission  | Files: 664
transmission  | Setting permission for watch directory (775) and its files (664)
transmission  |
transmission  | -------------------------------------
transmission  | Transmission will run as
transmission  | -------------------------------------
transmission  | User name:   abc
transmission  | User uid:    1000
transmission  | User gid:    1000
transmission  | -------------------------------------
transmission  |
transmission  | Updating Transmission settings.json with values from env variables
transmission  | Attempting to use existing settings.json for Transmission
transmission  | Successfully used existing settings.json /config/transmission-home/settings.json
transmission  | Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.23.0.7
transmission  | Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
transmission  | Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
transmission  | Overriding peer-limit-per-torrent because TRANSMISSION_PEER_LIMIT_PER_TORRENT is set to 50
transmission  | Overriding queue-stalled-enabled because TRANSMISSION_QUEUE_STALLED_ENABLED is set to false
transmission  | Overriding ratio-limit because TRANSMISSION_RATIO_LIMIT is set to 10
transmission  | Overriding ratio-limit-enabled because TRANSMISSION_RATIO_LIMIT_ENABLED is set to false
transmission  | Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
transmission  | Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
transmission  | Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to
transmission  | Overriding speed-limit-down-enabled because TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED is set to false
transmission  | Overriding speed-limit-up-enabled because TRANSMISSION_SPEED_LIMIT_UP_ENABLED is set to false
transmission  | Overriding upload-slots-per-torrent because TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT is set to 100
transmission  | Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
transmission  | sed'ing True to true
transmission  | STARTING TRANSMISSION
transmission  | Transmission startup script complete.
transmission  | 2023-03-09 11:41:51 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
transmission  | 2023-03-09 11:41:51 Initialization Sequence Completed
transmission  | 2023-03-09 11:44:43 [node-ch-10.protonvpn.net] Inactivity timeout (--ping-restart), restarting
transmission  | 2023-03-09 11:44:43 SIGTERM received, sending exit notification to peer
transmission  | 2023-03-09 11:44:44 /etc/openvpn/tunnelDown.sh tun0 1500 1584 10.23.0.7 255.255.0.0 init
transmission  | resolv.conf was restored
transmission  | Sending kill signal to transmission-daemon
transmission  | Waiting 5s for transmission-daemon to die
transmission  | Sending kill signal (SIGKILL) to transmission-daemon
transmission  | 2023-03-09 11:44:49 net_route_v4_del: 138.199.6.177/32 via 172.20.0.1 dev [NULL] table 0 metric -1
transmission  | 2023-03-09 11:44:49 sitnl_send: rtnl: generic error (-3): No such process
transmission  | 2023-03-09 11:44:49 ERROR: Linux route delete command failed
transmission  | 2023-03-09 11:44:49 net_route_v4_del: 0.0.0.0/1 via 10.23.0.1 dev [NULL] table 0 metric -1
transmission  | 2023-03-09 11:44:49 net_route_v4_del: 128.0.0.0/1 via 10.23.0.1 dev [NULL] table 0 metric -1
transmission  | 2023-03-09 11:44:49 Closing TUN/TAP interface
transmission  | 2023-03-09 11:44:49 net_addr_v4_del: 10.23.0.7 dev tun0
transmission  | 2023-03-09 11:44:49 SIGTERM[soft,exit-with-notification] received, process exiting

</details>

### HW/SW Environment

```markdown
- OS: Ubuntu 22-04
- Docker: version 23.0.1, build a5ee5b1
```

**Comment by doenietzomoeilijk** [comment]
I seem to have the same issue, different OS and docker versions, but the same inactivity loop.

**Comment by Downy** [comment]
Yup, same issue but with Mullvad. Started out of the blue the other day without me changing anything

**Comment by rhyst** [comment]
Also same with Mullvad. I switched from the `nl_all` config to `se_all` and that fixed it for me.

**Comment by LKay42** [comment]
I've just experienced it today with Mullvad and I'm using `se_got`, which is my default with an open port. I'm on Ubuntu 22.04 and latest stable Docker. This is a fresh setup from less than a day ago.

**Comment by jjgroenendijk** [comment]
> Also same with Mullvad. I switched from the `nl_all` config to `se_all` and that fixed it for me.
I had the same issue, and this fixed it for me!

**Comment by doenietzomoeilijk** [comment]
That seems to make it a VPN broker issue, not an issue with the container. As for [my case](#issuecomment-1465221243), I've done some further digging, and it turns out the password that my VPN provider used for the private key is simply wrong; I can't "open" the key from the commandline, let alone build a working VPN connection with it. So my case is most likely not an issue with this image.

**Comment by danielbiagi** [comment]
Sorry, I'm having sort of a inactivity disconnect also but have no clue where this nl_all and se_all configs are located, can someone help me?

**Comment by iparr** [comment]
I'll try @danielbiagi :
These configs refer to this repo: https://github.com/haugene/vpn-configs-contrib

Upon starting, docker-transmission-openvpn will look at that repo for the appropriate configs. So if you have `OPENVPN_PROVIDER` set to `MULLVAD` you can then set `OPENVPN_CONFIG` to `se_all`, et al.

**Comment by jjgroenendijk** [comment]
@danielbiagi, you can find more information here:
[https://haugene.github.io/docker-transmission-openvpn/config-options/#network_configuration_options](https://haugene.github.io/docker-transmission-openvpn/config-options/#network_configuration_options)

and:
[https://haugene.github.io/docker-transmission-openvpn/run-container/#2_it_is_not_mandatory_but_setting_openvpn_config_is_good](https://haugene.github.io/docker-transmission-openvpn/run-container/#2_it_is_not_mandatory_but_setting_openvpn_config_is_good)

**Comment by ocangelo** [comment]
having the same issue with pia running on a synology nas docker, every 3 minutes it disconnects.

during those 3 minutes i can bring up the transmission webui and i did a test with an online torrent tracker and the vpn seems to be working ok, i am not sure why it's restarting every 3 min

running with 
OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping-restart
DISABLE_PORT_UPDATER=true
OPENVPN_CONFIG=us_california

i did notice these in the logs:

14:11:37 net_addr_v4_add: 10.17.112.159/24 dev tun0
14:11:37 net_route_v4_add: 212.102.39.82/32 via 172.18.0.1 dev [NULL] table 0 metric -1
14:11:37 sitnl_send: rtnl: generic error (-101): Network is unreachable
14:11:37 ERROR: Linux route add command failed
14:11:37 net_route_v4_add: 0.0.0.0/1 via 10.17.112.1 dev [NULL] table 0 metric -1
14:11:37 net_route_v4_add: 128.0.0.0/1 via 10.17.112.1 dev [NULL] table 0 metric -1
14:11:37 WARNING: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.
14:11:37 add_route_ipv6(2000::/3 -> :: metric -1) dev tun0
14:11:37 net_route_v6_add: 2000::/3 via :: dev tun0 table 0 metric -1

**Comment by pkishino** [comment]
> having the same issue with pia running on a synology nas docker, every 3 minutes it disconnects.
> 
> during those 3 minutes i can bring up the transmission webui and i did a test with an online torrent tracker and the vpn seems to be working ok, i am not sure why it's restarting every 3 min
> 
> running with OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping-restart DISABLE_PORT_UPDATER=true OPENVPN_CONFIG=us_california (i have tried several here)
> 
> i did notice these in the logs on startup, but again i can access it just fine and the vpn is working (while it lasts):
> 
> ```
> 16:03:02 net_addr_v4_add: 10.29.112.238/24 dev tun0
> 16:03:02 net_route_v4_add: 191.96.106.38/32 via 172.19.0.1 dev [NULL] table 0 metric -1
> 16:03:02 sitnl_send: rtnl: generic error (-101): Network is unreachable
> 16:03:02 ERROR: Linux route add command failed
> 16:03:02 net_route_v4_add: 0.0.0.0/1 via 10.29.112.1 dev [NULL] table 0 metric -1
> 16:03:02 net_route_v4_add: 128.0.0.0/1 via 10.29.112.1 dev [NULL] table 0 metric -1
> 16:03:02 WARNING: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.
> 16:03:02 add_route_ipv6(2000::/3 -> :: metric -1) dev tun0
> 16:03:02 net_route_v6_add: 2000::/3 via :: dev tun0 table 0 metric -1
> ```
> 
> and also
> 
> ```
> /etc/transmission/userSetup.sh: line 57: "002": syntax error: operand expected (error token is ""002"")
> etc/transmission/userSetup.sh: line 56: "002": syntax error: operand expected (error token is ""002"")
> ```
> 
> but after those 3 minutes i get something like
> 
> ```
> 2023-05-17 16:03:02 Initialization Sequence Completed
> 2023-05-17 16:05:55 [losangeles411] Inactivity timeout (--ping-exit), exiting
> 2023-05-17 16:05:55 /etc/openvpn/tunnelDown.sh tun0 1500 1553 10.29.112.238 255.255.255.0 init
> resolv.conf was restored
> Sending kill signal to transmission-daemon
> Successfuly closed transmission-daemon
> 2023-05-17 16:05:57 net_route_v4_del: 191.96.106.38/32 via 172.19.0.1 dev [NULL] table 0 metric -1
> 2023-05-17 16:05:57 sitnl_send: rtnl: generic error (-3): No such process
> 2023-05-17T23:05:57.021237761Z	stdout	2023-05-17 16:05:57 ERROR: Linux route delete command failed
> ```

Regarding the userSetup thing, that was fixed on dev branch a week or two ago.. if you aren’t in dev by please try it and see if you can replicate the issues

**Comment by ocangelo** [comment]
> Regarding the userSetup thing, that was fixed on dev branch a week or two ago.. if you aren’t in dev by please try it and see if you can replicate the issues

tried it, that seems to remove the userSetup errors but i still get the others and the inactivity timeout issue

**Comment by rbrussell82** [comment]
I'm having the same issue starting last night after rebooting my host server and using Mullvad.  I tried the Dev branch but get this error instead:

```
TRANSMISSION_HOME is currently set to: /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: MULLVAD
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for MULLVAD. Defaulting to external config
Will get configs from https://github.com/haugene/vpn-configs-contrib.git
Cloning https://github.com/haugene/vpn-configs-contrib.git into /config/vpn-configs-contrib
Cloning into '/config/vpn-configs-contrib'...
fatal: Remote branch main} not found in upstream origin
```

**Comment by pkishino** [comment]
> I'm having the same issue starting last night after rebooting my host server and using Mullvad. I tried the Dev branch but get this error instead:
> 
> ```
> TRANSMISSION_HOME is currently set to: /config/transmission-home
> Creating TUN device /dev/net/tun
> Using OpenVPN provider: MULLVAD
> Running with VPN_CONFIG_SOURCE auto
> No bundled config script found for MULLVAD. Defaulting to external config
> Will get configs from https://github.com/haugene/vpn-configs-contrib.git
> Cloning https://github.com/haugene/vpn-configs-contrib.git into /config/vpn-configs-contrib
> Cloning into '/config/vpn-configs-contrib'...
> fatal: Remote branch main} not found in upstream origin
> ```

that error was just fixed

**Comment by rbrussell82** [comment]
> that error was just fixed

Latest dev version did fix that error, but I'm still having the:
```
2023-05-19 08:35:37 [UNDEF] Inactivity timeout (--ping-exit), exiting
2023-05-19 08:35:37 SIGTERM[soft,ping-exit] received, process exiting
```

If it helps at all, my issue seemed to start after apt did this update, although it could be coincidence.
docker-ce:amd64 (5:23.0.6-1~ubuntu.22.04~jammy, 5:24.0.0-1~ubuntu.22.04~jammy)

**Comment by rbrussell82** [comment]
I believe my issue is resolved.  Currently using the latest dev and back on docker-ce 5:24.0.0.  I think mine was related to DNS in the end.
