### ISSUE TITLE
Bug: 5.0 release did not trigger build workflow for semver tag

### ISSUE THREAD

**Issue by ksurl** [haugene/docker-transmission-openvpn#2577]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

docker pull haugene/transmission-openvpn:5.0.0

### Current Behavior

Build workflow did not tag 5,5.0,5.0.0 because the release was tagged as 5.0 and did not get detected via semver format. 

I think this happened in v4 as well. May need to bump to 5.0.1. If it’s a manual release then just a human error. But if it’s automated, maybe need to check release script/tooling for this edge case?

### Expected Behavior

Build workflow will tag semver build and push to registry 

### How have you tried to solve the problem?

Release tag issue

### Log output

Manifest unknown

### HW/SW Environment

```markdown
- OS: debian 11
- Docker: 20.11
```

**Comment by mochman** [comment]
If anyone else is wondering:
docker pull haugene/transmission-openvpn:master
docker pull haugene/transmission-openvpn:edge

both will pull the new 5.0 version until 5.0 is tagged.

**Comment by pkishino** [comment]
Should be fixed now

**Comment by ksurl** [comment]
> hi @pkishino , I still don't see any 5.0 images in [hub.docker.com/r/haugene/transmission-openvpn](https://hub.docker.com/r/haugene/transmission-openvpn/)

It's there now

**Comment by rui-nar** [comment]
yep, I see a 5, a 5.0 and a 5.0.0 
thanks

**Comment by ksurl** [comment]
@pkishino same issue again with 5.0.1 release. The tag has a capital V instead if lower v so I think the metadata action didn't pick it up.

**Comment by pkishino** [comment]
Thanks, hopefully fixed now

**Comment by mochman** [comment]
There is no 5.0.1 tag. It's now 5.0.2.
