### ISSUE TITLE
is it possible to have Only container/transmission through VPN?

### ISSUE THREAD

**Issue by ezkialrage** [haugene/docker-transmission-openvpn#258]
I would like the option to have only the container/Transmission data be tunneled through vpn while the rest of the host machine still has direct access to the net/not routed through vpn.  if this is already possible, i have not been able to figure it out. Is this something i can do with this container?

my usecase for this is I have a server running OMV with plex and when this container runs it changes the host computers ip and i can not use plex remote as well as some ssh things. 

If this is an easy thing that ive been overlooking sorry for the noob question.

**Comment by haugene** [comment]
Yup, that's kind of the point with this container. If you're experiencing that all traffic on the host machine is routed through the vpn I'm assuming you've set the `--net=host` flag? or something similar?

**Comment by ezkialrage** [comment]
I think I did.  You will have to excuse my ignorance with docker. I am running the container from within OMV docker service. It starts the container when the machine runs. 

During configuration I edited the transmission values and open vpn values.  There is an option for net to be 'host', 'bridge' or 'none'.  I did choose host mode as bridged mode added a new input field for port forwarding from the host that I couldn't figure out/was unsure of what to do. I tried using bridge mode with the port 9091 but transmission wouldn't connect then.

 Is this what I should change? Other than that I haven't edited any options or values. 

 I appreciate the help.

**Comment by ezkialrage** [comment]
fixed it by changing to bridge mode and having the host ip as 0.0.0.0.  having this info in the readme might save a lot of people some time.  or maybe i just dont know how it works.  but thank you for helping! i got it to work.

**Comment by gid204** [comment]
@ezkialrage how exactly did you change it to bridge mode?
I've installed it using docker-compose with a .yml file

**Comment by haugene** [comment]
Bridge mode is default. When you're using docker-compose it will create a separate network for all containers in the compose file, and that network will also be a bridge network if you don't define anything else.

https://docs.docker.com/engine/reference/run/#network-settings
