### ISSUE TITLE
Missing "Original UI" on the last version of Image

### ISSUE THREAD

**Issue by masterlog80** [haugene/docker-transmission-openvpn#2587]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    environment:
      - TZ=XXXXX
      - "OPENVPN_PROVIDER=XXXXX"
      - "OPENVPN_USERNAME=XXXXX"
      - "OPENVPN_PASSWORD=XXXXX"
      - "OPENVPN_CONFIG=XXXXX"
      - "LOCAL_NETWORK=192.168.0.0/24,172.17.0.0/16,10.8.0.0/16"
      - "TRANSMISSION_WEB_UI=transmission-web-control"
      - "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false"
      - "TRANSMISSION_RPC_PASSWORD=rpc_pass"
      - "TRANSMISSION_RPC_USERNAME=rpc_user"
      - "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=false"
      - "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=somescript"
      - "TRANSMISSION_SPEED_LIMIT_UP=1"
      - "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false"
      - "TRANSMISSION_SEED_QUEUE_ENABLED=false"
      - "TRANSMISSION_SEED_QUEUE_SIZE=1"
      - "TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true"
      - "TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10"
      - "TRANSMISSION_DOWNLOAD_DIR=/downloads/"
      - "TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete"
      - "TRANSMISSION_WATCH_DIR_ENABLED=false"
      - "TRANSMISSION_BLOCKLIST_URL=https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz"
      - "TRANSMISSION_BLOCKLIST_ENABLED=true"
      - "TRANSMISSION_RPC_WHITELIST=192.168.10.0/24,172.17.0.0/16,10.8.0.0/16,127.0.0.1,::1"
      - "TRANSMISSION_RPC_WHITELIST_ENABLED=false"
      - "TRANSMISSION_ALT_SPEED_DOWN=800"
      - "TRANSMISSION_ALT_SPEED_UP=10"
      - "TRANSMISSION_ALT_SPEED_ENABLED=true"
      - "TRANSMISSION_ALT_SPEED_TIME_ENABLED=false"
      - "TRANSMISSION_LPD_ENABLED=true"
      - "TRANSMISSION_PEER_LIMIT_GLOBAL=500"
      - "TRANSMISSION_PEER_LIMIT_PER_TORRENT=200"
      - "TRANSMISSION_SPEED_LIMIT_DOWN=3000"
      - "TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true"
      - "TRANSMISSION_SPEED_LIMIT_UP=20"
      - "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true"
      - "TRANSMISSION_UTP_ENABLED=true"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - NET_ADMIN
    devices:
     - /dev/net/tun
    volumes:
      - ********/volumes/transmission-openvpn_data:/data/
      - ********:/downloads/
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
      - 9091:9091
      - 51413:51413
    restart: always

### Current Behavior

Hello,
Since at least a couple of days, the `Original UI` stopped working.
Ti better clarify, the [button](https://user-images.githubusercontent.com/33828929/232651486-606cc2c4-d3e3-43c2-a15f-6eef14fe95a3.png) is still there, but it doesn't bring [anywhere](https://user-images.githubusercontent.com/33828929/232651648-e2d26d8d-5515-4bea-b5ef-010638318fd0.png).
As it was working since a couple of days ago, I believe it's related to the recent changes on the Image (https://hub.docker.com/r/haugene/transmission-openvpn).
I have temporary fixed it by using version `4.3.2` which is also much more [smaller](https://user-images.githubusercontent.com/33828929/232654287-36a46222-0b85-46bc-addb-de48bdbf59a9.png) in size (250MB vs. 600MB) compared to the last one.
Can you please troubleshoot this on the latest version as well?
And eventually clarify about the reason of such different size compared to the last one?

Regards,

### Expected Behavior

Being able to use Transmission with the `Original UI`.

### How have you tried to solve the problem?

1) Fixed with release 4.3.2

### Log output

N/A

### HW/SW Environment

```markdown
- OS: Ubuntu Server 22.04 LTS
- Docker: 23.0.2
```

**Comment by pkishino** [comment]
Please check the release notes and especially the move to transmission 4.0.. then check the official transmission repo..

**Comment by masterlog80** [comment]
Hello @pkishino,
Thank you for getting back. I am very familiar with GITHUB, but I have taken a look at here:
https://github.com/haugene/docker-transmission-openvpn/releases
I have understood that you have release version 5 of the Image, and including changes that may explain the very relevant increase in size, but it doesn't explain why the `Original UI` is not available with the last Image.
Am I missing something?

Regards,

**Comment by pkishino** [comment]
The increase is due to having to build the new transmission from source when creating the image…
Regarding the original UI, please look towards the official transmission repo linked in the 5.0.0 release notes.. we only package transmission, we don’t have anything to do with the actual client.. any problems related to that check the original repo

**Comment by the-robbie** [comment]
I'm having the exact same issue. Clicking Original UI results with "404: Not Found
/opt/transmission-ui/transmission-web-control/index.original.html (No such file or directory)". I checked that directory and found the index.original.html file but it appeared to be an empty placeholder file.

This issue just started with the new update this past weekend. I enjoy using both UIs so having the option to switch back and forth between the two was a great feature. I'm not sure specifically what happened but the new update definitely broke this functionality on the transmission-web-control TRANSMISSION_WEB_UI.

**Comment by edgd1er** [comment]
First, i'm sorry to post this here as it is not the main subject for this issue. 
Concerning the image size, building the deb package during transmissionBuilder stage would help. The debian package would then be either exported as artefact and/or used as package to install transmission v4 during the last phase.

To produce the debian package, just add after `make install`. TBT_VERSION is 4.0.3 at the moment.
```
checkinstall -y -D --pkgname transmission  --pakdir /var/tmp --pkgversion=${TBT_VERSION}
```
then in the next stage, add `COPY --from=transmissionBuilder /var/tmp/*.deb /var/tmp/` 
and hereunder a simple check for existing deb file and an install.
```
if [[ ${TBT_VERSION} =~ ^4 ]]; then \
      ls -alh /var/tmp/*.deb ;\
      debfile=$(compgen -G /var/tmp/transmission_*_$(dpkg --print-architecture).deb); \
      if [[ -n ${debfile} ]]; then \
      echo "Installing transmission ${TBT_VERSION}" && dpkg -i ${debfile} ;\
      else echo "No /var/tmp/transmission_*_$(dpkg --print-architecture).deb found. Exiting" \
      ; exit ; fi ; \
```

I'm sure you would prefer a PR but my fork is much different from yours, I'll see if this week end I could extract what is needed to go through the debian package. my V4 image is just 6Mb larger than the v3 image.

Last difference that I'm using debian:bullseye-slim as base image.

**Comment by pkishino** [comment]
> First, i'm sorry to post this here as it is not the main subject for this issue. Concerning the image size, building the deb package during transmissionBuilder stage would help. The debian package would then be either exported as artefact and/or used as package to install transmission v4 during the last phase.
> 
> To produce the debian package, just add, in Dockerfile, after `make install`. TBT_VERSION is 4.0.3 at the moment.
> 
> ```
> checkinstall -y -D --pkgname transmission  --pakdir /var/tmp --pkgversion=${TBT_VERSION}
> ```
> 
> then in the next stage, add `COPY --from=transmissionBuilder /var/tmp/*.deb /var/tmp/` and hereunder a simple check for existing deb file and an install.
> 
> ```
> if [[ ${TBT_VERSION} =~ ^4 ]]; then \
>       ls -alh /var/tmp/*.deb ;\
>       debfile=$(compgen -G /var/tmp/transmission_*_$(dpkg --print-architecture).deb); \
>       if [[ -n ${debfile} ]]; then \
>       echo "Installing transmission ${TBT_VERSION}" && dpkg -i ${debfile} ;\
>       else echo "No /var/tmp/transmission_*_$(dpkg --print-architecture).deb found. Exiting" \
>       ; exit ; fi ; \
> ```
> 
> I'm sure you would prefer a PR but my fork is much different from yours, I'll see if this week end I could extract what is needed to go through the debian package. my V4 image is just 6Mb larger than the v3 image.
> 
> Last difference that I'm using debian:bullseye-slim as base image.

cheers for the suggestion, trying it out locally

**Comment by pkishino** [comment]
Only TWC? I know flood still works fine.. I’ll check with twc later today

**Comment by jgramling17** [comment]
> Only TWC? I know flood still works fine.. I’ll check with twc later today

I've only tried TWC and flood. Flood works. 
The issue is when you click the "Original UI" button while using TWC.

**Comment by pkishino** [comment]
So,I don’t get why you’re have set TWC as the UI but want to use the original transmission GUI?? Don’t use  TWC then, use the original UI., TWC hasn’t been updated in a long time, yes there is a fork but that’s not what is used here.. 
without having checked the code I suspect with transmission 4 , they changed some details around the UI which is why the above button isn’t working.. please just use the transmission 4 native GUI or e.g flood

**Comment by pkishino** [comment]
Ok, had a quick look, the paths have changed so the docker file needs updating for the TWC symlinks.. I’ll see if I have time tomorrow..
Basically paths have moved to /usr/local/share/transmission/public_html

**Comment by pkishino** [comment]
Feel free to try a local build and check if everything works after changing the parts

**Comment by pkishino** [comment]
It looked like it worked fine when I updated the paths locally
