### ISSUE TITLE
VPN Unlimited provider

### ISSUE THREAD

**Issue by tokmudim** [haugene/docker-transmission-openvpn#259]
Hi,

I'm using https://www.vpnunlimitedapp.com vpn. Can somebody help me to add this provider?

**Comment by rwaesely** [comment]
Hi, seems haugene is busy theses days... I meet an issue with existing providers, but I do not find any support currently.

**Comment by neutrongenious** [comment]
i tried adding custom configuration. connection is successful, ping works as well. but face error on trackers not reachable

**Comment by haugene** [comment]
Trackers not reachable might be DNS issue, see README for setup. If you want to add this as a provider, please provide a link to all .ovpn config files (typically a .zip file)

And yeah. Sorry about the delay. Been busy and this project is starting to take too much time, need a collaborator ;)

**Comment by bdoooh** [comment]
They only support torrents from a handful of cities, so if you're not using one of their cities, I'm assuming there'll be issues.

**Comment by fusiondust** [comment]
Did you get the zip file?  They sent me one on request for setting up with DD-WRT.  Worked really great however I am now looking into setting up this provider with this docker.

**Comment by coolboiime** [comment]
Closing this for merging into issue #554! Please have all issues and updates directed towards that issue. Closing this for now, thanks!
