### ISSUE TITLE
duplicate mount point

### ISSUE THREAD

**Issue by rhodesfreak** [haugene/docker-transmission-openvpn#2594]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - /srv//Downloads/Transmission:/data
        environment:
            - PUID=1000
            - PGID=100
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=NORDVPN
            - NORDVPN_COUNTRY=
            - NORDVPN_CATEGORY=legacy_p2p
            - NORDVPN_PROTOCOL=udp
            - OPENVPN_USERNAME=
            - OPENVPN_PASSWORD=
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=
            - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
            - DNS=8.8.8.8,8.8.4.4
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        image: haugene/transmission-openvpn

### Current Behavior

When i'm triying to update I get the following error message: "duplicate mount point".

### Expected Behavior

I should be able to update as always

### How have you tried to solve the problem?

I'm not a portainer expert I would not even know where to start

### Log output

TRANSMISSION_HOME is currently set to: /config/transmission-home
WARNING: Deprecated. Found old default transmission-home folder at /data/transmission-home, setting this as TRANSMISSION_HOME. This might break in future versions.
We will fallback to this directory as long as the folder exists. Please consider moving it to /config/<transmission-home>

### HW/SW Environment

```markdown
- OS: OMV 6.3.9-1
- Docker: Portainer 2.18.1
```

**Comment by pkishino** [comment]
please read documentation/release notes.. you are missing /config mount
