### ISSUE TITLE
Update Openvpn version

### ISSUE THREAD

**Issue by Mikiya83** [haugene/docker-transmission-openvpn#261]
Hi
First thanks for the work, this docker is really helpfull and well configurable !
But i only have one problem : 
I use it with many custom providers and unfortunatly, openvpn version is outdated (2.3.2, now 2.4.3), and i encountered some problems. I think 2.3.2 is the last version on ubuntu 14.04, so is it possible to use ubuntu 16.04 as base to get a more recent version of openvpn ?
Thanks !

**Comment by Mikiya83** [comment]
Or maybe we can use this method https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos to use 14.04 and do not break anything ?

**Comment by Mikiya83** [comment]
Last update : i switch to ubuntu 16.04 (better openssl version too), update versions of dockerize and  dumb-init with :


FROM ubuntu:16.04
MAINTAINER Kristian Haugene

VOLUME /data
VOLUME /config

# Update packages and install software
RUN apt-get update \
    && apt-get -y install software-properties-common ufw \
    && add-apt-repository multiverse \
    && add-apt-repository ppa:transmissionbt/ppa \
    && apt-get update \
    && apt-get install -y transmission-cli transmission-common transmission-daemon \
    && apt-get install -y curl rar unrar zip unzip wget \
    && wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg|apt-key add - \
    && echo "deb http://build.openvpn.net/debian/openvpn/stable trusty main" > /etc/apt/sources.list.d/openvpn-aptrepo.list \
    && apt-get update \
    && apt-get install -y openvpn \
    && curl -sLO https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64.deb \
    && dpkg -i dumb-init_*.deb \
    && rm -rf dumb-init_*.deb \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && curl -L https://github.com/jwilder/dockerize/releases/download/v0.5.0/dockerize-linux-amd64-v0.5.0.tar.gz | tar -C /usr/local/bin -xzv \
    && groupmod -g 1000 users \
    && useradd -u 911 -U -d /config -s /bin/false abc \
    && usermod -G users abc

**Comment by rwaesely** [comment]
Hi Mikiya,

I tried with your code, but I get an error at container run : [dumb-init] /etc/openvpn/start.sh : Permission denied.
Any clues about solving this issue ?
Cheers,
rwaesely

**Comment by Mikiya83** [comment]
Hi
Do you use a custom user to start transmission (with PUID/PGID) ? 
Do you have the line of error in start.sh ?

**Comment by rwaesely** [comment]
Hi,
Nope, not at all. I run the container with "sudo docker run..."
I added a few lines in the dockerfile to add +x execution rights on every sh file, now it starts just fine.
Unfortunately, I meet the same dead end than original container : it launches, but I have no internet connection on the container. It cannot find any tracker :-(
I have no clue if this is a synology specific issue...

**Comment by Mikiya83** [comment]
I do not have to add any chmod +x in dockerfile, it's strange ...
Does your version of DSM was updated when the problem started ?
Have you tried your VPN settings on another computer recently  to check ?

**Comment by rwaesely** [comment]
There were a lot of DSM updates recently, so... Maybe. The HMA client works just fine on my laptop (macbook air), and my synology connects to the VPN without any issues, I can still download using download station any ISO of my favourite linux distribution :D from there. Still, nothing from the container. So it IS either related to the way DSM runs the container, either to the network information used in the HMA config file (ovpn). Sadly, I have no skills to debug this.

**Comment by haugene** [comment]
Hi guys. Haven't had the time to follow up on this container the last weeks. But now it's vacation time, and if it rains one day I'll do some upgrading here. We should probably change the base for Ubuntu 16.04 and get newer openvpn version.

**Comment by Mikiya83** [comment]
Good to here that, i do nat have any problems here with the conf describe in post above 👍

**Comment by gflarity** [comment]
I've got a modified version of Mikiya83's build working. I'll submit a pull request shortly.

**Comment by haugene** [comment]
Pull request #274 merged and tested using PIA. Thanks for your contributions @gflarity and @Mikiya83, closing this issue now.
