### ISSUE TITLE
Cannot access Webui

### ISSUE THREAD

**Issue by manandoshi9** [haugene/docker-transmission-openvpn#262]
Hello,

I am running the docker image with a custom vpn ( Protonvpn ). From the logs it seems like the connections is successful but yet I cannot access the webui.

Below is the text from the logs

Using OpenVPN provider: CUSTOM
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Sat Jun 24 16:22:38 2017 Multiple --up scripts defined.  The previously configured script is overridden.
Sat Jun 24 16:22:38 2017 Multiple --down scripts defined.  The previously configured script is overridden.
Sat Jun 24 16:22:38 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Sat Jun 24 16:22:38 2017 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Sat Jun 24 16:22:38 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Jun 24 16:22:38 2017 Control Channel Authentication: tls-auth using INLINE static key file
Sat Jun 24 16:22:38 2017 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Sat Jun 24 16:22:38 2017 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Sat Jun 24 16:22:38 2017 Socket Buffers: R=[212992->131072] S=[212992->131072]
Sat Jun 24 16:22:38 2017 UDPv4 link local: [undef]
Sat Jun 24 16:22:38 2017 UDPv4 link remote: [AF_INET]185.159.157.15:1194
Sat Jun 24 16:22:39 2017 TLS: Initial packet from [AF_INET]185.159.157.15:1194, sid=32b2aa76 112d0ac3
Sat Jun 24 16:22:39 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Jun 24 16:22:39 2017 VERIFY OK: depth=2, C=CH, O=ProtonVPN AG, CN=ProtonVPN Root CA
Sat Jun 24 16:22:39 2017 VERIFY OK: depth=1, C=CH, O=ProtonVPN AG, CN=ProtonVPN Intermediate CA 1
Sat Jun 24 16:22:39 2017 Validating certificate key usage
Sat Jun 24 16:22:39 2017 ++ Certificate has key usage  00a0, expects 00a0
Sat Jun 24 16:22:39 2017 VERIFY KU OK
Sat Jun 24 16:22:39 2017 Validating certificate extended key usage
Sat Jun 24 16:22:39 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sat Jun 24 16:22:39 2017 VERIFY EKU OK
Sat Jun 24 16:22:39 2017 VERIFY OK: depth=0, CN=uk-04.protonvpn.com
Sat Jun 24 16:22:39 2017 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Sat Jun 24 16:22:39 2017 Data Channel Encrypt: Using 512 bit message hash 'SHA512' for HMAC authentication
Sat Jun 24 16:22:39 2017 Data Channel Decrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Sat Jun 24 16:22:39 2017 Data Channel Decrypt: Using 512 bit message hash 'SHA512' for HMAC authentication
Sat Jun 24 16:22:39 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-SHA, 2048 bit RSA
Sat Jun 24 16:22:39 2017 [uk-04.protonvpn.com] Peer Connection Initiated with [AF_INET]185.159.157.15:1194
Sat Jun 24 16:22:42 2017 SENT CONTROL [uk-04.protonvpn.com]: 'PUSH_REQUEST' (status=1)
Sat Jun 24 16:22:42 2017 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.8.8.1,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,route-gateway 10.8.8.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.8.59 255.255.255.0'
Sat Jun 24 16:22:42 2017 OPTIONS IMPORT: timers and/or timeouts modified
Sat Jun 24 16:22:42 2017 OPTIONS IMPORT: explicit notify parm(s) modified
Sat Jun 24 16:22:42 2017 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Sat Jun 24 16:22:42 2017 Socket Buffers: R=[131072->425984] S=[131072->425984]
Sat Jun 24 16:22:42 2017 OPTIONS IMPORT: --ifconfig/up options modified
Sat Jun 24 16:22:42 2017 OPTIONS IMPORT: route options modified
Sat Jun 24 16:22:42 2017 OPTIONS IMPORT: route-related options modified
Sat Jun 24 16:22:42 2017 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sat Jun 24 16:22:42 2017 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
Sat Jun 24 16:22:42 2017 TUN/TAP device tun0 opened
Sat Jun 24 16:22:42 2017 TUN/TAP TX queue length set to 100
Sat Jun 24 16:22:42 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Sat Jun 24 16:22:42 2017 /sbin/ip link set dev tun0 up mtu 1500
Sat Jun 24 16:22:42 2017 /sbin/ip addr add dev tun0 10.8.8.59/24 broadcast 10.8.8.255
Sat Jun 24 16:22:42 2017 /etc/openvpn/update-resolv-conf tun0 1500 1634 10.8.8.59 255.255.255.0 init
dhcp-option DNS 10.8.8.1
Sat Jun 24 16:22:42 2017 /sbin/ip route add 185.159.157.15/32 via 172.17.0.1
Sat Jun 24 16:22:42 2017 /sbin/ip route add 0.0.0.0/1 via 10.8.8.1
Sat Jun 24 16:22:42 2017 /sbin/ip route add 128.0.0.0/1 via 10.8.8.1
Sat Jun 24 16:22:42 2017 Initialization Sequence Completed

Ip route table within the container
0.0.0.0/1 via 10.8.8.1 dev tun0 
default via 172.17.0.1 dev eth0 
10.8.8.0/24 dev tun0  proto kernel  scope link  src 10.8.8.59 
128.0.0.0/1 via 10.8.8.1 dev tun0 
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.2 
185.159.157.15 via 172.17.0.1 dev eth0 
192.168.1.0/24 via 172.17.0.1 dev eth0 

DockerEnv file
#Remove # for variables you want to use
OPENVPN_PROVIDER=CUSTOM
#OPENVPN_CONFIG=
OPENVPN_USERNAME=xxxxx
OPENVPN_PASSWORD=xxxxx
LOCAL_NETWORK=192.168.1.0/24
OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60

Can you please help me figure out what is missing?

**Comment by manandoshi9** [comment]
Did some more digging and it seems like the transmission start.sh is not executing. I  sshed inside the docker container and ran the start.sh manually and now I can access transmission from the webui.

I am not sure what is happening here.

Thanks

**Comment by kaethorn** [comment]
@manandoshi9 Did you generate the custom OpenVPN config? If so, please make sure to remove the `up <path>` and `down <path>` entries from your .ovpn file. The logs you posted suggest that the `--up` and `--down` parameters are overridden, effectively skipping the transmission startup.

**Comment by manandoshi9** [comment]
Thanks @kaethorn  that was it.
