### ISSUE TITLE
Enabling Transmission Webcontrol UI no longer allows to also use the default web UI

### ISSUE THREAD

**Issue by kstanleyadams** [haugene/docker-transmission-openvpn#2635]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

transmission-openvpn:
    container_name: transmission-openvpn
    mem_limit: 1024m
    cap_add:
        - NET_ADMIN
    #user: "${UID}:100" Running as root so it can create the TUN device
    volumes:
        - ./transmission-openvpn/resolve.conf:/etc/resolve.conf
        - ./transmission-openvpn/config:/config
        - /volume1/downloads:/volume1/downloads
        - /volume1/downloads:/data
    environment:
        - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
        - OPENVPN_CONFIG=${OPENVPN_CONFIG}
        - OPENVPN_USERNAME=${OPENVPN_USERNAME}
        - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
        - TRANSMISSION_HOME=/config/transmission-home
        - TRANSMISSION_UMASK=000
        - LOCAL_NETWORK=192.168.0.0/16
        - CREATE_TUN_DEVICE=true
        - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
        - TRANSMISSION_WATCH_DIR=/data/watch
        - TRANSMISSION_WEB_UI=transmission-web-control
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - '32770:8888'
        - '32771:9091'
    image: haugene/transmission-openvpn
    restart: unless-stopped

### Current Behavior

Transmission web control UI works as normal. There is a link within this UI that allows you to also use the original/official UI.

This used to work. However, for a month or two now it instead shows a page with the following error

404: Not Found

/opt/transmission-ui/transmission-web-control/index.original.html (No such file or directory)

### Expected Behavior

Expected behaviour is to redirect you to the original/default web UI of transmission

### How have you tried to solve the problem?

Tried rebuilding the container

### Log output

No relevant items in the docker log.

### HW/SW Environment

```markdown
- OS: Synology DSM 7
- Docker: 
haugene/transmission-openvpn:latest
```

**Comment by ilike2burnthing** [comment]
Dupe - https://github.com/haugene/docker-transmission-openvpn/issues/2587

Fixed in - https://github.com/haugene/docker-transmission-openvpn/pull/2600

Switch to dev branch or wait until this is merged into latest.
