### ISSUE TITLE
Transmission hangs when deleting downloads (Trash data and remove from list)

### ISSUE THREAD

**Issue by conorlap** [haugene/docker-transmission-openvpn#2639]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

  transmission:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    command:
      - dumb-init
      - /etc/openvpn/start.sh
    container_name: transmission
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - CREATE_TUN_DEVICE=true
      - DISABLE_PORT_UPDATER=true
      - DROP_DEFAULT_ROUTE=
      - ENABLE_UFW=false
      - GLOBAL_APPLY_PERMISSIONS=true
      - HEALTH_CHECK_HOST=google.com
      - 'LOCAL_NETWORK=192.168.0.0/24, 192.168.1.0/24, 10.192.1.0/24'
      - LOG_TO_STDOUT=false
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - OPENVPN_PASSWORD=AAAAA
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=AAAAA
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PEER_DNS=true
      - PEER_DNS_PIN_ROUTES=true
      - PGID=
      - PUID=
      - REVISION=1103172c3288b7de681e2fb7f1378314f17f66cf
      - SELFHEAL=false
      - TRANSMISSION_DOWNLOAD_DIR=/media/downloads/completed
      - TRANSMISSION_HOME=/config/transmission-home
      - TRANSMISSION_INCOMPLETE_DIR=/media/downloads/incomplete
      - TRANSMISSION_RPC_PASSWORD=AAAAA
      - TRANSMISSION_RPC_PORT=9091
      - TRANSMISSION_RPC_URL=/transmission/
      - TRANSMISSION_RPC_USERNAME=AAAAA
      - TRANSMISSION_WATCH_DIR=/media/downloads/watch
      - UFW_ALLOW_GW_NET=false
      - UFW_DISABLE_IPTABLES_REJECT=false
      - UFW_EXTRA_PORTS=
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PASSWORD=
      - WEBPROXY_PORT=8118
      - WEBPROXY_USERNAME=
    hostname: 546bcc2cee6f
    image: haugene/transmission-openvpn:latest
    ipc: private
    labels:
      autoheal: true
      com.centurylinklabs.watchtower.enable: true
      org.opencontainers.image.created: '2023-04-16T21:54:59.984Z'
      org.opencontainers.image.description: Docker container running Transmission
        torrent client with WebUI over an OpenVPN tunnel
      org.opencontainers.image.licenses: GPL-3.0
      org.opencontainers.image.ref.name: ubuntu
      org.opencontainers.image.revision: 1103172c3288b7de681e2fb7f1378314f17f66cf
      org.opencontainers.image.source: https://github.com/haugene/docker-transmission-openvpn
      org.opencontainers.image.title: docker-transmission-openvpn
      org.opencontainers.image.url: https://github.com/haugene/docker-transmission-openvpn
      org.opencontainers.image.version: 5.0.2
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:13
    networks:
      - my-multihost-network
    ports:
      - 0.0.0.0:8118:8118/tcp
      - 0.0.0.0:9091:9091/tcp
      - 0.0.0.0:9091:9091/udp
    restart: always
    volumes:
      - /srv/appdata/transmission:/config
      - /srv/mergerfs/Files/media/downloads:/data
      - /etc/localtime:/etc/localtime:ro
      - /srv/appdata/transmission/default.ovpn:/etc/openvpn/custom/default.ovpn
      - /srv/mergerfs/Files/media/downloads:/media/downloads

### Current Behavior

If I try to "trash data and remove from list" it causes Transmission to hang. Eventually it seems to delete the file and Transmission becomes responsive again but can take an extremely long time, especially if it's a large file. 
I didn't experience this on the older versions of the docker (2021 and prior etc)

### Expected Behavior

I expect the file to delete and the instance of Transmission to not hang/crash

### How have you tried to solve the problem?

Tried both latest and dev

### Log output

Nothing unusual comes up in the logs when this occurs. 

### HW/SW Environment

```markdown
- OS: Openmediavault 6.4.6-1 (Shaitan)
- Docker: 24.0.2
```

**Comment by pkishino** [comment]
please raise this issue on the official transmission repo, this is not related to the docker image here..
