### ISSUE TITLE
AUTH_FAILED NORDVPN

### ISSUE THREAD

**Issue by Papoualex** [haugene/docker-transmission-openvpn#2642]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

![Screenshot_20230630_191432_Chrome](https://github.com/haugene/docker-transmission-openvpn/assets/138242864/e068d779-7903-4c30-824a-208de7d80b3e)

### Current Behavior

Worked great for years. No password change. Authentication problem looped for 24 hours.

### Expected Behavior

authentication successful

### How have you tried to solve the problem?

Reboot system

### Log output

![Screenshot_20230630_192357_Chrome](https://github.com/haugene/docker-transmission-openvpn/assets/138242864/73c277f8-6bfa-4898-9eeb-07d98526e273)

### HW/SW Environment

```markdown
- OS:DSM 6.2.4
- Docker:20.10.3
```

**Comment by oldirtybasti** [comment]
Had exactly the same problem, also worked for years. I received a mail from NORDVPN this week that they will change something with the auth process:

You have to create a manual setup with username/pw on their site and use that to login. After that everything works fine again

**Comment by cedwards39** [comment]
@oldirtybasti any chance you could provide some more details on that? I already have a username/pw with my email (I don't use SSO) - that's what I've been running with for a long time but it suddenly stopped working. I've tried a password reset but that didn't help. Is there something else I have to explicitly do?

**Comment by cedwards39** [comment]
Nevermind I found instructions here: https://support.nordvpn.com/1114905392

Thanks for the tip, this was driving me nuts!

**Comment by Papoualex** [comment]
I found the solution, it's very simple. NORDVPN offers a password and an identifier created by them. Just copy them to environment in docker container.
https://nordaccount.com/login/password?challenge=2%7C31289daf5b9b490fbc3727e8a9f0ada2

**Comment by brett-stanley** [comment]
To clarify from above, use the Manual Setup on NordVPN to use Service Credentials (system-generated username and password).

https://my.nordaccount.com/dashboard/nordvpn/manual-configuration/

**Comment by ilike2burnthing** [comment]
https://github.com/haugene/docker-transmission-openvpn/issues/2638

**Comment by alexishirst** [comment]
Is it worth improving the logging to clarify for NordVPN the 'manual' authentication method is required vs. the previously accepted NordVPN account username and password?

I did check the documentation here but this is also not mentioned:
http://haugene.github.io/docker-transmission-openvpn/provider-specific/#nordvpn

I'd be more than happy to help update the documentation!

**Comment by ririck0** [comment]
hello, since this afternoon I have encountered this problem again.  Are there others in the same situation as me?

Best regards,
Ririck

**Comment by Papoualex** [comment]
Same for me

**Comment by paulmiddelkoop** [comment]
Same for me

**Comment by Papoualex** [comment]
I think Haugene needs to modify its docker so that it accepts NordVPN access tokens.

**Comment by ilike2burnthing** [comment]
Not seeing any issues here with Nord.

Stop the container, change your Nord password (this will also change your service credential password), and after ~15mins edit the container with the new service credential password, and redeploy. If that doesn't work, try again but with the container down for an hour or two.

**Comment by SirMartin** [comment]
I did like @ilike2burnthing commented and worked fine for me

**Comment by ririck0** [comment]
Thanks @ilike2burnthing :)
