### ISSUE TITLE
Cannot pre-load keyfile

### ISSUE THREAD

**Issue by breakfastpasta** [haugene/docker-transmission-openvpn#2645]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

here is my compose running thru a portainer stack

transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - '/srv/raidio/data/torrents:/data'
      - '/srv/dev-disk-by-uuid-45b14269-fd5b-4daf-ba31-b65a6c8bfda1/transmission-ovpn:/config'
      - '/srv/dev-disk-by-uuid-45b14269-fd5b-4daf-ba31-b65a6c8bfda1/ovpn_confs/:/etc/openvpn/custom/'
    environment:
      - PUID=1004
      - PGID=1004
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_CONFIG=AirVPN_America_UDP-443-Entry3_tr
      - OPENVPN_USERNAME=poop
      - OPENVPN_PASSWORD=poop
      - LOCAL_NETWORK=192.168.0.0/24
      - TRANSMISSION_WEB_UI=transmission-web-control
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      customnetwork:
        ipv4_address: 172.22.0.7
    logging:
      driver: json-file
      options:
          max-size: 10m
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn

### Current Behavior

I am trying to use Airvpn, which means I need to use a custom config. Upon starting the container, I get the error message 

"Cannot pre-load keyfile (/etc/openvpn/custom/"tls-crypt.key")"
and then, "Exiting due to fatal error". 

### Expected Behavior

For the container to start with custom config

### How have you tried to solve the problem?

1) changing openvpn config versions from provider
2) changing permissions of keyfile (ownership, also tried 777)
3) change permissions of entire custom config folder

### Log output

Starting container with revision: 1103172c3288b7de681e2fb7f1378314f17f66cf

TRANSMISSION_HOME is currently set to: /config/transmission-home

Creating TUN device /dev/net/tun

Using OpenVPN provider: CUSTOM

Running with VPN_CONFIG_SOURCE auto

CUSTOM provider specified but not using default.ovpn, will try to find a valid config mounted to /etc/openvpn/custom

Starting OpenVPN using config AirVPN_America_UDP-443-Entry3_tr.ovpn

Modifying /etc/openvpn/custom/AirVPN_America_UDP-443-Entry3_tr.ovpn for best behaviour in this container

Modification: Point auth-user-pass option to the username/password file

Modification: Change ca certificate path

Modification: Change ping options

Modification: Update/set resolv-retry to 15 seconds

Modification: Change tls-crypt keyfile path

Modification: Set output verbosity to 3

Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop

Modification: Updating status for config failure detection

Setting OpenVPN credentials...

adding route to local network 192.168.0.0/24 via 172.22.0.1 dev eth0

2023-07-01 14:39:10 Cannot pre-load keyfile (/etc/openvpn/custom/"tls-crypt.key")

2023-07-01 14:39:10 Exiting due to fatal error

### HW/SW Environment

```markdown
- OS: debian 11 bullseye
Linux magi 6.1.0-0.deb11.7-amd64 Debian 6.1.20-2~bpo11+1 x86_64 GNU/Linux
- Docker: Docker version 24.0.2, build cb74dfc
```

### Anything else?

> ls -alh
total 36K
drwxr-xr-x  2 datauser datausers 4.0K Jul  1 08:05 .
drwxr-xr-x 26 root     root      4.0K Jul  1 06:07 ..
-rw-r--r--  1 datauser datausers 7.0K Jul  1 08:04 AirVPN4.zip
-rw-r--r--  1 datauser datausers  749 Jul  1 08:05 AirVPN_America_UDP-443-Entry3.ovpn
-rw-r--r--  1 datauser datausers 2.3K Jul  1  2023 ca.crt
-rw-r--r--  1 datauser datausers  601 Jul  1  2023 tls-crypt.key
-rw-r--r--  1 datauser datausers 2.4K Jul  1  2023 user.crt
-rw-r--r--  1 datauser datausers 3.2K Jul  1  2023 user.key

**Comment by pkishino** [comment]
this should be a support question, not a container issue.. as you can see in your error message, there are quotation marks around the key.. not a valid path.. check your ovpn file
