### ISSUE TITLE
Parse Error Suddenly Appearing in Container Logs

### ISSUE THREAD

**Issue by ingsocdev** [haugene/docker-transmission-openvpn#2646]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/Data/container_data/transmission:/config
    environment:
      - OPENVPN_PROVIDER=NORDVPN
        #- OPENVPN_CONFIG=uk
      - OPENVPN_USERNAME=<nord_email>
      - OPENVPN_PASSWORD=<nord_password>
      - NORDVPN_COUNTRY=UK
      - NORDVPN_CATEGORY=legacy_p2p
      - NORDVPN_PROTOCOL=tcp
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_RPC_PASSWORD=<my transmission password>
      - TRANSMISSION_RPC_USERNAME=<my transmission username>
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: always
    ports:
      - 9091:9091
    image: haugene/transmission-openvpn

### Current Behavior

Container doesn't start and keeps restarting.

### Expected Behavior

Container to start and app to become accessible.

### How have you tried to solve the problem?

Checked the logs.

### Log output

TRANSMISSION_HOME is currently set to: /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN
/etc/openvpn/nordvpn/..
INFO: OVPN: Checking curl installation
INFO: OVPN: DNS resolution ok
INFO: OVPN: ok, configurations download site reachable
INFO: OVPN: Removing existing configs in /etc/openvpn/nordvpn
parse error: Invalid numeric literal at line 1, column 7

### HW/SW Environment

```markdown
- OS: Ubuntu
- Docker:
```

**Comment by ilike2burnthing** [comment]
> - [x] I have searched the existing issues

Lies...
https://github.com/haugene/docker-transmission-openvpn/issues/2638

**Comment by ingsocdev** [comment]
Yeah, my bad. I have resolved it. I did actually find this a minute ago after searching and came back to close the issue.

My mistake was only looking at the OPEN issues...
