### ISSUE TITLE
Which release is using the latest Transmission 3 please? 

### ISSUE THREAD

**Issue by tjxme** [haugene/docker-transmission-openvpn#2649]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

version: '3.3'
services:
  transmission-openvpn:
    container_name: 00-Transmission-OPVN
    cap_add:
      - NET_ADMIN
    volumes:
      - /volume1/media:/data
      - /volume1/download:/downloads
      - /volume1/docker/transmission:/config
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=ca_toronto
      - OPENVPN_USERNAME=p0822614
      - OPENVPN_PASSWORD=Tjx2820000
      - LOCAL_NETWORK=192.168.0.0/16
      - ENABLE_UFW=true
      - UFW_ALLOW_GW_NET=true
      - UFW_EXTRA_PORTS=9910,23561,443
      - UFW_DISABLE_IPTABLES_REJECT=true
      - GLOBAL_APPLY_PERMISSIONS=false
      - TRANSMISSION_WEB_UI=transmission-web-control
      - PUID=1026
      - PGID=100
      - TZ=America/Toronto
      - TRANSMISSION_WATCH_DIR=/downloads/watch
      - TRANSMISSION_DOWNLOAD_DIR=/downloads/transmission/completed
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/transmission/incomplete
      #SCRIPT-TORRENT-DONE-ENABLED=true
      #SCRIPT-TORRENT-DONE-FILENAME=/downloads/transmission/home/scripts/unzip.sh
      - CREATE_TUN_DEVICE=true
      - HEALTH_CHECK_HOST=google.ca
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    logging:
       driver: json-file
       options:
           max-size: 10m
    ports:
       - '9091:9091'
    sysctls:
       - net.ipv6.conf.all.disable_ipv6=1
    dns:
       - 1.1.1.1
       - 1.0.0.1
    image: haugene/transmission-openvpn:latest

### Current Behavior

there is nothing wrong, it works perfectly. 
its just one of my most used PT site requires specific version of transmission and they are not supporting 4.0 and above yet. 
which version should I roll back to ? 

### Expected Behavior

release number with latest Transmission 3

### How have you tried to solve the problem?

-

### Log output

-

### HW/SW Environment

```markdown
- OS:synology DSM 7.2
- Docker:docker compose
```

**Comment by ilike2burnthing** [comment]
v4.3.2

This should be a discussion, not an issue.
