### ISSUE TITLE
Maximum option line length (256) exceeded

### ISSUE THREAD

**Issue by domier** [haugene/docker-transmission-openvpn#2663]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

Created using synology container manager, but here are the environment variables:

CREATE_TUN_DEVICE | true
DROP_DEFAULT_ROUTE | **None**
ENABLE_UFW | false
GLOBAL_APPLY_PERMISSIONS | true
HEALTH_CHECK_HOST | google.com
LOG_TO_STDOUT | false
NORDVPN_CATEGORY | legacy_p2p
NORDVPN_COUNTRY | NL
NORDVPN_PROTOCOL | tcp
OPENVPN_CONFIG_URL | https://github.com/haugene/vpn-configs-contrib/blob/main/openvpn/nordvpn/configure-openvpn.sh
OPENVPN_OPTS | --inactive 3600 --ping 10 --ping-exit 60
OPENVPN_PASSWORD | ****
OPENVPN_PROVIDER | NORDVPN
OPENVPN_USERNAME | ****
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PEER_DNS | true
PEER_DNS_PIN_ROUTES | true
PGID | **None**
PUID | **None**
REVISION | b33d0fe4c938259a0d4eb844e55468f387456121
SELFHEAL | false
TRANSMISSION_DOWNLOAD_DIR | /data/completed
TRANSMISSION_HOME | /config/transmission-home
TRANSMISSION_INCOMPLETE_DIR | /data/incomplete
TRANSMISSION_RPC_PASSWORD | **None**
TRANSMISSION_RPC_PORT | 9091
TRANSMISSION_RPC_USERNAME | **None**
TRANSMISSION_WATCH_DIR | /data/watch
UFW_ALLOW_GW_NET | false
UFW_DISABLE_IPTABLES_REJECT | false
UFW_EXTRA_PORTS | **None**
WEBPROXY_ENABLED | false
WEBPROXY_PASSWORD | **None**
WEBPROXY_PORT | 8118
WEBPROXY_USERNAME | **None**

### Current Behavior

Startup fails with an error Maximum option line length (256) exceeded

### Expected Behavior

Starts sucessfully

### How have you tried to solve the problem?

Transmission had been running successfully for some time, but it seems an update to a newer version caused it to stop working. After reading the documentation and logs I saw I needed to add OPENVPN_CONFIG_URL and OPENVPN_PROVIDER, but after adding them I was met with the option line length error and not sure how to resolve. I tried looking for related text inside the vpn config file, but didn't see anything and have run out of ideas (https://github.com/haugene/vpn-configs-contrib/blob/main/openvpn/nordvpn/configure-openvpn.sh)

### Log output

Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121

TRANSMISSION_HOME is currently set to: /config/transmission-home

WARNING: Deprecated. Found old default transmission-home folder at /data/transmission-home, setting this as TRANSMISSION_HOME. This might break in future versions.

We will fallback to this directory as long as the folder exists. Please consider moving it to /config/transmission-home

Creating TUN device /dev/net/tun

Using OpenVPN provider: NORDVPN

Found URL to single OpenVPN config, will download and use it.

Modifying /etc/openvpn/nordvpn/downloaded_config.ovpn for best behaviour in this container

Modification: Point auth-user-pass option to the username/password file

Modification: Change ca certificate path

Modification: Change ping options

Modification: Update/set resolv-retry to 15 seconds

Modification: Change tls-crypt keyfile path

Modification: Set output verbosity to 3

Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop

Modification: Updating status for config failure detection

Setting OpenVPN credentials...

Options error: In /etc/openvpn/nordvpn/downloaded_config.ovpn:1: Maximum option line length (256) exceeded, line starts with {"payload":{"allShortcutsEnabled":false,"fileTree":{"openvpn/nordvpn":{"items":[{"name":"configure-openvpn.sh","path":"openvpn/nordvpn/configure-openvpn.sh","contentType":"file"}],"totalCount":1},"openvpn":{"items":[{"name":"anonine","path":"openvpn/anonin

Use --help for more information.

### HW/SW Environment

```markdown
- OS: DSM 7.2-64570
- Container Manager: 20.10.23-1413
```

**Comment by edgd1er** [comment]
As far as I know, OPENVPN_CONFIG_URL is not required for NORDVPN: https://haugene.github.io/docker-transmission-openvpn/provider-specific/

Could you point out where in the documentation it's mentioned ? it could be an error.

also, when migrating from an older version, transmission config moved, back in 2021:
https://github.com/haugene/docker-transmission-openvpn/commit/317a0a78adabb7aaff7c1a438dbdecce4cc3fe6f

downloaded files and config are in two different volumes now. You may wish to adapt to that change:
https://github.com/haugene/docker-transmission-openvpn/blob/445261aa4cfa81bc3c71e4f4d8607ba048d9c4bf/openvpn/start.sh#L25-L30

**Comment by domier** [comment]
Thanks for the feedback.  When I first noticed transmission had gone down I looked into the logs and found the below, so proceeded to set OPENVPN_CONFIG_URL.  (So, I did not see it in the docs)  I'm not entirely sure what happened, but it looks like at some point my Login/Pass, and even that I was using NORD was lost from the config.  It's been a long time since I'd touched it (hence not being up to date with the 2021 config move!) and in the meantime docker on synology transitioned to "Container Manager", Synology OS updated, Haugene Transmission updated... it could have been any number of things.

Log:

```
Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
TRANSMISSION_HOME is currently set to: /config/transmission-home
WARNING: Deprecated. Found old default transmission-home folder at /data/transmission-home, setting this as TRANSMISSION_HOME. This might break in future versions.
We will fallback to this directory as long as the folder exists. Please consider moving it to /config/transmission-home
Creating TUN device /dev/net/tun
ERROR: Cannot determine where to find your OpenVPN config. Both OPENVPN_CONFIG_URL and OPENVPN_PROVIDER is unset.
You have to either provide a URL to the config you want to use, or set a configured provider that will download one for you.
Exiting...
```

I've updated my settings:

```
CREATE_TUN_DEVICE | true
DROP_DEFAULT_ROUTE | **None**
ENABLE_UFW | false
GLOBAL_APPLY_PERMISSIONS | true
HEALTH_CHECK_HOST | google.com
LOG_TO_STDOUT | false
NORDVPN_CATEGORY | legacy_p2p
NORDVPN_COUNTRY | NL
NORDVPN_PROTOCOL | tcp
OPENVPN_OPTS | --inactive 3600 --ping 10 --ping-exit 60
OPENVPN_PASSWORD | (hidden)
OPENVPN_PROVIDER | NORDVPN
OPENVPN_USERNAME | (hidden)
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PEER_DNS | true
PEER_DNS_PIN_ROUTES | true
PGID | **None**
PUID | **None**
REVISION | b33d0fe4c938259a0d4eb844e55468f387456121
SELFHEAL | false
TRANSMISSION_DOWNLOAD_DIR | /data/completed
TRANSMISSION_HOME | /config/transmission-home
TRANSMISSION_INCOMPLETE_DIR | /data/incomplete
TRANSMISSION_RPC_PASSWORD | **None**
TRANSMISSION_RPC_PORT | 9091
TRANSMISSION_RPC_USERNAME | **None**
TRANSMISSION_WATCH_DIR | /data/watch
UFW_ALLOW_GW_NET | false
UFW_DISABLE_IPTABLES_REJECT | false
UFW_EXTRA_PORTS | **None**
WEBPROXY_ENABLED | false
WEBPROXY_PASSWORD | **None**
WEBPROXY_PORT | 8118
WEBPROXY_USERNAME | **None**
```

Now I'm getting an authentication failure.  I'm a bit confused about this one as well, at first I assumed I had entered the password into the settings incorrectly, but I tried it on the Nord GUI with no issues, and deleted and re-pasted a couple times just to make sure there were no typos.  

Logs:

```
2023-07-19 07:21:43 SIGTERM[soft,auth-failure] received, process exiting
2023-07-19 07:21:43 AUTH: Received control message: AUTH_FAILED
2023-07-19 07:21:43 SENT CONTROL [nl851.nordvpn.com]: 'PUSH_REQUEST' (status=1)
2023-07-19 07:21:37 SENT CONTROL [nl851.nordvpn.com]: 'PUSH_REQUEST' (status=1)
2023-07-19 07:21:36 [nl851.nordvpn.com] Peer Connection Initiated with [AF_INET]194.127.172.100:443
2023-07-19 07:21:36 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 4096 bit RSA, signature: RSA-SHA512
2023-07-19 07:21:36 VERIFY OK: depth=0, CN=nl851.nordvpn.com
2023-07-19 07:21:34 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2023-07-19 07:21:34 TCP_CLIENT link remote: [AF_INET]194.127.172.100:443
2023-07-19 07:21:36 VERIFY X509NAME OK: CN=nl851.nordvpn.com
2023-07-19 07:21:36 VERIFY EKU OK
2023-07-19 07:21:36 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2023-07-19 07:21:36 Validating certificate extended key usage
2023-07-19 07:21:36 VERIFY OK: depth=1, O=NordVPN, CN=NordVPN CA8
2023-07-19 07:21:36 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
2023-07-19 07:21:35 TLS: Initial packet from [AF_INET]194.127.172.100:443, sid=d1b577d6 0b551ecc
2023-07-19 07:21:36 VERIFY KU OK
2023-07-19 07:21:34 TCP_CLIENT link local: (not bound)
2023-07-19 07:21:34 TCP connection established with [AF_INET]194.127.172.100:443
2023-07-19 07:21:34 TCP/UDP: Preserving recently used remote address: [AF_INET]194.127.172.100:443
2023-07-19 07:21:34 Socket Buffers: R=[87380->87380] S=[16384->16384]
2023-07-19 07:21:34 Attempting to establish TCP connection with [AF_INET]194.127.172.100:443 [nonblock]
2023-07-19 07:21:34 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2023-07-19 07:21:34 NOTE: --fast-io is disabled since we are not using UDP
2023-07-19 07:21:34 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-07-19 07:21:34 library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
2023-07-19 07:21:34 OpenVPN 2.5.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 14 2022
Setting OpenVPN credentials...
Modification: Updating status for config failure detection
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Set output verbosity to 3
Modification: Change tls-crypt keyfile path
Modification: Update/set resolv-retry to 15 seconds
Modification: Change ping options
Modification: Change ca certificate path
Modification: Point auth-user-pass option to the username/password file
Modifying /etc/openvpn/nordvpn/nl851.nordvpn.com.ovpn for best behaviour in this container
Starting OpenVPN using config nl851.nordvpn.com.ovpn
OVPN: NORDVPN: selected: nl851.nordvpn.com, VPN_PROVIDER_HOME: /etc/openvpn/nordvpn
INFO: OVPN: Downloading config: nl851.nordvpn.com.ovpn
INFO: OVPN: Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/nl851.nordvpn.com.tcp.ovpn
Best server : nl851.nordvpn.com
INFO: OVPN: Best server : nl851.nordvpn.com, load: 4
INFO: OVPN:Searching for technology: openvpn_tcp
INFO: OVPN: Searching for country : NL (153)
INFO: OVPN: Searching for group: legacy_p2p
INFO: OVPN:Selecting the best server...
INFO: OVPN: Removing existing configs in /etc/openvpn/nordvpn
INFO: OVPN: ok, configurations download site reachable
Checking NORDPVN API responses
INFO: OVPN: DNS resolution ok
INFO: OVPN: Checking curl installation
/etc/openvpn/nordvpn/..
Executing setup script for NORDVPN
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Running with VPN_CONFIG_SOURCE auto
Using OpenVPN provider: NORDVPN
Creating TUN device /dev/net/tun
We will fallback to this directory as long as the folder exists. Please consider moving it to /config/transmission-home
WARNING: Deprecated. Found old default transmission-home folder at /data/transmission-home, setting this as TRANSMISSION_HOME. This might break in future versions.
TRANSMISSION_HOME is currently set to: /config/transmission-home
Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
```

**Comment by edgd1er** [comment]
user login + password is no more authorized with nordvpn: https://github.com/haugene/docker-transmission-openvpn/issues/2642
doc: https://haugene.github.io/docker-transmission-openvpn/provider-specific/

you can, also, define a token in nordaccount ,  then use it in the container: (set in USERNAME, PASSWORD='' )

**Comment by pkishino** [comment]
closing as this is due to user setup and outdated config..
