### ISSUE TITLE
update port from PIA

### ISSUE THREAD

**Issue by cloudy-brain** [haugene/docker-transmission-openvpn#267]
Hi Haugene,

Firstly, thank you and great work - love the container. 

Hitting a snag in the updatePort.sh script. It trips up and gives me the error 

'Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding'

I used the Netherlands config which should support forwarding - so I'm not quite sure how else I can troubleshoot this one. 

Thanks for your time.

**Comment by cloudy-brain** [comment]
I should add the default port 51413 is reporting as closed inside of transmission.

**Comment by cloudy-brain** [comment]
curl encountered an error looking up new port

**Comment by cloudy-brain** [comment]
So turns out my synology nas which is connected to PIA on the same network (but not running this container) was the problem. If I disconnect the synology nas VPN then it fixes my issue on this client which is running your container. Strange? - or expected?

**Comment by cloudy-brain** [comment]
I've no idea what the problem is but it's working now - sort of. I'm using the systemctl to manage the service and it appears that everytime I issue a restart, it sometimes finds a port with PIA and sometimes doesn't.

**Comment by haugene** [comment]
I've experienced the same with the new port API from PIA. I think it's the "already activated on this connection" part that is key here. Don't know if they see the IP you're connecting from and then decide that there's already a port set up for it? I think this is a PIA issue though, not something that can be fixed from this conainer?

**Comment by jtpavlock** [comment]
Having the same issue, except I'm using to docker-compose to manage and can't get it to find a new port at all. Always get's stuck at this point

**Comment by haugene** [comment]
Merged the pull request with an update to the script. Hopefully this solves the problem. Sorry for the delay.

Please re-open if the problem persists

**Comment by MartinAyla** [comment]
I have this exact problem every time I restart the container, I'm using the latest version.

I have to stop the container and wait for several minutes before starting it again, and then, sometimes, it starts working again?

**Comment by haugene** [comment]
This is a restriction put in place by PIA. If the container is restarted too often, PIA says that you already have a port and won't give you a new one until the old one expires. Or something like that. Not much we can do unless we want to persist the port on the host between container restarts which I think is too much hassle for little reward.

Open to other suggestions though.

**Comment by grostim** [comment]
I still have this issue at every start up of the container. 
Is there an update ?

I am using PIA Netherlands server which is supposed to support port forwarding .

**Comment by grostim** [comment]
OK, i switched to Germany, and now, this is working. So this is a server issue.

**Comment by haugene** [comment]
Yes. Servers are listed here: https://helpdesk.privateinternetaccess.com/hc/en-us/articles/219460187-How-do-I-enable-port-forwarding-on-my-VPN-

We should maybe switch the default config to one with port forwarding.

**Comment by timelf123** [comment]
Can we persist the port in the data dir? I run into this issue often

**Comment by OscarVanL** [comment]
I run into this issue still (although I'm intentionally using a PIA region that doesn't support port forwarding).

**Comment by loftwah** [comment]
> Yes. Servers are listed here: https://helpdesk.privateinternetaccess.com/hc/en-us/articles/219460187-How-do-I-enable-port-forwarding-on-my-VPN-
> 
> We should maybe switch the default config to one with port forwarding.

Was there anything useful here? The link is dead.

**Comment by loftwah** [comment]
> I still have this issue at every start up of the container.
> Is there an update ?
> 
> I am using PIA Netherlands server which is supposed to support port forwarding .







Using OpenVPN provider: PIA

Starting OpenVPN using config Netherlands.ovpn

Setting OPENVPN credentials...

adding route to local network 192.168.1.0/24 via 172.24.0.1 dev eth0

Sun Oct 4 20:43:01 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020

Sun Oct 4 20:43:01 2020 library versions: OpenSSL 1.1.1c 28 May 2019, LZO 2.10

Sun Oct 4 20:43:01 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts

Sun Oct 4 20:43:01 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]89.187.174.198:1198

Sun Oct 4 20:43:01 2020 UDP link local: (not bound)

Sun Oct 4 20:43:01 2020 UDP link remote: [AF_INET]89.187.174.198:1198

Sun Oct 4 20:43:02 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Sun Oct 4 20:43:03 2020 [6bf56c437422edf4fb3a359422926298] Peer Connection Initiated with [AF_INET]89.187.174.198:1198

Sun Oct 4 20:43:04 2020 TUN/TAP device tun0 opened

Sun Oct 4 20:43:04 2020 /sbin/ip link set dev tun0 up mtu 1500

Sun Oct 4 20:43:04 2020 /sbin/ip addr add dev tun0 local 10.55.12.10 peer 10.55.12.9

Sun Oct 4 20:43:04 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.55.12.10 10.55.12.9 init

Up script executed with tun0 1500 1558 10.55.12.10 10.55.12.9 init

Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.55.12.10

Generating transmission settings.json from env variables

sed'ing True to true

Enforcing ownership on transmission config directories

Applying permissions to transmission config directories

Setting owner for transmission paths to 1000:1000

Setting permission for files (644) and directories (755)

Setting permission for watch directory (775) and its files (664)


-------------------------------------

Transmission will run as

-------------------------------------

User name: abc

User uid: 1000

User gid: 1000

-------------------------------------


DROPPING DEFAULT ROUTE

STARTING TRANSMISSION

CONFIGURING PORT FORWARDING

Transmission startup script complete.

Wait for tunnel to be fully initialized and PIA is ready to give us a port

Sun Oct 4 20:43:04 2020 Initialization Sequence Completed

[2020-10-04 20:43:04.767] JSON parse failed in /data/transmission-home/settings.json at pos 2221: INVALID_NUMBER -- remaining text "02,

"upload-"

Generating new client id for PIA

Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding

curl encountered an error looking up new port: 7

Spewing, it must still be a luck thing.

**Comment by drewconner** [comment]
I'm still getting the same error: `curl encountered an error looking up new port: 7`

I'm able to get a port from the OS X client without issue on the same server. Is there any other solution other than cross your fingers and pray?
