### ISSUE TITLE
Hi all I am sort of new to docker I setup portainer (long time ago 2.9.1) in a synology nas and I am trying to deploy haugene/transmission-openvpn but I am getting some errors now

### ISSUE THREAD

**Issue by caladol1** [haugene/docker-transmission-openvpn#2677]
Hi all I am sort of new to docker I setup portainer in a synology nas and I am trying to deploy haugene/transmission-openvpn
it has been runing for quite some time, but now fails 

with the log error ->
2014-01-01 02:10:58 TLS: Initial packet from [AF_INET]172.94.87.4:80, sid=f454522d 3c1dea5b,
2014-01-01 02:10:58 VERIFY ERROR: depth=1, error=certificate is not yet valid: C=HK, ST=Central, L=HK, O=Secure-ServerCA, OU=IT, CN=Secure-ServerCA, name=Secure-ServerCA, emailAddress=mail@host.domain, serial=14472060699488478373,
2014-01-01 02:10:58 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed,
2014-01-01 02:10:58 TLS_ERROR: BIO read tls_read_plaintext error,
2014-01-01 02:10:58 TLS Error: TLS object -> incoming plaintext read error,
2014-01-01 02:10:58 TLS Error: TLS handshake failed,
2014-01-01 02:10:58 Fatal TLS error (check_tls_errors_co), restarting,
2014-01-01 02:10:58 SIGTERM[soft,tls-error] received, process exiting

I cant seem to get it to work anymore, anyone has any idea of what has changed?

my default.ovpn
```
client
dev tun
proto tcp
remote vlus-pa2-ovpn-tcp.dns2use.com 80
persist-key
persist-tun
ca /etc/openvpn/ivacy/ca.crt
tls-auth /etc/openvpn/ivacy/Wdc.key 1
cipher AES-256-CBC
comp-lzo
verb 1
mute 20
route-method exe
route-delay 2
route 0.0.0.0 0.0.0.0
float
auth-user-pass /etc/openvpn/ivacy/openvpn-credentials.txt
```

my composer code

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
         - '/volume2/docker/transmition/VPN/default.ovpn:/etc/openvpn/ivacy/default.ovpn'
         - '/volume2/docker/transmition/VPN/Wdc.key:/etc/openvpn/ivacy/Wdc.key'
         - '/volume2/docker/transmition/VPN/ca.crt:/etc/openvpn/ivacy/ca.crt'
         - '/volume2/docker/transmition/VPN/openvpn-credentials.txt:/etc/openvpn/ivacy/openvpn-credentials.txt'
         - '/volume2/docker/transmition/downloads:/data'
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=IVACY
            - OPENVPN_CONFIG=default
            - VPN_CONFIG_SOURCE=default
            - OPENVPN_USERNAME=xxx_user_xxx
            - OPENVPN_PASSWORD=xx_pass_xx
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.1.0/16
            - DNS=0.0.0.0,0.0.0.0
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
            - '9117:9117'
            - '7878:7878'
            - '8989:8989'
        image: haugene/transmission-openvpn

**Comment by ilike2burnthing** [comment]
Your container seems to think it's 2014 for some reason. Try adding the read-only volume map:

`/etc/localtime:/etc/localtime`

**Comment by edgd1er** [comment]
> Your container seems to think it's 2014 for some reason. Try adding the read-only volume map:
> 
> `/etc/localtime:/etc/localtime`

* as pointed out by ilike2burnthing, localtime is of
  `2014-01-01 02:10:58 VERIFY ERROR: depth=1, error=certificate is not yet valid:`
* config file should not be mounted as sed may need to modify the file, as per documentation: http://haugene.github.io/docker-transmission-openvpn/supported-providers/
`- '/volume2/docker/transmition/VPN/default.ovpn:/etc/openvpn/ivacy/default.ovpn'`

**Comment by pkishino** [comment]
Doesn’t properly follow issue template and is a duplicate
