### ISSUE TITLE
web forward

### ISSUE THREAD

**Issue by cake99** [haugene/docker-transmission-openvpn#27]
Hello, first of all I'm new to docker.  I was looking for something to run my transmission deamon and this seems perfect.  I have followed this guide and for some reason, I think I'm running into routing issues.  I've created the other container with nginx proxy rinning in it, but I get "409: conflict" when I try to access the transmission proxy.

Do I have to do something else to make it work?

Thanks in advance.

**Comment by haugene** [comment]
You should only need the transmission container plus nginx. Haven't encountered that problem before. Double check your configs, pull the images, restart docker daemon just in case?

If it still doesn't work I need more info. Like the command you use to run transmission container, mask your username and password. Also logs from the containers, nginx config and nginx run command.

**Comment by cake99** [comment]
thank you for your reply.
i removed all my containers, rebooted the host, then created both new containers with these commands:

docker run --privileged  -d \
              -v /data/docker/transmission/data:/data \
              -e "OPENVPN_PROVIDER=PIA" \
              -e "OPENVPN_CONFIG=CA Toronto" \
              -e "OPENVPN_USERNAME=x4676230" \
              -e "OPENVPN_PASSWORD=wNXeyrkopX" \
              -e "RESOLV_OVERRIDE=nameserver 209.222.18.222\nnameserver 209.222.18.218\n" \
              -p 9091:9091 \
              haugene/transmission-openvpn
docker run --privileged  -d \
              -v /data/docker/transmission/data:/data \
              -e "OPENVPN_PROVIDER=PIA" \
              -e "OPENVPN_CONFIG=xxx" \
              -e "OPENVPN_USERNAME=xxx" \
              -e "OPENVPN_PASSWORD=xxx" \
              -e "RESOLV_OVERRIDE=nameserver 209.222.18.222\nnameserver 209.222.18.218\n" \
              -p 9091:9091 \
              haugene/transmission-openvpn

docker run -d \
      -v /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro \
      -p 8080:8080 \
      nginx
Everyting is running,
Accessing the proxy gives me this:

409: Conflict

Your request had an invalid session-id header.

To fix this, follow these steps:

When reading a response, get its X-Transmission-Session-Id header and remember it
Add the updated header to your outgoing requests
When you get this 409 error message, resend your request with the updated header
This requirement has been added to help prevent CSRF attacks.

X-Transmission-Session-Id: wf63JvxDHFs8S6c36auSxxHoA3zQw1vsqkfAQ45Vztm6sVD2

Anything i can try?

**Comment by haugene** [comment]
Can you try this? https://trac.transmissionbt.com/ticket/4014
That is... Remember the trailing slash after your-host:8080/transmission/web so that it's /transmission/web/

If that doesn't work, please dump logs from containers and provide your nginx.conf

**Comment by cake99** [comment]
heyhey, that did the trick!!
Now it's playing time!

Thanks a lot!

**Comment by haugene** [comment]
Sweet. Np :)

**Comment by ipatch** [comment]
commenting on this, for future me 👴🏼,

i to, just ran into this "bug" and spent some time clicking through the documentation and saw no mention of adding a trailing slash on the below page.

https://haugene.github.io/docker-transmission-openvpn/faq/#the_container_runs_but_i_cant_access_the_web_ui

just thought i'd metion that, also saw no mentioin of,

```
invalid session-id header
```

hopefully a spider 🕷🕸 will pick up on this for others that run into this issue/bug
