### ISSUE TITLE
dev release build went latest tag on docker hub - No linux/amd64 and linux/arm/v7 builds for version 5.1.1

### ISSUE THREAD

**Issue by casaper** [haugene/docker-transmission-openvpn#2703]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

```sh
$ docker pull haugene/transmission-openvpn
5.1.1: Pulling from haugene/transmission-openvpn
no matching manifest for linux/amd64 in the manifest list entries
$ echo $CPUTYPE $ARCHFLAGS
x86_64 -arch x86_64
```

### Current Behavior

`docker pull haugene/transmission-openvp:latest` or just `docker pull haugene/transmission-openvp` tries to pull the development test image, which only has a linux/arm64 build on docker hub.

### Expected Behavior

To get the latest stable image with `haugene/transmission-openvp:latest` or just `haugene/transmission-openvp`.

### How have you tried to solve the problem?

- tried to pull it

```sh
$ docker pull haugene/transmission-openvpn
5.1.1: Pulling from haugene/transmission-openvpn
no matching manifest for linux/amd64 in the manifest list entries
$ echo $CPUTYPE $ARCHFLAGS
x86_64 -arch x86_64
```

Currently I try to make the current build manually for myself. This way I'll have my personal 

### Log output

```sh
$ docker pull haugene/transmission-openvpn:5.1.1
5.1.1: Pulling from haugene/transmission-openvpn
no matching manifest for linux/amd64 in the manifest list entries
$ echo $CPUTYPE $ARCHFLAGS
x86_64 -arch x86_64
```

### HW/SW Environment

```markdown
- OS: Linux minis 6.4.12-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Aug 24 17:37:05 UTC 2023 x86_64 GNU/Linux
- Docker: version 24.0.5, build ced0996600
```

### Anything else?

I presume the test dev release went not the way as it was intended?

**Comment by gregbert42** [comment]
Same issue, error here.
no matching manifest for linux/amd64 in the manifest list entries

**Comment by Twiistz** [comment]
Same issue here

**Comment by matthewsmithy** [comment]
Same here

**Comment by thetechwizard17** [comment]
Same here

**Comment by mdumois1** [comment]
Same.  I'm on linux mint (21.2).  I was able to pull pointing directly to 5.1.0 for now but obviously would prefer keyword latest or master for my docker compose file.  

sudo docker pull haugene/transmission-openvpn:**5.1.0**

X@X:~/Desktop$ sudo docker pull haugene/transmission-openvpn
Using default tag: latest
latest: Pulling from haugene/transmission-openvpn
no matching manifest for linux/amd64 in the manifest list entries
X@X:~/Desktop$ sudo docker pull haugene/transmission-openvpn:latest
latest: Pulling from haugene/transmission-openvpn
no matching manifest for linux/amd64 in the manifest list entries
X@X:~/Desktop$ sudo docker pull haugene/transmission-openvpn:master
master: Pulling from haugene/transmission-openvpn
no matching manifest for linux/amd64 in the manifest list entries
X@X:~/Desktop$ sudo docker pull haugene/transmission-openvpn:master
master: Pulling from haugene/transmission-openvpn
no matching manifest for linux/amd64 in the manifest list entries
X@X:~/Desktop$ sudo docker pull haugene/transmission-openvpn:5.1.0
5.1.0: Pulling from haugene/transmission-openvpn
b237fe92c417: Pull complete 
dba58ed47ad0: Pull complete 
d87f22d80fef: Pull complete 
73b0e547cc92: Pull complete 
7e00f8ad6fc1: Pull complete 
9049261e0f15: Pull complete 
f15f52b76873: Pull complete 
a45969ad954e: Pull complete 
67e3e99f2f14: Pull complete 
61eb914f538a: Pull complete 
098eedc4cfc3: Pull complete 
Digest: sha256:X
Status: Downloaded newer image for haugene/transmission-openvpn:5.1.0
docker.io/haugene/transmission-openvpn:5.1.0

**Comment by Mathieu-Coupe** [comment]
Looks like build failed for linux/amd64 (see https://github.com/haugene/docker-transmission-openvpn/actions/runs/6071206233/job/16468776091) :
```
Dockerfile:44
--------------------
  42 |           libssl-dev
  43 |     
  44 | >>> FROM ***/transmission-builder:4.0.4 as TransmissionBuilder
  45 |     
  46 |     FROM base
--------------------
ERROR: failed to solve: ***/transmission-builder:4.0.4: no match for platform in manifest sha256:4a9e0b0c1d03bad0d8918b80742d36c5329db2d75dc6bb6818fa7c490688c68f: not found
Error: buildx failed with: ERROR: failed to solve: ***/transmission-builder:4.0.4: no match for platform in manifest sha256:4a9e0b0c1d03bad0d8918b80742d36c5329db2d75dc6bb6818fa7c490688c68f: not found
```

**Comment by ksurl** [comment]
5.1.1 is a pre-release test version for the new image building workflow. no feature or version changes under the hood. we are still debugging the new build workflow. a good reason to stay off "latest" (thought it should have only done dev/edge?)

**Comment by Mathieu-Coupe** [comment]
Thanks for the explanation !
Having a dev / edge tag would be best as "latest" is expected to be working.
regards !
