### ISSUE TITLE
Add ProtonVPN provider

### ISSUE THREAD

**Issue by Zuescho** [haugene/docker-transmission-openvpn#271]
Just a quick question if anyone manage to get ProtonVPN
(https://protonvpn.com/pricing) working.

**Comment by Forage** [comment]
ProtonVPN works like a charm. The only thing it takes is RTFM, followed by:

Replacing
```
auth-user-pass
```
With
```
auth-user-pass /config/openvpn-credentials.txt
```

And deleting the two following lines
```
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```

This in any of the ovpn config files you use from ProtonVPN.

Even though they have quite a load of configs for the different end-points available, these minor requirements should make them easy to integrate into the project as well.

**Comment by haugene** [comment]
If someone provides a link to the .ovpn files for ProtonVPN we could bundle it in the image as well.

**Comment by Forage** [comment]
Below are all the free and Basic account configs. It lacks all the Secure Core server configs, for which you need a Plus or Visionary account. Do note that there is only a select number of configs that can be used by the free accounts. 

No file names nor content has been changed.
The configs for the free accounts contain "free" in their file name.
The only changes between the TCP and UDP versions of each config are, well, the `proto` setting and `remote` port number.

[ProtonVPN_country_configs_TCP.zip](https://github.com/haugene/docker-transmission-openvpn/files/1491229/ProtonVPN_country_configs_TCP.zip)
[ProtonVPN_country_configs_UDP.zip](https://github.com/haugene/docker-transmission-openvpn/files/1491230/ProtonVPN_country_configs_UDP.zip)
[ProtonVPN_server_configs_TCP.zip](https://github.com/haugene/docker-transmission-openvpn/files/1491231/ProtonVPN_server_configs_TCP.zip)
[ProtonVPN_server_configs_UDP.zip](https://github.com/haugene/docker-transmission-openvpn/files/1491232/ProtonVPN_server_configs_UDP.zip)

**Comment by Forage** [comment]
On a side note. I can't help but thinking: Though convenient to have VPN profiles included by default, it is quite funny that people actually use them. If privacy and security is such a concern, one should not use/trust profiles provided by third-parties ;)

In any case, feel free to verify the profiles I provided by downloading them yourself. You'd need an account, but ProtonVPN is worth the money.

**Comment by haugene** [comment]
Thanks for providing the configs, changed this issue to be directed towards adding ProtonVPN.

Regarding your side note, I both agree and disagree. Too many probably just uses and trusts them blindly, which could be a security concern. But as this project is open source and it's set up as an automated build on Docker hub so it's built from the source, everyone are able to (and probably should) inspect the configuration they're using. They can also inspect the files in the container.

So. Yes. It is a concern, but those who want can verify the configs used to make sure they're in the clear :)

**Comment by haugene** [comment]
Follow up in #378

**Comment by haugene** [comment]
#704 now merged
