### ISSUE TITLE
crash on startup due to git index.lock

### ISSUE THREAD

**Issue by hyyyjinx** [haugene/docker-transmission-openvpn#2715]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

/usr/bin/docker run \
			--sysctl net.ipv6.conf.all.disable_ipv6=0 \
			--network docker-default-net \
			--name transmission-openvpn \
			--cap-add=NET_ADMIN \
			-e "OPENVPN_PROVIDER=MULLVAD" \
			-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
			-p 9091:9091 \
		haugene/transmission-openvpn:5.0.2

### Current Behavior

Using recent releases, transmission-openvpn crashes on boot. This was previously working. No config changes done. 

Log included below. Relevant lines:

```
 fatal: Unable to create '/config/vpn-configs-contrib/.git/index.lock': File exists.             
docker[130069]: Another git process seems to be running in this repository                 
```

I am using mullvad VPN config

### Expected Behavior

transmission-openvpn should boot up

### How have you tried to solve the problem?

Rolling back to 5.0.2 fixes this issue. Later versions seem to be affected

### Log output

 01:38:48 nibbler systemd[1]: Started transmission-openvpn.service.                                                                         
 01:38:48 nibbler docker[130069]: Starting container with revision: 48299204d160d2d699ce6dd5ccdfcba0ecf13c83                                
 01:38:48 nibbler docker[130069]: TRANSMISSION_HOME is currently set to: /config/transmission-home                                          
 01:38:48 nibbler docker[130069]: Creating TUN device /dev/net/tun                                                                          
 01:38:48 nibbler docker[130069]: Using OpenVPN provider: MULLVAD                                                                           
 01:38:48 nibbler docker[130069]: Running with VPN_CONFIG_SOURCE auto                                                                       
 01:38:48 nibbler docker[130069]: No bundled config script found for MULLVAD. Defaulting to external config                                 
 01:38:48 nibbler docker[130069]: Will get configs from https://github.com/haugene/vpn-configs-contrib.git                                  
 01:38:48 nibbler docker[130069]: Repository is already cloned, checking for update                                                         
 01:38:49 nibbler docker[130069]: Already up to date.                                                                                       
 01:38:50 nibbler docker[130069]: fatal: Unable to create '/config/vpn-configs-contrib/.git/index.lock': File exists.                       
 01:38:50 nibbler docker[130069]: Another git process seems to be running in this repository, e.g.                                          
 01:38:50 nibbler docker[130069]: an editor opened by 'git commit'. Please make sure all processes                                          
 01:38:50 nibbler docker[130069]: are terminated then try again. If it still fails, a git process                                           
 01:38:50 nibbler docker[130069]: may have crashed in this repository earlier:                                                              
 01:38:50 nibbler docker[130069]: remove the file manually to continue.                                                                     
 01:38:50 nibbler systemd[1]: transmission-openvpn.service: Main process exited, code=exited, status=128/n/a                                
 01:38:50 nibbler systemd[1]: transmission-openvpn.service: Failed with result 'exit-code'.        

### HW/SW Environment

```markdown
- OS: Ubuntu 22.04
- Docker version 24.0.6, build ed223bc
```

**Comment by pkishino** [comment]
I can’t see your bind mounts for config and data..
Anyway, if you check the logs it tells you the problem ```01:38:48 nibbler docker[130069]: Repository is already cloned, checking for update
01:38:49 nibbler docker[130069]: Already up to date.
01:38:50 nibbler docker[130069]: fatal: Unable to create '/config/vpn-configs-contrib/.git/index.lock': File exists.
01:38:50 nibbler docker[130069]: Another git process seems to be running in this repository, e.g.
01:38:50 nibbler docker[130069]: an editor opened by 'git commit'. Please make sure all processes
01:38:50 nibbler docker[130069]: are terminated then try again. If it still fails, a git process
01:38:50 nibbler docker[130069]: may have crashed in this repository earlier:
01:38:50 nibbler docker[130069]: remove the file manually to continue.
```
So it seems like the container crashed or didn’t properly pull the config previously so there is a leftover lock file.. delete this and you’ll be fine. This is a git issue and not really this containers fault
