### ISSUE TITLE
Container breaking my nfs share

### ISSUE THREAD

**Issue by dorian33160** [haugene/docker-transmission-openvpn#2724]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/mnt/droplet/downloads/:/data'
            - '/docker/transmission/config/:/config'
        environment:
            - OPENVPN_PROVIDER=NORDVPN
            - OPENVPN_CONFIG=france
            - OPENVPN_USERNAME=***********************
            - OPENVPN_PASSWORD=***********************
            - LOCAL_NETWORK=10.0.0.0/24
            - NORDVPN_COUNTRY=CH
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

### Current Behavior

Before, you must know that downloads are placed in a NFS share (/mnt/droplet). Since the last image pull, everything was working perfectly. After deploying the stack with the new image, everything actually work. But when I add a torrent to download after a few minutes, I can't access to the web admin anymore and it breaks my nfs share !

ls: reading directory '.': Input/output error

I can't find where the problem is. I don't think it comes from the NFS, but I can't be sure. Furthermore, I let you logs of the transmission container in case you need it.
[transmission-log.txt](https://github.com/haugene/docker-transmission-openvpn/files/12677941/transmission-log.txt)

### Expected Behavior

Transmission downloads torrents in the nfs share without breaking my nfs share.

### How have you tried to solve the problem?

1) I verified everything about my nfs config
2) I tried with a SFTP share -> same problem

### Log output

[transmission-log.txt](https://github.com/haugene/docker-transmission-openvpn/files/12677966/transmission-log.txt)

### HW/SW Environment

```markdown
- OS: Ubuntu 22.04
- Docker: 24.0.6
```

**Comment by pkishino** [comment]
test this by reverting to the previous working image.. if it works there, there might be something related to the newer version, but I doubt this is a container issue, more likely you should check with docker issues instead.
You also have not mentioned what version was working and which doesn't

**Comment by dorian33160** [comment]
I agree with you, but the problem is that my radarr / sonarr containers are also pointing on the nfs share and it works fine. I'll take a look to the docker version side.

I use latest image, so I can't tell which image was working… I'll try with a very old image to see if there is a difference.

Also, to repair my nfs share, I must reload the nfs-kernel-server service because reboot doesn't do anything.

I'll keep you informed.

Thanks for your reply.

**Comment by pkishino** [comment]
In most cases you shouldn’t use :latest.. especially for reasons like this.
Always use tagged releases..

**Comment by dorian33160** [comment]
I can tell that it doesn't come from the container itself because I tried with the 5.0.0 version, and it didn't work either. I'll take a look to the docker engine version or with another type of share, life sshfs.

Thanks for your replies, I close the subject.

**Comment by pkishino** [comment]
If you dip find something, feel free to please share here, might be useful for someone :)

**Comment by dorian33160** [comment]
I solved it I think !

I changed nfs with sshfs et set r + w permissions to everyone on the device that is sharing the folder. I still have to see if I can secure a bit more. With only “allow_other” option when I mount the share doesn't work.

Apparently, sshfs is more reliable as transmission stoped breaking the share itself even without good permissions.
