### ISSUE TITLE
openvpn/privado loop

### ISSUE THREAD

**Issue by Xsatc77** [haugene/docker-transmission-openvpn#2727]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/mnt/downloads:/data'
            - '/opt/transmission/config:/config'
        sysctls:
            - "net.ipv6.conf.all.disable_ipv6=0"    
        environment:
            - OPENVPN_PROVIDER=HIDEME
            - OPENVPN_CONFIG=UK
            - OPENVPN_USERNAME=************
            - OPENVPN_PASSWORD=************
            - LOCAL_NETWORK=192.168.1.0/24
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

### Current Behavior

I am not using Privado, I am using Hide.me.  Upon start, the container starts and shows port in list.  The port disappears once the container goes from starting to running status.  I check the log and I get a loop then it aborts as seen in the logfile attached below.

### Expected Behavior

All functions load and are accessible and transmission connected behind Hide.me VPN

### How have you tried to solve the problem?

Restarted container
Stopped & restarted VPN
Rebooted machine where container is housed

### Log output

[_transmission-openvpn-transmission-openvpn-1_logs.txt](https://github.com/haugene/docker-transmission-openvpn/files/12726990/_transmission-openvpn-transmission-openvpn-1_logs.txt)

### HW/SW Environment

```markdown
- OS:Unbuntu 22.04.2
- Docker:24.0.5, build ced0996
```

**Comment by pkishino** [comment]
Delete container and recreate..

**Comment by Xsatc77** [comment]
That put me in the same state... still on the loop of a VPN i dont even use

**Comment by pkishino** [comment]
If you deleted the container completely it wouldn’t have a git cache of
downloaded profiles..

**Comment by Aniel** [comment]
@Xsatc77 if you delete the config from the opt/transmission/config directory the configuration gets freshly cloned and the issue disapears :)
You have mapped the config as volume and therfore just recreating the container does not work.

**Comment by pkishino** [comment]
Exactly, the clones repo is stored in config so check that the git clone
deleted
