### ISSUE TITLE
proxy is not working

### ISSUE THREAD

**Issue by GiChiken** [haugene/docker-transmission-openvpn#2729]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

version: '3.7'
services:
    transmission-openvpn:
        volumes:
            - /Torrents:/data
        environment:
            - OPENVPN_PROVIDER=SURFSHARK
            - OPENVPN_CONFIG=jp-tok.prod.surfshark.com_udp
            - OPENVPN_USERNAME=???????
            - OPENVPN_PASSWORD=???????
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - PUID=1000
            - PGID=1000
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.0.0/24
            - TRANSMISSION_PORT_FORWARDING_ENABLED=true
            - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
            - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
            - TRANSMISSION_SPEED_LIMIT_UP=0

        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        image: haugene/transmission-openvpn:latest
    proxy:
        image: haugene/transmission-openvpn-proxy
        links:
            - transmission-openvpn
        ports:
            - 8080:8080
        volumes:
            - /Torrents:/data

### Current Behavior

I realized that I need to use a proxy to access the Web UI from outside the VPN, but the proxy is not working. I have attached the log of proxy docker below.

### Expected Behavior

Allowing access from the outside while using a VPN

### How have you tried to solve the problem?

re install

### Log output

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/09/28 13:47:31 [emerg] 1#1: host not found in upstream "transmission" in /etc/nginx/nginx.conf:14
nginx: [emerg] host not found in upstream "transmission" in /etc/nginx/nginx.conf:14

      

### HW/SW Environment

```markdown
- OS:rasbian lite
- Docker:portainer
```

**Comment by pkishino** [comment]
this is a problem with your config..NOT a container issue..this should be in the discussion area..
anyway, if you had read the logs it would tell you your problem
**2023/09/28 13:47:31 [emerg] 1#1: host not found in upstream "transmission" in /etc/nginx/nginx.conf:14
nginx: [emerg] host not found in upstream "transmission" in /etc/nginx/nginx.conf:14

**

you haven't setup the proxy correctly

**Comment by pkishino** [comment]
http://haugene.github.io/docker-transmission-openvpn/
