### ISSUE TITLE
Transmission crash

### ISSUE THREAD

**Issue by casaoui86** [haugene/docker-transmission-openvpn#2733]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

sudo docker run --name="TO-NordVPN" --privileged -d \
	-v /volume1/docker/TO-NordVPN/custom:/data \
	-v /etc/localtime:/etc/localtime:ro \
	-v /volume1/docker/TO-NordVPN/resolv.conf:/etc/resolv.conf:ro \
        -e OPENVPN_PROVIDER=NORDVPN \
	-e OPENVPN_USERNAME=Username \
	-e OPENVPN_PASSWORD="Password" \
	-e NORDVPN_CATEGORY=legacy_p2p \
	-e NORDVPN_COUNTRY=ca \
	-e NORDVPN_PROTOCOL=tcp \
	-p 9091:9091 \
	-p 8888:8888 \
	haugene/transmission-openvpn

### Current Behavior

The container crash everytime, 

Here is the logs : 

WARNING: initial DNS resolution test failed                                                                               
Creating TUN device /dev/net/tun                                                                                          
Using OpenVPN provider: NORDVPN                                                                                           
Running with VPN_CONFIG_SOURCE auto                                                                                       
Provider NORDVPN has a bundled setup script. Defaulting to internal config                                                
Executing setup script for NORDVPN                                                                                        
/etc/openvpn/nordvpn/..                                                                                                   

### Expected Behavior

Be able to connecter to transmission

### How have you tried to solve the problem?

I use Docker on synology
And already tested the logins work fine on my computer 
Tired differente script : 
sudo docker run --name="TO-NordVPN" --privileged -d \
	-v /volume1/docker/TO-NordVPN/custom:/data \
	-v /etc/localtime:/etc/localtime:ro \
	-v /volume1/docker/TO-NordVPN/resolv.conf:/etc/resolv.conf:ro \
	-e CREATE_TUN_DEVICE=true \
        -e OPENVPN_PROVIDER=NORDVPN \
	-e OPENVPN_USERNAME=Login\
	-e OPENVPN_PASSWORD="Password" \
	-e NORDVPN_CATEGORY=legacy_p2p \
	-e NORDVPN_COUNTRY=ca \
	-e NORDVPN_PROTOCOL=udp \
	-e WEBPROXY_ENABLED=false \
	-e LOCAL_NETWORK=192.168.1.0/24 \
	-e OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60" \
	-e TRANSMISSION_WEB_UI=transmission-web-control \
	-e TZ=Canada/Eastern \
	-e PUID=1033 \
	-e PGID=100 \
	-p 9091:9091 \
	-p 8888:8888 \
	--log-driver json-file \
	--log-opt max-size=10m \
	--sysctl net.ipv6.conf.all.disable_ipv6=0 \
	--dns 8.8.8.8 \
	--cap-add=NET_ADMIN \
	--device=/dev/net/tun \
	haugene/transmission-openvpn

resolv.conf ==> 8.8.8.8

### Log output

WARNING: initial DNS resolution test failed                                                                               
Creating TUN device /dev/net/tun                                                                                          
Using OpenVPN provider: NORDVPN                                                                                           
Running with VPN_CONFIG_SOURCE auto                                                                                       
Provider NORDVPN has a bundled setup script. Defaulting to internal config                                                
Executing setup script for NORDVPN                                                                                        
/etc/openvpn/nordvpn/..                                                                                                   

### HW/SW Environment

```markdown
- OS: Synology DSM 7.1.1
- Docker: 20.10.3
```

**Comment by pkishino** [comment]
Please look through the wiki and other issues, you submit an incomplete log and not very detailed description,
If you need help, open a discussion..

**Comment by edgd1er** [comment]
resolving the dns problem would be a good start.
Not a transmission nor a openvpn/nordvpn problem though.
