### ISSUE TITLE
downloads.nordcdn.com giving 502 Bad Gateway

### ISSUE THREAD

**Issue by utdrmac** [haugene/docker-transmission-openvpn#2734]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

docker run --cap-add=NET_ADMIN -d --name transmission -v /opt/media/transmission:/data -v /opt/media/transmission/config:/config -e OPENVPN_PROVIDER=NORDVPN -e NORDVPN_COUNTRY=CA -e NORDVPN_CATEGORY=legacy_p2p -e NORDVPN_PROTOCOL=tcp -e OPENVPN_USERNAME=XX -e OPENVPN_PASSWORD=XX -e TRANSMISSION_DOWNLOAD_DIR=/data/Downloads -e TRANSMISSION_INCOMPLETE_DIR=/data/Incomplete -e TRANSMISSION_RPC_PORT=8181 -e TRANSMISSION_HOME=/config -e TRANSMISSION_LOG_LEVEL=info -e LOCAL_NETWORK=10.10.10.0/24,172.16.1.0/24 -p 8181:8181 haugene/transmission-openvpn

### Current Behavior

https://downloads.nordcdn.com/ is reporting 502 Bad Gateway, even from my own browser. I know this is a Nord issue, however, I feel that this container and the scripts should be able to gracefully handle this situation by automatically falling back to a previously downloaded config file.

### Expected Behavior

Expected that scripts gracefully fail back to a previously downloaded config file, and/or use a backup method for retrieving the server configs. 

### How have you tried to solve the problem?

1) docker pull :latest to ensure no recent fixes.
2) Confirmed the issue is with nordvpn's domain

### Log output

```
$ docker start transmission
transmission
$ docker logs -f transmission
Starting container with revision: 81277fb6f8ae6aeb57f913172d4d45c7af8c0b31
TRANSMISSION_HOME is currently set to: /config
WARNING: TRANSMISSION_HOME is not set to the default /config/transmission-home, this is not recommended.
TRANSMISSION_HOME should be set to /config/transmission-home OR another custom directory on /config/<directory>
If you would like to migrate your existing TRANSMISSION_HOME, please stop the container, add volume /config and move the transmission-home directory there.
Creating TUN device /dev/net/tun
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN
/etc/openvpn/nordvpn/..
-rw-r--r-- 1 root root 15273 Oct  5 02:24 /tmp/json_countries
-rw-r--r-- 1 root root 5294 Oct  5 02:24 /tmp/json_groups
-rw-r--r-- 1 root root 3758 Oct  5 02:24 /tmp/json_technologies
INFO: OVPN: Checking curl installation
INFO: OVPN: DNS resolution ok
ERROR: ERROR: OVPN: cannot ping https://downloads.nordcdn.com/configs/files, network or internet unavailable. Cannot download NORDVPN configuration files
```

### HW/SW Environment

```markdown
- OS:
- Docker:
```

**Comment by ilike2burnthing** [comment]
https://downloads.nordcdn.com/configs/files purposefully cannot be accessed in a browser and returns a 502 error. That's not what is being seen here for the container.

Resolve the warning in your log while you wait for some more help.

**Comment by edgd1er** [comment]
* the logs stated that the website cannot be pinged, is not online, there is no way to force the website to be online. 
At the moment, in my zone, the website can be pinged.
```
PING downloads.nordcdn.com (104.17.207.237) 56(84) bytes of data.
64 bytes from 104.17.207.237 (104.17.207.237): icmp_seq=1 ttl=57 time=8.73 ms
64 bytes from 104.17.207.237 (104.17.207.237): icmp_seq=2 ttl=57 time=8.05 ms
```
* Should you wish to use a specific config file, please feel free to seek information in the doc: [Using a local single .ovpn file from a provider](https://haugene.github.io/docker-transmission-openvpn/supported-providers/)

* the risk of using a openvpn config file sitting somewhere in the directory are to important:
    * possible wrong country, technology, ....
    * possible account locking due to too many retry.
    * use of an overloaded server
    * not a nordvpn provider config file.

**Comment by pkishino** [comment]
Answered above, thanks
