### ISSUE TITLE
Container fails to start

### ISSUE THREAD

**Issue by wickedyoda** [haugene/docker-transmission-openvpn#2738]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn:latest
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 192.168.100.2
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/traver/nasmedia/torrantdownloads:/data
    - /home/traver/docker/transmission-openvpnclient/openvpn/custom/:/etc/openvpn/custom/
    - /home/traver/docker/transmission-openvpnclient/config:/config

  environment:
    - OPENVPN_PROVIDER=MULLVAD
    - OPENVPN_CONFIG=default
    - OPENVPN_USERNAME=*********
    - OPENVPN_PASSWORD=m
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.100.0/24
  sysctls:
    - "net.ipv6.conf.all.disable_ipv6=0"

 proxy:
  image: haugene/transmission-openvpn-proxy:latest
  links:
    - transmission
  ports:
    - 8089:8080
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/traver/docker/transmission-openvpnclient/openvpn/custom/:/etc/openvpn/custom/
    - /home/traver/docker/transmission-openvpnclient/config:/config

 rss:
  image: haugene/transmission-rss:latest
  links:
    - transmission
  environment:
    - RSS_URL=http://.../xxxxx.rss

### Current Behavior

Aborting
Updating 3e77ce88f..a189d8f55
Starting container with revision: 81277fb6f8ae6aeb57f913172d4d45c7af8c0b31
TRANSMISSION_HOME is currently set to: /config/transmission-home
WARNING: Deprecated. Found old default transmission-home folder at /data/transmission-home, setting this as TRANSMISSION_HOME. This might break in future versions.
We will fallback to this directory as long as the folder exists. Please consider moving it to /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: MULLVAD
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for MULLVAD. Defaulting to external config
Will get configs from https://github.com/haugene/vpn-configs-contrib.git
Repository is already cloned, checking for update
error: Your local changes to the following files would be overwritten by merge:
	openvpn/mullvad/ae_all.ovpn
	openvpn/mullvad/ae_dxb.ovpn
	openvpn/mullvad/al_all.ovpn
	openvpn/mullvad/al_tia.ovpn
	openvpn/mullvad/at_all.ovpn
	openvpn/mullvad/at_vie.ovpn
	openvpn/mullvad/au_adl.ovpn
	openvpn/mullvad/au_all.ovpn
	openvpn/mullvad/au_bne.ovpn
	openvpn/mullvad/au_mel.ovpn
	openvpn/mullvad/au_per.ovpn
	openvpn/mullvad/au_syd.ovpn
	openvpn/mullvad/be_all.ovpn
	openvpn/mullvad/be_bru.ovpn
	openvpn/mullvad/bg_all.ovpn
	openvpn/mullvad/bg_sof.ovpn
	openvpn/mullvad/br_all.ovpn
	openvpn/mullvad/br_sao.ovpn
	openvpn/mullvad/ca_all.ovpn
	openvpn/mullvad/ca_mtr.ovpn
	openvpn/mullvad/ca_tor.ovpn
	openvpn/mullvad/ca_van.ovpn
	openvpn/mullvad/ch_all.ovpn
	openvpn/mullvad/ch_zrh.ovpn
	openvpn/mullvad/cz_all.ovpn
	openvpn/mullvad/cz_prg.ovpn
	openvpn/mullvad/de_all.ovpn
	openvpn/mullvad/de_fra.ovpn
	openvpn/mullvad/default.ovpn
	openvpn/mullvad/dk_all.ovpn
	openvpn/mullvad/dk_cph.ovpn
	openvpn/mullvad/es_all.ovpn
	openvpn/mullvad/es_mad.ovpn
	openvpn/mullvad/fi_all.ovpn
	openvpn/mullvad/fi_hel.ovpn
	openvpn/mullvad/fr_all.ovpn
	openvpn/mullvad/fr_par.ovpn
	openvpn/mullvad/gb_all.ovpn
	openvpn/mullvad/gb_lon.ovpn
	openvpn/mullvad/gb_mnc.ovpn
	openvpn/mullvad/gr_all.ovpn
	openvpn/mullvad/gr_ath.ovpn
	openvpn/mullvad/hk_all.ovpn
	openvpn/mullvad/hk_hkg.ovpn
	openvpn/mullvad/hu_all.ovpn
	openvpn/mullvad/hu_bud.ovpn
	openvpn/mullvad/ie_all.ovpn
	openvpn/mullvad/ie_dub.ovpn
	openvpn/mullvad/it_all.ovpn
	openvpn/mullvad/it_mil.ovpn
	openvpn/mullvad/jp_all.ovpn
	openvpn/mullvad/jp_tyo.ovpn
	openvpn/mullvad/lu_all.ovpn
	openvpn/mullvad/lu_lux.ovpn
	openvpn/mullvad/lv_all.ovpn
	openvpn/mullvad/lv_rix.ovpn
	openvpn/mullvad/md_all.ovpn
	openvpn/mullvad/md_kiv.ovpn
	openvpn/mullvad/nl_all.ovpn
	openvpn/mullvad/nl_ams.ovpn
	openvpn/mullvad/no_all.ovpn
	openvpn/mullvad/no_osl.ovpn
	openvpn/mullvad/no_svg.ovpn
	openvpn/mullvad/nz_akl.ovpn
	openvpn/mullvad/nz_all.ovpn
	openvpn/mullvad/pl_all.ovpn
	openvpn/mullvad/pl_waw.ovpn
	openvpn/mullvad/ro_all.ovpn
	openvpn/mullvad/ro_buh.ovpn
	openvpn/mullvad/rs_all.ovpn
	openvpn/mullvad/rs_beg.ovpn
	openvpn/mullvad/se_all.ovpn
	openvpn/mullvad/se_got.ovpn
	openvpn/mullvad/se_mma.ovpn
	openvpn/mullvad/se_sto.ovpn
	openvpn/mullvad/sg_all.ovpn
	openvpn/mullvad/sg_sin.ovpn
	openvpn/mullvad/us_all.ovpn
	openvpn/mullvad/us_atl.ovpn
	openvpn/mullvad/us_chi.ovpn
	openvpn/mullvad/us_dal.ovpn
	openvpn/mullvad/us_den.ovpn
	openvpn/mullvad/us_lax.ovpn
	openvpn/mullvad/us_mia.ovpn
	openvpn/mullvad/us_nyc.ovpn
	openvpn/mullvad/us_phx.ovpn
	openvpn/mullvad/us_qas.ovpn
	openvpn/mullvad/us_rag.ovpn
	openvpn/mullvad/us_sea.ovpn
	openvpn/mullvad/us_sjc.ovpn
	openvpn/mullvad/us_slc.ovpn
	openvpn/vpnunlimited/ae.ovpn
	openvpn/vpnunlimited/ar.ovpn
	openvpn/vpnunlimited/at.ovpn
	openvpn/vpnunlimited/au-syd.ovpn
	openvpn/vpnunlimited/ba.ovpn
	openvpn/vpnunlimited/be.ovpn
	openvpn/vpnunlimited/bg.ovpn
	openvpn/vpnunlimited/br.ovpn
	openvpn/vpnunlimited/by.ovpn
	openvpn/vpnunlimited/ca-tr.ovpn
	openvpn/vpnunlimited/ca-vn.ovpn
	openvpn/vpnunlimited/ca.ovpn
	openvpn/vpnunlimited/ch.ovpn
	openvpn/vpnunlimited/cl.ovpn
	openvpn/vpnunlimited/cr.ovpn
	openvpn/vpnunlimited/cy.ovpn
	openvpn/vpnunlimited/cz.ovpn
	openvpn/vpnunlimited/de.ovpn
	openvpn/vpnunlimited/dk.ovpn
	openvpn/vpnunlimited/ee.ovpn
	openvpn/vpnunlimited/es.ovpn
	openvpn/vpnunlimited/fi.ovpn
	openvpn/vpnunlimited/fr-rbx.ovpn
	openvpn/vpnunlimited/fr.ovpn
	openvpn/vpnunlimited/gr.ovpn
	openvpn/vpnunlimited/hr.ovpn
	openvpn/vpnunlimited/hu.ovpn
	openvpn/vpnunlimited/ie-dub.ovpn
	openvpn/vpnunlimited/il.ovpn
	openvpn/vpnunlimited/im.ovpn
	openvpn/vpnunlimited/in-ka.ovpn
	openvpn/vpnunlimited/in.ovpn
	openvpn/vpnunlimited/is.ovpn
	openvpn/vpnunlimited/it-mil.ovpn
	openvpn/vpnunlimited/jp.ovpn
	openvpn/vpnunlimited/kr.ovpn
	openvpn/vpnunlimited/lt.ovpn
	openvpn/vpnunlimited/lux.ovpn
	openvpn/vpnunlimited/lv.ovpn
	openvpn/vpnunlimited/ly.ovpn
	openvpn/vpnunlimited/md.ovpn
	openvpn/vpnunlimited/mx.ovpn
	openvpn/vpnunlimited/mys.ovpn
	openvpn/vpnunlimited/nl.ovpn
	openvpn/vpnunlimited/no.ovp
Updating 3e77ce88f..a189d8f55
Aborting

### Expected Behavior

Container to not constantly reboot and run correctly.

### How have you tried to solve the problem?

Removing container, pulling latest and rebuilding from docker-compose

### Log output

Aborting
Updating 3e77ce88f..a189d8f55
Starting container with revision: 81277fb6f8ae6aeb57f913172d4d45c7af8c0b31
TRANSMISSION_HOME is currently set to: /config/transmission-home
WARNING: Deprecated. Found old default transmission-home folder at /data/transmission-home, setting this as TRANSMISSION_HOME. This might break in future versions.
We will fallback to this directory as long as the folder exists. Please consider moving it to /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: MULLVAD
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for MULLVAD. Defaulting to external config
Will get configs from https://github.com/haugene/vpn-configs-contrib.git
Repository is already cloned, checking for update
error: Your local changes to the following files would be overwritten by merge:
	openvpn/mullvad/ae_all.ovpn
	openvpn/mullvad/ae_dxb.ovpn
	openvpn/mullvad/al_all.ovpn
	openvpn/mullvad/al_tia.ovpn
	openvpn/mullvad/at_all.ovpn
	openvpn/mullvad/at_vie.ovpn
	openvpn/mullvad/au_adl.ovpn
	openvpn/mullvad/au_all.ovpn
	openvpn/mullvad/au_bne.ovpn
	openvpn/mullvad/au_mel.ovpn
	openvpn/mullvad/au_per.ovpn
	openvpn/mullvad/au_syd.ovpn
	openvpn/mullvad/be_all.ovpn
	openvpn/mullvad/be_bru.ovpn
	openvpn/mullvad/bg_all.ovpn
	openvpn/mullvad/bg_sof.ovpn
	openvpn/mullvad/br_all.ovpn
	openvpn/mullvad/br_sao.ovpn
	openvpn/mullvad/ca_all.ovpn
	openvpn/mullvad/ca_mtr.ovpn
	openvpn/mullvad/ca_tor.ovpn
	openvpn/mullvad/ca_van.ovpn
	openvpn/mullvad/ch_all.ovpn
	openvpn/mullvad/ch_zrh.ovpn
	openvpn/mullvad/cz_all.ovpn
	openvpn/mullvad/cz_prg.ovpn
	openvpn/mullvad/de_all.ovpn
	openvpn/mullvad/de_fra.ovpn
	openvpn/mullvad/default.ovpn
	openvpn/mullvad/dk_all.ovpn
	openvpn/mullvad/dk_cph.ovpn
	openvpn/mullvad/es_all.ovpn
	openvpn/mullvad/es_mad.ovpn
	openvpn/mullvad/fi_all.ovpn
	openvpn/mullvad/fi_hel.ovpn
	openvpn/mullvad/fr_all.ovpn
	openvpn/mullvad/fr_par.ovpn
	openvpn/mullvad/gb_all.ovpn
	openvpn/mullvad/gb_lon.ovpn
	openvpn/mullvad/gb_mnc.ovpn
	openvpn/mullvad/gr_all.ovpn
	openvpn/mullvad/gr_ath.ovpn
	openvpn/mullvad/hk_all.ovpn
	openvpn/mullvad/hk_hkg.ovpn
	openvpn/mullvad/hu_all.ovpn
	openvpn/mullvad/hu_bud.ovpn
	openvpn/mullvad/ie_all.ovpn
	openvpn/mullvad/ie_dub.ovpn
	openvpn/mullvad/it_all.ovpn
	openvpn/mullvad/it_mil.ovpn
	openvpn/mullvad/jp_all.ovpn
	openvpn/mullvad/jp_tyo.ovpn
	openvpn/mullvad/lu_all.ovpn
	openvpn/mullvad/lu_lux.ovpn
	openvpn/mullvad/lv_all.ovpn
	openvpn/mullvad/lv_rix.ovpn
	openvpn/mullvad/md_all.ovpn
	openvpn/mullvad/md_kiv.ovpn
	openvpn/mullvad/nl_all.ovpn
	openvpn/mullvad/nl_ams.ovpn
	openvpn/mullvad/no_all.ovpn
	openvpn/mullvad/no_osl.ovpn
	openvpn/mullvad/no_svg.ovpn
	openvpn/mullvad/nz_akl.ovpn
	openvpn/mullvad/nz_all.ovpn
	openvpn/mullvad/pl_all.ovpn
	openvpn/mullvad/pl_waw.ovpn
	openvpn/mullvad/ro_all.ovpn
	openvpn/mullvad/ro_buh.ovpn
	openvpn/mullvad/rs_all.ovpn
	openvpn/mullvad/rs_beg.ovpn
	openvpn/mullvad/se_all.ovpn
	openvpn/mullvad/se_got.ovpn
	openvpn/mullvad/se_mma.ovpn
	openvpn/mullvad/se_sto.ovpn
	openvpn/mullvad/sg_all.ovpn
	openvpn/mullvad/sg_sin.ovpn
	openvpn/mullvad/us_all.ovpn
	openvpn/mullvad/us_atl.ovpn
	openvpn/mullvad/us_chi.ovpn
	openvpn/mullvad/us_dal.ovpn
	openvpn/mullvad/us_den.ovpn
	openvpn/mullvad/us_lax.ovpn
	openvpn/mullvad/us_mia.ovpn
	openvpn/mullvad/us_nyc.ovpn
	openvpn/mullvad/us_phx.ovpn
	openvpn/mullvad/us_qas.ovpn
	openvpn/mullvad/us_rag.ovpn
	openvpn/mullvad/us_sea.ovpn
	openvpn/mullvad/us_sjc.ovpn
	openvpn/mullvad/us_slc.ovpn
	openvpn/vpnunlimited/ae.ovpn
	openvpn/vpnunlimited/ar.ovpn
	openvpn/vpnunlimited/at.ovpn
	openvpn/vpnunlimited/au-syd.ovpn
	openvpn/vpnunlimited/ba.ovpn
	openvpn/vpnunlimited/be.ovpn
	openvpn/vpnunlimited/bg.ovpn
	openvpn/vpnunlimited/br.ovpn
	openvpn/vpnunlimited/by.ovpn
	openvpn/vpnunlimited/ca-tr.ovpn
	openvpn/vpnunlimited/ca-vn.ovpn
	openvpn/vpnunlimited/ca.ovpn
	openvpn/vpnunlimited/ch.ovpn
	openvpn/vpnunlimited/cl.ovpn
	openvpn/vpnunlimited/cr.ovpn
	openvpn/vpnunlimited/cy.ovpn
	openvpn/vpnunlimited/cz.ovpn
	openvpn/vpnunlimited/de.ovpn
	openvpn/vpnunlimited/dk.ovpn
	openvpn/vpnunlimited/ee.ovpn
	openvpn/vpnunlimited/es.ovpn
	openvpn/vpnunlimited/fi.ovpn
	openvpn/vpnunlimited/fr-rbx.ovpn
	openvpn/vpnunlimited/fr.ovpn
	openvpn/vpnunlimited/gr.ovpn
	openvpn/vpnunlimited/hr.ovpn
	openvpn/vpnunlimited/hu.ovpn
	openvpn/vpnunlimited/ie-dub.ovpn
	openvpn/vpnunlimited/il.ovpn
	openvpn/vpnunlimited/im.ovpn
	openvpn/vpnunlimited/in-ka.ovpn
	openvpn/vpnunlimited/in.ovpn
	openvpn/vpnunlimited/is.ovpn
	openvpn/vpnunlimited/it-mil.ovpn
	openvpn/vpnunlimited/jp.ovpn
	openvpn/vpnunlimited/kr.ovpn
	openvpn/vpnunlimited/lt.ovpn
	openvpn/vpnunlimited/lux.ovpn
	openvpn/vpnunlimited/lv.ovpn
	openvpn/vpnunlimited/ly.ovpn
	openvpn/vpnunlimited/md.ovpn
	openvpn/vpnunlimited/mx.ovpn
	openvpn/vpnunlimited/mys.ovpn
	openvpn/vpnunlimited/nl.ovpn
	openvpn/vpnunlimited/no.ovp
Updating 3e77ce88f..a189d8f55
Aborting

### HW/SW Environment

```markdown
- OS:debian 12
- Docker:

Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:10 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:10 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by wickedyoda** [comment]
Same issue when using, dev branch

version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn:dev
  cap_add:

**Comment by edgd1er** [comment]
Hello,

I'm not a mullvad user so these a just a few hints to try separately.
the Git is aborting when updatin ghte directory because of the file already existing.
* Enable [DEBUG](https://haugene.github.io/docker-transmission-openvpn/config-options/#debugging) to confirm git pull is the cause
* test using an existing single ovpn file as per doc: https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_local_single_ovpn_file_from_a_provider
* empty the /etc/openvpn/mullvad dir
* Define a source type as zip: VPN_CONFIG_SOURCE_TYPE="github_zip"

**Comment by wickedyoda** [comment]
I will give those a try and update the ticket.
________________________________

**Comment by pkishino** [comment]
Please read the logs, you need to delete the config directory as new configs were pushed

**Comment by wickedyoda** [comment]
@pkishino Tried that this morning and didn't correct it; thanks for closing the issue without confirming it was fixed. 

The issue was resolved; I pushed my pihole to use nextdns upstream a few days ago. I found earlier that NextDNS was blocking the mullvad.net domain. I added it to the exception list and restarted the container; everything loaded and is running with no issues. 

Thanks for the help, @edgd1er and @pkishino

**Comment by Qhilm** [comment]
Just a comment for other finding this: in my case, deleting the `vpn-configs-contrib` folder fixes the issue. The entire folder will be redownloaded, but it works fine then. Some git file got corrupted maybe.

I had this issue twice already, in both cases I could fix it like this.

**Comment by kosmonot** [comment]
> Just a comment for other finding this: in my case, deleting the `vpn-configs-contrib` folder fixes the issue. The entire folder will be redownloaded, but it works fine then. Some git file got corrupted maybe.
> 
> I had this issue twice already, in both cases I could fix it like this.

This just worked for me too. What a great tip!

**Comment by MrYann** [comment]
I see this error is closed, but I have the same and I think the answer is not satisfying : one should be able to pull new image without errors.

Almost each pull there are conflicts with the vpn config files with I did not touch.

Do I have to remove the vpn config folder each time before a new pull ?
