### ISSUE TITLE
LOCAL_NETWORK multiple ranges for accesing ui from vpn and local network

### ISSUE THREAD

**Issue by sbe-arg** [haugene/docker-transmission-openvpn#2750]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

  transmission-openvpn:
    container_name: transmission
    image: docker.io/haugene/transmission-openvpn:latest
    ports:
      - 9091:9091/tcp
      - 8118:8118
    cap_add:
      - NET_ADMIN
    volumes:
      - /srv/.../downloads/transmission-docker/data:/data
      - /srv/.../docker-services-config/transmission-docker/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - OPENVPN_PROVIDER=
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - NORDVPN_COUNTRY=
      - NORDVPN_PROTOCOL=udp
      - NORDVPN_CATEGORY=asia_pacific
      - LOCAL_NETWORK=192.168.1.0/24
      - HEALTH_CHECK_HOST=1.1.1.1
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_RPC_USERNAME=admin
      - TRANSMISSION_RPC_PASSWORD=
      - TRANSMISSION_RPC_WHITELIST='127.0.0.1,192.168.1.*'
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_PORT=9091
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8118
    restart: unless-stopped

### Current Behavior

can only access the ui-api via 192.168.1.* sources

### Expected Behavior

accessing the ui-api via 192.168.1.* and another range such as 10.0.1.* from a vpn

### How have you tried to solve the problem?

nothing

### Log output

nothing unusual

### HW/SW Environment

```markdown
- OS: debian 12
- Docker: latest
```

### Anything else?

would be amazing to be able to input multiple ranges in the LOCAL_NETWORK var

**Comment by pkishino** [comment]
this is not an issue..this should be raised a discussion.
and yes..you can add multiple ranges in LOCAL_NETWORK as a comma separated list

**Comment by sbe-arg** [comment]
Tried adding multiple cidr ranges in the LOCAL_NETWORK var and it does not work. It also breaks the working cidr range.

**Comment by pkishino** [comment]
this has to do with different domains..
the LOCAL_NETWORK is handled by the container.. the TRANSMISSION_* variables are forwarded to transmission..
I think the documentation examples show this though.
at least you have it working, feel free to check the code and submit an improvement
