### ISSUE TITLE
Wrong config for upload speed

### ISSUE THREAD

**Issue by janschulz** [haugene/docker-transmission-openvpn#278]
It currently uses this:
```
    "upload-limit": {{ .Env.TRANSMISSION_UPLOAD_LIMIT }},
    "upload-limit-enabled": {{ .Env.TRANSMISSION_UPLOAD_LIMIT_ENABLED }},
```

But according to https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#bandwidth
it's
```
speed-limit-up: Number (KB/s, default = 100)
speed-limit-up-enabled: Boolean (default = false)
```

Funnily, the download speed seems to be named ok:

```
    "speed-limit-down": {{ .Env.TRANSMISSION_SPEED_LIMIT_DOWN }},
    "speed-limit-down-enabled": {{ .Env.TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED }},
```

**Comment by haugene** [comment]
You caught me hacking at this container so I had a look right away. You're at least partially right :)

The container had the legacy option `TRANSMISSION_UPLOAD_LIMIT` as a parameter, but also the new ones `TRANSMISSION_SPEED_LIMIT_UP` and `TRANSMISSION_SPEED_LIMIT_UP_ENABLED`:
https://github.com/haugene/docker-transmission-openvpn/blob/dev/Dockerfile#L97

Removed the old ones now, but the new one should be working properly as well. Can you confirm?

**Comment by janschulz** [comment]
OMG, I shouldn't hack when I'm sleep deprived. You are right, thanks! Will test in the evening...

**Comment by janschulz** [comment]
It works, thanks for removing the old options.
