### ISSUE TITLE
download-dir override not working

### ISSUE THREAD

**Issue by aborin** [haugene/docker-transmission-openvpn#2784]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

version: '2.21'
services:
    transmission-openvpn:
        container_name: transmission
        cap_add:
            - NET_ADMIN
        volumes:
            - '/mnt/multimedia/torrents/:/data/torrents'
            - '/home/seedadm/.seeder/config/:/config'
        secrets:
            - openvpn_creds
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=ca_vancouver
            - LOCAL_NETWORK=192.168.50.0/24
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TRANSMISSION_WEB_UI=transmission-web-control
            - GLOBAL_APPLY_PERMISSIONS=false
            - WEBPROXY_ENABLED=false
            - TRANSMISSION_DOWNLOAD_DIR="/data/torrents/completed"
            - TRANSMISSION_INCOMPLETE_DIR="/data/torrents/incomplete"
            - TRANSMISSION_WATCH_DIR="/data/torrents/watch"
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

secrets:
    openvpn_creds:
      file: /home/seedadm/.openvpn/openvpn_creds

### Current Behavior

- Docker compose succeeds
- Docker logs show the use of the override environment variables as specified in my compose file
- exec into container and verified settings.json contains the paths specified in my compose file
- Examine settings via the Transmission web GUI and see the download directory is set to /data/completed
- Examine settings via the Transmission web GUI and see the incomplete directory enabled and set to /data/torrents/incomplete
- Attempts to change this setting in the GUI fail to persist

### Expected Behavior

- Ability to override the download-dir setting using the Docker compose environment
- Settings in Transmission GUI download directory to be /data/torrents/completed
- Ability to edit the download directory to a valid path via the Transmission GUI

### How have you tried to solve the problem?

- Tried the dev branch with the same results
- Tried mounting my local folder to /data instead of /data/torrents but the download directory persists to /data/completed regardless of what I set in the override

### Log output

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------

Updating Transmission settings.json with values from env variables
Attempting to use existing settings.json for Transmission
Successfully used existing settings.json /config/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.5.112.12
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/torrents/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/torrents/incomplete
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to 
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/torrents/watch
sed'ing True to true
STARTING TRANSMISSION
Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=true
Transmission startup script complete.
2024-01-01 00:06:08 Initialization Sequence Completed
Running functions for token based port fowarding
Reserved Port: 28731  Mon Jan  1 00:06:14 UTC 2024
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
     1   100%    1.90 GB  Done         0.0     0.0    5.0  Finished     Loop Track (2023) [1080p] [WEBRip] [5.1] [YTS.MX]
Sum:             1.90 GB               0.0     0.0
setting transmission port to 28731
localhost:9091/transmission/rpc/ responded: success
Checking port...
Port is open: Yes
#######################
        SUCCESS        
#######################
Port: 28731
Expiration Sun Mar  3 12:06:14 UTC 2024
#######################
Entering infinite while loop
Every 15 minutes, check port status

### HW/SW Environment

```markdown
- OS: Debian bookworm/sid
- Docker: Docker Engine - Community ver 24.0.7
```

**Comment by ilike2burnthing** [comment]
Don't dupe post - https://github.com/haugene/docker-transmission-openvpn/discussions/2783

**Comment by aborin** [comment]
Interesting, I created the issue using the link provided in the original comment thinking it would formalize (not duplicate) the concern.  Will close this if you suggested test works.

**Comment by aborin** [comment]
Issue was most likely due to to inconsistent settings between compose file and persistent config.  Shutting down container and removing the local configuration and testing torrents before starting the container produced the desired result.
