### ISSUE TITLE
Can't connect to https trackers

### ISSUE THREAD

**Issue by normanu** [haugene/docker-transmission-openvpn#280]
Transmission can't connect to https trackers
Any idea how to fix it?

**Comment by matthewmcpartland** [comment]
I have just tested using an https tracker and it appears to work fine on my end. Maybe provide more information on your setup; Are you using a systemd unit to autostart/restart this container? What flags and settings did you pass to transmission? What VPN are you using and did you type that info correctly? etc.

**Comment by Blue-speed** [comment]
I am experiencing the same problem. 
Here is the content of my log file
https://gist.github.com/Blue-speed/8c577adfaecac0c11eeed62d6d105480

Here is the settings I used to start the container
https://gist.github.com/Blue-speed/5bb120e63939e28c864516cf7e657a51

**Comment by haugene** [comment]
Any news on this? I'm connecting just fine to https trackers. Is it also failing with "a minimum" of settings? Ie like the example from the README? Could this be related to the blacklist @Blue-speed?

Need steps to reproduce this or I'll close it at some point.

**Comment by coolboiime** [comment]
Doesn't seem like this thread is active. Closing for now. Will re-open when thread becomes active again.
