### ISSUE TITLE
Documentation show `x.protonvpn.net.udp` while file are named `x.protonvpn.udp`

### ISSUE THREAD

**Issue by ethicnology** [haugene/docker-transmission-openvpn#2803]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

```yml
        environment:
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - OPENVPN_PROVIDER=PROTONVPN
            - OPENVPN_CONFIG=fr.protonvpn.net.udp
            - OPENVPN_USERNAME=user
            - OPENVPN_PASSWORD=pass
            - TRANSMISSION_RPC_USERNAME=user
            - TRANSMISSION_RPC_PASSWORD=pass
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_PEER_PORT_RANDOM_ON_START=true
            - TRANSMISSION_PORT_FORWARDING_ENABLED=true
            - DISABLE_PORT_UPDATER=true
```

### Current Behavior

container keep rebooting for the following reason:

```logs
transmission        | Supplied config fr.protonvpn.net.udp.ovpn could not be found.
transmission        | Your options for this provider are:
transmission        | at.protonvpn.tcp.ovpn
…
```

### Expected Behavior

The container should run and establish the connection

### How have you tried to solve the problem?

The fix is simple: 
removing the `.net` in `OPENVPN_CONFIG=fr.protonvpn.net.udp` to `OPENVPN_CONFIG=fr.protonvpn.udp`

### Log output

```logs
transmission        | Starting OpenVPN using config fr.protonvpn.udp.ovpn
```

### HW/SW Environment

```markdown
- OS: Debian 12
- Docker: 25.0.1
```

### Anything else?

Update the documentation:
http://haugene.github.io/docker-transmission-openvpn/provider-specific/#protonvpn
> copy your ovpn file (node-.protonvpn.net.udp.ovpn) from step 1 to the protonvpn directory
> … assuming configuration file named node-<country of choice>.protonvpn.net.udp is under local protonvpn subdirectory.

**Comment by ilike2burnthing** [comment]
Provide a PR - https://github.com/haugene/docker-transmission-openvpn/blob/master/docs/provider-specific.md
