### ISSUE TITLE
Settings not saved after restarting container

### ISSUE THREAD

**Issue by konjelly** [haugene/docker-transmission-openvpn#281]
Every time I adjust the transmission settings in the UI the settings disappear the next time the container is restarted. It wouldn't be a problem except I have it set to restart if the VPN connection is dropped, so it can happen when I am not expecting it. How do I get those settings to remain across sessions like they do in other docker containers I am running?

**Comment by rwaesely** [comment]
You have to set the transmission settings with environment variable, as indicated in the readme of the project. You even have examples about how go achieve this.
