### ISSUE TITLE
Transmission docker port mapping does not show any traffic

### ISSUE THREAD

**Issue by portah** [haugene/docker-transmission-openvpn#2847]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

services:
  transmission:
    image: haugene/transmission-openvpn:5.3.1
    cap_add:
      - NET_ADMIN
    dns:
      - 8.8.8.8
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 9092:9092
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=NORDVPN
      - NORDVPN_COUNTRY=US
      - ENABLE_UFW=false
      - DEBUG=true
      - PEER_DNS=false
      - TRANSMISSION_RPC_PORT=9092
      - HEALTH_CHECK_HOST=github.com
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - TRANSMISSION_HOME=/data/transmission-home
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=172.16.16.0/24
      - OVERRIDE_DNS_1=8.8.8.8
      - OVERRIDE_DNS_2=8.8.4.4
    volumes:
      - /Volumes/data-tank/media/Transmission:/data:rw
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 100M

### Current Behavior

It worked. I did not change anything. It started docker would not have access from container to outside world. That got fixed when I updated to the latest docker (MacOS). But now, I still can't access from host computer the interface. From inside container I can ping outside like partially local network and . 
I installed tracepath to better understand what is going on:

```
# tracepath -n 172.16.16.11
 1?: [LOCALHOST]                      pmtu 1500
 1:  172.28.0.1                                            0.061ms 
 1:  172.28.0.1                                            0.027ms 
 2:  172.16.16.11                                          0.336ms reached
     Resume: pmtu 1500 hops 2 back 2 
# tracepath 172.16.16.1
 1?: [LOCALHOST]                      pmtu 1500
 1:  172.28.0.1                                            0.046ms 
 1:  172.28.0.1                                            0.073ms 
 2:  192.168.64.1                                          0.687ms 
 3:  no reply
 ```
172.16.16.11 - hosts IP

Hosts ports not occupied by anything. And netstat shows listen only when image started. So, I'm out of options what to try. I have another image on the same host ownlcoud - and that one works well so this one should but it's not... 

### Expected Behavior

Would be able on hosts computer to access localhost:9092

### How have you tried to solve the problem?

ping, netstat, tracepath changing ports from 9091 to 9092 use webproxy, nothing inside is accessible from outside(host's), no firewall enabled inside container, no firewall on the host system

### Log output

Everything started, can do curl localhost:9091/9092 inside the container

### HW/SW Environment

```markdown
- OS: MacOS 13.6.6
- Docker: 4.30
```

**Comment by portah** [comment]
I changed config file added
```
    stdin_open: true # docker run -i
    tty: true
    entrypoint: /bin/bash
```

Installed netcat and simply ran nc -l -p 9091 I was able to do curl localhost from host computer

**Comment by RalleyD** [comment]
> See here #2723

I see this has worked for a couple of people but I'm not having such luck. I'm using dev containers to run my containers most of the time so i've added this to the JSON config:

` "containerEnv": { "LOCAL_NETWORK" : "192.168.1.0/24,192.168.65.0/24"},`

And this environment variable appears when inspecting the container's config.

Perhaps where i'm going wrong is using the wrong local IP address? I assumed it was the 'default' ip address of my host?
