### ISSUE TITLE
Feature Request : OpenVPN Provider IRONSOCKET

### ISSUE THREAD

**Issue by davioxx** [haugene/docker-transmission-openvpn#287]
Hello,
Requesting a new openvpn provider ironsocket.
https://ironsocket.com/network#ovpn
Regards

**Comment by davioxx** [comment]
Hello Haugene, 

any chance to help you get this to work? Ive been trying with custom provider with no luck

**Comment by brossow** [comment]
Moments ago I submitted pull request #508 to add the OVPN files from IronSocket. They are unaltered, exactly as downloaded from the URL in the initial comment here.

**Comment by coolboiime** [comment]
Closing this for merging into issue #554! Please have all issues and updates directed towards that issue. Closing this for now, thanks!
