### ISSUE TITLE
Log Handing -- OpenVPN

### ISSUE THREAD

**Issue by avluis** [haugene/docker-transmission-openvpn#288]
Hey there 😻
I've used this image on a Synology and under an unRaid system.
Really works great when configured properly.

I'm looking to try and address a minimal issue with logs.
For example, the following snaps are the result of running `du -ah /var/lib/docker/containers/ | grep -v "/$" | sort -rh | head -60` on a system running this Docker image after some time:

![capture1](https://user-images.githubusercontent.com/875593/29156501-df69ec38-7d67-11e7-9a59-dac325342a12.PNG)
![capture2](https://user-images.githubusercontent.com/875593/29156500-df69c3a2-7d67-11e7-897e-9b7366b328f2.PNG)

What you are seeing there is the container's log file after some time.
Here is an excerpt from this log:

`
{"log":"Using OpenVPN provider: NEWSHOSTING\n","stream":"stdout","time":"2017-06-09T18:00:57.637823342Z"}
{"log":"Starting OpenVPN using config tor-a10.ovpn\n","stream":"stdout","time":"2017-06-09T18:00:57.637873539Z"}
{"log":"Setting OPENVPN credentials...\n","stream":"stdout","time":"2017-06-09T18:00:57.637880838Z"}
{"log":"2017/06/09 13:00:57 Command finished successfully.\n","stream":"stderr","time":"2017-06-09T18:00:57.662544277Z"}
{"log":"adding route to local network 192.168.2.0/24 via 192.168.2.1 dev eth0\n","stream":"stdout","time":"2017-06-09T18:00:57.665017038Z"}
{"log":"RTNETLINK answers: File exists\n","stream":"stderr","time":"2017-06-09T18:00:57.665673216Z"}
{"log":"Fri Jun  9 13:00:57 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014\n","stream":"stdout","time":"2017-06-09T18:00:57.671383676Z"}
{"log":"Fri Jun  9 13:00:57 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts\n","stream":"stdout","time":"2017-06-09T18:00:57.671533407Z"}
{"log":"Fri Jun  9 13:00:57 2017 Socket Buffers: R=[212992-\u003e131072] S=[212992-\u003e131072]\n","stream":"stdout","time":"2017-06-09T18:00:57.671818514Z"}
{"log":"Fri Jun  9 13:00:57 2017 UDPv4 link local: [undef]\n","stream":"stdout","time":"2017-06-09T18:00:57.788713811Z"}
{"log":"Fri Jun  9 13:00:57 2017 UDPv4 link remote: [AF_INET]216.151.184.13:1194\n","stream":"stdout","time":"2017-06-09T18:00:57.788775541Z"}
{"log":"Fri Jun  9 13:00:57 2017 TLS: Initial packet from [AF_INET]216.151.184.13:1194, sid=56ced294 e28bb47d\n","stream":"stdout","time":"2017-06-09T18:00:57.822788413Z"}
{"log":"Fri Jun  9 13:00:57 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this\n","stream":"stdout","time":"2017-06-09T18:00:57.822856734Z"}
{"log":"Fri Jun  9 13:00:57 2017 VERIFY OK: depth=1, C=US, ST=VPN, L=VPN, O=VPN, OU=VPN, CN=VPN, name=VPN, emailAddress=VPN\n","stream":"stdout","time":"2017-06-09T18:00:57.880439375Z"}
{"log":"Fri Jun  9 13:00:57 2017 Validating certificate key usage\n","stream":"stdout","time":"2017-06-09T18:00:57.880472171Z"}
{"log":"Fri Jun  9 13:00:57 2017 ++ Certificate has key usage  00a0, expects 00a0\n","stream":"stdout","time":"2017-06-09T18:00:57.880478632Z"}
{"log":"Fri Jun  9 13:00:57 2017 VERIFY KU OK\n","stream":"stdout","time":"2017-06-09T18:00:57.880486573Z"}
{"log":"Fri Jun  9 13:00:57 2017 Validating certificate extended key usage\n","stream":"stdout","time":"2017-06-09T18:00:57.880491419Z"}
{"log":"Fri Jun  9 13:00:57 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication\n","stream":"stdout","time":"2017-06-09T18:00:57.880495973Z"}
{"log":"Fri Jun  9 13:00:57 2017 VERIFY EKU OK\n","stream":"stdout","time":"2017-06-09T18:00:57.880500464Z"}
{"log":"Fri Jun  9 13:00:57 2017 VERIFY OK: depth=0, C=US, ST=VPN, L=VPN, O=VPN, OU=VPN, CN=vpn, name=VPN\n","stream":"stdout","time":"2017-06-09T18:00:57.880506943Z"}
{"log":"Fri Jun  9 13:00:57 2017 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key\n","stream":"stdout","time":"2017-06-09T18:00:57.974377389Z"}
{"log":"Fri Jun  9 13:00:57 2017 Data Channel Encrypt: Using 256 bit message hash 'SHA256' for HMAC authentication\n","stream":"stdout","time":"2017-06-09T18:00:57.974427017Z"}`

And so on -- 1,981,282 lines of logging goodness to be exact.

As you can see, this is OpenVPN doing its thing so as time goes by, the container's volume will keep growing due to this.

---
Quick Fix:
You can add a few additional arguments to your docker run command to limit the total size of the log for the container: `--log-opt max-size=50m --log-opt max-file=1`
Note that in order to restrict to a single log file (instead of just archiving), `--log-opt max-file=1` is needed.

**Comment by haugene** [comment]
Hi. Reviewing old issues and your fix here is at least now documented in the README and included in the default run command. Closing this.
