### ISSUE TITLE
No access to Web UI outside local network ip's

### ISSUE THREAD

**Issue by clowrym** [haugene/docker-transmission-openvpn#289]
I have a VPN set up from my Work to home & my phone to home & with other TransmissionVPN dockers have always had access to transmission webui. After installing this one, I can only access the webui when I am on my home network. Is there anyway to gain access to the webui outside of my local network?

On Unraid with a couple other Dockers I have had to install iptable_mangle (/sbin/modprobe iptable_mangle) but that doesn't seem to work with this Docker container

Or is it possible to specify more than one local network, Ie my local 192.168.0.0/24 & my VPN 10.1.0.0/24?

**Comment by flackdl** [comment]
I am curious about this as well.  The [start.sh script](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L73) runs the following for my configuration:

    sudo /sbin/ip r a "192.168.1.0/24" via "192.168.1.1" dev "eth0"

And I can't seem find out how to permit connections from outside the network into the container.  I don't have the firewall enabled either.

Any ideas?

**Comment by clowrym** [comment]
I wrote a script that I run to add the second lan network for my vpn.

**Comment by flackdl** [comment]
Do you mind sharing it? We can close this out.

**Comment by clowrym** [comment]
This is specific to my Network VPN & unraid Server... As I'm not concerned about direct outside access. I run this script every time I reboot/restart the Docker container. I dont feel this solves the issue, its rather a work-around.


`#!/bin/bash
echo adding 10.1.0.0/25 LAN_NETWORK
docker exec Transmission_VPN /bin/sh -c "/sbin/ip r a 10.1.0.0/24 via 172.17.0.1 dev eth0"
echo Netowrk added
exit`

**Comment by flackdl** [comment]
Do you have any idea how you *could* open it up to the outside?  Using the `$LOCAL_NETWORK` works well when I'm inside my local network, but I'm still unable to access the webui from outside.

**Comment by flackdl** [comment]
I was thinking, at least as a workaround, to reverse proxy from nginx so the container sees the connection as a local one?

**Comment by haugene** [comment]
That would work, and is described in the [readme](https://github.com/haugene/docker-transmission-openvpn#access-the-webui). There's a prebuilt image you can use and a sample run command is in the docs. Let me know how it goes :)

**Comment by flackdl** [comment]
Oh, thanks for the tip!

**Comment by tleung927** [comment]
does anyone fix this?
I have exactly same problem. I can access webui in local. And I try the localnetwork and the proxy. None of them help me access webui via internet .

**Comment by flackdl** [comment]
@tleung927 the proxy worked well for me accessing the webui from outside the local network.

**Comment by tleung927** [comment]
@flackdl how did you config the proxy?

i am using this 

docker run -d \
      --link 6e701216d3f8:transmission \
      -p 8080:8080\
      haugene/transmission-openvpn-proxy 

6e701216d3f8 is my docker's name

**Comment by tleung927** [comment]
problem solved!!!! i am so stupid keep using the container id instead of the container's name.

does it got to be 8080 could i change to some other port?

**Comment by flackdl** [comment]
glad you got it sorted out.  you can use whatever external port you want but it has to map to the container with 8080, like `-v 8888:8080`.

**Comment by tleung927** [comment]
@flackdl 

Thanks a lot!!!! everything is working as my expect!!!!
