### ISSUE TITLE
Encrypted password in DockerEnv breaks updatePort.sh

### ISSUE THREAD

**Issue by RJSzynal** [haugene/docker-transmission-openvpn#292]
When using an encrypted password in the DockerEnv file it is also encrypted in the `/config/transmission-credentials.txt` file which then means the incorrect credentials are used in `transmission/updatePort.sh` on lines 77, 89, and 93. This causes the following output in the container log:
```STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Thu Aug 24 07:38:14 2017 Initialization Sequence Completed
Generating new client id for PIA
Got new port 30166 from PIA
transmission auth required
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized User1NjIwODBDSm16Vy5WMA==
User-Agent: transmission-remote/2.92 (14714)
Host: localhost:9091
Accept: */*
Accept-Encoding: deflate, gzip

Update UFW rules before changing port in Transmission
denying access to 51413
Rule updated
allowing 30166 through the firewall
Rule added
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized User1NjIwODBDSm16Vy5WMA==
User-Agent: transmission-remote/2.92 (14714)
Host: localhost:9091
Accept: */*
Accept-Encoding: deflate, gzip

Checking port...
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized User1NjIwODBDSm16Vy5WMA==
User-Agent: transmission-remote/2.92 (14714)
Host: localhost:9091
Accept: */*
Accept-Encoding: deflate, gzip
```

The current fix is to use a plain text password but this is not great from a security standpoint.
This caveat should be added to the readme.md as using an encrypted password is supported by transmission in it's settings.json

**Comment by haugene** [comment]
You're right, the updatePort.sh does not support encrypted passwords. We're using `transmission-remote` to set the port, and if it supports encrypted passwords the script could be fixed to support it as well. If not, it should be in the README. Any pull requests on this is welcomed :)

**Comment by haugene** [comment]
I think this is a "won't fix" for now.
