### ISSUE TITLE
Add ExpressVPN to list of VPN providers

### ISSUE THREAD

**Issue by Rawh** [haugene/docker-transmission-openvpn#293]
As in the subject, could you please add ExpressVPN to the list of VPN providers?

**Comment by Rawh** [comment]
Ah I see it's actually already been requested and discussed in https://github.com/haugene/docker-transmission-openvpn/issues/105

Sadly I can't seem to get the docker image working with the ovpn file. I pass the username and pw to the container via the docker startup line, but the container keeps on telling me it can't read the username from stdin. I also tried to instead run the container with --env-file but it still gives the same error.

```
Using OpenVPN provider: CUSTOM
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
2017/08/25 15:28:02 Command finished successfully.
adding route to local network 192.168.2.0/24 via 172.17.0.1 dev eth0
Fri Aug 25 15:28:02 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Fri Aug 25 15:28:02 2017 ERROR: could not read Auth username from stdin
Fri Aug 25 15:28:02 2017 Exiting due to fatal error
Enter Auth Username:
```

Any clues to what I might be doing wrong?

**Comment by Forage** [comment]
You probably didn't adapt the .ovpn  file to work with the Docker container. Read the manual.
In your case I assume there's a line `auth-user-pass` in your VPN config file. Change it to `auth-user-pass /config/openvpn-credentials.txt` and try again. Or add that line if it is not included.

**Comment by haugene** [comment]
ExpressVPN is still using per-user ovpn-files, right? In that case I don't think you should have an `auth-user-pass` section as it should already be included when you download your config file.

Pass "dummy" as username and password and apart from that use the ovpn file as it is. If you don't see any sections in the ovpn file regarding authentication or a private key of some kind it might be that they've changed their authorization and we might be able to add it to the image.

**Comment by Rawh** [comment]
I got it to work by putting my username and pw into a file and storing it on the /data share. Added that file together with the `full path` + `auth-user-pass` variable to the .ovpn file.

OpenVPN forum said something about the following. Quite sure it's in the manual as well :)
```
--auth-user-pass [up]
Authenticate with server using username/password. up is a file containing username/password on 2 lines 

If up is omitted, username/password will be prompted from the console.
```

**Comment by haugene** [comment]
Huh... If using the `auth-user-pass /some/file` worked for you that probably means we can bundle support for ExpressVPN as well. Do you have a link to the .ovpn configs provided by ExpressVPN?
