### ISSUE TITLE
New to this. So Many questions.

### ISSUE THREAD

**Issue by jeff-kingston** [haugene/docker-transmission-openvpn#296]
Please bear with me as I have been struggling to get this to work properly for a few days. Figured I would ask some questions here. 

A little about my setup:

Running Docker 17.06.1-ce-mac24 on my Mac mini
I have set up a few images in the past (mostly through the Kitematic GUI)
I was able to get this image up and running. It connected to my VPN service just fine. However it would not connect to any tracker.

I started reading through the help on how to fix this and this is where I quickly ended up over my head.

I figured I would try the DNS fix that was documented but I wasn't sure where to put the --dns in the Kitematic UI, so I figured maybe I had to create the image via the CLI. 

I also tried to run a custom config using an ovpn file from my provider. I am using HIDEME, and the only config file is for the Netherlands and I don't get great performance from there based on my location.
So I read about the custom config file and having to add the volume in the run command. I can't do this via the GUI so this was another thing pointing me to the CLI. (I am getting the hint) 

I used this run command to attempt to build the image instead of using the GUI.

docker run --privileged --cap-add=NET_ADMIN --device=/dev/net/tun -d \
--dns 8.8.8.8 \
--dns 8.8.4.4 \
-v /Users/BLAH/Docker/Downloads/:/data \
-v /Users/BLAH/Docker/myvpnconfig.ovpn:/etc/openvpn/custom/default.ovpn \
-v /etc/localtime:/etc/localtime:ro \
-e "OPENVPN_PROVIDER=CUSTOM” \
-e "OPENVPN_USERNAME=XXXXX” \
-e "OPENVPN_PASSWORD=XXXXX” \
-p 9091:9091 \
haugene/transmission-openvpn

However when I pasted that into terminal it wouldn't actually execute the command, it kept acting like it was waiting for another line of text. I tried typing it all out..same thing. I am obviously a little challenged here. 

If anyone is willing to help a total newbie out, I would really appreciate it. I promise I really did try and read through the help and documentation to figure this out on my own. :)

Thanks!

**Comment by jeff-kingston** [comment]
When I copied my run command it removed all my trailing \. I have a <space> \ at the end of each line but the last.

**Comment by niXta1** [comment]
Try to remove stuff until it works.

**Comment by niXta1** [comment]
If you came to a solution, share it, so anyone who searches for the same problem can find it.

**Comment by jeff-kingston** [comment]
I did what you suggested and tried copy /pasting one lien at a time and hitting ENTER to see if the command would execute.
 It was the line that added the data volume. Im not sure baceuase I copied that right from the DockerHub page. To get it running I copied in each line I had from text edit, manually typed that one line and then it launched.

**Comment by niXta1** [comment]
Great! 👍
