### ISSUE TITLE
Systemctl constantly restarting container

### ISSUE THREAD

**Issue by neddy99** [haugene/docker-transmission-openvpn#297]
I am wondering if anyone might be able to give me a little help. I have setup the container and it does work, but when I try to use systemctl to mange the container, it constantly restarts every 5 seconds.

I'm not sure where I have gone wrong...

Here is my systemctl service file.

Any help would be greatly appreciated!

```
[Unit]
Description=haugene/transmission-openvpn docker container
After=docker.service
Requires=docker.service

[Service]
User=htpc
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill transmission-openvpn
ExecStartPre=-/usr/bin/docker rm transmission-openvpn
ExecStartPre=/usr/bin/docker pull haugene/transmission-openvpn
ExecStart=/usr/bin/docker run \
        --name transmission-openvpn \
        --cap-add=NET_ADMIN \
        --device=/dev/net/tun -d \
        -v /home/htpc/Torrents-VPN:/data \
        -e "OPENVPN_PROVIDER=PIA" \
        -e "OPENVPN_USERNAME=xxxxxxxxx" \
        -e "OPENVPN_PASSWORD=xxxxxxxxx" \
        -e "OPENVPN_CONFIG=US East" \
        -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
        -e "TRANSMISSION_UMASK=0" \
        -e "LOCAL_NETWORK=10.7.7.0/24" \
        -e "TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true" \
        -p 9092:9091 \
        --dns 8.8.8.8 \
        --dns 8.8.4.4 \
        haugene/transmission-openvpn
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by neddy99** [comment]
This has stopped the constant restarting, but no idea if it will restart if the VPN drops...

I removed the 
```
Restart=always
RestartSec=5
```
and instead added the restart command to the docker run command:

Can anyone tell me if this is ok to do?

Thanks

```
[Unit]
Description=haugene/transmission-openvpn docker container
After=docker.service
Requires=docker.service

[Service]
User=htpc
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill transmission-openvpn
ExecStartPre=-/usr/bin/docker rm transmission-openvpn
ExecStartPre=/usr/bin/docker pull haugene/transmission-openvpn
ExecStart=/usr/bin/docker run --restart always \
        --name transmission-openvpn \
        --cap-add=NET_ADMIN \
        --device=/dev/net/tun -d \
        -p 9092:9091 \
        -e "OPENVPN_PROVIDER=PIA" \
        -e "OPENVPN_USERNAME=xxxxxx" \
        -e "OPENVPN_PASSWORD=xxxxxxxx" \
        -e "OPENVPN_CONFIG=Switzerland" \
        -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
        -e "TRANSMISSION_UMASK=0" \
        -e "LOCAL_NETWORK=10.7.7.0/24" \
        -e "TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true" \
        -v /home/htpc/Torrents-VPN:/data \
        --dns 8.8.8.8 \
        --dns 8.8.4.4 \
        haugene/transmission-openvpn

[Install]
WantedBy=multi-user.target
```

**Comment by haugene** [comment]
Looks very correct. The man page for systemctl restart [says](https://www.freedesktop.org/software/systemd/man/systemd.service.html) "Configures whether the service shall be restarted when the service process exits". You were running the container with the `-d` flag making run as a daemon. So that will return the id of the container and free the shell, triggering a restart.

By putting the restart on the docker run command it's dockers responsibility to restart the container if it exits, and it should do that when vpn drops for example. You could probably use your first systemctl configuration if you don't set the daemon flag in the run command.

**Comment by neddy99** [comment]
Thanks for the reply! I was staring at the config trying to figure it out... I knew something was making the process exit, I just couldn't spot it. I had copy and paste the command from the terminal when I was testing the config and I obviously missed the '-d'.

Thank you very much for your help!!

The container works great!!
