### ISSUE TITLE
Failure to connect socket

### ISSUE THREAD

**Issue by typhune** [haugene/docker-transmission-openvpn#301]
exceptionally slow to get any metadata, and getting these error messages in the log:

Couldn't connect socket 24 to 2601:200:8100:7b00:c40f:dab0:5897:7ca9, port 28153 (errno 99 - Cannot assign requested address) (net.c:290)
with different socket numbers and IPV6 addresses.

Using Docker for mac 17.06.1-ce-mac24

Docker-compose configuration:

  transvpn:
    image: haugene/transmission-openvpn
    container_name: transmission
    dns:
        - 208.67.222.222
        - 208.67.220.220
    environment:
        - OPENVPN_PROVIDER=TORGUARD
        - OPENVPN_CONFIG=USA-DALLAS
        - OPENVPN_USERNAME=xxx
        - OPENVPN_PASSWORD=yyy
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    ports:
        - 9091:9091
    volumes:
        - /Volumes/Multimedia/:/data
        - /etc/localtime:/etc/localtime:ro
    cap_add:
        - NET_ADMIN
    devices:
        - /dev/net/tun:/dev/net/tun
    restart: always

**Comment by haugene** [comment]
Hmm, googled this and found several issues regarding IPv6 and Docker for Mac (like [this](https://github.com/docker/for-mac/issues/932) and [that](https://github.com/docker/for-mac/issues/1586)).

Maybe disable IPv6?
