### ISSUE TITLE
Do blocklists work?  

### ISSUE THREAD

**Issue by nebhead** [haugene/docker-transmission-openvpn#302]
I've setup the following variables when creating my container:

```
-e "TRANSMISSION_BLOCKLIST_URL=http://list.iblocklist.com/?list=ydxerpxkpcfqjaybcssw&fileformat=p2p&archiveformat=gz" \
-e "TRANSMISSION_BLOCKLIST_ENABLED=true" \

```

Unfortunately, when I try to use my Transmission remote client to update the blocklist, I get a failure. Is there some way I can check to see that the setting was actually applied to the settings.json inside the container?  

Thanks!

**Comment by haugene** [comment]
#245
