### ISSUE TITLE
Cannot resolve host address error - VPN disconnected Transmission is up and running!

### ISSUE THREAD

**Issue by jeff-kingston** [haugene/docker-transmission-openvpn#303]
I have the container up and running. After about an hour my logs get spammed with this error message. and I have to restart the container.

Running Docker 17.06.2-ce-mac27

Wed Sep  6 21:16:53 2017 RESOLVE: Cannot resolve host address: ca-12.hide.me: Temporary failure in name resolution
Wed Sep  6 21:17:38 2017 RESOLVE: Cannot resolve host address: ca-12.hide.me: Temporary failure in name resolution

I am using HIDEME and I am using a custom open VPN file. when I start the container I do get these messages

Wed Sep  6 17:51:16 2017 SENT CONTROL [*.hide.me]: 'PUSH_REQUEST' (status=1)
Wed Sep  6 17:51:16 2017 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 173.209.57.241,dhcp-option DNS 173.209.57.243,topology subnet,ping 5,ping-restart 15,explicit-exit-notify,sndbuf 8388608,rcvbuf 8388608,route-gateway 10.3.101.254,redirect-gateway,dhcp-renew,dhcp-release,register-dns,block-outside-dns,client-nat dnat 10.3.101.254 255.255.255.255 10.255.255.254,ifconfig 10.3.101.58 255.255.255.0'
Wed Sep  6 17:51:16 2017 Options error: Unrecognized option or missing parameter(s) in [PUSH-OPTIONS]:11: dhcp-renew (2.3.2)
Wed Sep  6 17:51:16 2017 Options error: Unrecognized option or missing parameter(s) in [PUSH-OPTIONS]:12: dhcp-release (2.3.2)
Wed Sep  6 17:51:16 2017 Options error: Unrecognized option or missing parameter(s) in [PUSH-OPTIONS]:13: register-dns (2.3.2)
Wed Sep  6 17:51:16 2017 Options error: Unrecognized option or missing parameter(s) in [PUSH-OPTIONS]:14: block-outside-dns (2.3.2)

Docker run file
docker create --cap-add=NET_ADMIN --device=/dev/net/tun -d \
-v /Users/Me/Docker/Downloads/:/data \
-v /Users/Me/Docker/transmission-vpn:/config \
-v /etc/localtime:/etc/localtime:ro \
-v  /Users/Me/Docker/myovpn.ovpn:/etc/openvpn/custom/default.ovpn \ 
-dns 8.8.8.8 \
-dns 8.8.4.4 \
-e "OPENVPN_PROVIDER=CUSTOM” \
-e "OPENVPN_USERNAME=*UserName*” \
-e "OPENVPN_PASSWORD=*Password*” \
-p 9091:9091 \
haugene/transmission-openvpn

**Comment by jeff-kingston** [comment]
It seems it happen when the OVPN_Option to restart for inactivity is hit.

Transmission startup script complete.
Thu Sep  7 17:49:32 2017 /sbin/ip route add 173.209.57.242/32 via 172.17.0.1
Thu Sep  7 17:49:32 2017 /sbin/ip route del 0.0.0.0/0
Thu Sep  7 17:49:32 2017 /sbin/ip route add 0.0.0.0/0 via 10.3.101.254
Thu Sep  7 17:49:32 2017 Initialization Sequence Completed
Thu Sep  7 18:56:13 2017 [*.hide.me] Inactivity timeout (--ping-restart), restarting
Thu Sep  7 18:56:13 2017 SIGUSR1[soft,ping-restart] received, process restarting
Thu Sep  7 18:56:13 2017 Restart pause, 2 second(s)
Thu Sep  7 18:56:15 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Sep  7 18:56:15 2017 Socket Buffers: R=[212992->212992] S=[212992->212992]
Thu Sep  7 18:56:55 2017 RESOLVE: Cannot resolve host address: ca-12.hide.me: Temporary failure in name resolution
Thu Sep  7 18:57:35 2017 RESOLVE: Cannot resolve host address: ca-12.hide.me: Temporary failure in name resolution

**Comment by jeff-kingston** [comment]
Just discovered this is a major issue. When then container is in this state, the VPN is not connected but Transmission is still available! I am available to help troubleshoot the error.

**Comment by that1guy** [comment]
Same issue here all of the sudden

```
Using OpenVPN provider: PIA
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
2017/09/12 01:50:05 Command finished successfully.
Tue Sep 12 01:50:05 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Tue Sep 12 01:50:05 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Sep 12 01:50:45 2017 RESOLVE: Cannot resolve host address: nl.privateinternetaccess.com: Temporary failure in name resolution
Tue Sep 12 01:51:25 2017 RESOLVE: Cannot resolve host address: nl.privateinternetaccess.com: Temporary failure in name resolution
Tue Sep 12 01:52:10 2017 RESOLVE: Cannot resolve host address: nl.privateinternetaccess.com: Temporary failure in name resolution
```

**Comment by jeff-kingston** [comment]
that1guy - Can you confirm you are able to access Transmission when your container is in this state? Can you also confirm with PIA that you are NOT connected to the VPN. 

That is what I see with HIDEME, my connections drops from the VPN but Transmission continues to run. This leaves me exposed. I see this as a major bug and as a precaution and I have discontinued use of this container until the bug is addressed.

**Comment by that1guy** [comment]
@jeff-kingston I noticed I can resolve my issue by opening up the entire UDP port range on my machine.  How do I know what port Transmission needs so I don't have to open the entire range?  

To answer your question @jeff-kingston, no, I am not able to load the transmission UI when it is in this state.

**Comment by jeff-kingston** [comment]
I have been able to workaround this issue by using the IP address in my custom OVPN file instead of the hostname. I will close this issue since I am working and the container is stable.
