### ISSUE TITLE
Nordvpn can't find supplied config

### ISSUE THREAD

**Issue by tomhumphrey** [haugene/docker-transmission-openvpn#305]
Supplied config ch11.nordvpn.com.udp1194.ovpn could not be found
Same happens with ch10

The default for NordCPN then fails with the TLS handshake

**Comment by haugene** [comment]
Can't seem to be able to reproduce this locally. Setting `OPENVPN_CONFIG=ch11.nordvpn.com.udp1194` works fine here using the latest image.
```
transmission_1  | Using OpenVPN provider: NORDVPN
transmission_1  | Starting OpenVPN using config ch11.nordvpn.com.udp1194.ovpn
```

If you're still experiencing problems, please provide the  `docker run ...` command so I can test with the same configuration.
