### ISSUE TITLE
Unable to connect VPN

### ISSUE THREAD

**Issue by RiverRat205** [haugene/docker-transmission-openvpn#309]
I am having trouble getting this to work on QNAP TS-451+. I've tried to connect to several on Newshosting VPN server but the auth fails and the container terminates. I'm a beginner to linux and shell, but have been learning a lot about operating a NAS.

> Fri Sep 22 15:29:41 2017 [vpn] Peer Connection Initiated with [AF_INET]81.171.98.193:1194                                                                                                                                                                    
> Fri Sep 22 15:29:43 2017 SENT CONTROL [vpn]: 'PUSH_REQUEST' (status=1)                                                                                                                                                                                       
> Fri Sep 22 15:29:44 2017 AUTH: Received control message: AUTH_FAILED                                                                                                                                                                                         
> Fri Sep 22 15:29:44 2017 SIGTERM[soft,auth-failure] received, process exiting

**Comment by haugene** [comment]
Well, your log says `AUTH_FAILED` which means something is wrong with your username or password, are you sure they're set correctly?

If you run the following command:
`docker exec -it <container id|name> cat /config/openvpn-credentials.txt`
You should get your username and password printed on separate lines, does that look good?

If so, are you sure this is the right username/password pair for this kind of connection? Some providers have different sets of keys/passwords.

**Comment by RiverRat205** [comment]
I double-checked my login/pass for my VPN. They were both correct. I commented the puid and pgid lines out of my env file and recreated my container. Transmission seems to be working now, the container starts up, authenticates and continues to run. The only trouble I am still having is connecting to the webui. I have yet to try the proxy container. Thanks for your help.

**Comment by echaupynx** [comment]
Thanks for that RiverRat205! Worked for Nordvpn as well

**Comment by haugene** [comment]
There's been some issues running with UID/GID options. Not sure if it's plattform dependant or what it is, but there are other issues addressing this so let's hope it's solved through one of them. Closing this for now since, at least for you, the issue seems solved.
