### ISSUE TITLE
frostVPN ovpn files out of date

### ISSUE THREAD

**Issue by g-be** [haugene/docker-transmission-openvpn#312]
frost vpn changed the gateway and ovpn files, I intend on updating them

**Comment by haugene** [comment]
Thanks for letting me know, and it would be great if you could provide an updated set. If not, please provide me with a link to the config files zip and I can update them as well.

**Comment by g-be** [comment]
http://www.frostvpn.com/clients/knowledgebase/79/NEW-OpenVPN-configuration-files-and-usage.html
Here's the link to the current ovpn file, and it has instructions for editing it for your chosen gateway.
http://www.frostvpn.com/clients/servers.htm
Here's the full list of gateways.

Do you have any suggestions for an automated way of creating all these config files?

**Comment by haugene** [comment]
Thanks! I don't know what would be easiest to automate this. Maybe write a jQuery-snippet that extracts the location and gateway from the table and adds them to an array of sorts. Then use templating to loop through the locations, substitute the gateway and save it with the location name + .ovpn.

Some locations have several gateways, so the scripts need to handle that as well. Don't know if it's faster than 100+ copy-paste operations, but definitely more fun :)

**Comment by haugene** [comment]
Merged #343 and closing this issue
