### ISSUE TITLE
Cannot build on docker 17.06

### ISSUE THREAD

**Issue by kmccormick** [haugene/docker-transmission-openvpn#315]
...
    Step 6/10 : ADD openvpn/ /etc/openvpn/
     ---> 977626b9440f
    Step 7/10 : ADD transmission/ /etc/transmission/
     ---> 8cf112ad54d0
    failed to process "\"TRANSMISSION_ALT_SPEED_DOWN": unexpected end of statement while looking for 
    matching double-quote

According to https://github.com/moby/moby/issues/33943 the entire "key=value" pair has never been correct syntax, and is no longer supported. https://docs.docker.com/engine/reference/builder/#env shows key="value" if quoting is necessary.

**Comment by haugene** [comment]
Merged it to dev now, works. Bundling up some more changes and merge it to master and a new release soon. Thanks for providing the fix.
