### ISSUE TITLE
Bundle the Combustion UI

### ISSUE THREAD

**Issue by haugene** [haugene/docker-transmission-openvpn#318]
After fixing #255 the container supports using a different UI. The Combustion UI (and others) could be bundled in the build and chosen with an environment variable.

This needs to be added to the build and usage described in the README

**Comment by ylor** [comment]
I really love [kettu](https://github.com/endor/kettu). It's the best front-end I've found so far. Happy to be proven wrong though!

**Comment by haugene** [comment]
Merged the combustion ui PR, and created a new issue for kettu. Closing this.
