### ISSUE TITLE
1.1.7 image generates issue with --ping

### ISSUE THREAD

**Issue by Jonathan34** [haugene/docker-transmission-openvpn#319]
The image 1.16 runs fine while the image 1.17 fails with the following error message:
```
unrecognized option or missing or extra parameter(s) in [CMD] ping (2.4.4)
```
I tried commenting out my openvpn-opts (default values) in my `DockerEnv` but it still does not work.
i only have `ping-restart 60` in my .ovpn file; removing it does not fix the issue either.

Using torguard.
Deployed in unraid 6.3.5

**Comment by haugene** [comment]
How's your openvpn opts set in the DockerEnv file? Depending on your version of docker you might need to change or remove quotation marks. Probably related to #276?

**Comment by Jonathan34** [comment]
Well even if I comment out the line with # it still shows the issue. And it works fine with the opts using 1.16. is there a different version of OpenVPN between the two images?

**Comment by haugene** [comment]
Ah, yes you said that. My bad. And yes, it's a new version of openvpn in 1.17. But I can't remember seeing it in my logs, maybe I didn't look close enough. Won't be able to test it for a few days though.

**Comment by haugene** [comment]
Version 1.17 of the image also upgraded ubuntu from 14.04 to 16.04 where ping is not installed by default. Might be a long shot, but I've added ping now and it's available on the dev tag of the image. Can you try again and see if it works?

If not, it [seems likely](https://forums.openvpn.net/viewtopic.php?f=6&t=24967) to be a quotation issue we need to track down.

**Comment by Jonathan34** [comment]
With Dev: 
`Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/custom/USA-DALLAS.ovpn:22: script-security (2.4.4)
`

**Comment by haugene** [comment]
Allright! Which provider are you using? I see you've set it up as a custom config, was on my way to try and reproduce it before I saw that I couldn't :)

Closing this then.

**Comment by Jonathan34** [comment]
I'm using torguard with a custom config they provided. thanks for your help, everything is up and running using latest image.
