### ISSUE TITLE
Alternative VPN providers

### ISSUE THREAD

**Issue by itisNathaniel** [haugene/docker-transmission-openvpn#32]
Can this Docker container be used with other VPN providers such as FrootVPN?

**Comment by haugene** [comment]
Yes, it can be extended to support any OpenVPN provider.

How familiar are you with Docker? If you have a look at the code, and check out pull request #28 in particular you might figure out how to extend it and I would happily accept a pull request adding Froot as a provider. 

If not, I could extend it for you. I don't have an account there, but you could verify when it works.  I have a busy week so I won't rush it, but maybe next weekend?

**Comment by itisNathaniel** [comment]
That's awesome thank you!
Will have a go trying to extend it myself but if I struggle I'll let you know.
Cheers.
How easy would it be to run another app within the same instance? (Such as something like Sonarr kr

**Comment by itisNathaniel** [comment]
*or another application to transmit soley over the VPN?). 
P.S: sorry about the two posts, I clumsily submitted the first one before I'd finished!

**Comment by haugene** [comment]
Hello again.

I have now added FrootVPN as a provider. It should be OK but I need you to verify that it's working, as I don't have an account with Froot. Follow instructions from the readme, but use the dev-tag as it's only available there (image: haugene/transmission-openvpn:dev).

Second... Yes it is possible to run another app inside the same container, but it is generally [not recommended](https://docs.docker.com/articles/dockerfile_best-practices/#run-only-one-process-per-container). I get that it can tempting to squeeze it in there, and you could... But it would be cleaner to create a separate container for this.

**Comment by haugene** [comment]
Merged to master, closing issue.

**Comment by itisNathaniel** [comment]
Sorry, I meant to reply earlier!
It worked fantastically thank you and I have implemented it in addition to my other software in different containers.
Cheers for your help!

**Comment by haugene** [comment]
Glad to hear it works. Np :)
