### ISSUE TITLE
Tranmission hangs after download

### ISSUE THREAD

**Issue by jvisser** [haugene/docker-transmission-openvpn#320]
Hi,

I have this issue where after the download transmission becomes inaccessible for some time. Cpu usage and memory usage spike up. It takes about 15 minutes to end. After that I can connect to the web ui again.

There are no errors in the log file:

`[2017-10-18 21:54:32.748] <torrent> State changed from "Incomplete" to "Complete" (torrent.c:2218)
[2017-10-18 21:54:32.748] <torrent> moving "/data/incomplete/<torrent>" to "/target/<torrent>" (torrent.c:3157)`

The file move is the last thing in the logfile. Then transmission becomes unresponsive for about 15m. I have a download complete script configured. The script is also only invoked after the 15m hang. I have used tranmission a lot over the years and never experienced this until now.

Any help solving this is appreciated.

**Comment by jvisser** [comment]
I think it is related to how I have mounted my volumes. Resulting in a file copy. That the UI hangs while it is copying seems to be an issue with transmission itself.

**Comment by haugene** [comment]
Ah, good catch! Changing the mounts so that it's a move operation instead of copy fixes the problem? This might also solve #277 in that case, as that's probably the same issue as this.

**Comment by jvisser** [comment]
Confirmed. That did fix the problem for me.
