### ISSUE TITLE
Persistant settings.json, reports port closed

### ISSUE THREAD

**Issue by izznogooood** [haugene/docker-transmission-openvpn#322]
First I want to thank you for your work. Its a great Docker!

I am new with docker (not with linux!)

I made a systemd unit file to keep track on your docker.

```
[Unit]
Description=OpenVPN Docker Container
Documentation=https://github.com/haugene/docker-transmission-openvpn
After=network.target docker.socket
Requires=docker.socket

[Service]
RestartSec=10
Restart=always

Environment="NAME=transmission-openvpn"
Environment="IMG=haugene/transmission-openvpn"

# Clean-up bad state if still hanging around
ExecStartPre=-/usr/bin/docker rm -f $NAME

# Pull new image for updates
ExecStartPre=-/usr/bin/docker pull $IMG

# Start Service
ExecStart=/usr/bin/docker run --cap-add=NET_ADMIN --device=/dev/net/tun -v /zfs/downloads/:/data -v /etc/localtime:/etc/localtime:ro -v PUID=1000 -v PGID=1000 -e "OPENVPN_PROVIDER=NORDVPN" -e "OPENVPN_CONFIG=se-ch1.nordvpn.com.tcp443" -e "OPENVPN_USERNAME=xxx" -e "OPENVPN_PASSWORD=xxx" -e LOCAL_NETWORK=10.0.1.0/24 --name ${NAME} --dns 8.8.8.8 --dns 8.8.4.4 -p 9091:9091 haugene/transmission-openvpn

# Stop Service
ExecStop=/usr/bin/docker stop ${NAME}
```

Transmission reports Port 51413 as closed but its not. Its forwarded from my router. 
Is it possible to have a persisistant configuration så i could add upnp and set seed, umask and other options?

And how can I know if the VPN is really working?

**Comment by haugene** [comment]
Thanks for that, glad to hear it. As for your questions. While you're connected to VPN it's not your router you need to forward ports from. Your traffic is tunneled somewhere and that will be your public IP. That is where ports need to be opened. You need to ask your VPN provider for that. There is a script that does this automatically if you're using PIA. There are several previous issues where the same question has been raised, reading them and see if there's something useful.

The config is generated from environment variables for several reasons, one being that we dynamically set the ip address for transmission to bind to which is a security measure. You can set any of the transmission settings by setting the corresponding environment variable as described in the readme.

 To see if VPN is really working, see #323

**Comment by haugene** [comment]
I feel this issue is answered, so I'll close it. Re-open or create a new one if you still have issues or questions.
