### ISSUE TITLE
Is there a way to confirm that Transmission is actually working behind the VPN (i.e. confirm your IP)? 

### ISSUE THREAD

**Issue by nebhead** [haugene/docker-transmission-openvpn#323]
Probably a dumb question, but here you go... 

For the more paranoid people here, is there a way that we can confirm/validate that Transmission is indeed operating behind the VPN properly?  Is there a kill switch if I lose connection with the VPN? 

I've been running this for a month or so and just want to confirm that I'm behind my VPN.  

If I run ifconfig from the container, it's only going to show me my local docker bridge IP.

**Comment by 4Ply** [comment]
How about
> docker exec <your_container_name> curl ifconfig.co/json

**Comment by haugene** [comment]
You could use a service like http://ipmagnet.services.cbcdn.com or http://test.torrentprivacy.com/ to download a test torrent to see your IP. As for the kill switch, the container is set up with up and down scripts from openvpn that starts and stops transmission when the tunnel interface goes up and down. That way transmission is only running while the tunnel is up.
