### ISSUE TITLE
Possible to use plugins?

### ISSUE THREAD

**Issue by burton666** [haugene/docker-transmission-openvpn#327]
When using the regular transmission client there where some more options where you could install plugins etc. I really found labels useful so that I could choose where to save torrents directly from the web-browser. Like ISO, Ebook, Music etc. Is this possible to enable somehow in this version?

**Comment by haugene** [comment]
How do you usually install plugins? I guess it's a matter of dropping some files in a specified directory, maybe with some config? In that case you could just mount that into this container and it should work. If you specify which plugin you want to use, and what the regular setup would be, it would be easier to provide some pointers.
