### ISSUE TITLE
Receiving AUTH_FAILED message during connection to Nord VPN

### ISSUE THREAD

**Issue by RemotecUK** [haugene/docker-transmission-openvpn#329]
Not sure if I am doing something wrong here but I keep getting AUTH_FAILED messages during the start-up of the container.

Here is my docker command...

```
docker run -it --cap-add=NET_ADMIN --device=/dev/net/tun \
-v /mnt/ds01/downloads/:/data \
-v /etc/localtime:/etc/localtime:ro \
-e "OPENVPN_PROVIDER=NORDVPN" \
-e "OPENVPN_CONFIG=de70.nordvpn.com.udp1194" \
-e "OPENVPN_USERNAME=****@gmail.com" \
-e "OPENVPN_PASSWORD=********" \
-e "OPENVPN_OPTS=--auth-user-pass --auth-nocache --inactive 3600 --ping 10 --ping-exit 60" \
-p 9091:9091 \
haugene/transmission-openvpn
```

And here is a sample of the start up messages I get...

```
Sun Oct 29 15:36:09 2017 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
Sun Oct 29 15:36:09 2017 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sun Oct 29 15:36:09 2017 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Sun Oct 29 15:36:09 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun Oct 29 15:36:09 2017 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun Oct 29 15:36:09 2017 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun Oct 29 15:36:09 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]185.130.205.167:1194
Sun Oct 29 15:36:09 2017 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sun Oct 29 15:36:09 2017 UDP link local: (not bound)
Sun Oct 29 15:36:09 2017 UDP link remote: [AF_INET]185.130.205.167:1194
Sun Oct 29 15:36:09 2017 TLS: Initial packet from [AF_INET]185.130.205.167:1194, sid=22f281a7 2fe0a88b
Sun Oct 29 15:36:09 2017 VERIFY OK: depth=1, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=de70.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
Sun Oct 29 15:36:09 2017 VERIFY KU OK
Sun Oct 29 15:36:09 2017 Validating certificate extended key usage
Sun Oct 29 15:36:09 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sun Oct 29 15:36:09 2017 VERIFY EKU OK
Sun Oct 29 15:36:09 2017 VERIFY OK: depth=0, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=de70.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
Sun Oct 29 15:36:11 2017 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Sun Oct 29 15:36:11 2017 [de70.nordvpn.com] Peer Connection Initiated with [AF_INET]185.130.205.167:1194
Sun Oct 29 15:36:12 2017 SENT CONTROL [de70.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Sun Oct 29 15:36:12 2017 AUTH: Received control message: AUTH_FAILED
Sun Oct 29 15:36:12 2017 SIGTERM received, sending exit notification to peer
Sun Oct 29 15:36:15 2017 SIGTERM[soft,exit-with-notification] received, process exiting
```

I've tried a number of different servers at the provider and combination of both TCP and UDP but with no success. Am I missing something obvious?

Many thanks.

**Comment by haugene** [comment]
AUTH_FAILED should mean a wrong username/password. Sure you're using the right one? Providers sometimes have different credentials for the openvpn connection options as opposed to the app etc.

**Comment by RemotecUK** [comment]
Hi, I even reset it in Nord VPN and tried again. Agreed they probably have a different password but their website doesn't seem to show any different settings for Open VPN. Will investigate further.

**Comment by niXta1** [comment]
NordVPN uses the same as the login as on their website.

**Comment by echaupynx** [comment]
Hi! Try the solution from @RiverRat205 and comment out PUID and GUID in your config file. Then delete the containers, restart and hopefully should work for you as it did for me

**Comment by haugene** [comment]
Reopen if you still have an issue with this. 

Also, I just figured that it might have to do with the templating engine if you have special characters in your username or password. In that case you can try mounting the credentials file directly or put it in a persistent volume which is possible after #377. That feature is only on the dev branch for now.

**Comment by 0xcaff** [comment]
@echaupynx What solution from @RiverRat205 ?

**Comment by 0xcaff** [comment]
I got it to work by deleting and re-creating the containers.

**Comment by sourcx** [comment]
I have had the problem that my password worked on nordvpn.com but got `Received control message: AUTH_FAILED` during VPN connection. Then changed it to a simpler password on the website and that did work.

**Comment by haugene** [comment]
Only thing that comes to mind are the special characters and that they need to be escaped. I would guess that's definitely the case if the passord contains ". Could be interesting to find out more if someone wants to dig a little deeper.

After starting the container you can check the contents of /config/openvpn-credentials.txt, that will be used by openvpn to connect.

And as mentioned earlier, this file can be mounted directly to omit passing them as arguments.

**Comment by claytonrothschild** [comment]
I can confirm that using NordVPN one must use the regular credentials (email/password) rather than the API credentials that Nord gives you. Additionally, I received AUTH_FAIL until I removed the `!` character from my password and ensured no special characters were in my password.

**Comment by bartzz** [comment]
If anyone has this issue with **NordVPN**, you need to get your username and password from their website.

![gdWAxjdVXb](https://user-images.githubusercontent.com/7526930/132647565-8f918d41-d141-4142-b388-a4da65593e4c.png)

That fixed it for me!

**Comment by blachanc** [comment]
Thank you,
this is still true in Jan 2024  
the interface to get the token changed a bit:

![image](https://github.com/haugene/docker-transmission-openvpn/assets/7138887/720e2c0e-67d0-4e30-be87-0dd7f8fbda01)

then at the complete bottom of the page:
 
![image](https://github.com/haugene/docker-transmission-openvpn/assets/7138887/f2b91b7a-f3dc-47e0-a60f-7b81b2704f44)

Again,
Many thanks !!
Ben
> If anyone has this issue with **NordVPN**, you need to get your username and password from their website.
> 
> ![gdWAxjdVXb](https://user-images.githubusercontent.com/7526930/132647565-8f918d41-d141-4142-b388-a4da65593e4c.png)
> 
> That fixed it for me!

**Comment by gadamba** [comment]
Even with their username and password from their website, problem persists. Same errors as the initial post in this thread. No mistakes done in the setup

**Comment by bpoole6** [comment]
7 years later and this is still an issue. I'm experiencing the same issue. I'll also add this problem is not consistent. Sometimes when it authenticates just fine but other times it fails. What I ended up doing is creating a for loop trying nord vpn servers until the  creds worked. [https://nordvpn.com/ovpn/](https://nordvpn.com/ovpn/)  

You can download the files programatically `https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/<host_name>.udp.ovpn`

example: `curl https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ad1.nordvpn.com.udp.ovpn`

This isn't the best solutions because for smaller regions I might not authenticate on none of the servers. 😩
