### ISSUE TITLE
How to Run 2 Separate Instances

### ISSUE THREAD

**Issue by rammjet** [haugene/docker-transmission-openvpn#330]
I'm using docker-compose.  I have 2 separate docker-compose documents/directories set up with some different parameters.  I would like to run 2 separate Instances of Transmission and OpenVPN.  What modifications would be necessary to allow them to work simultaneously?  Particularly, naming changes.  Thank you.

**Comment by rammjet** [comment]
I found my answer.  I set up 2 transmission services with different names in the docker-compose.yml and eliminated the proxy which would have needed editing so that it would also listen on 8081 or some other port.

**Comment by haugene** [comment]
Good stuff! You should be able two run two proxies as well though, just map the second one to a different port on your host and it should be OK.

**Comment by rammjet** [comment]
When I tried that, it would knock out the first one.  I don't need the proxy.  I can just access the IP of the host with different ports for transmission.
