### ISSUE TITLE
Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:1: block-outside-dns (2.4.4)

### ISSUE THREAD

**Issue by izznogooood** [haugene/docker-transmission-openvpn#333]
I had some permission issues with Ovpn on arch and I accidentally came across this error in the journal:

nov. 06 16:59:47 yoga nm-openvpn[2831]: Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:1: block-outside-dns (2.4.4)

Deprecated instruction?

**Comment by haugene** [comment]
Might be. Which provider are you using?

**Comment by izznogooood** [comment]
Nordvpn.

**Comment by haugene** [comment]
The NordVPN configs have now been updated through #346.
Can you test again and see if that solves your problem? It's not yet merged to master, so you need to run the dev tag of the image.

**Comment by izznogooood** [comment]
No errors! ;)

I had some issues, and found a broken symlink:
https://github.com/haugene/docker-transmission-openvpn/pull/350

**Comment by haugene** [comment]
Great! I'll merge the PR and close this. Thanks for the fix ;)
