### ISSUE TITLE
TRANSMISSION_PEER_CONGESTION_ALGORITHM value required

### ISSUE THREAD

**Issue by ramonsmits** [haugene/docker-transmission-openvpn#335]
I wanted to not have my docker autostart at start and wanted to edit it but now it wants me to enter a value for `TRANSMISSION_PEER_CONGESTION_ALGORITHM `:

![image](https://user-images.githubusercontent.com/152998/32536602-754db228-c45f-11e7-87a3-30f18de6a0a9.png)

What value should it be set to?

**Comment by etheld** [comment]
I had the same problem, I just removed it, so it went back to default I guess, same for the next field.

**Comment by rcork** [comment]
I just put "" in the field and it let me save and didn't have any impact. When i deleted it i got errors on startup.

**Comment by haugene** [comment]
My settings.json has `"peer-congestion-algorithm": ""`. Looks like you're running it on a NAS, not sure why they don't accept empty variables but they should :)
