### ISSUE TITLE
Are the firewall and local_network features mutually exclusive?

### ISSUE THREAD

**Issue by mpt245** [haugene/docker-transmission-openvpn#340]
I'm setting this up on a QNAP NAS, which requires local traffic be enabled since its drives are only accessible as network drives.  

But, I'm also trying to get "kill switch" functionality - if my PIA connection drops for any reason, I want all my traffic to stop as well.  

If I enable the firewall AND pass a local_network, will I get the functionality I described above? [local traffic allowed, but kill switch for traffic leaving the local network on VPN disconnect]

Thanks for any insight!

**Comment by haugene** [comment]
They're not mutually exclusive as far as I know. There's [configuration](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L76) opening the transmission RPC port if the firewall is enabled.

The kill switch is not related to this. That is managed as openvpn up/down scripts. When the openvpn interface goes up, transmission is started. And if the interface goes down it is killed. You might lose connectivity, but as long as the interface is up traffic will be tunneled through it and we only need to stop transmission if the tun interface goes down and the ip rules are removed.
