### ISSUE TITLE
addr add failed: external program exited with error status: 2

### ISSUE THREAD

**Issue by CyberSardinha** [haugene/docker-transmission-openvpn#344]
I've tried multiple times but I always get this error when running this... Can anyone help me?

`Fri Nov 17 23:27:09 2017 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
Fri Nov 17 23:27:09 2017 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Fri Nov 17 23:27:09 2017 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
Fri Nov 17 23:27:09 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Nov 17 23:27:09 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]5.62.38.11:553
Fri Nov 17 23:27:09 2017 Socket Buffers: R=[212992->212992] S=[212992->212992]
Fri Nov 17 23:27:09 2017 UDPv4 link local: (not bound)
Fri Nov 17 23:27:09 2017 UDPv4 link remote: [AF_INET]5.62.38.11:553
Fri Nov 17 23:27:09 2017 TLS: Initial packet from [AF_INET]5.62.38.11:553, sid=6c9fbd67 d28411d2
Fri Nov 17 23:27:09 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Nov 17 23:27:09 2017 VERIFY OK: depth=1, C=UK, ST=London, L=London, O=Privax Ltd, OU=HMA Pro VPN, CN=hidemyass.com, emailAddress=info@privax.com
Fri Nov 17 23:27:09 2017 VERIFY OK: nsCertType=SERVER
Fri Nov 17 23:27:09 2017 VERIFY OK: depth=0, C=UK, ST=London, L=London, O=Privax Ltd, OU=HMA Pro VPN, CN=server, emailAddress=info@privax.com
Fri Nov 17 23:27:09 2017 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Fri Nov 17 23:27:09 2017 [server] Peer Connection Initiated with [AF_INET]5.62.38.11:553
Fri Nov 17 23:27:10 2017 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Fri Nov 17 23:27:10 2017 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 100.120.0.1,redirect-gateway def1,ping 9,ping-restart 30,explicit-exit-notify 1,route-gateway 100.120.48.1,topology subnet,redirect-gateway def1,ifconfig-ipv6 2001:db8:123::2/64 2001:db8:123::1,route-ipv6 2000::/3 2001:db8:123::1,explicit-exit-notify 2,compress lzo,ifconfig 100.120.49.29 255.255.252.0,peer-id 1,cipher AES-256-GCM'
Fri Nov 17 23:27:10 2017 Option 'explicit-exit-notify' in [PUSH-OPTIONS]:5 is ignored by previous <connection> blocks 
Fri Nov 17 23:27:10 2017 Option 'explicit-exit-notify' in [PUSH-OPTIONS]:11 is ignored by previous <connection> blocks 
Fri Nov 17 23:27:10 2017 OPTIONS IMPORT: timers and/or timeouts modified
Fri Nov 17 23:27:10 2017 OPTIONS IMPORT: explicit notify parm(s) modified
Fri Nov 17 23:27:10 2017 OPTIONS IMPORT: compression parms modified
Fri Nov 17 23:27:10 2017 OPTIONS IMPORT: --ifconfig/up options modified
Fri Nov 17 23:27:10 2017 OPTIONS IMPORT: route options modified
Fri Nov 17 23:27:10 2017 OPTIONS IMPORT: route-related options modified
Fri Nov 17 23:27:10 2017 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Fri Nov 17 23:27:10 2017 OPTIONS IMPORT: peer-id set
Fri Nov 17 23:27:10 2017 OPTIONS IMPORT: adjusting link_mtu to 1625
Fri Nov 17 23:27:10 2017 OPTIONS IMPORT: data channel crypto options modified
Fri Nov 17 23:27:10 2017 Data Channel: using negotiated cipher 'AES-256-GCM'
Fri Nov 17 23:27:10 2017 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Nov 17 23:27:10 2017 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Nov 17 23:27:10 2017 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
Fri Nov 17 23:27:10 2017 GDG6: remote_host_ipv6=n/a
Fri Nov 17 23:27:10 2017 ROUTE6: default_gateway=UNDEF
Fri Nov 17 23:27:10 2017 TUN/TAP device tun0 opened
Fri Nov 17 23:27:10 2017 TUN/TAP TX queue length set to 100
Fri Nov 17 23:27:10 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=1
Fri Nov 17 23:27:10 2017 /sbin/ip link set dev tun0 up mtu 1500
Fri Nov 17 23:27:10 2017 /sbin/ip addr add dev tun0 100.120.49.29/22 broadcast 100.120.51.255
Fri Nov 17 23:27:10 2017 /sbin/ip -6 addr add 2001:db8:123::2/64 dev tun0
Fri Nov 17 23:27:10 2017 Linux ip -6 addr add failed: external program exited with error status: 2
Fri Nov 17 23:27:10 2017 Exiting due to fatal error`

Thank you

**Comment by haugene** [comment]
My first thought is that it looks like IPv6 is enabled, which might case various issues with Docker depending on platform etc etc. You could try disabling that and see if it works?

**Comment by CyberSardinha** [comment]
Thank you for your answer.

I tried to do that but I don't think I managed to do it... I'm new to docker

**Comment by CyberSardinha** [comment]
So.. I managed to disable ipv6 on the host system to see if it helps but it didn't... I struggling to figure out if I can do it on the container itself

**Comment by haugene** [comment]
See #279
