### ISSUE TITLE
Bundle the Kettu web UI

### ISSUE THREAD

**Issue by haugene** [haugene/docker-transmission-openvpn#345]
After #255 the container supports third party web ui for transmission. #318 adds the Combustion UI and [kettu](https://github.com/endor/kettu) was suggested as another great UI. Should be bundled in the same way as Combustion, but we might consider changing the `ENABLE_COMBUSTION_UI` variable to `TRANSMISSION_WEB_UI` and then letting `combustion` and `kettu` be the config value.

If anyone want to contribute with this feature, that would be great.

**Comment by izznogooood** [comment]
I will have a look as this, this weekend.

**Comment by haugene** [comment]
Thanks for wanting to contribute. That would have been great, but I should have closed this. Merged some days ago :) #348
