### ISSUE TITLE
/data vs /downloads

### ISSUE THREAD

**Issue by izznogooood** [haugene/docker-transmission-openvpn#353]
I use sonarr and radarr, they both use /downloads. The problem I have switching to docker-transmission-openvpn is that both sonarr/radarr automatically searches the downloaders (in this case docker-transmission-openvpn) given download folder /data.

This folder does not exist in the sonarr/radarr container. I dont think I can solve this without building my self and adding /data to both sonarr and radarr or vice versa adding /downloads to docker-transmission-openvpn.

Would you consider implementing an option for a /download ? Should be just an extra VOLUME as you allready have the ability to set folders through all (christ all mighty) environment.

**Comment by haugene** [comment]
You can dynamically add volumes using `docker run -v /downloads ...` and then use `--volumes-from ... ` to make them accessible in other containers. I think that will solve your issue without changing the image.

**Comment by ronaldmexico** [comment]
@izznogooood have you tried making use of Sonarr's _Remote Path Mappings_ under the _Download Client_ section?  That's what I use to make it work with transmission-openvpn and nzbget containers although I don't have Sonarr containerized yet.

**Comment by izznogooood** [comment]
@haugene That works, I was unaware  of the possibility to dynamically add volumes.

@ronaldmexico That would not work as both run in separate containers, meaning they dont have access to the same physical locations (if run as "intended"). Thanks

**Comment by jfdhuiz** [comment]
You could use symlinks as well (junction on Windows)

**Comment by haugene** [comment]
This is resolved, right? Re-open if you still have issues.
