### ISSUE TITLE
Readme.md Hint to check which external IP transmission is using

### ISSUE THREAD

**Issue by echaupynx** [haugene/docker-transmission-openvpn#357]
Hi guys! I had some problems with the VPN connection. I did not know that, the container resorts to a default VPN connection if an error occurs within the config file. 
This meant in my case that a mistake in the vpn config name, would lead to a connection somewhere in The Nederlands. The container would work so I only got onto this after a couple of months.

Please consider putting a small paragraph in the Readme.md and a link to http://ipmagnet.services.cbcdn.com or similar service.
This creates a unique Magnet link, which one can add to transmission and immediately get the external IP Address used by Transmission to connect to the Internet.

Thanks !

**Comment by jfdhuiz** [comment]
Useful.

https://ipleak.net does the same though when you visit either of these websites in your browser, its over your regular connection.

I recommend the ENABLE_UFW variable, ie. ENABLE_UFW=true

You might also wanna configure DNS --dns xx.xx.xx.xx

The documentation covers both but suggests to use Google DNS which might constitute a DNS leak.

For me, my VPN also runs a DNS server which is pushed. At your option you could run a Pi-Hole or DNSCrypt(-proxy).

**Comment by haugene** [comment]
That's an unintended side effect of the default.ovpn stuff. The script should choose default config if no `OPENVPN_CONFIG` parameter is given. However, if a file name is specified and it doesn't exist we should not fallback to default but exit with an error message.
