### ISSUE TITLE
Cleanup README and move most of the documentation to wiki

### ISSUE THREAD

**Issue by haugene** [haugene/docker-transmission-openvpn#362]
There is a section with known issues, tips and tricks. This should be rewritten/extended and maybe renamed to FAQ. Also it should be referenced from the top, so people know to look there.

Stuff to include:
- Default values when running on a NAS #360 #335 #339 
- How to check container IP behind VPN #357 #323
- Somehow make it clearer how to make the container accessible from outside local network #354 #289 

Anything else?

**Comment by viamin** [comment]
Might this be easier to maintain in a wiki?

**Comment by haugene** [comment]
Yes, in general I agree. The README is big enough as it is and should contain the essentials to get up and running. Then the rest could be put in a wiki. Same as I've tried to do with the gitter chat to avoid issues being created when there's not a bug with the container, but just people needing help to get going.

Just unsure how much "other stuff" to maintain besides the code ;) Got some suggestions for a good wiki platform? Are there free hosted solutions, or is it better to host an open source alternative?

**Comment by viamin** [comment]
Any reason not to use the GitHub wiki? https://github.com/haugene/docker-transmission-openvpn/wiki

**Comment by haugene** [comment]
Hi. Sorry about the late reply, but of course. Over engineering alert 😄 

I agree, rewriting/simplifying the README and moving all the tips/tricks/quirks and advanced stuff to the wiki would be a big improvement.

If someone is up for it - the rewards would be minimal - but the credz would be overwhelming ;)

**Comment by zoispag** [comment]
I have a slightly better idea that wiki. Github pages. Happy to help @haugene
