### ISSUE TITLE
Feature request: NAT for everyone

### ISSUE THREAD

**Issue by himred** [haugene/docker-transmission-openvpn#367]
Hello,

First of all thanks for this amazing container, I use it everyday.
I'm not sure if this request will be accepted as it may be considered out of scope of the container purpose.

I use your container for 2 purposes,:
- The main one: use transmission over vpn
- The second one: as this container already set up a vpn, i can be used as a gateway for other containers if they ever need to use the vpn.

In short, some of my other containers have a static route to this one when they ever need to access internet via the vpn.
To make it work, I had to run the following command on your container:
`/sbin/iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE`

As by default (which is the good policy) is only NAt for the container itself.

I would be very handy (and easy) to add an option for this purpose, something like:
ALLOWED_NAT_NETWORKS=172.30.30.0/24

This would fire at boot the command:
/sbin/iptables -t nat -s 172.30.30.0/24 -A POSTROUTING -o tun0 -j MASQUERADE

And before you refuse arguing this is out of the scope of this container, keep in mind that some VPN providers allow only one VPN up, meaning when used by your container, we cannot use it anymore so it would be fair to allow other container to use the only allowed VPN we are paying for :)

Regards,

Salim

**Comment by haugene** [comment]
First off, I would think that the easiest way to make other containers go through the VPN of this container is by using the [container network mode](https://docs.docker.com/engine/reference/run/#network-settings) that Docker provides. Just add --network container:<id|name> and the new container will use the network stack of the openvpn container and all traffic flow through there.

If not, there is a pull-request that adds support for pre- and post scripts, where you could include your iptables command. #372 

And there's a proxy coming for all web traffic and other stuff that can use a proxy #256 

But for your use, I think the docker networking trick could do the job

**Comment by alron** [comment]
Docker container mode networking won't work if you enable UFW. Not unless you modify the scripts to support defining a list of ports for UFW #408

**Comment by haugene** [comment]
The pull-request with support for extra ports is merged, so I'm closing this one.
