### ISSUE TITLE
Upload torrent from linked one failed

### ISSUE THREAD

**Issue by egobiah** [haugene/docker-transmission-openvpn#368]
Hello, 

While I was testing the app i've just found that we cannot send torrent from mobile phone.
Actually, while accessing to transmission from android navigator, we can't upload any file then we had to past the torrent link.

Then, transmission justed return me the error : "gotMetadataFromURL: http error 503: Service Unavailable".
I can't see any variable about metadata from url.

Any of you can upload file from "pasting" torrent link ?

Thank you,

ps : I'm running it on armhf
pss: Sorry for the bad english

**Comment by haugene** [comment]
Hey. Sorry for not getting back to you on this. If you still have an issue with this, or anyone else stumbles on the issue. I don't think Transmission supports URLs directly to a torrent file, so is this a magnetic link or a link to .torrent? Also, check if it can be a DNS error - many connection errors in the container comes from missing DNS config.

Closing for now. Re-open if needed.
