### ISSUE TITLE
TRANSMISSION_PROXY_... settings are omitted?

### ISSUE THREAD

**Issue by mgrandl** [haugene/docker-transmission-openvpn#370]
Everything else is working just fine, but not the proxy entries. They won't be added to the settings.json. Please help.

**Comment by mgrandl** [comment]
Ok upon further research it appears the transmission devs killed support for proxies...

**Comment by nicbou** [comment]
As an important note for anyone reading this in the future: Transmission has a peculiar behaviour with settings. If I recall correctly, settings are saved on exit, so if you run Transmission, change the settings, then restart transmission, your changes will be overwritten.

This is not related to your issue, but it's a common question regarding transmission.
