### ISSUE TITLE
Please update Cryptostorm openvpn config files

### ISSUE THREAD

**Issue by HotBlack77** [haugene/docker-transmission-openvpn#371]
The VPN provider Cryptostorm has updated their CA certificate, which means all clients need to switch to the new one.  The config files, with embedded certificates, used in this docker expired today and consequently openvpn can not connect when using cryptostorm as a VPN provider. 

This should be fixable by simply replacing the files in the /openvpn/cryptostorm/ directory with these new ones (from Cryptostorm's repo): https://github.com/cryptostorm/cryptostorm_client_configuration_files/tree/master/linux

BTW: Thanks for a great container.

**Comment by microbug** [comment]
I also ran into this problem and made a [new repo that sorts this](https://github.com/microbug/docker-cryptostorm-client). It only handles the VPN but you can link other containers to it (see the README), so you can run (for example) LinuxServer.io's [Transmission container](https://hub.docker.com/r/linuxserver/transmission/) on the VPN. My container updates Cryptostorm's ovpn files automatically so it should never go out of date.
