### ISSUE TITLE
Setting Max Peers Doesn't Work

### ISSUE THREAD

**Issue by clarkent86** [haugene/docker-transmission-openvpn#374]
I have set the max peers above 50 through the environment variable, and I even see it effected when clicking on the peers tab in settings through the UI after the container boots, but none of my downloads will go above the default 50.

**Comment by haugene** [comment]
If you see your change reflected in the settings tab in the GUI as you say, then it seems that the container is working correctly and that this has to do with transmission itself.

Just a thought. Have you also increased the global peer limit in case multiple torrents cause it to be the limiting factor as opposed to the per torrent ones?

**Comment by clarkent86** [comment]
I added a couple new torrents and what seems to be happening is that when a torrent gets added the config gets applied depending on what the config is set to when the torrent is added. My pre-existing torrents are maxed at 50, but I added a new torrent since the config change and it's exceeding 50 for those.

**Comment by clarkent86** [comment]
Seems to be confirmed by removing and re-adding the pre-existing torrents.
