### ISSUE TITLE
Support for ProtonVPN (Newer thread)

### ISSUE THREAD

**Issue by bfayers** [haugene/docker-transmission-openvpn#378]
Add VPN support for [protonvpn](https://protonvpn.com/)

**Comment by fabienheureux** [comment]
It seems that it had already been discussed here: https://github.com/haugene/docker-transmission-openvpn/issues/271

**Comment by haugene** [comment]
Yup, this issue is a duplicate of #271. It's higher up the list. Maybe someone will see it if I tag it. And maybe I'll have the time to add it myself as well. Are the links to the other issue still good?

**Comment by coolboiime** [comment]
Closing this for merging into issue #554! Please have all issues and updates directed towards that issue. Closing this for now, thanks!

**Comment by haugene** [comment]
#704 now merged
