### ISSUE TITLE
Rutorrent/Rtorrent

### ISSUE THREAD

**Issue by Pentaganos** [haugene/docker-transmission-openvpn#380]
Hi, 

This is the first container I have used that I was able to connect to with out having to tunnel due to the vpn(remote server)

I was wondering how I would go about doing this for rtorrent/rutorrent as the title says.
Any pointers would be great thanks.

**Comment by a-lagopus** [comment]
Hi, you might look into forks of this project, for instance this one seems to have replaced transmission with qbittorrent, a similar task to what you're trying to do.
https://github.com/hayduck/docker-qBittorrent-openvpn

**Comment by bamtan** [comment]
I recommend binhex's rtorrent-vpn Docker https://github.com/binhex/arch-rtorrentvpn, which as features such as Privoxy and autodl-irssi.

**Comment by coolboiime** [comment]
Looks like this issue seems solved, closing for now.
