### ISSUE TITLE
Peer listening port 'Closed'?

### ISSUE THREAD

**Issue by eroji** [haugene/docker-transmission-openvpn#381]
I don't see this mentioned anywhere but I assume this is normal though I want to confirm. Is this expected behavior for the web UI to show the peer listening port to be in Closed state?

**Comment by tylerburleigh** [comment]
I'm also having this problem.

I told it to use port forwarding, and I also configured port forwarding in my router. It still says closed, and I'm afraid that means I'm in "passive" mode with peers (not good!).

Any advice?

**Comment by tylerburleigh** [comment]
@eroji I think I got it.

I found a related issue in the repository: 
https://github.com/haugene/docker-transmission-openvpn/issues/97

To get the port open you need to setup port forwarding with your VPN provider.

> This means that your vpn provider needs to support port forwarding and it's up to them to have documentation for this. This will be different for every provider. PIA has this support and I've scripted port opening using them because that's the provider I use.

**Comment by eroji** [comment]
The impression I got was that PIA is supported out of the box, and it is also the provider I am using. I Googled the topic and it seems like it is limited to a small set of gateways?

**Comment by eroji** [comment]
The script seems to update the port periodically, but it doesn't always end up showing "Open" for the port it selects? Is this expected for the way the script works?

**Comment by spede** [comment]
I had trouble with PIA + Port Forwarding as well. Often times when starting the container it would not forward the port. After some testing, and some reading, I found out the new PIA port forwarding API is only available for 2 minutes after you connect to the tunnel -- after 2 minutes, you get the "curl error".

Furthermore I think the port forward request is sent too early, possibly before the tunnel is up and ready (or maybe the PIA port forward API needs a second or two to do something behind the scenes...). I tossed a `sleep 15` before `updatePort.sh` is executed in `start.sh` and so far the port has been forwarded correctly every time over a period of a week or two. This used to be almost an every day problem before.

**Comment by eroji** [comment]
That's interesting information. I will give your modification a try.

**Comment by haugene** [comment]
Thanks @spede, I added that change to the dev branch now. Would be great if that makes the script stable. This has been a recurring problem.

**Comment by haugene** [comment]
The fix that was added to the port update script for PIA has been merged to master and is included in the lastest tag of this image. Closing this.
