### ISSUE TITLE
Could not connect to tracker under OpenVPN

### ISSUE THREAD

**Issue by woomg** [haugene/docker-transmission-openvpn#385]
The Transmission does not work with OpenVPN.
Transmission show up the message like
```
Announce error: Could not connect to tracker - Today 09:16:32 PM
Next announce in 24 minutes
Scrape error: Could not connect to tracker - Today 09:09:50 PM
```

Here is my container startup command.
```
$ docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \
--driver bridge \
-v /storage/config/:/config \
-v /storage/data/:/data \
-v /etc/localtime:/etc/localtime:ro \
-e "OPENVPN_PROVIDER=NORDVPN" \
-e "OPENVPN_CONFIG=kr4.nordvpn.com.tcp" \
-e "OPENVPN_USERNAME=user" \
-e "OPENVPN_PASSWORD=pass" \
-e "LOCAL_NETWORK=192.168.0.0/24" \
-e "ENABLE_UFW=true" \
--log-driver json-file \
--log-opt max-size=10m \
--dns 8.8.8.8 \
--dns 8.8.8.4 \
-p 9091:9091 \
haugene/transmission-openvpn

```

When I ping to anywhere, I cannot receive any packet from outside.
 
[openvpn.log](https://github.com/haugene/docker-transmission-openvpn/files/1615130/openvpn.log)

**Comment by woomg** [comment]
Never mind. It's NordVPN problem.
It does not allow port forwading, so I changed peer port to 1080 and login to specific server.

**Comment by noweverywhere** [comment]
@woomg can you elaborate a bit on how you solved the problem?
