### ISSUE TITLE
PIA: CA Vancouver and CA Montreal sites missing

### ISSUE THREAD

**Issue by millercentral** [haugene/docker-transmission-openvpn#388]
Hello, and thanks for your hard work on this project!

A couple of sites on PIA that support port forwarding appear to be absent from the container configurations, specifically:

CA Montreal  (ca.privateinternetaccess.com) - this may be called "CA North York" currently?
CA Vancouver (ca-vancouver.privateinternetaccess.com)

Would it be possible to add these? Thanks!

**Comment by haugene** [comment]
Closing this as the configs have now been added. Thanks to @eugenioseveri for providing the update.
