### ISSUE TITLE
Add support for IPVanish

### ISSUE THREAD

**Issue by IrishCubsFan** [haugene/docker-transmission-openvpn#39]
Can you add support for IPVanish?

Configs can be found at: https://www.ipvanish.com/software/configs/

**Comment by haugene** [comment]
Yep, added it now. Tested locally and it seems to work, at least until I get an AUTH_FAILED message.
Try running the container as described in README, but use the dev tag. That is; haugene/transmission-openvpn:dev

Let me know if it works so that I can update the README and merge to master.

**Comment by haugene** [comment]
@IrishCubsFan ping

**Comment by haugene** [comment]
Expecting it to work, merged to master and closing issue. Open new issue if there are bugs for this provider.
