### ISSUE TITLE
Port not exposed on hosts external interface

### ISSUE THREAD

**Issue by YoloClin** [haugene/docker-transmission-openvpn#390]
Hi all, new to docker to apologies if there is an obvious solution, I've also searched open issues and cannot find any existing threads. I wish to setup a transmission docker container on a server accessible from other machines on the local network. I have the following startup script:
```
docker run \
       --name "downloader" \
       -v /var/downloads:/data \
       -v /etc/localtime:/etc/localtime:ro \
       --log-driver json-file \
       --log-opt max-size=10m \
       -p 9092:9091 \
       --device=/dev/net/tun -d \
       --cap-add=NET_ADMIN \
       -e "OPENVPN_PROVIDER={HIDDEN}" \
       -e "OPENVPN_CONFIG={HIDDEN}" \
       -e "OPENVPN_USERNAME={HIDDEN}" \
       -e "OPENVPN_PASSWORD={HIDDEN}" \
       -e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true" \
       -e "TRANSMISSION_RPC_USERNAME=transmission" \
       -e "TRANSMISSION_RPC_PASSWORD={HIDDEN}" \
       -e "TRANSMISSION_RPC_WHITELIST_ENABLED=true" \
       -e "TRANSMISSION_RPC_WHITELIST=*.*.*.*" \
       haugene/transmission-openvpn
```

On starting up, I'm able to access transmission via http://localhost:9092/transmission/web/ and http://172.17.0.2:9091/ on the server. I am also to access via the servers network IP for a period of seconds shortly after restarting the container, after which nmap reports the port as 'filtered' - my guess that OpenVPN is preventing communications with the port as part of its startup process, it could also be a firewall but grepping for iptables within the source returned no results.

Is this a known issue / is there a workaround? I'd like to avoid iptables forward rules if at all possible.

**Comment by haugene** [comment]
Take another crack at the README ;) Specifically https://github.com/haugene/docker-transmission-openvpn#access-the-webui

**Comment by YoloClin** [comment]
Thanks, this solved the issue, sorry I missed that.
