### ISSUE TITLE
Upgrade to 2.93 ASAP to prevent DNS rebinding attack

### ISSUE THREAD

**Issue by aaronjwood** [haugene/docker-transmission-openvpn#392]
https://github.com/transmission/transmission/pull/468

Hopefully 2.93 will be released soon...

**Comment by nebhead** [comment]
Might I also suggest adding details on how to set the RPC login and password in the readme, after this has been patched.

**Comment by aerickson** [comment]
Ubuntu has a patched version available.

https://github.com/haugene/docker-transmission-openvpn/pull/395

**Comment by Mikiya83** [comment]
Do you have any news about a release with the 2.93 update ? It's a major security update :/

**Comment by haugene** [comment]
FYI. The software source change made in #395 is now reverted due to errors #418. You can still run the patched ubuntu version from tag 1.20, but we're still waiting for the ppa to have a patched version and when it is released we need to add README instructions if configuration breaks the default run command.

**Comment by haugene** [comment]
2.93 is now released (https://launchpad.net/~transmissionbt/+archive/ubuntu/ppa). Activated the ppa repository and pushed to dev.

**Comment by nebhead** [comment]
Just a suggestion here, but can we add instructions to the dockerhub on how to setup a username/password for remote access so that we can fully mitigate the security issue here?

**Comment by haugene** [comment]
@nebhead, you mean rpc authentication? If so, check the gitter chat.
Fix is now merged to master and the latest tag is on Transmission version 2.93, closing this.
