### ISSUE TITLE
Docker for windows?

### ISSUE THREAD

**Issue by stevemk14ebr** [haugene/docker-transmission-openvpn#399]
Does this work with docker for windows? I've got it to the point where i can access the transmission webUI but all dns lookups fail. If i trying pinging google from bash i get

> docker exec -it vpn /bin/bash
root@a242509bf549:/# ping www.google.com
ping: unknown host www.google.com

I did try with the --dns flags you recommended too.

**Comment by drewh1991** [comment]
I'm getting the same issue using W10 Pro. It would be really great if this could work for Windows. Has anybody else had any luck?

**Comment by stevemk14ebr** [comment]
Glad you managed to solve it! Unforunately i still seem to have issues, my logs:

> Fri Jan 26 06:03:55 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
Fri Jan 26 06:03:55 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Fri Jan 26 06:03:55 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Jan 26 06:05:15 2018 RESOLVE: Cannot resolve host address: ca-toronto.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Fri Jan 26 06:06:35 2018 RESOLVE: Cannot resolve host address: ca-toronto.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Fri Jan 26 06:06:35 2018 Could not determine IPv4/IPv6 protocol
Fri Jan 26 06:06:35 2018 SIGUSR1[soft,init_instance] received, process restarting
Fri Jan 26 06:06:40 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Jan 26 06:08:00 2018 RESOLVE: Cannot resolve host address: ca-toronto.privateinternetaccess.com:1198 (Temporary failure in name resolution)

**Comment by haugene** [comment]
So it's still a DNS problem. What is the content of your `/etc/resolv.conf` in the container? Could be that Docker on Windows isn't setting the dns servers correctly. With the dns flags set the contents should be:
```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

If it isn't, try creating that file and mounting it to `/etc/resolv.conf`

**Comment by stevemk14ebr** [comment]
docker exec transmission less /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4

Is it possible my docker itself is messed up. Perhaps the virtual adapters or something is misconfigured? I don't really know what else to check

**Comment by stevemk14ebr** [comment]
I GOT IT! My school blocks google's nameservers apparently. To fix i did this:

on windows 10 host: nslookup *insert public ip*
the two ip's that resulted i put as the ip's for the --dns flags to the following command:

> docker run --cap-add=NET_ADMIN --privileged="true" --device=/dev/net/tun --name="transmission" --dns 157.182.203.110  --dns 72.50.144.171 -d -v E:\Torrents\Temp:/data -e "OPENVPN_PROVIDER=PIA" -e "OPENVPN_CONFIG=CA Toronto
" -e "OPENVPN_USERNAME=p8153474" -e "OPENVPN_PASSWORD=4o9Vt6NGbj" --log-driver json-file --log-opt max-size=10m -p 9091:9091 haugene/transmission-openvpn

**Comment by stevemk14ebr** [comment]
Ok new port-forwarding issue: 

> STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Fri Jan 26 19:23:47 2018 Initialization Sequence Completed
Generating new client id for PIA
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 56
PS C:\WINDOWS\system32> docker exec transmission ping www.google.com
ping: unknown host www.google.com
PS C:\WINDOWS\system32> docker exec transmission /etc/transmission/updatePort.sh
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 56

Is it related to this post by pia?:
https://www.privateinternetaccess.com/forum/discussion/23431/new-pia-port-forwarding-api

> We've recently introduced a new port forwarding API. This one's simpler, more reliable, and will be replacing the port forwarding API all of you fine folks currently use.

**Comment by haugene** [comment]
It's related. After upgrading to the new script it sometimes gives you this message. And it's exactly as it says. You have either connected to a location that doesn't support port forwarding or you've already requested a port from that connection (at least it thinks). I've found that I can get this error if I restart my container too many times and just have to wait a little and it starts working again. The old port is probably flushed after some delay.
