### ISSUE TITLE
Metadata not being downloaded. stuck Retrieving metadata. 

### ISSUE THREAD

**Issue by aprillia99** [haugene/docker-transmission-openvpn#403]
have 30-40 torrent that is stuck retrieving metadata. Other torrents work fine. They are typically the torrents that are hard to find as well.

I am using PIA, and I have opened my ports and tried uPNP. I have also tried to disable uTP still nothing. When I run transmission-remote --port-test it says my port is open.  Any thoughts?

**Comment by haugene** [comment]
I'm blank, and seems this issue has been stale for a while. Any news?
Never had a problem with it and as long as other torrents are working then I think the container is working as it should. Have you tried these torrents in a non-containerized environment, do they work there. Need to check this to be sure this is an issue with the container itself. Closing for now, reopen if you have something that points to the container and not the torrents.

**Comment by CosmicMJ** [comment]
@aprillia99 @haugene I'm having this same issue. Torrents never begin downloading, perpetually stuck in "downloading metadata". But I haven't been able to get any torrents at all to work. Tested them on a different system and they download fine. Did either of you ever figure anything out with this?

**Comment by JoooostB** [comment]
Does anyone of you manage to fix this issue? I'm experiencing exactly the same.

**Comment by haugene** [comment]
#552, for @JoooostB this was a DNS thing. Could it be the same for you? I see you're not setting dns options in your docker-compose.

**Comment by dhjw** [comment]
In my case transmission-gtk would find peers and metadata download percentage would increase but never get to 100% before dropping back to 0%. I looked in `Help > Message Log` and saw an error `Couldn't save temporary file /home/d/.config/ ...` and `Unable to save torrent file: File name too long.` Simply shortening the filename in the magnet URI and re-adding it to transmission fixed the problem for me.
