### ISSUE TITLE
PureVPN - Update ovpn config files

### ISSUE THREAD

**Issue by ryanlauterbach** [haugene/docker-transmission-openvpn#404]
Update to latest server list files

**Comment by nicomarti83** [comment]
hi, are you sure there is new files?

**Comment by nicomarti83** [comment]
ok please don't add vpn servers that not support p2p file sharing... 
the server list is here : [https://support.purevpn.com/p2p-file-sharing](url)

**Comment by haugene** [comment]
Many new servers added in #406, I suspect that list isn't taken into account

**Comment by nicomarti83** [comment]
hum, I'm just downloaded the file from purevpn (linux-files.zip) and the last modified file date is from 2016... @ryanlauterbach where have you downloaded your "news" files ?

**Comment by ryanlauterbach** [comment]
Yes the linux-files are from 2016.  I have used several servers from a "banned" country over the last few months (including last night) and I was able to torrent fine. The choice of server seems to me a run-time configuration and up to the user to decide. The VPN server list may grow or shrink. Perhaps a disclaimer when start.sh is run to "keep an eye on your providers global p2p policy"?

**Comment by haugene** [comment]
#406 is now on master
