### ISSUE TITLE
how can i rename the path /data/ to /downloads/?

### ISSUE THREAD

**Issue by bamtan** [haugene/docker-transmission-openvpn#405]
i wish to rename the path that is set on Transmission from /data/ to /downloads/, similar to non-VPN other Transmission Dockers (for seamless transferring of torrents/resume files).

how it is currently:

![](https://i.imgur.com/dDxKlol.png) Regular Transmission
![](https://i.imgur.com/VumZEyD.png) Transmission VPN

i also wish to put place the `transmission-home` folder out of my torrents directory, and into the Transmission_VPN Docker directory (I am using Unraid, and Docker files are placed into `/mnt/user/appdata/`

thanks in advance!

**Comment by bamtan** [comment]
Issue solved, just renamed the paths using Transmission Remote GUI.

**Comment by haugene** [comment]
That will reset when container restarts. You should do the same, but with environment variables. And then of course mount `/downloads`as a volume instead of `/data`

**Comment by bamtan** [comment]
Oh, I just transferred my `/resume/` and `/torrents/` files across from non-vpn -> vpn container. So all I had to do was rename /downloads/ to /data/ in the location of torrent path.

**Comment by haugene** [comment]
Ahhh, that's what you meant. Thought you wanted a new default for all new torrents. Should be all good then.
