### ISSUE TITLE
How can I stop logging?

### ISSUE THREAD

**Issue by bamtan** [haugene/docker-transmission-openvpn#407]
I'd like to stop logging into transmission.log, as it is filled with failed IPv6 connection attempts, even though I have IPv6 disabled with `--sysctl net.ipv6.conf.all.disable_ipv6=1`.

Similar issue: https://github.com/transmission/transmission/issues/86

**Comment by haugene** [comment]
I understand that these log statements are unwanted. But I'm not sure I agree that it's is an issue with this container. This is a Transmission configuration issue and the one you are linking to is the one that needs correction. If there's a way to tell transmission not to log these errors, and this container doesn't allow you to set that option, then that's another story. But that seems not to be the case.

We could do stuff to hide them from the logs you get from this Docker container. Like running the transmission log through a filter, to a new log file, and then tailing that to stdout. But it's a hack and it's not the purpose of this container to do that.

Open to other suggestions, but for now transmission logs what it logs and I'm not sure if it's a clean way to fix it outside Transmission itself.

**Comment by bamtan** [comment]
Anyway to remove the logging process completely?

**Comment by haugene** [comment]
We're explicitly setting logging to file: https://github.com/haugene/docker-transmission-openvpn/blob/dev/transmission/start.sh#L42. So we could make a "NO_LOGS" configuration that excludes the `--logfile`option.

It's either that or check with the transmission community if the logging could be configured better.

**Comment by bamtan** [comment]
Alright, thanks!
