### ISSUE TITLE
Solved problems with connections and slow speeds

### ISSUE THREAD

**Issue by m4f1j0z0** [haugene/docker-transmission-openvpn#409]
Hey guys, I have managed to solve all the problems I've had with slow downloads and uploads, failed connections to trackers etc. Here is a short description.

The problems have nothing to do with the docker package or configuration, it's all about your VPN provider. During the past week I have tested IPVanish, NordVPN, ExpressVPN, Vyprvpn, Perfect Privacy and lastly TorGate.

TorGate is the only provider, of the ones mentioned above, to offer static port forwarding. Once I have opened Transmission's peer listening port, my download speeds shot up to 25-30 MB/s, and upload speeds to 5 MB/s (my connection cap). 

After setting up an automatic unpacking script, it's a perfect solution.

If anyone is interested about the exact TorGate steps to open a port and generate an OpenVPN Profile to set-up the custom provider (it doesn't work with the bundled profile), I'd be happy to write a detailed tutorial, just let me know.

**Comment by haugene** [comment]
Glad to hear you've found a good setup. And there has been several issues through the years on the speed one gets through VPN. I have often pointed to the opening of ports and that this is something the VPN provider needs to support. Interesting that you've tried several providers, many so popular, and only one supports it.

Not sure what the right forum is for this kind of discussions. The issues board is temporary, maybe adding some info in the README could be something, or we could set up some sort of wiki-like site to share experiences. But the README should probably contain a disclaimer saying that the speed of torrents often depends on an open port and then hinting to which providers have this ability. Maybe a new column in the providers list. Just some thoughts :)

**Comment by haugene** [comment]
I changed the title to be easier to find it for those googling for slow speeds and how to solve it. This is not an issue per se, so I'll close it. But it's good to have something to refer to for later.

**Comment by tompijls** [comment]
Hi m4f1j0z0,

if you have a short description of the steps that would be appreciated.

Cheers

**Comment by mouzzampk2014** [comment]
> Hey guys, I have managed to solve all the problems I've had with slow downloads and uploads, failed connections to trackers etc. Here is a short description.
> The problems have nothing to do with the docker package or configuration, it's all about your VPN provider. During the past week I have tested IPVanish, NordVPN, ExpressVPN, Vyprvpn, Perfect Privacy and lastly TorGate.
> TorGate is the only provider, of the ones mentioned above, to offer static port forwarding. Once I have opened Transmission's peer listening port, my download speeds shot up to 25-30 MB/s, and upload speeds to 5 MB/s (my connection cap).
> After setting up an automatic unpacking script, it's a perfect solution.
> If anyone is interested about the exact TorGate steps to open a port and generate an OpenVPN Profile to set-up the custom provider (it doesn't work with the bundled profile), I'd be happy to write a detailed tutorial, just let me know.

I am having difficulty achieving 80-90% of my download speed when VPN active and I already forwarded the port :(

**Comment by Muckoma** [comment]
@m4f1j0z0 I'm definitely interested in your detailed guide. Please let me know. Any help would be appreciated
