### ISSUE TITLE
automove Tools Copy Problem

### ISSUE THREAD

**Issue by s-c-o-o-t** [haugene/docker-transmission-openvpn#412]
Hey all seem to have a problem using *copy* method in automove. torrent
Main Dir /home/downloads
In rutorrent i have it set /home/spiderman/Finished to move the downloaded files there, but everytime i edit that box hit Ok then go back its not there, doesnt set it ?
drwxr-xr-x  5 spiderman spiderman 4096 Jan 28 03:23 downloads
drwxr-xr-x 10 spiderman spiderman 4096 Jan 28 03:34 spiderman

now id like the downloaded files from /home/downloads to be able to be copyed to /home/spiderman/Finished

**Comment by coolboiime** [comment]
This issue doesn't seem to be related to this image. You have to set the download directory using that program which you used to download from. Closing for now.
