### ISSUE TITLE
help using vpn for another container and accessing web page via nginx

### ISSUE THREAD

**Issue by Wimma77** [haugene/docker-transmission-openvpn#414]
Firstly, thanks so much - this was easy to set up and get running (on ubuntu server, using PIA). 
Awesome container!!

However, I'm having issues using it for other containers. I've tried a few, and checking their IP it looks like they're successfully linked to the network stack and using the vpn, but I can't hit their web pages.
I tried (and failed, lots) using nginx to reverse proxy, but wondering if this was something you/someone had done already?
Simple example is headphones:

docker create --name="headphones" --net=container:transmission-pia ... etc
docker run -it --name dproxy -p 80:80 --link transmission-pia:headphones -d dperson/nginx  -w "http://headphones:8181;/headphones/"

So it has web client on port 8181, but I can't get it accessible from my 10. LAN range :(
404 Not Found
The path '/headphones/' was not found.

I know this will be simple, but could you please help a noob?
Thanks.

**Comment by haugene** [comment]
Glad to hear that the container is at it's best behaviour ;)

The networking stuff can get tricky. But from your run statements I see at least one thing that doesn't seem right. You're creating the headphones container and attaching it to the network stack of the transmission-pia container. Then this headphones container has a service on port 8181, right? Just a FYI, if you want to expose that port to your host you need to add `-p 8181:8181` to the transmission-pia container as that's the network binding you want to forward.

But in this example you're creating the proxy and using it to proxy traffic to the headphones container instead. That should also work. But the `--link` statement seems off. You're not linking it to the headphones container. You're linking it to the transmission-pia container and calling that link "headphones" inside the dproxy. So the headphones:8181 proxy config will point to the transmission-pia container, and then the 404 makes sense.

I would expect `--link headphones` to be what you're looking for. Not sure if it will work out of the box, but it's closer to the truth ;)

**Comment by Wimma77** [comment]
Thanks for the response.
And yes, this is correct:
> You're creating the headphones container and attaching it to the network stack of the transmission-pia container. Then this headphones container has a service on port 8181, right?

Running a container on it's own with net=host I can expose ports via -p 8181 and all fine, but when using --net=container: to link to the vpn connection that (-p option) is not valid/allowed. 

If I just use --link headphones it runs but get an error 'Sorry, the page you are looking for is currently unavailable.'

Even randomly trying --link transmission-pia:headphones results in
nginx: [emerg] host not found in upstream "headphones" in /etc/nginx/conf.d/default.conf:51

But I'm well beyond my experience - never used nginx, so time to hit up google again and see what I can learn. Was just trying to implement same as awesinine/openvpn-client had (using nginx).
Just thought someone may have already linked another container through your vpn and exposed ports, so I could shortcut some research :)
No worries, appreciate the reply.
Cheers.

**Comment by haugene** [comment]
As far as I know, with net=host you won't need to add -p 8181. It will bind to your host network interface anyways. Only reason to have -p in that case is to mark the port as exposed on the container, for linking purposes and other.

How are you accessing the transmission web interface? Is it through a proxy, or using LOCAL_NETWORK configuration? If you're using LOCAL_NETWORK then that should work for port 8181 as well. So start your transmission-pia container with -p 8181:8181 in addition to the regular transmission port. Then start headphones container with `--net=container:transmission-pia` as you have done, and it should be accessible directly on port 8181 on your host.

**Comment by Wimma77** [comment]
Ok, so after deleting all containers and doing again from scratch, yes, that worked - so simple!! :D 
Thanks for the help. Can hit the web gui now, so will have a play with it.
Will try to recreate with a few more containers and see how it goes.
Cheers.
