### ISSUE TITLE
Torrent File Size

### ISSUE THREAD

**Issue by bentech** [haugene/docker-transmission-openvpn#419]
I have a torrent file size of 1.2MB.

I am using the proxy and get this error message
413 Request Entity Too Large
nginx/1.13.7

**Comment by haugene** [comment]
You're in luck. I'm sitting at my computer and think I know that one ;)
Committed a fix, it's building now: https://hub.docker.com/r/haugene/transmission-openvpn-proxy/builds/

When it's complete, you can try to run the dev tag of the proxy and see if that fixes it...

**Comment by bentech** [comment]
Thanks, I have edited my container with the new file which works. I will try the build next time I do a docker-compose update.

**Comment by haugene** [comment]
Np. I'll leave this issue open until you verify or I get to verify it myself.

**Comment by haugene** [comment]
merged
