### ISSUE TITLE
if you have some time ahead of you, could you please include anonine VPN provider ?

### ISSUE THREAD

**Issue by arakeis** [haugene/docker-transmission-openvpn#42]
here is there configuration files :  https://anonine.com/static/anonine_openvpn.zip

and there installation guide : https://anonine.com/en/guides/openvpn-ubuntu-14.04-64bit  

if you want me to test it, no problem at all of course !

thks

Arnaud

**Comment by haugene** [comment]
Hey Arnaud,

I get this question a lot so I've scripted the whole "new provider thing".
Added anonine now and pushed to dev branch. Once the latest build on docker hub is done you should be able to test it using the dev tag.
Builds are here: https://hub.docker.com/r/haugene/transmission-openvpn/builds/

Let me know how it goes!

**Comment by arakeis** [comment]
Hi Kristian,

Great (speed and all), will report how it goes !

thks

Le mer. 25 nov. 2015 à 16:01, Kristian Haugene <notifications@github.com> a
écrit :

**Comment by haugene** [comment]
No problem. And btw, as you see I recommitted the changes because I fucked up my git config before I pushed the last time ;) So there's a new build in the queue now...

**Comment by arakeis** [comment]
it work's the anonine provider is operational !
thanks !
