### ISSUE TITLE
Synology NAS: Default file attributes problem

### ISSUE THREAD

**Issue by evsasha** [haugene/docker-transmission-openvpn#423]
Hi, what are the default file attributes?

When i run container on Synology Nas with root use i see that:
```
# ls -al /volume1/Transmission-vpn/config/
total 8
d---------+ 1 root         root   106 Feb  8 23:44 .
drwx------+ 1 transmission users   12 Feb  8 23:44 ..
d---------+ 1 root         root     0 Feb  8 23:44 blocklists
d---------+ 1 root         root     0 Feb  8 23:44 resume
----------+ 1 root         root  2299 Feb  8 23:44 settings.json
d---------+ 1 root         root     0 Feb  8 23:44 torrents
----------+ 1 root         root  2192 Feb  8 23:45 transmission.log
```
And all work fine, but when i change user to not root, he can't read file with ----------+ permissions and fails.

```
docker run \
-p 19091:9091 \
--name transmission-openvpn \
--cap-add=NET_ADMIN \
--device=/dev/net/tun \
--restart=always \
--dns 8.8.8.8 \
--dns 8.8.4.4 \
--log-driver json-file \
--log-opt max-size=10m \
-v /volume1/Transmission-vpn:/data \
-v /etc/localtime:/etc/localtime:ro \
-e "OPENVPN_PROVIDER=xxx" \
-e "OPENVPN_CONFIG=xxx" \
-e "OPENVPN_USERNAME=xxx" \
-e "OPENVPN_PASSWORD=xxx" \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
-e "TRANSMISSION_DOWNLOAD_DIR=/data/downloads/complite" \
-e "TRANSMISSION_INCOMPLETE_DIR=/data/downloads/incomplete" \
-e "TRANSMISSION_HOME=/data/config" \
-e "TRANSMISSION_ENCRYPTION=2" \
-e "TRANSMISSION_RATIO_ENABLED=true" \
-e "TRANSMISSION_RATIO=3" \
haugene/transmission-openvpn:latest
```

**Comment by evsasha** [comment]
I found the cause.
The file "settings.json" is created by the user Root, and after that the owner's name changes to PUID (userSetup.sh).
But by default in SYNOLOGIES NAS the user Root creates files with the permissions "---------" and when you make only the chown command you do not change the permissions, but only the owner.

So now u can use only Root user.
Or we need pull request for test and change file attributes after chown command.

**Comment by haugene** [comment]
Merged the PR and added chmod -R to the same paths. It's available on the dev tag now. Would be great if you could verify that it works, and then we can close this issue :)

**Comment by evsasha** [comment]
Hi, i verified that, all works fine.
