### ISSUE TITLE
Provider request: BufferedVPN

### ISSUE THREAD

**Issue by kataik** [haugene/docker-transmission-openvpn#425]
Anybody working on a buffered provider by any chance?

**Comment by haugene** [comment]
I doubt anyone is already working on it, but if you supply a link to where the ovpn files can be found someone might help you out.

**Comment by haugene** [comment]
Re-open this issue when you've provided a link to the ovpn configuration files. Until then I'm closing this issue.

**Comment by RohanHinton** [comment]
Here is an example of the buffered OVPN file. Renamed as .txt for uploading purposes.
[Buffered OVPN File.txt](https://github.com/haugene/docker-transmission-openvpn/files/3496596/Buffered.OVPN.File.txt)
