### ISSUE TITLE
Transmission somehow not starting

### ISSUE THREAD

**Issue by snizzleorg** [haugene/docker-transmission-openvpn#433]
I had this running fine for a while. I today updated the image for the latest version and now the VPN is up but it seems that transmission is not starting. Inside the container I see this:

```
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 dumb-init /etc/openvpn/start.sh
    7 ?        Ss     0:00 openvpn --script-security 2 --up-delay --up /etc/transmission/start.sh --down /etc/transmission/stop.sh --inactive 3600 --ping 10 --ping-exit 60 --config /etc/openvpn/cryptostorm/cstorm_lin
   46 ?        Ss     0:00 /bin/bash
  104 ?        R+     0:00 ps -ax
```

the logs don't give a hint:

```
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.33.153.160
Generating transmission settings.json from env variables
sed'ing True to true
Setting owner for transmission paths to 1000:1000

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Tue Feb 20 21:49:13 2018 us=231747 /sbin/ip route add 167.114.84.133/32 via 172.17.0.1
Tue Feb 20 21:49:13 2018 us=233083 /sbin/ip route add 0.0.0.0/1 via 10.33.0.1
Tue Feb 20 21:49:13 2018 us=234017 /sbin/ip route add 128.0.0.0/1 via 10.33.0.1
Tue Feb 20 21:49:13 2018 us=235228 Initialization Sequence Completed
```

The transmission log file is empty 

Any Idea on how to debug this?

**Comment by snizzleorg** [comment]
So i four dout that it has to do with the user transmission is running. If i set it to be running as root everything works. This however is less then ideal. since then also the files generated are owned by root. And generally it is not a good idea to run as root.

**Comment by hildebrau** [comment]
@snizzleorg, check to see what your permissions are on your host machine's folder that you have the container's /data mapped to.  Just a thought; I'm certainly no expert.  Make sure the user you are trying to run transmission as has read/write permissions to all the directories that /data is mapped to.

**Comment by snizzleorg** [comment]
Yeah I did that. did not help unfortunately. In any case it would be cool to get some kind of error... (have it running as root now)

**Comment by Mossop** [comment]
I've only just tried using this container but I'm seeing the same problem. Transmission doesn't start and no log file is written to its config directory.

**Comment by Mossop** [comment]
Updating to the dev tag fixed this for me.

**Comment by snizzleorg** [comment]
so you pull :dev instead of :latest?

**Comment by Mossop** [comment]
Yes

**Comment by mesartwell** [comment]
+1, I experienced the same symptoms and pulling haugene/transmission-openvpn:dev fixed it as well.

**Comment by berglh** [comment]
I also moved to dev for this reason but now am experiencing https://github.com/haugene/docker-transmission-openvpn/issues/432

**Comment by haugene** [comment]
Made a new release and merged to master. Can someone confirm that the latest tag and latest release is ok and that this issue could be closed?

**Comment by Mossop** [comment]
I switched back to latest and things still work for me.

**Comment by haugene** [comment]
Great, thanks! I'm closing this now, others can re-open if it's still an issue.

**Comment by izznogooood** [comment]
Same issue.

**Comment by haugene** [comment]
And you've pulled the image again?

**Comment by izznogooood** [comment]
Yes, look at the unit file. I set it up to do that automatically. (And tried manually now).

**Comment by haugene** [comment]
And if you run as root, it works? Been some issues with the user settings, looking into permissions now in #435

**Comment by izznogooood** [comment]
It runs on root, but my variables are not implemented...

**Comment by haugene** [comment]
Ahh, I see. But they should be prefixed with transmission, ref [this section](https://github.com/haugene/docker-transmission-openvpn#transmission-configuration-options)

**Comment by izznogooood** [comment]
Gotcha :)
