### ISSUE TITLE
Reverse Proxy + UFW 

### ISSUE THREAD

**Issue by h45rd** [haugene/docker-transmission-openvpn#434]
Hi,

Re-enabled UFW now that one can chain e.g. a privoxy container through the VPN with UFW enabled thanks to @alron's #408.

Any reason we are only allowing access to the RPC port from the gateway itself instead of the whole ip range of the specific docker network here?: 

https://github.com/haugene/docker-transmission-openvpn/blob/fb289b489c39d0680dc40d3f56829ad9b07acff6/openvpn/start.sh#L69

To make a reverse proxy container within the range of the default gateway work with UFW enabled one would need e.g.
`ufw allow proto tcp from 172.18.0.0/24 to any port 9091`
instead of
`ufw allow proto tcp from 172.18.0.1 to any port 9091`

No big deal since we can hook custom scripts now, but I thought I would ask in the vein of ease of use / beginner friendliness.

**Comment by haugene** [comment]
Hey. In general I agree with you. As long as security is not heavily compromised, ease of use should get priority. If possible a new argument could be needed to set a more secure, but customised version.

I need to look into this a bit further. But have got enough iptables for one night. Just merged #256 to the dev tag which now bundles a proxy server. That might also fix the need you have for privoxy, but the ufw question is still relevant for other services anyways.

**Comment by h45rd** [comment]
Hehe.. I am no ip tables wizz by any stretch of the imagination either.
Yes, #256 will indeed fix my need for chaining a privoxy container. Going to give the dev tag a spin this weekend. Thx!

RE: UFW
I understand the need for further investigation.
Looked at the original PR #231 and maybe @ullbergm could give us some pointers as to why he implemented access from the default gateway the way he did and why we should/shouldn't change it to allow access from the whole default gateway ip range?

Not being very deep into this topic, I could easily be missing something. But off the top of my head I can't think of any use case where the docker network gateway itself would want/need to access transmissions RPC port.

**Comment by ullbergm** [comment]
I don't remember of the top of my head why I needed the local GW to be able to talk to it, but at the time that is all I needed so that is all i opened up.

I don't see any reason you couldn't open up the whole local ip range, they are all internal machines so the exposure is minimal.

**Comment by alron** [comment]
If y'all want, I can add a few of the FW related features. It'd be pretty simple to add a UFW_ALLOW_GW_NET=true or something similar. Make it optional.

We already do something like:
`eval $(/sbin/ip r l m 0.0.0.0 | awk '{if($5!="tun0"){print "GW="$3"\nINT="$5; exit}}') `

It wouldn't be to difficult to add something like this to get the CIDR of the GW to use in allow rules:
`eval $(ip r l dev ${INT} | grep -v default | awk '{print "GW_CIDR="$1}')`

Along the same line of FW options, I was considering extending LOCAL_NETWORK to support a comma seperated list of CIDR (kind of like ports in my #408 ). Would this be of some use? The LOCAL_NETWORK stuff does ip routes and firewall rules, wouldn't be too hard to make it handle many routes and rules.

**Comment by h45rd** [comment]
I would be all for it, given that it does not add too much complexity but a lot of flexibility for all kinds of setups.

Maybe even make the less restrictive blocking (e.g. UFW_ALLOW_GW_NET and UFW_ALLOW_LOCAL_NET both true if UFW is enabled) the default for ease of use?

**Comment by alron** [comment]
I haven't had a chance to test it, but I believe I've made the [changes](https://github.com/alron/docker-transmission-openvpn/commit/18c0245e8d67e5a6725e4c2e4cf7a6d45447fc43) for the UFW_ALLOW_GW_NET and multiple networks in LOCAL_NETWORK features. It does pass syntax check, so that is 99% of the fight. 


I'll give it a test in the AM, and submit pull requests when it works properly.

**Comment by alron** [comment]
@h45rd I've submitted pull #440 with the UFW_ALLOW_GW_NET=true and LOCAL_NETWORK accepting multiple comma separated CIDR.

If you want to test to see if it does what you want, I've set a test [docker](https://hub.docker.com/r/alron/transmission-openvpn/) build.

Cheers.

CC: @ullbergm  @haugene

**Comment by h45rd** [comment]
Thanks much, alron.
Sounds great. Going to test and give feedback once I am home tonight.

**Comment by h45rd** [comment]
Arg.. sorry for the late feedback.
As expected your change is working nicely for my setup and has retired my custom pre-run script. Thanks again :)
