### ISSUE TITLE
Transmission UI unable to connect to server

### ISSUE THREAD

**Issue by ochompsky** [haugene/docker-transmission-openvpn#439]
I get this error when going to the transmission UI - 

Connection Failed
Could not connect to the server. You may need to reload the page to reconnect.

This is the docker command I am running: 

```
              docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \
              -v /your/storage/path/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e OPENVPN_PROVIDER=Windscribe \
              -e OPENVPN_CONFIG=US-East-udp \
              -e OPENVPN_USERNAME=username \
              -e 'OPENVPN_PASSWORD=password' \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=172.16.0.0/16 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn
```

Everything looks ok in the logs.  What's going on?

**Comment by ochompsky** [comment]
EDIT: this is hostname related.

 I have an entry for DNS for this server but it looks like transmission doesn't like that.  How can I get this to work by hostname instead of LAN ip address?

**Comment by skogsmaskin** [comment]
You must add your hostname to the ``TRANSMISSION_RPC_HOST_WHITELIST`` ENV parameter.

**Comment by jvicondoa** [comment]
I ran into the same issue. You'll need to do what @skogsmaskin describes, or turn on authentication on the rpc interface.

**Comment by ochompsky** [comment]
thanks, setting the ENV parameter resolved it.

**Comment by haugene** [comment]
Or use the dev tag of the image. The rpc host whitelist is disabled by default there, and will be the default on the latest tag after next release.
