### ISSUE TITLE
Add ExpressVPN

### ISSUE THREAD

**Issue by NY152** [haugene/docker-transmission-openvpn#441]
Hello,

I am an ExpressVPN user on unRAID server and you do not offer this VPN yet common.

Can you add it or suggest the option to add your VPN manually?

Thank you

**Comment by haugene** [comment]
This is #105. ExpressVPN had personal .ovpn files generated for each user which meant they couldn't be shared. If they've changed that, and you provide a link to a zip or similar package of configs they could be added.

As for adding provider manually, have you read the README? Do it again...

**Comment by haugene** [comment]
Closing this. Either provide link to ovpn config files and we can add ExpressVPN to the image. Or use the custom provider approach described in the README. Re-open if you have other issues.

**Comment by NY152** [comment]
This is an personal .ovpn file!
Instead of trying to maintain a list of VPN providers, why not add support for .ovpn files directly? It would simplify things and you would avoid provider.

**Comment by haugene** [comment]
Have you read #105 that I linked to? It pretty much explains this, and the support for .ovpn files directly. The list of VPN providers is just a handy feature for most, but you can definitely use your own if you want. It's described [here](https://github.com/haugene/docker-transmission-openvpn#using-a-custom-provider), if not in the issue I linked.

**Comment by NY152** [comment]
My english is very bad and i do not really understand how to do it :(
