### ISSUE TITLE
Dockerhub images come with transmission 2.84

### ISSUE THREAD

**Issue by spede** [haugene/docker-transmission-openvpn#444]
Yo, `docker pull haugene/transmission-openvpn` gives you an older version with transmission 2.84 bundled in even with the tags `latest`, `1.22` and `dev`.

![capture](https://user-images.githubusercontent.com/1430753/36943423-daaf7c4a-1f91-11e8-95b8-2dccd29558e8.PNG)

**Comment by spede** [comment]
Looking at it, seems like the transmissionbt packages are `transmission-daemon/xenial-updates,xenial-security 2.84-3ubuntu3.1 amd64` on Ubuntu LTS...

**Comment by haugene** [comment]
Yes, this has to do with #392 and #395 and security issues. We're using patched version of 2.84 while waiting for the 2.93 version from the ppa:transmissionbt repo.

But checked the [ppa](https://launchpad.net/~transmissionbt/+archive/ubuntu/ppa) now, and it seems 2.93 is now available. Will try to build with ppa and see.

**Comment by haugene** [comment]
Dev branch is updated, closing this issue. Follow-up in #392 if anything. Will close that when merging to master.
