### ISSUE TITLE
Open port 51413 for incoming connection.

### ISSUE THREAD

**Issue by Brilhasti-ap-Tarjan** [haugene/docker-transmission-openvpn#453]
When I test whether the incoming port is open it says "Incoming port is closed.  Check your firewall settings".  My VPN provider does support incoming port forwarding.  I have it working on a Pi with Transmission and OpenVPN so I know it works.

**Comment by Brilhasti-ap-Tarjan** [comment]
When I test whether the incoming port is open it says that it is closed.  My VPN provider does support incoming port forwarding.  I have it working on a Pi with Transmission and OpenVPN so I know it works.

**Comment by haugene** [comment]
You're basically saying "It doesn't work, but it should work". You need to describe the problem better, and what you have done to fix it.

First, how are you testing your port? Are you running `transmission-remote -pt` inside the container?

Second, your provider supports port forwarding - great. I assume you've set up a port to forward? Have you verified that this is indeed opened? Find your public IP and do a `telnet <IP> <port>` to see if you can connect.

What kind of setup did you do on your Pi? You've had to set the port you've opened to Transmission somehow?

**Comment by Brilhasti-ap-Tarjan** [comment]
I am using Transmission Remote GUI.  When I click on Test port it gives me the port closed error.  I do not have any sort of port blocking or UFW installed.  I am wide open.

I noticed these options: ENABLE_UFW, UFW_ALLOW_GW_NET, UFW_EXTRA_PORTS.  Do I need to set some settings with these to expose 51413?

When I just have OpenVPN and Transmission installed and I do the same thing it tells me "Incoming port tested successfully.".

Is there a better place for me to ask these questions?  Do you have a forum?  I didn't want to open an issue with the software but it was the only place I could find to post.

**Comment by mmcc-xx** [comment]
Hi - I think I'm having the same issue. I use PIA, and started the docker using this command: 

docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \
              -v /mnt/archive/media/downloads:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e "OPENVPN_PROVIDER=PIA" \
              -e "OPENVPN_CONFIG=Netherlands" \
              -e "OPENVPN_USERNAME=mynameasdasd" \
              -e "OPENVPN_PASSWORD=mypasskljfdskjfgd" \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn

The transmission web page comes right up when I point at http://127.0.0.1:9091 but when I look at the settings, it says that the peer listening port is 51413, and that it is closed.

I have successfully used PIA with port forwarding on my "real" machine and in a VirtualBox VM.

I have tried stopping and restarting the container.

I don't have much experience with Docker so I'm not very sure how to troubleshoot this further.

**Comment by mmcc-xx** [comment]
I stopped and removed the image and restarted. This time I have a different port listed and it is indeed open. I'm going to leave it running and see if it stays that way.

**Comment by Brilhasti-ap-Tarjan** [comment]
I did the same and now it is working.

**Comment by haugene** [comment]
Great. I'm closing this then. And FYI @Brilhasti-ap-Tarjan, you asked for another forum for these kinds of questions. I recently set up a [gitter chat](https://gitter.im/docker-transmission-openvpn). There's not much activity yet, but I hope that it can work as a place to ask (and search) for help getting started.
