### ISSUE TITLE
Can't reach trackers when running for extended periods

### ISSUE THREAD

**Issue by richardtheb** [haugene/docker-transmission-openvpn#455]
Hey all, I am running this excellent Docker thing under Ubuntu 16.04, connecting to PureVPN. It works fine most of the time, but I have noticed that it seems to lose the connection somewhere if it is running for an extended time. By this, I mean that I notice that all of my torrents seem to end up with "can't reach tracker" error after the docker has been running for a while. 

I have added the --restart=always and INACTIVE=3600 lines to the script that starts up the docker.

I could just add a cron to restart the docker every 24 hours or so but any suggestions as to a better way to figure out what is going on?

**Comment by haugene** [comment]
Hello there! Glad to hear that you like the container.

As for this issue. I suggest you close it and join in on #454 instead. This has been a recurring itch, and it also seems to be provider specific.

Read up on that issue and others it links to. I think it should cover what you're describing here. Hopefully we can get a permanent fix that doesn't need external tools like cron to keep going.

**Comment by richardtheb** [comment]
Closing as this is covered by #454
