### ISSUE TITLE
Cannot open TUN/TAP

### ISSUE THREAD

**Issue by Kaoz52** [haugene/docker-transmission-openvpn#46]
I am French, I use google translation

Hello,

I have a Qnap ts253pro.

That's the problem I have:
```
Tue Dec. 22 2015 2:24:22 p.m. [vpnsvc] Peer Connection Initiated with [AF_INET] 95.211.195.84:443
Tue Dec. 22 2015 2:24:25 p.m. ERROR: Can not open TUN / TAP dev / dev / net / tun: No such file or directory (errno = 2)
Tue Dec. 22 2015 2:24:25 p.m. Exiting due to fatal error
```
The problem is that /dev/net/ tun is present in my Qnap.

I saw some problems that resembled mine but I did not find satisfesante answer.

Would you have an idea of the problem?

Thank you in advance for your assistance.

----------------------------------------------------------------------------------------------------

Bonjour,

Je possède un Qnap ts253pro. 

Voilà le problème que je rencontre :

```
Tue Dec 22 14:24:22 2015 [vpnsvc] Peer Connection Initiated with [AF_INET]95.211.195.84:443                                                                                                                 
Tue Dec 22 14:24:25 2015 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)                                                                                                   
Tue Dec 22 14:24:25 2015 Exiting due to fatal error
```

Le problème est que /dev/net/tun est bien présent dans mon Qnap.

J'ai vu quelques problèmes qui ressemblaient au miens mais je n'ai pas trouvé de réponse satisfesante.

Auriez vous une idée du problème ?

Merci d'avance pour votre aide.

**Comment by haugene** [comment]
Hello,

When the container starts it tries to open a vpn connection through a tun/tap device that isn't present on your system. OpenVPN is installed inside the container but it requires this device to open a connection.

You need to set up such a device, and this is what's described for a Synology NAS in issue #41.
The easiest solution for you is probably to install openvpn on your NAS as well, this should create a tun/tap device that the container will use when it's connecting.

**Comment by Kaoz52** [comment]
Thank you for your answer.

My problem is that OpenVPN is already activated on my NAS.

So I have already /dev/net/tun : 

![capture d ecran 2015-12-23 a 00 07 23](https://cloud.githubusercontent.com/assets/4966339/11968137/501240aa-a909-11e5-8612-1e755efd2198.png)

OpenVPN is preinstalled, I simply activated via the control panel:
![capture d ecran 2015-12-23 a 00 07 57](https://cloud.githubusercontent.com/assets/4966339/11968143/5c9b8ea8-a909-11e5-85fc-18c83ad77156.png)

I'm sorry, I started and I confess not to understand my problem.

Thank you
----------------------------------------------------------------------------
Merci pour ta réponse.

Mon problème est que OpenVpn est déjà activé sur mon NAS.

J'ai donc bien /dev/net/tun :

(Voir Image au dessus)

OpenVPN est préinstallé, je l'ai simplement activé via le panneau de controle :

(Voir Image au dessus)

Je suis désolé, je débute et j'avoue ne pas comprendre mon problème.

Merci

**Comment by haugene** [comment]
Hmm. From your first logs it says: "Cannot open TUN/TAP dev /dev/net/tun: No such file or directory" so that should imply that it's not present. But then you activated the VPN server and now you have it?

If you deacivate OpenVPN will the dev/net/tun device disappear? If it was installed/configured the first time you activated OpenVPN you should then be able to deactivate your OpenVPN server and then start the container?

**Comment by Kaoz52** [comment]
That's my problem, it tells me "Can not open TUN/TAP dev /dev/net/tun: No such file or directory" when it is present ...

In addition, OpenVPN works fine when I connect myself to my PC via Viscosity (same tunnelblick).

It's really going crazy ...

As against what is weird is that if I disables OpenVPN via the control panel, "/dev/net/tun" is always present. (and I still have the same error)

Thank you for your help

**Comment by haugene** [comment]
Well, it makes sense that the /dev/net/tun is still there as that interface is probably set up when OpenVPN is installed/activated for the first time. Also note that the service you're enabling/disabling is just a OpenVPN server shipped with your NAS, not all of the OpenVPN capabilities. If you don't plan to host your own OpenVPN server I would keep it disabled...

As for your problem, the "No such file or directory" error will also come if there are permission issues. Are you running the container with the --privileged flag?

**Comment by Kaoz52** [comment]
Hello,

In fact I use the "Container Station" Qnap in which is "Docker".

Once your package installed, I have to go to "Advanced Settings"

![capture](https://cloud.githubusercontent.com/assets/4966339/11979952/9ecb33a8-a997-11e5-97b9-5df789d27282.PNG)

Can I return my data:

![capture 2](https://cloud.githubusercontent.com/assets/4966339/11979958/aa618424-a997-11e5-9623-daa6eabd0e44.PNG)

If I do not go through there and I go directly into the terminal after you install your container, I have this error:
![capture 3](https://cloud.githubusercontent.com/assets/4966339/11980079/62898eca-a998-11e5-8806-fc97e46cd963.PNG)

I have changed on the highlighted data

That's where I am, a little lost.

**Comment by haugene** [comment]
Hmm. I'm not sure why the qnap container station isn't working, but there should be a choice to run the container in privileged mode. Somewhere in the advances settings? 

For the terminal example you have a "\" between -d and -v there. That's probably why it thinks it should load v:latest image which doesn't exist. The \ symbols are only used for multi-line commands. You don't need them if you write it all on one line...

**Comment by Kaoz52** [comment]
Ah we advance!

Indeed there was a good way "with privilege" check that I had not seen AND I had the damn "\" too much in my line terminal !!!

So it connects with both methods BUT disconnects after a few seconds (20 / 30sec). here is what I have in the logs:

![capture 4](https://cloud.githubusercontent.com/assets/4966339/11985426/00c080f4-a9c5-11e5-9a57-936c67323174.PNG)

Port opening problems?
I have no log at the time of disconnection

Thank you for your help, I feel a glimpse of the end of the tunnel ...

**Comment by haugene** [comment]
Nah, that looks correct. The port updating is just a custom script for the PIA provider that asks for an open port and sets it to transmission every hour. You're supposed to get that message if you're using another provider. 

What do you mean by disconnect? The container stops? Never seen that before...

**Comment by Kaoz52** [comment]
Thank you for your answer, sorry for the wait (Christmas ...).

Yes, it is that OpenVPN disconnected.

I do not understand the connection but it is disconnected between 10 and 20 seconds later ...
(The problem does not come from VPN because it works well on the PC via OpenVPN and PPTP on the NAS.)

I just tested on the OpenVPN Nas and I have the same problem so this comes from my side and not your container.

So you can close my issue in my case.

Thank you for your time and your help.

PS: If you have an idea for my problem, I'm still ...

**Comment by Kaoz52** [comment]
close #46

**Comment by Kaoz52** [comment]
fixed #46

**Comment by victoere** [comment]
Have the same issue "Can not open TUN/TAP dev /dev/net/tun: No such file or directory"  I saw the reference the "Privilege" check in advanced setting in Container Station.  I'm gong to take a closer look at this tonight but wondering if you can elaborate on where you found that?  Maybe a screenshot of the advanced settings.

**Comment by ratabora** [comment]
@victoere privileged mode worked for me right out of the box

![screenshot](http://i.imgur.com/9XfZnhy.png)
