### ISSUE TITLE
Help with armhf build

### ISSUE THREAD

**Issue by jata1** [haugene/docker-transmission-openvpn#463]
Hi all - i'm new to using docker but have learnt a lot trying to get this image/repo working on my rock64 / armhf board - it's like a raspberry pi but better!

Situation is that i have edited the dockerfile and created a build that compiles into an image with no errors based on the baseimage arm32v7/debian:jessie.

When i try to create and/or start a container using the image I have built it doesn't start and says it's dead. 

how can I find out what is going wrong?

**Comment by haugene** [comment]
We need logs to see what is failing. First try grabbing the container logs `docker logs <container>` and if they don't provide any insight then have a look at the docker daemon logs. You should refer to Docker documentation for your platform on how to get these.

Have a look and paste them here if you need help figuring it out after that.

**Comment by jata1** [comment]
Thanks. I appreciate the help. 

I am making progress and I have worked out that the start.sh script is failing with an error. I'm adding additional debugging into the start.sh script to see if I can find out where the issue is. the error message is below

--up script fails with '/etc/transmission/start.sh': Permission denied

**Comment by jata1** [comment]
Is it possible to copy a new version of the start.sh script into a container? At the moment I am making changes to start.sh and then building the image but i'm thinking there must be a better way!

**Comment by haugene** [comment]
You can do `docker cp /your/modified/start.sh <container-name/id>:/etc/transmission/start.sh`. Double check the syntax, but I think that's correct. But rebuilding the image and recreating the container is a good solution as well.

**Comment by jata1** [comment]
Thanks to both of you for the help - really appreciate it and I know i'm a total noob!

So situation is that I have added a load of debug lines to start.sh and when the container runs it gets right to the end of start.sh and I am getting a permissions error on exec openvpn 

below is the log from the docker container when I run it - you can see by echo debug outputs  including some that output TRANSMISSION_CONTROL_OPTS, OPENVPN_OPTS and OPENVPN_CONFIG

Anything obvious that I have wrong?

Using OpenVPN provider: SMARTDNSPROXY
Starting OpenVPN using config Australia-Newcastle_UDP1194_SMART.ovpn
Setting OPENVPN credentials...
debug - mkdir -p /config [done]
debug - openvpn-credentials.txt [done]
debug - chmod 600 /config/openvpn-credentials.txt [done]
debug - dockerize -template /etc/transmission/environment-variables.tmpl:/etc/transmission/environment-variables.sh [done]
debug - TRANSMISSION_CONTROL_OPTS = --script-security 2 --up-delay --up /etc/transmission/start.sh --down /etc/transmission/stop.sh
debug - OPENVPN_OPTS = 
debug - OPENVPN_CONFIG = /etc/openvpn/smartdnsproxy/Australia-Newcastle_UDP1194_SMART.ovpn
Options error: --up script fails with '/etc/transmission/start.sh': Permission denied
Options error: Please correct this error.

**Comment by h45rd** [comment]
I guess you already checked the chmods of _/etc/transmission/start.sh_?

**Comment by haugene** [comment]
What @h45rd said. If you're a noob as you say, what we're interested in is the output from `ls -la /etc/transmission/start.sh`. As for debug info, you don't need to add debug lines with echo. If you add a line `set -x` you'll get all executed commands and changes to state along the way.

But I'm guessing this is a missing execute flag, so setting that on your new start.sh script with `chmod +x /etc/transmission/start.sh` should fix it I think.

**Comment by haugene** [comment]
The set -x line goes in start.sh

As for the startup logs, that's expected if the device is not set up on your host. If you post your docker run command I'll know more. But we're mounting the tun device from the host, so that needs to be in place. If you install openvpn on the host it will be set up or you can do it with mknod command.
