### ISSUE TITLE
Synology and native VPN support

### ISSUE THREAD

**Issue by Xaelias** [haugene/docker-transmission-openvpn#465]
Hey,

I was wondering. DSM/Synology supports VPN out of the box.
Is there a way to configure this container to use that connection instead of establishing a new one? And stop the container if that connection dies?

Thanks!
Alexis

**Comment by haugene** [comment]
Hello.

So. Long story short - this is not supported and I wouldn't recommend doing it that way. You might be able to get something that resembles it by setting --net=host, that way the container will not set up it's own network stack but work on the host network instead. It will still open a new tunnel though, and not reuse an existing one. The tunnel will be system wide, and not confined to the container.

But if that's the setup you want, I don't think this is the container you need. The whole purpose of this container - at least for the rest of us - is to avoid VPN on the host and only have it for transmission in the container.

You could probably find some inspiration from this image, which you can apply on your host instead. What you need to do is to get another container that only runs transmission, and then make that container go up and down when the host VPN goes up and down. We use [up/down scripts](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L50) to tell OpenVPN to start and stop stuff when the tunnel goes up and down.

I guess you can add this either to your OpenVPN at startup or in the .ovpn config you're using and set the up script to be `docker run <some container>` and then have the down script do "docker rm -f <some container>`.

Good luck

**Comment by h45rd** [comment]
E.g. the [linuxserver transmission only container](https://hub.docker.com/r/linuxserver/transmission/) seems to be rather popular.
Another option besides what haugene outlined (if you don't actually want to kill the container but just want to prevent leakage in case the VPN goes down) would be to use a user-defined network for your torrent container and iptables and route on your host to block any non-VPN traffic for this network.

**Comment by Xaelias** [comment]
Woaw thanks guys for all the help.
Honestly, I'm not against your more "limited" (I don't mean that negatively, just that it impacts only that container) option. I was wondering if there was an easy way to go global with the VPN, while keeping the kill switch behavior for this specific container.
But thanks, I'll go through all of this when I have some free time.
You guys are great!

**Comment by coolboiime** [comment]
I think my script might be able to solve your problem. I used to have Transmission installed directly on the system with a VPN script I wrote.

Maybe this might help: https://github.com/coolboiime/transmissionVPN
