### ISSUE TITLE
PIA Port Forwarding is Not Updating settings.json; Stuck on Port 51413

### ISSUE THREAD

**Issue by newmossie** [haugene/docker-transmission-openvpn#466]
Hello 

I'm using the latest dev build and the settings.json is not updating with the port number that PIA is providing.  It is always stuck using 51413 and so Transmission is reporting the connection is closed.  

I've tried recreating the container and restarting docker host (Synology).

Thanks for any help you can give, cheers

I'm attaching the logfile, env file, and settings.json.
[TransmissionVPN-log.zip](https://github.com/haugene/docker-transmission-openvpn/files/1871394/TransmissionVPN-log.zip)

[transmission-openvpn.env.txt](https://github.com/haugene/docker-transmission-openvpn/files/1871396/transmission-openvpn.env.txt)

[settings.json.txt](https://github.com/haugene/docker-transmission-openvpn/files/1871397/settings.json.txt)

**Comment by Celoxocis** [comment]
I'm seeing this too. my guess its not an container issue but PIA having issues with it's port forwarding API.

**Comment by newmossie** [comment]
Well you were right, PIA removed port forwarding for Sweden, which is what I was connecting to.  Port forwarding is working for Switzerland.  I'm gonna close this now

**Comment by haugene** [comment]
At least good it's not another issue with the port forwarding script, at least on the dev branch it's supposed to be more stable after e89ed2c.

By the way. I don't think you'll see the changes in settings.json anyways, as transmission only persists settings on shutdown.

**Comment by auanasgheps** [comment]
> By the way. I don't think you'll see the changes in settings.json anyways, as transmission only persists settings on shutdown.

It may not be related to this issue, but I wanted to comment on this one. Every time I stop and restart the container, settings.json gets overriden with "default" environment settings, eeven if I did not set those. Is this expected? @haugene

**Comment by haugene** [comment]
Yes. All changes you do in the settings.json manually, or through the WebUI will be overridden at startup. Config you want to be persisted needs to be set in environment variables. It's sometimes a hassle, but it's good for portability and some of the fields are actually updated every time (like ipv4 bind address) and then needs to be overridden.

**Comment by auanasgheps** [comment]
Thanks for letting me know. I've wasted 2 hours fighting with settings reverting to default, and then I discovered this case...

**Comment by douggard** [comment]
Stop the daemon, edit settings.json, restart the daemon.
