### ISSUE TITLE
OpenVPN credentials not set.

### ISSUE THREAD

**Issue by CoderKiwi** [haugene/docker-transmission-openvpn#467]
Hi,

I'm sure this has been asked before but I can't figure this out. 

I'm using a custom provider. The docker env vars for username and password are set correctly (although I think they're not used when using a custom provider).

I added a reference to `expressvpn_credentials.txt` in the `auth-user-pass` line where the .txt file has the username as the first line and the password as the second line.

```
auth-user-pass expressvpn_credentials.txt
```

`expressvpn_credentials.txt` is in the directory mounted as `/data` so the container should be able to see it and read it.

I even read the config.sh script provided in the repo to see if I'm putting credentials in the wrong place but I don't think so.

Really not sure why the app can't find the credentials! Thanks for the help

**Comment by CoderKiwi** [comment]
```
transmission_1  | Using OpenVPN provider: CUSTOM
transmission_1  | Starting OpenVPN using config default.ovpn
transmission_1  | OpenVPN credentials not set. Exiting.
```

**Comment by CoderKiwi** [comment]
Thanks @h45rd -- mounting the credentials file that way fixed the issue.

However now it's giving this error immediately afterwards. If I'm not mistaken I think these errors are after the startup script so that's something!

```
Starting src_transmission_1 ... done
Attaching to src_transmission_1
transmission_1  | Using OpenVPN provider: CUSTOM
transmission_1  | Starting OpenVPN using config default.ovpn
transmission_1  | Found existing OPENVPN credentials...
transmission_1  | Sun Apr  8 13:47:01 2018 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
transmission_1  | Sun Apr  8 13:47:01 2018 OpenVPN 2.4.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar  1 2018
transmission_1  | Sun Apr  8 13:47:01 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
transmission_1  | Sun Apr  8 13:47:01 2018 neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Auth Username:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.
transmission_1  | Sun Apr  8 13:47:01 2018 Exiting due to fatal error
src_transmission_1 exited with code 1
```

**Comment by CoderKiwi** [comment]
Seems like the certificates have been generated using a passphrase

**Comment by CoderKiwi** [comment]
Got it. The same **auth-user-pass** line needs to be reading the mounted file described above:

`auth-user-pass /config/openvpn-credentials.txt`

**Comment by CoderKiwi** [comment]
It may be a good idea to post these solutions to the README so no one else with ExpressVPN gets confused since it's a custom provider

**Comment by haugene** [comment]
Yes, the custom provider section really describes providers that have per user generated certificates and where a username/password shouldn't be necessary. I thought that was how expressvpn worked, but you're supplying authentication. Is it both?

I agree that the custom provider section should contain both how to use it if all info is in the ovpn config (so you don't need to point to the credentials file) and what needs to be changed in the files if you want to point to it. Would happily merge a PR if you update it :)

**Comment by CoderKiwi** [comment]
Yeah it seems not only transmission needs the credentials file, but the .ovpn file needs a reference to the credentials file as well. 

I'll do some testing to confirm that's the case and then submit a pull request.

ExpressVPN is a big provider. Surely I can't be the only one to find this is the case...? Maybe there is a better way of doing this I'm not aware of, in which case I'm a little more hesitant to rewrite the README

**Comment by haugene** [comment]
Transmission only needs the rpc credentials, and only if PIA is used, right? It is used to set the port in the port update script.

The container fails if openvpn username/pass is not given. But for ExpressVPN and others that generate user-specific configs, you should be able to set "dummy/dummy" and have no reference to the auth-user-pass file in the config.

Check it out and let me know what you find.
