### ISSUE TITLE
Watch don't work

### ISSUE THREAD

**Issue by cedvan** [haugene/docker-transmission-openvpn#468]
Hi,

Thank you to great work!

I used back hole with watch directory. But torrents only added on starting docker image, but after, watch directory no longer seems to be scanned. An idea ?

**Comment by haugene** [comment]
I would guess this has to do with how you're mounting the directories.
The watch directory isn't scanned, I think it relies on inotify and I've previously seen glitches with this on docker volumes.

How are your mounts?

**Comment by cedvan** [comment]
Yes, inotify is used ;)

I mount my volume by NFS with rancher-nfs container.

**Comment by haugene** [comment]
Yes, so I meant more specific on which mount points you provide the container. Are you mounting the parent folder, or the watch folder directly?

**Comment by haugene** [comment]
I don't know why it isn't working for you. I've never had a problem with it and this is such a central feature that there would be tons of issues if it didn't work.

Can this be because of the NFS?

**Comment by cedvan** [comment]
NFS, maybe... I will take the time to look more ;)

**Comment by coolboiime** [comment]
Closing this issue in favor of #512! Thanks
