### ISSUE TITLE
404 not found when loading up with transmission-web-control

### ISSUE THREAD

**Issue by bamtan** [haugene/docker-transmission-openvpn#470]
Here's what loads up

![](https://i.imgur.com/B6zFxT3.png)

**Comment by haugene** [comment]
Probably relates to @h45rd comment on #459 about symlinking index.html?

**Comment by bamtan** [comment]
Permissions error maybe?

Visiting `http://ip:9092/transmission/web/tr-web-control/style/base.css` (and all other urls) lead to:

404: Not Found
/opt/transmission-ui/transmission-web-control/tr-web-control/style/base.css (Permission denied)

**Comment by bamtan** [comment]
@davinkevin any ideas?

**Comment by bamtan** [comment]
I managed to get the UI working, it definitely was a permissions error where all the contents of `/opt/transmission-ui/transmission-web-control` were set to chmod 666, rather then the chmod 755 of the other web UIs. 

![](https://i.imgur.com/gXztcNr.png)

Now I'm just getting a RPC conflict which is probably due to the fact that I have two instances of this Docker image running currently. 

![](https://i.imgur.com/YBsUZeW.png)

**Comment by bamtan** [comment]
Maybe to do with the Dockerfile, when creating the folder on this line https://github.com/davinkevin/docker-transmission-openvpn/blob/182f2f2c70ea822f965e63bf4b6fd3fe771652be/Dockerfile#L21 causing the folder to have different permissions than the other WebUIs

**Comment by haugene** [comment]
I took a look at this. It could be a permissions issue, but I can't seem to reproduce it. All commands in Dockerfile is run as root, and when I look at directory ownership of /opt/transmission-ui/ they all are owned by root.

I've tried running transmission as root and my own user, the latest tag and a local build. But I don't get the 404s. We could do chmod 755 for the files in transmission-ui, but are more people having an issue with this?

**Comment by coolboiime** [comment]
I tried this, and everything seems to be working normally. It could possibly be a cached thing.

**Comment by bamtan** [comment]
@coolboiime I think you're right, tried again and it loads perfectly on both Chrome and Firefox. I'll close the issue!

**Comment by mnkhouri** [comment]
I ran into this issue: examining the directories in `/opt/transmission-ui/transmission-web-control`, I see they are all `chmod 666`:

```
> ll /opt/transmission-ui/transmission-web-control/tr-web-control:
total 48
drw-rw-rw- 6 root root 4096 Mar 28 08:00 ./
drwxr-xr-x 3 root root 4096 Apr  8 20:51 ../
-rw-rw-rw- 1 root root 1755 Mar 28 08:00 config.js
drw-rw-rw- 2 root root 4096 Mar 28 08:00 lang/
-rw-rw-rw- 1 root root 7341 Mar 28 08:00 logo-white.png
-rw-rw-rw- 1 root root 7257 Mar 28 08:00 logo.png
-rw-rw-rw- 1 root root  870 Oct 19  2017 plugin.js
drw-rw-rw- 5 root root 4096 Mar 30 00:50 script/
drw-rw-rw- 5 root root 4096 Mar 28 08:00 style/
drw-rw-rw- 2 root root 4096 Mar 28 08:00 template/
```

![image](https://user-images.githubusercontent.com/6535396/43815775-4de3e808-9a9f-11e8-81be-083777e1fd9e.png)



**Running the following command inside my container fixed the UI:**

```
find /opt/transmission-ui/transmission-web-control/ -type d -exec chmod 755 {} \;
```

Unfortunately, I'm not sure how to reproduce -- I'll comment if I find out. BTW I love this UI, thank you!
