### ISSUE TITLE
Peer port (port forwarding) is no longer open for PIA.

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [haugene/docker-transmission-openvpn#471]
I've updated to the latest image. Otherwise torrents are working as expected... just a dearth of peers, and it's nearly impossible to seed. When I click on the configuration button and the panel comes up, it's telling me that the port is closed.

I don't know how long it's been closed, I only started noticing about a week and a half ago when torrents started crawling. As far as I can tell, the last time PIA made changes to the port forwarding api was this time last year.

Has anyone else had similar problems?

**Comment by firecat53** [comment]
Reading through the PIA forums, it seems that some of the sites with port forwarding have had occasional troubles over the past year. As we speak, I'm testing the alpine image (with a few edits) and port forwarding is functioning on the "strong/CA Vancouver" site.

**Comment by NoMoreNicksLeft** [comment]
Thanks @firecat53, this seems to be the issue. Switching to Vancouver has fixed the issue.
