### ISSUE TITLE
container infinite rebooting

### ISSUE THREAD

**Issue by nicomarti83** [haugene/docker-transmission-openvpn#472]
hi,
this container was working great for more than a year, but since the last update (few weeks) it just restart over and over...
I run the container on a QNAP nas with purevpn provider.

I use this ssh command to run it:
`docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d -v /share/Download/:/data -v /etc/localtime:/etc/localtime:ro --env-file /share/homes/xxx/haugene-transmission/docker-transmission.env --log-driver json-file --log-opt max-size=10m --dns 8.8.8.8 --dns 8.8.4.4 --name=transmission-openvpn --restart=always -p 9091:9091 haugene/transmission-openvpn`

and this env file.
[docker-transmission.txt](https://github.com/haugene/docker-transmission-openvpn/files/1896353/docker-transmission.txt)

I tried in TCP or UDP with the same symptoms... please help me.

**Comment by firecat53** [comment]
You need to look at the docker logs and see what error is occurring that is causing the failure. With the `--restart-always` flag set, docker will continue to restart the container.

Run the container, then try `docker logs -f transmission-openvpn` in a terminal.

**Comment by nicomarti83** [comment]
ok, here is a "little" sample of the docker log. 
[docker log.txt](https://github.com/haugene/docker-transmission-openvpn/files/1900207/docker.log.txt)

**Comment by firecat53** [comment]
Here's the error. Seems to be on the openvpn side, but I can't tell for sure. You'd have to start a terminal session inside your container and test things one at a time to be sure.
    ....
    Transmission startup script complete.
    RTNETLINK answers: File exists
    Wed Apr 11 20:53:31 2018 ERROR: Linux route add command failed: external program exited with 
    error status: 2
    Wed Apr 11 20:53:31 2018 Initialization Sequence Completed
    Using OpenVPN provider: PUREVPN
    2 servers found in OPENVPN_CONFIG, Germany.He-tcp chosen randomly
   ....

I wonder if your openvpn option "--pull-filter ignore ping" is causing problems? I googled that, 'cause I have no idea what it does :smile: and I didn't find any exact matches for what  you have...which seems odd. Maybe remove that and try again?

**Comment by firecat53** [comment]
According to [this page](https://serverfault.com/questions/718391/rtnetlink-answers-file-exists-openvpn-errors), there is a route being added that already exists (based on the "RTNETLINK answers: File exists" error). Try commenting out the 'LOCAL_NETWORK=' option in your env variable file.

As to the second issue, some googling pointed possibly to using UDP over a high latency connection (i.e. Wifi). Maybe try switching to TCP or switch VPN servers if that's an option.

**Comment by nicomarti83** [comment]
I think the fault is from the udp protocol, I don't have the error with tcp.

**Comment by firecat53** [comment]
Well, that seems odd. I would've thought it would work regardless of the LOCAL_NETWORK variable. I'm out of ideas, man, sorry! I'm no networking guru unfortunately. You might post your routing table (`ip r`) from inside the container, as that might help someone figure out what the problem is.

**Comment by nicomarti83** [comment]
thanks for your help anyway...
here is the routing rable from the container:
`0.0.0.0/1 via 185.2.28.33 dev tun0 
default via 10.0.3.1 dev eth0 
10.0.3.0/24 dev eth0  proto kernel  scope link  src 10.0.3.2 
31.3.154.35 via 10.0.3.1 dev eth0 
128.0.0.0/1 via 185.2.28.33 dev tun0 
185.2.28.32/27 dev tun0  proto kernel  scope link  src 185.2.28.45 
192.168.1.0/24 via 10.0.3.1 dev eth0 `

**Comment by psychic69** [comment]
I dont know if this helps, but I upgraded to QTS 4.3.4.0551 and my transmission would crash.  I noticed that if a tun0 adapter wasn't plugged at the kernel level the container will crash.  To remedy the solution I started up the openvpn server, plugging a tun0.  They must have added security protocols in the last few releases.  If I have more time I will play with it, but for now it is 100% reproducible.

This works w/ UDP or TCP (I prefer UDP).

**Comment by nicomarti83** [comment]
hi, I've just update to QTS 4.3.4.0551 and the container just run fine. Do you have the qvpn service package install on your nas?

**Comment by kylecribbs** [comment]
I am having the same issue. I have tried with qvpn service installed and not installed.. Just keeps rebooting. QNAP Version 4.3.4.0644

**Comment by tenfourty** [comment]
+1 same issue here, I've tried a few suggestions on this issue from others but it doesn't seem to work for me.
I'm on a QNAP with version 4.3.4.0644

**Comment by haugene** [comment]
Hey guys. I'm going through and cleaning up issues, is this still an issue? Anyone tried with the option introduced in #559? Found a good workaround?

Might be that I'm grasping at straws, and I've probably gone through too many issues and started to mix them. But at first glance it seems it could be related to the Synology issues referenced from there.

**Comment by nicomarti83** [comment]
I've got the same issue randomly (once every two months approximately). I don't have the skills to understand why so I remove the container and rebuild it several times until it work ...

**Comment by haugene** [comment]
Issues are still there @nicomarti83? Referring to #573, #585 and #589 there are others getting this error using PureVPN and updated configs seems to fix it. Can you pull the latest image if you haven't and see if the issue persists?

**Comment by nicomarti83** [comment]
HI it work like a charm since a month but I don't do anything to help... I use the dev branch.
