### ISSUE TITLE
Docker stops during boot

### ISSUE THREAD

**Issue by joshuamallow** [haugene/docker-transmission-openvpn#474]
I am using PrivateVPN on a QNAP docker. This is as far as I can get with PrivateVPN (not sure if other providers work or not). Any thoughts or tips?

`Wed Apr 11 03:35:54 2018 OpenVPN 2.4.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar  1 
2018                                                                                                                                        
Wed Apr 11 03:35:54 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08                                                             
Wed Apr 11 03:35:54 2018 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.                                             
Wed Apr 11 03:35:54 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts              
Wed Apr 11 03:35:54 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]91.240.64.19:21003                                      
Wed Apr 11 03:35:54 2018 Socket Buffers: R=[212992->212992] S=[212992->212992]                                                              
Wed Apr 11 03:35:54 2018 UDP link local: (not bound)                                                                                        
Wed Apr 11 03:35:54 2018 UDP link remote: [AF_INET]91.240.64.19:21003 `

**Comment by joshuamallow** [comment]
I think it is an issue with the VPN config. I just tried WINDSCRIBE and it's working with no issues.

**Comment by haugene** [comment]
@joshuamallow feel free to re-open if you have any updates. But need some logs and the docker run command to give any good advice, as @firecat53 says.
