### ISSUE TITLE
"ADD tinyproxy /opt/tinyproxy/ "  is missing from Dockerfile.armhf and Dockerfile.alpine

### ISSUE THREAD

**Issue by goostincain** [haugene/docker-transmission-openvpn#475]
When trying to run container hangs when it trys to run the tunnelup.sh script in line 64 of openvpn/start.sh . Since ADD tinyproxy /opt/tinyproxy is not in the Dockerfile.armhf and .alpine as it is in the original Dockerfile, the script cannot find the tinyproxy/up.sh script

Solution:

add "ADD tinyproxy /opt/tinyproxy/ to the alternative dockerfiles.

Thanks

**Comment by firecat53** [comment]
I was going to suggest a note in the README and a fix to openvpn/tunnelUp.sh and tunnelDown.sh instead. 

The tinyproxy idea works great for when you want local access, but gets more complicated (I think, at least) when the container is running on a server. Also, people building the more minimal containers may not be interested in the additional processes.

This fix for will bypass starting tinyproxy if it doesn't exist, either in and Ubuntu or Alpine container:

openvpn/tunnelDown.sh:

    -/opt/tinyproxy/stop.sh
    +[ ! -f /usr/sbin/tinyproxy ] || /opt/tinyproxy/stop.sh

openvpn/tunnelUp.sh

    -/opt/tinyproxy/start.sh
    +[ ! -f /usr/sbin/tinyproxy ] || /opt/tinyproxy/start.sh

**Comment by goostincain** [comment]
I still like to use the proxy. However I've noticed the my fix above allows the container to boot, but still doesnt fix tiny proxy as it now is requestion a tinyproxy.conf file that isn't in the image

**Comment by lyz-code** [comment]
Thanks @firecat53 for your solution :) 

Hope they accept your PR

**Comment by lyz-code** [comment]
@firecat53 hope you don't mind, but I've made the [PR](https://github.com/haugene/docker-transmission-openvpn/pull/476)

**Comment by firecat53** [comment]
No worries... @haugene could handle the tinyproxy issue in a number of different ways. :smile:

**Comment by haugene** [comment]
Hi guys. I merged the pull-request by @lyz-code with the fix. Sure, the proxy should be configured to work with alpine and arm. But I'm not able to maintain all the versions and platforms of this container that closely. Focus on the ubuntu version and let the community manage the others.

But I agree this could go in the README, I think it could save some issues being created.
