### ISSUE TITLE
Transmission_Web_UI doesn't seem to work

### ISSUE THREAD

**Issue by tomhumphrey** [haugene/docker-transmission-openvpn#478]
I've set `TRANSMISSION_WEB_UI = combustion` however I'm still present with the default site when navigating. I've also tried with kettu and no joy there either. Can anyone advise how to change the webui?

**Comment by tomhumphrey** [comment]
On further investigation, there are no files downloaded in /opt just an empty folder. TRANSMISSION_WEB_HOME also remains the default value and seems to reset on start. Am running this on a Synology NAS

**Comment by tomhumphrey** [comment]
Fixed by updating to dev branch

**Comment by haugene** [comment]
Good that it now works. But there are no differences between lastest and dev now. I think it just triggered a pull, and to update you can just pull the latest in the future. If you want to stay on the stable branch.
