### ISSUE TITLE
Updating Docker to 18.03.0 (mac) causes container to fail to start

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [haugene/docker-transmission-openvpn#479]
Error is as follows: 

```
Pomelo:~ john$ docker start transmission
Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/bf20832867c6c115ff0f0347b1e32646eb95f5a2681a2e31a5ae3fda9814945c/merged\\\" at \\\"/var/lib/docker/overlay2/bf20832867c6c115ff0f0347b1e32646eb95f5a2681a2e31a5ae3fda9814945c/merged/usr/share/zoneinfo/Etc/UTC\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Error: failed to start containers: transmission
```

This happened immediately after the upgrade (teach me to do those, right?) and seems to be related to the `-v /etc/localtime:/etc/localtime:ro ` portion of the invocation command. Is this safe to leave out? Does it need to be modified? Half suspect the worst case scenario is that Transmission misreports start/finish times for torrents, but I'm not sure if Openvpn needs that as well.

**Comment by tomhumphrey** [comment]
Sorry unrelated - How did you get the vpn connection to work on a mac? I couldn't get it to initiate for the life of me

**Comment by haugene** [comment]
That mount is just getting time settings for the container to be read from the host. The only thing you'll notice by removing it is that your logs might be off by some hours depending on the timezone you're on.

As for the mac @tomhumphrey, I'm also running Docker 18.03.0-ce on my mac without issues. Are other docker containers working? For example `docker run -d -p 9898:80 nginx`, does that work and you get nginx welcome page on port 9898?

**Comment by adidalal** [comment]
Looks to be a documented issue in Docker for Mac (#2396). You can just pull the timezone from a static text file and replace the appropriate line in the `run` command. An example workaround:

----------

Save out `localtime`
```bash
readlink /etc/localtime | sed -e "s/^\/var\/db\/timezone\/zoneinfo\///" > /tmp/localtime
```

Modify `run`:
```bash
-v /tmp/localtime:/etc/localtime:ro
```

**Comment by james1238** [comment]
I just get a hash out on a mac even with this
