### ISSUE TITLE
Synology / TAP / Working ! (+extra provider)

### ISSUE THREAD

**Issue by mysterfr** [haugene/docker-transmission-openvpn#48]
Hi, and thanks for your great work !

I'm a total noob with Docker, but I've managed to make it work on my Synology NAS (DS2415+).
As my VPN provider was not listed, I had to create the config files myself in the image (bad, I know).

As my VPN provider uses TAP instead of TUN with full port forward to the client, I also had to trick the transmission start script, which makes it more generic.

OpenVPN calls the script and passes link information through the script arguments.
For instance in my OpenVPN log (visible trough docker log:
`Wed Jan 20 16:50:19 2016 /etc/transmission/start.sh tap0 1500 1574 91.240.66.198 255.255.255.224 init `

**My changes in /etc/transmission/start.sh**
Original : `tun0ip=$(ifconfig tun0 | sed -n '2 p' | awk '{print $2}' | cut -d: -f2)`
First suggestion : `tun0ip=$(ifconfig $1 | sed -n '2 p' | awk '{print $2}' | cut -d: -f2)`
 => use device name passed as first argument instead of arbitrarily using tun0

__**Second suggestion, straight forward ! : **__
`tun0ip=$4` 
  => use device IP address as passed directly as the 4th argument by OpenVPN !

Cherry on top, without any change, I can access the transmission web UI by either using my NAS' private IP, or the public IP.

**QUESTION :** How can I restrict the web UI to the local IP only (or put at least some auth on it ?)
(nevermind, I found out I had to pass extra ENV variables (TRANSMISSION_...) to tune it)

If you want to add PrivateVPN provider, here's the default file I used : 
```
client
remote-random
remote 91.240.64.20 21000
remote 91.240.64.20 21001
remote 91.240.64.20 21002
remote 91.240.64.20 21003
remote 91.240.64.19 21000
remote 91.240.64.19 21001
remote 91.240.64.19 21002
remote 91.240.64.19 21003
remote 91.240.64.18 21000
remote 91.240.64.18 21001
remote 91.240.64.18 21002
remote 91.240.64.18 21003
remote 91.240.64.18 21004
remote 91.240.64.18 21005
remote 91.240.64.18 21006
remote 91.240.64.18 21007
dev tap0
proto udp
resolv-retry infinite
nobind
persist-key
persist-tun
mute-replay-warnings
<ca>
-----BEGIN CERTIFICATE-----
MIIE3zCCA8egAwIBAgIJAMXxdK4eMVKxMA0GCSqGSIb3DQEBBQUAMIGlMQswCQYD
VQQGEwJTRTELMAkGA1UECBMCQ0ExEjAQBgNVBAcTCVN0b2NraG9sbTETMBEGA1UE
ChMKUHJpdmF0ZVZQTjETMBEGA1UECxMKUHJpdmF0ZVZQTjETMBEGA1UEAxMKUHJp
dmF0ZVZQTjERMA8GA1UEKRMIY2hhbmdlbWUxIzAhBgkqhkiG9w0BCQEWFHN1cHBv
cnRAcHJpdmF0dnBuLnNlMB4XDTE0MDQyNjA3MjcxNVoXDTI0MDQyMzA3MjcxNVow
gaUxCzAJBgNVBAYTAlNFMQswCQYDVQQIEwJDQTESMBAGA1UEBxMJU3RvY2tob2xt
MRMwEQYDVQQKEwpQcml2YXRlVlBOMRMwEQYDVQQLEwpQcml2YXRlVlBOMRMwEQYD
VQQDEwpQcml2YXRlVlBOMREwDwYDVQQpEwhjaGFuZ2VtZTEjMCEGCSqGSIb3DQEJ
ARYUc3VwcG9ydEBwcml2YXR2cG4uc2UwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQC/H+vc6QChwv2fj5XLzQcO05b3zIpPqQWsKunWyLnKUybFz79pUfhv
07L9arJj2LPwW0DVcyl9dxUWgqJOcWG5UrwYWF3ZDlGHkJywH5XKpnmdiqR8kkPi
atGm28aMpYIOvP+uIFrMD509cZONC0WIyVUrV9tpRX7LfKBti509ifPH+tINm5R9
B9dMQJKBI951wYXD8cCBodXsan++yOzuazkKHn1U1tY3TdqdIyD2HiBUbXhSH86w
fAmvY/O7L6f+YHzyI4hHseLzEo9htbaOQLvtg57cr2eBl2K46qiDwKn2q1aiJ2kx
uNkK1Q1uYAUzdyJHUsbbg+FZFxra8uAxAgMBAAGjggEOMIIBCjAdBgNVHQ4EFgQU
cLPgc+zc/6yPLEOKVPL62EW9rLAwgdoGA1UdIwSB0jCBz4AUcLPgc+zc/6yPLEOK
VPL62EW9rLChgaukgagwgaUxCzAJBgNVBAYTAlNFMQswCQYDVQQIEwJDQTESMBAG
A1UEBxMJU3RvY2tob2xtMRMwEQYDVQQKEwpQcml2YXRlVlBOMRMwEQYDVQQLEwpQ
cml2YXRlVlBOMRMwEQYDVQQDEwpQcml2YXRlVlBOMREwDwYDVQQpEwhjaGFuZ2Vt
ZTEjMCEGCSqGSIb3DQEJARYUc3VwcG9ydEBwcml2YXR2cG4uc2WCCQDF8XSuHjFS
sTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQA0UbskTX1IX6NLfAs3
8gPj321zN2ryj3ADxS8sLjy/+hUbdHu3FyQ12pI7jIVeAK4n7DccBRAMDBTWfNtv
jqFiWp10G2cI6d2xwDaDZFJNSWDyl4OYQjE4RtyBwH4IskKAdrT0oXg+kVgo8TiU
BwAvzuoZFWFHYYYhfCh9bGdicLCtBfiZ6zjlAltjVA0tjdbYCG5WkPqsXAUeKBmf
oQ5n10nzGdkZSMwlp9g5tFfni9kq/oSAupS5XXyvUG3IpFsdZWuZUo6fr5Hp6Ve5
Yvux4/hgnPLuT8E/46EKkATabVnpNa3/CgSqiJLEd4m6ZUiykqI7Hq3juKkK6DrT
ilw/
-----END CERTIFICATE-----
</ca> 

auth-user-pass /config/openvpn-credentials.txt
ns-cert-type server
comp-lzo
verb 3

# OpenVPN controls startup and shut down of transmission
script-security 2
up /etc/transmission/start.sh
down /etc/transmission/stop.sh
```

**Comment by haugene** [comment]
Hey! I've not been active here for a while. But cool that you got it working! :+1: 
Your "tun0ip=$4" solution sounds much better than the awk and cut that's there today. I will try to get some time to cach up with some technical debt on this container in the near future. Then I'll hopefully fix that and add the PrivateVPN provider. Thanks :)

**Comment by rolandb5** [comment]
Hi mysterfr, would you know how I can make those changes in the installed container on my Synology? Guess I'm even more noob than you :-)

**Comment by rolandb5** [comment]
I created a fork of Haugene's branch and made the edit. Created a docker from that github branch, but still not working :-(

**Comment by SVR111** [comment]
Wouw, sounds really good! I tried to build a new docker with AirVPN configuration, but somehow it fails running. The TAP isn't found... and I don' know what the TAP is :(
Hope someone can help or build a version with new config for AirVPN.

**Comment by haugene** [comment]
I've now added privateVPN as provider, created and merged a pull request from the fork by @rolandb5 containing the "tun0ip=$4" suggestion and created a new issue to add AirVPN as provider. I hope you can follow up there @SVR111 with a config.

If you're still having trouble with tap devices or something else @rolandb5, I suggest you make a new issue. When it comes to running this container on a Synology however there is already an issue with lots of information that you should read and try first.
