### ISSUE TITLE
Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)

### ISSUE THREAD

**Issue by stsvilik** [haugene/docker-transmission-openvpn#488]
Getting an error on start. Running container in Rancher. After some research it seems that openvpn needs to run with `sudo` to fix this.

**Comment by haugene** [comment]
Not familiar with Rancher. Still an issue or can we close this?
Did you change it in the image so that openvpn is started with sudo instead of the regular exec as root?

**Comment by stsvilik** [comment]
You may close this

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by thsmrtone1** [comment]
For others having this issue, the documentation doesn't specify much about it, but failing to use `--cap-add=NET_ADMIN` in your run command (or omitting `cap_add` configuration in docker-compose file in my case) will yield this error message.
