### ISSUE TITLE
NordVPN files are out of date

### ISSUE THREAD

**Issue by skogsmaskin** [haugene/docker-transmission-openvpn#492]
Just a heads up.

Seems like NordVPN has updated their ovpn files and the container just endlessly restarts without connecting.

Did a test with setting up a custom provider with the latest upstream file, and it worked fine.

Diffing the files shows that they have changed the certificates.

**Comment by skogsmaskin** [comment]
I see there is an incoming PR to update them, great!

https://github.com/haugene/docker-transmission-openvpn/pull/489

**Comment by haugene** [comment]
Yes. #489 is now merged to dev. Would be nice if you could verify it.

**Comment by skogsmaskin** [comment]
@haugene Built the image here from latest dev-branch, and it works great.

**Comment by coolboiime** [comment]
Looks like this has solved! Closing now!
