### ISSUE TITLE
Separate volume for data and downloads

### ISSUE THREAD

**Issue by krisnyse** [haugene/docker-transmission-openvpn#493]
Hi,

I'm I doing something wrong or is it not possible to separate the config files from the download folder structure? 
I run  this in docker compose:

  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      **- /srv/transmission:/data
      - /opt/downloads:/downloads**
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${username}
      - OPENVPN_PASSWORD=${password}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24 
      - PGID=1000
      - PUID=1000

Downloads folder is still set to /data/downloads after starting the container. If I change the variables manually in the settings.json file, it is overwritten the next time I restart the container. 

I've already got Radarr and Sonarr monitoring another folder structure for downloads from NZBget, so it would be nice to have transmission adopted to the same folder structure.

**Comment by haugene** [comment]
Yeah. That's a Transmission thing. It only reads the settings.json on startup and flushes changes to file when it exits. But we're overwriting the settings on each startup as networking changes every time and we want to bind to the correct address etc.

You should set the TRANSMISSION_DOWNLOAD_DIR variable as a start. All configuration of Transmission is possible through the environment variables and you can see the defaults [here](https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile#L55)

**Comment by krisnyse** [comment]
Thanks for the clarification. Makes sense now :) And thanks for a great piece of sw 👍
