### ISSUE TITLE
ENABLE_UFW on Synology NAS

### ISSUE THREAD

**Issue by tregota** [haugene/docker-transmission-openvpn#499]
I'm running this very helpful container on my 918+ and it works great without ufw but I want to run my VPN unNATed so I can receive connections. Running with ENABLE_UFW however prevents me from accessing the GUI and it results in Error messages such as:
```
ERROR: problem running ufw-init
/lib/ufw/ufw-init: 118: /lib/ufw/ufw-init: modprobe: not found
/lib/ufw/ufw-init: 118: /lib/ufw/ufw-init: modprobe: not found
/lib/ufw/ufw-init: 118: /lib/ufw/ufw-init: modprobe: not found
iptables-restore: line 55 failed
sysctl: setting key "net.ipv4.conf.default.rp_filter": Read-only file system
sysctl: setting key "net.ipv4.conf.all.rp_filter": Read-only file system
[...]
sysctl: setting key "net.ipv4.conf.all.log_martians": Read-only file system
Problem running '/etc/ufw/user.rules'
```

Now, I have figured out that if I move a copy of `/etc/ufw/user.rules` out of the container and remove the logging and limiting lines, leaving only the rules, then reinsert the file like so:
`-v /volume1/docker/user.rules:/etc/ufw/user.rules:ro`

Then all I get is the error message:
```
ERROR: Could not load logging rules
```
But everything works!
Now here is the question: Am I breaking anything important by doing this?
I'm not well versed in iptables stuff. 

Thanks for a great container.

**Comment by haugene** [comment]
@tregota Have you tested this after #559 was merged?
I'm closing this now for the same reasons as in #328. But feel free to re-open if you still have problems with it or you have some new clues to what's going on with this.
