### ISSUE TITLE
Use openvpn tunnel on local network side

### ISSUE THREAD

**Issue by SenexCrenshaw** [haugene/docker-transmission-openvpn#504]
It would be great to be able to route traffic through the openvpn tunnel from my local network. This way i can use this image for all my vpn needs.

**Comment by faulander** [comment]
Why don't you install OpenVPN directly then? Or do you mean Split-Tunneling by exactly telling the system which application should use VPN and which not?

**Comment by SenexCrenshaw** [comment]
yes split tunneling. I want to re-use the same IP the docker openvpn client has.

**Comment by haugene** [comment]
Other containers can have their traffic routed through the VPN by specifying --network container:<name|id>. For system wide configuration, this is probably out of scope of this image and should be installed and configured on the host system instead?
