### ISSUE TITLE
Can someone help me with this custom provider please?

### ISSUE THREAD

**Issue by faulander** [haugene/docker-transmission-openvpn#505]
Here's my Docker create:

> docker create --cap-add=NET_ADMIN --device=/dev/net/tun -v /root/downloads:/data -v /etc/localtime:/etc/localtime:ro -v /root/openvpn/config.ovpn:/etc/openvpn/custom/default.ovpn -e OPENVPN_PROVIDER=CUSTOM  -e OPENVPN_CONFIG=Germany -e OPENVPN_USERNAME=##USER### -e OPENVPN_PASSWORD=###PASS### -e WEBPROXY_ENABLED=false -e LOCAL_NETWORK=10.13.5.0/24 --log-driver json-file --log-opt max-size=10m -p 9092:9091 odroid-transmission 

Here's my config.ovpn:

> dev tun
> fast-io
> persist-key
> persist-tun
> nobind
> remote germany-frankfurt-1-ca-version-2.expressnetw.com 1195
> remote-random
> pull
> comp-lzo
> tls-client
> verify-x509-name Server name-prefix
> ns-cert-type server
> key-direction 1
> route-method exe
> route-delay 2
> tun-mtu 1500
> fragment 1300
> mssfix 1450
> verb 3
> cipher AES-256-CBC
> keysize 256
> auth SHA512
> sndbuf 524288
> rcvbuf 524288
> auth-user-pass /config/openvpn-credentials.txt
> <cert>
> -----BEGIN CERTIFICATE-----
> -----END CERTIFICATE-----
> </cert>
> <key>
> -----BEGIN RSA PRIVATE KEY-----
> -----END RSA PRIVATE KEY-----
> </key>
> <tls-auth>
> -----BEGIN OpenVPN Static key V1-----
> -----END OpenVPN Static key V1-----
> </tls-auth>
> <ca>
> -----BEGIN CERTIFICATE-----
> -----END CERTIFICATE-----
> </ca>

and here's the error:

> 
> Using OpenVPN provider: CUSTOM
> Supplied config Germany.ovpn could not be found.
> Using default OpenVPN gateway for provider custom
> Setting OPENVPN credentials...
> adding route to local network 10.13.5.0/24 via 172.17.0.1 dev eth0
> Tue May  8 16:42:24 2018 OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017
> Tue May  8 16:42:24 2018 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
> Tue May  8 16:42:24 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Tue May  8 16:42:24 2018 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
> Tue May  8 16:42:24 2018 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
> Tue May  8 16:42:24 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]91.109.28.145:1195
> Tue May  8 16:42:24 2018 Socket Buffers: R=[163840->327680] S=[163840->327680]
> Tue May  8 16:42:24 2018 UDP link local: (not bound)
> Tue May  8 16:42:24 2018 UDP link remote: [AF_INET]91.109.28.145:1195
> Tue May  8 16:42:24 2018 TLS: Initial packet from [AF_INET]91.109.28.145:1195, sid=657f335d 36c6dd2b
> Tue May  8 16:42:24 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Tue May  8 16:42:24 2018 VERIFY OK: depth=1, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=ExpressVPN CA, emailAddress=support@expressvpn.com
> Tue May  8 16:42:24 2018 VERIFY OK: nsCertType=SERVER
> Tue May  8 16:42:24 2018 VERIFY X509NAME OK: C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-2886-0a, emailAddress=support@expressvpn.com
> Tue May  8 16:42:24 2018 VERIFY OK: depth=0, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-2886-0a, emailAddress=support@expressvpn.com
> Tue May  8 16:42:25 2018 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
> Tue May  8 16:42:25 2018 [Server-2886-0a] Peer Connection Initiated with [AF_INET]91.109.28.145:1195
> Tue May  8 16:42:26 2018 SENT CONTROL [Server-2886-0a]: 'PUSH_REQUEST' (status=1)
> Tue May  8 16:42:26 2018 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.87.0.1,route 10.87.0.1,topology net30,ping 10,ping-restart 60,ifconfig 10.87.12.74 10.87.12.73'
> Tue May  8 16:42:26 2018 OPTIONS IMPORT: timers and/or timeouts modified
> Tue May  8 16:42:26 2018 OPTIONS IMPORT: --ifconfig/up options modified
> Tue May  8 16:42:26 2018 OPTIONS IMPORT: route options modified
> Tue May  8 16:42:26 2018 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
> Tue May  8 16:42:26 2018 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
> Tue May  8 16:42:26 2018 Data Channel Encrypt: Using 512 bit message hash 'SHA512' for HMAC authentication
> Tue May  8 16:42:26 2018 Data Channel Decrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
> Tue May  8 16:42:26 2018 Data Channel Decrypt: Using 512 bit message hash 'SHA512' for HMAC authentication
> Tue May  8 16:42:26 2018 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:04
> Tue May  8 16:42:26 2018 TUN/TAP device tun0 opened
> Tue May  8 16:42:26 2018 TUN/TAP TX queue length set to 100
> Tue May  8 16:42:26 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
> Tue May  8 16:42:26 2018 /sbin/ip link set dev tun0 up mtu 1500
> Tue May  8 16:42:26 2018 /sbin/ip addr add dev tun0 local 10.87.12.74 peer 10.87.12.73
> Tue May  8 16:42:26 2018 /etc/openvpn/tunnelUp.sh tun0 1500 1606 10.87.12.74 10.87.12.73 init
> Up script executed with tun0 1500 1606 10.87.12.74 10.87.12.73 init
> Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.87.12.74
> Generating transmission settings.json from env variables
> sed'ing True to true
> 
> -------------------------------------
> Transmission will run as
> -------------------------------------
> User name:   root
> User uid:    0
> User gid:    0
> -------------------------------------
> 
> STARTING TRANSMISSION
> NO PORT UPDATER FOR THIS PROVIDER
> Transmission startup script complete.
> /etc/openvpn/tunnelUp.sh: 4: /etc/openvpn/tunnelUp.sh: /opt/tinyproxy/start.sh: not found
> Tue May  8 16:42:26 2018 WARNING: Failed running command (--up/--down): could not execute external program
> Tue May  8 16:42:26 2018 Exiting due to fatal error

**Comment by todely** [comment]
1/ you need to change line in orignal file tunnelUp.sh:
/opt/tinyproxy/start.sh
with:
#/opt/tinyproxy/start.sh

to avoir tinyproxy trying to launch

2/ in your config.ovpn add line:
script-security 2

3/ rebuild container for ARM

4/ For starting container change:
 /root/openvpn/config.ovpn
with:
 /root/openvpn/config

**Comment by phipolis** [comment]
While @todely's suggestion to comment out `/opt/tinyproxy/start|stop.sh` in `tunnelUp|tunnelDown.sh` does avoid tinyproxy failing to start, I don't think it's the solution. `Dockerfile` contains the line `ADD tinyproxy /opt/tinyproxy/`, while `Dockerfile.armhf` does not. 

So I'm not sure which way is correct, but it seems like the x86 and armhf versions should be in parity. My biggest confusion is that tinyproxy seems meant run in a separate container, but it's also included and expected within the transmission-openvpn container.

**Comment by phipolis** [comment]
Oops, posted this before I found #475

**Comment by coolboiime** [comment]
Thanks for referencing issue. Closing for now.
