### ISSUE TITLE
Could't not connect to tracker

### ISSUE THREAD

**Issue by KZL1992** [haugene/docker-transmission-openvpn#507]
Hello Guys !

I setup everything and it works like a charm for many trackers.
But I tried to download from http://tracker.ygg.is:8080. And this tracker cannot be connected.. 
This is only a problem I faced while I am trying to use docker-transmission-openvpn, on the same network (but not connected to my vpn, seedbox.fr,) I tried to download from my own computer and it works.

Do you have any idea about that ? It seems that other torrents I downloaded are linked to multiple trackers. So maybe this is the reason why?

**Comment by niXta1** [comment]
Getting HTTP ERROR 404 on that one.

**Comment by coolboiime** [comment]
Doesn't seem like an issue with the container. Possibly with the VPN provider you're using. Closing for now until more logs are provided.

**Comment by renaudaste** [comment]
Hello @KZL1992 , 
Did you finally made it works ? i'm currenly facing facing the same issue on my NAS with YGGTorrent :
- working on my desktop, with VPN.
- working on my NAS running Debian/OpenMediaVault, without VPN.
- not working with this docker image, using NordVpn.
Thanks you in advance, 
Renaud
