### ISSUE TITLE
Issue with user permissions

### ISSUE THREAD

**Issue by auanasgheps** [haugene/docker-transmission-openvpn#509]
Hello there,

I have an issue with file permissions that is driving me nuts.
Here's my scenario:

- This container is running with a user callled **dockeruser**. PUID set to the user, PGID set to _Users_ group
- I am accessing the folder via SMB from my PC using my own user
- Both users belong to the group _Users_

**Hardware**: Synology DS918+
**Docker**: 17.05
**Container**: latest version, image built on 2018-04-08

Every time the container fires up, it changes the permissions of downloads folder, to this:
- **dockeruser** - full read and write access
- _Users_ group - only read access

All **existing** files and folders get this treatment, and new elements too.

I can change permissions to what I want, but they will get overriden at the next reboot.

The parent folder of the download folder has Read and Write access for the _Users_ group.

How can I solve this problem? Am I doing anything wrong?
Thanks

**Comment by setlursh** [comment]
Hi,

I'm experiencing the exact same issue, with a very similar permissions configuration. Hardware is a dell server, OS is Ubuntu 16.04 LTS. 

In terms of providing some more information, setting the TRANSMISSION_UMASK environment variable doesn't change the container's behaviour. On startup, the container sets the permissions of the directory to 755, even when TRANSMISSION_UMASK=2 (which should mask to 775).

Any help on this issue would be appreciated!

Thanks!

**Comment by auanasgheps** [comment]
Hi setlursh,
I've done a quick search and the feature you have mentioned should be the correct one for us. The problem is, correct me if I'm wrong, this feature is not standard and must be implemented in a container in order to work.

**Comment by coolboiime** [comment]
For Synology NAS devices, don't set a specific user to run. Simply add these two arguments in your run command:
```
    -e "PGID=100" \
    -e "PUID=1234" \
```

Afterward, you have two options. If you don't want to mess with the permissions, make sure the downloads folder is inside the docker folder. If you don't want it there, then you need to set a script to allow it 777 permissions for the downloads folder.

I have solved this issue before, so I am closing this for now. Feel free to comment below, thanks.

**Comment by auanasgheps** [comment]
Hi @coolboiime thanks for the heads up. Do you have an example for the script? Thanks!

**Comment by coolboiime** [comment]
```
# Downloads folder
chmod -R 777 /volume1/downloads/

exit 0
```

Have the script run in root every minute using the Synology's Task Manager

**Comment by auanasgheps** [comment]
That's easier than expected, thanks. 
I guess the script needs to run just after the container... Could this be integrated in the container?

**Comment by haugene** [comment]
@auanasgheps About integrating it in the container. People have different preferences and setup for these kinds of things, on different platforms, etc.

You can try to use the [script-torrent-done](https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#misc) option in Transmission and mount the script into the container. I haven't tried it, and I'm not familiar with the Synology side of this. But it could be an option. Guessing the script will be called with some parameters for the file name etc.

**Comment by auanasgheps** [comment]
@haugene I'm not sure if _script-torrent-done option_ would help, since the permission override is made for the whole download folder, and not for a single torrent file/folder.

I have discovered there is a way to make it happen "inside" the container, using **[Custom pre/post scripts](https://github.com/haugene/docker-transmission-openvpn#custom-prepost-scripts)** via the script _/scripts/transmission-post-start.sh_ 

I will update this case with the outcome, and if successful, will open a pull request to describe this behaviour in the documentation.

**Comment by haugene** [comment]
Aha, maybe I was too quick. I was thinking of the downloaded files.

The folder you're mounting is managed by docker or your file system. If docker changes it on start, then you need something running on your host.

But if it's what's happening [here](https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/userSetup.sh#L12) that's the problem, where we set 644/755 for files/dirs when PUID/PGID is set then we could make those configurable. So if you set PUID/PGID we can check for another config variable containing the desired permissions.

Then we're back to the proliferation of config variables, and the pre/post-script feature could be a good solution as it allows for more flexibility for the users.

As for the documentation. I feel #362 coming closer ;)

**Comment by auanasgheps** [comment]
> But if it's what's happening here that's the problem

Yes, I think this is where the problem happens!

> So if you set PUID/PGID we can check for another config variable containing the desired permissions.

Yes, I have set PUID and PGID for this container. So I believe it is actually "working": becomes the owner based on PUID I have set, the group (PGID) to read only.

I am using a dedicated user for docker, in the same group of the users, because I don't want to run it a "human" user. Should I use the post-script feature then?

**Comment by haugene** [comment]
For now I think that's a good solution if you can make it work. Then we can have a discussion if others also are having a problem with those permissions. But that script should set what could be described as a least common multiple that will be best for most people - and then local customizations should be done using the pre/post scripts or torrent-done scripts. To keep the container general purpose.

**Comment by auanasgheps** [comment]
Sorry for the late follow-up. I can confirm that the post scripts works great!

1. Added /scripts folder in the container configuration
2. Placed transmission-post-start.sh in such folder
3. The script contains the following

```
chmod -R 770 /download
exit 0
```
4. Profit

The script gets executed after every time the container is started (and logs show such event) and I always have correct permissions (read/write/execute for user and group). This is great, because I don't have to set up any weird recurring scripts in the host server.

I will make a contribution to the main page, so it may help others.

**Comment by coolboiime** [comment]
If you're using Synology, make sure the permissions are `777` or else you won't be able to access them inside File Station. I was just trying this before.

**Comment by auanasgheps** [comment]
I am using Synology, works fine with 770! I can access files using another users that belongs to the group "Users".

**Comment by coolboiime** [comment]
@auanasgheps That only applies if you set the permissions inside the container. I set my permissions outside the container, so that didn't work.

But either way works. Just make sure the permissions are `770` when your permission script is inside the container and `777` if outside the container.

**Comment by auanasgheps** [comment]
@coolbooime if you read my procedure you will see that I apply the permission inside the container, after Transmission has started.
I prefer this approach because I want to avoid system scripts, and it is more reliable as it is run only after Transmission has started.
