### ISSUE TITLE
Custom script to detect container's IP

### ISSUE THREAD

**Issue by tir38** [haugene/docker-transmission-openvpn#513]
The custom pre/post Transmission scripts are run on the container not host, right? I'm trying to achieve something like #323 with `transmission-pre-start.sh`:

```
#!/bin/bash

echo "Your external IP address is: "
curl -s http://whatismyip.akamai.com/
echo ""
```

But this is spitting out my host IP, not my container's VPN IP. I'm sure the VPN is working because I can use http://ipmagnet.services.cbcdn.com/ to see Transmission is running through VNP

**Comment by coolboiime** [comment]
I believe you need to hook into the OpenVPN interface, because the entire container isn't really in VPN mode. Only Transmission is.

**Comment by coolboiime** [comment]
Use this to check the IP locally:
`ip -4 addr show tun0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'`

Use this to check the IP through an API:
`curl -sS --interface tun0 http://ipinfo.io/ip`

**Comment by TMaddox** [comment]
A quick and easy workaround I am using:
https://torguard.net/checkmytorrentipaddress.php
