### ISSUE TITLE
Windows LCOW Support

### ISSUE THREAD

**Issue by borigas** [haugene/docker-transmission-openvpn#514]
Is Windows LCOW supported? Hopefully I'm not asking a duplicate, but I didn't see anything.

I'm having issues getting it running. I run:
`docker run --name=transmission --platform linux --cap-add=NET_ADMIN -d -v E:\DockerTest:/data -e OPENVPN_PROVIDER=PIA -e OPENVPN_CONFIG=Netherlands -e OPENVPN_USERNAME=****** -e OPENVPN_PASSWORD=******* -e WEBPROXY_ENABLED=false -e LOCAL_NETWORK=172.17.0.0/16 --log-driver json-file --log-opt max-size=10m -p 9091:9091 haugene/transmission-openvpn`

I've also tried running with `--device=/dev/net/tun` option included. Both can't find `/dev/net/tun`.

```
Using OpenVPN provider: PIA
Starting OpenVPN using config Netherlands.ovpn
Setting OPENVPN credentials...
adding route to local network 172.17.0.0/16 via 172.18.128.1 dev eth0
RTNETLINK answers: Operation not permitted
Fri May 18 00:36:12 2018 WARNING: file '/config/openvpn-credentials.txt' is group or others accessible
Fri May 18 00:36:12 2018 OpenVPN 2.4.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar  1 2018
Fri May 18 00:36:12 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Fri May 18 00:36:12 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri May 18 00:36:12 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]46.166.186.251:1198
Fri May 18 00:36:12 2018 UDP link local: (not bound)
Fri May 18 00:36:12 2018 UDP link remote: [AF_INET]46.166.186.251:1198
Fri May 18 00:36:12 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri May 18 00:36:13 2018 [870052d8272cf91f27719adb646ec93b] Peer Connection Initiated with [AF_INET]46.166.186.251:1198
Fri May 18 00:36:14 2018 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Fri May 18 00:36:14 2018 Exiting due to fatal error
```

Thanks for your help!

**Comment by coolboiime** [comment]
I don’t think so. The only versions I see is Ubuntu, Alpine Linux and Raspberry Pi

**Comment by ikbenfrank** [comment]
I have docker for windows installed with linux containers on windows 10 pro and it is working for me with the following docker-compose file excluding environment variables:

```
version: '3'
services:
 transmission:
  container_name: Transmission
  image: haugene/transmission
  cap_add:
   - NET_ADMIN
  devices:
   - /dev/net/tun
  restart: unless-stopped
  ports:
   - "8085:9091"
   - "8888:8888"
  dns:
   - 8.8.8.8
   - 8.8.4.4
```

**Comment by borigas** [comment]
Thanks @ikbenfrank, but I'm still having problems. I think those settings are equivalent to the `docker run` command I posted above, but just to double check I tried using docker-compose also. I'm still getting the same result as the log above. It's exiting with
```
Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
```
What version of Windows and Docker are you running? I'm on Windows 1803 and Docker version 18.05.0-ce, build f150324. Any other ideas on what the differences might be?

**Comment by haugene** [comment]
Hey @borigas, did you figure out anything here? Lost track of the Docker on Windows status, and Windows containers etc. LCOW is still running with a VM on the Windows host, right? could try to install openvpn on that host as it will create the tun interface.
Could be the same issue that is referred from the README for Synology. Where mknod is used to create /dev/net/tun.

**Comment by borigas** [comment]
I gave up on getting it running in LCOW. I ended up running on a linux machine instead

**Comment by haugene** [comment]
Allright. I've only been using linux and mac for years now - so have no idea for Docker on windows.
Would like it to work of course, but I'll close this for now. If there's more interest in it and more issues posted I might have to borrow a Windows computer and try to reproduce it :)

**Comment by StewartThomson** [comment]
Can confirm this is not working on windows. However I am also reproducing with binhex/arch-delugevpn and markusmcnugen/qbittorrentvpn so this isn't a haugene/transmission-openvpn specific problem
