### ISSUE TITLE
Creation of ipv6 address fails

### ISSUE THREAD

**Issue by theailer** [haugene/docker-transmission-openvpn#516]
I'm having issues with the openvpn part of this container:

Tue May 22 20:45:06 2018 TUN/TAP device tun0 opened
Tue May 22 20:45:06 2018 TUN/TAP TX queue length set to 100
Tue May 22 20:45:06 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=1
Tue May 22 20:45:06 2018 /sbin/ip link set dev tun0 up mtu 1500
Tue May 22 20:45:06 2018 /sbin/ip addr add dev tun0 10.5.0.7/16 broadcast 10.5.255.255
Tue May 22 20:45:06 2018 /sbin/ip -6 addr add fdda:d0d0:cafe:443::1005/64 dev tun0
RTNETLINK answers: Permission denied
Tue May 22 20:45:06 2018 Linux ip -6 addr add failed: external program exited with error status: 2
Tue May 22 20:45:06 2018 Exiting due to fatal error

**Comment by theailer** [comment]
After many frustrating attempts i finally got it working with supplying the docker run cmd with:
--sysctl net.ipv6.conf.all.disable_ipv6=0

**Comment by coolboiime** [comment]
The disable ipv6 is listed inside the readme.

**Comment by theailer** [comment]
Yeah I saw that. It is however posted under Synology Nas.

**Comment by coolboiime** [comment]
You’re right! I’ll figure a way and see how I can improve this.
