### ISSUE TITLE
Settings wont save

### ISSUE THREAD

**Issue by Masterzior** [haugene/docker-transmission-openvpn#517]
Changing values in the Settings.json file dosent work after restarting the docker instance.,

**Comment by coolboiime** [comment]
You're not supposed to edit the `settings.json` file.
The docker variables can help you with that.

```
OPENVPN_USERNAME=**None** \
OPENVPN_PASSWORD=**None** \
OPENVPN_PROVIDER=**None** \
TRANSMISSION_ALT_SPEED_DOWN=50 \
TRANSMISSION_ALT_SPEED_ENABLED=false \
TRANSMISSION_ALT_SPEED_TIME_BEGIN=540 \
TRANSMISSION_ALT_SPEED_TIME_DAY=127 \
TRANSMISSION_ALT_SPEED_TIME_ENABLED=false \
TRANSMISSION_ALT_SPEED_TIME_END=1020 \
TRANSMISSION_ALT_SPEED_UP=50 \
TRANSMISSION_BIND_ADDRESS_IPV4=0.0.0.0 \
TRANSMISSION_BIND_ADDRESS_IPV6=:: \
TRANSMISSION_BLOCKLIST_ENABLED=false \
TRANSMISSION_BLOCKLIST_URL=http://www.example.com/blocklist \
TRANSMISSION_CACHE_SIZE_MB=4 \
TRANSMISSION_DHT_ENABLED=true \
TRANSMISSION_DOWNLOAD_DIR=/data/completed \
TRANSMISSION_DOWNLOAD_LIMIT=100 \
TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0 \
TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true \
TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5 \
TRANSMISSION_ENCRYPTION=1 \
TRANSMISSION_IDLE_SEEDING_LIMIT=30 \
TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false \
TRANSMISSION_INCOMPLETE_DIR=/data/incomplete \
TRANSMISSION_INCOMPLETE_DIR_ENABLED=true \
TRANSMISSION_LPD_ENABLED=false \
TRANSMISSION_MAX_PEERS_GLOBAL=200 \
TRANSMISSION_MESSAGE_LEVEL=2 \
TRANSMISSION_PEER_CONGESTION_ALGORITHM= \
TRANSMISSION_PEER_ID_TTL_HOURS=6 \
TRANSMISSION_PEER_LIMIT_GLOBAL=200 \
TRANSMISSION_PEER_LIMIT_PER_TORRENT=50 \
TRANSMISSION_PEER_PORT=51413 \
TRANSMISSION_PEER_PORT_RANDOM_HIGH=65535 \
TRANSMISSION_PEER_PORT_RANDOM_LOW=49152 \
TRANSMISSION_PEER_PORT_RANDOM_ON_START=false \
TRANSMISSION_PEER_SOCKET_TOS=default \
TRANSMISSION_PEX_ENABLED=true \
TRANSMISSION_PORT_FORWARDING_ENABLED=false \
TRANSMISSION_PREALLOCATION=1 \
TRANSMISSION_PREFETCH_ENABLED=1 \
TRANSMISSION_QUEUE_STALLED_ENABLED=true \
TRANSMISSION_QUEUE_STALLED_MINUTES=30 \
TRANSMISSION_RATIO_LIMIT=2 \
TRANSMISSION_RATIO_LIMIT_ENABLED=false \
TRANSMISSION_RENAME_PARTIAL_FILES=true \
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false \
TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0 \
TRANSMISSION_RPC_ENABLED=true \
TRANSMISSION_RPC_HOST_WHITELIST= \
TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=false \
TRANSMISSION_RPC_PASSWORD=password \
TRANSMISSION_RPC_PORT=9091 \
TRANSMISSION_RPC_URL=/transmission/ \
TRANSMISSION_RPC_USERNAME=username \
TRANSMISSION_RPC_WHITELIST=127.0.0.1 \
TRANSMISSION_RPC_WHITELIST_ENABLED=false \
TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=true \
TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=false \
TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME= \
TRANSMISSION_SEED_QUEUE_ENABLED=false \
TRANSMISSION_SEED_QUEUE_SIZE=10 \
TRANSMISSION_SPEED_LIMIT_DOWN=100 \
TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false \
TRANSMISSION_SPEED_LIMIT_UP=100 \
TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false \
TRANSMISSION_START_ADDED_TORRENTS=true \
TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false \
TRANSMISSION_UMASK=2 \
TRANSMISSION_UPLOAD_LIMIT=100 \
TRANSMISSION_UPLOAD_LIMIT_ENABLED=0 \
TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=14 \
TRANSMISSION_UTP_ENABLED=true \
TRANSMISSION_WATCH_DIR=/data/watch \
TRANSMISSION_WATCH_DIR_ENABLED=true \
TRANSMISSION_HOME=/data/transmission-home \
ENABLE_UFW=false \
UFW_ALLOW_GW_NET=false \
UFW_EXTRA_PORTS= \
TRANSMISSION_WEB_UI= \
PUID= \
PGID= \
TRANSMISSION_WEB_HOME= \
DROP_DEFAULT_ROUTE= \
WEBPROXY_ENABLED=false \
WEBPROXY_PORT=8888 \
```

**Comment by haugene** [comment]
#150 #158 #322 and there's more like this. We need to update the settings.json file on each restart because the IP changes and we want to update the bind address. Also, we've gone for a "stateless" approach where stuff like this needs to be given as env variables so that the container is portable and not dependant on the current state of settings.json.

**Comment by sglewis100** [comment]
Just to add to this question, I don't like defining a password in a docker command line. I do have /config mapped to a local directory (i.e. -v /mypath/config:/config) and in there are two files... openvpn-credentials.txt which I can edit and then chmod 600 plus transmission-credentials.txt, which seems to get overwritten each time the container restarts.

It would be nice to either be able to modify that file, or have a variable like TRANSMISSION_CREDENTIALS=/path/openvpn.credentials to avoid passing username and password from the command line. Thoughts?

Incidentally... this is an amazing project that really added a ton of value to my HTPC setup. I had everything in Docker except transmission and my vpn, which was on a separate Linux VM. Now I've consolidated it all into one machine thanks to this project!

**Comment by haugene** [comment]
Glad to hear you like the project @sglewis100.

That feature should already be implemented. If you mount a file to /config/openvpn-credentials.txt you don't have to set the username and password variables. https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L44

That should avoid it being overwritten. If you provide the username and password vars it will still overwrite the existing file.

**Comment by sglewis100** [comment]
That feature def. exists for openvpn, and I use it by mounting /config and having a username/password in openvpn-credentials.

There is a similar transmission-credentials file in that same directory, but it gets overwritten at startup. I don't see equivalent code to handle that file in your transmission code directory. So I'm having to pass username/password via variable. My issue with this, is anyone on that box with access to docker can do a docker inspect transmission | grep RPC_PASSWORD and view the password in all it's plaintext glory.

Attached a screenshot, since I think you read my last comment and thought I was concerned with openvpn, and not transmission - so just in case. ;) 

![docker-screenshot](https://user-images.githubusercontent.com/40810349/42284440-8202c4e6-7f7a-11e8-9cc7-4947e7da3042.png)
