### ISSUE TITLE
No external connections when VPN is running

### ISSUE THREAD

**Issue by scottydelicious** [haugene/docker-transmission-openvpn#52]
I fired up a haugene/transmission-openvpn docker instance with PIA credentials. I can reach the web interface, but adding magnet links or torrent files never progresses. They are stalled at 0% with no connections.

Tailing the log I can see: 
`(6) Could not resolve host: www.privateinternetaccess.com
Got new port  from pia
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 0: No Response
`

When I "docker exec -it haugene-transmission /bin/bash", I cannot ping anything. restarting openvpn through the script doesn't help. If i issue "ip link delete tun0" to remove the tunnel device (tun0-00), I get "File descriptor in bad state".

Any ideas?

**Comment by haugene** [comment]
Sounds like a DNS issue. Have you tried starting the container with Google dns as stated in the "Known Issues" section of the readme?

**Comment by scottydelicious** [comment]
Thank you haugene. I feel like an idiot missing such a simple corrective measure that was laid out right in the README. Adding "--dns 8.8.8.8 --dns 8.8.4.4" to my docker run command resolved this issue.

I apologize for taking up your time on this. Please mark this issue as solved or resolved.

SOLUTION: add --dns flags to the docker command.

**Comment by haugene** [comment]
No worries :) Glad it worked!
