### ISSUE TITLE
why is transmission spamming my firewall?

### ISSUE THREAD

**Issue by blackyellowred** [haugene/docker-transmission-openvpn#522]
Hey,

Everytime transmission has a torrent loaded and downloading it keeps spamming my firewall logs on pfsense.
![firewall](https://i.imgur.com/etv5gZb.png)

When I use vpns on other computers I don't get this issue.

**Comment by coolboiime** [comment]
Can you tell us more information? I don't see why your firewall would spam your firewall logs unless you are blocking the upload port.

**Comment by blackyellowred** [comment]
I don't have outgoing filtering enabled.
Well I have openvpn running on my firewall but it is only setup to forward traffic from certain vlans and not on the vlan docker runs on. I suppose I can set it up to forward all traffic from my docker boxes IP address directly from my firewall. Maybe that is was it causing the problem. 
Here is my routing table:
![routes](https://i.imgur.com/Z6oudNa.png)

If I add to my firewalls' instance of openvpn:
`ifconfig 10.7.7.9 255.255.255`
`ifconfig-noexec`
I don't get the whole subnet `10.7.7.9/24` added to my routing table but that is not how it is suppose to work and it keeps disconnecting and it still blocks outgoing traffic.

**Comment by blackyellowred** [comment]
I have decided to put my whole docker machine on vpn, so I don't need help anymore. But I am sure its to do with routes, thanks anyway!
