### ISSUE TITLE
webGUI connection timed out on Win10, docker virtualbox

### ISSUE THREAD

**Issue by j2l** [haugene/docker-transmission-openvpn#524]
Hi,
First of all, thank you for this gem!
I have transmission running in the docker container:
docker run --cap-add=NET_ADMIN --privileged="true" --device=/dev/net/tun --net="bridge" --name="transmission" --dns 8.8.8.8 --dns 8.8.4.4 -d -v /transmission/data:/dat
a -e OPENVPN_PROVIDER=VPNBOOK -e OPENVPN_USERNAME=whatever -e OPENVPN_PASSWORD=whatever -e LOCAL_NETWORK=192.168.1.1/16 --log-driver json-file --log-opt max-size=10m -p 9091:9091 haugene/transmission-openvpn

DNS is working fine (I checked I'm seen as 176.126.237.217 from the VM).
But I can't access 192.168.99.100:9091 (docker windows image) from the PC host (192.168.1.13).
Did I miss something?
Thanks

Full message below:
```
Using OpenVPN provider: VPNBOOK
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.1.1/16 via 172.17.0.1 dev eth0
RTNETLINK answers: Invalid argument
Tue May 29 09:21:32 2018 WARNING: file '/config/openvpn-credentials.txt' is group or others accessible
Tue May 29 09:21:32 2018 OpenVPN 2.4.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar  1 2018
Tue May 29 09:21:32 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Tue May 29 09:21:32 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Tue May 29 09:21:32 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue May 29 09:21:32 2018 NOTE: --fast-io is disabled since we are not using UDP
Tue May 29 09:21:32 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]176.126.237.217:443
Tue May 29 09:21:32 2018 Socket Buffers: R=[87380->87380] S=[16384->16384]
Tue May 29 09:21:32 2018 Attempting to establish TCP connection with [AF_INET]176.126.237.217:443 [nonblock]
Tue May 29 09:21:33 2018 TCP connection established with [AF_INET]176.126.237.217:443
Tue May 29 09:21:33 2018 TCP_CLIENT link local: (not bound)
Tue May 29 09:21:33 2018 TCP_CLIENT link remote: [AF_INET]176.126.237.217:443
Tue May 29 09:21:36 2018 TLS: Initial packet from [AF_INET]176.126.237.217:443, sid=1e13312c cb01af71
Tue May 29 09:21:36 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue May 29 09:21:41 2018 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Tue May 29 09:21:41 2018 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Tue May 29 09:21:41 2018 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 1024 bit RSA
Tue May 29 09:21:41 2018 [vpnbook.com] Peer Connection Initiated with [AF_INET]176.126.237.217:443
Tue May 29 09:21:42 2018 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Tue May 29 09:21:45 2018 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS  8.8.4.4,dhcp-option DNS  91.239.100.100,route 10.9.0.1,topology net30,ping 5,ping-restart 30,ifconfig 10.9.0.34 10.9.0.33,peer-id 0,cipher AES-256-GCM'
Tue May 29 09:21:45 2018 OPTIONS IMPORT: timers and/or timeouts modified
Tue May 29 09:21:45 2018 OPTIONS IMPORT: --ifconfig/up options modified
Tue May 29 09:21:45 2018 OPTIONS IMPORT: route options modified
Tue May 29 09:21:45 2018 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Tue May 29 09:21:45 2018 OPTIONS IMPORT: peer-id set
Tue May 29 09:21:45 2018 OPTIONS IMPORT: adjusting link_mtu to 1627
Tue May 29 09:21:45 2018 OPTIONS IMPORT: data channel crypto options modified
Tue May 29 09:21:45 2018 Data Channel: using negotiated cipher 'AES-256-GCM'
Tue May 29 09:21:45 2018 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue May 29 09:21:45 2018 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue May 29 09:21:45 2018 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
Tue May 29 09:21:45 2018 TUN/TAP device tun0 opened
Tue May 29 09:21:45 2018 TUN/TAP TX queue length set to 100
Tue May 29 09:21:45 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Tue May 29 09:21:45 2018 /sbin/ip link set dev tun0 up mtu 1500
Tue May 29 09:21:45 2018 /sbin/ip addr add dev tun0 local 10.9.0.34 peer 10.9.0.33
Tue May 29 09:21:45 2018 /etc/openvpn/tunnelUp.sh tun0 1500 1555 10.9.0.34 10.9.0.33 init
Up script executed with tun0 1500 1555 10.9.0.34 10.9.0.33 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.9.0.34
Generating transmission settings.json from env variables
sed'ing True to true
2018-05-29T09:21:45.607773229Z 
-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------
2018-05-29T09:21:45.607834413Z 
STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Tue May 29 09:21:47 2018 /sbin/ip route add 176.126.237.217/32 via 172.17.0.1
Tue May 29 09:21:47 2018 /sbin/ip route add 0.0.0.0/1 via 10.9.0.33
Tue May 29 09:21:47 2018 /sbin/ip route add 128.0.0.0/1 via 10.9.0.33
Tue May 29 09:21:47 2018 /sbin/ip route add 10.9.0.1/32 via 10.9.0.33
Tue May 29 09:21:47 2018 Initialization Sequence Completed
```

**Comment by haugene** [comment]
Sounds like you have two layers of IP networks? That can create some extra difficulties sometimes.

So docker is running on it's own network (172.17.x.x) and then the docker host is on 192.168.99.X and your host on 192.168.1.X. I do agree that your LOCAL_NETWORK CIDR with 192.168.1.1/16 should allow traffic from both the docker host and your host machine but have you tried to see where it stops?

So if you get a shell inside the docker host and do a curl localhost:9091, is that working? If so it might be port forwarding from your windows host to your docker host vm.

In any case the proxy solution might be simpler from a network perspective, it's described in the README and might be worth a shot.

**Comment by j2l** [comment]
Thanks for replying so quickly!
curl throws a 301:
```
root@8e811645f66c:/# curl localhost:9091
<h1>301: Moved Permanently</h1>
```
192.168.99.100 is the standard IP for Docker Windows (no idea how to change it). I don't know where 172.x.x.x comes from and 192.168.1.x is just my LAN/router.
I accessed other Docker containers web interface on 192.168.99.100 (but nothing was running when trying this image).

Indeed, the proxy works! Fixed

[Sorry in advance for the next noob question:] 
How to run the container with the same name again? 
For now, I have to delete transmission in kitematic before launching it again, because launching through kitematic doesn't work for this transmission image.
The proxy container has the weird name and the link is empty in Kitematic (but exists since proxy works). I asked Kitematic support if their links were something else but never got a reply. 
Should I add in the proxy the link to transmission and launch it via Kitematic next time?

**Comment by haugene** [comment]
Looks like you curl'ed from within the container. That should definitely work. Then you could try the same in the VM and on the host to see where the problem lies.

192.168.99.100 - probably the IP of the VM used to run the containers in
172.x.x.x - the Docker network

I don't know much about Kitematic, never used it. But if you want to create a new container with the same name as before, you need to remove the one that has this name now. `docker rm <name>` should do it. Linking and launching in Kitematic should work.

**Comment by j2l** [comment]
And now it's the port and setting issue.
Looks like the port is forbidden on VPNBOOK.
I can change the bool to true, but it comes back to false after restarting:
![image](https://user-images.githubusercontent.com/65325/40671979-be307cac-636d-11e8-8f44-d1c525ec17da.png)
Sorry, it's another ticket subject but I don't get how to set it up.

**Comment by j2l** [comment]
OK, so, for other readers using 2018 kitematic (unfinished edition): Delete the container in kitematic and rerun the docker run with `-e TRANSMISSION_PEER_PORT_RANDOM_ON_START=true` and `--sysctl net.ipv6.conf.all.disable_ipv6=0`

ifconfig was run at the docker VM level and it's still IPv6.
