### ISSUE TITLE
Upload doesn't work

### ISSUE THREAD

**Issue by elgabo86** [haugene/docker-transmission-openvpn#525]
Hi,
I'm on the armhf version with PIA. 
- Port is opened (logged too)
- Logs of container have no error
- Acces UI from external network ok
- Dns of google changed
- Private tracker is announced and no error in transmission
Download works but upload not.
Where is my fault ? 
Sorry for my poor english and thanks in advance for help!

**Comment by niXta1** [comment]
What does ipleak.net say when you add it's magnet link?

**Comment by elgabo86** [comment]
Added the magnet link and it shows an ip from PIA and the open port

**Comment by elgabo86** [comment]
After several hours, the upload starts, but very slowly.
Sorry for the inconvenience.
Solved.
