### ISSUE TITLE
When connecting via RPC / at the end is needed

### ISSUE THREAD

**Issue by niXta1** [haugene/docker-transmission-openvpn#528]
Is it just me or does this container always need a / at the end of the RPC address?
I've proposed to add this information to the readme in a PR.

**Comment by LennyM8472** [comment]
Hi,

I have no idea why I can't get RPC working.

My docker RPC variables are as followed
`              -e TRANSMISSION_RPC_AUTHENTIFICATION_REQUIRED=true \
              -e TRANSMISSION_RPC_ENABLED=true \
              -e TRANSMISSION_RPC_USERNAME=admin \
              -e TRANSMISSION_RPC_PASSWORD=XXXX \
              -e TRANSMISSION_RPC_URL="/transmission/" \
              -e TRANSMISSION_RPC_WHITELISTE="127.0.0.1,192.168.*.*" \`

If I enter website::9091/transmission/rpc/ I receive following error:
"409: Conflict
Your request had an invalid session-id header.

To fix this, follow these steps:

When reading a response, get its X-Transmission-Session-Id header and remember it
Add the updated header to your outgoing requests
When you get this 409 error message, resend your request with the updated header
This requirement has been added to help prevent CSRF attacks.

X-Transmission-Session-Id: xxxxx"

I just want to have simple password-protection for transmission.

Thanks for help in advance.

Best regards
Lenny

**Comment by niXta1** [comment]
I've had this problem on my Synology NAS. I ended up using Synology's internal nginx.
What device are you running this on?

**Comment by LennyM8472** [comment]
Hi,

I run it on a QNAP (Containerstation via ssh).

Best regards
Lennart

**Comment by niXta1** [comment]
Is there a built in nginx in the QNAP that you can try?
