### ISSUE TITLE
add HideMyAss VPN provider (HMA)

### ISSUE THREAD

**Issue by gaeldevo** [haugene/docker-transmission-openvpn#53]
hello,

thanks a lot for your stuff !

i try to add a new provider, but i'm working on a synology.
i'm not able to start with a vpn missconfiguration.

i tried with a free hideme account but it does not work with trial version (only few servers are available)

is it possible to directly add a HMA provider ?

thanks

**Comment by haugene** [comment]
Referring to your comment in issue #45 and closing this issue

**Comment by haugene** [comment]
Ahhh, a little quick there. I'll keep this issue open until I've added it for others. Or until you submit a PR with HMA :)

**Comment by haugene** [comment]
I have now added HMA as provider on the dev branch. If one of you could verify that it works by using the dev tag of the image (haugene/transmission-openvpn:dev) then I will merge it to the master branch and main image.

**Comment by haugene** [comment]
Merged to master and is now available in default image
