### ISSUE TITLE
OpenVPN not resuming after internet dropout

### ISSUE THREAD

**Issue by tralce** [haugene/docker-transmission-openvpn#530]
Not really sure how to diagnose this. I have a bit of an unstable connection, which tends to drop out for a second or two every few hours. When it comes back up, OpenVPN doesn't seem to, or otherwise torrents don't resume until I restart the container. 

I've thought about writing a wrapper script that does `docker exec -it transmission-openvpn ping -c 1 google.com` then restarts the container if it fails, but I was hoping before I got involved in that that I was missing something simple. Shouldn't it be resetting OpenVPN by itself already?

**Comment by coolboiime** [comment]
Referencing issue #454. Closing this for now.
