### ISSUE TITLE
Can you build more often?

### ISSUE THREAD

**Issue by a3rosol** [haugene/docker-transmission-openvpn#532]
Both master and dev branches?

**Comment by coolboiime** [comment]
What's wrong?

**Comment by haugene** [comment]
The automated builds are set up to trigger on changes in the code. So they will always be up to date code wise. But I'm guessing you want more frequent builds to have updates of base image and the OS installed packages?

**Comment by derekoharrow** [comment]
Looks like transmission is at v2.94 while this image is still at v2.93.

**Comment by coolboiime** [comment]
@derekoharrow That’s because the source is still using v2.93.

**Comment by haugene** [comment]
I see you closed this. Just to add some more information. I can't seem to find any periodic build settings on the Docker hub automated build. I could use build triggers and run a script from a server that triggers the builds daily or weekly, but it won't be a top priority for now. I have a server formatting coming up, maybe I'll set something up after that.

If this is something many want to see fixed, bump this issue.
