### ISSUE TITLE
Magnet links stuck at retrieving metadata (0.00%)

### ISSUE THREAD

**Issue by derekoharrow** [haugene/docker-transmission-openvpn#533]
I've installed this and have it working correctly. I can open the web UI, download torrents, etc. It connects ok via my VPN provider (newshosting).
Everything seems fine, except for magnet downloads which get added but then don't progress above 0% - they just say "Magnetized transfer - retrieving metadata (0.00%)"
Any ideas?

**Comment by coolboiime** [comment]
It’s most likely your VPN provider stalling. This happens to me often when I have the container open a very long time, and I’m forced to restart with the script I wrote since the OpenVPN restarter doesn’t work.

**Comment by derekoharrow** [comment]
I don't think that's it as torrent files work fine - it's just magnet downloads that don't - and it's like it even when the container and VPN link is first started.

**Comment by coolboiime** [comment]
Can you paste your docker logs so I can see?

**Comment by derekoharrow** [comment]
Herre you go - not much in there (fresh log with a transmission re-start).

"Pantheon" is loaded from a .torrent - the other 2 are magnetised...

> [2018-06-18 06:27:50.288] Transmission 2.93 (3c5870d4f5) started (session.c:740)
> [2018-06-18 06:27:50.288] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
> [2018-06-18 06:27:50.289] RPC Server Adding address to whitelist: 192.168.*.* (rpc-server.c:971)
> [2018-06-18 06:27:50.289] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
> [2018-06-18 06:27:50.289] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
> [2018-06-18 06:27:50.289] Couldn't bind port 51413 on fe80::: Invalid argument (net.c:380)
> [2018-06-18 06:27:50.289] Port Forwarding Stopped (port-forwarding.c:180)
> [2018-06-18 06:27:50.289] UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:84)
> [2018-06-18 06:27:50.289] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:89)
> [2018-06-18 06:27:50.289] UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:95)
> [2018-06-18 06:27:50.289] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:100)
> [2018-06-18 06:27:50.289] DHT Reusing old id (tr-dht.c:307)
> [2018-06-18 06:27:50.289] DHT Bootstrapping from 72 IPv4 nodes (tr-dht.c:156)
> [2018-06-18 06:27:50.289] Using settings from "/data/transmission-home" (daemon.c:528)
> [2018-06-18 06:27:50.289] Saved "/data/transmission-home/settings.json" (variant.c:1266)
> [2018-06-18 06:27:50.289] Watching "/data/watch" for new .torrent files (daemon.c:573)
> [2018-06-18 06:27:50.289] Loaded 4 torrents (session.c:2034)
> [2018-06-18 06:27:59.292] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Starting IPv4 DHT announce (poor, 13 nodes) (tr-dht.c:577)
> [2018-06-18 06:28:03.285] Couldn't set source address fe80:: on 24: Invalid argument (net.c:272)
> [2018-06-18 06:28:03.285] Couldn't set source address fe80:: on 24: Invalid argument (net.c:272)
> [2018-06-18 06:28:04.287] Ray Kurzweil - Are We Spiritual Machines.pdf Starting IPv4 DHT announce (poor, 16 nodes) (tr-dht.c:577)
> [2018-06-18 06:28:06.285] Sam Bourne - Pantheon EPUB MOBI Starting IPv4 DHT announce (poor, 16 nodes) (tr-dht.c:577)
> [2018-06-18 06:28:11.284] Searching for web interface file "/config/.local/share/transmission/web/index.html" (platform.c:430)
> [2018-06-18 06:28:11.284] Searching for web interface file "/usr/share/transmission/web/index.html" (platform.c:430)
> [2018-06-18 06:28:41.285] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Scrape error: Could not connect to tracker (announcer.c:1279)
> [2018-06-18 06:28:41.285] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Retrying scrape in 20 seconds. (announcer.c:1288)
> [2018-06-18 06:28:50.285] Sam Bourne - Pantheon EPUB MOBI Scrape error: Connection failed (announcer.c:1279)
> [2018-06-18 06:28:50.285] Sam Bourne - Pantheon EPUB MOBI Retrying scrape in 20 seconds. (announcer.c:1288)
> [2018-06-18 06:28:50.285] Sam Bourne - Pantheon EPUB MOBI Connection failed (announcer.c:996)
> [2018-06-18 06:28:50.285] Sam Bourne - Pantheon EPUB MOBI Retrying announce in 307 seconds. (announcer.c:1005)
> [2018-06-18 06:28:50.285] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Connection failed (announcer.c:996)
> [2018-06-18 06:28:50.285] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Retrying announce in 20 seconds. (announcer.c:1005)
> [2018-06-18 06:28:50.286] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Scrape error: Connection failed (announcer.c:1279)
> [2018-06-18 06:28:50.286] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Retrying scrape in 20 seconds. (announcer.c:1288)
> [2018-06-18 06:28:50.286] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Connection failed (announcer.c:996)
> [2018-06-18 06:28:50.286] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Retrying announce in 329 seconds. (announcer.c:1005)
> [2018-06-18 06:29:21.285] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Could not connect to tracker (announcer.c:996)
> [2018-06-18 06:29:21.285] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Retrying announce in 320 seconds. (announcer.c:1005)
> [2018-06-18 06:29:31.285] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Scrape error: Could not connect to tracker (announcer.c:1279)
> [2018-06-18 06:29:31.285] Sam+Bourne+-+The+Chosen+One+EPUB+MOBI.torrent Retrying scrape in 902 seconds. (announcer.c:1288)

**Comment by coolboiime** [comment]
Seems like there’s an issue with IPv6, did you disable it using the container arguments?

**Comment by derekoharrow** [comment]
I read about a couple of issues to do with excessive IPv6 errors in the logs.
One was MTU, so I've set mssfix to 1640.
The other was to set TRANSMISSION_BIND_ADDRESS_IPV6 to "fe80::" (I did also try "::" which seemed to do similar but gave slightly different errors in the log).
From what I read, I couldn't see how you actually disable IPV6 in the container.
However - magnet links weren't downloading before I made these changes either.

**Comment by derekoharrow** [comment]
Just found out that my VPN provider (NEWSHOSTING) doesn't support port-forwarding - could this be why?

**Comment by coolboiime** [comment]
Using this argument, you can disable IPv6:

`--sysctl net.ipv6.conf.all.disable_ipv6=0`

**Comment by coolboiime** [comment]
From my experience, VPN’s that have no port forwarding enabled would only be able to download.

This doesn’t cause magnet links to stop working. If it’s not the VPN, then the source could be an issue.

Transmission shows the status of each magnet. It could just be that it’s waiting for authentication.

**Comment by a3rosol** [comment]
@derekoharrow: did you follow the recommendation to use googles dns servers? 
You know the old mantra: [It's always DNS](https://i.imgur.com/WmRbmf5.png)

**Comment by derekoharrow** [comment]
Yes - using 8.8.8.8

**Comment by knightowl1000** [comment]
Hi, I'm having the exact same issue where magnitized torrents are not downloading. Where do I find the logs from? My docker logs don't show any logs in regards to transmission. Also @coolboiime - I think --sysctl net.ipv6.conf.all.disable_ipv6=0 actually means to enable ipv6 because when I do that, I get a ipv6 ip when checking inside the container using the command ip a. When I have it set to 1, I don't get an IP, but it still doesn't help with the magnitized torrents.

**Comment by cannona** [comment]
I'm also facing this same issue. Any ideas? How can I help you folks troubleshoot things?

**Comment by knightowl1000** [comment]
@cannona - It seems coolbiimes suggestion worked, but as I mentioned in my comment, it looks like --sysctl net.ipv6.conf.all.disable_ipv6=0 actually enables ipv6 because I got an ipv6 ip. but when I changed it to --sysctl net.ipv6.conf.all.disable_ipv6=1 I didn't. I have it also pointed to googles DNS 8.8.8.8 and 8.8.4.4. Some magnitized downloads that were not working, I took the URL and put it in utorrent and it did not work, then I took 2 magnitized URLs (new ones) and put them in transmission and 1 worked and the other didn't. The one that didn't was actually also not working on utorrent which tells me that it's a problem with the torrent itself.

**Comment by coolboiime** [comment]
@knightowl1000 Weird. I think my VPN provider never gave me IPv6 addresses, but I used to code a similar Synology Transmission script that involved turning off IPv6 from the Synology control panel.

**Comment by deltwalrus** [comment]
Magnetized links also not working here...

**Comment by mrjackyliang** [comment]
Seems like @deltwalrus solved this issue. Closing for now until further issues arise.

**Comment by conorlap** [comment]
I'm having this issue and can't seem to figure out a fix!
Downloads are getting stuck at "Magnetized Transfer - Retrieving metadata (0%)".  I'm using NordVPN and have set the variables:

NORDVPN_COUNTRY=UK
NORDVPN_CATEGORY=P2P
NORDVPN_PROTOCOL=udp
--cap-add=NET_ADMIN -d --device=/dev/net/tun --sysctl net.ipv6.conf.all.disable_ipv6=1 --dns 8.8.8.8 --dns 1.1.1.1

but unfortunately the issue still exists. Any ideas?

**Comment by jgramling17** [comment]
Same thing as @conorlap 

-e CREATE_TUN_DEVICE=true   \
-e OPENVPN_PROVIDER=NORDVPN  \
-e NORDVPN_COUNTRY=US  \
-e NORDVPN_CATEGORY=legacy_p2p \
-e NORDVPN_PROTOCOL=tcp \

Logs:
`[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 06 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [07DB0036] Scrape error: Connection failed (announcer.c:1279)
[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 06 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [07DB0036] Retrying scrape in 20 seconds. (announcer.c:1288)
[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 08 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [D1A327D2] Scrape error: Connection failed (announcer.c:1279)
[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 08 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [D1A327D2] Retrying scrape in 20 seconds. (announcer.c:1288)
[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 09 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [3D2D528E] Scrape error: Connection failed (announcer.c:1279)
[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 09 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [3D2D528E] Retrying scrape in 20 seconds. (announcer.c:1288)
[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 23 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [16AED019] Scrape error: Connection failed (announcer.c:1279)
[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 23 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [16AED019] Retrying scrape in 20 seconds. (announcer.c:1288)
[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 17 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [FEBD638C] Scrape error: Connection failed (announcer.c:1279)
[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 17 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [FEBD638C] Retrying scrape in 20 seconds. (announcer.c:1288)
[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 20 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [AEE72FA5] Scrape error: Connection failed (announcer.c:1279)
[2020-04-28 00:10:32.673] [Golumpa] Darling in the FranXX - 20 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [AEE72FA5] Retrying scrape in 20 seconds. (announcer.c:1288)
[2020-04-28 00:11:09.672] [Golumpa] Darling in the FranXX - 15v2 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [5AA94C32] IPv4 DHT announce done (tr-dht.c:545)
[2020-04-28 00:12:02.672] [Golumpa] Darling in the FranXX - 03 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [42B94F92] IPv4 DHT announce done (tr-dht.c:545)
[2020-04-28 00:12:02.672] [Golumpa] Darling in the FranXX - 01 [English Dub] [FuniDub 1080p x264 AAC] [MKV] [B224772F] IPv4 DHT announce done (tr-dht.c:545)`
