### ISSUE TITLE
Possible non transmission image?

### ISSUE THREAD

**Issue by shaboigan** [haugene/docker-transmission-openvpn#535]
Is there any chance you can do a openvpn only docker image? I'm currently using this image to route all my traffic via VPN but have no need for transmission. I've tried to use dpersons openvpn image but it's nowhere near as simple to get running as yours

**Comment by sheldonkwoodward** [comment]
If you are using PIA this might work https://github.com/qdm12/private-internet-access-docker

**Comment by coolboiime** [comment]
Seems like the issue has solved, closing for now.
