### ISSUE TITLE
docker in raspberry pi create by Dockerfile.armhf show /etc/openvpn/start.sh: Permission denied in log

### ISSUE THREAD

**Issue by tleung927** [haugene/docker-transmission-openvpn#536]
This is my second time post here , last time i return my raspberry for the bad quality, now i got a new one so decide to try this docker one more time. 
I am using open media vault as basic system. I am not sure this will cause problem or not. But i use OMV and this docker on my old AMD PC for months without any problem. 

Here is my step from create docker => run .
First  I download the zip file and unzipped it push to my root/trans-vpn folder by winscp 
Second Create the image by   == > docker build --tag="tony-trs-vpn" --file="Dockerfile.armhf".
After a long wait i got the message said  "Successfully built 5dca779656ec"
                                                               "Successfully tagged tony-trs-vpn:latest"
Third Using the same script I used in x86 system. 
              sudo docker run --cap-add=NET_ADMIN --device=/dev/net/tun --restart=always -d \
              -v :/srv/dev-disk-by-label-untitled/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              --env-file /root/DockerEnv \
	      -e LOCAL_NETWORK=192.168.1.0/24 \
              -p 9091:9091 \
              tony-trs-vpn

Now I saw the container is keep restart by itself and repeat this error message 
"[dumb-init] /etc/openvpn/start.sh: Permission denied"

Any idea??? Is the problem with OMV or something i missing?
![1](https://user-images.githubusercontent.com/2639138/41677784-2fe7390a-747e-11e8-9511-a05c1b86ff0b.JPG)
![2](https://user-images.githubusercontent.com/2639138/41677787-339cc092-747e-11e8-951b-c5eb6bf7cb77.JPG)
![3](https://user-images.githubusercontent.com/2639138/41677790-3533e14c-747e-11e8-8175-d385b3886b32.JPG)

**Comment by tleung927** [comment]
Finally it works! All i need to do is make chmod +x on different kind of .sh file ;  download and add tinyproxy. It works now!!! Finally got a super light weight torrent box!

**Comment by coolboiime** [comment]
Looks like you got the issue solved! Closing for now.
