### ISSUE TITLE
Running multiple transmission containers with different VPNs on same host

### ISSUE THREAD

**Issue by Troubadoure** [haugene/docker-transmission-openvpn#538]
Is it possible to run multiple containers using different VPN connections on the same host?

I've tried to do it but had no joy. I think they're using the same tun device and as such the VPN conflicts with each other. Would this be something that is possible or not at all?

**Comment by haugene** [comment]
Merged a feature to the dev branch that creates the TUN device automatically inside the container so it doesn't need to be mounted from the host. Then at least it should be no problem. It seems to be working really well so it will become the new default behaviour and released to master soon.

Closing this.
