### ISSUE TITLE
SSH out of the container

### ISSUE THREAD

**Issue by tomhumphrey** [haugene/docker-transmission-openvpn#539]
On the finish of a download I'd like to be able to run a script on a remote machine. Is it possible to ssh out of the container? At the moment I'm just getting a connection refused error

**Comment by coolboiime** [comment]
Not sure what you meant by run a script on a remote machine. Can you elliborate?

**Comment by haugene** [comment]
ssh out of the container should not be an issue.
Just verified from my container instance:
`ssh username@myhost './test.sh'` ran my test.sh script on a remote server, in my user home folder.

For authentication you can either use sshpass or ssh-copy-id so you don't get prompted.

Closing this. Re-open if that doesn't work.

**Comment by tomhumphrey** [comment]
Had a look at this again and still couldn't get it to work. Finally realised it was due to missing the LOCAL_NETWORK Environment variable. Added LOCAL_NETWORK 192.168.0.0/24 to my config, restarted and it worked fine

**Comment by haugene** [comment]
Aha. Didn't think about that. When you said remote machine I thought it was on a remote network, and that the traffic could pass through the VPN. But yes. If you want to SSH to a "remote machine" on you local network you need to add that config so that an opening is created in iptables.

**Comment by tomhumphrey** [comment]
I’m trying to use this as a script for on completion of download. I’ve generated ssh key for the root user but due to it running as ‘abc’ it struggles to use it. Have also, tried generating the key for ‘abc’ but again it won’t connect in the script. 

Have also tried to use sshpass but get command not found. 

Any ideas?

**Comment by haugene** [comment]
Shouldn't matter which user you generate key "for". They're just rsa keys right?
The user on the remote machine needs the authorized_keys entry and then you can point `ssh -i /some/key.file user@host.com`

**Comment by haugene** [comment]
What errors?

**Comment by tomhumphrey** [comment]
Got it working finally - it was complaining that the ssh key had the wrong permissions on it. And then further complaining that the folder on the destination had the wrong permissions. Whilst I haven't figured this part out yet it is an unrelated issue to this container.

**Comment by haugene** [comment]
yeah, so the ssh key should probably be 600. on the destination folder I don't know. The user you're logging in as has to have at least write I guess but I'll leave it up to you then.
