### ISSUE TITLE
nordvpn files needs an update

### ISSUE THREAD

**Issue by himred** [haugene/docker-transmission-openvpn#542]
Hello,

NordVPN  added a lot of servers and the thus new servers config files are missing.
I have downloaded today all the files and patched them for the container.
You can download them here: https://gasmi.net/down/nordvpn.tgz

Regards

**Comment by himred** [comment]
By the way here is the script I used to patch them:

```
#!/bin/bash

wget https://nordvpn.com/api/files/zip
unzip zip
rm zip

sed -i "s/auth-user-pass/auth-user-pass \/config\/openvpn-credentials.txt/" *.ovpn

for i in *.ovpn
do
        n=$(echo $i | sed -e "s/udp1194/udp/g" -e "s/tcp443/tcp/g")
        mv "$i" "$n"
        echo "Renaming $i to $n"
done
```

**Comment by coolboiime** [comment]
Closing this for merging into issue #554! Please have all issues and updates directed towards that issue. Closing this for now, thanks!
