### ISSUE TITLE
Create template-repository for Unraid support?

### ISSUE THREAD

**Issue by Tuumke** [haugene/docker-transmission-openvpn#551]
Just like https://github.com/linuxserver/docker-templates/tree/master/linuxserver.io
I really like your docker, could you add something like above?

**Comment by haugene** [comment]
Hey @Tuumke. Sorry for the late reply. As there were no other takers I think I'll close this now.
I'd happily accept a PR for this if someone wants to add it, but I don't have the time to add and maintain this myself (as I know little about it).

Closing for now, but for anyone reading this at a later time. A PR is still welcome 😄
