### ISSUE TITLE
Need an update of the list of opvn file for PIA

### ISSUE THREAD

**Issue by mirirald** [haugene/docker-transmission-openvpn#553]
Hello,

There is new servers so new files for PIA available
[Link to the website](https://www.privateinternetaccess.com/helpdesk/kb/articles/what-s-the-difference-between-the-ovpn-files) 

Thank you 

Miri

**Comment by coolboiime** [comment]
Closing this for merging into issue #554! Please have all issues and updates directed towards that issue. Closing this for now, thanks!
