### ISSUE TITLE
Adding New and Updating ALL VPN Provider Files

### ISSUE THREAD

**Issue by mrjackyliang** [haugene/docker-transmission-openvpn#554]
I have seen so many issues related to supporting and updating various VPN provider files. Looking to keep a top list here, so everyone can see the providers that are pending updates and additions.

__If you have any updates or additional suggestions please @mrjackyliang or @haugene, so we can add it into this list.__

### Updates Pending
* FrootVPN (#234)
* Windscribe VPN (#569)
* Newshosting (#629)

### Additions Pending
* Invisible Browsing VPN (#502)
* ProtonVPN (#378)
* IronSocket (#287)
* VPN Unlimited (#259)
* CyberGhost (#597)
* Forcefield (#641)
* TweakNews VPN (#839)
* GooseVPN (#738)
* SurfShark VPN (#734)
* Air VPN (#817)
* LeVPN (#813)

**Comment by lamboid** [comment]
any news on VPN Unlimited being added?

**Comment by coolboiime** [comment]
@lamboid We're missing ovpn files! If you have those images, would you mind contributing? Thanks!

**Comment by iamaburrama** [comment]
[en_configs.zip](https://github.com/haugene/docker-transmission-openvpn/files/2268220/en_configs.zip)

Easynews is my provider.  Attached ovpn files.  TY!

**Comment by lamboid** [comment]
I thought the VPNunlimited ovpns are tied to our personal accounts. Am I wrong?

**Comment by lamboid** [comment]
[VPNunlimited.zip](https://github.com/haugene/docker-transmission-openvpn/files/2342452/VPNunlimited.zip)

Took a look inside them - only certs and some config!
Attached are all the torrenting server ovpn files

**Comment by haugene** [comment]
Hey @pejotll. Yes, if you can provide a zip file with ovpn files I can have a look at adding it.
Also seeing that @lamboid uploaded some config files, I'll check those as well.

Want to run through this issue and update/add what I can during the holdidays so we can close it :)

**Comment by pejotll** [comment]
Hey @haugene, let me know if that's everything you need. 
[ProtonVPN_server_configs.zip](https://github.com/haugene/docker-transmission-openvpn/files/2690103/ProtonVPN_server_configs.zip)
[ProtonVPN_country_configs.zip](https://github.com/haugene/docker-transmission-openvpn/files/2690104/ProtonVPN_country_configs.zip)

**Comment by markedphillips** [comment]
Hi, I also have VPN Unlimited and some lifetime team account which I can assign an account for you guys if that would be helpful.

**Comment by jfessard** [comment]
I submitted  #676 which updates all of Mullvad's configs. It's quite big, but not surprising since they're all more than a year old at this point.

**Comment by nravanelli** [comment]
Updated IVACY with #677

**Comment by cat24max** [comment]
https://github.com/haugene/docker-transmission-openvpn/pull/704

**Comment by vovanec** [comment]
Any news on IBVPN? I have IBVPN subscription, let me know if I can help you with anything.

**Comment by haugene** [comment]
@vovanec No news, we should maybe rewrite the post a little bit - as it might seem like this is things that are planned and will come. We mostly add new providers on requests like yours.

I've spent too much time digging around for .ovpn files previously so I've kind of made it a rule that someone from the provider needs to get the files, sort out servers that don't support p2p, and give a link to a .zip file or similar with all the wanted configs and necessary certs. If you could provide that for IBVPN then I will try to add it :)

**Comment by darklite80** [comment]
Can we add support for surfshark vpn

**Comment by Nightbr** [comment]
Any news on VPNUnlimited? Anyone succeed to configure it?

**Comment by theailer** [comment]
@mrjackyliang @haugene 
Hi, seems provider mullvad have updated their certs. It is no longer possible to connect using the mullvad option as provider.

**Comment by haugene** [comment]
@theailer The Mullvad certificate was updated in a pull-request 7 days ago. #751 
Is it updated again? Have you pulled the latest image?

@Nightbr This issue is hard to track. I think we'll move back to one issue per provider. I see that @lamboid posted a link here a while back for the .ovpn config files for VPNUnlimited. Can you verify that these are still the correct configs? Or get a link to updated config? And please open a new issue for it, so we can remove it from here and get this closed.

**Comment by Nightbr** [comment]
@haugene done https://github.com/haugene/docker-transmission-openvpn/issues/766

**Comment by theailer** [comment]
@haugene Sorry, I thought I had pulled the latest image but apparently not. Everything in working order now. Thanks

**Comment by jamesinsf** [comment]
What about VPN Unlimited? Are there .opvn configuration files?
