### ISSUE TITLE
Transmission "forgets" where my files are on restart

### ISSUE THREAD

**Issue by rushupedge** [haugene/docker-transmission-openvpn#560]
If I stop the image and restart it, transmission errors "No data found! Ensure your drives are connected..." etc for my existing torrents. I should note that my data is on a separate drive mounted using -v, which is in fact a network cifs share mounted to the host filesystem via fstab. How do I prevent this behavior?

**Comment by rushupedge** [comment]
Okay, so I found that I need to run mount -av on start every time...but even then, Transmission thinks the files are only half done. I have to verify them all.

**Comment by coolboiime** [comment]
Looks like you solved it! Would you mind sharing what you did to resolve the issue?
