### ISSUE TITLE
`transmission-remote` missing

### ISSUE THREAD

**Issue by nexusmaniac** [haugene/docker-transmission-openvpn#567]
```
transmission auth required
/etc/transmission/updatePort.sh: line 78: transmission-remote: not found
/etc/transmission/updatePort.sh: line 97: transmission-remote: not found
Checking port...
/etc/transmission/updatePort.sh: line 97: transmission-remote: not found
```

Looks like something's missing in the port selection 😄 It's not a package I could find using `apk` though - so not sure 😋 Any logs I can shoot over to help out?

**Comment by haugene** [comment]
Hmm, probably some changes in the new transmission versions then. Need to find the new cli operations for this. Thank's for letting us know. I don't have time to look at this for the next couple of weeks, but if someone else could help out that would be great. In the mean time you could try to use one of the older versions by using the tags https://hub.docker.com/r/haugene/transmission-openvpn/tags/ but then there might be a problem if there are updated configs.

**Comment by haugene** [comment]
Came across this again, and tested it now locally with the latest ubuntu build.
Port forwarding script works fine and transmission-remote seems to be in place:
```
root@239079f31a69:/# transmission-remote -V
transmission-remote 2.94 (d8e60ee44f)
```

Closing this for now. Re-open if you still encounter this. Was it the ubuntu or alpine image btw?

**Comment by benssson** [comment]
I'm getting this issue in 'latest-alpine'

```
/ # transmission-remote -V
/bin/sh: transmission-remote: not found
```

**Comment by haugene** [comment]
Yeah... About the alpine image. I've never really sat down and done any maintenance on it, it's been community driven. I'm using alpine myself on a lot of images, the low footprint is nice, but I simply don't have time to maintain the core openvpn image (ubuntu, alpine, armhf), rss-plugin(ubuntu,armhf) and nginx-proxy(ubuntu,armhf). So I've basically set my mission to support the ubuntu versions as best I can for all the distros people are running it on (Synology, Qnap, Windows, Mac, Linux).

The compatibility-matrix could possibly be very big ;) So I'll leave this issue as closed. Maybe if I feel the spirit coming over me one day I'll do a brush-up on the alpine version (it doesn't have tinyproxy feature either), but I'm not sure when that day will come. So I encourage people to find out why this is not included in the alpine install, and in other cases just take the 100MB overhead of running the ubuntu version.

I could make this more clear in the README.

**Comment by benssson** [comment]
No problems. It would be nice to be have the alpine image with port forwarding but using the ubuntu image is no big deal. I might take a peek if I get some time.

Thanks!

**Comment by nexusmaniac** [comment]
> Came across this again, and tested it now locally with the latest ubuntu build.
> Port forwarding script works fine and transmission-remote seems to be in place:
> 
> ```
> root@239079f31a69:/# transmission-remote -V
> transmission-remote 2.94 (d8e60ee44f)
> ```
> Closing this for now. Re-open if you still encounter this. Was it the ubuntu or alpine image btw?

It was on the Alpine image 👍 

Looks like you've already gone into detail on Alpine support 😂 I don't think this issue breaks the container in any way, just some issue around port forwarding (no idea how big of a deal that is for the VPN connection)

**Comment by HotBlack77** [comment]
I just bumped into the lack of "transmission-remote" when running post torrent completion scripts on the Alpine image. Why cant we just add the installation to the 'Dockerfile.alpine' file for the alpine image? i.e. in Line 9 here: https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile.alpine just include transmission-remote as an item to install? it only makes the image a few 100k larger.
