### ISSUE TITLE
start.sh not found

### ISSUE THREAD

**Issue by nexusmaniac** [haugene/docker-transmission-openvpn#568]
I've had this container running on unRAID for months and months... But today, no matter which version I use (dev, alpine, 2.00, 1.22, etc.) I am unable to connect to Transmission! No web UI access. 

`ps aux` reveals openvpn being the only running process... no `transmission-daemon`

```
STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
/etc/openvpn/tunnelUp.sh: line 4: /opt/tinyproxy/start.sh: not found
Sat Jul 28 17:49:08 2018 WARNING: Failed running command (--up/--down): could not execute external program

Sat Jul 28 17:49:08 2018 Exiting due to fatal error
```

I've deleted my docker image, tried a fresh config / data path, multiple re-pulls of differing versions - all to no avail. I can no longer get this container working correctly 🤔 

Can't even run `docker exec` to get into the container, it's restarting every 5 or 10 seconds!

**Comment by coolboiime** [comment]
Hi! Seems like you've solved the issue. Would you be willing to share your resolution? Thanks!

**Comment by nexusmaniac** [comment]
Hey, 

I have no idea - it just kinda fixed itself 🙈 
So I assumed it was a one off and closed this 😋 

Sorry! 😄
