### ISSUE TITLE
update frootvpn

### ISSUE THREAD

**Issue by snakefox666** [haugene/docker-transmission-openvpn#57]
Hello Haugene,

it seem that frootvpn just updated their openvpn config, is it possible to modify the container ?
The mail received from froot :

_Beloved Customer,

we're currently updating our swedish OpenVPN servers which might affect you sooner or later.
You're required to download a new copy of the OpenVPN Configuration file found at:
 https://www.frootvpn.com/files/se.openvpn.frootvpn.ovpn
The current configuration files will result in errors such as:
 Authenticate/Decrypt packet error: packet HMAC authentication failed And most importantly will leave you unencrypted!

The entire Update will last 2 weeks, giving you enough time to update before the last legacy servers are being shut down.

Nevertheless we urge you to update your config as soon as possible!

Best Regards,_

many thanks in advance

**Comment by haugene** [comment]
Hey, you caught me sitting here geeking a bit anyways so I updated it now. Have pushed the changes to the dev branch. After the dev build has succeeded, you should be good to go: https://hub.docker.com/r/haugene/transmission-openvpn/builds/

Could you try to pull and run the dev-image (haugene/transmission-openvpn:dev) to verify that it works with the new config? Let me know and I'll merge the changes into the main image.

**Comment by snakefox666** [comment]
Wowww that's fast :-)
For sure I will try and let you know asap.
Thanks !!
Le ven. 1 avr. 2016 à 19:19, Kristian Haugene <notifications@github.com> a
écrit :

**Comment by snakefox666** [comment]
Hello,
I tried the dev container but I have the following :

403: Forbidden

Unauthorized IP Address.

Either disable the IP address whitelist or add your address to it.

If you're editing settings.json, see the 'rpc-whitelist' and
'rpc-whitelist-enabled' entries.

If you're still using ACLs, use a whitelist instead. See the
transmission-daemon manpage for details


I think it's not a big deal but do you have an idea ?

Le ven. 1 avr. 2016 à 19:50, [So!ide-Sn@ke] <solidesnake007@gmail.com> a
écrit :

**Comment by haugene** [comment]
Hmm, so this error is from Transmission. The fact that Transmission has started should indicate that the new .ovpn config is working as it should. Have you turned on whitelisting as the error says?

By default whitelisting is disabled by the container: https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile#L79

You can see your settings.json file in "transmission-home" folder under your storage mount directory. Be aware that changes you make to it will not be read by transmission while it's running.

If the issue doesn't resolve, please attach container startup-logs and settings.json here...

**Comment by haugene** [comment]
Merged this to master now. If anyone encounters any problems they can open a new issue and use the 1.7 tag while we fix it.

**Comment by snakefox666** [comment]
Sorry,

But I don't have Time to test the dev branch :(

Promise I Will test stable when I'll have Time.

Anyway thx for your quick fix,

Rgs,
Le mar. 5 avr. 2016 à 18:48, Kristian Haugene <notifications@github.com> a
écrit :

**Comment by haugene** [comment]
No problem. Just let me know when you have tested :) Would be good to know that it still works!

**Comment by snakefox666** [comment]
Hello,

for the moment it still works fine but I don't know how to check if I'm
using the new frootvpn setup :-)
I will check that when I will have time...
Just another stupid question, each time I need to add in the resolv.conf of
the container the DNS of google because otherwise there is not DNS
resolution, but after each reboot I loose it, is there any way to fix it ?
Thanks a lot for your help.
Rgds.

Le mar. 5 avr. 2016 à 19:08, Kristian Haugene <notifications@github.com> a
écrit :

**Comment by haugene** [comment]
Well to make sure you're running with the new configuration you'll need to stop and remove your container. Run `docker pull haugene/transmission-openvpn` and then start the container again using `docker run ...`.

As for the DNS, see the Known Issues of the README. But for a regular server setup, just add "--dns 8.8.8.8 --dns 8.8.4.4" to your `docker run ...`. If you're on a NAS of some sort you should read the comments on the "Synology NAS" issue. You can create a resolv.conf outside your container and mount it as a volume, once again, in the `docker run ...` command. See the README and the Synology issue, you'll probably figure it out from there.

**Comment by haugene** [comment]
Relating to Froot, I've now added configs for france, canada and the US. It's available on the dev branch along with some other config changes. If you're using the dev tag you should be able to set ```OPENVPN_CONFIG=us.openvpn.frootvpn``` and so on to use other configs. If it's not set it will still default to sweden.

If you have the time and want to check that everything works before I merge it to master, that would be great :)

**Comment by snakefox666** [comment]
I will try to download the dev branch and test but last time the dev was
not working on my side, don't ask me why :)
Latest is working perfectly fine, anyway I will try to test again the dev
branch...

Le mer. 27 avr. 2016 à 23:33, Kristian Haugene <notifications@github.com> a
écrit :

**Comment by snakefox666** [comment]
Hehe I confirm that is working fine with the dev branch, by default country
code "SE" and with the OPENVPN_CONFIG=us.openvpn.frootvpn country code = US
:D

Le jeu. 28 avr. 2016 à 10:41, [So!ide-Sn@ke] <solidesnake007@gmail.com> a
écrit :

**Comment by haugene** [comment]
Great :+1: Thanks!
