### ISSUE TITLE
Combustion web ui does not render the setting for transmission

### ISSUE THREAD

**Issue by alternativ** [haugene/docker-transmission-openvpn#570]
If I attach to the running docker container I see the following settings:

> root@53948f473c1e:/etc/transmission# printenv | grep RATIO
TRANSMISSION_RATIO_LIMIT=2 
TRANSMISSION_RATIO_LIMIT_ENABLED=true

However they are not reflected in the web ui when I use combustion, if I use the normal web ui they are reflected. Below a screenshot of the combustion interface:

<img width="1414" alt="screen shot 2018-08-02 at 12 18 21" src="https://user-images.githubusercontent.com/20473098/43578158-3a545dae-964e-11e8-8628-5cdd2fad5340.png">

Found the following on combustion and it looks to be not respecting a `Authorization header` https://github.com/Secretmapper/combustion/issues/16

Can we have a look?

**Comment by coolboiime** [comment]
This might possibly be a bug with the combustion interface. What have you tried so far?

**Comment by haugene** [comment]
I think this operation timed out
