### ISSUE TITLE
How to run this on a RPi

### ISSUE THREAD

**Issue by theincredibleman** [haugene/docker-transmission-openvpn#571]
Sorry, Docker noob here. Trying to get my head around this instruction for the RPi: 

> Since the Raspberry PI runs on an ARM architecture instead of x64, the existing x64 images will not work properly. To support users that wish to run this container on a Raspberry Pi, there are 2 additional Dockerfiles created. The Dockerfiles supported by the Raspberry PI are Dockerfile.armhf -- there is also an example docker-compose-armhf file that shows how you might use Transmission/OpenVPN and the corresponding nginx reverse proxy on an RPI machine.

But I can't figure out how to do this. Anyone that can help me with a step-by-step instruction?
I am running the OMV 4 OS with the Docker GUI installed.

By the way, amazing work guys!

**Comment by theincredibleman** [comment]
Figured this out by myself (and with some help from the Docker subreddit community), and thought I'd list the steps to get this working to help other RPi users.

1. SSH to your RPi and run the following command (in the root of the RPi) to pull the GIT repo:
`git checkout git@github.com:haugene/docker-transmission-openvpn.git`

2. Browse to the downloaded folder:
`cd docker-transmision-openvpn`

3. Build the Docker image with using the ARMF file for the PI:
`docker build -t transmission-openvpn -f Dockerfile.armhf .`

4. After that, the Docker image was set up. I used the Docker GUI on OMV to configure the environment variables and networking, create the Docker container and start it.

**Comment by haugene** [comment]
Update: #582 adds support for automatic builds on Docker Hub. New tag dev-armhf is [built and available](https://hub.docker.com/r/haugene/transmission-openvpn/tags/).

**Comment by eskimos2000** [comment]
Another noob here, sorry ;-). Is it going to work on arm64 as well?. I want to run it on odroid c2.  

Cheers

**Comment by CovertDad** [comment]
So, as a newbish pi/docker user, how would I pull the dev-armhf image for docker?

**Comment by haugene** [comment]
@CovertDad I guess you figured it out, but for future reference: `docker pull haugene/transmission-openvpn:dev-armhf`

**Comment by nemchik** [comment]
@haugene do you recommend
```
haugene/transmission-openvpn:latest-armhf
```
Or
```
haugene/transmission-openvpn:dev-armhf
```
For general use (people looking for the most stable option)

**Comment by haugene** [comment]
Right now they're the same. But in general, latest will be more stable than dev.

**Comment by nemchik** [comment]
Thanks! I'll add the ARM image to my project.
