### ISSUE TITLE
many AEAD Decrypt error bad packet ID errors

### ISSUE THREAD

**Issue by ilovett** [haugene/docker-transmission-openvpn#574]
All of a sudden I've started to get many off the following errors for about 10 minutes and then the service crashes and stops responding:

```
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22239 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22240 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22241 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22242 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22245 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22248 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22249 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22251 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22255 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22258 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22259 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22264 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22266 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22270 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22286 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22335 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22346 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22349 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22362 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22373 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22374 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22375 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22386 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22387 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22433 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Aug  8 22:17:35 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #22437 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
```

Nothing changed on my end at all except rebooting my pi.  It was working great before and now I can't get this error to go away.

**Comment by niXta1** [comment]
Try with another VPN server.

**Comment by dcrdev** [comment]
I've also started getting these - also with nordvpn

**Comment by mbach04** [comment]
Having same issue with Nordvpn as well. Also, the crash appears to be memory related. The container memory usage just steadily grows until there's nothing more available at which time it crashes.

**Comment by haugene** [comment]
Linking to #257 for future reference. Anyone had luck with changing MTU size?
This warning should probably have a section in the README as it is a recurring issue. Then it would be nice to have a recommended MTU size, and the mute-replay-warnings option as proposed solutions?

On a sidenote, the README is getting very large. #362 is up for grabs ;)

**Comment by niXta1** [comment]
NordVPN running fine here...
I do get ahead messages though.

**Comment by dcrdev** [comment]
Yeah it's working for me too , I'm just getting these messages spamming the journal.

**Comment by niXta1** [comment]
--mssfix 1475 seems to have fixed the spam in the log for me...

**Comment by PlqnK** [comment]
> Anyone had luck with changing MTU size?

As I said in #257 yes I've fixed the problem by playing with the mssfix value.

> Then it would be nice to have a recommended MTU size, and the mute-replay-warnings option as proposed solutions?

I agree, I'm pretty sure any value below 1500 will fix the problem but I will need to do some testing first to be sure and I don't really have the time for now :-/

**Comment by ilovett** [comment]
I tried a few `--mssfix` values with no luck -- but not sure I tried 1475.

For now I've just switched to TCP

**Comment by ilovett** [comment]
Does mounting `/etc/localtime` work as expected for armhf?

**Comment by rrd911** [comment]
I did some tests on my instance and the MTU 1390 seems to work for PureVPN

Tests performed from within the transmission-openvpn docker instance to get to 1390 MTU

ping -M do -s "mtu# less than 1500" -c 1 yahoo.com

# ping yahoo.com
PING yahoo.com (98.138.219.232) 56(84) bytes of data.
64 bytes from media-router-fp2.prod1.media.vip.ne1.yahoo.com (98.138.219.232): icmp_seq=1 ttl=51 time=277 ms
64 bytes from media-router-fp2.prod1.media.vip.ne1.yahoo.com (98.138.219.232): icmp_seq=2 ttl=51 time=273 ms
^C
--- yahoo.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 273.655/275.817/277.980/2.225 ms

# ping -M do -s 1440 -c 1 yahoo.com
PING yahoo.com (98.137.246.8) 1440(1468) bytes of data.

--- yahoo.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

# ping -M do -s 1470 -c 1 yahoo.com
PING yahoo.com (98.138.219.231) 1470(1498) bytes of data.

--- yahoo.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

# ping -M do -s 1460 -c 1 yahoo.com
PING yahoo.com (72.30.35.10) 1460(1488) bytes of data.

--- yahoo.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

# ping -M do -s 1410 -c 1 yahoo.com
PING yahoo.com (72.30.35.10) 1410(1438) bytes of data.

--- yahoo.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

# ping -M do -s 1400 -c 1 yahoo.com
PING yahoo.com (98.138.219.231) 1400(1428) bytes of data.

--- yahoo.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq state UNKNOWN mode DEFAULT group default qlen 100
    link/none
964: eth0@if965: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 02:42:ac:12:00:0e brd ff:ff:ff:ff:ff:ff link-netnsid 0

# ping -M do -s 1360 -c 1 yahoo.com
PING yahoo.com (72.30.35.9) 1360(1388) bytes of data.
1368 bytes from media-router-fp1.prod1.media.vip.bf1.yahoo.com (72.30.35.9): icmp_seq=1 ttl=52 time=255 ms

--- yahoo.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 255.104/255.104/255.104/0.000 ms

# ping -M do -s 1370 -c 1 yahoo.com
PING yahoo.com (72.30.35.9) 1370(1398) bytes of data.
1378 bytes from media-router-fp1.prod1.media.vip.bf1.yahoo.com (72.30.35.9): icmp_seq=1 ttl=52 time=269 ms

--- yahoo.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 269.745/269.745/269.745/0.000 ms

# ping -M do -s 1380 -c 1 yahoo.com
PING yahoo.com (98.138.219.232) 1380(1408) bytes of data.
1388 bytes from media-router-fp2.prod1.media.vip.ne1.yahoo.com (98.138.219.232): icmp_seq=1 ttl=51 time=287 ms

--- yahoo.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 287.594/287.594/287.594/0.000 ms

# ping -M do -s 1390 -c 1 yahoo.com
PING yahoo.com (98.138.219.231) 1390(1418) bytes of data.
1398 bytes from media-router-fp1.prod1.media.vip.ne1.yahoo.com (98.138.219.231): icmp_seq=1 ttl=51 time=284 ms

--- yahoo.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 284.787/284.787/284.787/0.000 ms

# ping -M do -s 1396 -c 1 yahoo.com
PING yahoo.com (98.138.219.231) 1396(1424) bytes of data.

--- yahoo.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

# ping -M do -s 1392 -c 1 yahoo.com
PING yahoo.com (98.137.246.7) 1392(1420) bytes of data.
^[[A
--- yahoo.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

#ping -M do -s 1391 -c 1 yahoo.com
PING yahoo.com (72.30.35.10) 1391(1419) bytes of data.

--- yahoo.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

#ping -M do -s 1390 -c 1 yahoo.com
PING yahoo.com (98.137.246.7) 1390(1418) bytes of data.
1398 bytes from media-router-fp1.prod1.media.vip.gq1.yahoo.com (98.137.246.7): icmp_seq=1 ttl=50 time=319 ms

--- yahoo.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 319.547/319.547/319.547/0.000 ms

**Comment by ilovett** [comment]
After some time with this issue I've noticed that docker doesn't map all protocols when mapping ports... by default, it only maps TCP... I've not mapped both TCP & UDP, and also ensured my router forwards BOTH TCP & UDP on 9091...

```bash
docker run -d \
  ...
  -p 9091:9091/tcp \
  -p 9091:9091/udp \
```

This appears to have been the issue on my end!

**Comment by niXta1** [comment]
After some more testing: --mssfix 1452 is optimal for NordVPN.
