### ISSUE TITLE
Proxy not working on Raspbian

### ISSUE THREAD

**Issue by IvanGolovko3k** [haugene/docker-transmission-openvpn#575]
When running on Raspbian the proxy won't work because the `tinyproxy.conf` cannot be found.

```
STARTING TINYPROXY
Setting tinyproxy port to 8888
sed: can't read /etc/tinyproxy.conf: No such file or directory
sed: can't read /etc/tinyproxy.conf: No such file or directory
Starting Tinyproxy lightweight HTTP proxy daemon: tinyproxy.
Tinyproxy startup script complete.
```

I inspected the running container and noticed that the location is not in `/etc/tinyproxy.conf` but in `/etc/tinyproxy/tinyproxy.conf`.

I modified the `/tinyproxy/start.sh` and changed the location to `PROXY_CONF='/etc/tinyproxy/tinyproxy.conf'`. 

I rebuild the image, started the container and now it's working.

```
STARTING TINYPROXY
Setting tinyproxy port to 8888
Starting Tinyproxy lightweight HTTP proxy daemon: tinyproxy.
Tinyproxy startup script complete.
```

I'm running Raspbian GNU/Linux 9 (stretch).

Since I'm not too familiar with shell I'll leave the fixing to someone else.

**Comment by nicolas-albert** [comment]
Same here, I have copied the `/opt/tinyproxy` on my Pi, fixed and run it using a `-v <myfolder>:/opt/tinyproxy`.

**Comment by haugene** [comment]
This should now be fixed. #732 
Sorry it took a while, but people post a lot of issues and I'm mainly focusing on the regular ubuntu version of the image. Anyways. Closing this now.

PS: It's currently only available on the dev tag. will be pushed to latest soon. There's also been some build issues on Docker Hub for the armhf image, this is also fixed on dev. So `dev-armhf` is the one to use for now.
