### ISSUE TITLE
NordVPN config not working

### ISSUE THREAD

**Issue by namekal** [haugene/docker-transmission-openvpn#577]
Hi, I noticed there was a recent change #576  that replaced the missing default.ovpn file for this provider. I ran a `docker rmi` on the images and `docker pull` for an update, however the error is not changed for me,

I tried to bypass with by defining the volume `-v /etc/openvpn/nordvpn/default.ovpn` but a new error appears:
```
Using OpenVPN provider: NORDVPN
Supplied config us10.nordvpn.com.udp.ovpn could not be found.
Using default OpenVPN gateway for provider nordvpn
Setting OPENVPN credentials...
Thu Aug 16 02:59:24 2018 disabling NCP mode (--ncp-disable) because not in P2MP client or server mode
Options error: You must define TUN/TAP device (--dev)
Use --help for more information.
```

**Comment by haugene** [comment]
From what I can see this shouldn't be related to the default.ovpn file but that there is no TUN/TAP device. Are you specifying `--cap-add=NET_ADMIN --device=/dev/net/tun` in your docker run command?

The basic run command should look something like:
```
docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \
        -v /your/storage/path/:/data \
        -e OPENVPN_PROVIDER=NORDVPN \
        -e OPENVPN_USERNAME=username \
        -e OPENVPN_PASSWORD=password \
        -e LOCAL_NETWORK=192.168.0.0/16 \
        --log-driver json-file \
        --log-opt max-size=10m \
        -p 9091:9091 \
        haugene/transmission-openvpn
```

**Comment by namekal** [comment]
I've normally just run `--privileged` in place of those. To test your suggestion, I removed privileged and put those options in, and have my run command now as the following, with the result: 

```
docker run \
--name transmission-openvpn \
--cap-add=NET_ADMIN \
--device=/dev/net/tun \
-v /docker/containers/transmission-openvpn/data:/data \
-v /media:/media \
-v /etc/openvpn/nordvpn/default.ovpn \
-e "WEBPROXY_ENABLED=true" \
-e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true" \
-e "TRANSMISSION_RPC_PASSWORD=xxxxxxxxxxxxxxxxxxx" \
-e "TRANSMISSION_RPC_USERNAME=xxxxxxxxxxxxx" \
-e "OPENVPN_PROVIDER=NORDVPN" \
-e "TRANSMISSION_DOWNLOAD_DIR=/media/download/tv_dl" \
-e "TRANSMISSION_INCOMPLETE_DIR_ENABLED=true" \
-e "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true" \
-e "TRANSMISSION_SPEED_LIMIT_UP=250" \
-e "TRANSMISSION_INCOMPLETE_DIR=/media/download/incomplete" \
-e "TRANSMISSION_RATIO_LIMIT_ENABLED=true" \
-e "TRANSMISSION_RATIO_LIMIT=0.01" \
-e "TRANSMISSION_WEB_UI=transmission-web-control" \
-e "OPENVPN_CONFIG=us100.nordvpn.com.udp" \
-e "OPENVPN_USERNAME=xxxxxxxxxxxxxxxx" \
-e "OPENVPN_PASSWORD=xxxxxxxxxxxxxxx" \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
--dns 8.8.8.8 \
haugene/transmission-openvpn

Using OpenVPN provider: NORDVPN
Supplied config us100.nordvpn.com.udp.ovpn could not be found.
Using default OpenVPN gateway for provider nordvpn
Setting OPENVPN credentials...
Thu Aug 16 13:21:33 2018 disabling NCP mode (--ncp-disable) because not in P2MP client or server mode
Options error: You must define TUN/TAP device (--dev)
Use --help for more information.
```

**Comment by namekal** [comment]
oh that had nothing to do with that. there is no longer any configs less than `us323` I used to use `us10` then tried switching to `us100` when i noticed this issue popping up.
I'm now using `us502` in place of `us100` with no issues, using the command above.

**Comment by sameep22** [comment]
Hi,

I seem to be having a similar problem. NordVPN is unable to find the config file, and even defining the config file name in the parameters doesn't seem to work.

Here is the config I have : 

  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9003:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - ${USERDIR}/Downloads:/data/watch
      - ${USERDIR}/Downloads/completed:/data/completed
      - ${USERDIR}/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=****
      - OPENVPN_PASSWORD=****
      - OPENVPN_CONFIG=fr261.nordvpn.com.udp
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.1.*,*.*.*.*"
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true

**Comment by namekal** [comment]
Sameep22,
Try changing the config # anywhere from 7 to 196. I can't find anything higher than fr196 in the files.

**Comment by haugene** [comment]
Had updated NordVPN configs on the dev branch. Merged them now.
Will be available on the latest tag after it's built: https://hub.docker.com/r/haugene/transmission-openvpn/builds/
