### ISSUE TITLE
IntegrityVPN - Cant find any peers

### ISSUE THREAD

**Issue by Thunderoux** [haugene/docker-transmission-openvpn#578]
So I'm trying to set up a docker for transmission and everything seems to work until I try to download something. Transmission wont find any peers and it's bar will just stay red. Tried to reinstall but issue still remains. Tried with >10 different torrents without any success. Running with privileged mode and login for OpenVPN is correct.

> Using OpenVPN provider: INTEGRITYVPN
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
Thu Aug 16 22:59:59 2018 WARNING: file '/etc/openvpn/integrityvpn/tls.key' is group or others accessible
Thu Aug 16 22:59:59 2018 WARNING: file '/config/openvpn-credentials.txt' is group or others accessible
Thu Aug 16 22:59:59 2018 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 24 2018
Thu Aug 16 22:59:59 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Thu Aug 16 22:59:59 2018 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
Thu Aug 16 22:59:59 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Aug 16 22:59:59 2018 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Aug 16 22:59:59 2018 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Aug 16 22:59:59 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]85.24.253.50:1196
Thu Aug 16 22:59:59 2018 Socket Buffers: R=[212992->212992] S=[212992->212992]
Thu Aug 16 22:59:59 2018 UDP link local: (not bound)
Thu Aug 16 22:59:59 2018 UDP link remote: [AF_INET]85.24.253.50:1196
Thu Aug 16 22:59:59 2018 TLS: Initial packet from [AF_INET]85.24.253.50:1196, sid=e0b3cafb 09290193
Thu Aug 16 22:59:59 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Aug 16 23:00:01 2018 VERIFY OK: depth=1, C=SE, ST=S, L=Stockholm, O=5july.org, OU=integrityvpn, CN=integrity, name=integrity vpn, emailAddress=admin@integrity.st
Thu Aug 16 23:00:01 2018 VERIFY OK: nsCertType=SERVER
Thu Aug 16 23:00:01 2018 VERIFY OK: depth=0, C=SE, ST=S, L=Stockholm, O=5july.org, OU=integrity_vpn, CN=integrity, name=integrity, emailAddress=admin@integrity.st
Thu Aug 16 23:00:01 2018 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Thu Aug 16 23:00:01 2018 [integrity] Peer Connection Initiated with [AF_INET]85.24.253.50:1196
Thu Aug 16 23:00:02 2018 SENT CONTROL [integrity]: 'PUSH_REQUEST' (status=1)
Thu Aug 16 23:00:02 2018 PUSH: Received control message: 'PUSH_REPLY,route-gateway 10.251.6.1,topology subnet,route 85.24.253.50 255.255.255.255 net_gateway,redirect-gateway def1,dhcp-option DNS 213.80.98.2,dhcp-option DNS 213.80.101.3,dhcp-option DNS 79.136.77.113,ping 5,ping-restart 30,ifconfig 10.251.6.89 255.255.255.0'
Thu Aug 16 23:00:02 2018 OPTIONS IMPORT: timers and/or timeouts modified
Thu Aug 16 23:00:02 2018 OPTIONS IMPORT: --ifconfig/up options modified
Thu Aug 16 23:00:02 2018 OPTIONS IMPORT: route options modified
Thu Aug 16 23:00:02 2018 OPTIONS IMPORT: route-related options modified
Thu Aug 16 23:00:02 2018 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Thu Aug 16 23:00:02 2018 Outgoing Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Thu Aug 16 23:00:02 2018 Outgoing Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Aug 16 23:00:02 2018 Incoming Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Thu Aug 16 23:00:02 2018 Incoming Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Aug 16 23:00:02 2018 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
Thu Aug 16 23:00:02 2018 TUN/TAP device tun0 opened
Thu Aug 16 23:00:02 2018 TUN/TAP TX queue length set to 100
Thu Aug 16 23:00:02 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Thu Aug 16 23:00:02 2018 /sbin/ip link set dev tun0 up mtu 1500
Thu Aug 16 23:00:02 2018 /sbin/ip addr add dev tun0 10.251.6.89/24 broadcast 10.251.6.255
Thu Aug 16 23:00:02 2018 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.251.6.89 255.255.255.0 init
Up script executed with tun0 1500 1558 10.251.6.89 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.251.6.89
Generating transmission settings.json from env variables
sed'ing True to true
-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------
STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Thu Aug 16 23:00:02 2018 /sbin/ip route add 85.24.253.50/32 via 172.17.0.1
Thu Aug 16 23:00:02 2018 /sbin/ip route add 0.0.0.0/1 via 10.251.6.1
Thu Aug 16 23:00:02 2018 /sbin/ip route add 128.0.0.0/1 via 10.251.6.1
Thu Aug 16 23:00:02 2018 /sbin/ip route add 85.24.253.50/32 via 172.17.0.1
RTNETLINK answers: File exists
Thu Aug 16 23:00:02 2018 ERROR: Linux route add command failed: external program exited with error status: 2
Thu Aug 16 23:00:02 2018 Initialization Sequence Completed

**Comment by Seba0702** [comment]
I got the same issue with NordVPN. It can't find any peers. :(

**Comment by haugene** [comment]
I'm closing this issue. @Thunderoux, sorry you didn't get any reply - but last years summer was way too good here in Norway and I fell behind on all things geeky.

If you still have this issue and want to try again and fix it, please create a new issue for it.
Cleaning up old issues and have created some new templates for issues that will make debugging simpler. Basically telling everyone to supply necessary information when submitting the issue. A check-list :)

Same for you @Seba0702. If it's still an issue, create a new one please.
