### ISSUE TITLE
Traceroute

### ISSUE THREAD

**Issue by scottcom4** [haugene/docker-transmission-openvpn#583]
I am struggling with the connection to my VPN provider's (IPVanish) servers and the connection is very slow.  They have asked that I run a traceroute on the servers I have been attempting to you, but it doesn't appear that traceroute is installed as part of this image.  

Is there an alternative way to run a traceroute?

**Comment by haugene** [comment]
You can just install it in the container. Exec in and run `apt update && apt install inetutils-traceroute`, then traceroute as normal. If you're using the PUID/PGID options you will need to exec in as root instead of default user: `docker exec -it -u root <container> bash`

**Comment by scottcom4** [comment]
Thanks @haugene. 

That results in the following error message (which is similar to what I was getting using apt-get):

Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://build.openvpn.net/debian/openvpn/stable xenial InRelease
  Temporary failure resolving 'build.openvpn.net'
Err:5 http://security.ubuntu.com/ubuntu xenial-security InRelease       
  Temporary failure resolving 'security.ubuntu.com'
Err:6 http://ppa.launchpad.net/transmissionbt/ppa/ubuntu xenial InRelease
  Temporary failure resolving 'ppa.launchpad.net'
Reading package lists... Done       
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Failed to fetch http://build.openvpn.net/debian/openvpn/stable/dists/xenial/InRelease  Temporary failure resolving 'build.openvpn.net'
W: Failed to fetch http://ppa.launchpad.net/transmissionbt/ppa/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'ppa.launchpad.net'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package inetutils-traceroute

**Comment by haugene** [comment]
Dns issues. Are you running the container with the --dns flags as described in the README?

**Comment by scottcom4** [comment]
I definitely did the first time I ran the container but may have missed it the second time.

Do I have to run it again from scratch, or is there a way to modify the existing container?

**Comment by scottcom4** [comment]
I can confirm that I failed to use the dns flag on the second occasion.

**Comment by scottcom4** [comment]
Ran using the below syntax and the error resulting from running apt update && apt install inetutils-traceroute continues.

```
docker run \
--cap-add=NET_ADMIN \
--device=/dev/net/tun \
-d \
-v /volume1/docker/haugene-transmission/resolv.conf:/etc/resolv.conf \
-v /volume1/docker/haugene-transmission/data:/data \
-e "OPENVPN_PROVIDER=IPVANISH" \
-e "OPENVPN_CONFIG=ipvanish-HK-Hong-Kong-hkg-c16" \
-e "OPENVPN_USERNAME=XXXX" \
-e "OPENVPN_PASSWORD=XXXX" \
-e "LOCAL_NETWORK=192.168.0.0/24" \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
-e "PGID=65545" \
-e "PUID=1047" \
-p 9091:9091 \
--dns 8.8.8.8 --dns 8.8.4.4  \
--sysctl net.ipv6.conf.all.disable_ipv6=0 \
--name "haugene-transmission-openvpn1" \
haugene/transmission-openvpn:latest
```

**Comment by haugene** [comment]
You're overwriting the resolv.conf anyways, so it's probably more important what you have in your mounted file. It doesn't work if you only have --dns lines and skip the resolv.conf mounting?

**Comment by scottcom4** [comment]
That fixed it thank you.
