### ISSUE TITLE
Using own custom VPN

### ISSUE THREAD

**Issue by jbg77** [haugene/docker-transmission-openvpn#584]
Hello,

I have my own vpn using https://github.com/Angristan/OpenVPN-install script, I have juste a .ovpn file.

I try to deploy but I haven't credentials
`docker run -v /home/client.ovpn:/etc/openvpn/custom/default.ovpn -e "OPENVPN_PROVIDER=CUSTOM"`

`Credentials not set. Exiting`

**Comment by haugene** [comment]
https://github.com/haugene/docker-transmission-openvpn#using-a-custom-provider

> If you are using AirVPN or other provider with credentials in the config file, you still need to set OPENVPN_USERNAME and OPENVPN_PASSWORD as this is required by the startup script. They will not be read by the .ovpn file, so you can set them to whatever.
