### ISSUE TITLE
PUREVPN not maintaining connection

### ISSUE THREAD

**Issue by rrd911** [haugene/docker-transmission-openvpn#585]
Recently I have experienced issues with PUREVPN
It will appear to connect but no traffic passed through the VPN. Snippet from the Docker logs.

Couple of errors stands out:
1.) Bad LZO decompression header
2.) ERROR: Linux route add command failed: external program exited with error status: 2
3.)  WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'

Thoughts?
-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    999
-------------------------------------
STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
RTNETLINK answers: File exists
Mon Aug 20 17:02:10 2018 ERROR: Linux route add command failed: external program exited with error status: 2
Mon Aug 20 17:02:10 2018 Initialization Sequence Completed
Mon Aug 20 17:02:18 2018 Bad LZO decompression header byte: 42
Mon Aug 20 17:02:28 2018 Bad LZO decompression header byte: 42
Mon Aug 20 17:02:38 2018 Bad LZO decompression header byte: 42
Mon Aug 20 17:02:48 2018 Bad LZO decompression header byte: 42
Mon Aug 20 17:02:59 2018 Bad LZO decompression header byte: 42
Mon Aug 20 17:04:09 2018 [PureVPN] Inactivity timeout (--ping-restart), restarting
Mon Aug 20 17:04:09 2018 SIGUSR1[soft,ping-restart] received, process restarting
Mon Aug 20 17:04:14 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Mon Aug 20 17:04:14 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Aug 20 17:04:14 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]79.142.73.4:53
Mon Aug 20 17:04:14 2018 UDP link local (bound): [AF_INET][undef]:1194
Mon Aug 20 17:04:14 2018 UDP link remote: [AF_INET]79.142.73.4:53
Mon Aug 20 17:04:17 2018 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1558', remote='link-mtu 1557'
Mon Aug 20 17:04:17 2018 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'
Mon Aug 20 17:04:17 2018 [PureVPN] Peer Connection Initiated with [AF_INET]79.142.73.4:53
Mon Aug 20 17:04:18 2018 Preserving previous TUN/TAP instance: tun0
Mon Aug 20 17:04:18 2018 Initialization Sequence Completed
Mon Aug 20 17:04:29 2018 Bad LZO decompression header byte: 42
Mon Aug 20 17:04:39 2018 Bad LZO decompression header byte: 42

**Comment by haugene** [comment]
Have you tried the new config added in #573? Use the dev tag and the new Norway2-udp or Norway2-tcp configs and see if that helps.

**Comment by nicomarti83** [comment]
same problem here, I'll try the dev version this afternoon.

**Comment by nicomarti83** [comment]
it seem to work great with this new config file 👍

**Comment by coolboiime** [comment]
Confirms that using `dev` and `Norway2-udp` or `Norway2-tcp` works!

**Comment by nicomarti83** [comment]
I just received a mail from purevpn about this problem... 

>Dear xxx,
Recently a vulnerability was identified in comp-lzo, the compression parameter on OpenVPN. The vulnerability could potentially allow a hacker or a middleman to intercept and read communications between two devices, even if the devices were protected by VPN encryption.
This vulnerability affected all VPN providers equally, with the majority of providers opting for a patch on server side, and requiring users to update their apps, which, to a certain extent, disrupted the connectivity of users.
Being a customer-centric and privacy-focused organization, our engineers figured out a way that ensured minimum downtime of servers, complete protection of our infrastructure, and maximum convenience of our users.
Here’s What We’ve Already Executed:
Our servers and infrastructure have already been patched and you don’t require to do anything at your end. This goes true for both our apps and manual users.
We could’ve sent this email earlier, but we did not want to fuel the frenzy surrounding the vulnerability in question. We quietly started to figure out ways to ensure 100% protection of our users, which we successfully achieved without troubling you or disrupting the service.
Thank you for trusting us with your privacy.
Your security comes first,
Hamelin - Product Manager
PureVPN

**Comment by coolboiime** [comment]
@nicomarti83 I got the same email. The issue should be fixed! Keeping it open for searchability. Will be closed soon!

**Comment by rrd911** [comment]
Is the solution
- remove 3 route commands from each connection
- change ca cert

Will the removal of the route commands cause any issues with leakage of info or not routing traffic through the vpn?

Will the changes be implemented and pushed to the master branch soon?

thanks

**Comment by haugene** [comment]
@rrd911 In #573 you can read the tests I've performed with these route options. As you can se the routes looks the same and the 0.0.0.0/1 via tun0 should take all the traffic.

The route-method option is Windows specific, so that doesn't matter. The route-delay is just about DHCP handshake timing, and there's only 3 providers of the 40+ in this image that has this option so I think that timing is not an issue here in general and the "route 0.0.0.0 0.0.0.0" line i'm not sure. Based on the errors I would say it defines a route that is already there, crashes with the 0.0.0.0/1? This option is also a rare sight in the ovpn configs across providers so I don't think is needed. And as described in the other thread, the public IP seen from the trackers is the VPN address. So it seems good.

Anyways, you could always ask PureVPN why they have it there and what the consequences would be of removing it in a Linux environment when the ip routes are as posted.

**Comment by rrd911** [comment]
I pulled down the Linux file for all the configurations and modified them to remove the route. Going through them do remove ones that are no longer applicable.

I will upload if you like. Just let me know how you would want the files

**Comment by rrd911** [comment]
I updated all the Connection files
- removed route lines
- confirmed gateway details using https://support.purevpn.com/vpn-servers
- deleted and renamed a few of the files

[Linux OpenVPN Updated files.zip](https://github.com/haugene/docker-transmission-openvpn/files/2372589/Linux.OpenVPN.Updated.files.zip)

**Comment by rrd911** [comment]
Here is a file I created with the modified connection
- removed route statement
-validated vpn gateways from https://support.purevpn.com/vpn-servers
- added missing and removed/renamed a few of the gateways files
[Linux OpenVPN Updated files.zip](https://github.com/haugene/docker-transmission-openvpn/files/2384843/Linux.OpenVPN.Updated.files.zip)

**Comment by haugene** [comment]
@rrd911 Completely missed the follow-up here. Are the configs you posted above still relevant after #589? That are the missing configs you mentioned? I can add them in that case 😄

**Comment by rrd911** [comment]
@haugene

There are more configurations for PureVPN based on the server page. I haven't gone through them all again to see if they are relevant still. I had pulled down the Linux PureVPN client from their web page when I put together the file.

https://support.purevpn.com/vpn-servers

**Comment by haugene** [comment]
Closing this and following up PureVPN config update in #1012 
New recommended configs have been downloaded from [here](https://support.purevpn.com/openvpn-files).
