### ISSUE TITLE
Issues running on ODROID

### ISSUE THREAD

**Issue by rushupedge** [haugene/docker-transmission-openvpn#586]
I've been running this on Raspberry Pi for a while now, but every week or so the Pi would lose network connection entirely and I would have to restart it by pulling the power, which risks SD card corruption. So I decided to get an ODROID C1+ (also for its gigabit ethernet.)

I exported the transmission-openvpn image and imported it on my odroid running Debian Jesse, replicating all the network mount points, etc. Everything seems to work fine – all the torrents I have seed correctly – except the last few I added give "error: file too large." Then, after about 10 minutes, the webui stops working entirely and just 404s, even though the container is running. Am I missing some preq package here?

**Comment by sudotrebor** [comment]
What file format is your raspberry pi writing to? (NFTS, MacOS Journaled, exFAT, ext4)

I had this problem with my Pi writing torrent data to an old external hard drive I put on my network. After much frustration I realized that my drive was formatted as exFAT which has a file size limit of 4gb. Any torrent that totaled over 4gb would start and then hang after about 15 minutes before crashing.

**Comment by sudotrebor** [comment]
CIFS is the type of share that is used to r/w data across the network. The actual drives should be one of the formats listed. I really doubt the NAS would let you format the drive with exFAT or FAT32 but it's worth ruling out.

**Comment by rushupedge** [comment]
It's a Synology device – Synology Hybrid Raid is ext4. Again, I read and write massive files to this no problem from the pi running raspbian. It's running it on this distribution on the ODROID which presents the problem: https://forum.odroid.com/viewtopic.php?f=96&t=17542

**Comment by haugene** [comment]
Cleaning up open issues and not sure what to do here. Seems like it's starting and running reasonably good, and then fails in a way I know very little about.

Want to close it. @rushupedge, is this still an issue?
And if so. Do you have any more details that could help debugging this? Are you building the image yourself or using the prebuilt ones on Docker hub. There's a new image now on the dev-armhf tag, could be worth a shot? Although it sounds like the issue might run a little deeper.
