### ISSUE TITLE
Problem with NordVPN default config

### ISSUE THREAD

**Issue by Dswamprat** [haugene/docker-transmission-openvpn#587]
This stopped working 2 days ago. It been working fine for 8 months .
The log says "Option error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/default.ovpn"

**Comment by cavalon** [comment]
... same here. container won't come up :(

**Comment by Briffou** [comment]
Check the name of the env variable OPENVPN_CONFIG (and do not forget to remove the "ovpn" extension in the name when setting the environment variable). I just chose a new file name among those in the folder nordvpn, and everything was back to normal.

**Comment by cavalon** [comment]
thx Briffou, this was the trick!

I guess, there were several problems on my side: I had a server configured, that was no longer in use and I did use the (old?) format:
`-e "OPENVPN_CONFIG=XXX.nordvpn.com.tcp443" \`

Changing to an appropriate server and configure the OPENVPN_CONFIG variable as "XXX.nordvpn.com.tcp" solved my problem...

**Comment by cavalon** [comment]
Dswamprat: What is this UI? Try to eddit OPENVPN_CONFIG (1st Screenshot, 2nd from below) with e.g. "us811.nordvpn.com.tcp" for an us-based server...

**Comment by Briffou** [comment]
@cavalon I was in the same configuration as you, looks like names haved changed. Seems also related to PR #576 and issue #577 .

@Dswamprat I don't know your UI, but as @cavalon said, try to edit OPENVPN_CONFIG...

**Comment by Dswamprat** [comment]
Yes, that worked!  :-) 
Now how do I know the geographic location ?

**Comment by cavalon** [comment]
... just choose / select a server name from https://nordvpn.com/servers/ or /etc/openvpn/nordvpn

**Comment by robinekenheim** [comment]
Hey I'm able to start nordVPN with editing said openvpn_config: "us811.nordvpn.com.tcp"

But I'm not able to do so with Swedish VPN servers, any ideas what that could be about?
Right now using US vpn for EU...

**Comment by PAKalucki** [comment]
@robinekenheim Same here, us811.nordvpn.com.tcp works, but none of the german and polish servers...

**Comment by cavalon** [comment]
... no problem here with my non-us server. your server is listed under nordvpn.com/servers/ ?

**Comment by robinekenheim** [comment]
@cavalon Yeah they're on the list and they've got a corresponding file in : https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/nordvpn

**Comment by Briffou** [comment]
@robinekenheim I just tried (randomly) with se40.nordvpn.com.udp and everything works fine for me. Have you tried udp ? What about the logs ?

**Comment by robinekenheim** [comment]
Sorry for the delay. Yes your suggestion worked @Briffou :)
