### ISSUE TITLE
PUREVPN config file name ignored

### ISSUE THREAD

**Issue by gtfunited** [haugene/docker-transmission-openvpn#590]
So I'm trying to connect using PUREVPN but the config file for Australia,Melbourne-tcp name gets ignored after the comma.

So when I put in:
Australia,Melbourne-tcp 

the logs only shows:

Australia.ovpn could not be found

Is there a naming convention that I am missing?

**Comment by haugene** [comment]
Ah, unfortunate. This has to do with the redundancy option.

https://github.com/haugene/docker-transmission-openvpn#run-container-from-docker-registry
> You can also provide a comma separated list of openvpn configuration filenames. If you provide a list, a file will be randomly chosen in the list, this is useful for redundancy setups.

This of course becomes a problem when the file name has a comma in it. We should rename all config files with comma. So Australia,Melbourne-tcp should be Australia-Melbourne-tcp for example.

**Comment by haugene** [comment]
Closing this. The reason for this behaviour has been explained and in the updated config files that are now in the dev branch, all files with "," in the name have been renamed to avoid this issue.
