### ISSUE TITLE
VPNbook cannot connect????

### ISSUE THREAD

**Issue by lamboid** [haugene/docker-transmission-openvpn#592]
Despite having to update the password all the time, does anyone else see vpnbook not connecting on regular occasion?

**Comment by haugene** [comment]
I think this should be fixed now, there has been a change in servers so the configs that were there before was not valid.

See #603, referencing commit f8269efc1ecf67aa60830310dad561dd733eb0a0 that adds the new configs. New configs are available on the dev branch, names can be found here: https://github.com/haugene/docker-transmission-openvpn/tree/dev/openvpn/vpnbook

**Comment by haugene** [comment]
Merged to master
