### ISSUE TITLE
transmission webui exposed on VPN UI with no auth?

### ISSUE THREAD

**Issue by allywilson1** [haugene/docker-transmission-openvpn#593]
I can access the WebUI on my LAN no problem, my worry is the public IP of the VPN also allows me to connect to the WebUI - and I don't want that.

The authentication options also appear to be getting ignored in /data/transmission-home/settings.json

Any idea what I should be doing differently?

```
sudo docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d
 -v /media/DataStore01/Downloads/:/data
 -v /etc/localtime:/etc/localtime:ro 
 -e OPENVPN_PROVIDER=IPREDATOR
 -e OPENVPN_USERNAME=username
 -e OPENVPN_PASSWORD=password
 -e WEBPROXY_ENABLED=false
 -e LOCAL_NETWORK=10.0.0.0/24
 --log-driver json-file
 --log-opt max-size=10m
 -p 10.0.0.1:9091:9091
 --dns 8.8.8.8
 --dns 8.8.4.4
 -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"
 --restart=always
 haugene/transmission-openvpn
```

**Comment by haugene** [comment]
If your VPN provider gives you a public IP (all ports), then it will be accessible from WAN. Most providers don't open ports though.

As for your settings issues, see the readme under "Transmission configuration options":
> Transmission options changed in the WebUI or in settings.json will be overridden at startup and will not survive after a reboot of the container. You may want to use these variables in order to keep your preferences.

And other issues explaining this:
#517 #150 #158 #322

**Comment by allywilson** [comment]
Thank you very much. I knew it was going to overridden, but thought that was an override file for it (to stop people editing one inside the image). Your links were helpful, and I've at least been able to secure it with a username and password passing through the variables in your first link.
