### ISSUE TITLE
Container repeatedly restarts, PIA VPN issue

### ISSUE THREAD

**Issue by Johnpojohn** [haugene/docker-transmission-openvpn#594]
Hi there!

My container is shutting down randomly every couple of hours, it gives an AUTH_FAILED message, runs the tunneldown.sh script and shuts down. I'm assuming its related to PIA shutting down my connection for some reason? If so it seems the container in itself is working properly, maybe some environment variable is wrong?

Thanks for your help!

**Comment by mrjackyliang** [comment]
Can you post the Docker logs and the command block you used to create the docker? Thanks.

**Comment by Johnpojohn** [comment]
I pulled the image and created the container using the Docker GUI on DSM, following the instructions from the Gitlab repo, particularly the issue regarding access to the TUN adapter. The container in itself launches without a problem, and works without issue as well, but it restarts every 2 hours or so because of this connection issue. Here's the log from the most recent one

[log.txt](https://github.com/haugene/docker-transmission-openvpn/files/2535215/log.txt)

**Comment by mrjackyliang** [comment]
That most likely because of the VPN service. That happens to me too. Trying to ping the OpenVPN connection doesn't seem to work for me, so I wrote a script to automatically check if the connection is active.

**Comment by Johnpojohn** [comment]
Its definitely because of the VPN service. Wouldnt it be possible to make the container pause all downloads and then resume them once connection has been re-established, instead of restarting?

**Comment by mrjackyliang** [comment]
It's mostly because of the conflicts that would happen if the docker was implemented with a self-shutdown checker. I developed TunnelChecker just for this reason: https://github.com/mrjackyliang/tunnelChecker

**Comment by Johnpojohn** [comment]
Hi!

Just to let you know that either one of the latest commits or editing the parameters (raising max peers global, and enabling the queue_stalled) solved the issue.

Thanks for your help!

**Comment by h45rd** [comment]
Thanks for checking back in with good news and some pointers for others that might face the same issue :)
