### ISSUE TITLE
CONFIGURATION WORKING FOR OPENMEDIAVAULT ARRAKIS (one net interface) / CYBERGHOST

### ISSUE THREAD

**Issue by maikvids** [haugene/docker-transmission-openvpn#595]
CONFIGURATION WORKING FOR OPENMEDIAVAULT ARRAKIS (one net interface) / CYBERGHOST

After two days of try/error, I managed to set up the docker image running correctly (or at least I assume it, I didn't get any weird error messages)
I attach the params I used for it, hope it'll be useful for somebody
If anyone can replicate and check if this configuration works fine with Cyberghost + OMV, I'll try to fork it and submit a pull request (although I can't promise anything because I'm completely newbie when it comes to docker+git XDDD)

###########################################################
#FIRST ENABLE TUN INTERFACE

modprobe tun
lsmod | grep tun
nano /etc/modules
add: tun at the end of the file so it will load in the kernel at start up

###########################################################
#DOCKER CONTAINER CREATION COMMANDS

docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \
--dns 1.1.1.1 \
-v /sharedfolders/your-route-to-the-file/:/data \
-v /sharedfolders/your-route-to-the-file/config/:/config \
-v /sharedfolders/your-route-to-the-file/openmediavault.ovpn:/etc/openvpn/custom/default.ovpn \
-v /sharedfolders/your-route-to-the-file/ca.crt:/etc/openvpn/custom/ca.crt \
-v /sharedfolders/your-route-to-the-file/client.crt:/etc/openvpn/custom/client.crt \
-v /sharedfolders/your-route-to-the-file/client.key:/etc/openvpn/custom/client.key \
-v /sharedfolders/your-route-to-the-file/openvpn-credentials.txt:/config/openvpn-credentials.txt \

***
Note: I had this file already created, I suppose because of the several tries I've done
If it's not created yet in your system, just put in it:
$OPENVPN_USERNAME (the username provided by Cyberghost in add device section, same as in ENV FILE)
$OPENVPN_PASSWORD (password provided by Cyberghost in add device section, same as in ENV FILE)
***

-v /etc/localtime:/etc/localtime:ro 
--env-file /sharedfolders/your-route-to-the-file/envvar \
-p 1194:1194 \
-p 9091:9091 \
-p 8080:8080 \
-p 8888:8888 \
--sysctl net.ipv6.conf.all.disable_ipv6=0 \
--log-driver json-file \
--log-opt max-size=10m \
--restart unless-stopped \ 
--name "transmission-openvpn-omv" \
haugene/transmission-openvpn \

###########################################################
#ENVIROMENT VARIABLES (envvar)

OPENVPN_PROVIDER=CUSTOM
OPENVPN_CONFIG=default
OPENVPN_USERNAME=username provided by Cyberghost in add device section
OPENVPN_PASSWORD=password provided by Cyberghost in add device section
#OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
OPENVPN_AUTH-NOCACHE=true
LOCAL_NETWORK=X.X.X.X/XX (your local network)
ENABLE_UFW=true
UFW_ALLOW_GW_NET=true
UFW_EXTRA_PORTS=1194,8888,9091,443,9910,23561
UFW_DISABLE_IPTABLES_REJECT=true
GLOBAL_APPLY_PERMISSIONS=true
#TRANSMISSION_ALT_SPEED_DOWN=50
#TRANSMISSION_ALT_SPEED_ENABLED=false
#TRANSMISSION_ALT_SPEED_TIME_BEGIN=540
#TRANSMISSION_ALT_SPEED_TIME_DAY=127
#TRANSMISSION_ALT_SPEED_TIME_ENABLED=false
#TRANSMISSION_ALT_SPEED_TIME_END=1020
#TRANSMISSION_ALT_SPEED_UP=50
TRANSMISSION_BIND_ADDRESS_IPV4=X.X.X.X (IP Adress of your openmediavault device)
#TRANSMISSION_BIND_ADDRESS_IPV6=::
#TRANSMISSION_BLOCKLIST_ENABLED=false
#TRANSMISSION_BLOCKLIST_URL=http://www.example.com/blocklist
#TRANSMISSION_CACHE_SIZE_MB=4
TRANSMISSION_DHT_ENABLED=true
TRANSMISSION_DOWNLOAD_DIR=/data/completed
#TRANSMISSION_DOWNLOAD_LIMIT=100
#TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0
TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5
TRANSMISSION_ENCRYPTION=1
#TRANSMISSION_IDLE_SEEDING_LIMIT=30
#TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false
TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
#TRANSMISSION_LPD_ENABLED=false
#TRANSMISSION_MAX_PEERS_GLOBAL=200
#TRANSMISSION_MESSAGE_LEVEL=2
#TRANSMISSION_PEER_CONGESTION_ALGORITHM=
#TRANSMISSION_PEER_ID_TTL_HOURS=6
#TRANSMISSION_PEER_ID_TTL_HOURS=6
#TRANSMISSION_PEER_LIMIT_GLOBAL=200
#TRANSMISSION_PEER_LIMIT_PER_TORRENT=50
#TRANSMISSION_PEER_PORT=51413
#TRANSMISSION_PEER_PORT_RANDOM_HIGH=65535
#TRANSMISSION_PEER_PORT_RANDOM_LOW=49152
#TRANSMISSION_PEER_PORT_RANDOM_ON_START=false
#TRANSMISSION_PEER_SOCKET_TOS=default
#TRANSMISSION_PEX_ENABLED=true
#TRANSMISSION_PORT_FORWARDING_ENABLED=false
#TRANSMISSION_PREALLOCATION=1
#TRANSMISSION_PREFETCH_ENABLED=1
#TRANSMISSION_QUEUE_STALLED_ENABLED=true
#TRANSMISSION_QUEUE_STALLED_MINUTES=30
#TRANSMISSION_RATIO_LIMIT=2
#TRANSMISSION_RATIO_LIMIT_ENABLED=false
#TRANSMISSION_RENAME_PARTIAL_FILES=true
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
#TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0
TRANSMISSION_RPC_ENABLED=true
#TRANSMISSION_RPC_HOST_WHITELIST=
#TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=true
TRANSMISSION_RPC_PASSWORD=XXXXX (set it up for Transmission client)
TRANSMISSION_RPC_PORT=9091
TRANSMISSION_RPC_URL=/transmission/
TRANSMISSION_RPC_USERNAME=XXXXX (set it up for Transmission client)
#TRANSMISSION_RPC_WHITELIST=127.0.0.1
#TRANSMISSION_RPC_WHITELIST_ENABLED=false
#TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=true
#TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=false
#TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=
#TRANSMISSION_SEED_QUEUE_ENABLED=false
#TRANSMISSION_SEED_QUEUE_SIZE=10
#TRANSMISSION_SPEED_LIMIT_DOWN=100
#TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false
#TRANSMISSION_SPEED_LIMIT_UP=100
#TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false
#TRANSMISSION_START_ADDED_TORRENTS=true
#TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false
#TRANSMISSION_UMASK=2
#TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=14
#TRANSMISSION_UTP_ENABLED=true
TRANSMISSION_WATCH_DIR=/data/watch
TRANSMISSION_WATCH_DIR=/data/watch
TRANSMISSION_WATCH_DIR_ENABLED=true
TRANSMISSION_HOME=/data/transmission-home
#TRANSMISSION_WATCH_DIR_FORCE_GENERIC=false
PUID=XXXX (PUID of the user for docker)
PGID=XXX (PGID of the group for docker)
#WEBPROXY_ENABLED=false
#WEBPROXY_PORT=8888

###########################################################
#OPENVPN.OPVN FILE

client
remote OPENVPN_Server_name_provided_in_add_device_section (Type cg-CC.net) 443
dev tun
proto udp
auth-user-pass /config/openvpn-credentials.txt

resolv-retry infinite
redirect-gateway def1
persist-key
persist-tun
nobind
cipher AES-256-CBC
auth SHA256
ping 5
ping-exit 60
ping-timer-rem
explicit-exit-notify 2
script-security 2
remote-cert-tls server
route-delay 5
tun-mtu 1500
fragment 1300
mssfix 1300
verb 4
comp-lzo

ca /etc/openvpn/custom/ca.crt

cert /etc/openvpn/custom/client.crt

key /etc/openvpn/custom/client.key

###########################################################
** Modify ACL to match PUID / PGID Stated in ENV FILE after creating the conatiner

Finally, just say Thank you haugene and all contributors for what you done for the community!!!
Many times we forget what you're doing for the rest for free
Regards

**Comment by smith000-000** [comment]
So I followed the instructions above for making sure the tun module worked. Also I ran the tun.sh and I'm still getting the tun/tap error. Totally looks like the VPN is connecting fine so I didn't go through the works of setting all the environments. 

@maikvids , did you get this far with you setup before editing all the docker files?

Where are you doing this:
###########################################################
#DOCKER CONTAINER CREATION COMMANDS

docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d 

I'm creating my container through the web UI.

* warning - this is my first docker experience so please be gentle.


Sat Sep  8 16:23:40 2018 ROUTE_GATEWAY 192.168.1.1/255.255.255.0 IFACE=enp3s0 HWADDR=50:e5:49:e4:45:e4
Sat Sep  8 16:23:40 2018 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Sat Sep  8 16:23:40 2018 Exiting due to fatal error

**Comment by maikvids** [comment]
Hi @smith000-000 
I only managed to make it work through console, I got tired of rerror messages without proper descriptions in the IU
But to be fair I dont' remeber if I had the TUN devide loaded when I tried to do it by IU so maybe that was my mistake.
Anyway Congrats for making it wotrk through IU!!

Just for confirmation, did your transmission server loaded correctly? I mean you get, this output at the log?

`Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : x.x.x.x`
`Generating transmission settings.json from env variables`
`sed'ing True to true`
`Enforcing ownership on transmission config directories`
`Applying permissions to transmission config directories`
`-------------------------------------`
`Transmission will run as`
`-------------------------------------`
`User name:   xx`
`User uid:    xxxx`
`User gid:    xxx`
`-------------------------------------`
`STARTING TRANSMISSION`
`NO PORT UPDATER FOR THIS PROVIDER`
`Transmission startup script complete.`
`Sun Sep  9 12:28:40 2018 us=83790 /sbin/ip route add x.x.x.x/x via x.x.x.x`
`Sun Sep  9 12:28:40 2018 us=86226 /sbin/ip route add x.x.x.x/x via x.x.x.x`
`Sun Sep  9 12:28:40 2018 us=88443 /sbin/ip route add x.x.x.x/x via x.x.x.x`
`Sun Sep  9 12:28:40 2018 us=90709 /sbin/ip route add x.x.x.x/x via x.x.x.x`
`Sun Sep  9 12:28:40 2018 us=93017 add_route_ipv6(x::/x -> x:x:x:x:x:x:x:x metric -1) dev tun0`
`Sun Sep  9 12:28:40 2018 us=93110 /sbin/ip -6 route add x::/x dev tun0`
`Sun Sep  9 12:28:40 2018 us=95457 Initialization Sequence Completed`

And if so, last check, did you ensure that you've are connected to the VPN and getting a remote IP through the method described in:
#323 

If you had a remote IP, I think this config will be valid
Thank you

**Comment by smith000-000** [comment]
Yeah that's exactly what I got. (well different IPs, but yeah)

So I used that little proxy server and did an ifconfig.co to check my
address.

I also used that torrent IP checker website where they give you a magnet
link specific to you and then pop the address up when your client connects.
Definitely VPN'd

So I didn't totally get it though the UI but the actual loading of the
container for sure was.

I'm not seeing very good performance even with my Usenet client. Docker
containers have full access to ram and CPU right? They aren't throttled at
all are they?

Josh

**Comment by maikvids** [comment]
To be fair I'm as new as you in docker... I suppose you may need to tweak a little bit the container, but I can't bring any help in it. Let's see if any guru of plex can give you some light about it. 
In my case I don't have an extraordinay performance but with the 10mb dSL that I have in my home I can't expect anything better

**Comment by xorinzor** [comment]
Just follow this, much easier.

https://github.com/haugene/docker-transmission-openvpn#using-a-custom-provider

And look at this config file for how to edit your own config file: 
https://github.com/haugene/docker-transmission-openvpn/blob/da0efcdfd3155530beda897ee8ba8d8d51b2e2bc/openvpn/tunnelbear/Australia.ovpn

**Comment by robertbaker** [comment]
please provide cyberghost config

**Comment by maikvids** [comment]
@xorinzor @robertbaker 

Important point is to introduce this line, which is not included by default (and is not detailed in the #custom provider section):

auth-user-pass /config/openvpn-credentials.txt

This is the openvpn config file for cyberghost:
--------------------------------------------------------
#OPENVPN.OPVN FILE

client
remote OPENVPN_Server_name_provided_in_add_device_section (Type cg-CC.net) 443
dev tun
proto udp
auth-user-pass /config/openvpn-credentials.txt

resolv-retry infinite
redirect-gateway def1
persist-key
persist-tun
nobind
cipher AES-256-CBC
auth SHA256
ping 5
ping-exit 60
ping-timer-rem
explicit-exit-notify 2
script-security 2
remote-cert-tls server
route-delay 5
tun-mtu 1500
fragment 1300
mssfix 1300
verb 4
comp-lzo

ca /etc/openvpn/custom/ca.crt

cert /etc/openvpn/custom/client.crt

key /etc/openvpn/custom/client.key

---------------------------------------------------------

**Comment by xorinzor** [comment]
@maikvids that depends on where you put the credentials file.
In the end, the openvpn from this docker container wasn't working for me, so I set up a different openvpn container, which worked instantly with the exact same config.
