### ISSUE TITLE
ERROR: Linux route add command failed: external program exited with error status: 2

### ISSUE THREAD

**Issue by xirian** [haugene/docker-transmission-openvpn#596]
I'm having an issue once it gets to the part for starting transmission. I'm using proxpn as my vpn provider and it seems like it connects.

I'm running this on Debian 9.5. It fails at 

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Sat Sep  8 18:14:34 2018 us=901079 /sbin/ip route add 50.7.88.172/32 via 172.17.0.1
Sat Sep  8 18:14:34 2018 us=902031 /sbin/ip route del 0.0.0.0/0
Sat Sep  8 18:14:34 2018 us=904072 /sbin/ip route add 0.0.0.0/0 via 192.168.54.1
Sat Sep  8 18:14:34 2018 us=904768 /sbin/ip route add 0.0.0.0/0 via 192.168.54.1
RTNETLINK answers: File exists
Sat Sep  8 18:14:34 2018 us=906500 ERROR: Linux route add command failed: external program exited with error status: 2
Sat Sep  8 18:14:34 2018 us=906546 Initialization Sequence Completed

Here are my full logs:

-------------------------------------------------

Using OpenVPN provider: PROXPN
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 10.10.0.0/16 via 172.17.0.1 dev eth0
Sat Sep  8 18:14:31 2018 us=93885 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Sat Sep  8 18:14:31 2018 us=93919 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Sat Sep  8 18:14:31 2018 us=93926 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Sat Sep  8 18:14:31 2018 us=93947 Current Parameter Settings:
Sat Sep  8 18:14:31 2018 us=93953   config = '/etc/openvpn/proxpn/default.ovpn'
Sat Sep  8 18:14:31 2018 us=93962   mode = 0
Sat Sep  8 18:14:31 2018 us=93966   persist_config = DISABLED
Sat Sep  8 18:14:31 2018 us=93971   persist_mode = 1
Sat Sep  8 18:14:31 2018 us=93975 NOTE: --mute triggered...
Sat Sep  8 18:14:31 2018 us=93985 325 variation(s) on previous 5 message(s) suppressed by --mute
Sat Sep  8 18:14:31 2018 us=93990 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 24 2018
Sat Sep  8 18:14:31 2018 us=93999 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sat Sep  8 18:14:31 2018 us=94100 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Sat Sep  8 18:14:31 2018 us=94111 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Sep  8 18:14:31 2018 us=94395 LZO compression initializing
Sat Sep  8 18:14:31 2018 us=94446 Control Channel MTU parms [ L:1622 D:1212 EF:38 EB:0 ET:0 EL:3 ]
Sat Sep  8 18:14:31 2018 us=94465 Data Channel MTU parms [ L:1622 D:1450 EF:122 EB:406 ET:0 EL:3 ]
Sat Sep  8 18:14:31 2018 us=94484 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1542,tun-mtu 1500,proto UDPv4,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-client'
Sat Sep  8 18:14:31 2018 us=94490 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1542,tun-mtu 1500,proto UDPv4,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-server'
Sat Sep  8 18:14:31 2018 us=94506 TCP/UDP: Preserving recently used remote address: [AF_INET]50.7.88.172:443
Sat Sep  8 18:14:31 2018 us=94525 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sat Sep  8 18:14:31 2018 us=94531 UDP link local: (not bound)
Sat Sep  8 18:14:31 2018 us=94536 UDP link remote: [AF_INET]50.7.88.172:443
Sat Sep  8 18:14:31 2018 us=184144 TLS: Initial packet from [AF_INET]50.7.88.172:443, sid=7f9a6b88 30d5a3f3
Sat Sep  8 18:14:31 2018 us=834918 VERIFY OK: depth=1, C=US, ST=CA, L=SanFrancisco, O=proXPN Direct, LLC, OU=proxpn.com, CN=proxpn.com, name=proxpn.com, emailAddress=support@proxpn.com
Sat Sep  8 18:14:31 2018 us=835098 VERIFY OK: depth=0, C=US, ST=CA, L=SanFrancisco, O=proXPN Direct, LLC, OU=proxpn.com, CN=proxpn.com, name=proxpn.com, emailAddress=support@proxpn.com
Sat Sep  8 18:14:32 2018 us=414409 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1542', remote='link-mtu 48042'
Sat Sep  8 18:14:32 2018 us=414440 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1500', remote='tun-mtu 48000'
Sat Sep  8 18:14:32 2018 us=414511 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA
Sat Sep  8 18:14:32 2018 us=414535 [proxpn.com] Peer Connection Initiated with [AF_INET]50.7.88.172:443
Sat Sep  8 18:14:33 2018 us=603400 SENT CONTROL [proxpn.com]: 'PUSH_REQUEST' (status=1)
Sat Sep  8 18:14:33 2018 us=694933 PUSH: Received control message: 'PUSH_REPLY,sndbuf 393216,rcvbuf 393216,dhcp-option DNS 10.0.22.1,dhcp-option DNS 10.0.22.2,redirect-gateway,route-gateway 192.168.54.1,topology subnet,ping 10,ping-restart 60,ifconfig 192.168.54.205 255.255.255.0'
Sat Sep  8 18:14:33 2018 us=695025 OPTIONS IMPORT: timers and/or timeouts modified
Sat Sep  8 18:14:33 2018 us=695039 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Sat Sep  8 18:14:33 2018 us=695054 Socket Buffers: R=[212992->425984] S=[212992->425984]
Sat Sep  8 18:14:33 2018 us=695059 OPTIONS IMPORT: --ifconfig/up options modified
Sat Sep  8 18:14:33 2018 us=695065 OPTIONS IMPORT: route options modified
Sat Sep  8 18:14:33 2018 us=695069 OPTIONS IMPORT: route-related options modified
Sat Sep  8 18:14:33 2018 us=695073 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sat Sep  8 18:14:33 2018 us=695102 Data Channel MTU parms [ L:1542 D:1450 EF:42 EB:406 ET:0 EL:3 ]
Sat Sep  8 18:14:33 2018 us=695195 Outgoing Data Channel: Cipher 'BF-CBC' initialized with 512 bit key
Sat Sep  8 18:14:33 2018 us=695209 WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
Sat Sep  8 18:14:33 2018 us=695216 Outgoing Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
Sat Sep  8 18:14:33 2018 us=695264 Incoming Data Channel: Cipher 'BF-CBC' initialized with 512 bit key
Sat Sep  8 18:14:33 2018 us=695276 WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
Sat Sep  8 18:14:33 2018 us=695282 Incoming Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
Sat Sep  8 18:14:33 2018 us=695287 WARNING: cipher with small block size in use, reducing reneg-bytes to 64MB to mitigate SWEET32 attacks.
Sat Sep  8 18:14:33 2018 us=695413 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:03
Sat Sep  8 18:14:33 2018 us=695615 TUN/TAP device tun0 opened
Sat Sep  8 18:14:33 2018 us=695636 TUN/TAP TX queue length set to 100
Sat Sep  8 18:14:33 2018 us=695649 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Sat Sep  8 18:14:33 2018 us=695674 /sbin/ip link set dev tun0 up mtu 1500
Sat Sep  8 18:14:33 2018 us=696549 /sbin/ip addr add dev tun0 192.168.54.205/24 broadcast 192.168.54.255
Sat Sep  8 18:14:33 2018 us=697266 /etc/openvpn/tunnelUp.sh tun0 1500 1542 192.168.54.205 255.255.255.0 init
Up script executed with tun0 1500 1542 192.168.54.205 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 192.168.54.205
Generating transmission settings.json from env variables
sed'ing True to true

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Sat Sep  8 18:14:34 2018 us=901079 /sbin/ip route add 50.7.88.172/32 via 172.17.0.1
Sat Sep  8 18:14:34 2018 us=902031 /sbin/ip route del 0.0.0.0/0
Sat Sep  8 18:14:34 2018 us=904072 /sbin/ip route add 0.0.0.0/0 via 192.168.54.1
Sat Sep  8 18:14:34 2018 us=904768 /sbin/ip route add 0.0.0.0/0 via 192.168.54.1
RTNETLINK answers: File exists
Sat Sep  8 18:14:34 2018 us=906500 ERROR: Linux route add command failed: external program exited with error status: 2
Sat Sep  8 18:14:34 2018 us=906546 Initialization Sequence Completed

**Comment by xirian** [comment]
nevermind it turned out to be a really crappy vpn provider

**Comment by ernstp** [comment]
I'm also getting this error with Anonine.
latest-arm, LibreELEC

Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 1.2.7
runc version: v1.0.0-rc8
init version: fec3683b971d9c3ef73f284f176672c44b448662
Kernel Version: 4.19.57
Operating System: LibreELEC (official): 9.1.002
OSType: linux
Architecture: armv7l

**Comment by staticgroup** [comment]
I had to rebuild my container due to stupidity and am now getting this error any tips?

**Comment by pkishino** [comment]
please provide more details (config, logs etc) in a new thread
