### ISSUE TITLE
Add AirVPN as provider

### ISSUE THREAD

**Issue by haugene** [haugene/docker-transmission-openvpn#60]
@SVR111 requested AirVPN as new provider in #48. As it was a bit off topic, I'm creating a new issue for this request.

Question though! I can add AirVPN as provider, but it seems you need to generate a configuration on their home pages which needs you to be logged in. Could you generate a config for me @SVR111? From what I understand you choose operating system (go linux) and a region to connect to. If you want, you could generate configs for several regions and I'll add them all. Or just send me one.

If someone gives me a dropbox-link or something with configs for AirVPN, I'll it as a provider to the container.

**Comment by stevepet** [comment]
AirVPN uses .ovpn files with private keys generated for each user account. Adding any of these files to the container will only work for the user that generated them. A better solution may be to add a new volume (-v) that points to a configuration directory where users can put their own .ovpn files.
The environment variables OPENVPN_USERNAME and OPENVPN_PASSWORD are also not necessary with these .ovpn files.

**Comment by haugene** [comment]
Aha, I see. Well, that can be done without any changes to the container as it is today.

To run it with a custom provider and .ovpn file just add:
`-v /path/to/custom/config.ovpn:/etc/openvpn/custom/default.ovpn` 
and then set `OPENVPN_PROVIDER=CUSTOM`

You still need to set OPENVPN_USERNAME and OPENVPN_PASSWORD as the startup script will fail if they're not there. But they can both be set to "dummy" and it won't have an effect as the ovpn-config will not read them anyways.

**Comment by stevepet** [comment]
Thanks Kristian, This worked as you described for AirVPN.

**Comment by haugene** [comment]
Glad to hear it! Instructions are provided in README and code is merged to master. Closing this.
