### ISSUE TITLE
Improvement: Broken with newer docker versions (IPv6)

### ISSUE THREAD

**Issue by Kira9204** [haugene/docker-transmission-openvpn#602]
Hi!

I've noticed that newer versions of docker are IPv4 only and outright disables IPv6 support with sysctl net.ipv6.conf.all.disable_ipv6=1.
This makes the container silently crash since VPN providers like Mullvad sends IPv6 configurations.
I am quite new to docker but found that adding --sysctl net.ipv6.conf.all.disable_ipv6=0 solves the issue. Maybe there is a better/more permanent place to put it?
Example: docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \
              --sysctl net.ipv6.conf.all.disable_ipv6=0 \
I think adding this to the the run command in the documentation will be quite helpful if nothing else.

System:
Ubuntu server 18.04 x64
Docker version: 18.06.1-ce, build e68fc7a

**Comment by haugene** [comment]
That option is mentioned in the section of the README for Synology NAS. Could be nice to have a short description in a separate section, feel free to submit a PR :)
