### ISSUE TITLE
Debian : docker start, but not transmission. Using vpnbook

### ISSUE THREAD

**Issue by Bschalck** [haugene/docker-transmission-openvpn#603]
When I start the docker vpn, it starts.
But there is no transmission process.

Here is logs :
/root $ docker logs transmission

> Using OpenVPN provider: VPNBOOK
Starting OpenVPN using config vpnbook-euro1-udp25000.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.42.1 dev eth0
Wed Sep 19 11:15:40 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on S
ep 26 2017
Wed Sep 19 11:15:40 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Wed Sep 19 11:15:40 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Wed Sep 19 11:15:40 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Sep 19 11:15:40 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]176.126.237.217:25000
Wed Sep 19 11:15:40 2018 Socket Buffers: R=[212992->212992] S=[212992->212992]
Wed Sep 19 11:15:40 2018 UDP link local: (not bound)
Wed Sep 19 11:15:40 2018 UDP link remote: [AF_INET]176.126.237.217:25000

**Comment by Bschalck** [comment]
I have nothing else from **docker logs** command ...

> Using OpenVPN provider: VPNBOOK
> Starting OpenVPN using config vpnbook-euro1-udp25000.ovpn
> Setting OPENVPN credentials...
> adding route to local network 192.168.0.0/24 via 172.17.42.1 dev eth0
> Wed Sep 19 11:25:50 2018 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 24 2018
> Wed Sep 19 11:25:50 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
> Wed Sep 19 11:25:50 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
> Wed Sep 19 11:25:50 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Wed Sep 19 11:25:50 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]176.126.237.217:25000
> Wed Sep 19 11:25:50 2018 Socket Buffers: R=[212992->212992] S=[212992->212992]
> Wed Sep 19 11:25:50 2018 UDP link local: (not bound)
> Wed Sep 19 11:25:50 2018 UDP link remote: [AF_INET]176.126.237.217:25000
> Wed Sep 19 11:26:50 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Wed Sep 19 11:26:50 2018 TLS Error: TLS handshake failed
> Wed Sep 19 11:26:50 2018 SIGUSR1[soft,tls-error] received, process restarting
> Wed Sep 19 11:26:50 2018 Restart pause, 5 second(s)
> Wed Sep 19 11:26:55 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
> Wed Sep 19 11:26:55 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Wed Sep 19 11:26:55 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]176.126.237.217:25000
> Wed Sep 19 11:26:55 2018 Socket Buffers: R=[212992->212992] S=[212992->212992]
> Wed Sep 19 11:26:55 2018 UDP link local: (not bound)
> Wed Sep 19 11:26:55 2018 UDP link remote: [AF_INET]176.126.237.217:25000

**Comment by Bschalck** [comment]
Here is th ps -eaf on the docker  : 

> UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 11:25 ?        00:00:00 dumb-init /etc/openvpn/start.sh
root         8     1  0 11:25 ?        00:00:00 openvpn --script-security 2 --up-delay --up /etc/openvpn/tunnelUp.sh --down /etc/openvpn/tunnelDown.sh --config /etc/openvpn/vpnbook/vpnbook-euro1-udp25000.ovpn
root        34     0  0 11:46 pts/0    00:00:00 ps -eaf -www

**Comment by haugene** [comment]
This one is probably it:
> Wed Sep 19 11:26:50 2018 SIGUSR1[soft,tls-error] received, process restarting
Wed Sep 19 11:26:50 2018 Restart pause, 5 second(s)

Seems to be due to TLS error?
>Wed Sep 19 11:26:50 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Sep 19 11:26:50 2018 TLS Error: TLS handshake failed

You should check the bundled config: https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/vpnbook/vpnbook-euro1-udp25000.ovpn

Is the key up to date with the current config file you get from VPN-book? And if so, this might be a DNS/connection issue. Try running the container interactively and see if you can ping the server etc.

**Comment by haugene** [comment]
Transmission won't start until the tunnel is set up. So it not running is expected.

**Comment by haugene** [comment]
Ref that link
> https://www.vpnbook.com/freevpn

It seems that the FR server you added in #604 does not permit p2p downloads? Does it still work? This container kind of needs p2p to work ;)

**Comment by Bschalck** [comment]
Yep you're right ! I did not notice this detail.
Sould we take https://www.vpnbook.com/free-openvpn-account/VPNBook.com-OpenVPN-DE4 ?

Ijsut see the transmission stared, I d'ont onw if download works :)

**Comment by Bschalck** [comment]
Hy,
I made 2 new files for vpnbook vpn  with p2p allowed

**Comment by haugene** [comment]
Hey. So I just deleted all the previous configs and added all the servers for the two destinations that allows p2p. You can see my changes in the two commits referenced above. Can you test and see if it works on the dev tag?

**Comment by Bschalck** [comment]
It works perfectly ! Thanks a lot !
