### ISSUE TITLE
IPVANISH Setup Issue

### ISSUE THREAD

**Issue by s4b3rt0oth** [haugene/docker-transmission-openvpn#609]
Starting a new container with IPVANISH seems to be broken. (It may be all VPNs but I only have IPVANISH to test)
 The docker logs returns:
`Sun Sep 23 07:30:34 2018 /etc/openvpn/tunnelUp.sh tun0 1500 1553 172.21.20.202 255.255.254.0 init
/etc/transmission/start.sh: 46: /etc/transmission/environment-variables.sh: Syntax error: newline unexpected
/opt/tinyproxy/start.sh: 46: /etc/transmission/environment-variables.sh: Syntax error: newline unexpected
Sun Sep 23 07:30:34 2018 WARNING: Failed running command (--up/--down): external program exited with error status: 2
Sun Sep 23 07:30:34 2018 Exiting due to fatal error
Using OpenVPN provider: IPVANISH`

Here is the config I am using to start the container:

`docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d --dns 84.200.69.80 --dns 84.200.70.40 --restart=always \
              -v /mnt/download/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e OPENVPN_PROVIDER=IPVANISH \
              -e OPENVPN_CONFIG="ipvanish-US-Ashburn-iad-a01,ipvanish-US-Ashburn-iad-a02,ipvanish-US-Ashburn-iad-a03,ipvanish-US-Ashburn-iad-a04,ipvanish-US-Ashburn-iad-a05,ipvanish-US-Ashburn-iad-a06,ipvanish-US-Ashburn-iad-a07,ipvanish-US-Ashburn-iad-a08,ipvanish-US-Ashburn-iad-a09,ipvanish-US-Ashburn-iad-a10,ipvanish-US-Ashburn-iad-a11,ipvanish-US-Ashburn-iad-a12,ipvanish-US-Ashburn-iad-a13,ipvanish-US-Ashburn-iad-a14,ipvanish-US-Ashburn-iad-a15,ipvanish-US-Ashburn-iad-a16,ipvanish-US-Ashburn-iad-a17,ipvanish-US-Ashburn-iad-a18,ipvanish-US-Ashburn-iad-a19,ipvanish-US-Ashburn-iad-a20,ipvanish-US-Atlanta-atl-a02,ipvanish-US-Atlanta-atl-a03,ipvanish-US-Atlanta-atl-a04,ipvanish-US-Atlanta-atl-a05,ipvanish-US-Atlanta-atl-a06,ipvanish-US-Atlanta-atl-a07,ipvanish-US-Atlanta-atl-a08,ipvanish-US-Atlanta-atl-a09,ipvanish-US-Atlanta-atl-a10,ipvanish-US-Atlanta-atl-a11,ipvanish-US-Atlanta-atl-a12,ipvanish-US-Atlanta-atl-a13,ipvanish-US-Atlanta-atl-a14,ipvanish-US-Atlanta-atl-a15,ipvanish-US-Atlanta-atl-a16,ipvanish-US-Atlanta-atl-a17,ipvanish-US-Atlanta-atl-a19,ipvanish-US-Atlanta-atl-a21,ipvanish-US-Atlanta-atl-a23,ipvanish-US-Atlanta-atl-a24,ipvanish-US-Atlanta-atl-a25,ipvanish-US-Atlanta-atl-a26,ipvanish-US-Atlanta-atl-a27,ipvanish-US-Atlanta-atl-a28,ipvanish-US-Atlanta-atl-a29,ipvanish-US-Atlanta-atl-a30,ipvanish-US-Atlanta-atl-a31,ipvanish-US-Atlanta-atl-a32,ipvanish-US-Atlanta-atl-a33,ipvanish-US-Atlanta-atl-a34,ipvanish-US-Atlanta-atl-a35,ipvanish-US-Atlanta-atl-a36,ipvanish-US-Atlanta-atl-a37,ipvanish-US-Atlanta-atl-a38,ipvanish-US-Atlanta-atl-a39,ipvanish-US-Atlanta-atl-a40,ipvanish-US-Chicago-chi-a01,ipvanish-US-Chicago-chi-a02,ipvanish-US-Chicago-chi-a03,ipvanish-US-Chicago-chi-a04,ipvanish-US-Chicago-chi-a05,ipvanish-US-Chicago-chi-a06,ipvanish-US-Chicago-chi-a07,ipvanish-US-Chicago-chi-a08,ipvanish-US-Chicago-chi-a09,ipvanish-US-Chicago-chi-a10,ipvanish-US-Chicago-chi-a11,ipvanish-US-Chicago-chi-a12,ipvanish-US-Chicago-chi-a13,ipvanish-US-Chicago-chi-a14,ipvanish-US-Chicago-chi-a15,ipvanish-US-Chicago-chi-a16,ipvanish-US-Chicago-chi-a17,ipvanish-US-Chicago-chi-a18,ipvanish-US-Chicago-chi-a19,ipvanish-US-Chicago-chi-a20,ipvanish-US-Chicago-chi-a21,ipvanish-US-Chicago-chi-a22,ipvanish-US-Chicago-chi-a23,ipvanish-US-Chicago-chi-a24,ipvanish-US-Chicago-chi-a25,ipvanish-US-Chicago-chi-a26,ipvanish-US-Chicago-chi-a27,ipvanish-US-Chicago-chi-a28,ipvanish-US-Chicago-chi-a29,ipvanish-US-Chicago-chi-a30,ipvanish-US-Chicago-chi-a31,ipvanish-US-Chicago-chi-a32,ipvanish-US-Chicago-chi-a33,ipvanish-US-Chicago-chi-a34,ipvanish-US-Chicago-chi-a35,ipvanish-US-Chicago-chi-a36,ipvanish-US-Chicago-chi-a37,ipvanish-US-Chicago-chi-a38,ipvanish-US-Chicago-chi-a39,ipvanish-US-Chicago-chi-a40,ipvanish-US-Dallas-dal-a01,ipvanish-US-Dallas-dal-a02,ipvanish-US-Dallas-dal-a03,ipvanish-US-Dallas-dal-a04,ipvanish-US-Dallas-dal-a05,ipvanish-US-Dallas-dal-a06,ipvanish-US-Dallas-dal-a07,ipvanish-US-Dallas-dal-a08,ipvanish-US-Dallas-dal-a09,ipvanish-US-Dallas-dal-a10,ipvanish-US-Dallas-dal-a11,ipvanish-US-Dallas-dal-a12,ipvanish-US-Dallas-dal-a13,ipvanish-US-Dallas-dal-a14,ipvanish-US-Dallas-dal-a15,ipvanish-US-Dallas-dal-a16,ipvanish-US-Dallas-dal-a17,ipvanish-US-Dallas-dal-a18,ipvanish-US-Dallas-dal-a19,ipvanish-US-Dallas-dal-a20,ipvanish-US-Las-Vegas-las-c01,ipvanish-US-Las-Vegas-las-c02,ipvanish-US-Las-Vegas-las-c03,ipvanish-US-Las-Vegas-las-c04,ipvanish-US-Las-Vegas-las-c05,ipvanish-US-Las-Vegas-las-c06,ipvanish-US-Las-Vegas-las-c07,ipvanish-US-Las-Vegas-las-c08,ipvanish-US-Las-Vegas-las-c09,ipvanish-US-Las-Vegas-las-c10,ipvanish-US-Los-Angeles-lax-a01,ipvanish-US-Los-Angeles-lax-a02,ipvanish-US-Los-Angeles-lax-a03,ipvanish-US-Los-Angeles-lax-a04,ipvanish-US-Los-Angeles-lax-a05,ipvanish-US-Los-Angeles-lax-a06,ipvanish-US-Los-Angeles-lax-a07,ipvanish-US-Los-Angeles-lax-a08,ipvanish-US-Los-Angeles-lax-a09,ipvanish-US-Los-Angeles-lax-a10,ipvanish-US-Los-Angeles-lax-a11,ipvanish-US-Los-Angeles-lax-a12,ipvanish-US-Los-Angeles-lax-a13,ipvanish-US-Los-Angeles-lax-a14,ipvanish-US-Los-Angeles-lax-a15,ipvanish-US-Los-Angeles-lax-a16,ipvanish-US-Los-Angeles-lax-a17,ipvanish-US-Los-Angeles-lax-a18,ipvanish-US-Los-Angeles-lax-a19,ipvanish-US-Los-Angeles-lax-a20,ipvanish-US-Los-Angeles-lax-a21,ipvanish-US-Los-Angeles-lax-a22,ipvanish-US-Los-Angeles-lax-a23,ipvanish-US-Los-Angeles-lax-a24,ipvanish-US-Los-Angeles-lax-a25,ipvanish-US-Los-Angeles-lax-a26,ipvanish-US-Los-Angeles-lax-a27,ipvanish-US-Los-Angeles-lax-a28,ipvanish-US-Los-Angeles-lax-a29,ipvanish-US-Los-Angeles-lax-a30,ipvanish-US-Los-Angeles-lax-a31,ipvanish-US-Los-Angeles-lax-a32,ipvanish-US-Los-Angeles-lax-a33,ipvanish-US-Los-Angeles-lax-a34,ipvanish-US-Los-Angeles-lax-a36,ipvanish-US-Los-Angeles-lax-a38,ipvanish-US-Los-Angeles-lax-a40,ipvanish-US-Miami-mia-a01,ipvanish-US-Miami-mia-a02,ipvanish-US-Miami-mia-a03,ipvanish-US-Miami-mia-a04,ipvanish-US-Miami-mia-a05,ipvanish-US-Miami-mia-a06,ipvanish-US-Miami-mia-a07,ipvanish-US-Miami-mia-a08,ipvanish-US-Miami-mia-a09,ipvanish-US-Miami-mia-a10,ipvanish-US-Miami-mia-a11,ipvanish-US-Miami-mia-a12,ipvanish-US-Miami-mia-a13,ipvanish-US-Miami-mia-a14,ipvanish-US-Miami-mia-a15,ipvanish-US-Miami-mia-a16,ipvanish-US-Miami-mia-a17,ipvanish-US-Miami-mia-a18,ipvanish-US-New-York-nyc-a01,ipvanish-US-New-York-nyc-a02,ipvanish-US-New-York-nyc-a03,ipvanish-US-New-York-nyc-a04,ipvanish-US-New-York-nyc-a05,ipvanish-US-New-York-nyc-a06,ipvanish-US-New-York-nyc-a07,ipvanish-US-New-York-nyc-a08,ipvanish-US-New-York-nyc-a09,ipvanish-US-New-York-nyc-a10,ipvanish-US-New-York-nyc-a11,ipvanish-US-New-York-nyc-a12,ipvanish-US-New-York-nyc-a13,ipvanish-US-New-York-nyc-a14,ipvanish-US-New-York-nyc-a15,ipvanish-US-New-York-nyc-a16,ipvanish-US-New-York-nyc-a17,ipvanish-US-New-York-nyc-a18,ipvanish-US-New-York-nyc-a19,ipvanish-US-New-York-nyc-a20,ipvanish-US-New-York-nyc-a21,ipvanish-US-New-York-nyc-a22,ipvanish-US-New-York-nyc-a23,ipvanish-US-New-York-nyc-a24,ipvanish-US-New-York-nyc-a25,ipvanish-US-New-York-nyc-a26,ipvanish-US-New-York-nyc-a27,ipvanish-US-New-York-nyc-a28,ipvanish-US-New-York-nyc-a29,ipvanish-US-New-York-nyc-a30,ipvanish-US-New-York-nyc-a31,ipvanish-US-New-York-nyc-a32,ipvanish-US-New-York-nyc-a33,ipvanish-US-New-York-nyc-a34,ipvanish-US-New-York-nyc-a35,ipvanish-US-New-York-nyc-a36,ipvanish-US-New-York-nyc-a37,ipvanish-US-New-York-nyc-a38,ipvanish-US-New-York-nyc-a39,ipvanish-US-New-York-nyc-a40,ipvanish-US-New-York-nyc-a41,ipvanish-US-New-York-nyc-a42,ipvanish-US-New-York-nyc-a43,ipvanish-US-Phoenix-phx-a01,ipvanish-US-Phoenix-phx-a02,ipvanish-US-Phoenix-phx-a03,ipvanish-US-Phoenix-phx-a04,ipvanish-US-Phoenix-phx-a05,ipvanish-US-Phoenix-phx-a06,ipvanish-US-Phoenix-phx-a07,ipvanish-US-Phoenix-phx-a08,ipvanish-US-Phoenix-phx-a09,ipvanish-US-Phoenix-phx-a10,ipvanish-US-Phoenix-phx-a11,ipvanish-US-Phoenix-phx-a12,ipvanish-US-Phoenix-phx-a13,ipvanish-US-Phoenix-phx-a14,ipvanish-US-Phoenix-phx-a15,ipvanish-US-Phoenix-phx-a16,ipvanish-US-Phoenix-phx-a17,ipvanish-US-Phoenix-phx-a18,ipvanish-US-Phoenix-phx-a19,ipvanish-US-Phoenix-phx-a20,ipvanish-US-Phoenix-phx-a22,ipvanish-US-Phoenix-phx-a24,ipvanish-US-San-Jose-sjc-a01,ipvanish-US-San-Jose-sjc-a02,ipvanish-US-San-Jose-sjc-a03,ipvanish-US-San-Jose-sjc-a04,ipvanish-US-San-Jose-sjc-a05,ipvanish-US-San-Jose-sjc-a06,ipvanish-US-San-Jose-sjc-a07,ipvanish-US-San-Jose-sjc-a08,ipvanish-US-San-Jose-sjc-a09,ipvanish-US-San-Jose-sjc-a10,ipvanish-US-San-Jose-sjc-a11,ipvanish-US-San-Jose-sjc-a12,ipvanish-US-San-Jose-sjc-a13,ipvanish-US-San-Jose-sjc-a14,ipvanish-US-San-Jose-sjc-a15,ipvanish-US-San-Jose-sjc-a16,ipvanish-US-San-Jose-sjc-a17,ipvanish-US-San-Jose-sjc-a18,ipvanish-US-San-Jose-sjc-a19,ipvanish-US-San-Jose-sjc-a20,ipvanish-US-Seattle-sea-a01,ipvanish-US-Seattle-sea-a02,ipvanish-US-Seattle-sea-a03,ipvanish-US-Seattle-sea-a04,ipvanish-US-Seattle-sea-a05,ipvanish-US-Seattle-sea-a06,ipvanish-US-Seattle-sea-a07,ipvanish-US-Seattle-sea-a08,ipvanish-US-Seattle-sea-a09,ipvanish-US-Seattle-sea-a10,ipvanish-US-Seattle-sea-a11,ipvanish-US-Seattle-sea-a12,ipvanish-US-Seattle-sea-a13,ipvanish-US-Seattle-sea-a14,ipvanish-US-Seattle-sea-a15,ipvanish-US-Seattle-sea-a16,ipvanish-US-Seattle-sea-a17,ipvanish-US-Seattle-sea-a18,ipvanish-US-Seattle-sea-a19,ipvanish-US-Seattle-sea-a20,ipvanish-US-Seattle-sea-a21,ipvanish-US-Seattle-sea-a22,ipvanish-US-Seattle-sea-a23,ipvanish-US-Seattle-sea-a24,ipvanish-US-Seattle-sea-a25,ipvanish-US-Seattle-sea-a26,ipvanish-US-Seattle-sea-a27,ipvanish-US-Seattle-sea-a28,ipvanish-US-Seattle-sea-a29,ipvanish-US-Seattle-sea-a30,ipvanish-US-Seattle-sea-a32,ipvanish-US-Seattle-sea-a33,ipvanish-US-Seattle-sea-a34,ipvanish-US-Seattle-sea-a35,ipvanish-US-Seattle-sea-a36,ipvanish-US-Seattle-sea-a37,ipvanish-US-Seattle-sea-a38,ipvanish-US-Seattle-sea-a39,ipvanish-US-Seattle-sea-a40,ipvanish-US-Seattle-sea-a41,ipvanish-US-Trenton-ttn-a01,ipvanish-US-Trenton-ttn-a02" \
              -e OPENVPN_USERNAME=<REDACTED> \
              -e OPENVPN_PASSWORD="<REDACTED>" \
              -e WEBPROXY_ENABLED=true \
              -e WEBPROXY_PORT=8888 \
              -e LOCAL_NETWORK=<REDACTED> \
              -e TRANSMISSION_RATIO_LIMIT_ENABLED \
              -e TRANSMISSION_RATIO_LIMIT=.1 \
              -e OPENVPN_OPTS="--pull-filter ignore ping --inactive 3600 --ping 10 --ping-exit 60" \
              -e ENABLE_UFW="true" \
              -e UFW_ALLOW_GW_NET="true" \
              -e TRANSMISSION_SPEED_LIMIT_UP \
              -e TRANSMISSION_SPEED_LIMIT_UP_ENABLED \
              -e TRANSMISSION_RATIO_LIMIT \
              -e TRANSMISSION_RATIO_LIMIT_ENABLED \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn`

Am I doing something wrong or is there an error in the startup scripts?

**Comment by s4b3rt0oth** [comment]
I tracked the stated issue from `environment-variables.sh` to the line `export TRANSMISSION_RENAME_PARTIAL_FILES=true` but I'm not quite sure what's wrong with it, or if I'm even troubleshooting down the correct path.
<img width="1374" alt="screen shot 2018-09-23 at 3 47 25 am" src="https://user-images.githubusercontent.com/3665270/45925468-b8146c80-bee3-11e8-9af1-28d4e11b8846.png">

**Comment by haugene** [comment]
The line above it looks more worrying. `TRANSMISSION_RATIO_LIMIT_ENABLED=<no value>`.
But it's according to the env vars you set in your run command. You're setting several of them without providing a value, like `TRANSMISSION_RATIO_LIMIT_ENABLED, TRANSMISSION_SPEED_LIMIT_UP, TRANSMISSION_SPEED_LIMIT_UP_ENABLED, TRANSMISSION_RATIO_LIMIT`. And you're setting `TRANSMISSION_RATIO_LIMIT_ENABLED to blank twice.

Please go through your env vars and don't override the defaults unless you need to. If you're experiencing more issues, go with a basic/minimal setup and add them one by one so you know where the error is coming from. Then raise a new issue if you believe there's a bug in this container.
