### ISSUE TITLE
Set DisableViaHeader in /etc/tinyproxy.conf

### ISSUE THREAD

**Issue by buckmelanoma** [haugene/docker-transmission-openvpn#611]
Tinyproxy seems to be using the default conf file.  One of the defaults is to enable the HTTP_VIA header which sends the following string: "1.1 tinyproxy (tinyproxy/1.8.3)".  This is a problem from a privacy perspective as sites like http://www.whatismyproxy.com/ are then easily able to detect that you're using a proxy:
<img width="858" alt="screen shot 2018-09-29 at 9 11 57 am" src="https://user-images.githubusercontent.com/43704682/46247949-bbb66080-c3c7-11e8-8b6e-d405d0ff8f55.png">

This can be disabled in the conf file with the following:

`DisableViaHeader Yes`

**Comment by buckmelanoma** [comment]
This can be done by adding the following lines to tinyproxy/start.sh:

`  # Disable Via Header for privacy (leaks that you're using a proxy)
  sed -i -e "s/#DisableViaHeader/DisableViaHeader/" ${PROXY_CONF}

  # Lower log level for privacy (writes dns names by default)
  sed -i -e "s/LogLevel Info/LogLevel Critical/" ${PROXY_CONF}`

**Comment by mrjackyliang** [comment]
Looks like an enhancement instead of an issue. Added the proper tags, and closing for now!

**Comment by haugene** [comment]
Re-opening this. Think we should add it, the proxy should be transparent.

**Comment by haugene** [comment]
Committed the proposed changes, tested and it looks to be working as described.
Thanks for the fix @buckmelanoma, later is better than never I guess 😄
