### ISSUE TITLE
Can access webui without setting LOCAL_NETWORK

### ISSUE THREAD

**Issue by andre1974** [haugene/docker-transmission-openvpn#614]
Hello,
i can access the webui without having LOCAL_NETWORK set.
If i check my torrent IP with ipMagnet it says i am connected to a VPN.
Is this normal?

Thanks in advance.

**Comment by andre1974** [comment]
http://192.168.1.140:9091

**Comment by haugene** [comment]
So not a public ip. Is this your host, as in localhost? Or another server?

Or.. Are you running with --net=host maybe?

**Comment by andre1974** [comment]
This is the IP my Openmediavault is running at.
Also Nextcloud and TransmissionOpenVPN.
I have not set any --net anywhere.

**Comment by haugene** [comment]
Hmm. Then what is the ip of your container, and it's ip table routes?
Exec into container and run: `ip addr` and `ip r`

**Comment by andre1974** [comment]
ip addr:

root@OMV:~# docker exec -it transmissionopenvpn ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 70:85:c2:83:bd:9b brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.140/24 brd 192.168.1.255 scope global enp3s0
       valid_lft forever preferred_lft forever
    inet6 fe80::7285:c2ff:fe83:bd9b/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:e9:ec:57:ca brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:e9ff:feec:57ca/64 scope link
       valid_lft forever preferred_lft forever
5: vethf90d63c@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default
    link/ether 82:60:e6:69:f4:a6 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::8060:e6ff:fe69:f4a6/64 scope link
       valid_lft forever preferred_lft forever
7: vethe319d90@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default
    link/ether ae:bc:e9:f3:8e:66 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::acbc:e9ff:fef3:8e66/64 scope link
       valid_lft forever preferred_lft forever
14: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none
    inet 10.0.81.244/24 brd 10.0.81.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fdbf:1d37:bbe0:0:5:1:0:f4/112 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::bf25:6e4a:76c3:2198/64 scope link flags 800
       valid_lft forever preferred_lft forever

ip r:

root@OMV:~# docker exec -it transmissionopenvpn ip r
0.0.0.0/1 via 10.0.81.1 dev tun0
default via 192.168.1.1 dev enp3s0
10.0.81.0/24 dev tun0  proto kernel  scope link  src 10.0.81.244
82.199.134.162 via 192.168.1.1 dev enp3s0
128.0.0.0/1 via 10.0.81.1 dev tun0
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
192.168.1.0/24 dev enp3s0  proto kernel  scope link  src 192.168.1.140

**Comment by haugene** [comment]
Yeah, so that's why. You container has an interface enp3s0 with network 192.168.1.140/24.
Then OpenVPN creates routes for all local networks automatically, not just the docker network.

```
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
192.168.1.0/24 dev enp3s0 proto kernel scope link src 192.168.1.140
```

I don't have a 192.168.x.x interface in my container, and therefore only get the 172.17 route, and need to add the other manually through LOCAL_NETWORK variable. Exactly why this interface is mounted to your container, I don't know. But that's why you can access it.

**Comment by andre1974** [comment]
Ok. So it is safe for me?
VPN working correctly?

**Comment by andre1974** [comment]
After i changed the container to bridge mode i get this.

root@OMV:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none
    inet 10.0.80.242/24 brd 10.0.80.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fdbf:1d37:bbe0:0:5::f2/112 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::4b4b:acba:e127:1381/64 scope link flags 800
       valid_lft forever preferred_lft forever
31: eth0@if32: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.4/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:4/64 scope link
       valid_lft forever preferred_lft forever

root@OMV:/# ip r
0.0.0.0/1 via 10.0.80.1 dev tun0
default via 172.17.0.1 dev eth0
10.0.80.0/24 dev tun0  proto kernel  scope link  src 10.0.80.242
82.199.134.162 via 172.17.0.1 dev eth0
128.0.0.0/1 via 10.0.80.1 dev tun0
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.4
192.168.1.0/24 via 172.17.0.1 dev eth0

Looks better?!

**Comment by haugene** [comment]
Yeah, I guess. But you're still running `root@OMV:/# docker exec -it transmissionopenvpn ip r`? Or is this on the host?

The routes looks good to me. The 0.0.0.0/1 is will still get most of the traffic and send it through the tunnel. Then you have the 10.0.80.0/24 which seems to be the network for your vpn server. Apart from that theres a docker internal network route and the rest looks good.

Check your torrent IP: http://checkmyip.torrentprivacy.com/
Then curl your ip from another service like: https://ipecho.net/plain

Do that inside and outside the container and you'll know if the VPN is working. I'm still not sure enough about iptables routing to give you an absolute answer, and this is not an issue with the image. If you read up, post to other networking forums and figure that there's something wrong - then open a new issue.

I've been playing with this on my Mac, and I also can connect to the container without setting the LOCAL_NETWORK variable, but it seems that Docker for mac is doing some magic with VPN passthrough: https://docs.docker.com/docker-for-mac/networking/

So this is up to your platform and how Docker is run and much more - so it's not easy to say something definite. Closing this now.
