### ISSUE TITLE
Allow hostnames in LOCAL_NETWORK

### ISSUE THREAD

**Issue by rcdailey** [haugene/docker-transmission-openvpn#631]
When using transmission in a docker network, it gets assigned a special subnet. Something like `172.30.0.0/16`. This is customizable. Traefik serving as a reverse proxy frontend is not able to access port 9091 through the UFW since it's not specified on the local network. Since otherwise configured, the docker network subnet is unknown at configuration time, it would be great to specify the hostname of traefik in the list for `LOCAL_NETWORK`. Example from `docker-compose.yml`:

```
environment:
  LOCAL_NETWORK: 192.168.1.0/24,traefik
```

And `traefik` comes from the defined hostname for the container running traefik:

```
services:
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
```

Right now logs show:

```
adding route to local network 192.168.1.0/24 via 172.31.0.1 dev eth0
adding route to local network traefik via 172.31.0.1 dev eth0
Error: ??? prefix is expected rather than "traefik".
```

I think that if a non-IP is detected in this list, the entry point script should instead run a command to get the IP address of that host (maybe `nslookup`?) and use that IP in the whitelist. This will give me the ability to allow only the IP address of the traefik server on the docker network to access through the firewall.

**Comment by rcdailey** [comment]
I assumed UFW since I didn't explicitly see a log showing the right IP was allowed. The part that makes it difficult is that Docker assigns the IPs and I'm not sure if there's a specific subnet mask I can use that would capture all the possible variations.

I'm sure there's a lot of other solutions, but based on my limited knowledge of how this stuff works, I made the best suggestion I could. Open to other solutions you feel are better.

I'll go ahead and close this since you've already (very strongly) expressed your disinterest in this change.

**Comment by haugene** [comment]
Yeah, sorry about that. Didn't mean to be too snappy, but there's just so many Docker-related issues that is not related to this container... I see it could be handy in your case, but it's too network specific and the idea of Docker is to separate concerns - and this is not a containers responsibility. But I get that many aren't that familiar with Docker.

Anyways. You can specify the subnet when you create a Docker network:
https://docs.docker.com/engine/reference/commandline/network_create/

So if you first create a network, and then start traefik with --net <your-network>, then you should know the CIDR specs that can be passed to the openvpn container.

**Comment by rcdailey** [comment]
You're absolutely right on the separation of concerns. Nothing to dispute there. Just a bad idea on my part. I like your idea of explicitly specifying the subnet. I'm not aware of any negative side effects of doing that, and assuming there are none that are Docker-related, it'll probably be the solution I pick. Thanks again for your feedback.
