### ISSUE TITLE
Inconsistent case-sensitivity in provider naming

### ISSUE THREAD

**Issue by makloda** [haugene/docker-transmission-openvpn#632]
I am testing "PIA" as a VPN provider because it appears to be the only one which reliably can open a peering port using an API. During testing I encountered the following issue with port updating:

1. I mistakenly set the wrong case using  `-e "OPENVPN_PROVIDER=pia" ` (note the lower case "pia")
2. The container connected correctly using my username and password to the desired VPN location. However, the startup log complained `"NO PORT UPDATER FOR THIS PROVIDER".` 
3. Inspecting /etc/transmission/start.sh: `if [ "$OPENVPN_PROVIDER" = "PIA" ]` is a case-sensitive if clause. The start.sh script in /etc/openvpn/start.sh however is NOT case-sensitive: it establishes the VPN connection to PIA correctly even when using the lower-case `-e "OPENVPN_PROVIDER=pia" `
4. Suggestion: 
a. Either both `=pia` and `=PIA` should work for both establishing the openvpn connection and the transmission port update
_OR_
b. An error should be thrown designating the lower-case `pia` as an unknown provider

Regarding 4 a)
A way to disregard case in shell scripts is piping it to `grep -iq`, e.g.  `if echo pIA | grep -iq PIA ; then echo Provider PIA detected; fi`

So changing
```
if [ "$OPENVPN_PROVIDER" = "PIA" ]
```
to
```
if echo $OPENVPN_PROVIDER | grep -iq PIA
```
in /etc/transmission/start.sh should eliminate this minor issue.

**Comment by haugene** [comment]
Added it and just tested with "OPENVPN_PROVIDER=pia" and the port forwarder started. Should be good 👍
