### ISSUE TITLE
Is it possible to define other directory for downloaded torrents

### ISSUE THREAD

**Issue by JoeTN** [haugene/docker-transmission-openvpn#635]
I really like your great work with this docker image, thank you!

Is it possible to define another directory for the location of the downloaded torrents?
I am storing my config in one place (/share/ContainerStation/transmission/data/) and would like to store the downloaded torrents in another place (/share/Medier/Downloads/)

I tried doing like this, in my Docker-compose, but it does not work - as stated I am unsure whether or not this is possible.
volumes:
    - /share/ContainerStation/transmission/data/:/data
    - /share/Medier/Downloads/:/data/transmission-home/torrents

Thanks in advance

Regards
Joe

**Comment by haugene** [comment]
You can change all the Transmission settings through environment variables, and their defaults are listed in the [Dockerfile](https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile)

I would guess that changing the `TRANSMISSION_DOWNLOAD_DIR, TRANSMISSION_INCOMPLETE_DIR, TRANSMISSION_WATCH_DIR` variables would do it.

I don't think you want to mount volumes into other docekr volumes, like the mounts you describe on /data and /data/transmission-home. But mount different root folders or areas under /home and then change the paramters of Transmission. If you search for /data in the Dockerfile, you see where Transmission is instructed to use that directory.

**Comment by JoeTN** [comment]
Thanks for quick response. I ended up doing it like this:
volumes:
    - /share/ContainerStation/transmission/:/data
    - /share/Medier/Downloads/:/downloads

environment:
    - TRANSMISSION_DOWNLOAD_DIR=/downloads

**Comment by nsar1907** [comment]
i wanna thank you so much for all those,

is it possible to creat more download folders than only one ?

i wanna separate the downloaded files

as

/downloads
/downloads/movies
/donwloads/tvseries

is it possible ?

**Comment by S3BSama** [comment]
> i wanna thank you so much for all those,
> 
> is it possible to creat more download folders than only one ?
> 
> i wanna separate the downloaded files
> 
> as
> 
> /downloads
> /downloads/movies
> /donwloads/tvseries
> 
> is it possible ?

Yes you can. Just type the path that you want when you add your torrent or when you move an existing one. The path needs to be under /downloads though.
It will then appears in the available list of paths after that.
