### ISSUE TITLE
Authenticate/Decrypt packet error

### ISSUE THREAD

**Issue by gjulien69** [haugene/docker-transmission-openvpn#65]
Hello,
I come to you because I have a problem I have this message that appears.

Tue Apr 19 12:35:57 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #19046837 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with -
-mute-replay-warnings

The download does well but apparently this is the upload does not work .

Did message says something to you ?

thank you in advance for your help.

Best regards.

sorry for my english, i'm french

**Comment by haugene** [comment]
It is normal that this message appears sometimes. If your logs are flooded with it something might be wrong, but apart from that it's ok. There will be some packet errors.

Sounds like stuff is working. You're downloading OK? What do you mean upload does not work? Keep in mind that unless your provider says otherwise you're probably behind a closed port (without port forwarding) and this might impact your seeding...

**Comment by gjulien69** [comment]
Good evening,
thanks for your return.
The error message appears constantly with a suite number .

Wed Apr 20 18:13:24 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #4750554 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --
mute-replay-warnings                                                                                                                                                                                                 
Wed Apr 20 18:13:24 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #4750555 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --
mute-replay-warnings                                                                                                                                                                                                 
Wed Apr 20 18:13:24 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #4750556 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --
mute-replay-warnings                                                                                                                                                                                                 
Wed Apr 20 18:13:24 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #4750560 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --
mute-replay-warnings                                                                                                                                                                                                 
Wed Apr 20 18:13:24 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #4750561 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --
mute-replay-warnings 

The download works correctly , the upload does not work.

Listening Port 51413 is blocked .

my vpn provider is IPVanish .

is what we are already back problem with IPVanish .

thank you for your help.

Best regards,

**Comment by haugene** [comment]
So you get a lot of warnings. Maybe try to change VPN server? Have you tried a different config? 
That being said, I don't think this is the reason for your upload not working.

Your port will be closed if your provider don't have a way for you to forward ports through your VPN interface public ip. This will make it harder for you to seed a torrent as you're not discoverable. 

But if you download a new torrent, with lots of traffic and few seeds you should see upload traffic as well. Are you saying you have 0 uploaded on all your torrents?

**Comment by bertybassett** [comment]
Im getting these logs too about 100 an hour? on PIA should I retry a different server?

**Comment by haugene** [comment]
Nah, it's no problem. Millions of packets run through there, doesn't matter if you get some errors. They'll be retransmitted anyways. I'm considering muting those warnings...

**Comment by gjulien69** [comment]
for my part I use ipvansh is with this supplier that I have all that is wrong. Apparently I 'm not the only one with this problem is that ca be that the port 51413 is blocked.
in the file download works well but not upload

**Comment by haugene** [comment]
Yup. As long as you're behind a NAT, to get an open port it needs to be forwarded to you.

**Comment by MindTooth** [comment]
Just hit by this my self.  And I must ask, can this spam cause the container du crash?  After a nights sleep, I find the container not forwarded?
