### ISSUE TITLE
Not accepting NordVPN password with special characters

### ISSUE THREAD

**Issue by noah2121** [haugene/docker-transmission-openvpn#650]
I'm getting this error:

`ERROR: Invalid interpolation format for "environment" option in service "transmission-vpn": "OPENVPN_PASSWORD=[redacted but it has special characters like $, *, and #]"`

I'm running on Ubuntu Server 18.04 on docker.

**Comment by haugene** [comment]
Yeah. It's a known limitation. #245 
Should be fixed, but then there's finding the time. Up for having a look?

**Comment by haugene** [comment]
Closing this in favour for #245
