### ISSUE TITLE
if [ "$GLOBAL_APPLY_PERMISSIONS" = true ]

### ISSUE THREAD

**Issue by celeroll** [haugene/docker-transmission-openvpn#652]
I think in userSetup.sh this line 
if [ "$GLOBAL_APPLY_PERMISSIONS" = true ] 
should be 
if [ "$GLOBAL_APPLY_PERMISSIONS" = **"true"** ]

or even 
if [ **!** "$GLOBAL_APPLY_PERMISSIONS" = **"true"** ]

**Comment by tlc** [comment]
This is why I'm seeing this on my host, even when GLOBAL_APPLY_PERMISSIONS is set.

```
$ ls -lsn
total 10
1 drwxr-xr-x 2    0    0 2 Dec  6 18:25 completed/
1 drwxr-xr-x 2    0    0 2 Dec  6 18:25 incomplete/
9 drwxr-xr-x 5 1000 1000 7 Dec  6 18:25 transmission-home/
1 drwxr-xr-x 2    0    0 2 Dec  6 18:25 watch/
```

**Comment by tlc** [comment]
Actually, I think that's valid sh.  But _something_ seems to stop that chmod from being run because I see this on the host even when GLOBAL_APPLY_PERMISSIONS is set.

```
$ ls -lsn
total 10
1 drwxr-xr-x 2    0    0 2 Dec  6 18:25 completed/
1 drwxr-xr-x 2    0    0 2 Dec  6 18:25 incomplete/
9 drwxr-xr-x 5 1000 1000 7 Dec  6 18:25 transmission-home/
1 drwxr-xr-x 2    0    0 2 Dec  6 18:25 watch/
```

Perhaps it needs to be in `environment-variables.tmpl` like all the other env vars?

**Comment by tlc** [comment]
See https://github.com/haugene/docker-transmission-openvpn/pull/657

**Comment by haugene** [comment]
Merged to dev. Can you confirm it's working properly on the dev tag @celeroll?

**Comment by haugene** [comment]
This is now merged to master. Re-open if it's still an issue, but considering it fixed for now.
