### ISSUE TITLE
Torguard has stopped working

### ISSUE THREAD

**Issue by derekoharrow** [haugene/docker-transmission-openvpn#653]
I've had Torguard configured and working fine for several months now. This week it's suddenly stopped working, and I can't see why.
I've tried connecting to Torguard separately using my android phone and that works just fine.
I've also tried connecting using Newshosting instead of Torguard and that works fine.

This is the contents of the log:
```
transmission-vpn    | Using OpenVPN provider: TORGUARD
transmission-vpn    | Starting OpenVPN using config Sweden.Stockholm.ovpn
transmission-vpn    | Setting OPENVPN credentials...
transmission-vpn    | adding route to local network 192.168.1.0/24 via 172.24.0.1 dev eth0
transmission-vpn    | Sun Dec  2 17:03:15 2018 WARNING: file '/etc/openvpn/torguard/ta.key' is group or others accessible
transmission-vpn    | Sun Dec  2 17:03:15 2018 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 24 2018
transmission-vpn    | Sun Dec  2 17:03:15 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
transmission-vpn    | Sun Dec  2 17:03:15 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission-vpn    | Sun Dec  2 17:03:15 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]46.246.29.158:1912
transmission-vpn    | Sun Dec  2 17:03:15 2018 UDP link local: (not bound)
transmission-vpn    | Sun Dec  2 17:03:15 2018 UDP link remote: [AF_INET]46.246.29.158:1912
```

Any ideas?

**Comment by haugene** [comment]
Hi, and sorry about the late reply. It could be that the configs have been updated. Have you tried some of the other configs? Or could you check with torguard if they've updated the ovpn files lately? If you can provide a link to a .zip file or similar containing all configs I can update them.

**Comment by haugene** [comment]
Updated configs and pushed to dev. Use the dev tag for now and re-open this issue if the problem still persists
