### ISSUE TITLE
gotMetadataFromURL: http error 0: No Response

### ISSUE THREAD

**Issue by mrjackyliang** [haugene/docker-transmission-openvpn#654]
I'm getting this error from many public APIs when I directly add the torrent links. Not sure has anyone got this error? If this is Transmission specific or an API issue.

**Comment by haugene** [comment]
Just to be sure. This is when using magnetic links to add torrents, right?

**Comment by mrjackyliang** [comment]
I found out it was an internal networking issue. Transmission could not communicate with Jackett, which was what I was using.
