### ISSUE TITLE
NordVPN API integration

### ISSUE THREAD

**Issue by niXta1** [haugene/docker-transmission-openvpn#655]
I'd love to see the NordVPN API integrated like here: https://github.com/azinchen/nordvpn

**Comment by tomhumphrey** [comment]
Would love to see this implemented as well

**Comment by haugene** [comment]
Anyone tested this?

**Comment by haugene** [comment]
This seems to be quite stable now. Thanks again to @Troubadoure for implementing this feature. Closing.
