### ISSUE TITLE
GhostPath VPN integration  ?

### ISSUE THREAD

**Issue by psppro26** [haugene/docker-transmission-openvpn#658]
Im with ghostpath vpn , i tried to set it with custom vpn , seems to work i get connected but in torrent i have like 1peer and very slow download ? There is something to do ? like open a port or something ?
Here is a example of server , i just added the => auth-user-pass /config/openvpn-credentials.txt

# host/port of vpn server
remote cdg1.gpvpn.com 443 udp

# prompt for authentication
auth-user-pass /config/openvpn-credentials.txt

# equivalent to pull, tls-client
client

# redirect all outgoing traffic to the vpn gateway
redirect-gateway

# verify the server certificate for authenticity
remote-cert-tls server

cipher AES-256-CBC

proto udp
dev tun
keepalive 10 120
nobind

persist-key
persist-tun

# ssl certificate / key used for tls
#ca certs/ca.crt

**Comment by haugene** [comment]
Closing this now. You could try a months subscription with PIA to see if it's better with an open port.
DL without open port gives lower speeds, but shouldn't be any different in a container than on the regular client afaik.

Re-open if you have any questions or updates to this.
