### ISSUE TITLE
how to access transmission from the internet

### ISSUE THREAD

**Issue by bertybassett** [haugene/docker-transmission-openvpn#66]
First off top marks for one of the best dockers images and guides that I have come across, I had this setup on my Sinology within a few hours and everything just worked.

one tiny change with DMS 6 I had to use 

`docker run --name TransmissionVPN  --privileged -d -v /volume1/DockerVPN/resolv.conf:/etc/resolv.conf -v /volume1/DockerVPN/:/data -e "OPENVPN_PROVIDER=PIA" -e "OPENVPN_CONFIG=Netherlands" -e "OPENVPN_USERNAME=p111111111" -e "OPENVPN_PASSWORD=whatever" -p 9091:9091 haugene/transmission-openvpn`

Putting `--name TransmissionVPN` at the end of the command failed.

The Docker image is using a PIA VPN'ed IP address within the subnet range of 40.0.0.0/8 and the NAS is using an ISP IP address within the subnet range of 101.0.0.0/8 .  The strange bit is that I can get to transmission from my Mac without any proxy/NGINX, just using 192.168.0.22:9010 the NAS's local lan IP  address.  I have even tested using http://ipmagnet.services.cbcdn.com to prove my bittorents are going out over the VPN and they do.  Bit confused why I do not need NGINX but hay its working as expected

Now my question is this. 
So how do I access the Transmission web client from my iPhone when not on Wi-Fi but over the mobile signal LTE/3G?  DDNS would be one option any more ideas?

**Comment by haugene** [comment]
Thanks ;) Glad to hear it was a smooth setup! But you're right. Name cannot go at the end. Also the guide says -name, while it should be --name. I'll fix it sometime, but it's not a showstopper :)

Hmm, must agree it sounds strange that you can connect directly. Can you do a "docker exec TransmissionVPN ifconfig" just to make sure the eth0 is on docker subnet? And I assume your mac is on the 192.168.0.0/24 as well? So the NAS has two interfaces? Which one of them is docker bridged against? You can choose a local IP address to bind the container port to using -p. Maybe it's bound to the ISP interface, and when you connect through the local network your traffic is routed through some local bridge that is effect serves as a proxy? Don't know, but you'll need to check your iptables setup in the container as well as on all your interfaces at the host.

If you want to access it from outside your network, you must either configure a way to VPN into your local network or forward the port in your router.  And as you say, use DDNS to keep track of your IP. I'm doing port forwarding with DDNS. If you need a free one, you can try duckdns.

**Comment by bertybassett** [comment]
On my iPhone is browse to my NAS's DDNS of myname.NO-IP.ORG:9010 I get transmission.  I just had to do the firewall port forward I was being a dummy.  P.S. Do not tell my boss because I am suppose to be a network and firewall engineer by trade, lol.  

All I can say for the not needing NGINX is so strange routing must be going on between the Sinology and the Docker image.  Will look into it

**Comment by haugene** [comment]
Haha :+1:
Cool. Let me know if you figure it out.

I'm guessing it's a typo, but your docker run command is for port 9091, but you keep writing 9010 for your Webui. Is there some address translation going on there?

**Comment by bertybassett** [comment]
yeah dyslexia, its a right bitch.

**Comment by haugene** [comment]
Np! Closing this then.

**Comment by bertybassett** [comment]
from NAS SSH

sudo route -n

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG    0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.0.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
