### ISSUE TITLE
VPN Facile

### ISSUE THREAD

**Issue by yannickminne** [haugene/docker-transmission-openvpn#664]
hi

Can you add all vpnfacile configurations ? 
More info : https://vpnfacile.net/

Thanks

**Comment by haugene** [comment]
Just added the configs. Running it locally gives me AUTH_FAILED which usually means that it's good to go as long as valid credentials are added.

It will be available on the dev tag shortly (although the hub has build slow lately).
Use OPENVPN_PROVIDER=VPNFACILE and OPENVPN_CONFIG as one of the configs in [this list](https://github.com/haugene/docker-transmission-openvpn/tree/dev/openvpn/vpnfacile) (minus .ovpn at the end)

You can see when the build is ready here: https://hub.docker.com/r/haugene/transmission-openvpn/builds/

**Comment by yannickminne** [comment]
Hi, 
Thanks for job, it work.
