### ISSUE TITLE
Run the container without the VPN

### ISSUE THREAD

**Issue by niXta1** [haugene/docker-transmission-openvpn#666]
This question has been up before. 
But now I agree that there should be a way to disable the VPN part. Because even if I use another VPN docker ([azinchen/nordvpn](https://github.com/azinchen/nordvpn), zero maintenance, and 100% servers availability), I would still like to use this.
There are other transmission dockers, but none of them are as good as this. For example, the included transmission-web-control.

Alternatively, this approach can be integrated into this: [#655](https://github.com/haugene/docker-transmission-openvpn/issues/655)
But that is much more work.

**Comment by haugene** [comment]
Making vpn optional is a bigger rewrite no matter how we do it, but the holidays are coming up so it might be a good time to do it. Would be nice if more people have time to contribute to the rewrite and/or testing. And this would be a breaking change, so I propose a 3.0-beta tag for a while.

First we should discuss how we want this to work, and if we should separate transmission entirely (also tinyproxy?). Although it seems that having them bundled is what most people want.

It's also a hassle to keep ovpn configs up to date. If all providers had a good and reliable URL to fetch them from we could do it build time. But I'm concerned that dynamically downloading 40 zip files will fail of networking reasons too often.

**Comment by edgd1er** [comment]
Could it be a good idea not to provide vpn files but have an empty ovpn folder and download based on OPENVPN_PROVIDER value (well, for vpn provider that have a download conf url )? at reboot could be a good moment to update files ? emptying the folder would force a new download.

as for a disable vpn switch, the question is why use another openvpn image  ? what is missing/incorrect in yours, avantage, disavantage ? what could be changed ? for the moment, I'm very happy with your container using nordvpn, but I don't have a 24/24 7/7 usage.
For what I have understood, you would have an image for tinyproxy, one for transmission (yours) and one for openvpn (yours or another). everything would be tied through a docker-compose ?

**Comment by niXta1** [comment]
The nordvpn container above works fine, I dont think downloading ovpn files on demand should be a problem.

I just use —network=”container:vpn” to connect.

**Comment by haugene** [comment]
Marking this as a "won't fix" for now. I think it's a cool idea and could be useful exactly for those scenarios, but it's outside the scope at least for me to make the improvement.

**Comment by dev-ddoe** [comment]
I know this issue is closed, but I was facing the same issue. I just to share my solution somewhere.
On my side it was possible using the following code change:
`diff --git a/openvpn/start.sh b/openvpn/start.sh
index 38cd9515f..bfef59765 100755
--- a/openvpn/start.sh
+++ b/openvpn/start.sh
@@ -11,8 +11,10 @@ if [[ "${CREATE_TUN_DEVICE,,}" == "true" ]]; then
 fi
 
 if [[ "${OPENVPN_PROVIDER}" == "**None**" ]] || [[ -z "${OPENVPN_PROVIDER-}" ]]; then
-  echo "OpenVPN provider not set. Exiting."
-  exit 1
+  # Hack to not use th vpn
+  dockerize -template /etc/transmission/environment-variables.tmpl:/etc/transmission/environment-variables.sh
+  /etc/openvpn/tunnelUp.sh x x x 0.0.0.0
+  sleep infinity
 elif [[ ! -d "${VPN_PROVIDER_CONFIGS}" ]]; then
   echo "Could not find OpenVPN provider: ${OPENVPN_PROVIDER}"
   echo "Please check your settings."
`

**Comment by jpdsceu** [comment]
> I know this issue is closed, but I was facing the same issue. I just to share my solution somewhere.
> On my side it was possible using the following code change:
> 
> ```diff
> index 38cd9515f..bfef59765 100755
> --- a/openvpn/start.sh
> +++ b/openvpn/start.sh
> @@ -11,8 +11,10 @@ if [[ "${CREATE_TUN_DEVICE,,}" == "true" ]]; then
>  fi
>  
>  if [[ "${OPENVPN_PROVIDER}" == "**None**" ]] || [[ -z "${OPENVPN_PROVIDER-}" ]]; then
> -  echo "OpenVPN provider not set. Exiting."
> -  exit 1
> +  # Hack to not use th vpn
> +  dockerize -template /etc/transmission/environment-variables.tmpl:/etc/transmission/environment-variables.sh
> +  /etc/openvpn/tunnelUp.sh x x x 0.0.0.0
> +  sleep infinity
>  elif [[ ! -d "${VPN_PROVIDER_CONFIGS}" ]]; then
>    echo "Could not find OpenVPN provider: ${OPENVPN_PROVIDER}"
>    echo "Please check your settings."
> ```

Do you have more information on where you changed this part? I am facing the same issue here but it seems like the source code has changed.

**Comment by haugene** [comment]
Hmmm @jpdsceu. We could have a look at a simple way of doing this to get the core functions of Transmission with the bundled web frontends etc. But I'm a bit hesitant of making this even close to some officially supported mode of running, as every new feature causes complexity and backward compatability issues.

If you try something like this:
```
docker run -e PEER_DNS=no -p 9091:9091 \
  haugene/transmission-openvpn \
  bash -c "echo sleep infinity >> /etc/transmission/start.sh && exec dumb-init /etc/transmission/start.sh x x x 0.0.0.0"
```

How far does that get you? I'm guessing something isn't working like it should, but I see that the bundled UIs load using:
```
docker run -e PEER_DNS=no -e TRANSMISSION_WEB_UI=flood -p 9091:9091 \
  haugene/transmission-openvpn \
  bash -c "echo sleep infinity >> /etc/transmission/start.sh && exec dumb-init /etc/transmission/start.sh x x x 0.0.0.0"
```

I'll re-open this for some fiddling. But no promises. And @mention me when you respond here. There's a lot of notifications.

**Comment by ksurl** [comment]
You can use the image as is by overriding the entry point with your own script mounted to the container. It would just be self supported for any breaking changes in future updates

**Comment by jmarshallpresnell** [comment]
I definitely do think this needs a closer look. The philosophy of good (and composable) development is that one program do one thing very well. This can be expanded to one container does one thing very well.

The effort expended to decouple transmission from the VPN side of things will ultimately reduce your workload and increase your VPN provider options, as you can reference several exceptional docker VPN containers (I personally use qmcgaw/gluetun) and simply use that container to manage the VPN and use other containers to manage solely what they are good at. All it takes is a network_mode: "container:gluetun" in my other containers and poof!, instant VPN support - and not just one VPN, but quite a few.

I think I will take a hack at this as well, if you don't mind. Having a reliable and single-function transmission daemon/UI in an isolated and composable docker container sounds like a cool Christmas project! :)
