### ISSUE TITLE
updatePort.sh ignores TRANSMISSION_RPC_URL value

### ISSUE THREAD

**Issue by gwenl** [haugene/docker-transmission-openvpn#669]
Having modified TRANSMISSION_RPC_URL from its default value, updatePort.sh fails with the following errors:
```Dec 19 20:38:39 sync docker[32397]: transmission auth not required
Dec 19 20:38:39 sync docker[32397]: Unexpected response: <h1>301: Moved Permanently</h1>pplication/x-www-form-urlencoded
Dec 19 20:38:39 sync docker[32397]: Update UFW rules before changing port in Transmission
Dec 19 20:38:39 sync docker[32397]: denying access to
Dec 19 20:38:39 sync docker[32397]: ERROR: Bad port
Dec 19 20:38:39 sync docker[32397]: allowing 49548 through the firewall
Dec 19 20:38:39 sync docker[32397]: Rule added
Dec 19 20:38:39 sync docker[32397]: Unexpected response: <h1>301: Moved Permanently</h1>pplication/x-www-form-urlencoded
Dec 19 20:38:39 sync docker[32397]: Checking port...
Dec 19 20:38:49 sync docker[32397]: Unexpected response: <h1>301: Moved Permanently</h1>pplication/x-www-form-urlencoded
```

It seems updatePort.sh assumes the default RPC URL (/transmission) is always used, for instance in the following line:
```transmission-remote $myauth -p "$new_port"```

although the transmission-remote command can be given a non-default URL:

```transmission-remote [http(s?)://host:port/transmission/] [options]```

**Comment by haugene** [comment]
Yep. Good catch, we're assuming the default value. I'll gladly accept a PR - but I'm not sure when I'll come around to fixing this.
