### ISSUE TITLE
Sickbeard and CouchPotota download issues

### ISSUE THREAD

**Issue by bertybassett** [haugene/docker-transmission-openvpn#67]
The Transmission Docker image is set  to \data\download aka \volume1\DockerVPN\download

This works for torrents that I manually added via the transmission web client. 

Sickbeard and CouchPotota are set to download using transmission mode, not using a watch folder. Here are the links I sent up to tell them to where to download to 

\volume1\DockerVPN\download\TV
\volume1\DockerVPN\download\Movies

The downloads snatch and appear in transmission  and appear to download ok but the files never physically appear anywhere on the NAS or docker image. 

Everything is 777 permission why I manually ran Chmod 777 -R on 

\volume1\DockerVPN\

If I set Sickbeard and CouchPotato's download location to blank and let transmission decide where to download to then it will works fine. 

I think this has something to do with the Docker image using \data\download and not \volume1\DockerVPN\download. I think Sickbeard is passing over the full link and transmission is like what is that? I need the docker shortcut style link instead. 

Any ideas?

P.S I cannot use the watch folder aka black hole option because transmission does not support multiple watch folders.

**Comment by bertybassett** [comment]
Pretty sure this is nothing to do with Sickbeard or CouchPotato and I've set them up on the NAS and it works as expected.

**Comment by haugene** [comment]
Hey. You could make the paths look the same inside the container. If you add another volume mount like -v \volume1\DockerVPN\download:\volume1\DockerVPN\download then it will exist on the same path inside and outside the container.

You still need to mount the /data volume of the container if you want transmission to have persistant state. You can use the environment variables to override watch, completed and incomplete dirs as you need them to be.

**Comment by bertybassett** [comment]
What a good idea once again thanks Tom

**Comment by bertybassett** [comment]
docker run --name TransmissionVPN --privileged -d 

-v /volume1/DockVPN/resolv.conf:/etc/resolv.conf 

-v /volume1/DockVPN/:/data 

-v /volume1/bittorent/:/volume1/bittorrent 

-e "OPENVPN_PROVIDER=PIA" -e "OPENVPN_CONFIG=Netherlands" -e "OPENVPN_USERNAME= 1111111" -e "OPENVPN_PASSWORD= 22222222" -p 9091:9091 haugene/transmission-openvpn


this worked for me 

@jaysonsantos 

-v /volume1/bittorent/:/volume1/bittorrent                    for you would = /ovm/where/you/save/to: //ovm/where/you/save/

**Comment by bertybassett** [comment]
this can be closed now thanks for you help.

**Comment by haugene** [comment]
:+1: Np!
