### ISSUE TITLE
Transmission GUI Showing But Not Visually Active

### ISSUE THREAD

**Issue by bmoneruiux** [haugene/docker-transmission-openvpn#670]
I'm using this container on the Docker app on my Synology DS918+

Had this running very smoothly for months, but then decided to change my folder structure, and everything went downhill from there. At first I couldn't access the webUI, but the downloads were still working at least. Now the downloads aren't working, and I still can't access the webUI and I'm getting "Safari Can’t Connect to the Server".

I'm at a severe loss at what to do, and definitely need some guidance

Connection Settings:

- Router: 10.0.1.1
- NAS: 10.0.1.37
- Client (PC): 10.0.1.138
- URL: http://10.0.1.37:9091/transmission/web/

Docker App Settings:

- Port Settings
  - Port 1: 8888
  - Port 2: 9091
- Volume
  - docker/transVPN => /config
  - docker/transVPN/resolv.conf => /etc/resolv.conf
  - Downloads/torrents => /data
  - Downloads/torrents/watch => /watch
- Environment Variables
  - OPENVPN_USERNAME => ****
  - OPENVPN_PASSWORD => ****
  - OPENVPN_PROVIDER => NORDVPN
  - TZ => America/Detroit
  - LOCAL_NETWORK => 10.0.1.0/24
  - TRANSMISSION_HOME => /config/transmission-home
  - PUID => ****
  - PGID => ***
  - TRANSMISSION_DOWNLOAD_DIR => /data/completed
  - TRANSMISSION_INCOMPLETE_DIR => /data/incomplete
  - TRANSMISSION_WATCH_DIR => /data/watch

**Comment by bmoneruiux** [comment]
Here's the JSON dump of my container settings. If more is needed, let me know:

`{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "dumb-init /etc/openvpn/start.sh",
   "cpu_priority" : 50,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : true,
   "env_variables" : [
      {
         "key" : "OPENVPN_CONFIG",
         "value" : ""
      },
      {
         "key" : "TZ",
         "value" : "America/Detroit"
      },
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "OPENVPN_USERNAME",
         "value" : "myUsername"
      },
      {
         "key" : "OPENVPN_PASSWORD",
         "value" : "myPassword"
      },
      {
         "key" : "OPENVPN_PROVIDER",
         "value" : "NORDVPN"
      },
      {
         "key" : "GLOBAL_APPLY_PERMISSIONS",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_DOWN",
         "value" : "50"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_BEGIN",
         "value" : "540"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_DAY",
         "value" : "127"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_END",
         "value" : "1020"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_UP",
         "value" : "50"
      },
      {
         "key" : "TRANSMISSION_BIND_ADDRESS_IPV4",
         "value" : "0.0.0.0"
      },
      {
         "key" : "TRANSMISSION_BIND_ADDRESS_IPV6",
         "value" : "::"
      },
      {
         "key" : "TRANSMISSION_BLOCKLIST_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_BLOCKLIST_URL",
         "value" : "http://www.example.com/blocklist"
      },
      {
         "key" : "TRANSMISSION_CACHE_SIZE_MB",
         "value" : "4"
      },
      {
         "key" : "TRANSMISSION_DHT_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_DIR",
         "value" : "/data/completed"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_LIMIT",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_LIMIT_ENABLED",
         "value" : "0"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_QUEUE_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_QUEUE_SIZE",
         "value" : "5"
      },
      {
         "key" : "TRANSMISSION_ENCRYPTION",
         "value" : "1"
      },
      {
         "key" : "TRANSMISSION_IDLE_SEEDING_LIMIT",
         "value" : "30"
      },
      {
         "key" : "TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_INCOMPLETE_DIR",
         "value" : "/data/incomplete"
      },
      {
         "key" : "TRANSMISSION_INCOMPLETE_DIR_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_LPD_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_MAX_PEERS_GLOBAL",
         "value" : "200"
      },
      {
         "key" : "TRANSMISSION_MESSAGE_LEVEL",
         "value" : "2"
      },
      {
         "key" : "TRANSMISSION_PEER_CONGESTION_ALGORITHM",
         "value" : ""
      },
      {
         "key" : "TRANSMISSION_PEER_ID_TTL_HOURS",
         "value" : "6"
      },
      {
         "key" : "TRANSMISSION_PEER_LIMIT_GLOBAL",
         "value" : "200"
      },
      {
         "key" : "TRANSMISSION_PEER_LIMIT_PER_TORRENT",
         "value" : "50"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT",
         "value" : "51413"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT_RANDOM_HIGH",
         "value" : "65535"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT_RANDOM_LOW",
         "value" : "49152"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT_RANDOM_ON_START",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_PEER_SOCKET_TOS",
         "value" : "default"
      },
      {
         "key" : "TRANSMISSION_PEX_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_PORT_FORWARDING_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_PREALLOCATION",
         "value" : "1"
      },
      {
         "key" : "TRANSMISSION_PREFETCH_ENABLED",
         "value" : "1"
      },
      {
         "key" : "TRANSMISSION_QUEUE_STALLED_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_QUEUE_STALLED_MINUTES",
         "value" : "30"
      },
      {
         "key" : "TRANSMISSION_RATIO_LIMIT",
         "value" : "2"
      },
      {
         "key" : "TRANSMISSION_RATIO_LIMIT_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_RENAME_PARTIAL_FILES",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_RPC_BIND_ADDRESS",
         "value" : "0.0.0.0"
      },
      {
         "key" : "TRANSMISSION_RPC_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_RPC_HOST_WHITELIST",
         "value" : ""
      },
      {
         "key" : "TRANSMISSION_RPC_HOST_WHITELIST_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_RPC_PASSWORD",
         "value" : "password"
      },
      {
         "key" : "TRANSMISSION_RPC_PORT",
         "value" : "9091"
      },
      {
         "key" : "TRANSMISSION_RPC_URL",
         "value" : "/transmission/"
      },
      {
         "key" : "TRANSMISSION_RPC_USERNAME",
         "value" : "username"
      },
      {
         "key" : "TRANSMISSION_RPC_WHITELIST",
         "value" : "127.0.0.1"
      },
      {
         "key" : "TRANSMISSION_RPC_WHITELIST_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME",
         "value" : ""
      },
      {
         "key" : "TRANSMISSION_SEED_QUEUE_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SEED_QUEUE_SIZE",
         "value" : "10"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_DOWN",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_UP",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_UP_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_START_ADDED_TORRENTS",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_UMASK",
         "value" : "2"
      },
      {
         "key" : "TRANSMISSION_UPLOAD_LIMIT",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_UPLOAD_LIMIT_ENABLED",
         "value" : "0"
      },
      {
         "key" : "TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT",
         "value" : "14"
      },
      {
         "key" : "TRANSMISSION_UTP_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_WATCH_DIR",
         "value" : "/data/watch"
      },
      {
         "key" : "TRANSMISSION_WATCH_DIR_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_HOME",
         "value" : "/config/transmission-home"
      },
      {
         "key" : "TRANSMISSION_WATCH_DIR_FORCE_GENERIC",
         "value" : "false"
      },
      {
         "key" : "ENABLE_UFW",
         "value" : "false"
      },
      {
         "key" : "UFW_ALLOW_GW_NET",
         "value" : "false"
      },
      {
         "key" : "UFW_EXTRA_PORTS",
         "value" : ""
      },
      {
         "key" : "UFW_DISABLE_IPTABLES_REJECT",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_WEB_UI",
         "value" : ""
      },
      {
         "key" : "PUID",
         "value" : "1024"
      },
      {
         "key" : "PGID",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_WEB_HOME",
         "value" : ""
      },
      {
         "key" : "DROP_DEFAULT_ROUTE",
         "value" : ""
      },
      {
         "key" : "WEBPROXY_ENABLED",
         "value" : "false"
      },
      {
         "key" : "WEBPROXY_PORT",
         "value" : "8888"
      }
   ],
   "exporting" : false,
   "id" : "c6736145a82d1b7248a0defb9a1b015fa30ddd24228ccf57a3a7745dd6b19a24",
   "image" : "haugene/transmission-openvpn:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "diskstation-transVPN",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 8888,
         "host_port" : 0,
         "type" : "tcp"
      },
      {
         "container_port" : 9091,
         "host_port" : 0,
         "type" : "tcp"
      }
   ],
   "privileged" : true,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "ulimits" : null,
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/Downloads/torrents/watch",
         "mount_point" : "/watch",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/transVPN",
         "mount_point" : "/config",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/transVPN/resolv.conf",
         "mount_point" : "/etc/resolv.conf",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/Downloads/torrents",
         "mount_point" : "/data",
         "type" : "rw"
      }
   ],
   "volumes_from" : null
}
`

**Comment by haugene** [comment]
Hey @bmoneruiux. In general this looks good to me, but if it doesn't work it doesn't work.
I can't point to any obvious blockers but since you've shared the config I can comment a bit in general.

* As long as you're not using WEBPROXY_ENABLED=true, you don't need to bind port 8888
* You shouldn't need to mount the /config volume. Nothing of interest is stored there by default
* Ref last point, you've overridden TRANSMISSION_HOME to /config/transmission-home. Any particular reason?
* Setting TRANSMISSION_DOWNLOAD_DIR, TRANSMISSION_INCOMPLETE_DIR and TRANSMISSION_WATCH_DIR is not necessary as you're setting them to default values anyways.
* PUID/PGID, have you masked them? They're not *** in your config?

You're mounting Downloads/torrents/watch to /watch, but tell transmission to look for torrents in /data/watch

I would remove the /config mount and the /watch mount and just use Downloads/torrents -=> /data and then by default there would be a completed, incomplete and watch folder under it.

Clearing the folders, or just testing with mounting /data to an empty folder temporarily could also minimise the number of error-causes here.

If you exec into your container and run `curl -I localhost:9091` - what is the output? You should get a 301 redirect to /transmission/web.
And could you get the container logs?
