### ISSUE TITLE
VPNTunnel configurations have changed

### ISSUE THREAD

**Issue by nonobzh29** [haugene/docker-transmission-openvpn#671]
VPNTunnel recently changed all their OVPN config files.
Those in the image are now obsolete, and need to be updated.
They now have TCP & UDP on port 1195.
TCP 443 doesn't exist anymore, it has been replaced by Stunnel (not sure this can be integrated)
They also changed their cipher and a few other things.

**Comment by haugene** [comment]
Ok, thanks for the heads up. Do they offer some kind of .ovpn config bundle for download?
If you could find that I can update the configs to the new versions.

**Comment by nonobzh29** [comment]
Config files are only visible to customers.
I've gathered them and you can find the .ovpn files here : https://www.dropbox.com/sh/rblcj5m2ia89sxo/AAApEHcvTWyUp4zjISBZ5xJea?dl=0

**Comment by nonobzh29** [comment]
Looks good to me.
Just thinking if it's a good idea to keep "spaces" in filenames.

**Comment by haugene** [comment]
Was thinking the same. Will just squash it together camel case style, so we get `ArgentinaBuenosAires.tcp.ovpn` and so on? For Britain (UK), just do GreatBritainCoventry.tcp.ovpn? Keep clean from "special" characters.

**Comment by nonobzh29** [comment]
Should be perfect! Thanks

**Comment by nonobzh29** [comment]
I tested the dev taged image, and it's working fine !

**Comment by haugene** [comment]
Sorry about the delay. Got nothing done over the holidays :/
Anyways, updated now. Committing and closing this issue. Doing a merge to master later (today I think)

**Comment by haugene** [comment]
Re-open if there are any other problems...
