### ISSUE TITLE
Ivacy certificates (and/or configuration) are outdated

### ISSUE THREAD

**Issue by dieselburner** [haugene/docker-transmission-openvpn#673]
[Here ](https://support.ivacy.com/wp-content/uploads/2018/09/OpenVPN-Configs.zip)is location of new OpenVPN configuration files (as per [this link](https://support.ivacy.com/kb/openvpn-files-windows-routers-ios-linux-and-mac/)). Sorry, too busy atm to bake a pr.

**Comment by haugene** [comment]
Hey. Thanks for the heads up and link. Updated them now, can you test if it works?
Will be available on the dev tag soon, and I think I'll just merge it to master later today so it's available on the latest tag as well. Getting stuff done after the holidays :)

**Comment by haugene** [comment]
#554
