### ISSUE TITLE
Credentials are stored in plain text

### ISSUE THREAD

**Issue by RealLukeManning** [haugene/docker-transmission-openvpn#675]
I've just installed this Docker, having it running with NordVPN, but I've noticed two plain text files in this config folder containing the credentials for Transmission and the credentials for my NordVPN account. They are named:
- openvpn-credentials.txt
- transmission-credentials.txt

This seems like a pretty serious security vulnerability? 

`root@Tower:/mnt/user/Docker Config/Transmission_VPN# cat transmission-credentials.txt`
`admin`
`password`

**Comment by RealLukeManning** [comment]
The offending code comes from `start.sh` in the openvpn directory. The environmental variables are echoed out to a plain text file, and a quick look suggests that plain text file is never referenced again anywhere.. so not sure what purpose it serves:

```# add OpenVPN user/pass
if [[ "${OPENVPN_USERNAME}" == "**None**" ]] || [[ "${OPENVPN_PASSWORD}" == "**None**" ]] ; then
  if [[ ! -f /config/openvpn-credentials.txt ]] ; then
    echo "OpenVPN credentials not set. Exiting."
    exit 1
  fi
  echo "Found existing OPENVPN credentials..."
else
  echo "Setting OPENVPN credentials..."
  mkdir -p /config
  echo "${OPENVPN_USERNAME}" > /config/openvpn-credentials.txt
  echo "${OPENVPN_PASSWORD}" >> /config/openvpn-credentials.txt
  chmod 600 /config/openvpn-credentials.txt
fi```

**Comment by haugene** [comment]
And then I found #534 that propose a solution. Closing this then, and following up in 534. Not sure it will be implemented - but still - worth a look.
