### ISSUE TITLE
Perfect Privacy certificates are outdated

### ISSUE THREAD

**Issue by sstativa** [haugene/docker-transmission-openvpn#678]
Looks like `.ovpn` files for Perfect Privacy are outdated. I was unable to run the container until I replaced certificate and private key in `ovpn` file.
Here is the new [conf](https://mega.nz/#!02p0GK7L!fS6YUmnHVmbzrKh5zbVTUZSlojg2vQ1s_PcQK370W70).

**Comment by haugene** [comment]
Ok, I'll see if I have time for this over the weekend. Thanks for the heads up and configs, looks good.
I see there's two versions of the config files. All and single.

Any preferences for which to use? Can have both as well, either bunched together in the same folder or the singles can be under /single/Amsterdam1 for example?

**Comment by sstativa** [comment]
I suppose "grouped" config should be enough. 

Perfect Privacy offers two types of configs: "servers grouped" and "servers separately". I was not sure which one will you need, therefore I gave you both types.

**Comment by randaal** [comment]
double tapping this... big issues for docker containers on synology :(

**Comment by haugene** [comment]
Hey @sstativa and @randaal. Sorry about the delay, pushed new configs to master now. Should be on latest tag any minute. Can you test it and give me a 👍 or 👎 ?

**Comment by pkaufman** [comment]
just when I wanted to open a PR... 🙈 I tested the latest image and it works with PP, thanks!

**Comment by randaal** [comment]
certificates seem to work, new pull doesnt work from the Synology UI (havent tested from ssh and commandline docker)... i'm sure its my issue though and unrelated to the PP certificates

**Comment by haugene** [comment]
👍 Closing this then...
