### ISSUE TITLE
Froot VPN changed

### ISSUE THREAD

**Issue by kornflex** [haugene/docker-transmission-openvpn#68]
Hello,

With default FrootVPN config, the URL has changed : 
se-vpn.frootvpn.com

 to

 se.vpn.frootvpn.com

**Comment by haugene** [comment]
Have you pulled the latest image? I updated the froot config in #57. Its now like this: https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/froot/frootvpn.ovpn

**Comment by kornflex** [comment]
Hi,

Sorry, I will do the update with docker.

Thanks

Le lun. 25 avr. 2016 20:14, Kristian Haugene <notifications@github.com> a
écrit :

**Comment by haugene** [comment]
Relating to Froot, I've now added configs for france, canada and the US. It's available on the dev branch along with some other config changes. If you're using the dev tag you should be able to set ```OPENVPN_CONFIG=us.openvpn.frootvpn``` and so on to use other configs. If it's not set it will still default to sweden.

If you have the time and want to check that everything works before I merge it to master, that would be great :)
