### ISSUE TITLE
Raspberry Pi - ports not reachable

### ISSUE THREAD

**Issue by ni-ka** [haugene/docker-transmission-openvpn#683]
I'm trying to use docker-compose up with the arm file, however I cannot reach any of the exposed ports. Something is connecting, but requests time out.

Also, I noticed a route error in the log:
transmission_1  | STARTING TRANSMISSION
transmission_1  | NO PORT UPDATER FOR THIS PROVIDER
transmission_1  | Transmission startup script complete.
transmission_1  | RTNETLINK answers: File exists
transmission_1  | Tue Jan 15 17:42:54 2019 ERROR: Linux route add command failed: external program exited with error status: 2
transmission_1  | Tue Jan 15 17:42:54 2019 Initialization Sequence Completed

**Comment by haugene** [comment]
If you haven't changed the docker-compose file then it declares LOCAL_NETWORK=192.168.0.0/24.
What is your local network? Have you changed the variable accordingly?

Please provide the docker run command, or docker-compose file that you're using. Plus the complete logs. Mask sensitive stuff and post the rest. We need something to go on if we're going to help you get this working.
