### ISSUE TITLE
Please add Celo.Net provider

### ISSUE THREAD

**Issue by damccull** [haugene/docker-transmission-openvpn#685]
Celo.net is a vpn provider I use and would love to see it added natively.

**Comment by haugene** [comment]
Can you provide a link to where we can download the .zip file with .ovpn configs and certificates? Most providers have one of these.

**Comment by damccull** [comment]
https://support.celo.net/article/openvpn-server-config-files/

**Comment by haugene** [comment]
Went to add this now, and followed the links to the bundled configs which I think are the ones we want. But I'm met with a login page: https://support.celo.net/kb/bundled-connection-files/

Looks to be the same for all the others as well.

**Comment by raptor1jec** [comment]
I have the same issue, for some reason I can't get CELO to work using the CUSTOM settings. I paid for a lifetime plan, so I'd rather not use another provider

Here's the config files:

[Celo_Server_Configs.zip](https://github.com/haugene/docker-transmission-openvpn/files/4240169/Celo_Server_Configs.zip)
