### ISSUE TITLE
FreeNAS TUN/TAP

### ISSUE THREAD

**Issue by RaGeXGotYoded** [haugene/docker-transmission-openvpn#686]
All right, so I have been spending way too much time on this and trying to figure out a solution that I've almost got no hair left on my head. I don't know if it is a problem related to the container at all so I would probably redirect this to the freenas forums.

I have been trying to get openvpn to work in any shape or form, and it just does not want to. I either get `'Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)'` or the cannot allocate one. I could not get this to work on a jail either, that is why I'm thinking that this is not a container problem at all.

I'm using FreeNAS, and I've tried installing a normal openvpn pkg on the host, but it is not possible from what I've seen. I've tried running the tun.sh script, but with no luck, as multiple errors are being spit. The /dev/net folder and tun file are there and do exist on the container, but the error still persists.

Any help is appreciated, and will move this to freenas's forums if it is on their side.

**Comment by RaGeXGotYoded** [comment]
Okay, so the file structure is different on FreeBSD, respectively '/dev/net/tun' being 'dev/tun', and no way of creating a /dev/net/tun. It's incompatible with FreeBSD as of now.

**Comment by niXta1** [comment]
> Okay, so the file structure is different on FreeBSD, respectively '/dev/net/tun' being 'dev/tun', and no way of creating a /dev/net/tun. It's incompatible with FreeBSD as of now.
Can't you just symlink it?

**Comment by RaGeXGotYoded** [comment]
Tried it, but I can't find a way of creating the net folder in dev. Everything I've tried just gives smt as operation not supported or whatever.

**Comment by haugene** [comment]
How about adding a line in the ovpn config? `dev-node <node>`
Ref: https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/

> Explicitly set the device node rather than using /dev/net/tun, /dev/tun, /dev/tap, etc. If OpenVPN cannot figure out whether node is a TUN or TAP device based on the name, you should also specify –dev-type tun or –dev-type tap.

From the way they write it, it almost sounds like it should automatically check /dev/tun as well.
You've tried running with `--cap-add=NET_ADMIN --device=/dev/tun` directly? If that doesn't work out of the box, maybe the `dev-node` option can help.

**Comment by RaGeXGotYoded** [comment]
Cannot test it right now, but I just realized I forgot about changing the --device option to /dev/tun to begin with, and left it at dev/net/tun. That'd probably do the trick. Appreciate it mates.
