### ISSUE TITLE
organizr can't talk to transmission

### ISSUE THREAD

**Issue by kiwijunglist** [haugene/docker-transmission-openvpn#689]
I can access transmissionvpn web gui via my local ip address on my PC on the same network 
http://192.168.1.99:9091

However my organizr docker running on the same pc as tranmission, can't access the transmission currentl downloads data using the same IP address above.

Organizr was working fine when I was using transmission-nonvpn

**Comment by kiwijunglist** [comment]
transmissionvpn:
    container_name: transmissionvpn
    image: haugene/transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=xxxxxxxxxxxx
      - OPENVPN_PASSWORD=xxxxxxxxxxxxxx
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
      - TRANSMISSION_WATCH_DIR=/downloads/watch
      - TRANSMISSION_RPC_USERNAME=xxxxxxxxxxxxxxxxxxx
      - "TRANSMISSION_RPC_PASSWORD={xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      - 9091:9091
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/transmissionvpn/vpn:/config
      - ${DOCKERCONFDIR}/transmissionvpn/transmission:/data/transmission-home
      - ${DOCKERSHAREDDIR}:/shared
      - ${DOWNLOADSDIR}:/downloads

  organizr:
    container_name: organizr
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    image: organizrtools/organizr-v2:php-fpm
    ports:
    - ${ORGANIZR_PORT_80}:80
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/organizr:/config
    - ${DOCKERSHAREDDIR}:/shared

  letsencrypt:
    cap_add:
    - NET_ADMIN
    container_name: letsencrypt
    environment:
    - DNSPLUGIN=${LETSENCRYPT_DNSPLUGIN}
    - DUCKDNSTOKEN=${LETSENCRYPT_DUCKDNSTOKEN}
    - EMAIL=${LETSENCRYPT_EMAIL}
    - EXTRA_DOMAINS=${LETSENCRYPT_EXTRA_DOMAINS}
    - ONLY_SUBDOMAINS=${LETSENCRYPT_ONLY_SUBDOMAINS}
    - PGID=${PGID}
    - PUID=${PUID}
    - SUBDOMAINS=${LETSENCRYPT_SUBDOMAINS}
    - TZ=${TZ}
    - URL=${LETSENCRYPT_URL}
    - VALIDATION=${LETSENCRYPT_VALIDATION}
    image: linuxserver/letsencrypt
    ports:
    - ${LETSENCRYPT_PORT_443}:443
    - ${LETSENCRYPT_PORT_80}:80
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/letsencrypt:/config
    - ${DOCKERSHAREDDIR}:/shared

**Comment by kiwijunglist** [comment]
i fixed it.

**Comment by undaunt** [comment]
What was the fix?
