### ISSUE TITLE
Installing additional packages

### ISSUE THREAD

**Issue by Troubadoure** [haugene/docker-transmission-openvpn#692]
Is there a way of installing additional packages in this that will survive an update?

I’m mainly thinking of python3, pip3 and scrapyd?

**Comment by jfessard** [comment]
You probably should fork the repo, and add whatever you need to the dockerfile, and build that to use yourself.
What do you need those packages for if I may ask?

**Comment by haugene** [comment]
Not as of now @tomhumphrey. When you say update, that means re-creating the image and the file system goes with it. That kind of libraries would need to be installed in the image and then everyone would get them. We've been restrictive on this till now.

You can make it quite close thoug. Using the custom pre/post-script functionality. https://github.com/haugene/docker-transmission-openvpn#custom-prepost-scripts

I guess you could make a script that checks if required packages exists before starting Transmission. If they don't the script can install them.
