### ISSUE TITLE
Sonarr import problem

### ISSUE THREAD

**Issue by Rodrigueztb** [haugene/docker-transmission-openvpn#694]
Since i migrate to transmission-vpn, sonarr cant import the files from the download folder. I get this msg on Sonarr log:

DownloadedEpisodesImportService	Import failed, path does not exist or is not accessible by Sonarr: /data/complete/Filename

Other clients works well. Already reset permission and set to false the overwrite permission option on variables. Im using docker on openmediavault.

Any idea How to fix it? Thank for any help

**Comment by Rodrigueztb** [comment]
I had tried this but unfortunately it didnt work. I deleted all the containers and will try to create a container with the patchs and use on the others containers the volume from this one.

**Comment by Rodrigueztb** [comment]
Fix it. I stop using sharedfolder and map it direct to the HD folder!

**Comment by haugene** [comment]
Seems this issue is resolved. Re-open if that is not the case.

**Comment by olivariusFR** [comment]
@Rodrigueztb could give me more details on how you solved the problem? I tried everythingand I am stuck

**Comment by bubez81** [comment]
hello, sorry can you explain what did you do to fix? i'm using docker transmission only, sonarr is directly installed on my Mac mini, transmission download the file but sonarr can't see it

**Comment by pkishino** [comment]
> hello, sorry can you explain what did you do to fix? i'm using docker transmission only, sonarr is directly installed on my Mac mini, transmission download the file but sonarr can't see it
This sounds like a sonarr config Problem. Most likely you haven’t mapped the folders correctly in sonarr. I have the same setup: Mac mini, transmission docker, sonarr and radarr working perfectly, but you need to setup downloaded in sonarr and in advanced settings create folder mapping

**Comment by bubez81** [comment]
hello, thank you for the response. Can i ask you a more specific hint? 
i have mounted /Users/myuser/Downloads in /data/
then 
              -e TRANSMISSION_WATCH_DIR=/data \
              -e TRANSMISSION_WATCH_DIR_ENABLED=true \
              -e TRANSMISSION_INCOMPLETE_DIR=/data/incomplete \
              -e TRANSMISSION_INCOMPLETE_DIR_ENABLED=true \
so, now i know that transmission search for new torrent in /Users/myuser/Downloads and that the completed files go to /Users/myuser/Downloads/completed.
In sonarr in the download client section what i have to select?
Thank you in advice.

**Comment by bubez81** [comment]
eureka...the sonarr/radarr setting is the remote path!
