### ISSUE TITLE
How to test that the Transmission uses VPN?

### ISSUE THREAD

**Issue by kyxap** [haugene/docker-transmission-openvpn#698]
I have configured custom provider and logs says is connected.
But how I can test if all traffic goes to the vpn?

thanks

**Comment by kyxap** [comment]
wow, thanks

**Comment by haugene** [comment]
For future reference: #323, #513, #197 are some similar questions. And #357 + #362 is getting more relevant.

**Comment by qu4542** [comment]
this creates a magnet link you can use

http://ipmagnet.services.cbcdn.com/
