### ISSUE TITLE
NordVPN 185.30.232.17 timeout

### ISSUE THREAD

**Issue by jscoys** [haugene/docker-transmission-openvpn#709]
Hello ive got exactly the same issue than here: https://github.com/haugene/docker-transmission-openvpn/issues/672

Can you check the openvpn files please? Pretty sure they changed...

**Comment by jscoys** [comment]
@augene?

**Comment by h45rd** [comment]
Why so impatient? :)

If this matter is of such high importance to you, go ahead and spend some time to actually debug and verify the exact issue. 
I am sure @haugene would be more than happy to incorporate your pull request for updated NordVPN files and/or a NordVPN API implementation as described in #655.

The pieces are all there. You just have to invest some of your own time and put them together.
If you hit any roadblocks on the way, feel free to ask for guidance.
I am certain there are more than enough people willing to assist someone who wants to contribute to the project.

**Comment by haugene** [comment]
Hey @jscoys. @h45rd is right, incorporating #655 seems to be the only permanent fix for NordVPN as they seem to have a quite dynamic set of servers.

I'm very open to pull-requests that fixes this. And if one does not show up, I might do the first part myself soon. Just doing dynamic downloading of new config files so we don't need to do that manually all the time.

It's been a couple of very busy months at work, coding at all hours, so sitting down do code some more has not been the priority for a little while. And my gf would kill me. But give me a couple of weeks and things should calm down and I might be able to do some of the upgrades I'm thinking about for the image.

I just did a quick check for the `al10.nordvpn.com.tcp.ovpn` and it is still up to date with what I find on nordvpn.com, so it might not be all servers. Have you tried several?

In the mean time... If you want you could just download an .ovpn file yourself and use that.
As far as I can see, for NordVPN, just download a file and remove:
```
ping 15
ping-restart 0
ping-timer-rem
```
Then replace the `auth-user-pass` line for:
```
auth-user-pass /config/openvpn-credentials.txt
```

Finally mount your config into the container with: 

`-v /path/to/myspecial.ovpn:/etc/openvpn/nordvpn/myspecial.ovpn` and set `OPENVPN_CONFIG=myspecial`. Then you should be in the clear, until we get the automatic updates implemented here...

**Comment by haugene** [comment]
This is also basically the same as using the "custom provider" guide in the README.
The image was meant to be a turn-key solution and pre-packaging it with configs seemed to be a good idea. But with so many providers, the maintenance also grows. And especially for NordVPN we should consider a change. But... time :)

**Comment by jscoys** [comment]
Hey guys thx a lot! I put the al10.nordvpn.com.tcp.ovpn in my yaml file and it connected super fast.

I'm sorry @h45rd didn't want to be annoying it's just I'm using this wonderful docker project for 2 days now so I don't even know how it works! Thx again for your help. Would be very happy to see the implementation of the permanent fix. Have a good days guys, and @haugene don't work too much, one day you will discover life's short and you missed important things.

**Comment by h45rd** [comment]
lol! And thanks for the trust @haugene :)

I am a bit torn on the idea of a turn-key solution.
It would be easily maintainable with the great basic structure that is already in place. **If** more users contributed to updating the configs of the provider they use.

I had a long section here about encouraging user collaboration by adding a tutorial on how to adapt and PR configs, when I noticed that the readme already has just that :)

Is it still the plan to cut back on the verbosity of the readme and branch off broader topics into the wiki?
I could get started on that once work gets a little less busy (same story all around, eh?).

@jscoys 
Don't sweat it. If you want to learn/contribute in the future and need some pointers, feel free to hit me up.
Adding NordVPN API support looks to be mainly busywork at first glance. Especially easy for someone with credentials to this provider. Would be a great little first project ;)

**Comment by robinekenheim** [comment]
Hey having similar issues as above. Setup has been working great for a long time until maybe I week ago or so - posted back at #587 and seems again to be related to NordVPN... Been trying a couple different servers with editing, openvpn_config and putting diffent server urls from the https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/nordvpn

Unsure how to proceed

**Comment by haugene** [comment]
@robinekenheim Not sure there's much more to say than what I wrote in my first post in this issue.
The servers are changing fast, and that is an issue as the update from our side is a manual one.

You can either try different configs and find one that hasn't changed since last update, for example the al10.nordvpn.com.tcp.ovpn seemed to still work for @jscoys. Apart from that you either need to wait for #655 to get implemented or handle configs yourself by downloading the one you want from NordVPN and mount it as I also described in that post.

**Comment by haugene** [comment]
Closing this in favour of #655 which is closing in on a solution. PR is made and will be merged soon.
