### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by welpseeyalater** [haugene/docker-transmission-openvpn#712]
Here's what I'm running into.  Thanks in advance.

1.)Windows 10 home OS. All my media files live here. I have Emby and Picard scraping/sorting them.

2.)Have Ubuntu Server 18.04 running in Hyper-V.

3.)Transmission-VPN running as a Docker container in Ubuntu Server Hyper-V

4.)Per my docker-compose file, Transmission should be putting completed filed in /data/completed, which is mirrored to ${USERID}/Downloads/completed.

5.)I would like completed filed to be sent to a folder visible by Emby and Picard, so I mounted ${USERID}/Downloads/completed as a folder on the host machine.

6.)This connection seems to work--when I sudo mkdir a folder in ${USERID}/Downloads/completed, I can see it on my Windows side. (Note that this does not work without typing "sudo.").

7.)Transmission seems to work ok. It creates a folder in ${USERID}/Downloads/incomplete while a file is downloading.

8.)When the download is complete, the file never ends up in ${USERID}/Downloads/completed. In my Transmission log, I see this error: "Couldn't create '/data/completed/{MEDIA}' : Permission Denied (file-posix.c:189)

**Comment by h45rd** [comment]
Disclaimer: I don't think I fully get your setup and I never used Hyper-V :)

Just to clarify:
2) Hosted on your Win10 box?
4) mirrored? Are we talking about a docker volume mount on the Ubuntu box or an actual filesystem mirroring?
5) mounted how? Via the hypervisor or a network filesystem on the guest?

Your host box (Win10) has the physical storage and sorts and serves your media, correct?
I think the cleanest approach (as in being portable and not relying on any proprietary hypervisor features) would be to create a cifs share for your downloads folder on the host itself. Then just mount that share on your Ubuntu box and docker volume mount it to the transmission container.

**Comment by welpseeyalater** [comment]
Thanks for the reply!

1.)Hosted on Win10
4.)Not sophisticated enough to answer your question directly, but here's what my docker compose file shows, which I believe has the function of saying "OK, so when you think you're putting something in /data/completed within your container, it's really going in /home/myusername/Downloads/completed: 

> /home/${USERDIR}/Downloads/completed:/data/completed

5.)I used the following command: mount.cifs //hostmachinename/NewDownloadsFromDockers completed (when I was in the "Downloads" folder).  It prompted me for my windows password and that seems to have worked.  When I make a dummy folder in that "completed" folder from the command line in Ubuntu, I can see it Windows.  Note that this requires "sudo".

My host does have the physical storage and sorting.  I think I've done what you said, right?

**Comment by h45rd** [comment]
Did you run mount.cifs as root (i.e. with sudo) or as your user?
Are you using the [PUID and/or PGID](https://github.com/haugene/docker-transmission-openvpn#user-configuration-options) environment variables?

Either way I would suggest mounting your share system-wide for all users via /etc/fstab. Have a look at [MountWindowsSharesPermanently](https://wiki.ubuntu.com/MountWindowsSharesPermanently) in the Ubuntu wiki and [community](https://help.ubuntu.com/community/MountWindowsSharesPermanently) for further information and troubleshooting.
Make sure to set appropriate permissions so the transmission user has full access to the share.

**Comment by haugene** [comment]
Stale issue, closing.
