### ISSUE TITLE
installing docker transmisison openvpn on arm64 device qnap

### ISSUE THREAD

**Issue by dikkedikkie** [haugene/docker-transmission-openvpn#715]
Hello all,

im searching for a way to test the dev branch armfs on my qnap using container station. Is there any manual for doing this?

**Comment by haugene** [comment]
Use the dev-armhf tag of the image.
`haugene/transmission-openvpn:dev-armhf`

**Comment by dikkedikkie** [comment]
Hi, thanks for the quick reply. The container station oom my QNAP only connects to  Docker Hub as a repro.
Any idea how i can install github repro on my Container station or how i can download haugene/transmission-openvpn:dev-armhf and the import manually?

**Comment by haugene** [comment]
Yeah, well. It's on the Docker Hub. But what you're saying is that you can't choose the tag to use from the Docker hub? In that case you can ssh into your qnap and run `docker pull haugene/transmission-openvpn:dev-armhf` - i guess.

But your questions seems not to be related to this image specifically. It seems that your troubles lay in understanding how Docker works on QNAP. While there may be other QNAP users of this image, I think this question should be directed at QNAP forums?

**Comment by dikkedikkie** [comment]
Hi, thanks again for your quick reply. i will ask on the qnap forum
