### ISSUE TITLE
running a script inside the container

### ISSUE THREAD

**Issue by b0red** [haugene/docker-transmission-openvpn#717]
I'm trying to run the [addtracker-script](https://github.com/oilervoss/transmission) inside the container, but it seems like it's not working, stops at the first line of the script: `Fail on transmission. Aborting.`
I moved the script inside the container with: `docker cp addtracker.sh transmission-vpn:/bin/` and it's executable `(-rwxr-xr-x)`, and residing in the /bin folder in the container.
Any tips?

**Comment by h45rd** [comment]
Had a quick look at the script.
The error you get indicates, that there is something wrong with transmission-remote, as the test call does not exit with 0.

What output do you get if you manually run `transmission-remote -l; echo "EXIT CODE: $?"` within the container?
Which tag/arch are you using?

**Comment by b0red** [comment]
Running `transmission-remote -l; echo "EXIT CODE: $?"` gives me the following;
```
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized User�V
EXIT CODE: 1
``` 
So it seems like some kind of authentication error?

**Comment by haugene** [comment]
I guess you've set `TRANSMISSION_RPC_USERNAME` and `TRANSMISSION_RPC_PASSWORD`? Doesn't seem like that script supports authentication being enabled.

**Comment by b0red** [comment]
Yes, username/password is set. It might be that, have to check with the script's author then. Thanx for checking though.

**Comment by haugene** [comment]
Then that's it. Should be a relatively quick fix for you though. Just modify this line of the script:
https://github.com/oilervoss/transmission/blob/master/addtracker.sh#L8

We're also using transmission-remote in this project to update with open port for PIA. To use it with auth the line should be like this: https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/updatePort.sh#L90

Where $myauth is set like this: https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/updatePort.sh#L71

**In sum:** Add `--auth username:password` to line 8 of your script and it should work...
