### ISSUE TITLE
HMAC Auth Failure

### ISSUE THREAD

**Issue by SQLJeet** [haugene/docker-transmission-openvpn#718]
Using TigerVPN and connecting to MON on the latest image. Checking the TigerVPN portal the MON connection has been established.

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Fri Feb 22 18:15:18 2019 Initialization Sequence Completed
Fri Feb 22 18:15:28 2019 Authenticate/Decrypt packet error: packet HMAC authentication failed

**Comment by haugene** [comment]
Could you maybe describe a bit more? I see you get an error but what else is happening? Is Transmission working? Is this the end of the logs?

Can you download the corresponding config from TigerVPN web page and compare it to the config you're using? What platform are you running on? Please share your docker run command and full logs.

**Comment by SQLJeet** [comment]
Transmission is working intermittently. I can restart it a few times and it keeps working until its down with the download. When another download gets added it cant find any peers. When that problem starts the webproxy throws this error: 

Could not connect to the server. You may need to reload the page to reconnect.

Logs from transmissions. It seems like it restarted a couple of times

Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 100.97.0.31,
Using Combustion UI, overriding TRANSMISSION_WEB_HOME,
Generating transmission settings.json from env variables,
sed'ing True to true,
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   root,
User uid:    0,
User gid:    0,
-------------------------------------,
,
STARTING TRANSMISSION,
NO PORT UPDATER FOR THIS PROVIDER,
Transmission startup script complete.,
Wed Feb 27 17:26:54 2019 Initialization Sequence Completed,
Wed Feb 27 17:27:04 2019 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Wed Feb 27 17:27:14 2019 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Wed Feb 27 17:27:24 2019 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Wed Feb 27 17:27:24 2019 [tigervpn.com] Inactivity timeout (--ping-restart), restarting,
Wed Feb 27 17:27:24 2019 /sbin/ip addr del dev tun0 100.97.0.31/16,
Wed Feb 27 17:27:24 2019 /etc/openvpn/tunnelDown.sh tun0 1500 1561 100.97.0.31 255.255.0.0 init,
Wed Feb 27 17:27:24 2019 SIGUSR1[soft,ping-restart] received, process restarting,
Wed Feb 27 17:27:29 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.,
Wed Feb 27 17:27:29 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Wed Feb 27 17:27:29 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]192.99.37.192:1194,
Wed Feb 27 17:27:29 2019 UDP link local (bound): [AF_INET][undef]:1194,
Wed Feb 27 17:27:29 2019 UDP link remote: [AF_INET]192.99.37.192:1194,
Wed Feb 27 17:27:29 2019 [tigervpn.com] Peer Connection Initiated with [AF_INET]192.99.37.192:1194,
Wed Feb 27 17:27:31 2019 TUN/TAP device tun0 opened,
Wed Feb 27 17:27:31 2019 /sbin/ip link set dev tun0 up mtu 1500,
Wed Feb 27 17:27:31 2019 /sbin/ip addr add dev tun0 100.97.0.31/16 broadcast 100.97.255.255,
Wed Feb 27 17:27:31 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1561 100.97.0.31 255.255.0.0 init,
Up script executed with tun0 1500 1561 100.97.0.31 255.255.0.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 100.97.0.31,
Using Combustion UI, overriding TRANSMISSION_WEB_HOME,
Generating transmission settings.json from env variables,
sed'ing True to true,
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   root,
User uid:    0,
User gid:    0,
-------------------------------------,
,
STARTING TRANSMISSION,
NO PORT UPDATER FOR THIS PROVIDER,
Transmission startup script complete.,
Wed Feb 27 17:27:31 2019 Initialization Sequence Completed,
Wed Feb 27 17:27:40 2019 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Wed Feb 27 17:27:50 2019 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Wed Feb 27 17:28:00 2019 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Wed Feb 27 17:28:01 2019 [tigervpn.com] Inactivity timeout (--ping-restart), restarting,
Wed Feb 27 17:28:01 2019 /sbin/ip addr del dev tun0 100.97.0.31/16,
Wed Feb 27 17:28:01 2019 /etc/openvpn/tunnelDown.sh tun0 1500 1561 100.97.0.31 255.255.0.0 init,
Wed Feb 27 17:28:01 2019 SIGUSR1[soft,ping-restart] received, process restarting,
Wed Feb 27 17:28:06 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.,
Wed Feb 27 17:28:06 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Wed Feb 27 17:28:06 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]192.99.37.192:1194,
Wed Feb 27 17:28:06 2019 UDP link local (bound): [AF_INET][undef]:1194,
Wed Feb 27 17:28:06 2019 UDP link remote: [AF_INET]192.99.37.192:1194,
Wed Feb 27 17:28:06 2019 [tigervpn.com] Peer Connection Initiated with [AF_INET]192.99.37.192:1194,
Wed Feb 27 17:28:08 2019 TUN/TAP device tun0 opened,
Wed Feb 27 17:28:08 2019 /sbin/ip link set dev tun0 up mtu 1500,
Wed Feb 27 17:28:08 2019 /sbin/ip addr add dev tun0 100.97.0.31/16 broadcast 100.97.255.255,
Wed Feb 27 17:28:08 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1561 100.97.0.31 255.255.0.0 init,
Up script executed with tun0 1500 1561 100.97.0.31 255.255.0.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 100.97.0.31,
Using Combustion UI, overriding TRANSMISSION_WEB_HOME,
Generating transmission settings.json from env variables,
sed'ing True to true,
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   root,
User uid:    0,
User gid:    0,
-------------------------------------,
,
STARTING TRANSMISSION,
NO PORT UPDATER FOR THIS PROVIDER,
Transmission startup script complete.,
Wed Feb 27 17:28:08 2019 Initialization Sequence Completed,
Wed Feb 27 17:28:17 2019 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Wed Feb 27 17:28:27 2019 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Wed Feb 27 17:28:37 2019 Authenticate/Decrypt packet error: packet HMAC authentication failed,
Wed Feb 27 17:28:38 2019 [tigervpn.com] Inactivity timeout (--ping-restart), restarting,
Wed Feb 27 17:28:38 2019 /sbin/ip addr del dev tun0 100.97.0.31/16,
Wed Feb 27 17:28:38 2019 /etc/openvpn/tunnelDown.sh tun0 1500 1561 100.97.0.31 255.255.0.0 init,
Wed Feb 27 17:28:38 2019 SIGUSR1[soft,ping-restart] received, process restarting,
Wed Feb 27 17:28:43 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.,
Wed Feb 27 17:28:43 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Wed Feb 27 17:28:43 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]192.99.37.192:1194,
Wed Feb 27 17:28:43 2019 UDP link local (bound): [AF_INET][undef]:1194,
Wed Feb 27 17:28:43 2019 UDP link remote: [AF_INET]192.99.37.192:1194,
Wed Feb 27 17:28:43 2019 [tigervpn.com] Peer Connection Initiated with [AF_INET]192.99.37.192:1194,

 Im using both transmissions and the web proxy. I checked TigerVPN web page and it is correct. Im using a portainer stack and I included the portion transmission. 


   transmission:
        image: haugene/transmission-openvpn:latest
        container_name: transmission
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        restart: always
        ports:
            - 9091:9091
            - 8888:8888
        dns:
            - 8.8.8.8
            - 1.1.1.1
        networks:
            - plexnet
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /disk2/transmission/:/data
            - /disk2/transmission/:/data/watch
        environment:
            - OPENVPN_PROVIDER=TIGER
            - OPENVPN_USERNAME=xxxxxxxxxxx
            - OPENVPN_PASSWORD=xxxxxxxxxx
            - OPENVPN_CONFIG=CA Montreal
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - LOCAL_NETWORK=192.168.1.0/24
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
            - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.1.13"
            - TRANSMISSION_UMASK=022
            - TRANSMISSION_RATIO_LIMIT = .025
            - TRANSMISSION_RATIO_LIMIT_ENABLED = true
            - TRANSMISSION_SPEED_LIMIT_UP = .5
            - TRANSMISSION_SPEED_LIMIT_UP_ENABLED = true
            - TRANSMISSION_WEB_UI=combustion
            - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED = 1
            - TRANSMISSION_DOWNLOAD_QUEUE_SIZE = 30
    ombi:
        image: linuxserver/ombi:latest
        container_name: ombi
        networks:
          - plexnet
        volumes:
          - /disk2/ombi/:/config
          - /etc/localtime:/etc/localtime:ro
        ports:
          - 3579:3579
        mem_limit: 4096m
        restart: unless-stopped
    proxy:
        image: haugene/transmission-openvpn-proxy:latest
        links:
             - transmission
        ports:
            - 8080:8080
        volumes:
            - /etc/localtime:/etc/localtime:ro
        networks:
            - plexnet
        restart: always

**Comment by haugene** [comment]
Hmm. Can you download new .ovpn configs from TigerVPN and compare them to the ones in this repo? Could be that the connection can't be established because the they have updated their servers.

**Comment by amcolash** [comment]
I noticed the `.ovpn` files differ quite a bit - lots more config from the newer ones (though not sure to what extent it matters). Here is a diff of Toronto, CA https://www.diffchecker.com/dokRWCFj

**Comment by amcolash** [comment]
Unfortunately, it seems my fix from a little bit ago didn't solve my problems longer term and it was just the restart which seemed to make it more stable. I am looking into other solutions... Restarting from a healthcheck might be sufficient
