### ISSUE TITLE
Torrents won't download

### ISSUE THREAD

**Issue by matthewdias** [haugene/docker-transmission-openvpn#72]
When I add torrents to transmission, they seem to load okay (metadata is downloaded), but none of the data will download.

**Comment by haugene** [comment]
You need to provide more info. Which provider are you using? Do you have any logs? Do you still have network connectivity if you exec into the container and try to ping stuff? Is DNS working inside the container? etc etc

**Comment by matthewdias** [comment]
I'm using PIA. It doesn't seem like I have network connectivity. How would I check if DNS is working in the container?

**Comment by haugene** [comment]
"docker exec -it <container name/id> bash" will give you a bash shell inside the container. From there you can ping Google or something to see if it resolves.

**Comment by matthewdias** [comment]
right, DNS isn't working either. It could be possible that I messed it up. I did
```
for i in {49000..49900}; do
  VBoxManage modifyvm "boot2docker-vm" --natpf1 "tcp-port$i,tcp,,$i,,$i";
  VBoxManage modifyvm "boot2docker-vm" --natpf1 "udp-port$i,udp,,$i,,$i";
done
```
to get the nginx proxy working on my url.

**Comment by matthewdias** [comment]
Doesn't work with new machine either. Other images work fine.

**Comment by haugene** [comment]
Remove the container and then start a new one. Post the logs after it started up. You are running in privileged mode?

**Comment by matthewdias** [comment]
yup running in privileged.
[logs](https://gist.github.com/bdd684af59a20b12912d86b90b8231d9)

**Comment by haugene** [comment]
Ok, so the container starts but no dns. Are you setting the --dns flags suggested in the readme when you start it? After the container is started up, can you exec into it and check the contents of /etc/resolv.conf?

**Comment by matthewdias** [comment]
It turns out something had gone wrong with my pfSense box. I've since restarted it, and dns is working properly. Thanks for the help anyway.
