### ISSUE TITLE
NewsHosting updated configs

### ISSUE THREAD

**Issue by shadofall** [haugene/docker-transmission-openvpn#724]
Keep getting a soft,connection-reset] received, process restarting  message, no errors in logs
but i dont see the IP from this message on their server list

TCP/UDP: Preserving recently used remote address: [AF_INET]**81.171.97.65**:443

Pulled down their opnv files. all last modified 12/3/2018, however VPN was working after that date.
tried cycling/reinstalling the docker image  havent rebooted my server yet will try that next a little later. but just incase these are needed

Will update if it comes back after reboot w

[nh_configs.zip](https://github.com/haugene/docker-transmission-openvpn/files/2921605/nh_configs.zip)

**Comment by shadofall** [comment]
i got it. pointed my config to a different ovpn file other than default

i'll leave the issue open for the configs to be reviewed just incase 

As a thought. is it possible, or would it be possible to make it so you could specify that it try a different ovpn file after X time if default isnt connecting? either via list in the OPENVPN_CONFIG paramater or randomly?

**Comment by h45rd** [comment]
You can provide a comma separated list of OVPN files via the OPENVPN_CONFIG variable. At each start one of the files will be chosen at random.
Have a look at latter half of [this section](https://github.com/haugene/docker-transmission-openvpn#run-container-from-docker-registry) of the readme.

To accomplish your redundancy goals you should combine the above with the various OpenVPN inactivity timeout options, see e.g. [here](https://github.com/haugene/docker-transmission-openvpn#restart-container-if-connection-is-lost) and `man openvpn` for further information.

**Comment by lukeborn** [comment]
Thank you very much for finding this @shadofall !  This issue has had me baffled all day. After doing as @h45rd recommended transmission is back up and running as if it never had a problem!

**Comment by haugene** [comment]
From what I could see in the new configs it seems they've changed from tcp to udp for all their server configs? Are you still getting some of them to work?

Updated the configs now, and pushed to dev branch. Can you test the dev tag of the image and let me know it that works as it should @lukeborn @shadofall?
