### ISSUE TITLE
Same thing but with amule, Possible?

### ISSUE THREAD

**Issue by alfamatteo92** [haugene/docker-transmission-openvpn#725]
Hi, is it possible to create a docker container like this but with amule over openvpn?? It would be really great!!! Let me know, thanks

**Comment by h45rd** [comment]
Don't see what would stop you :)
Since it is all open source, you could easily accomplish this with minimal effort, using haugene's docker as a template for your own.

An even less effort option would be to share the network stack of an OpenVPN-enabled container with one of the existing amule dockers via the `--network container:` parameter, see [docker run reference](https://docs.docker.com/engine/reference/run/#network-settings).

**Comment by alfamatteo92** [comment]
Mmh...I would include amule daemon in this existing container...how can I do this?

**Comment by h45rd** [comment]
While possible (e.g. by calling an appropriate shellscript via one of the pre start hooks), I would not recommend doing so.
The _docker way_ is one service per container, preferably stateless.
Even though (ab)used by some like this, docker is not meant to be a "light" version of a catch-all VM.
Using a clean approach means less work and hassle in the long run, too.

**Comment by alfamatteo92** [comment]
I used --network container: parameter but obviously I cannot access to amule webui...How can I overcame this problem?

**Comment by h45rd** [comment]
You need to map the port of amule's webif using the `-p` parameter in the docker run call of the **parent** container.

**Comment by alfamatteo92** [comment]
Hi, I've added -p 4711:4711 to amule docker run call and now works...but how can I be sure that the amule traffic is under vpn too?

**Comment by haugene** [comment]
The short answer is just: "it is". There are many questions on exactly that, "how do I know?", and the long answer is that it depends on how deep you want to dig.

You can do some network tests from the amule container. Exec in and curl some ip echo services. This will be the same as testing the openvpn container though, as it is attached to the same networking stack.

Then you could inspect your iproute tables to see what the routing rules are. For most people that would also mean learning to interpret them. Or you could install a packet sniffer like wireshark and analyse your networking.

In general I would say that as long as you haven't misused the LOCAL_NETWORK variable, you should be good. Any IP in the range given there **will not** be routed via VPN. Other traffic will.

**Comment by haugene** [comment]
Ready to close this @alfamatteo92?
