### ISSUE TITLE
ProtonVPN and p2p server setup

### ISSUE THREAD

**Issue by pejotll** [haugene/docker-transmission-openvpn#727]
Hi there, 

I was able to set up TransmissionOpenVPN using ProtonVPN in docker in openmediavault. I was wondering if someone could show me how to set up specific ProtonVPN server in docker using TransmissionOpenVPN pluggin. There are few p2p servers that are much faster than default one. 
Is it through OPENVPN_CONFIG="name of the server"?

thanks.

**Comment by h45rd** [comment]
Yes, you need to select the server(s) you want to use via the OPENVPN_CONFIG variable.
If they are not on [this list](https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/protonvpn), you need to follow the readme steps about adding a custom provider configuration.

**Comment by pejotll** [comment]
@h45rd thanks for that list, I found server that I want on that list. Im a bit new to that stuff, could you please tell me what should i put in OPENVPN_CONFIG? Do you link the file to it somehow or do you just paste the name?

Thanks for your help

**Comment by haugene** [comment]
@pejotll: You just paste the name, minus the .ovpn extension.

So to use `au-11.protonvpn.com.udp.ovpn` you would set `OPENVPN_CONFIG=au-11.protonvpn.com.udp`

**Comment by pejotll** [comment]
@h45rd many thanks.
