### ISSUE TITLE
Setup problem with rpi OMV docker armhf

### ISSUE THREAD

**Issue by cihat1** [haugene/docker-transmission-openvpn#730]
Hi, 
I have a Rpi 3b+ with OMV 4. I installed the transmission-openvpn container with armhf tag through docker, and used the guide on the OMV forum to set it up. Even tough i added LOCAL_NETWORK=192.168.1.0/24 parameter, as soon as i start the container it stucks on loading in the omv docker ui, and i lost connection to my rpi. I cant connect through OMV gui or putty even after reboot. (I guess that have smth to do with setting restart policy as always). I installed OMV from start like 5 times since i cant connect to my RPI after starting the container. I d like any help. Thanks in advance.

**Comment by h45rd** [comment]
> [...] and i lost connection to my rpi. I cant connect through OMV gui or putty even after reboot.

So no shell access via SSH? Via local terminal (monitor & keyboard)?
Does the rpi still give a ping response in this scenario?

Since the rpi is pretty starved for resources to begin with, a failing and constantly restarting container might push it over the edge.

For further diagnosis you will have to start by posting the [container logs](https://docs.docker.com/engine/reference/commandline/container_logs/).

The easiest way to extract them if the rpi is caught in a bootloop, would be to access the SD card directly. Alternatively you could set the container restart policy to manual and access them after a hard-reset.
A third option would be to set up remote logging.

**Comment by cihat1** [comment]
As soon as i start the container i cant access via SSH or OMV web interface. I didnt try connecting via HDMI because i dont have a cable. When i reboot the pi i have a 10 sec window that i can connect via SSH but after that the connection is lost and i cant access again. I dont have logs because i cant connect via ssh. Since i cant access i dont know whats going on. When that happens i reinstall OMV on the sd card from start and try again.

**Comment by h45rd** [comment]
For getting to the logs, see the last paragraph of my last post.
E.g.: Fresh install. Create container as always, but omit automatic restart policy. Hard-reset rpi a couple of minutes after the manual container start freezes the system. Extract logs. Post logs.

Without them, any debugging would have to be done via crystal balls and tea leaves :)

**Comment by haugene** [comment]
Holy shit that sound frustrating. And don't take this the wrong way but I had to laugh a bit as well 😆  I've been in the situation where I need to race my computer to get something done before "X happens" and it's a steep uphill battle.

Anyways. I'll try to be of help :) First of all, don't start the container with `--restart=always`. This is what triggers it to start together with the Docker daemon on startup and also the things that is giving you the 10 seconds (I guess). Then the logs will be easier to get to after a reboot.

Could you post your docker run command? I have a feeling that you've started it with `--network=host`? That would explain it at least. That would put the complete host networking under VPN and even your SSH traffic would not get out. I agree that the LOCAL_NETWORK parameter should have fixed this, but there could be some "alternative routing" here making that parameter tougher to get right.

PS: Just saw @h45rd's answer pop up here, but I'll just post as it was written. You can merge them mentally ;)

**Comment by cihat1** [comment]
Don't worry i also started laughing to it after 5 formats :) Yes i started with "network mode=host". I am following the guide from the OMV forum that is why i do that. I tried with "restart=none" and i can at least connect after a reboot, that's a good start :) 

I started the container, it freezes, then i got a reboot. Then in SSH console i wrote 
"docker container logs transmissionopenvpn" nothing happens. So i cant manage to get any logs. Did i forget smth? 

I extract the container details from OMV docker ui and attach below. 

[containerDetails.txt](https://github.com/haugene/docker-transmission-openvpn/files/2947220/containerDetails.txt)

**Comment by cihat1** [comment]
I get some logs after a few trial/errors. 

{"log":"Using OpenVPN provider: CUSTOM\n","stream":"stdout","time":"2019-03-08T22:26:09.649238265Z"}
{"log":"No VPN configuration provided. Using default.\n","stream":"stdout","time":"2019-03-08T22:26:09.650518053Z"}
{"log":"Setting OPENVPN credentials...\n","stream":"stdout","time":"2019-03-08T22:26:09.651153468Z"}
{"log":"adding route to local network 192.168.1.0/24 via 192.168.1.1 dev enxb827eb928f66\n","stream":"stdout","time":"2019-03-08T22:26:09.982481962Z"}
{"log":"Sat Mar  9 01:26:10 2019 WARNING: file '/config/openvpn-credentials.txt' is group or others accessible\n","stream":"stdout","time":"2019-03-08T22:26:10.240047892Z"}
{"log":"Sat Mar  9 01:26:10 2019 OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017\n","stream"$
{"log":"Sat Mar  9 01:26:10 2019 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08\n","stream":"stdout","time":"2019-03-08T22:26:10.241006066Z"}
{"log":"Sat Mar  9 01:26:10 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts\n","stream":"stdout","time":"2019-03-$
{"log":"Sat Mar  9 01:26:10 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication\n","stream":"stdout","time":"2019-03-0$
{"log":"Sat Mar  9 01:26:10 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication\n","stream":"stdout","time":"2019-03-0$
{"log":"Sat Mar  9 01:26:10 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]84.16.224.15:1195\n","stream":"stdout","time":"2019-03-08T22:26:10.298828361Z"}
{"log":"Sat Mar  9 01:26:10 2019 Socket Buffers: R=[163840-\u003e327680] S=[163840-\u003e327680]\n","stream":"stdout","time":"2019-03-08T22:26:10.298984871Z"}
{"log":"Sat Mar  9 01:26:10 2019 UDP link local: (not bound)\n","stream":"stdout","time":"2019-03-08T22:26:10.299547109Z"}
{"log":"Sat Mar  9 01:26:10 2019 UDP link remote: [AF_INET]84.16.224.15:1195\n","stream":"stdout","time":"2019-03-08T22:26:10.299757421Z"}
{"log":"Sat Mar  9 01:26:10 2019 TLS: Initial packet from [AF_INET]84.16.224.15:1195, sid=07ad5f48 c5ab95ef\n","stream":"stdout","time":"2019-03-08T22:26:10.358739139Z"}
{"log":"Sat Mar  9 01:26:10 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this\n","stream":"stdout","time":"2019-$
{"log":"Sat Mar  9 01:26:10 2019 VERIFY OK: depth=1, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=ExpressVPN CA, emailAddress=support@expressvpn.com\n","stream":"stdout","$
{"log":"Sat Mar  9 01:26:10 2019 VERIFY OK: nsCertType=SERVER\n","stream":"stdout","time":"2019-03-08T22:26:10.435957579Z"}
{"log":"Sat Mar  9 01:26:10 2019 VERIFY X509NAME OK: C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-3741-0a, emailAddress=support@expressvpn.com\n","stream":"stdout",$
{"log":"Sat Mar  9 01:26:10 2019 VERIFY OK: depth=0, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-3741-0a, emailAddress=support@expressvpn.com\n","stream":"stdout",$
{"log":"Sat Mar  9 01:26:10 2019 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA\n","stream":"stdout","time":"2019-03-08T22:26:10.596$
{"log":"Sat Mar  9 01:26:10 2019 [Server-3741-0a] Peer Connection Initiated with [AF_INET]84.16.224.15:1195\n","stream":"stdout","time":"2019-03-08T22:26:10.597022203Z"}
{"log":"Sat Mar  9 01:26:11 2019 SENT CONTROL [Server-3741-0a]: 'PUSH_REQUEST' (status=1)\n","stream":"stdout","time":"2019-03-08T22:26:11.657610632Z"}
{"log":"Sat Mar  9 01:26:11 2019 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.130.0.1,comp-lzo no,route 10.130.0.1,topology net30,pi$
{"log":"Sat Mar  9 01:26:11 2019 OPTIONS IMPORT: timers and/or timeouts modified\n","stream":"stdout","time":"2019-03-08T22:26:11.717271202Z"}
{"log":"Sat Mar  9 01:26:11 2019 OPTIONS IMPORT: compression parms modified\n","stream":"stdout","time":"2019-03-08T22:26:11.717457869Z"}
{"log":"Sat Mar  9 01:26:11 2019 OPTIONS IMPORT: --ifconfig/up options modified\n","stream":"stdout","time":"2019-03-08T22:26:11.717528493Z"}
{"log":"Sat Mar  9 01:26:11 2019 OPTIONS IMPORT: route options modified\n","stream":"stdout","time":"2019-03-08T22:26:11.717790524Z"}
{"log":"Sat Mar  9 01:26:11 2019 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified\n","stream":"stdout","time":"2019-03-08T22:26:11.717857243Z"}
{"log":"Sat Mar  9 01:26:11 2019 OPTIONS IMPORT: peer-id set\n","stream":"stdout","time":"2019-03-08T22:26:11.71797943Z"}
{"log":"Sat Mar  9 01:26:11 2019 OPTIONS IMPORT: adjusting link_mtu to 1629\n","stream":"stdout","time":"2019-03-08T22:26:11.71822646Z"}
{"log":"Sat Mar  9 01:26:11 2019 OPTIONS IMPORT: data channel crypto options modified\n","stream":"stdout","time":"2019-03-08T22:26:11.718293127Z"}
{"log":"Sat Mar  9 01:26:11 2019 Data Channel Encrypt: Cipher 'AES-256-GCM' initialized with 256 bit key\n","stream":"stdout","time":"2019-03-08T22:26:11.718983854Z"}
{"log":"Sat Mar  9 01:26:11 2019 Data Channel Decrypt: Cipher 'AES-256-GCM' initialized with 256 bit key\n","stream":"stdout","time":"2019-03-08T22:26:11.719439322Z"}
{"log":"Sat Mar  9 01:26:11 2019 ROUTE_GATEWAY 192.168.1.1/255.255.255.0 IFACE=enxb827eb928f66 HWADDR=b8:27:eb:92:8f:66\n","stream":"stdout","time":"2019-03-08T22:26:11.720$
{"log":"Sat Mar  9 01:26:11 2019 TUN/TAP device tun0 opened\n","stream":"stdout","time":"2019-03-08T22:26:11.748976118Z"}
{"log":"Sat Mar  9 01:26:11 2019 TUN/TAP TX queue length set to 100\n","stream":"stdout","time":"2019-03-08T22:26:11.749366273Z"}
{"log":"Sat Mar  9 01:26:11 2019 do_ifconfig, tt-\u003edid_ifconfig_ipv6_setup=0\n","stream":"stdout","time":"2019-03-08T22:26:11.749432471Z"}
{"log":"Sat Mar  9 01:26:11 2019 /sbin/ip link set dev tun0 up mtu 1500\n","stream":"stdout","time":"2019-03-08T22:26:11.749496273Z"}
{"log":"Sat Mar  9 01:26:11 2019 /sbin/ip addr add dev tun0 local 10.130.0.146 peer 10.130.0.145\n","stream":"stdout","time":"2019-03-08T22:26:11.749569502Z"}
{"log":"Sat Mar  9 01:26:11 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1557 10.130.0.146 10.130.0.145 init\n","stream":"stdout","time":"2019-03-08T22:26:11.755783704Z"}
{"log":"Up script executed with tun0 1500 1557 10.130.0.146 10.130.0.145 init\n","stream":"stdout","time":"2019-03-08T22:26:11.770836112Z"}
{"log":"Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.130.0.146\n","stream":"stdout","time":"2019-03-08T22:26:11.771247778Z"}
{"log":"Using Transmission Web Control  UI, overriding TRANSMISSION_WEB_HOME\n","stream":"stdout","time":"2019-03-08T22:26:11.77134835Z"}
{"log":"Generating transmission settings.json from env variables\n","stream":"stdout","time":"2019-03-08T22:26:11.771376319Z"}
{"log":"sed'ing True to true\n","stream":"stdout","time":"2019-03-08T22:26:11.907448822Z"}
{"log":"\n","stream":"stdout","time":"2019-03-08T22:26:11.948948034Z"}
{"log":"-------------------------------------\n","stream":"stdout","time":"2019-03-08T22:26:11.949189127Z"}
{"log":"Transmission will run as\n","stream":"stdout","time":"2019-03-08T22:26:11.949230221Z"}
{"log":"-------------------------------------\n","stream":"stdout","time":"2019-03-08T22:26:11.949255533Z"}
{"log":"User name:   root\n","stream":"stdout","time":"2019-03-08T22:26:11.949283398Z"}
{"log":"User uid:    0\n","stream":"stdout","time":"2019-03-08T22:26:11.949309491Z"}
{"log":"User gid:    0\n","stream":"stdout","time":"2019-03-08T22:26:11.949337356Z"}
{"log":"-------------------------------------\n","stream":"stdout","time":"2019-03-08T22:26:11.949364075Z"}
{"log":"\n","stream":"stdout","time":"2019-03-08T22:26:11.949397981Z"}
{"log":"STARTING TRANSMISSION\n","stream":"stdout","time":"2019-03-08T22:26:11.949421679Z"}
{"log":"NO PORT UPDATER FOR THIS PROVIDER\n","stream":"stdout","time":"2019-03-08T22:26:11.949880115Z"}
{"log":"Transmission startup script complete.\n","stream":"stdout","time":"2019-03-08T22:26:11.949957979Z"}
{"log":"STARTING TINYPROXY\n","stream":"stdout","time":"2019-03-08T22:26:11.963890026Z"}
{"log":"Setting tinyproxy port to 8888\n","stream":"stdout","time":"2019-03-08T22:26:11.968899596Z"}
{"log":"sed: can't read /etc/tinyproxy.conf: No such file or directory\n","stream":"stderr","time":"2019-03-08T22:26:11.97232542Z"}
{"log":"sed: can't read /etc/tinyproxy.conf: No such file or directory\n","stream":"stderr","time":"2019-03-08T22:26:11.976059681Z"}
{"log":"Starting Tinyproxy lightweight HTTP proxy daemon: tinyproxy.\n","stream":"stdout","time":"2019-03-08T22:26:12.178999401Z"}
{"log":"Tinyproxy startup script complete.\n","stream":"stdout","time":"2019-03-08T22:26:12.179514764Z"}
{"log":"Sat Mar  9 01:26:14 2019 /sbin/ip route add 84.16.224.15/32 via 192.168.1.1\n","stream":"stdout","time":"2019-03-08T22:26:14.24235443Z"}
{"log":"Sat Mar  9 01:26:14 2019 /sbin/ip route add 0.0.0.0/1 via 10.130.0.145\n","stream":"stdout","time":"2019-03-08T22:26:14.248755767Z"}
{"log":"Sat Mar  9 01:26:14 2019 /sbin/ip route add 128.0.0.0/1 via 10.130.0.145\n","stream":"stdout","time":"2019-03-08T22:26:14.255407052Z"}
{"log":"Sat Mar  9 01:26:14 2019 /sbin/ip route add 10.130.0.1/32 via 10.130.0.145\n","stream":"stdout","time":"2019-03-08T22:26:14.26343927Z"}
{"log":"Sat Mar  9 01:26:14 2019 Initialization Sequence Completed\n","stream":"stdout","time":"2019-03-08T22:26:14.267250874Z"}

**Comment by haugene** [comment]
@cihat1 This looks correct. OpenVPN is connected and Transmission is starting.

I'm still pretty sure the --network=host needs to go. Are you still using that?
One of the major points of this image is to be able to run VPN containerised so that you don't affect the host. Setting that parameter effectively removes the containerised networking.

If you then exec into the container and run `curl localhost:9091` you should get a response from Transmission. And if you can't reach it from outside the OMV you need to look more at the local network stuff.

But first. Run it without network=host

--

There's also a couple of minor stuff showing up in the logs. None of these are blockers for now. But I'll comment on it anyways.

The first thing is this line:
```
{"log":"Sat Mar  9 01:26:11 2019 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.130.0.1,comp-lzo no,route 10.130.0.1,topology net30,ping 10,ping-restart 60,ifconfig 10.130.0.146 10.130.0.145,peer-id 13,cipher AES-256-GCM'\n","stream":"stdout","time":"2019-03-08T22:26:11.716552663Z"}
```

Just note that your provider is overriding the ping-exit option if you've set it. There is something about pull-filters in the README. Have a look.

The second issue is that tinyproxy config isn't set correctly. But that can be followed up in #681, a fix seems to be on the way.

**Comment by haugene** [comment]
Oh yeah. And for getting container logs:
```
docker logs transmissionopenvpn
```
Not
```
docker container logs transmissionopenvpn
```

**Comment by cihat1** [comment]
Yes i guessed it is working as intended. All the guides i saw sets network=host thats why i insisted on that and actually i dont know which option i should choose instead and how to set it.

From ppls logs i saw that their container routes to dockers interface like 172.x.x.x which makes sense. But according to my logs, my container routes to default gw 192.168.1.1. I guess thats why this happens but i m no expert.

What is the other option to network=host and how can i do that?

**Comment by haugene** [comment]
You will get 172.x.x.x as long as you're not doing network=host. You're getting your host networking 192.168.x.x because of it.

You don't need to set anything else. Just remove it. It will go with the default bridge mode. https://docs.docker.com/engine/reference/run/#network-settings

**Comment by cihat1** [comment]
Ok i ll try that tonight. Why the guides selecting host mode then. What is the difference between host and brigde? Just being curious :)

**Comment by cihat1** [comment]
The whole point of your container is to seperate the whole traffic from transmission for vpn. So why would anyone select host mode for this container.

**Comment by haugene** [comment]
Exactly. I don't know why anyone would do that.

There have been requests for allowing the container to run without VPN. People have found the Transmission functionality with alternate web ui and other stuff interesting, but they're running on a host with VPN and don't need the VPN functionality. Maybe in such a scenario one could use VPN on the host, but run in this container just to get the other stuff. I'm not sure.

In any case I don't recommend it. All the reasons I can think of for doing it that way sounds like a hack for something else. Would be interesting to hear if someone has a good reason for it.

**Comment by cihat1** [comment]
I tried bridge mode, it started normal and i did not lose connection to rpi, but now i cant connect to transmission webui. I wrote 192.168.1.30:9091 , 192.168.1.30:9091/transmission/ , 192.168.1.30:9091/transmission/rpc/ all failed. 192.168.1.30 is my rpi's ip address.

my container setup : 
[containerDetails.txt](https://github.com/haugene/docker-transmission-openvpn/files/2948911/containerDetails.txt)

container log:
[containerLogs.txt](https://github.com/haugene/docker-transmission-openvpn/files/2948914/containerLogs.txt)

**Comment by haugene** [comment]
Well. This looks good I think. The container is probably running as it should by now. You can verify this by exec'in into the container and running `curl localhost:9091`.

I think your current problem with connecting to the web ui is the same issue as you had before when running network=host and couldn't connect to the host at all. Are you sure there are not more subnets at play here? That there isn't a virtual network in OMV or something?

LOCAL_NETWORK is setting up a route in iptables to allow traffic to that range. The probable reason traffic is not being returned is that it doesn't see you as a remote address within the range you've given.

LOCAL_NETWORK is a neat way to get access to the web ui, but different network setups can cause different issues. Try running the proxy that is described in the README, that should work.

**Comment by cihat1** [comment]
Ok i found a solution again with trial/errors->hairloss risk :) 
I set to bridge mode and used port forwarding, host ip is my RPI's IP.
At least i reached to transmission webUI. Lets see if everything works now. I ll give updates.
![image](https://user-images.githubusercontent.com/48334144/54085414-edf0c480-434e-11e9-93f5-12e46df6993a.png)

**Comment by cihat1** [comment]
I tested many things (manual dl, auto dl for sonarr, radarr etc.), it works as intended. Thanks for the good work and help.

**Comment by haugene** [comment]
Glad to hear it! You're welcome.

Just to make sure. Did you end up using LOCAL_NETWORK or the proxy to access the WebUI? And if you went for LOCAL_NETWORK, what value did you set? I've seen people put values that efficiently disables the VPN, like `0.0.0.0/0` (**TO OTHERS: DON'T!**), and just want to make sure you didn't ;)

**Comment by cihat1** [comment]
I used LOCAL_NETWORK=192.168.1.0/24, did not use proxy. 
I just used bridge mode and port forwarding as i told in previous post. The rest is all same with the guide on OMV forum. The guide tells to set host for network mode that is why it did not work for me.

**Comment by haugene** [comment]
I see. Then it all sounds good! You should post a correction to that saying that you should not use network=host. There's been several cases of people having issues because they set that parameter.

**Comment by cihat1** [comment]
Yea, i dont know why they choose the host mode. I am new to rpi, dockers and stuff thats why i struggled :) and i put a lot of detail in this topic here so that may help those who struggled.
