### ISSUE TITLE
Tinyproxy config in different location on armhf image

### ISSUE THREAD

**Issue by haugene** [haugene/docker-transmission-openvpn#732]
We use sed to set the tinyproxy config before starting it. This file is in another location on armhf than it is in the alpine and ubuntu version of the image.

This issue is a follow-up of the discussion that started in #681. A fix has been pushed to the dev branch. Hopefully @neil123454 @Xyv @dipietro-salvatore can confirm that it is working on the dev tag.

Doing some other refactoring and will release to master/latest soon.

**Comment by Xyv** [comment]
Unfortunately I cannot test your changes as the armhf version is no longer built on docker hub.
Thanks for keeping an eye on this issue though!

**Comment by haugene** [comment]
Yes, of course. When it rains it pours. Made a commit for #721 now, hopefully that fixes it and we can finally get new versions of armhf out there 🤞

**Comment by Xyv** [comment]
Everything is working nicely out of the box now, you can close this issue. Thanks again!
