### ISSUE TITLE
Transmission WebUI settings not saving

### ISSUE THREAD

**Issue by gid204** [haugene/docker-transmission-openvpn#733]
When I change setting on transmission using the Webui they will keep their state for a few hours but then when I come back to it to check (maybe a day later) they've gone back to default. There doesn't appear to be a 'save' button so normally I just change the settings and click the 'x' in the top right corner.

Not sure if this is a bug in my setup or maybe I'm doing something wrong..

**Comment by haugene** [comment]
Check this and linked issues #517
