### ISSUE TITLE
Adding Goose to list of providers

### ISSUE THREAD

**Issue by JBS5** [haugene/docker-transmission-openvpn#738]
Is someone able to add Goose (https://goosevpn.com) to the list of providers?
That would be great.

**Comment by haugene** [comment]
Do you have a link to a zip file with all ovpn configs?

**Comment by moekdegroot** [comment]
Will this do? It's all ovpn configs that allow P2P.
[ovpn goose vpn.zip](https://github.com/haugene/docker-transmission-openvpn/files/3164522/ovpn.goose.vpn.zip)

**Comment by mrjackyliang** [comment]
Closing this and merging.

**Comment by robertm5746** [comment]
quick question and I am new to github. Like to understand if the Ovpn files for Goosevpn are available.

**Comment by pkishino** [comment]
> quick question and I am new to github. Like to understand if the Ovpn files for Goosevpn are available.

According to the merge above, the ones from last year were added. If there have been changes since, I don’t know

**Comment by mrjackyliang** [comment]
They were not added. I created an issue tracker, in the beginning, to help merge the VPN file updates but it turned out a failure. So if anyone is willing to do PRs for it, I'll check it out.

**Comment by MartinHotmann** [comment]
> Do you have a link to a zip file with all ovpn configs?

Isn´t this (https://github.com/haugene/docker-transmission-openvpn/issues/1206) what you have been asking for?
