### ISSUE TITLE
proton vpn not working

### ISSUE THREAD

**Issue by kornflex** [haugene/docker-transmission-openvpn#739]
Hello,

I'm using transmission vpn since febuary but, with the latest github/docker update, I can't use it.
I have "auth failed".

I check the user and password twice, copy/paste they are correct. I'm using OpenVPN/IKEv2 Username.

It should work. With their dedicated app or with openVPN, it works.

Thank you for your help

**Comment by haugene** [comment]
Please post your docker run command and logs at least. I don't have much to go on here.
Also check the ovpn configs here in this repo against the ones you get from protonvpn, maybe there's an update? Lastly, have you changed username/password? There has been an issue with special characters in username/password.

**Comment by haugene** [comment]
Btw, ProtonVPN config discussion going on in #684 as well. If this is a config problem we'll follow up in that thread.

**Comment by cat24max** [comment]
I have just tested ProtonVPN with their nl-12 server and it works like a charm.

**Comment by kornflex** [comment]
Sorry,
I was using the Free VPN. It's works for a month as TRIAL but now, I'm not allowed on PAID servers, so I was unable to log in.

**Comment by kornflex** [comment]
Hello,

Today, Port is open with PIA !
I think they fixed the problem
