### ISSUE TITLE
How to keep container components up to date?

### ISSUE THREAD

**Issue by avamk** [haugene/docker-transmission-openvpn#740]
Important components in this Docker container such as OpenVPN or Transmission are updated fairly regularly. Is there a recommended way to keep them updated to the latest versions? Do I have to regularly destroy and re-create the container, or do I do something else? Thank you.

**Comment by haugene** [comment]
Yes. One of the benefits with Docker containers is that you get all of the software packaged and ready to use. The Docker way of doing it is to upgrade the versions in the image and then recreate the containers where they are used.

You can keep your container and exec into it to keep it up to date, but this is not the recommended way. We maintain the image here, upgrading repos and versions and then it is ready to be pulled and recreated for everyone using it.

Closing this issue as it isn't really an issue 😄 In the future, questions like this could also be asked in the gitter chat.
