### ISSUE TITLE
Is there a reason why transmission-web-control is not downloaded from its source repository?

### ISSUE THREAD

**Issue by bperel** [haugene/docker-transmission-openvpn#746]
**Is your feature request related to a problem? Please describe.**
I noticed that transmission-web-control is downloaded from an archive located in https://github.com/ronggang/twc-release/blob/master/src.tar.gz, and not from one of the releases in https://github.com/ronggang/transmission-web-control/releases . Is there a reason for that?

**Describe the solution you'd like**
The differences between the TGZ file in ronggang/twc-release and the one in ronggang/transmission-web-control/releases are quite small, it could be worth it to download the TGZ from the source repository:
- Using the original repository would allow to always download the latest release (using a command like one of those listed in [this gist](https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c)). This is not currently the case : the latest version pushed on https://github.com/ronggang/twc-release is 1.6.0-alpha, but a new release has been published upstream more than 6 months ago (1.6.0-beta2)
- Downloading a TGZ that was manually created by the repo's maintainer defeats the purpose of downloading the package from a versioned source control website. 

**Describe alternatives you've considered**
We can also wait until the src.tar.gz file in https://github.com/ronggang/twc-release is updated, but it sounds like an unnecessary waiting time when the TGZ is already stored somewhere else (in ronggang/transmission-web-control/releases)

**Comment by haugene** [comment]
Hey @bperel. Good question. To the best of my knowledge, I'd say no.
Don't have the time to fix it right now, but would gladly merge a PR on it 😄

**Comment by bperel** [comment]
Created PR : https://github.com/haugene/docker-transmission-openvpn/pull/756

**Comment by haugene** [comment]
Fix merged for all platforms 👍
