### ISSUE TITLE
Mullvad changed his CA certificate

### ISSUE THREAD

**Issue by husimo** [haugene/docker-transmission-openvpn#750]
**Which provider?**
Mullvad

Mullvad changed their CA root certificate. [More information here](https://mullvad.net/en/blog/2019/3/22/suddenly-cant-connect-mullvad/). New certificate is linked.

I mounted the new certificate in the docker container replacing the old one and it's working again.

Thank you !

[mullvad_ca.zip](https://github.com/haugene/docker-transmission-openvpn/files/3000521/mullvad_ca.zip)

**Comment by haugene** [comment]
See #748. We should already be up to date. Try pulling the latest image and it should work?

**Comment by haugene** [comment]
Also just merged #751 as there seemed to be more issues with Mullvads certificate after all.
The latest image now should hopefully be good 👍(once the builds complete)
