### ISSUE TITLE
Bug with NordVPN in latest release

### ISSUE THREAD

**Issue by pseudoyams** [haugene/docker-transmission-openvpn#752]
Hi everyone-
  watchtower seemed to have updated transmission-vpn docker on my system last night.  Now I get the following log msgs over and over.  I tried searching around but came up short. Can anyone help?

> Using OpenVPN provider: NORDVPN
> 2019-03-25 13:16:01 Checking curl installation
> 2019-03-25 13:16:01 Checking unzip installation
> 2019-03-25 13:16:01 Removing existing configs
> 2019-03-25 13:16:01 Downloading latest configs
> 2019-03-25 13:16:01 Checking line endings
> 2019-03-25 13:16:01 Updating configs for docker-transmission-openvpn
> sed: can't read default.ovpn: No such file or directory

**Comment by haugene** [comment]
Merged a new release to master branch (latest tag) yesterday that contained a script to automatically update NordVPN configs. Must be a bug there. #728 #655 

Until it is fixed I think a workaround is to select a config using OPENVPN_CONFIG or revert back to tag `2.6`. Will try to get a fix out within a couple of days. @Troubadoure, able to help out?

**Comment by pseudoyams** [comment]
Adding OPENVPN_CONFIG did allow it to start on the latest image.

Thanks for squashing this one. ;)

**Comment by Troubadoure** [comment]
I've ran into it myself. It's an issue with the updateConfigs.sh script and the default.ovpn symlink. Will take a look, not sure I'll have time tonight though.
