### ISSUE TITLE
Keeps restarting

### ISSUE THREAD

**Issue by AKDub** [haugene/docker-transmission-openvpn#754]
**Describe the problem**
Roughly every 1-2 hours or so the container seems to restart. Seems to be a recent problem as the container has been working fine for months. Made a new test container and it suffers the same problem

**Add your docker run command**
I have set this up on openmediavault so not really sure what this is

**Logs**
From what I can tell the logs below initiate the restarts, I can post more logs if needed.

Tue Mar 26 11:58:38 2019 Connection reset, restarting [0]
Tue Mar 26 11:58:38 2019 SIGUSR1[soft,connection-reset] received, process restarting
Tue Mar 26 11:58:38 2019 Restart pause, 5 second(s)

**Host system:**
OMV 4 on custom intel NAS

**Comment by haugene** [comment]
Did this start occuring the last couple of days? Which VPN provider are you using?
Can you try to use the 2.6 tag of the image and see if that solves it? Looks like there's a couple of bugs with release 2.7 :/

**Comment by AKDub** [comment]
Forgot to add, the VPN provider is NordVPN. I did try a few different servers but that didn't solve anything.

**Comment by AKDub** [comment]
The 2.6 container just reset at the same time as the latest, so there must be something else going on.

**Comment by haugene** [comment]
Could this be the same as #752?
If so it might be solved soon, merged #755 and #757 that addresses NordVPN connection issues.

**Comment by haugene** [comment]
Ah, sorry. Didn't read you last post well enough I think. Getting late for me here.
Can you post the full logs and the content of the .ovpn file after startup?

**Comment by nicomarti83** [comment]
I don't know if it's the same problem but since few days I can't start my container, I've got the same message in loop`Tue Apr  2 18:44:18 2019 Initialization Sequence Completed
Tue Apr  2 18:44:25 2019 Connection reset, restarting [0]
Tue Apr  2 18:44:25 2019 SIGUSR1[soft,connection-reset] received, process restarting`
My vpn provider is purevpn.

**Comment by nicomarti83** [comment]
[log haugene.txt](https://github.com/haugene/docker-transmission-openvpn/files/3036005/log.haugene.txt)
my logs here

**Comment by nicomarti83** [comment]
And now it worked fine all night... Seriously I don't understand the logic...

**Comment by joshobriencom** [comment]
Reviving this thread, this has started happening for me at the same time I moved to the 3.0 version. Also NordVPN, container is restarting sometimes multiple times a minute, other times will go a day or so without issue.

**Comment by haugene** [comment]
@joshobriencom Can you try the 3.1 tag and see if you have the same there?

**Comment by joshobriencom** [comment]
@haugene I've rebuilt with 3.1 and added variable flags --dns 1.1.1.1 --dns 1.0.0.1 for the container incase it was a DNS issue with OpenVPN, as I saw a couple of older posts from other NordVPN users. 

I haven't had it restart since. 

I'll get around to trying just 3.1 without the added DNS flag.

**Comment by krugerm** [comment]
> Reviving again the thread, I'm getting the same error connection reset, restarting [-1], I'm using cyberghost VPN. How can I solve It?

Likewise - this issue seems to have been resurrected.
