### ISSUE TITLE
Need to understand nordvpn/updateConfigs.sh

### ISSUE THREAD

**Issue by rfenouil** [haugene/docker-transmission-openvpn#759]
Hello,

thank you for the great work.
Sorry to open an issue while the script probably works but I need clarification on the code, and I can't find a better way to get in contact with @Troubadoure (who authored many recent changes).

Here are my questions regarding the latest version of the script nordvpn/updateConfigs.sh : 

1. I don't understand the test ```if [[ ! -z $OPENVPN_CONFIG ]] && [[ ! -z $NORDVPN_COUNTRY ]]``` since the variable OPENVPN_CONFIG is not used in subsequent calls.
If I understand correctly ```OPENVPN_CONFIG``` is used to specify a config name to be downloaded from NordVPN server (option "--openvpn-config"), so it should be irrelevant in 'select_hostname' context. Is that correct ?

2. For filters 'country' and 'category', a line with possibly multiple values (separated by ',' or ';') is parsed, but then only the first element is used: ```country=${country[0]//_/ }```
Is that the intended behavior ? 
Maybe I misunderstood the bash command though...

3. For function 'select_hostname', can't we just remove the test ```if [[ "$1" != "-d" ]];``` ?
I think that this option is set based on ```NORDVPN_COUNTRY``` being set but anyway it looks like 'country_filter' will just do nothing if ```NORDVPN_COUNTRY``` is not set (empty array).
Does that sound correct ?

Sorry for the naive questions, I wish I can help but I'm just too scared to alter normal function so I prefer to understand how the scripts works before.

Thank you for your help.

**Comment by Troubadoure** [comment]
1. My plan for this was if both are specified the OPENVPN_CONFIG would be used for the primary connection but then it would also set the backup (default.ovpn) to a connection based in the specified country. if OPENVPN_CONFIG is set and NORDVPN_COUNTRY is unset it will take the NordVPN recommended which usually is a server based in the country you are physically in. Having said that with the api it is probably unlikely the default.ovpn connection would be used but it's left in there to be compliant with the rest of the package.

2. This was script I reused from @bubuntux repo and I think it is their plan to be able to use the script to return multiple configs. We could possibly update it in future to do the same

3. You're correct. I'll admit hadn't thought of it whilst I was rewriting it. Please feel free to change if you wish 👍

**Comment by rfenouil** [comment]
Awesome, thank you for your answer.
I did not change it in this repository as I'm doing many other modifications on my repo, but your comment helped me to understand how the script works.

I'll close the issue, sorry for polluting the repository.
