### ISSUE TITLE
VPN Unlimited provider

### ISSUE THREAD

**Issue by Nightbr** [haugene/docker-transmission-openvpn#766]
Hey guys!
I recreate an issue to handle VPN Unlimited provider. The old global issue is here: https://github.com/haugene/docker-transmission-openvpn/issues/554

**Which provider?**
VPN Unlimited - https://www.vpnunlimitedapp.com

**Where are the configs?**
Here is the latest openvpn config:
[634437CA6F37ACCCA2DA8769F673F554_default_openvpn.zip](https://github.com/haugene/docker-transmission-openvpn/files/3026520/634437CA6F37ACCCA2DA8769F673F554_default_openvpn.zip)

Let me know if you need more info ;) 

I can try to make a PR if it's simple to implement =)

Cheers!

**Comment by haugene** [comment]
Great. If you could try to create a PR that would be great. I'll review and point out stuff that might need to be changed.

It's relatively straight forward. Clone the repo and create a new folder under "openvpn" with the provider configs. Rename them if they have a lot of boilerplate stuff in the names, like "VpnUnlimited_www.blablalba.com.Netherlands.ovpn" is easier if it's just "Netherlands.ovpn".

Apart from that there's always a `auth-user-pass` line in the configs that needs to be changed for `auth-user-pass /config/openvpn-credentials.txt` so it reads the username/password from the container.

And if there's a reference to .ca certificate, the path is different in the container. It's then /etc/openvpn/<provider-name>/ca.crt or whatever the file is.

Then just add a line in the README with the new provider and you should be done. There are other minor stuff that might be relevant, but I'll point it out in the PR if it's the case.
