### ISSUE TITLE
Subshell executions bypass VPN

### ISSUE THREAD

**Issue by rfenouil** [haugene/docker-transmission-openvpn#770]
Hello,

sorry to open an issue again but I don't understand the behaviour of the container.
I run on arm device with openmediavault, transmission and tinyproxy seem to work properly.

When I try to double check my IP address by running `curl -s ipecho.net/plain` inside the container, I get the same result as what I get using my web browser with the proxy. Perfect !

However, when I run `echo $(curl -s ipecho.net/plain)`, it returns my provider's network address...

I cannot find the reason for that, do someone have any idea why running the command in a subshell seems to bypass the VPN ?

I use NordVPN and I set DROP_DEFAULT_ROUTE to true (but it does not change when false).

It does not seem linked to the execution of openvpn program using `exec` statement, though I don't understand why it is not just started with a regular call to openvpn command.

Thak you for your help.

**Comment by haugene** [comment]
Yup, that doesn't make sense. Are you running the command with a one line docker exec?
I.e: `docker exec -it <container> bash -c "echo $(curl -s ipecho.net/plain)"`?

Because in that case it makes sense. The subshell will be evaluated on your host, so the command sent to the container is "echo 1.2.3.4" and it just prints your provider IP as instructed.

The exec statement when starting openvpn is to not start a sub-process but let openvpn take the shell we're running in. From `man bash`:

>  exec [-cl] [-a name] [command [arguments]]
>
> If command is specified, it replaces the shell.  No new process is created.  The arguments become the arguments to command.  If the -l option is supplied, the shell places a dash at the beginning of the zeroth arg passed to  com-mand.   This  is what login(1) does.  The -c option causes command to be executed with an empty environment.  If -a is supplied, the shell passes name as the zeroth argument to the executed command.  If command cannot be executed for some reason, a non-interactive shell exits, unless the shell option execfail is enabled, in which case it returns failure.  An interactive shell returns failure if the file cannot be executed.  If command  is  not  specified, any redirections take effect in the current shell, and the return status is 0.  If there is a redirection error, the return status is 1.

**Comment by rfenouil** [comment]
Owwww that's very stupid of me ! Of course it makes sense, execution is made on the host... Shame one me :/.
I did not realize that because I was using OMV graphic interface to execute the command, lesson learnt...

Thank you so much for your answer.

Regarding the `exec`, yes I had a look at the documentation but I did not understand the actual reason, is it required to get the configuration running or is it just here to save on ressources ?

**Comment by haugene** [comment]
Not sure I can give an exact reason. It is not required I guess, and the resources saved is also minimal.
It was thought to be the "correct way" I guess. The docker container should run openvpn as the root process. But we need to do stuff first, so the script is started and upon completion it hands the shell over to ovpn. But no strong arguments either way here.

**Comment by rfenouil** [comment]
Ok that makes sense.
Thank you very much, let's close the issue and sorry for the lack of common sense regarding the error :)
