### ISSUE TITLE
RSS plugin not supporting HTTP authorization

### ISSUE THREAD

**Issue by YardaX** [haugene/docker-transmission-openvpn#781]
Hi!
I'm trying to start the RSS plugin in a separate docker container. It works very well, however it seems I'm not able to add into the environment username & password when the transmission has the authentication enabled.

These variables are missing completely in the environment.

Did someone manage to run it with the authentication?

**Comment by rubenvarela** [comment]
Seems like the [template file](https://github.com/haugene/docker-transmission-openvpn/blob/0e0f6786a41b504250fb055053f7ae1a7ac8acbc/plugins/rss/transmission-rss.tmpl) for the settings is not passing the value. 

It's missing the username and password entries. Here's an example - https://github.com/nning/transmission-rss/blob/8c13dd87ce23d35ded993e9ff475d610ff4b0a04/transmission-rss.conf.example#L52-L54

On `plugins/rss/transmission-rss.tmpl`  you should be able to add

```
login:
  username: {{ .Env.TRANSMISSION_RPC_USERNAME }}
  password: {{ .Env.TRANSMISSION_RPC_PASSWORD }}
```

**Comment by YardaX** [comment]
Thanks! I will look into it.

**Comment by mrjackyliang** [comment]
Looks solved! Closing for now. Let us know if there additional issues.

**Comment by canzone** [comment]
Hello. I know this was closed long ago, but this issue still remains in the latest version of this docker container. Would you please add it to the latest version, so the fix we apply manually won't be overwritten when we pull upgrades from docker? Thanks a lot.

**Comment by pkishino** [comment]
> Hello. I know this was closed long ago, but this issue still remains in the latest version of this docker container. Would you please add it to the latest version, so the fix we apply manually won't be overwritten when we pull upgrades from docker? Thanks a lot.

create a PR with the fix and I'll take a look
