### ISSUE TITLE
Add Ghost Path VPN as a provider

### ISSUE THREAD

**Issue by siopao** [haugene/docker-transmission-openvpn#782]
Would it be possible to add Ghost Path VPN to the list of providers? They have a custom Open VPN client, but have the config files available for download.
[GhostPathVPN.zip](https://github.com/haugene/docker-transmission-openvpn/files/3096369/GhostPathVPN.zip)

https://ghostpath.com/servers

Attached are a few of them, I couldn't figure out how to manually download all of them at once.

**Comment by haugene** [comment]
Merged #777 and Ghostpath should be available now. Will you test and report back and close the issue if it's working as expected?

**Comment by siopao** [comment]
Sorry for the delay and thanks for the help. I'm getting an authentication error, but it's connecting to an unfamiliar IP address:

Wed May  1 13:45:14 2019 [VPN] Peer Connection Initiated with [AF_INET]173.255.139.216:443
Wed May  1 13:45:15 2019 AUTH: Received control message: AUTH_FAILED

**Comment by haugene** [comment]
Great. Closing this then
