### ISSUE TITLE
CREATE_TUN_DEVICE gives Operation not permitted

### ISSUE THREAD

**Issue by jmrushing** [haugene/docker-transmission-openvpn#788]
After removing the devices: /dev/net/tun flag, and switching to the CREATE_TUN_DEVICE=true environment variable, I keep getting Operation not permitted errors.

Only made 2 changes to my previously working docker-compose.yml...
REMOVED:
```
    devices:
      - /dev/net/tun

```

ADDED:
```
    environment:
      - CREATE_TUN_DEVICE=true
```

**Logs**
```
mknod: /dev/net/tun: Operation not permitted
chmod: cannot access '/dev/net/tun': No such file or directory
Using OpenVPN provider: NORDVPN
<---edited for brevity, the rest goes on normally until---->
Mon Apr 22 22:43:56 2019 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Mon Apr 22 22:43:56 2019 Exiting due to fatal error
```
Then the whole process starts over and does the same thing

**Host system:**
LXD/LXC container: Ubuntu 18.04 LTS amd64 (minimal release) (20190320)
security.nesting: "true" (to allow docker to run inside "host" linux container)

This is obviously a permission error, but I can't see why it's happening now since device: /dev/net/tun worked just fine before. Does using the environment variable require that the permissions (inside the docker container) be elevated some way? This may be related to #706

**Comment by haugene** [comment]
Please share the rest of your docker-compose.yml. All the TRANSMISSION_ options are not that relevant, but the rest could be important. Like are you running with PUID/PGUID? Are you running in privileged mode or NET_ADMIN capability, if any?

No other log lines that could be relevant?

**Comment by dennisvanderpool** [comment]
For me the solution was to reboot host if I remember correctly. I had installed Photon OS updates but didn't reboot yet.

**Comment by jmrushing** [comment]
@haugene 
Sorry for the late reply. I've been experimenting without alternatives outside docker and haven't had time to circle back on this. Here's a [link to my docker-compose](https://gist.github.com/jmrushing/782f6b0c3bf4257feede6850e258971e) as requested. Fair warning, it's pretty long as it contains my entire media download automation config.

The variables scattered throughout are provided by my /etc/environment file:
```
PUID=1000
PGID=999
TZ="America/Chicago"
USERDIR="/home/ubuntu"
```
Everything works flawlessly with the old "devices: - /dev/net/tun", but switching to "environment: - CREATE_TUN_DEVICE=true" causes the `mknod: /dev/net/tun: Operation not permitted` error.

**Comment by koenvanderlinden** [comment]
@jmrushing You should run the container in 'Privileged mode'.
