### ISSUE TITLE
New VPN provider ivacy?

### ISSUE THREAD

**Issue by vkim** [haugene/docker-transmission-openvpn#79]
Hi,

Could anyone add ivacy as a new VPN provider?

Thanks,
Vitaliy

**Comment by haugene** [comment]
Hey. Finally had the time to take a look at this one. I've added Ivacy as a provider now.
Test it out and let me know if it works or not! :)

**Comment by vkim** [comment]
Thanks, a lot!

**Comment by haugene** [comment]
Np! :)
