### ISSUE TITLE
Nordvpn, port, sock5?

### ISSUE THREAD

**Issue by garffi** [haugene/docker-transmission-openvpn#790]
Hello,

I have a problem with nordvpn: port block and exchange very long.

How to configure you nordvpn with the container.
Port 1080 is supposed to be open but it's for sock5.
Can we do sock5 with transmission?
As indicated on this link:
https://nordvpn.com/fr/tutorials/socks5/bittorrent/

Thank you

**Comment by niXta1** [comment]
Port 1080 works fine for NordVPN with openVPN.

**Comment by haugene** [comment]
Scrolling quickly through the guide from your link I don't see how this relates to this image? That seems like a setting in a bittorrent client in order not to use VPN, or am I missing something? If you use this image you will be protected by VPN and don't need to use SOCKS5.

**Comment by niXta1** [comment]
>Scrolling quickly through the guide from your link I don't see how this relates to this image? That seems like a setting in a bittorrent client in order not to use VPN, or am I missing something? If you use this image you will be protected by VPN and don't need to use SOCKS5.

@haugene the user didn’t know that port 1080 was available for VPN as well as SOCK5. Therefore he requested a way to the container with a proxy setup instead of VPN.
He now knows that he can use 1080 in this container with NordVPN’s VPN, and the case is closed.

**Comment by haugene** [comment]
Allright, thanks! 😄

**Comment by pkishino** [comment]
hello..long time since I participated in the project.. but I just wanted to comment that no, port 1080 does not work with Nordvpn any longer, only for socks5..not with transmission port-forwarding.
So nordvpn is pretty much useless for p2p use now..still trying to get a refund for my extension I did recently..

**Comment by niXta1** [comment]
Correct, port 1080 was opened with NordVPN on VPN but they have since closed it.
Avoid NordVPN like the plague.
