### ISSUE TITLE
Access via VPN

### ISSUE THREAD

**Issue by Piotr1122** [haugene/docker-transmission-openvpn#793]
In the end, I managed to start working haugene / transmission-openvpn on NAS QNAP. I have only one problem. 

Transmission in the local network has the address 192.168.0.102:9091, it works fine, connecting to NordVPN, all computers have access to it. I also have an OpenVPN server placed on the router, if I connect to it from outside, I do not have access to 192.168.0.102:9091. 
I installed second OpenVPN server (on NAS) to testing, and it does not connect with transmission too.

**Comment by haugene** [comment]
Question is, are you using the proxy or LOCAL_NETWORK to access the webui?
If you're setting LOCAL_NETWORK, what is it set to?

And what is your IP when you're connected through the VPN to your home? If it's not within the range of LOCAL_NETWORK it will be blocked by the container VPN.

Also see #699 and #687

**Comment by Piotr1122** [comment]
I using LOCAL_NETWORK and its set to:
-e LOCAL_NETWORK=192.168.0.0/24
My ip when i connected from outside is from range: 10.8.0.2-254

I change VPN range to 192.168.1.2-254
and LOCAL_NETWORK=192.168.0.0/23

It works. Thanks!
Can it stay like that or is there a better way?

**Comment by haugene** [comment]
That's a good solution 👍 

It's either that (getting the VPN range within/around the existing local network range) or adding a new range in LOCAL_NETWORK. You can have several ranges defined separated by comma.

**Comment by beneix** [comment]
Piotr1122 - would you mind sharing with me the settings you use to get haugene/transmission-vpn to run on your QNAP? I have made many attempts but something keeps stopping the container after it has run for about 20-30 seconds. This is the command I use to start mine (I do it from the command line because it is easier than going through the web interface for Container Station).

docker run --cap-add=NET_ADMIN -d \
              -v /share/Download/transmission:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=SURFSHARK \
              -e OPENVPN_CONFIG=fr-mrs_udp \
              -e OPENVPN_USERNAME=<my user name> \
              -e OPENVPN_PASSWORD=<my password> \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.1.0/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn

**Comment by Piotr1122** [comment]
`docker run --privileged --restart always --name transmission-openvpn --cap-add=NET_ADMIN -d \
              -v /share/Download/transmission/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=NORDVPN \
              -e OPENVPN_USERNAME=xxxxxx \
              -e OPENVPN_PASSWORD=xxxxxx \
              -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
              -e WEBPROXY_ENABLED=false \
              -e TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true \
              -e TRANSMISSION_RPC_USERNAME=admin \
              -e TRANSMISSION_RPC_PASSWORD=xxxxxx \
              -e LOCAL_NETWORK=192.168.0.0/24,10.8.0.0/24,10.8.1.0/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn`

**Comment by beneix** [comment]
Many thanks!
