### ISSUE TITLE
Files not being moved to "Complete" Folder

### ISSUE THREAD

**Issue by mokshmridul** [haugene/docker-transmission-openvpn#796]
I have configured transmission to download files to an incomplete folder, but after completion it does not move the completed files to the completed folder.

Screenshots of my configuration can be found below
https://i.imgur.com/V7zwpmd.png

**Logs**

**Host system:**
Docker is running on Ubuntu 19.04
Docker versions details are:

``Client:
`` Version:           18.09.5
`` API version:       1.39
`` Go version:        go1.10.8
`` Git commit:        e8ff056
`` Built:             Thu Apr 11 04:43:57 2019
`` OS/Arch:           linux/amd64
`` Experimental:      false

The drive is network drive, which is mounted with the needed permissions

**Comment by luluhoc** [comment]
mount it like that and it should work
![image](https://user-images.githubusercontent.com/22813220/56864780-bbfef480-69c6-11e9-86bd-1e7627639469.png)

**Comment by mrjackyliang** [comment]
Looks like this issue is solved. Closing for now.
