### ISSUE TITLE
Configure Transmission using env vars

### ISSUE THREAD

**Issue by ianneub** [haugene/docker-transmission-openvpn#8]
If you would accept a PR, I'd like to create env vars that will override the transmissions config options at start up. This would let the image be a lot more configurable, without requiring a user to mount a config folder.

What do you think?

**Comment by ianneub** [comment]
This would also be good for the openvpn settings, specifically the pia credentials and the remote hostname.

**Comment by haugene** [comment]
This looks sweet! See my comments on the PR, and lets get it in there :+1:
