### ISSUE TITLE
new IVACY provider issues I think.

### ISSUE THREAD

**Issue by nravanelli** [haugene/docker-transmission-openvpn#803]
**Describe the problem**
This was working just fine... and recently became an issue. I believe the issue resides with OpenVPN;

```
Sun May  5 06:22:40 2019 ERROR: Linux route add command failed: external program exited with error status: 2
Sun May  5 06:22:40 2019 Initialization Sequence Completed
```

I am using IVACY and it worked just fine previously..., I tried different config files too in case it was just a region error...

**Add your docker run command**
Using OpenMediaVault Docker and latest transmission-haugene build

**Logs**
```
Using OpenVPN provider: IVACY
Starting OpenVPN using config GermanyFrankfurtTCP.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Sun May  5 06:22:34 2019 WARNING: file '/etc/openvpn/ivacy/Wdc.key' is group or others accessible
Sun May  5 06:22:34 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Sun May  5 06:22:34 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sun May  5 06:22:34 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Sun May  5 06:22:34 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun May  5 06:22:34 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]188.72.83.2:80
Sun May  5 06:22:34 2019 Attempting to establish TCP connection with [AF_INET]188.72.83.2:80 [nonblock]
Sun May  5 06:22:35 2019 TCP connection established with [AF_INET]188.72.83.2:80
Sun May  5 06:22:35 2019 TCP_CLIENT link local: (not bound)
Sun May  5 06:22:35 2019 TCP_CLIENT link remote: [AF_INET]188.72.83.2:80
Sun May  5 06:22:35 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun May  5 06:22:36 2019 [Secure-Server] Peer Connection Initiated with [AF_INET]188.72.83.2:80
Sun May  5 06:22:37 2019 TUN/TAP device tun0 opened
Sun May  5 06:22:37 2019 /sbin/ip link set dev tun0 up mtu 1500
Sun May  5 06:22:37 2019 /sbin/ip addr add dev tun0 188.72.83.157/26 broadcast 188.72.83.191
Sun May  5 06:22:37 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1560 188.72.83.157 255.255.255.192 init
Up script executed with tun0 1500 1560 188.72.83.157 255.255.255.192 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 188.72.83.157
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1000:100
Setting permission for files (644) and directories (755)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    100
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
RTNETLINK answers: File exists
Sun May  5 06:22:40 2019 ERROR: Linux route add command failed: external program exited with error status: 2
Sun May  5 06:22:40 2019 Initialization Sequence Completed
```

**Host system:**
Docker (Linux OMV)

**Comment by Todapie** [comment]
I am having a similar issue with my container normally it goes unhealthy part way through and prints
`
Wed May 22 02:35:22 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.


Wed May 22 02:35:22 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts


Wed May 22 02:36:42 2019 RESOLVE: Cannot resolve host address: usnj2-ovpn-tcp.ivacy.net:80 (Temporary failure in name resolution)


Wed May 22 02:38:03 2019 RESOLVE: Cannot resolve host address: usnj2-ovpn-tcp.ivacy.net:80 (Temporary failure in name resolution)


Wed May 22 02:38:03 2019 Could not determine IPv4/IPv6 protocol


Wed May 22 02:38:03 2019 SIGUSR1[soft,init_instance] received, process restarting`

over and over again

**Comment by haugene** [comment]
@nravanelli Does the WebUI still work? I think this error is just the openvpn daemon trying to add a route that is already there. If it still works I think you can ignore it.

@Todapie That's something else. Seems like the classic DNS issue which is listed first under "Known Issues" of the README. Try adding `--dns 8.8.8.8 --dns 8.8.4.4` to your run command and see if that fixes it.

**Comment by Todapie** [comment]
@haugene My original problem in this is no longer occurring but I am now having the same issue as @nravanelli In my case the WebUI does still work the only problem in this case is that it will not retrieve metadata and start torrenting in this case. Probably the case that transmission is working but the route failed issue is openvpn failing and thus transmission works but doesn't torrent without the vpn. What steps could I take to try to see if it is the openvpn daemon problem?

**Comment by bruvv** [comment]
duplicated:
https://github.com/haugene/docker-transmission-openvpn/issues/798
