### ISSUE TITLE
Provider settings change

### ISSUE THREAD

**Issue by theaudiopile** [haugene/docker-transmission-openvpn#807]
**Which provider?**
TRUSTZONE

**Where are the configs?**
https://trust.zone/get_ovpn_file.php?ZoneID=30&UsingAuthFile=1&port=443&proto=tcp
https://trust.zone/downloads/ovpn.zip

**Comment by haugene** [comment]
Thanks to @fetzu for adding the provider in #821. Should be available on the latest tag after it's been built. Can you test and verify that it's working @theaudiopile? Re-open this issue if there are any problems.
