### ISSUE TITLE
Add FastestVPN to providers

### ISSUE THREAD

**Issue by martsimon** [haugene/docker-transmission-openvpn#809]
**Which provider?**
FastestVPN

**Where are the configs?**
https://support.fastestvpn.com/download/openvpn-tcp-udp-config-files/

**Comment by haugene** [comment]
Thanks to @fetzu for adding the provider in #821. Should be available on the latest tag after it's been built. Can you test and verify that it's working @martsimon? Re-open this issue if there are any problems.
