### ISSUE TITLE
Problem with custom VPN

### ISSUE THREAD

**Issue by Capslock2204** [haugene/docker-transmission-openvpn#811]
Hello,

Real noob here. On a fresh install of OMV4 on a Raspberry 3.
I 've installed docker, and configured an image for my first user using DockerfileMYUSER.armhf file (which is a copy of Dockerfile.armhf with environment variable modified).

In extra args I've specified : -v /etc/openvpn/myuser/:/etc/openvpn/custom/

I want to use a custom provider (ca.crt / myuser.crt  / myuser.key  / myuser.ovpn /  ta.key generated via a dedicated server). These files are in /etc/openvpn/myuser/

When I launch my container I've this in the logs : 

```
Using OpenVPN provider: CUSTOM
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
Options error: --ca fails with '/etc/openvpn/custom/ca.crt': No such file or directory
Options error: --cert fails with '/etc/openvpn/custom/myuser.crt': No such file or directory
Sun May 12 08:03:12 2019 WARNING: cannot stat file '/etc/openvpn/custom/myuser.key': No such file or directory (errno=2)
Options error: --key fails with '/etc/openvpn/custom/myuser.key': No such file or directory
Sun May 12 08:03:12 2019 WARNING: cannot stat file '/etc/openvpn/custom/ta.key': No such file or directory (errno=2)
Options error: --tls-auth fails with '/etc/openvpn/custom/ta.key': No such file or directory
Options error: Please correct these errors.
Use --help for more information.
```

And in my /etc/openvpn/custom/myuser.ovpn file, I've specified the complete path of ca.crt / myuser.crt  / myuser.key  /  ta.key.

For example : 

```
# Client
client
dev tun
proto tcp-client
remote XX.XX.XX.XX 443
resolv-retry infinite
cipher AES-256-CBC

# Clés
ca /etc/openvpn/custom/ca.crt
cert /etc/openvpn/custom/myuser.crt
key /etc/openvpn/custom/myuser.key
tls-auth /etc/openvpn/custom/ta.key 1

# Sécurite
nobind
persist-key
persist-tun
comp-lzo
verb 3
```

I don't understand what's wrong with my configuration.
Is it a bug ? 
Many thanks for your help !

**Comment by fetzu** [comment]
Hello,

It might be a crapshoot, but have you tried to set your keys with a simple relative path? (ie "ca ca.crt" instad of "ca /etc/openvpn/custom/ca.crt")
The second thing to look into would be file permissions: is the docker's UID allowed to read those files?

I hope this helps.
Cheers.

**Comment by haugene** [comment]
I agree, that should work. Question (as @fetzu also points to): Are the files really missing? Or is it a permission issue? Do a `docker exec -it <container> bash` and then cd to the openvpn/custom folder and see what's really there.

And what do you mean by "configured for my first user"? Can you share the contents of DockerfileMYUSER.armhf?
