### ISSUE TITLE
Can someone help me add LeVPN config?

### ISSUE THREAD

**Issue by dariokan82** [haugene/docker-transmission-openvpn#813]
Hi guys,

I'm pretty new to all this. I have a lifetime subscription with LeVPN and would love to add them as a provider, but don't know where to start.

I'm happy if someone does it, even happier to learn how to do it :) 

Thanks!

**Comment by fetzu** [comment]
Hey there,

You can check out haugene's explanation in issue #45 or [the relevant section of the readme](https://github.com/haugene/docker-transmission-openvpn#adding-new-providers). It's a pretty straightforward process. You can either go the "Custom" route (for yourself) or add a new provider for everyone to use and make a pull request once that's done.

Cheers !

**Comment by mrjackyliang** [comment]
Merging this with the master issue. You may provide the files pending to be added, thanks!
