### ISSUE TITLE
NORDVPN Open VPN files missing

### ISSUE THREAD

**Issue by darkneo29** [haugene/docker-transmission-openvpn#814]
Been working great then it just stopped.  I noticed on GIT under OpenVPN/NORDVPN there are no files.  This is the error I am getting now

Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/ca193.nordvpn.com.tcp.ovpn:1: html (2.4.7)

**Comment by digitalap3** [comment]
go to issue 764 for directions on the new update that downloads the files.  remember to update your docker image.
