### ISSUE TITLE
When I activate the docker, all ports closed

### ISSUE THREAD

**Issue by persson1589** [haugene/docker-transmission-openvpn#815]
**Describe the problem**
When I activate the docker, all ports become closed. I can't ssh or do anything, and when I check if ports are open, not a single one is open, they're all closed. But when I stop the docker, port forwaring works again and ports are open? Is it something with openvpn that messes with my router or something? It works when activated but all ports are closed. When I ran freenas on the same network and hardware this never happened, but I ran openvpn in a jail with transmission,

I use ANONINE vpn

**Add your docker run command**
I start it in openmediavault's docker plugin

**

**Host system:**
openmediavault 4

**Comment by fetzu** [comment]
Hello,

Let me try to understand this correctly: when you start the docker container ALL connections to your machine are closed? Have you tried to set "ENABLE_UFW=false" in the environment variables?

**Comment by haugene** [comment]
I have a feeling that you're starting the container with --net=host or the corresponding setting in openmediavault? That would make the VPN connection affect the whole host and could then interrupt other traffic. If it's not that then we need more information. The container can't mess with your router. Something else is going on.

Please provide your settings as best you can (screenshot or whatever). Especially the settings for port-forwarding, network (host?) and LOCAL_NETWORK variable.
