### ISSUE TITLE
Air VPN

### ISSUE THREAD

**Issue by GregHilston** [haugene/docker-transmission-openvpn#817]
**Which provider?**
Air VPN

**Where are the configs?**
These are downloaded when you're logged in and fill out a form.

https://airvpn.org/generator/

![image](https://user-images.githubusercontent.com/4227776/58444828-15863c00-80b7-11e9-9398-3e2fd0452265.png)

**Comment by fetzu** [comment]
Hello Greg, I'd like to help but I don't have an account/don't want to create one.

Could you please generate a set of configs (just pick linux/UDP), and upload to file over to a sharing site and post the link here. **Please double check your credentials aren't showing in the configs before uploading !** Also tell us which ones are suitable for P2P traffic (if not all).

Thanks!

**Comment by haugene** [comment]
The assumption up until now is that there is some sort of private information in these configs and that they cannot be added. This is addressed in the [Using a custom provider](https://github.com/haugene/docker-transmission-openvpn#using-a-custom-provider) part of the README where AirVPN is mentioned as a specific example.

If this is not the case then I agree with @fetzu, generate the configs and provide a link.

**Comment by mrjackyliang** [comment]
Merging and closing.

**Comment by GregHilston** [comment]
I legit just saw this, woops.
