### ISSUE TITLE
Name Resolution and TLS Errors

### ISSUE THREAD

**Issue by Cheezzhead** [haugene/docker-transmission-openvpn#823]
I don't know if these issues are related, but I've been trying to get Transmission with PIA back to a healthy state after it started failing since yesterday. Before that, it worked for a couple of days.

**Describe the problem**
First, I started getting name resolution errors to the PIA server. Pinging to google.com or any other host wouldn't work, although pinging to an IP address still works. Trying with different PIA configuration, including the default one, resulted in the same error. I tried a temporary fix by replacing the hostname of the PIA server with its IP address, but this resulted in a TLS handshake error (similar to the one below, although at the time I figured this was just PIA's way of saying 'don't do this').

Today I removed the container and image, as well as any volumes associated with it in an attempt to start with a clean slate. Then ran a minimal docker run command to test (see below), but the same tls handshake error occurs.

**Add your docker run command**
```
docker run --cap-add=NET_ADMIN -d \
-v /etc/localtime:/etc/localtime:ro \
--device=/dev/net/tun \
-e OPENVPN_PROVIDER=PIA \
-e OPENVPN_USERNAME=*user* \
-e OPENVPN_PASSWORD=*pass* \
-e LOCAL_NETWORK=*localnetwork* \
haugene/transmission-openvpn:latest
```

**Logs**
Name resolution error:
```
Using OpenVPN provider: pia
Starting OpenVPN using config DE Frankfurt.ovpn
Setting OPENVPN credentials...
adding route to local network *** via 172.18.0.1 dev eth0
Mon Jun  3 08:13:28 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Mon Jun  3 08:13:28 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Jun  3 08:13:28 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jun  3 08:14:08 2019 RESOLVE: Cannot resolve host address: de-frankfurt.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Mon Jun  3 08:14:48 2019 RESOLVE: Cannot resolve host address: de-frankfurt.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Mon Jun  3 08:14:48 2019 Could not determine IPv4/IPv6 protocol
Mon Jun  3 08:14:48 2019 SIGUSR1[soft,init_instance] received, process restarting
Mon Jun  3 08:14:53 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
```

TLS Handshake error:
```
Using OpenVPN provider: PIA
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network *** via 172.17.0.1 dev eth0
Mon Jun  3 12:48:49 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Mon Jun  3 12:48:49 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Jun  3 12:48:49 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jun  3 12:48:49 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.142:1198
Mon Jun  3 12:48:49 2019 UDP link local: (not bound)
Mon Jun  3 12:48:49 2019 UDP link remote: [AF_INET]172.98.67.142:1198
Mon Jun  3 12:49:49 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Jun  3 12:49:49 2019 TLS Error: TLS handshake failed
Mon Jun  3 12:49:49 2019 SIGUSR1[soft,tls-error] received, process restarting
```

Thanks for any help in advance, and I'm happy to provide any additional requested info

**Comment by haugene** [comment]
Hey. Hopefully this is just the DNS issue, and it looks that way. The TLS handshake probably fails when you replace the DNS name with IP because it's signed for that domain name.

This is described in a [section of the README](https://github.com/haugene/docker-transmission-openvpn#use-google-dns-servers), try to add --dns options to your simple run command:

```
docker run --cap-add=NET_ADMIN -d \
-v /etc/localtime:/etc/localtime:ro \
--device=/dev/net/tun \
--dns 8.8.8.8 \
--dns 8.8.4.4 \
-e OPENVPN_PROVIDER=PIA \
-e OPENVPN_USERNAME=*user* \
-e OPENVPN_PASSWORD=*pass* \
-e LOCAL_NETWORK=*localnetwork* \
haugene/transmission-openvpn:latest
```

Also in the later versions of this image, mounting the tun device is no longer necessary. You can set a parameter to make the container create one itself. The result would then be:

```
docker run --cap-add=NET_ADMIN -d \
-v /etc/localtime:/etc/localtime:ro \
--dns 8.8.8.8 \
--dns 8.8.4.4 \
-e CREATE_TUN_DEVICE=true \
-e OPENVPN_PROVIDER=PIA \
-e OPENVPN_USERNAME=*user* \
-e OPENVPN_PASSWORD=*pass* \
-e LOCAL_NETWORK=*localnetwork* \
haugene/transmission-openvpn:latest
```

Hope this will resolve the problem, if not - come back with update and new logs ;)

**Comment by Cheezzhead** [comment]
I have used the DNS flag somewhere during my experiments, but just to be sure tried it again with DNS flags and the CREATE_TUN_DEVICE option just to be sure. No luck, unfortunately.

```
***@Ubuntu-1804-bionic-64-minimal:~$ docker run --cap-add=NET_ADMIN -d -v /etc/localtime:/etc/localtime:ro --dns 8.8.8.8 --dns 8.8.4.4 -e CREATE_TUN_DEVICE=true -e OPENVPN_PROVIDER=PIA -e OPENVPN_USERNAME=*** -e OPENVPN_PASSWORD=*** -e LOCAL_NETWORK=*** haugene/transmission-openvpn:latest
Unable to find image 'haugene/transmission-openvpn:latest' locally
latest: Pulling from haugene/transmission-openvpn
9ff7e2e5f967: Pull complete
59856638ac9f: Pull complete
6f317d6d954b: Pull complete
a9dde5e2a643: Pull complete
256cbb683649: Pull complete
377a1da28260: Pull complete
e573f0851794: Pull complete
cf3e217abcfa: Pull complete
f4374f91e307: Pull complete
Digest: sha256:e7a8897e65925a42c3bc790d97850b4a57ccaea3c7d2226ddaf01e04909a28ce
Status: Downloaded newer image for haugene/transmission-openvpn:latest
1fbf33fb817e85d3a21cf37ebff9045f2c11c3508a8d96b7225dbb92e870006e
***@Ubuntu-1804-bionic-64-minimal:~$ docker ps | grep transmission
1fbf33fb817e        haugene/transmission-openvpn:latest          "dumb-init /etc/open…"   11 seconds ago      Up 6 seconds (health: starting)   8888/tcp, 9091/tcp                                                                                                                                                                                                                                                   ecstatic_minsky
***@Ubuntu-1804-bionic-64-minimal:~$ docker logs -f ecstatic_minsky
Using OpenVPN provider: PIA
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network *** via 172.17.0.1 dev eth0
Mon Jun  3 14:52:32 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Mon Jun  3 14:52:32 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Jun  3 14:52:32 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jun  3 14:53:52 2019 RESOLVE: Cannot resolve host address: ca-toronto.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Mon Jun  3 14:55:12 2019 RESOLVE: Cannot resolve host address: ca-toronto.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Mon Jun  3 14:55:12 2019 Could not determine IPv4/IPv6 protocol
Mon Jun  3 14:55:12 2019 SIGUSR1[soft,init_instance] received, process restarting
Mon Jun  3 14:55:17 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
```

**Comment by haugene** [comment]
Hmm. That is weird. But that would also mean that DNS doesn't work with any other docker container either? If you pull the latest ubuntu and then run:
`docker run --rm -it ubuntu bash -c "apt update && apt install -y iputils-ping && ping ca-toronto.privateinternetaccess.com"`

or
`docker run --rm -it --dns 8.8.8.8 --dns 8.8.4.4 ubuntu bash -c "apt update && apt install -y iputils-ping && ping ca-toronto.privateinternetaccess.com"`

You see the same issue?

You could try to make a resolv.conf file locally and mount it directly into the container to see if that helps in any way. Content would be:
```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

And then mount it to /etc/resolv.conf

Any luck then?

**Comment by Cheezzhead** [comment]
Well, this is interesting.

Your first command executes normally, but the second command (with dns parameters) receives similar errors during the `apt install` commands:

```
***@Ubuntu-1804-bionic-64-minimal:~$ docker run --rm -it --dns 8.8.8.8 --dns 8.8.4.4 ubuntu bash -c "apt update && apt install -y iputils-ping && ping ca-toronto.privateinternetaccess.com"
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
```

So it seems to be related to the DNS parameters? Doing a quick google search led me to [this stackoverflow question](https://serverfault.com/questions/642981/docker-containers-cant-resolve-dns-on-ubuntu-14-04-desktop-host) and subsequently [here](https://github.com/moby/moby/issues/866), which, while being a fairly outdated issue looks to be a similar problem. I'll try it out once I get home tonight.

As for your first question, my other containers are experiencing no problems, but then those containers aren't configured to use a DNS server. I tried adding the test container to the bridge network that hosts all my other containers, but it didn't change anything.

I believe (although not 100% sure) that mounting resolv.conf doesn't work, because docker overwrites that file with the hosts' resolv.conf and/or the dns parameters. Will need to do a bit more research on this, though.

**Comment by Cheezzhead** [comment]
As I was looking through the resolv.conf on the host, I fell upon some IP addresses which turn out to be the nameserver of my hosting company. Using those as DNS parameter in the `docker run` command made it work!

Unfortunately, using the same nameservers for this docker brings me back to the TLS Handshake error:
```
Using OpenVPN provider: PIA
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network *** via 172.17.0.1 dev eth0
Mon Jun  3 15:33:51 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Mon Jun  3 15:33:51 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Jun  3 15:33:51 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jun  3 15:33:51 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.4:1198
Mon Jun  3 15:33:51 2019 UDP link local: (not bound)
Mon Jun  3 15:33:51 2019 UDP link remote: [AF_INET]172.98.67.4:1198
Mon Jun  3 15:34:52 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Jun  3 15:34:52 2019 TLS Error: TLS handshake failed
Mon Jun  3 15:34:52 2019 SIGUSR1[soft,tls-error] received, process restarting
Mon Jun  3 15:34:57 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jun  3 15:34:57 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.91:1198
Mon Jun  3 15:34:57 2019 UDP link local: (not bound)
Mon Jun  3 15:34:57 2019 UDP link remote: [AF_INET]172.98.67.91:1198
```

Like you said, the handshake probably fails because the cert is signed for the domain name, not the IP address (which the logs indicate is what the startup script is using). But why is it using the IP address in the first place?

**Comment by haugene** [comment]
This is when running the container with no other modifications to the .ovpn files?
If so (no tampering with hostnames etc) then I would normally expect this to be caused by the keys actually being wrong and needing an update. But I'm using PIA myself and haven't noticed anything on my server.

**Comment by Cheezzhead** [comment]
No modifications whatsoever. I've actually redownloaded the image every step of the way, and no volumes are mounted (besides /etc/localtime), so the .ovpn files are vanilla.

So I'm at a bit of a loss as to what's going on. Everything was working fine less than 48 hours ago...

**Comment by haugene** [comment]
Yeah. Downloaded the configs locally and compared with the existing keys, all looks good to me.
Just out of curiosity, do you have another server to test with? If not, use the DigitalOcean referral link on the repo front page and you'll get credits to fire up a VM to test on.

If you can't start it on one of those VMs then at least it's reproducible and I can try it myself as well. Don't have the time now, got to go. But keep me posted if there's any progress.

**Comment by Cheezzhead** [comment]
Turns out it was unrelated to this docker app (I started suspecting as much when I did the tests with a default Ubuntu docker). Turns out my hosting company's firewall was giving trouble. Had no idea it was still on. I've since disabled the firewall entirely and implemented ufw.

Issue can be closed, and apologies for any extra time you had to put in this!

**Comment by realcanadrian** [comment]
@Cheezzhead are you able to expand on what the issue was with the hosting provider's firewall? I'm having the same issue, and I haven't been able to find a resolution yet.
