### ISSUE TITLE
VPN config file could not be found

### ISSUE THREAD

**Issue by itlists** [haugene/docker-transmission-openvpn#824]
**Describe the problem**

I've added a recently created ProtonVPN config file into the OPENVPN_CONFIG variable but the logs show that the docker can't find it. Same error for ca.protonvpn.com.udp as well.
Supplied config ch-ca-01.protonvpn.com.udp.ovpn could not be found.

**Add your docker run command**

![protonvpn-1](https://user-images.githubusercontent.com/51167659/58801941-f2d5b500-85d9-11e9-9b70-7b5455fac043.png)
![protonvpn-2](https://user-images.githubusercontent.com/51167659/58801943-f2d5b500-85d9-11e9-8f52-eaad679e88bd.png)

**Logs**

Using OpenVPN provider: PROTONVPN
Supplied config ch-ca-01.protonvpn.com.udp.ovpn could not be found.
Using default OpenVPN gateway for provider protonvpn
Setting OPENVPN credentials...

**Host system:**

unRAID 6.7.0 NAS

**Comment by haugene** [comment]
The free builds on Docker Hub isn't always the fastest. And when there are many changes they are queued up. Seems your change is in the image that was pushed 37 minutes ago though. If you pulled before that, it's simply not there yet.

Pull the image again and re-create the container. Any luck then?

**Comment by itlists** [comment]
Hi, thanks for the quick reply. 
I'm using a docker from unraid's app repo, which is essentially a template for your docker customized / made more simple to use with unraid. I've asked the author if he needs to do something with his build in order to get this working.
If that fails, I'll try using your docker directly from docker hub.
Thanks again.
