### ISSUE TITLE
The path /etc/localtime is not shared from OS X and is not known to Docker

### ISSUE THREAD

**Issue by mbenezra** [haugene/docker-transmission-openvpn#827]
I'm trying to run the container on Docker for Mac. When running the container I get the following:

```
docker: Error response from daemon: Mounts denied: 
The path /etc/localtime
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
```

I've tried sharing the /etc folder but docker says that:

`The path /etc is reserved by Docker however it may be possible to export specific subdirectories.
`

**Comment by haugene** [comment]
Yes. So either share "/etc/localtime" directly - or just skip that line entirely.

The only reason why it's there is to make the logs have the correct timestamp. It might be off by some timezones if it's not there. But it has no other effect on the container.

**Comment by haugene** [comment]
Huh. I'm on a Mac myself and thought I'd test it. I'm usually running the container on my server and only do some local testing on the mac - but even specifying /etc/localtime I get some error.

Just skip the line for now. I'll install tzdata in the container so that we can set `-e TZ=CET` for example and then control it with environment instead. But it is not in the image as of now. Will update later.

**Comment by mbenezra** [comment]
Thanks a lot @haugene, looking forward to the update. it's a great image!

> Huh. I'm on a Mac myself and thought I'd test it. I'm usually running the container on my server and only do some local testing on the mac - but even specifying /etc/localtime I get some error.
> 
> Just skip the line for now. I'll install tzdata in the container so that we can set `-e TZ=CET` for example and then control it with environment instead. But it is not in the image as of now. Will update later.

**Comment by haugene** [comment]
Pushed now, will be available on next build.
