### ISSUE TITLE
Using OVPN?

### ISSUE THREAD

**Issue by ratnose** [haugene/docker-transmission-openvpn#830]
Hello!
I am a OVPN user and I have a hard time figuring out how to set this up, I am using the provided us.ovpn file from the project and the container just keeps restarting.

`transmission:
        image: haugene/transmission-openvpn
        container_name: transmission
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=OVPN
            - OPENVPN_CONFIG=NO Oslo
            - OPENVPN_USERNAME=username
            - OPENVPN_PASSWORD=password
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=10.10.10.0/24
        ports:
            - 8082:9091
        volumes:
            - /home/admin/appdata/transmission:/config
            - /home/admin/media/downloads:/download
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped`

What am I doing wrong here?

**Comment by macmattias** [comment]
So I used parts of the docker-compose file in the project and now it seems to be working. :)

So how do I check that the container is running VPN?

**Comment by haugene** [comment]
Hey. Glad you got it working.
For testing that you're on VPN, see #698 and related issues from there.

**Comment by mrjackyliang** [comment]
Seems like it's solved! Closing it for now, thanks!
