### ISSUE TITLE
Could someone help me setting up Premiumize.me?

### ISSUE THREAD

**Issue by jfml** [haugene/docker-transmission-openvpn#831]
**Which provider?**
Premiumize.me

**Where are the configs?**
These are the servers on which torrenting is explicitly allowed:

[vpn-bg.premiumize.me-generic.zip](https://github.com/haugene/docker-transmission-openvpn/files/3273070/vpn-bg.premiumize.me-generic.zip)

[vpn-nl.premiumize.me-generic.zip](https://github.com/haugene/docker-transmission-openvpn/files/3273047/vpn-nl.premiumize.me-generic.zip)

I'd also be up for getting tips on how to set this up without adding the provider if that's easier. I'm a total Docker noob and I got it working on my Synology with Proxy.sh but with Premiumize.me I can't connect to the Web-UI. The logs look ok to me but I'm pretty sure something (probably user/password?) is wrong.

Any help would be greatly appreciated ^__^

**Comment by jfml** [comment]
Do I need to supply the username/pw via a file?

**Comment by jfml** [comment]
I think I got it to work:

I put the username/password from the Premiumize.me VPN into a pass.txt like [described here](https://torguard.net/knowledgebase.php?action=displayarticle&id=138) (just make it a text file with two lines, first one the username, second the pw) put it next to the default.opvn and then mounted the "custom" folder into the docker container and changed the .opvn to

`auth-user-pass /etc/openvpn/custom/pass.txt`

**Comment by haugene** [comment]
Glad you got it working 👍 
For future reference, the username and password entered in OPENVPN_USERNAME and OPENVPN_PASSWORD environment variables will be stored to a file in the container. So you could also use `auth-user-pass /config/openvpn-credentials.txt` which is the default for the other providers.

**Comment by jfml** [comment]
Good to know, thanks!
