### ISSUE TITLE
NordVPN connection issues

### ISSUE THREAD

**Issue by AKDub** [haugene/docker-transmission-openvpn#832]
**Describe the problem**
Every few days the container fails and ends up in a restart loop. Most of the time it will randomly start working again after a couple of days, so not sure if the problem is with the docker, NordVPN or something I am doing

**Logs**
https://pastebin.com/dAVKrPuK

**Host system:**
OMV4

**Comment by Esteidinger** [comment]
@AKDub  Have you had any further context about this? I was just getting ready to attempt to set this up on OMV4 with NordVPN. 

Wondering if you can share your docker run script as well.

**Comment by AKDub** [comment]
It started working again yesterday without me doing anything. It looks like for whatever reason it does not like/download certain configs. At some point it tries on it likes, and we are back in business.

**Comment by AKDub** [comment]
> @AKDub Have you had any further context about this? I was just getting ready to attempt to set this up on OMV4 with NordVPN.
> 
> Wondering if you can share your docker run script as well.

I would say go ahead and set it up. As you can see, you may have some issues, but for someone like me who is new to all of this, it is the easiest way to have torrents with VPN.

I didn't use a script, I just used the OMV GUI to install.

**Comment by gardner** [comment]
Can you paste log files from the container when it is in a bad state?

**Comment by AKDub** [comment]
The container is back to not working again. Does the container have to be running to inspect the file system?

**Comment by AKDub** [comment]
Even though I have set NORDVPN_COUNTRY=uk  (also tried others)  it keeps trying to get a German config file.

Setting best server de652.nordvpn.com.udp
Supplied config de652.nordvpn.com.udp.ovpn could not be found.

Is there any way to force it to use a different file?

**Comment by AKDub** [comment]
Tried to cheat by mapping /etc/openvpn/nordvpn to another folder where I had added a config file I downloaded.

Gets a little further down the line, but still fails as I am messing up the filesystem I presume.

Using OpenVPN provider: NORDVPN
Starting OpenVPN using config uk1365.nordvpn.com.udp.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Fri Jun 21 12:12:00 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 24 2018
Fri Jun 21 12:12:00 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Fri Jun 21 12:12:00 2019 neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Auth Username:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.
Fri Jun 21 12:12:00 2019 Exiting due to fatal error

**Comment by simonjthomas** [comment]
Just to confirm that I'm having the same issue. My logs have the same:

> 2019-06-22 19:53:13 Checking curl installation,
> 2019-06-22 19:53:13 Removing existing configs,
> 2019-06-22 19:53:13 Selecting the best server...,
> 2019-06-22 19:53:13 Searching for technology: openvpn_tcp,
> 2019-06-22 19:53:13 Unable to find a server with the specified parameters, using any recommended server,
> 2019-06-22 19:53:13 Best server : ,
> 2019-06-22 19:53:13 Downloading config: default.ovpn,
> 2019-06-22 19:53:13 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn,
> curl: (6) Could not resolve host: downloads.nordcdn.com,
> No VPN configuration provided. Using default.

I'm assuming it's looking at the wrong URL (https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn) for some reason as that's a 404 (presumably it should have an actual server, or group of servers, before ".tcp".

 This appears to be a fairly recent issue for me. My config is set to use Netherlands P2P servers and was working a couple of weeks ago.

**Comment by AKDub** [comment]
> Just to confirm that I'm having the same issue. My logs have the same:
> 
> > 2019-06-22 19:53:13 Checking curl installation,
> > 2019-06-22 19:53:13 Removing existing configs,
> > 2019-06-22 19:53:13 Selecting the best server...,
> > 2019-06-22 19:53:13 Searching for technology: openvpn_tcp,
> > 2019-06-22 19:53:13 Unable to find a server with the specified parameters, using any recommended server,
> > 2019-06-22 19:53:13 Best server : ,
> > 2019-06-22 19:53:13 Downloading config: default.ovpn,
> > 2019-06-22 19:53:13 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn,
> > curl: (6) Could not resolve host: downloads.nordcdn.com,
> > No VPN configuration provided. Using default.
> 
> I'm assuming it's looking at the wrong URL (https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn) for some reason as that's a 404 (presumably it should have an actual server, or group of servers, before ".tcp".
> 
> This appears to be a fairly recent issue for me. My config is set to use Netherlands P2P servers and was working a couple of weeks ago.
> 
> Edit: Looking at the filesystem in the container, the only thing in /etc/openvpn/nordvpn is 'updateConfigs.sh'

That specific error doesn’t seem to appear in my logs

**Comment by AKDub** [comment]
Once again, at some point last night it started working again.

> plied config de626.nordvpn.com.udp.ovpn could not be found.
Using default OpenVPN gateway for provider nordvpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/default.ovpn
Use --help for more information.
Using OpenVPN provider: NORDVPN
Setting best server de626.nordvpn.com.udp
Supplied config de626.nordvpn.com.udp.ovpn could not be found.
Using default OpenVPN gateway for provider nordvpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/default.ovpn
Use --help for more information.
Using OpenVPN provider: NORDVPN
Setting best server de112.nordvpn.com.udp
Starting OpenVPN using config de112.nordvpn.com.udp.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Sat Jun 22 02:13:06 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 24 2018
Sat Jun 22 02:13:06 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sat Jun 22 02:13:06 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Jun 22 02:13:06 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Sat Jun 22 02:13:06 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

**Comment by simonjthomas** [comment]
So I did a bit of digging and I strongly suspect my issue is different to yours. I'd set up a different DNS provider within that container and for whatever reason they'd stopped resolving Nord's CDN. I've now changed DNS provider and it's working. Took a bit of diagnosing, but got there in the end!

**Comment by gardner** [comment]
@AKDub your issue may be related to improper configuration. Inspecting https://api.nordvpn.com/v1/servers/countries one can see that there is no `uk` country, only `GB`.

I was able to connect to the uk995 endpoint using: 

    docker run --cap-add=NET_ADMIN -d \
                -v data:/data \
                -v /etc/localtime:/etc/localtime:ro \
                -e CREATE_TUN_DEVICE=true \
                -e OPENVPN_PROVIDER=NORDVPN \
                -e NORDVPN_COUNTRY=GB \
                -e LOCAL_NETWORK=192.168.0.0/16 \
                -p 9091:9091 \
                haugene/transmission-openvpn

From the command line you can see the list of endpoints using: `curl -s "https://api.nordvpn.com/v1/servers/countries" | python -mjson.tool`

To add to the confusion, NordVPN specifically calls this region "UK" on their website (and in their hostnames).

**Comment by AKDub** [comment]
I see what you mean, although even if that code is wrong, it would still try grab a config and fail. So if it ignores uk and tries to connect to a German server, shouldn’t the German server still connect?

I had also tried various us variants that other threads would indicate work like united_states.

**Comment by lavaguy1** [comment]
I'm going to "me, too" on this one. Since yesterday, all connection attempts fail with 

`Tue Jun 25 19:24:12 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Tue Jun 25 19:24:12 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Tue Jun 25 19:24:12 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Jun 25 19:24:12 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jun 25 19:24:12 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jun 25 19:24:12 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]5.254.16.89:1194
Tue Jun 25 19:24:12 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Tue Jun 25 19:24:12 2019 UDP link local: (not bound)
Tue Jun 25 19:24:12 2019 UDP link remote: [AF_INET]5.254.16.89:1194
Tue Jun 25 19:24:12 2019 TLS: Initial packet from [AF_INET]5.254.16.89:1194, sid=066ec5b9 d865adfe
Tue Jun 25 19:24:12 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Jun 25 19:24:12 2019 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Tue Jun 25 19:24:12 2019 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA3
Tue Jun 25 19:24:12 2019 VERIFY KU OK
Tue Jun 25 19:24:12 2019 Validating certificate extended key usage
Tue Jun 25 19:24:12 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue Jun 25 19:24:12 2019 VERIFY EKU OK
Tue Jun 25 19:24:12 2019 VERIFY OK: depth=0, CN=de454.nordvpn.com
Tue Jun 25 19:24:13 2019 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Tue Jun 25 19:24:13 2019 [de454.nordvpn.com] Peer Connection Initiated with [AF_INET]5.254.16.89:1194
Tue Jun 25 19:24:14 2019 SENT CONTROL [de454.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Tue Jun 25 19:24:14 2019 AUTH: Received control message: AUTH_FAILED
Tue Jun 25 19:24:14 2019 SIGTERM[soft,auth-failure] received, process exiting`

and it simply loops constantly trying to connect to **de454.nordvpn.com** over **UDP**.

I need it to use TCP - which has been working a charm using the following Compose file snippet up until today:

`    container_name: transmission
    restart: unless-stopped
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /media/ogre/dl:/data
      - /media/ogre/torrentdl:/bigdata
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
#      - ${USERDIR}/docker/vpntransmission:/config
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=us1853.nordvpn.com.tcp,us2245.nordvpn.com.tcp,us2675.nordvpn.com.tcp,us1210.nordvpn.com.tcp,us1861.nordvpn.com.tcp,us39.nordvpn.com.tcp,us500.nordvpn.com$
#      - OPENVPN_CONFIG=us985.nordvpn.com.tcp,us981.nordvpn.com.tcp,us984.nordvpn.com.tcp,us975.nordvpn.com.tcp,us983.nordvpn.com.tcp,us971.nordvpn.com.tcp,us986.nordvpn.com.tcp$
#      - NORDVPN_COUNTRY=GB
#      - OPENVPN_CONFIG=us3226.nordvpn.com.tcp
      - OPENVPN_USERNAME=UID
      - OPENVPN_PASSWORD=PW
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - WEBPROXY_ENABLED=true
      - ENABLE_UFW=true
      - GLOBAL_APPLY_PERMISSIONS=false
      - TRANSMISSION_BLOCKLIST_ENABLED=true
      - TRANSMISSION_BLOCKLIST_URL="http://list.iblocklist.com/?..."
      - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true
      - TRANSMISSION_DOWNLOAD_DIR="/bigdata/completed"
      - TRANSMISSION_INCOMPLETE_DIR="/bigdata/incomplete"
      - TRANSMISSION_BIND_ADDRESS_IPV6="fe80::"
      - LOCAL_NETWORK=192.168.178.0/24
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - DROP_DEFAULT_ROUTE=true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - "9091:9091"
      - "8888:8888"
`

so... nothing works. I need to be able to specify connection over TCP, as I am already using a UDP tunnel for a different process on this machine...

Any ideas?

- Steve

**Comment by AKDub** [comment]
de112 has been working for me for a couple of days if you want to try, although that’s udp, maybe tcp will also wor

**Comment by lavaguy1** [comment]
Thanks! Fixed it using the new NORDVPN_ env. vars in my compose file.

**Comment by foordy08** [comment]
I've still got issues with NORDVPN is anyone able to post their docker run commands they're using with NORD successfully?

**Comment by AKDub** [comment]
For me it was a case of ditching all of the specific Nord setting (NORDVPN_COUNTRY / NORDVPN_PROTOCOL / NORDVPN_CATEGORY) and finding a specific config that worked and using OPENVPN_CONFIG.

Mine ended up being one from Germany just because I had seen it work in the past and I don't really care about the country or protocol. If you need one in Denmark I think you will have just keep trying different ones.

All this is obviously only matters if you were having the same issue as me.

**Comment by edgd1er** [comment]
I ve suggested a PR to give some information about nordVpn udpate script: https://github.com/haugene/docker-transmission-openvpn/pull/842/commits/5453d74d85ae41ae68e7735a9e3515a6bed10535 

You might find some information there

here is the part of the conf of the docker settings used with OMV4:
                "NORDVPN_COUNTRY=xxx",
                "OPENVPN_PROVIDER=NORDVPN",
                "NORDVPN_CATEGORY=P2P",
                "OPENVPN_USERNAME=myusername",
                "NORDVPN_PROTOCOL=tcp",
                "OPENVPN_PASSWORD=mypassword",

there is also as extra args: --cap-add=NET_ADMIN --device=/dev/net/tun

**Comment by foordy08** [comment]
Thanks all for the help, I haven't had much time to look into this with what with work but have managed to get this all sorted now...completely unrelated to the docker container. Issue was with permissions to the transmission-home folder.

**Comment by haugene** [comment]
Merged fix for NordVPN in #868. Proposing to follow up NordVPN connectivity in #867 and close this. Verifying on the dev image and merging fix to master soon.

Anything else that should be discussed in this thread? There seems to be a need for updated docs for NordVPN as many is asking for usage here.
