### ISSUE TITLE
No way to set folder permissions

### ISSUE THREAD

**Issue by aSaltyPirate** [haugene/docker-transmission-openvpn#833]
**Is your feature request related to a problem? Please describe.**
My system requires the items downloaded and the folders they are in to be accessible to all members of the group. Currently one can set the umask but that only applies to the files inside the folders they're downloaded in and not the folders themselves.

**Describe the solution you'd like**
Either making the folders reflect the given umask in settings or simply allowing changing the permissions of the completed directory. As it is now the permissions of this directory are hardcoded to 640 and they revert to this on container restart.

**Comment by evsasha** [comment]
Hi, I did not understand your request.

- What is your system?
- What parameters do you run the container with?
- What folders do you have not group permissions for?

I tested on CentOS and synology NAS and transmission user and group have full acces to data directories:

```
$ cd downloads/Anime/
$ ls -al
total 0
drwxrwx---+ 1 transmission transmission 1592 Jun  3 00:55 .
drwxrwx---+ 1 transmission transmission  432 Nov 12  2018 ..
drwxrwx---+ 1 transmission transmission 3268 Mar 15 11:43 XXX1
drwxrwx---+ 1 transmission transmission   12 Jun  1 21:16 XXX2
drwxrwx---+ 1 transmission transmission  562 Mar 15 12:02 XXX3
```

Show some examples please.

**Comment by aSaltyPirate** [comment]
Huh, now it seems to be ignoring my umask variable completely.  I run with the following command 

```
docker run --name=transmission --cap-add=NET_ADMIN  -d \
	--label autoheal=true \
	-v /home/transmission/data:/data \
	-v /etc/localtime:/etc/localtime:ro \
	-v /home/transmission/vpns/AirVPN_America_UDP-443.ovpn:/etc/openvpn/custom/default.ovpn \
	-v /media/videos/downloads/completed:/completed \
	-v /media/videos/downloads/incomplete:/incomplete \
	-v /media/videos/downloads/dropbox:/dropbox \
	-e CREATE_TUN_DEVICE=true \
	-e TRANSMISSION_UMASK=2 \
	-e OPENVPN_PROVIDER=CUSTOM \
	-e TRANSMISSION_PEER_PORT=57014 \
	-e TRANSMISSION_RATIO_LIMIT_ENABLED=true \
	-e TRANSMISSION_RATIO_LIMIT=3 \
	-e TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true \
	-e TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0 \
	-e TRANSMISSION_WATCH_DIR_ENABLED=false \
	-e TRANSMISSION_MAX_PEERS_GLOBAL=500 \
	-e TRANSMISSION_PEER_LIMIT_GLOBAL=500 \
	-e TRANSMISSION_PEER_LIMIT_PER_TORRENT=50 \
	-e TRANSMISSION_SEED_QUEUE_ENABLED=true \
	-e TRANSMISSION_SEED_QUEUE_SIZE=5 \
	-e TRANSMISSION_DOWNLOAD_QUEUE_SIZE=20 \
	-e TRANSMISSION_DOWNLOAD_DIR=/completed \
	-e TRANSMISSION_INCOMPLETE_DIR=/incomplete \
	-e OPENVPN_USERNAME=user \
	-e OPENVPN_PASSWORD=pass \
	-e WEBPROXY_ENABLED=false \
	-e TZ=America/Detroit \
	-e PUID=1004 \
	-e PGID=1002 \
	-e LOCAL_NETWORK=192.168.0.0/16 \
	--log-driver json-file \
	--log-opt max-size=10m \
	-p 9091:9091 \
	--restart unless-stopped \
	haugene/transmission-openvpn
```

It seems to be ignoring the umask completely, all of the folders containing movie files downloaded are 755 and the files within them are 644.

**Comment by evsasha** [comment]
https://trac.transmissionbt.com/wiki/MovedToGitHub/ConfigurationParameters

```
Sets transmission's file mode creation mask. See ​the umask(2) manpage. For world-writable torrents set umask to 0.
Note: JSON only accepts base 10 numbers, so convert standard octal umask to base 10, "022" is thus written as 18. 
```

**Comment by haugene** [comment]
Any update @aSaltyPirate?

**Comment by wriches** [comment]
I have been encountering the same issue. The problem stems from the download and incomplete directories having their permissions hardcoded (recursively) on startup:
https://github.com/haugene/docker-transmission-openvpn/blob/93d0141d928ec661411e2c6f0e079aeff2c018dd/transmission/userSetup.sh#L44-L47

In my use case, my data directory is on a NAS where the group is enforced, so I need write access for the group. The Transmission umask defaults to `002`, but this image does not respect that due to the hardcoded permissions.

The only directory that I think should have hardcoded permissions is the watch directory, so that it's globally accessible for anyone to drop a file in.

The solution I think is simple: respect the `TRANSMISSION_UMASK` configuration, and fall back to the Transmission default of `002`.
