### ISSUE TITLE
How to open port with PIA

### ISSUE THREAD

**Issue by cheezebow** [haugene/docker-transmission-openvpn#834]
First of all, this is my first experience with Docker so i feel a bit lost.
I wonder how i can enable open port for PIA, i read and found the script but i dont know how to use it.
What code shall i put where to get it working? ^^
Do i need to configurate the .sh file?
I installed using Docker Compose.

**Comment by haugene** [comment]
You shouldn't need to do anything. If PIA is used as provider, an open port is requested and set on Transmission automatically within the first minutes of running the container. This only works if you're using one of the supported regions though. See list here: https://www.privateinternetaccess.com/helpdesk/kb/articles/how-do-i-enable-port-forwarding-on-my-vpn

**Comment by haugene** [comment]
If it's still not working please provide your logs.

**Comment by cheezebow** [comment]
Transmission say port open (Use Sweden server), so you have right.
Think its the private tracker i have that have problem then.
Thanks for fast answer and a great docker package.
