### ISSUE TITLE
Cannot connect to Plex when docker is on

### ISSUE THREAD

**Issue by ascheel319** [haugene/docker-transmission-openvpn#838]
**Describe the problem**

So I was able to get it mostly working but then found out that when I have the docker container connected I cannot connect to Plex from anything, even on a local computer. I think that it is something with the network settings on the run command that I used as I didn't really understand that part. I posted the the command below, but I did take out my PIA login info.

**Add your docker run command**

docker run --cap-add=NET_ADMIN -d               -v /home/andrew/Plex/shows/temp/:/data               -v /etc/localtime:/etc/localtime:ro               -e CREATE_TUN_DEVICE=true               -e OPENVPN_PROVIDER=PIA               -e OPENVPN_CONFIG=CA\ Toronto               -e OPENVPN_USERNAME=username               -e OPENVPN_PASSWORD=password               -e WEBPROXY_ENABLED=false               -e LOCAL_NETWORK=192.168.0.0/16               --log-driver json-file               --log-opt max-size=10m               --restart=always               --name downloader               -p 9091:9091               haugene/transmission-openvpn

**Logs**

**Host system:**

I'm on Ubuntu 18.04.2 LTS and whatever the newest docker is, 18.09.6

**Comment by AKDub** [comment]
I would wait for one of the pros to confirm, but for me to get Plex working I had to run in bridge mode, and map the ports, and indicate the local network (which you have done - in my case it was LOCAL_NETWORK=192.168.1.0/24)

-p 8080:8080
-p 9091:9091
--net=bridge (I think)

Once Plex is not going through the VPN it will work fine, unless you have some other issue

**Comment by ascheel319** [comment]
> I would wait for one of the pros to confirm, but for me to get Plex working I had to run in bridge mode, and map the ports, and indicate the local network (which you have done - in my case it was LOCAL_NETWORK=192.168.1.0/24)
> 
> -p 8080:8080
> -p 9091:9091
> --net=bridge (I think)
> 
> Once Plex is not going through the VPN it will work fine, unless you have some other issue

Is the 8080 the port you are using for Plex? Also why do you have the IP address like that? I was confused on what I why I was supposed to put 192.168.1.0 when I know my up is 192.168.1.32. Also why the 24?

**Comment by AKDub** [comment]
This is why I mentioned to wait for the pros, I just bundle my way through this....

I may have made up that extra port. I think that or 8888 is offered to me on openmediavault when I set this up, it my not be needed.

My NAS is 192.168.1.100, my router is 192.168.1.1 - everything I read said to drop the last digit and add 0/24, and it seems to work. My Plex is accessible remotely and on the local network.

**Comment by ascheel319** [comment]
Well while I wait for the pros, you gave me a few things to try so thanks

**Comment by haugene** [comment]
@ascheel319 Did you figure it out? What was the solution?

From the docker run command you posted above I can't see how it should interfere with running Plex. When the container is started with "--net=host" then it will tamper with the networking on the host, but as long as it's in bridge mode (which is default) it should be OK.

**Comment by ascheel319** [comment]
Ya I was about to get it working. It ended up being an issue of the IP that I put in.
