### ISSUE TITLE
Please Add TweakNews VPN provider

### ISSUE THREAD

**Issue by kevke1990** [haugene/docker-transmission-openvpn#839]
Hi Haugene,

Could you add TweakNews to the provider section. I tried it with your solutions but I can not get it working. I attached the OVPN and the certificate in the OVPN.
[TweakNews.zip](https://github.com/haugene/docker-transmission-openvpn/files/3324448/TweakNews.zip)

If you need more information I will provide it to you.

Greetings, Kevin

**Comment by mrjackyliang** [comment]
Closing this and merging.
