### ISSUE TITLE
Slow DNS Queries

### ISSUE THREAD

**Issue by kkniffin** [haugene/docker-transmission-openvpn#84]
I am experiencing slow DNS when using this container. It only seems to occur when the vpn is initialized. I am not sure if it has something to do with the new built in DNS server in docker or something simple I am missing. I have this working on an older version of docker, but on the latest version of debian jessie and trying stable, testing, and experimental I get timeouts.

If I run it as network_mode: "host" it seems to work fine.

Using Docker Compose I have:

version: '2'
services:
  ###### Transmission & OpenVPN
  #############################
  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn
    restart: always
    volumes:
      - ${DOC_TRANSMISSION_DOWNLOADS}:/data/completed:rw
    environment:
      - OPENVPN_PROVIDER=${DOC_OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${DOC_OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${DOC_OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${DOC_OPENVPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSION_IDLE_SEEDING_LIMIT=1
      - TRANSMISSION_DOWNLOAD_LIMIT=100
      - TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_BLOCKLIST_URL=http://john.bitsurge.net/public/biglist.p2p.gz
      - TRANSMISSION_BLOCKLIST_ENABLED=1
      - TRANSMISSION_RPC_USERNAME=transmission
      - TRANSMISSION_RPC_PASSWORD=transmission
      - TRANSMISSION_UMASK=0
    dns:
      - 8.8.8.8
      - 8.8.4.4
    privileged: true

When I enter the container and run the following I get:

ping www.google.com
ping: unknown host www.google.com

Any pointers as to what I am missing?

**Comment by haugene** [comment]
Hmm. Can't say that I see any reason for it not working.
I'm running Debian jessie on my laptop with Docker 1.10.1, works fine. Is it just this container? If you run other containers or start this container without launching OpenVPN you can ping google? Which provider are you using?

**Comment by kkniffin** [comment]
Yah, it seems to just be this container for some reason. I think it has to do with the built-in DNS server that is now in Docker for some reason. I have tried two different carriers IPVanish and PUREVPN, both seem to do the same. I was able to resolve the issue for now by modifying the resolv.conf and having it only contain the Public DNS Server's and it works fine. However, when it points to the internal docker DNS proxy, it doesn't seem to work.

**Comment by haugene** [comment]
Ok, good to know! Which version of docker are you running? I could try to reproduce it.

**Comment by kkniffin** [comment]
Well I tried the latest stable, testing, dev and all at the same issue.

Currently I am on: Docker version 1.12.0-dev, build b02acfc, experimental

Debian version 8.5

**Comment by haugene** [comment]
Any new discoveries? I've been busy for a while, but I hope to get some time to look at it this weekend. 
If this is going to be a problem with 1.12, I want to know why ;)

**Comment by divThis** [comment]
I had this same issue running on a Synology DiskStation. Switching the google nameservers to OpenDNS resolved the issue for some reason.

**Comment by divThis** [comment]
@kkniffin: Note that if you run via the host network, your torrent client will make DNS requests via your regularly configured DNS servers. You can check for this using https://www.doileak.com/ and the additional torrent tests.

**Comment by kkniffin** [comment]
@divThis Did you swap them via the docker engine or inside of the docker container? The only thing I could figure out to work was to replace them inside the container in the /etc/resolv.conf with the google dns servers instead of whatever proxy docker DNS servers were in there. That seemed to work.

**Comment by divThis** [comment]
@kkniffin I have a resolv.conf on the host machine and mount it at /etc/resolv.conf as a volume. The only difference is that instead of:

    nameserver 8.8.8.8
    nameserver 8.8.4.4

I have:

    nameserver 208.67.222.222
    nameserver 208.67.222.220

My hunch (I haven't investigated thoroughly) is there's some sort of loopback happening with the Google DNS servers within the container and using different DNS servers bypass that.

**Comment by timkelty** [comment]
@divThis I think I'm having the same issue with the Google DNS/Synology. Though it seems if I restart the container, it can fix itself. Giving it a shot with OpenDNS

**Comment by HotBlack77** [comment]
Is this working for people when using OpenDNS?
