### ISSUE TITLE
Tinyproxy creates open proxy

### ISSUE THREAD

**Issue by c-hri-s** [haugene/docker-transmission-openvpn#840]
When using WEBPROXY_ENABLED=true Tinyproxy creates a proxy that is open from the Internet via your assigned VPN address. This is a problem because the proxy is unauthenticated.

There should be (or perhaps, is there already?) a way to restrict the use of Tinyproxy to the local IP range of the internal network.

**Comment by mrjackyliang** [comment]
Are you port forwarding the ports on the router?

**Comment by c-hri-s** [comment]
No - the packets are coming in through the VPN interface ... that bypasses (is a tunnel through) the router. Using the VPN IP address and the tinyproxy port anyone on the Internet can use my connection as a proxy. 

It should be authenticated or firewalled within the docker image somehow.

**Comment by tommitytom** [comment]
For this to happen wouldn't the VPN have to be forwarding that particular port to your IP? Presuming there are many people connected to the VPN..

**Comment by c-hri-s** [comment]
The VPN isn't NAT, so no port forwarding is needed on their side. The IP you are assigned is 'your' IP for the duration of the VPN session. Any connection attempt (on any port) will hit the OpenVPN interface. If you've something running there it will respond, assuming it's configured to listen on that IP interface (which is the problem here with the Tinyproxy config - it should only listen on the internal interface).

**Comment by haugene** [comment]
This depends on your provider. Getting a "whole IP" for yourself with all ports open is not how most of them operate I think (estimation). With PIA you have to cURL a specific URL to get an open port assigned. NordVPN apparently closed all incoming ports (?), ref: https://github.com/haugene/docker-transmission-openvpn/issues/790#issuecomment-521976944

All that taken into account. Adding the possibility of restricting access would still be nice of course :)

**Comment by c-hri-s** [comment]
Just for clarity, I use iPredator - they currently operate as I've described. 
I can see it may not be an issue across all providers according to their policies.
