### ISSUE TITLE
No Upload and port 51413 closed

### ISSUE THREAD

**Issue by milou161185** [haugene/docker-transmission-openvpn#844]
Hello, I'm having a problem with transmission. I download the torrents correctly, but I have no upload, and the port 51413 remains desperately closed. I redirected the port into the docker, open on my router but nothing works. Does this have a relationship with the upload?

my dockercompose file:

  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    restart: ${RESTARTPOLICY}
    depends_on:
      - nginx
    networks:
      - torrent_net
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      - 8888:8888
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /media/Downloads:/data
    environment:
      - OPENVPN_PROVIDER=${VPNPROVIDER}
      - OPENVPN_USERNAME=${VPNUSER}
      - OPENVPN_PASSWORD=${VPNPASS}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - HEALTH_CHECK_HOST=google.com
      - TZ=${TZ}
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888
      - VIRTUAL_HOST=transmission.${LOCALDOMAIN}
      - VIRTUAL_PORT=9091
      - LOCAL_NETWORK=192.168.1.0/24,172.19.0.0/16
      - CREATE_TUN_DEVICE=true

**Comment by mrjackyliang** [comment]
The ports should be open on your VPN side, not through the Docker. For uploads to work, some VPNs require you to purchase some sort of firewall, like PureVPN (NAT Firewall) at an additional cost.

Closing this for now as it has no direct issue with `transmission-openvpn` itself.
