### ISSUE TITLE
Port forwarding doesn't work.

### ISSUE THREAD

**Issue by OrgoneBlaster** [haugene/docker-transmission-openvpn#851]
[container_log.txt](https://github.com/haugene/docker-transmission-openvpn/files/3369296/container_log.txt)
[transmission.log](https://github.com/haugene/docker-transmission-openvpn/files/3369300/transmission.log)
[settings.json.txt](https://github.com/haugene/docker-transmission-openvpn/files/3369302/settings.json.txt)

**Describe the problem**
Port forwarding doesn't for for the 9091 & the port 51413 either

**Add your docker run command**
extra args: "--cap-add=NET_ADMIN -d -p 9091:9091 --dns 8.8.8.8 --dns 8.8.4.4 --sysctl net.ipv6.conf.all.disable_ipv6=0

**Logs**
Attached

**Host system:**
OMV docker

**Comment by OrgoneBlaster** [comment]
NordVPN doesn't suport port forwarding.

**Comment by niXta1** [comment]
Correct, port 1080 was opened with NordVPN on VPN but they have since closed it.
Avoid NordVPN like the plague.
