### ISSUE TITLE
NordVPN Issues - Torrents not downloading since switching VPN Provider

### ISSUE THREAD

**Issue by foordy08** [haugene/docker-transmission-openvpn#852]
Evening all, 

Decided to switch from TorGuard to NordVPN (kind of regretting that now) but since switching I've had nothing but problems trying to get this up and working. 

I did have issues originally getting the container to start but have since sorted this now from pulling the latest image. 

See here (https://pastebin.com/a42DLEhp) for my docker run command which I'm running. 

The logs show the container starts and I can access the WebUI perfectly (Docker logs https://pastebin.com/tYQ7DRM3) 

The transmission logs are just constantly saying torrents are retrying and scrape error connection failed. 

Not sure if I'm doing anything wrong but this is really frustrating as it worked perfectly with Torguard. I did a quick Torguard image and this still works fine. 

Any help would be appreciated!

**Comment by williammuff** [comment]
Same problem here (except i'm new to this trying to use NORDVPN). I'm super unfamiliar with proxy/etc; do they use UDP or TCP?

**Comment by foordy08** [comment]
Hey mate, I believe the intention is that you can specify either, UDP or TCP depending on your requirements using the variables within the container.

**Comment by foordy08** [comment]
Closing issue. Resolution - Permissions fault which only seemed to crop up after changing VPN provider.
