### ISSUE TITLE
Settings reset

### ISSUE THREAD

**Issue by ascheel319** [haugene/docker-transmission-openvpn#857]
**Describe the problem**

I like to have the amount of time that I am seeding set. For some reason idk if the docker restarts or something else but maybe every other day or so the setting gets turned off and the number that I put in gets erased.
**Add your docker run command**

> version: '3'
> services:
>   openvpn:
>     image: haugene/transmission-openvpn
>     # name container whatever you want
>     container_name: downloader
>     ports:
>       - 9091:9091
>     # Configure your logging options
>     logging:
>       driver: json-file
>       options:
>         max-size: 10m
>     restart: always
>     cap_add:
>       - NET_ADMIN
>     volumes:
>       - /etc/localtime:/etc/localtime:ro
>       - /home/andrew/Plex/shows/temp:/data
>     # Configure all of your environment variables
>     environment:
>       - CREATE_TUN_DEVICE=true
>       - OPENVPN_PROVIDER=PIA
>       - OPENVPN_CONFIG=US Chicago
>       - OPENVPN_USERNAME=username
>       - OPENVPN_PASSWORD=password
>       - WEBPROXY_ENABLED=false
>       - LOCAL_NETWORK=192.168.1.0/24

**Logs**

**Host system:**

Ubuntu 18.04.2 LTS

**Comment by eDavidT** [comment]
Should probably remove your credentials from your post.

**Comment by ascheel319** [comment]
Thanks @eDavidT....I forgot to do that

**Comment by mrjackyliang** [comment]
For the amout of seeding set, you can set the `TRANSMISSION_RATIO_LIMIT` environment variable during container creation. I will mark this as solved in the meantime.

P.S. It's best to reset your PIA password. Editing a post on GitHub doesn't remove the password.
