### ISSUE TITLE
Can't Access Container GUI Connected To VPN Network

### ISSUE THREAD

**Issue by gist901** [haugene/docker-transmission-openvpn#860]
First off, thanks so much for making this docker container, it is a god send. I am new to docker and trying to learn. 

I have been able to successfully run this container on my Raspberry Pi. But I want to run additional containers through the VPN network that is created. I want to have additional containers connect / use the VPN network that is created. 

I have added the following argument to my Jackett container: ``--network=container:vpn``

When I try to access the Jackett container via port 9117  ``192.168.1.3:9117``, I get no response.

When I check to see if Jackett container gets assigned an IP, it doesn't appear so:
`` sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' jackett ``

If I try the following I do not get a response from the Jackett container:
`sudo docker exec -it jackett /bin/bash
root@6d1c1cc14639:/# curl localhost:9117`

Any help on how to best setup this up or any help on troubleshooting the issue would be greatly appreciated.

Please see below for my haugene/docker-transmission-openvpn and Jackett config files

```
docker create \
        --name=vpn \
        --cap-add=NET_ADMIN \
        -v /mnt/torrents/dockerConfig:/shared \
        -v /mnt/torrents/downloads:/data \
        -v /mnt/torrents/downloads:/data/watch \
        -v /mnt/torrents/downloads/completed:/data/completed \
        -v /mnt/torrents/downloads/incomplete:/data/incomplete \
        -v /etc/localtime:/etc/localtime:ro \
        -e CREATE_TUN_DEVICE=true \
        -e OPENVPN_PROVIDER=\
        -e OPENVPN_CONFIG= \
        -e OPENVPN_USERNAME=\
        -e OPENVPN_PASSWORD=\
        -e WEBPROXY_ENABLED=false \
        -e LOCAL_NETWORK=192.168.1.0/24 \
        -e TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true \
        -e TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/data/unrar.sh \
        -e TRANSMISSION_WEB_UI=transmission-web-control \
        -e WEBPROXY_ENABLED=true \
        -e WEBPROXY_PORT=8888\
        --restart unless-stopped \
        --log-driver json-file \
        --log-opt max-size=10m \
        -p 9091:9091 \
        haugene/transmission-openvpn:latest-armhf
```
Jackett
```
docker create
  --name=jackett \
  --net=container:vpn \
  -e PUID=1001 \
  -e PGID=1001 \
  -e TZ=America/New_York \
  -v /mnt/torrents/dockerConfig/jackett:/config \
  -v /mnt/torrents/downloads:/downloads \
  --restart unless-stopped \
  linuxserver/jackett
```
PS - Sorry I couldn't figure out how to get new line breaks in the code

**Comment by haugene** [comment]
When using --network=container the new container is not assigned a new IP as it is attached to the network stack of the other container. This also means that if you want to forward port 9117 for Jackett you need to do this on the vpn container. Then it will be available when Jackett attaches later. The rest of your config looks good 👍 

As for the multiline code. The code syntax is to have a ` sign on each side. For multiline blocks, just triple it. so do ``` on the lines above and below your code, and that should be it.


```
docker run -d --name beautiful
  multiline
```

**Comment by gist901** [comment]
Many thanks haugene for the information! I added the following syntax to my VPN config

``` -p 9117:9117 \ ``` 

I can now access Jackett. This was a very simple solution. Many thanks for the help and this awesome docker container!
