### ISSUE TITLE
Container periodically stops working until system reboot, then works again

### ISSUE THREAD

**Issue by dlowd** [haugene/docker-transmission-openvpn#862]
**Describe the problem**
I'm running the container on a QNAP NAS, connecting to PIA. The container works fine for a few days, but then it starts rebooting every ~30 seconds. After rebooting the NAS, the container works again. Nothing else seems to fix it, including removing the container and its image and rebuilding the container from scratch.

**Add your docker run command**

docker run --restart=always --name=transmission \
   --cap-add=NET_ADMIN --device=/dev/net/tun -d \
   -v /share/Transmission:/data \
   -v /etc/localtime:/etc/localtime:ro \
   -v /share/Transmission/resolv.conf:/etc/resolv.conf \
   -e "OPENVPN_PROVIDER=PIA" \
   -e "OPENVPN_USERNAME=*****" \
   -e "OPENVPN_PASSWORD=*****" \
   -e "OPENVPN_CONFIG=CA Toronto" \
   -e "LOCAL_NETWORK=192.168.1.0/24" \
   -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 300" \
   --log-driver json-file \
   --log-opt max-size=10m \
   -p 9091:9091 \
   haugene/transmission-openvpn

**Logs**

EXAMPLE LOGS WHEN FAILING:

Using OpenVPN provider: PIA
Starting OpenVPN using config CA Toronto.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 10.0.3.1 dev eth0
Sat Jul 20 00:26:24 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Sat Jul 20 00:26:24 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sat Jul 20 00:26:24 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Jul 20 00:26:24 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.69:1198
Sat Jul 20 00:26:24 2019 UDP link local: (not bound)
Sat Jul 20 00:26:24 2019 UDP link remote: [AF_INET]172.98.67.69:1198
Sat Jul 20 00:26:24 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Jul 20 00:26:24 2019 [41ee26e72fda9a8f6ec950d73fb7ac1e] Peer Connection Initiated with [AF_INET]172.98.67.69:1198
Using OpenVPN provider: PIA
Starting OpenVPN using config CA Toronto.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 10.0.3.1 dev eth0
Sat Jul 20 00:26:28 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Sat Jul 20 00:26:28 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sat Jul 20 00:26:28 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Jul 20 00:26:28 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.69:1198
Sat Jul 20 00:26:28 2019 UDP link local: (not bound)
Sat Jul 20 00:26:28 2019 UDP link remote: [AF_INET]172.98.67.69:1198
Sat Jul 20 00:26:28 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Jul 20 00:26:28 2019 [41ee26e72fda9a8f6ec950d73fb7ac1e] Peer Connection Initiated with [AF_INET]172.98.67.69:1198
Sat Jul 20 00:26:30 2019 TUN/TAP device tun0 opened
Sat Jul 20 00:26:30 2019 /sbin/ip link set dev tun0 up mtu 1500
Sat Jul 20 00:26:30 2019 /sbin/ip addr add dev tun0 local 10.85.10.6 peer 10.85.10.5
Sat Jul 20 00:26:30 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.85.10.6 10.85.10.5 init
Up script executed with tun0 1500 1558 10.85.10.6 10.85.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.85.10.6
Generating transmission settings.json from env variables
sed'ing True to true

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Sat Jul 20 00:26:30 2019 Initialization Sequence Completed
Generating new client id for PIA
Got new port 58972 from PIA
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Using OpenVPN provider: PIA
Starting OpenVPN using config CA Toronto.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 10.0.3.1 dev eth0
Sat Jul 20 00:26:57 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Sat Jul 20 00:26:57 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sat Jul 20 00:26:57 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Jul 20 00:26:58 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.69:1198
Sat Jul 20 00:26:58 2019 UDP link local: (not bound)
Sat Jul 20 00:26:58 2019 UDP link remote: [AF_INET]172.98.67.69:1198
Sat Jul 20 00:26:58 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Jul 20 00:26:58 2019 [41ee26e72fda9a8f6ec950d73fb7ac1e] Peer Connection Initiated with [AF_INET]172.98.67.69:1198
Sat Jul 20 00:26:59 2019 TUN/TAP device tun0 opened
Sat Jul 20 00:26:59 2019 /sbin/ip link set dev tun0 up mtu 1500
Sat Jul 20 00:26:59 2019 /sbin/ip addr add dev tun0 local 10.35.10.10 peer 10.35.10.9
Sat Jul 20 00:26:59 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.35.10.10 10.35.10.9 init
Up script executed with tun0 1500 1558 10.35.10.10 10.35.10.9 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.35.10.10
Generating transmission settings.json from env variables
sed'ing True to true

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Sat Jul 20 00:26:59 2019 Initialization Sequence Completed
Got new port 58972 from PIA
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Port is open: Yes
Using OpenVPN provider: PIA
Starting OpenVPN using config CA Toronto.ovpn
Setting OPENVPN credentials...

...and then this repeats over and over again...

EXAMPLE LOGS WHEN SUCCEEDING:

Using OpenVPN provider: PIA
Starting OpenVPN using config CA Toronto.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 10.0.3.1 dev eth0
Sat Jul 20 01:05:09 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Sat Jul 20 01:05:09 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sat Jul 20 01:05:09 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Jul 20 01:05:09 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.85:1198
Sat Jul 20 01:05:09 2019 UDP link local: (not bound)
Sat Jul 20 01:05:09 2019 UDP link remote: [AF_INET]172.98.67.85:1198
Sat Jul 20 01:05:09 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Jul 20 01:05:09 2019 [e6a23fca9c68b963fcf314a41f1751f6] Peer Connection Initiated with [AF_INET]172.98.67.85:1198
Sat Jul 20 01:05:10 2019 TUN/TAP device tun0 opened
Sat Jul 20 01:05:10 2019 /sbin/ip link set dev tun0 up mtu 1500
Sat Jul 20 01:05:10 2019 /sbin/ip addr add dev tun0 local 10.47.11.6 peer 10.47.11.5
Sat Jul 20 01:05:10 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.47.11.6 10.47.11.5 init
Up script executed with tun0 1500 1558 10.47.11.6 10.47.11.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.47.11.6
Generating transmission settings.json from env variables
sed'ing True to true

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Sat Jul 20 01:05:10 2019 Initialization Sequence Completed
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Got new port 58972 from PIA
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Port is open: Yes

**Host system:**

QNAP NAS

docker version:

Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   0a5102e
 Built:        Wed Nov 28 10:48:56 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   0a5102e
 Built:        Wed Nov 28 10:48:56 2018
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by airship-david** [comment]
+1

**Comment by mrjackyliang** [comment]
I can't seem to figure this out as there is no logs that state the container is being restarted. What I do notice is that the logs always start with:
```
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
```
Perhaps it is something that you're running that is causing the 30 second reboots?

**Comment by dlowd** [comment]
I don't know what's causing the reboots. My best guess is that something in the container dies (or kills itself, perhaps related to an automated internet kill switch for some VPNs?), and then it auto-restarts as specified by the "docker run --restart=always" command.

Here's what the docker ps command looks like right now:

```
[~] # docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                             PORTS                              NAMES
b30caef1bbb5        haugene/transmission-openvpn   "dumb-init /etc/op..."   5 days ago          Up 11 seconds (health: starting)   8888/tcp, 0.0.0.0:9091->9091/tcp   transmission
a5def1dfce73        coppit/filebot                 "/sbin/my_init"          4 weeks ago         Up 5 days                          3389/tcp, 8080/tcp                 filebot
30602c94d34f        linuxserver/radarr             "/init"                  5 months ago        Up 5 days                          0.0.0.0:7878->7878/tcp             radarr
d879e93c7a35        linuxserver/sonarr             "/init"                  5 months ago        Up 5 days                          0.0.0.0:8989->8989/tcp             sonarr
c0732040bc5f        linuxserver/jackett            "/init"                  5 months ago        Up 5 days                          0.0.0.0:9117->9117/tcp             jackett
[~] #
```

**Comment by mrjackyliang** [comment]
The only thing I can think of that causes the reboots is the tun tap driver itself. My VPN purposely stalls itself (and I wrote a script to restart it), but never does it restart itself.

If the web interface never shows up, then it could be a high possibility that the config is not working at the moment, or it's a wrong config.

**Comment by dlowd** [comment]
The web interface actually does show up before it reboots. Sometimes a torrent even starts transferring data. And then it loses connection, and the cycle repeats.

**Comment by haugene** [comment]
There's something strange about you needing to restart the host system. I see you're mounting the /dev/net/tun device from the host - could you try the `CREATE_TUN_DEVICE=true` variable and drop the `--device` option?

And also. Looking at your logs from the times it is failing. It seems so abrupt, with no indication as to what is failing. Every time it prints `Using OpenVPN provider: PIA` it is just starting a new cycle. So the last line before that will be the last line of the last attempt. And there is no consistency. The first time it happens after `Peer Connection Initiated`, the second time it's while checking if the port is open and the third time it's after verifying that the port is opened.

It doesn't seem to be dependant on where in the process it is, so I'm thinking that it could be a timer of sorts or something on the system.

It's also usually interesting to see if it runs in a "bare minimum" options setup. Something like:
```
docker run --restart=always --name=transmission \
--cap-add=NET_ADMIN --device=/dev/net/tun -d \
-e "OPENVPN_PROVIDER=PIA" \
-e "OPENVPN_USERNAME=" \
-e "OPENVPN_PASSWORD=" \
-e "OPENVPN_CONFIG=CA Toronto" \
haugene/transmission-openvpn
```

Or with the CREATE_TUN_DEVICE flag I mentioned:
```
docker run --restart=always --name=transmission \
--cap-add=NET_ADMIN -d \
-e "CREATE_TUN_DEVICE=true" \
-e "OPENVPN_PROVIDER=PIA" \
-e "OPENVPN_USERNAME=" \
-e "OPENVPN_PASSWORD=" \
-e "OPENVPN_CONFIG=CA Toronto" \
haugene/transmission-openvpn
```

**Comment by dlowd** [comment]
Thanks for the response! I can run transmission with the minimal options, but running curl returns:

`<h1>301: Moved Permanently</h1>`

And when I check its status in docker ps, it says: "Up 3 minutes (health: starting)".

If I add a few more options (port mapping, directory mapping, and local network), then transmission runs fine:

    docker run --restart=always --name=transmission \
    --cap-add=NET_ADMIN -d \
    -v /share/Transmission:/data \
    -e "CREATE_TUN_DEVICE=true" \
    -e "OPENVPN_PROVIDER=PIA" \
    -e "OPENVPN_USERNAME=" \
    -e "OPENVPN_PASSWORD=" \
    -e "OPENVPN_CONFIG=CA Toronto" \
    -e "LOCAL_NETWORK=192.168.1.0/24" \
    -p 9091:9091 \
    haugene/transmission-openvpn

I'll let this run for a few days and report back if/when the infinite rebooting happens again.

**Comment by mrjackyliang** [comment]
Let us know if there are any problems.

**Comment by dlowd** [comment]
So it ran fine for a couple of days, and now it's repeatedly rebooting again. The instigating incident may have been a brief loss of internet access (ISP seemed to go down for about a minute or so before coming back). I've attached the full logs from the semi-minimal docker setup. I also tried an even more bare setup as well (skipping the directory and port mapping), and that one is rebooting just the same.

[transmission-logs.txt](https://github.com/haugene/docker-transmission-openvpn/files/3459704/transmission-logs.txt)

**Comment by dlowd** [comment]
Sadly, no. Roughly once a week, Transmission gets stuck in a reboot loop, at which point I ssh in and reboot the NAS. I also run coppit/filebot, linuxserver/jackett, linuxserver/sonarr, and linuxserver/radarr. I haven't seen this behavior with any of the others. Of course, this is the only one that's working with a VPN.

For now, I'm just accepting that periodic reboots are the required workaround.

**Comment by jyc66** [comment]
I have been seeing the same thing.  It worked flawless for months but I noticed a lack of successful downloads lately and saw that it was restarting every 30 seconds.  I haven't rebooted yet to see if that fixes it temporarily.  I will try that later tonight.

**Comment by haugene** [comment]
Also on a QNAP NAS @jyc66? Or another system? Can you print host OS, linux kernel and Docker versions? Maybe there are similarities?

**Comment by jyc66** [comment]
Yes, QNAP as well.

**Comment by jyc66** [comment]
Docker version 17.09.1-ce, build e398b97
It's a QNAP TS-453BE firmware version 4.3.6.0979

The NAS is running Container Station 2.0.356.  (This app is what provides docker support on the NAS).

Linux Kernel 4.2.8

**Comment by honestbleeps** [comment]
I see commenting on this has stopped, but I'm wondering if it's still an issue or if perhaps a firmware update from QNAP fixed this?

I'm considering installing on a qnap ts-453be myself, but hesitant to do so given this is still open.  Any updates would be appreciated!

**Comment by turban0** [comment]
For me the issue has stopped, I'm using very outdated docker-transmission-openvpn (more than year), but newest qnap firmware on ts-453a, so I think that something got fixed on qnap side. Anyway I'm using quite "minimal" config on qnap - no fancy vpn services and virtualization stuff in background, that might be related.
