### ISSUE TITLE
Do I need a separate openvpn installation to get this to work?

### ISSUE THREAD

**Issue by jaydoc** [haugene/docker-transmission-openvpn#863]
I cannot get this container to run and am not able to access the webui. 

> Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/fastestvpn/default.ovpn:1: Netherlands-UDP.openvpn (2.4.7)

This is the error I get in the docker log. I have openvpn installed on my router, but not in the server I am trying to run this container on. So there is no /etc/openvpn/fastestvpn directory. 

Should I create it and add the file default.ovpn.1:Netherlands-UDP.openvpn? 

Thanks.

**Comment by mrjackyliang** [comment]
You don't need a separate OpenVPN installation to work, but it's recommend to use with VPN providers that are already supported with the container.

**Comment by jaydoc** [comment]
This is my docker-compose section

>container_name: transmission-vpn
image: haugene/transmission-openvpn
cap_add:
- NET_ADMIN
devices:
- /dev/net/tun
restart: always
ports:
 - "9091:9091"
dns:
     - 1.1.1.1
  - 1.0.0.1
volumes:
  - /etc/localtime:/etc/localtime:ro
  - ${USERDIR}/docker/transmission-vpn:/data
  - ${USERDIR}/docker/shared:/shared
- ${USERDIR}/Downloads:/data/watch
  - ${USERDIR}/Downloads/completed:/data/completed
  - ${USERDIR}/Downloads/incomplete:/data/incomplete

environment:
- OPENVPN_PROVIDER=FASTESTVPN
- OPENVPN_USERNAME=User
- OPENVPN_PASSWORD=Pass
- OPENVPN_CONFIG=
- OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-ex$
- LOCAL_NETWORK=192.168.1.0/24
- PUID=${PUID}
- PGID=${PGID}
- TZ=${TZ}
- TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
- TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.1.139$
- TRANSMISSION_RPC_PASSWORD=Pass
- TRANSMISSION_RPC_USERNAME=User
- TRANSMISSION_UMASK=002
- TRANSMISSION_RATIO_LIMIT=1.00
 - TRANSMISSION_RATIO_LIMIT_ENABLED=true

Not sure where I am going wrong since fastestvpn is a supported provider.

**Comment by mrjackyliang** [comment]
Try adding the specific config for the VPN, not sure why this happens without logs present.

**Comment by jaydoc** [comment]
> Try adding the specific config for the VPN, not sure why this happens without logs present.

How do I do that? What should I add in the docker-compose file? 

Thanks.

**Comment by mrjackyliang** [comment]
Try using `Netherlands-UDP` for the OpenVPN config instead of manually adding the file.

**Comment by jaydoc** [comment]
That worked and I am able to access the webui now. Thanks.

**Comment by mrjackyliang** [comment]
No problem! Marking this as resolved.
