### ISSUE TITLE
Transmission_VPN does NOT work on UNRAID server

### ISSUE THREAD

**Issue by vpn00000** [haugene/docker-transmission-openvpn#865]
I installed Transmission_VPN via apps on UNRAID server.

The app starts, but connection log shows: "Exiting due to fatal error"

Why is this happening???

According to the log, the server is trying to find .ovpn file that does not exits. It is NOT POSSIBLE to edit OPENVPN_CONFIG: field. Whatever I enter, is automatically defaulted to some other ovpn name, that does not match those on https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn AT ALL. Adding .ovpn file either from github or from Mullvad site into appdata/Transmission_VPN folder does not work. Renaming the .ovpn file doesn't do anything either. Adding openvpn folder and putting same files here doesnt work either. Certificate is trying to be read from location tat doesn't exist.

What is wrong with this docker image?

Why will the server not start?

![vpn](https://user-images.githubusercontent.com/53250755/61770748-fc022780-adbb-11e9-91be-0bfb34a60e0e.jpg)
![vpn1](https://user-images.githubusercontent.com/53250755/61770750-fe648180-adbb-11e9-8324-23fde974f102.jpg)
![errror](https://user-images.githubusercontent.com/53250755/61805343-a487aa00-ae03-11e9-8cce-7b65e2d919b0.jpg)

**Comment by mrjackyliang** [comment]
The config has to follow the files name structure inside the `openvpn/mullvad/` folder.

**Comment by mrjackyliang** [comment]
If I got the country code right, the 4 choices for Switzerland is `mullvad_ch_tcp443`, `mullvad_ch_tcp80`, `mullvad_ch_udp`, and `mullvad_ch_udp53`.

Closing this for now as I believe I have solve this issue. Let me know if I didn't and I'll reopen this issue.
