### ISSUE TITLE
404 transmission-web-control/index.html (No such file or directory)

### ISSUE THREAD

**Issue by rinzes** [haugene/docker-transmission-openvpn#870]
I.m running your Docker package on Synology and it's running ok. When I go to the ip:9091 WebUI I get 404 transmission-web-control/index.html (No such file or directory)

**Comment by mrjackyliang** [comment]
Which version are you pulling?

**Comment by rinzes** [comment]
The latest 2 days ago

**Comment by mrjackyliang** [comment]
Can you paste the configuration that you used to create the container? That will help me further debug the issue.

**Comment by rinzes** [comment]
Here you go...

{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "dumb-init /etc/openvpn/start.sh",
   "cpu_priority" : 50,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : false,
   "env_variables" : [
      {
         "key" : "TZ",
         "value" : "America/Boise"
      },
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "OPENVPN_USERNAME",
         "value" : "p8671846"
      },
      {
         "key" : "OPENVPN_PASSWORD",
         "value" : "c6tr4UGYBV"
      },
      {
         "key" : "OPENVPN_PROVIDER",
         "value" : "PIA"
      },
      {
         "key" : "GLOBAL_APPLY_PERMISSIONS",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_DOWN",
         "value" : "50"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_BEGIN",
         "value" : "540"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_DAY",
         "value" : "127"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_TIME_END",
         "value" : "1020"
      },
      {
         "key" : "TRANSMISSION_ALT_SPEED_UP",
         "value" : "50"
      },
      {
         "key" : "TRANSMISSION_BIND_ADDRESS_IPV4",
         "value" : "0.0.0.0"
      },
      {
         "key" : "TRANSMISSION_BIND_ADDRESS_IPV6",
         "value" : "::"
      },
      {
         "key" : "TRANSMISSION_BLOCKLIST_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_BLOCKLIST_URL",
         "value" : "http://www.example.com/blocklist"
      },
      {
         "key" : "TRANSMISSION_CACHE_SIZE_MB",
         "value" : "4"
      },
      {
         "key" : "TRANSMISSION_DHT_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_DIR",
         "value" : "/data/completed"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_LIMIT",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_LIMIT_ENABLED",
         "value" : "0"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_QUEUE_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_DOWNLOAD_QUEUE_SIZE",
         "value" : "5"
      },
      {
         "key" : "TRANSMISSION_ENCRYPTION",
         "value" : "1"
      },
      {
         "key" : "TRANSMISSION_IDLE_SEEDING_LIMIT",
         "value" : "30"
      },
      {
         "key" : "TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_INCOMPLETE_DIR",
         "value" : "/data/incomplete"
      },
      {
         "key" : "TRANSMISSION_INCOMPLETE_DIR_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_LPD_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_MAX_PEERS_GLOBAL",
         "value" : "200"
      },
      {
         "key" : "TRANSMISSION_MESSAGE_LEVEL",
         "value" : "2"
      },
      {
         "key" : "TRANSMISSION_PEER_CONGESTION_ALGORITHM",
         "value" : ""
      },
      {
         "key" : "TRANSMISSION_PEER_ID_TTL_HOURS",
         "value" : "6"
      },
      {
         "key" : "TRANSMISSION_PEER_LIMIT_GLOBAL",
         "value" : "200"
      },
      {
         "key" : "TRANSMISSION_PEER_LIMIT_PER_TORRENT",
         "value" : "50"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT",
         "value" : "51413"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT_RANDOM_HIGH",
         "value" : "65535"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT_RANDOM_LOW",
         "value" : "49152"
      },
      {
         "key" : "TRANSMISSION_PEER_PORT_RANDOM_ON_START",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_PEER_SOCKET_TOS",
         "value" : "default"
      },
      {
         "key" : "TRANSMISSION_PEX_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_PORT_FORWARDING_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_PREALLOCATION",
         "value" : "1"
      },
      {
         "key" : "TRANSMISSION_PREFETCH_ENABLED",
         "value" : "1"
      },
      {
         "key" : "TRANSMISSION_QUEUE_STALLED_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_QUEUE_STALLED_MINUTES",
         "value" : "30"
      },
      {
         "key" : "TRANSMISSION_RATIO_LIMIT",
         "value" : "2"
      },
      {
         "key" : "TRANSMISSION_RATIO_LIMIT_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_RENAME_PARTIAL_FILES",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_RPC_BIND_ADDRESS",
         "value" : "0.0.0.0"
      },
      {
         "key" : "TRANSMISSION_RPC_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_RPC_HOST_WHITELIST",
         "value" : ""
      },
      {
         "key" : "TRANSMISSION_RPC_HOST_WHITELIST_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_RPC_PASSWORD",
         "value" : "password"
      },
      {
         "key" : "TRANSMISSION_RPC_PORT",
         "value" : "9091"
      },
      {
         "key" : "TRANSMISSION_RPC_URL",
         "value" : "/transmission/"
      },
      {
         "key" : "TRANSMISSION_RPC_USERNAME",
         "value" : "username"
      },
      {
         "key" : "TRANSMISSION_RPC_WHITELIST",
         "value" : "127.0.0.1"
      },
      {
         "key" : "TRANSMISSION_RPC_WHITELIST_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME",
         "value" : ""
      },
      {
         "key" : "TRANSMISSION_SEED_QUEUE_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SEED_QUEUE_SIZE",
         "value" : "10"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_DOWN",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_UP",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_SPEED_LIMIT_UP_ENABLED",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_START_ADDED_TORRENTS",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_UMASK",
         "value" : "2"
      },
      {
         "key" : "TRANSMISSION_UPLOAD_LIMIT",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_UPLOAD_LIMIT_ENABLED",
         "value" : "0"
      },
      {
         "key" : "TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT",
         "value" : "14"
      },
      {
         "key" : "TRANSMISSION_UTP_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_WATCH_DIR",
         "value" : "/data/watch"
      },
      {
         "key" : "TRANSMISSION_WATCH_DIR_ENABLED",
         "value" : "true"
      },
      {
         "key" : "TRANSMISSION_HOME",
         "value" : "/data/transmission-home"
      },
      {
         "key" : "TRANSMISSION_WATCH_DIR_FORCE_GENERIC",
         "value" : "false"
      },
      {
         "key" : "ENABLE_UFW",
         "value" : "false"
      },
      {
         "key" : "UFW_ALLOW_GW_NET",
         "value" : "false"
      },
      {
         "key" : "UFW_EXTRA_PORTS",
         "value" : ""
      },
      {
         "key" : "UFW_DISABLE_IPTABLES_REJECT",
         "value" : "false"
      },
      {
         "key" : "TRANSMISSION_WEB_UI",
         "value" : ""
      },
      {
         "key" : "PUID",
         "value" : "1029"
      },
      {
         "key" : "PGID",
         "value" : "100"
      },
      {
         "key" : "TRANSMISSION_WEB_HOME",
         "value" : "transmission-web-control"
      },
      {
         "key" : "DROP_DEFAULT_ROUTE",
         "value" : ""
      },
      {
         "key" : "WEBPROXY_ENABLED",
         "value" : "false"
      },
      {
         "key" : "WEBPROXY_PORT",
         "value" : "8888"
      },
      {
         "key" : "HEALTH_CHECK_HOST",
         "value" : "google.com"
      },
      {
         "key" : "--cap-add",
         "value" : "NET_ADMIN"
      },
      {
         "key" : "--device",
         "value" : "/dev/net/tun"
      },
      {
         "key" : "OPENVPN_OPTS",
         "value" : "--inactive 3600 --ping 10 --ping-exit 60"
      },
      {
         "key" : "LOCAL_NETWORK",
         "value" : "192.168.182.0/24"
      }
   ],
   "exporting" : false,
   "id" : "01030fe7141cde7b6eef6751df170716287b700cd922344ea3baf51979c60f0f",
   "image" : "haugene/transmission-openvpn:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 1073741824,
   "memory_limit_slider" : 1024,
   "name" : "haugene-transmission-openvpn1",
   "network" : [
      {
         "driver" : "host",
         "name" : "host"
      }
   ],
   "network_mode" : "host",
   "port_bindings" : [],
   "privileged" : true,
   "shortcut" : {
      "enable_shortcut" : true,
      "enable_status_page" : false,
      "enable_web_page" : true,
      "web_page_url" : "http://192.168.182.250:9091"
   },
   "ulimits" : null,
   "use_host_network" : true,
   "volume_bindings" : [
      {
         "host_volume_file" : "/torrents/transmissionVPN/resolv.conf",
         "mount_point" : "/etc/resolv.conf",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/downloads/TransmissionVPN",
         "mount_point" : "/data",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/torrents/transmissionVPN",
         "mount_point" : "/config",
         "type" : "rw"
      }
   ],
   "volumes_from" : null
}

**Comment by saikpr** [comment]
I'm also having the same issue, here's the compose file which I used : https://gist.github.com/saikpr/332ff7b609a6f6d07b59cd29e77b0a1b

**Comment by saikpr** [comment]
Ahh sorry my bad, the issue is that I was providing a custom "TRANSMISSION_WEB_HOME" which was not accepted. After removing it started to work

**Comment by rinzes** [comment]
saikpr comments fixed mine
