### ISSUE TITLE
openvpn restarting frequently to disrupt function, Mullvad VPN

### ISSUE THREAD

**Issue by exaiyo** [haugene/docker-transmission-openvpn#871]
The container starts, I can access transmission web GUI, but the logs indicate that the openvpn connection is being reset frequently enough to impede proper function and eventually it becomes unresponsive totally with name resolution error, unable to resolve mullvad's domain name.  The config I'm using worked perfectly a few months ago when I last used it.  The problem occurs even when I try mullvad_us_tcp443 config.  EDIT: I've now tried v2.6 of the docker build and still the same problem.  I configured openvpn client on host with transmission and it works fine.

docker command:
```
docker run -dt --name=trans \
	--network=torr \
	--restart=always \
	--sysctl net.ipv6.conf.all.disable_ipv6=0 \
	--cap-add NET_ADMIN \
	--dns 8.8.8.8
	-v /media/aux/data/transmission:/data \
	-v /etc/localtime:/etc/localtime:ro \
	--env-file /root/docker/transmission/env \
	--log-driver json-file \
	--log-opt max-size=10m \
	-p 9091:9091 \
	haugene/transmission-openvpn
```

env file:
```
PUID=1489
PGID=1489
CREATE_TUN_DEVICE=true
OPENVPN_PROVIDER=MULLVAD
OPENVPN_CONFIG=mullvad_us_udp
OPENVPN_USERNAME=redacted 
OPENVPN_PASSWORD=redacted
OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
DROP_DEFAULT_ROUTE=true
LOCAL_NETWORK=10.0.14.0/24
ENABLE_UFW=false
UFW_ALLOW_GW_NET=true
```

Logs:
https://pastebin.com/XeN3w4fm

This occurs after i leave the container failing for long enough:
RESOLVE: Cannot resolve host address: us.mullvad.net:1301 (Temporary failure in name resolution)

Host: Gentoo up to date with Docker 18.09.7

**Comment by XenGi** [comment]
I still have this exact issue.

**Comment by haugene** [comment]
@XenGi Have you tried setting the --dns flags as mentioned here? https://haugene.github.io/docker-transmission-openvpn/known-issues/#use_google_dns_servers
