### ISSUE TITLE
Stop seeding on idle?

### ISSUE THREAD

**Issue by eflemingtra** [haugene/docker-transmission-openvpn#872]
**Is your feature request related to a problem? Please describe.**

Hi, is there (or if not can we) a way to stop seeding on idle through an envrionmental argument, say TRANSMISSION_STOP_IDLE=enabled, and another argument for idle time? I know this can be done in preferences but that doesn't survive container restart.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by matthewmcpartland** [comment]
Yes, listed here are all the settings you can alter with the settings.json file that transmission supports.

These lines would need to be added to your configuration (of course with N replaced with desired minutes) which is likely in a systemd unit or you may need to rebuild the container if you ran it manually:

-e "TRANSMISSION_IDLE-SEEDING-LIMIT=N" \
-e "TRANSMISSION_SEEDING-LIMIT-ENABLED=true" \

If these settings don't work for you, let me know. I've had trouble with alt-speed-time-day

**Comment by eflemingtra** [comment]
> -e "TRANSMISSION_IDLE-SEEDING-LIMIT=N" 
> -e "TRANSMISSION_SEEDING-LIMIT-ENABLED=true" \

Should that be TRANSMISSION_IDLE-SEEDING-LIMIT-ENABLED ?

**Comment by matthewmcpartland** [comment]
Yes my apologies. I've updated my reply above with the correct argument, as it should also be underscores instead of hyphens

**Comment by JeroenDM-BE** [comment]
Hi, have still the same problem. Seedings stay on idle and so Sonarr doesn't move the completed file.
Above change doens't work.
Everthing works fine execpt after the seeding ratio... idle.

(Rasb PI 4, container dev-armhf.)

Somebody an idea???

**Comment by ToXinE** [comment]
> 
> 
> > -e "TRANSMISSION_IDLE-SEEDING-LIMIT=N"
> > -e "TRANSMISSION_SEEDING-LIMIT-ENABLED=true" \
> 
> Should that be TRANSMISSION_IDLE-SEEDING-LIMIT-ENABLED ?

No, it should be 
`-e "TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true"`
