### ISSUE TITLE
Suggest to use --dns docker option

### ISSUE THREAD

**Issue by paolopan83** [haugene/docker-transmission-openvpn#873]
In my home network configuration DNS is provided by the router, that is 192.168.1.1 which is not a public address.

DNS Resolution is broken inside the container. The container will inherit this DNS configuration in /etc/resolv.conf. I assume that once the vpn tunnel is enabled this IP can't be reached anymore. 

I solved the issue by adding

`--dns=8.8.8.8`

to  `docker run` command. As this can be a fairly common issue and not so easy to troubleshoot it would be nice to have some clue in the documentation.

**Comment by pkishino** [comment]
this is covered in https://haugene.github.io/docker-transmission-openvpn/known-issues/

**Comment by haugene** [comment]
As @pkishino says it's already in the documentation, but I get your point, maybe it should be even clearer. I'm thinking about how to best structure the docs - and one improvement lately has been to move it to GitHub pages (#825).

There are a lot of clever and much used options (like --dns) that we maybe should consider default and add it to the example `docker run` command. But there's also something about keeping the examples simple and then explaining the additional features separately.

This will be considered. The DNS-option is a very frequent flyer on the issue-pages. But I'm closing this for now and will follow later up in #362
