### ISSUE TITLE
Stuck on starting

### ISSUE THREAD

**Issue by masterxdk** [haugene/docker-transmission-openvpn#874]
Hi,

I have issues starting the container. Keeps saying starting in container health.
In the logs, the last entry is: "Port is open: Yes"

What can be done to fix this? Its running as root

I've tried messing the the proxy settings, the firewall settings and the global apply permission without any luck.

Hope someone else knows what to do :)

**Comment by reptilbud** [comment]
Hi @masterxdk 

Did you find how to manage it ? I'm also stuck at the same point...

**Comment by barronlroth** [comment]
@reptilbud @masterxdk did either of you manage to solve this? Just got this issue.
