### ISSUE TITLE
Windows Configuration

### ISSUE THREAD

**Issue by MrMACHOMAN86** [haugene/docker-transmission-openvpn#875]
I can't seem to get the image running correctly. Even when I tweak the settings to get the WebGUI to load, it seems the download path is invalid in Transmission as it's missing the forward slashes.

docker run --cap-add=NET_ADMIN --privileged="true" -d -v F:\\data:\data -e CREATE_TUN_DEVICE=true -e TRANSMISSION_DOWNLOAD_DIR=F:\\data\\completed -e TRANSMISSION_INCOMPLETE_DIR=F:\\data\\incomplete -e OPENVPN_PROVIDER=NORDVPN -e NORDVPN_COUNTRY=us -e OPENVPN_USERNAME=xxx -e OPENVPN_PASSWORD=xxx -e OPENVPN_OPTS=--mute-replay-warnings -e WEBPROXY_ENABLED=false -e LOCAL_NETWORK=192.168.0.0/16 --log-driver json-file --log-opt max-size=50m --log-opt max-file=1 --dns 8.8.8.8 --dns 8.8.4.4 -p 9091:9091 haugene/transmission-openvpn

**Logs**

Fri Aug  9 04:09:44 2019 Initialization Sequence Completed

[2019-08-09 04:09:44.542] JSON parse failed in /data/transmission-home/settings.json at pos 448: ESCAPE_INVALID -- remaining text "data\completed","

**Host system:**
Windows 10 Pro.

I previously had this working in Ubuntu, but I can't get the Windows paths to work.

**Comment by haugene** [comment]
It's important to remember that the inside of the container is a linux-distro even if you're running it on a windows host. So you can use volume mounts to mount a directory from your host to the container - but that doesn't change the directories in the container.

Even after your `-v F:\data:\data`, it's still `/data/completed` and `/data/incomplete` inside the container. So skip overriding the TRANSMISSION_DOWNLOAD_DIR and TRANSMISSION_INCOMPLETE_DIR variables.

Then whether it should be `-v F:\data:\data` or `-v F:/data:/data` as [this example](https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c) shows you'll just have to find out. Should be some pointers here as well: https://docs.docker.com/docker-for-windows/
