### ISSUE TITLE
Timeout when accessing port [RaspberryPi]

### ISSUE THREAD

**Issue by kilmc** [haugene/docker-transmission-openvpn#877]
**Describe the problem**
I'm having an issue where accessing the port that transmission is timing out. The logs say it succeeded but I have yet to load the Transmission UI. I'm not exactly sure what to try at this point, any and all help would be appreciated. Thanks!

**Docker run command**
```
docker run --cap-add=NET_ADMIN -d \
  -v /home/pi/docker/:/data \
  -v /etc/localtime:/etc/localtime:ro \
  -e CREATE_TUN_DEVICE=true \
  -e OPENVPN_PROVIDER=PIA \
  -e OPENVPN_CONFIG=CA\ Toronto \
  -e OPENVPN_USERNAME=**** \
  -e OPENVPN_PASSWORD=**** \
  -e TRANSMISSION_WEB_UI=combustion \
  -e WEBPROXY_ENABLED=false \
  -e LOCAL_NETWORK=192.168.1.1/24 \
  --log-driver json-file \
  --log-opt max-size=10m \
  --dns 8.8.8.8 \
  --dns 8.8.4.4 \
  -p 192.168.1.13:9091:9091 \
  haugene/transmission-openvpn:latest-armhf
```

**Logs**
```
Using OpenVPN provider: PIA,
Starting OpenVPN using config CA Toronto.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.1/24 via 172.17.0.1 dev eth0,
RTNETLINK answers: Invalid argument,
Tue Aug  6 03:09:17 2019 OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Oct 14 2018,
Tue Aug  6 03:09:17 2019 library versions: OpenSSL 1.0.2r  26 Feb 2019, LZO 2.08,
Tue Aug  6 03:09:17 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Tue Aug  6 03:09:17 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.18:1198,
Tue Aug  6 03:09:17 2019 UDP link local: (not bound),
Tue Aug  6 03:09:17 2019 UDP link remote: [AF_INET]172.98.67.18:1198,
Tue Aug  6 03:09:17 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Tue Aug  6 03:09:17 2019 [f804ad24bda3202144aa48497b9b433b] Peer Connection Initiated with [AF_INET]172.98.67.18:1198,
Tue Aug  6 03:09:18 2019 TUN/TAP device tun0 opened,
Tue Aug  6 03:09:18 2019 do_ifconfig, tt->did_ifconfig_ipv6_setup=0,
Tue Aug  6 03:09:18 2019 /sbin/ip link set dev tun0 up mtu 1500,
Tue Aug  6 03:09:18 2019 /sbin/ip addr add dev tun0 local 10.77.10.6 peer 10.77.10.5,
Tue Aug  6 03:09:18 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.77.10.6 10.77.10.5 init,
Up script executed with tun0 1500 1558 10.77.10.6 10.77.10.5 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.77.10.6,
Using Combustion UI, overriding TRANSMISSION_WEB_HOME,
Generating transmission settings.json from env variables,
sed'ing True to true,
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   root,
User uid:    0,
User gid:    0,
-------------------------------------,
,
STARTING TRANSMISSION,
CONFIGURING PORT FORWARDING,
Transmission startup script complete.,
Wait for tunnel to be fully initialized and PIA is ready to give us a port,
Tue Aug  6 03:09:18 2019 Initialization Sequence Completed,
Generating new client id for PIA,
Got new port 23987 from PIA,
transmission auth not required,
localhost:9091/transmission/rpc/ responded: "success",
Checking port...,
Port is open: Yes,
```

**Host system:**
OS: Raspbian GNU/Linux 10 (buster)
Docker: 0.0.0-20190727010531-15bdbd7, build 15bdbd7

**Comment by haugene** [comment]
The setup looks good to me, and the logs as well apart from:
```
adding route to local network 192.168.1.1/24 via 172.17.0.1 dev eth0,
RTNETLINK answers: Invalid argument,
```

Seems like the route to your local network can't be added so that explains the behaviour. I guess if you "docker exec" into the container and do `curl localhost:9091` you get a response?

Where are you trying to get access from? Another machine on the LAN or on the Raspberry Pi?
if you `curl localhost:9091` on the Pi, any difference? or since you're binding the port to 192.168.1.13:9091 maybe try `curl 192.168.1.13:9091` on the Pi?

Any reason you're binding to the IP specifically instead of just -p 9091:9091? Would you mind trying that, not that I can why it would matter here.

**Comment by haugene** [comment]
The `RTNETLINK answers: Invalid argument` is probably more interesting. No special characters or similar things that have gotten in there?

**Comment by kilmc** [comment]
Thanks for the really quick response. I had previously tried `curl`ing on the PI itself from my `ssh` connection and got a `Connection refused` error. I'm using `portainer` to make managing the docker stuff easier but I curled from the container console in `portainer` and got this as a result

```
root@22bd7b526350:/# curl localhost:9091
<h1>301: Moved Permanently</h1>
```

As far as `RTNETLINK`, I'm not sure where to be looking for that? I'm not seeing it as part of the docker command and that's basically the only thing I'm inputting.

**Comment by burnbrigther** [comment]
I have this working with ExpressVPN now and standard transmission.  I just want to get it working with docker-compose, which was quite a bear to get working/installed with pi.

Here is my docker run:
 ```
docker run --name xxx --device=/dev/net/tun --cap-add=NET_ADMIN -d \
 -v /media/winshare/DOWNLOADS:/data \
 -v /etc/localtime:/etc/localtime:ro \
 -v /home/pi/d-hto/d-hto-SF.ovpn:/etc/openvpn/custom/default.ovpn \
 -v /home/pi/d-hto/auth.txt:/etc/openvpn/custom/auth.txt \
 -e CREATE_TUN_DEVICE=true \
 -e OPENVPN_PROVIDER=CUSTOM \
 -e OPENVPN_USERNAME=**** \
 -e OPENVPN_PASSWORD=**** \
 -e WEBPROXY_ENABLED=false \
 -e LOCAL_NETWORK=192.168.1.0/24 \
 -e TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true \
 -e TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*" \
 -e TRANSMISSION_RPC_USERNAME=XXXXXXXXX \
 -e TRANSMISSION_RPC_PASSWORD=XXXXXXXXX \
 -e TRANSMISSION_UMASK=002 \
 -e TRANSMISSION_RATIO_LIMIT=1.00 \
 -e TRANSMISSION_RATIO_LIMIT_ENABLED=true \
 --log-driver json-file \
 --log-opt max-size=10m \
 --dns 8.8.8.8 \
 --dns 8.8.4.4 \
 -p 9091:9091 \
 haugene/transmission-openvpn:latest-armhf
```

**Comment by burnbrigther** [comment]
I cannot get "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" to be passed correctly to pi like it works in x86.  Opening a new issue for this.

**Comment by kilmc** [comment]
Thanks for the suggestion @burnbrigther but sadly that didn't seem to make much difference. I'm still getting the timeout.

@haugene is there anything I can try related to the `RTNETLINK` that you'd suggest?

**Comment by burnbrigther** [comment]
Try moving your config to the external file like I have.  You’ll need to mount the external mapping and locate the file in a local file system.  Check your VPN provider for the right OpenVPN config.
