### ISSUE TITLE
OPENVPN_OPTS don't appear to be accepting options with Pi (ExpressVPN)

### ISSUE THREAD

**Issue by burnbrigther** [haugene/docker-transmission-openvpn#879]
**Describe the problem**

With Raspberry Pi, 

Trying to pass this option via docker run or docker-compose
OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
Pi version fails (latest-armhf), regular version for x86_64 works (haugene/transmission-openvpn)

If I remove the OPENVPN_OPTS - container works without issues.

I've tried this multiple ways with quotes/without, inside of docker and inside of docker-compose.  I can replicate on armv6l and armv7l.

**Add your docker run command**

docker-compose run --publish 8882:9091 -d --name transmission-vpn transmission-vpn 

d-hto-SF.ovpn:
dev tun
fast-io
persist-key
persist-tun
nobind
remote usa-sanfrancisco-ca-version-2.expressnetw.com 1195

remote-random
pull
comp-lzo no
tls-client
verify-x509-name Server name-prefix
ns-cert-type server
key-direction 1
route-method exe
route-delay 2
tun-mtu 1500
fragment 1300
mssfix 1200
verb 3
cipher AES-256-CBC
keysize 256
auth SHA512
sndbuf 524288
rcvbuf 524288
auth-user-pass /etc/openvpn/custom/auth.txt

<cert>
---

docker-compose.yml:
version: '2'
services:
 transmission-vpn:
  container_name: transmission-vpn
  image: haugene/transmission-openvpn:latest-armhf
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /home/pi/d-hto/d-hto-SF.ovpn:/etc/openvpn/custom/default.ovpn
    - /home/pi/d-hto/auth.txt:/etc/openvpn/custom/auth.txt
    - /etc/localtime:/etc/localtime:ro
    - /media/winshare/DOWNLOADS:/data
  environment:
    - OPENVPN_PROVIDER=CUSTOM
    - OPENVPN_USERNAME=dummy
    - OPENVPN_PASSWORD=dummy
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 <----- THIS!
    - LOCAL_NETWORK=192.168.1.0/24
    - WEBPROXY_ENABLED=false
    - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
    - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
    - TRANSMISSION_RPC_USERNAME=XXXXX
    - TRANSMISSION_RPC_PASSWORD=XXXXX
    - TRANSMISSION_UMASK=002
    - TRANSMISSION_RATIO_LIMIT=1.00
    - TRANSMISSION_RATIO_LIMIT_ENABLED=true
**Logs**

No logs are produced because container remains in a state of "restarting...":
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                          PORTS               NAMES
bb2d8f976b38        haugene/transmission-openvpn:latest-armhf   "/usr/bin/entry.sh d…"   52 seconds ago      Restarting (1) 13 seconds ago                       transmission-vpn
**Host system:**

raspberry pi stretch
pi@dockerpi-a:~ $ uname -a
Linux dockerpi-a 4.19.58+ #1245 Fri Jul 12 17:20:08 BST 2019 armv6l GNU/Linux

**Comment by haugene** [comment]
Hmm. You should get logs. If not then it sounds to me as more of a Docker daemon / container compatability (64bit vs 32bit) or something.

If you skip the `restart: always` and just let it start and then die. You still can't get any logs?
