### ISSUE TITLE
Supported Provider Request: Buffered

### ISSUE THREAD

**Issue by RohanHinton** [haugene/docker-transmission-openvpn#882]
**Which provider?**
Buffered VPN

**Where are the configs?**
Buffered VPN allows downloads of ovpn files for it's servers, however these files do not include the user/password to login, only server configs. I have truncated the certs/keys in the attached file.

Below is a link to the .ovpn file (saved as .txt for uploading purposes).
[AU_Australia.ovpn.txt](https://github.com/haugene/docker-transmission-openvpn/files/3513706/AU_Australia.ovpn.txt)

**Comment by russellmann** [comment]
+1 Buffered. Rolled my own, but it would be nice.
