### ISSUE TITLE
Can't get custom provider get to work after Synology-DSM update

### ISSUE THREAD

**Issue by jfml** [haugene/docker-transmission-openvpn#884]
**Describe the problem**
I'm running Transmission in Synology and just updated DSM and the Synology's Docker app (I think it went from 17 to now 18.09). All my other docker containers work well except for Transmission which is restarting constantly saying „OpenVPN provider not set. Exiting.“ I haven't changed anything in the environment settings, I'm using a custom provider and have OPENVPN_PROVIDER=CUSTOM which always worked well (for some reason I also had to set OPENVPN_USERNAME, OPENVPN_PASSWORD even though I know it should work without that). Now all three say **None** when I do a docker-inspect on the container.

**Add your docker run command**
The Transmission part of my docker-compose is:

  transmission:
    privileged: true
    container_name: transmission-compose
    image: haugene/transmission-openvpn:latest
    restart: unless-stopped
    ports:
      - 33773:8888
      - 33772:9091
      - TZ=Europe/Berlin
      #- PUID=1026
      #- PGID=101
      - PUID=0
      - PGID=101
      - UMASK=002
    environment:
      - OPENVPN_USERNAME=***UsernameHere***
      - OPENVPN_PASSWORD=***PasswordHere***
      - OPENVPN_PROVIDER=CUSTOM
      - TRANSMISSION_ALT_SPEED_DOWN=50
      - TRANSMISSION_ALT_SPEED_ENABLED=false
      - TRANSMISSION_ALT_SPEED_TIME_BEGIN=540
      - TRANSMISSION_ALT_SPEED_TIME_DAY=127
      - TRANSMISSION_ALT_SPEED_TIME_ENABLED=false
      - TRANSMISSION_ALT_SPEED_TIME_END=1020
      - TRANSMISSION_ALT_SPEED_UP=50
      - TRANSMISSION_BIND_ADDRESS_IPV4=0.0.0.0
      - TRANSMISSION_BIND_ADDRESS_IPV6="::"
      - TRANSMISSION_BLOCKLIST_ENABLED=false
      - TRANSMISSION_BLOCKLIST_URL=http://www.example.com/blocklist
      - TRANSMISSION_CACHE_SIZE_MB=4
      - TRANSMISSION_DHT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/data/completed
      - TRANSMISSION_DOWNLOAD_LIMIT=100
      - TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5
      - TRANSMISSION_ENCRYPTION=1
      - TRANSMISSION_IDLE_SEEDING_LIMIT=30
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_LPD_ENABLED=false
      - TRANSMISSION_MAX_PEERS_GLOBAL=200
      - TRANSMISSION_MESSAGE_LEVEL=2
      - TRANSMISSION_PEER_CONGESTION_ALGORITHM=
      - TRANSMISSION_PEER_ID_TTL_HOURS=6
      - TRANSMISSION_PEER_LIMIT_GLOBAL=200
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=50
      - TRANSMISSION_PEER_PORT=51413
      - TRANSMISSION_PEER_PORT_RANDOM_HIGH=65535
      - TRANSMISSION_PEER_PORT_RANDOM_LOW=49152
      - TRANSMISSION_PEER_PORT_RANDOM_ON_START=false
      - TRANSMISSION_PEER_SOCKET_TOS=default
      - TRANSMISSION_PEX_ENABLED=true
      - TRANSMISSION_PORT_FORWARDING_ENABLED=false
      - TRANSMISSION_PREALLOCATION=1
      - TRANSMISSION_PREFETCH_ENABLED=1
      - TRANSMISSION_QUEUE_STALLED_ENABLED=true
      - TRANSMISSION_QUEUE_STALLED_MINUTES=30
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RENAME_PARTIAL_FILES=true
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_RPC_HOST_WHITELIST=
      - TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=false
      - TRANSMISSION_RPC_PASSWORD=password
      - TRANSMISSION_RPC_PORT=9091
      - TRANSMISSION_RPC_URL=/transmission/
      - TRANSMISSION_RPC_USERNAME=username
      - TRANSMISSION_RPC_WHITELIST=127.0.0.1
      - TRANSMISSION_RPC_WHITELIST_ENABLED=false
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=false
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=
      - TRANSMISSION_SEED_QUEUE_ENABLED=false
      - TRANSMISSION_SEED_QUEUE_SIZE=10
      - TRANSMISSION_SPEED_LIMIT_DOWN=100
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false
      - TRANSMISSION_SPEED_LIMIT_UP=100
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false
      - TRANSMISSION_START_ADDED_TORRENTS=true
      - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false
      - TRANSMISSION_UMASK=2
      - TRANSMISSION_UPLOAD_LIMIT=100
      - TRANSMISSION_UPLOAD_LIMIT_ENABLED=0
      - TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=14
      - TRANSMISSION_UTP_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/data/watch
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_HOME=/data/transmission-home
      - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=false
      - ENABLE_UFW=false
      - UFW_ALLOW_GW_NET=false
      - UFW_EXTRA_PORTS=
      - UFW_DISABLE_IPTABLES_REJECT=false
      - TRANSMISSION_WEB_UI=combustion
      - TRANSMISSION_WEB_HOME=
      - DROP_DEFAULT_ROUTE=
      - WEBPROXY_ENABLED=false
      - WEBPROXY_PORT=8888
      - HEALTH_CHECK_HOST=google.com
      - LOCAL_NETWORK=192.168.178.0/24"
    volumes:
      - /volume1/docker/transmission-openvpn/data:/data
      - /volume1/docker/transmission-openvpn/config:/config
      #- /volume1/docker/transmission-openvpn/premiumize/default.ovpn:/etc/openvpn/custom/default.ovpn
      - /volume1/docker/transmission-openvpn/premiumize:/etc/openvpn/custom/:ro
      - /volume1/docker/transmission-openvpn/resolv.conf:/etc/resolv.conf
      - /volume1/DownTheRabbitHole/DumbThemHere:/data/completed

**Logs**
OpenVPN provider not set. Exiting.

**Host system:**
Synology DSM 6.2.2-24922 Update 3

Thanks in advance for any tips on how to solve with! I'd also come to the gitter chat but I don't know how +___+

**Comment by haugene** [comment]
Well. The error has to be that the environment variable isn't set inside the container. So this is not an error with the image/container, but how it is being run. I agree that it's weird that a docker update would cause this - but it sounds like an issue for the Synology/DSM forums.

If you run a docker-compose file like this:
```
version: "3"
services:
  ubuntu:
    image: ubuntu:latest
    environment:
      - OPENVPN_PROVIDER=test
    command: env
```

Do you see `OPENVPN_PROVIDER=test` in the printed output of env variables?
If you add the `command: env` line to your compose then you could try to reconfigure it until you see the env variables being set. That is Dockers responsibility and not the apps running inside the container.

Good luck :)

**Comment by jfml** [comment]
Thanks for the fast reply! The environment variable *was* set in the docker-compose, I just accidentality deleted it when I deleted a comment before pasting it here, super sorry for that +____+

I'm not really sure I follow you on the docker-compose test, when I run a docker inspect on the container created by

version: "3"
services:
  ubuntu:
    image: ubuntu:latest
    environment:
      - OPENVPN_PROVIDER=test
    command: env

I don't see a - OPENVPN_PROVIDER=test it only says:

  "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "env"
            ],


Sorry again +___+

**Comment by haugene** [comment]
Then something is wrong with your Docker or docker-compose. If you run `docker-compose up` with that file then first of all it should print all environment variables that are set and OPENVPN_PROVIDER should be among them.

If you run docker inspect on the container after that you should see:
```
            "Env": [
                "OPENVPN_PROVIDER=test",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
```

You need to figure out why environment variables aren't set in the container. Since your environment variables aren't being set in the official ubuntu image either, it is not a problem with the transmission-openvpn image

**Comment by jfml** [comment]
Cool, thanks for the explanation, I'll investigate.

**Comment by umputun** [comment]
@jfml - this is not your local problem, but something is broken with the new version of docker synology released. I'm having the same issue and there are several threads on synology forum and reddit discussing it. As far as I understand the only "fix" is to downgrade docker.

**Comment by jfml** [comment]
@jfml Yeah, I later found out that was the problem as well, wanted to come back here and say exactly that ^__^ Downgrading fixed the issue for me for now. Let's hope they'll resolve that soon.
