### ISSUE TITLE
Unable to update RPC password using Synology docker container.

### ISSUE THREAD

**Issue by HardlyAnonymous** [haugene/docker-transmission-openvpn#885]
**Describe the problem**
Unable to update RPC password using Synology docker container.  When changing manually via the GUI environmental variables and the settings.json file, the old password remains.

**Add your docker run command**
The container runs fine, I'm just needing to update the password.

**Logs**
N/A

**Host system:**
Synology NAS
Docker version: 18.09.0-0505

**Comment by haugene** [comment]
Copying my answer from the gitter chat, for future reference here:

> The settings.json file is quite useless with this container. Transmission only reads it at startup, and writes to it when it shuts down. So even if you change a setting in Transmission GUI it is not reflected in the file before you stop Transmission. And we overwrite the file on every startup to the values set by the environment variables.

Changes done in the GUI will only be in affect until the next restart. I guess that changing the RPC password requires Transmission to be started again and then it's overwritten.

So the "only" way to do this is to set the `TRANSMISSION_RPC_PASSWORD` environment variable and restart/recreate the container. Be aware of special characters, that can cause problems (see #245). Apart from special characters that should work...

**Comment by haugene** [comment]
Closing this then @HardlyAnonymous. From the chat on Gitter it seems like it worked out 😄
