### ISSUE TITLE
Could the PureVPN config be looked at?

### ISSUE THREAD

**Issue by dasfast** [haugene/docker-transmission-openvpn#887]
**Which provider?**
 PureVPN

**Where are the configs?**
[New+OVPN+Files.zip](https://github.com/haugene/docker-transmission-openvpn/files/3555971/New%2BOVPN%2BFiles.zip)

**Comment by mcwhitty** [comment]
I am having issues with this as well. Is there are work around?

**Comment by pkishino** [comment]
I just use a custom file with the pure files

**Comment by mcwhitty** [comment]
@pkishino Can you provide a bit more details of how you do it??

Thank you in advance.

**Comment by pkishino** [comment]
check here: https://haugene.github.io/docker-transmission-openvpn/supported-providers/

basically:
-Set OPENVPN_PROVIDER to CUSTOM
-add bind to /etc/openvpn/custom/default.ovpn for your ovpn file
-update ovpn file with script as above

**Comment by haugene** [comment]
Closing this and following up PureVPN config update in #1012 
New recommended configs have been downloaded from [here](https://support.purevpn.com/openvpn-files).
