### ISSUE TITLE
Support specifying UID and GID

### ISSUE THREAD

**Issue by MikeSchroll** [haugene/docker-transmission-openvpn#89]
Right now it runs as root, saving files as the same.

It would be great if it were possible to specify these values when starting the docker container.
Similar to [this project](https://github.com/linuxserver/docker-transmission).

**Comment by rolandb5** [comment]
+1

**Comment by wryspy** [comment]
I kind of like the approach of examining the UID/GID of the target folder and then matching it, similar to this approach http://stackoverflow.com/a/28596874

Combined with something like [gosu](https://github.com/tianon/gosu), the approach works nicely without hard coding a UID/GID into the image/container or passing it as a parameter.

**Comment by haugene** [comment]
I've tested this and it looks to work perfectly :smile: 
Code is merged to master and is available with the latest tag. Closing this.
