### ISSUE TITLE
"Port is Closed"

### ISSUE THREAD

**Issue by daniel-hermann** [haugene/docker-transmission-openvpn#890]
I am Using this Docker image, and generally it seems to work.

However, when entering the config it says "Listening Port: Peer Listening Port: 51413. Port is Closed".

I am running (current) Docker on a Alpine Linux VM.

**Comment by haugene** [comment]
When you're running VPN all your traffic will exit through your VPN provider. Your ability to open a port is then dependant on if they support it.

**Comment by daniel-hermann** [comment]
Sorry, my bad, contacted VPN provider.
