### ISSUE TITLE
Enable access for web proxy from WAN

### ISSUE THREAD

**Issue by teyou** [haugene/docker-transmission-openvpn#892]
**Is your feature request related to a problem? Please describe.**

I was wondering if there is a way to enable access web proxy from wan?

I have below environment configuration enabled and I am able to connect to proxy from the localhost
```
- WEBPROXY_ENABLED=true
- WEBPROXY_PORT=8888
```
However, I would like to expose it to wan as well. any idea how should I do that?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pkishino** [comment]
use apache in front and setup ssl etc and use reverse proxy, thats how I used to expose it to wan

**Comment by teyou** [comment]
I mapped port 8888 from container to host port 8888 and actually I tried to setup a nginx and use `proxy_pass` to pass it to `http://proxy:8888/` and it still doesn't work. any working sample that you can provide it to me? Thanks in advance

**Comment by pkishino** [comment]
this is from my vhost files:
#<VirtualHost *:443>
#        ServerName securetransmission.xxxxx.se
#        ProxyRequests Off
#        <Proxy *>
#                Allow from all
#        </Proxy>
#        ProxyPreserveHost On
#        ProxyPass / http://hackserver.xxxxx.se:9092/
#        ProxyPassReverse / http://hackserver.xxxxxx.se:9092/
#</VirtualHost>

**Comment by pkishino** [comment]
yes,proxy
