### ISSUE TITLE
watchdir Failed to open directory "/data/watch"

### ISSUE THREAD

**Issue by Esteidinger** [haugene/docker-transmission-openvpn#893]
Getting this error when trying to point Radarr at this container. 

Can you tell me where to create this folder?

**Comment by haugene** [comment]
Where are you getting this error, from this container or radarr?
The folder should be created under /data in the container. Specifcally at `/data/watch` as the error message says. Where that is on you host system depends on your `docker run` command, what directory are you mounting to /data?

**Comment by Esteidinger** [comment]
It was in the logs of transmission from your container. 

I edited the docker run to include the watch directory specifically and solved the problem. But it was not created automatically.
