### ISSUE TITLE
Cannot access to webUI

### ISSUE THREAD

**Issue by gruesomehit** [haugene/docker-transmission-openvpn#897]
I can't access to webUI with user and pass. The system tell me always 

401: Unauthorized
Unauthorized User

I have used the following variables:
     - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.1.*"
      - TRANSMISSION_RPC_PASSWORD=anyusername
      - TRANSMISSION_RPC_USERNAME=anypassword
      - TRANSMISSION_RPC_PORT=9091

If I comment these lines I can enter without problems inside the web UI, but it's not safe.

I run my docker with CentOS 7 and docker-compose 1.25.0-rc2

Thanks in advance for your help.

**Comment by pkishino** [comment]
check that your client IP is in the whitelist range?
