### ISSUE TITLE
Synology Task Scheduler solution is sub-optimal

### ISSUE THREAD

**Issue by abedegno** [haugene/docker-transmission-openvpn#90]
The documentation solution to loading the tun kernel module is suboptimal using the task scheduler, it would be far better to have an init.d script on startup like follows:
# !/bin/sh
# 

MODULES_DIR="/lib/modules"
MAINMODULE="tun.ko"
SUBMODULES=""

start_modules(){
        echo "--- Load modules ---"
        for i in $MAINMODULE $SUBMODULES; do
                echo "Loading $i"
                insmod $MODULES_DIR/$i
        done

```
    if ( [ ! -c /dev/net/tun ] ); then
      if ( [ ! -d /dev/net ] ); then
        mkdir -m 755 /dev/net
      fi
      mknod /dev/net/tun c 10 200
    fi
```

}

stop_modules(){
        echo "--- Unload modules ---"
        for i in $SUBMODULES $MAINMODULE; do
                echo "Unloading $i"
                rmmod $MODULES_DIR/$i
        done
}

case "$1" in
start)
        start_modules
        ;;
stop)
        stop_modules
        ;;
*)
        echo "usage: $0 { start | stop }" >&2
        exit 1
        ;;
esac

**Comment by sylarevan** [comment]
But would such a script resist to system updates? I'm not sure... But using the task scheduler to launch a script at startup will.

**Comment by haugene** [comment]
I can't speak for how Synology does their system updates, but it seems invasive if they mess around with other init.d scripts of the system.

I guess it's a matter of preference. If the GUI setup is easy, it might save someone from having to deal with init.d. But I agree, an init.d script would be a nice and robust solution.

Would happily accept a pull request adding a guide for this solution as well under the "setting up on synology" section of the README :)

**Comment by wryspy** [comment]
I believe if you run the VPN Server package from Synology, then his package sets up the tun device itself for the OpenVPN server.  I haven't had to run any tasks or manual setup steps to create the tun device.

See /usr/syno/etc.defaults/synovpnclient/scripts/ovpnc.sh

**Comment by haugene** [comment]
Sounds reasonable that Synology would manage the tun device if running an OpenVPN service. Even if you're running another service that you might not need, it's probably the simplest solution then.

Should maybe be outlined as a quick solution to the tun device problem in the README

**Comment by haugene** [comment]
Anyone eager to update the README with the init.d approach outlined by @abedegno ? I agree it's a cleaner way to do it than saving a script on the disk and calling it from the Synology task scheduler. But I'm just running this container on my server and it would be nice if someone could add the instructions while being able to confirm that they're working :) Should also document how to add the init.d service on startup.

**Comment by haugene** [comment]
Cleaning old issues. Re-open or create a new issue if it's still a problem. Remember logs and steps to reproduce.
