### ISSUE TITLE
Container stuck at "Port is open: Yes" in logs

### ISSUE THREAD

**Issue by lastb0isct** [haugene/docker-transmission-openvpn#907]
**Describe the problem**
The container will not finish starting.  It is stuck at "status starting" and the logs only show the above, that it stops at Port is open: Yes

**Add your docker run command**
  transmissionvpn:
    image: haugene/transmission-openvpn
    container_name: transmissionvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    depends_on:
      - "traefik"
      - "organizrv2"
    networks:
      - traefik_proxy
    ports: 
      - 9091:9091
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=US\ California
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/mnt/jails/transmission/extract.sh
    volumes:
      - /mnt/jails/transmission:/data
      - /mnt/freenas:/mnt/freenas
      - /etc/localtime:/etc/localtime:ro

**Logs**

**Host system:**
RHEL 7 Host

**Comment by barronlroth** [comment]
@lastb0isct How'd you get this fixed? I have the same issue.
