### ISSUE TITLE
iptables: No chain/target/match by that name.

### ISSUE THREAD

**Issue by greenpasta** [haugene/docker-transmission-openvpn#908]
**Describe the problem**
I get the following error when trying to run the container:
`docker: Error response from daemon: driver failed programming external connectivity on endpoint priceless_dewdney (7858d1740ae0764b442d46aeb4d24e516f56852bd1a76f732ee5289682ddf103):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 9091 -j DNAT --to-destination 172.17.0.2:9091 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)).
`

**Add your docker run command**
`docker run --cap-add=NET_ADMIN -d \
              -v /your/storage/path/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=PIA \
              -e OPENVPN_CONFIG=CA\ Toronto \
              -e OPENVPN_USERNAME=user \
              -e OPENVPN_PASSWORD=pass \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.0.0/16 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn`

**Logs**
No additional logs

**Host system:**
CentOS 7.7
Docker 19.03.2

**Comment by ipleten** [comment]
Hey,
How did you solve this?

**Comment by akvadrat** [comment]
I guess you have solved this by now, but I just came across the very same issue. My fix was simply to restart docker. E.g: systemctl restart docker

:-)
