### ISSUE TITLE
Is it possible to share this container's vpn with other containers?

### ISSUE THREAD

**Issue by clueo8** [haugene/docker-transmission-openvpn#914]
Is it possible to share this containers vpn tunnel with other docker containers so that their traffic will also route through the vpn connection made within the docker-transmission-openvpn vpn?

**Comment by lucasff** [comment]
Yes it's very possible. I use  this. You just need to set network_mode" "container:<vpn_container_name_here>" on docker-compose or equivalent.

**Comment by clueo8** [comment]
I don't really want to use docker-compose, is there equivalent config to do without docker-compose?  I tried using a user defined network for the two containers but the second container didn't route through the tunnel of the openvpn container.

**Comment by haugene** [comment]
https://docs.docker.com/engine/reference/run/#network-settings

Run the second container with `--network=<vpn-container-name/id>`

**Comment by clueo8** [comment]
Thanks, I'll give that a shot.  Is there a way to ensure the DNS that gets pushed down from the vpn is used?

**Comment by haugene** [comment]
There is an open issue on that somewhere, I think. Apparently there are
provider differences that makes it tricky. Can't remember exactly. Feel
free to find that issue and bump it so we'll follow up there.

The recommended solution so far is to use Google dns. You can supply --dns
options to the container, same way as network. So you could always look up
the dns servers of your provider and add them manually for now.

**Comment by clueo8** [comment]
I was able to get `--network=container:<vpn-container-name>` to work successfully, but I'm unable to publish any ports of the secondary container as it appears all of the network related settings become invalid in this mode: https://docs.docker.com/engine/reference/run/#network-container

**Comment by haugene** [comment]
Yeah. Or... Your second container "joins" the network interface of your first container. So if you want to publish ports, you need to do it on the first container - even if the ports are "running" in the second container. They now have the same network interface.

Containers are abstract beings ;)

**Comment by haugene** [comment]
Didn't see your edit there. But yes, that should work...

**Comment by clueo8** [comment]
I'll try it again, but it didn't seem to work, nothing was resolving over the published port.

**Comment by clueo8** [comment]
I think it's a binding issue.  It looks like the service within the secondary container (port 9117) appears to be listening via ipv6 instead of ipv4 (I believe that's what the 3 ":::"(s) indicate):

```
$ docker exec -it transmission ss -atn | grep LISTEN
LISTEN     0      128    10.32.60.4:51413                    *:*                  
LISTEN     0      128          *:8888                     *:*                  
LISTEN     0      128          *:9091                     *:*                  
LISTEN     0      128         :::51413                   :::*                  
LISTEN     0      128         :::9117                    :::*                  
```
I tried starting the secondary container with `--sysctl net.ipv6.conf.all.disable_ipv6=1` as well, but that did not work... Still trying...

**Comment by haugene** [comment]
I'm closing this issue now. The answer is that it is possible, but it's not a feature of this container. It's a pure Docker feature and I'll post the link again for anyone experiencing the same and are scrolling through issues: https://docs.docker.com/engine/reference/run/#network-settings

I don't have the capacity for all Docker-related questions (as there are a lot) - so I'll have to refer you to other forums for this. I hope it's pointed you in the right direction - and I hope you can post your solution here when you find it for others that might experience it later.

**Comment by orange888** [comment]
Really would like an docker-compose example on how to use VPN container with another container

**Comment by melyux** [comment]
My problem was that I had `ENABLE_UFW` on. I had to add the ports of the services behind the VPN to `UFW_EXTRA_PORTS`. Here's an example docker compose @orange888:

```yaml
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - LOCAL_NETWORK=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      ...
      - ENABLE_UFW=true
      - UFW_EXTRA_PORTS=8989,7878 # Ports of the services that are being routed through this VPN, only needed if ENABLE_UFW is on
    volumes:
      ...
#    ports:
#      - "9091:9091" # Transmission (only enable if you need to access the Transmission UI over LAN; you can leave it commented if only accessed over a reverse proxy)
#      - "8989:8989" # Sonarr (ditto)
#      - "7878:7878" # Radarr (ditto)

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      ...
    volumes:
      ...
#    ports:
#      - "7878:7878" # No longer used here since we're routing through the Transmission VPN container
    network_mode: container:transmission
