### ISSUE TITLE
Is it possible to add kick off a script when a torrent is added? I know it is possible for when a torrent finishes

### ISSUE THREAD

**Issue by zellenberg** [haugene/docker-transmission-openvpn#915]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
The same way we can initiate a script when a torrent finishes, I would like to be able to initiate a script when a torrent is added

**Describe alternatives you've considered**
No alternatives

**Additional context**
Nothing comes to mind

**Comment by pkishino** [comment]
this was discussed here: https://trac.transmissionbt.com/ticket/5586
solution exists, should have added it to mainline..

**Comment by rousseau-christopher** [comment]
Yes it's possible using this docker image juste add this 2 env variable (or docker compose parameter)
- TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
- TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/data/transmission-home/mv-file-to-nas.sh

and an example script : https://forum.transmissionbt.com/viewtopic.php?t=10364

**Comment by pkishino** [comment]
> Yes it's possible using this docker image. Add this 2 env variable (or docker compose parameter)
> 
> * TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
> * TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/someplace/myCustomScript.sh
> 
> Your script will be on the host, don't forget to map your directory inside the container :
> 
> volumes:
> - /host/someplace:/someplace
> 
> and an example script : https://forum.transmissionbt.com/viewtopic.php?t=10364

Above is for when the torrent is completed, the question is related to when a torrent is added

**Comment by ShipOfUnraid** [comment]
It deserves another look
