### ISSUE TITLE
Add cryptostorm.is as a VPN provider

### ISSUE THREAD

**Issue by HotBlack77** [haugene/docker-transmission-openvpn#92]
Is it possible to add cryptostorm as a VPN provider (https://cryptostorm.is/)? 

There are linux _ovpn_ files available for their free service here:
https://github.com/cryptostorm/cryptostorm_client_configuration_files
And then a list of regionally localised _ovpn_ files here:
https://github.com/cryptostorm/cryptostorm_client_configuration_files/tree/master/linux

I am specifically interested in the Danish one, but i imagine the best solution would be to be able to pick  between them somehow.

**Comment by haugene** [comment]
That aught to do it. Cryptostorm is now available as a provider using the dev tag. Please test it and verify if it works. I think they have a slight error or at least an unnecessary line in their config files. They inline their ca certificate in the ovpn files so they shouldn't need the "ca ca.crt" line.

Anyhow, let me know how it goes... And if it doesn't work, post the logs from the container(docker logs <container name/id>)

**Comment by haugene** [comment]
Oh yeah. And you can pick between them by setting the OPENVPN_CONFIG environment variable. For example OPENVPN_CONFIG=cstorm_linux-denmark_udp

**Comment by haugene** [comment]
@HotBlack77 ping... Or are there anyone else that has tested this provider?

**Comment by haugene** [comment]
I'll assume this issue as resolved for now. If someone tests it and finds out the provider isn't working they just need to open a new issue... Preparing to merge dev -> master later...

**Comment by HotBlack77** [comment]
Sorry about the long delay, I was moving house and had to go without internet for a while. Cryptostorm works perfectly.

**Comment by haugene** [comment]
:+1:
