### ISSUE TITLE
Launching this container disconnects all the devices on my network

### ISSUE THREAD

**Issue by slbailey** [haugene/docker-transmission-openvpn#924]
I am running this container on unraid using purevpn as my vpn provider.  Every time I launch the container, I test port forwarding, check.  I start to download a torrent and it starts but then within a few seconds, it times out and every device on my network loses connection to the Internet.  I checked my router @ 192.168.1.1 and it says the router lost connection to the internet.

My run command is as follows:

/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Transmission_VPN' --net='bridge' --privileged=true -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'OPENVPN_USERNAME'='*' -e 'OPENVPN_PASSWORD'='*' -e 'OPENVPN_CONFIG'='default' -e 'OPENVPN_PROVIDER'='PUREVPN' -e 'LOCAL_NETWORK'='"172.17.0.0/24' -e 'TRANSMISSION_RPC_USERNAME'='***' -e 'TRANSMISSION_RPC_PASSWORD'='***' -e 'OPENVPN_OPTS'='--inactive 3600 --ping 10 --ping-exit 60' -e 'PUID'='99' -e 'PGID'='100' -e 'TRANSMISSION_DOWNLOAD_DIR'='/downloads/complete' -e 'TRANSMISSION_RPC_AUTHENTICATION_REQUIRED'='true' -e 'TRANSMISSION_RATIO_LIMIT'='2' -e 'TRANSMISSION_RATIO_LIMIT_ENABLED'='true' -e 'TRANSMISSION_PORT_FORWARDING_ENABLED'='true' -e 'TRANSMISSION_PEER_PORT'='51413' -e 'TRANSMISSION_HOME'='/data' -e 'TRANSMISSION_INCOMPLETE_DIR'='/downloads/incomplete' -p '9091:9091/tcp' -p '1198:1198/udp' -p '51413:51413/tcp' -v '/mnt/user/appdata/transmission_vpn':'/data':'rw' -v '/mnt/user/transmission/downloads':'/downloads':'rw' -v '/mnt/user/transmission/torrentfiles':'/watch':'rw' -v '/mnt/user/appdata/transmission/torrents':'/data/torrents':'rw' -v '/mnt/user/appdata/Transmission_VPN':'/config':'rw' --restart=always --log-opt max-size=50m --log-opt max-file=1 --dns 8.8.8.8 'haugene/transmission-openvpn'

**Comment by pkishino** [comment]
uhm,might want to sanitize your sensitive info like user and pass..

**Comment by GuillaumeJulien** [comment]
Any solution ? i've got the same issue

**Comment by pkishino** [comment]
Can’t see anything stranger about the run command, but the udp and peer port, don’t think you need to forward to the docker host. I only forward the 9091 to access ui.. peer peer still works fine. 
There must be something else causing this.. have you tried running on a different platform just using default docker run? There are no problems connecting to VPN via some other container or client?
