### ISSUE TITLE
Cyptostorm, default config or update config?

### ISSUE THREAD

**Issue by garffi** [haugene/docker-transmission-openvpn#927]
hello, i try to configure cryptostorm in my servicedocker that worked well with another provider. I configured with the following variable:
-e "OPENVPN_PROVIDER=CRYPTOSTORM" \
        -e "OPENVPN_USERNAME=my_token" \
        -e "OPENVPN_CONFIG=cstorm_linux-paris_tcp" \

I can not make serice docker operational problem with my variable or obsolescence cryptostorm internal configuration of the image docker?

Thank you

**Comment by HotBlack77** [comment]
The problem is that cryptostorm openvpn configs are out of date, if you replace them with the updated RSA ones from cryptostorm's github it works fine.

**Comment by garffi** [comment]
thank you very much

**Comment by garffi** [comment]
@HotBlack77 Are you able to use upnp for port forwarding?
