### ISSUE TITLE
Isolatile VPN connection to transmission container only

### ISSUE THREAD

**Issue by koenvanderlinden** [haugene/docker-transmission-openvpn#928]
Is it possible to isolate the VPN tunnel to only the transmission container?

I'm also running Home Assistant and DuckDuck DNS to do dynamic DNS. However it's mapping the VPN up address to my personal domain name.
I just want to use the VPN tunnel for transmission.

Any ideas how to make this happen?

**Comment by haugene** [comment]
Yes, that is the intended use. Vpn isolated only for transmission. Sounds
like you're running --network=host?

Then you will disable container networking and allow the container to alter
the network for the whole host system.

**Comment by koenvanderlinden** [comment]
> Yes, that is the intended use. Vpn isolated only for transmission. Sounds like you're running --network=host? 

I was running with network=host. But also tried in with bridge (fails to start in container) and with network=none. Also tried without any network configuration. But doing a `curl ifconfig.co` on my duckduck dns container always returned the VPN IP address instead of the normal IP address.

**Comment by haugene** [comment]
You need to run it in bridge mode to get the behaviour you want. Not setting the network will also default to bridge. Host networking mode will affect the host, and none will isolate the container completely.

As for the curl command, I don't have a good answer. It would be interesting to see if you still got the VPN IP if the container was shut down - and then we could blame some caching etc.

As for the Error you get. This looks like a local networking kind of problem, or Docker.
The IP-range that it tries to allocate is already taken for some reason. Are you doing something special with your Docker-installation, or running other container setups that have "special needs? What host system are you running on?

If fixing the host stuff isn't the priority, then I'd try one of the following strategies:

1. See if it helps creating a separate bridge network and specify another IP range. You get conflict around the `172.30.33.4/23` range, so `172.40.33.4/23` should be way off the reserved area.
You can create a network with the `docker network create` command detailed here: https://docs.docker.com/engine/reference/commandline/network_create/
Then you can give it a name and set `--subnet 172.40.33.4/23`, and then do `--network=your-network` when starting the container.

2. Change the deault bridge network. "See Configure the default bridge network" here: https://docs.docker.com/network/bridge/

**Comment by koenvanderlinden** [comment]
> As for the curl command, I don't have a good answer. It would be interesting to see if you still got the VPN IP if the container was shut down - and then we could blame some caching etc.
When stopping the transmission-vpn container the curl command immediately returns the correct original ip address. Starting the transmission-vpn container again will give VPN ip address. So no caching.
 
> As for the Error you get. This looks like a local networking kind of problem, or Docker.
> The IP-range that it tries to allocate is already taken for some reason. Are you doing something special with your Docker-installation, or running other container setups that have "special needs? What host system are you running on?
I'm running on Raspberry Pi 3.

I will try to make a bridge network as you suggest. Hopefully I can get the container to start.

**Comment by koenvanderlinden** [comment]
Problem solved.
Previously I added a 'bridge' network to the container, which resulted in errors. However when editing the transmission container the 'Network' setting itself states it was 'Host'. So a bit strange that there are two options for setting network. Setting this 'Network' to 'bridge' fixed the issue immediately.

Joining network is not working:
![image](https://user-images.githubusercontent.com/1288924/67163201-65b6b100-f36c-11e9-81c9-da7a9d380585.png)

Setting network on container works fine:
![image](https://user-images.githubusercontent.com/1288924/67163177-17a1ad80-f36c-11e9-8c57-ef212bf97a1c.png)

So closing this issue.
