### ISSUE TITLE
Synology DSM6 Unable to connect

### ISSUE THREAD

**Issue by cjgiddings** [haugene/docker-transmission-openvpn#93]
Hi firstly i just want to say im not an expert in any of this just learning Docker.
I have setup the container as per the instruction, have it executing but can not connect and receive just the log below. I have tried your proxy but this comes back with 502 Bad Gateway.

Do i need to do anything to get the VPN open, ports, firewalls. Do i need to do anything outside of docker to support this?

**Log file:**

Using OpenVPN provider: PIA
Starting OpenVPN using config AU Melbourne.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Mon Jun 27 09:15:39 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Mon Jun 27 09:15:39 2016 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jun 27 09:15:39 2016 UDPv4 link local: [undef]
Mon Jun 27 09:15:39 2016 UDPv4 link remote: [AF_INET]168.1.75.9:1194
Mon Jun 27 09:16:39 2016 [UNDEF] Inactivity timeout (--ping-exit), exiting
Mon Jun 27 09:16:39 2016 SIGTERM[soft,ping-exit] received, process exiting
Using OpenVPN provider: PIA
Starting OpenVPN using config AU Melbourne.ovpn
Setting OPENVPN credentials...

Thanks for your help

**Comment by cjgiddings** [comment]
Worked it out, was my router blocking everything. Had to open it up to allow for connections with default port for PIA.

**Comment by haugene** [comment]
Glad to hear you worked it out! :+1:
