### ISSUE TITLE
Nord VPN issue again

### ISSUE THREAD

**Issue by steinbep** [haugene/docker-transmission-openvpn#935]
**Describe the problem**

Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/usXXX.nordvpn.com.tcp.ovpn:1: html (2.4.7)

Use --help for more information.
**Add your docker run command**

**Logs**

**Host system:**
Ubuntu

Same issue that you closed today #932.  Issue was fixed with yesterday's merge but I am seeing the same issue with this mornings update.  I may be missing something, if so please close and let me know.

**Comment by McSwindler** [comment]
I had the same issue after updating, be sure to remove the `OPENVPN_CONFIG` variable. That fixed the issue for me.

**Comment by koenvanderlinden** [comment]
@steinbep Please provide us your (OPENVPN_CONFIG and NORDVPN_*) environment configs?

**Comment by steinbep** [comment]
Looks like the removal of the OPENVPN_CONFIG was the fix.
