### ISSUE TITLE
Trouble with (openvpn) IP address

### ISSUE THREAD

**Issue by HerbM3** [haugene/docker-transmission-openvpn#937]
I'm a newbie, but I've done everything not to ask this here. I don't think my openvpn via PIA 
is working. This is on OpenMediaVault, so that could be the problem.

I have the container installed and running. Transmission downloads torrents just fine. But my torrent ip shows as 172.98.67.30 when I check it at https://ipleak.net. I pretty sure this is an internal ip. It's certainly not the ip from my ISP, but it's not an ip from PIA either. 

[ContainerLog.txt](https://github.com/haugene/docker-transmission-openvpn/files/3791344/ContainerLog.txt)

**Comment by miigotu** [comment]
```
user:~: ping ca-toronto.privateinternetaccess.com
PING ca-toronto.privateinternetaccess.com (172.98.67.97) 56(84) bytes of data.
64 bytes from 172.98.67.97: icmp_seq=1 ttl=54 time=29.3 ms
64 bytes from 172.98.67.97: icmp_seq=2 ttl=54 time=29.8 ms
64 bytes from 172.98.67.97: icmp_seq=3 ttl=54 time=29.8 ms
```
That ip you mentioned is one of the several load balanced servers for ca-toronto
