### ISSUE TITLE
Help with specifying variables

### ISSUE THREAD

**Issue by andsoitgoes** [haugene/docker-transmission-openvpn#946]
Hi all,

I’m trying to specify the transmission variables for things like ratio, as even though I am modifying the settings they o don’t even keep if I don’t restart. 

The question I have is for things like the ratio, do I use an “=“ sign after the variable and feed it the ratio number, so would my argument look like this:

```
TRANSMISSION_RATIO_LIMIT=2
TRANSMISSION_RATIO_LIMIT_ENABLED=True
```

Also, how is it best to specify the number in `TRANSMISSION_SPEED_LIMIT_UP`
? If I wanted to limit it to 2Mb/s, how would it be best to specify that?

Thanks in advance!

**Comment by pkishino** [comment]
If you change settings in the UI and then restart the container, these settings are lost..
specify in your docker run, either using the https://github.com/haugene/docker-transmission-openvpn/blob/master/DockerEnv files or specifying in run command with -e XXX=X

like this:
TRANSMISSION_SPEED_LIMIT_UP=100
TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false

or 
-e TRANSMISSION_SPEED_LIMIT_UP=100
-e TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false

as per here: https://github.com/transmission/transmission/wiki/Editing-Configuration-Files
the speed limit is in kb/s, default is 100
