### ISSUE TITLE
Please update Configs for perfect privacy

### ISSUE THREAD

**Issue by grince** [haugene/docker-transmission-openvpn#947]
**Which provider?**
Perfect Privacy

**Where are the configs?**
attached

[linux_op24_udp_v4_AES256GCM_CR_in_ci.zip](https://github.com/haugene/docker-transmission-openvpn/files/3814286/linux_op24_udp_v4_AES256GCM_CR_in_ci.zip)

**Comment by haugene** [comment]
Hey @grince. I just merged #983 with new configs for perfect privacy. They are available using the :dev tag of the image. This hopefully solves this issue. If not, feel free to re-open.

PS: Would also be great with a feedback either way if you test it, if it works or not 😄
