### ISSUE TITLE
Synology, no peers & config won't save

### ISSUE THREAD

**Issue by olehumborstad** [haugene/docker-transmission-openvpn#95]
Running this on a Synology. Ports are open, connecting to usenetserver just fine, config won't save and when I try to download, nothing happens, any torrent just can't get peers. Can't seem to find anything relevant in my logs as to why this fails either.. Any suggestions?

**Comment by olehumborstad** [comment]
missing DNS, fixed..

**Comment by haugene** [comment]
Bra at det ordnet seg! Fant ut av konfig'en også?

DNS har visstnok blitt helt nødvendig å angi på Docker 1.12 ser det ut til på et annet issue her. Kjører du 1.12? Tidligere trengte man ikke overstyre den. Skal ta en titt på standard oppførsel for DNS. Kanskje kjøre inn Google by default også kan folk heller overstyre derfra om de ønsker...

**Comment by olehumborstad** [comment]
Hei, tenkte det var unødvendig at dette var en tråd i det hele tatt så jeg forsøkte å slette den.
Kjempebra hva du har fått til å lage her da! :+1:
Jeg kjører på "Docker version 1.11.2, build eabacaa-synology", har ikke sett mer på konfigèn, men regner med det er bare å finne ut hvor transmission lagrer det for så å overkjøre det på samme måte jeg gjorde med resolv.con? :)

**Comment by olehumborstad** [comment]
Ser ut til at uansett hva jeg gjør så blir settings.json overkjørt?
"Generating transmission settings.json from env variables "

**Comment by haugene** [comment]
Takk for det! :) 

Men det stemmer ja. Settings fila blir overstyrt på oppstart basert på environment variabler som du angir til containeren. Står beskrevet i Readme. Si heller ifra om det er en spesifikk setting du ikke får satt, så kan jeg shippe et eksempel...

**Comment by olehumborstad** [comment]
Aha! RTFM ;) Det var så mye der at jeg skum-leste bare litt for fort over første gang egentlig, og antok at det kun var de fire valgene der. Men dette funket fjell det, wunderbar! :)

 

Fra: Kristian Haugene [mailto:notifications@github.com] 
Sendt: fredag 8. juli 2016 11.22
Til: haugene/docker-transmission-openvpn <docker-transmission-openvpn@noreply.github.com>
Kopi: Ole Humborstad <ole@humborstad.no>; State change <state_change@noreply.github.com>
Emne: Re: [haugene/docker-transmission-openvpn] DNS Issues (#95)

 

Takk for det! :) 

Men det stemmer ja. Settings fila blir overstyrt på oppstart basert på environment variabler som du angir til containeren. Står beskrevet i Readme. Si heller ifra om det er en spesifikk setting du ikke får satt, så kan jeg shippe et eksempel...
