### ISSUE TITLE
NAS Install - OpenVPN Status

### ISSUE THREAD

**Issue by bc24fl** [haugene/docker-transmission-openvpn#956]
Much appreciate all the work being done here.  I have a NAS install (OMV) using ExpressVPN and it appears to be working by looking at the docker logs but is there a way to tell for sure while using transmission GUI?  Running a dig in the command line i see it does go through the VPN though.

**Comment by Raka74** [comment]
I downloaded a 'detection' torrent from https://ipleak.net/
It gives me the address of the VPN server that is currently connected.

Is that something you could use?

**Comment by bc24fl** [comment]
That's a good test (i just tried it and works fine) but would be nice to actively see it in case the vpn connection is disrupted for whatever reason.

**Comment by haugene** [comment]
Just commented on #958 which is very similar to this issue. I believe that one of the test methods listed in #323 actually outputs the IP to the Transmission view. Check it out.

That being said. Some of the core functionality of this container is that Transmission is started when the OpenVPN tunnel is created, and it is killed if the tunnel goes down. As long as the tunnel is up, the iptables routing will force all traffic (except what's listed in LOCAL_NETWORK variable) to go through the tunnel.

That being said. The more people actively monitoring their public IP, the earlier someone will raise an issue if there are scenarios where this is not working as intended.
