### ISSUE TITLE
How to confirm it is working

### ISSUE THREAD

**Issue by medelay** [haugene/docker-transmission-openvpn#958]
Hi there i just got this fantastic container up and running with expressVPN.

But im searching all over to find a way to see it it is really working and not using my regular up adres?
How do i see it is working i was trying to go through the info on the transmision webui but could not find anyhting?

**Comment by haugene** [comment]
Some comments for furutre readers of this issue:

1. As long as you can access Transmission Web interface, the VPN is running.
2. The LOCAL_NETWORK variable is the only "hole" in your VPN, make sure it's as narrow as possible.
3. If you want to test your IP, see #323 (and linked issues)
