### ISSUE TITLE
Open "Listenning Port"

### ISSUE THREAD

**Issue by CooperBarrett** [haugene/docker-transmission-openvpn#97]
_I use Google Translation_

Hello,
It's [me](https://github.com/haugene/docker-transmission-openvpn/issues/80) again...

I come to ask you for help to open the "Listenning Port": 51413 for me.

I now connects me with OpenVPN Connect using the configuration "auto login profile": no need to enter its password.

So that's how I run my container:

```
docker run --privileged -d \
-v /My/Directory/To/Data/:/data \
-v /My/Directory/To/MyOVPN/client.ovpn:/etc/openvpn/custom/default.ovpn \
-e "OPENVPN_PROVIDER=CUSTOM" \
-e "OPENVPN_USERNAME=idontcare" \
-e "OPENVPN_PASSWORD= idontcare" \
-e "TRANSMISSION_PORT_FORWARDING_ENABLED=true" \
-e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true" \
-e "TRANSMISSION_RPC_ENABLED=true" \
-e "TRANSMISSION_RPC_USERNAME=username" \
-e "TRANSMISSION_RPC_PASSWORD=password" \
-e "TRANSMISSION_BLOCKLIST_ENABLED=true" \
-e "TRANSMISSION_BLOCKLIST_URL=http://john.bitsurge.net/public/biglist.p2p.gz" \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
-e "LOCAL_NETWORK=192.168.0.18" \
-p 9091:9091 \
--dns 96.90.175.167 \
--dns 50.116.23.211 \
--dns 50.116.40.226 \
--dns 104.238.153.178 \
--restart=always \
--name Transmission-OpenVPN_Perso \
haugene/transmission-openvpn
```
I used [OpenNIC](https://www.opennicproject.org/) for DNS, I think it's better than using those of Google.

I have this [technique](https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/updatePort.sh) that you advised me but I have no idea how the fit my setup.

I need to open this port because my Downloads and Uploads are extremely slow and I think that can come from it.

Thank you in advance for your help.

---------------------------------------
_En Français_

Salut, 
C'est encore moi...

Je viens te demander de l'aide pour ouvrir le "Listenning Port" : 51413 pour moi.

Je me connecte désormais avec OpenVPN Connect en utilisant la configuration "autologin profile" : pas besoin de rentrer ses identifiants.

Donc, voilà comment je lance mon conteneur :

```
docker run --privileged -d \
-v /My/Directory/To/Data/:/data \
-v /My/Directory/To/MyOVPN/client.ovpn:/etc/openvpn/custom/default.ovpn \
-e "OPENVPN_PROVIDER=CUSTOM" \
-e "OPENVPN_USERNAME=idontcare" \
-e "OPENVPN_PASSWORD= idontcare" \
-e "TRANSMISSION_PORT_FORWARDING_ENABLED=true" \
-e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true" \
-e "TRANSMISSION_RPC_ENABLED=true" \
-e "TRANSMISSION_RPC_USERNAME=username" \
-e "TRANSMISSION_RPC_PASSWORD=password" \
-e "TRANSMISSION_BLOCKLIST_ENABLED=true" \
-e "TRANSMISSION_BLOCKLIST_URL=http://john.bitsurge.net/public/biglist.p2p.gz" \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
-e "LOCAL_NETWORK=192.168.0.18" \
-p 9091:9091 \
--dns 96.90.175.167 \
--dns 50.116.23.211 \
--dns 50.116.40.226 \
--dns 104.238.153.178 \
--restart=always \
--name Transmission-OpenVPN_Perso \
haugene/transmission-openvpn
```

Pour info, j'ai utilisé OpenNIC pour les DNS, je pense que c'est mieux que d'utiliser ceux de Google.

J'ai bien cette technique (https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/updatePort.sh) que tu m'as conseillé mais je n'ai aucune idée de comment l'adapter à ma configuration.

J'ai besoin de l'ouverture de ce port car mes Downloads et Uploads sont extremement lent et je pense que ça peut venir de là.

Merci d'avance pour ton aide.

**Comment by haugene** [comment]
Hey there!

Well, it's not sure that you can open the port. You can't do it in the container or your local network. The port needs to be forwarded to you by the router managing your public ip. That's the address you're visible under when connecting to the vpn and that's where requests will be sent. 

This means that your vpn provider needs to support port forwarding and it's up to them to have documentation for this. This will be different for every provider. PIA has this support and I've scripted port opening using them because that's the provider I use. 

That script is totally specific to PIA. You need to check with you provider if they support port forwarding and how to do it. If they provide some documentation, share it here and I might be able to hint on how two do it for this container.

**Comment by haugene** [comment]
Closing this soon if you either solved it or don't have any follow up questions :)

**Comment by CooperBarrett** [comment]
Yes sorry, I'll close. 
I have not found solutions and I do not have much Remps now. I will return to you probeblement later. Sorry for the delay.

**Comment by haugene** [comment]
Well, it all depends on your VPN provider as I said. They are the ones owning the public IP that you're exposed with. If you really need an open port for speed you could always test a months subscription to PIA where I've written the port update script. To check if that solves your problem with speed.

No worries. Come back when you have a new issue ;)
