### ISSUE TITLE
Slow download speeds through NordVPN max 2MB/s on a 300/20 connection

### ISSUE THREAD

**Issue by laniier** [haugene/docker-transmission-openvpn#970]
Hello,

Lately I have run into an issue which I can't seem to get fixed on my Synology DS916+ NAS using the haugene/docker-transmission-openvpn:latest image.

Whatever I'm trying to download seems to cap at 1.5-2MB/s (total bandwidth not per torrent)

Some tests I ran myself;

- Set up a new container from scratch - no luck
- Set up  a transmission only container - download speeds are fast (considering 300/20)
- Connecting to the corresponding NordVPN server through other means (ie. desktop/smartphone app, I get higher speeds)
-  I did swap my ISP's modem but I can't think of a way that could be related
- DSM 6.2.2-24922 Update 4
- Docker 18.09.0-0506

I'm using the docker GUI on my NAS to fill in all parameters.
I'm not very experienced in CLI but I'm willing to give it a try if I have to.

Hopefully by providing you,dear community, a log of what happens when I start the container + pictures of my settings in the GUI my issue can be resolved.

<pre>Using OpenVPN provider: NORDVPN
2019-12-08 11:16:46 Checking curl installation
2019-12-08 11:16:46 Removing existing configs
2019-12-08 11:16:46 Selecting the best server...
2019-12-08 11:16:46 Searching for group: legacy_p2p
2019-12-08 11:16:46 Searching for technology: openvpn_tcp
2019-12-08 11:16:46 Best server : be136.nordvpn.com
2019-12-08 11:16:46 Downloading config: default.ovpn
2019-12-08 11:16:46 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/be136.nordvpn.com.tcp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2820  100  2820    0     0   9603      0 --:--:-- --:--:-- --:--:--  9591
2019-12-08 11:16:46 Selecting the best server...
2019-12-08 11:16:46 Searching for country : nl (153)
2019-12-08 11:16:46 Searching for group: legacy_p2p
2019-12-08 11:16:46 Searching for technology: openvpn_tcp
2019-12-08 11:16:46 Best server : nl432.nordvpn.com
2019-12-08 11:16:46 Downloading config: nl432.nordvpn.com.ovpn
2019-12-08 11:16:46 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/nl432.nordvpn.com.tcp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  2820    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2820  100  2820    0     0   4183      0 --:--:-- --:--:-- --:--:--  4183
2019-12-08 11:16:46 Checking line endings
2019-12-08 11:16:46 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config nl432.nordvpn.com.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Sun Dec  8 11:16:54 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Sun Dec  8 11:16:54 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sun Dec  8 11:16:54 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun Dec  8 11:16:54 2019 NOTE: --fast-io is disabled since we are not using UDP
Sun Dec  8 11:16:54 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Sun Dec  8 11:16:54 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Sun Dec  8 11:16:54 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]212.8.252.179:443
Sun Dec  8 11:16:54 2019 Socket Buffers: R=[87380->87380] S=[16384->16384]
Sun Dec  8 11:16:54 2019 Attempting to establish TCP connection with [AF_INET]212.8.252.179:443 [nonblock]
Sun Dec  8 11:16:55 2019 TCP connection established with [AF_INET]212.8.252.179:443
Sun Dec  8 11:16:55 2019 TCP_CLIENT link local: (not bound)
Sun Dec  8 11:16:55 2019 TCP_CLIENT link remote: [AF_INET]212.8.252.179:443
Sun Dec  8 11:16:55 2019 TLS: Initial packet from [AF_INET]212.8.252.179:443, sid=16478f9c b3af16ac
Sun Dec  8 11:16:55 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Dec  8 11:16:55 2019 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Sun Dec  8 11:16:55 2019 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
Sun Dec  8 11:16:55 2019 VERIFY KU OK
Sun Dec  8 11:16:55 2019 Validating certificate extended key usage
Sun Dec  8 11:16:55 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sun Dec  8 11:16:55 2019 VERIFY EKU OK
Sun Dec  8 11:16:55 2019 VERIFY OK: depth=0, CN=nl432.nordvpn.com
Sun Dec  8 11:16:55 2019 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Sun Dec  8 11:16:55 2019 [nl432.nordvpn.com] Peer Connection Initiated with [AF_INET]212.8.252.179:443
Sun Dec  8 11:16:57 2019 SENT CONTROL [nl432.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Sun Dec  8 11:16:57 2019 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.7.3.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.7.3.6 255.255.255.0,peer-id 0,cipher AES-256-GCM'
Sun Dec  8 11:16:57 2019 OPTIONS IMPORT: timers and/or timeouts modified
Sun Dec  8 11:16:57 2019 OPTIONS IMPORT: --explicit-exit-notify can only be used with --proto udp
Sun Dec  8 11:16:57 2019 OPTIONS IMPORT: compression parms modified
Sun Dec  8 11:16:57 2019 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Sun Dec  8 11:16:57 2019 Socket Buffers: R=[87380->425984] S=[22680->425984]
Sun Dec  8 11:16:57 2019 OPTIONS IMPORT: --ifconfig/up options modified
Sun Dec  8 11:16:57 2019 OPTIONS IMPORT: route options modified
Sun Dec  8 11:16:57 2019 OPTIONS IMPORT: route-related options modified
Sun Dec  8 11:16:57 2019 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sun Dec  8 11:16:57 2019 OPTIONS IMPORT: peer-id set
Sun Dec  8 11:16:57 2019 OPTIONS IMPORT: adjusting link_mtu to 1659
Sun Dec  8 11:16:57 2019 OPTIONS IMPORT: data channel crypto options modified
Sun Dec  8 11:16:57 2019 Data Channel: using negotiated cipher 'AES-256-GCM'
Sun Dec  8 11:16:57 2019 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Dec  8 11:16:57 2019 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Dec  8 11:16:57 2019 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:06
Sun Dec  8 11:16:57 2019 TUN/TAP device tun0 opened
Sun Dec  8 11:16:57 2019 TUN/TAP TX queue length set to 100
Sun Dec  8 11:16:57 2019 /sbin/ip link set dev tun0 up mtu 1500
Sun Dec  8 11:16:57 2019 /sbin/ip addr add dev tun0 10.7.3.6/24 broadcast 10.7.3.255
Sun Dec  8 11:16:57 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1587 10.7.3.6 255.255.255.0 init
Up script executed with tun0 1500 1587 10.7.3.6 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.7.3.6
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1024:101
Setting permission for files (644) and directories (755)
-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    ****
User gid:    ***
-------------------------------------
STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Sun Dec  8 11:16:57 2019 /sbin/ip route add 212.8.252.179/32 via 172.17.0.1
Sun Dec  8 11:16:57 2019 /sbin/ip route add 0.0.0.0/1 via 10.7.3.1
Sun Dec  8 11:16:57 2019 /sbin/ip route add 128.0.0.0/1 via 10.7.3.1
Sun Dec  8 11:16:57 2019 Initialization Sequence Completed

</pre>

![parameters1](https://user-images.githubusercontent.com/36863196/70388649-e7ae7800-19b4-11ea-97eb-30993c2f2c6d.png)
![parameters2](https://user-images.githubusercontent.com/36863196/70388650-e7ae7800-19b4-11ea-8b32-e25457a5259a.png)
![parameters3](https://user-images.githubusercontent.com/36863196/70388651-e7ae7800-19b4-11ea-9a86-a071c199b90c.png)
![parameters4](https://user-images.githubusercontent.com/36863196/70388652-e7ae7800-19b4-11ea-8945-12964cb58b8c.PNG)
![parameters5](https://user-images.githubusercontent.com/36863196/70388653-e7ae7800-19b4-11ea-9031-d4537e038ef8.png)
![parameters6](https://user-images.githubusercontent.com/36863196/70388654-e7ae7800-19b4-11ea-9caa-a06caf214147.PNG)
![parameters7](https://user-images.githubusercontent.com/36863196/70388655-e8470e80-19b4-11ea-8292-f81c8e2f29d0.PNG)
![parameters8](https://user-images.githubusercontent.com/36863196/70388656-e8470e80-19b4-11ea-87a4-d9a4349394cc.PNG)
![parameters9](https://user-images.githubusercontent.com/36863196/70388657-e8470e80-19b4-11ea-8501-ea4cde226387.PNG)

**Comment by gotjazz** [comment]
set TRANSMISSION_UTP_ENABLED to false and all will be well. uTP seems to hurt a lot via VPN. I also get about 2MB/s on my 250 mbps with uTP. As soon as I disable it, I can use my full bandwidth

**Comment by laniier** [comment]
> set TRANSMISSION_UTP_ENABLED to false and all will be well. uTP seems to hurt a lot via VPN. I also get about 2MB/s on my 250 mbps with uTP. As soon as I disable it, I can use my full bandwidth

Thank you so much for your input!
Unfortunately disabling the parameter didn't solve the problem for me.

I did find out about [this ](https://www.reddit.com/r/nordvpn/comments/8qp201/slow_p2p_speeds/)reddit thread, describing the same symptoms as I'm having and implementing your suggested solution with success but alas... for me it doesn't seem to work

**Comment by sebnapower** [comment]
@laniier I am having the same issue as you had. Can you write a bit more about your general setup? 

Am I right that you were using Transmission as a torrent client? Which container have you downloaded for it? I am using qbittorrent with linuxserver/qbittorrent image and I have configured NordVPN as a network adapter in DSM 7.1 and I dont seem to have access to variable causing the slowdown.

Can you explain in a bit more detail where have you configured your VPN and what torrent client you are using and are those both functions running from same container or are those separate ones etc.?

Thanks
