### ISSUE TITLE
settings.json after start-up

### ISSUE THREAD

**Issue by lordportux** [haugene/docker-transmission-openvpn#974]
Hi everyone,

Is there any way to mantain the configurations changes of settings.json file after the start-up/reboot? 

Thanks in advance,
Andres

**Comment by tommitytom** [comment]
It's not possible to persists changes to settings.json, as it is generated on each run, based on the options you pass to the docker container.  If you want to maintain settings, you have to set them in your run call or docker-compose.yml

**Comment by lordportux** [comment]
ok, Thanks for the feedback @tommitytom.

Yes, I know all settings are reset to the env variables during the start-up, but, I'd like to maintain the changes I do trough the RPC. So, It could be nice if that behaviour could be configured by an env variable like: TRANSMISSION_KEEP_CHANGES=yes/no, or something similar.

Since it's not supported, I created a custom pre-start script in order to backup the settings.json file before it is re-generated; and a post-start script to stop transmission, recover the settings.json file and start transmission again.
