### ISSUE TITLE
default TRANSMISSION_UTP_ENABLED to false

### ISSUE THREAD

**Issue by gotjazz** [haugene/docker-transmission-openvpn#978]
**Is your feature request related to a problem? Please describe.**
*really* hurts bandwidth 

**Describe the solution you'd like**
by using false as default

**Describe alternatives you've considered**
none

**Additional context**
I can only use 10% of my bandwidth when uTP is enabled. Wihtout it I reach my full bandwidth. And I don't seem to be alone if google is any indication.

**Comment by JoooostB** [comment]
@gotjazz You're a lifesaver, finally getting some decent speeds after setting TRANSMISSION_UTP_ENABLED to false
