### ISSUE TITLE
SIGUSR1[soft,tls-error] received, process restarting

### ISSUE THREAD

**Issue by jockebq** [haugene/docker-transmission-openvpn#979]
**Describe the problem**
For some unknown reason my Transmission OpenVPN setup stopped working. I am using FastestVPN with server Sweden, and I have never had any issues before. I can access the Transmission UI, but downloads are not working.

**Logs**
`Fri Dec 13 15:03:28 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Fri Dec 13 15:03:28 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Dec 13 15:03:28 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]128.127.104.201:4443
Fri Dec 13 15:03:28 2019 UDP link local (bound): [AF_INET][undef]:1194
Fri Dec 13 15:03:28 2019 UDP link remote: [AF_INET] hiddenipadress:4443
Fri Dec 13 15:03:53 2019 TLS Error: local/remote TLS keys are out of sync: [AF_INET]hiddenipadress:4443 [0]
Fri Dec 13 15:04:28 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Fri Dec 13 15:04:28 2019 TLS Error: TLS handshake failed
Fri Dec 13 15:04:28 2019 SIGUSR1[soft,tls-error] received, process restarting`

**Host system:**
Debian 9, Docker 19.03.5

**Comment by resuarez** [comment]
It is curious, I have the same problem, but I am using IPVanish.

**Comment by fredericpfisterer** [comment]
Same here with PIA

**Comment by Mmarwandi** [comment]
Same issue with purevpn

**Comment by PlowRaiser** [comment]
Same here with PIA the docker didn't start because of this error. I run a virtual machine on synology

**Comment by fredericpfisterer** [comment]
https://github.com/haugene/docker-transmission-openvpn/issues/1001#issuecomment-573654035
