### ISSUE TITLE
Bandwidth issue

### ISSUE THREAD

**Issue by Mameluk007** [haugene/docker-transmission-openvpn#980]
Hi everybody !

Following issue #953, regarding which I thank you all for your help and feedbacks, I have another one : shitty bandwidth in comparison with my previous config (transmission run directly as a regular app under my Synology NAS through a VPN). Obvisouly I ran bandwidth tests with exactly the same VPN servers with the same protocol and results are far slower !
I checked if any firewall or bandwith limitation was active but there is not...

Anybody encoutered the same issue ?

Thanks.

**Comment by haugene** [comment]
Can you test setting this flag to false #978, maybe try udp protocol as suggested in #970 or the mssfix discussed in #702 (last comment).

Let me know if you get some results. Hoping to do some tweaking on the image over the holidays. Some people have raised speed issues previously, so it would be good to fix it :)

**Comment by Mameluk007** [comment]
Hi !

Thank you for your feedback. I tried to disable uTP. I was already with UDP protocol and try to adjust the mssfix parameter... but I still have far lower bandwidth than expected (especially in comparison with the same config outside the container...). Around 10% of the bandwidth !...
