### ISSUE TITLE
Incomplete torrents are all dropped and ignored on reboot of stack or docker host

### ISSUE THREAD

**Issue by callahan22** [haugene/docker-transmission-openvpn#982]
**Describe the problem**
What was running for months has now decided to stop working. Aside from updates to the OS, there have been no changes to the setup I have running.
I'm running a docker stack with the standard radarr/sonarr/transmission-vpn stack.
When I reboot the host it's all running on or run a docker-compose down then docker-compose up -d, all torrents that were waiting to complete are lost from the GUI. I can exec into the transmission-vpn container and can see that the bind mount to the incomplete folder (hosted on my NAS) has successfully mapped and I can see the incomplete files and folders in the mapped incomplete folder from the container yet the GUI shows nothing. If I then push a new download from sonarr/radarr, the new download appears in the Transmission web GUI.

The docker-compose section for transmission-vpn is as follows:
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    ports:
    - "8001:9091"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/shared:/shared
      - ./docker/transmission-vpn/watch:/data/watch
      - /mnt/nfs/temp/transmission/incomplete:/data/incomplete
      - /mnt/nfs/temp/transmission/completed:/data/completed
    environment:
      - OPENVPN_PROVIDER=IPVANISH
      - OPENVPN_USERNAME=my_username
      - OPENVPN_PASSWORD=my_password
      - OPENVPN_CONFIG="ipvanish-*********************************************"
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=1000
      - PGID=999
      - TZ=Europe/London
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.1.*"
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=150
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSION_IDLE_SEEDING_LIMIT=1

**Logs**
Tue Dec 17 15:40:25 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1553 172.21.20.208 255.255.254.0 init
Up script executed with tun0 1500 1553 172.21.20.208 255.255.254.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 172.21.20.208
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1000:999
Setting permission for files (644) and directories (755)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    999
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Tue Dec 17 15:40:25 2019 /sbin/ip route add my_external_ip/32 via 172.18.0.1
Tue Dec 17 15:40:25 2019 /sbin/ip route add 0.0.0.0/1 via 172.21.20.1
Tue Dec 17 15:40:25 2019 /sbin/ip route add 128.0.0.0/1 via 172.21.20.1
Tue Dec 17 15:40:25 2019 Initialization Sequence Completed

**Host system:**
Ubuntu Server V18.04

I'm getting bored of having to add the files back in every time I have to restart my docker host. Has anyone seen this before or know of a fix?

Thanks for any suggestions you have.

**Comment by haugene** [comment]
Hey there. Transmission home directory is by default set to /data/transmission-home.
So when you mount specific sub-directories instead of mounting the complete /data dir, you're not persisting the state. So you could either mount`/mnt/nfs/temp/transmission:/data` as you have both incomplete and completed there anyways. Or you have to mount something to `/data/transmission-home`
