### ISSUE TITLE
Having an issue with looping NORDVPN

### ISSUE THREAD

**Issue by Stallern** [haugene/docker-transmission-openvpn#985]
docker run --cap-add=NET_ADMIN -d \
              -v /your/storage/path/:/data \
              -e NORDVPN_COUNTRY=NO
              -e OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=NORDVPN \
              -e OPENVPN_CONFIG=default
              -e OPENVPN_USERNAME=user \
              -e OPENVPN_PASSWORD=pass \
              -e WEBPROXY_ENABLED=true \
              -e LOCAL_NETWORK=192.168.0.0/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
             

Error Log:

Using OpenVPN provider: NORDVPN
Setting NORDVPN_PROTOCOL to: DEFAULT
2019-12-20 04:50:10 Checking curl installation
2019-12-20 04:50:10 Removing existing configs
2019-12-20 04:50:10 Selecting the best server...
2019-12-20 04:50:10 Unable to find a server with the specified parameters, using any recommended server
2019-12-20 04:50:10 Best server :
2019-12-20 04:50:10 Downloading config: default.ovpn
2019-12-20 04:50:10 Downloading from: https://downloads.nordcdn.com/configs/files
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0curl: (6) Could not resolve host: downloads.nordcdn.com
Supplied config default.ovpn could not be found.
Using default OpenVPN gateway for provider nordvpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/default.ovpn
Use --help for more information.

**Host system:**
Intel Nuc, Debian 9, OMV

**Comment by haugene** [comment]
Drop the OPENVPN_CONFIG variable, does it work then?

**Comment by Stallern** [comment]
same error

Using OpenVPN provider: NORDVPN
2019-12-20 19:41:23 Checking curl installation
2019-12-20 19:41:23 Removing existing configs
2019-12-20 19:41:23 Selecting the best server...
2019-12-20 19:41:23 Searching for technology: openvpn_udp
2019-12-20 19:41:23 Unable to find a server with the specified parameters, using any recommended server
2019-12-20 19:41:23 Best server :
2019-12-20 19:41:23 Downloading config: default.ovpn
2019-12-20 19:41:23 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:23 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:24 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:25 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:27 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:28 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:31 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:32 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:33 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:34 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:35 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:36 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:37 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:38 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:39 --:--:--     0curl: (6) Could not resolve host: downloads.nordcdn.com
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/default.ovpn
Use --help for more information

**Comment by edgd1er** [comment]
Hi guys,  not checked the source but that one I can answer :) 
``Could not resolve host: downloads.nordcdn.com```

the new dl url is https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn it used to be https://downloads.nordvpn.com/configs/files/ovpn_udp/servers/.udp.ovpn
noticed the vp changed to cd ? I m not sure what is the reason for this, could be a wild sed on files and its sub dirs....

Ive

**Comment by nadav74** [comment]
I also have this problem:
docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \
              -v ...:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e "OPENVPN_PROVIDER=NORDVPN" \
              -e "OPENVPN_USERNAME=..." \
              -e "OPENVPN_PASSWORD=..." \
              -e "OPENVPN_CONFIG=<a very working one>" \
              -e "LOCAL_NETWORK=192.168.2.0/24" \
              -e "PUID=1000" \
              -e "PGID=1000" \
              -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
              --log-driver json-file \
              --log-opt max-size=10m \
              --sysctl net.ipv6.conf.all.disable_ipv6=0 \
              -p 9091:9091 \
              --name "nordvpn" \
              --dns 192.168.2.1 \
              haugene/transmission-openvpn

Results with:

$ docker start -ia nordvpn 
Using OpenVPN provider: NORDVPN                                                                                                                                                                                   
Setting NORDVPN_PROTOCOL to: UDP                                                                                                                                                                                  
2019-12-25 23:20:03 Checking curl installation                                                         
2019-12-25 23:20:03 Removing existing configs                                          
2019-12-25 23:20:03 Selecting the best server...       
2019-12-25 23:20:03 Removing existing configs                                                                                                                                                              [0/1722]
2019-12-25 23:20:03 Selecting the best server...                                                                                                             
2019-12-25 23:20:03 Searching for technology: openvpn_udp                                                                                                         
2019-12-25 23:20:03 Unable to find a server with the specified parameters, using any recommended server                                                      
2019-12-25 23:20:03 Best server :                                                                                                                       
2019-12-25 23:20:03 Downloading config: default.ovpn                  
2019-12-25 23:20:03 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn                                                                                                      
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0curl: (6) Could not resolve host: downloads.nordcdn.com                                                                             
Supplied config al9.nordvpn.com.udp.ovpn could not be found.               
Using default OpenVPN gateway for provider nordvpn                      
Setting OPENVPN credentials...                                                                                                           
adding route to local network 192.168.2.0/24 via 172.17.0.1 dev eth0
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/default.ovpn
Use --help for more information.

**Comment by edgd1er** [comment]
as stated before, i believe the three variables are needed: https://github.com/haugene/docker-transmission-openvpn/issues/953#issuecomment-555247639 
NORDVPN_CATEGORY
NORDVPN_COUNTRY
NORDVPN_PROTOCOL

these might be set with default values in the script but it's not done for the moment :)

**Comment by nadav74** [comment]
@edgd1er Which still results in:

docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \
              -v ...:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e "OPENVPN_PROVIDER=NORDVPN" \
              -e "OPENVPN_USERNAME=..." \
              -e "OPENVPN_PASSWORD=..." \
              -e "LOCAL_NETWORK=192.168.2.0/24" \
              -e "PUID=1000" \
              -e "PGID=1000" \
              -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
              -e "NORDVPN_COUNTRY=..." \
              -e "NORDVPN_PROTOCOL=udp" \
              -e "NORDVPN_CATEGORY=P2P" \
              --log-driver json-file \
              --log-opt max-size=10m \
              --sysctl net.ipv6.conf.all.disable_ipv6=0 \
              -p 9091:9091 \
              --name "nordvpn" \
              --dns 192.168.2.1 \
              haugene/transmission-openvpn


Using OpenVPN provider: NORDVPN
2019-12-26 16:13:18 Checking curl installation
2019-12-26 16:13:18 Removing existing configs
2019-12-26 16:13:18 Selecting the best server...
2019-12-26 16:13:18 Searching for technology: openvpn_udp
2019-12-26 16:13:18 Unable to find a server with the specified parameters, using any recommended server
2019-12-26 16:13:18 Best server : 
2019-12-26 16:13:18 Downloading config: default.ovpn
2019-12-26 16:13:18 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0curl: (6) Could not resolve host: downloads.nordcdn.com
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.2.0/24 via 172.17.0.1 dev eth0
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/default.ovpn
Use --help for more information.

No "best server" (why would I want one? It gives me one where I live in a working setup, beats the purpose, exactly what shouldn't happen), no other server detected (tried NORDVPN_COUNTRY both upper & lower case), not working!

**Comment by nadav74** [comment]
The problem lied in the fact the container had no connectivity. Once this problem was resolved, everything seems to be working fine. In my case, I had to set `"iptables": true` rather than `false` in `/etc/docker/daemon.json`. Do diagnose it I started a shell while the container was coming up and saw that `ping 8.8.8.8` failed.

**Comment by edgd1er** [comment]
@nadav74, I'm glad you found a solution.

**Comment by joshmello** [comment]
@nadav74 have you had anymore issues I have the same

**Comment by rootindex** [comment]
There seems to be 2 solutions to this problem:

1) You missed the update where the configs was swapped out for a *live* (SCARY) downloaded version with the ovpn file --env/-e vars of NORDVPN_COUNTRY/NORDVPN_CATEGORY/NORDVPN_PROTOCOL needs to be added

2) No resolution of download.nordcdn.com. The /etc/resolv.conf file does not seem to use the entry from --dns 8.8.8.8 ? I swapped out that entry with --dns-opt "nameserver 8.8.8.8"  which works for me for now
