### ISSUE TITLE
Error parsing reference.

### ISSUE THREAD

**Issue by dublinus** [haugene/docker-transmission-openvpn#99]
I'm trying to run this container like this:

```
id=$(docker run --privileged  -d \
    -v /some/path:/data \
    -e "OPENVPN_PROVIDER=PIA" \
    -e "OPENVPN_CONFIG=Netherlands" \
    -e "OPENVPN_USERNAME=myusername" \
    -e "OPENVPN_PASSWORD=mypassword" \
    -p 9091:9091 \
    haugene/transmission-openvpn)

docker run -d \
    --link $(id):transmission \
    -p 8080:8080 \
    haugene/transmission-openvpn-proxy
```

And I'm getting the following error:

```
docker: Error parsing reference: "gid=1000(dublinus)" is not a valid repository/tag.
See 'docker run --help'.
```

Not sure how that's related to what I'm doing. Did I do something wrong here?

**Comment by haugene** [comment]
Hmm. Not sure what's happening here, and I'm not at my computer to check it either. But is this part of a bash script? To reference the id variable it should be $id? 

Have you considered using the --cidfile option of docker run? Then the container id would be written to a file and you could use $(cat /path/cidfile) in your link command... 

Or docker compose of course.

**Comment by dublinus** [comment]
Yeah, that's definitely better, especially so I can make another script that quits just that container.

It's the weirdest thing. When I type that command (`docker run -d --link $(cat ~/.cidfile):transmission -p 8080 haugene/transmission-openvpn-proxy` after the cidfile modification), it works. But not from the script. Of course, this is an issue unrelated to this project, and and I'll figure it out.

Thanks for taking the time :)

**Comment by haugene** [comment]
Interesting... Good luck with that ;) 
Np!
