### ISSUE TITLE
[Docs] better arguments/config documentation

### ISSUE THREAD

**Issue by laundmo** [haugene/docker-transmission-openvpn#993]
**Is your feature request related to a problem? Please describe.**

Trying to figure out how the config works is difficult, due to bad documentation of possible values for config options etc.

**Describe the solution you'd like**

I woudl like the documentation to clearly state ALL enviroment variables and ALL their possible values. 

examples:
`NORDVPN_COUNTRY` isn't documented on the arguments page, only mentioned on the [update script page](https://haugene.github.io/docker-transmission-openvpn/nordvpn-script/).

the documentation for `OPENVPN_CONFIG` does not show any info about the possible values, or where to find them.

**Describe alternatives you've considered**

possible alternative: config generator which allows the selection of config options from a dropdown menu, and outputs a docker run or docker-compose

**Additional context**

**Comment by laundmo** [comment]
since this is a feature request that hasn't been implemented or denied i do not think it should be stale

**Comment by pkishino** [comment]
@laundmo please feel free to update the documentation, it is editable ;)
