### ISSUE TITLE
can't ask for 'Enter Auth Username:' ?

### ISSUE THREAD

**Issue by v-marinkov** [haugene/docker-transmission-openvpn#996]
**Describe the problem**
The container fails with the following message:
`neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Auth Username:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.`

I am running it on Raspberry Pi 3B+ with my own .ovpn files from an Openvpn server I have set up.

**Add your docker run command**
```
docker run --cap-add=NET_ADMIN -d \
              -v /your/storage/path/:/data \
              -v /home/pi/vpn-trans/default.ovpn:/etc/openvpn/custom/thin-vpn.ovpn \
              -v /home/pi/vpn-trans/auth.txt:/etc/openvpn/custom/auth.txt \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=CUSTOM \
              -e OPENVPN_CONFIG=thin-vpn \
              -e OPENVPN_USERNAME=user \
              -e OPENVPN_PASSWORD=pass \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.44.0/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn:dev-armhf
```
**Logs**
```
Using OpenVPN provider: CUSTOM


Starting OpenVPN using config thin-vpn.ovpn


Setting OPENVPN credentials...


adding route to local network 192.168.44.0/24 via 172.17.0.1 dev eth0


Thu Jan  2 14:37:32 2020 OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Oct 14 2018


Thu Jan  2 14:37:32 2020 library versions: OpenSSL 1.0.2s  28 May 2019, LZO 2.08


Thu Jan  2 14:37:32 2020 neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Auth Username:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.


Thu Jan  2 14:37:32 2020 Exiting due to fatal error
```

I feel I am missing something fundamental here. What could be going wrong?

**Comment by pkishino** [comment]
You need to modify the ovpn files from default, in quote certain the wiki describes how.. there is a script that can do it as well, but basically tell it to get the auth details from a file etc

**Comment by rowanruseler** [comment]
So you have this line:
```-v /home/pi/vpn-trans/auth.txt:/etc/openvpn/custom/auth.txt \```

That means that, within your .ovpn file you should point `auth-user-pass` towards that file, as so:
```
auth-user-pass /etc/openvpn/custom/auth.txt
```

**Comment by v-marinkov** [comment]
Thanks for the replies. I made the change but the result is exactly the same.
Here are the settings of the `default.ovpn` file:
```
client
remote SERVER.IP PORT
proto udp
dev tun
remote-cert-tls server
;comp-lzo
auth-user-pass /etc/openvpn/custom/auth.txt
persist-key
persist-tun
nobind
resolv-retry infinite
verb 3
mute 10
```

**Comment by v-marinkov** [comment]
Nevermind, the needed option was:
` askpass /etc/openvpn/custom/auth.txt`

All solved now. Thanks
