### ISSUE TITLE
Issues with AUTH on Surfshark

### ISSUE THREAD

**Issue by talannon** [haugene/docker-transmission-openvpn#997]
I have been using the container with no issues using PIA but recently switch to Surfshark. When I update my docker-compose file by changing the provider, username and password I get an error with the authentification. I checked multiple times my username/password and I tried to provide different servers (tcp or udp) but the auth always fail.

[transmission-vpn.log](https://github.com/haugene/docker-transmission-openvpn/files/4017238/transmission-vpn.log)

**Comment by haugene** [comment]
Please read my comment here and see if that helps you: https://github.com/haugene/docker-transmission-openvpn/issues/869#issuecomment-521571014

This is your provider refusing your credentials. The AUTH_FAILED message is coming from them. It is possible that your provider has different credentials for OpenVPN clients and their apps (mine does). Or it might be something else.

Anyways, read it, test the proposals there and get back to me.

**Comment by voandy** [comment]
Hey talannon,

I use SurfShark. To find your OpenVPN Credentials to to My Account > Devices > Manual Configuration.

**Comment by talannon** [comment]
Sorry for the delay. It was indeed an issue with the wrong credentials used. Sorry about that!
